### ISSUE TITLE
Comment paging needs to handle the gap between new and cached

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#1000]
Comments are loaded 20 at a time. When you scroll to the end of them, the next 20 are loaded. But since comments are cached, there's a chance you could miss some due to the gap between new comments are those cached. 

Ex: if you previously loaded 20 comments then use the app again after 40 more comments were posted, you'd get the most recent 20 of those comments but 20 of them would never show up.

**Comment by rachelmcr** [comment]
I tested this in 4.8-rc-3 with the following steps:
1. Selected a site in the app and opened the Comments section to load the existing comments
2. Posted 25 new comments on the site (in a web browser)
3. Reopened the Comments section in the app
Result: I saw all 25 new comments followed by the previous comments.

I'm closed this issue as resolved, but if I've missed something here please reopen.
