### ISSUE TITLE
Block Editor: Next item in list block uses formatting

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#10017]
My understanding of this could be wrong. So please close if the actual behavior is the expected behavior. 

After creating a list block and choosing formatting(Bold, italics, etc...) going to a new list element removes that formatting. 

### Expected behavior

Expected the formatting to be the same. 

### Actual behavior

Formatting is not the same.

![list formatting enter](https://user-images.githubusercontent.com/6520461/59216951-7404ed00-8b82-11e9-94c6-d54d436baa92.gif)

### Steps to reproduce the behavior

1. Create a new post with the Block editor
2. Add a list block
3. Choose some formatting and enter some text
4. Click enter and enter more text

##### Tested on [device], Android [version], WPAndroid [version]

Alcatel 3v, 8, alpha-172

**Comment by koke** [comment]
I tested this on the web and Gutenberg behaves the same way. I'm closing the issue since it's not mobile specific, but I agree that it's a sensible expectation.

@iamthomasbishop what do you think about this one? Should we propose that change to core gutenberg?

**Comment by iamthomasbishop** [comment]
I would expect the same, for the formatting to be maintained. I also tried a few other writing apps to see if that's common and it appears to be. Might be worth proposing it for core.

**Comment by JavonDavis** [comment]
> Might be worth proposing it for core.

I agree
