### ISSUE TITLE
Block Editor: List block loses formatting when text from item is removed

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#10018]
When creating a list block formatting is lost when removing text from an item that isn't the first item, formatting is lost. 

### Expected behavior
 
The formatting for the text should still be applied. 

### Actual behavior

On the first item, it works fine

![formatting presence](https://user-images.githubusercontent.com/6520461/59217252-2341c400-8b83-11e9-9eb9-788c6aaa8acc.gif)

On the others, the behavior is this, 

![formatting loss](https://user-images.githubusercontent.com/6520461/59217285-381e5780-8b83-11e9-8251-22a8393be92b.gif)

### Steps to reproduce the behavior

1. Create a post with the block editor
2. Add a list block 
3. Add more than items to the list
4. On an item that isn't the first apply formatting(block, italics, etc...)
5. remove the text and type additional text

##### Tested on [device], Android [version], WPAndroid [version]
Alcatel 3v, 8, alpha-172

**Comment by koke** [comment]
I tested this on the web and Gutenberg behaves the same way. I'm closing the issue since it's not mobile specific, but I agree that it's a sensible expectation.

@iamthomasbishop what do you think about this one? Should we propose that change to core gutenberg?

**Comment by koke** [comment]
🤦‍♂ I was meaning to close/comment on a different issue

**Comment by koke** [comment]
Added to the [backlog](https://github.com/wordpress-mobile/gutenberg-mobile/projects/1) but not sure about priority yet. I think the upcoming improvements to rich text might help 🤞

**Comment by cameronvoell** [comment]
re-checking this issue, looks like it is still occurring.

Today this issue is slightly worse, in that even with the first item in the list, if you delete it and then start typing again, the formatting is lost. I confirmed that in other blocks like paragraph, quote and heading, if you delete bold text, and then start typing again, the bold style is retained. 
(Samsung Galaxy S10+, Android 11, WPAndroid 17.1 )

**Comment by thehenrybyrd** [comment]
I was unable to reproduce this on Samsung Galaxy S21, Android 12, WPAndroid 19.9-rc-2.
Closing for now, please reopen if this is still an issue.
