### ISSUE TITLE
Block Editor: Heading block loses formatting

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#10016]
When typing text into a Heading block it loses its formatting if all the text is deleted.

### Expected behavior

Expected text to keep its formatting

### Actual behavior

![heading block](https://user-images.githubusercontent.com/6520461/59216699-c1348f00-8b81-11e9-9118-e57375e8238d.gif)

### Steps to reproduce the behavior

1. Create a new post with Block Editor enabled
2. Add a heading block
3. Type out text 
4. Delete all the text
5. Type text again

##### Tested on [device], Android [version], WPAndroid [version]

Alcatel 3v, 8, alpha-172

**Comment by koke** [comment]
[Added this](https://github.com/wordpress-mobile/gutenberg-mobile/projects/1#card-22676460) to the backlog

**Comment by cameronvoell** [comment]
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!
