### ISSUE TITLE
Login: trying to log in to a self-hosted site you already added results in a blank splash screen

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10011]
Steps to reproduce:

1. Open the app and add a self-hosted site.
1. Log out (if you were logged in to WordPress.com).
1. Go to Me > Log in to WordPress.com.
1. Tap "Log in".
1. Tap "Log in by entering your site address."
1. Enter the site address for a self-hosted site you already added.
1. Follow the prompts to log in.

Result: the login splash screen is blank.

<img src="https://user-images.githubusercontent.com/1119271/59126321-09ee0d00-8922-11e9-8b67-a3d6d865eb14.png" width="270" alt="Screenshot_20190607-123304">
<sup>Tested with WPAndroid alpha-172 (12.6 alpha) on Pixel 3 Android 9.</sup>

In comparison:

1. Open the app and add a self-hosted site.
1. Log out (if you were logged in to WordPress.com).
1. Go to the "Choose site" screen (Switch Site).
1. Tap the "+" at top right.
1. Enter the site address for a self-hosted site you already added.
1. Follow the prompts to log in.

Result: a message appears that says, "Couldn't select newly added self-hosted site.

<img src="https://user-images.githubusercontent.com/1119271/59126315-065a8600-8922-11e9-80c3-104a09c7d56a.png" width="270" alt="Screenshot_20190607-124034">
<sup>Tested with WPAndroid alpha-172 (12.6 alpha) on Pixel 3 Android 9.</sup>

**Comment by planarvoid** [comment]
hey @designsimply , I've tried to reproduce this issue and 

- Open the app and add a self-hosted site.
- Log out (if you were logged in to WordPress.com).
- Go to Me > Log in to WordPress.com.
- Tap "Log in".
- Tap "Log in by entering your site address."

the step to "Log in by entering your site address" is no longer there when trying to log in to WP.com, right? I think I can safely close it.
