### ISSUE TITLE
Account Settings Shows Unchanged Email Address as Empty

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#10012]
### Expected
Saving an unchanged email address shows the previous value in the ***Email Address*** field.

Alternatively, there would be validation on the dialog input field to enable the ***OK*** button only after the value entered is different than the value when the dialog was created.

### Observed
Saving an unchanged email address shows an empty value in the ***Email Address*** field.

### Reproduced
1. Go to ***Me*** tab.
2. Tap ***Account Settings*** option.
3. Notice email address shown in ***Email Address*** summary.
4. Tap ***Email Address*** option.
5. Tap ***OK*** button.
6. Notice email address hidden in ***Email Address*** summary.
7. Tap back arrow.
8. Tap ***Account Settings*** option.
9. Notice email address shown in ***Email Address*** summary.

##### Tested
Google Pixel 3 on Android 9.0 with WordPress alpha-172

**Comment by hafizrahman** [comment]
In looking at this and trying to replicate the issue, the issue still persists but I'm seeing a new behavior:

1. Go to Me tab.
2. Tap Account Settings option.
3. Notice email address shown in Email Address summary.
4. Tap Email Address option.
5. Tap OK button without changing any email.
6. For a second or so, the `Click the verification link in the email sent to %1$s to confirm your new address` snackbar appears, then disappears quickly
7. Notice email address hidden in Email Address summary.
8. Tap back arrow.
9. Tap Account Settings option.
10. Email address is now still hidden,
11. Tap back arrow twice to the "My Site" screen,
12. Go back to Me > Account Settings
13. The hidden email is now shown again.

**Comment by hafizrahman** [comment]
I am unable to replicate this on a local build, though. After step 4, it gives me the error message:

`Your client is not permitted to set the user's email`

and then none of the other steps happen.

This is on version 15.0-rc-1.

**Comment by hypest** [comment]
> Your client is not permitted to set the user's email

Ah, looks like this is one of the privileged fields that only the official app can change. Sorry about that @hafizrahman :(

**Comment by jkmassel** [comment]
This appears to have been resolved.
