### ISSUE TITLE
Localization: String instability after image insertion

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#10038]
### Expected behavior
I've set my app to a particular language (such as Japanese), and all strings should remain in that language as I navigate through the app.

### Actual behavior
Adding an image to a new post using either editor disrupts the strings and some of them change back into English. For instance, after adding an image, going back to the Post List shows filters in English, and switching between "Me" and "My Sites" results in switching both to English, even though the app settings still say the language is Japanese.

### Steps to reproduce the behavior
1. Set app language to Japanese. If Japanese strings don’t appear immediately, restart the app.
2. Go to My Site > Blog Posts and start a new post. 
3. Add an image block and add an image to it (if testing in classic editor, just add an image)
4. Now some strings are in English that weren’t before. Places to check: “…” menu in the post editor, Posts List, My Site, Me tab.

Leaving the app and opening it again sets some strings back, but navigating around again reveals further instability, particularly after opening a post. 

I've tried this in Japanese and in Arabic.

![StringInstability](https://user-images.githubusercontent.com/15107387/59422279-6ba1f180-8dd0-11e9-98c3-3b72655b18b1.png)

##### Tested on Nokia 2, Android 7.1.1, WPAndroid Alpha-172
User report in #2101850-zen, on SHARP SH-M08, WPAndroid 12.5.

**Comment by thehenrybyrd** [comment]
Updated to Alpha-173 and tried again, same results.

**Comment by Josimarcsilva** [comment]
I have the same problem too.
It all started when I enabled the Block Editor in the App.
The App now alternates between my language (Portuguese Brazil) and the English language.

**Comment by thehenrybyrd** [comment]
I'm no longer able to reproduce this (in WP Android19.6), closing.
