### ISSUE TITLE
Editor: wrong message in progress dialog while discarding local changes

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#10064]
For simplicity we will refer only to Posts in the following description, but the issue applies both to Posts and Pages and it's not dependent on the editor (Aztec or GB) used.
### Expected behavior
 While editing an existing Post (Published, Draft, Scheduled or Trashed), we get the possibility to discard the local changes using the “Discard Local Changes” menu item in the Editor overflow menu. Selecting to discard the local changes we should get a Progress Dialog with the message “Discarding local changes”.
### Actual behavior
During discarding operation, we get the message “Loading revision”.
### Steps to reproduce the behavior
1. From the Posts list select a category (Published, Draft, Scheduled or Trashed),
2. Choose to Edit an existing post from the selected category
3. Make some editing
4. Select the “Discard Local Changes” menu item from the overflow menu
5. Observe the “Loading revision” message in the Progress Dialog
### Some analysis done
[Here](https://github.com/wordpress-mobile/WordPress-Android/blob/a3c7ee00975c808bb719351af0907b1c31cf7772/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1412) the flag `mIsDiscardingChanges = true;` is set after the call to  `showDialogProgress(true);`. Should be enough to swap their order to make the trick.

**Comment by develric** [comment]
PR #10085 should fix this issue as a side effect.

**Comment by maxme** [comment]
FWIW, we're going to drop the "Discard Local Changes" feature soon: https://github.com/wordpress-mobile/WordPress-Android/issues/9561

**Comment by oguzkocer** [comment]
It looks like "Discard Local Changes" were indeed dropped. Closing this issue.
