### ISSUE TITLE
Domain Credit: Domain can't be registered and error appears for selected country in contact information

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#10062]
### Expected behavior

When I try to use my domain credit to register a domain on a business site, I expect to be able to enter all my contact information and proceed to registering the domain.

### Actual behavior

My selected country isn't accepted, and instead I get a "This field is required" toast message with an error icon indicating a problem with the country. (I set my app language to US English and used United States as the country to confirm it wasn't only a problem with non-EN/non-US settings.)

The app logs include this error:

```
79 - [Jun-18 15:46 API] Volley error on https://public-api.wordpress.com/rest/v1.1/me/transactions/?locale=en_US - exception: null
80 - [Jun-18 15:46 API] StackTrace: com.android.volley.ServerError
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

81 - [Jun-18 15:46 DOMAIN_REGISTRATION] An error occurred while redeeming a shopping cart : COUNTRY_CODE This field is required.
```

### Steps to reproduce the behavior

1. Select a site with a business plan and *.wordpress.com address.
2. Go to My Sites > Plugins.
3. Select a plugin and install it.
4. When prompted, choose to register a domain.
5. Search for and select a domain.
6. Enter your contact information and select Register Domain.

Result: The toast message "This field is required." appears and you can't proceed.

![Screenshot_20190618-163412](https://user-images.githubusercontent.com/8658164/59699335-53274200-91e9-11e9-9aa4-80c2f19464b2.png)

**Comment by khaykov** [comment]
Fixed in #10063 and should be available in next beta.
