### ISSUE TITLE
Block Editor: Formatting indicator toolbar not showing correct information

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#10084]
### Expected behavior

Leaving some text that has already been formatted and coming back to that text should preserve existing formatting.

### Actual behavior

The formatting toolbar doesn't quite match up once you leave the text you're currently editing. See below for examples

![vid1](https://user-images.githubusercontent.com/6520461/59951620-81a25880-9447-11e9-8179-58471decc548.gif)

![vid2](https://user-images.githubusercontent.com/6520461/59951626-849d4900-9447-11e9-8cd0-e15281b020f4.gif)

![vid3](https://user-images.githubusercontent.com/6520461/59951631-8830d000-9447-11e9-9765-cf305b851a7e.gif)

![vid4](https://user-images.githubusercontent.com/6520461/59951634-8b2bc080-9447-11e9-8753-164db7b56f0b.gif)

### Steps to reproduce the behavior

Format some text then leave the block and come back to that text.

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 3a, Android 9, alpha-175

**Comment by koke** [comment]
It seems related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/729 although this one seems to be covering more scenarios

**Comment by JavonDavis** [comment]
@koke You might be right, I've left comments both on that issue and on https://github.com/wordpress-mobile/gutenberg-mobile/issues/757#issuecomment-505083797

**Comment by JavonDavis** [comment]
Closing here, this is already being tracked wordpress-mobile/gutenberg-mobile#729 and wordpress-mobile/gutenberg-mobile#757

**Comment by etoledom** [comment]
Hey @JavonDavis - I left a comment here https://github.com/wordpress-mobile/gutenberg-mobile/issues/729#issuecomment-505298850

I think these are different issues, and https://github.com/wordpress-mobile/gutenberg-mobile/issues/729 might not even be a bug :)
So I think it's better to keep this one open and close https://github.com/wordpress-mobile/gutenberg-mobile/issues/729

Maybe we could move this one to the gutenberg-mobile repo? 🤔

**Comment by etoledom** [comment]
UPDATE:
I did a test on the gutenberg web, and it behaves on a very similar way.
The only difference is that the typing attributes matches the buttons status, so when you move to the end and there are no attribute buttons selected, it won't add the attributes to the new text.

That makes me thing that is Aztec Native (both iOS and Android) who add the last attributes to the typing attributes, without gutenberg telling it to do so.
