### ISSUE TITLE
[Site Creation] Animate out header on Verticals and Domains screen on input focus

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10086]
### Expected behavior
The header on Verticals and Domains screens is animated out when the edittext receives focus.

### Actual behavior
The header on Verticals and Domains screens is animated out when the user types a first letter into the EditText.

### Steps to reproduce the behavior
1. My Site
2. Switch Site
3. Click on "+" icon in the toolbar
4. Select "Create WordPress.com site"
5. Select a site type
6. Notice the header is animated out when you type a letter
7. Choose a vertical
8. Skip the next step
9. Notice the header on the domain search screen is animated out when you type a letter

![1](https://user-images.githubusercontent.com/2261188/59996685-4d9f8100-965b-11e9-8ccb-64de7233cc21.gif)

Note: The downside of this approach is the user won't be able to clear the focus and therefore they won't be able to "re-show" the header. They'd need to leave the screen and come back. cc @SylvesterWilmott Wdyt?

**Comment by SylvesterWilmott** [comment]
There’s a couple of issues with doing this that might not be immediately obvious.

- Animating the header out on focus means that it becomes impossible to return the screen to a state where the title/subtitle is shown.
- This animation type is a reusable pattern for single field input/search results and can be used in other areas of the app. By applying the animation on focus, we forgo the possibility of using an auto-focus wherever this might be useful.
