### ISSUE TITLE
[Site Creation] Create Site feature is difficult to find

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10088]
The "create site" feature is currently placed under "My Site->Switch Site->Plus Sign icon in the toolbar". We are getting feedback that the feature is hard to find. I'd like us to consider moving it to a more prominent place in the app. Wdyt?

cc @SylvesterWilmott

**Comment by SylvesterWilmott** [comment]
This is something that will be addressed within the IA project.
