### ISSUE TITLE
[Site Creation] Show default domain suggestions when EditText gets cleared

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10087]
### Expected behavior
When the user clears the query on the domains suggestion screen the list of default suggestions (suggestions derived from "site title") is shown.

### Actual behavior
When the user enters the domains suggestion screen a list of default suggestions (suggestions derived from "site title") is shown. However, when the user types a query and they clear it, the default suggestions are not shown. The user needs to go to the previous screen and back to domains suggestions screen to see the list of default suggestions.

### Steps to reproduce the behavior
1. My Site
2. Switch Site
3. Click on plus sign icon in the top right corner
4. Select "Create WordPress.com site"
5. Choose a site type
6. Skip
7. Enter site title
8. Click on Next
9. Notice the list of default suggestions is shown
10. Type a query and clear it
11. Notice the list of default suggestions is not shown

**Comment by cameronvoell** [comment]
Taking a look at this.
