### ISSUE TITLE
Implement Restore Revision dialog Android

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-Android#10108]
For discovery history - #10008, #9812
If the post has local changes and a remote autosave, we are going to show a dialog to the user. 
This issue is for implementing the design for this dialog.
<img width="422" alt="screenshot-2019-05-03-at-09 25 19" src="https://user-images.githubusercontent.com/40213/57301854-3a9c1600-70da-11e9-8b51-caace0fe6d33.png">

## Matching iOS Issue:

https://github.com/wordpress-mobile/WordPress-iOS/issues/12141

**Comment by yaelirub** [comment]
@osullivanchris, can you please share the proposed copy for this?

**Comment by malinajirka** [comment]
Fixed in #10426
