### ISSUE TITLE
After plugin installation during AT "INSTALL" button is not switched to "INSTALLED"

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#10100]
### Expected behavior
After you successfully perform AT by installing the plugin, "INSTALL" button at the plugin details page should switch to "INSTALLED" and become disabled.

### Actual behavior
The button does not change, and tapping on it again results in an error message since the plugin is already installed.

Here is the super long gif of the problem:
![error](https://user-images.githubusercontent.com/728822/60047130-915fae00-968e-11e9-9c98-238b5f0ac08b.gif)

### Steps to reproduce the behavior
On a Simple site with Bussines plan, install a plugin and start AT. After AT is finished observe the abovementioned behavior.

**Comment by irfano** [comment]
This is no longer reproducible.

**Comment by irfano** [comment]
This is no longer reproducible.
