### ISSUE TITLE
Stats Widget: "Today" and "Views all week" widget revert to "All-time" if you tap "Retry" after logging out and back in

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10146]
Steps to reproduce:

1. Add the "Today" and "Views all week" widget (long-press on the home screen).
1. Log out.
1. Resize the widgets to trigger an update.
1. Observe the notice that says "Couldn't load data".
1. Log back in and resize the "Views this week" widget again.
1. Tap "Retry".

<strong>Result:</strong> the "All-time" widget is shown instead of the "Today" and "Views all week" widgets if you tap "Retry" after logging out of the app and back in again.

While logged out at first:  | Log out and resize: | After tapping "Retry":
--- | --- | ---
<img src="https://user-images.githubusercontent.com/1119271/60625044-f78db480-9da3-11e9-8033-87b28bda26ee.png" width="200" alt="Screenshot_20190703-143725"> | <img src="https://user-images.githubusercontent.com/1119271/60625762-fb223b00-9da5-11e9-9ddf-9ce02e7e8b8d.png" width="200" alt="Screenshot_20190703-143928"> | <img src="https://user-images.githubusercontent.com/1119271/60625551-63245180-9da5-11e9-881d-4ebb5e2b1166.png" width="200" alt="Screenshot_20190703-144052">

<sup>Tested with WPAndroid alpha-177 (12.8 alpha) on Pixel 3 Android 9.</sup>

**Comment by planarvoid** [comment]
This was already fixed
