### ISSUE TITLE
Show an error for Remote Previews on Jetpack sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#10161]
Due to an issue in the API with Jetpack sites, generated previews are not up to date.

Until the API is fixed, we must show an error for previews on published post (remote auto-save) on Jetpack sites.

More information on the iOS ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/11684

**Comment by maxme** [comment]
Note: we should make the preview unavailable only on published posts with local changes on Jetpack connected sites. These posts require to remotely auto-save the post via the REST API on a Jetpack site, and that's what is currently broken.

**Comment by shiki** [comment]
The Calypso issue: https://github.com/Automattic/wp-calypso/issues/20265

**Comment by yaelirub** [comment]
Hey @maxme , can we move forward with this ticket (will do the same for iOS) now that the patch is out there?

**Comment by maxme** [comment]
The patch doesn't fix the issue for Jetpack sites (from the Calypso's ticket comment 3 weeks ago: "More patches will be needed to deploy this fix for Atomic and Jetpack sites, too. I'll post updates as we proceed." - and I don't see any update since).

I also tried a few days ago before asking for review on https://github.com/wordpress-mobile/WordPress-Android/pull/10212 and the issue was still there.
