### ISSUE TITLE
Comments: Default Text when Editing Wrong

### ISSUE THREAD

**Issue by Aurorum** [wordpress-mobile/WordPress-Android#10166]
### Expected behavior

When editing a comment, the default initial text should always be identical to the original comment. 

### Actual behavior

When editing a comment, the default initial text read "You replied to this comment".

### Steps to reproduce the behavior

1. Select a comment you've already replied to 
2. Click edit 
(Note: I repeated this several times to get this video, it happened on almost all attempts but not one) 

![ezgif-3-21039a5d517b](https://user-images.githubusercontent.com/43215253/60767079-38d6da80-a0aa-11e9-95c4-a47bc45cb0e5.gif)

**Comment by khaykov** [comment]
I believe this was fixed when we introduce slide-up comment editor. Closing for now.

**Comment by Aurorum** [comment]
Yes, I haven't seen this issue for a while so I think it's been resolved too.
