### ISSUE TITLE
siteCreationState data payloud out of synch with UI when moving backwards then skipping forwards through site creation wizard

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/WordPress-Android#10189]
### Expected behavior
During new site creation, moving backwards in the wizard should not create a deviation between the "siteCreationState" used to create your site, and what the UI input forms show to the user. 

### Actual behavior
If you move backwards in the site creation wizard, you will clear the user input forms for vertical, site title, and tagline. If you skip through them on your next pass through, however, leaving them in this empty form, and then search for a domain and create a site, the vertical, site title, and tagline previously entered will come back because they stayed preserved in the siteCreationState.  

### Feeback welcome!, see my suggestion below:
Not objectively obvious whether we want these fields to clear when the user moves backwards, but if we do, then we should clear the "siteCreationState" so users next pass through doesn't save unexpected state, not visible to the user if they skip. In my opinion, we should not clear the UI when the user moves backwards through the wizard, we should just display the previously saved "siteCreationState" which we are already retaining anyway.

### Steps to reproduce the behavior

1. My Site
2. Switch Site
3. Click on plus sign icon in the top right corner
4. Select "Create WordPress.com site"
5. Choose a site type
6. Enter some custom vertical type, click next
7. Enter site title and tagline, click next
8. On the choose a domain screen, hit the back arrow
9. On the title/tagline screen, hit the back arrow
10. On the vertical screen, hit the back arrow
11. Choose a site type
12. Press skip for site vertical
13. Press skip for title/tagline
14. Search a domain, select, and press create (before you search you will see the previously entered title even though you skipped title input this time)
15. Verify that the previously entered vertical, title, and tagline have returned even though they were skipped on second pass through the wizard. 

*Note in test build I wasn't able to create a site (OAuth settings?), but I was able to verify the issue with Play Store build, and with test build I was able to verify unexpected "siteCreationState" using the debugger.

**Comment by cameronvoell** [comment]
I'll submit a PR for fixing using the behavior that I suggested in the Issue description, unless someone says they would prefer that moving backwards in the wizard clears the previously entered fields.

**Comment by malinajirka** [comment]
Great find! I can confirm the behavior.

>In my opinion, we should not clear the UI when the user moves backwards through the wizard, we should just display the previously saved "siteCreationState" which we are already retaining anyway.

I think we don't actually retain the previous UI state in "siteCreationState", but just the outcome of the screen which sometimes happens to be the UI state. Eg. if you take a look at the second screen of the flow (step 1 of 3) - the user enters a query/vertical but we retain only an ID of the vertical, not the query the user has entered. We plan to keep improving the flow and I think we'll have more such cases. 
So even though I agree with you it'd make sense so keep the UI state, I think it's not worth the added complexity. I'd personally go with the "clear siteCreationState" solution. Wdyt?

**Comment by cameronvoell** [comment]
@malinajirka Yea I noticed what you mean about only saving the verticalId and not the user search. This is a pretty minor issue, so I think clearing the siteCreationState is the better option. I'll submit a PR for that later today.
