### ISSUE TITLE
Content loss after adding a caption to an image in a draft

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10188]
Steps to reproduce gathered from this help request in the WordPress.com support forum:

* https://en.forums.wordpress.com/topic/i-was-typing-in-the-editor-and-lost-everything/

1. Create a new draft using the Aztec editor.
1. Add a title and some content.
1. Add categories and tags.
1. Insert a photo at the top.
1. Set a featured image.
1. Add an image at the end of the post.
1. Tap the image and add a caption.
1. Hit the back button to go back to see how it looked.
1. Check to see if all previous content is lost at this point.

**Result as described by the person reporting the problem:** the picture disappeared and the caption appeared as the only text on the whole page.

**Note:** I tried two tests but I was unable to replicate the problem described where all content from the post disappears after adding a caption to an image at the bottom of a draft post.

**Video 1:** [1m46s](https://cloudup.com/cxDH-xjw7qJ)
<sup>Tested with WPAndroid alpha-178 (12.8 alpha) on Pixel 3 Android 9.</sup>

**Video 2:** [3m49s](https://cloudup.com/csq37KZKEGJ)
<sup>Tested with WPAndroid 12.6 on Pixel 3 Android 9.</sup>

<sub>(internal references: p4a5px-2pB-p2, 2151902-zen)</sub>

**Comment by malinajirka** [comment]
I've tried to reproduce this issue without success :(. My guess is that the app ends up in an unexpected state which results in this behavior. However, it's very difficult to fix or even debug when we are not able to reproduce it.

I'd consider running remote-auto-save periodically to prevent the content loss.

**Comment by malinajirka** [comment]
I've created an enhancement ticket for periodic remote-auto-save: #10398 

@maxme Also mentioned one of the causes of the content loss got fixed in  https://github.com/wordpress-mobile/WordPress-Android/pull/10368

**Comment by designsimply** [comment]
I sent the person who inspired this issue an update in the forums 😊 at https://en.forums.wordpress.com/topic/i-was-typing-in-the-editor-and-lost-everything/#post-3354486.

**Comment by planarvoid** [comment]
@designsimply do you think we can close this ticket?

**Comment by designsimply** [comment]
🤔 yes, I think we can close this one in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/10398. Thanks everyone!
