### ISSUE TITLE
Improve error message when post/page upload fails with an unknown cause

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10200]
### Expected behavior
When a post upload times out a valid or at least a user friendly message is shown.

### Actual behavior
When a post upload times out "GENERIC_ERROR" (untranslated) label is shown.

### Steps to reproduce the behavior
1. Create a post
2. Set emulator's network to Edge or lower and signal strength to poor. (or turn on airplane mode during the ongoing upload)
3. Click on "Publish"
4. Notice the upload fails and "GENERIC_ERROR" label is shown

**Comment by osullivanchris** [comment]
@malinajirka could you post a screenshot of the generic error? I don't have that emulator setup, and my network is too good to encounter the issue lol

**Comment by malinajirka** [comment]
![Screenshot_1562930296](https://user-images.githubusercontent.com/2261188/61124585-88047d00-a4a7-11e9-8114-506b29fc9861.png)

**Comment by osullivanchris** [comment]
Oh wow, that's actually what it says 🙈

So as we improve so many of the other use cases, hopefully this is not shown too often?

Is it just shown when there's an error related to publishing, or how broadly is it used?

**Comment by malinajirka** [comment]
>hopefully this is not shown too often?

It's hard to say - I think the most common use case is when the upload request times out (the internet connection is too slow). I could simply replace it with `Couldn\'t perform operation` error message which we use in some other parts of the app and log the actual error into the log so we can debug the issue when the user reaches the support. Wdyt?

>Is it just shown when there's an error related to publishing

yes, only when the upload of the post fails without a specific reason (specific reason is for example: insufficient permissions, remote post doesn't exist, site doesn't exist etc).

**Comment by osullivanchris** [comment]
> I could simply replace it with Couldn't perform operation error message which we use in some other parts of the app and log the actual error into the log so we can debug the issue when the user reaches the support. Wdyt?

"Couldn't perform operation" sounds better tan "GENERIC_ERROR" and I assume we have translations for it already if its used elsewhere, so could you do that as a patch for now at least?

If we can show an error log. Does that mean we can differentiate different types of error? which makes it not a generic error? If we are showing an error log, can we use some kind of error number rather than another robotic string. Like if it say "Couldn't perform operation, error 123". Then a user might consider telling us about it. Or we could track it. But it would be a weird experience if it said "Couldn't perform operation, specific_error_reason', I think it puts pressure on the user as if they should understand it.

**Comment by malinajirka** [comment]
>If we can show an error log. Does that mean we can differentiate different types of error? which makes it not a generic error? If we are showing an error log, can we use some kind of error number rather than another robotic string. Like if it say "Couldn't perform operation, error 123". 

I really like the idea, but it's unfortunately out of scope. AFAIK we don't have any such numbers at the moment and we'd probably want to introduce them for both local and remote errors -> it's not trivial. If the user contacts the support, the HEs can ask them to send their logs -> we should be able to find out what is going on from there.

>"Couldn't perform operation" sounds better tan "GENERIC_ERROR" and I assume we have translations for it already if its used elsewhere, so could you do that as a patch for now at least?

That's correct -> 👍
