### ISSUE TITLE
Add timeout for offline actions

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-Android#10214]
Came up on: https://github.com/wordpress-mobile/WordPress-Android/issues/9555#issuecomment-510844042

The decision on how to do this should apply for both platforms. 

## Matching iOS Issue:

https://github.com/wordpress-mobile/WordPress-iOS/issues/12136

**Comment by malinajirka** [comment]
We've added 48hours timeout for auto-upload as requested by Diego - https://github.com/wordpress-mobile/WordPress-Android/blob/ae4222197ce71d82504e4cd53a2e45b9ce731ea6/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt#L32.
