### ISSUE TITLE
Keyboard doesn't automatically open in expanded comment view

### ISSUE THREAD

**Issue by prtksxna** [wordpress-mobile/WordPress-Android#10235]
### Expected behavior
When I click the expand button the keyboard should open.

### Actual behavior
The comment view expands, but I still have to tap to open the keyboard.

### Steps to reproduce the behavior
My Site > Comments > Comment Detail screen, tap the expand icon on the bottom left (as mentioned in https://make.wordpress.org/mobile/2019/07/16/call-for-testing-wordpress-for-android-12-9/)

##### Tested on Redmi 4, Android 7.1.2, Wordpress 12.9-rc-1

Comment detail page | After clicking expand button
------------ | -------------
![photo_2019-07-17 12 12 12](https://user-images.githubusercontent.com/9491/61352960-3f283c00-a88c-11e9-9791-8edc6fea82dc.jpeg) | ![photo_2019-07-17 12 12 08](https://user-images.githubusercontent.com/9491/61352961-3f283c00-a88c-11e9-9d67-52e23b2539e2.jpeg)

**Comment by designsimply** [comment]
Thank you for testing! ❤️

**Comment by prtksxna** [comment]
Thanks @khaykov and @planarvoid!  😊

Would this be available to test on the Android beta program already?

**Comment by designsimply** [comment]
It should be available in version 13.2 of the release. A beta testing request should be posted to https://make.wordpress.org/mobile/ when 13.2 beta is ready for testing if you want to try it out before the full release.
