### ISSUE TITLE
Domain Registration: cannot select Country or State in the "Domain contact information" form

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10241]
Steps to reproduce:

1. Select a site with a Personal or Premium plan with an unused domain credit.
1. Tap "Register Domain".
1. Search for and select a domain.
1. Select the "Register privately with Privacy Protection" option.
1. In the "Domain contact information form", try to select a "Country".
1. In the "Domain contact information form", try to select a "State".

<strong>Result:</strong> none of the dropdown fields in the "Domain contact information form" are letting me set a value and I am blocked from completing the form using the "Register Domain" button. (<a href="https://cloudup.com/cBR7fwfM9V8">2m32s</a>)

**Note:** sometimes these fields are pre-filled, you may need to do a brand new sign up and use an account that has never been used to register a domain before in order to get a clean slate for testing this form.

<img src="https://user-images.githubusercontent.com/1119271/61416486-15354080-a8b1-11e9-9f1e-291459c55630.png" width="270" alt="register-privately-with-privacy-protection"> <img src="https://user-images.githubusercontent.com/1119271/61416343-993af880-a8b0-11e9-8941-a06cd3bf3a1f.png" width="270" alt="domain-contact-information-form-select-country">
<sup>Tested with WPAndroid alpha-180 (12.9 alpha) on Pixel 3 Android 9.</sup>

**Comment by elibud** [comment]
It this one ok to close @khaykov?

**Comment by khaykov** [comment]
@elibud yes! Closing, since it was fixed some time ago.
