### ISSUE TITLE
Domain Registration: cannot see off-screen form errors when there are missing required fields in the "Domain contact information form"

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10242]
Steps to reproduce:

1. Select a site with a Personal or Premium plan with an unused domain credit.
1. Tap "Register Domain".
1. Search for and select a domain.
1. Select the "Register privately with Privacy Protection" option.
1. In the "Domain contact information form", skip the Phone field.
1. Fill out the rest of the form and tap the "Register Domain" button.

<strong>Result:</strong> if there are any problems in the form and I tap the "Register Domain" button at the bottom of the form, I am not scrolled up to see that there were errors and no feedback is given about the form errors so it's hard to tell what's wrong. ([27s](https://cloudup.com/cjBhyP7HCyC))

<img src="https://user-images.githubusercontent.com/1119271/61416940-b4a70300-a8b2-11e9-96b5-6ad6c9df5046.png" width="270" alt="register-domain-form-with-off-screen-errors">
<sup>Tested with WPAndroid alpha-180 (12.9 alpha) on Pixel 3 Android 9.</sup>

**Comment by ravishanker** [comment]
This seems to be working fine.  Please open it again if ever found to be not working again.
