### ISSUE TITLE
Previews: video blocks and everything below them are missing from editor previews

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10257]
### Expected behavior

I expect to be able to see a preview of a video added to a post, regardless of what editor I am using. If I cannot see a preview of the video, then I expect to at least be able to see a video shortcode or placeholder as well as the content below it in a preview.

### Actual behavior

I cannot see video blocks or any content below video blocks when previewing posts made with the block editor. I can see a `[wpvideo]` shortcode instead of a video and I can see the content below the videos in previews of posts made with the Aztec editor.

### Steps to reproduce the behavior

1. Go to Me > App Settings and toggle `Use Block Editor` on.
1. Create a new post.
1. Add some text.
1. Add a video block using any option.
1. Add some more text below the video block.
1. Go to More > Preview and check to see if the video is visible in the preview.

**Result:** the video block and all content below it is missing from previews of posts with videos made using the block editor. ([1m25s](https://cloudup.com/c_EjGaz4ZF3))

<img src="https://user-images.githubusercontent.com/1119271/61568785-daaedd80-aa41-11e9-8ae3-9f3edd3cefac.png" width="270" alt="video-post-in-block-editor-wpandroid-12 9-beta"> <img src="https://user-images.githubusercontent.com/1119271/61568784-da164700-aa41-11e9-97ed-f1e22064d3d5.png" width="270" alt="video-post-preview-in-block-editor-wpandroid-12 9-beta">
<sup>Tested with WPAndroid alpha-181 (12.9 alpha) on Pixel 3 Android 9 with the block editor on a WordPress.com Personal Plan.</sup>

1. Go to Me > App Settings and toggle `Use Block Editor` off.
1. Create a new post.
1. Add some text.
1. Add a video.
1. Add some more text below the video.
1. Go to More > Preview and check to see if the video is visible in the preview.

**Result:** the video shows up as a shortcode in previews of posts with videos made using the Aztec editor and I can see the content below the video. ([1m2s](https://cloudup.com/ckArxVnqkAD))

<img src="https://user-images.githubusercontent.com/1119271/61568536-ddf59980-aa40-11e9-9e4a-3209e3d9a6cd.png" width="270" alt="video-post-in-aztec-wpandroid-12 9-beta"> <img src="https://user-images.githubusercontent.com/1119271/61568535-dd5d0300-aa40-11e9-9651-a3f1b9748b80.png" width="270" alt="video-post-preview-in-aztec-wpandroid-12 9-beta">
<sup>Tested with WPAndroid alpha-181 (12.9 alpha) on Pixel 3 Android 9 with the Aztec editor on a WordPress.com Personal Plan.</sup>

##### Tested on WPAndroid alpha-181 (12.9 alpha) on Pixel 3 Android 9.

<sup>h/t @JavonDavis for help with 12.9 beta testing (internal reference: p5T066-Wo-p2#comment-3235)</sup>

**Comment by mchowning** [comment]
I just tested this, and I was not able to recreate the issue on WPAndroid alpha-285 (blocks both before and after a video block were showing fine for me in the preview), so I'll go ahead and close this. Feel free to re-open if you still see the issue @designsimply .
