### ISSUE TITLE
Publish confirmation dialog shown when submitting for review

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10298]
### Expected behavior
When the user clicks on "Submit" button on an item in the Post list the publish confirmation dialog is not shown.

@osullivanchris Wdyt? Should we show "submit" confirmation dialog or simply submit the post for review? (When the user clicks on "Submit" button in the editor dialog is not shown.)

### Actual behavior
When the user clicks on "Submit" button on an item in the Post list the publish confirmation dialog is shown ("Ready to publish", "This post will be published immediately", "Publish Now"). When the user clicks on "Publish Now" the post is submitted for review.

### Steps to reproduce the behavior
1. Switch to a site in contributor role
2. Create a draft
3. Open Drafts tab on post list
4. Click on "Submit" button
5. Notice the dialog

![submit-for-review](https://user-images.githubusercontent.com/2261188/62106087-92df5000-b2a4-11e9-9d15-c2119285d191.gif)

**Comment by osullivanchris** [comment]
@malinajirka thanks for the ping. What do I see if I'm the other role. Like if you were a contributor and I was the owner, and you sent me a post for review, what would I see? Is there a way to dogfood that, or otherwise could you send a video of that?

**Comment by malinajirka** [comment]
@osullivanchris You'd see "Publish" button and publish confirmation dialog. 
https://user-images.githubusercontent.com/2261188/61872415-85f8e000-aee3-11e9-9ead-cf4662059bc8.png

**Comment by osullivanchris** [comment]
@malinajirka ah got it. 

So the owner (whatever we call that role) sees the 'publish' button and gets the confirmation dialog. Therefore someone has to see the dialog before it goes live.

Therefore I think we don't need a confirmation dialog of any kind for 'submit for review'. Tje pm;y reason to show one would be a kind of onboarding thing to explain what submit for review is.  But that's a separate topic. Its a non committing action so I don't think there's a risk which requires a dialog like the risk of accidentally publishing something. Unless someone has a really scary editor :D

**Comment by malinajirka** [comment]
;) ok, thanks.

Basically the reason why I was considering a dialog was that a contributor might not want to accidentally submit a post for review to their boss for example. But it seems like and edge case scenario anyway + they can still go to post settings and change it back to draft.

**Comment by osullivanchris** [comment]
Yeah I don't think we should add that unless we learn that people feel they need it. Plus it might add some confusion, seeing a really prominent confirmation dialog might make you feel like you're actually publishing. If you disagree I don't have a very strong opinion on this though

**Comment by malinajirka** [comment]
I absolutely agree with you;)! Thanks
