### ISSUE TITLE
Don't allow post to be edited if it is uploading

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1030]
If a post is being uploaded, I can still tap on it and edit it. If I make changes to that post while it's still being uploaded and then upload it again, I end up with two copies of the post in the post list (one has the edits, the other doesn't).

![dup](https://f.cloud.github.com/assets/3903757/2321190/c2f4c7ea-a39e-11e3-9234-781b12f0067c.png)

Aside: I can also delete a post while it's being uploaded.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by aforcier** [comment]
This issue was auto closed during editor issue migration - it persists with the new editor, but is more of a WPAndroid post list/db issue.
