### ISSUE TITLE
WPNumberPicker is not displayed correctly in number of dialogs

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#10331]
Starting with API 28 certain Restrictions on non-SDK interfaces were introduced, as explained [here](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces).

We are using reflection to do access fields from `NumberPicker` and do some styling magic on `WPNumberPicker` and since API 28 this widget is broken with following errors:

```
No field mSelectorElementHeight in class Landroid/widget/NumberPicker; (declaration of 'android.widget.NumberPicker' appears in /system/framework/framework.jar!classes2.dex)
No field mCurrentScrollOffset in class Landroid/widget/NumberPicker; (declaration of 'android.widget.NumberPicker' appears in /system/framework/framework.jar!classes2.dex)
No field mInitialScrollOffset in class Landroid/widget/NumberPicker; (declaration of 'android.widget.NumberPicker' appears in /system/framework/framework.jar!classes2.dex)
No field mCurrentScrollOffset in class Landroid/widget/NumberPicker; (declaration of 'android.widget.NumberPicker' appears in /system/framework/framework.jar!classes2.dex)
```

### Steps to reproduce the behavior

1. Launch app on a device with API 28 (android 9).
2. Navigate to Site Settings.
3. Open Posts Per Page preference.
4. Notice that number picker is not displayed correctly.

![Screenshot_1565042046](https://user-images.githubusercontent.com/728822/62507812-62267b80-b7ba-11e9-83db-e91e6eeb33b0.png)

##### Tested on [device], Android [version], WPAndroid [version]
Emulator of Pixel 2 with API 28 and 27

**Comment by marecar3** [comment]
Thanks, @khaykov. I can confirm the same behavior on a real device.

**Pixel 3, Android 9, API 28**

Maybe it will help. 
Peeking at API 28 codebase, NumberPicke class, I can find those fields: e.g. https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-28/blob/809dd8b7822332cdbc68939d777eb70a6951908a/android/widget/NumberPicker.java#L329

But when I print all class fields at runtime, using the reflection, I can't find them.

Full list of fields from NumberPicker class: (**Pixel 3, Android 9, API 28**)

<img width="223" alt="Screen Shot 2019-08-05 at 10 59 11 PM" src="https://user-images.githubusercontent.com/28219092/62508169-b0e10f00-b7d4-11e9-9939-8bc001e1b8b6.png">
