### ISSUE TITLE
Change the post author

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-Android#10336]
### Expected behavior

The user would like to change the post author using the app.

### Actual behavior

This change isn't possible unless the user accesses the post editor using a browser.

### Additional context

#2255172-zen

**Comment by designsimply** [comment]
Thank you for the report @leandroalonso !

Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/4230.
