### ISSUE TITLE
Editor preference "Use Block Editor" does not work the first time a new post is created after the app is reopened after having been closed for several minutes

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10346]
Steps to reproduce:

1. Go to My Site > Settings and turn on "Use block editor."
1. Start a new post and make sure it opens in the block editor as expected.
1. Go to My Site.
1. Close the app.
1. Wait several minutes (maybe shorter, maybe longer).
1. Re-open the app.
1. Tap the + icon at bottom middle of the My Site screen to start a new post.

**Result:** the “Use Block Editor” setting does not work the first time a new post is started from the My Site screen after the app comes back from being closed for at least several minutes. (<a href="https://cloudup.com/cRwj0_JKT07">1m4s</a>, [1m1s](https://cloudup.com/cI2UL4Xj1IP))

Note: the same problem does not happen with the + icon at bottom right on the Blog Posts screen, it only happens for the + icon at the bottom middle in the My Site screen. I was able to reproduce it several times, but not _every single_ time.

<sup>Tested with WPAndroid alpha-183 (13.0 alpha) on Pixel 3 Android 9 using a WP.com simple site.</sup>

**Comment by hypest** [comment]
Fixed with #10345 . Feel free to re-open if it still happens after v13.0 of the app.
