### ISSUE TITLE
[Stats] "Selected" state pink is too dark on charts

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#10341]
Currently the selected state (light pink) part of the charts is too dark and looks like the bar is taller than it really is.

- Change light pink colour to Pink 0

**Comment by theck13** [comment]
Is this related to the pending color updates to the chart in https://github.com/wordpress-mobile/WordPress-Android/pull/10297?

**Comment by SylvesterWilmott** [comment]
Thanks @theck13 , it looks as intended in the "After" Screenshot
