### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Johnyy45** [wordpress-mobile/WordPress-Android#10340]
Hello. I would like to compile APK word press, but Make project failed with error:

_The following class loaders are orphaned: ClassLoaderScopeIdentifier.Id{root:C:\Users\userz\WordPress-Android\buildSrc:root-project:project-libs:project-utils:project-WordPressUtils(export)}:org.gradle.api.internal.initialization.loadercache.DefaultClassLoaderCache$CachedClassLoader@6e7bea5b,ClassLoaderScopeIdentifier.Id{root:C:\Users\user\WordPress-Android\buildSrc:root-project:project-libs:project-analytics:project-WordPressAnalytics(export)}:org.gradle.api.internal.initialization.loadercache.DefaultClassLoaderCache$CachedClassLoader@6e7bea5b_

I have installed:
- Android studio 3.4.2
- git version 2.22.0.windows.1 (with SSH hithub keys)
- java version "1.8.0_221" Java(TM) SE Runtime Environment (build 1.8.0_221-b11), but in Android Studio - About: JRE build 1.8.0_152_release_1343_b01 amd64
- gradlew -v

_Gradle 5.1.1
Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807
Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_221 (Oracle Corporation 25.221-b11)
OS:           Windows 7 6.1 amd64_

I performed following steps:
1. Generate and setup SSH keys (with git)
2. Clone git clone git@github.com:wordpress-mobile/WordPress-Android.git
3. Renamed gradle.properties-example to gradle.properties
4. Open in Android Studio, wait for downloading some components and Make Project

And command
gradlew installVanillaDebug

_WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessManifest(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Task :libs:networking:WordPressNetworking:compileDebugJavaWithJavac FAILED_

Please, help me. It is "Java jokes"?

**Comment by Johnyy45** [comment]
[Type] Enhancement

**Comment by designsimply** [comment]
Is it possible your gradle version is too far ahead? You may have got a prompt in Android Studio to upgrade but should be ~v4.10. 

Aside: right now, a generally good place to ask support-oriented questions like this one about build troubles is in [the #mobile channel](https://app.slack.com/client/T024MFP4J/C02RQC4LY) on Slack (see https://make.wordpress.org/chat/) because you'll likely get a quicker response there! 😊

**Comment by jkmassel** [comment]
We've received no response, so we'll close this for now. Please reach out if you need further assistance!
