### ISSUE TITLE
Remote-auto-saved not automatically invoked when editing published post

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10349]
This issues is currently reproducible only on `issue/10174-update-changes-confirmed-at`.

After editing a published post and exiting the editor, the remote auto-save does not seem to get executed right away. I can force the remote auto-save by swiping to refresh. Here is a [video](https://drive.google.com/file/d/1SrKjJkQBJ6Nn_aeURSoztFvGtypgjt85/view?usp=sharing) showing this. And the steps:

1. Edit a published post.
2. Make changes.
3. Exit the editor by pressing the Back button.
4. Confirm in Calypso that no revision was created.
5. 00:23 Swipe to refresh. An upload feedback UI will show that the post is being remote auto-saved.
6. Confirm in Calypso that a revision was created.

Thank you @shiki for finding and recording the issue;)!

Note: [This if statement](https://github.com/wordpress-mobile/WordPress-Android/blob/5516721e8275aa088473d756129a0f024d57635a/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2337) is causing these troubles. I think we should completely get rid of it and get rid of `savePostLocallyAndFinishAsync`. As we always want to invoke remote-auto-save (with exception for self-hosted sites). Just be careful that we'll need to handle https://github.com/wordpress-mobile/WordPress-Android/blob/5516721e8275aa088473d756129a0f024d57635a/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2133.

**Comment by shiki** [comment]
Closing since this is fixed by #10353.
