### ISSUE TITLE
Create new page with Gutenberg, tap "Switch to Classic Editor", post (not page) will be created

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#10352]
I guess the `EXTRA_IS_PAGE` is not passed when recreating the activity.

### Actual behavior

- From the Draft tab in the Page list (same will happen elsewhere, but it's easier to notice the issue).
- Create new page with Gutenberg, 
- From the overflow menu, tap "Switch to Classic Editor"
- Add a title
- Tap back
- Refresh the Draft tab in the Page list, notice there is no new page.
- Go to the Draft tab in the Post list, here is your newly created "Page".

### Expected behavior

- From the Draft tab in the Page list (same will happen elsewhere, but it's easier to notice the issue).
- Create new page with Gutenberg, 
- From the overflow menu, tap "Switch to Classic Editor"
- Add a title
- Tap back
- Notice the new page on the Draft tab in the Page list

**Comment by hypest** [comment]
Can't repro on WPAndroid v15.9-rc-2. New page properly stays in the Pages draft section and doesn't appear on the posts list. Closing but please reopen if the issue happens again. Thanks!
