### ISSUE TITLE
Draft remote-auto-saved multiple-times

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10350]
This issue is currently reproducible only on `issue/10174-update-changes-confirmed-at`

It looks like previously remote auto-saved drafts are always remote auto-saved even when there are no changes. These steps are reproduced when online:

1. Create a draft and exit the editor.
2. After uploading, edit the draft.
3. Exit the editor. Remote auto-save will happen.
4. Open the draft but do not make any changes.
5. When exiting the editor, the draft gets uploaded again.

Here is a [video](https://drive.google.com/file/d/1yghDBpU_tnQfherbzFN8CDA0JHweExQD/view?usp=sharing) showing this.

Thank you @shiki for finding and recording this issue!

Note: Previously, drafts with local changes were always uploaded to the server - https://github.com/wordpress-mobile/WordPress-Android/blob/5516721e8275aa088473d756129a0f024d57635a/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2370 this is the line which is causing the problem. `ShouldSave` returns true even when the user haven't made any changes during this editing session.

**Comment by shiki** [comment]
Closing. This should be fixed by #10351.
