### ISSUE TITLE
Add analytics to track undo/redo in Aztec and Gutenberg

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#10360]
Implementation will be different for Aztec (overflow menu items) and Gutenberg (toolbar buttons). We also have to track from which editor the event originates (via event props).

**Comment by iamthomasbishop** [comment]
Thanks for filing this issue, @maxme! One note on the implementation: We might want to track these (as a group) in a way that's location agnostic because I'm not sure where in the UI they will be positioned in the future. Right now they're in the quick toolbar in GB, but I'm considering moving them to the app bar or somewhere else depending on what the data tells us.

**Comment by daniloercoli** [comment]
I've also noticed that Aztec is not bumping stats for some of the toolbar buttons. `Bold` and `Italic` as an example don't trigger the analytics code. We should double check that everything is bumped correctly in Aztec, and add the tracking code to GB, that is quite clean atm.

**Comment by hypest** [comment]
What's the status of this on the WPiOS side? Do you know @maxme ? Ideally we want to have the same tracks among the platforms.

**Comment by maxme** [comment]
(I'm a bit late) noticed that one on iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/12327

@hypest good point, I thought the source was tracked in wpios, but apparently it's only for aztec/hybrid and I guess something should be changed to add gutenberg. I'll open an issue on wpios to track event source.

**Comment by maxme** [comment]
Issue created here: https://github.com/wordpress-mobile/WordPress-iOS/issues/12333

@daniloercoli can you make sure we use the same name in wpios (`editor_source`) and wpandroid for this specific event?

**Comment by designsimply** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/12333. @maxme please re-open if Gutenberg (toolbar buttons) tracking is still needed and I've closed this issue too early!
