### ISSUE TITLE
Add search for "Set Parent" page

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#10399]
### Expected behavior
When you go to My Site > Pages you can search for the different pages on your site.  If you then click on the options button and try select Set Parent you are taken to another page that displays your pages, but this one does not have a search.

For sites with a small number of pages, this isn't a problem, but if you start having a lot of pages, trying to find the right one to set as parent can be difficult.  It would be great if the set parent page had a search field too

<img src="https://cdn-std.dprcdn.net/files/acc_593859/gsK0QB" />

### Steps to reproduce the behavior
1. Go to My Site > Pages > Options for a page > Set Parent
there is no search option

**Comment by designsimply** [comment]
Closing in favor of a new issue which was also added to a project board: https://github.com/wordpress-mobile/WordPress-Android/issues/11119.
