### ISSUE TITLE
Activity Log: Backup download link takes one to stats view which is unexpected

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/WordPress-Android#10408]
### Expected behavior

The backup download link takes one to the Activity Log view.

### Actual behavior

The backup download link takes one to the Stats view.

### Steps to reproduce the behavior

- Initiate a backup download for a site from Jetpack's Activity Log.
- Wait for the backup to be prepared.
- When it is prepared, a notification will be shown.
- Click on the backup download link available on that notification.

##### Tested on [device], Android [version], WPAndroid [version]

Tested on OnePlus 5 with Android 9 and WordPress version alpha-178

### Screenshots

<img src="https://user-images.githubusercontent.com/18581859/63208288-dbde3380-c0ef-11e9-9765-96a7125b066c.jpg" width="320">

<img src="https://user-images.githubusercontent.com/18581859/63208287-db459d00-c0ef-11e9-9238-eb3df8b031b9.jpg" width="320">

**Comment by hafizrahman** [comment]
Did a bit of testing. The "download it" string on the notification links to this:

https://wordpress.com/activity-log/[sitename]

**Comment by hafizrahman** [comment]
So the function that deals with the tapping of the "download it" string is here:

https://github.com/wordpress-mobile/WordPress-Android/blob/50f98a16880a535af82c35f7a81c3c65e592fa9a/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.java#L254

It does different things on different type of links on a notification depending on the notification note. For the particular "download it" string, the `clickedSpan.getRangeType()` returns `STATS`, hence why the Stats view is then shown when it is tapped. Still trying to figure out why the link is categorized as `STATS` in the first place.

**Comment by shiki** [comment]
@hafizrahman I agree that this should be fixed in the API. I'm not sure about intercepting it as this might be affecting WPiOS too.

**Comment by zwarm** [comment]
This has been addressed. See attached.

<img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/175982872-97972ad6-8170-490a-9c02-589ae4b5bca1.gif">
