### ISSUE TITLE
Local auto-save doesn't work in Gutenberg

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10415]
### Expected behavior
When I'm editing a post in Gutenberg it's being auto-saved periodically into the local database.

### Actual behavior
When I'm editing a post in Gutenberg it's not being auto-saved into the local storage.

### Steps to reproduce the behavior
1. Create a draft
2. Edit title and content
3. Notice `https://github.com/wordpress-mobile/WordPress-Android/blob/180162d62b568319f497ae3b82f22d0b98d87448/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2333` is never invoked
4. Restart/kill the app using ADB
5. Open the app and notice the Title and Content you created in step 2 is lost.

@hypest Could you please look into this issue or ping someone who might have some insights. Thanks

**Comment by designsimply** [comment]
@wpericam thank you for the comment! This is a public repository and so it's really helpful to also have a quote or some kind of detail or short explanation about the support interaction to help explain the problem when referring to a user report. I've checked the chat transcript you linked to and here's an example of what we're looking to see when you add a comment to an issue like this one:

> I just created a blog post and now can’t find it. I created it off of my WordPress app on my phone and went to upload it, it kept saying upload failed so I closed and reopened the app and it was gone.

<sup>(internal reference: 10314703-hc)</sup>

I also noticed that the user agent note in the chat transcript details at the top mentions "iPhone" and it's helpful for mobile issues to note which type of device the user is working from.

Noteworthy: it's not clear in the support interaction whether they were using the Aztec editor or the block editor. If you see a similar report in the future about a lost post, it would help to try to find out the user's device details and which editor was being used (if possible!) at the time the problem happened. In this case, it looks like they had already closed/reopened the app and lost their post but if they hadn't already done that then we may have been able to get that information from the app logs or checked the API to see what their current editor preference setting is and you can ask a Mobile Guild Happiness Engineer for help with that (in the #cellular-happiness channel in Slack) if you need to. Thanks so much!

**Comment by mkevins** [comment]
I reproduced this on a Pixel 3a using the steps described. [The line in the description](https://github.com/wordpress-mobile/WordPress-Android/pull/10483/files#diff-02f567e707c1df878dfea548cfec3da7R290) is invoked _once_ though, when the post is first opened. @malinajirka, is that expected?

**Comment by daniloercoli** [comment]
> I reproduced this on a Pixel 3a using the steps described. [The line in the description](https://github.com/wordpress-mobile/WordPress-Android/pull/10483/files#diff-02f567e707c1df878dfea548cfec3da7R290) is invoked _once_ though, when the post is first opened. @malinajirka, is that expected?

The original line was https://github.com/wordpress-mobile/WordPress-Android/blob/180162d62b568319f497ae3b82f22d0b98d87448/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2333 , that is invoked only at the beginning. Move the breakpoint into the `Observer` object few lines below,  set the breakpoint "inside" the runnable `mSave ` here https://github.com/wordpress-mobile/WordPress-Android/blob/180162d62b568319f497ae3b82f22d0b98d87448/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L714 
You can also set it into `updatePostObject`.

**Comment by mkevins** [comment]
Oh, thanks for clarifying @daniloercoli ! :+1:

**Comment by marecar3** [comment]
I was also able to reproduce the bug on Pixel3, Android 9.
command which I used to kill the app with adb is: `adb shell am force-stop org.wordpress.android.beta`
