### ISSUE TITLE
PostList: Change copy of "Unhandled autosave" label

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10462]
Two things related to "Unhandled Auto Save" label came up during our design review with @osullivanchris.

1. We might want to consider changing the copy 
2. We might want to consider changing the color from red to yellow

cc @osullivanchris 

**Question for a copy reviewer:**

We currently show "Unhandled Auto Save" when the user edits a post on another device (eg web) and leaves the editor without saving the changes.

<img src="https://user-images.githubusercontent.com/2261188/65508813-59f0df80-ded1-11e9-98b3-970781249d9f.png" height="300" />

When the user clicks on such post we show the following dialog (the dialog has already been copy reviewed).
<img src="https://user-images.githubusercontent.com/2261188/65508963-aa683d00-ded1-11e9-8e80-bc425516232a.png" height="300" />
I'm not sure about the current "Unhandled Auto Save" copy, wdyt?

**Comment by elibud** [comment]
> We might want to consider changing the copy

Please do. "Unhandled autosave" is not clear/descriptive to users.

> We currently show "Unhandled Auto Save" when the user edits a post on another device (eg web) and leaves the editor without saving the changes.

I don't really understand the situation from that description.

**Comment by malinajirka** [comment]
>>We currently show "Unhandled Auto Save" when the user edits a post on another device (eg web) and leaves the editor without saving the changes.

>I don't really understand the situation from that description.

1. Open a published post in Calypso and edit its content
2. Wait approximately 30s so the autosave gets invoked
3. Close the browser without manually saving the changes
4. Open the app
5. The post has two versions 
     - published version
     - unpublished version (the one you created in step 1)

-> we currently show "Unhandled Auto Save" label to indicate this state 

This is the dialog we show in Calypso

<img width="403" alt="Screenshot 2019-09-24 at 14 02 33" src="https://user-images.githubusercontent.com/2261188/65510015-1f3c7680-ded4-11e9-83e0-59b7a805ec1d.png">

I think we could change "Unhandled Auto Save" to "Unpublished revision available" and change its color from red to yellow. Wdyt?

**Comment by elibud** [comment]
> I think we could change "Unhandled Auto Save" to "Unpublished revision available" and change its color from red to yellow. Wdyt?

Much better than "Unhandled Auto Save", but maybe we want to mention the fact that there's a conflict? Have you looked at what Calypso does if things happen the other way around? (post updated on mobile)

**Comment by malinajirka** [comment]
>Much better than "Unhandled Auto Save", but maybe we want to mention the fact that there's a conflict? 

In fact, there isn't any conflict in this scenario -> there is just an unpublished/autosaved revision available. 
Calypso doesn't show any indication on the item in the post list -> it simply shows the dialog I posted above when the user clicks on a post with "unpublished/autosaved revision". We could theoretically follow the same pattern, but we thought it'd be nicer to be explicit since we already support "status" labels on post list items.

**Comment by elibud** [comment]
> but we thought it'd be nicer to be explicit since we already support "status" labels on post list items.

Agreed, let's wait to see what Editorial says about the copy.

**Comment by benhuberman** [comment]
@malinajirka @elibud I very much agree that "Unhandled Auto Save" is not optimal. I'm also not sure about "Unpublished version available," which could be confusing in the case of edits made to an already-published post (as opposed to a draft). How about this as another option:

> This post has more than one version available. 

Or:

> You've made unsaved changes to this post.

I would likely vote for the second option, as it centers the user's perspective. But as I also remember from the recent discussion around the dialog copy ("which version would you like to edit?") this is a really tricky scenario/flow, and no single line of copy is likely to make it all perfectly clear and obvious.

**Comment by shiki** [comment]
This was done in #10528
