### ISSUE TITLE
Remove the "Publish with Confidence" dialog

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#10474]
I think we can remove the `Publish with Confidence` promo dialog, that was introduced long time ago to get users comfortable with the "async publishing" feature, and that's shown the first time the users publish a post from the mobile app - 
![device-2019-09-02-170241](https://user-images.githubusercontent.com/518232/64123231-16a8c280-cda4-11e9-8359-c45dc32b5bea.png)

and fall back to the classic `Publish now` dialog, since the async publishing feature is not 2 years old?!
![device-2019-09-02-170450](https://user-images.githubusercontent.com/518232/64123387-8323c180-cda4-11e9-89aa-83e18b395edd.png)

cc @iamthomasbishop

**Comment by iamthomasbishop** [comment]
Agree this can be removed. It was mostly a feature announcement dialog, and is now more of an expected behavior. I would ping @diegoreymendez and team to see if they feel the publish confirmation dialog needs any copy adjustment related to offline, but that can be tackled in another issue.
