### ISSUE TITLE
client no longer honours http basic auth

### ISSUE THREAD

**Issue by kbsingh** [wordpress-mobile/WordPress-Android#10499]
### Expected behavior
when logging into a self hosted site, the client prompts for basic auth, and passes it along and is able to access the site

### Actual behavior
the client only uses the basic auth user/pass for the first call to the /xmlrpc.php endpoint, all subsequent calls are made without the basic auth resulting in 403 errors from the service; this problem exists on the stable channel client and the beta channel client.

### Steps to reproduce the behavior
select login to self-hosted site that has basic auth enabled

##### Tested on [device], Android [version], WPAndroid [version]
Andorid 9
Wordpress 5.1.2
Android client 13.2 ( on beta channel ).

**Comment by designsimply** [comment]
Thanks for reporting! This looks very similar to https://github.com/wordpress-mobile/WordPress-Android/issues/6264 which was closed by stalebot in the past (we no longer auto-close those!), but since this issue has a more detailed report let's leave the other closed in favor of the new request here.

**Comment by kbsingh** [comment]
Anything I can help with to get traction here?

**Comment by designsimply** [comment]
@kbsingh I think it might be helpful to note what type of web server you are using (i.e. nginx, Apache, IIS). 

I am also interested to know more about your use case and why you think this is an important request—for example, was your site attacked and then you implemented basic auth as an extra layer of security or is there another reason? (not required but I am interested in the whys behind such requests! 🙂) 

@planarvoid can you or @develric please look into this issue during Groundskeeping this week?

Notes:

> http auth should be supported at FluxC level, all xmlrpc calls should be http authenticated if the first one was authenticated
<sup>(internal reference: archives/GMPLDSYSD/p1568966161011600-slack-mobile-issues-planning)</sup>

**Comment by designsimply** [comment]
I tested with an nginx server using the following steps and here's what I found:

1. Create an `.httpasswd` file in a location such as `/etc/nginx` on the server.
1. Add an `auth_basic` directive to a password protected area such as `/wp-admin` in a root standalone WP install. I used [these instructions](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/#config).
1. Restart the web server.
1. Confirm basic auth is working by testing it in a browser.
1. Log out of the app (if you were logged in already).
1. Log in to the app for a self-hosted site with http basic auth in place by choosing the option that says "Log in by entering your site address."
1. Browse Pages, Posts, & Media.
1. Create and save a few draft posts.
1. Completely delete the app and reinstall it and test again (for good measure).

**Results:** with basic auth setup for the root directory of my self-hosted WordPress install, I am still able to log in and browse posts and pages as well as create drafts—I was unable to view media though— and I was not prompted for http basic auth credentials at all during the process.

App logs related to failed media load:

```
58 - [Sep-24 21:21 API] Dispatching action: MediaAction-FETCH_MEDIA_LIST
59 - [Sep-24 21:21 API] Dispatching action: SiteAction-FETCH_SITE
60 - [Sep-24 21:21 API] long type could be misinterpreted when sent to the WordPress XMLRPC end point
61 - [Sep-24 21:21 API] long type could be misinterpreted when sent to the WordPress XMLRPC end point
62 - [Sep-24 21:21 UTILS] trackLastActivity, activityId: Media Library
63 - [Sep-24 21:21 MEDIA] No more media items to delete. Stopping MediaDeleteService.
64 - [Sep-24 21:21 API] Dispatching action: SiteAction-UPDATE_SITE
65 - [Sep-24 21:21 DB] Site found by (local) ID: 2
66 - [Sep-24 21:21 DB] Updating site: http://designsimply.com
67 - [Sep-24 21:21 MEDIA] Fetched media list for site via XMLRPC.GET_MEDIA_LIBRARY
68 - [Sep-24 21:21 API] Dispatching action: MediaAction-FETCHED_MEDIA_LIST
69 - [Sep-24 21:21 API] Dispatching action: MediaAction-FETCH_MEDIA_LIST
70 - [Sep-24 21:21 API] Dispatching action: SiteAction-FETCH_SITE
71 - [Sep-24 21:21 API] long type could be misinterpreted when sent to the WordPress XMLRPC end point
72 - [Sep-24 21:21 API] long type could be misinterpreted when sent to the WordPress XMLRPC end point
73 - [Sep-24 21:21 API] Dispatching action: SiteAction-UPDATE_SITE
74 - [Sep-24 21:21 DB] Site found by (local) ID: 2
75 - [Sep-24 21:21 DB] Updating site: http://designsimply.com
76 - [Sep-24 21:21 MEDIA] Fetched media list for site via XMLRPC.GET_MEDIA_LIBRARY
77 - [Sep-24 21:21 API] Dispatching action: MediaAction-FETCHED_MEDIA_LIST
78 - [Sep-24 21:21 MEDIA] Failed to load resource
There was 1 cause:
com.android.volley.AuthFailureError(null)
call GlideException#logRootCauses(String) for more detail
79 - [Sep-24 21:21 MEDIA] StackTrace: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 cause:
com.android.volley.AuthFailureError(null)
call GlideException#logRootCauses(String) for more detail
  Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
There was 1 cause:
com.android.volley.AuthFailureError(null)
call GlideException#logRootCauses(String) for more detail
    Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
There was 1 cause:
com.android.volley.AuthFailureError(null)
call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.android.volley.AuthFailureError: 

80 - [Sep-24 21:21 UTILS] trackLastActivity, activityId: Media Library
81 - [Sep-24 21:21 MEDIA] No more media items to delete. Stopping MediaDeleteService.
82 - [Sep-24 21:21 UTILS] App goes to background
83 - [Sep-24 21:21 STATS] 🔵 Tracked: application_closed, Properties: {"last_visible_screen":"Media Library","time_in_app":681}
84 - [Sep-24 21:21 MAIN] ConnectionChangeReceiver successfully unregistered
85 - [Sep-24 21:21 UTILS] App comes from background
86 - [Sep-24 21:21 STATS] 🔵 Tracked: application_opened
87 - [Sep-24 21:21 STATS] 🔵 Tracked: deep_link_not_default_handler, Properties: {"interceptor_classname":"com.android.internal.app.ResolverActivity"}
88 - [Sep-24 21:21 UTILS] trackLastActivity, activityId: My Site
89 - [Sep-24 21:21 API] Dispatching action: SiteAction-FETCH_POST_FORMATS
90 - [Sep-24 21:21 API] Dispatching action: SiteAction-FETCH_SITE_EDITORS
91 - [Sep-24 21:21 API] long type could be misinterpreted when sent to the WordPress XMLRPC end point
92 - [Sep-24 21:21 NOTIFS] Sending GCM token to our remote services: **REDACTED**
93 - [Sep-24 21:21 UTILS] trackLastActivity, activityId: Media Library
94 - [Sep-24 21:21 MEDIA] No more media items to delete. Stopping MediaDeleteService.
95 - [Sep-24 21:21 API] Dispatching action: SiteAction-FETCHED_POST_FORMATS
96 - [Sep-24 21:21 UTILS] trackLastActivity, activityId: Me
97 - [Sep-24 21:21 STATS] 🔵 Tracked: me_tab_accessed
98 - [Sep-24 21:21 STATS] 🔵 Tracked: support_opened, Properties: {"origin":"ME_SCREEN_HELP"}
99 - [Sep-24 21:21 UTILS] trackLastActivity, activityId: Help Screen
```

<sup>Tested with WPAndroid alpha-189 (13.3 alpha) on Pixel 3 Android 9.</sup>

@kbsingh it seems my testing results are different from yours so let's sync up on testing steps. 

> the client only uses the basic auth user/pass for the first call to the /xmlrpc.php endpoint, subsequent calls are made without the basic auth resulting in 403 errors from the service

How exactly did you test and verify the 403 errors you mentioned earlier?

What type of web server are you using and how did you setup basic auth?

Can you please let me know your testing steps exactly similar to how I listed my testing steps above?

**Comment by kbsingh** [comment]
@designsimply answering your question about the 'why of the problem space' - this is a private website that we use in a small closed group, its not a public website, so https + BasicAuth. 

httpd-2.4.34
php-7.2
WordPress 5.2.3
mariadb-5.5.64
caddy-v1.0.3

auth is implemented at the LB ( Caddy ), the config looks like :
```
priv.karan.org, www.priv.karan.org {
    proxy / https://192.168.122.53 {
        transparent
        max_fails 1
    }
    log /var/lib/caddy/logs/priv.ko
    basicauth / hello world
}
```
![UntitledDiagram](https://user-images.githubusercontent.com/207967/65835666-fc013500-e2e0-11e9-88fc-bdc9f38096be.png)
( ignore the 2nd instance of wordpress, its a convenience thing, and entirely irrelevant to this conversation ) 

the httpd config is also fairly simple : 
```
VirtualHost *:80>
  ServerAdmin webmaster@priv.karan.org
  ServerName priv.karan.org
  ServerAlias www.priv.karan.org
  CustomLog logs/pko-maccess.log common
  ErrorLog logs/pko-error.log

  DocumentRoot /home/pko/public_html

</VirtualHost>
```

public_html/ here is just untar'd wordpress's latest.tar.gz and the db config edited

When i hit the service from a browser ( google-chrome,76.0.3809.100 and  firefox-69.0.1, both on linux ), they do their right thing and here are the log lines i see:

```
Caddy:
10.0.10.223 - - [29/Sep/2019:17:00:21 +0000] "GET / HTTP/2.0" 401 17
10.0.10.223 - hello [29/Sep/2019:17:00:22 +0000] "GET / HTTP/2.0" 200 66779
10.0.10.223 - - [29/Sep/2019:17:00:22 +0000] "GET /favicon.ico HTTP/2.0" 401 17
10.0.10.223 - hello [29/Sep/2019:17:00:22 +0000] "GET /favicon.ico HTTP/2.0" 200 0

httpd:
192.168.122.80 - hello [29/Sep/2019:17:00:21 +0000] "GET / HTTP/1.1" 200 66779
192.168.122.80 - hello [29/Sep/2019:17:00:22 +0000] "GET /favicon.ico HTTP/1.1" 200 -
```
note that caddy will pass along the user in the http headers, there is no auth setup at that layer, its only at the caddy level; Now when hitting the service from the android app, the logs look like this 
```
Caddy:
10.0.10.213  - - [29/Sep/2019:17:04:24 +0000] "POST /xmlrpc.php HTTP/2.0" 401 17
10.0.10.213  - - [29/Sep/2019:17:04:24 +0000] "POST /xmlrpc.php HTTP/2.0" 401 17
<app asks for http auth login/pass>
10.0.10.213 - hello [29/Sep/2019:17:04:40 +0000] "POST /xmlrpc.php HTTP/2.0" 200 403
10.0.10.213 - - [29/Sep/2019:17:04:40 +0000] "GET /xmlrpc.php HTTP/2.0" 401 17
10.0.10.213 - - [29/Sep/2019:17:04:40 +0000] "GET /xmlrpc.php HTTP/2.0" 401 17
<app asks again for http auth login /pass>
.. this loop now repeats ...
httpd:
192.168.122.80 - hello [29/Sep/2019:17:04:39 +0000] "POST /xmlrpc.php HTTP/1.1" 200 403
```
So the call is passed through from caddy, to httpd, with a valid user/pass, but the android client is not generating a valid call. xmlrpc.php  403's the request.

on the cli, i can "curl -X POST https://hello:world@priv.karan.org/xmlrpc.php" and get a 200 response.
hitting up the /xmlrpc.php url from a browser, gets me an expected 405 ( method not supported, i guess its looking for a POST )

addional data points : 
1. my wordpress android flow is, to just install it, start it up, login using site address and that gets me in this loop.
2. turning off HTTPS all over, and just going with http:// makes everything work fine ( ie, i can login with the andorid client and i can edit posts, upload images  etc ) - so while its possible the problem is elsewhere, this brought me to the 'https issue'. I realise looking through the logs now that the problem maybe more client side, that it generates the 403's instead of 200's.

In effect, this may not be a auth related issue, but something else (?) in that the client does its POST, gets a 403, and unsure howto handle it, just gets stuck in a loop asking for user/pass.

**Comment by kbsingh** [comment]
Spent a bit more time on this today, and it looks like media uploads do not send user/pass at all for basic Auth. The server is sending 401 errors back to the client, and on the android device it's surfaced as 'upload failed, retry?' 

Any chance you can help confirm this @designsimply ?

**Comment by kbsingh** [comment]
I have the whole stack setup and now working, reproduced, with WordPress Android 13.3-rc-1 and WordPress 5.2.3, working behind Caddy 1.0.3 on CentOS Linux 7 (rh-php72 scl ).

The challenges were entirely in WordPress itself and the way Caddy prefers to run by default. I will put some docs together, along with an example ansible script to get this working for anyone else who may run into the same issues I did.

Appreciate the help here.
