### ISSUE TITLE
Self-hosted site: Upload error after successful media upload

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10513]
### Expected behavior
When a media upload finishes and the user didn't explicitly confirm the changes we don't want to upload the post on self-hosted sites.

### Actual behavior
When a media upload finishes and the user didn't explicitly confirm the changes we try to remote-auto-save the post (remote auto save isn't supported on self-hosted sites) which results in an upload error.

### Steps to reproduce the behavior
1. Connect to a self-hosted site
2. Turn on airplane mode
2. Add image to an existing draft
3. Click on back
4. Turn off airplane mode
5. Notice the media is uploaded but the post upload fails with "Couldn't perform operation" error. (we shouldn't try to upload a post for which the user didn't confirm the changes).

**Comment by shiki** [comment]
Closed by #10517.
