### ISSUE TITLE
Post update notification shown after remote-auto-save

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10518]
### Expected behavior
When the remote-auto-save finishes, "post updated/published" notification shouldn't be shown.

### Actual behavior
When the remote-auto-save finishes, "post updated/published" notification is shown.

### Steps to reproduce the behavior
1. Add media item to a published post
2. Click on back
3. Click on home
4. Notice the notification

**Comment by shiki** [comment]
Fixed by #10519
