### ISSUE TITLE
Infinite media upload notification

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10535]
There are two probably related issues:
- Completely unrelated "Error while trying to save post before preview" error is sometimes shown when I upload an image in the editor. The error shouldn't be shown unless I'm trying to preview the post and it fails.
- If I try to upload another media after the error mentioned above was shown, the media upload notification gets stuck on 100% and never disappears

### Steps to reproduce the behavior
I tested it on a self-hosted site, I'm not sure if it's related.
1. Add an image into a post
2. Wait until the upload completes
3. Add an image into a different post
4. Notice that sometimes un unrelated error is shown
5. Add another image
6. Notice there is a dangling media upload notification

![danling-notification](https://user-images.githubusercontent.com/2261188/65761877-06c09c00-e120-11e9-97be-1260cbd20f29.gif)

##### Tested on [device], Android [version], WPAndroid [version]
Emulator API 29

**Comment by shiki** [comment]
> "Error while trying to save post before preview"

@malinajirka  I think I saw this once and mentioned you and Maxime about it but it was difficult to reproduce. My only guess is it has something to do with `onPostUploaded`. Possibly an invalid state is being set somewhere. 

https://github.com/wordpress-mobile/WordPress-Android/blob/133af1cb8e71ee01b9f3e46ffa478b09d02f5be2/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L4017-L4021

**Comment by malinajirka** [comment]
I wasn't able to reproduce this issue - I think [this change](https://github.com/wordpress-mobile/WordPress-Android/pull/10557/files) might have fixed it.
