### ISSUE TITLE
Draft preview fails to load: Page not found

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10544]
Test Online-SelfHosted-4

### Expected behavior
The preview of a draft without local changes loads.

### Actual behavior
The preview of a draft without local changes fails to load - page not found message is shown.

### Steps to reproduce the behavior
0. ~Log into a Self-hosted site~ (update: Login into a Jetpack site using self-hosted login)
1. On the post list, Draft tab selected
2. Open the editor (Aztec) with a draft without local changes
3. Tap “… More” -> “View”
3. Remote view (webview) should open

##### Tested on [device], Android [version], WPAndroid [version]
Samsung Galaxy S9 (Android 9)

See comments on p77Llu-cHb-p2 for more info and video.

**Comment by malinajirka** [comment]
Sites created on http://poopy.life/ don't work. It seems like an issue with a login (+redirect).

It seems the server is redirecting us to `http://clear-kouprey.w5.poopy.life/wp-admin/admin.php?page=sandbox&tab=expiration` instead of the preview url

<img width="1292" alt="Screenshot 2019-10-01 at 10 02 32" src="https://user-images.githubusercontent.com/2261188/65944720-a341b180-e432-11e9-9005-13bce8cae5ba.png">

It seems our request is following the documentation - https://developer.wordpress.org/reference/hooks/login_redirect/.

@oguzkocer I know you worked on opening sites in an internal browser issue - this seems a bit related. Do you have any suggestions?

**Comment by maxme** [comment]
@malinajirka I just tried on my self hosted and it worked fine.

> &tab=expiration

Url looks suspicious but maybe it's specific to poopy.life site, can you double check the site is not expired?

**Comment by malinajirka** [comment]
>Url looks suspicious but maybe it's specific to poopy.life site, can you double check the site is not expired?

I tried to perform the same steps with a site created right before the test and the result was the same. 
I also tried to publish/edit posts after I received the wrong redirect and everything worked as expected -> the site isn't expired.

**Comment by oguzkocer** [comment]
> @oguzkocer I know you worked on opening sites in an internal browser issue - this seems a bit related. Do you have any suggestions?

Sorry @malinajirka, nothing comes to mind. I can look into it though if you want.

**Comment by shiki** [comment]
This looks like it's specific to poopy.life. 

I tried with a bare jurassic.ninja site -- no jetpack and logged in using site credentials in the app. The redirect is correct:

```
curl -d "log=demo&pwd={PASSWORD}&redirect_to=https%3A%2F%2Fvalid-de.jurassic.ninja%2F%3Fp%3D5%26preview%3Dtrue" -X POST https://valid-de.jurassic.ninja/wp-login.php -i
HTTP/2 302
server: nginx
date: Wed, 02 Oct 2019 14:11:14 GMT
content-type: text/html; charset=UTF-8
location: https://valid-de.jurassic.ninja/?p=5&preview=true
```

With a poopy.life site, it redirects to `wp-admin/admin.php`:

```
curl -d "log=demo&pwd={PASSWORD}&redirect_to=http%3A%2F%2Faverage-angelfish.w6.poopy.life%2F%3Fp%3D5%26preview%3Dtrue" -X POST http://average-angelfish.w6.poopy.life/wp-login.php -i
HTTP/1.1 302 Found
Date: Wed, 02 Oct 2019 14:26:33 GMT
Server: Apache/2.4.26 (Red Hat)
Location: wp-admin/admin.php?page=sandbox&tab=expiration
Content-Type: text/html; charset=UTF-8
```

Similar requests but with different results. 

I acquired these arguments by placing a breakpoint in: 

https://github.com/wordpress-mobile/WordPress-Android/blob/b93cf48d916f0f43a3df11c6dbee42af783a31fe/WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java#L771-L776

**Comment by malinajirka** [comment]
Yep I agree, that it seems server specific. Having said that, I have sites which don't work from similar reasons which are not hosted on poopy.life 🤷‍♂ ... I'll try to look into it, but my hopes aren't high - I think we won't be able to make it work without changing the setup of the server side.

**Comment by malinajirka** [comment]
So the issue with poopy.life seems really server specific.

However, I was able to fix the issue which @AmandaRiu originally reported. As it turned out the site which didn't work was actually a jetpack (not a pure self-hosted) site. There was a bug in the app and we tried to load the site with empty an "frame_nonce". Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/10561
