### ISSUE TITLE
Add labels to bottom navigation

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#10590]
We should show labels as well as icons when we have 3 bottom navigation items. We'll reduce the number of bottom navigation items to 3 as part of the IA project.

**Comment by designsimply** [comment]
Adding a quick screenshot from 13.4-rc-1 for reference.

<img src="https://user-images.githubusercontent.com/1119271/66681877-e7059980-ec30-11e9-9784-876d39b37a0c.png" width="270" alt="Screenshot_20191011-140759">

**Comment by develric** [comment]
Closed by #10730
