### ISSUE TITLE
Stats: change default site icon

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#1063]
The default site icon is just a grey box. Perhaps a simple black & white globe instead?

![device-2014-03-07-182318](https://f.cloud.github.com/assets/3903757/2363543/9b156960-a64f-11e3-872c-0232f5dd8476.png)

**Comment by daniloercoli** [comment]
This ticket is still valid for Calypso Stats.
![screen shot 2015-01-07 at 10 52 41](https://cloud.githubusercontent.com/assets/518232/5643655/52516ae2-965b-11e4-9078-cff4c21713c2.png)

We should use the globe icon: 
![screen shot 2015-01-07 at 10 53 29](https://cloud.githubusercontent.com/assets/518232/5643661/6ed88eb6-965b-11e4-95b8-e53f90085a9e.png)

**Comment by daniloercoli** [comment]
@maxme - Is there’s any possibility at all of using SVGs for this that would make a ton of sense as we’re moving to use SVGs on the web.

**Comment by maxme** [comment]
> Is there’s any possibility at all of using SVGs for this that would make a ton of sense as we’re moving to use SVGs on the web.

They're currently different problems with Android native vector images support:
* [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html) is an API 21+ only feature. It's not implemented in the support library and there is no ETA for this.
* You need to convert SVGs to [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html). It could be done easily with a script thanks to `android:pathData`:
`Defines path string. This is using exactly same format as "d" attribute in the SVG's path data. This is defined in the viewport space.`

The only solutions at the moment if we have SVGs as source files for icons:
* Generate drawables for supported screens during the build step (or pre-generate them like we did from font files).
* Try some android-svg libraries (https://code.google.com/p/svg-android/ for instance) not convenient cause we can't use them in xml layouts.
* Wait for VectorDrawables to be included in the support library.

**Comment by daniloercoli** [comment]
@jancavan - Recapping, we need png icons at the following sizes:
- 48px (hdpi)
- 64px (xhdpi)
- 96px (xxhdpi)

**Comment by jancavan** [comment]
![stats_icon_web](https://cloud.githubusercontent.com/assets/4924246/5981160/9219487a-a86c-11e4-8866-9a2db7581310.png)
![stats_icon_web](https://cloud.githubusercontent.com/assets/4924246/5981161/964a6d7a-a86c-11e4-8964-575f45eebafa.png)
![stats_icon_web](https://cloud.githubusercontent.com/assets/4924246/5981163/9ad630d6-a86c-11e4-93cb-da95f204acdd.png)

@daniloercoli I'm assuming the light blue bg will be added in the code so it's not on the PNG, but if you need it otherwise, let me know.

**Comment by daniloercoli** [comment]
@jancavan - It's better to have the light blue right in the icons, otherwise I need to change the XML file, but ut's shared among views...

**Comment by jancavan** [comment]
@daniloercoli here are the icons with bg included:

![stats_icon_web](https://cloud.githubusercontent.com/assets/4924246/5984269/857f6c26-a889-11e4-9ff2-ee91e022d557.png)

![stats_icon_web](https://cloud.githubusercontent.com/assets/4924246/5984272/8bd4762a-a889-11e4-9536-56a7d944369f.png)

![stats_icon_web](https://cloud.githubusercontent.com/assets/4924246/5984275/92eb3c6e-a889-11e4-862c-9e89704be354.png)
