### ISSUE TITLE
File Download Stats being counted by usage in the app

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-Android#10653]
### Expected behavior

When I view a video in the app from my media library or preview it in a page in the app that view shouldn't count on my stats

### Actual behavior

My file download stats go up from work I do on my Android App

### Steps to reproduce the behavior

1. Add a video to your media library
2. Preview a page and play the video or watch the video after selecting it in your media library
3. Wait a bit and check your stats. The file downloads will have increased by at least 2.

##### Tested on Pixel 3, Android 10 , WPAndroid 13.4-rc-1

Reported by user in #2403740-zen

**Comment by designsimply** [comment]
Nice find! Tested and confirmed using WPAndroid 13.4-rc-1 on Pixel 3 Android 10. ([2m4s](https://cloudup.com/ckLBn2ZKOvR))

**Comment by designsimply** [comment]
Related: file download stats are also being triggered for videos in the editors, which explains what I saw in my test, tracking at https://github.com/wordpress-mobile/gutenberg-mobile/issues/1387.

<sup>/hat tip @cameronvoell </sup>

**Comment by chipsnyder** [comment]
Just leaving a note to confirm this is still happening. I ended up with 4 downloads after adding a video and viewing once in preview.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ravishanker** [comment]
`Preview` option on a post opens up in a WebView.  It is probably an API issue, not something to fix in the app.  

@irfano  Wdyt?



| Preview | WebView | Stats |
|--------|--------|--------|
|![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/7379fb81-13c7-43cb-93d1-7ead8008a0ac)|![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/48e67eef-b383-4711-9ced-7328ca2e0fcb)|![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/abd164b2-f064-4390-ac92-0018a3696045)|

**Comment by irfano** [comment]
This issue could have a similar root cause with https://github.com/wordpress-mobile/WordPress-Android/issues/10675. There are some discussions on that issue related to the authentication state of the web view. So, if we are sure there is nothing on our site. we can close both Android issues and open an issue for API.

**Comment by ravishanker** [comment]
See above. Probably no way to figure this out if they're not logged in on Mobile Web either!  May be preview needs to be opened in logged in state, to not count it.

**Comment by ravishanker** [comment]
It does [open with login-in creds](https://github.com/wordpress-mobile/WordPress-Android/blob/d8aceba97f8462af38acc0a57ec9fd4d260ff52b/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L1135)

**Comment by irfano** [comment]
> It does [open with login-in creds](https://github.com/wordpress-mobile/WordPress-Android/blob/d8aceba97f8462af38acc0a57ec9fd4d260ff52b/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L1135)

Thank you for finding it, @ravishanker. So, it makes sense to conclude that there is nothing that we can do on the mobile side.

**Comment by guarani** [comment]
👋 Do you have an API issue for this and https://github.com/wordpress-mobile/WordPress-Android/issues/10675#issuecomment-2038580033 @ravishanker?

**Comment by ravishanker** [comment]
Initially, it looked like an API issue. It probably belongs to gutenberg-mobile, and related issue exists there already. https://github.com/wordpress-mobile/gutenberg-mobile/issues/1387
