### ISSUE TITLE
Store the Realm in case of Basic HTTP Auth protected blogs

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#1066]
....and use it later before sending the HTTP credentials to the server.
See WPWebViewClient, and XML-RPC Client.

Also remember to compare the domain before sending the request to the server.

**Comment by rachelmcr** [comment]
I checked and it looks like this is still an issue, see: https://github.com/wordpress-mobile/WordPress-Android/blob/615d636bdc0063490b64cf0e344c5d4ac5e9a9bf/WordPress/src/main/java/org/wordpress/android/util/WPWebViewClient.java#L58

Is this still a medium priority issue?

**Comment by daniloercoli** [comment]
Not sure how many people is using this app on blogs protected with HTTP basic auth.
I think a very small percentage of our userbase. Anyway, it's a "small"? security issue that has been in the app since the night of time. Maybe it's the time to fix it? Or change the priority to low.

**Comment by rachelmcr** [comment]
I investigated but I don't think we track how many users use the app on blogs with HTTP basic auth. I'll change the priority to low for now, and we can revisit this when we have a chance.

**Comment by maxme** [comment]
Note that we store the realm in FluxC `HTTPAuthManager`, we could eventually use it in our Webviews in the future.
