### ISSUE TITLE
TypeCastException: null cannot be cast to non-null

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10676]
<img width="834" alt="Screenshot 2019-10-24 at 10 27 23" src="https://user-images.githubusercontent.com/2261188/67467355-e285ab80-f648-11e9-9c70-44b32020c122.png">

Similar issues: https://sentry.io/organizations/a8c/issues/1286493949/similar/?project=1438088

Steps to reproduce:
1. Clear app data
2. Login
3. Switch to a site with at least 40 published posts
4. Open post list
5. Scroll down as fast as you can

**Comment by designsimply** [comment]
**30-day impact:** ~100
**Users affected in the last 30 days:** 1700
**First seen in:** 13.4
**Last seen in:** 13.6-rc-2
<sup>https://sentry.io/share/issue/6adffdac9ed14adcb19bf55fbb84a3e9/</sup>

**Comment by khaykov** [comment]
I do believe this one is fixed in #10677
