### ISSUE TITLE
Can't use custom sizes for photo uploads as default

### ISSUE THREAD

**Issue by drgraff** [wordpress-mobile/WordPress-Android#1069]
There is a major drawback to the Android app that stops me from using it more:

- My blog columns are 480 pixels wide.  
- I want my photos to fill the column perfectly.  
- I'm only able to set 400 or 500 for the default.  I don't get the slider option (it used to be there)

Granted, I can get the slider option on the individual pictures in the post, but picking the right pixel width for each photo is annoying.  Putting the slider element in the default width selector would be much appreciated.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
