### ISSUE TITLE
[Proposal] Change system navigation bar to match UI

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-Android#10695]
### Expected behavior

I expected the system navigation bar (on the bottom of the screen) to adapt to the color of the UI, particularly the bottom navigation bar.

### Actual behavior

The system navigation bar is black by default, whereas our bottom navigation and UI in general is white or off-white. 

This tension is especially noticeable when you're using a device with rounded display corners where the navigation bar doesn't extend to account for the curvature – for example, when Gesture Navigation is turned on on a Pixel 4. Example:

![image](https://user-images.githubusercontent.com/1200432/67505274-8cb50180-f650-11e9-8d95-79a1346623fa.jpeg)

Note: This isn't as much a problem in "3-button Navigation" mode because the height of that variation extends beyond the curvature of the corners. But I'm guessing (?) if we apply a style to one variation, it applies to others as well.

### Proposed Solution

Simply changing the system navigation bar so it provides a black indicator on a white background (specifically in light theme – dark theme would need a white indicator on system dark background) would basically solve this. Here's what it would look like in various places in the app (current version on left, proposed on right).

My site:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/1200432/67516654-9cd7db80-f666-11e9-8645-f1faaf4e4cd8.png">

Editor:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/1200432/67516733-c264e500-f666-11e9-8053-b8b87a41b751.png">

Stats:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1200432/67516711-ba0caa00-f666-11e9-9336-5fe6f24d08ca.png">

Browser:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/1200432/67516755-cb55b680-f666-11e9-8553-385d999dfb12.png">

##### Tested on [device], Android [version], WPAndroid [version]

Issue might be universally relevant, but currently testing on: Pixel 4, Android 10, WPAndroid 13.4

**Comment by malinajirka** [comment]
Thanks for the detailed description @iamthomasbishop ! ;)

I've quickly tried to change the color to white and I noticed a couple of ui issues.

![nav-color](https://user-images.githubusercontent.com/2261188/67667540-563bf700-f96e-11e9-8163-fd1c7504bc2c.jpg)

- My Site screen looks good 👍 
- App Settings screen - the content background is grey, but the color of the nav bar is white and it looks a bit weird. Note: We could theoretically change the color of the nav bar based on the screen.
- Activity Log - the content background is white and the nav bar is also white, which is fine. However, notice how the text at the bottom of the screen gets cut off. Note: We could theoretically use transparent color and display the list items behind the nav bar.

I tried to change the color of the nav bar to our primary color. It fixes the issues, but I'll leave the decision whether it looks good form the design point of view to you. I'd personally vote for using it as we won't need to solve any issues screen by screen which is a huge win imo. Wdyt?

**Comment by iamthomasbishop** [comment]
@malinajirka Awesome, thanks for tackling this so quickly!

> App Settings screen - the content background is grey, but the color of the nav bar is white and it looks a bit weird. Note: We could theoretically change the color of the nav bar based on the screen.

Agreed with this screen – I think the white certainly looks _better_ than the current black, but maybe we should set some clear rules.

* If whole page background is gray (like on `App Settings`), use a gray background on navigation bar
* If there are mixed backrounds (like on `Activity Log`), use white background on navigation bar

> I tried to change the color of the nav bar to our primary color. It fixes both the original rounded corner issue and the ui issues mentioned above, but I'll leave the decision whether it looks good form the design pov to you.

While using the blue here is _slightly_ better, I think using it also suffers from the original concern. Honestly even using white on all scenarios (including `App Settings`) is a lot better, but ideally we'd blend it with the gray on full-gray backgrounds.

**Comment by malinajirka** [comment]
Thanks for the reply;). Just to make sure you have all the info for the decision.

> I think using it also suffers from the original concern.

I've tested it on my Pixel 3 with rounded corners and I believe it doesn't suffer from the original concern.

![Untitled](https://user-images.githubusercontent.com/2261188/67685565-9b275400-f995-11e9-990f-d0838cbdcb01.jpg)


>Honestly even using white on all scenarios (including App Settings) is a lot better, but ideally we'd blend it with the gray on full-gray backgrounds.

Tbh the "cut off" text seems like a bigger issue to me. I agree that using white on all screens is better than the black.

**Comment by iamthomasbishop** [comment]
I agree the blue is definitely better, but still doesn't feel quite right.

The text being cut off isn't as big of a concern for me because things being "cut off" are pretty normal in scroll-views. I think your suggestion for making the background semi-transparent would look nice – maybe white at 90-95% opacity?
