### ISSUE TITLE
Migrate Release Checks to Ruby

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-Android#10699]
We use `fastlane` to automate many aspects of our build tooling, and use our release toolkit to build reusable actions. However in a lot of cases, our lanes are just calling out to shell scripts that previously existed.

This has a couple of downsides:

1. These shell scripts tend to be tailored towards the project that they were built for. This can sometimes make them tricky to re-use elsewhere on other projects.
2. It makes the release toolkit more difficult for outside folks to use – some of the commands call hardcoded paths within the project with specific shell script names that may be inscrutable to other developers. Those developers may not understand where those live or why they're like that, and calling into the release toolkit, then having that call resources within the project is non-intuitive.

We'd like to improve on that.

---

To start with, we'd like to migrate [`release-checks.sh`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/tools/release-checks.sh) into the release toolkit. This script currently does several things:

1. It ensures that there are no languages that have reached greater than 90% translation, but are not yet included in the project. 
2. It ensures that `strings.xml` contains all of the strings from the project.
3. It prints the current version of Gradle to the log
4. It *should* run the test suite, but currently doesn't
5. If it does run the test suite, it *should* verify before attempting to start that there's an available device (or emulator) to test with.

The migration should accomplish the following objectives:

1. It should break the shell script into multiple actions.
2. Each new action should be reusable across multiple projects by providing an appropriate set of parameters.
3. The `WordPress-Android` project should be the first to take advantage of these new actions, and should have the shell script removed.

**For bonus points**, the implementation should be sufficiently abstracted so as not to rely on Automattic or WordPress-specific infrastructure (as a for-instance, not everyone uses GlotPress, so allowing for the possibility of other translation services would be beneficial, but is not required).

**Comment by ravenstewart** [comment]
Starting on this today. 🤩

**Comment by jkmassel** [comment]
This was done long ago
