### ISSUE TITLE
Accessibility: Reader Pull To Refresh

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#10733]
For Filters, I have realized that the Pull To Refresh functionality exists. Should a refresh button be placed on the menu for accessibility reasons since doing a refresh with swipes might be difficult?

So the Buffer team had a similar issue where they had a swipe interaction that would be difficult for users who are using accessibility features so what they did was they created a [different UI/UX for that interaction ](https://overflow.buffer.com/2018/09/05/announce-actions/) and in their case, this was a bottom sheet that's triggered once an `AccessibilityService` is enabled I think.
So in our case, adding a refresh button would be along the lines of this behaviour.

**Comment by shiki** [comment]
Sorry for the double post. I didn't see the new issue until after I commented. In https://github.com/wordpress-mobile/WordPress-Android/issues/10718#issuecomment-549954666, I mentioned that we don't need the refresh button. It's a good addition but I think it's a very low priority.

**Comment by jd-alexander** [comment]
Okay, I agree. Let's close this for now.
