### ISSUE TITLE
Localization: tickets from Indonesian users being assigned deprecated language code `in`

### ISSUE THREAD

**Issue by mahangu** [wordpress-mobile/WordPress-Android#10742]
### Expected behavior
The correct ISO 639-1 language code for Indonesian is `id`. Tickets from users with Indonesian set as their app language should show `id` in the `WP Mobile App Language` field in Zendesk.

### Actual behavior
Tickets from Indonesian-speaking WordPress for Android users are showing up in Zendesk with their `WP Mobile App Language` field incorrectly set to `in` (many thanks to @erricgunawan for confirming this). 

Therefore, `in` shows up as a language code in Zendesk reporting as well.

## Steps to reproduce
1) Run the following advanced search in ZD: `custom_field_360008583691:in form:"Mobile Support Form" group:wordpress.com order_by:created sort:asc`
2) Open any ticket and look at the `WP Mobile App Language` field on the sidebar
3) The field will be populated with `in` and not `id`, as it should be

The `WP Mobile App Language` field `(360008583691)`, along with some others, was added in #8161.

I also found this reference in this repo's source code about Java defaulting to the deprecated language code for Indonesian, so just linking it here too, in case it helps - https://github.com/wordpress-mobile/WordPress-Android/blob/50f98a16880a535af82c35f7a81c3c65e592fa9a/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java#L55-L58

Please let me know if you need any other information from me. Thank you for having a look!

**Comment by hafizrahman** [comment]
Looking. By the way, just want to add that we can test this from the user perspective by setting the Interface Language in the app to Indonesia, then sending message thru the contact form.
