### ISSUE TITLE
Feature request: Custom Taxonomies in mobile app (posts)

### ISSUE THREAD

**Issue by jaworowicz** [wordpress-mobile/WordPress-Android#10758]
### Expected behavior
Show custom taxonomies on settings post.

### Actual behavior
The application only allows you to configure tags and categories. 

### Steps to reproduce the behavior
Create/Edit post > Settings post

**Comment by designsimply** [comment]
It appears this is a long-standing request! I'd like to close this issue in favor of the one filed at https://github.com/wordpress-mobile/WordPress-Android/issues/63 and not your request there.
