### ISSUE TITLE
Tab Indicator View has Elevation on Login/Signup Prologue

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#10766]
### Expected
Tab indicator view has no elevation on login/signup prologue.

### Observed
Tab indicator view has elevation on login/signup prologue.  See the screenshots below for illustration.

![wordpress_prologue](https://user-images.githubusercontent.com/3827611/68496044-aa689600-020e-11ea-8ae8-416a0a972e63.png)

### Reproduced
1. Clear app data.
2. Launch app.
3. Notice tab indicator view has elevation/shadows.

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel 4|10.0|alpha-194

**Comment by designsimply** [comment]
I'm not seeing this in the 13.7 release from the Play Store.

<img src="https://user-images.githubusercontent.com/1119271/70193119-5e98f780-16bb-11ea-91d3-9e76bee37474.png" width="270" alt="Screenshot_20191204-172319">
<sup>Tested with WPAndroid 13.7 (official release) and 13.8-rc-1 on Pixel 3 Android 10.</sup>

**Comment by theck13** [comment]
I don't see it on the latest `develop`.  We can close it.
