### ISSUE TITLE
Navigation Bar Buttons Not Visible on Web Views

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#10765]
### Expected
Navigation buttons are visible (i.e. dark buttons on light background) on web views.

### Observed
Navigation buttons are not visible (i.e. light buttons on light background) on web views.  See the screenshots below for illustration.

![wordpress_navigation_bar](https://user-images.githubusercontent.com/3827611/68495809-33330200-020e-11ea-9bd7-239623cd4bd1.png)

### Reproduced
1. Go to ***Sites*** tab.
2. Tap ***View Site*** item under ***External*** section.
3. Notice navigation buttons are light on light background.

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel 4|10.0|alpha-194

**Comment by designsimply** [comment]
Thank you for the report!

This was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/10768. Props @malinajirka 🎉 and should already be available in 13.7 released on 2019-12-02.
