### ISSUE TITLE
Reader: Some YouTube videos can't play (only in app)

### ISSUE THREAD

**Issue by donalirl** [wordpress-mobile/WordPress-Android#10780]
Copied with slight modifications from https://github.com/wordpress-mobile/WordPress-iOS/issues/10693

### Expected behavior

I expect that if I can play an embedded YouTube video in the browser, I should be able to play it in the app Reader.

### Actual behavior

Some YouTube videos can be played in the app Reader. However, others behave as described:

>This post's embedded Youtube video works on the site in a browser, on both desktop and mobile, it works in the Reader when accessed from a browser, but not in the Reader within the app.

This is a video that won't play in the app Reader: https://www.youtube.com/watch?v=DT-yQgzN9ZM

### Steps to reproduce the behavior

1. Embed the problem video in a post.
2. Open that post in the browser Reader and play the video.
3. Open the same post in the app Reader and try to play the video.

Result: It shows the message "Video unavailable."

Internal ref: #2481671-zen

**Comment by malinajirka** [comment]
I've looked into this, but I wasn't able to figure it out. It seems YouTube prevents some video to be playable from embeds. However, I've encountered videos which are playable from a browser (which uses embeds as well) but the same video won't play from a webview. I'll try to ask some web devs if they have any tips.

**Comment by leandroalonso** [comment]
Some specific videos don't play in the apps — we're not sure if this is some different permission or any other thing. But there isn't much we can do about that (since a Youtube video is just an `iframe`)

Anyway, most of the videos play without any issues.

I'll close this one for now, if we start seeing that as a recurrent thing we can investigate it further.
