### ISSUE TITLE
Bug: Incorrect Timezone in Restore Revision Dialog

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#10786]
### Expected behavior

The Restore Revision dialog should display dates using the device timezone.

### Actual behavior

The Restore Revision dialog appears to be displaying dates in UTC/GMT-00:00.

### Steps to reproduce the behavior

1. On WordPress.com, create a new post or open an existing post for editing
2. Set the title and body with arbitrary text
3. Publish the post
4. Re-open the post and add a new line, “Two.” – then close the browser tab without saving (this creates an autosave revision)
5. On the Android app, navigate to the post list and observe the message "You've made unsaved changes to this post" on the newly created post
6. Tap the post and a dialog is shown - observe that both dates/times are displayed incorrectly (e.g. if the device is in UTC-03:00, and the save occurred at 09:50pm, the time is incorrectly shown as 12:50am of the following day)

<img src="https://user-images.githubusercontent.com/1898325/68723609-cfa32e80-0597-11ea-93d8-be39323d3982.png" width="400"/>

**Comment by guarani** [comment]
@malinajirka, just a heads up - this could be related to https://github.com/wordpress-mobile/WordPress-Android/issues/10108.

**Comment by malinajirka** [comment]
Thanks for the report @guarani! ;) I've fixed the issue in #10788 - it should be released in WPAndroid v13.7.
