### ISSUE TITLE
Can't change display name during signup

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#10835]
On the signup screen after email confirmation there are 3 fields: Display name, Username and Password

It's impossible to update the display name and the password at the same time (I'm not sure if it's a local check or an API limitation).

<img src="https://user-images.githubusercontent.com/40213/69410032-74e1a380-0d0a-11ea-8d7d-7a2a8f629f1d.png" width="270" alt="Screenshot_1574411160">

### Steps to reproduce the behavior

- Signup by email address in wpandroid
- Confirm email address, click in "Sign up to WordPress.com" in the received email.
- Update the display name, fill the password field and tap "Continue"
- Get the "The password setting cannot be changed at the same time as any other setting dialog. 💥

**Comment by renanferrari** [comment]
Is there any way to reproduce this behavior with a development build? 

I'm asking this because the [OAuth2 Authentication](https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication) section of the README states that:
> credentials created with our WordPress.com applications manager allow login only and not signup

**Comment by renanferrari** [comment]
So, here's what I found so far:

- This is definitely an API limitation.
- The iOS app seems to circuvent that limitation by [saving each field separately].(https://github.com/wordpress-mobile/WordPress-iOS/blob/a81baa590159495200af4b9eab329364dc80fcaf/WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift#L147-L184).

**Comment by renanferrari** [comment]
So, here's what I found so far:

- This is definitely an API limitation.
- The iOS app seems to circumvent that limitation by [saving each field separately](https://github.com/wordpress-mobile/WordPress-iOS/blob/a81baa590159495200af4b9eab329364dc80fcaf/WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift#L147-L184).

That being said, I think it's worth experimenting with a similar solution on `SignupEpilogueFragment`. I'm going to try doing that next.

**Comment by hypest** [comment]
> I traced back the problem to these lines where it adds a password field in the same action payload of a display name update.
I think you’re right in that assessment @renanferrari .

Apparently the API doesn't allow changing the password at the same time as other settings, so the password change will need its own network call.
