### ISSUE TITLE
Internationalization needed in MediaGalleryAdapter

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1083]
Check bindView in: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/src/org/wordpress/android/ui/media/MediaGalleryAdapter.java

There's strings like "Dimensions: " that need to be added to the strings.xml file to support internationalization.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
