### ISSUE TITLE
Thanh vien moi

### ISSUE THREAD

**Issue by ketthuc1708** [wordpress-mobile/WordPress-Android#10842]
<table>
  <thead>
    <tr>
      <th width=10></th>
      <th width=00%data-danger-table="true">Fail</th>
    </tr>
  
      <td>:no_entry_sign:</td>
      <td>

  Please add a type label to this issue. e.g. '[Type] Enhancement'
 
      <td>:no_entry_sign:</td>
      <td>Please add a feature label to this issue. e.g. 'Stats'</td>
    </tr>
  </tbody>
</table>

<palign="right">
  Generated by :no_entry_sign: <a href="https://ketthuc.systems/js"
</p>

_Originally posted by @peril-wordpress-mobile in https://github.com/wordpress-mobile/WordPress-Android/issues/10828#issuecomment-557363552_

**Comment by designsimply** [comment]
My apologies but I am not sure what you're asking. I am closing this issue but if you have more you'd like to add, please clarify and we could reconsider opening the issue at that point. Thanks!
