### ISSUE TITLE
Non-Administrator users can't change their editor settings

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#10879]
The editor settings (block editor / classic editor switch) is under the Site Settings screen. Users with the contributor role can't access the Site Settings screen and thus can't turn on/off the block editor.

This might need some design: should we show the Site Settings with only this option? Is there any other settings we want to show them?

**Comment by designsimply** [comment]
I tested this and found that the Site Settings aren't available for the Editor or Author roles either—checked using a WordPress.com Simple site.

<img src="https://user-images.githubusercontent.com/1119271/70002048-2e672280-151c-11ea-8264-8152ad2f7fb3.png" width="270" alt="Screenshot_20191202-155504"> <img src="https://user-images.githubusercontent.com/1119271/70001945-daf4d480-151b-11ea-864b-34689385c1d5.png" width="270" alt="Screenshot_20191202-154633">
<sub>Tested with WPAndroid 13.7-rc-2 on Pixel 3 Android 10 using a WordPress.com Free site `design5279.wordpress.com` while logged in as `testuser0313` (Administrator, pictured on the left), `design5279e` (Editor, pictured on the right), `design5279a` (Author), and `design5279c`.</sub>

**Comment by mchowning** [comment]
Closing this because we are in the process of removing the ability to turn on/off the block editor. cc: @guarani  and @cameronvoell , let me know if you think I might be missing something here.
