### ISSUE TITLE
Accessibility : Sign Up/ Login TalkBack Improvements

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#10896]
For this audit the governing principles are as follows ([inspired by a previous audit](https://github.com/wordpress-mobile/WordPress-Android/issues/7288))

- All the clickable elements should be marked as so.
- All nonactionable and decorative elements should be non-focusable.
- Relevant content should be grouped together.
- All important elements should be described through content description.

The changes that were made in https://github.com/wordpress-mobile/WordPress-Android/pull/7296 will be reviewed as insights from there might assist in the changes that are made in this iteration as the discovery continues.

The following is a list of opportunities to improve the accessibility of the Editor. 

### TalkBack Issues

*  Home Screen - Sign up and Login  
	* Onboarding welcome slider isn't accessible at all times. Content isn't read out loud swipes occur. 
	* It says "multi page view". There might be room for improvement here but that will need to be a discussion.

**Comment by jd-alexander** [comment]
> Onboarding welcome slider isn't accessible at all times. Content isn't read out loud swipes occur.

So it seems when you use the TalkBack swipe up then right to access the page navigation the focus functions appropriately but when you do swipes it doesn't. I guess this isn't something we should wrestle with since TalkBack actually provides instructions on how to navigate between the pages and once the user follows that then the built-in functionality to focus the viewpager's content on swipe kicks in.

**Comment by shiki** [comment]
> I guess this isn't something we should wrestle with since TalkBack provides instructions

I agree. Let's just leave it as it is right now. 🙂
