### ISSUE TITLE
[TalkBack] Empty screens are spoken with “Tap to save posts...“

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#10907]
## Expected behavior

Only the text should be spoken.

## Actual behavior

The extra unrelated text is spoken.

<img src="https://user-images.githubusercontent.com/198826/70181387-09e78380-169f-11ea-97ad-81f38904e1f6.png" width="320">

### Steps to reproduce the behavior

1. Navigate to Reader → Followed Sites
2. Tap on Search
3. Enter a very long text that should have no results
4. Turn on TackBack
5. Hover on the empty list

Tested on Pixel 3, Android 9.0, WPAndroid `develop` ()

---

FYI @jd-alexander 🙂

**Comment by jd-alexander** [comment]
Thanks for spotting this!
