### ISSUE TITLE
Add site switcher inside the editor

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10910]
Can we add the option to switch sites after starting a new post similar to how the iOS app does?

We received the following feedback:

> Hitting the new post button in-app opens the block editor for the site you had selected whenever on the Sites tab and no way to change.

The iOS app has this functionality:

<img src="https://user-images.githubusercontent.com/1119271/70264101-057da200-1755-11ea-87f4-5f702ff80bc0.PNG" width="270" alt="IMG_3179"> <img src="https://user-images.githubusercontent.com/1119271/70264102-057da200-1755-11ea-9297-dd83c5c82b32.PNG" width="270" alt="IMG_3180">
<sup>Tested with WPiOS 13.8.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

Also see https://github.com/wordpress-mobile/WordPress-iOS/issues/13041 where we requested analytics to see how often that feature is used in the iOS app.

<sub>(internal reference: p4k3M4-2BP-p2#comment-2106 cc @kraftbj @hypest)</sub>

**Comment by maxme** [comment]
I'm closing this issue - We'll remove the site switcher from the editor in iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/14744
