### ISSUE TITLE
Groundskeeping (Android) Master Issue: December 9-13

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/WordPress-Android#10912]
### Description

This is what I'll be working on during my groundskeeping rotation.

### Project Issues

* #10505 "NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable..."
* #10951 "Comments: per-post comments disabled even though allowing comments is enabled globally"

**Comment by mchowning** [comment]
## "NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable..."
Investigated this, determined the root cause, and am currently soliciting feedback on possible approaches. I'll implement a fix as soon as I feel there's some consensus on the best approach.

## "Comments: per-post comments disabled even though allowing comments is enabled globally"
Investigated this, but was unable to recreate the issue. Also did not see anything concerning in the api requests or code around leaving comments. Left a [comment](https://github.com/wordpress-mobile/WordPress-Android/issues/10951#issuecomment-566761751) on the issue. 🥁  Maybe someone else will have better luck. 😞

**Comment by designsimply** [comment]
Thank you for your work during the 9-13 Dec maintenance rotation!
