### ISSUE TITLE
Application stops responding if you rotate the device while selecting an image to upload

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10920]
Steps to reproduce:

1. Add and image block.
1. Rotate the device.
1. Tap "Choose image from device".
1. Rotate the device.
1. Tap to select an image.

**Result:** the application stops responding. ([18s](https://cloudup.com/c8PnDcrAOpb))

 <img src="https://user-images.githubusercontent.com/1119271/70370520-758b4580-1885-11ea-929d-7e1a15f5709d.png" width="270" alt="anr">
<sup>Tested with WPAndroid 13.8-rc-1 on Pixel 3 Android 10.</sup>

**Comment by planarvoid** [comment]
I reproduced this on debug version with following Gutenberg crash. I'm changing the type of this issue to `gutenberg-mobile`. Do you think someone from the GB team could look into it @mkevins? Thanks!
![Screenshot_1575883938](https://user-images.githubusercontent.com/1079756/70424172-34568980-1a6f-11ea-903e-89e4423dc987.png)

**Comment by mkevins** [comment]
Hi @planarvoid :wave: 

I have also reproduced this, and I have confirmed it is related with [the double-rotation crash](https://github.com/wordpress-mobile/WordPress-Android/issues/10227). I have also confirmed that the approach used to address that crash (in this draft PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10383) also fixes this issue.

**Comment by cameronvoell** [comment]
Should be fixed now that https://github.com/wordpress-mobile/WordPress-Android/pull/10383 is merged.
