### ISSUE TITLE
Login: The Email Address error is not preserved once the screen is rotated

### ISSUE THREAD

**Issue by yesunch** [wordpress-mobile/WordPress-Android#10930]
### Expected behavior

When writing the email in a wrong format error message appears. When rotating the screen the message should be preserved.

### Actual behavior

When rotating the screen the message is not preserved.

### Steps to reproduce the behavior
1. Press Log In
2. Enter Email address and press Next. An error message will be shown
3. Rotate the screen. The message is not shown anymore

##### Tested on Samsung S10, Android 9, WPAndroid 13.7
![WP-login-issue](https://user-images.githubusercontent.com/39059254/70522031-a3e87980-1b40-11ea-92f5-fdf24a22fb60.gif)

**Comment by jd-alexander** [comment]
Behavior here is similar to this [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/10361) so a fix could be applied to both.

**Comment by FernandaCG** [comment]
Hi! can I work on this?

**Comment by jd-alexander** [comment]
@FernandaCG Sure! definitely can!

**Comment by FernandaCG** [comment]
Hi! Can you check if my solution solve both issues? :D

**Comment by FernandaCG** [comment]
Hi @jd-alexander, any update?

**Comment by jd-alexander** [comment]
Hi @FernandaCG I will have a look soon!

**Comment by namanrana16** [comment]
Hey, Can I work on this issue?

**Comment by jd-alexander** [comment]
Hi @namanrana16 Thank you for your interest in contributing to WordPress Android! This issue was already resolved in https://github.com/wordpress-mobile/WordPress-Android/pull/11537 so I will be closing this!
