### ISSUE TITLE
Activity Log: activity icon does not need to be read aloud

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10935]
Steps to reproduce:

1. Go to Settings > Accessibility > TalkBack > "Use service" or use the [Volume key shortcut](https://support.google.com/accessibility/android/answer/6006966?hl=en).
1. In the WordPress app, go to My Site > Activity.
1. Swipe right to read through several items in the log.

**Result:** the activity icon is read aloud as "activity log" for each item which is repetitive and doesn't add value. Ideally, the type of item would be read first then the title and the icon would not be read aloud at all. ([1m13s](https://cloudup.com/c-k99Sg3B_i))

<img src="https://user-images.githubusercontent.com/1119271/70562635-072ad980-1b4a-11ea-9c84-7de23db6c143.png" width="270" alt="talkback-activity-icon-wpandroid-13 8-rc-1">
<sup>Tested with WPAndroid 13.8-rc-1 on Pixel 3 Android 10.</sup>

<p style="clear:both;"><sub>/hat tip @mchowning for the report, internal reference: p77Llu-c0a-p2</sub></p>

**Comment by jclement92** [comment]
Hi, I would like to work on this issue.

**Comment by jd-alexander** [comment]
Hi @jclement92 You can assign it to yourself and definitely have a go 😄 Let me know if you need any help with anything 🙏

**Comment by jclement92** [comment]
Awesome! How do I assign it to myself? I haven't committed to this repository before

**Comment by jd-alexander** [comment]
I just did it for you @jclement92 😎

**Comment by A-L-Fearon** [comment]
Hey @jclement92 are you still working on this ?

**Comment by jclement92** [comment]
Unfortunately, I am not

**Comment by A-L-Fearon** [comment]
I would like to take a crack at it then

**Comment by jclement92** [comment]
Go for it @A-L-Fearon
