### ISSUE TITLE
Editing async images

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-Android#10982]
The Media Editor should be able to accept async images. This will cover some cases like:

* Images that we just have a small thumbnail and need to download the full quality image
* Image assets that come from the device and we need to fetch the full quality image

## Acceptance criteria

1. Given an async image
2. We start to fetch a high-quality image
3. And show the thumbnail with a loading indicator
 
.

1. Given an async image
2. Once the high-quality image is available
3. We show the editing capabilities with the given image

## Design

![async_image](https://user-images.githubusercontent.com/7040243/70330737-e8140b00-181c-11ea-8346-8655d5c2bd1a.png)

* This activity indicator will probably change
* The crop buttons will not be displayed, only the Cancel
* We need to adapt this design to Android

**Comment by leandroalonso** [comment]
@ashiagr @malinajirka Since there are more atomic cards created on this issue, I think we might close this one. What do you think?

**Comment by malinajirka** [comment]
Yep, agree thanks!
