### ISSUE TITLE
Site Creation - domain suggestions are being cut off

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11008]
### Expected behavior
The domain suggestions aren't cut off.

### Actual behavior
The domain suggestions are being cut off.
![Screenshot_1577087981](https://user-images.githubusercontent.com/2261188/71359314-55010200-258c-11ea-84f0-a1650c5016d7.png)

### Steps to reproduce the behavior
1. My Site
2. Switch Site
3. + sign button
4. Create WordPress.com site
5. Choose a type
6. Skip
7. Skip
8. Type a long domain name into the search box

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, Android 9
cc @jd-alexander I think we've introduced this with the "domain unavailable" PR.

**Comment by jd-alexander** [comment]
I will have a look!
