### ISSUE TITLE
Comments Seemingly Disappear After Post is Restored from Trash

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#11026]
### Expected behavior

I expected the entirety of a post's content, including its comments, to be retained after restoring it from the trash folder.

### Actual behavior

Comments seemingly disappear after restoring a post from the trash folder in either app. They're not viewable on their original post or in the admin's area's **Comments** section.

### Steps to reproduce the behavior

* Navigate to <em>My Site</em> > <em>Blog Posts</em> and tap <strong>Trash</strong> alongside any post that has comments.
* Next, tap the <strong>Trashed</strong> filter in the app and choose the option to <strong>Move to Draft</strong>, you can then <strong>Publish</strong> the draft. 
* View the post to verify that it no longer has any comments and also check the admin area's <strong>Comments</strong> section. You may need to clear the cache first. The comments won't appear in either the app or the web.

If I chose the <strong>Restore</strong> option immediately after trashing a post from either app, so that it was restored as a published post rather than a draft, then the comments were retained. I was also unable to replicate the above in Calypso, where there isn't an option to restore a trashed post as a draft. <strong>Move to Draft</strong> appears to be the key option causing issues here.

I wonder whether the underlying problem here could be related to <a href="https://github.com/Automattic/jetpack/issues/11313#issuecomment-475486547">this open GH report</a> about comments being trashed if there are too many status changes in a short amount of time.

I note that the comments still appear for approval from the notifications tab.

iOS version of report: https://github.com/wordpress-mobile/WordPress-iOS/issues/13160

##### Tested on Pixel 3, Android 10, WPAndroid beta

**Comment by designsimply** [comment]
Moving to the Prioritized Android list due to potential data loss in the scenario presented.

**Comment by enejb** [comment]
Just wanted to make a note that this should be fixed now on the api side. So I am closing this PR. 

The changes will be shipped with Jetpack sites (atomic) in version 9.2
