### ISSUE TITLE
Free Photo library crashes in Debug build

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11041]
### Expected behavior
The app doesn't crash when I select an image in the Free Photo library.

### Actual behavior
The app crashes as soon as I select an image in the Free Photo Library

### Steps to reproduce the behavior
1. Create a new post
2. Add a new image
3. Select "Choose from Free Photo Library"
4. Type "cat" into the search box
5. Select an image and notice the app crashes

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, API 28

@jd-alexander Could you please look into this issue as it seems related to the recent accessibility changes. Thanks

**Comment by jd-alexander** [comment]
Thanks! I didn't get this during testing for some reason. Looked into it and found it nonetheless 👍
