### ISSUE TITLE
SearchView does not extend to the whole length of Toolbar

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#11043]
### Expected behavior
Ideally, the expanded SearchView in the toolbar should cover it's whole available width.

### Actual behavior
Looks like expanded SearchView has a minimum width, which looks a bit weird on big devices, or in landscape mode:
[![Image from Gyazo](https://i.gyazo.com/cdf1d4178b3640f0318c7a64c53771fb.png)](https://gyazo.com/cdf1d4178b3640f0318c7a64c53771fb)

Looking at the potential solutions, we might want to provide a custom layout for SearchView with minWidth set to some large number.

**Comment by hafizrahman** [comment]
I'll take a look at this.
