### ISSUE TITLE
Textview or layout visibility not being set 

### ISSUE THREAD

**Issue by Diogo-Menezes** [wordpress-mobile/WordPress-Android#11055]
### Expected behavior
The text view that says "What would you like to find?" In the reader list fragment after clicking on the search icon. Should be set to gone after restart or the layout should be reloaded as previously. See screenshot.

### Actual behavior
The text is still visible overlapping the below text as seen in the screenshot.

### Steps to reproduce the behavior
Click on the search icon send the app to background, open the app again.
Or in configuration change.. Change from portrait to landscape causes the behavior too.

#### Tested on [device], Android [version], WPAndroid [version]
Xiaomi mi5, Android 8.0.0 , version 13.9-rc-2

## Screenshot

<img src="https://user-images.githubusercontent.com/57217107/71929854-d4045600-319a-11ea-9eee-c514684ffb18.png" width="270" alt="Screenshot_2020-01-07-21-48-09-820_org wordpress android">

**Comment by designsimply** [comment]
I tested and I could see this bug happen but only from the Discover stream in the Reader. ([55s](https://cloudup.com/cgxvcodjTb1))

@Diogo-Menezes does this problem happen for you in any other area besides Reader > Discover?

Here are the steps I used for testing:

1. Go to Reader in the app.
1. Note that you are in the Followed Sites stream.
1. Tap the search icon at top right.
1. Rotate the device then rotate back.
1. Check to see if the "What would you like to find?" text overlaps other content.
1. Go to Reader > My Likes and repeat steps 3 to 5.
1. Go to Reader > tag and repeat steps 3 to 5.
1. Go to Reader > Saved posts and repeat steps 3 to 5.
1. Go to Reader > Discover and repeat steps 3 to 5.

**Result:** the "What would you like to find?" text overlaps other content if you open the search interface in the Reader while on the Discover stream and then rotate the device or background and resurface the app.

<img src="https://user-images.githubusercontent.com/1119271/72085761-df0ed180-32d3-11ea-908d-3ed7cef175cf.png" width="270" alt="Screenshot_20200109-112924">
<sup>Tested with WPAndroid 13.9-rc-2 on Pixel 3 Android 10.</sup>

**Comment by Diogo-Menezes** [comment]
@designsimply at that moment I only saw this with the discovery selected like in your video. 
Other areas that included a search looked like they were working normal.

**Comment by designsimply** [comment]
Fixed in #11097. Props @Diogo-Menezes. 🎉
