### ISSUE TITLE
Post History: No network error for self-hosted (while online)

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11061]
If I visit the History page for a self-hosted post, I get a "No network available" error when I am actually online:

![Screenshot_1578525087](https://user-images.githubusercontent.com/662023/72024116-a83cab00-3242-11ea-941d-1aaf050beb69.png)

**Comment by designsimply** [comment]
I tested but couldn't find the History option for a post on a self hosted site. ([1m29s](https://cloudup.com/cO4uJH7DKu8))
<sup>Tested with WPAndroid 14.0-rc-2 on Pixel 3 Android 10.</sup>

Is this possibly something only happening in `develop`?

**Comment by oguzkocer** [comment]
@designsimply It looks like this only happens if the self-hosted site is connected to Jetpack. Here are the steps to reproduce this issue:

* Add a site that's connected to Jetpack through "Add self-hosted site" (this can be done with the + button from the site picker or from the login screen)
* Open a post in the editor
* Tap on the "⋮" icon and select "History"

I'll be opening a PR for this shortly.
