### ISSUE TITLE
Generated excerpts show gallery captions without spacing between the captions making them hard to read

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#11063]
### Expected behavior
The generated excerpt for a post with a gallery block as the first content shouldn't display captions at all or there should be spaces between each caption so the excerpt is more readable.

### Actual behavior
Excerpt is shown without spaces between each caption.

![gallery_block_test](https://user-images.githubusercontent.com/1405144/72068794-de922d00-330b-11ea-9fce-f2675e77a404.png)

### Steps to reproduce the behavior

- Add a new post using the block editor.
- Add a gallery block as the first content in the post.
- Add captions for each photo in the gallery.
- Go to My Sites > Blog Posts and look at the generated excerpt.

##### Tested on Pixel3a, Android 10, WPAndroid 13.9-rc-2

This issue was created on iOS. Please see reference to the issue here:
[wordpress-mobile/WordPress-iOS/issues/13154](https://github.com/wordpress-mobile/WordPress-iOS/issues/13154)

**Comment by BElluu** [comment]
Hello. Can I take care of this task?

**Comment by yaelirub** [comment]
@BElluu  thank you so much for offering to tackle this task! I unfortunately missed your comment here and so we ended up fixing it. 

If there is any other task you'd like to work on please let us know 🙏🏻
