### ISSUE TITLE
Cannot remove Jetpack sites from the Site Picker even though the option is given to Remove site

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11087]
Steps to reproduce:

1. Start by adding a Jetpack and a self-hosted site to the app.
1. Go to My Site > Switch Site.
1. Long-press on the Jetpack site from step 1.
1. When you see the "Remove site" prompt, tap "YES."
1. Long-press on the self-hosted site from step 1.
1. When you see the "Remove site" prompt, tap "YES."
1. Pull to refresh the site picker screen.

**Result:** Jetpack sites appear to get removed if you long-press and select "YES" to remove site but they are not actually removed. Self-hosted sites are removed as expected. ([1m6s](https://cloudup.com/cjKRPE9Ruut))

<img src="https://user-images.githubusercontent.com/1119271/72441280-b478b900-37aa-11ea-80d2-c80f43b8c1f1.png" width="270" alt="410-error"> <img src="https://user-images.githubusercontent.com/1119271/72441278-b478b900-37aa-11ea-88f2-ae09bbf56065.png" width="270" alt="remove-site">
<sup>Tested with WPAndroid 14.0-rc-1 on Pixel 3 Android 10.</sup>

**Comment by oguzkocer** [comment]
Closed by #11099.
