### ISSUE TITLE
Accessibility : My Site Menu Icons Issue

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11115]
<img src="https://user-images.githubusercontent.com/1509205/72758603-3862e480-3ba1-11ea-9431-e2b165e5ef63.png" width="320">

### Expected behavior
The entire layout of the icon and the text beneath should focus as one and be read aloud. 

### Actual behavior
The icon and text beneath are two different views and the icon is read as "Unlabelled,Button". 

### Steps to reproduce the behavior
1. Turn TalkBack on. 
2. Go to "My Site". 
3. Select Stats icon. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by designsimply** [comment]
@jd-alexander it seems this is covered by https://github.com/wordpress-mobile/WordPress-Android/issues/10828? If you agree, can you choose one issue to keep open and close the other with a `[Status] Duplicate` label?

**Comment by jd-alexander** [comment]
Thanks for spotting this! @designsimply
