### ISSUE TITLE
Scroll to a page after leaving the editor

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11132]
When the user eg. publishes a page draft, they are redirected back to the "Draft" tab. However, the page they just edited disappears (it's moved to the "Published" tab). If they manually go to "Published" tab, the page might not be visible at the top as pages are ordered alphabetically. 
Goal of this task is to automatically change the tab and scroll to the page after the user leaves the editor.

**Comment by designsimply** [comment]
This would be lovely to update. ❤️
