### ISSUE TITLE
Search only displays latest posts

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#11165]
### Expected behavior

I would expect that when I search for a post through the app for the Blog List, all posts would display.

### Actual behavior

Only the most recent posts will be listed, making it difficult to find specific posts you are wanting to edit.

### Steps to reproduce the behavior

The user reports browsing his posts from a browser and noticing issues that need to be updated in older posts. He goes to the app to search for the post (as it's not possible to select the option to 'edit in app when viewing the site in a browser), but some of the older posts do not come up in the search. 

The blog in question has over 5000 posts, so this can be quite inconvenient. 
Site in question:: https://blog.solignani.it/

##### Tested on Note 10 Plus, Android 9, WPAndroid 13.8 (at the time this was published it was the latest app)

Reported in forums: https://android.forums.wordpress.org/topic/how-many-old-post-are-searched?replies=3 A set of logs is available from within the forum thread.

**Comment by malinajirka** [comment]
cc @oguzkocer

**Comment by oguzkocer** [comment]
This should be fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/11098 and will be available when `14.1` ships.
