### ISSUE TITLE
When sharing images the button "Add to media library" is blank

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-Android#11173]
### Expected behavior
The button above "Add to new post" should be populated with the text "Add to media library"

### Actual behavior

<img width=300 src="https://user-images.githubusercontent.com/3384451/73100750-31e3ae00-3ebc-11ea-83f5-572e63d07dd2.png">

### Steps to reproduce the behavior

- Go to Photos and Videos on your device (outside of WP)
- Find proper image/video
- Click on the share button and choose WPAndroid
- WPAndroid will open and image/video 

##### Tested on [device], Android [version], WPAndroid [version]
Tested on Pixel 3a, API 29, while validating https://github.com/wordpress-mobile/WordPress-Android/pull/11121

**Comment by antonis** [comment]
Run into this issue while searching/testing another bug and this seems not to be reproducible with the latest versions of the app. Please reopen if that is not the case.
![device-2022-02-14-103646](https://user-images.githubusercontent.com/304044/153828737-b79841ae-5dd9-438a-ada3-a50ba6225d0b.png)
