### ISSUE TITLE
Sharing an external resource to Gutenberg doesn't work

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11187]
### Expected behavior
When I share an image or text/url from another app to WPAndroid and I choose "Share to new post", the resources is added to the post content.

### Actual behavior
When I share an image or text/url from another app to WPAndroid and I choose "Share to new post", the app is opened with an empty post.

### Steps to reproduce the behavior
1. Open browser
2. Select an url and click on share
3. Choose the WPAndroid app
4. Select a blog and click on "New Post"
5. Notice the post is empty

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, Pixel 2, Api 28

**Comment by malinajirka** [comment]
I've investigated this issue, but I can't find the problem. It seems the state of the PostModel in EditPostRepository is correct, but Gutenberg isn't showing the content. Perhaps, an issue with [this invocation](https://github.com/wordpress-mobile/WordPress-Android/blob/762866abdfc69ad69653b46f3162d59d0fd0be44/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2393). @mkevins Could you or someone from your team please look into this issue. It seems like a breaking change and we've received negative comments on GP.
I still think it might be related to the EditPostActivity refactoring, but I wasn't able to find the issue and the state on the WPAndroid side of things seems correct.

**Comment by sarahfg** [comment]
Issue was reproduced by a user in #2663327-zen

**Comment by malinajirka** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11121.
