### ISSUE TITLE
[GlobalStep] The feature to change the Profile Photo does not function

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11196]
### Description
When the user attempts to change the Profile Photo, after selecting or taking a new photo the application returns to the profile screen but the Profile Photo remains unchanged.

### Reproduction Rate
4/4 100%

### Expected behavior
The Profile Photo should update to the selected photo.

### Actual behavior
The Profile Photo remains unchanged.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Me” button on the top right of the screen.
4. Press “Change Photo”.
5. Select an existent photo or take a new one.
##### Tested on the following
Samsung Galaxy S6 (7.0)
Samsung Galxay S7 (6.0.1)

#### Please see the attached video for more information
[AndroidProfilePhoto.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4133838/AndroidProfilePhoto.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid 14.1-rc-1 on Pixel 3 Android 10. ([9s](https://cloudup.com/cWtr1KXtPcr))

<img src="https://user-images.githubusercontent.com/1119271/73519835-527d9d80-43bf-11ea-9ed1-96d84959f905.png" width="270" alt="change-photo">

**Comment by rachelmcr** [comment]
I confirmed this is resolved by https://github.com/wordpress-mobile/WordPress-Android/pull/11207 in the 14.1-rc-2 release.
