### ISSUE TITLE
[GlobalStep] The Share options aren’t displayed when in a Blog Post’s Preview

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11199]
### Description
While the “Share this” section is displayed as expected when viewing a post through the Reader, when previewing a blog post, those share options are not displayed.

### Reproduction Rate
4/4 100%

### Expected behavior
The “Share this” section should be displayed when previewing a post.

### Actual behavior
The “Share this” section is omitted when previewing a post.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press “Posts”.
4. Press “View” on a post.
##### Tested on the following
Samsung Galaxy S6 (7.0)
Samsung Galxay S7 (6.0.1)

#### Expected Behavior (iOS)
<img width="270" src="https://user-images.githubusercontent.com/60415523/73451321-4661f380-435f-11ea-864f-d40bc748833b.jpg" />

#### Actual Behavior (Android)
<img width="270" src="https://user-images.githubusercontent.com/60415523/73451323-4661f380-435f-11ea-86ee-9594321900e1.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Thank you for the report! Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/9649 which I believe covers this case.
