### ISSUE TITLE
[GlobalStep] Flickr videos are displayed as a blank space

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11208]
### Description
Utilizing shortcodes to add a Flickr video to a post causes it to be displayed as a blank space due to lack of Adobe Flash support.

### Reproduction Rate
4/4 100%

### Expected behavior
An error message should be displayed.

### Actual behavior
A blank space is displayed.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add a Flickr video, the following example can be used:
```
[flickr video=2402990826] 
```
##### Tested on the following
Samsung Galaxy Tab S2 9.7” (7.0)

#### Post’s content
<img width="270" src="https://user-images.githubusercontent.com/60415523/73531776-17a55500-4413-11ea-9ecd-ca1c1cc6ba57.png" />

#### Post’s View
<img width="270" src="https://user-images.githubusercontent.com/60415523/73531777-17a55500-4413-11ea-88c9-27855f763e40.jpg" />

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue was seen to still occur on WordPress 4.2

Luis Pimenta

**Comment by chipsnyder** [comment]
This seems to be the same as the issue mentioned on iOS https://github.com/wordpress-mobile/WordPress-iOS/issues/13335#issuecomment-809621753
