### ISSUE TITLE
[GlobalStep] Pressing “Play on SoundCloud” on a block with an invalid SoundCloud URL displays a blank page

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11210]
### Description
Pressing “Play on SoundCloud” on a block with an invalid SoundCloud URL displays a blank page without any error message.

### Reproduction Rate
4/4 100%

### Expected behavior
There should be an error message stating the SoundCloud URL is invalid.

### Actual behavior
Pressing the “Play on SoundCloud” button causes a blank page to appear.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add the shortcode for a SoundCloud with an invalid SoundCloud link, the following example can be used:
```
[soundcloud url=”https://soundcloud.com/claude-de-lune”] 
```
##### Tested on the following
Huawei P30 Pro (9.0)

#### Please see the attached video for more information
[AndroidInvalidSoundCloud.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4139390/AndroidInvalidSoundCloud.zip)

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue was seen to still occur on WordPress 4.2

Luis Pimenta

**Comment by chipsnyder** [comment]
Closing this would be something handled in [Jetpack](https://github.com/Automattic/jetpack) as part of the [Soundcloud](https://wordpress.com/support/soundcloud-audio-player/) shortcode
