### ISSUE TITLE
[GlobalStep] The button for the Cardboard Viewer causes the UI to disappear

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11214]
### Description
Pressing the button for the Cardboard Viewer functionality causes the UI of the 360 Photo viewer to disappear and, consequently, the user can no longer rotate the photo.

### Reproduction Rate
4/4 100%

### Expected behavior
The screen for the Cardboard Viewer should be displayed.

### Actual behavior
The 360 Photo viewer becomes locked and its UI disappears.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add the shortcode for a 360 photo, the following example can be used:
```
[vr url=https://en-support.files.wordpress.com/2016/12/vr-shortcode-360.jpg view=360]
```
7. Publish that post.
8. View that post.
9. Press the Cardboard Viewer button.
##### Tested on the following
Huawei P30 Pro (9.0)

#### Please see the attached video for more information
[Android360CardboardViewer.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4140153/Android360CardboardViewer.zip)

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue has been retested today using the Samsung Galaxy S7 (7.0) on WordPress 14.2-rc-1
And is still seen to occur.
- O Howe

**Comment by chipsnyder** [comment]
I'm also getting this issue on the web so I believe this is an issue that needs to be ported to [Jetpack](https://github.com/Automattic/jetpack).
