### ISSUE TITLE
Refactor Post Upload Status to support Pages

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11233]
While working on #11127 we realized that the logic for getting the upload status for a post doesn't support pages in an efficient manner. Meaning, it needs a whole `PostModel` to be passed. In a PR attempt to implement the progress state on the Page List, the respective post/page was being fetched when the upload status changes but this isn't efficient and might [cause a performance impact](https://github.com/wordpress-mobile/WordPress-Android/pull/11191#discussion_r374558140). So we need to find another solution which involves refactoring classes that simply need a `post id` or creating a component specific to pages.

**Comment by malinajirka** [comment]
AFAIK this issue will be fixed in https://github.com/wordpress-mobile/WordPress-Android/issues/11271. We won't load the model from database and we'll interact with the model which we already have, right?  If I'm not missing something, please feel free to close this issue @jd-alexander . Thanks!
