### ISSUE TITLE
Media: Media may not load with Jetpack connection even when it works on other clients

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#11249]
### Expected behavior

In the Media section, all the site's media should appear and you should be able to preview it when selecting any media item.

### Actual behavior

A user reported that they can’t see their media in the Android app only when logged in with their WordPress.com account. All files give the error: “Media could not be found”

These are the place they CAN see media:

- in the iOS app
- at /wp-admin/uploads on the same device
- at WordPress.com/media on the same device
- in the app on the same device when they log in by site address

What the user has tried:

- Turning off security plugins
- Uninstalling/reinstalling the app
- Logging in and out again
- Whitelisting Jetpack’s IP ranges in `fail2ban`

App logs suggest that the media is fetched without any issues:

```
67 - [Dec-27 09:04 API] Dispatching action: MediaAction-FETCH_MEDIA_LIST
68 - [Dec-27 09:04 API] Dispatching action: SiteAction-FETCH_SITE
69 - [Dec-27 09:04 API] Dispatching action: SiteAction-UPDATE_SITE
70 - [Dec-27 09:04 DB] Site found by (local) ID: 1
71 - [Dec-27 09:04 DB] Updating site: [REDACTED]
72 - [Dec-27 09:04 MEDIA] Fetched media list for site with size: 48
73 - [Dec-27 09:04 API] Dispatching action: MediaAction-FETCHED_MEDIA_LIST
```

Given that their media library loads as expected over XML-RPC (when they are logged in to the app via the site address) and it loads as expected on other clients (iOS, Calypso) via the Jetpack connection / when logged in to a WordPress.com account, I would expect it to work that way in the Android app.

We haven't been able to reproduce this issue on another site, but this merits investigation because it seems like the Android app must be handling the media for Jetpack sites differently from other clients, in a way that makes this issue possible.

User report: 2550066-zen
Discussion: p4a5px-2u0-p2

**Comment by develric** [comment]
Quick comment to share that the difference in iOS and Android app is in how we manage Photon accelerated JetPack powered sites where in iOS we append in the query parameters `ssl=1` with https sites while we are not doing it in Android.

Not sure if I'm missing something more up to date but also looking into this comment and the linked documentation here `p1hpg7-fh-p2/#comment-2979` it seems that `ssl=1` is not documented. 

I was able to successfully use it anyway with a jurassic ninja test site (that was working also without that parameter set) and with the user site (that was not working with that parameter set with Android app). It seems like it is possible to make images available only over ssl but not sure how (maybe someone more knowledgeable than me on WP/JetPack setup or API can share some more insights on this).

I will open a PR to further elaborate on the above (cc @rachelmcr)
