### ISSUE TITLE
Bottom sheet animation glitch when app comes from background.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#11242]
As part of the Information Architecture project we are adding a filter to select different streams of posts in the reader. The filter is implemented with a bottom sheet and the main PR is [this one](https://github.com/wordpress-mobile/WordPress-Android/pull/11193).

During review the following issue has been noticed (see [here](https://github.com/wordpress-mobile/WordPress-Android/pull/11193#pullrequestreview-353506061) for more context)

### Expected behavior
When the bottom sheet is opened and you bring the app to background and then to foreground again you should see the bottom sheet not animating but stay as it was before to go into background.

### Actual behavior
When the bottom sheet is opened and you bring the app to background and then to foreground again you see the bottom sheet animating and sliding from bottom to bring to it's previous position.

### Steps to reproduce the behavior
1. Click on "Filter"
2. Press Home button
3. Bring the app back to foreground
4. Notice the animation glitch

NOTE: this same behavior affects the bottom sheet of the main FAB in My Site and should be addressed there also.

##### Tested on [emu Pixel 3], Android [API 28], WPAndroid [14.1 zalpha]

**Comment by develric** [comment]
This is still an issue (tested with current develop 16.1-rc-1 on Pixel 3 Emu API 28), so leaving it opened but removing it from IA GH Project that is not currently active. 

NOTE: on API 29 it seems the issue is not present at least for me.

**Comment by daniloercoli** [comment]
Cannot reproduce the issue with version 22.4 of the Jetpack app.
