### ISSUE TITLE
Unable to Change Profile Photo

### ISSUE THREAD

**Issue by sarahfg** [wordpress-mobile/WordPress-Android#11248]
### Expected behavior
1. Go to Me
2. Tap Change Photo
3. Select a photo
4. Tap the check mark next to "Use this photo:"
5. WordPress.com profile picture updates to the selected photo on both the app and WordPress.com in a browser

### Actual behavior
The selection area for the photo disappears, but your account profile photo stays the same on both app and WordPress.com in a browser.

##### Reported on Samsung Galaxy J3 Orbit, WPAndroid 14

#2694449-zen

**Comment by rezzap** [comment]
Another report of this here: 2694579-zen

WPAndroid 14
Android device name: Samsung SM-N950U

**Comment by sarahfg** [comment]
This will be corrected in an upcoming release of the app: https://github.com/wordpress-mobile/WordPress-Android/pull/11207
