### ISSUE TITLE
Offline Support : Pages - PageListEventListener uploadStatus not cleared on error

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11265]
### Expected behavior
When an update is being made on a post and an error occurs the `ProgressState` should be updated to reflect this. 

### Actual behavior
This should be invoked whether an error has took place or not since it will update the status.
https://github.com/wordpress-mobile/WordPress-Android/blob/1adbfd718608a7d15290d70f73f6bb788b5b6912/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListEventListener.kt#L102
At the moment, the invocation only occurs if the event doesn't have an error. 

Similar behavior in `PostListEventListener`
https://github.com/wordpress-mobile/WordPress-Android/blob/be1eff3ff6af9dbd60a79e83364f533e4b4c13a4/WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt#L125

### Steps to reproduce the behavior
1. Update/Upload a post.
2. Create some form of error by manipulating the environment eg. disabling the internet during an upload.

**Comment by malinajirka** [comment]
Does it have any impact on the UX? Eg. is the progress bar still shown when an error occurs?
