### ISSUE TITLE
Offline Support - Pages : Add PostModel reference to PageModel

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11271]
### Expected behavior
The `PostModel` for each page should be available across [PagesViewModel](https://github.com/wordpress-mobile/WordPress-Android/blob/59778060ca0dd6b716ba60ea8a727fa6a0d4137c/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt) and [PagesListViewModel](https://github.com/wordpress-mobile/WordPress-Android/blob/2f8c4efb962da6c91f2dfe85fbdb93d0f877eab0/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt) so that functionality and components that need to be shared between the `Pages` and `Posts` can be done in an efficient manner since the APIs would contain `PostModel` as a parameter in some cases. 

### Actual behavior
Currently, `PageModel` is being used to create the UI and behavior for the Page List functionality. It's created by mapping a `PostModel` to its properties. The issue with this approach is that this model worked for the current implementation but when further details of the post are needed for certain APIs or functionality a call has to be made to the `PostStore` which isn't performant in many cases. 

### Steps to reproduce the behavior
There are several related issues where `PostModel` fetching is affecting performance and at times causing `NullPointers` such as https://github.com/wordpress-mobile/WordPress-Android/issues/11233 , https://github.com/wordpress-mobile/WordPress-Android/issues/11260 , https://github.com/wordpress-mobile/WordPress-Android/pull/11266

**Comment by malinajirka** [comment]
We originally planned to remove PageModel and use PostModel everywhere. However, as it turned out this change wouldn't be as straightforward as we hoped. For example the PageModel has reference to its parent. Parent-child concept isn't supported by regular posts so it's doesn't sound like a good idea to add `parent` field to PostModel. We opted for adding PostModel field to PageModel.
