### ISSUE TITLE
Self-hosted sites ignore w= attribute resulting in full resolution image display

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#11276]
### Expected behavior
Self-hosted sites should display smaller images inside the app that can load faster similar to wordpress.com sites. 

### Actual behavior
Resized image url generated for self-hosted sites contains width attribute `w=`but such sites ignore the attribute, therefore the image gets loaded in full resolution.

Issue was noticed while generating low resolution image urls in the media editing project. For more details see this comment [#11142 (comment)](https://github.com/wordpress-mobile/WordPress-Android/pull/11222#pullrequestreview-355898900). It exists at other places in the app as well, like for featured image on the post list.

**Comment by jkmassel** [comment]
.org sites don't use photon, so there's no way to fix this.
