### ISSUE TITLE
[GlobalStep] When selecting the overflow icon, the cursor will jump back to the title.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11286]
### Description
While editing or creating a post with block editor off on Android, when the user selects the overflow icon for more text formatting options, the cursor will always jump back up to the title line.

### Reproduction Rate
4/4 100%

### Expected behavior
The cursor should remain on the line the user has selected.

### Actual behavior
The cursor jumps back to the title line.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. In settings ensure block editor is disabled.
4. Press the “Add new” button.
5. Select the blog post option.
6. Place some text in multiple lines
7. With the cursor on the last line of text select the overflow icon.

##### Tested on the following
Huawei P10 (7.0)

### Submitted by:
Oliver Howe

[cursor_jump_android.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4192066/cursor_jump_android.zip)

**Comment by jhnstn** [comment]
I am unable to reproduce with WPAndroid 17.0-rc-2 on a Pixel 5.

I don't see an overflow icon in the text formatting toolbar. Instead I am able to scroll the toolbar to reveal items that are off screen
