### ISSUE TITLE
[GlobalStep] Sharing media displays an inaccurate error despite the post being successful

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11297]
### Description
When sharing media from another application the error message “1 file not uploaded There was an error uploading the media in this post: We couldn’t complete this action.” is displayed despite the post being successful.
The message has been seen to specifically state “1 file not uploaded” even when several files are uploaded.

### Reproduction Rate
4/4 100%

### Expected behavior
No error message should be displayed.

### Actual behavior
The aforementioned error message is displayed despite the successful post.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Open a media browser like Google Photos.
4. Select several photos.
5. Press the Share button.
6. Select WordPress.
7. Press “Add to new post”.
8. Press Publish.
9. Select Publish Now.
##### Tested on the following
Google Pixel C (8.1.0)

#### Please see the attached video and log for more information
[ShareMediaError.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4198258/ShareMediaError.zip)
[ShareMediaErrorLog.txt](https://github.com/wordpress-mobile/WordPress-Android/files/4198259/ShareMediaErrorLog.txt)

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment]
I do see that there were some actual media upload errors in the logs and at least one post published around this time that did not have successful media uploads: https://madefortesting9845.wordpress.com/2020/02/13/438/

The post was successfully published but there is an image in that post has a reference to a local image: `<img class="wp-image-56" src="///data/user/0/org.wordpress.android/cache/wp-1581595745665.jpg" alt="" />`

It would be helpful to know:

* When this happens, if you check the post on another device does the image appear in the post?
* Does the error message appear repeatedly even after media uploads are working again?

**Comment by designsimply** [comment]
I tested with WPAndroid 14.2-rc-2 on Pixel 3 Android 10 and image uploads worked normally for me. Very interested in any info that could lead to reliable steps to reproduce the problem. Also interested to know if it happens if you try testing it again after some time has passed.

**Comment by jhnstn** [comment]
I was unable to reproduce with WPAndroid 17.0-rc-2 on a Pixel 5.

I was able to trigger a failure when trying to share a RAW image file from Google Photos. In that case the notifications look correct since the image did not have a valid MIME type

**Comment by mchowning** [comment]
Should we close this issue since we don't seem to be able to reproduce it? We can obviously reopen it later if we want.
