### ISSUE TITLE
Pages hierarchy is displayed as flat

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11294]
### Expected behavior
I'm not sure what the expected ordering is. But I believe we always want to show pages in the hierarchy (parent-children) mode.

### Actual behavior
When I open page list, the pages hierarchy is either shown as flat or it appears as expected but is automatically reordered into a flat list within +-2s.

### Steps to reproduce the behavior
1. My Site
2. Open Site Pages
3. Wait 3 s
4. Repeate steps 1-3 until the error occurs

![pages-ordering](https://user-images.githubusercontent.com/2261188/74422887-a1abdf80-4e4f-11ea-9dba-0a94b41dcdea.gif)

##### Tested on [device], Android [version], WPAndroid [version]
Emulator Pixel 3a, develop as of 13th of February 2020

**Comment by planarvoid** [comment]
@elibud I forgot to remove my assignment. I didn't get to it during my groundskeeping. Doing that now

**Comment by frosty** [comment]
@planarvoid We'll need to fix this one next sprint, so I'll re-assign you 👍

**Comment by frosty** [comment]
I was unable to recreate this myself, but after talking to @malinajirka it seems like it's easiest to reproduce with a site that has a lot of pages. It happens almost every time on his primary testing site.

**Comment by planarvoid** [comment]
hey @malinajirka, I couldn't reproduce it either. We're actually showing the flat hierarchy when there is more than a 100 pages on a site. This was a request from the testers. I was wondering if it's possible your site has > 100 published pages? 

I still don't know why it's first displayed as a hierarchy and changed to the flat view later but I can investigate it only if I can reproduce it so please let me know about your page count. Thanks!

**Comment by malinajirka** [comment]
Hi there,

>I was wondering if it's possible your site has > 100 published pages?

Yes, I can confirm my site has more than 100pages. However, the re-ordering animation still seems like a bug. Having said that I think it seems like a low priority bug.

I've found some interesting additional info
- When I keep opening the page list it's sometimes opened with "Zzzzzzzzzzyr" as first post and sometimes with "(Untitled)" as first post.
<img src="https://user-images.githubusercontent.com/2261188/85366967-a6348300-b528-11ea-9e73-cafb7eecddd5.gif" width="200px" />


- when it's opened with "Zzzzzzzzzzyr" (correct behavior) - everything seems to work as expected

- when it's opened with "(Untitled)" and I wait for all pages to get re-fteched cca (3-5s), the issue happens
<img src="https://user-images.githubusercontent.com/2261188/85367037-c401e800-b528-11ea-8b90-7e8e1ed3bdd3.gif" width="200px" />

**Comment by frosty** [comment]
Thanks for looking into this, both. @planarvoid, can you remember the reason testers wanted the list flattened for large numbers of pages?

**Comment by planarvoid** [comment]
hey @frosty , yep. It's because they wanted to find their latest page fast when looking into the pages list. The flat hierarchy is ordered by latest first. This is the calypso issue https://github.com/Automattic/wp-calypso/pull/13871 matched in this WPAndroid issue - https://github.com/wordpress-mobile/WordPress-Android/issues/10440. The PR is linked there.
I think there is an issue there @malinajirka, my guess is it's linked to the coroutine threading and live data but I'd have to look into it. The structure is quite complicated.

**Comment by frosty** [comment]
Thanks for checking into this, @planarvoid. I think it makes sense that we're matching Calypso behaviour there. It would be good for us to get to the bottom of the reordering issue 👍
