### ISSUE TITLE
Add a Dark Theme

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#113]
A user requested that the app have a dark theme instead of the current holo lite theme:
​http://android.forums.wordpress.org/topic/switch-themes-feature?replies=1

**Comment by magnus2lin** [comment]
Hi, we're thinking of starting to work on this. Do you have any procedures or advice to give as a starting point?

**Comment by rachelmcr** [comment]
A user requested a night (dark) theme in a recent app review:

> No night mode? This app is so bright it hurts

Another user requested a dark theme in 109376-h:

> Please add a amoled friendly true black theme to the app.

Noting these user requests here so we can track the frequency.

If N includes a [system switch for night mode/dark themes](http://www.androidcentral.com/night-mode-back-and-we-hope-its-here-stay) that would be preferred over a setting in the app. (p4a5px-1kH-p2)

**Comment by maxme** [comment]
We got another request for a dark theme.

> If N includes a system switch for night mode/dark themes that would be preferred over a setting in the app. (p4a5px-1kH-p2)

Night mode in Android 7.0 is a sadly a blue light filter (tint the whole screen orange) like [flu.x](https://justgetflux.com/).

So a Dark Theme is unrelated to that.

**Comment by rachelmcr** [comment]
We have another request for this in an app review:

> Night mode feature, please!
> I hope you add this feature to let the night bloggers like me write and edit their posts.

(This user is on Android 5.1 so they also don't have access to night mode in Android 7.0.)

**Comment by rachelmcr** [comment]
Another app review (4 stars) mentioned wanting a night mode:

> It would be great if there was a 'night mode' as well.

**Comment by rachelmcr** [comment]
Another app review requested night mode:

> Something I'd like would be a "night mode" to write comfortably with the lights off!

**Comment by sabret00the** [comment]
This app just hurt my eyes. It definitely needs a night mode.

**Comment by sarahblackstock** [comment]
A user downgraded a 5-star review to 1-star due to lack of night mode.

**Comment by sarahblackstock** [comment]
User (who loves the app and wants to use it as their main writing app) has sent feedback requesting night mode: 

>But to create in the evening, in a room with a guest light and a cup of hot cocoa, with your application, is difficult. Righteous light pouring from the tablet, with the running "WordPress", burns the tired eyes of the day, and you have to climb into the settings to reduce the flame of the fire screen. (translated from Russian)

#231391-h

**Comment by sarahblackstock** [comment]
From a 4-star review: 

> A great app for blogging. Would even be better if you could change the background theme to night mode.

**Comment by sarahblackstock** [comment]
Request for night mode in support.

internal ref: #26398-h

**Comment by SiobhyB** [comment]
We got a 1-star review with the following message: 

> No Nightmode.

**Comment by SiobhyB** [comment]
From a 4 star review:

> Nice work! But it needs a dark theme.

**Comment by SiobhyB** [comment]
From a 1 star review:

> Will you ever think of the dark theme... 😔

**Comment by SiobhyB** [comment]
From a four star review:

> Very good, stable and solid, however, lacks a dark theme, so please fix it. Then there will be a five directly

**Comment by SiobhyB** [comment]
From a five star review:

> Please add dark mode for the app

**Comment by SiobhyB** [comment]
From a four star review:

> Dark theme. I had a client of this app on BlackBerry 10 with a dark theme, perfect for working at night. Please take this into account for future updates.

**Comment by SiobhyB** [comment]
From another four star review:

> Wordpress is almost fully functional with a clean interface. The only thing I miss is a dark subject. All in all, a great job.

**Comment by SiobhyB** [comment]
From a three star review:

> It'd be much better off if you introduced dark theme.

**Comment by SiobhyB** [comment]
From a three star review: 

> When are you going to have Dark Mode??

**Comment by SiobhyB** [comment]
From a one star review:

> Dark theme?

**Comment by SiobhyB** [comment]
From a three star review:

> It really needs a dark theme to read at nights

**Comment by SiobhyB** [comment]
From a four star review:

> Please, a dark theme to enjoy reading

**Comment by thehenrybyrd** [comment]
From a four star review:
> Great app. Can we get a dark theme soon?

**Comment by melindahelt** [comment]
From a three star review:

> There should be a night reading mode, change the font size. The App also has restrictions on finding the chapters of the poster, sometimes I find the post others have already posted on the app without it but on google it appears.

**Comment by sarahfg** [comment]
Requested in #2429470-zen

**Comment by khaykov** [comment]
We are actively working on implementing the Dark Theme, so if necessary it's OK to mention it.

**Comment by SiobhyB** [comment]
From a four star review:

> The app is excellent, just one thing. If youł could look into integrating dark mode on it that would be great. The white is straining on the eyes

I'll mention it's being actively worked on. :)

**Comment by erricgunawan** [comment]
From a three star review:

> there is still no dark theme

I mentioned it's being actively worked on.

**Comment by designsimply** [comment]
Dark Theme shipped in WPAndroid 14.6 https://github.com/wordpress-mobile/WordPress-Android/pull/11580 and was released to the Play Store on 2020-04-20. Props @khaykov. 🎉

Please update people who have asked about this if you can. 🙏
