### ISSUE TITLE
[GlobalStep] The wrong icon is used when a Password is visible

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11307]
### Description
While when a Password is hidden the icon of an eye with a slash is displayed, when the user presses that button so the Password becomes visible the icon shown is the WordPress icon but the same eye without the slash should be displayed.
Besides the devices mentioned below, this issue was also tested on the LG G3 (5.0) but not seen to occur on this device.

### Reproduction Rate
4/4 100%

### Expected behavior
The eye icon should be displayed.

### Actual behavior
The WordPress icon is displayed.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Press the Log In button.
3. Type in a valid email address.
4. Select the “Enter your password instead” option.
5. Press the Eye button to make the password visible.
##### Tested on the following
Samsung Galaxy J3 (8.0.0)
Samsung Galaxy Tab S2 8.0" (7.0)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74526686-cec5c400-4f1b-11ea-9e1f-08bd7b75b9c4.jpg" />

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment]
I confirmed this also isn't an issue on my moto e5 play — I'm guessing it's Samsung-specific.

@marecar3 I see you worked recently (in https://github.com/wordpress-mobile/WordPress-Android/pull/11172) on the password visibility icon. Could you take a quick look and see if any ideas come to mind as to why this would happen?

**Comment by marecar3** [comment]
Hey @rachelmcr, 

Thanks for the update. This is very important feedback for us.
I will reference it in the main issue.

**Comment by marecar3** [comment]
Hey @rachelmcr @designsimply with a bit of luck I have found the root cause of this problem.
Here is the fix: https://github.com/wordpress-mobile/WordPress-Android/pull/11983
