### ISSUE TITLE
[GlobalStep] Tapping and holding on images in the profile picture album shows ‘Unable to load media’.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11314]
### Description
If the user goes on to the ‘Me’ profile section and selects the profile picture, when the album loads it is possible to tap and hold on an image which will always result in a black screen with the error ‘Unable to load media’.

### Reproduction Rate
4/4 100%

### Expected behavior
Tap and hold has a function or else can’t be done.

### Actual behavior
Tap and hold shows ‘Unable to load media’.

### Steps to reproduce the behaviour
1.	Install WordPress 14.2
2.	Login.
3.	Select the ‘Me’ profile icon.
4.	Tap the user profile picture.
5.	Tap and hold on an image in the album.

##### Tested on the following
Samsung Galaxy S2 8.0” (7.0)
LG G3 (5.0)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74546325-532b3d80-4f42-11ea-9fe9-ac6968bd1b18.png" />

### Submitted by:
Oliver Howe

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid 14.2-rc-2, 14.1, 14.0, 13.9, and 13.8 on Pixel 3 Android 10.
