### ISSUE TITLE
Posts duplication reading from Atomic sites

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#11350]
### Expected behavior
When looking at a list of posts taken from a single site stream you should get an entry for each post.

### Actual behavior
When looking at a list of posts taken from a single site stream it can happen you get two entries for each post.

### Steps to reproduce the behavior
I was able to reproduce it in the current develop (14.2) but also back until at least 13.2 and 13.0 versions. Currently was able to reproduce it only with Atomic sites (for example `https://fueledbylolz.com/`).

- Add an atomic site to follow if you do not have already  (for example `https://fueledbylolz.com/`)
- Go to reader > Followed Sites and check you get posts from the atomic site

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/74945295-c7a92500-53f7-11ea-88b7-1091ea69cf00.png">
</p>

- Tap on the title of a post to open the stream of that site posts

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/74945449-0e971a80-53f8-11ea-93bd-155cbac885b1.png">
</p>

- Tap on a post and start fast right swiping between 5 or 6 posts (not fully share the swipe part is necessary tbh)

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/74946098-14d9c680-53f9-11ea-9383-aebc43c9f592.png">
</p>

- Come back to the main reader and go to Reader Settings

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/74946195-3b97fd00-53f9-11ea-8500-a86310906aa3.png">
</p>

- Tap the followed site from there to open the the stream of that site posts again and wait few seconds. Bam the posts get duplicated

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/74946385-7ac64e00-53f9-11ea-84c6-2dd2aab56088.png">
</p>

- Strangely from this time on the posts of this atomic stream appears duplicated in the stream of this only site but not in the main stream in Following

| Main Following Stream (not duplicated posts | Single site stream (duplicated posts) |
|---|---|
| ![image](https://user-images.githubusercontent.com/47797566/74946885-430bd600-53fa-11ea-9b4a-3e38a03bc3e9.png) | ![image](https://user-images.githubusercontent.com/47797566/74946827-2bcce880-53fa-11ea-891f-69ab3dfc3d82.png) |

Not sure if it can be in some way related to this closed issue #4705

**Comment by ashiagr** [comment]
Duplicate issue.
Will be addressed in #12938.
