### ISSUE TITLE
Support flipped exif images

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1135]
When we resize an image, we don't support transpose/transverse/flipped modes:
See:
https://github.com/wordpress-mobile/WordPress-Android/blob/issue/1122-oom-bitmap/src/org/wordpress/android/util/ImageHelper.java#L105

And:
http://sylvana.net/jpegcrop/exif_orientation.html

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
