### ISSUE TITLE
Comments made using Gutenberg appears with big spacing between paragraphs

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-Android#11363]
### Details
Related Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/13507

### Expected behavior

The comment should have regular paragraph spacing.

### Actual behavior

The comment has huge spacing between the paragraphs.

<img src="https://user-images.githubusercontent.com/793774/75071053-63469e00-54a9-11ea-961f-1185087e5e44.png" width="50%" />

Note: The above screenshot has the content redacted. The gray boxes represent the text positions.

### Steps to reproduce the behavior

1. Create a comment using Gutenberg
2. Check the comment on the "Notifications" tab of the app

**Comment by emilylaguna** [comment]
Created this issue for visibility, this appears to be a server issue that is affecting both iOS and Android. 

More details here: https://github.com/wordpress-mobile/WordPress-iOS/issues/13507#issuecomment-589805444

**Comment by dmsnell** [comment]
Tracking in p9zg7s-5k-p2
