### ISSUE TITLE
Support for Uploading Multiple Images from a Device to Gallery Block

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#11367]
### Expected behavior

In Aztec, it's possible for users to upload multiple images from their device to the app by navigating to the post editor, tapping the + icon, then tapping all the images from their device that they'd like to upload.

As a lot of users are used to this workflow, I'd expect it to be possible for them to easily upload multiple photos from their device with Gutenberg, also. In particular, I'd expect it to be possible to select multiple images from your device using the Gallery block.

### Actual behavior

If Gutenberg's enabled, you're only able to upload one image from your device at a time. 

The Gallery block only allows you to choose images from your site's media library. It doesn't allow you to select images from your device.

To upload multiple images from your device, you'd need to follow these steps:

1. Tap the + icon in the post editor.
1. Choose the Image block to add that block to your post.
1. Tap the Image block then select the "choose from device" option.
1. Select the image you want to use from your device.
1. Repeat the above steps for every image you'd like to upload to the post.

This adds a lot of time and steps to a process that is relatively simple with the Aztec editor.  

This was reported in 2736092-zen, by a user who regularly uploads multiple images from their device at a time and who found that the switch to the block editor disrupted their workflow.

##### Tested on Pixel, WP Android alpha-209

iOS version: https://github.com/wordpress-mobile/WordPress-iOS/issues/13537

**Comment by SiobhyB** [comment]
Another request for this option in 2742571-zen. The user wants to upload images to a Gallery block while offline but is unable to as they can only choose from the site's media library.

**Comment by pinarol** [comment]
Image uploads were added to Gallery block with WP 14.3 https://github.com/wordpress-mobile/WordPress-Android/blob/ee8250c7608c016df0129d8cf557be4d0d56c022/RELEASE-NOTES.txt#L117
