### ISSUE TITLE
Low res(LR) image is saved to file on moving the app to background and bringing it back to foreground when images are loading

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#11377]
### Expected behavior
High res(HR) image should be saved to file on moving the app to background and bringing it to foreground again while images are loading. 

### Actual behavior
Low res(LR) image is saved to file on moving the app to background while LR image is loading and bringing the app to foreground after it is loaded but before HR image is loaded. 

For more details, see https://github.com/wordpress-mobile/WordPress-Android/pull/11376#issue-379506529.

### Steps to reproduce the behavior
1. Clear the app cache.
2. Open preview image screen from the Gutenberg editor so that LR image loading starts. 
3. Click device home button to move the app to background.
4. Wait for a while and bring the app to foreground from the recent apps list. 
5. Notice that LR image is saved in the cache.

**Comment by malinajirka** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11459
