### ISSUE TITLE
PostUtils. isMediaInGutenbergPostBody doesn't work for Video, MediaText and Gallery blocks

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11386]
As @mkevins [correctly pointed out](https://github.com/wordpress-mobile/WordPress-Android/pull/11378#issuecomment-591207678), PostUtils. isMediaInGutenbergPostBody doesn't take into account any other media block types but image block. 

An issue where image was uploaded with a local path was reported [here](https://github.com/wordpress-mobile/WordPress-Android/issues/10203#issuecomment-582346379) and fixed [here](https://github.com/wordpress-mobile/WordPress-Android/pull/11378). However, the PR fixed only one instance of the problem as it supports only an image block. Goal of this issue is to extend the regex in isMediaInGutenbergPostBody so it supports even other media block types.

Copy-pasting part of Matthew's comment as it might be useful:
`
the patterns in the processors here might be useful as reference: https://github.com/wordpress-mobile/WordPress-Android/tree/15996c7c2bc8656d2d63c421294a6efbe66b308b/WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors.
`

**Comment by oguzkocer** [comment]
Looks like this has been addressed in #11378.

**Comment by malinajirka** [comment]
The fix in #11378 fixed only regular image block. However we realized we need to take into account all media related blocks - gallery, video etc.
