### ISSUE TITLE
Rotate the device dismiss the keyboard while replying to a comment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1142]
Tested on Nexus 7 and Nexus 5

1. Go to the comment list
1. Tap a comment and start to write a reply
1. Rotate portrait to landscape or landscape to portrait
1. Keyboard is dismissed

**Comment by rachelmcr** [comment]
I tested this on Nexus 9, OS 6.0, app beta 4.8-rc-1 and confirmed that this is still an issue.
