### ISSUE TITLE
[Crash] AutoSavePostIfNotDraftUseCase is triggered more than once unexpectedly

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11439]
This crash is happening because `AutoSavePostIfNotDraftUseCase` is triggered for the same post more than once. Due to the way `PostUploadHandler` is setup, this should normally not happen.

Although seems like a stretch, this may be happening because we are removing the id from the continuations after we resume it [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/uploads/AutoSavePostIfNotDraftUseCase.kt#L140) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/uploads/AutoSavePostIfNotDraftUseCase.kt#L151). I don't really have any other ideas about why this might be happening.

@malinajirka Do you have any thoughts on that ^ or any other theories about this crash?

https://sentry.io/share/issue/9ee3b862c6ac45f781ff37a8b61165ae/

**Comment by malinajirka** [comment]
Hmm, this is an interesting issue.

>this may be happening because we are removing the id from the continuations after we resume it here and here. I don't really have any other ideas about why this might be happening.

I agree it's one possible explanation. Having said that, I'd be quite surprised if starting a new async task would be faster than removing an item from a HashMap. I'm wondering if it might be an issue with Thread/Cpu-cache 🤷‍♂.

Another possible explanation is that someone emits [`OnPostUploaded`](https://github.com/wordpress-mobile/WordPress-Android/blob/1268a78cab7f67c5dfa8f11ecc3d79b2fab0ba30/WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java#L644) -> which results in invocation of[ `finishUpload`](https://github.com/wordpress-mobile/WordPress-Android/blob/1268a78cab7f67c5dfa8f11ecc3d79b2fab0ba30/WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java#L185). AFAICT we don't check if the `OnPostUploaded` event is related to the event the PostUploadHandler is trying to upload. Perhaps it's an unrelated event from for example [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/e914246e87c7a3e8f5e4f466a0093a67a64f0da7/WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt#L162). 
1. PostUploadHandler invokes fetchPostStatus for post A
2. PushPostAction for post B is invoked somewhere else in the app
3. PushPostAction for post B completes and `OnPostUploaded` is emitted.
4. PostUploadHandler receives `OnPostUploaded` and starts uploading the next post in the queue even though it wasn't done with post A -> Boom.

Wdyt?

**Comment by oguzkocer** [comment]
@malinajirka That might be a more likely, good catch. We should be able to check if post uploaded is the one we were expecting and ignore it otherwise. I think we actually should do that regardless of the crash.

This is not a high priority issue, but I think in time the reports will build up. We currently have 11 crashes from 9 different people, so it'd be good to give this a try early before it builds up.

We also have a separate crash for the new autosave use case: https://sentry.io/share/issue/bdf49ac6f5bf45629aa41e2b988ddfa6/. It looks like it's unrelated to me, but I haven't had a chance to look into it yet. If you end up working on this, could you take a look at it and see if it's something we can address together?
