### ISSUE TITLE
Stats cards bounds cannot be seen on tablets when using the new material theme's background color

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#11468]
This issue was originally raised by @planarvoid [here](https://github.com/wordpress-mobile/WordPress-Android/pull/11432#issuecomment-599545387).

### Actual behavior
| Stats cards on `develop` | Stats cards on `material-theme` |
|---|---|
|![develop](https://user-images.githubusercontent.com/1079756/76764305-ddaacb00-6794-11ea-8cf6-b96419a7e67d.png)|![material-theme](https://user-images.githubusercontent.com/1079756/76764311-e0a5bb80-6794-11ea-89b4-8b5aebd07cea.png)|

### Expected behavior
@mattmiklic has provided a mockup of how this should like:

![Cards](https://user-images.githubusercontent.com/830056/77015901-f530b200-6954-11ea-8115-5c63aa0afd4a.png)

### Steps to reproduce the behavior

Using a build from the `material-theme` branch, open the stats screen on a tablet.

**Comment by oguzkocer** [comment]
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.6` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.5` branch which will be available later today and update the milestone for the issue accordingly.

**Comment by renanferrari** [comment]
Hi @oguzkocer! This issue should have been close automatically when the PR #11470 was merged. Not sure why it wasn't. I'm reverting the milestone change and closing it now.

**Comment by oguzkocer** [comment]
@renanferrari Auto-close will only work if the PR is targeting `develop`. https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
