### ISSUE TITLE
Offline Support : Pages -  Media upload progress not being displayed on Post List 

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11471]
### Expected behavior
Media upload progress is shown on Post List items. 

### Actual behavior
The media upload progress isn't shown at all. The local changes label remains until the upload is completed.

### Steps to reproduce the behavior
1. Check out `feature/master-pages-offline-support`
2. Go to My Site. 
3. Open Posts. 
4. Create a new post with media. 
5. Publish the post and then return to the Post List before the upload completes.
6. Notice that the determinate progress isn't being shown. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `feature/master-pages-offline-support` ()

**Comment by malinajirka** [comment]
Fixed
