### ISSUE TITLE
100 posts notification shows "<count>"

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#11499]
![Screenshot_20200318-141807](https://user-images.githubusercontent.com/3903757/77336718-4e566800-6cfe-11ea-9af2-c4bb7a2b6fde.png)

**Comment by dmsnell** [comment]
Not sure why this appeared only in Android. Are we sure it didn't appear in the other apps? If it _is_ localized to android then it's likely that we're rendering the image `alt` attribute when we shouldn't.

@roundhill did you write the notifications code in the Android app? Don't need you to fix it if it's broken, but might ask some questions…

**Comment by dmsnell** [comment]
removed from the backend in D40878-code

**Comment by roundhill** [comment]
🦆
