### ISSUE TITLE
Reader: Password-protected posts appear to site members in site feed but can't be viewed

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#11519]
### Expected behavior

I expect password-protected posts to always be excluded from the Reader, since they can't be viewed there.

### Actual behavior

As the owner of a site, when I view my site's feed in the Reader I can see password-protected posts in the feed:

Site Feed|Post Detail
-|-
<img src="https://user-images.githubusercontent.com/8658164/77439655-3c002b00-6ddf-11ea-81b2-25a70fb1bac0.png"> | <img src="https://user-images.githubusercontent.com/8658164/77439666-3e628500-6ddf-11ea-9577-e3d89611f878.png">

Other scenarios that work as expected:

* If I view the site feed (logged in as the same user) on the web, the password-protected post doesn't appear.
* If I am logged in as a user who isn't a member of the site and I view the site feed, the password-protected post doesn't appear.

### Steps to reproduce the behavior

1. Follow a site you own.
2. Publish a password-protected post on that site.
3. Confirm you don't see that post in your followed sites feed under Reader > Followed Sites.
4. View the site's Reader feed, e.g. by going to Reader > Following > Filter > Select the site.
5. Notice that the post appears in the list of posts in the site feed. Select the post to open the post detail.

##### Tested on [moto e5 play], Android [8.1.0], WPAndroid [alpha-213]

Related iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/13719

**Comment by ashiagr** [comment]
Closing with the same reason as in the linked iOS issue:

> given the lack of activity here and the fact that is not affecting users I'll go ahead and close the issue. We can reassess that decision anytime, of course.
