### ISSUE TITLE
Post+Page list: Rename Cancel action in collapsed view

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11515]
When the user edits a post/page and confirms the changes while offline, a label is displayed (eg. "We'll publish this post/page when your device is back online"). We also display a "Cancel" action on the item. The goal of this task is to rename the "Cancel" action in the collapsed view on Post List and regular view on Page List (we want to keep "cancel" on the expanded view on post list). 
We are not sure about the new text. One of the proposals is "Cancel publishing". However, I think we support the cancel action even when the user explicitly saves a draft in offline. In that scenario "cancel publishing" doesn't make sense.

**Comment by jd-alexander** [comment]
"Cancel Upload" won't work either? We could make the text contextual based on the action being performed since we want to be as clear as possible.

**Comment by malinajirka** [comment]
"Cancel Upload" would be definitely better. However, we'd still auto-save the post which is technically an upload. I'm not sure how much precise the text needs to be. Wdyt @osullivanchris ?

**Comment by osullivanchris** [comment]
Yeah I think that sounds good. Its a small detail so I don't mean to overcomplicate things. I also know that overflow menu is quite narrow, don't know if the width is dynamic to accommodate that string if its long in other languages. But if it can fit, I think go for it.
