### ISSUE TITLE
Add reblog functionality to Reader posts: Allow user to change site after reaching the editor

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#11538]
Master issue #10934

The user should be able to change the selected site with “spinner button” like action that reports the currently selected site title and allows to access the site picker.

**Comment by antonis** [comment]
The ability to change site can be added in the more actions menu of the editor when the user has more than one sites.

![device-2020-03-29-130359](https://user-images.githubusercontent.com/304044/77846450-ce794380-71be-11ea-9871-8908b24ae57b.png)

When the new option _Switch Site_ is triggered the site picker will be launched.
When a site is chosen the user will resume in the editor with the new site selection.

@osullivanchris, @develric Do you think the above solution would cover the requirement?

Also, should we leave this option open in the Editor even when triggered from other places (not reblog)?

**Comment by osullivanchris** [comment]
@antonis thanks for taking a look at this. I don't think we need to solve the site switching as part of this right now, as its a global question about the editor whether we want this functionality. 

I'm also unsure if the more menu would be the right place. I'd probably go with something closer to iOS if we are adding this - i.e. some indicator next to the site name that you can change site. 

But for now I think we should park it. Although it would be beneficial - 
- most users only have one site
- most of the time lets assume multi-site users will select the correct site to post to
- even if they choose the incorrect site, they can still achieve the switch by abandoning their draft and taking the reblog action again. Its not perfect. But I don't think its big enough to warrant this investment right now.

Hope thats ok, I believe @develric chatted to you a bit about it too. Let me know if you have any other thoughts. Thanks!

**Comment by designsimply** [comment]
iOS screenshots for reference:

Editor showing site selector|Select Site screen
---|---
<img src="https://user-images.githubusercontent.com/1119271/80819158-aef48280-8b91-11ea-8d34-6c3e52bb3cf4.PNG" width="200" alt="IMG_3970">|<img src="https://user-images.githubusercontent.com/1119271/80819165-b156dc80-8b91-11ea-9016-0383ad855bf7.PNG" width="200" alt="IMG_3971">

<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.3 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

Question: would this be better to file in https://github.com/wordpress-mobile/gutenberg-mobile/issues because the update would technically need to happen in the editor? 

cc @SergioEstevao (for triage help)

**Comment by osullivanchris** [comment]
> Question: would this be better to file in https://github.com/wordpress-mobile/gutenberg-mobile/issues because the update would technically need to happen in the editor?

Yes I think its a general editor issue, that's why I suggested against tackling it just for reblog. Have mentioned it to @iamthomasbishop as well. Feel we should either have it in both android and iOS, or neither. And make the decision for gutenberg editor going forward.

**Comment by iamthomasbishop** [comment]
> Question: would this be better to file in https://github.com/wordpress-mobile/gutenberg-mobile/issues because the update would technically need to happen in the editor?

While this does involve the editor, this is actually an Aztec component that is utilized by mobile Gutenberg. I agree with @osullivanchris that this should probably be aligned between platforms, and the Aztec repos ([Aztec-iOS](https://github.com/wordpress-mobile/AztecEditor-iOS), [Aztec-Android](https://github.com/wordpress-mobile/AztecEditor-Android)) are probably the right place for that work to be housed.

I also don’t think it’s a huge urgency, especially if we end up working on [edit/view modes](https://github.com/wordpress-mobile/gutenberg-mobile/issues/204) in GB in the near future. // cc @SergioEstevao @hypest

**Comment by hypest** [comment]
The post-wide menu that lives in the app-bar is actually owned by the main app and is shared between the block and classic editors. In particular, the editors are implemented such as the site itself is not information they need. In other words, the repo here (WPAndroid) is the proper one for this ticket.

> I also don’t think it’s a huge urgency, especially if we end up working on edit/view modes in GB in the near future.

Hmm, how's this feature related to the edit/view modes @iamthomasbishop ? In any case, I agree that it doesn't seem urgent to align the platforms on the "change site while in the editor" front just yet.

**Comment by iamthomasbishop** [comment]
> Hmm, how's this feature related to the edit/view modes @iamthomasbishop ?

@hypest I was assuming (maybe wrongly) that the logic for mode-switching would be housed in Aztec bc that's where all of the logic/mechanisms (save/autosave states, post settings, etc) currently exist. If that's not the case, disregard my comment 😄

**Comment by SergioEstevao** [comment]
It's like @hypest says, all the logic for site switching is on the main
apps, so this ticket should stay on the main app repos.

**Comment by osullivanchris** [comment]
That's really interesting, thanks for the context! I figured it was an editor thing. But understood now. I'll follow up with Thomas on this.

**Comment by hypest** [comment]
The site switcher has been removed from the apps ([from iOS here](https://github.com/wordpress-mobile/WordPress-iOS/issues/14744), wasn't there on Android anyway) so, should we perhaps close this ticket or should the editor screen start to offer it in this particular flow (reblog)?

**Comment by osullivanchris** [comment]
@hypest agree we should close the ticket. If we don't have it for the editor in general it seems unnecessary to have it for this one use case.
