### ISSUE TITLE
Add reblog functionality to Reader posts: Investigate error while fetching History revisions

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#11563]
Master issue #10934

When reblogging the following error occurs (detected in the logs).
```
An error occurred while fetching History revisions
```

Further investigation is needed on this.

REF: https://github.com/wordpress-mobile/WordPress-Android/pull/11540#pullrequestreview-384090625

**Comment by daniloercoli** [comment]
I tried reblogging posts from different feeds and didn't experience the problem. Since this is a fairly old ticket, I'll close it for now.
