### ISSUE TITLE
[GlobalStep] The screen to input the Login Password lacks basic features while in Landscape mode.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11610]
### Description
While Logging in using Landscape orientation, tapping the Password text box causes it do be displayed in Full Screen above the device’s keyboard. When the user inputs an invalid password, the “Logging in” popup can be seen for a brief moment before it disappears, and while the Incorrect password error message can be visible if the user dismisses the keyboard, this message is not immediately visible in the same screen the user types the password on.
Furthermore, it is not possible to view the already input password while in Landscape mode.
This issue is related to https://github.com/wordpress-mobile/WordPress-Android/issues/6364

### Reproduction Rate
4/4 100%

### Expected behaviour
The error messages prompted by a failed Login attempt should be visible and it should be possible to make the input password visible in Landscape mode.

### Actual behaviour
The error messages are not visible while the password text box remains selected and it is not possible to view the input password while in Landscape mode.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Tap “Log In” button.
3. Select the “Continue with WordPress.com” option.
4. Input a valid Email Address.
5. Press the “Next” button.
6. Select the option to “Enter your password instead.”.
7. Rotate the device to Landscape mode.
8. Tap the Password text box.
9. Insert an invalid Password and press “Done”.
##### Tested on the following
Samsung Galaxy S8+ (8.0)

#### Please see the attached video for more information
[AndroidLoginLandscape.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4449512/AndroidLoginLandscape.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Also see https://github.com/wordpress-mobile/gutenberg-mobile/issues/2089/.

**Comment by designsimply** [comment]
Labeled as low priority for now because we don't really have a design solution for this and because it will likely need to be incorporated into future project work, and also because users have an escape route by temporarily rotating back to portrait mode then back if needed.

Thank you for raising the issue!

**Comment by megsfulton** [comment]
Tested this in the latest alpha build with the new login flow and the issue appears to have been addressed. Closing for now.
