### ISSUE TITLE
Sharing intent receiver screen is not styled correctly in dark mode

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#11635]
This site list is also used in `LoginEpilogueFragment`. We apply special styling manually in `ShareIntentReceiverFragment`, and we will have to remove it, so the look will match one in `LoginEpilogueFragment`

![Screenshot_1586465900](https://user-images.githubusercontent.com/728822/78940105-2e4ad680-7a6a-11ea-8cbf-c3ad02a6e5b7.png)

**Comment by designsimply** [comment]
For reference: dropping by with a quick note to say this was also reported internally at p4a5px-2y3-p2. 👍
