### ISSUE TITLE
Dash is not translated correctly

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#11638]
@akirk  reported the issue where [the dash character `\u2014` in the block-editor popup](https://github.com/wordpress-mobile/WordPress-Android/blob/967f768ee03711590f9c556d81010952380849d6/WordPress/src/main/res/values/strings.xml#L373-L374) is not translated correctly via GlotPress and translators, leading to a stray `u2014` to appear on the UI. See screenshot:

<img src="https://user-images.githubusercontent.com/1032913/78992528-13e52b80-7b44-11ea-8623-90a1d5d4eb92.jpg" width=250)/>

Issue reported happening on Huawei P30, WordPress alpha-216, Android 10, build 10.0.0.190

**Comment by akirk** [comment]
Just wanted to add that this already is a problem in US English, thus not fully related to translation. As the screenshot shows, the `u2014` is actually being displayed.

**Comment by hypest** [comment]
> Just wanted to add that this already is a problem in US English, thus not fully related to translation. As the screenshot shows, the u2014 is actually being displayed.

Interesting. Is rendered as a dash on my Android 10 Pixel 2XL running WPAndroid from `develop`, hash 967f768ee0. @akirk , can you share the setup (device, Android version, app version) you're seeing the issue?

**Comment by akirk** [comment]
Huawei P30, WordPress alpha-216, Android 10, build 10.0.0.190

**Comment by akirk** [comment]
Turns out if you have English set as a language and Austria as a a region that our Android app will use `en-AU` as a language and not `en-US`. Maybe because of a close match of `en-AT`?
