### ISSUE TITLE
Reader: button block background doesn't display in Reader

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11679]
Steps to reproduce:

1. Create a new post.
1. Add a paragraph.
1. Add a button block.
1. Open the block settings.
1. Change the border radius.
1. Add a URL.
1. Toggle "Open in new tab" on.
1. Publish the post.
1. View the post in the Reader.
1. Compare how the post looks in the editor, preview, mobile web, and Reader.

**Result:** the button background color doesn't display in the Reader at all.

Editor | Block Settings | Editor Preview | Mobile Web | Reader in app 
--- | --- | --- | --- | ---
<img src="https://user-images.githubusercontent.com/1119271/79497878-ad4d8b00-7fe5-11ea-9bdc-a51a57ae85ba.png" width="200" alt="Screenshot_20200416-091416"> | <img src="https://user-images.githubusercontent.com/1119271/79497928-bdfe0100-7fe5-11ea-811c-9518b386a381.png" width="200" alt="Screenshot_20200416-091809"> | <img src="https://user-images.githubusercontent.com/1119271/79507932-d8d87180-7ff5-11ea-936d-6606fef14fc5.png" width="200" alt="Screenshot_20200416-091525"> | <img src="https://user-images.githubusercontent.com/1119271/79507945-dd9d2580-7ff5-11ea-9b7f-a28e185edb52.png" width="200" alt="Screenshot_20200416-091605"> | <img src="https://user-images.githubusercontent.com/1119271/79508082-189f5900-7ff6-11ea-850b-8df712e46a19.png" width="200" alt="Screenshot_20200416-091724">

<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 Dark Theme.</sup></p>

Note: the Button Block was shipped in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866 and it will become a component of the newer Buttons Block which is being worked on in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866 — noting it because the html is subject to change and we'll also want to re-test once the Buttons Block ships.

**Comment by ashiagr** [comment]
Fixed in Automattic/wp-calypso#43779

![device-2021-06-11-211341](https://user-images.githubusercontent.com/1405144/121713247-47ca3100-cafa-11eb-800c-35ecb95091a1.png)

To be noted: 
 > reader is opinionated on colours, so I haven't brought those over.
