### ISSUE TITLE
Reader: gallery blocks are displayed as a bulleted list of images

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11673]
Steps to reproduce:

1. Create a new post.
1. Add a gallery block and add several images.
1. Publish the post.
1. View the post in the Reader or Notifications.

**Result:** gallery blocks are displayed as a bulleted list of images instead of as a gallery.

Block Editor | Reader Cards in app | Reader Full Post in app
--- | --- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79399513-c9e3b780-7f40-11ea-93e0-5dd139863f9b.png" width="200" alt="Screenshot_20200415-131128"> | <img src="https://user-images.githubusercontent.com/1119271/79399525-cfd99880-7f40-11ea-8c4c-d439c6ed3d3c.png" width="200" alt="Screenshot_20200415-133700"> | <img src="https://user-images.githubusercontent.com/1119271/79399530-d405b600-7f40-11ea-8c79-c3213320f4a3.png" width="200" alt="Screenshot_20200415-133711">

Reader Cards Mobile Web | Reader Full Post Mobile Web
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79399463-a6b90800-7f40-11ea-8a97-87fcc57556da.png" width="200" alt="Screenshot_20200415-134110"> | <img src="https://user-images.githubusercontent.com/1119271/79399456-a3be1780-7f40-11ea-90cf-369484359ebe.png" width="200" alt="Screenshot_20200415-134124">
<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 in Dark Theme.</sup></p>

<p style="clear:both;"><sub>(internal reference: p4a5px-2wF-p2 h/t @elibud)</sub></p>

**Comment by designsimply** [comment]
It appears galleries were supported in Reader streams at one point (https://github.com/wordpress-mobile/WordPress-Android/pull/4316), and there are two major changes that possibly affected it: images are no longer attached to posts as a rule, the gallery block html code is quite different.

For reference, here is the source code for the gallery block from the post shown in the first set of screenshots in the original report in this issue.

```
<!-- wp:gallery {"ids":[878,886,880],"linkTo":"media"} -->
<figure class="wp-block-gallery columns-3 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><a href="https://madefortesting190318.files.wordpress.com/2020/04/pexels-photo-1629777.jpg"><img src="https://madefortesting190318.files.wordpress.com/2020/04/pexels-photo-1629777.jpg" data-id="878" class="wp-image-878"/></a></figure></li><li class="blocks-gallery-item"><figure><a href="https://madefortesting190318.files.wordpress.com/2020/04/pexels-photo-1629780.jpg"><img src="https://madefortesting190318.files.wordpress.com/2020/04/pexels-photo-1629780.jpg" data-id="886" class="wp-image-886"/></a></figure></li><li class="blocks-gallery-item"><figure><a href="https://madefortesting190318.files.wordpress.com/2020/04/pexels-photo-1629781.jpg"><img src="https://madefortesting190318.files.wordpress.com/2020/04/pexels-photo-1629781.jpg" data-id="880" class="wp-image-880"/></a></figure></li></ul></figure>
<!-- /wp:gallery -->
```

**Comment by malinajirka** [comment]
Thanks for finding the bug and also for finding the releated PR ;).

I think we'll need to manually modify `ReaderPostRenderer` so it supports the syntax of gallery blocks. Tbh I'm not fully convinced it's something we want to do. Since as the number of blocks increases we might find ourselves keep adding workarounds into the Reader. 

I'm wondering if inlining the css classes (replacing classes with inline styles) on the server would help. What do you think @maxme @hypest? Or do you have another idea how to solve this without manually handling specific types of blocks?

**Comment by maxme** [comment]
> I'm wondering if inlining the css classes (replacing classes with inline styles) on the server would help.

It's not going to work that way, Gutenberg and themes are using those classes.

> What do you think @maxme @hypest? Or do you have another idea how to solve this without manually handling specific types of blocks?

Can we take the styles from the web reader and reuse them in our apps reader? There is maybe a way to automate that part. I think the current supported styles live in [`ReaderPostRenderer`](https://github.com/wordpress-mobile/WordPress-Android/blob/31ef563ac86efeb9a78ccf914fa30a5fd4359f4e/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java)

**Comment by malinajirka** [comment]
>>I'm wondering if inlining the css classes (replacing classes with inline styles) on the server would help.

>It's not going to work that way, Gutenberg and themes are using those classes.

I meant replacing them just on the mobile-reader endpoint. Not on all the endpoints. 

>Can we take the styles from the web reader and reuse them in our apps reader? There is maybe a way to automate that part. I think the current supported styles live in ReaderPostRenderer

Yeah, we can keep update the renderer but it seems like we'll need to keep updating whenever a new block is introduced, right?

**Comment by maxme** [comment]
> I meant replacing them just on the mobile-reader endpoint. Not on all the endpoints.

Ok I see, this should work. Do you plan to do this replacement automatically? If not, we'll just move the problem to another place.

> we can keep update the renderer but it seems like we'll need to keep updating whenever a new block is introduced, right?

Yes and even when old blocks are modified, I agree this is not an ideal solution if we have to manually update that. Can't we reuse the same stylesheet which is used in Calypso for the Mobile Web version?

**Comment by malinajirka** [comment]
>Ok I see, this should work. Do you plan to do this replacement automatically? If not, we'll just move the problem to another place.

Yeah, I was thinking about automatic replacement. Essentially inline all the classes.

>Yes and even when old blocks are modified, I agree this is not an ideal solution if we have to manually update that. Can't we reuse the same stylesheet which is used in Calypso for the Mobile Web version?

We'll look into that ;).


Thanks for the discussion ;)!

**Comment by leandroalonso** [comment]
Updating the mobile-reader endpoint seems great, @malinajirka. 

Once we do that I'll have to double-check the iOS behavior — since we render the content there natively. Hoppefuly we won't need any additional change, but who knows.

**Comment by designsimply** [comment]
So much better! 😍 I'm adding in a few Reader detail screenshots of galleries after the update to have for reference. 

Reader detail gallery block:

<img src="https://user-images.githubusercontent.com/1119271/86489912-f37fd400-bd22-11ea-84e8-aa3c8ddac02c.png" width="24%" alt="Screenshot_20200703-113158"> <img src="https://user-images.githubusercontent.com/1119271/86489915-f4186a80-bd22-11ea-8731-82012bd18ac4.png" width="24%" alt="Screenshot_20200703-114510"> <img src="https://user-images.githubusercontent.com/1119271/86489916-f4b10100-bd22-11ea-86fe-9e395c6fba8f.png" width="24%" alt="Screenshot_20200703-114518"> <img src="https://user-images.githubusercontent.com/1119271/86489918-f4b10100-bd22-11ea-950b-30a4afd59620.png" width="24%" alt="Screenshot_20200703-114527">

Reader card for post with gallery: 

<img src="https://user-images.githubusercontent.com/1119271/86490056-583b2e80-bd23-11ea-8cf8-9395e07489d1.png" width="24%" alt="Screenshot_20200703-114522">

One thing I did notice is there is a difference in between the Reader and the mobile web where thumbnails are cropped to align and look great on the web—this is with the "Crop images" setting on in the gallery block settings—while the corresponding gallery doesn't look as good in the app because the thumbnails aren't cropped:

Reader detail in app|Mobile web
---|---
![Screenshot_20200703-113137](https://user-images.githubusercontent.com/1119271/86490109-84ef4600-bd23-11ea-9683-66a0bd23b6d3.png)|![Screenshot_20200703-113146](https://user-images.githubusercontent.com/1119271/86490117-8882cd00-bd23-11ea-8b22-4d532554aae1.png)|
<img width="1280" alt="Screen Shot 2020-07-03 at Jul 3 11 53 16 AM" src="https://user-images.githubusercontent.com/1119271/86490284-11016d80-bd24-11ea-85cc-fb07cbae3187.png">

<p style="clear:both;"><sup>Tested with WPAndroid 15.2-rc-1 on Pixel 3 Android 10.</sup></p>
