### ISSUE TITLE
Error 403 on Comment Details View for a Jetpack site

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#1167]
I see the following error when I open the comment detail view for a comment on eritreo.it/wp37 (Jetpacked site)

```
03-27 18:53:26.345: E/WordPress(8910): [2711] BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1/sites/59732081/posts/115/?meta=site,likes
03-27 18:53:26.736: E/WordPress(8910): [2711] BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1/sites/59732081/posts/115/?meta=site,likes
03-27 18:53:27.166: E/WordPress(8910): [2711] BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1/sites/59732081/posts/115/?meta=site,likes
03-27 18:53:27.527: E/WordPress(8910): [2711] BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1/sites/59732081/posts/115/?meta=site,likes
03-27 18:53:27.527: E/WordPress-READER(8910): null, status 403 - com.android.volley.NetworkResponse@439ee840
03-27 18:53:27.527: E/WordPress-READER(8910): com.android.volley.AuthFailureError
03-27 18:53:27.527: E/WordPress-READER(8910):   at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:134)
03-27 18:53:27.527: E/WordPress-READER(8910):   at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:105)
```

Thrown in <code>ReaderPostActions->
requestPost(final long blogId, final long postId, final ReaderActions.ActionListener actionListener)</code>

Note: I'm correctly authenticated to WordPress.com and can access Reader and Notifications.

**Comment by rachelmcr** [comment]
I tested this issue in 4.8-rc-3 with the following steps:
1. Disabled the JSON API module on a self-hosted Jetpack site
2. Published a comment on that site
4. Went to Comments
5. Tapped the comment to view comment detail
6. For good measure, went to Notifications
7. Tapped the comment to view comment detail
8. Tapped the post title to view the post

Everything worked as expected for me; I didn't find any user-facing issues. Are these errors still an issue?

**Comment by daniloercoli** [comment]
Closing this issue since it was fixed plugin/server side.
