### ISSUE TITLE
Reader: cover block text is not formatted properly and image background doesn't look correct in the Reader

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11674]
Steps to reproduce:

1. On the web, create a new post.
1. Add a cover block with an image background.
1. Add a cover block with a solid color background.
1. Add a cover block with a linear gradient background.
1. Add a cover block with a radial gradient background.
1. Set the height for each block to 100.
1. View the post in the Reader.
1. Compare how the post looks in the editor, preview, mobile web, and Reader.

**Result:** 

- [ ] Image background and focal point aren't displayed correctly.
- [ ] Spacing between cover blocks is collapsed.
- [ ] Text size is incorrect.
- [ ] Text is not centered horizontally or vertically.

**Note:**  not being able to see radial gradients in the block editor in the app was filed as a separate issue at https://github.com/wordpress-mobile/gutenberg-mobile/issues/2140.

Editor | Preview in app | Mobile Web | Reader in app 
--- | --- | --- | ---
<img src="https://user-images.githubusercontent.com/1119271/79401479-72484a80-7f46-11ea-8c51-c215bb044200.png" width="200" alt="Screenshot_20200415-142418"> | <img src="https://user-images.githubusercontent.com/1119271/79401199-aff8a380-7f45-11ea-9929-b6195c0c62d5.png" width="200" alt="Screenshot_20200415-141756"> | <img src="https://user-images.githubusercontent.com/1119271/79401200-b0913a00-7f45-11ea-9c16-9e61e2633ee9.png" width="200" alt="Screenshot_20200415-141741"> | <img src="https://user-images.githubusercontent.com/1119271/79401193-acfdb300-7f45-11ea-82f0-a72dcbf0e497.png" width="200" alt="Screenshot_20200415-141815">

<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 Dark Theme.</sup></p>

**Comment by designsimply** [comment]
The ability to add a color-only backgrounds has been added to the Cover block in Gutenberg Mobile and is planned for beta release in v15.4. 

During beta testing, I found that gradients added via the editor in the app were not displayed in the Reader, and I verified that the horizontal and vertical text alignment are both still incorrect as well.

Editor|Preview|Reader
---|---|---
![Screenshot_20200728-175130](https://user-images.githubusercontent.com/1119271/88740916-8bdb5f80-d0fb-11ea-8362-ce7d5e6f4ac3.png)|![Screenshot_20200728-175152](https://user-images.githubusercontent.com/1119271/88740910-87af4200-d0fb-11ea-8400-72dcdd37b954.png)|![Screenshot_20200728-175115](https://user-images.githubusercontent.com/1119271/88740922-8da52300-d0fb-11ea-9534-84387125974a.png)

<p style="clear:both;"><sup>Tested with WPAndroid 15.4-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by designsimply** [comment]
Removing from high priority because this is likely a problem happening upstream and needs to be fixed on the Calypso side. Adding the `Needs manual testing` label to ask for a check on that.

**Comment by ashiagr** [comment]
Closing with the same reasoning for Android as for the same issue on iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/13920

> If any block doesn't appear correctly, it probably doesn't render correctly on the web too. All the fixes done for Reader web now apply to iOS Reader, so if there's any block issue we should open an issue in https://github.com/Automattic/wp-calypso
