### ISSUE TITLE
Reader: missing spacing between titles and dates in the latest posts block

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11682]
Steps to reproduce:

1. Create a new post on the web.
1. Add a Latest Posts block.
1. Adjust the block settings to show 10-word excerpts.
1. Adjust the block settings to display the post date
1. Publish the post.
1. View the post in the Reader.

**Result:** dates in the latest post block appear next to the title without any spacing between them instead of showing on the next line like they do on the web.

Reader in app | Chrome on Android 10
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79513865-1fcc6400-8002-11ea-8110-f94587d2d659.png" width="200" alt="Screenshot_20200416-124459"> | <img src="https://user-images.githubusercontent.com/1119271/79513861-1e9b3700-8002-11ea-8df0-c2c5a5422d39.png" width="200" alt="Screenshot_20200416-124511">

<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 Dark Theme.</sup></p>

**Comment by ashiagr** [comment]
Should be addressed in Automattic/wp-calypso#43595
