### ISSUE TITLE
Reader: Spacer blocks are ignored in the Reader

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11684]
Steps to reproduce:

1. Create a new post.
1. Add a paragraph block.
1. Add a 20-pixel spacer block.
1. Add another paragraph block.
1. Add a 50-pixel spacer block.
1. Add another paragraph block.
1. Add a 100-pixel spacer block.
1. Publish the post.
1. View the post in the Reader.

**Result:** spacer paragraphs are ignored in the Reader.

Reader in app | Chrome on Android 10
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79518552-a5eea780-800e-11ea-8f37-4023ac2ac564.png" width="200" alt="Screenshot_20200416-141357"> | <img src="https://user-images.githubusercontent.com/1119271/79518550-a4bd7a80-800e-11ea-8316-3d2575cbeb6f.png" width="200" alt="Screenshot_20200416-141410">

<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 Dark Theme.</sup></p>

**Note:** This could be by design! If it is, please close this issue with an explanation. cc @mbshakti

**Comment by zwarm** [comment]
We want to keep a consistency and generic experience in the Reader. For now, we won't be supporting custom spacing: Automattic/wp-calypso#43595 (comment)
