### ISSUE TITLE
Reader: video block is offset too far to the right

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11685]
Steps to reproduce:

1. Create a new post.
1. Add a paragraph block.
1. Add a video block with a caption.
1. Add another paragraph block.
1. Publish the post.
1. View the post in the Reader.

**Result:** the video appears offset to the right in the Reader from where it should be and horizontal scrolling is possible.

Reader in app | Chrome on Android 10
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79519291-ad16b500-8010-11ea-9cc3-545662ef3383.png" width="200" alt="Screenshot_20200416-142851"> | <img src="https://user-images.githubusercontent.com/1119271/79519286-aa1bc480-8010-11ea-82c9-41f3e78ce2b5.png" width="200" alt="Screenshot_20200416-142926">

<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 Dark Theme.</sup></p>

**Comment by malinajirka** [comment]
I've centered the video in https://github.com/wordpress-mobile/WordPress-Android/pull/12213. However, it still doesn't expand to full content width. These default attributes are adding 40px horizontal margin.
<img width="324" alt="Screenshot 2020-06-19 at 16 14 44" src="https://user-images.githubusercontent.com/2261188/85142396-9e36c380-b248-11ea-9fbf-3de4089fe391.png">
