### ISSUE TITLE
Toolbar buttons not highlighted

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#11701]
The **List** and **Header** buttons are highlighted (correctly) in dark mode, but not in light mode:

| Light mode | Dark mode |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1522856/79700200-633e0100-8294-11ea-926e-b34674043c42.png) | ![image](https://user-images.githubusercontent.com/1522856/79700214-73ee7700-8294-11ea-9b93-359a9503c012.png) |

@khaykov do you have an idea about what could be happening here?

Tested on API 28.

**Comment by khaykov** [comment]
I worked on that part recently, so I'll take a look while it's still fresh in memory :)
