### ISSUE TITLE
App crash when accessing App Settings

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11724]
### Description

The app crashes when accessing app settings.

### Steps to Reproduce

1. On the site screen, tap the profile icon in the header bar
2. Tap App Settings
3. Observe the app crashes

### Crash Report

**Sentry Url**: https://sentry.io/share/issue/294df5db39da45ae997c1c81de8475ca/
**User Count**: 71
**Count**: 112
**First Release**: org.wordpress.android-14.6
**First Seen**: 2020-04-21T04:19:24Z
**Last Release**: org.wordpress.android-14.6
**Last Seen**: 2020-04-22T15:57:02Z
**24 Hours**: 92
**30 Days**: 111

### Screenshots
|  |
| - |
| <img width="300" src="https://user-images.githubusercontent.com/1898325/80005745-027c1780-8492-11ea-8a93-7658b1449f5a.gif"> |

```
ArrayIndexOutOfBoundsException: length=2; index=2
     at android.preference.ListPreference.getEntry(ListPreference.java:229)
     at android.preference.ListPreference.getSummary(ListPreference.java:174)
     at android.preference.Preference.onBindView(Preference.java:651)
     at android.preference.Preference.getView(Preference.java:585)
     at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:255)
     at android.widget.AbsListView.obtainView(AbsListView.java:2428)
     at android.widget.ListView.makeAndAddView(ListView.java:2071)
     at android.widget.ListView.fillDown(ListView.java:797)
     at android.widget.ListView.fillFromTop(ListView.java:859)
     at android.widget.ListView.layoutChildren(ListView.java:1814)
...
(54 additional frame(s) were not displayed)
```

### Environment

Device Android Galaxy S10 (SM-G973F), Android version 10

**Comment by renanferrari** [comment]
I'm starting to look into this but I haven't been able to reproduce the issue so far. 

Looking in the logs, this seems to be hapenning after we try to fetch the user's account settings. @guarani @oguzkocer Is there any other detail you could share about the account you're using?

**Comment by guarani** [comment]
I was able to reproduce this on a brand new WordPress.com account and new site – so we can rule out it being something to do with my specific WP.com account. It could be related to my device type, android version, etc.
Device Android Galaxy S10 (SM-G973F), Android version 10

**Comment by oguzkocer** [comment]
I wasn't able to reproduce this issue when I opened it, but I am also looking into it now due to its importance.

**Comment by oguzkocer** [comment]
I figured out the cause, working on the steps now.

**Comment by oguzkocer** [comment]
@renanferrari Here is how to reproduce this issue: https://cloudup.com/cbEnVKMIzOU. It's likely that the changes in this commit: https://github.com/wordpress-mobile/WordPress-Android/commit/4585d19679b9f651d39dfd3372de544a093b221c#diff-cdcbc2d7423e158442299f266c956df1 are related, but probably not directly points to the cause.

There are 3 different options for theme dialog in some languages, but only 2 of them in others. So, if the 3rd option is selected and a language that doesn't support it is selected, the app will keep crashing while opening the app settings.

---

In case my debugging process helps, here are some steps I took to get here:
1. In the logs below, you can see that the `App Settings` page is tracked twice without any other pages in between. It means more than likely that the page is restarted.
2. Also shown in the logs that the account settings was fetched but was not retrieved before the crash, so it's unlikely to be related to the fetch directly.
3. The crash started to happen in `14.6`, so history of `AppSettingsFragment` is likely to be related, which pointed me to https://github.com/wordpress-mobile/WordPress-Android/commit/4585d19679b9f651d39dfd3372de544a093b221c#diff-cdcbc2d7423e158442299f266c956df1.
4. The activity restarts happen with language and theme changes. Playing with those led me to the crash.

Hope this helps!

<img width="839" alt="Screenshot_3" src="https://user-images.githubusercontent.com/662023/80015760-33634900-84a0-11ea-8a08-72c43fd51ffd.png">

**Comment by renanferrari** [comment]
@oguzkocer Excellent! Thanks for detailing the steps you took, it's really helpful.

**Comment by renanferrari** [comment]
Ok, I think I got it. Working on a fix.

**Comment by oguzkocer** [comment]
@renanferrari Could you please target `release/14.6.1` for your PR and cc me?

**Comment by elibud** [comment]
Thanks everyone for the hard and speedy work on this one.
