### ISSUE TITLE
Image uploads multiple times even after it is uploaded once

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#11722]
### Expected behavior
If I accidentally close the app while an image is uploading, the app should attempt to upload the image on next re-launch. Once uploaded there shouldn't be any further attempt.

### Actual behavior
If I accidentally close the app while an image is uploading, the app attempts to upload the image on next re-launch. Once uploaded, the app re-attempts to upload that image on next relaunch resulting in multiple images upload.

### Steps to reproduce the behavior
[Link to video](https://www.dropbox.com/s/0gs943y1tizkafa/Screen%20Recording%202020-04-22%20at%201.22.13%20PM.mov?dl=0)

**Comment by designsimply** [comment]
Tested and confirmed that if I close the app while uploading an image to a published post, the "Local Changes" label appears on the post and the media gets duplicated in the media library a few times (note: it stopped at 3 in my case).

My testing steps:

1. Create a new post.
1. Add a title.
1. Add an image block.
1. Add an image using "Choose from device".
1. Close the app while the image is uploading.
1. Re-open the app.
1. Publish the post.
1. Re-open the post for editing.
1. Add another image block.
1. Add another image using "Choose from device".
1. Close the app while the image is uploading.
1. Re-open the app and go to My Site > Blog Posts > Published.
1. Notice that the "Local changes" label is there now.
1. Re-open the post for editing.
1. Add another image block.
1. Add another image and select the "WordPress Media Library" option.
1. Check to see if multiple versions of the last image uploaded appears in the media library.

**Result:** the image that should have only been uploaded once appears to have been uploaded multiple times.

**Video:** [4m21s](https://cloudup.com/cyvLJk-pPok)<br><sup>Tested with WPAndroid 14.7-rc-2 on Pixel 3 Android 10.</sup>

Attaching the video here just in case the link stops working in the future: [Screen Recording 2020-04-22](https://github.com/wordpress-mobile/WordPress-Android/files/4530876/Screen.Recording.2020-04-22.at.1.22.13.PM.mov.zip) (my video was too large to upload).

**Comment by planarvoid** [comment]
I cannot reproduce this issue. Do you think you double check whether this is still happening @designsimply ? thanks!
