### ISSUE TITLE
Prepublishing Nudges - Create a input filter regex for tags fragment

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11720]
## Expected behavior
The `Tags` option within `Post Settings` should prevent invalid inputs. You should only be able to type/add tags separated by commas.

## Actual behavior

Currently, you can type anything you want into the tags input 
eg. `Android,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Cars,,,,, , , , , , , ,,,,,,,,,,` 
We should allow only [a-zA-Z,], and single whitespace.

### Steps to reproduce the behavior
1. Open the app. 
2. Create a new post. 
3. Click the more icon. 
4. Click Tags. 
5. Enter tags with invalid characters such as too many commas, semicolons etc. 

<kbd><img src="https://user-images.githubusercontent.com/1509205/81971230-605dd400-95e6-11ea-9fe5-2be0014772b2.png" width="320"></kbd>

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by segunfamisa** [comment]
Hey @jd-alexander  I was thinking of trying my hands on this task, but I was confused about the details of how this will work. Particularly,
1. Is there anything you have in mind with communicating invalid inputs to the user? (e.g setting error on the `TextInputLayout`?)
2. How do you think of preventing invalid inputs? Should an alert pop up if the user pastes invalid text and attempts to navigate back? (I see that there is no "save" option, and finishing the activity is what saves the tags.
3. Slightly related to the question above, do you expect the validation to be done as user types, or when they attempt to leave the page (hence, save)?

**Comment by jd-alexander** [comment]
Thanks for the interest @segunfamisa I am going to update this issue so it's a bit more descriptive. It was in a project board so the context is missing here. Once, I am done I will answer all of your questions 😄

**Comment by jd-alexander** [comment]
> Is there anything you have in mind with communicating invalid inputs to the user? (e.g setting error on the TextInputLayout?)

Great question! Yes, it would be good to set an error on the `TextInputLayout` if we are giving the user the full control to fix the input. 

> How do you think of preventing invalid inputs? Should an alert pop up if the user pastes invalid text and attempts to navigate back? (I see that there is no "save" option, and finishing the activity is what saves the tags.

Indeed! My initial idea due to their being no "save" option was to use some form of `InputFilter` that would prohibit it, so once the user types an invalid character(s) it wouldn't be shown at all. What are your thoughts on this from a user experience standpoint? 

> Slightly related to the question above, do you expect the validation to be done as user types, or when they attempt to leave the page (hence, save)?

Yes, with the current implementation we would have to do the validation as the user types.

**Comment by jd-alexander** [comment]
@malinajirka do you have any thoughts on this issue. I remember you raising a valid point about the usage of the back button as the means of saving. I am thinking to let it remain for now because all of the other Post Settings on this screen operate this way already.

**Comment by malinajirka** [comment]
Thank you Segun for taking a look at this issue! It's really appreciated ;). Great question! 

> I remember you raising a valid point about the usage of the back button as the means of saving. I am thinking to let it remain for now because all of the other Post Settings on this screen operate this way already.

I'm personally not a fan of this behavior, but I agree we should keep it for now (for the sake of consistency).

>Is there anything you have in mind with communicating invalid inputs to the user? (e.g setting error on the TextInputLayout?)

> > Great question! Yes, it would be great idea to set an error on the TextInputLayout. I am looping in another engineer to get a second opinion on this issue.

I think we should set the error on the TextInputLayout only if we let the user enter the invalid character. But as you discussed I think preventing them from entering the character might be a better solution. How would you feel about showing a note with a list of allowed characters bellow the input?


Either case, I'll make this discussion even more tangled 😢. I've checked how the web (Calypso) behaves and they allow all the characters, so you can create a tag "...,,,,,,k,,.,/" there. I'm wondering what will happen when the user opens a post created on the web with such weird tags. Or imagine someone is used to using a certain characters in their tags and we'll prevent them from do so out of nowhere. To be honest I'd vote for closing this issue with "Won't fix" tag. Wdyt?

**Comment by segunfamisa** [comment]
> I've checked how the web (Calypso) behaves and they allow all the characters, so you can create a tag "...,,,,,,k,,.,/" there.

Yeah, seeing this, I'm voting "Won't fix" too until a product alignment happens with the mobile and web clients.

Thanks @jd-alexander & @malinajirka for checking 👍
