### ISSUE TITLE
[GlobalStep] Android – video preview screen in the media picker is blank

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11735]
### Description
The user will observe that upon adding a video block, selecting the "Choose from device option" and then previewing any of the videos, the preview does not function and a black screen is displayed instead.

### Expected behaviour
When viewing the preview of a video it plays as expected

### Actual behaviour
The video preview is a black screen.

### Steps to reproduce the behaviour
1.	Install WordPress 14.7-rc-1
2.	Login to a valid account.
3.	Create a new post.
4.	Add a video block.
5.	Tap the “ADD VIDEO” button and select “Choose from device”.
6.	Preview any of the videos.

##### Tested on the following:
Huawei P10 (7.0)
Samsung Galaxy S8+ (8.0)

#### Please see the attached video for reference.
[Android Video preview issue reference.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4522167/Android.Video.preview.issue.reference.zip)

#### Submitted by:
Nicholas Brown

**Comment by designsimply** [comment]
Tested and confirmed with 14.7-rc-2 using the following steps:

1. Create a new post.
1. Add a video block.
1. Tap "ADD VIDEO".
1. Tap "Choose from device".
1. Notice the heading says "Choose photo" not "Choose video". See https://github.com/wordpress-mobile/gutenberg-mobile/issues/2184.
1. Tap once to select a video (or long press and skip the next step).
1. Tap again to preview a video.

**Result:** the video preview screen in the media picker is completely blank.

<img src="https://user-images.githubusercontent.com/1119271/80253746-0dbc7800-8637-11ea-9745-8901b483eee6.png" width="200" alt="Screenshot_20200424-101918"> <img src="https://user-images.githubusercontent.com/1119271/80253878-5a07b800-8637-11ea-8c6d-144129b60e74.png" width="200" alt="Screenshot_20200424-101932">
<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-2 on Pixel 3 Android 10.</sup></p>

**Comment by designsimply** [comment]
Possibly related: https://github.com/wordpress-mobile/WordPress-Android/issues/11754.
