### ISSUE TITLE
[GlobalStep] Selecting an incorrect file type to upload in media leads to a persistent crash.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11748]
### Description
From the My Site – Media page it is possible to select to upload media from Google Drive, this will then allow the user to select a file with any extension, if the user selects a non-image or video file such as .pdf the application will crash, all subsequent attempts to access Media from My Sites thereafter, for the same site, will cause a crash. 

### Expected behavior
No crash can occur, non-image and video cannot be selected from Google Drive.

### Actual behavior
An invalid file type can be selected and causes the app to crash.

### Steps to reproduce the behavior
1.	Install WordPress 14.7
2.	Ensure a google account is logged into the device.
3.	Register or login to an account.
4.	For this it is safest to use a newly created site.
5.	Once a new site is created select the Media page from My Sites.
6.	Tap the plus icon to add media.
7.	Select the lowest Drive option.
8.	Select a non-image or video from the Google Drive.
9. 	If nothing occurs for a moment simply tap the background of the window.
10.	Relaunch the app and attempt to access media again.

##### Tested on the following:
Samsung Galaxy Tab A 10.1” 2016 (7.0)

#### Please see the attached video for reference.
[wp_crash_.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4529733/wp_crash_.zip)

#### Submitted by:
Oliver Howe

**Comment by designsimply** [comment]
> Select a non-image or video from the Google Drive.

I tried with WPAndroid 14.7-rc-2 on Pixel 3 Android 10 and I wasn't able to select a non-video using the media picker from My Sites > Media > + > "Choose video from device". I tried selecting a PDF another way, and it let me select and upload a PDF with out a crash. ([1m19s](https://cloudup.com/chQIgUHL82t))
<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-2 on Pixel 3 Android 10.</sup></p>

However! I did try searching for a related crash in our crash monitoring service (Sentry) and the following steps led me to…

1. Log in to Sentry.
1. Select "wordpress-android" as the project.
1. Search for: `os:"Android 7.0" version:14.7-rc-1 `.
1. Notice that 3 results appear.
1. Notice that the stacktraces in the "NotFoundException" result has several "Media" mentions.
1. It's this one: https://sentry.io/share/issue/ff8cb93e6b0045e882cfc3619a1cab53/

@oguzkocer I noticed the Sentry issue I suspect is the right one is filed at https://github.com/wordpress-mobile/WordPress-Android/issues/11617 (and already fixed even 🎉), can you help me verify that's likely the same issue as the one reported here?

**Comment by oguzkocer** [comment]
@designsimply Yes, this should be fixed. @wptester9845 could you give `14.7-rc-2` a try? You can find this release here: https://github.com/wordpress-mobile/WordPress-Android/releases/tag/14.7-rc-2

**Comment by wptester9845** [comment]
Hi @oguzkocer 
Retested using the same device: Samsung Galaxy Tab A 10.1" 2016 (7.0) in the 14.7-rc-2 build can I can verify the issue is resolved.
When selecting a PDF this time the upload would fail but the UI handles this gracefully with the option to retry or remove the file without a crash.

**Comment by oguzkocer** [comment]
Thanks for testing it again @wptester9845!
