### ISSUE TITLE
[GlobalStep] Dark theme is not functioning on a OnePlus 6 device

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11743]
### Description
Selecting Dark Mode as the Device’s Colour Theme causes the Application to be displayed in its default Colour Theme.

### Reproduction Rate
4/4 100%

### Expected behaviour
The Application should reflect the selected Dark Mode.

### Actual behaviour
The Application is displayed in its Default Colour Theme.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Switch the Device’s Colour Theme to Dark Mode.
3. Select the “Log In” option.
4. Navigate the Application.
##### Tested on the following
One Plus 6 (9.0)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/80204692-3c2f5880-8621-11ea-9bd1-a9828dd347ea.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
I wonder if this is limited to One Plus 6. I can't seem to replicate it on my Pixel 3 Android 10 device.

@wptester9845 do you recall if you changed the theme in the OnePlus 6 device settings? I noticed at least one [forum reply](https://forums.oneplus.com/threads/dark-theme-auto-change-to-light-during-day-while-using-android-auto.1167361/) that mentions updating the theme in addition to Dark Mode.

@khaykov I'm unable to see this problem on my Pixel 3, do you have any insight as to why the WP app might not be updating to Dark Theme for a OnePlus 6 user?

**Comment by khaykov** [comment]
@designsimply I'm not sure what flavor of Android One Plus 6 is using, but system-wide dark theme option is only officially supported from Android 10. I don't have One Plus 6, but maybe it's some sort of dark skin instead of a dark mode? On Android 9 only battery saver can trigger the theme on system level.

Another option is that Light mode is selected in App Settings? This will override any system settings.

**Comment by designsimply** [comment]
> System-wide dark theme option is only officially supported from Android 10.

Ah! Didn't know that. 🙂In the original report above, I believe "One Plus 6 (9.0)" means they are using Android 9.0.

Great suggestion about checking App Settings! @wptester9845 can you double check that you have "Dark" selected for Account > App Settings > Appearance in your WPAndroid app? Here is what it looks like for me:

<img src="https://user-images.githubusercontent.com/1119271/80256726-870a9980-863c-11ea-8333-6ad82e62ebcb.png" width="200" alt="Screenshot_20200424-110056">
<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-2 on Pixel 3 Android 10.</sup></p>

**Comment by wptester9845** [comment]
After further testing I can confirm it behaves as explained in the comments.
I wasn't aware the System Setting was tied to the Battery Saver on this device. Changing the Appearance in the Application's Settings fixed it.
Thank you for the explanation.
I'm closing this as it's now confirmed not to be an issue.
* Luis Pimenta
