### ISSUE TITLE
[GlobalStep] The option to Disconnect a Jetpack Site is not present

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11749]
### Description
After adding a Self-Hosted Jetpack Site the option to disconnect it from the current WordPress account is not present in the respective Site’s settings.

### Reproduction Rate
4/4 100%

### Expected behaviour
There should be an option to disconnect the Site from the account.

### Actual behaviour
The button to disconnect the Site from the account is not present.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Login to a valid account.
3. Switch to a Self-Hosted Jetpack Site.
4. Navigate to the Settings.
##### Tested on the following
One Plus 6 (9.0)
Samsung Galaxy S8+ (8.0)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/80230494-ede27f80-8649-11ea-9daa-7abeacd0772b.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Thank you for the report!

Closing in favor of the previous request already on file for this at https://github.com/wordpress-mobile/WordPress-Android/issues/6195.
