### ISSUE TITLE
Improve UI of post card in the Reader

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11759]
Update the UI of the post card in the Reader. 

Note: 
- The following design might be out-of-date. Check out `figma` to see the most current design.
<img width="1056" alt="Screenshot 2020-04-27 at 12 06 39" src="https://user-images.githubusercontent.com/2261188/80360609-e3a9c680-887f-11ea-929a-835942849065.png">
<img width="1226" alt="Screenshot 2020-04-27 at 12 08 12" src="https://user-images.githubusercontent.com/2261188/80360618-e73d4d80-887f-11ea-82f6-e09842d531b3.png">

**Comment by oguzkocer** [comment]
Hi there! `14.9` is being frozen, so this PR is being bumped to `15.0`. If these changes _have to_ be shipped with `14.9`, please target `release/14.9` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.
