### ISSUE TITLE
Prepublishing Nudges : Change Publish To Time 

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11768]
For the publish/scheduling functionality the word "Time" should be used instead of "Publish" since it's causing confusion for some users with the button/action "Publish Now".

**Comment by designsimply** [comment]
Should it be "Time" or "Date and Time"? Should we ask Editorial or are you totally cool making the decision on the wording (or was it already discussed elsewhere perhaps)?

**Comment by designsimply** [comment]
I might be confused. Would it be ok to ask for designs to be posted as part of this issue? 

Have you considered how the wording will be different for backdated and scheduled posts?

Aside: here are some example screenshots from WPiOS for comparison.

<img src="https://user-images.githubusercontent.com/1119271/80828472-8c1e9a00-8ba2-11ea-9200-97101dfeee77.PNG" width="150" alt="IMG_3975"> <img src="https://user-images.githubusercontent.com/1119271/80828465-8923a980-8ba2-11ea-898a-730a281f6976.PNG" width="150" alt="IMG_3972"> <img src="https://user-images.githubusercontent.com/1119271/80828467-8aed6d00-8ba2-11ea-8128-97e17761c71d.PNG" width="150" alt="IMG_3973"> <img src="https://user-images.githubusercontent.com/1119271/80828469-8b860380-8ba2-11ea-9779-76602991f33a.PNG" width="150" alt="IMG_3974">
<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.3 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by jd-alexander** [comment]
Hi @designsimply I should have updated this issue with the new direction from the here. I will close this one https://github.com/wordpress-mobile/WordPress-Android/issues/11776

**Comment by jd-alexander** [comment]
> Have you considered how the wording will be different for backdated and scheduled posts?

This is a good point Sheri :) . I will check how this looks during testing 👍
