### ISSUE TITLE
Reader: table styling needs direction

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11771]
Steps to reproduce:

1. Create a new post on the web.
1. Add a paragraph.
1. Add a table with several rows and select the "Stripes" style in the block settings.
1. Add a caption for the table.
1. Add another paragraph.
1. Publish the post.

**Result:** 

- [ ] Table background/stripes are not respected in the Reader.
- [ ] Table captions are not styled differently compared to paragraphs.
- [ ] Spacing looks awkward.

WPAndroid Reader | Safari view for comparison
---|---
<img src="https://user-images.githubusercontent.com/1119271/80551626-53ec4100-8981-11ea-8b9e-5f6dc8b87fe2.png" width="200" alt="Screenshot_20200428-144432">|<img src="https://user-images.githubusercontent.com/1119271/80551624-52bb1400-8981-11ea-94db-e6ce5af4cf8e.png" width="200" alt="Screenshot_20200428-144445">

<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.2 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

This issue is also filed for WPiOS, please see https://github.com/wordpress-mobile/WordPress-iOS/issues/10333#issuecomment-620927730.

**Comment by maxme** [comment]
Edit: the table is horizontally scrollable.

<s>Tables with a lot of columns are not horizontally scrollable, which makes part of the content inaccessible.</s>

**Comment by zwarm** [comment]
@maxme Can you provide some more detail not scrolling? I tried on emulator and physical device (pixel 3XL) and the content of the screen scrolls as expected. See attached gif. Thanks.

<img src="https://user-images.githubusercontent.com/506707/94694296-afd93e00-0302-11eb-8e36-88b6dfa53f40.gif" width="300" alt="Screenshot">

**Comment by maxme** [comment]
@zwarm you're right! I tried again on the Reader directly, but also via a notification, and I was able to scroll horizontally and that same post with a table block. I'll update my previous comment.
