### ISSUE TITLE
Reader: file block is missing spacing and the download button isn't styled

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11778]
Steps to reproduce:

1. On the web, create a new post.
1. Add a paragraph.
1. Add a file block.
1. Add another paragraph.
1. Publish the post.
1. View the post in the Reader.

**Result:** 

- [ ] No space between the filename and the download button.
- [ ] Download button is missing styling.

WPAndroid Reader | WPAndroid Reader | Chrome Android 10
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/80653651-e7804900-8a37-11ea-89f7-5b3be3b5a3c0.png" width="200" alt="Screenshot_20200429-122046">|<img src="https://user-images.githubusercontent.com/1119271/80653555-b3a52380-8a37-11ea-8e2c-18b1cc2c8454.png" width="200" alt="Screenshot_20200429-122643">|<img src="https://user-images.githubusercontent.com/1119271/80653552-b30c8d00-8a37-11ea-86b9-d28fcee24031.png" width="200" alt="Screenshot_20200429-122651">

<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-2 on Pixel 3 Android 10.</sup></p>

**Comment by designsimply** [comment]
Related button block issue: https://github.com/wordpress-mobile/WordPress-Android/issues/11679.

**Comment by ashiagr** [comment]
Should be addressed in Automattic/wp-calypso#43595
