### ISSUE TITLE
Reader: not all content from the markdown demo is rendered correctly in the Jetpack Markdown Block

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11777]
Steps to reproduce:

1. On the web, log in to a Jetpack site and create a new post.
1. Add a paragraph.
1. Add a [Markdown Block](https://jetpack.com/support/jetpack-blocks/markdown-block/).
1. Copy and paste the [demo content](https://markdown-it.github.io/) linked to from the related Jetpack support page.
1. Add another paragraph.
1. Publish the post.
1. View the post in the Reader.

**Result:** 

- [ ] Typographic replacements doesn't change strings like `(R)` to symbols like `®`.
- [ ] One whole line of spacing between items in ordered lists (is this intended?).
- [ ] Subscript/Superscript text isn't differentiated.
- [ ] Inserted text isn't differentiated.
- [ ] Marked text isn't differentiated.
- [ ] Footnotes don't work.
- [ ] Abbreviations don't work.

**Various Screenshots** 

<img src="https://user-images.githubusercontent.com/1119271/80650916-1d223380-8a32-11ea-8681-59f7f42a2cad.png" width="200" alt="Screenshot_20200429-115321"> <img src="https://user-images.githubusercontent.com/1119271/80650912-1bf10680-8a32-11ea-9b49-c36cef5dc7d7.png" width="200" alt="Screenshot_20200429-115346"> <img src="https://user-images.githubusercontent.com/1119271/80650909-1abfd980-8a32-11ea-915f-cc0ff97479fb.png" width="200" alt="Screenshot_20200429-115432">

<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-2 on Pixel 3 Android 10.</sup></p>

**Comment by designsimply** [comment]
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14022.

**Comment by daniloercoli** [comment]
Closing this issue since the demo content is now rendered correctly on version 22.4 of the Jetpack app.
