### ISSUE TITLE
Update login prologue UI

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#11782]
This task is to update the Prologue screen with the new designs. 
The task is to: 
- create both light and dark version of the screen. 
- create new tutorial steps
- update navigation bar background to match the updated designs
- figure out a way to hide the new designs behind a feature flag so we can turn them off/on remotely

The buttons now have 2 different actions (adding the actions will be part of different task):
- Continue with WordPress.com
- Enter your site address

The prologue screen has updated tutorial steps to swipe through (could you please provide the remaining steps and the designs @mattmiklic ?):
- Step 1: 
  - title: 36% of the web is built on WordPress.
  - subtitle: Unlock the power of the most flexible website builder.
 
![Screen : Prologue Light](https://user-images.githubusercontent.com/1079756/80683042-d5e48300-8ac3-11ea-89f3-100613616cdc.png)

**Comment by mattmiklic** [comment]
> The prologue screen has updated tutorial steps to swipe through (could you please provide the remaining steps and the designs @mattmiklic ?):

I sure will; though we haven't yet defined what content we want to show here. If it makes sense, we could hide the paging dots and make this a single static screen initially, and then add the other content later.

**Comment by renanferrari** [comment]
Closed by #11876.
