### ISSUE TITLE
Update login epilogue UI

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#11783]
The task is to:
- update epilogue according to the new designs
- make sure the designs can be turned on/off by a flag
- Instead of the current 2 options "Continue" and "Connect another site" we'll use only "Done" option that replaces the "Continue". The "Connect another site" option should move at the bottom of the current site list
- the epilogue uses a shared component called SitePicker. We need to make sure we're not breaking any other place that uses this component. I see multiple approaches we can take:
  - update UI of the whole component - changing the site picker also for switching sites and reblogging
  - make the UI changes in the same component but turn it on/off by a flag - this would mean that the previous usage of the component would remain unchanged
  - create a new component for the epilogue - this would require more work but it would give us more flexibility to do some changes to the screen without changing the other uses (for example moving the "Connect another site" button).

what do you think @mattmiklic ? should we also update the designs of the rest of the site pickers? 

![Epilogue States](https://user-images.githubusercontent.com/1079756/80685213-20b3ca00-8ac7-11ea-9703-aba74b102ef9.png)

**Comment by mattmiklic** [comment]
> update UI of the whole component - changing the site picker also for switching sites and reblogging

This sounds like it's probably the right approach. FWIW this layout uses the list item component from the Material Design sketch resources, so it should be very close to a [standard two-line list item](https://material.io/components/lists#anatomy).
