### ISSUE TITLE
Update the UI of the login flow

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#11785]
The task is to update the UI of all the steps of the login/signup flow. This flow uses shared components so the screen changes will be overlapping
- The toolbar is changing, instead of a logo it now contains a title with the flow you're in ("Get Started" changes either into "Log In" or into "Sign Up"), the help is now an icon
- The action buttons are moving to the bottom of the screen
- The colors and styling are changing
- Go step by step and compare the screens to the desings to see all the changes
- If possible, the changes should be behind a feature flag

![Continue with WordPress com](https://user-images.githubusercontent.com/1079756/80691007-e7cc2300-8acf-11ea-9f59-aebd85ec9699.png)

**Comment by renanferrari** [comment]
This issue will be handled by multiple PRs:

- [x] Updates to the Login Library theme and styles: #12047
- [x] Updates to the Login Library existing screens layouts: #12048
  - [x] Login Email Screen
  - [x] Login Email Password Screen
  - [x] Login Magic Link Request Screen
  - [x] Login Magic Link Sent Screen
  - [x] Login 2FA Screen
  - [x] Login Site Address Screen
  - [x] Login Username Password Screen
  - [x] Signup Email Screen
  - [x] Signup Magic Link Screen
- [ ] Addition of the new Signup Confirmation screen to the new Login library: TBA
- [ ] Updates to the Jetpack flow and other alternative flows: TBA
