### ISSUE TITLE
AndroidRuntimeException: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11790]
**Sentry Url**: https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/
**User Count**: 14
**Count**: 17
**First Release**: org.wordpress.android-14.6.1
**First Seen**: 2020-04-24T14:44:38Z
**Last Seen**: 2020-04-30T11:01:25Z
**24 Hours**: 4
**30 Days**: 17

```
AndroidRuntimeException: requestFeature() must be called before adding content
     at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:345)
     at android.app.Dialog.requestWindowFeature(Dialog.java:1079)
     at org.wordpress.android.ui.prefs.SiteSettingsFragment.lambda$getListEditorView$15$SiteSettingsFragment(SiteSettingsFragment.java:1640)
     at org.wordpress.android.ui.prefs.-$$Lambda$SiteSettingsFragment$hYyOvwBaWv2Jj7FXq91kotc5ZsE.onClick(lambda:null)
     at android.view.View.performClick(View.java:4848)
     at android.view.View$PerformClick.run(View.java:20262)
     at android.os.Handler.handleCallback(Handler.java:815)
     at android.os.Handler.dispatchMessage(Handler.java:104)
     at android.os.Looper.loop(Looper.java:194)
     at android.app.ActivityThread.main(ActivityThread.java:5644)
...
(4 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Following the Sentry event breadcrumbs... looks like this seems to occur on Site Settings. User count is at 15.

**Comment by designsimply** [comment]
**Events:** 112
**Users affected:** 83
**Note:** the majority of these crashes appear to be in Android 5 and 6
**Note:** looks to be a new crash in WPAndroid 14.6.1
**Also see:** [this graph](https://sentry.io/organizations/a8c/discover/results/?field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629118824&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
<sub>https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/</sub>

**Comment by designsimply** [comment]
**Events in the last 90d:** 142
**Events in the last 9d since 14.8 was released:** [zero](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629118824+version+14.8&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
**Users affected in the last 90d:** 108
**Limited to:** mostly Android 5 and 6
<sub>https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/</sub>

Strange that this is a new crash in 14.6.1 but the majority of affected devices are on Android 5 or 6.

**Comment by designsimply** [comment]
**Events in the last 90d:** 269
**Users affected in the last 90d:** 200
<sub>WORDPRESS-ANDROID-AVV: https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629118824&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85910430-f7b86880-b7db-11ea-9a67-88614fce066f.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 455
**Users affected in the last 90d:** 259
**Limited to:** Android 5, 6, 7 (mostly 6.x, only 3 reports for 7.x)
<sub>WORDPRESS-ANDROID-AVV: https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629118824&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/90676212-e3f81400-e218-11ea-92b2-45e691a5dd75.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 639
**Users affected in the last 90d:** 218
**Majority of cases are for:** Android 5.x and 6.x
<sub>WORDPRESS-ANDROID-AVV: https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629118824&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96305118-97cc1480-0fba-11eb-9b66-dceac0775f98.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 743
**Users affected in the last 90d:** 199
**Majority of cases are for:** Android 5.x and 6.x
<sub>WORDPRESS-ANDROID-AVV: https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629118824&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100303760-87fd0400-2f5a-11eb-868e-b1b3c4162256.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 856
**Users affected in the last 90d:** 138
**Limited to:** Android 5 & 6
**Culprit:** org.wordpress.android.ui.prefs.SiteSettingsFragment in lambda$getListEditorView$15$SiteSettingsFragment
<sub>WORDPRESS-ANDROID-AVV: https://sentry.io/share/issue/703dcdfc9828483f8a7ff8f63ac85ffb/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1629118824&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105398250-5bbed600-5bdf-11eb-8c49-6b721da3a6d6.png)</a>

Percent|OS
---|---
28.22% | Android 6.0
27.23% | Android 6.0.1
20.30% | Android 5.1.1
13.86% | Android 5.1
3.47% | Android 5.0.2
2.97% | Android 5.0
1.49% | Android 5.0.1
0.99% | Android 10.0
0.99% | Android 7.1
0.50% | Android 8.1

Appears to affect mainly very old versions of Android and has been open for some time. Recommend closing.
