### ISSUE TITLE
Stats: Referrers: Not Possible to Mark a Referrer as Spam

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#11818]
In Calypso, referrers which are not whitelisted can be marked spam by tapping the three dots to the right of the referrer. This is not the case in the WordPress Android app (or iOS).

Expected:
I expected to be able to mark referrers as spam from within the app.

Actual: 
The option to mark referrers as spam doesn’t exist within the app.

Stats referrers in WPAndroid version alpha-220 and Calypso web (same site) on moto e5 play phone:
![androidreferrers](https://user-images.githubusercontent.com/15107387/81057428-a8854400-8ecc-11ea-95d7-f5d34a0750ba.png)

##### Tested on Moto e5 Play, WPAndroid alpha-220
This came up in #2934822-zen when a user wanted to mark some referrers as spam but couldn't.

**Comment by thehenrybyrd** [comment]
Same issue in iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/14055

**Comment by planarvoid** [comment]
I've looked into the Calypso implementation and the endpoint that's used for marking (and unmarking) referrers as spam is this:
```https://public-api.wordpress.com/rest/v1.1/sites/**site_id**/stats/referrers/spam/new?domain=**referrers_domain**```
```https://public-api.wordpress.com/rest/v1.1/sites/**site_id**/stats/referrers/spam/delete?domain=**referrers_domain**```

I recommend using a longpress to show the "Mark as spam" buttom, what do you think @SylvesterWilmott ?

**Comment by SylvesterWilmott** [comment]
>I recommend using a longpress to show the "Mark as spam" button

I agree, adding a dedicated icon or a "more" icon there will remove at least 56px of horizontal space in each row (16 margin, 24 icon, 16 margin). I would favour a long press over using an icon.

**Comment by marco-altran** [comment]
Thoughts about how the UI should be? What do you think of the example below?

![image](https://user-images.githubusercontent.com/69607277/94472126-adf76980-01a0-11eb-9f7c-6205b9f6876f.png)

**Comment by planarvoid** [comment]
This is now implemented and merged so I'm closing this issue
