### ISSUE TITLE
[GlobalStep] [Android] User is not able to Follow and Unfollow the site from  "Notification" tab.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-Android#11854]
Environment:
iOS: iPad Air 2(v13.3.1).

Android: Samsung Galaxy s9 v(10)

 
 Steps To Reproduce:
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Create one site and add post or page and publish it.
 5. Now tap on "Notifications"
 6. Tap on Follow/Unfollow button to Follow/Unfollow the site.
 7.  Observe that "Problem with Following and Unfollowing site" error message popup is displayed and user is not able to Follow/Unfollow the site.
 
  
Actual Result:
User is not able to Follow and Unfollow the site from "Notification" tab.
 
Expected Result:
User should be able to Follow and Unfollow the site from "Notification" tab.

[#11854.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4594700/11854.zip)

**Comment by designsimply** [comment]
I was unable to reproduce this issue on WPAndroid 14.8-rc-3 using the steps provided. ([3m22s](https://cloudup.com/c2eJQiLn78l))

<p style="clear:both;"><sup>Tested with WPAndroid 14.8-rc-3 on Pixel 3 Android 10.</sup></p>

Note: the 11854.zip file in the original issue contains a filed named #14078.mp4 which appears to be associated with a similar WPiOS bug report at https://github.com/wordpress-mobile/WordPress-iOS/issues/14078 for the same testing steps, so I think what happened is that the test was done and confirmed on WPiOS but perhaps not for WPAndroid. Please let me know in the comments if that's not correct and you observed the follow/unfollow bug on an Android device as well. Thank you!
