### ISSUE TITLE
[GlobalStep] [Android] At My site->Pages, Blog is  displayed in the draft even after publishing it.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-Android#11858]
Environment:
 Samsung Galaxy s9(v10).
 
 Steps To Reproduce:
 
 1. Install and open the application.
 2. log in with valid credentials.
 3. Tap on "My site"
 4. Tap on "Page".
 6. Sroll by side to "drafts"
 5. Tap on "Create" symbol to create blog
 6. Enter any information and from header tap on "Publish".
 7. Pop-up appears tap on "Publish now".
 8. Notice that blog is in the draft, now tap on three dots symbol.
 9. Tap on "Publish now".
 6. Observe that blog is  displayed in the draft even after publishing it.

 Actual Result:
At My site->Pages, Blog is  displayed in the draft even after publishing it.
Note: Observed same on "Posts" tab

 Expected Result:
At My site->Pages, Blog should display in the published after publishing it.

[#11858.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4594743/11858.zip)

**Comment by designsimply** [comment]
I tested with 14.8-rc-3 and I was unable to replicate the problem described where publishing a page from the editor results in the page getting saved as a draft. ([1m13s](https://cloudup.com/cqIvvReV1rF))

<p style="clear:both;"><sup>Tested with WPAndroid 14.8-rc-3 on Pixel 3 Android 10 on Jetpack (shown in the video), Self-hosted, and WordPress.com sites.</sup></p>

I also checked that tapping on More (three dots) > Publish Now from the Site Pages > Drafts list for a draft page results in it getting published normally and displaying in the Site Pages > Published list right after publishing it.

I would like to get a 2nd check on this one if possible. @gglobalstep would you mind doing a quick check of these steps again after switching to 14.8-rc-3 which you should update to by tapping "Update" for the WordPress app in the Google Play Store for your device if you are part of the [beta tester group](https://play.google.com/apps/testing/org.wordpress.android). If you are still seeing the problem, then I will need to loop back and figure out what is different in my tests.

**Comment by gglobalstep** [comment]
This issue is observed to be "Fixed" on following Environment:
Samsung Galaxy s9(v10).
Build WPAndroid [version]: v14.9
