### ISSUE TITLE
[GlobalStep] [Android] Upon changing app language to Hindi, app fails to convert all the app content to Hindi.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-Android#11857]
Environment:
Android: Oppo A57, Samsung Galaxy Tab A (v9), Samsung Galaxy s9 v(10).

Steps to Reproduce:
1. Install and launch the application.
2. Login using valid credentials.
3. Tap on Profile icon.
4. Go to App Settings.
5. Change app language to Hindi.
6. Go to My Site, Reader or Notification.
7. Observe that app text fails to convert to Hindi.

Actual Result:
Upon changing app language to Hindi app fails to convert all the app text to Hindi

Expected Result:
Upon changing app language to Hindi all the text should be displayed in Hindi.

[#11857.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4594719/11857.zip)

**Comment by designsimply** [comment]
Thank you for the report! WordPress relies on volunteers for many translations, especially languages which are not the most heavily used. 

You can see a list of which languages have the most coverage for string translations at https://translate.wordpress.org/projects/apps/android/dev/. We usually we wait until the translation count of strings is at least 75%, and as of today Hindi is at 16% so it has not yet been added to the WPAndroid app.

Anyone interested may become a volunteer and submit translations to help improve coverage for their language. If you, or anyone reading back through this issue later, would like to help translate you can get started by going to https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/.

<sup>(internal reference: p4a5px-1YN-p2)</sup>
