### ISSUE TITLE
[GlobalStep] [Android] Unable to upload document and audio file using upload media as the options are missing.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-Android#11859]
Environment:
Oppo A57(v6.0.1), Samsung Galaxy S9(v10.0), Samsung Galaxy Tab (v9).

Steps to Reproduce:
1. Install and launch the application.
2. Sign In using valid credentials.
3. Create a new site.
4. Tap on Media.
5. Tap on Documents or Audio.
6. Tap on Upload Media button.
7. Note that option is not provided to upload document or audio.
8. Tap on "Choose photo from device" or "Choose video from device".
9. Observe that user is not able to select doc or audio from the device.

Actual Result:
On Media screen, user is unable to upload document and audio file using upload media as the options are missing.

Expected Result:
User should be able to upload document and audio file using upload media.

[#11859.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4594769/11859.zip)

**Comment by designsimply** [comment]
Thank you for the report! We are tracking requests to be able to upload document and audio files at https://github.com/wordpress-mobile/WordPress-Android/issues/4842.
