### ISSUE TITLE
Testing: Fix and re-enable editor UI tests

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#11897]
The [Editor UI tests](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java) were disabled in https://github.com/wordpress-mobile/WordPress-Android/pull/11530 due to failures discussed [here](https://github.com/wordpress-mobile/WordPress-Android/pull/11506#issuecomment-603829709):

> the problem seems to be that the tests expect Aztec (not Gutenberg) but for some reason sometimes Gutenberg is getting enabled.

We should fix those tests and enable both those Aztec editor tests and the [Block editor tests](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java).

**Comment by mkevins** [comment]
I've drafted a PR to allow setting the editor explicitly in the different editor UI tests. It is currently only in draft since the startup time issue for Gutenberg has not been solved yet, but we should have the option now to temporarily enable Aztec only if that becomes a blocker.
