### ISSUE TITLE
BottomNavigation: Multiple fragments are drawn on top of each other

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11910]
When you sign in with a user who doesn't have a site and doesn't follow any sitesthe content can overlap like this (the fragments are drawn on top of each other).

![image](https://user-images.githubusercontent.com/2261188/81807255-0c87b800-951e-11ea-884e-1ff9328d4074.png)

![image](https://user-images.githubusercontent.com/2261188/81807244-085b9a80-951e-11ea-9915-5b820bb74c18.png)

https://github.com/wordpress-mobile/WordPress-Android/pull/11872#pullrequestreview-410102938

**Comment by malinajirka** [comment]
@planarvoid I've just encountered this issue. I thought it's related to the Reader Refactoring, but it's happening even on develop. I'm able to reproduce it 10/10 times after I clear the app data. I think it's related to the changes in the BottomNavigationComponent, wdyt?

**Comment by malinajirka** [comment]
It's a very random guess - but it almost seems like it happens only when `Post-Signup Interstitial` is shown.

**Comment by oguzkocer** [comment]
Hi there! `14.9` is being frozen, so this PR is being bumped to `15.0`. If these changes _have to_ be shipped with `14.9`, please target `release/14.9` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

**Comment by malinajirka** [comment]
I've re-tested the app and this issue is not happening anymore.
