### ISSUE TITLE
Feature request: Open post for editing using intents

### ISSUE THREAD

**Issue by adityabhaskar** [wordpress-mobile/WordPress-Android#11911]
### Expected behavior

The app currently handles intents with `wordpress://post` and `https://wordpress.com/post` URI to open the post editor with a new blank post. In the case of second URI, it optionally takes a `blog_id` or `blogname` as parameter in the pathname, e.g. `https://wordpress.com/post/1231`. If blog_id is present, the new post is created for that site, else for the currently selected site.

The reference code is here: The reference code starts here: https://github.com/wordpress-mobile/WordPress-Android/blob/31cf4fe3094ddf13a86dfdbfdc2455564314652d/WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java#L133

### Requested behavior

Allow specification of a post_id as additional parameter in both these URI to enable opening of a specific post for editing. 

E.g., the URI below would open post with id `786` on site with id `1231` for editing:

`wordpress://post/blog_id=1231&post_id=786`
`https://wordpress.com/post/1231/786`

##### Similar behaviour is already present for viewing a post in the app:

`wordpress://viewpost/blog_id=1231&post_id=786`

---

Following up from feedback by @maxme here https://github.com/wordpress-mobile/WordPress-Android/pull/11550#issuecomment-627168327_

**Comment by maxme** [comment]
Thanks for filling this ticket. I added the `good first issue` label, as I expect this to be fixed easily by changing the receiver in https://github.com/wordpress-mobile/WordPress-Android/blob/master/WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java

It's possible to open the editor for a specific site by using this: 
https://github.com/wordpress-mobile/WordPress-Android/blob/47cb966e1616873746038e881220b2169736a4ca/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L292-L303

**Comment by adityabhaskar** [comment]
Thanks @maxme 

I'll take a shot at fixing this later in the week. 

Cheers!

**Comment by adityabhaskar** [comment]
@maxme , I need a little help.

I've got the app working to open post for editing with a deep link intent, e.g. `wordpress://post?blogId=1&postId=22`. But there's one issue: if the post with `postId` is not already in the `PostStore`, the app is unable to open editor with the post.

The obvious solution to this would be to refresh the posts from server if `postId` (remote post id) is not found in `PostStore`. I need help with this bit:

1. Syncing with server before opening the editor will introduce a delay. Even though this may only happen in cases when the post had not already been synced offline, it may still be bad UX. What are your thoughts on this?
2. I don't know how to sync posts. I'm not well versed with the WordPress-Android source, so a link to some code that does syncing will be helpful.

Cheers!

**Comment by adityabhaskar** [comment]
@maxme Created a PR with the changes. Would love your review. #11996
