### ISSUE TITLE
Reader: Unrelated content overwritten by Discover

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#11957]
**NOTE:** We might want to look into this issue after https://github.com/wordpress-mobile/WordPress-Android/issues/11849 is merged into `develop`.

Note2: I believe this issue is caused by this line - https://github.com/wordpress-mobile/WordPress-Android/blob/a9d79fd56d32ed9d2f541f47eb6d2767c97f4c91/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java#L604. We should at least check we update the tag only when `isTopLevel == true`. However, I'd even consider removing this whole block all together as each top level instance of ReaderPostListFragment displays one of "Following, discover, liked, saved" so there is no need to update it manually in onResume. If we want to request newer posts for Discover everytime, we can simply modify this condition https://github.com/wordpress-mobile/WordPress-Android/blob/bca7d138750581c3ab38698f21b75d5979fc3a04/WordPress/src/main/java/org/wordpress/android/datasets/ReaderTagTable.java#L330.

### Expected behavior
When I open a post detail from a list of posts for a tag, and I go back I should see the list of posts for the tag.

### Actual behavior
When I open a post detail from a list of posts for a tag, and I go back I see "discover.com" and a list of posts for "discover.com".

### Steps to reproduce the behavior
1 - Tap Reader
2 - Tap Discover
3 - Tap post on list
4 - Shown the detail view
5 - Tapped on one of the tags (if there aren't any, just open a different post detail)
6 - Shown a new list of sites related to that tag (with title on view set to the tag)
7 - Tapped on a post from list
8 - Shown the detail view
9 - Tapped Back
10 - Should be shown the tag list.
- Title matches tag
- Contents were the original Discover list not the tag list <- this is not expected

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, API 29

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid 14.6.1 on Pixel 3 Android 10. ([42s](https://cloudup.com/cHeFxdhxclf))

Note: I noticed that in step 9 the tag list is shown after tapping the "x" at top left OR the back button on the device but only for a moment and then it auto-redirects back to the Discover list and the tag label remains stuck at the top.

<img src="https://user-images.githubusercontent.com/1119271/83281895-050b1480-a196-11ea-9d3a-2c6c6c4a5315.gif" width="200" alt="11957-reader-discover-tag-then-back-does-not-show-tag-list-as-expected"> <img src="https://user-images.githubusercontent.com/1119271/83282117-60d59d80-a196-11ea-8adc-eb5e1432fe91.png" width="200" alt="11957-reader-discover-tag-then-back-does-not-show-tag-list-as-expected">

**Comment by ashiagr** [comment]
Closed with #12930 ([tested](https://cloudup.com/cIR4h5A79QR))
