### ISSUE TITLE
Notifications: 2FA login push notification sometimes does not trigger in-app confirmation prompt

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#11958]
### Expected behavior

I expect that if I am logged in to my account with 2FA in the app, and I try to log in to that account on the web, I'll be prompted with a 2FA push notification about the login attempt. When I tap the push notification, I'll be taken to a confirmation prompt in the app where I can ignore or approve the login.

### Actual behavior

Sometimes, tapping the push notification Approve, nothing happens in the web browser.

### Steps to reproduce the behavior

We don't have exact steps to reproduce, but these are the steps used when it happened:

1. Start logged in to the app with a WordPress.com account with 2FA. Ensure you have push notifications enabled on your device.
2. On the web, log in to the same account. At the 2FA step, you should see a message that a push notification was sent to your device for 2FA.
3. When the push notification arrives, tap it.

Result: Sometimes the app opens with the confirmation prompt, but nothing happens in the browser when you click on it.

##### Reported on Pixel 3a, Android 10, WPAndroid 14.6.1

Reported in a [forum post initially here](https://wordpress.com/forums/topic/login-push-notifications/), but also seeing an increasing amount of internal reports about this.

Same issue is reported on iOS as well in https://github.com/wordpress-mobile/WordPress-iOS/issues/13412

**Comment by elibud** [comment]
Fixed https://github.com/Automattic/wp-calypso/pull/42504. Please reopen and mention me if it happens again.
