### ISSUE TITLE
Build Problem: Could not resolve project :react-native-gutenberg-bridge

### ISSUE THREAD

**Issue by plutonem-mobile** [wordpress-mobile/WordPress-Android#11969]
Hi guys.

I just download the version number 14.8 stable and got the issue when i build it.

i did not change anything from resource.

![image](https://user-images.githubusercontent.com/8728579/82507530-18cecf00-9b35-11ea-881b-1af1d221a9cc.png)

**Comment by designsimply** [comment]
Noting the full error in text for reference:

```
ERROR: Unable to resolve dependency for ":libs:editor:WordPressEditor@debug/compileClasspath': Could not resolve project :react-native-gutenberg-bridge.
```

The Gutenberg (WordPress Editor) teams are working to combine the `gutenberg-mobile` repo with the main `gutenberg` project and this may be a side effect of that work. A temporary workaround could be to rebase off of `develop`. Can you give that a try?

<sup>(internal reference: p1590770545421700-slack-platform9)</sup>

**Comment by plutonem-mobile** [comment]
okay, thanks. I will try it later

**Comment by plutonem-mobile** [comment]
i am sorry that i feel a little confused about rebase off of develop, don't know how to achieve this.

can you explain it more specifically?

**Comment by plutonem-mobile** [comment]
Hi, Sheri.

I tried many methods but keep poping this question and it works well before i used version 14.6.

to rebase off develop do you mean when git cloning do not clone from develop branch? i tried this but failed.

**Comment by plutonem-mobile** [comment]
really need help with this one. I need the fresh WordPress version to update my project
