### ISSUE TITLE
Plans: feature lists in the app do not match the web

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11984]
Steps to reproduce:

1. On the web, go to https://wordpress.com/plans and view the Premium feature list.
1. In the app, go to My Site > Plans and view the Premium and Business feature lists.
1. Compare the lists to see if they are the same on the web and in the app.

**Result:** the plan feature lists in the app do not match the web. Specifically, Google Analytics is included in the Premium plan on the web but is not included in the Premium plan on the app.

Web Premium|WPAndroid Premium|WPAndroid Business
---|---|---
<img width="200" alt="Screen Shot 2020-05-21 at May 21 7 18 00 AM" src="https://user-images.githubusercontent.com/1119271/82563978-3a2fbb00-9b35-11ea-8678-aa846e46c0ee.png">|<img src="https://user-images.githubusercontent.com/1119271/82563976-38fe8e00-9b35-11ea-85a7-b55011144f31.png" width="200" alt="wp-1590067729002-premium">|<img src="https://user-images.githubusercontent.com/1119271/82563974-3734ca80-9b35-11ea-8d3d-ba468b8d726b.png" width="200" alt="wp-1590067729014-business">

<p style="clear:both;"><sup>Tested with WPAndroid 14.9-rc-3 on Pixel 3 Android 10.</sup></p>

Support request:

> Confused cause the Google Analytics feature was included in the Business but not in the Premium Plan.

<sup>(internal reference: p4a5px-2z5-p2, 21283866-hc h/t @mlaetitia)</sup>

**Comment by designsimply** [comment]
This requires an API change because the plans were out of date there. Tracking in D43794-code.

**Comment by aerych** [comment]
Fixed via r208293-wpcom
