### ISSUE TITLE
XML-RPC client should follow HTTP redirect (HTTP code 3XX)

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#1198]
Some users reported issues with the XML-RPC calls made by the app, when their servers reply with an HTTP 30X code. At a first glance this seems an edge case, but I noticed from the number of reports we've received that many users are affected by this issue. (users of altervista.org for example).

This is not an issue introduced in 2.7 so I set the Milestone to 2.7.2.

**Comment by rachelmcr** [comment]
I tested and confirmed that the app still follows 301 and 302 redirects notifying the user. I tested in version 4.9-rc-1.

**Comment by maxme** [comment]
We use OkHttp as our only HTTP client in FluxC - should be compliant with the RFC (added fluxc-obsolete label here)

**Comment by aforcier** [comment]
I guess we are still doing this incorrectly in FluxC. 301/302 redirects don't result in a repeat POST request (which is correct), but our discovery process continues and eventually does make a POST request to that URL (our fault, not OkHttp's):

1. User enters a URL that will redirect, let's say iwillredirect.site redirects to redirected.site
2. Direct attempts at `system.listMethods` on iwillredirect.site (with and without /xmlrpc.php added to the URL) fail, as the `POST` redirects to a plain `GET` request on redirected.site
3. We eventually resort to RSD lookup, which fetches the content body of iwillredirect.site
4. This is a GET request, so it gets redirected to redirected.site, which contains an RSD link in its post body
5. The rsd link, which looks like `<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://redirected.site/xmlrpc.php?rsd" />`, is extracted
6. The rsd link is visited, and the xmlrpc.php URL is returned: http://redirected.site/xmlrpc.php
7. The `system.listMethods` is sent to the above URL and succeeds
8. An authenticated `wp.getUsersBlogs` is sent to the URL

I suppose what we should be doing is stopping the process sometime before step 8 and letting the user know the URL we're about to attempt to sign into, and wait for approval. Does that sound right @daniloercoli, @maxme?

**Comment by daniloercoli** [comment]
> I suppose what we should be doing is stopping the process sometime before step 8 and letting the user know the URL we're about to attempt to sign into, and wait for approval.

Yes, manual user intervention is required here.

**Comment by aforcier** [comment]
I'll remove the `fluxc-obsolete` label but leave this issue open to be addressed later on.
