### ISSUE TITLE
[GlobalStep] [Android]  Video is displayed in improper resolution for blog post under readers tab.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-Android#12003]
**Environment:**
Android: Samsung Galaxy s9 (v10).
Build WPAndroid [version]: v14.9

**Steps To Reproduce:**
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Tap on "My site".
 5. Tap on "Create Blog" symbol.
 6. Add any text at title.
 7. From footer tap on "+" to add Video block.
 8. Upload video in video block.
 9. Tap on "Publish" button.
 10. Go to My Site-> View Site and play the video.
 Note that video has proper resolution
 11. Now go to Reader tab, (Assuming your site is in "followed sites" or else Followed Sites> Manage> Enter URL)
 12. Observe that video is displayed in very less resolution screen as compared to View Site.

 **Actual Result:**
 Video is displayed in improper resolution for blog post under readers tab.

 **Expected Result:**
 Video should be displayed appropriately for blog post under readers tab.

**Attachment:**
[#2291.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663062/2291.zip)

**Comment by zwarm** [comment]
@designsimply Looks like this may have already been addressed in 15.2-rc-1 . Please let me know if it's still an issue. Thanks.

<img width="200" alt="Screen Shot" src="https://user-images.githubusercontent.com/506707/86277713-2ef49400-bba5-11ea-915d-a6abe27d68e0.png"/>

**Comment by ashiagr** [comment]
Fixed in 15.2-rc-1
Re-tested same video > appears in the proper resolution 

![video_testing](https://user-images.githubusercontent.com/1405144/121553973-64e5fd80-ca2f-11eb-813f-daa2ff471da2.png)
