### ISSUE TITLE
Prepublishing Nudges : Disable Publish Date on Private Post

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#12009]
### Expected behavior
The Publish Date should be disabled on Private Post since they can't be scheduled. 

### Actual behavior
The Publish Date can be changed even though it won't matter since the post is private.

### Steps to reproduce the behavior
1. Create a new post. 
2. Click Publish Now. 
3. Change Visibility to Private. 
4. Change Publish Date. 
5. Publish and see that it's Immediate. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `feature/prepublishing_nudges` ()

**Comment by designsimply** [comment]
I think the publish date matters for private posts. Shouldn't I be able to publish a private post and update the date so it appears where I want it to in the post list on the front-end?

**Comment by jd-alexander** [comment]
Thanks for asking this @designsimply so does that mean, even though a private post can't be scheduled the person should be able to select a date that is not in the future?

**Comment by designsimply** [comment]
Stepping back a little, I was wondering why a private post can't be scheduled or backdated, but I tested it on Calypso and now I see that you're matching with that behavior and that makes sense to me. See [4m38s](https://cloudup.com/cRMOdukpRYl) for a test showing what I was thinking. Sorry for the noise!

**Comment by jd-alexander** [comment]
Nice. Thanks for checking this out @designsimply This notification got lost in so many that's the reason I am just getting back to you here.
