### ISSUE TITLE
Comments: User's have option to Edit other user's comments on other sites, but it won't save

### ISSUE THREAD

**Issue by msilbers** [wordpress-mobile/WordPress-Android#12011]
### Expected behavior
That people cannot edit comments on other sites, not left by them.

### Actual behavior
User's can tap More, then Edit and appear to have the option to edit comments on other people's sites. The edits do not save but this shouldn't be an option at all.

### Steps to reproduce the behavior
- from a non-a8c account, log in
- you must be following or commenting on a site you are not a user on
- from notifications, tap a comment alert
- tap "More" underneath
- tap Edit
- make any changes
- try to Save

<img src="https://user-images.githubusercontent.com/31680407/82737807-97786780-9d01-11ea-807c-7f14a993df66.jpg" width="200" alt="Screenshot_20200523-135949_WordPress"> <img src="https://user-images.githubusercontent.com/31680407/82737815-9b0bee80-9d01-11ea-9d42-eb2f264c7e8a.jpg" width="200" alt="Screenshot_20200523-135952_WordPress"> <img src="https://user-images.githubusercontent.com/31680407/82737818-9fd0a280-9d01-11ea-96c2-a1164c5e28df.jpg" width="200" alt="Screenshot_20200523-140001_WordPress">

##### Tested on Samsung Galaxy Note 10, Android 10.0, WPAndroid 14.9-rc-1
reported by a user in 2998257-zen

> The "more" button in the panel that shows up for comments...it gives you the ability to go in alter comments...even those on other's sites.

**Comment by designsimply** [comment]
Thank you for the report @msilbers!

Tested and confirmed that I can see the option to edit someone else's comment but I cannot save changes to it. I tested with WPAndroid 14.9-rc-1 on Pixel 3 Android 10 using the steps below. ([1m10s](https://cloudup.com/cEdNWqQ6JKi))

To prepare:

1. Select two users and a site to use for testing.
1. Verify the 2nd user does not have moderate_comments rights on the first user's test site (i.e. user 2 is not a superadmin, admin, or editor on user 1's blog). [#](https://wordpress.org/support/article/roles-and-capabilities/#capability-vs-role-table)

To test:

1. On the web, log in as user 1 (user4712).
1. In the app, log in as user 2 (testuser0313).
1. In the app, leave a comment on user 1's blog (madefortesting471234.wordpress.com).
1. On the web, approve the comment if needed and reply to the comment.
1. In the app, user 2 will see the comment reply in their notifications.
1. In the app, user 2 can tap More > Edit for user 1's comment (this option shouldn't be avail).
1. In the app, user 2 should try to edit user 1's comment and save the change.

**Results:** user 2 is able to see an Edit option for user 1's comment but cannot save the edits.

**Note:** I also tested WPiOS 14.9.0.2 and was not able to see the same problem there. The comment edit option is not shown in the iOS app on a site where I do not have moderate_comments rights. ([screenshot](https://user-images.githubusercontent.com/1119271/82738603-e7513180-9cf5-11ea-9315-dfd57d3787e3.PNG))

<sup>(internal reference: p1590244750387500-slack-mobile-support, 998257-zen cc @tijosh)</sup>

**Comment by elibud** [comment]
@designsimply let's prioritize this one for groundskeeping please.

**Comment by designsimply** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/12012. Props @zwarm. 🎉 

Users should see the update in the 14.9 release. 👍
