### ISSUE TITLE
Media browser: preview broken for private sites

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#12025]
### Expected behavior
When going to the Media section of the app, I expect to be able to browse the available media on my site, with the thumbnails displaying correctly, and be able to see each item in full by tapping on them and getting their preview.

### Actual behavior
On a private site that has just been loaded, it doesn't load videos (some but not all image thumbnails are loaded, I'd think because we're using the authentication code for all Glide requests via GlideAppModule). Videos can't obtain a thumbnail nor be played.

### Steps to reproduce the behavior
1. upload a media item to a site on the web
2. make the site private
3. open the site on a WP app
4. go to media
5. observe you can't preview the uploaded media

**Comment by elibud** [comment]
@khaykov can you please look into this one?

**Comment by mzorz** [comment]
I can tackle this on Thursday if you prefer @khaykov  ( was in my hack week plans anyway) - lmk

**Comment by khaykov** [comment]
@mzorz Sure! Thank you 🙇
