### ISSUE TITLE
No Background When Paging Between Notifications

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#12040]
### Expected
The background is opaque when paging through notifications in ***Notifications*** like paging through revisions in ***History***.

### Observed
The background is transparent when paging through notifications in ***Notifications*** unlike paging through revisions in ***History***.  See the screenshots below for illustration.

![paging_background](https://user-images.githubusercontent.com/3827611/83036195-8bd5bb00-9ff7-11ea-81a2-1c6d0c5de9e9.png)

### Reproduced
1. Go to ***Notifications***
2. Tap any notification in list.
3. Swipe left/right to page through notifications.
4. Notice entering notification has no background.

##### Tested
Google Pixel 2 on Android 10.0 with WordPress Android 14.9-rc-2

**Comment by develric** [comment]
This is still valid as of today in current develop (at this point in [history](https://github.com/wordpress-mobile/WordPress-Android/tree/a860d8b29eb097aed016d28092021c4fa756a2c4)).

Tested on Pixel 4 Emu API 29.
