### ISSUE TITLE
Add the ability to search the post list for self-hosted site

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#12058]
### Expected behavior

I expected that any kind of site I added to the app would give me the option to search the post or page list.

### Actual behavior

Only WordPress.com/Jetpack sites have the option for this feature. 

### Steps to reproduce the behavior

1. Go to My Site and select a WordPress.com site.
2. Go to Blog Post List
3. You'll see the search icon in the top menu.
4. Go back to My Site and select a self-hosted site. 
5. Go to Blog Post List
6. The icons doesn't display and there is no way to search through posts.

##### Tested on Samsun Tab A, Android 9, WPAndroid 14.9-rc-1

It does look like this was implemented purposefully in #10023, but it was requested by a user with a self-hosted site in 3002439-zen and kind of caught me off guard since I didn't realize this behaviour would be different. I wasn't able to find another report of this anywhere that wasn't related to the old PR.

**Comment by designsimply** [comment]
I tested and found that the pages list is searchable for self-hosted sites, but the posts list is not.

Comparing Self-hosted > My Sites > Blog Posts screen to the same screen for a WordPress.com site:

Blog Posts for Self-hosted Site|Blog Posts for WordPress.com Site
---|---
![Screenshot_20200602-141102](https://user-images.githubusercontent.com/1119271/83581901-46d0ed80-a4fd-11ea-9038-3c9043d869dd.png)|![Screenshot_20200602-141232](https://user-images.githubusercontent.com/1119271/83582005-8d264c80-a4fd-11ea-83b1-4b19ff41189c.png)

<p style="clear:both;"><sup>Tested with WPAndroid 15.0-rc-1 on Pixel 3 Android 10 with frightened-hazel.jurassic.ninja (Self-hosted, left) and artindesignco.blog (WP.com, right).</sup></p>

The Pages List, in contrast, did have a working search option for a self-hosted site when I tested:

Site Pages on a self-hosted site showing search icon|Pages search on a self-hosted site|Working Pages search on a self-hosted site
---|---|---
![Screenshot_20200602-141112](https://user-images.githubusercontent.com/1119271/83582089-c8c11680-a4fd-11ea-8dc1-3be44db124ba.png)|![Screenshot_20200602-141157](https://user-images.githubusercontent.com/1119271/83582084-c6f75300-a4fd-11ea-89d7-3e0ebb71fbae.png)|![Screenshot_20200602-141136](https://user-images.githubusercontent.com/1119271/83582086-c8288000-a4fd-11ea-92fd-4bea87106f44.png)

<p style="clear:both;"><sup>Tested with WPAndroid 15.0-rc-1 on Pixel 3 Android 10 with self-hosted site frightened-hazel.jurassic.ninja.</sup></p>

**Comment by rachelmcr** [comment]
This came up in feedback from a beta tester:

> Is it really possible that I can't find a post by searching? If the function is not there, it cannot be used for anything.
