### ISSUE TITLE
Keep facing build problem after downloading latest version

### ISSUE THREAD

**Issue by plutonem-mobile** [wordpress-mobile/WordPress-Android#12120]
Hi, guys. I did download several times latest version 14.8, 14.9, when i start to build the project, Andrioid Studio keep showing "Unable to resolve dependency for ':libs:editor:WordPressEditor@debug/compileClasspath': Could not resolve project :react-native-gutenberg-bridge."

I never faced this issue when i use version no.14.6 so it stucks me many days, really need help here!

**Comment by gibtang** [comment]
I am having the same issue too. Can't build and deploy to device

**Comment by mchowning** [comment]
:wave: @plutonem-mobile and @gibtang ! Can you check and make sure that your `libs/gutenberg-mobile` submodule is up to date. First, make sure that you don't have any changes in the`libs/gutenberg-mobile/` directory, and then run `git submodule update --init --recursive`. If you still get an error after that, please try deleting the `libs/gutenberg-mobile/` folder and then running that same git submodule command.

Sorry you're running into these issues. We're in the process of making some changes to how the build process handles gutenberg-mobile, and we know there are still some rough edges we need to take care of, so thanks for bringing this up! :bow:

**Comment by plutonem-mobile** [comment]
ok, thanks @mchowning . I will give it a try later

**Comment by plutonem-mobile** [comment]
thanks @mchowning . I will give it a try later.

**Comment by plutonem-mobile** [comment]
that command works quite good. I just finished my build without any problem!

and i see you just add this command suggestion in introduction page, very good hint here.

![image](https://user-images.githubusercontent.com/8728579/84210705-fa347600-aaeb-11ea-97ee-801c757bcb86.png)

thanks again @mchowning .

**Comment by plutonem-mobile** [comment]
bad news, bad news. I want to edit the previous comment.

yes, after i render the command "git submodule update --init --recursive", it did work at first - retrieving files about gutenberg, but when i build the project in Android Studio, the error becomes

"Process 'command 'libs\gutenberg-mobile\react-native-gutenberg-bridge\android\null\jsbundle\null\yarn\yarn-v1.22.4\yarn.cmd'' finished with non-zero exit value 1"

and even if i tryb deleting the libs/gutenberg-mobile/ folder and run that command again, i still face the same error code here.

may be something bad happened about yarn? i don't know.

**Comment by plutonem-mobile** [comment]
@oguzkocer @mchowning you guys are so adorable, thank you so much for the time being spent on catching up this problem!

yes, the system i use to develop with wordpress is windows, a little bit wield ha~. i did not change my system for a very long time. 

@mchowning i will try the command line build way later, if i have good luck there, i will let you know!

thanks guys again and wish you could solve this build issue soon as possible as i really want to use the latest version of wordpress to continue the project.

for now probably the only option i could choose is to go back to version 14.6 temporarily, sad....

**Comment by oguzkocer** [comment]
@plutonem-mobile Here is a workaround that is working for me on Windows:

1. Add `wp.BUILD_GUTENBERG_FROM_SOURCE=true` to your `gradle.properties` file
2. Run the app
3. Go to your site's settings and disable the block editor: `My Site` -> `Settings` -> `Use Block Editor`

The reason this works is because the first step will turn the block editor to a runtime dependency instead of a compile-time dependency. (which is the build failure you experience) If you try to use the block editor with this setup, it'll likely crash because you'll need to setup your local environment to support it. However, with the 3rd step you can use the previous editor, which is completely native and the app will just work fine.

Let me know if you have any questions.

**Comment by mchowning** [comment]
Thanks so much @oguzkocer ! 

When buildign with `wp.BUILD_GUTENBERG_FROM_SOURCE` set to `true`, you will also need to run `yarn install` from inside the `libs/gutenberg-mobile` folder. Also, you should re-run that command to refresh your `libs/gutenberg-mobile/node_modules` dependencies anytime you switch to a branch that uses a different submodule for gutenberg.

**Comment by plutonem-mobile** [comment]
Hi, guys.

I just followed @oguzkocer method to add the configuration command to gradle.properties file. and after that i build it, AS tells me to manually run "yarn install" just as @mchowning said.

but after i download yarn (i never used this tool before) and type the command, i got this error

![image](https://user-images.githubusercontent.com/8728579/84670771-1bb4b800-af59-11ea-8790-289c24663073.png)

it seems like something bad happened about install process, i am not sure if it is my personal system problem or not.

I cannot run the app directly without yarn install process after add wp.BUILD_GUTENBERG_FROM_SOURCE=true to the properties file.

**Comment by plutonem-mobile** [comment]
@oguzkocer did you face the same problem after building with wp.BUILD_GUTENBERG_FROM_SOURCE set to true that AS tells you to manully run "yarn install" command?

**Comment by plutonem-mobile** [comment]
I also tried a second way to build with wp.BUILD_GUTENBERG_FROM_SOURCE set to true.

after i download the latest version of wordpress, i followed @mchowning previous answers:

![image](https://user-images.githubusercontent.com/8728579/84673429-45231300-af5c-11ea-8219-de0aaf47905f.png)

to update libs/gutenberg-mobile submodule. and after that, i set wp.BUILD_GUTENBERG_FROM_SOURCE to true then start building. this time, the AS does not reporting error at first and everything goes fine (downloading lots of necessary packages) but after a while. it turns out to be this output:

![image](https://user-images.githubusercontent.com/8728579/84673704-a64ae680-af5c-11ea-9f17-80b6e9c97616.png)

failed again.

i must say this whole new building process really challenges me a lot more than before. hope you could replace it with more easier way.

**Comment by oguzkocer** [comment]
@plutonem-mobile About the issue with `yarn`, I've seen it happen on Windows for other people as well and unfortunately it's an issue with `yarn` and not the project. We don't have a lot of experience with `yarn` on Windows, so I don't think we can help much there. However, I use [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) to use `yarn` and that works fine, so if you have `WSL` setup, maybe you can look into that?

About the error you attached the screenshots for, can you try changing the build variant you're using to `vanillaDebug` or any of the ones that has `Debug` in it. The release build variants may expect some credentials you won't have access to. Once you fix this issue, you'll still need to run `yarn install` successfully at least once or otherwise you'll get another build issue.

> i must say this whole new building process really challenges me a lot more than before. hope you could replace it with more easier way.

Hopefully this will be fixed soon.

**Comment by plutonem-mobile** [comment]
Hi, @oguzkocer 

it is being a little bit long time for me to test the build again.

not cool for me, i still got build issue on this one, even if i am using WSL to do the yarn install.

my whole process is: 

1. git clone wordpress from github.
2. cp gradle.properties-example gradle.properties to set up the sample app credentials file.
3. open the project in android studio and add wp.BUILD_GUTENBERG_FROM_SOURCE=true in gradle.properties file.
4. run yarn install in libs/gutenberg-mobile folder from WSL Ubuntu 20.04 TLS (at this time, i got the following response, i think it's working)
![image](https://user-images.githubusercontent.com/8728579/85876589-880ca280-b808-11ea-9e57-6472f8c725eb.png)
5. return to android studio and starting build project.
6. got this error: 
![image](https://user-images.githubusercontent.com/8728579/85877012-1c770500-b809-11ea-8af6-f99c2b9bfe9f.png)

@oguzkocer can you please show me your whole building process that works well in windows? so i can follow exactly what you've done. May be i forgot to download some components or missed some core steps?

**Comment by plutonem-mobile** [comment]
Is it possible that i did not install some environmental components to make this building process work on windows?

cause from what i know when trying to build wordpress on mac os x this morning(btw, it works fine unlike windows), i did not install yarn and nodejs at first, so i met two issues during that time, one is to tell that i need to install yarn and the second is to tell i need to install nodejs.

so maybe i missed some core components that is needed in windows environment to finish building?

**Comment by mchowning** [comment]
Sorry about the issues @plutonem-mobile .

> not cool for me, i still got build issue on this one, even if i am using WSL to do the yarn install.

**Comment by mchowning** [comment]
Sorry this is so painful on Windows currently. We know this is broken and needs to be fixed.

> i still got build issue on this one, even if i am using WSL to do the yarn install.

If you're using the latest code, we just merged to `develop` an update that switched from `yarn` to `npm`, so the command to run from `libs/gutenberg-mobile/` is now `npm install`. Perhaps give that a try. `npm install` will take a while if it's working, and afterwards you should see a bunch of files in the `libs/gutenberg-mobile/node_modules/` and `libs/gutenberg-mobile/gutenberg/node_modules/`.

**Comment by plutonem-mobile** [comment]
Hi @mchowning , thank you so much for the suggestion gave before.

at this moment, i just use my mac to run the latest wordpress and my windows to do the developing. Although it's a little bit annoying that i need to switch to mac to see what's going on when running, i can handle that, anyway.

hope you guys could fix this issue soon or later so that i do not need to switch machine anymore /laugh.

**Comment by kaytat** [comment]
@mchowning I've tried the latest and I'm still having issues building on Windows. Looking at logs a little closer, the error I'm seeing is "The syntax of the command is incorrect." and specifically it's the command "mkdir -p ..." in the "bundle:android:text" script of gutenberg-mobile/package.json

Seems like cmd.exe's mkdir doesn't like the -p option.

I did try manually creating that directory and removing mkdir and the build proceeds a little further but then starts complaining about "Import statement may only appear at top level" which I was unable to debug.

The workaround suggested with using wp.BUILD_GUTENBERG_FROM_SOURCE=true works for me.

**Comment by mchowning** [comment]
Thanks to [some really great work](https://github.com/wordpress-mobile/WordPress-Android/pull/14175) by @oguzkocer and @mokagio  🙇 , mobile-gutenberg is now a regular binary dependency for WPAndroid. That means the build is _much_ simpler (and faster) now and 🤞 , the problems discussed in this thread should no longer happen.
