### ISSUE TITLE
Notifications content drawn on top of the previous state

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#12136]
### Expected behavior
When I open notifications tab I see only the current content of the tab.

### Actual behavior
When I open notifications tab I see the current content drawn on top of the previous content.

### Steps to reproduce the behavior
1. Log in with a .com account
2. Add a self-hosted site using the self-hosted login
3. Click on Notifactions
4. Click on My Site
5. Open App Settings
6. Log out of .com account
7. Open Notifications and notice the content is broken
--------------------------------
1. Log in with a self-hosted site
2. Open Notifications
3. Connect Jetpack
4. Boom

![notifs-frg](https://user-images.githubusercontent.com/2261188/84127153-29d97480-aa3f-11ea-82bc-9d4c62d35e69.gif)

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, Pixel 2, API 27

**Comment by elibud** [comment]
@malinajirka is this good to close?
