### ISSUE TITLE
[GlobalStep] Android - “Play on SoundCloud” button does not function. 

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#12164]
**Describe the bug**
When creating a post containing a SoundCloud shortcode a soundcloud box is present with 2 buttons “Play on SoundCloud” and “Listen in browser”. The “Play on SoundCloud” button would always produce an error “Unable to open the link”. 

** Reproduction Rate**
4/4 100%

**To Reproduce**
1. Launch WordPress wpandroid-14.1-rc-1-universal.apk
2. Log into an account
3. Create a post with a valid soundcloud shortcode  (e.g. [soundcloud url =”https://soundcloud.com/chvrches/death-stranding”]
4. View the post. 
5. Tap “Play on SoundCloud”. 

**Expected behavior**
The soundcloud app should open and play the song. 

**Actual behavior**
An error message appears stating the link cannot be opened. 

**Tested on**
Samsung Galaxy S8 (7.0) 
Huawei P30 Pro (9.0) 

Please see attached video 
[PlayOnSoundCloud Android.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4139781/PlayOnSoundCloud.Android.zip)

**Submitted By**
Alex Wood

**Comment by rachelmcr** [comment]
I tested with WPAndroid Alpha-231 on moto e5 play, Android 8.1.0, and cannot reproduce the issue. When I tap on "Play on SoundCloud," I am shown an action sheet to select what app I want to use to open the link.
