### ISSUE TITLE
[GlobalStep] There is a refresh button with no functionality when previewing a post.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#12163]
### Description
While editing or creating a post if the user selects the preview option from the triple dot icon there is a refresh icon in the upper right, however this doesn’t appear to serve a function as while the user is previewing a post they haven’t published no changes would be seen until backing out of the preview and making further edits.

### Reproduction Rate
4/4 100%

### Expected behavior
All buttons on screen serve a functional purpose.

### Actual behavior
A refresh button is present without functionality.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Add any text or media.
6. Select the triple dot icon in the upper right.
7. Select ‘Preview’.
8. Tap the refresh button in the upper right.

##### Tested on the following
Huawei P10 (7.0)
iPad Air 3 (13.2.3)

#### Please see the attached screenshot for more information.
<img width="270" src="https://user-images.githubusercontent.com/60415523/74349808-ac616880-4dac-11ea-9a62-80a7a54c3adc.jpg" />

### Submitted by:
Oliver Howe

**Comment by rachelmcr** [comment]
Given the possible refresh purposes noted above, I'm going to close this issue.
