### ISSUE TITLE
Unified Login & Sign-Up: Disabled buttons style doesn't match design spec

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#12242]
This is part of the **Unified Login & Sign-Up** project.

### Expected behavior
Disabled buttons should have the new style shown in the design spec (outlined with no fill, with light gray text) — internal ref: pbArwn-mA-p2.

### Actual behavior
Disabled buttons are not outlined and have a gray fill.

**Comment by mattmiklic** [comment]
Hey @renanferrari -- after reading your [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/12048#issuecomment-646899288) on #12048 I think we should leave the disabled style as-is. After re-reading the material design [documentation for disabled styles](https://material.io/design/interaction/states.html#disabled) I think what we have in place already is better than the outlined style I'd specified in the login designs.

**Comment by renanferrari** [comment]
@mattmiklic Thanks for your input, I'm closing this then.
