### ISSUE TITLE
[Quick Start] Add initial "Set a site title" step

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-Android#12251]
Since we removed choosing a site title from the site creation flow, we'd like to move it to be the first step in the Quick Start process.

**Gridicon:** pencil
**Title:** "Set your site title"
**Description:** "Give your site a name that reflects its personality and topic. First impressions count!"

**Steps**

* "Tap _Site Title_ to set a new title" (replace Site Title with the current site name, and show a spotlight on it in the site header)
* The usual popup menu will be displayed, and a spotlight will be shown on the site title row in Site Settings, as per #12250. Visiting the Site title screen will check off this tour.

**Comment by khaykov** [comment]
Done in #12290
