### ISSUE TITLE
RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.sitecreation.SiteCreati...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12260]
This is a weird issue as I don't know how `ImageView` wouldn't be available. It's also only happening to 64 users, but it's happening to them _a lot_ that I felt the need to report it.

**Sentry Url**: https://sentry.io/share/issue/027fed659e884718ac18307ff8de680e/
**User Count**: 64
**Count**: 1804
**First Release**: org.wordpress.android-12.4
**First Seen**: 2019-05-11T18:15:12Z
**Last Seen**: 2020-06-23T13:40:55Z
**24 Hours**: 0
**30 Days**: 27

```
RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.sitecreation.SiteCreationActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class ImageView
     at org.wordpress.android.ui.sitecreation.SiteCreationBaseFormFragment.createMainView(SiteCreationBaseFormFragment.java:43)
     at org.wordpress.android.ui.sitecreation.SiteCreationBaseFormFragment.onCreateView(SiteCreationBaseFormFragment.java:49)
...
(39 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
**Events:** 1,800
**Users affected:** 67
<sub>WORDPRESS-ANDROID-13C: https://sentry.io/share/issue/027fed659e884718ac18307ff8de680e/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1039914269&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85980709-254e0f00-b9a0-11ea-9322-5ec2c646a96c.png)</a>

**Comment by designsimply** [comment]
**Events last 90d:** 2,000
**Users affected last 90d:** 45
**Majority of cases recorded are for:** Android 8.1.0 and below (plus 2 reports for Android 9)
<sub>WORDPRESS-ANDROID-13C: https://sentry.io/share/issue/027fed659e884718ac18307ff8de680e/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1039914269&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96306223-7ff59000-0fbc-11eb-807d-8d5606c2f692.png)</a>

**Comment by designsimply** [comment]
**Events last 90d:** 2,100
**Users affected last 90d:** 30
**Majority of cases recorded are for:** Android 6.0.1 with nothing reported in the last 90d above Android 8.1.0
<sub>WORDPRESS-ANDROID-13C: https://sentry.io/share/issue/027fed659e884718ac18307ff8de680e/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1039914269&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100304712-9815e300-2f5c-11eb-82ad-000c1da54fdd.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 2,100
**Users affected in the last 90d:** 13
**Limited to:** Android 5, 6, & 8.1.0
**App versions affected:** No recent cases in any version higher than 16.1
**Culprit:** `android.app.ActivityThread in performResumeActivity`
<sub>WORDPRESS-ANDROID-13C: https://sentry.io/share/issue/027fed659e884718ac18307ff8de680e/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1039914269&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105400133-c40eb700-5be1-11eb-968f-98f73f26e2f2.png)</a>

This crash no longer appears to be happening in the latest few releases and has very low instances that have continued to trend down. Recommend closing.
