### ISSUE TITLE
Persist Snackbars during the Quick Start tour

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#12261]
When Quick Start automatically goes to the next tip, it can sometimes auto-dismiss before there is time to read it. We also auto-dismiss the tips while persisting the dot target.

For the next tips, there is already a Not Now button if I don’t want to see it. 

In all locations, we should have another mechanism to dismiss. I suggest we dismiss it when the user taps.

**Comment by khaykov** [comment]
@osullivanchris Dismissing snack bar when user taps on it is a bit challenging (without interfering with other buttons). You can dismiss it by swiping it to the right. This not super intuitive, so I wonder, should we still auto dismiss it after some time? We can double or triple the current delay.

**Comment by osullivanchris** [comment]
@khaykov yeah that seems fair. We wouldn't want to keep it _forever_ in the case the user doesn't discover the correct mechanism to dismiss it. Doubling the time seems like a safe bet. Go for it!
