### ISSUE TITLE
Quick Start Tour repeats previous step

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#12278]
### Steps to reproduce the behavior

- I went to the Grow Your Audience guide
- The first step is 'Enable Post Sharing'
- I didn't have Facebook or anything logged in on the device I'm on, so I skipped
- I completed step two: 'Publish a Post'
- I then automatically get prompted with the next tip

### Expected behavior
I expect to see the next tip in the list (in this case, tip 3)

### Actual behavior
The next prompt I got was 'Enable Post Sharing' again. It felt annoying as I had decided not to do that right now. 

I think it should go forward to step 3, and not auto prompt a step I have seen already. Might take some investigation to figure out how to generally apply this logic, or where the existing logic is coming from.

**Comment by startuptester** [comment]
Reopening because the skipped step still shows as incomplete in the Quick Start list

**Comment by startuptester** [comment]
@yaelirub I'm not sure if I should link this to #13888 or just leave this one as closed?

**Comment by renanferrari** [comment]
Just a heads-up that we're currently reworking several aspects of Quick Start tasks as part of the [My Site Dynamic Cards project](https://github.com/orgs/wordpress-mobile/projects/79) (internal ref: pbArwn-1fl-p2), so we should probably be cautious when considering which changes to make right now, as they may become obsolete soon.

**Comment by startuptester** [comment]
That's such a good point, @renanferrari, thank you! 
#13888 and re-opening this were part of some bug prep I was doing for the [Focused Site Creation](https://github.com/orgs/wordpress-mobile/projects/82) project
cc: @yaelirub
