### ISSUE TITLE
WordPress Stories : Refactor post type boolean flags to enum

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#12316]
Create an enum that we can utilize to determine the type of post that's triggering the bottom sheet as described [here](https://github.com/wordpress-mobile/WordPress-Android/pull/12307#discussion_r446934266)

https://github.com/wordpress-mobile/WordPress-Android/blob/e30d89d991d5be36078a47af7b56910efee2593d/WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt#L341

> can we consist these 2 flags into an enum that holds Post, Page, Story post type of values? So we wouldn't be passing around 2 variables when we could pass one, and moreover we would make sure to not allow any ambiguities or impossible states such as isPage and isStoryPost being both true (which cannot be)

Also do refactoring of view types within the `PrepublishingViewHolder`https://github.com/wordpress-mobile/WordPress-Android/pull/12306#discussion_r446943631

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
