### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null objec...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12343]
Another minor NPE that might be a good candidate for quick wins during Groundskeeping.

**Sentry Url**: https://sentry.io/share/issue/44c38036c5a7459facd6ec94f08111b9/
**User Count**: 2
**Count**: 3
**First Release**: org.wordpress.android@15.1+885
**First Seen**: 2020-07-02T05:46:33.863000Z
**Last Seen**: 2020-07-02T18:25:27Z
**24 Hours**: 3
**30 Days**: 3

```
NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
     at org.wordpress.android.ui.uploads.UploadService.getRetriableStandaloneMedia(UploadService.java:1066)
     at org.wordpress.android.ui.uploads.UploadService.onMediaUploaded(UploadService.java:916)
...
(2 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Adding to groundskeeping

**Comment by designsimply** [comment]
**Events in the last 90d:** 38
**Users affected in the last 90d:** 13
<sub>WORDPRESS-ANDROID-FC1: https://sentry.io/share/issue/44c38036c5a7459facd6ec94f08111b9/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1758312274&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/90943379-f7e97480-e3d6-11ea-97c8-95467bc8d5ff.png)</a>

Noting this one has a very low number of occurrences in the first 50 days of it being around.

**Comment by designsimply** [comment]
**Events in the last 90d:** 81
**Users affected in the last 90d:** 22
<sub>WORDPRESS-ANDROID-FC1: https://sentry.io/share/issue/44c38036c5a7459facd6ec94f08111b9/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1758312274&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96306050-2725f780-0fbc-11eb-84ef-6b8266a25a87.png)</a>
