### ISSUE TITLE
Bug: 'Problem displaying block' error given when changed the property of an element and switched to blocks editor

### ISSUE THREAD

**Issue by ahmet-izgi** [wordpress-mobile/WordPress-Android#12361]
### Expected behavior
Elements added on the classic editor should be converted when switched to blocks editor. (Tried with list and image elements)

### Actual behavior
‘Problem displaying block’ error is given

#### List
1. Create a new post 
2. Add unordered list
3. Enter some values 
4. Switch to classic editor 
5. Change list type to ordered list 
6. Switch to blocks editor

#### Image
1. New post 
2. Add image 
4. Select/Upload an image
3. Switch to classic editor 
4. Change any attribute on Media Settings
5. Switch to blocks editor

##### Tested on [device], Android [version], WPAndroid [version]
PIXEL 2 API 30 Emulator, WordPress 15

Same as wordpress-mobile/WordPress-iOS#14426 for iOS

**Comment by rachelmcr** [comment]
Closing per the issue already reported at https://github.com/wordpress-mobile/gutenberg-mobile/issues/2282. As noted there:

> Seamless editing from the classic editor to -> the block editor is not supported and is not planned to be supported either.
