### ISSUE TITLE
WordPress Stories : Capitalize title text in bottom sheet

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#12408]
Portkey reference issue https://github.com/Automattic/portkey-android/issues/416

## Expected behavior
The story title text should make the first letter of the sentence a capital letter. 

## Actual behavior
Its not a capital letter. 

### Steps to reproduce the behavior
1. Create a new story post. 
2. Click Publish. 
3. Enter a story title and realize the first letter isn't capitalized. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by mzorz** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/12521
