### ISSUE TITLE
Login: Illustration on "What's my site address?" dialog is not properly sized

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#12422]
### Steps to reproduce the behavior
On the Site Address screen, tap the “Find your site address” button and notice how the illustration in the "What's my site address?" dialog is not properly sized:

<img src="https://user-images.githubusercontent.com/830056/87180023-1b88ad80-c2b6-11ea-9d19-521c51f399ed.jpg" width=320/>

Note: these steps were originally provided by @rachelmcr in pbMoDN-ET-p2#comment-1307

**Comment by planarvoid** [comment]
I couldn't reproduce this issue on either emulator or my phone. Is this tied to a specific system version or was it already fixed? 

![Screenshot_20210510-110517](https://user-images.githubusercontent.com/1079756/117634923-af99fe80-b17f-11eb-86f1-2ca3d9dfe5bd.png)

**Comment by rachelmcr** [comment]
@planarvoid I still see the original issue on my device (Moto e5 play, Android 8.1.0), so it might be specific to the system version I have. (I don't get Android updates on this device.)

**Comment by planarvoid** [comment]
Thanks for the check! I was checking issues for things that could be closed so let's keep this open.
