### ISSUE TITLE
InflateException for design_password_eye in Login

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12466]
There was a similar `InflateException` that we fixed about `design_password_eye` in #9905, but this might be more similar to the recently fixed https://github.com/wordpress-mobile/WordPress-Android/issues/12396. There are quite a few users having this crash, but it's also dating far back.

**Sentry Url**: https://sentry.io/share/issue/bd1fcd0ffbc44e2eb80c97e2d1801f01/
**User Count**: 141
**Count**: 1427
**First Release**: org.wordpress.android-12.3-rc-2
**First Seen**: 2019-05-11T09:10:01Z
**Last Seen**: 2020-07-16T13:50:42Z
**24 Hours**: 27
**30 Days**: 229

```
InflateException: Binary XML file line #111: Error inflating class <unknown>
     at org.wordpress.android.login.widgets.WPLoginInputRow.init(WPLoginInputRow.java:82)
     at org.wordpress.android.login.widgets.WPLoginInputRow.<init>(WPLoginInputRow.java:48)
     at org.wordpress.android.login.LoginBaseFormFragment.createMainView(LoginBaseFormFragment.java:103)
     at org.wordpress.android.login.LoginBaseFormFragment.onCreateView(LoginBaseFormFragment.java:109)
...
(41 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
**Events in the last 90d:** 2,000
**Users affected in the last 90d:** 96
<sub>WORDPRESS-ANDROID-AT: https://sentry.io/share/issue/bd1fcd0ffbc44e2eb80c97e2d1801f01/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1021808172&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96308445-a5849880-0fc0-11eb-99b9-c52aed845f1c.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 2,200
**Users affected in the last 90d:** 56
<sub>WORDPRESS-ANDROID-AT: https://sentry.io/share/issue/bd1fcd0ffbc44e2eb80c97e2d1801f01/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1021808172&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100553635-1d92df00-324c-11eb-9c01-4d9d758124b8.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 2,100
**Users affected in the last 90d:** 36
<sub>WORDPRESS-ANDROID-AT: https://sentry.io/share/issue/bd1fcd0ffbc44e2eb80c97e2d1801f01/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1021808172&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105405963-01c30e00-5be9-11eb-8f48-395a936d5eb8.png)</a>

Very few occurrences (19) were recorded for versions 16.0 through 16.4 in the last 90 dyas:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1021808172+version%3A16.%2A&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105406200-55355c00-5be9-11eb-9423-913d0a3a7b55.png)</a>

Recommend closing.
