### ISSUE TITLE
Bug: The 'Use Block Editor' switch within the 'Site Settings' screen is misbehaving

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#12529]
### Expected behavior
Clicking on the `Use Block Editor` switch setting to disable it, within the Site Settings screen, it should disable the setting.

### Actual behavior
When clicking on the `Use Block Editor` switch setting to disable it, within the Site Settings screen, it immediately switches on again. Only after doing that consecutively from more than 3 times, sometimes 10 times in a row, it disables this setting. On the other hand, when clicking on the `Use Block Editor` switch setting to enable it, it works as expected.

### Steps to reproduce the behavior
1. Open `My Site`
1. Choose a `site`
1. Make sure you have access and can navigate to this site's `Configuration -> Settings` screen
1. Navigate to the `Settings` screen
1. Find the `Use Block Editor` switch
1. If the switch is `enabled`, try to `disable` it
1. After an attempt to `disable` it, you should see it to automatically switch back to an `enabled` state
1. Try to `disable` it again, this time persist few times, from 3 to 10 times, it should succeed at some point
1. Now that the switch is `disabled, try to `enable` it
1. This part should succeed with no problem

##### Tested on [device], Android [version], WPAndroid [version]
Tested on Pixel 2 XL, Android 10, WPAndroid 15.3-rc-2

**Comment by jhnstn** [comment]
Issue still happens for me on Pixel 5 (Android 11) WPAndroid 17.0-rc-2

**Comment by hypest** [comment]
The toggle is [no longer available](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3092#issuecomment-851699842) so, I'll go ahead and close this ticket. That said, happy to reopen if it still holds for any flow, and we can adjust the description accordingly. Thank you all!
