### ISSUE TITLE
Reader doesn't respect the Media & Text block settings to "Crop image to fill entire column" or "Show image on right" 

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12544]
Steps to reproduce:

1. Create a new post.
1. Add a Media & Text block.
1. Tap "Add image or video".
1. Tap "Choose from Free Photo Library".
1. Search for, select, and insert an image.
1. Tapp "Show image on right" button.
1. Tap the cog icon to open block settings.
1. Turn on the "Crop image to fill entire column" option. 
1. Publish the post.
1. View the post in the Reader.

**Result:** in the Reader, the image is not cropped to fit the entire column and the image isn't shown on right (with text stacked above in a small screen view) as they are in a web view. ([2m42s](https://cloudup.com/cLUNl47N3Qw))

"Show image on right" setting|"Crop image to fill entire column" setting|Preview|Reader
---|---|---|---
<img width="480" alt="Screen Shot 2020-07-28 at Jul 28 5 15 22 PM" src="https://user-images.githubusercontent.com/1119271/88738572-96472a80-d0f6-11ea-8aec-76f77e95b8ef.png">|<img width="480" alt="Screen Shot 2020-07-28 at Jul 28 5 15 32 PM" src="https://user-images.githubusercontent.com/1119271/88738613-99dab180-d0f6-11ea-83a2-4712f515056d.png">|<img width="480" alt="Screen Shot 2020-07-28 at Jul 28 5 15 51 PM" src="https://user-images.githubusercontent.com/1119271/88738643-9c3d0b80-d0f6-11ea-878e-074db8333051.png">|<img width="480" alt="Screen Shot 2020-07-28 at Jul 28 5 21 10 PM" src="https://user-images.githubusercontent.com/1119271/88739039-c393d880-d0f6-11ea-9455-4831f91eed32.png">

<p style="clear:both;"><sup>Tested with WPAndroid 15.4-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by zwarm** [comment]
@designsimply 
I wanted to recap what I am reading
1 - The text is not top stacking when right align (There is a prior rule for screens smaller than 660px that ignores left/right alignment requests - we've discussed this rule when we did the work for social media link icons)
2 - The image doesn't fill entire column

Take a look at this [video](https://d.pr/v/SYHAkj ) for 15.7-rc-1. The right alignment text always aligns at the bottom for preview, live, and reader (I did not screen shot reader). This is different from your video for 15.4. I'm not sure what I need to do for this one or if anything needs to be done at all. I'll be looking into number 2.  Thanks.

@designsimply -
FYI: 
The first issue has to wait on calypso normalizing some styles
PR #12929 takes care of the second issue

**Comment by designsimply** [comment]
I re-tested and I see what you mean about the text always stacking below the image now, so now it looks like Gutenberg Mobile is the only place where the stacking order changes if the "Show media on right" setting is on—which isn't critical but is inconsistent. I think it's worth a mention as a nitpick and I'll file an issue for it in the `gutenberg-mobile` repo since that's the only place it seems to be stacking inconsistently now.
