### ISSUE TITLE
Reader doesn't display Social Icons block with correct formatting, alignment, or colors

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12545]
Steps to reproduce:

1. Create a new post.
1. Add a Social Icons block.
1. Add a URL for several of the icons.
1. Center the icons.
1. Publish the post. 
1. View the post in the Reader.

Results, in the Reader:

* Social Icons appear in a bulleted list instead of in a row.
* Alignment is not correct.
* Icons are missing colors.
* Icons are black on a black background in Dark Theme.

Editor|Preview|Reader
---|---|---
![Screenshot_20200728-132516](https://user-images.githubusercontent.com/1119271/88739907-f9d25780-d0f8-11ea-80da-f829c6664292.png)|![Screenshot_20200728-132459](https://user-images.githubusercontent.com/1119271/88739910-fb038480-d0f8-11ea-9b38-4b02b69192ec.png)|![Screenshot_20200728-132437](https://user-images.githubusercontent.com/1119271/88739914-fccd4800-d0f8-11ea-84f3-b7b8f247f30d.png)

<p style="clear:both;"><sup>Tested with WPAndroid 15.4-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by zwarm** [comment]
Addressed in https://github.com/Automattic/wp-calypso/pull/44584
