### ISSUE TITLE
RuntimeException: Unable to destroy activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: ...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12550]
This one seems like an old issue and not a lot of crashes, but it's also probably easy enough to fix. Maybe a candidate for Groundskeeping?

**Sentry Url**: https://sentry.io/share/issue/1b677ab4487e47579f3dcba7e4763fa4/
**User Count**: 70
**Count**: 108
**First Release**: org.wordpress.android-12.4
**First Seen**: 2019-05-31T13:06:47Z
**Last Seen**: 2020-07-29T08:34:55Z
**24 Hours**: 10
**30 Days**: 35

```
RuntimeException: Unable to destroy activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.IllegalStateException: my_site_title_label must not be null
     at org.wordpress.android.ui.main.MySiteFragment.onTextInputDialogDismissed(MySiteFragment.kt:1473)
     at org.wordpress.android.ui.TextInputDialogFragment.onDismiss(TextInputDialogFragment.java:118)
     at org.wordpress.android.ui.main.WPMainActivity.onDestroy(WPMainActivity.java:692)
...
(18 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
I agree @oguzkocer - adding it to the groundskeeping project.

**Comment by designsimply** [comment]
**Events in the last 90d:** 940
**Users affected in the last 90d:** 754
<sub>WORDPRESS-ANDROID-1E9: https://sentry.io/share/issue/1b677ab4487e47579f3dcba7e4763fa4/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1051398125&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96308543-d4027380-0fc0-11eb-8e98-cfc869582dfe.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 1,200
**Users affected in the last 90d:** 700
<sub>WORDPRESS-ANDROID-1E9: https://sentry.io/share/issue/1b677ab4487e47579f3dcba7e4763fa4/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1051398125&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100553676-5e8af380-324c-11eb-8d87-963674bbd2ee.png)</a>

**Comment by mkevins** [comment]
I found steps to reproduce this:

* Log in and go to "My Site" tab
* Tap site title to open text input dialog
* Rotate phone
* :boom:

and have opened a PR to fix the issue: https://github.com/wordpress-mobile/WordPress-Android/pull/13505
