### ISSUE TITLE
Activity Result not set when changing site icon

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#12556]
While testing #12555 I found an issue with setting the site icon of a site from the WP Media Library.

### Expected behavior
When setting a site icon in My Site, selecting an image from the WP Media Library I would expect the site icon to be changed accordingly

### Actual behavior
When setting a site icon in My Site, selecting an image from the WP Media Library the site icon is not changed and nothing happens.

### Steps to reproduce the behavior
- Go in My Site for a WP.com/JP site
- Tap on the site icon and acknowledge the dialog that appears
- Go to WP Media Library from the screen that appears
- Select an image and note that the site icon is not updated

**Comment by mzorz** [comment]
Closing via #12558
