### ISSUE TITLE
Create WPAndroid screenshots on CI

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#12601]
We have a Fastlane setup to create enhanced screenshots for WPAndroid. It runs a dedicated set of UI tests which use mocked API calls and takes basic screenshots. Then, the screenshots are processed to add promo text, composites, etc. 

Currently:
- The screenshot generation lane has to be run on a local machine and takes quite a bit of time. 
- There are some small issues with some languages that need to be fixed. 

It would be nice to make it run on CI, triggered by a manual event (adding a label or opening a PR with a define name pattern or an API call, etc.). The final screenshots should be available for download, ready to be uploaded with Fastlane to the Play Store. 

In order to make this work, the following issues need to be fixed: 
- Screenshot for `sr` doesn't get generated.
- Screenshot generation for `ar` crashes in stats section due to a mocked data parsing issue.
- `id` locale screenshots are not generated properly. `in` seems to work. It seems to be one of the usual issues due to Android having changed some locale shortcodes in the past.
- Promo screenshots should be generated under the folder and with the layout that Fastlane expects to upload them, and the original simple screenshots shouldn't be there at the end of the job.

Stretch goal: upload them to Play Store from CI, after user review.

**Comment by AliSoftware** [comment]
@loremattei 

> Screenshot generation for ar crashes in stats section due to a mocked data parsing issue.

Is this still true? I've run the lane locally and see all screenshots for `ar` properly generated on my Machine in `fastlane/metadata/android` (and also in `fastlane/promo_screenshots` after running the `create_promo_screenshots` lane)

> Promo screenshots should be generated under the folder/layout that Fastlane expects to upload them, and the original simple screenshots shouldn't be there at the end of the job.

Currently, raw screenshots are in `fastlane/metadata/android` and promo screenshots are in `fastlane/promo_screenshots`. I can change the output from `fastlane/promo_screenshots` to `fastlane/layout` if you prefer, but I'm not sure what you expect in that sentence about the raw screenshots:
 - should I delete `fastlane/metadata/android/**/images` even tho they are not in the same folder as the `promo_screenshots` and don't risk to cause any confusion?
 - What's the point of removing them is the screenshots are taken by the CI anyway?
 - Or is this point obsolete and was written at an earlier point where both the promo screenshots and the raw screenshots were all in the same folder?

**Comment by loremattei** [comment]
> Is this still true? I've run the lane locally and see all screenshots for ar properly generated on my Machine

If all the screenshots are generated properly, that's ok.

> should I delete fastlane/metadata/android/**/images even tho they are not in the same folder as the promo_screenshots and don't risk to cause any confusion?
What's the point of removing them is the screenshots are taken by the CI anyway?
Or is this point obsolete and was written at an earlier point where both the promo screenshots and the raw screenshots were all in the same folder?

Sorry, I didn't meant to to move the output to `fastlane/layout`, I meant to move it to the folder and with the layout that fastlane expects.

**Comment by AliSoftware** [comment]
> Is this still true? I've run the lane locally and see all screenshots for ar properly generated on my Machine

Update: `ar` UI Tests actually still crash, so this is not fixed after all. That doesn't prevent the screenshots to be generated, but that still makes the UI Tests crash and thus still needs to be fixed
