### ISSUE TITLE
Rename Contact Us to Connect App support

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#12633]
We receive a lot of tickets in the mobile apps with only phone number and contact details. One user followed up on such a ticket to confirm that they thought they were settings up their support for people who visit their site through the app to contact them. 

We're wondering if part of the issue here is the label 'Contact Us' that may be causing people to not realize this is for App Support. 

I'd like to be able to edit this label to make it clearer that they are contacting app support to see if this helps to reduce the incoming number of unknown support requests with contact details. 

### Steps to reproduce the behavior

Navigate to Me > Help & Support, view the 'Contact Us' button.

**Comment by elibud** [comment]
Let's rename the label to: "Contact WordPress support"

**Comment by rezzap** [comment]
I think we need to be careful to clarify that this is 'App Support' and not 'WordPress support'. We don't support the WordPress software, just the app.

**Comment by designsimply** [comment]
Adding some screenshots for reference and noting that we are also discussing the exact wording of the text for this screen in the comments at https://github.com/wordpress-mobile/WordPress-iOS/issues/14616.

<img src="https://user-images.githubusercontent.com/1119271/89947891-63b32c80-dbe2-11ea-875a-a7b0b720d603.png" width="33%" alt="Screenshot_20200811-144851"> <img src="https://user-images.githubusercontent.com/1119271/89947888-6281ff80-dbe2-11ea-94e8-8bedc575e30f.png" width="33%" alt="Screenshot_20200811-144923"> <img src="https://user-images.githubusercontent.com/1119271/89947885-61e96900-dbe2-11ea-8548-297bc0b30159.png" width="33%" alt="Screenshot_20200811-144950">

<p style="clear:both;"><sup>Tested with WPAndroid 15.5-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by bummytime** [comment]
As @mattmiklic mentioned [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/14616#issuecomment-672899406), `Contact Support` looks like the winner.

**Comment by jd-alexander** [comment]
Thanks for sharing @bummytime 🙇‍♂️
