### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.addOnScrollListe...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#12657]
**Sentry Url**: https://sentry.io/share/issue/af9bf1418add4f589f5f91c794263e7a/
**User Count**: 388
**Count**: 557
**First Release**: org.wordpress.android@15.3-rc-1+891
**First Seen**: 2020-07-17T17:12:12.464000Z
**Last Seen**: 2020-08-12T09:58:23Z
**24 Hours**: 41
**30 Days**: 556

```
NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.addOnScrollListener(androidx.recyclerview.widget.RecyclerView$OnScrollListener)' on a null object reference
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$showNewUnseenNotificationsRunnable$1.run(NotificationsListFragmentPage.kt:71)
```

**Comment by bummytime** [comment]
Seems like we are seeing a significant number of these crasher events (1.4K) since 15.3 (and 844 users). @zwarm it looks like you recently worked on `NotificationsListFragmentPage`, could you take a peek at this? Thanks!

**Comment by bummytime** [comment]
**Update:** 3.3k events and 1.6k users — @zwarm did you have a chance to investigate this one?

**Comment by designsimply** [comment]
+1 this one's totally worth a look!

**Events in the last 90d:** 3,300
**Users affected in the last 90d:** 1,600
<sub>WORDPRESS-ANDROID-HC9: https://sentry.io/share/issue/af9bf1418add4f589f5f91c794263e7a/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1790223792&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96309774-30ff2900-0fc3-11eb-89c5-fb27f3466e99.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 5,100
**Users affected in the last 90d:** 1,800
<sub>WORDPRESS-ANDROID-HC9: https://sentry.io/share/issue/af9bf1418add4f589f5f91c794263e7a/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1790223792&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100553722-a27df880-324c-11eb-8173-21ecabc7a287.png)</a>
