### ISSUE TITLE
Site icon change not working when aborting action

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#12668]
### Expected behavior
Changing the site's icon should either work or show an error if something could not be done or if the process is aborted.

### Actual behavior
When aborting a change in the crop tool, you end up with a forever spinning wheel.

### Steps to reproduce the behavior
1. tap on my site icon to change the icon
2. accept the dialog
3. choose an image
4. when the crop tool appears, tap the X on the top left to abort the action
5. observe the site's icon shows a neverending spinning wheel  instead of showing the previous, unchanged site icon.
6. Also, try tapping on it: nothing happens (so you can't change it anymore).

**Comment by designsimply** [comment]
Good find! Tested and confirmed using WPAndroid 15.5-rc-1 that starting to select an image then exiting the Edit Photo screen using the X results in a spinner that doesn't go away until you leave the My Site section of the app and then go back again. ([2m12s](https://cloudup.com/cRwVn6JnOby))

<img width="33%" alt="Screen Shot 2020-08-13 at Aug 13 11 22 48 AM" src="https://user-images.githubusercontent.com/1119271/90166414-70a55c80-dd57-11ea-84ba-5d7cb2950314.png"> <img width="33%" alt="Screen Shot 2020-08-13 at Aug 13 11 21 42 AM" src="https://user-images.githubusercontent.com/1119271/90166420-74d17a00-dd57-11ea-98a9-46416145a5f4.png"> <img width="33%" alt="Screen Shot 2020-08-13 at Aug 13 11 22 00 AM" src="https://user-images.githubusercontent.com/1119271/90166427-77cc6a80-dd57-11ea-94c7-904fea30124d.png">
<p style="clear:both;"><sup>Tested with WPAndroid 15.5-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by mzorz** [comment]
Thanks for confirming and adding screenshots to this @designsimply 🙇

**Comment by thehenrybyrd** [comment]
I'm no longer able to reproduce this in WP Android 21.1-rc-2. In addition, the "change site icon" process has be updated and the cropping part is no longer required to finish changing the site icon. I wasn't able to find a way to get that indefinite spinner, so I'll close this issue.
