### ISSUE TITLE
Quick start not showing up

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-Android#12683]
### Expected behavior
After creating a new account and going through the site creation flow, I expected to see the quick start flow.

### Actual behavior
I didn't encounter the quick start flow

### Steps to reproduce the behavior
1. Create new account
2. Go through account creation flow
3. Go through site creation flow

##### Tested on [device], Android [version], WPAndroid [version]
Device Pixel 2a XL
WPAndroid 15.4

**Comment by renanferrari** [comment]
This seems to be a duplicate of #12578, which was fixed by #12590. I'm closing this for now but feel free to open it again if I'm missing something.
