### ISSUE TITLE
Test failing on CircleCI as of 17 August 2020, 15:34:27 UTC

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-Android#12702]
I noticed that the "test" step if failing on CircleCI across different branches.

**I believe the error has something to do with the CircleCI internals or environment, rather than with code that we shipped.**

I pushed a branch with the head pointing to the [last successful `develop` build](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/15019/workflows/98eaae87-beb1-45f1-a02d-d3015d22eca5), and [it failed](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/15090/workflows/aefc4449-4461-44e7-b865-a86005de75ad/jobs/66959), too.

Unfortunately, I wasn't able to find a solution, or even a pointer to what might have changed on the CircleCI side.

Below is the information I collected, hopefully it can help you figure out a solution faster.

### Extra information

The first instance of the failure I could find is [this build](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/15050/workflows/db66f660-68b2-45b9-8f05-a315fca8b998), at 17 August 2020, 15:34 UTC.

The [CircleCI changelog](https://circleci.com/changelog/) doesn't mention anything. Their Twitter account has [a tweet at more or less the same time](https://twitter.com/CircleCI/status/1295366524623040513?s=20) mentioning news in the changelog, but the link points to changes that date back to April 2020, so that's just content marketing noise.

The failing tests are:

https://github.com/wordpress-mobile/WordPress-Android/blob/ad63db144b94013d39ec6f6801fa2b09a6205402/WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt#L142-L158

```
org.junit.ComparisonFailure: expected:<"17.12 - 23.12"> but was:<null>
```

https://github.com/wordpress-mobile/WordPress-Android/blob/ad63db144b94013d39ec6f6801fa2b09a6205402/WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt#L122-L130

```
org.junit.ComparisonFailure: expected:<"25.[11.]2018"> but was:<"25.[ 11. ]2018">
```

https://github.com/wordpress-mobile/WordPress-Android/blob/ad63db144b94013d39ec6f6801fa2b09a6205402/WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt#L132-L140

```
org.junit.ComparisonFailure: expected:<"25.[11.]2018"> but was:<"25.[ 11. ]2018">
```

The failing test command works for me locally, and so does running the test class that is failing.

```
SUPPRESS_GUTENBERG_MOBILE_JS_BUNDLE_BUILD=1 ./gradlew testVanillaRelease --stacktrace --no-daemon
```

**Comment by mokagio** [comment]
I opened a [PR on WooCommerce Android](https://github.com/woocommerce/woocommerce-android/pull/2735) where the only change I made was on the README. 

It failed on CI, too, whereas the last commit on `develop` (so the same code as that PR) [passed](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/6924/workflows/76368fc9-3244-480a-8c8a-edae57a017bd)

**Comment by mokagio** [comment]
@anitaa1990 pointed out that builds fail on [WordPress-FluxC-Android](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android), too.

In fact, I re-run [a recent passing build](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/2661/workflows/f44af035-f501-4917-b88f-29e9df402a49), and [it failed](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/2661/workflows/4aba9baf-d5db-461b-bbf2-6e010d747ad2):

![image](https://user-images.githubusercontent.com/1218433/90474268-3decd100-e168-11ea-9aa1-d60ecb3c29a4.png)

**Comment by mokagio** [comment]
I thought maybe something changed in [our CircleCI orbs](https://github.com/wordpress-mobile/circleci-orbs/) that could have to do with these failures, but there hasn't been a commit since [Jun 11](https://github.com/wordpress-mobile/circleci-orbs/commit/a8c0d45f33ff1f80d227fb7a37f6b4e77f8cca85)

**Comment by loremattei** [comment]
Fixes are here: 
https://github.com/woocommerce/woocommerce-android/pull/2739
https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1671
https://github.com/wordpress-mobile/WordPress-Android/pull/12703
