### ISSUE TITLE
[AvatarHelper] IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNo...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12730]
**Sentry Url**: https://sentry.io/share/issue/704c7d1782b146e38dbd470f3456c32c/
**User Count**: 5
**Count**: 124
**First Release**: org.wordpress.android@15.4+901
**First Seen**: 2020-08-11T13:34:35.035000Z
**Last Seen**: 2020-08-20T08:16:20Z
**24 Hours**: 18
**30 Days**: 123

```
IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter model
     at org.wordpress.android.login.util.AvatarHelper$loadAvatarFromUrl$1.onLoadFailed(null:2)
     at org.wordpress.android.login.util.AvatarHelper.loadAvatarFromUrl(AvatarHelper.kt:61)
     at org.wordpress.android.login.SignupConfirmationFragment.onViewCreated(SignupConfirmationFragment.kt:121)
...
(17 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@renanferrari this crasher started on August 11th. Looks like it might be originating on `SignupConfirmationFragment` in `onViewCreated`.  Any thoughts?

**Comment by renanferrari** [comment]
@bummytime This seems to be related to a new class added during UL&S. Should be an easy fix. I think I'll be able to work on it tomorrow.
