### ISSUE TITLE
Reader: Jetpack slideshow block displays as bulleted image list

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#12738]
Slideshow blocks are being displayed as a list of images with bullet points in the reader. This likely requires a similar fix to https://github.com/wordpress-mobile/WordPress-Android/issues/11673, at least to remove the bullets.

![wpandroid-reader-slideshow-bullet-list-merged](https://user-images.githubusercontent.com/9613966/90840561-45dd8880-e395-11ea-92d4-be1dc6c450f1.png)

This is happening in the Calypso reader, iOS, and e-mail notifications as well.

Calypso issue: https://github.com/Automattic/wp-calypso/issues/45085
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14701

### Expected behavior

Possibly the slideshow in gallery format, or at least no bullets.

### Steps to reproduce the behavior

1. Create a new post with a Slideshow block
2. View that post in the reader
3. Observe that the images show up as a bulleted list

**Comment by ashiagr** [comment]
Needs to be fixed in Calypso.
