### ISSUE TITLE
Reader - Comment: tables are not formatted and styled

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#12745]
# What I see on the comment screen

<img src="https://bia.is/s/LURv/Screenshot_20200821_114457_org.wordpress.android.jpg" width="400" />

# What I see in the Web Reader

<img width="1069" alt="Screenshot 2020-08-21 at 11 26 15" src="https://user-images.githubusercontent.com/40213/90877279-1bdf9280-e3a4-11ea-9bd2-f33b92a08e23.png">

**Comment by zwarm** [comment]
FYI: ATM blocks are not rendered in comments and I believe discussions are in progress on how to address this moving forward.

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
