### ISSUE TITLE
Reader - Comment: Audio block is not visible

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#12746]
### Expected behavior

What I see in a Reader comment:

<img src="https://bia.is/s/xRXH/Screenshot_20200821_114457_org.wordpress.android.jpg" width="400" />

### Actual behavior

What I see in the Web Reader:

<img width="1063" alt="Screenshot 2020-08-21 at 11 50 13" src="https://user-images.githubusercontent.com/40213/90877547-87c1fb00-e3a4-11ea-8893-56ebc298e13f.png">

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
