### ISSUE TITLE
Contact Block link not encapsulating full address in comments

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-Android#12758]
### Expected behavior

The entire contact block to be linked to google maps

### Actual behavior

On the email and phone number are linkified

### Steps to reproduce the behavior

1. Post comment with Contact Block w/ link to google maps turned on
2. Observe comment in reader
3. Observe only email and phone number are linkified

![image](https://user-images.githubusercontent.com/6817400/90914022-25202d80-e3ab-11ea-96ca-bc6c33d63e6e.png)

##### Tested on [device], Android [version], WPAndroid [version]

Pixel 1, Android 10, alpha-238

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
