### ISSUE TITLE
Reader doesn't process Column Blocks

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-Android#12759]
### Expected behavior
WPA's Reader would arrange content in columns, whenever the Columns block is used.

### Actual behavior
Content is displayed in rows.

### Steps to reproduce the behavior
1. Add a new post (in Calypso!)
2. Insert the **Columns** block
3. Add content to each column
4. Publish the post
5. Open the content in the Reader
6. Observe the content is rendered in rows

<img width="300" src="https://user-images.githubusercontent.com/1195260/90921840-50157c00-e3c1-11ea-9dc7-73c76b65bc82.png">

### Post

```
<!-- wp:heading -->
<h2>Layout: 50/50</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>50/50 Left | BLA BLA BLA BLA</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>50/50 Right| BLA BLA BLA BLA</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

##### Tested on [device], Android [version], WPAndroid [version]
Android Simulator, WPAndroid [15.4]

**Comment by zwarm** [comment]
@designsimply This is the intended behavior. TLDR; For mobile devices ≤ 580px the columns are stacked. This [iOS ticket](https://github.com/wordpress-mobile/WordPress-iOS/issues/14714#issuecomment-680271886) details the why much better than I can do.
