### ISSUE TITLE
Reader Comment: Verse block displays as plain text

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-Android#12753]
### Expected behavior

Text should display as a verse

### Actual behavior

Text displays as plain text

![image](https://user-images.githubusercontent.com/6817400/90906609-edf84f00-e39f-11ea-982c-fb2767fe2266.png)

### Steps to reproduce the behavior

1. Use the verse block in a comment
2. View that comment in the reader

##### Tested on [device], Android [version], WPAndroid [version]

Pixel 1, Android 10, alpha-238

**Comment by zwarm** [comment]
Blocks are not rendered in the comments section at the moment. Future plans are in discussion.

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
