### ISSUE TITLE
Facebook Embed Block does not appear in comments

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-Android#12757]
### Expected behavior

Facebook Embed block in comments should appear

### Actual behavior

Facebook Embed block does not appear

### Steps to reproduce the behavior

1. Use Facebook embed block in a comment
2. View comment in app
3. Observe it does not appear

##### Tested on [device], Android [version], WPAndroid [version]

Pixel 1, Android 10, alpha-238

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
