### ISSUE TITLE
Reader doesn't show next page block

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#12750]
### Expected behavior
I was expecting the break block to render

### Actual behavior
The break block doesn't render

### Steps to reproduce the behavior
1. write a new post
2. add some text
3. add a break block
4. add some more text
5. publish
6. open it in the reader
7. observe no break block is rendered

<img width="409" alt="Screen Shot 2020-08-21 at 11 31 51" src="https://user-images.githubusercontent.com/6597771/90902871-8512d600-e3a3-11ea-987c-d338e44003e8.png">

This is the original content https://testmzorz3.wordpress.com/2020/08/21/another-test/

Here's a copy of the content:
```
<!-- wp:paragraph -->
<p>one paragraph</p>
<!-- /wp:paragraph -->

<!-- wp:nextpage -->
<!--nextpage-->
<!-- /wp:nextpage -->

<!-- wp:paragraph -->
<p>second paragraph</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>third paragraph</p>
<!-- /wp:paragraph -->
```

Also note GB on the web is not rendering the blocks below as reported here https://github.com/WordPress/gutenberg/issues/24724

h/t @jleandroperez for helping me test this 🙇

**Comment by ashiagr** [comment]
Closing with similar reason as on iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14711

> HTML that's being returned to us just includes a number of \n's instead of a next page block indicator.

Tracked in wp-calypso issue here: Automattic/wp-calypso#46013
