### ISSUE TITLE
Reader: Pay with PayPal Block, PayPal button does not render

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-Android#12751]
### Expected behavior

When using the Pay with PayPal block I should see the PayPal button in the reader

### Actual behavior

I do not see the PayPal button

### Steps to reproduce the behavior

1. Starting at URL: https://wordpress.com/read/feeds/77116051/posts/2871659129
2. Observe that PayPal button does not appear

##### Tested on [device], Android [version], WPAndroid [version]

Pixel 1, Android 10, alpha-238

**Comment by ashiagr** [comment]
Needs to be fixed in Calypso/backend.

Given this is not part of the scope of the Reader mobile I'm closing this issue.

Related iOS issue https://github.com/wordpress-mobile/WordPress-iOS/issues/14705 is closed as well.
