### ISSUE TITLE
Reader: Paragraph alignment is off

### ISSUE THREAD

**Issue by davemart-in** [wordpress-mobile/WordPress-Android#12756]
### Expected behavior
Center and right aligned content to show up in the Android reader.

### Actual behavior
All text was left aligned.

### Steps to reproduce the behavior
Here's what I posted:

<img width="803" alt="Image 2020-08-21 at 11 27 01 AM" src="https://user-images.githubusercontent.com/5634774/90908094-e8036d80-e3a1-11ea-8764-f0439d6fe137.png">

Here's what I saw in the Android reader:

![Screenshot_2020-08-21-11-37-13](https://user-images.githubusercontent.com/5634774/90908987-23eb0280-e3a3-11ea-87d6-8e2ca339d644.png)

##### Tested on [device], Android [version], WPAndroid [version]

Moto G - 5.0.2 - 11.1-rc-1

**Comment by ashiagr** [comment]
Closing it with the same reasoning mentioned for the issue in iOS https://github.com/wordpress-mobile/WordPress-iOS/issues/14707:

> The reader doesn't apply all the styles that a user defines. We did that in order to keep the consumable in Reader a little bit more generic.

> Plus, this needs to be addressed in Calypso styles, not in the mobile code.

> I'm closing the issue, we can always reassess if needed.
