### ISSUE TITLE
Reader: Vimeo Block embeds do not render in comments

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-Android#12752]
### Expected behavior
Vimeo video should show in the comment

### Actual behavior
Vimeo video does not show

### Steps to reproduce the behavior
1. Add a Vimeo Block to a comment
2. View in Android
3. Observe video does not show

Example: pceC9O-60-p2

##### Tested on [device], Android [version], WPAndroid [version]

Pixel 1, Android 10, alpha-238

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
