### ISSUE TITLE
Reader: Lastest Posts block doesn't appear when inserted in a comment

### ISSUE THREAD

**Issue by cpapazoglou** [wordpress-mobile/WordPress-Android#12754]
### Expected behavior
Expected to at least see the latest posts block .

### Actual behavior
Latest posts block is not visible at all.

### Steps to reproduce the behavior
1. Boot a site which has Gutenberg enabled for comments (eg a P2)
2. Add a comment containing `latest-posts` block
3. View the comment in the Reader of your android device

##### Tested on [device], android [version]
Tested on Huawei Mate 10 Pro, Android 10

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
