### ISSUE TITLE
Notifications: Youtube Blocks in Comments aren't processed

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-Android#12763]
### Expected behavior
Comment Notifications containing Youtube Blocks should display a video player.

### Actual behavior
Raw text is displayed!

**NOTE:**
Mentions in post **do work**. This issue is for **comment Notifications!**

### Steps to reproduce the behavior
1. Add a new comment
2. Mention **User B**
3. Insert a Youtube Block

As a result, whenever **User B** receives the notification, there won't be a Youtube player.

**Comment by develric** [comment]
This seems still to be valid in current develop (at this point in [history](https://github.com/wordpress-mobile/WordPress-Android/tree/a860d8b29eb097aed016d28092021c4fa756a2c4)).

If I'm not wrong, it actually seems to be the case in general even if not placing a mention but letting the User B get a notification as an answer to User B comment (like below on the right)

| With mention | Without mention |
|---|---|
| ![image](https://user-images.githubusercontent.com/47797566/115308659-5be15a00-a16b-11eb-8b48-a5d6825d8a9b.png) | ![image](https://user-images.githubusercontent.com/47797566/115308644-52f08880-a16b-11eb-8108-66935ce5483e.png) |

Tested on Pixel 4 Emu API 29.

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
