### ISSUE TITLE
Notifications: Column Blocks aren't processed

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-Android#12762]
### Expected behavior
Comment Notifications containing Column Blocks should layout the content in columns.

### Actual behavior
Text isn't laid out in columns

### Steps to reproduce the behavior
1. Add a new Comment
2. Insert a Columns Comment
3. Add content to each comment
4. Mention a second User

As a result, whenever **User B** gets the notification, the contents will not be displayed in columns.

### Payload
```
<!-- wp:heading -->
<h2>Layout: 50/50</h2>
<!-- /wp:heading -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>50/50 Left | BLA BLA BLA BLA</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>50/50 Right| BLA BLA BLA BLA</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

##### Android Simulator, WPAndroid [15.6]

**Comment by ashiagr** [comment]
Closing it based on the same reasoning as for this similar issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12759#

>  For mobile devices ≤ 580px the columns are stacked.
