### ISSUE TITLE
Comments: Quote block is not rendering correctly

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#12765]
### Expected behavior

The Quote block on comments should render correctly.

### Actual behavior

In the comment preview the quote block definitely looks wrong.
![Screenshot_2020-08-21-15-53-00-115_org wordpress android](https://user-images.githubusercontent.com/5558824/90926799-33317680-e3ca-11ea-982f-6d23dabde39b.jpg)

In the comment details there's room for improvement.
![Screenshot_2020-08-21-16-06-29-841_org wordpress android](https://user-images.githubusercontent.com/5558824/90926123-e0a38a80-e3c8-11ea-8e09-d58fe5c58bcf.jpg)

### Steps to reproduce the behavior

1. Add a quote block in a comment of a site you own.
2. Go to the site, Comments.

**Comment by thehenrybyrd** [comment]
No longer able to reproduce this in 20.6-rc-2, the quote block now renders in the comments list preview.
