### ISSUE TITLE
Instagram embed not rendering correctly in Reader comment

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#12769]
### Expected behavior

An Instagram embed in a post **comment** should be rendered correctly (i.e. the Instagram post should be visible in the comment).

### Actual behavior

The Instagram embed shows the text "View this post on Instagram" followed by the Instagram's text which appears to be unformatted.

This works correctly (known issues https://github.com/wordpress-mobile/WordPress-Android/issues/12767 and https://github.com/wordpress-mobile/WordPress-Android/issues/12772) when viewing an Instagram embed in a _post_ in Reader, this issue tracks its broken state when the embed is in a _comment_ in Reader.

| Reader Post ✅ | Reader Comment ❌ |
| -- | -- |
| <img alt="Screenshot showing Instagram embed working correctly in Reader post" src="https://user-images.githubusercontent.com/1898325/90930473-acc86500-e3c8-11ea-909a-30f323865c2b.jpg" width="300" /> | <img alt="Screenshot showing Instagram embed not rendering in Reader comments" src="https://user-images.githubusercontent.com/1898325/90930433-9c17ef00-e3c8-11ea-96aa-7bf1c8e3387b.jpg" width="300" /> |

### Steps to reproduce the behavior

1. Log into the WPAndroid app and locate a post with a comment that contains an Instagram embed. If none are available, here's how to create one:
  a. On the web, log into a WordPress site that has Gutenberg enabled in comments (e.g. create a site on http://wp.com/p2)
  b. Reply to any post or comment, and add the Instagram block (embed any Instagram post) 
  c. Click Reply to send the comment
  d. Return to the app and locate the newly added comment
2. Go to Reader, and find the comment (you can filter by the site in question)
3. Notice:
    - the embed renders as "View this post on Instagram" instead of the post's photo
    - the Instagram post's text has lost most of its formatting (new lines, blank lines, etc)

**Comment by zwarm** [comment]
FYI: At the time of this ticket, the Android app doesn't render any gutenberg blocks in comments.

**Comment by thehenrybyrd** [comment]
This is still an issue in 20.6-rc-2, though it's being handled a bit more gracefully.
Currently, if an Instagram embed is added in a comment, the Comments List preview for that comment reads "View this post on Instagram", rendered like a quote block.

After tapping the comment to view it in full, it still states "View this post on Instagram", rendered like a quote block, with a short description stating who it's by.

Though having the post itself render in Comments would be nice, this handling seems acceptable - especially given the use case (Blocks in Comments) appears to be mostly for p2 (internal).

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
