### ISSUE TITLE
Comments: Gallery block not rendering correctly

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#12766]
### Expected behavior

The Gallery block on comments should render correctly.

### Actual behavior

Instead, there's a bulleted list of images.

### Steps to reproduce the behavior

Add a gallery block in a comment of a site you own.
Go to the site, Comments.

![Screenshot_2020-08-21-15-53-49-301_org wordpress android](https://user-images.githubusercontent.com/5558824/90927348-527cd380-e3cb-11ea-8a1b-c76d20ddacb0.jpg)

**Comment by thehenrybyrd** [comment]
No longer able to reproduce this in 20.6-rc-2, the gallery block now renders in the comment.
