### ISSUE TITLE
Comments: Code Block is Not Styled

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#12768]
### Expected behavior
The code block is styled with monospace font and a colored background.

### Actual behavior
The code block is not styled with monospace font and a colored background.

### Steps to reproduce the behavior
0. Follow a site.
1. Publish a post with a code block to the site in Step 0.
2. Comment on post from Step 1.
3. Go to **_Notifications_**.
4. Tap the notification for the comment from Step 2.
5. Notice the code block style in the post.

<kbd><a href="https://user-images.githubusercontent.com/3827611/90929397-e17ef100-e3b5-11ea-8d5e-a7beda31bb74.png"><img src="https://user-images.githubusercontent.com/3827611/90929397-e17ef100-e3b5-11ea-8d5e-a7beda31bb74.png" width="300"></a></kbd>

##### Tested on [device], Android [version], WPAndroid [version]
Google Pixel 2, Android 10, WPAndroid alpha-235

**Comment by guarani** [comment]
Thanks for the report @theck13! 

Block rendering in notifications isn't handled by gutenberg, so I've updated the labels.

**Comment by develric** [comment]
This seems still to be current in develop (at this point in [history](https://github.com/wordpress-mobile/WordPress-Android/tree/a860d8b29eb097aed016d28092021c4fa756a2c4)).

| <image width=300 src="https://user-images.githubusercontent.com/47797566/115309444-95ff2b80-a16c-11eb-88ad-f0824cceba4b.png"/> | <image width=300 src="https://user-images.githubusercontent.com/47797566/115309409-867fe280-a16c-11eb-9943-04e6550410ce.png"/> |
|---|---|

Tested on Pixel 4 Emu API29.

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
