### ISSUE TITLE
Notifications : Button block is not rendering correctly in comments

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#12764]
### Expected behavior
The button block will be rendered with the respective border or background based on the behavior that's added during it's creation. 

### Actual behavior
Only the text and link (if configured) are shown. The button's style is not rendered.
<kbd><img src="https://user-images.githubusercontent.com/1509205/90921903-aa5a1100-e3b0-11ea-9206-3f0274d44230.png" width="320"></kbd>

### Steps to reproduce the behavior
1. Utilize the bock editor to create a button block as a response to a comment or post.
2. See the behavior.

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by zwarm** [comment]
@designsimply 
This behavior is as expected. The app doesn't render any blocks in notifications or comments.
