### ISSUE TITLE
Comments : Media & Text - text alignment does not work.

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#12773]
### Expected behavior
The text will be right-aligned if configured as such.

### Actual behavior
The text is not right-aligned.

### Steps to reproduce the behavior
1. Make a Media & Text block within a comment and right-align the text. 
2. Notice that the right align does not take effect.

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by zwarm** [comment]
ATM, comments do not support any block rendering. Next steps are being discussed.

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
