### ISSUE TITLE
Instagram embed not rendering correctly in notification mention

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#12771]
### Expected behavior

When viewed via the Notifications tab in WPAndroid, a comment containing an Instagram embed should be rendered correctly (i.e. the Instagram post should be visible in the comment). Note: it should be possible to see the post's photo, since it renders fine in Reader posts).

### Actual behavior

The Instagram embed shows the text "View this post on Instagram" in the center of the screen with significant white space all around (similar to https://github.com/wordpress-mobile/WordPress-Android/issues/12769, but with much more whitespace).

| <img alt="Screenshot showing Instagram embed rendering incorrectly in a Notification comment" src="https://user-images.githubusercontent.com/1898325/90935569-80fdad00-e3d1-11ea-9ce3-27c91805107d.jpg" width="300" /> |
| -- |

### Steps to reproduce the behavior

1. On the WPAndroid app in the Notifications tab, locate a notification for a comment that contains an Instagram post. If none are available, create one like so:
  a. On the web, log into a WordPress site that has Gutenberg enabled in comments (e.g. create a site on http://wp.com/p2)
  b. Add another WordPress user, granting the Administrator role (other roles may work)
  c. Still on the same site, create a reply (comment) to a post, @-mentioning the newly added user
  d. Add an Instagram embed to that same reply
  e. Send the reply
2. From the WPAndroid app, log in as the newly added Administrator
3. In the Notifications tab, locate the notification containing the Instagram embed
4. Open the comment, and notice:
    - The comment renders as mostly whitespace, with a "View this post on Instagram" instead of the post's photo
    - The post's text (scroll down to see it) has lost most of its formatting (new lines, blank lines, etc)

**Comment by thehenrybyrd** [comment]
This is still an issue in 20.6-rc-2, though it's being handled a bit more gracefully.
Currently, if an Instagram embed is added in a comment, the comment reads "View this post on Instagram", rendered like a quote block.

Though having the post itself render in Comments would be nice, this handling seems acceptable - especially given the use case (Blocks in Comments) appears to be mostly for p2 (internal).

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
