### ISSUE TITLE
Comments: Embed block not rendering 

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#12770]
### Expected behavior

Embed block to render youtube preview

### Actual behavior

Block did not render

### Steps to reproduce the behavior

1. Create a comment on a post
2. add an embed block 
3. use url http://www.youtube.com/watch?v=dQw4w9WgXcQ
4. view comment from Android

<img width="495" alt="Screenshot 2020-08-21 at 4 08 23 PM" src="https://user-images.githubusercontent.com/6520461/90935474-e600d500-e3c8-11ea-92b0-a1b1af609dd3.png">

HTML content for comment: 

```
<!-- wp:core-embed/youtube {"url":"http://www.youtube.com/watch?v=dQw4w9WgXcQ","type":"rich","providerNameSlug":"","className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"} -->
<figure class="wp-block-embed-youtube wp-block-embed is-type-rich wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
http://www.youtube.com/watch?v=dQw4w9WgXcQ
</div></figure>
<!-- /wp:core-embed/youtube -->
```

Post: https://testingblocks231341132.wordpress.com/2020/08/21/testing-post/

**Comment by thehenrybyrd** [comment]
This is still an issue in 20.6-rc-2, though it's being handled a bit more gracefully.
Currently, if a YouTube embed it added in a comment, the Comments List preview for that comment reads "Unable to show this comment".

Unfortunately, after tapping the comment to view it in full, it still states "Unable to show this comment".

**Comment by thehenrybyrd** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/17416, as discussed in this internal post: pdcxQM-1v4-p2
