### ISSUE TITLE
Site Pages: "Saving…" dialog stuck after tapping "View" on a page while "Uploading Media…"

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12785]
Steps to reproduce:

1. Go to My Site > Site Pages > Drafts > "+".
1. Apply any page template.
1. Add an image block and use "take a photo" to add an image.
1. Tap back arrow before the upload completes.
1. Tap "+" to start a new page before the upload completes.
1. Apply any page template.
1. Add an image block and use "take a photo" to add an image.
1. Tap back arrow before the upload completes.
1. While the page says "Uploading Media…" below the title, tap three dots > View.
1. Watch to see if the "Saving…" dialog appears and gets stuck.

Results: if you have uploaded media to a page and left the page before the upload completes twice in a row, a "Saving…" dialog appears and never goes away. It should ideally be cancellable and it shouldn't get stuck when "view" is invoked during an upload. ([2m48s](https://cloudup.com/crk6iMIa6JS))

<img width="270" alt="Screen Shot 2020-08-24 at Aug 24 7 38 50 PM" src="https://user-images.githubusercontent.com/1119271/91112880-76494f00-e641-11ea-8b7c-86fca6ee1527.png">
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-1 on Pixel 3 Android 10.</sup></p>

<p style="clear:both;"><sup>/hat tip gglobalstep for the original report in #12143.</sup></p>

**Comment by AmandaRiu** [comment]
I've tried reproducing this on a physical device (Pixel 4 - Api 30) and an emulator running Api 30 with WordPress v. 17.0. I can't move fast enough to get to the point where the photo is uploading and I can click to view before it's finished. Even after tweaking the network settings on the emulator to be "poor". Keeping open as it may still be an issue, I just don't have a device slow enough to replicate the issue.

**Comment by antonis** [comment]
I failed to reproduce the issue on a Pixel 5 with Android 12 (check video below). Since the some of the reproduction steps have changed (e.g. the page template chooser) from when this issue was reported I'm closing it as deprecated. Please reopen if that is not the case 🙇 

https://user-images.githubusercontent.com/304044/165897875-494e128a-86d8-4d94-a60f-73b7ee67c78b.mp4
