### ISSUE TITLE
Infinite loading screen in Reader

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#12802]
Update: This is happening only when the ReaderImprovements feature flag is enabled.

### Expected behavior
When I open Reader, the fullscreen progress screen should automatically disappear.

### Actual behavior
When I open Reader, the fullscreen progress screen is sometimes shown indefinitely.

### Steps to reproduce the behavior
1. Start the app and go to My Site
2. Restart the app
3. Turn on airplane mode
4. Go to Reader
5. Go to My Site
6. Turn off airplane mode
7. Go to Reader
8. Click on Retry
9. Notice the fullscreen progress is shown indefinitely

cc @ashiagr Could you please take a look at this issue. Thanks!

**Comment by designsimply** [comment]
@malinajirka I tested the steps provided a handful of times with two different accounts using WPAndroid 15.6-rc-2 on Pixel 3 Android 10 and I wasn't able to see the infinite loading screen described in this issue. ([1m22s](https://cloudup.com/ctY_U_qsK4Z))

**Comment by malinajirka** [comment]
😞 I'm sorry @designsimply. I forgot to mention that this is happening only when the Reader Improvements feature flag is enabled. The fullscreen progress view isn't used at all in a regular build. Ashita is already looking into the root cause of this issue ;).

**Comment by ashiagr** [comment]
This issue seems to happen only on an emulator.

Shortest steps to reproduce:
- Go to Reader -> discover tab (with RI FF enabled)
- Enable and then disable airplane mode
- Pull to refresh
- Notice loading for approx. 3 mins 

It could not be reproduced on an actual device.

As discussed on Slack, marking it as won't fix.

**Comment by malinajirka** [comment]
Just for future reference: The root of the issue is that volley requests on emulators sometimes take minutes to finish (even though we receive the response from the server within ms). This can be noticed even with disabled RI FF.
1. Open Reader - following tab
2. Enable and then disable airplane mode
3. Pull to refresh
4. Notice loading for approx. 3 mins
