### ISSUE TITLE
Site creation preview screen subdomain is not visible in dark mode

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12829]
Steps to reproduce:

1. Switch the device or app settings to Dark Theme.
1. Log out and start a new signup.
1. Follow the prompts.
1. Select a site address and tap the "Create Site" address.
1. Check to see that all text on the next screen is readable.

**Result:** the site address on the "Your site has been created!" screen is white on almost white and isn't readable.

<img width="270" alt="Screen Shot 2020-08-28 at Aug 28 5 12 59 PM" src="https://user-images.githubusercontent.com/1119271/91621918-2ecd0680-e952-11ea-9bed-a35017808b62.png">
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-2 on Pixel 3 Android 10.</sup></p>

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13467
