### ISSUE TITLE
Reader Improvements: Sites/Blogs you might like

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#12834]
Project Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12899

### Goal
Display a list of recommended sites to follow in the new "Discover" feed on the "Reader" tab, and allow the user to follow a site directly in the feed or tap it to see all the posts for the site. 

<img width="50%" alt="Screen Shot 2020-08-26 at 2 35 18 PM" src="https://user-images.githubusercontent.com/793774/91342704-43fa3780-e790-11ea-9855-e51a8b0abc07.png">

**Note** 
New "Discover" feed is currently hidden under a runtime feature flag which can be enabled as per steps described in #12050.

### Designs
Specs: [Figma](https://www.figma.com/file/RjrZZjXCtNYXWsPt5i0jha/Sites-You-Might-Like?node-id=0%3A1)

### Tasks

**BackLog**

**In Progress**

**Done**
- [x] Display recommended blogs card item in Discovery tab, add click action #12911
- [x] Design review #12960
- [x] Integrate Follow action #12960

**Comment by AdamGrzybkowski** [comment]
Some question about the feature:
1. I can see that the "Sites to follow" card is displayed somewhere between other cards. Is there a specified/fixed position for it? If not, is there a rule on how it should be calculated? 
2. How should the app behave when:
       - there are no suggestions (is this even possible with the API?)
       - there are more than 3 suggestions
3. Should there be a message displayed to the user if "Follow/Unfollow" action after the icon click fails? If yes, is there a guideline on how you handle such messages (Snackbar etc.) and is there a copy for such message defined?

**Comment by ashiagr** [comment]
Great questions! Here are the answers:

> 1. I can see that the "Sites to follow" card is displayed somewhere between other cards. Is there a specified/fixed position for it? If not, is there a rule on how it should be calculated?

We should follow the order returned by [the API](https://public-api.wordpress.com/wpcom/v2/read/tags/cards?tags=android) and display cards with “recommended_blogs” card type under “Sites to follow”. Note that “recommended_blogs” are not parsed yet unlike other card types. We can discuss it more when you've gone through the entire flow.

> 2. How should the app behave when: 
> - there are no suggestions (is this even possible with the API?)

If there are no suggestions, we shouldn’t display “Sites to follow” section.

  > - there are more than 3 suggestions

Let’s restrict to just 3 suggestions in a section. I’ll confirm the exact count.

> 3. Should there be a message displayed to the user if "Follow/Unfollow" action after the icon click fails? If yes, is there a guideline on how you handle such messages (Snackbar etc.) and is there a copy for such message defined?

There’s an existing error message already defined in the `strings.xml `(let me know if you can't find it). We can utilise it and get it confirmed when we create a PR. We now display such messages in a snackbar.

Hope this helps, let me know if you have additional questions 🙂.
