### ISSUE TITLE
Quick Start: indicator dot is missing on the site icon step and FAB was missing for the post publish step the step could not be completed

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12830]
Steps to reproduce:

1. Log out and sign up as a new user and create a new site.
1. Select "Yes, Help Me" when prompted for help getting started.
1. Complete both tours in the Next Steps section.

**Result:** see the full video for this signup and quick start test: [13m6s](https://cloudup.com/c7gu79UYhB2).

* Couldn't get past the "Publish new post" step at first because the floating action bar was missing the first time trying the step. (scroll to 7:52 in the video)

<img width="270" alt="Screen Shot 2020-08-28 at Aug 28 5 42 04 PM" src="https://user-images.githubusercontent.com/1119271/91622783-06470b80-e956-11ea-83d5-e021f1e1657d.png">
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-2 on Pixel 3 Android 10.</sup></p>

**Nitpicks:**

* The "Customize your site" step led me to the browser where I was logged in as a different user. (5:21)
* Strange scrolling glitch when trying to select/deselect sharing buttons. (5:46)
* Initial stats screen doesn't look good on a brand new site. (12:14)

Notes: It's possible this was an odd glitch. If you can't replicate, let me know and I'll try testing again. Also, nitpicks can be filed separately if that's wanted—just let me know!

**Comment by aforcier** [comment]
Just a quick note to mention that I tested this on `15.5.1` and could reproduce for that version as well (I was checking if https://github.com/wordpress-mobile/WordPress-Android/pull/12728 might be the cause, looks like it isn't).

**Comment by khaykov** [comment]
So, I watched the video and can reproduce and confirm that that the FAB is missing right after site creation for new accounts. Quick Start trying to point to it is just a consequence. I pinpointed the issue to 15.5.1 (15.4 is ok).

I did some more digging and was able to pinpoint it to [this](https://github.com/wordpress-mobile/WordPress-Android/commit/675c9c122723960f4526e9dfca27ac2c2fa00f08#diff-50e9b65f54841aa53f45b1ecf2af52e5) commit, where we changed the way site creation progress starts. ping @renanferrari 

On a separate note, the FAB is also not shown when you create a new site separately from the signup process (eg you created an account, and went to My Site screen, and created a site from there). Maybe @develric has some more context on this one.

@designsimply Regarding the indicator dot on the site icon - you should not see the dot until you start the task (tap GO when the prompt appeared) :)
Also, thank you so much for digging deep! Video really helps pinpoint the exact case of the issue :)

**Comment by renanferrari** [comment]
>I did some more digging and was able to pinpoint it to [this](https://github.com/wordpress-mobile/WordPress-Android/commit/675c9c122723960f4526e9dfca27ac2c2fa00f08#diff-50e9b65f54841aa53f45b1ecf2af52e5) commit, where we changed the way site creation progress starts. ping @renanferrari
> 
>On a separate note, the FAB is also not shown when you create a new site separately from the signup process (eg you created an account, and went to My Site screen, and created a site from there). Maybe @develric has some more context on this one.

Thanks for pinging me here, @khaykov. I wasn't able to look much into this today, but what I can say for now is that since you said the FAB is also not being shown when you don't create a new site from the Post-Signup Interstitial, then I believe it's unlikely that this is related to that specific change you mentioned, as we only start the site creation flow in that new way if we tap the "Create WordPress.com site" button. 

I'll be happy to take another look at this next week either way 🙂

**Comment by khaykov** [comment]
@renanferrari Yes, I think that commit just uncovered the underlying issue. I think I might know what the problem might be, so I'll try to fix it 👍

**Comment by renanferrari** [comment]
@khaykov Let me know if I can help you with anything :)
