### ISSUE TITLE
Some ReaderPost list items are shown with a huge bottom padding

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#12840]
Some ReaderPost list items are shown with a huge bottom padding

### Steps to reproduce the behavior
1. Open Reader on Android API 22
2. Scroll until you encounter a post with a huge bottom padding

<img src="https://user-images.githubusercontent.com/2261188/91712024-3c1f0680-eb87-11ea-9914-9e7037ba188c.png" width="250px" />

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, API 22

**Comment by malinajirka** [comment]
This issue is fixed in `com.google.android.material:material:1.2.0` - https://github.com/material-components/material-components-android/commit/6f10bd0606ee68ddd19a269694374e8d3525a672. We'll update the library during the hack week.

**Comment by ashiagr** [comment]
Material library updated to `1.2.1`, marking this issue as closed.
