### ISSUE TITLE
Update Action mode in Media Picker 

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#12865]
Based on the designs the action mode should have grey background and the "Edit" icon should show the number of items that are selected. 

The task of this PR is to implement these two changes and generally update the action mode to look according to the designs.

**Comment by designsimply** [comment]
Do you have a design file you could include with this issue? What is the action mode?

**Comment by khaykov** [comment]
Action mode is the AppBar that appears above the regular one, usually when you select some elements on the screen.
Here is the design:
[![Image from Gyazo](https://i.gyazo.com/ec453e327ec3ed6577843bc33a2eb8eb.png)](https://gyazo.com/ec453e327ec3ed6577843bc33a2eb8eb)
