### ISSUE TITLE
Wrong thumbnail shortly shown for videos at the end of the upload in media library

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#12885]
While working on #12867 we noticed the following behaviour (that is not related to that PR itself).

### Expected behavior
In Media library, when loading a video from the device, in the final upload phase a thumbnail should be shown taken from the video frames.

### Actual behavior
In Media library, when loading a video from the device, in the final upload phase sometimes a thumbnail is shown that is not taken from a preview of the video, but it seems taken from another of the images that are already loaded in the Media Lib; then after a short time from the end of upload the actual and correct video thumbnail is shown (I do not have steps to reproduce consistently but it happened a few times in my emulator). I don't think this is related to this PR tbh, so we can further investigate/address in another PR, but I preferred to mention so we do not overlook it (let me know if you want me to open a ticket for this 🙇‍♂️ ).

### Steps to reproduce the behavior
unfortunately it does not reproduce consistently for me but was able to reproduce few times in the following way:

- be sure you have a media library with some images and videos already loaded
- try to upload a video from the device
- when the issue happens you can notice the thumbnail shown at the end of the video upload is not taken from the video but is one of the already loaded in the library image thumbnail
- after a short time (like a second or so) from when the issue happens the correct thumbnail taken from the video frames is shown

**Comment by designsimply** [comment]
The problem where the wrong thumbnail sometimes shows up for a video upload in the media library came up in an app review:

> I've had the app for 2 weeks. In the beginning everything worked fine. For a few days now I have barely been able to edit posts. If I want to select videos from the media library, it does not work because it takes forever for the videos to build up and pictures are displayed in the video frame that do not belong to the video. When I then click one, the app usually hangs up. I've already checked everything. I think your app is overloaded!
> 
> <sup>3-star app review - Oct 26-2020 at 7:45 AM - Nokia 6.1, WPAndroid 15.9.1, Android 10</sup>

<sup>play-store-reviewid=gp:AOqpTOEFa_4xGgTSHTiglh4RCq63eL5LeLWEVJeE6RGXo9aJqfqZMwPRu0tCb2jXp1YRnuRhQtBWpYjeTZuFGQ</sup>

**Comment by thehenrybyrd** [comment]
I was unable to reproduce this in WP Android 20.6-rc-3, Android 12, on Samsung Galaxy S21. 
Currently, the initial thumbnail show is a simple dark grey background, which is updated to the correct thumbnail after a pull-to-refresh.
