### ISSUE TITLE
Reader Detail: Post content loses paragraph spacing on second viewing

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-Android#12906]
| First View | Second View |
|:--:|:--:|
|<img src="https://user-images.githubusercontent.com/793774/92484379-75b2cb80-f19e-11ea-9d58-4734f7c81f21.jpg" width="50%" />|<img src="https://user-images.githubusercontent.com/793774/92484388-777c8f00-f19e-11ea-92dc-1f6dd66dd4fd.jpg" width="50%" />|

### Steps to reproduce the behavior
1. Launch the app
2. Tap on the Reader tab
3. Tap on the Following section
4. Tap the Cog
5. Tap the 'Followed Sites' section
6. Add `techcrunch.com`
7. Go back to the following feed
8. Tap on any post
9. Notice the paragraph spacing is being rendered correctly
10. Hit back
11. Tap on the same post

Demo Video: https://cloudup.com/cKqZ_KjiEga

### Expected behavior
The paragraph spacing is rendered correctly

### Actual behavior
There is no paragraph spacing when viewing a post for the second time

##### Tested on [device], Android [version], WPAndroid [version]
 Android 10 + ColorOS V7, WPAndroid 15.4.1

**Comment by thehenrybyrd** [comment]
I was unable to reproduce this in WP Android 20.6 on Samsung Galaxy S21.
Please reopen if still valid.
