### ISSUE TITLE
Manage adding from Free Photo Library case in Media Picker for WP Stories.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#12914]
This is related to the #12884 PR

In that PR we are removing menus when user need to browse the device for media and the user is directly landed to the system file browser with the correct file type filtering (image only, video only, image and video only or all files with a supported WP MIME type); menus we are removing are like this one:

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/92580927-4fb92400-f28f-11ea-833c-a647bb864bdc.png>
</p>

In the above WP stories specific case we should allow user to choose if source is the Device or the Free Photo Library so we should keep the menu (or find an alternative UX).

cc @planarvoid

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
