### ISSUE TITLE
Clicking New Post or New Page causes the app to crash in 15.7-rc-1 (WordPress.com Simple sites only)

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#12927]
### Expected behavior

Clicking on the new post button when trying to create a new post would open the editor.

### Actual behavior

When I click on the + button to add a new page or page and then select either of the options, the app does a refresh the first time around and keeps me on the My Site page. The second time I do so, the app crashes and a message with as pop-up that 'WordPress keeps stopping' comes up.

A new draft is created and when you try to open the draft, the app crashes. 

### Steps to reproduce the behavior

1. Start from My sites and click on the + button
2. Click 'Add New Post'
3. The app refreshes
4. Click on the + again and add new post.
5. The message comes up that WordPress stops working.
6. Go to Site > Blog Posts > Drafts and the post appears (untitled) Local draft. 
7. Try to open the post, the app crashes again.

This wasn't originally happening on a private atomic site, but after re-installing it's also crashing there. 

##### Tested on Samsung Tab A, Android 10, WPAndroid 15.7-rc-1

Beta User reported in 3303751-zen

**Comment by designsimply** [comment]
Nice catch @rezzap !!! 

Tested and confirmed using with WPAndroid 15.7-rc-1 on Pixel 3 Android 11. Oof, I'm surprised I didn't catch this earlier—I happened to literally test every single other type of site and didn't hit the bug on any of them! Grr. However, it's an excellent case showing our beta testers being really awesome. ❤️

I couldn't replicate the bug with a WordPress.com Business, Jetpack, or self-hosted site, so I'll update the title accordingly.

**Comment by maxme** [comment]
I found this crash on alpha-242 yesterday when testing the update and @loremattei published an update quickly after that (15.7-rc-2 and alpha-243). It's not clear why this happened, local builds of these versions where not crashing but the one we got from the Play Store was flawed. I'm not sure if Lorenzo had time to investigate the build logs yet.
