### ISSUE TITLE
Update header for P2 postcards to show author

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-Android#12934]
After receiving some feedback internally that it's much more efficient to have the author name included in the postcard UI for P2 posts specifically, I've updated the design for P2 postcards as per below:

Changes to header include:

- Show author name next to site name
- Show author icon next to site icon
- Show timestamp below

<img width="850" alt="Screen Shot 2020-09-10 at 2 58 13 PM" src="https://user-images.githubusercontent.com/6350997/92786232-127b9180-f376-11ea-89d3-eecccd0c38e2.png">

<img width="858" alt="Screen Shot 2020-09-10 at 2 58 19 PM" src="https://user-images.githubusercontent.com/6350997/92786244-14ddeb80-f376-11ea-8813-4f164c9aa973.png">

Specs coming tomorrow (Sep 11)

**Comment by ScoutHarris** [comment]
From https://github.com/wordpress-mobile/WordPress-iOS/issues/14875#issuecomment-726152245:

There is a slight change in design:

> On cross-post cards, the author avatar is on top of the site icon. Can we make the P2 card the same for consistency?

> Good catch! yes, let's do that.

And a clarification:

> do you want to show the author any time a P2 card is displayed in any Reader feed (Following, Likes, etc.)? Or just when Automattic is selected?

> Yes, anywhere the card is displayed (likes/saved).

**Comment by ScoutHarris** [comment]
From https://github.com/wordpress-mobile/WordPress-iOS/issues/14875#issuecomment-726901672 - another change in design. We decided to still display the URL.
