### ISSUE TITLE
Feature Request: add Facebook and Twitter login options

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12998]
We received a request to add Facebook & Twitter login options in our beta tester feedback.

> Facebook/Twitter login pls.

<sup>Sep 17, 2020 at 10:18 PM - Galaxy On Nxt WPAndroid 15.6 Android 8.1</sup>
<sup>play-store-feedbackid=gp:AOqpTOGTX181J4jWlS-71kxUqLV5nIFJaT6z5vdf8tHjiqHAqQsOJhgLnjTttxe1Tt77aWWDzSa7PosYn_ENihh-</sup>

**Comment by jkmassel** [comment]
We will not be pursuing this – we're moving toward web-based authentication, so we'll support what .org site owners choose for their sites, and what WP.com does.
