### ISSUE TITLE
AppBar: the header covers up some of the data in "View more" screens in the Stats section

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13025]
Steps to reproduce:

1. Go to Stats > Insights.
1. Tap "View more" on the Latest Posts Summary card.
1. Tap "View more" on the Recent Weeks card.

**Result:** the first row of data is cut off and you cannot scroll to see it.

<img src="https://user-images.githubusercontent.com/1119271/94480781-070cd080-0194-11eb-8f21-2390aa4af10f.png" width="270" alt="Screenshot_20200928-140329">
<p style="clear:both;"><sup>Tested with WPAndroid 15.8-rc-1 on Pixel 3 Android 11.</sup></p>

**Comment by khaykov** [comment]
@designsimply I don't have "View more" on the Recent Weeks card, and not sure how to get to that page 😕 Any ideas on what I might be doing wrong?

[![Image from Gyazo](https://i.gyazo.com/d8b4e3b2062f63fa34a47296b3030886.gif)](https://gyazo.com/d8b4e3b2062f63fa34a47296b3030886)

**Comment by designsimply** [comment]
Strange! I don't see it anymore either! I'm certain it was there before though—screenshot as evidence! 😂

Well, I'll close this for now unless I can spot the issue again.
