### ISSUE TITLE
Only allow supported media types in media selecting entry points

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#13036]
### Expected behavior
History: follow up from https://github.com/wordpress-mobile/WordPress-Android/issues/12822 - the fix in https://github.com/wordpress-mobile/WordPress-Android/pull/12824 turned out to cause major delays as explained in https://github.com/wordpress-mobile/WordPress-Android/issues/12996.

Given this, the expected behavior would be to not allow people to pick unsupported media items.
For this, it'd be nice to give users a heads up that they've just selected an unsupported media item once it has been assigned to a block, or attempted to be inserted in Aztec or a Story or uploaded to the Media Browser, for example.

I think we should be ok with this and perhaps move the checks for supported media types only on the insertion points once the potentially unsupported file has been picked (i.e. Aztec, Gutenberg, Media browser, Stories).

### Actual behavior
Currently, after this https://github.com/wordpress-mobile/WordPress-Android/pull/13035 gets merged (and as such we get back to the situation described in https://github.com/wordpress-mobile/WordPress-Android/issues/12822), users can choose an unsupported media type item  and these won't get uploaded, but the editors will just continuously say "tap to retry".

### Steps to reproduce the behavior
Same as described in https://github.com/wordpress-mobile/WordPress-Android/issues/12822

**Comment by thehenrybyrd** [comment]
I was unable to reproduce this issue with a .webp image in Gutenberg. Tried in WP Android 20.6 on Samsung Galaxy s21. I was also unable to view unsupported files (such as a .apk) which appear in my Files app but would not appear when using "choose from device" to upload files.
From what I can tell, this issue has been fixed somewhere along the way, so I'm going to close it.
