### ISSUE TITLE
EncryptedLogging: ExceptionInInitializerError

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13044]
**Sentry Url**: https://sentry.io/share/issue/16f46ed069914393abcc576fae700e8d/
**User Count**: 83
**Count**: 160
**First Release**: org.wordpress.android@15.6+915
**First Seen**: 2020-09-10T04:08:34Z
**Last Seen**: 2020-10-01T08:04:40Z
**24 Hours**: 10
**30 Days**: 160

```
ExceptionInInitializerError: 
     at org.wordpress.android.util.EncryptedLogging.start(EncryptedLogging.kt:42)
     at org.wordpress.android.WordPress.onCreate(WordPress.java:266)
...
(19 additional frame(s) were not displayed)
```

**Comment by loremattei** [comment]
cc @jkmassel

**Comment by bummytime** [comment]
@jkmassel  Looks like this commit https://github.com/wordpress-mobile/WordPress-Android/commit/738a93400395cf0eecf46a7061b189d275334a15 **may** be the culprit for these crashers? Any thoughts on this one?

**Comment by jkmassel** [comment]
These seem to be exclusively very old Samsung devices that hit this issue, all of which are running Android 5. I'd guess it's a bad software version that somehow doesn't work right with loading Sodium. Given the low number of device types affected, we could probably make a list of those that just don't get encrypted logging to avoid this crash (though I wonder how they'd fare trying to launch Gutenberg with Hermes)

**Comment by designsimply** [comment]
**Events in the last 90d:** 318
**Users affected in the last 90d:** 147
**Limited to:** Samsung devices with Android 5.x
<sub>WORDPRESS-ANDROID-Q9R: https://sentry.io/share/issue/16f46ed069914393abcc576fae700e8d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1886989694&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96310282-53de0d00-0fc4-11eb-9b70-2d0333ff3223.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 757
**Users affected in the last 90d:** 291
**Limited to:** Samsung devices with Android 5.x
<sub>WORDPRESS-ANDROID-Q9R: https://sentry.io/share/issue/16f46ed069914393abcc576fae700e8d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1886989694&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100553765-f4268300-324c-11eb-9bd3-1ef0d88a49db.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 1,200
**Users affected in the last 90d:** 363
**Limited to:** Samsung devices with Android 5.x (and 1 case in 8.0)
<sub>WORDPRESS-ANDROID-Q9R: https://sentry.io/share/issue/16f46ed069914393abcc576fae700e8d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1886989694&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105526266-66d93b00-5c9f-11eb-97c5-47e4bf98f57c.png)</a>

**Comment by planarvoid** [comment]
I've investigated this issue and it seems that there is a problem with some older Samsung devices. You can read more about the bug [here](https://github.com/Kotlin/kotlinx.coroutines/issues/490). There is nothing we can at the moment to fix this. We'll get rid of this once we move `minSdk` from 21 to 22.

**Comment by thehenrybyrd** [comment]
We recently moved `minSdk` to API 24: https://wp.me/paaHJt-2pw
It's probably a good time to take another look at this and see if we can close it; I'll put it in groundskeeping for that purpose.

**Comment by zwarm** [comment]
The `minSdk` was upped from 21 to 24 starting with `release 18.0`. As of today, Sentry hasn't identified this issue in `18.0` release. However it is still occurring in release < 18.0 and as already stated above, there is nothing we can fix. We will need to wait one more groundskeeping round to review live data before officially closing the issue.

**Comment by ravishanker** [comment]
Given that it is actually on the wane and happening still only on older Samsung devices and below v18.0.  I'm closing this issue

**Events in the last 90d:** 143
**Users affected in the last 90d:** 84
**Limited to:** Samsung devices with Android 5.x (and 1 case in 8.0)
<sub>WORDPRESS-ANDROID-Q9R: https://sentry.io/share/issue/16f46ed069914393abcc576fae700e8d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1886989694&sort=-timestamp&statsPeriod=90d&user=1079278&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/990349/131429934-8ed9fb0f-8176-4770-b3b9-74faadc72ba6.png)</a>
