### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a n...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13045]
**Sentry Url**: https://sentry.io/share/issue/7cacd4f401ea4058bf8b971fa13399eb/
**User Count**: 760
**Count**: 941
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-07-03T09:14:52Z
**Last Seen**: 2020-10-01T07:48:08Z
**24 Hours**: 7
**30 Days**: 282

```
NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a null object reference
     at org.wordpress.android.ui.prefs.SiteSettingsFragment.onSiteChanged(SiteSettingsFragment.java:1976)
...
(1 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@planarvoid Looking through the history of `SiteSettingsFragment`, this commit https://github.com/wordpress-mobile/WordPress-Android/commit/c6cd5191e09978eec008cdfb8ff00a8f348945fb#diff-2ef05e651dd8427b13f1714a6f1afeb1 seems to line up with the timing (crashes first seen on Jun 20, 2020) of this crasher. Would you checking this one out?

**Comment by planarvoid** [comment]
hey @bummytime , I don't think that's commit is related but I'll look into it, it seems like a simple fix (even though it's scary it appeared 4 months ago)
