### ISSUE TITLE
Permission issue while reading images from device

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#13055]
While reviewing the #13009 PR I noticed the issue described below. Tracking here since it is something to further investigate.

### Expected behavior
I expect to be able to add an image to a GB image block from device.

### Actual behavior
At least with code from the above mentioned PR when trying to add an image from device to the GB image block in logcat I get the error `7103-7103/org.wordpress.android.beta E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Download/amazing-animal-beautiful-beautifull.jpg: open failed: EACCES (Permission denied)` and the following error is shown in the UI

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/95095157-fb3c8380-072a-11eb-8629-9e1b6c81e40d.png>
</p>

### Steps to reproduce the behavior
- In GB editor add an image block
- Try to add an image from device
- Notice you get the error as per above image and log

##### Tested on [Pixel 3 Emu], Android [API 29], WPAndroid [13009 PR]

**NOTE:** as suspected by @planarvoid it seems related to API 29 permissions management. With API 28 the issue is not present.

**Comment by thehenrybyrd** [comment]
I'm no longer able to reproduced this in WP Android 20.6 on Samsung Galaxy S21. It seems the fix for API 29 sorted this out, or we've fixed this somewhere else along the way.
Closing for now, please reopen if necessary.
