### ISSUE TITLE
Unsupported block bottom sheet is triggered when device is rotated

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#13052]
### Expected behavior

When a post that contains an unsupported block is open in the block editor, rotating the device shouldn't cause a bottom sheet to appear.

### Actual behavior

When a post that contains an unsupported block is open in the block editor, rotating the device **causes a bottom sheet to appear**.

### Steps to reproduce the behavior

1. Open the block editor on a post that contains an unsupported block (e.g. Audio is a block that's not yet supported on mobile at time of writing)
2. With the editor open, rotate the device and notice the bottom sheet appears

**Comment by guarani** [comment]
The fix should be the same as what was done for the Reusable block component, see [here](https://github.com/WordPress/gutenberg/pull/25265/commits/f99ef14d255a2234579140cea225d5c8ee2421e1).

**Comment by hypest** [comment]
Related and probably the same issue as https://github.com/wordpress-mobile/gutenberg-mobile/issues/2680. Leaving both open until those get investigated. @marecar3 please check out both of these issues, thanks!

**Comment by marecar3** [comment]
> Related and probably the same issue as [wordpress-mobile/gutenberg-mobile#2680](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2680). Leaving both open until those get investigated. @marecar3 please check out both of these issues, thanks!

Thanks, @hypest, I will prioritize it.
