### ISSUE TITLE
Site Pages feature missing for Editor on self-hosted sites

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13056]
### Expected behavior
I would expect the Editor user of a self-hosted WordPress site is able to access the Site Pages feature on the app.

### Actual behavior
Site Pages feature is missing for Editor on self-hosted WordPress site.

### Steps to reproduce the behavior

1. Log in to the app as an Editor user of a self-hosted WordPress site (not connected to Jetpack).
2. See that the Site Pages feature is missing.

#### Self-hosted WordPress site (Version 5.5.1) + Editor role + iOS app (Version 15.7)

The Site Pages feature is available on the iOS app.

<img src="https://user-images.githubusercontent.com/40906847/95148467-f2dd5a80-07b5-11eb-9372-fecb3ad774d4.png" width="270" alt="img_0010">

#### Self-hosted WordPress site (Version 5.5.1) + Editor role + Android app (15.7 and 15.8-rc-2)

The Site Pages feature is missing.

<img src="https://user-images.githubusercontent.com/40906847/95148697-8adb4400-07b6-11eb-85b2-8f26c16e227c.jpg" width="270" alt="Screenshot_20201006-091250">

#### Self-hosted WordPress site (Version 5.5.1) + Jetpack (Version 8.9.1) + Editor role + (15.7 and 15.8-rc-2)

The Site Pages feature is available.

<img src="https://user-images.githubusercontent.com/40906847/95148808-df7ebf00-07b6-11eb-9723-c8ead7c25871.jpg" width="270" alt="Screenshot_20201006-092142">

##### Tested on Huawei Nova 2i, Android 8, WPAndroid 15.7

Also tested on OPPO Reno 4, Android 10, WPAndroid 15.8-rc-2

Originally reported at [the forum](https://android.forums.wordpress.org/topic/pages-not-showing-up-for-editor-role).

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid 15.9-rc-1 on Pixel 3 Android 11. Thank you for the report @reginabally! 

Even though this issue was filed first, I'd like to close it in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/13057 which already has some additional discussion and technical detail in the comments.
