### ISSUE TITLE
Check all string identifiers in the app and rename ambiguous one to help translators

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1306]
Rename ambiguous strings that can refers to verbs or nouns like: `trash`, `like`, `comment` - rename the string id to explicit where it's used: `trash_action` for instance or even `trash_verb`.

**Comment by oguzkocer** [comment]
@maxme is this something we still want to do? If so, would refactoring all these names break the translated strings? If we still want to do it, I think it's better handled sooner rather than later, so we can start following the naming pattern and handle less(!) strings right now.
