### ISSUE TITLE
Local changes label appears after I open a page and close it without making any changes

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#13072]
### Expected behavior
When I open a page and close it without making any changes, the "local changes" label does not appear.

### Actual behavior
When I open a page and close it without making any changes, the "local changes" label appears.

I think it happens only on self-hosted sites (eg. jurassic ninja). It does NOT happen on posts so I believe there isn't any technical limitation.

<img src="https://user-images.githubusercontent.com/2261188/95312696-89ca1580-088f-11eb-9620-14d3b075495a.gif" width="250px" />

### Steps to reproduce the behavior
1. Open Page List
2. Open a published page
3. Close the editor
4. Notice "local changes" label appears

##### Tested on [device], Android [version], WPAndroid [version]
Emulator API 27

**Comment by thehenrybyrd** [comment]
I'm no longer able to reproduce this in **WP Android 20.5-rc-1**, on **Samsung Galaxy S21**. 
I do remember seeing this issue previously on this device, so I suspect it's been resolved. I'll close for now.
