### ISSUE TITLE
Referrers "View more" is sometimes hidden

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#13086]
When some of the referrers are marked as a spam, they're not returned from the API. However, the endpoint still counts them in the limit and this causes the "View more" item to be incorrectly invisible. This needs to be fixed on the API.

Steps to reproduce:
- Mark your referrers between position 1 and 6 as spam
- Go to Stats/Referrers block
- Notice that the referrers you marked as a spam are invisible
- Notice that there are no referrers replacing them and the "View more" item is not visible

**Comment by guarani** [comment]
👋 Could you please report this in https://github.com/Automattic/jetpack if this is an API issue, @ravishanker?

**Comment by ravishanker** [comment]
Please see issue on Jetpack https://github.com/Automattic/jetpack/issues/36910
