### ISSUE TITLE
Post Previews: Previewing changes to an already published post on an Atomic site shows the published version

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#13093]
### Expected behavior
When editing an already published post and previewing changes, we expect to see a preview of those changes appear in a web browser. 

### Actual behavior
The published version of the post is shown rather than the autosave. 

### Steps to reproduce the behavior
Edit a post on an Atomic site.  Do not use an ephemeral site as they do not correctly report their atomic status via the REST API.
After making some changes, attempt to preview the changes via the Preview option. 

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 2, 14.8-rc-1  There is some more context and proposed fix at https://github.com/wordpress-mobile/WordPress-iOS/pull/15061#issuecomment-705840222

**Comment by designsimply** [comment]
Thank you for the report @aerych! Tested and confirmed using the following steps:

1. In the app, open a WordPress.com Business site that has plugins installed.
1. Open any previously published post in the block editor.
1. Make changes to the title and content.
1. Go to  More (three dots at top right) > Preview.
1. Check to see if the changes are present.

Results: the title change is visible but the content area says "Preview Unavailable." ([1m44s](https://cloudup.com/cvcR7TTinGO))

<img src="https://user-images.githubusercontent.com/1119271/95625163-4e694b80-0a35-11eb-94cf-ff1df657d5f2.png" width="270" alt="Screenshot_20201009-131356">
<sup>Tested with WPAndroid 15.8.1 on Pixel 3 Android 11.</sup>

Related comment from an auto-upload + auto-save project done in Sep 2019:

> The site on which the preview doesn’t work has a business plan – it’s an atomic site. Therefore it behaves like a JetPack and not pure WPCom site. As I mentioned in the article there is a bug in Jetpack which prevents us from supporting previews on such sites. Hopefully it’ll get fixed soon and we’ll re-enable it in the apps.
> 
> <sup>(internal reference: p77Llu-cHb-p2#comment-15011)</sup>
