### ISSUE TITLE
request fdroid download

### ISSUE THREAD

**Issue by songsammy** [wordpress-mobile/WordPress-Android#13102]
I am in a region where google services is not available. 
I' read #9387 but here's what i wanted.
I don't need features like login with google, so will you please release a version like an fdroid version.
An official fdroid version without sensitive data.

**Comment by designsimply** [comment]
Thank you for your interest in the app. The answer in #9387 still stands at the moment and I'm sorry I don't have a better answer for you at this time. As mentioned in the other issue, installing the app with limits on the functionality is currently the best available solution. You can find .apk files attached for each release at https://github.com/wordpress-mobile/WordPress-Android/releases.
