### ISSUE TITLE
Preview feature isn't working when draft isn't saved after adding the second block

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13115]
### Expected behavior
I would expect the Preview feature to automatically save the draft for me and let me preview my draft after I added the second (and more) block to the page/post.

### Actual behavior
The Preview feature doesn't pop-up the preview screen to let me view my draft after I added a second block.

### Steps to reproduce the behavior

1. Go to My Site > Site Pages or Blog Posts to create a new page/post
2. Add a Paragraph block with some text
3. Tap Preview and see the notification that the post is saving
4. App launches a pop-up with the preview of the content
5. Add a new block to the page/post and add more content
6. Tap Preview again and see the notification that the app is generaing a preview
7. Nothing happens after the notification
8. Tap Preview once again, app launches a pop-up with the preview of the content.

Please see the video recording here: https://d.pr/v/ROV4zw/HkxbMQfgnS

##### Tested on Oppo Reno 4, Android 10, WPAndroid 15.9-rc-2

Originally reported in an app review.

> pls update the preview button, if u want to preview while ur yet to save ur draft / post; after u press the preview button it saves the draft / post first then u have to press it again to really preview it; what u should do rather is after u press the preview button while ur yet to save ur draft / post, show still the process that its being save (or better not), then proceed the with preview already ok

Date of review: Oct 1, 2020, 03:20
Device: Redmi 9
App version code: 924
App version name: 15.7

**Comment by designsimply** [comment]
Thank you for reporting this @reginabally! We're already tracking this issue at https://github.com/wordpress-mobile/WordPress-Android/issues/12570 so I will close this one as a duplicate. 👍
