### ISSUE TITLE
Copy Logs and Share button can't be seen against white background

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#13120]
### Expected behavior

I would expect to be able to see the copy and share buttons in the top corner of the Application Logs page which helps users share logs with us.

### Actual behavior

The buttons are showing white against white, therefore can't be seen.

### Steps to reproduce the behavior

1. Navigate to Me > Help & Support
2. Go to Application Log
3. View the button in the top right corner which don't display. 

<img width="630" alt="Image 2020-10-13 at 3 01 33 pm" src="https://user-images.githubusercontent.com/10325627/95871066-25aec200-0d65-11eb-9bcc-a81e7e265846.png">

##### Tested on Samsung Galaxy S9+, Android 10, WPAndroid 15.9-rc-2
Reported by a user in 3399425-zen

**Comment by designsimply** [comment]
Thank you for the report @rezzap!! We're tracking this one in https://github.com/wordpress-mobile/WordPress-Android/issues/13067 so I'll close this as a duplicate. 👍
