### ISSUE TITLE
Post Settings: location setting does not stay open on first tap, "locations near me" list is missing, and location setting is not visible after it is set unless you leave and return to Post Settings

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13135]
Steps to reproduce:

1. Go to My Sites > + > Blog post to start a new post.
1. Go to More (three dots at top right) > Post settings.
1. Scroll down and tap Location.
1. Observe that a window opens and immediately closes the first time Location is tapped.
1. Tap Location again.
1. Look for a list of "locations near me" to select from.
1. Observe there is nothing in the "locations near me" list.
1. Select a location and tap "Select this location" then "Select".
1. Observe that the location setting is still blank.
1. Return to the post and re-open Post Settings.
1. Observe that the location setting now shows the previously selected location.

**Result:** location window opens and closes immediately the first time Location is tapped in Post Settings, "locations near me" are no longer listed making it difficult to select a location nearby, and a selected location does not appear in Post Settings after it is selected unless you close and re-open Post Settings. ([1m52s](https://cloudup.com/cOywd3YinSp))

Location does not stay open on first tap|Should a nearby places list be populated automatically?|Select location|Location does not appear after it is selected
---|---|---|---
![location-does-not-stay-open-on-first-tap](https://user-images.githubusercontent.com/1119271/96023985-6e6f8500-0e10-11eb-9c14-14d07bbda731.gif)|![Screen Shot 2020-10-14 at Oct 14 11 31 09 AM](https://user-images.githubusercontent.com/1119271/96024403-e8a00980-0e10-11eb-968f-290c369105da.png)|![Screen Shot 2020-10-14 at Oct 14 11 27 01 AM](https://user-images.githubusercontent.com/1119271/96024011-74fdfc80-0e10-11eb-999c-dff2d2172ba1.png)|![Screen Shot 2020-10-14 at Oct 14 11 26 43 AM](https://user-images.githubusercontent.com/1119271/96024002-729ba280-0e10-11eb-9af8-6239a8287d17.png)

<sup>Tested with WPAndroid 15.9-rc-2 on Pixel 3 Android 11 using a WordPress.com Free site (fuzzywuzzy.home.blog) logged in as user design5279.</sup>

Originally reported in an 15.9 beta tester feedback via the Google Play Store:

> The location function for posts is broken and has been broken for some time. When I try to post location I have to make several attempts as the location window only pops up for only a quick moment and then closes. When I do finally get it to open and stay open I have no options to select location, where it used to list locations near me to select from there is no longer a list and the only option I am given is to select where I exactly am on the map which takes some time to select.

<sup>Oct 14, 2020, 07:23
Device: Samsung Galaxy Note9
Device language: English
App version code: 933
App version name: 15.9-rc-2
Android version (SDK): Android 10 (SDK 29)
Internal reference: play-store-reviewId=gp%3AAOqpTOG_TeLh5ivrIxi3BJ9s1jIxgEKF3T-0U8pGgUUgOecZIa6qptigk-BB5TG5-XEYWLy737fRPybgj2lJsCHE</sup>

**Comment by khaykov** [comment]
Looks like the PlacePicker library we were using was deprecated, and is no longer working. I will try to migrate us to the new version.
