### ISSUE TITLE
Indeterminate progress bar in site icon when cancelling editing.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#13155]
### Expected behavior
When setting/change the site icon, when landed into the photo edit, if I cancel the operation (x cross on top left) site icon should stay unchanged

### Actual behavior
When setting/change the site icon, when landed into the photo edit, if I cancel the operation (x cross on top left) site icon get the indeterminate progressbar that is never stopped.

### Steps to reproduce the behavior
- My Site -> Change site icon 
- Select an image and tap on confirm
- in the Edit Photo screen tap on the top left x icon and check the indeterminate progress bar is shown in the site icon placeholder

**Comment by ParagDalvi** [comment]
@develric this is because circular progress is handled after selecting the image and also after cropping it. It can be solved by setting the circular progress only after cropping the image.

So I have removed the lines which set progress after selecting the image from the image picker.

by replacing
```
fun handleTakenSiteIcon(iconUrl: String?, source: PhotoPickerMediaSource?) {
        val stat = if (source == ANDROID_CAMERA) Stat.MY_SITE_ICON_SHOT_NEW else Stat.MY_SITE_ICON_GALLERY_PICKED
        analyticsTrackerWrapper.track(stat)
        val imageUri = Uri.parse(iconUrl)?.let { UriWrapper(it) }
        if (imageUri != null) {
            selectedSiteRepository.showSiteIconProgressBar(true)
            launch(bgDispatcher) {
                val fetchMedia = wpMediaUtilsWrapper.fetchMediaToUriWrapper(imageUri)
                if (fetchMedia != null) {
                    _onNavigation.postValue(Event(SiteNavigationAction.OpenCropActivity(fetchMedia)))
                } else {
                    selectedSiteRepository.showSiteIconProgressBar(false)
                }
            }
        }
    }
```
    
to 

```
fun handleTakenSiteIcon(iconUrl: String?, source: PhotoPickerMediaSource?) {
val stat = if (source == ANDROID_CAMERA) Stat.MY_SITE_ICON_SHOT_NEW else Stat.MY_SITE_ICON_GALLERY_PICKED
        analyticsTrackerWrapper.track(stat)
        val imageUri = Uri.parse(iconUrl)?.let { UriWrapper(it) }
        if (imageUri != null) {
            launch(bgDispatcher) {
                val fetchMedia = wpMediaUtilsWrapper.fetchMediaToUriWrapper(imageUri)
                if (fetchMedia != null) {
                    _onNavigation.postValue(Event(SiteNavigationAction.OpenCropActivity(fetchMedia)))
                }
            }
        }
    }
```


https://user-images.githubusercontent.com/29736284/153401074-c808212d-e974-45f4-bb56-4e58d1fbd4b1.mp4


Am I missing anything? Is this the right approach? @develric

**Comment by antonis** [comment]
Hey @ParagDalvi 👋 
Thank you for stepping forward to help with this issue 🙇‍♂️ 

> Is this the right approach?

Your approach looks good 👍 
Please open a pull request to test this further and integrate your fix in the codebase. Don't hesitate to ping us if you need more help on this.
