### ISSUE TITLE
Reader Posts intermittently duplicated upon bookmark action

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#13163]
### Expected behavior
Reader post is shown once in the feed

### Actual behavior
The reader post is duplicated in the feed after bookmarking
 detail | detail | feed
---|---|---
<img width="480" src="https://user-images.githubusercontent.com/506707/96300871-4f195900-0fc4-11eb-9208-ade7cbb97bba.png">|<img width="480" src="https://user-images.githubusercontent.com/506707/96300872-517bb300-0fc4-11eb-9f65-76693bc36cf3.png">|<img width="480" src="https://user-images.githubusercontent.com/506707/96300878-53de0d00-0fc4-11eb-82a3-d878212d531f.png">

### Steps to reproduce the behavior
1. Launch app
2. Tap on Reader
3. In following feed tap a post to launch the reader detail view
4. Tap the bookmark action icon
5. The post will be duplicated in the feed or the reader detail pager

**Comment by designsimply** [comment]
Not sure if it's related, but there's another issue on file about duplicate sites showing in the Reader at https://github.com/wordpress-mobile/WordPress-Android/issues/12938 that I wanted to mention in case fixing one affects the other. 😊

**Comment by ashiagr** [comment]
Duplicate Issue. 
Will be fixed as part of issue #12938.
