### ISSUE TITLE
Featured image not set from WP Media Lib in http self-hosted sites

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#13187]
**Note 1:** this was noted while working in the consolidated media picker project but it seems not related to it since behaviour is the same also without that feature on.
**Note 2:** the following applies for http pure self-hosted sites; https case (like with jurassic ninja without setting up the JP) works as expected.

### Expected behavior
When setting a featured image from WP Media lib I expect the featured image to be set and appear in the post settings.

<p align=center>
<img src="https://user-images.githubusercontent.com/47797566/96643677-38f2fc00-1328-11eb-8d02-cedce058b83d.png" width=300/>
</p>

### Actual behavior
When setting a featured image from WP Media the featured image does not appear in the post settings.

<p align=center>
<img src="https://user-images.githubusercontent.com/47797566/96643960-a010b080-1328-11eb-89c6-3dabfe6c894c.png" width=300/>
</p>

### Steps to reproduce the behavior
- Create a new post
- Go to post settings and tap on set featured image
- Select an image from the WP Media Lib and notice it is not set in the post settings

**Comment by thehenrybyrd** [comment]
Given that we've had no further reports, and that SSL (https) usage is now between 80-95% worldwide, I'll close this issue.
