### ISSUE TITLE
Some posts have a featured image in the list, but not in the post detail

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#13239]
### Expected behavior
Featured image if set on the post should be present in the post detail.

### Actual behavior
Some posts having a featured image in the list do not show it in the post detail.

![featured-image](https://user-images.githubusercontent.com/1405144/97257792-f906aa00-183c-11eb-907a-41aaeedca182.gif)

### Steps to reproduce the behavior
See video

**More details**

https://github.com/wordpress-mobile/WordPress-Android/pull/12931#pullrequestreview-500724506
https://github.com/wordpress-mobile/WordPress-Android/pull/12931#pullrequestreview-504709956

Related PR #10611
It makes the reader not add a featured image if the image is already present in the post body.
Multiple checks were added in this PR based on Calypso logic. Need to recheck this logic.

**Comment by reginabally** [comment]
Another case reported in 3807063-zd-woothemes. I'm seeing the same behavior on WordPress.com Reader.

Link to the post without a featured image: https://wordpress.com/read/feeds/94930564/posts/3223494127

<img width="1277" alt="Markup 2021-03-10 at 09 48 29" src="https://user-images.githubusercontent.com/40906847/110563710-a93ed480-8186-11eb-900c-1d7ac2c64988.png">

Link to the post with a featured image: https://wordpress.com/read/feeds/94930564/posts/3218801612

<img width="1267" alt="Markup 2021-03-10 at 09 48 53" src="https://user-images.githubusercontent.com/40906847/110563722-b065e280-8186-11eb-9f4e-f459b333041e.png">
