### ISSUE TITLE
IllegalArgumentException org.wordpress.android.editor.gutenberg.GutenbergPropsBuilder in build

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13248]
Sentry Url: https://sentry.io/share/issue/c98a69d0e21641bf885f0910eeae2650/
User Count: 426
Count: 1.8K
First Release: org.wordpress.android@15.8-rc-1 (925)
First Seen: Sep 24, 2020 6:51:47 PM UTC
Last Seen: Oct 28, 2020 10:16:55 AM UTC
24 Hours: 29
30 Days: 1.8K
```
org.wordpress.android.editor.gutenberg.GutenbergPropsBuilder in build at line 2
org.wordpress.android.editor.gutenberg.GutenbergContainerFragment in updateCapabilities at line 215
org.wordpress.android.editor.gutenberg.GutenbergEditorFragment in updateCapabilities at line 696
org.wordpress.android.ui.posts.EditPostActivity in onSettingsUpdated at line 680
org.wordpress.android.ui.prefs.SiteSettingsInterface$4 in run at line 1155
...
(40 additional frame(s) were not displayed)
```

**Comment by emilylaguna** [comment]
The sentry url 404's for me so here's a correct one: https://sentry.io/share/issue/c98a69d0e21641bf885f0910eeae2650/

**Comment by emilylaguna** [comment]
Unable to reproduce this on my end, reached out to @marecar3 who mentioned this maybe similar to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2692 but since this is happening in 15.9.1 he's going to take another look. 

Thank you @marecar3!

**Comment by marecar3** [comment]
Thank you @emilylaguna! 👍
