### ISSUE TITLE
Post List: consider adding an option to copy the post URL

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13292]
We've received a request in beta tester feedback to have an option to copy the URL for a post:

> The app is utter waste without the option to copy the url of published post. Its completely useless.., there is share icon and copy option, but in some phones that copy option will not appear, so we need to share it to some person in whatsapp and copy it from there.

* 2-star beta tester feedback
* Oct 27, 2020, 06:39
* Device: LGE LG G7 ThinQ
* Device language: English
* App version code: 939
* App version name: 16.0-rc-2
* Android version (SDK): Android 10 (SDK 29)

<sup>(internal reference: play-store-reviewId=gp%3AAOqpTOGxPytP9Xd-OvKfM-hn5mtQsQmTYXVx9GJjKOoDScX0q-KYXQTJvyJ0t8loRo6ydmeQYe6e8Idp3_GGDGji&corpus=BETA_FEEDBACK)</sup>

**Comment by hypest** [comment]
> but in some phones that copy option will not appear

User might be referring to the "Copy" option some phones offer inside the OS's Share flow (external to the app), and the fact that some device vendors might not be offering that functionality.

**Comment by ovitrif** [comment]
@iamthomasbishop I noticed in the web version (calypso) we have an option to copy the link of a published post right above the trash option in the post actions menu:

<img width="824" alt="1_preview_web_version" src="https://user-images.githubusercontent.com/4588074/141437597-1be768de-f027-48b3-a512-7676ab67c46c.png">

When the user copies the link they also receive a notification saying: "Link copied to clipboard".

<img width="825" alt="2_preview_web_version_notification" src="https://user-images.githubusercontent.com/4588074/141445577-a0bcea1c-9cfe-477b-b0ad-6dc7923517d9.png">

Currently under the "More" menu in the android app we have:

<img width="256" alt="phone_before" src="https://user-images.githubusercontent.com/4588074/141448142-6997ed59-00e2-4f65-a10f-93f18d43a920.png">


### One proposal is to:
- [ ] Show a new option in the More menu, right above trash to ‘Copy link’ ONLY for published posts
- [ ] Show toast notification to the user in case of success or failure.

Your feedback is welcome!

**Comment by ovitrif** [comment]
Following the [feedback](https://github.com/wordpress-mobile/WordPress-Android/pull/15570#issuecomment-973111846) received in [the pull-request for addressing this issue](https://github.com/wordpress-mobile/WordPress-Android/pull/15570),
the following changes apply to the initial proposal:
- Show a snackbar notification (instead of the initially proposed toast)
- Show the option to copy the Post URL also for posts/pages that are in the Scheduled and Draft state.
