### ISSUE TITLE
General: optimize for smart watches

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13293]
We've received a request in beta tester feedback asking to optimize for a smart watch:

> Optimize for smartwatch wear OS

* 4-star beta tester feedback
* Oct 22, 2020, 11:41
* Device: Samsung Galaxy Tab S7+
* Device language: Italian
* App version code: unavailable
* App version name: unavailable
* Android version (SDK): Android 10 (SDK 29)

<sup>(internal reference: play-store-reviewId=gp%3AAOqpTOGunQyUuQC_a1h85eNsF8iyR49kM6R34EQKkgki027lDhFRJf2B5yQ6eQ3poY-v90HU840nbdMSwNLDCwJE&corpus=BETA_FEEDBACK)</sup>

**Comment by jkmassel** [comment]
This isn't a priority for us, and won't be in the foreseeable future.
