### ISSUE TITLE
Reader: Line/paragraph breaks not rendered properly for classic block

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13294]
The line/paragraph breaks in a classic block isn't rendered properly in the Reader on the Android version of the app. It works well on WordPress.com Reader as well as the Reader on the iOS version of the app.

### Expected behavior
I would expect the output of the post in the Reader is the same across all platforms/devices.

### Actual behavior
The text added on a classic block in the Reader on the Android version of the app is displayed without line/paragraph breaks.

**Screenshot taken on WPAndroid 16.1-rc-1**

![Screenshot_2020-11-05-08-58-04-29_1cdbe7dded7ec259ed1024b4ff1ae8db](https://user-images.githubusercontent.com/40906847/98185175-15929880-1f47-11eb-88c7-c6d62dda114a.jpg)

**Screenshot taken on WPiOS 15.9**

![IMG_F962C93DC634-1](https://user-images.githubusercontent.com/40906847/98185258-3955de80-1f47-11eb-9b14-7717d4e044ba.jpeg)

###Additional testing

I copied the content on the classic block to a test site and converted it to blocks, the post rendered okay in the Reader on WPAndroid.

![Screenshot_2020-11-05-09-02-59-55_1cdbe7dded7ec259ed1024b4ff1ae8db](https://user-images.githubusercontent.com/40906847/98185372-77eb9900-1f47-11eb-923b-ee3a768f6c0c.jpg)

##### Tested on OPPO Reno 4, Android 10, WPAndroid 16.1-rc-1

Originally reported in 3464049-zen with Motorola moto g power and WPAndroid 15.9.2

The link of the post can be found in the ticket.

**Comment by rossanafmenezes** [comment]
Another report here 3464940-zen

Asking user for more info on their device (it's a Blackberry according to the logs but  that's it)
App version: 16.0

They mentioned they are using the classic editor but I check and they are using the classic block.

**Comment by azollafox** [comment]
User above provided more details:

>It's BlackBerry Key2 with Android 8.1.0 (updated automatically). Thanks! 😃

**Comment by reginabally** [comment]
Another report in 3453540-zen on Sony F5121, WPAndroid 15.9.2.

<img src="https://user-images.githubusercontent.com/40906847/98341493-e284fd80-2049-11eb-9ff6-c2416f32ae87.png" width="270" alt="Screenshot_20201105-193103~2">

Link to the post can be found in the ticket.

**Comment by designsimply** [comment]
I was unable to reproduce the problem testing with my Pixel 3 Android 11 device using the following testing steps:

1. On the web, create and publish a post using a classic block that contains several paragraphs. 
1. Try copy/pasting content from elsewhere but also try typing in the entire post directly without using the paste function.
1. In the app, find the posts in the Reader.
1. Check to see whether paragraphs have breaks between them as expected.

<strong>Result:</strong> paragraph breaks appear with breaks between them as expected.

<img src="https://user-images.githubusercontent.com/1119271/98871817-ceb70e00-2432-11eb-8bc6-84ae01467cf6.png" height="350" alt="Screenshot_20201111-151201"> <img src="https://user-images.githubusercontent.com/1119271/98871830-d1b1fe80-2432-11eb-9175-3c7976d67695.png" height="350" alt="Screenshot_20201111-151440">

<sup>Tested with WPAndroid 16.1-rc-3 on Pixel 3 Android 11.</sup>

I tested the post from the original report above as well and that looked correct to me as well.

<img src="https://user-images.githubusercontent.com/1119271/98871856-daa2d000-2432-11eb-88c7-f2586c9eedc4.png" height="350" alt="Screenshot_20201111-152213">
<sup>Tested with WPAndroid 16.1-rc-3 on Pixel 3 Android 11.</sup>

I looped back and installed 16.1-rc-1 and tested again and everything still looks good to me 😕  and this made me 2nd guess that something isn't cached even though I uninstalled and reinstalled a new app via an apk file from GitHub. 🤔

<img src="https://user-images.githubusercontent.com/1119271/98871880-e393a180-2432-11eb-96f7-d414920415fa.png" height="350" alt="Screenshot_20201111-152650">
<sup>Tested with WPAndroid 16.1-rc-1 on Pixel 3 Android 11.</sup>

@reginabally any chance you could search for made4testing0318.blog in a Reader site search and view the latest posts and let me know if the paragraphs look normal to you on your OPPO Reno 4 Android 10 device? Also, could you find out what version of Android the person from 3453540-zen is using and update the related comment above to include that info?

**Comment by designsimply** [comment]
I tested with the 16.0.1 tag using a Nexus 5 Android 10 emulator and I am still able to see paragraphs render properly. I'm not sure what I'm missing in these testing steps (see steps noted in the previous comment) and may need to ask for some additional help/ideas for how to test this issue.

<img src="https://user-images.githubusercontent.com/1119271/98875820-3a50a980-243a-11eb-80a9-e07bf88e0b32.png" width="270" alt="Screenshot_1605136902"> <img src="https://user-images.githubusercontent.com/1119271/98875817-39b81300-243a-11eb-84e0-6e2c65d01d3a.png" width="270" alt="Screenshot_1605136998">
<sup>Tested with Nexus 5 Android 10 emulator running tag/16.0.1 `32cf7cb803` viewing the post from the original report (left) and a new post on the made4testing0318.blog site (right).</sup>

**Comment by reginabally** [comment]
I've tested with OPPO Reno 4, Android 10 on WPAndroid version 16.1-rc-2, the paragraphs render properly now. It works well on Huawei Nova 2i, Android 8 on WPAndroid version 16.0 too.

Since we're not able to replicate this, I'm closing this for now. Thank you so much, @designsimply!
