### ISSUE TITLE
Reader: Related posts feature missing in 16.0

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13302]
### Expected behavior
I would expect at the end of the post in the Reader on the app, I'm able to see the related posts section, which can be found in the earlier version of the app.

**Screenshot taken on WPAndroid 15.9.2**

<img src="https://user-images.githubusercontent.com/40906847/98331371-684b7d80-2037-11eb-93a0-94db578da482.jpg" width="270" alt="Screenshot_20201106-134617">

### Actual behavior
The related posts section in the Reader doesn't appear at the end of the post.

### Steps to reproduce the behavior

1. Tap Reader on the app
2. Select a post to read
3. Scroll down to the bottom of the post and noticing the related posts section is missing.

##### Tested on BlackBerry Key2, Android 8.1.0, WPAndroid 16.0 (3464940-zen)

Also tested on OPPO Reno 4, Android 10, WPAndroid 16.1-rc-1

**Comment by mbshakti** [comment]
Thanks for filing this issue @reginabally -- we actually removed this as part of the[ new Reader changes ](https://wordpress.com/blog/2020/09/23/discover-blogs-get-inspired-wordpress-reader/). However, I'd be curious to know if you encountered any users who mentioned this or if it was an observation of yours. If it's an observation of yours, was that section something you found value in? The questions will help us decide whether we should bring this back :)

**Comment by reginabally** [comment]
@mbshakti Thank you for the reply. The report was originated from the ticket 3464940-zen (it was mentioned at the device information above but maybe not too obvious).

I use Reader mainly to read internal P2s but as a user, I think it helps us in discovering posts that are related to the content that we're currently reading, without having to navigate away from the current screen. I hope that makes sense.

**Comment by ashiagr** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/issues/14128.
