### ISSUE TITLE
Media: Newly uploaded media fails to play just after upload on certain sites

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#13314]
### Expected behavior
Newly uploaded media should play properly just after upload from the media section under "My Site". 

### Actual behavior
Newly uploaded media fails to play for certain kind of sites (tested on a wordpress.com site with business plan and public privacy settings) if played immediately after upload. App displays "unable to load media" error.

It plays fine on a simple site with a free plan.

More details: https://github.com/wordpress-mobile/WordPress-Android/pull/12976#issuecomment-723031873

### Steps to reproduce the behavior
See video: https://cldup.com/CBxy880m-N.mp4

**Comment by designsimply** [comment]
This came up in a mobile request and I am adding a quick note here for reference.

> When a video is first uploaded from device, while the video is still processing, a temporary URL is created like https://example.wpcomstaging.com/example-file-name-mp4. This URL does not end with .mp4 extension. This url is using the GUID and redirects to the actual one when loaded in a browser. However, the Android app cannot load a video with GUID when user tries to load it immediately after upload.

<sup>(internal reference: p4a5px-2Ma-p2#comment-12357)</sup>

In that report, they were using a self-hosted jetpack-connected free site. They had also subscribed to a personal plan once and then unsubscribed.

**Comment by ravishanker** [comment]
A related [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3292) that has plausible [reasons](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3292#issuecomment-846012015) why this could be happening.

**Comment by ravishanker** [comment]
This seems to be no longer an issue.  It is playing video fine soon after upload as well.
