### ISSUE TITLE
Featured image missing after editing a post

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#1334]
* Create a new post, give it a title but no content
* Insert a picture and set it as the featured image
* Publish the post
* Edit it in the app 

The featured image doesn't appear anywhere in the post editor.

**Comment by maxme** [comment]
I'm removing the milestone (fix will come with the new editor).

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
