### ISSUE TITLE
Publishing empty post result in undismissable progress dialog and unresponsive app

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#13379]
##### Steps to reproduce the behavior
- Create a new empty post.
- Tap PUBLISH in the toolbar.
- Notice the "Saving" progress dialog and that "Can't publish empty post Toast appears for a moment"
- Confirm that dialog is not disappearing and can't be dismissed.

Might not be clear from GIF - but the progress dialog is never dismissed by itself.
[![Image from Gyazo](https://i.gyazo.com/ffc0ae6ed7f20f29455eede2b80eceed.gif)](https://gyazo.com/ffc0ae6ed7f20f29455eede2b80eceed)

**Comment by hypest** [comment]
Wondering if this related to recent work on the save-on-exit. @mchowning , @malinajirka can you please have a look? Thanks!

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13381
