### ISSUE TITLE
Loading indicator in pick from WP Media lib does not disappear when 1 match in search

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#13370]
### Expected behavior
When picking from the WP Media lib and using the search feature, I expect the bottom loading indicator to disappear after matching images are loaded.

### Actual behavior
When picking from the WP Media lib and using the search feature, the bottom loading indicator does not disappear after matching images are loaded, when only 1 image matches.

### Steps to reproduce the behavior
- In GB place an Image block
- Add image from WP Media Library
- Be sure to have only one image matching the search (for example I have only 1 image matching the `cat` search here below

<p align=center>
<img src=https://user-images.githubusercontent.com/47797566/98931530-72a9c380-24de-11eb-9b64-c0466ee6582b.png width=300/>
<p>
- Notice the bottom loading indicator does not disappear after the 1 matching image is loaded

**Comment by irfano** [comment]
Hey @develric, me and @notandyvee can't reproduce this issue. It is a 3-year-old issue, and it may have already been fixed. Could you test if you can still reproduce this? If not, we can close this issue.

**Comment by develric** [comment]
Hey @irfano 👋 , I was not able to reproduce it as well (on Pixel 4 emu API29 nor on S23 device with API34), seems fair to close this one and I'm doing it now 👍
