### ISSUE TITLE
unable to remove spam from comments listing

### ISSUE THREAD

**Issue by michield** [wordpress-mobile/WordPress-Android#1341]
using Wordpress for Android v2.8 on a Galaxy S4.
Self-hosted Wordpress

In my listing of comments on my site, there are some 20 spam comments, listed as "Pending". However, trying to remove them fails, and I will explain why.

I had them listed in the app, but then went to the blog with my browser and removed them in Wordpress instead. Ever since, I cannot remove them from the app. When I try to either mark them spam or trash them, I get "an error occurred while moderating" and the comment is not removed from the listing. The log shows that there is an error 404 on the request.

**Comment by fadils** [comment]
Related to this, on my comment list.. I cannot edit a comment from "SPAM" to "NOT SPAM".
That is, if I tap a comment with "SPAM" label, then tap "NOT SPAM" then I got the following error:
```
04-24 16:50:35.549   32278-5728/org.wordpress.android W/WordPress-API﹕ Response document received from the server: <?xml version="1.0" encoding="UTF-8"?>
    <methodResponse>
    <fault>
    <value>
    <struct>
    <member>
    <name>faultCode</name>
    <value><int>500</int></value>
    </member>
    <member>
    <name>faultString</name>
    <value><string>Sorry, the comment could not be edited. Something wrong happened.</string></value>
    </member>
    </struct>
    </value>
    </fault>
    </methodResponse>
04-24 16:50:35.549   32278-5728/org.wordpress.android E/WordPress-COMMENTS﹕ Error while editing comment
    org.xmlrpc.android.XMLRPCFault: Sorry, the comment could not be edited. Something wrong happened. [Code: 500]
            at org.xmlrpc.android.XMLRPCClient.parseXMLRPCResponse(XMLRPCClient.java:316)
            at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:497)
            at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:412)
            at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:229)
            at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:213)
            at org.wordpress.android.ui.comments.CommentActions$11.run(CommentActions.java:377)
```

**Comment by rachelmcr** [comment]
I tested this again in 4.8-rc-3 and reproduced the issue.

After spamming a comment from the web admin, when I tried to moderate it in the app it looked like the action worked. (I got a confirmation message at the bottom of the screen.) However, after refreshing the comments the spammed comment reappeared with the message "an error occurred while moderating."

**Comment by hypest** [comment]
I tested the iOS app as well (against a self-hosted site) and it behaves the same as the Android app. That is, the comment appears again on the list, although no error message is displayed in the iOS case.
