### ISSUE TITLE
Site creation preview shows cut-off site header

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#13410]
### Expected behavior

The preview of a newly created site shouldn't have cut-off sections.

### Actual behavior

After creating a site in the app, the site preview is shown but the top of the site is cut-off.

| <img src="https://user-images.githubusercontent.com/1898325/99396333-621f9180-28c0-11eb-8073-78d89338c179.jpg" alt="Screenshot showing cut-off site preview" width="350"> |
| - |

### Steps to reproduce the behavior

1. Start the "Create WordPress.com site" wizard (either after the creation of a new WP.com account or from the site list when logged in)
2. Create a Blank Site (although this issue might be present for other types of sites)
3. On the "Your site has been created!" screen, notice that the top of the preview is cut-off

### Additional info

This issue is also present on WPiOS https://github.com/wordpress-mobile/WordPress-iOS/issues/15313

**Comment by designsimply** [comment]
Not directly related, but the [subdomain is not readable in dark mode on the site creation preview screen](https://github.com/wordpress-mobile/WordPress-Android/issues/12829) and it would be cool for anyone working on this issue to see if that one can be fixed at the same time.

**Comment by designsimply** [comment]
Noting that the "Create your website" banner showing in this view isn't expected during site creation and @enejb has submitted a PR on the WP.com side to fix it.

<sup>(internal reference: D53196-code, pbMoDN-1A9-p2#comment-3222)</sup>

**Comment by antonis** [comment]
This seems to be resolved now

<img width="360" src="https://user-images.githubusercontent.com/304044/100094706-180b5280-2e62-11eb-96a5-30e9d17b25bf.png"/>

**Comment by guarani** [comment]
Hi @antonis, I'm still seeing the "Create your website" banner in Play Store WPAndroid v16.1 when creating a new site, and the internal patch for WP.com side mentioned in https://github.com/wordpress-mobile/WordPress-Android/issues/13410#issuecomment-732507376 is still open. Which version did you see this resolved in?

| <img src="https://user-images.githubusercontent.com/1898325/100099246-f009f800-2e3d-11eb-8bef-653307d2c45e.jpg" alt="Screenshot showing the 'Create your website' banner" width="350"> |
| - |

If this is resolved, we should be able to close https://github.com/wordpress-mobile/WordPress-iOS/issues/15313 as well.

**Comment by antonis** [comment]
Hello @guarani 👋 
This is solved on the client by adding the wordpress user-agent in the preview webview. This was done as a minor fix on the clients as part of:
* Android: https://github.com/wordpress-mobile/WordPress-Android/pull/13409
* iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15303

This should be merged soon and be available in `16.3`
Reopening the issue till this is done.

**Comment by guarani** [comment]
Hi @antonis 👋 I hadn't realized this was being fixed in the apps themselves, thanks for clarifying!

I'm curious if that means that the fix @enejb is doing (mentioned in https://github.com/wordpress-mobile/WordPress-Android/issues/13410#issuecomment-732507376) is addressing a different issue, or if it's no longer needed.

**Comment by antonis** [comment]
@guarani My understanding is that a fix was needed in both the server and the clients for this to work. I'll leave this open and recheck.

**Comment by guarani** [comment]
> @guarani My understanding is that a fix was needed in both the server and the clients for this to work. I'll leave this open and recheck.

I see, thanks again @antonis!

**Comment by enejb** [comment]
We just shipped a PR that addresses this issue from the backend. @antonis and @chipsnyder As I understand it was addressed on the client side as well. 

I am closing this issue for now but feel free to open it again in case. I misunderstood and there is more work to be done.
