### ISSUE TITLE
Add support for invite links to P2 sites

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#13456]
We should add support for invite links to P2 sites. This will include a feature for generating (and disabling) invite links with specific privileges.

I'm not yet sure if we should add the functionality to open P2 links in the app.

This might also include a refactor of the People Management screen, since it's pretty old.

**Comment by designsimply** [comment]
I would **love** to be able to accept invitations through the app instead of by email—I'm not sure if this is on the table as an option or in scope for this issue and would like to add that this is a personal note from me as a user 🙂

**Comment by develric** [comment]
Adding designs for Android.

![image](https://user-images.githubusercontent.com/47797566/106901453-1084e700-66f8-11eb-987e-4b7eee5e44fb.png)

**Comment by develric** [comment]
>I would love to be able to accept invitations through the app instead of by email—I'm not sure if this is on the table as an option or in scope for this issue and would like to add that this is a personal note from me as a user 🙂

Hi @designsimply , in my understanding is not currently covered and not sure what it could require tbh 🤔 . Maybe you could place a comment about it on our team project backlog (pctCYC-3s-p2)? I think it sounds like an interesting scenario to consider 👍  (cc @aerych)
