### ISSUE TITLE
JSApplicationIllegalArgumentException: Error while updating property 'textAlign' in shadow node of type: RCTAztecView

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13462]
**Sentry Url**: https://sentry.io/share/issue/047910f7e0d54079a42e4fde6944db32/
**User Count**: 153
**Count**: 176
**First Release**: org.wordpress.android@16.0-rc-1+936
**First Seen**: 2020-10-20T09:05:59.596000Z
**Last Seen**: 2020-11-24T08:14:47Z
**24 Hours**: 33
**30 Days**: 174

```
JSApplicationIllegalArgumentException: Error while updating property 'textAlign' in shadow node of type: RCTAztecView

...
(8 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment]
@marecar3 do you have any idea which block might be causing this issue? (pinging you here because I've seen that you already fixed a [similar error](https://github.com/wordpress-mobile/WordPress-Android/issues/12211) before).

**Comment by hypest** [comment]
@marecar3 is focusing on some other projects as we speak so, let me reel in @cameronvoell to have a look at this one.

For context, the nested exception has some additional clues, possibly related to an attempt to set textAlign to `full`:

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Invalid textAlign: full
    at com.facebook.react.views.text.ReactBaseTextShadowNode.setTextAlign(ReactBaseTextShadowNode.java:451)
    at java.lang.reflect.Method.invoke(Method.java)
	...
```

**Comment by designsimply** [comment]
**Events in the last 90d:** 594
**Users affected in the last 90d:** 473
<sub>WORDPRESS-ANDROID-VD3: https://sentry.io/share/issue/047910f7e0d54079a42e4fde6944db32/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1968116529&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105527633-32ff1500-5ca1-11eb-8d4a-f4c8e8cb4c6a.png)</a>

I couldn't find any new cases for this crash reported in Sentry for versions 16.2+. Recommend closing.
