### ISSUE TITLE
Site Creation - Preview shows as blank screen for buisness.blog subdomains

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-Android#13468]
`.buisness.blog` subdomains render as a blank screen in preview.

### Steps to reproduce the behavior
1. Navigate to site creation flow
1. Select a design that that allows `.blog` subdomains like `Cassel`
1. On the Choose a Domain screen search for and select a domain that includes `buisness.blog`
1. Create your site:

Screenshot | GIF
--- | ---
<kdb><a href="https://user-images.githubusercontent.com/3384451/100100484-e2994180-2e2e-11eb-80d5-ee86759b3c54.jpg"><img width="300" src="https://user-images.githubusercontent.com/3384451/100100484-e2994180-2e2e-11eb-80d5-ee86759b3c54.jpg"/></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/100100516-f2188a80-2e2e-11eb-87e5-5153909d6e65.gif"><img width="300" src="https://user-images.githubusercontent.com/3384451/100100516-f2188a80-2e2e-11eb-87e5-5153909d6e65.gif"/></a></kdb> 

📓 I walked through these steps on iOS as well. On iOS I picked `chipcup.buisness.blog` and that loaded as `chipcupbusiness.wordpress.com` navigating to https://chipcupbusiness.wordpress.com in a browser will redirect to https://chipcup.business.blog

<details>
<summary>iOS screenshot</summary>

<kdb><a href="https://user-images.githubusercontent.com/3384451/100100298-9b12b580-2e2e-11eb-9e91-d890309bc9f2.jpeg"><img width="300" src="https://user-images.githubusercontent.com/3384451/100100298-9b12b580-2e2e-11eb-9e91-d890309bc9f2.jpeg"/></a></kdb>

</details>

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13472
