### ISSUE TITLE
Comments: the "No comments yet" text is a bit lost at the bottom of the screen

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13536]
Steps to reproduce:

1. Go to Reader.
1. Tap the comment icon for any post with comments enabled but doesn't have any comments yet.
1. Observe that the "No comments yet" text is a bit lost at the bottom of the screen and no padding below the text makes the spacing of it awkward.

<img src="https://user-images.githubusercontent.com/1119271/101105685-68ce2a00-358b-11eb-858e-09ccdffe17c0.png" width="270" alt="Screenshot_20201201-154711">

<sup>Tested with WPAndroid 16.3-rc-2 on Pixel 3 Android 11.</sup>

**Comment by KirillPovarintsev** [comment]
Is it better like this? Can I take care of the issue then?

![Screenshot_1630035708](https://user-images.githubusercontent.com/688018/131068460-75034f87-4c79-4ec6-87f6-5a9acaa82433.png)

**Comment by chandradeepkumar16** [comment]
I am trying to fix the bug but the code changes are not being reflected in my emulator. Why? 
I have followed the Readme file and successfully logged in with WordPress account.

**Comment by danmaze** [comment]
Here's what I have:

![image](https://user-images.githubusercontent.com/50293775/131404835-f823c570-4e12-42cb-ab13-41044973fedb.png)

I can't push the fix branch to create a pull request. It looks like I need some additional permissions.

**Comment by KirillPovarintsev** [comment]
I thought I was the first one to grab it guys :)

**Comment by danmaze** [comment]
No one has been assigned yet. Since you first indicated interest, you're probably going to get this one. :)

**Comment by KirillPovarintsev** [comment]
Trying to obtain write permissions for the repo...

**Comment by ashiagr** [comment]
👋 @KirillPovarintsev 

I've assigned this issue to you. 

> Trying to obtain write permissions for the repo...

You cannot directly merge changes to the main repo. Can you fork the repo and submit a PR? Let me know if you come across any issues.
