### ISSUE TITLE
Media Picker: replicate behavior of making a local copy for remote media for Stories

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#13549]
After the implementation of this PR  https://github.com/wordpress-mobile/WordPress-Android/pull/13548, we changed the behavior for the media picker for Stories when the user selects a media item which belongs to the site's Media section. Given these items are represented with remote URLs (i.e. `https://`) we need to first download a local copy in order for things to behave properly and smoothly in the Story composer while the user makes edits to their slides.

This behavior should be replicated in the new consolidated  Media Picker once we move Stories to use the new media picker as well.

cc @aforcier

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
