### ISSUE TITLE
[Home Page Picker] - screen is greyed out when rotated

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#13559]
### Expected behavior
The color of the screen should remain the same when rotating.

### Actual behavior
Rotating the phone shows a greyed overlay on the screen:
#### **Dark mode:**
![gray_colored_screen](https://user-images.githubusercontent.com/6597771/101397811-f1123f00-38ab-11eb-88d7-2f9b8a004de7.gif)

#### **Light mode:**
![gray_colored_screen_light_mode](https://user-images.githubusercontent.com/6597771/101397977-2dde3600-38ac-11eb-946b-142963c2ac25.gif)

### Steps to reproduce the behavior
1. open the WPAndroid app, and go to the site picker
2. tap on + 
3. select "WordPress.com site"
4. the Design selection screen appears.
6. rotate the screen and observe it now has a greyed overlay

**Comment by mzorz** [comment]
Note: I also tested this on an actual Pixel 2 device with Android 8.1, and couldn't observe the behavior there.

**Comment by designsimply** [comment]
fwiw, I've seen this before in the emulator but not on my actual device when using WPAndroid.

I just tested on my Pixel 3 Android 11 devcie using WPAndroid 16.3-rc-2 and 16.3-rc-3 and I'm unable to replicate so I'm labeling low priority for now as it appears to be emulator-only in testing so far.

![WordPress-Android-13559-WPAndroid-16 3-rc-3](https://user-images.githubusercontent.com/1119271/101423515-8286ae80-38b6-11eb-9f1a-470fa7f8b22b.gif)

**Comment by antonis** [comment]
I performed a preliminary investigation but wasn't able to replicate the issue on an actual device or find the cause of this behaviour. Leaving this issue for groundskeeping.

**Comment by mzorz** [comment]
Thank you for taking the time to test a bit on a device @antonis! Might be just an emulator glitch, I think if it's not happening on devices we can close it - I have tested on an actual device with Android 8.1 and couldn't observe it either - wdyt @designsimply @antonis  ?

**Comment by antonis** [comment]
@mzorz I agree. I feel that it would be safe to close this (and probably reopen if the problem appears on an actual device).
I was hesitant to close it directly because I'm only able to test on one actual device (Pixel 2XL/Android 11) at this point.

**Comment by mzorz** [comment]
Sounds good, no need to keep this open if it's not really affecting users. Closing then! 👍 thanks a ton for your time @antonis @designsimply  🙇
