### ISSUE TITLE
[Home Page Picker] - title and action bar default action overlap in German

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#13558]
### Expected behavior
The labels should not overlap

### Actual behavior
The "skip" translation for German is "überspringen" and it occupies much more space, overlapping with the title when it's collapsed as you scroll down

![overlap](https://user-images.githubusercontent.com/6597771/101393682-3a5f9000-38a6-11eb-930f-b6df0468f121.gif)

### Steps to reproduce the behavior
1. set your device language to German (Deutsch)
2. open the WPAndroid app, and go to the site picker
3. tap on + 
4. select "WordPress.com-site erstellen"
5. the Design selection screen appears.
6. Scroll down to observe the behavior described above.

**Comment by mzorz** [comment]
Note: I also tested this on an actual Pixel 2 device with Android 8.1, and couldn't observe the behavior there.

**Comment by designsimply** [comment]
Thanks for the report @mzorz! I tested with WPAndroid 16.3-rc-3 on Pixel 3 Android 11 with a few different languages and I see what you mean.

Spanish|Hebrew|Russian
---|---|---
![Screenshot_20201207-181216](https://user-images.githubusercontent.com/1119271/101424303-15741880-38b8-11eb-9125-2a22be7bcf95.png)|![Screenshot_20201207-181242](https://user-images.githubusercontent.com/1119271/101424295-11e09180-38b8-11eb-9b68-4468d68f0816.png)|![Screenshot_20201207-181140](https://user-images.githubusercontent.com/1119271/101424305-16a54580-38b8-11eb-817c-848811fc356c.png)
