### ISSUE TITLE
Reader: Track Cards API response

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-Android#13609]
### Goal

The goal is to track when the Reader Cards API response has arrived. We want to make a funnel to check how many users are leaving the Reader _before_ the response returns.

In WPiOS [this was implemented](https://github.com/wordpress-mobile/WordPress-iOS/pull/15183) by triggering an event when the cards appear: `reader_discover_content_presented`.

#### Appearing

1. Open Discover
2. Wait for the cards to appear
3. Check that `reader_discover_content_presented` is fired

#### Leaving the screen before it appears

1. Open Discover
2. Immediately switch to other section (like Following)
3. Check that `reader_discover_content_presented` is *not* fired

**Comment by leandroalonso** [comment]
@ParaskP7 can you please tackle this issue?

I'm available to help with anything you need. :)

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

Sure, will tackle it as soon as possible!

Since this is the first time I hear about that, how urgent is it? 😊

**Comment by leandroalonso** [comment]
Given the discussion in the PR above we're closing this issue.
