### ISSUE TITLE
Unable to switch to static page at My Site > Settings > Homepage Settings for sites with privacy setting set to Hidden

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13611]
Originally reported in 3573089-zen.

### Expected behavior
I would expect to be able to change my homepage settings to use a static page through My Site > Settings > Homepage Settings.

### Actual behavior
There's a loading wheel on the Homepage Settings pop-up. When I chose the "Static Homepage" option and tap the "ACCEPT" button, I see the error "Cannot save homepage settings before pages are loaded".

I have performed testing on several test sites (including AT sites and Jetpack sites), It looks like the issue happens on a site's privacy setting that is set to Hidden.

But if I toggled the privacy setting to Public or Private, and back to Hidden. I'm able to load the additional options for the Static Homepage setting.

### Steps to reproduce the behavior

0. Choose a WordPress.com site that has the privacy setting set to Hidden before you perform the following steps.
1. Go to My Site > Settings > Homepage Settings.
2. Tap Static Homepage and see that the additional options for the Static Homepage setting are loading.
3. Tap ACCEPT and see the error "Cannot save homepage settings before pages are loaded".
4. Change the site's privacy setting to Public or Private.
5. Go back to the Homepage Settings and see the additional options for the Static Homepage are available now.
6. Switch the site's privacy setting back to Hidden.
7. The additional options for the Static Homepage are available.

Screen recording: https://d.pr/v/invmHR/gHubLN12yS

##### Tested on OPPO Reno 4, Android 10, WPAndroid 16.3-rc-2

Originally reported on Xiaomi Redmi 8A, WPAndroid 16.2

**Comment by thehenrybyrd** [comment]
Tried to reproduce on Samsung Galaxy S21, WP Android 20.4-rc-2, and was unable to. I used a WordPress.com Simple site which was set to "Hidden", and in Settings > Homepage Settings I was able to tap "Static Homepage" and see the options to set my homepage and posts page.

I'll close this issue for now, but please reopen if you find a way to reproduce or get more reports.
