### ISSUE TITLE
Stats: update GeoChart to resolve map border issues

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#13637]
A user reported that the borders for Morrocco in the stats map were not up to date and were missing content of the Sahara. They mentioned that Google had updated their maps to reflect this which seems to be the case on Google Maps.
On looking at the [GeoChart map](https://developers.google.com/chart/interactive/docs/gallery/geochart#Example) which the app uses, it doesn't look like the difference is showing there. 

On checking, @frosty noticed that the app doesn't use the most recent version of GeoChart, so it may be worth looking if it can be updated or not for cases where Google made some updates which the app isn't reflecting.

Internal discussion: p1608298268293900-slack-C011BKNU1

**Comment by rossanafmenezes** [comment]
Another report in the app reviews about the map of India:

`The map of india shown in your app is wrong... 👊 Thinking to uninstall you and switch to some another blog app.`

User: R Ranade
Feb 1, 2021, 22:10
Device: Xiaomi Redmi 5 Plus
Device language: English
App version code: 982
App version name: 16.5
Android version (SDK): Android 8.1 (SDK 27)
