### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.notificatio...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13643]
**Sentry Url**: https://sentry.io/share/issue/d8e5aceeedd24cbc981d1f00fe10f704/
**User Count**: 45
**Count**: 69
**First Release**: org.wordpress.android@16.3-rc-1+962
**First Seen**: 2020-12-02T12:38:18.780000Z
**Last Seen**: 2020-12-21T07:20:50Z
**24 Hours**: 9
**30 Days**: 69

```
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.notifications.NotificationsDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean org.wordpress.android.models.Note.isCommentType()' on a null object reference
     at org.wordpress.android.ui.notifications.NotificationsDetailActivity.trackCommentNote(NotificationsDetailActivity.java:249)
     at org.wordpress.android.ui.notifications.NotificationsDetailActivity.onCreate(NotificationsDetailActivity.java:153)
...
(7 additional frame(s) were not displayed)
```

**Comment by ashiagr** [comment]
@loremattei, I can take a look into it tomorrow. Seems like devs working on this part are on 🎄 leave.

**Comment by ashiagr** [comment]
@loremattei , this one is fixed in the linked PR. Even though user count is small right now, this issue was introduced in the last release `16.3-rc-1+962`. I can create a PR against `release/16.4` instead of `develop`. Let me know.

**Comment by ashiagr** [comment]
Closing as fixed.
