### ISSUE TITLE
Facebook connection confirmation screen layout issue

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13718]
It was originally reported in 36219290-zen that the user wasn't able to connect their Facebook account to their site on the WPAndroid app because they weren't able to see the content of the page to select the Facebook page to connect.

I was able to see a similar issue on the confirmation screen when I was asked to connect Facebook to my test site. This happens on WPAndroid but not on WPiOS.

### Expected behavior

I would expect the Facebook connection confirmation screen is visible on the screen.

### Actual behavior

The user was seeing a footer of the confirmation screen that blocks the content of the Facebook page selection screen.

![Annotation on 2021-01-07 at 14-51-57](https://user-images.githubusercontent.com/40906847/103861347-41bdc780-50f8-11eb-8db3-c06477b334e0.png)

They're also seeing a similar layout issue on the access permission screen.

![Annotation on 2021-01-07 at 15-00-01](https://user-images.githubusercontent.com/40906847/103862015-420a9280-50f9-11eb-81ac-a3d7a43fd360.png)

### Steps to reproduce the behavior

1. Go to My Site > Sharing > Facebook and tap on CONNECT
2. Log in to Facebook
3. Confirm to connect Facebook account to the WordPress site. (I'm seeing a layout issue here when I was performing the test)
4. See that the footer of the page covers the content of the Facebook page selection screen.
5. On the access permission page, see that the footer of the page is also covering the content of the screen.

A screen recording of my testing can be found on the ticket. I'm not attaching the video here for privacy concerns.

**Comment by thehenrybyrd** [comment]
I'm unable to reproduce on Samsung Galaxy S21, Android 12, WP Android 20.3-rc-2. 
The entire login process is now done in the web browser, and no footer blocks page selection or permissions.
Closing for now, feel free to reopen if there are further reports or you're able to reproduce on a different device.
