### ISSUE TITLE
Reader: track topic followed in Discover section

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-Android#13763]
### Expected behavior

1. Given the user followed a topic/interest in the Discover section
2. Track the topic/interest that was followed

### Additional information

As for now, we have the `reader_reader_tag_followed` being fired. However, it is fired from multiple places, so there's no easy way to check if it came up from the Discover section.

We can either:

* Add a property `source` in `reader_reader_tag_followed`
* Create a new event and fire it only in Discover

**Comment by leandroalonso** [comment]
@malinajirka can I have your inputs about this one? What do you think would be a better solution:

1) Adding a `source` property
2) Or creating a new event?

If it's (2) I was wondering about `discover_followed_topic` with a "topic: name" property. Thoughts?

**Comment by malinajirka** [comment]
I lean towards `1` as it's still exactly the same event, the only difference is the place we fire it from. One more difference is that we use "topic" instead of "tag" on discover, but that's a user facing difference and imho shouldn't affect our internal naming.

> Given the user followed a topic/interest in the Discover section

Is this referring to the "Choose interests" screen? AFAIK you can't follow a tag directly from the discover screen right? Or should we track this event even when the user opens "tag/topic" detail and clicks on the follow button?

**Comment by leandroalonso** [comment]
> Is this referring to the "Choose interests" screen?

Yes, exactly!

I guess to keep simplicity we can keep `reader_reader_tag_followed` and add a `source` property.

* If in Discover: `source=discover`
* If not, `source=unknown`

**Comment by malinajirka** [comment]
@leandroalonso ~One more question - the existing event always tracks a single "tag". However, we support adding multiple tags in the Choose Interest screen. Should we add them in a list or fire multiple events?~

Update: Sorry, I didn't give this enough thoughts. We already track this event (we fire an event per tag). Goal of this task is to just add the "source" property.

**Comment by leandroalonso** [comment]
@ParaskP7 JFYI, in iOS I targeted the `16.5` release branch.

The change was simple and it's something that we wanted to have ASAP. Do you think it's possible to do the same for Android?

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

We discussed it with @malinajirka yesterday and agreed I'll start work on it tomorrow morning so that it ends up in `16.5` release.

I haven't look at it in more detail, but as far as I understood the change is simple on Android as well.

**Comment by malinajirka** [comment]
Actually, we discussed we'd merge it by Friday into 16.6. However, I guess we can merge it into 16.5 if Platform team is fine with that.

**Comment by ParaskP7** [comment]
Oh, you are right, for some reason I thought I  was talking about `16.6`, aka the release to be, not the one already cut. I'll focus on it tomorrow and let the platform team know as soon as I get the PR ready, maybe they will be fine with it.

PS: Thanks for catching on it @malinajirka . @leandroalonso if I were aware of that I would have started with this issue sooner.

**Comment by leandroalonso** [comment]
@ParaskP7 no worries! I should have added this info in the ticket, my bad.

**Comment by ParaskP7** [comment]
This is now done: #13823

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

Maybe you want to close this [iOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/15636) as well.
