### ISSUE TITLE
'Manage Your Stats' card link text cut off vertically on with Large or Largest device font

### ISSUE THREAD

**Issue by melek** [wordpress-mobile/WordPress-Android#13791]
### Expected behavior
The call-to-action/link text on dismissable cards should look natural and intentional regardless my device text size.

### Actual behavior
With 'large' device font set, The `DISMISS` and `TRY IT NOW` are cut off vertically, resulting in a glitchy look. It is most visible on the D, S, and O characters.

Similar to #11839.

<img src="https://user-images.githubusercontent.com/220149/104783987-211af080-573c-11eb-84a7-4cf5cbb2ecc8.png" alt="Screenshot of cut off link text" width="300">

### Steps to reproduce the behavior
1. Open the app. In my app, it shows a page for my primary site.
2. Click 'Stats'.
3. See error. (If you've previously dismissed the card, I do not know how to retrieve it.)

**Comment by designsimply** [comment]
Thank you for the report @melek! 

I will add this to our maintenance list but with a note that other issues may take precedence if they are more urgent. 👍

**Comment by AliAkberAakash** [comment]
Can I be assigned to this issue?

**Comment by khaykov** [comment]
Hey @AliAkberAakash 👋 Sure thing, and thank you! Please check out the [build instructions ](https://github.com/wordpress-mobile/WordPress-Android#build-instructions) and [contribution guidelines](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md) to get started. 

For this issues, you probably will be looking for [stats_block_dialog_buttons_item.xml](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/stats_block_dialog_buttons_item.xml). Let us know if you have any questions :)
