### ISSUE TITLE
Missing overflow menu in reader post cards when filter is active.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#13821]
While reviewing a not related PR [here](https://github.com/wordpress-mobile/WordPress-Android/pull/13766#pullrequestreview-568758343) it was noted the following.

### Expected behavior
When in the reader in a filterable tab like Following, if I select a filter, I would expect the posts shown to have the overflow menu like the posts card when no filter is selected like in the image below

<p align=center><image src="https://user-images.githubusercontent.com/47797566/105112447-579d9600-5ac3-11eb-8478-75c0d495a9ad.png" width=300/></p>

### Actual behavior
When in the reader in a filterable tab like Following, if I select a filter, the posts shown do not have the overflow menu

<p align=center><image src="https://user-images.githubusercontent.com/47797566/105112429-494f7a00-5ac3-11eb-9a3a-b54cad68f718.png" width=300/></p>

### Steps to reproduce the behavior
In the reader:
- go in a filterable tab like Following
- select a filter 
- notice the post cards presented do not have the overflow menu

##### Tested on [Pixel 3 Emu], Android [API 29], WPAndroid [current develop alpha-267]

NOTE: iOS seems ok already.

**Comment by khaykov** [comment]
Fixed in #13836
