### ISSUE TITLE
Modify Quick Start Steps to support quick start steps

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-Android#13832]
## Description

To more align with our changes to site creation we'd like to modify the quick start steps so that users can get to editing the content of those pages as soon as possible. 

## Changes
1. Fully remove "Browse Themes"
2. Add "Edit your homepage"
2. Add "Review site pages"

<kbd><a href="https://user-images.githubusercontent.com/3384451/105220335-8fd5c080-5b25-11eb-9b9c-234f594b7f60.png"><img width="300" src="https://user-images.githubusercontent.com/3384451/105220335-8fd5c080-5b25-11eb-9b9c-234f594b7f60.png"/></a></kbd> 

## Additional Info
We removed the steps to "Customize your site" and "Create a new page" in https://github.com/wordpress-mobile/WordPress-Android/pull/13756. Since we determined not to modify those we can fully clean up their usage.

**Comment by JavonDavis** [comment]
Hey! Bumping this to `16.7`, if you'd like to get it in for this release please merge this into release/16.7 and then DM me to release a new Beta version.

**Comment by chipsnyder** [comment]
Thanks @JavonDavis this actually merged but didn't auto close. Closing now
