### ISSUE TITLE
ZenDesk Push Notifications don't work 

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-Android#13861]
### Steps to reproduce the behavior
- Submit a support ticket
- Respond to it from within ZenDesk
- You should receive a push notification from ZenDesk saying that your message was responded to, but that's not working

I suspect the issue is related to the fact that the Push Token changes over time, and we may not be updating the token with the ZenDesk SDK properly.  Viewing web hooks coming back to WP.com from ZenDesk, there are nearly none that contain an Android push token.

**Comment by zwarm** [comment]
@jkmassel 
A bit of testing 
Steps
- Install  app
- Note that token gets registered successfully 
- Submit a support ticket
- Prompted to create identity
- Push app to background
- Reply in zendesk 
- There is no error logged in IRC #wpcom-pushnotifications-errors channel and no push notification is received on device

- Bring app to foreground 
- Submit a support ticket 
- Reply in zendesk 
- Error is logged in IRC #wpcom-pushnotifications-errors channel and push notification is received on device

It almost feels like there is a lag on the zendesk side. They respond that the token is registered, but some internal task hasn't completed yet. Every request I make after the initial one I receive.

**Comment by zwarm** [comment]
Update @jkmassel 

- This issue I describe above is fixed by upgrading to Release 5.0.2 of the Zendesk Support API. See the [zendesk release log](https://developer.zendesk.com/embeddables/docs/android-support-sdk/release_notes).

I have tested the update and I now receive push notifications for the first ticket, and continue to receive notifications for subsequent tickets.

**Comment by designsimply** [comment]
Re-tested (to double check) using 16.9-rc-1 and found that I was able to receive a push notification for a reply to a help request made with the app.

Closing as fixed. Props @zwarm. 🎉
