### ISSUE TITLE
Comment Activity multiselect feature selects wrong comment  after applying filter [Type][Bug]

### ISSUE THREAD

**Issue by ManmeetAT** [wordpress-mobile/WordPress-Android#13875]
### Expected behavior
1,MultiSelect comments 
2,Change the filter.

Selected comments should be the same after applying filter.

### Actual behavior

After applying filter, selection changes on different comments which were not selected

### Steps to reproduce the behavior
In Comments Activity
1,MultiSelect comments 
2,Change the filter.

##### Tested on [device], Android [version], WPAndroid [version]
Device Android -SM-J7
PF - Marshmallow
WP - 16.2
Version code 961

**Comment by designsimply** [comment]
Nice catch! ([45s](https://user-images.githubusercontent.com/1119271/105751349-20841600-5f03-11eb-91da-a3b40b2c529d.mp4)) Maybe the selection should get removed when the filter is changed? @aerych wdyt?

![comment-multiselect-test-wpandroid-16 5-rc-3](https://user-images.githubusercontent.com/1119271/105751674-96887d00-5f03-11eb-8ae0-6aa1cce969e0.gif)
<sup>Tested with WPAndroid 16.5-rc-3 on Pixel 3 Android 11.</sup>

**Comment by aerych** [comment]
Yeah. Let's clear the selection when the filter changes.  We can look at that as we're iterating on the filters in the very near future.  cc @khaykov @develric

**Comment by ManmeetAT** [comment]
I think If we clear the selection if filter changes one case will arise ,Let's say i want to delete few comments from approved and some from other filter than earlier selected comments  will get missed

**Comment by aerych** [comment]
I think this is preferred. We wouldn't want to surprise a user by performing operations on selections they can not currently see. 

Consider this: if a user were to select a few comments in one filter, then change filters to view a different set of comments, there is no visual indicator to show that those other comments remain selected.  Now we're in a situation where a user might forget what was previously selected and make an unintended change. 

I'm not sure we should assume there is an expectation that selections should be preserved across filters. If we look at wp-admin as an example, we'll see that selections are _not_ preserved.  So clearing the selections will (at least) be consistent with the experience in wp-admin,

**Comment by khaykov** [comment]
In #14140 We changed the Comment Filters from dropdown to tabs, and disabled filter change filters until you are done with batch moderation:
[![Image from Gyazo](https://i.gyazo.com/fecdd541b5b973efd962c5e6bcf6e429.gif)](https://gyazo.com/fecdd541b5b973efd962c5e6bcf6e429)
