### ISSUE TITLE
Login: "Continue with WordPress.com" might not be clear to some users.

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-Android#13879]
### Description
During a recent site-creation discovery session (internal reference `pbArwn-1AT`) a point was made that the login option "Continue with WordPress.com" might not be clear to all users that this will present you with options to create an account. As a result of that session, it was mentioned that it might be worth exploring ideas to add clarity in that area. 

<kbd><a href="https://user-images.githubusercontent.com/3384451/105766761-217b6e80-5f28-11eb-80d5-5588dd9f94d1.png"><img width="300" src="https://user-images.githubusercontent.com/3384451/105766761-217b6e80-5f28-11eb-80d5-5588dd9f94d1.png"/></a></kbd>

iOS Ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/15703

**Comment by leandroalonso** [comment]
@ParaskP7 can you please tackle this?

We should change "Continue with WordPress.com" to "Log in or sign up with WordPress.com".

(iOS reference: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/572/files)

**Comment by ParaskP7** [comment]
> @ParaskP7 can you please tackle this?

👋 @leandroalonso , definitely, I am on it, will tackle it today!

> We should change "Continue with WordPress.com" to "Log in or sign up with WordPress.com".

👍 

> (iOS reference: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/572/files)

🙏
