### ISSUE TITLE
Themes: Hide WordPress.com masterbar on theme details

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-Android#13880]
This is the Android clone of https://github.com/wordpress-mobile/WordPress-iOS/issues/7716 

Below is a copy-paste from that issue with the Android screenshots.

### Expected behavior
When you go to the Themes page and click on the details for your current theme, the information for the theme should appear in the framework of the app

### Actual behavior
However when you click on the theme details it is loading the complete webpage for the theme details as if you were seeing it in a browser instead of the app. This leads to replicating the menus twice, once for the app, and a second time because the admin bar appears at the top of the details section

<kbd><a href="https://user-images.githubusercontent.com/3384451/105768811-ee86aa00-5f2a-11eb-9682-dc26be9533ef.png"><img width="300" src="https://user-images.githubusercontent.com/3384451/105768811-ee86aa00-5f2a-11eb-9682-dc26be9533ef.png"/></a></kbd>

### Steps to reproduce the behavior

1. go to Themes in your mobile app
2. Click on Details to see the details for the current theme
What you see is actually a web browser version of the theme details page including the logged in WordPress admin bar at the top, so if you…
3. click on the my sites in the top left to open the WordPress.com menu you can have menus inside of menus

**Comment by chipsnyder** [comment]
We're exploring a Calypso fix for this https://github.com/Automattic/wp-calypso/pull/49281

**Comment by enejb** [comment]
The masterbar is now gone in calypso for mobile app requests. 
We might want to hide some of the buttons though as well. The arrow and the activate theme buttons for example.

**Comment by enejb** [comment]
This seems to be fixed now. With https://github.com/Automattic/wp-calypso/pull/49686
