### ISSUE TITLE
Quick Start: Skipped Step Still Shows as Incomplete

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-Android#13888]
### Expected behavior
If I choose "Not Now", it should no longer be in the list of steps to Customize my site

### Actual behavior
It remains in the list

### Steps to reproduce the behavior

1. While completing Quick Start, follow the guide dots to change your site title
2. Once you complete that, a prompt will appear suggesting you upload a new site icon
3. Choose "Not Now"
4. View the Customize your Site list and see that uploading a new site icon is still there

**Comment by JavonDavis** [comment]
I tested this on a Pixel3a Android version 11 and got the same behavior with uploading the site icon still in the checklist.

**Comment by designsimply** [comment]
I think that if you tap “Not Now” then the expectation is for that item to still be an incomplete item. 

Closing as I believe this is working as expected with a note that Quick Start will be getting some new improvements in the short term (you won't be able to dismiss a single task but you will be able to dismiss an entire category) and an ask to re-open if you feel strongly that it's a bug. 🙂

cc @renanferrari @chipsnyder (for visibility, and please re-open if you feel this is a bug)

**Comment by startuptester** [comment]
Yep, this was discussed here:https://github.com/wordpress-mobile/WordPress-iOS/issues/15713, just hadn't got to this one yet so thanks for grabbing it :)
