### ISSUE TITLE
User can delete Homepage and break their site

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-Android#13908]
### Description
It is possible to delete your Homepage while it's set as your static Homepage. This is a feature that is disabled on dotCom. If a user does delete their Homepage then their site will render with an error when you navigate there. 

### Steps to reproduce the behavior
**_Setup:_** Set your site's Homepage settings to use a Static Homepage

1. Navigate to pages
2. Tap the `...` 
3. Tap `Move to Trash`

##### Tested on Pixel 3a, Android 29, WPAndroid 16.6

iOS Ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/15729

**Comment by designsimply** [comment]
This seems like a bad experience, so I've prioritized it in our maintenance rotation project board and will check in at the next Sprint to see if it can be picked up sooner than later.

In the mean time, very open to having it picked up earlier in project work if possible! cc @chipsnyder (for visibility)

**Comment by chipsnyder** [comment]
I also just discovered that I can move my homepage to a draft which also breaks the site. So we should prevent that too even though the web allows it. I'll add it to Gutenpages board as well just to keep it top of mind.

**Comment by chipsnyder** [comment]
@designsimply I was able to grab some time to take this on. It'll be a part of 16.8

**Comment by designsimply** [comment]
Thank you @chipsnyder!
