### ISSUE TITLE
Limit to 1000 (one thousand) categories showing on Mobile

### ISSUE THREAD

**Issue by rossanafmenezes** [wordpress-mobile/WordPress-Android#13911]
### Expected behavior

User should be able to scroll through all the categories they have from the post editor - post settings - Categories to select a specific category to a post. 

### Actual behavior

There's a 1000 category limit in the apps. I believe it was not an issue so far because it's not common that users would go over 1000 categories, but when they do, they are not able to scroll down past the 1000th category. 

### Steps to reproduce the behavior

You would need to add more than 1000 categories to a site
Go to the posts tab
Click on an existing post or create a new one
Click on the ellipse menu
Post Settings
Categories
And scroll down to the end of the list. It won't show over 1000. 

##### Tested on [device], Android [version], WPAndroid [version]

User has Android 5.1.1 and WordPress 14.6.1 
But we were able to confirm over Slack(link to the thread in the ticket) that the limit is there

3686028-zen

**Comment by designsimply** [comment]
Thanks for the report @rossanafmenezes! Let's combine this one with the same open report for this on tags at https://github.com/wordpress-mobile/WordPress-Android/issues/11843. 👍
