### ISSUE TITLE
My Site: In light mode, placeholder avatar is just a grey circle.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#13918]
When in Light mode testing a self-hosted site (no Jetpack, no other sites), on the My Site screen, the avatar placeholder appears to just be a gray circle, not the actual avatar placeholder image.

![screenshot_20210129-152853](https://user-images.githubusercontent.com/1435271/106338523-98cb3e00-6259-11eb-89ac-32d605004b60.png)

wpandroid 16.6-rc-1, Pixel 2

**Comment by AjeshRPai** [comment]
Due to the changes in UI, this issue is no longer valid in the current version of the app
