### ISSUE TITLE
New screen options don't continue to final site preview when creating sites

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#13925]
### Expected behavior

After choosing a screen option from the site design picker screen page I'd expect that screen to be shown on the final preview shown after the site was created

### Actual behavior
 Mobile preview is always shown. 

### Steps to reproduce the behavior

1. Create a new site
2. change the screen option design from mobile to anything else
3. Finish creating the site

Notice the site preview is still on mobile

##### Tested on [device], Android [version], WPAndroid [version]
Tested on Google Pixel 4a, Android 11, 16.6-rc-2

**Comment by chipsnyder** [comment]
We are currently scoping out a project (ref `pb3aDo-NT#comment-1454`) that might end up replacing this screen. So putting this on hold for now.

**Comment by antonis** [comment]
Closing this as there is ongoing work on the Android site creation (ref: `pc8HXX-5j-p2`)
