### ISSUE TITLE
Shorter sign up - remove Send Link by email screen

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-Android#13971]
related WPiOS issue: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/574
1. Remove this screen: 

<img src="https://user-images.githubusercontent.com/1335657/106846256-6c506100-6661-11eb-8412-1800da561a0c.png" width="270" alt="Simulator Screen Shot - iPhone 12 Pro - 2021-02-02 at 13 00 39">

2. Instead, we will be sending the email immediately after the user entered their email : 

https://user-images.githubusercontent.com/1335657/106846364-96098800-6661-11eb-812e-c80a3ae1cdc2.MP4

3. Update copy in the second screen to add: "Didn't mean to create a new account? Go back to re-enter your email address." So it will look like :

<img src="https://user-images.githubusercontent.com/1335657/106958365-1bd31500-66ee-11eb-82fd-f87ac60712ad.jpeg" width="270" alt="IMG_7863C43CB5A6-1">

**Comment by leandroalonso** [comment]
@malinajirka @ParaskP7 @zwarm @ashiagr can one of you work on this issue this sprint, please? Thanks!

**Comment by elibud** [comment]
I'm a fan of this change, let's keep an eye on metrics to make sure it's actually making user's lives easier.

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

I'll start work on it today.
