### ISSUE TITLE
Jetpack Section: Add Date Headers to "Scan History" screen 

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#13992]
### Goal 

Currently a site with scan capability displays "Scan History" screen in the app including threat items without date headers. 

Goal of this issue is to group and display these threat items under date headers similar to "Activity Log" screen.

Scan History (without Date Headers) | Activity Log (with Date Headers)
-- | --
![image](https://user-images.githubusercontent.com/1405144/107221832-2b2dc780-6a3a-11eb-9d10-9ccea0a13e79.png) | ![activity_log](https://user-images.githubusercontent.com/1405144/107221951-51ebfe00-6a3a-11eb-83c3-124afa103489.jpg)

**Comment by thehenrybyrd** [comment]
@ashiagr looks like was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/14039 - I'm closing this issue on that basis, but please reopen if there's anything remaining to be fixed.
