### ISSUE TITLE
Change order of more menu items so "Visit site" won't be next to "Block site"

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-Android#14004]
The two menu items are too close

<img width="413" alt="Screen Shot 2021-02-05 at 8 20 56 AM" src="https://user-images.githubusercontent.com/1335657/107275661-e9375e00-6a06-11eb-80ee-a7ea2544075d.png">

**Comment by zwarm** [comment]
@mbshakti - any thoughts on how they should be reordered ?
