### ISSUE TITLE
Audio Block doesn't stop playback after exiting post preview

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#14046]
### Expected behavior

Audio Block should stop audio playback after exiting post preview

### Actual behavior

After previewing a post with an audio block and playing the audio, exiting the preview and continuing use of the app does not stop audio playback.

### Steps to reproduce the behavior

1. Create a post with an audio block 
2. Add an audio file to the block with a decent amount of playback time
3. Preview the post and play the audio file 
4. Exit the preview and observe the playback doesn't stop

##### Tested on [device], Android [version], WPAndroid [version]
Google Pixel 4a, Android version 11, WPAndroid 16.7-rc-4

**Comment by hypest** [comment]
Thanks for opening the issue Javon!

@jd-alexander , did we actually add any special support for the audio block in the post preview webview based flow? Looks like the Video block doesn't have this issue in my testings, but the Audio block does.

**Comment by jd-alexander** [comment]
Thanks for the ping @hypest and thanks for opening the issue @JavonDavis 

> @jd-alexander , did we actually add any special support for the audio block in the post preview webview based flow? Looks like the Video block doesn't have this issue in my testings, but the Audio block does.

@hypest No modifications were done to the webview flow. I am going to investigate this as I didn't experience it during testing.

**Comment by jd-alexander** [comment]
@hypest I created a PR to address the issue. I added a milestone of the next release, 16.8.
