### ISSUE TITLE
With some keyboard creates chips on dot

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#14066]
### Expected behavior
In the Invite People screen, while adding `Usernames or emails`I would expect to be able to add emails with dot sign without the string being transformed in a chip.

### Actual behavior
In the Invite People screen, while adding `Usernames or emails`I can have the string validated and being transformed in a chip when using a keyboard different from the Google Gboard standard one. Not sure on other keyboards but I noticed this for example with the MS SwiftKey keyboard.

### Steps to reproduce the behavior
- Install and enable the MS SwiftKey keyboard
- Try to add a user email with a dot (like name.surname@domain.com)
- Check the string is validated and transformed into a chip when pressing dot (so getting a chip with `name.` string)

**Comment by thehenrybyrd** [comment]
Seems this was addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/14063
