### ISSUE TITLE
Gallery doesn't work well on self-hosted sites

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#1406]
Some of the features in "Gallery Settings" are available to WordPress.com sites only. The app doesn't check if the current blog is Self-Hosted or not when creating that screen, resulting in unexpected result on self-hosted blogs.
For example if the user select type = Slideshow.

Ref: http://android.forums.wordpress.org/topic/slideshow-gallery-seems-not-to-work?replies=1

http://codex.wordpress.org/The_WordPress_Gallery

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by aforcier** [comment]
Re-opening since it's a WP media issue and not an editor issue.

**Comment by nbradbury** [comment]
Looking at [the docs](https://codex.wordpress.org/Gallery_Shortcode), self-hosted galleries don't support the `type` attribute, so for them we should remove the section highlighted below.

![screenshot_1494876159](https://cloud.githubusercontent.com/assets/3903757/26075304/bfdfbfc4-3982-11e7-98e9-88f9a9f992f9.png)
