### ISSUE TITLE
Jetpack Section: Update Activity Log Details UI and Add Backup Download Button/Flow

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14095]
As per the requirements in this post (`pcdRpT-cM`, see `Activity Log: Event Details`), this issue is about:
- UI updates on this screen to match design, and
- Adding the `Backup Download` button and connecting the button with the new flow.

Before | After
-------|------
<img width="250" height="500" alt="before" src="https://user-images.githubusercontent.com/9729923/108225084-4092a800-7144-11eb-9458-e2ece9899626.png"> | <img width="250" height="500" alt="after" src="https://user-images.githubusercontent.com/9729923/108225150-53a57800-7144-11eb-88ef-dce217851bd4.png">

On Android, the screen looks a bit different today, comparing the before (or current) of Android with the after (or current) of iOS:

Before or Current (Android) | After or Current (iOS)
-------|------
<img width="250" height="500" alt="before android" src="https://user-images.githubusercontent.com/9729923/108225656-cf9fc000-7144-11eb-9232-0fc8cb8126a1.png"> | <img width="250" height="500" alt="after ios" src="https://user-images.githubusercontent.com/9729923/108226033-302efd00-7145-11eb-8eaf-883176d46547.png">

@osullivanchris can you please suggest what UI changes need to happen to the UI so that Android get the appropriate after look, and still be comparable with iOS's after look?

**Comment by osullivanchris** [comment]
👋  Hey Petros, thanks for creating the issue. I tried to do as little as possible, just to add the extra button to this screen. I couldn't help tidying up the spacing a little bit. But only do that if its easy. I did have to move things a little bit, as it doesn't make sense to have the buttons above the information...unless you think that info could get really long?

Also - again if its quick - wondering if we are using default type styles. They looked a little off to me. I think maybe there's too much letter spacing. As a basis I used:

- 'Backup and scan complete' used 14dp body 2, medium emphasis color
- '15 plugins...' used 16dp body 1, high emphasis color


![event details button](https://user-images.githubusercontent.com/50576199/108235859-3077ca00-713e-11eb-9ccb-c88724467941.png)

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

Thank you so much for providing the updated design and specs on such a short notice. All you suggestions seem about right and I'll be doing all of them as part of this task. ❤️ 

> I couldn't help tidying up the spacing a little bit. But only do that if its easy.

Many thanks for tidying things up. 🌟 

> I did have to move things a little bit, as it doesn't make sense to have the buttons above the information...unless you think that info could get really long?

I agree, it doesn't make sense to have the buttons above the information. 🌟 

> Also - again if its quick - wondering if we are using default type styles. They looked a little off to me. I think maybe there's too much letter spacing. As a basis I used:
> - 'Backup and scan complete' used 14dp body 2, medium emphasis color
> - '15 plugins...' used 16dp body 1, high emphasis color

I agree again, will update those as well. 🌟 

🙏

**Comment by osullivanchris** [comment]
@ParaskP7 Sweet! Thanks for the positivity and making all the proposed fixes. And no problem on the design work, it didn't take long and I love making a quick fix! 😄
