### ISSUE TITLE
Jetpack Restore: app does not let you know if restores are disabled because server credentials are missing on the site

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#14100]
If you have not yet added server credentials to a Jetpack site then restores may not be enabled and the app will fail in several tasks with error messages that are not specific.

To prepare:

* Create a Jetpack site.
* Add a Jetpack Security Daily plan.
* Do NOT enable restores. You should see the following warning in your dashboard on the web.

![image](https://user-images.githubusercontent.com/1119271/108286361-2b1e7d80-7146-11eb-9a9c-e1f6fc0aa65b.png)

To test:

1. Go to My Site > Jetpack > Backup > overflow menu for any backup > Restore to this point.
1. Tap the "Restore site" button.
1. Tap the "Confirm" button.
1. Observe error: "There was a problem handling the request. Please try again later.
1. Go to My Site > Jetpack > Activity Log > overflow menu for any backup > Restore to this point.
1. Tap the "Restore site" button.
1. Tap the "Confirm" button.
1. Observe error: "There was a problem handling the request. Please try again later.

**Result:** if server credentials have not been added to the site then restores will not be enabled and you will see a generic error notice for any action such as a restore or trying to fix a threat or similar actions. Note that this is specific to 16.7 beta. ([2m20s](https://user-images.githubusercontent.com/1119271/108286309-14782680-7146-11eb-8fa4-68a1955c81fa.mp4))

There was a problem handling the request.|Error getting fix status. Please contact our support.
---|---
<img src="https://user-images.githubusercontent.com/1119271/108286345-23f76f80-7146-11eb-9617-cb566111c858.png" width="270" alt="there-was-a-problem-handling-the-request-please-try-again-later-WPAndroid16 7-rc-5">|<img src="https://user-images.githubusercontent.com/1119271/108286343-235ed900-7146-11eb-99f4-fcc227a91630.png" width="270" alt="error-getting-fix-status-please-contact-our-support-WPAndroid-16 7-rc-5">

<sup>Tested with WPAndroid 16.7-rc-5 on Pixel 3 Android 11 logged in as testuser011121.</sup>

Recommendations specific to the 16.7 release:

* The app should absolutely let you know if restores are not enabled for your site (i.e. missing server credentials) and direct you to how to correct the problem. I feel this is critical information that we should be able to detect and help users with.
* In addition to adding a persistent warning when restores are disabled, is there any chance of making those error notices that appear for a few seconds at the bottom of the screen more specific? Good error messaging is very important for our users!

**Comment by leandroalonso** [comment]
> In addition to adding a persistent warning when restores are disabled, is there any chance of making those error notices that appear for a few seconds at the bottom of the screen more specific? Good error messaging is very important for our users!

100% agree with that, @designsimply.

I'll create a separate issue for that for Android and iOS.

**Comment by momo-ozawa** [comment]
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/15924
iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/15951

**Comment by thehenrybyrd** [comment]
Looks like this was addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/14772.
