### ISSUE TITLE
Login: Button hidden by keyboard during Authenticator step

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#14120]
- I'm on a Pixel 3a 
- Android version 11
- app Version 16.7-rc-5

At the authenticator step, the primary button is hidden by the keyboard. I could still proceed by tapping the checkmark in the keyboard, so its not a blocker. But it didn't look right.

Not sure how the position of the button is defined, to resolve it.

Let me know if more details needed.

![image](https://user-images.githubusercontent.com/50576199/108529156-1966e280-72cc-11eb-8e6c-fd087438d474.png)

cc @mattmiklic

**Comment by designsimply** [comment]
I reported this previously in https://github.com/wordpress-mobile/WordPress-Android/issues/12964 and was quite surprised at the time that a lot more people hadn't mentioned the issue. After a bit of research, I found that it may be (have been?) part of an A/B test on the Gboard keyboard on Pixel devices—which would explain the very low numbers of reports (me, you, and one other person so far). Anyway! I'd like to close this one as a duplicate in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/12964 with a note that it will be good to keep an eye out for additional reports but it certainly doesn't appear to be a very widespread problem so far (from what I can gather).
