### ISSUE TITLE
Media Pickers should filter files based on site's plan supported MIME types.

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#14121]
### Expected behavior
The MediaPicker needs support for allowed MIME types based on a site’s plan ([Dot Com](https://en.support.wordpress.com/accepted-filetypes/)) or configuration ( [Dot Org](https://href.li/?https://codex.wordpress.org/Uploading_Files)) as a means of filtering unavailable MIME types from the media pickers. 

`FluxC` is expected to have support for this at it's layer since it is in charge of managing the mime types allowed. [An issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1884) is tracking the behavior needed there.

### Actual behavior
All file types that are on a device are shown. 

### Steps to reproduce the behavior
1. Utilize a WPCom site with a free plan. 
2. Go to the File Block. 
3. Notice you are able to add `.key` and `.zip` files which should only be available on paid plans.

**Comment by designsimply** [comment]
Also see https://github.com/wordpress-mobile/WordPress-Android/issues/13353.

Are different media pickers used in the Media Library vs Gutenberg Mobile? If yes, do changes need to be made in both places?

**Comment by jd-alexander** [comment]
> Also see https://github.com/wordpress-mobile/WordPress-Android/issues/13353.
> 
> 
> 
> Are different media pickers used in the Media Library vs Gutenberg Mobile? If yes, do changes need to be made in both places?

Good question. I will investigate this and get back to you @designsimply 🙏🏾

**Comment by jd-alexander** [comment]
@designsimply to answer your question, based on my investigation both the Media Library and Gutenberg Mobile utilize the same pickers which will be modified with these changes so both places will get the updated functionality as a result. Currently, the Consolidated Media Picker is powering both experiences but the previous picker design/functionality still exists for rollback purposes. You can give it a test when I create the behavior and tag the PR :)
