### ISSUE TITLE
Reader Improvements: Redesign "Topics you might like"

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#14129]
Show topics using topic chips instead of a list to reduce vertical space taken up by the "Topics you might like" section.

![topics-you-might-like-card](https://user-images.githubusercontent.com/1405144/108673767-430d4d00-750a-11eb-8c8c-e6ea3deff12d.png)

**Comment by designsimply** [comment]
Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/issues/15556.
