### ISSUE TITLE
App crashing when you try to create a new page

### ISSUE THREAD

**Issue by rossanafmenezes** [wordpress-mobile/WordPress-Android#14152]
### Expected behavior

When you click on the option to add something and select a new page, the template screen should show so the user can select one, and after this is selected the app creates a new page. 

### Actual behavior

I have now seen 2 reports where the user clicks on the option to create a new page (after the update) and the app crashes right after. The template screen blinks for a second and the app crashes (video available here 3772214-zen). 

### Steps to reproduce the behavior

I was not able to reproduce it, but on the user's video are as follow:

1 - open the app
2 - click on my sites
3 - click on the Add pink button at the bottom right corner of the screen
4 - Select Site page
5 - the app crashes

##### Tested on [device], Android [version], WPAndroid [version]

User 1 3772214-zen
WordPress - 16.7
Android device name: Samsung Galaxy Note10
Asking for Android Version

User 2 3772718-zen
WordPress - 16.7 - Version code: 1002
Android device name: Xiaomi Mi MIX 2
Asking for Android Version

Me - Pixel 3 
Android 11
WordPress 16.7 rc 7 

Me - Pixel 2 
Android 11
WordPress 16.7 rc 7

**Comment by antonis** [comment]
Hey @rossanafmenezes 👋 
Thank you for reporting this 🙇 
This is related to [this Sentry report](https://sentry.io/share/issue/84d9ff222a3248ccab6c168bf7de8361/).

A server side fix was applied (internal ref: `pb3aDo-Pe-p2`) to stop the Android app from crashing and a [client side fix will be included in the next version](https://github.com/wordpress-mobile/WordPress-Android/pull/14153) to prevent such issue from occurring in the future.

**Comment by antonis** [comment]
I consider this fixed. Please reopen if the issue persists 🙇
