### ISSUE TITLE
Jetpack Scan/Backup displays "Something went wrong" when VaultPress is being used

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-Android#14168]
If you try to access the Jetpack Backup/Scan with a site that's connected to VaultPress, the app shows a generic error without much info on what to do next.

### Expected behavior

In Calypso, for both Scan and Backup we show users a button/link that points them to their https://dashboard.vaultpress.com/:

<img width="904" alt="Captura de Tela 2021-03-01 às 18 35 20" src="https://user-images.githubusercontent.com/1136160/109562241-e5a26e80-7abc-11eb-8b17-023f2aa19505.png">

<img width="844" alt="Captura de Tela 2021-03-01 às 18 35 46" src="https://user-images.githubusercontent.com/1136160/109562340-01a61000-7abd-11eb-9517-a9b88b2de453.png">

### Actual behavior

We see a `Something went wrong` error message that forces the user to contact us:

<img width="424" alt="Captura de Tela 2021-03-01 às 18 33 47" src="https://user-images.githubusercontent.com/1136160/109562064-b12eb280-7abc-11eb-873d-1a500644dd80.png">

### Steps to reproduce the behavior

1. Select a site that has VaulPress as the backup option
2. Go to Jetpack Scan/Backup
3. Check the message

* Related report: 3781174-zen
* Convo: p1614626234308800-slack-C0CMN0V97

**Comment by leandroalonso** [comment]
@ashiagr @AjeshRPai could you please prioritize this issue for the next few days? I did an investigation and on iOS it shouldn't be super complex to solve. [More info here](https://github.com/wordpress-mobile/WordPress-iOS/issues/17146).

All we want is to communicate the issue to the user and give them a button to access `https://dashboard.vaultpress.com/`
