### ISSUE TITLE
Unable to Update Price (moved to woocommerce repo)

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/WordPress-Android#14167]
### Expected behavior
After tapping on the price field, you're able to update it to a new value.

### Actual behavior
After tapping on the price field and tapping on the backspace key, the existing price will clear, but you aren't able to enter a new price.

### Steps to reproduce the behavior
1. Navigate to Products tab
2. Select product
3. Enter the price change view
4. Tap on backspace key
5. Attempt to enter new price

##### Tested on Honor 8A, Android 9, WPAndroid 6.1-rc-2, using Microsoft SwiftKey keyboard.

Video of this found here: 3783405-zd-woothemes

**Comment by designsimply** [comment]
I think this one got filed in the wrong spot! Moved to https://github.com/woocommerce/woocommerce-android/issues/3651 👍
