### ISSUE TITLE
"This post no longer exists" for links that use the non primary domain

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#14216]
It was reported in 3771371-zd-woothemes that when opening a link through the Chrome browser, the app shows "The post no longer exists".

### Expected behavior

I would expect the app would be able to open up the post that I clicked through the Chrome browser.

### Actual behavior

When I click a link that's pointing to the URL with a non-primary domain on Chrome browser, choose to open up with the WordPress app, I see a "The post no longer exists" error.

### Steps to reproduce the behavior

1. Visit a WordPress.com site that has a custom domain set as the primary domain on a Chrome browser (e.g. https://premiumtestsite20190311.blog/)
2. Click a link on the site that is pointing to the WordPress.com site address (see [this image](https://d.pr/i/C5fkrV) for the link to click)
3. Open up the link with WordPress app
4. See "This post no longer exists" error

Video recording: https://d.pr/v/JCZtZS/QfCufdf8mG

##### Tested on OPPO Reno 4, Android 11, WPAndroid 16.8-rc-2

**Comment by designsimply** [comment]
Thanks for including a video @reginabally! 

Tested and confirmed that links opened from Chrome into the app that are pointing to the *.wordpress.com version of a URL on a site using a custom domain results in a "This post no longer exists" message.

My testing steps:

1. Be on a site with a custom domain set as the primary domain.
1. Copy the URL for any post from the site.
1. Create a new post and add a link to the URL from the previous step.
1. Add another link to the URL from the previous step, except change the custom domain to the *.wordpress.com version.
1. Publish the post.
1. Open the post in Chrome.
1. Click on the 2nd link and choose to open the link in the app when prompted.

**Result:** an error appears saying "This post no longer exists." It appears the in-app browser does not properly redirect *.wordpress.com links to their custom domains. ([1m35s](https://user-images.githubusercontent.com/1119271/110525670-1b091680-80d2-11eb-908c-e9a528abfd74.mp4))

*.wordpress.com version of link|Opt to open link in app|Error
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/110526108-a4204d80-80d2-11eb-9d77-08df0783a5e5.png" width="270" alt="link-example">|<img src="https://user-images.githubusercontent.com/1119271/110526113-a5517a80-80d2-11eb-94b8-40fbbfd75608.png" width="270" alt="open-with-wordpress">|<img src="https://user-images.githubusercontent.com/1119271/110526107-a387b700-80d2-11eb-979c-f6c5edfc7501.png" width="270" alt="this-post-no-longer-exists">

<sup>Tested with WPAndroid 16.9-rc-1 on Pixel 3 Android 11.</sup>

**Notes:** the same link works properly when opened using a web browser—it redirects to the custom domain version of the URL. Links in the app to the custom domain do not offer to open the link in the app (as expected).

**Comment by jd-alexander** [comment]
Thanks for reproducing this @reginabally and @designsimply 🔆  I have started my investigation into the issue and once it has been resolved and tested, I will provide a link to the APK so you can test while the PR is being reviewed. 🙇🏾

**Comment by jd-alexander** [comment]
I was able to resolve the issue @reginabally @designsimply 😄  . If you wish to give it a try you can [download the APK ](https://github.com/wordpress-mobile/WordPress-Android/pull/14280#issuecomment-802292230).
