### ISSUE TITLE
Increase the severity of `UseAppTint` lint error

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#14222]
While working on the composite Gutenberg build project, we came across `UseAppTint` lint error in files we have not made any changes to. We don't know why this error wasn't present before these changes and we don't think it'd be right to handle these errors as part of a larger project, so we decreased the severity of it to `warning` in https://github.com/wordpress-mobile/WordPress-Android/pull/14212.

Since we were already unintentionally ignoring these lint errors, it shouldn't change anything in practice. However, since we decreased its severity without giving it a proper look, it'd be great to re-visit it and either handle the errors or verify that this is the best way to handle them.

**Comment by designsimply** [comment]
Adding to Groundskeeping To Do with a note that we should do this update in the rotation that starts on 2021-03-29 (as discussed in Slack 👍).

<sup>(internal reference: p1615307153317300-slack-CC7L49W13)</sup>

**Comment by oguzkocer** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/14366.
