### ISSUE TITLE
Reader: add back suggested posts 

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#14266]
This is a suggestion from someone made in an app review:

> There was a tweak in the previous update where you could see an overview of more on Wordpress with listed posts with similar tags and categories on Reader. But it's gone. I'd like it back, please...

* Mar 13, 2021, 20:28
* Device: Samsung Galaxy A01
* Device language: English
* App version name: 16.8.1
* Android version (SDK): Android 10 (SDK 29)

**Comment by ashiagr** [comment]
Related posts were brought back via https://github.com/wordpress-mobile/WordPress-Android/issues/14128.
Closing it as duplicate.
