### ISSUE TITLE
Support: text on the empty state My tickets page is unreadable white on light gray

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#14277]
Steps to reproduce:

1. Change the device settings to dark theme.
1. Delete and re-install the app (if needed) to clear out any support ticket history.
1. Go to My Site > Account > Help & Support > My Tickets.
1. Try to read the text on the screen.
1. Change the device settings to light theme.
1. Try to read the text on the screen.

**Result:** in dark theme the text "Conversations started from this app will be visible here" and the text "START A CONVERSATION" are both too light to read—in light theme, only the "START A CONVERSATION" text is too light to read.

Dark theme|Light theme
---|---
<img src="https://user-images.githubusercontent.com/1119271/111558297-1e487600-8754-11eb-946c-85bb6cb467f1.png" width="270" alt="Screenshot_20210317-181731">|<img src="https://user-images.githubusercontent.com/1119271/111558295-1d174900-8754-11eb-89cc-db223d7b6396.png" width="270" alt="Screenshot_20210317-181746">

<sup>Tested with WPAndroid 16.9-rc-3 on Pixel 3 Android 11.</sup>

**Comment by thehenrybyrd** [comment]
No longer able to reproduce on **Samsung Galaxy S21, Android 12, WP Android 20.3-rc-1**. Now, all text is visible in both light and dark mode. Closing as resolved.
