### ISSUE TITLE
Jetpack App

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14291]
This is the main project issue for the `Jetpack App` project.

Project Thread: `pcdRpT-93-p2`

### Task

- [x] Basics: #14293 ⚙️ 
- [ ] Emphasis: #14294  ⚙️ 
~~- [ ] IAP: #14295~~ Note: This will be a separate issue when the time comes

**Comment by jkmassel** [comment]
This issue doesn't appear to be relevant anymore.
