### ISSUE TITLE
Improve UX when adding externally hosted image

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1429]
When you add an image from the Photos app (or any other app that doesn't store the image locally), the image has to be downloaded before being inserted in the editor.

Currently we show a toast message that the image is downloading, which isn't so great. It'd be much better to animate in a progress bar view so that the user can view the download progress.  

It also doesn't appear that there's any messaging if the download fails, which can cause confusion.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
