### ISSUE TITLE
Jetpack App (Basics): Configure Sentry

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14313]
Parent: #14293

TODO

- Sentry DSN.

**Comment by wzieba** [comment]
In order to keep a consistent setup of Sentry between projects and have some other features like encrypted logging, I'd recommend to use `Automattic-Tracks-Android` - it'll soon be available in `WordPress` project #14833. WDYT @ParaskP7 ?

**Comment by ParaskP7** [comment]
👋 @wzieba !

Thanks for checking this issue and your suggestion. 🙏  I am 💯 up for it.

I am also adding @JavonDavis to the loop, since this task is being handled by the Platform9 team.

**Comment by AliSoftware** [comment]
Implemented in https://github.com/wordpress-mobile/WordPress-Android/pull/14983
