### ISSUE TITLE
Jetpack App (Basics): Configure WPCom API

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14310]
Parent: #14293

TODO

- WPCom API key.

**Comment by AliSoftware** [comment]
@ParaskP7 I'm assuming this can be closed, as JP probably uses the same WPCom API key as WP? Can you confirm?

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

Yes, I think so too. Let's close it, JP uses the same WPCom API key as WP.

PS: Thanks for taking a look at those tasks and closing them one-by-one. 🙏
