### ISSUE TITLE
Jetpack App (Basics): Configure Logging

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14311]
Parent: #14293

TODO

- Encrypted log key.

**Comment by jkmassel** [comment]
This should just work out-of-the-box, because the encryption key is the same across all apps (it's a public key).

I think we can close this

/cc @JavonDavis @AliSoftware

**Comment by AliSoftware** [comment]
I verified with some random issues in the `jetpack-android` Sentry project and confirm that it works out of the box.
