### ISSUE TITLE
Jetpack App (Basics): Update About the App 

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#14315]
Parent #14293

App Settings: About the App Section
- [ ] Update WordPress for Android
- [ ] Update Open source licenses

|Wordpress for |open source
|---|---
|![light](https://user-images.githubusercontent.com/506707/112011405-a042f100-8afe-11eb-82be-deb043707dd7.png)|![dark](https://user-images.githubusercontent.com/506707/112011415-a20cb480-8afe-11eb-816a-006e5df6f6bf.png)

**Comment by ashiagr** [comment]
Closed via #14420.
