### ISSUE TITLE
Jetpack App (Basics): Configure Google API

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14336]
Parent: #14293

TODO

- Login client ID.
- Login scheme ID.
- Login server client ID.

**Comment by AliSoftware** [comment]
@ParaskP7 I'm assuming this can be closed, as JP Google login works as expected? Can you confirm?

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

Yes, you are right, since JP Google login works as expected, this can be effectively closed as complete.
