### ISSUE TITLE
Tabs for comments filters don't keep the list's scrolling position on orientation changes

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#14347]
See related PR where the feature was introduced https://github.com/wordpress-mobile/WordPress-Android/pull/14140

### Expected behavior
When changing the device orientation, I expect the scroll placement on the list I'm looking at to be kept.

### Actual behavior
The list is scrolled all the way up to the first element.

https://user-images.githubusercontent.com/6597771/112458851-049ec400-8d3c-11eb-9c37-79db428b744a.mp4

### Steps to reproduce the behavior
1. go to Comments
2. scroll down on any of the filtered tabs
3. change the device orientation
4. observe the list gets scrolled all the way up

**Comment by mzorz** [comment]
Also note:
> Preserving action mode selection on configuration change.
> Preserving scroll position on configuration change.

Selecting (action mode) state is lost as well when testing 17.0-rc-2

**Comment by khaykov** [comment]
Thanks for reporting this one, @mzorz ! Just for a context, this is preexisting behavior, and not related to the comment filters :) We are planing to address this in the near future.

**Comment by mzorz** [comment]
> Things that I have not covered in this PR and that are present in existing implementation:

🤦 I totally missed reading the preceding text - very sorry @khaykov and thanks for your kind clarifying comment here! 🙇 (from https://github.com/wordpress-mobile/WordPress-Android/pull/14140)

**Comment by AliSoftware** [comment]
I'm about to submit 17.9 to Google, so I just moved this issue yet again to the next milestone (18.0).

But I see this issue hasn't moved since 17.0, so wondering if we should repriorize/retriage it instead of pushing it to the next milestone over and over? (\cc @AmandaRiu as CTrO)

**Comment by AliSoftware** [comment]
Moved the milestone yet again as I'm code-freezing 18.0. Re-added the `"Requires Triage"` label as I feel it needs it given my comment above ☝️ and the issue being constantly postponed since 10 versions now. \cc @zwarm

**Comment by zwarm** [comment]
@khaykov 
>  We are planing to address this in the near future.

Do you still have plans to address this bug? If not, I'm going to lower the priority and move it to the groundskeeping board. Please let me know. Thanks.

**Comment by khaykov** [comment]
Sorry for a delayed update - we fixed this in #15107
