### ISSUE TITLE
[Login] Button covered by keyboard in 2FA authentication code screen

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#14350]
### Expected behavior
Button should be visible after entering code so I can tap on it

### Actual behavior
Button is half covered by the numeric  keyboard
![Screenshot_20210325-103608](https://user-images.githubusercontent.com/6597771/112480079-6b2fdc00-8d54-11eb-90ff-b3dcd382bce0.png)

### Steps to reproduce the behavior
1. enable 2fa 
2. login to the WPAndroid app
3. observe the screen when the authenticator code is requested

**Comment by sakets3010** [comment]
@mzorz i would like to work upon this feature.

**Comment by planarvoid** [comment]
I'm closing this issue for duplicity with https://github.com/wordpress-mobile/WordPress-Android/issues/13238
