### ISSUE TITLE
Jetpack App (Basics): Handle Notifications

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14379]
Parent: #14293

- [x] Add new AppKey for `com.jetpack.android`  #14468

**Comment by leandroalonso** [comment]
@ParaskP7 @zwarm @ashiagr we'll change the backend code to handle the JP apps. The first step is to change the push notification app ID constant.

For iOS, this was done here: https://github.com/wordpress-mobile/WordPress-iOS/pull/16304

We need to do the same for Android (change `org.wordpress*` to `com.jetpack*`

Can one of you please give priority to this issue? Once we have both PRs ready we can test integrated with the server. Thanks!

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

Many thanks for your message, and referencing the iOS PR, we will prioritize that one indeed! 🙏

**Comment by zwarm** [comment]
@leandroalonso 
We don't have permission to create a new App in Google Developer/Play console. We'll need P9 to create the app first and provide us with the App Id.

**Comment by ashiagr** [comment]
Closed via #14507
