### ISSUE TITLE
Site timezone defaults to UTC instead of user timezone 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-Android#14400]
From user feedback session:

This comes up very often in testing so it's obvious it confuses people.

You schedule a post for later and it publishes immediately but you have no idea why. It's because new site timezones default to UTC instead of the user's location. This is not an intuitive experience.

**Comment by ovitrif** [comment]
As already [mentioned on the iOS twin issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/16231#issuecomment-1021506952), the Android app is also not sending any timezone info to the WP.com public api as of version 19.0 when creating a new site.

I'll explore the option of passing the [local time zone id](https://github.com/wordpress-mobile/WordPress-Android/blob/ea4b71354918f6772cf49674a4fd7e890b6e9e75/WordPress/src/main/java/org/wordpress/android/util/LocaleManagerWrapper.kt#L12) of the user's device to the payload of the `POST /sites/new`  WP.com REST API endpoint with an upcoming pull request 🙇‍♂️
