### ISSUE TITLE
Drag & Drop support

### ISSUE THREAD

**Issue by fahdriyami** [wordpress-mobile/WordPress-Android#14416]
Please add drag and drop support to the app. It would make things a lot easier to be able to drag images or text from another app like Chrome or Edge into the Wordpress editor. Especially useful when running two apps side by side in split screen or on dual screen devices like the Surface Duo.

Android has a [guide](https://developer.android.com/guide/topics/ui/drag-drop) on adding drag and drop support.

**Comment by thehenrybyrd** [comment]
Thanks for the suggestion! This would definitely be nice on larger devices.

**Comment by hypest** [comment]
👋 all! I copied the feature request over to the ticket already opened about it on the gutenberg-mobile repo, [see here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1602#issuecomment-821005925), and will close this ticket to avoid splitting the conversation/information in many tickets. Please, feel free to add any additional info/thoughts to that other ticket, thanks!
