### ISSUE TITLE
PDF Files cannot be downloaded if the site is private

### ISSUE THREAD

**Issue by rossanafmenezes** [wordpress-mobile/WordPress-Android#14425]
The user has a private Premium Plan site and is not able to download PDF files they add to their site when they visit the site from the app. 

I was able to reproduce the issue on my phone. However only with simple sites since you can't set atomic sites to private. 

The site is set to private. If you add a file block and a PDF file to the block and publish the post/page then visit the post from the app, either from the toast message that shows at the bottom of the screen after you publish the post or from the Visit Site tab in the dashboard and you click on the download button it won't work and the app shows the following error message:

![photo_2021-04-08 07 45 02](https://user-images.githubusercontent.com/30724184/114021324-93ccd100-983e-11eb-81f9-5d367743d979.jpeg)

However, if you access the post from a browser you are able to download it. Also and weirder, if you set the site to public, access the site from the app, then set it back to private, access the site from the app again the download works without any issues. 

![photo_2021-04-08 07 44 58](https://user-images.githubusercontent.com/30724184/114021533-cd054100-983e-11eb-82ba-882fb02e5c1f.jpeg)

### Steps to reproduce the behavior

Set a simple site to private
Add a new post or page
Add a File Block
Add a PDF file (I have tried with other types of file like DOCX and it works. The issue seems to be with PDF files only)
Publish the page/post
Visit the post from the View Post in the toast message at the bottom of the screen or from the Visit Site tab
Try to download the file and see the error message
Then set the site to public
visit the site from the app
Download the PDF file. It works fine
Set the site back to Private
Visit the site from the app
Download the PDF file. It works 

##### Tested on [device], Android [version], WPAndroid [version]

USER:
HUAWEI CLT-L29
WP Version: 16.9
Android Version: Not provided in the logs. Waiting for user to confirm

Me:

Pixel 3
Android 11
WP app 17.1 rc 1

**Comment by thehenrybyrd** [comment]
Unable to reproduce on **Samsung Galaxy S21, Android 12, WP Android 20.3-rc-1**. I was able to download a PDF from a post on a private simple site, via "View Site", and by "View" in the post list.
Closing this for now, please reopen if necessary.
