### ISSUE TITLE
Jetpack App (Basics): Update Control Activated Colors (Checkbox, Switch, Etc)

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14436]
Parent: #14293

Some native components are using a lighter colour than the one we have defined.

Search for usages of:
- Checkboxes, and
- Switches
For example, see `Restore` and `Backup Download` screens for checkboxes. Also, see `Settings` for switches.

PS: @osullivanchris can you please confirm a screen where you are seeing switch colors using a lighter colour than intended? For example, is the `Settings` screen a good example?

**Comment by osullivanchris** [comment]
Sure thing. Here are screenshots from notification settings, and from restore/backup, where the checkboxes and switches appear to be using something close to Jetpack Green 30.

![Screenshot_20210409-123200](https://user-images.githubusercontent.com/50576199/114174077-08cc0380-9930-11eb-96cc-c7a61bf29324.png) 

![Screenshot_20210409-123139](https://user-images.githubusercontent.com/50576199/114174072-0669a980-9930-11eb-90a3-4fde95972377.png)

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

Great, thanks so much for sharing that Chris. 🙏
