### ISSUE TITLE
My Site navigations labels misaligned in RTL languages

### ISSUE THREAD

**Issue by rossanafmenezes** [wordpress-mobile/WordPress-Android#14438]
### Expected behavior

Since Hebrew is one the Mag16 languages I would expect the app to maintain the layout  structured based on the selected language. 

### Actual behavior

I had one user reporting that after the latest update they were not able to switch sites when their phone is set to Hebrew because the layout looks truncated. They are on iOS and I have reported this in the iOS repo but I have tested it on my pixel 2 and 3 and something very similar happened. 

Since Hebrew is one the Mag16 languages I would expect the app to maintain the layout but even tho I was able to switch sites, so not exactly the same situation the user reported on iOS the layout is also truncated:

![Annotation on 2021-04-09 at 09-43-16](https://user-images.githubusercontent.com/30724184/114189397-27260500-9918-11eb-9dce-db04d8514a2a.png)

### Steps to reproduce the behavior

Go to the device settings
change the language to Hebrew
Open the WordPress app

##### Tested on [device], Android [version], WPAndroid [version]

Pixel2 and Pixel 3
Both on Android 11
WP 17.1-rc-2 on Pixel 2
WP 17.1-rc-1 on Pixel 3

3886795-zen
iOS Report [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/16267)

**Comment by thehenrybyrd** [comment]
@rossanafmenezes thanks for reporting this!
I was able to reproduce on my Nokia 2, in both Hebrew and Arabic:

![Screenshot_20210412-135552](https://user-images.githubusercontent.com/15107387/114386930-885d0b00-9b9a-11eb-8069-79c97a83b748.png)
![Screenshot_20210412-140422](https://user-images.githubusercontent.com/15107387/114386932-898e3800-9b9a-11eb-82d1-ec9dc5073b1a.png)

Tested on Nokia 2, Android 7.1.1, WPAndroid 17.1-rc-1

**Comment by antonis** [comment]
Assigning the `[Pri] Medium` tag since this issue on Android is visual but affects a lot of our users
