### ISSUE TITLE
Plans: Personal plan description inaccurate

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#14442]
### Expected behavior
My Site > Plans should display accurate, up-to-date information.

### Actual behavior
The WordPress.com Personal plan no longer includes live chat, however it is shown in the app.

Currently, going to My Site > Plans > Personal plan shows that live chat is included:

![Screenshot_20210412-144039](https://user-images.githubusercontent.com/15107387/114390315-c52b0100-9b9e-11eb-89bb-ee633667dd48.png)

This is contrary to [wordpress.com/pricing](https://wordpress.com/pricing/) which states "Unlimited Email Support" is included and live chat is not.
The inaccuracy resides (at least) at the API layer, where the Personal plan function still includes ‘get_feature_support_live’ (Plans.php, line 153). See most recent changeset at r220085-wpcom.

##### Tested on:
Nokia 2, Android 7.1.1, WPAndroid 17.1-rc-1
Samsung Galaxy S21, Android 11, WPAndroid 17.1-rc-1

Initially reported by @reginabally in #14374

**Comment by thehenrybyrd** [comment]
This came up again in beta testing for 18.7.

**Comment by jkmassel** [comment]
We no longer display plans, so this can be closed.
