### ISSUE TITLE
Jetpack App (Basics): Change Tracks Event Prefix

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-Android#14493]
Parent: #14293

The events sent by WPAndroid contain the prefix `wpandroid`. For the Jetpack app we should change that to `jpandroid`.

#### Jetpack

1. Given an event is sent by Jetpack
2. The prefix is `jpandroid`

#### WordPress

1. Given an event is sent by Jetpack
2. The prefix is `wpandroid`

**Comment by ParaskP7** [comment]
Another part of this task is to test in Hue if the event was recorded (thus is whitelisted). Here's the query:

`SELECT * FROM tracks.etl_events WHERE eventname = 'jpandroid_application_opened'`

PS: You can also change to `LIKE "%jpandroid%"`.
PSS: Thanks @leandroalonso .
