### ISSUE TITLE
Empty error message when logging in with invalid credentials through self-hosted flow

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#14506]
### Expected behavior

I would expect to see a meaningful error message (e.g. invalid username/password) when I failed to log in to the app through the "Enter your existing site address" flow.

### Actual behavior

I'm seeing a grey placeholder without the actual error message.

https://user-images.githubusercontent.com/40906847/115647271-0e751080-a356-11eb-8fc1-0e56da43ebfd.mp4

### Steps to reproduce the behavior

1. On the login screen, select the "Enter your existing site address" option.
2. Enter a self-hosted WordPress site address.
3. Enter incorrect site credentials (username and/or password).
4. See a grey placeholder appear on the screen without an actual error message.

**Comment by thehenrybyrd** [comment]
Thanks @reginabally! I was able to reproduce this and see the same thing, with either incorrect username or incorrect password.

https://user-images.githubusercontent.com/15107387/115677356-12566200-a359-11eb-9059-fdbc5b488176.mp4

Tested on Samsung Galaxy S21, Android 11, WPAndroid 17.2-rc-1

**Comment by thehenrybyrd** [comment]
Another report of this came up in [beta testing](https://wp.me/p5T066-2bn#comment-8046).

https://user-images.githubusercontent.com/15107387/116236431-bbd99100-a767-11eb-9b54-f075c1f7b8da.mp4

Tested on WPAndroid 17.2-rc-2
