### ISSUE TITLE
Illustration for 10k views notification shows 100k instead

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/WordPress-Android#14518]
### Expected behavior

The illustration on the notification must show 10k for 10k views. 

### Actual behavior

It shows 100k instead.

![signal-2021-04-23-141728](https://user-images.githubusercontent.com/18581859/115845635-ac440a80-a43e-11eb-9e8f-e7402813c7b7.jpeg)

### Steps to reproduce the behavior

Create a website (not sure if this is a feature of WordPress.com or of Jetpack), get 10k views, check the notification on the app.

##### Tested on [device], Android [version], WPAndroid [version]

OnePlus 5, Android 10.0.0, WordPress 17.2-rc-1

**Comment by arunsathiya** [comment]
It is worth noting that the illustration no WordPress.com notifications on desktop is okay though. I see 10k there.

<img width="379" alt="Screenshot 2021-04-23 at 2 18 17 PM" src="https://user-images.githubusercontent.com/18581859/115845709-c0880780-a43e-11eb-99c7-22cace2c96ef.png">

**Comment by thehenrybyrd** [comment]
Thanks for the heads up @arunsathiya!
Looks like we're puling in the wrong view-milestone-badge for the 10K mark.

@emilylaguna can you take a look at this one? We probably want to double-check we don't have the same issue on iOS, as well. Thanks!

**Comment by emilylaguna** [comment]
@thehenrybyrd Heya! Thanks for letting us know, we pushed out a server fix for this last week. And will be fixed for everyone once the CDN refreshes. Going to close this for now.
