### ISSUE TITLE
Enhancement: change "Blog Posts" menu label to simply "Posts"

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-Android#14570]
Now with the Nav Unification in WordPress.com, the dashboard is closely aligned to self-hosted sites. On both dashboards, we have **Posts** as the menu item.

On the mobile devices, however, we still show them as **Blog Posts**. The suggestion is to change it **Posts** so they all match.

### Steps to reproduce the behavior

1. Open the app
2. Tap on My Site
3. Find **Blog Posts**

Context: 3949093-zen

**Comment by thehenrybyrd** [comment]
Same issue in iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/16418 
Thanks Edu! ❤️

**Comment by AliSoftware** [comment]
@eduardozulian Same question as in https://github.com/wordpress-mobile/WordPress-iOS/issues/16418#issuecomment-919566395 – aka should we also change "Site Pages" to "Pages" in that screen for consistency?
