### ISSUE TITLE
Jetpack App (Basics): Include Atomic Sites

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#14619]
Parent #14293 

- [x] Include Atomic sites in the API call
- [x] Validate Login flow continues to work correctly for No Jetpack Sites & Not a Jetpack Site

**Comment by ashiagr** [comment]
Changes not needed (see https://github.com/wordpress-mobile/WordPress-Android/pull/14628#issuecomment-843176496).
