### ISSUE TITLE
Story Block: display Media Upload Options immediately

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#14646]
### Desired behavior
When adding an Image, Video, or File block, the Media Upload Options (Choose from Device, Media Library, etc) open immediately.
There's no need to tap "Add Image", "Add Video", etc.
It would be nice if this were the case for the Story Block, as well. Users may want to choose an existing Story Post to display, create a new one from existing media, or from scratch.

### Actual behavior
When adding a Story Block, no upload options appear immediately. Instead, the user needs to tap "Add Media" to get started.

### Steps to reproduce the behavior
In a Post or Page, add the Story Block from the block picker.
Note that the block is added, but no upload options appear. 
In order to add media, note you need to tap "Add Media".
Try out an Image, Video, or File block to compare.

##### Tested on Samsung Galaxy S21, Android 11, WPAndroid 17.3-rc-1
Beta testing context: p5T066-2fh-p2#comment-8242

**Comment by hypest** [comment]
👋 @mzorz , since the feature of auto-opening the media picker is implemented on a block-by-block basis, depending mostly on design side consideretions, can you perhaps add this to the Storys related backlog for y'all Story block folks to consider? 😃

**Comment by mzorz** [comment]
Definitely! Added to our "to be sorted" column in our project here https://github.com/Automattic/stories-android/projects/1#column-6852115 👍 

Edit: (for the record, it was already added, but for some reason GH doesn't add that event to the issue's activity timeline 🤷‍♂️ )

**Comment by aforcier** [comment]
Just wanted to underline some of the hidden complexity here:

The other blocks mentioned all open a bottom sheet with media selection options. The story case is different in that media are sourced from a universal media picker, which allows e.g. sourcing images and videos at the same time.

Launching the bottom sheet instead to be consistent with other blocks would limit the sources available, and would also present a different experience from the main flow for creating a story (via the create sheet).

Alternatively, adding the story block could immediately launch the media picker (and not require a tap on 'add media'); however that's opening an entirely new view vs just a bottom sheet, and may be a confusing experience for the user (and would still behave differently from what happens for other media blocks). I would say we would want some additional design consideration before going this route.

It's also worth noting that story creation via the block picker is a fairly rare flow compared to the direct one from the create sheet.

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
