### ISSUE TITLE
Improve Server Credentials Clarity

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#14666]
We got feedback that it was easy to miss the line about server credentials, and it was not clear it was actionable.

I cannot reproduce the current version on Android to verify the current appearance, but here's the new design with hopefully minor tweaks. 

- Again I couldn't find an example of a disabled button currently in the app to use. But if we have a disabled state already let's use it. I just took the generic guidelines from https://material.io/components/buttons#contained-button
- Action next to the relevant button
- Plus icon to make it clear there is an action here, and consistent with Calypso
- Using normal text colour, but with an interactive green part highlighted

![server credentials android](https://user-images.githubusercontent.com/50576199/118520216-ca491600-b731-11eb-9d09-32918b4a438a.png)

**Comment by ashiagr** [comment]
Closed via #14722 &  #14772.
