### ISSUE TITLE
Post List: Refresh always prompts about local changes

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#147]
~~If there is a local draft in the post list, refreshing the post list prompts the user that refreshing will overwrite local changes.  This always happens, even when there are no changes since the last refresh.~~

Edit: 
Edited vs creating a new issue.  This is always happening when refreshing the post list on any of my test blogs regardless of if there are local drafts in the list or not. 

Nexus 7, 2.5 beta 3.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
