### ISSUE TITLE
Reader/Stories - Viewing a Story post in the Reader showed partially loaded image

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Android#14726]
I published a new post on my WordPress.com site with my Pixel 2 XL. I let the post publish and waited for the snackbar to disappear. I went over to reader, pulled to refresh and saw the new story post. When I tapped on the post the story image didn’t seem to load completely. I was able to tap that little section and it launched out to a web browser to view the story. I came back to the app, returned to the reader list, then back to the story post and then the image fully loaded.

### Expected behavior

When viewing a new Reader post containing a WPStory object, the preview should show a static image of the story.

### Actual behavior

Upon initial view moments after creating the story and it appearing in Reader, the image did not fully load.

<img width="687" alt="2021-05-26_07-45-35" src="https://user-images.githubusercontent.com/373903/119661899-64762180-bdf6-11eb-85d8-78a103da6cf2.png">

### Steps to reproduce the behavior

1. Make sure you're subscribed to your site in Reader first before performing the next steps.
2. Publish a new story on a WordPress.com site.
2. Let the post publish and wait for the snackbar to disappear.
3. In Reader, pull to refresh to show the newly published post.
4. Tap on the post to view more details of it.
5. Notice the static image doesn't fully load. It is still tappable and it launches to a web browser to view.

**Comment by thehenrybyrd** [comment]
I'm no longer able to reproduce this on Samsung Galaxy S21, Android 12, WP Android 20.3-rc-1. The story image loads fully when I first view the post from Reader.
Closing for now, please re-open as necessary.
