### ISSUE TITLE
Schedule Misses on Scheduled Posts

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14732]
### Expected behavior
When a user is scheduling a post to be published in the future, through `Publish Date` and `SCHEDULE NOW` bottom sheet action button, on that specified date and time the scheduled post gets published.

Afterward, the scheduled post moves from the `SCHEDULED` tab and into the `PUBLISHED` tab.

### Actual behavior
When a user is scheduling a post to be published in the future, through `Publish Date` and `SCHEDULE NOW` bottom sheet action button, on that specified date and time, on some occasions, pretty much randomly, the scheduled post misses its schedule.

![image](https://user-images.githubusercontent.com/9729923/119788560-e93a6b80-beda-11eb-94b0-a931f5b72b5e.png)

As such, the scheduled post ends up sitting within the `SCHEDULED` tab indefinitely and until it is being manually published or rescheduled again.

### Steps to reproduce the behavior
1. Open the app, while on the main `My Site` tab, find the `Blog Posts` item under the `Publish` section and click on it.
2. Add a new `Blog post` using the `FAB` button, add a title and some content, then click the `PUBLISH` toolbar button.
3. A bottom sheet will open and the action button will be set to `PUBLISH NOW` with a `Publish Date` set to `Immediately`.
4. Find the `Publish Date` and change the `Date and Time` to a future time, like 15' mins ahead. Now go back.
5. The action button should be set to `SCHEDULE NOW` with a `Publish Date` set to some like `Schedule for: May 27, 2021, 11:30 AM`. Now click `SCHEDULE NOW`.
6. Check the `SCHEDULED` tab and verify that your newly scheduled post is available within that list.
7. Check the web and verify that your newly scheduled post is also available within the `Posts` list. Its status should be `Scheduled`, presented on the `Date` column.
8. Wait until that specified date and time is reached and check on the scheduled post status.
9. It will either be `Scheduled` if everything works as expected, or `Missed schedule` otherwise.

##### Tested on [device], Android [version], WPAndroid [version]
Tested on [Pixel 4], Android [12], WPAndroid [17.4-rc-3]

**Comment by LauraSWP** [comment]
User had this issue here 29715043-hc Their scheduled posts are not publishing when they should so they have to do it manually.

**Comment by ovitrif** [comment]
One reason why this happens for new sites is explained here:
https://github.com/wordpress-mobile/WordPress-iOS/issues/10456

**Summary**
> The post's status stays as Scheduled even after a REST API request. Only when a particular site is visited on the web (logged out or in Calypso), the scheduled publish is triggered. After this the post's status is correctly loaded as Published in the app, as well.

I could reproduce it also on the WP-android app.

**Comment by antonis** [comment]
Searching on how the scheduled posts work I found the [following notice on the documentation](https://wordpress.com/support/schedule-a-post-or-page/):

> Scheduled posts will be triggered by the first visit to your blog on or after the exact date/time you set. If you see that the scheduled time has come and gone and your post or page has not published, log out of WordPress.com and view your blog’s front page. Your visit should cause the post or page to appear.

I believe that this indicates the the client app works as expected. A fix would require a change on how the server works and I'm closing this issue.
