### ISSUE TITLE
Reader settings: Following icon color

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#14796]
### Expected behavior
Following(unfollow) icon has the same tint/color on tags and sites tab.

### Actual behavior
The color of "following(unfollow)" icon is slighly different between tags and sites tabs.

### Steps to reproduce the behavior
1. Open the app
2. Select Reader tab
3. Tap on the gear icon in the top left corner
4. Notice the color of "following(unfollow)" icon
5. Tap on "Sites" tab and notice the icon color is slighly different

| Tags | Sites |
|---|---|
| ![Screenshot_1623095627](https://user-images.githubusercontent.com/2261188/121080177-b593f700-c7a0-11eb-9a64-9d9479435b50.png) | ![Screenshot_1623095626](https://user-images.githubusercontent.com/2261188/121080152-ae6ce900-c7a0-11eb-9952-a96239dc1948.png) |

##### Tested on [device], Android [version], WPAndroid [version]
Emulator

**Comment by danielmbutler** [comment]
Can I grab this one :) ?

**Comment by gorvk** [comment]
Hey @malinajirka , 

I just made a PR #14849 for this issues. 

Here are the changes - 

![After](https://user-images.githubusercontent.com/52004037/122192142-fed6fb80-ceb0-11eb-9473-44d87e524d3b.jpg)

**Comment by malinajirka** [comment]
Thank you @Gstar1525 for fixing the issue and thank you @danielmbutler for your willingness to work on it ;)! It's much appreciated!
