### ISSUE TITLE
When signing in with an email link, the check email button does not work as expected.

### ISSUE THREAD

**Issue by KirkwallDay** [wordpress-mobile/WordPress-Android#14820]
### Expected behavior
![Screenshot_20210610-135604_Jetpack](https://user-images.githubusercontent.com/49131029/121588933-bbcde180-c9f3-11eb-9d3f-e687ff040897.jpg)

Using the "Check email" button in the login flow should open my email in Gmail to get the email link.

### Actual behavior

The app attempts to open Samsung mail and asks me to set up my email for that app. Once I do, the link will open up there.

### Steps to reproduce the behavior

Open the Jetpack App
Enter an email address and continue
Choose "Get login link by email"
Choose "Check Email"

**Comment by antonis** [comment]
This should be solved in `19.4` with https://github.com/wordpress-mobile/WordPress-Android/pull/15979
