### ISSUE TITLE
Stories Pre-publish BottomSheet Cut off on some devices

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/WordPress-Android#14821]
### Expected behavior
The Pre publish Bottom Sheet for stories should not cut off top text input field

### Actual behavior
On Pixel 2 API 29, stories pre-publish bottom sheet has top text field input cut off.

### Steps to reproduce the behavior 
*See devices tested below, only reproducible on Emulator Pixel 2 so far*
1. Create a new story in WPAndroid
2. Click publish
3. Notice that the bottom sheet that opens has its top text input field cut off from the screen, and stays that way as you drag the Bottom Sheet

### Screenshot
![Jun-10-2021 14-39-09](https://user-images.githubusercontent.com/1103838/121598328-92628500-c9f6-11eb-9669-08e77c607c0d.gif)

##### Tested on Emulator Pixel 2, Android 29, WPAndroid develop, d34b2f6aafded9f9a8b5bee698c633ad2a06cc17 (Thu Jun 10)

I tested this on a few devices (latest develop):
Galaxy S10 API 30 => could not reproduce
Emulator Pixel 4, API 29 => could not reproduce
Emulator Pixel 2, API 29 => Reproduced, same as GIF, top text input is cut off
Emulator Pixel 2, API 30 => Reproduced, same as GIF

**Comment by cameronvoell** [comment]
Possibly related to https://github.com/Automattic/stories-android/issues/475

**Comment by thehenrybyrd** [comment]
I wasn't able to reproduce the issue fully on my Samsung Galaxy S21, Android 11, WPAndroid 17.5-rc-1. 
However, the top text input field does feel somewhat cramped for space at the top:
<img src="https://user-images.githubusercontent.com/15107387/121666365-d49ccc80-cab1-11eb-9762-0895208cb3d7.jpg" width="40%">

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
