### ISSUE TITLE
Quick Start padding has a background colour in dark mode

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#14839]
### Expected behavior
In Quick start, The dialog prompt should float above the UI

### Actual behavior
The dialog prompt is positioned correctly. But in dark mode, rather than the padding around it being empty, it has a black colour fill.

### Steps to reproduce the behavior
- change to dark mode
- make a new site
- accept quick start
- complete a task
- see the auto prompts have a dead space around them

![image](https://user-images.githubusercontent.com/50576199/122027078-b3462400-cdc2-11eb-96c1-c5e464876423.png)

**Comment by ashiagr** [comment]
Closed via #15611
