### ISSUE TITLE
No loading indication in reader content

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#14840]
### Expected behavior
When the content is loading, show a loading indication

### Actual behavior
When the post content is slow to load, there's no indication its loading. 

### Steps to reproduce the behavior
- Go to reader
- find a post with lots of content, or be on a slow connection
- see that the page lazy loads (which is good)
- you see the title etc initially
- the page content is not yet loaded, but there's no indication something is happening
- as a user, I would think this post is blank. Or maybe something broke. 

| <img width="314" src="https://user-images.githubusercontent.com/4588074/195057838-22e04acb-6504-45d6-a212-5fc0e35437d4.png"> |
| - |

**Comment by itsnitish22** [comment]
Hey @osullivanchris. I would like to work on this issue. Can you assign this to me? I can add a progress bar and make it visible until the body arrives. In this way a user would know that the data is loading.

**Comment by lonewolf2208** [comment]
Hey @osullivanchris . I am new to open source and I would like to work on this issue.

**Comment by thomashorta** [comment]
Hey 👋 

I opened a PR for this issue which I believe should fix the behavior explained in the issue, by showing a loading indicator for the Reader content. #17356

**Comment by Stanzin7** [comment]
is this issue resolved ?

**Comment by thomashorta** [comment]
> is this issue resolved ?

The PR was open for a while but was not merged. I just reopened it and asked for review so it might be merged soon.
https://github.com/wordpress-mobile/WordPress-Android/pull/18758
