### ISSUE TITLE
Reader: you can swipe between tabs even when they are off screen

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#14841]
### Expected behavior
didn't expect to sideways swipe and end up in a different stream

### Actual behavior
swiped while down the feed and ended up on a different stream

### Steps to reproduce the behavior
- go to reader
- notice that you can swipe between the top tabs (following, discover, etc)
- scroll through any stream (following, discover, etc)
- notice that as you scroll, the tabs for following, discover, etc move off screen
- swipe left are right
- you move streams. its now unclear where you are
- suggested solution: either keep the tabs sticky so its clear what you are swiping. or disable swiping.

its also possible this is standard android behaviour and maybe not our issue. Open to feedback.

**Comment by daniloercoli** [comment]
Moved to a new design in 22.4 that doesn't have tabs. We can close this issue now.
