### ISSUE TITLE
Wrong background colour reader empty state

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#14842]
### Expected behavior
the empty state should have the same background colour as any page

### Actual behavior
in dark mode the reader empty state has a non standard background colour with a blue tint

### Steps to reproduce the behavior
- turn on dark mode
- go to reader
- find a tab where you have no content
- see empty state
- check background colour is not the standard one we use, and has a blue tint

<img width="973" alt="Screenshot 2021-06-15 at 10 25 38" src="https://user-images.githubusercontent.com/50576199/122028791-459af780-cdc4-11eb-9361-6590946764e7.png">

**Comment by danmaze** [comment]
I'd like to take on this issue.

**Comment by ashiagr** [comment]
👋 @danmaze 

Thanks for your interest in this issue! I've assigned it to you.

Let me know if you have any questions regarding [Project Setup](https://github.com/wordpress-mobile/WordPress-Android#wordpress-for-android) or the [Contributing Guide](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md).

**Comment by danmaze** [comment]
@ashiagr I've submitted a PR.

**Comment by mokagio** [comment]
The PR @danmaze like is closed, but the change they made landed in `develop` via https://github.com/wordpress-mobile/WordPress-Android/pull/15307. Thank you @danmaze!

@osullivanchris, when you have a minute, it would be great if you could verify if the screen renders as desired. 🙇‍♂️

**Comment by osullivanchris** [comment]
Looks correct to me! Thanks @mokagio @danmaze

**Comment by mokagio** [comment]
Excellent! Thank you for confirming @osullivanchris 🙌
