### ISSUE TITLE
Unable to edit text on previously published story post

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#14857]
On a Story Post which has been created, published, and edited already, editing the story again in the same session can cause issues. Initially reported in iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/16697

### Expected behavior
The user would expect they could edit the text on the image of a story post.

### Actual behavior
The text on the image of the story post wasn't selectable for edit.
A "Limited Story Editing" message was shown.

### Steps to reproduce the behavior

1. Create a new story post with an image and some text on it.
2. Publish the story post.
3. Edit the story post again. At this point, we may be able to edit the text.
4. Make some changes to the text or add another image to the story post with text.
5. Tap the checkmark icon to save the change. Don't close the post editor though.
6. Tap to edit the story post again. 
Note the "Limited Story Editing" message, which claims this story was created on another device.
Notice that the text on the first image is not able to be selected for edit.

In my case, text on the second and third images were still editable, but not on the first.

##### Samsung Galaxy S21, Android 11, WPAndroid 17.6-rc-1

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
