### ISSUE TITLE
Notification: Make sure to load the whole notification content for self-hosted site from PN

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#1486]
A user reported an issue where he can't open the notification details screen from the notification center when tapping on the comment notification row.

I bet the app doesn't refresh the notification content in background when receiving a PN object with the comment_id absent in the payload. 
The notification details screen requires both the blog_id, and the comment_id, to retrieve the actual notification data. 

Ref: http://android.forums.wordpress.org/topic/cant-read-comments-from-notifications-screen

**Comment by roundhill** [comment]
The Simperium switch took care of this.
