### ISSUE TITLE
Blogging Reminders Announcement Editorial Review

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#14937]
We are introducing a feature in the WordPress apps where a user can select the days of the week they want to blog, and we will send them a push notification. The flow is shown at the bottom. 

We have a feature announcement tool to tell users about new features. We want to make this as clear and compelling as we can.

Current copy
Heading1: Blogging Reminders
Body1: Get notifications to keep you on track.

Heading2: Set your schedule
Body2: Choose the days you want to blog on.

![WhatsNewBloggingReminders](https://user-images.githubusercontent.com/50576199/123395585-45ef7b80-d598-11eb-887a-a05ff0673646.png)

Here is the flow. Its already built. If anything stands out from a copy perspective input is definitely welcome there too and we can update in the next release.
<img width="3764" alt="blogging reminders flow" src="https://user-images.githubusercontent.com/50576199/123398209-2a39a480-d59b-11eb-9fe4-50e4c1f4b803.png">

**Comment by cavalierlife** [comment]
“Choose the days you want to blog on” is a little awkward. What about “Choose the days you prefer to blog”?
