### ISSUE TITLE
Jetpack: Hide Restore Option for Unavailable Rewind State

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14945]
iOS Issue: [WordPress-iOS#16754](https://github.com/wordpress-mobile/WordPress-iOS/issues/16754)

If a site is a multisite, the rewind endpoint returns `unavailable` for the rewind state, see:

GET: `https://public-api.wordpress.com/wpcom/v2/sites/SITE_ID/rewind`
RESPONSE:
```
{
    "state": "unavailable",
    "threats": null,
    "has_cloud": false,
    "reason": "multisite_not_supported"
}
```

Currently, we are not doing anything for this `unavailable` state, we continue displaying the restore option, see below:

<img src="https://user-images.githubusercontent.com/9729923/123427520-65ed6200-d5cd-11eb-9bed-26aca5e155e0.png" width="250" height="500">

We should consider displaying the same view we show in `Calypso` and hide, or at least disable, the restore option, see below:

![Jetpack App - Display Restore Not Available for Unavailable Rewind State (Calypso)](https://user-images.githubusercontent.com/9729923/123427269-160e9b00-d5cd-11eb-831b-5c44c073d1b4.png)

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

@leandroalonso asked [this question](https://github.com/wordpress-mobile/WordPress-iOS/issues/16754#issuecomment-870006785) about solving the same on iOS. I find this solution great, but on Android we don't have the same component or flow. So, my question is, what should we be doing for Android instead?

I have the below suggestions:
1) Hide the `Restore to this point` option completely, or
2) Disable the `Restore to this point` option instead, else
3) Disable the `Restore to this point` option, but make it clickable so that when the user tries to click on it they will get a dialog explaining to them about the `Jetpack Backup for Multisite installations provides downloadable backups, no one-click restores.`.

Your thoughts?

**Comment by osullivanchris** [comment]
👋  Hey thanks for raising here as well @ParaskP7 

I suggest we go with option 1, hide it in this overflow menu.

But, on the event details view, we can offer a disabled button with some explanation so the user gets more info.

I can mock it up later/tomorrow but I think that approach could work. I mentioned the event detail view on the iOS issue also.

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

Thanks for getting on this so quickly!

> I suggest we go with option 1, hide it in this overflow menu.

I agree! 🙏 

> But, on the event details view, we can offer a disabled button with some explanation so the user gets more info.

This is very true, we need to handle the `Event Details View` as well. 🌟 

> I can mock it up later/tomorrow but I think that approach could work. I mentioned the event detail view on the iOS issue also.

Great, thank you so much, I will be also following the iOS issue closely! 🙏

**Comment by osullivanchris** [comment]
Suggest hiding it on the dropdown shortcut. On event details, show disabled button with text explanation and link (similar to server credentials.) 

noting on iOS @leandroalonso  [went without disabled button](https://github.com/wordpress-mobile/WordPress-iOS/issues/16754#issuecomment-872453938). So that is fine too if we wanna stick with that.

<img width="932" alt="Screenshot 2021-07-02 at 00 43 48" src="https://user-images.githubusercontent.com/50576199/124200958-91d97d80-dace-11eb-9c7a-ee041e0d0a43.png">

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> Suggest hiding it on the dropdown shortcut.

👍 

> On event details, show disabled button with text explanation and link (similar to server credentials.)

🤔 

> noting on iOS @leandroalonso went without disabled button. So that is fine too if we wanna stick with that.

I am actually in favor of what @leandroalonso did on the iOS side for the below reasons:
1) Not having to reorder the `RESTORE` and `DOWNLOAD BACKUP` buttons for multisite, then making the `RESTORE` disabled and enhancing the list items with addition information, will make the whole solution much more complicated.
2) Not showing the `RESTORE` at all, instead of having it disable, makes it consistent with not showing the `Restore to this point` menu option on the events list screen.
3) On the web, the `RESTORE` button is also not shown, thus not showing it on mobile will make it more consistent with the web.
4) Showing just this extra information at the bottom of the event details screen makes the whole solution more straightforward and since this event details screen is to be "potentially" redesigned in the future, I would go with the simpler solution for now and maybe update it later on with the new UI.

Wdyt?

**Comment by osullivanchris** [comment]
@ParaskP7 yeah that all sounds good to me! I didn't feel strongly. 

1. Yeah didn't need to be flipped. Was just an idea, to have the enabled action first. I left them in the normal order in the iOS mock. So I was open to both.
2. Do you mean the overflow item? I figured that's a shortcut, so it was easier to drop it there than have to explain it. 
3. 👍 
4. 👍 

Either way I think there is little value difference between the two options, so your points 3 and 4 swing it in favour of doing what iOS is doing. I don't want us investing too much time here.

Here is how I'm assuming things will then look on Android.

<img width="897" alt="Screenshot 2021-07-02 at 11 03 44" src="https://user-images.githubusercontent.com/50576199/124258322-2cfd4200-db25-11eb-8acd-aa9abc76761f.png">

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> @ParaskP7 yeah that all sounds good to me! I didn't feel strongly.

Me neither, although it did seem so, I just wanted to avoid doing too much work for now... 😅  Thanks lot! 🙇 

1. True, the idea to have the enabled action first is very reasonable, didn't think about it.
2. Yes and yes you are right that this is a shortcut and easier to drop it there than have to explain it.
3. 👍
4. 👍

> Either way I think there is little value difference between the two options, so your points 3 and 4 swing it in favour of doing what iOS is doing. I don't want us investing too much time here.

Many thanks, will progress with the simplest solution to avoid investing too much time here. 👍 

> Here is how I'm assuming things will then look on Android.

Looking good, I am on it! 🙏 🚀
