### ISSUE TITLE
Jetpack: Display Error Screen for Disabled Stats Module

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14942]
iOS Issue: [WordPress-iOS#16753](https://github.com/wordpress-mobile/WordPress-iOS/issues/16753)

Currently, we don’t indicate to the user that the `Stats` module is disabled. Instead, we display a generic loading error, see below:

<img src="https://user-images.githubusercontent.com/9729923/123419909-7b5d8e80-d5c3-11eb-9c08-7b60f50113b0.png" width="250" height="500">

We should consider displaying the same error screen we show in `Calypso`, see below:

![Jetpack App - Show Error Screen for Disabled Stats Module (Calypso)](https://user-images.githubusercontent.com/9729923/123419363-d0e56b80-d5c2-11eb-89b2-015ef440e28f.png)

**Comment by osullivanchris** [comment]
Thought we could just use web content with our existing empty state style.

Image optional. Button only if action is possible, obviously!

<img width="528" alt="Screenshot 2021-07-02 at 00 42 21" src="https://user-images.githubusercontent.com/50576199/124200887-5dfe5800-dace-11eb-8029-bbab85773bfd.png">

**Comment by momo-ozawa** [comment]
@zwarm @ParaskP7 
Posting here to sync w Android...On the iOS PR I am using wp-illustration-stats for the image.
Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/16822#issuecomment-875741302

**Comment by ParaskP7** [comment]
Thanks so much for syncing with Android @momo-ozawa , you rock! ❤️

**Comment by zwarm** [comment]
@osullivanchris - iOS is not showing the stats tabs in their view which makes it so much easier to handle error conditions and prevent all sorts of edge cases. FYI: I will be doing the same - not showing the tabs.

**Comment by leandroalonso** [comment]
FYI: in iOS, we hit a problem that ended up disabling Stats for all WP.com sites. 😬 (more here: https://github.com/wordpress-mobile/WordPress-iOS/pull/16849)

The logic change can be seen here: https://github.com/wordpress-mobile/WordPress-iOS/pull/16849/files#diff-0ccea120cbd4cf44b5d3b55d59b899fd5e51e814f685f0fed994768fb198c600R623

Perhaps y'all want to implement it another way, but just make sure to test in different site types (P2, Atomic, WP.com, hosted outside WP.com with Jetpack) so we prevent making the same mistake on the Android side.

**Comment by osullivanchris** [comment]
@zwarm sounds good!

**Comment by zwarm** [comment]
Two more q's for you @osullivanchris.

(1) iOS appears to be showing a Lottie animation which we don't have (or I can't locate it). I'll just be showing a small progress spinner like we do for jetpack install unless you want to provide the lottie animation.

(2) If the enable stats module fails are we (a) Showing an Error View or  (b) The original Disable view with a snack bar message?  I think an error view with a "retry" button would be overkill, just want to get your thoughts. 

Thanks.

**Comment by osullivanchris** [comment]
> (1) iOS appears to be showing a Lottie animation which we don't have (or I can't locate it). I'll just be showing a small progress spinner like we do for jetpack install unless you want to provide the lottie animation.

That's totally fine. A progress spinner is good.

> (2) If the enable stats module fails are we (a) Showing an Error View or (b) The original Disable view with a snack bar message? I think an error view with a "retry" button would be overkill, just want to get your thoughts.

I agree with your thinking. A snackbar on this view would make sense to me as long as its not too heavy to implement. Going to another full screen error might have the user feeling a little lost.

**Comment by osullivanchris** [comment]
@zwarm PS the stats empty image that Momo used would be good here too! I didn't know we had one at the time I mocked with the icon.

**Comment by zwarm** [comment]
> @zwarm PS the stats empty image that Momo used would be good here too! I didn't know we had one at the time I mocked with the icon.

Yes, I am showing the same one. :)

**Comment by zwarm** [comment]
@osullivanchris - I utilized the existing empty view layout. 
https://user-images.githubusercontent.com/506707/125813839-859a0ac0-2c61-431f-bc90-b790b6e19b27.mov

**Comment by osullivanchris** [comment]
@zwarm looks great! 🙌  not sure if you are able to show me the fail version, or if you have it yet.

**Comment by zwarm** [comment]
<img width="528" alt="Screenshot 2021-07-02 at 00 42 21" src="https://user-images.githubusercontent.com/506707/125819926-71b0af4d-a961-4511-a08b-8ac72e59c90c.png">
All error views use this pattern. Stay on disable view with a snackbar.

**Comment by osullivanchris** [comment]
LGTM!
