### ISSUE TITLE
Jetpack: Display Scan Not Available Screen for Unavailable Scan State

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14946]
iOS Issue: [WordPress-iOS#16755](https://github.com/wordpress-mobile/WordPress-iOS/issues/16755)

If a site is a multisite, the scan endpoint returns `unavailable` for the scan state.

GET: `https://public-api.wordpress.com/wpcom/v2/sites/SITE_ID/scan`
RESPONSE:
```
{
    "state": "unavailable",
    "threats": null,
    "has_cloud": false,
    "reason": "multisite_not_supported"
}
```

Currently we are not doing any anything for this `unavailable` the state, we display a generic error, see below:

<img src="https://user-images.githubusercontent.com/9729923/123430158-84a12800-d5d0-11eb-8664-0f4907388306.png" width="250" height="500">

We should consider displaying the same view we show in `Calypso`, see below:

![Jetpack - Display Scan Not Available Screen for Unavailable Scan State (Calypso)](https://user-images.githubusercontent.com/9729923/123429812-12c8de80-d5d0-11eb-8752-047fdd82195e.png)

**Comment by osullivanchris** [comment]
As with the stats error, I thought we could just use the web content with our standard empty state style.

<img width="430" alt="Screenshot 2021-07-02 at 00 45 54" src="https://user-images.githubusercontent.com/50576199/124201047-dcf39080-dace-11eb-8de3-d7d6fc590d41.png">

**Comment by momo-ozawa** [comment]
@ParaskP7
Posting here to sync w Android...I'm using the scan error icon for the image.
Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/16817#issuecomment-875496160

**Comment by ParaskP7** [comment]
Thanks so much for syncing with Android @momo-ozawa , you rock! ❤️
