### ISSUE TITLE
Custom Forms: Select File upload button doesn't initiate in Preview

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-Android#14967]
When using custom form plugins like CF7, you have the ability to add file/attachment upload fields. However, when you preview the page, tapping the file upload field doesn't do anything.

All the other tested fields (text, email, textarea, etc) works.

### Expected behavior
To have a functional form when I tap Preview, even if the block is not supported in the editor, like we see in the iOS app:

<img src="https://user-images.githubusercontent.com/1136160/123984778-4a9ea000-d99b-11eb-9713-8db859b41250.png" width="400"/>

### Actual behavior
* When tapping the file field in Preview mode, nothing happens.
* The file field works without issues when you visit the page from a browser

### Steps to reproduce the behavior
1. Install a custom plugin like CF7: https://wordpress.org/plugins/contact-form-7/
2. Edit the default form and make sure you add a [file upload field](https://contactform7.com/file-uploading-and-attachment/)
3. Add the CF7 block to a post or page
4. Tap the 3-dots, then "Preview"

##### User report: 4101931-zen

**Comment by thehenrybyrd** [comment]
Thanks for reporting @eduardozulian! 
One question - does the tapping the upload field do nothing only in Preview? 
Or does it also fail when you publish the post and visit it in a web browser?

**Comment by eduardozulian** [comment]
> One question - does the tapping the upload field do nothing only in Preview?
Or does it also fail when you publish the post and visit it in a web browser?

It only fails when you tap from the Preview!

I edited the "Actual behavior" section with this info. :)

**Comment by hypest** [comment]
Replicated the issue and happens in the Preview modal, even outside of the native block editor. I will remove the `gutenberg-mobile` label as it's not related to the native block editor and add it to Groundskeeping.

**Comment by SiobhyB** [comment]
I started looking into this issue but didn't complete it this week. Adding my notes in case they're of use for the next Groundskeeper. :)

* I believe a fix will require changes in [WPWebViewActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java).
* Googling variations of `webview` and `file chooser` brings up a number of StackOverflow threads with suggestions for fixing this known "missing piece" from Android's WebView. For example: https://stackoverflow.com/questions/51704560/android-file-chooser-not-calling-from-android-webview
* The majority of suggestions I saw involved usage of the `startActivityForResult` method, however, this method is now deprecated. The solutions could likely be refactored using more modern methods from the activity class: https://developer.android.com/training/basics/intents/result

**Comment by jd-alexander** [comment]
> I started looking into this issue but didn't complete it this week. Adding my notes in case they're of use for the next Groundskeeper. :)
> 
> * I believe a fix will require changes in [WPWebViewActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java).
> * Googling variations of `webview` and `file chooser` brings up a number of StackOverflow threads with suggestions for fixing this known "missing piece" from Android's WebView. For example: https://stackoverflow.com/questions/51704560/android-file-chooser-not-calling-from-android-webview
> * The majority of suggestions I saw involved usage of the `startActivityForResult` method, however, this method is now deprecated. The solutions could likely be refactored using more modern methods from the activity class: https://developer.android.com/training/basics/intents/result

Thanks for sharing these notes @SiobhyB they were helpful in crafting the solution I created. 🙇🏾
