### ISSUE TITLE
Reader: Media preview controls difficult to see and toggle

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-Android#14964]
### Expected behavior
While viewing media full screen in the Reader, the controls (e.g. back button) have enough contrast with the background to be visible and tapping anywhere outside of a control toggles the visibility of controls (e.g. "X of Y" label). 

### Actual behavior
While viewing media full screen in the Reader, the controls (e.g. back button) do not have enough contrast with the background are sometimes invisible and tapping on the media itself causes some controls (e.g. "X of Y" label) visibility to toggle sporadically and never remain visible. 

### Steps to reproduce the behavior
1. Launch the WPAndroid app. 
2. Visit a post with image media in the Reader. 
3. Tap the image media to view it fullscreen. 
4. ⚠️ The back button is invisible atop the black background. 
5. Tap the image while in fullscreen. 
6. ⚠️ The "X of Y" label sporadically toggles visibility, but never remains visible. 

##### Tested on Samsung Galaxy S20, Android 11, WPAndroid 17.6-rc-1. 

<details><summary>Screenshot</summary>

![reader-media-controls](https://user-images.githubusercontent.com/438664/123824205-72223980-d8c3-11eb-8547-9c937e7019d8.jpg)

</details>

<details><summary>Video</summary>

https://user-images.githubusercontent.com/438664/123824228-78181a80-d8c3-11eb-8e32-535bbba896ca.mp4

</details>

**Comment by vicky-tech** [comment]
can i pick this issue?

**Comment by twstokes** [comment]
👋 This also occurred for me within the block editor when tapping a GIF (and probably other media types).

1. Add an animated GIF with the image block
2. Tap the GIF to view it fullscreen
3. ⚠️ The "Back" arrow at the top left is black on a black background

**WPAndroid 19.5 / Pixel 4a / Android 12**

https://user-images.githubusercontent.com/2092798/160135672-23f60a7f-2a17-4034-ac3f-7f151f359411.mp4
