### ISSUE TITLE
Self-hosted site connected with WP admin credential lacks Blogging Reminders settings option

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-Android#14981]
### Expected behavior
After publishing a post for a self-hosed site connected via WP admin credentials, I am prompted to set Blogging Reminders and can modify that configuration within the Settings screen (OR I am neither prompted and able to modify the configuration within the Settings screen).

### Actual behavior
After publishing a post for a self-hosed site connected via WP admin credentials, I am prompted to set Blogging Reminders and _cannot_ modify that configuration within the Settings screen. 

### Steps to reproduce the behavior
1. Install and launch WPAndroid. 
2. Connect a self-hosted site via WP admin credentials, i.e. do not rely upon Jetpack. 
3. Publish a post. 
4. Set Blogging Reminders within the prompt displayed after the post is published. 
5. ⚠️ Navigate to the site Settings screen and observe there is no way to modify the Blogging Reminders configuration. 

##### Tested on Samsung Galaxy S20, Android 11, WPAndroid 17.7-rc-2. 

https://user-images.githubusercontent.com/438664/124280373-38913e80-db0e-11eb-9adc-318ab46209c5.mp4

**Comment by renanferrari** [comment]
@dcalhoun Thanks for reporting this! I can confirm I was able to reproduce the issue.

**Comment by renanferrari** [comment]
Closed by #14986.
