### ISSUE TITLE
Jetpack App: “Rate now” prompt points to WordPress app

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#14996]
Ref: pcdRpT-p7-p2#comment-544

### Expected behavior
“Rate now” prompt for Jetpack Android app should point to the **Jetpack** app

### Actual behavior
“Rate now” prompt for Jetpack Android app points to the **WordPress** app

### Steps to reproduce the behavior
“Rate now” prompt is shown when [these specific criteria](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/AppRatingDialog.kt#L29-L34) are met.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

As opposed to the iOS equivalent issue (see [WordPress-iOS#16808](https://github.com/wordpress-mobile/WordPress-iOS/issues/16808)), on Android we are using it dynamically and pointing to the correct PlayStore link base on the app's `packageName` (see [AppRatingDialog. setPositiveButton(...)](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/AppRatingDialog.kt#L126-L144)), As such:
- For `WordPress` we point to: https://play.google.com/store/apps/details?id=org.wordpress.android
- For `Jetpack` we point to: https://play.google.com/store/apps/details?id=com.jetpack.android

As such, there is no problem in Android and this issue can be effectively closed. All that were also tested and verified.
