### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.pages.Pages...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15015]
**Sentry Url**: https://sentry.io/share/issue/b029d48de6724ab8b55530db00041c58/
**User Count**: 1497
**Count**: 2664
**First Release**: org.wordpress.android@17.0-rc-2+1021
**First Seen**: 2021-03-26T14:55:04.147000Z
**Last Seen**: 2021-07-12T09:30:27Z
**24 Hours**: 22
**30 Days**: 846

```
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.pages.PagesActivity}: kotlin.UninitializedPropertyAccessException: lateinit property viewModel has not been initialized
     at org.wordpress.android.ui.pages.PagesFragment.onSpecificPageRequested(PagesFragment.kt:169)
     at org.wordpress.android.ui.pages.PagesActivity.handleIntent(PagesActivity.kt:49)
     at org.wordpress.android.ui.pages.PagesActivity.onCreate(PagesActivity.kt:30)
...
(8 additional frame(s) were not displayed)
```

**Comment by SiobhyB** [comment]
I haven't been able to reproduce, but there were some changes to [the PagesActivity file](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt) on March 11th that seem like they could coincide with this crash. Those changes were introduced in https://github.com/wordpress-mobile/WordPress-Android/commit/f53ac824bf706a0d232c76eb4f36e4376cadf19a.

@planarvoid, would you be able to take a look to see if those changes could be causing the crash here?  

I'm labelling this as a `Medium` priority as, although we don't yet have steps to reproduce, any crash around the page screens would disrupt an important flow and the user count is significant, though not so high that I think this warrants a `High` priority yet.

**Comment by SiobhyB** [comment]
@renanferrari, 👋 , I see Vojta's no longer on the project and wondered if you might be able to take a look into whether the changes in https://github.com/wordpress-mobile/WordPress-Android/pull/14238 could be contributing to this crash? I see you helped review them originally.

**Comment by renanferrari** [comment]
@SiobhyB Thanks for the ping! I was able to reproduce the issue after a few tries, and I agree that the changes in #14238 are the likely culprit here. 

**Explanation:**

When the Pages screen is opened from the notification shown after a successful page upload, we call the `PagesFragment::onSpecificPageRequested` method, which then calls the `ViewModel` before it has been initialized. The `ViewModel` initialization logic was moved as part of the changes introduced by #14238.

**Here's a video of the crash:**

https://user-images.githubusercontent.com/830056/126825594-9148dd90-5710-425a-871c-f79bc2fd1326.mp4


**Steps to reproduce:**

1. Open the app.
1. On the My Site screen, tap "Pages".
1. On the Pages screen, tap the FAB.
1. Select a layout for the page and tap "Create Page".
1. On the Editor, wait until the page is loaded and tap "Publish".
1. On the bottom sheet, tap "Publish now".
1. Press back until you have exited the app. (In my experience, this has to be done really quickly!)
1. Notice a notification indicating the page upload status.
1. Notice a second notification indicating the page was uploaded successfully.
1. Tap the notification.
1. Notice the crash.

Note: If you don't see the second notification, try exiting the app faster. It won't show up if the app is in the foreground.

**Next steps:**

Unless something else comes up on my side, I should be able to submit a PR with a fix later today.
