### ISSUE TITLE
Creating a page with a template is very slow on certain devices

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15025]
### Expected behavior
When creating a new page with template the editor starts normally

### Actual behavior
Creating a page with a template is very slow on certain devices.
At this point the problem has been observed on Pixel devices but it may be more wide spread.

https://user-images.githubusercontent.com/304044/125572120-5f0aa36b-a97f-4953-a746-bea781936f6c.mp4

### Steps to reproduce the behavior
1. Try to create a new blank page
2. Verify that the editor opens with no delay
3. Try to create a new page with any template
4. Observe that the **editor loads forever** or starts with a really big delay

##### Tested on:
* Pixel 2 XL, Android 11, WPAndroid 17.7 💥 
* Pixel 5, Android 11, WPAndroid 17.7 💥 
* Pixel 5, Android 12, WPAndroid 17.7 💥 
* Pixel 3a, Android 11, WPAndroid 17.7 💥 
* Samsung Galaxy S21, Android 11, WPAndroid 17.8-rc-1 💥 
* Samsung Galaxy S20, Android 11, WPAndroid 17.8-rc-1 💥 
* Redmi Note 8T, Android 10 👻 
* Samsung  Galaxy S7edge, Android 8, WPAndroid 17.8-rc-1 ✅ 
* Emulator (any) ✅

**Comment by antonis** [comment]
The issue seems to start with the [upgrade of React Native to 0.64](https://github.com/wordpress-mobile/WordPress-Android/pull/14702) (Gutenberg mobile `v1.56.0-alpha1`).
Checking APK artifacts from the commits on `develop` from June 16th:
* https://github.com/wordpress-mobile/WordPress-Android/commit/0db39c7bf5299db399812d57f80f4683548bcce7 ✅ 
* https://github.com/wordpress-mobile/WordPress-Android/commit/238a442f0b43b225136d089460b4dfab5e5b31e5 💥

**Comment by thehenrybyrd** [comment]
I was able to reproduce on Samsung Galaxy S21, Android 11, WPAndroid 17.8-rc-1.

https://user-images.githubusercontent.com/15107387/125597071-47efa600-b5f6-46d8-b34f-07a7af950bbc.mp4

After waiting more than 30 seconds for it to load, I tapped the back button which initiated saving. This took another 20 seconds.
After leaving the new Page, I can find it in the Drafts list and tap on it. The editor loads immediately in this case.

**Comment by hypest** [comment]
FWIW, **can't** reproduce on a Galaxy S7 Edge running Android 8.0, WPAndroid v17.8-rc-1.

I **do** replicate on a Pixel 2XL, Android 11., WPAndroid v17.8-rc-1.

**Comment by antonis** [comment]
Among other things I tried to clear the `initialData` [when it reaches Gutenberg ](https://github.com/WordPress/gutenberg/blob/fa3bfd5e960fb6d9901edc05530a27454ecb912a/packages/react-native-editor/src/index.js#L102). Even in that case the problem still persists 😞
This makes me think that something breaks on certain devices when passing the data above the RN bridge.

**Comment by dcalhoun** [comment]
I replicated the issue with Samsung Galaxy S20, Android 11, WPAndroid 17.8-rc-1. After tapping the back button, loading the Page from Drafts loaded immediately.

**Comment by antonis** [comment]
The same behaviour is observed in the other two cases where we initialize the editor with content:
- Reblog
- Share action


https://user-images.githubusercontent.com/304044/125625049-b9867b98-5cf4-4ff6-9b7a-c698c39041fc.mp4


https://user-images.githubusercontent.com/304044/125625082-e2097e13-2788-4b55-a6e9-7b58c22e7439.mp4

**Comment by dcalhoun** [comment]
> The same behaviour is observed in the other two cases where we initialize the editor with content:
> 
> * Reblog
> * Share action

@antonis good find! I captured Reblog in https://github.com/wordpress-mobile/WordPress-Android/issues/14972, but didn't realize the connection. It looks like someone captured Sharing in https://github.com/wordpress-mobile/WordPress-Android/issues/15023 as well.

**Comment by antonis** [comment]
Good catch @dcalhoun 👍 
Thank you for linking the issues 🙇 
It seems that something is broken when we try to pass content over the RNBridge in RN0.64 😢

**Comment by geriux** [comment]
Yesterday I tried it on my Redmi Note 8T running Android 10 and it worked, today I turned on my phone to test it again and its failing, it gets stuck loading too :(

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/15027 in `17.8`
