### ISSUE TITLE
Blogging Reminders: Settings do not remain intact across app version updates.

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#15022]
### Expected behavior
Updating the app will not effect my Blogging Reminders schedule. In other words, if I set up Blogging Reminders, and then update the app to the latest version, I should still receive reminders and see them in My Site > Settings.

### Actual behavior
After updating the app to 17.8-rc-1, I no longer see Blogging Reminders set in My Site > Settings.
However, though Blogging Reminders are not set, publishing a post doesn't trigger the "Set Blogging Reminders" interface.

### Steps to reproduce the behavior
1. Make sure you have 17.7 currently
2. Set up Blogging Reminders
3. Update to 17.8.
4. Check My Site > Settings, and see that Blogging Reminders are not set.
5. Publish a post to try to trigger Blogging Reminders interface.

##### Samsung Galaxy S21, Android 11, WPAndroid 17.7-rc-2 and 17.8-rc-1
Also experienced by @loremattei and @dcalhoun

**Comment by renanferrari** [comment]
Closed by #15024.
