### ISSUE TITLE
"Select from media library" shows default icons instead of image previews

### ISSUE THREAD

**Issue by supernovia** [wordpress-mobile/WordPress-Android#1508]
Add images from the media library to a post, and you'll see default thumbnails instead of previews of the actual images:

![missing image icons](https://cloud.githubusercontent.com/assets/3476361/3291100/dc6dc4c2-f580-11e3-9032-b61f61f0519a.png)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
