### ISSUE TITLE
Post List: The load more spinner is always visible and animating when there are very few posts.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#15095]
### Expected behavior
Once a post list has been synced the load more spinner is not visible.

### Actual behavior
The load more spinner is visible and constantly refreshes and animates. 

Example: 

![IMG_2609 2021-07-28 16_18_40](https://user-images.githubusercontent.com/1435271/127397431-2d233d18-b57e-4c4e-b09f-91cd10ed9e02.gif)

### Steps to reproduce the behavior
View the post list for a site that has very few posts.  My test was on a site with only four posts, where my user had an author role. 

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 2. WPAndroid 17.9 beta.

**Comment by thehenrybyrd** [comment]
No longer able to reproduce this behavior, on **Samsung Galaxy S21, Android 12, WP Android 20.3-rc-1**. I used a simple site with 4 posts.
The spinner has also been moved to the top, so I suspect the whole behavior has changed.
Closing for now, feel free to reopen if this behavior shows up again!
