### ISSUE TITLE
Media file extension added to the media file title

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#15108]
It was reported in 4190221-zd-woothemes that the media file extension was added to the media file title in the Media Library when the file was uploaded through the app. In the case reported, it was JPEG files.

However, when uploading the same file on Calypso, the file extension didn't get added to the media file title.

### Expected behavior

The user expects the file extension won't get added to the media file title.

### Actual behavior

The media files uploaded through the app contain the media file extension at the media file title.

### Steps to reproduce the behavior

1. Go to My Site > Media
2. Tap the "+" icon > Choose from device, and upload a JPEG image file
3. Once the media file is uploaded, tap the image and see that the file title contains the file extension

![Markup on 2021-08-02 at 10:13:03](https://user-images.githubusercontent.com/40906847/127795605-a59a36f0-d180-43ee-a361-48962b9566d6.png)

##### Tested on OPPO Reno 4, Android 11, WPAndroid 17.9-rc-2

**Comment by thehenrybyrd** [comment]
Thanks for the report!
I agree with the user here, it makes more sense to not have the file extension in the title.

I was able to repro this Samsung Galaxy S21, Android 11, WPAndroid 17.9-rc-2.
It also happens from "+" > Take Photo.
