### ISSUE TITLE
My Site Dashboard - Phase 1 [My Site Refactor, Quick Start, Quick Actions]

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#15126]
Parent #15125

`My Site Dashboard - Phase 1` will deprecate existing `MySiteFragment` in favor of `ImprovedMySiteFragment`. This task list down lists the tasks for this phase.

### Tasks

- [x] #15122 - @zwarm 
- [x] #15127 @ashiagr
- [x] #15136 Migrate `Quick Start - Notification/Reminders` to `ImprovedMySiteFragment` @zwarm 
- [x] #15130 @ParaskP7
- [x] #15191 @ParaskP7
- [x]  #15187 @ParaskP7, @ashiagr 
- [x] #15250 @ashiagr 
- [x] #15189 @ashiagr, @zwarm 
- [x] #15193 @zwarm, @ashiagr
- [x] #15252  @ashiagr
- [x] #15255 https://github.com/wordpress-mobile/WordPress-Android/pull/15236#pullrequestreview-738366500  @ashiagr @zwarm 
- [x] #15265 @ashiagr 
- [x] #15249 @ashiagr

**Comment by AliSoftware** [comment]
I was about to move this issue to milestone 18.3 as I'm doing code freeze of 18.2 as we speak, but I see that the all the tasks in this issue's checklist have been checked and done, so maybe this issue is ready to be closed after all? (if not, please move it to 18.3)

**Comment by ashiagr** [comment]
All important tasks for this issue are merged into `18.2`.

Few minor ones https://github.com/wordpress-mobile/WordPress-Android/issues/15258#issuecomment-910489481 are tracked separately. 

Closing this one.
