### ISSUE TITLE
My Site Dashboard

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#15125]
This is the main project issue for the `My Site Dashboard` project.

Project Thread: pbArwn-2zs-p2

### Phases

- [x] #15126
- [x] #15198
- [x] #15199
- [x] #15989

Remove Feature Flags
- [x] #15658 @ashiagr 
- [x] #15754
- [x] My Site Dashboard - Tabs - Remove Featured Flag

Today's Stats Card
- [x] #15753

Tabs

- [x] #16202 (Post Release Support)
- [x]  #16255

### Extra Tasks

- [x] What's new announcement (❓ - See [discussion here](https://github.com/wordpress-mobile/WordPress-Android/issues/15198#issuecomment-1011245529))
- [ ] Dashboard Cards ([FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android)): Implement `ReleaseStack_CardsTest` Test Suite

Others
- [x] #15296
- [ ] Refactor `QuickStartPromptDialogFragment`

**Comment by AjeshRPai** [comment]
Closing this issue as the linked project is wrapped up
