### ISSUE TITLE
Custom HTML is not stripped from post title

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-Android#15158]
It is possible to add custom HTML such as `<em>` or `<i>` to post and page titles and they will be rendered correctly when you visit the post.

Examples from WordPress.com:

- https://wordpress.com/forums/topic/italics-in-post-title/
- https://wordpress.com/forums/topic/how-do-i-italicize-in-the-title/

### Expected behavior
To have HTML tags either:

- Transformed into the element. For example, `<em>This is italic</em>` shown as italic in the post list; _or_
- Stripped as we see in WordPress.com:

![Screen Shot on 2021-08-09 at 13:27:12](https://user-images.githubusercontent.com/1136160/128740656-77a44324-21ea-4ee9-9a05-d7ad65bb2275.png)

### Actual behavior

We see the unstripped HTML tag in the posts list:

<img src="https://user-images.githubusercontent.com/1136160/128742457-37fdd8ce-066b-4cca-9a36-c8150ad26fe9.png" width="450"/>

### Steps to reproduce the behavior
1. Start a post
2. In its title, use some custom HTML like `<em>` or `<i>`
3. Save the post
4. Check the new post in the posts list

***

Also reported for https://github.com/wordpress-mobile/WordPress-iOS/issues/16999

**Comment by KirillPovarintsev** [comment]
Can I have it? I've got a fix (it should address the issue in multiple places across the app).
