### ISSUE TITLE
Keyboard not dismissed when tapping back button on Login screen

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-Android#15168]
### Expected behavior
Keyboard should be dismissed if the back button is tapped

### Actual behavior
Keyboard isn't dismissed

### Steps to reproduce the behavior

1. Tap Login in or sign up with WordPress.com button
2. Tap into the email address field
3. Tap the back arrow button
4. 👀 **Keyboard isn’t dismissed**
5. Tap anywhere on the Prologue screen
6. 👀 **Keyboard isn’t dismissed**

https://user-images.githubusercontent.com/6711616/129182269-324e5243-24a9-45a9-89dd-a426ebcc6b89.mp4

**Comment by thehenrybyrd** [comment]
I just ran into this when testing login flows, and am seeing the same behavior.
**Reproduced on Samsung Galaxy S21, Android 11, WPAndroid 18.0-rc-1**
I was only able to clear the keyboard by leaving the app and re-entering.

The same occurs with "Enter your existing site address".
