### ISSUE TITLE
My Site: Site Info Block - Site URL is cutoff when system font is set to largest setting

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#15172]
### Expected behavior
The site URL should be fully visible in the site Info Block on the My Site view when the system font is set to the largest setting.

### Actual behavior
The site URL is cutoff in the site Info Block on the My Site view when the system font is set to the largest setting.

### Steps to reproduce the behavior
- Set system font to highest setting on device
- Open app
- Navigate to My Site
- Note the Site url is cutoff

###Screenshot###
![Screen Shot 2021-08-12 at 8 35 34 AM](https://user-images.githubusercontent.com/506707/129197683-10e1ed47-2183-4a1a-a514-26a76698b902.png)

**Comment by namanrana16** [comment]
I would like to take up this issue.

**Comment by chandradeepkumar16** [comment]
I would love to contribute to this project. I am a beginner and looking forward to contributing to the community

**Comment by ashiagr** [comment]
👋 @chandradeepkumar16,

Thanks for your interest in the project! 

Since this issue is already assigned, can you take a look at this other issue https://github.com/wordpress-mobile/WordPress-Android/issues/13536? Let me know if you have any questions regarding [Project Setup](https://github.com/wordpress-mobile/WordPress-Android#wordpress-for-android) or the [Contributing Guide](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md).

**Comment by namanrana16** [comment]
@ashiagr I am having some problems with logging in, changed the OAuth ID and app secret but it persists.

**Comment by namanrana16** [comment]
> @ashiagr I am having some problems with logging in, changed the OAuth ID and app secret but it persists.

I am entering my ID but it still prompts currently unavailable, please enter the password.

**Comment by ashiagr** [comment]
Do you see any errors in the logs? What exact error are you seeing?

**Comment by namanrana16** [comment]
`BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1.3/auth/send-login-email/?locale=en_IN`

`org.wordpress.android.prealpha E/WordPress-API: OnAuthEmailSent has error: GENERIC_ERROR - Invalid client_id.`

`org.wordpress.android.prealpha E/Volley: [268943] BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1.3/auth/send-login-email/?locale=en_IN
2021-08-30 17:03:56.071 19687-19687/org.wordpress.android.prealpha E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.3/auth/send-login-email/?locale=en_IN
    com.android.volley.AuthFailureError`

This is one of the errors.
When I enter my email and login it shows Currently Unavailable. Please enter your password.

**Comment by ashiagr** [comment]
Have you followed these instructions?https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication

**Comment by namanrana16** [comment]
Yeah, I created the application in the app manager and changed the 2 Gradle properties mentioned.

**Comment by danmaze** [comment]
I'm unable to replicate this issue. I'm testing on Pixel 3a, Android 11 and I set the system font to largest. I also tested on my Android device and the site URL doesn't cut off.

**Comment by chandradeepkumar16** [comment]
I am trying to fix the bug but the code changes are not being reflected in my emulator. Why?
I have followed the Readme file and even successfully logged in with WordPress account.

**Comment by namanrana16** [comment]
When the name of the title is more than a single line then the URL is cut off.

**Comment by namanrana16** [comment]
> I am trying to fix the bug but the code changes are not being reflected in my emulator. Why?
> I have followed the Readme file and even successfully logged in with WordPress account.

Can you help me as I am having trouble logging in even after changing the client ID and Secret.

**Comment by danmaze** [comment]
> When the name of the title is more than a single line then the URL is cut off.

Ah, I see. Thanks.

**Comment by ashiagr** [comment]
👋 @chandradeepkumar16 

> I am trying to fix the bug but the code changes are not being reflected in my emulator. Why?
I have followed the Readme file and even successfully logged in with WordPress account.

I might not be able to help without looking at your changes. Since this issue is already assigned,  to avoid duplicating efforts, could you please work on this [other issue](https://github.com/wordpress-mobile/WordPress-Android/issues/13536) (also mentioned in my [earlier comment](https://github.com/wordpress-mobile/WordPress-Android/issues/15172#issuecomment-903473786))?  

I'd appreciate it if you can leave a comment before I assign it to you.

EDIT: My bad, #13536 is already taken. Can you take up this issue #15020?

**Comment by ashiagr** [comment]
👋 @namanrana16 

> Can you help me as I am having trouble logging in even after changing the client ID and Secret.

> When I enter my email and login it shows Currently Unavailable. Please enter your password.

It seems you're trying to log in using the magic link. Can you share the email address you're using to log in with? I'm guessing you already have a WordPress.com account for the email address based on these instructions:

> Note that credentials created with our [WordPress.com applications manager](https://developer.wordpress.com/apps/)
allow login only and not signup. New accounts must be created using the [official app](https://play.google.com/store/apps/details?id=org.wordpress.android)
or [on the web](https://wordpress.com/start). Login is restricted to the WordPress.com
account with which the credentials were created.

**Comment by namanrana16** [comment]
Yes, I already have an account. My Email Id is namanrana1828@gmail.com.

**Comment by ashiagr** [comment]
> Yes, I already have an account. My Email Id is namanrana1828@gmail.com.

All seems ok, can you retry? Or else set a password on the web and log in using email + password?

**Comment by namanrana16** [comment]
![WhatsApp Image 2021-08-31](https://user-images.githubusercontent.com/47075510/131456308-fe0e4ef0-b95f-493d-8918-f413fde52d89.jpeg)
![WhatsApp Image 2021-08-31 at 12 22 57](https://user-images.githubusercontent.com/47075510/131456312-8bfb1b7a-9a4d-4057-a839-c1e1f8b577b9.jpeg)

This is the screen, there is no password field.

**Comment by ashiagr** [comment]
> This is the screen, there is no password field.

You can go to https://wordpress.com/, login, and set a password from there.

**Comment by namanrana16** [comment]
> > This is the screen, there is no password field.
> 
> You can go to https://wordpress.com/, login, and set a password from there.

It worked! Thanks a lot.

**Comment by namanrana16** [comment]
@ashiagr  I have solved the issue and am in the process of making a PR.  How do I push the branch to GitHub as I am getting an error

`ERROR: Permission to wordpress-mobile/WordPress-Android.git denied to namanrana16.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`

**Comment by ashiagr** [comment]
@namanrana16, the repo is protected, you'll need to fork it and create a PR from it.

**Comment by namanrana16** [comment]
@ashiagr  I have created a PR. There are a couple of tasks that need to be taken care of but I don't know how to add labels, milestones, etc.
