### ISSUE TITLE
Comment Detail: Like icon does not stay highlighted when sharing link

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#15171]
### Expected behavior
When liking a comment, then copying link/sharing link from with the comment detail view, navigating out of the app to share and then back in, the Like icon remains highlighted.

### Actual behavior
When liking a comment, then copying link/sharing link from with the comment detail view, navigating out of the app to share and then back in, the Like icon does not remain highlighted.

### Steps to reproduce the behavior

- Tap on comment in comments list to open the Comment detail view
- Tap Like icon and note that it highlights
- Tap More → Copy Link Address → Snackbar → Share
- Share with an app outside of WP (For example: slack or messages)
- Return to app 
- Note that the Like icon is no longer highlighted on the detail view
- Tap the ← button to return to the comments list
- Tap the same comment to open the detail view
- Note the Like icon is highlighted

**Comment by thehenrybyrd** [comment]
I was able to reproduce on **Samsung Galaxy S21, Android 11, WPAndroid 18.0-rc-1**.
I happens with apps that open up to do the share process (messages, calendar, Gmail...), but not with those that share immediately from within the share-sheet (for instance My Drive).

**Comment by tiagomar** [comment]
I was also able to reproduce on **Samsung Galaxy Note20, Android 11 WPAndroid 18.0-rc-2**.
It happens whenever the application is sent to background and is back to foreground.
