### ISSUE TITLE
Login Epilogue: “Choose a site to open” is not bold

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#15179]
### Expected behavior
According to the design mock in https://github.com/wordpress-mobile/WordPress-Android/issues/14990, "Choose a site to open" should be bold.

### Actual behavior
"Choose a site to open" is in a larger font than the line below, but not bold.

![image](https://user-images.githubusercontent.com/15107387/129319602-38caf63b-a9bc-4829-b68a-8e1d46942045.png)

### Steps to reproduce the behavior
- Login to the WordPress app
- Stop at the login epilogue and note the design

**Comment by osullivanchris** [comment]
Good eye for detail @thehenrybyrd thanks! @ParaskP7 and I worked through this together and used an existing type style. So we diverged from the original design a bit, with my approval 😄  Thanks for spotting but we can close this.
