### ISSUE TITLE
Migrate Snackbar Reminders to ImprovedMySiteFragment

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#15187]
Parent #15126 

Display remind next task [snackbars](https://cloudup.com/cGhrRs6wQ5N) [currently not shown in ImprovedMySiteFragment]

**Comment by ParaskP7** [comment]
After confirming with @osullivanchris we want to keep the remind next task snackbars, but using the new snackbar style (while, black, blue). As such I will be now starting with this task.

**Comment by osullivanchris** [comment]
Quick Start clarifications per conversation with @ParaskP7 

### Style

**Correct style:**

- In light mode, snackbars/tooltips should have a dark background
- In dark mode, snackbars/tooltips should have a light background
- In both modes, actions should be blue.

**Issues:**
Quick Start appears to have missed some style updates. 
1. In Dark Mode, quick start snackbars are still displaying a dark background. Background should be light.
2. In both light and dark mode, quick start snackbars have pink actions. Should be blue.

### Functionality


- In the previous attempt to make a new My Site fragment, the prompts which automatically tell the user to go to the next task were removed.
- However, this resulted in less people completing Quick Start
- We should therefore keep the behaviour of the live version of Quick Start, where prompts appear to guide the user to the next task
