### ISSUE TITLE
Domains: domain selection results don't appear in landscape mode

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#15184]
### Expected behavior
I expected to be able to see my domain search results immediately when in landscape mode, just as I can in portrait mode.

### Actual behavior
In landscape mode, domain search results do not appear while typing.
Instead, there's a large empty space where I expected the results to appear.
I eventually figured out that tapping "search" closes the keyboard and shows the results.

<img src="https://user-images.githubusercontent.com/15107387/129324103-2dfac7ae-412f-483d-89f4-e7bcd4861afd.jpg" width="80%">

### Steps to reproduce the behavior
1. Create a new site
2. Select a theme
3. During domain selection, type part of a domain you want to search for
4. Turn your device to move to landscape mode.
5. Note the search results stop appearing.

https://user-images.githubusercontent.com/15107387/129324314-d8e68420-c2e3-4f90-aa8a-366b4b4c997d.mp4

**Comment by ravishanker** [comment]
Looked into this issue.  Search results are appearing in landscape mode, they're just hidden behind the keyboard. If the keyboard is dismissed or search button is pressed then results are revealed.  Need to fix input field to not expand in landscape mode.  Will find a fix.
