### ISSUE TITLE
Quick Start - Grow List: Text wrap seems a little off

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#15182]
### Expected behavior
Based on the mockup in https://github.com/wordpress-mobile/WordPress-Android/pull/15052,  I expected text wrap to kick in when the screen width was smaller, or wrap only one word.

### Actual behavior
"Keep up to date on your site's performance" seems to wrap a little early, and wraps the last two words instead of only one.

![image](https://user-images.githubusercontent.com/15107387/129321939-a89dd8a3-aab1-4723-a654-c4e98649bf0d.png)

### Steps to reproduce the behavior
1. Create a new site.
2. Choose "Show me around" on the Quick Start prompt.
3. Tap "Grow your audience" to open the list of tasks.
4. Compare the subtext under "Check your stats" to that in https://href.li/?https://github.com/wordpress-mobile/WordPress-Android/pull/15052 

Not sure if this is actually problematic, but it looked visually off.

**Comment by osullivanchris** [comment]
Good spot @thehenrybyrd, ➕ 1️⃣
