### ISSUE TITLE
Quick Start - Customize List: "Create your site" task shouldn't have "+" button

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#15181]
### Expected behavior
In the "Customize your site" list, I did not expect to be able to restart the "Create your site" task.

### Actual behavior
There is a "+" button next to "Create your site" under "Complete".
Tapping it closes the "Customize your site" list.
"Create your site" is not re-added to the "Customize your site" list. (good!)

### Steps to reproduce the behavior
1. Create a new site.
2. Choose "Show me around" on the Quick Start prompt.
3. Tap "Customize your site" to open the list of tasks.
4. Note that "Create your site" is marked as complete and appears at the bottom of the screen.
5. Tap the "+" to re-add "Create your site" to the list.
6. Note that the "Customize your site" list closes.

Implementation suggestion:
Either the "+" button should not appear next to this particular item (perhaps a checkmark instead), or it should note that this task can't be restarted.

##### Tested on Samsung Galaxy S21, Android 11, WPAndroid 18.0-rc-1

**Comment by zwarm** [comment]
@osullivanchris - want to chime in from a design perspective? Icons remain the same when tasks move from the uncompleted to completed list. I'm going to assume (i know) the "+"  is equivalent to "add". No other completed task shows a checkmark - maybe it's okay just for create site. Maybe we change the text of the `Get your site up and running` to something past tense? What are your thoughts? In the interim, I'm going to add the checkmark to see to what it looks like.

<img width="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/133087797-af953e2f-8579-448b-9a1b-399c5c8671b4.png">

**Comment by osullivanchris** [comment]
Good spot @thehenrybyrd !

Thoughts:
- this step is always completed
- I don't really want to introduce a checkmark. It might make me think all the done ones should have a checkmark, and they won't.
- We have a GridIcon called 'Site'. Can we use that one? It doesn't exactly have an obvious meaning, but I think thats ok given its precompleted.
- Not sure about past tense @zwarm because again maybe I'd expect all to be past tense if completed? But if we do it, we could say "Your site is up and running".
- I'm not really sure what I expect to happen when I tap it. Effectively, nothing. Maybe we could spring a Snackbar saying 'Site already created'. 
- A side thought is what if someone doesn't like their site, and thinks this is a place to make a new one? We could pop a dialog that says 'site already created. Did you want to make another one'. But it really seems like a stretch and would potentially add extra confusion rather than resolve.

Here's how the site icon looks btw
<img width="200" alt="Screenshot 2021-09-13 at 15 25 58" src="https://user-images.githubusercontent.com/50576199/133102591-8dd4706e-643b-4ed5-b5f9-f78c03305c49.png">

**Comment by zwarm** [comment]
@osullivanchris - thanks for the input. 

> * I don't really want to introduce a checkmark. It might make me think all the done ones should have a checkmark, and they won't.

I was just coming to this conclusion ... I added the checkmark and it doesn't look right mixed in with the others.

> * We have a GridIcon called 'Site'. Can we use that one? It doesn't exactly have an obvious meaning, but I think thats ok given its precompleted.

Let me drop that in and see. 

> * Not sure about past tense...

Same problem as the checkmark - all the others are present tense

> * I'm not really sure what I expect to happen when I tap it. Effectively, nothing. Maybe we could spring a Snackbar saying 'Site already created'.

I think the row should be unclickable. Not sure if we are set up for that right now, so it will take a bit of work (but it is hack week :) )

> * A side thought is what if someone doesn't like their site, and thinks this is a place to make a new one? We could pop a dialog that says 'site already created. Did you want to make another one'. But it really seems like a stretch and would potentially add extra confusion rather than resolve.

IMO, too much confusion if we push them to "create site" here. I would leave it as is.

**Comment by osullivanchris** [comment]
Agree with all the above @zwarm . To summarise I would say:

- use the 'Site' GridIcon
- Keep the current present tense
- make the row unclickable...don't create another path its confusing

Nice to have:
- when unclickable row is tapped, show a snackbar saying 'Your site is already created, try another task' or similar.

**Comment by zwarm** [comment]
@osullivanchris 
> when unclickable row is tapped, show a snackbar saying 'Your site is already created, try another task' or similar.

The row has to be clickable for us react with a snackbar. :) 
I can do one or the other ... @osullivanchris or @thehenrybyrd pick one and I'll implement it. Thanks!!

First video shows unclickable row/no snackbar and second video shows snackbar on tap - the snackbar will show back on the My Site view (like all the others) not on the list itself.


https://user-images.githubusercontent.com/506707/133132094-3a0d68c3-f33d-4e1e-bf9c-b66c2d6436bc.mp4

https://user-images.githubusercontent.com/506707/133132099-d3946585-9c7f-487f-8265-38289bb12684.mp4

**Comment by osullivanchris** [comment]
Thanks for pulling those videos together @zwarm 

> The row has to be clickable for us react with a snackbar. :)

Haha ok clickable but 'go nowhere' maybe is what I meant.

In video 2, I would expect to stay in the same location, and display the snackbar on top of the current view, not collapse the list. Is that possible? If so I think its the better option. WDYT? 

If not possible, maybe we can just disable the row for now.

**Comment by zwarm** [comment]
@osullivanchris 
>  display the snackbar on top of the current view, not collapse the list. Is that possible 

Yes, that is possible. I'll call you out on the PR for a design review. Give me 15 to post it. Thanks!
