### ISSUE TITLE
My Site Dashboard - Stats Card (Improve Structure, Stats, API, Networking and Persistence)

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15199]
Parent #15125

`My Site Dashboard - Stats Card` will implement the `Stats` and the (TBC) `Pages` dashboard card. This task list down lists the tasks for this phase.

### Phase 2
- [x] #15738 @zwarm 

### Tasks

- [x] #15748 @ashiagr
- [x] #15755 @zwarm , @ParaskP7,  @ashiagr
- [x] #15201 @ashiagr, @AjeshRPai 
- [x] #15747 @zwarm
- [x] #15749 @ashiagr
- [x] #15750 @ashiagr
- [x] #15751 @zwarm , @AjeshRPai, @ashiagr
- [x] #15973 @ashiagr
- [x] #15752 @ashiagr

**Comment by AliSoftware** [comment]
@ParaskP7 I'm doing code freeze of 19.3 right now, and I see this meta issue has all its checkboxes checked except the "To be done later" ones.

Can I let you sort this out, either by moving the milestone to 19.4, or by closing this issue and moving the remaining 2 checkboxes in a separate issue and milestone? Thanks!

**Comment by ParaskP7** [comment]
👋 @AliSoftware !

> @ParaskP7 I'm doing code freeze of 19.3 right now, and I see this meta issue has all its checkboxes checked except the "To be done later" ones.

Thanks for the ping! 👍 

> Can I let you sort this out, either by moving the milestone to 19.4, or by closing this issue and moving the remaining 2 checkboxes in a separate issue and milestone? Thanks!

I am shamelessly pinging @ashiagr as she would be the one to know what to do best. 😄

**Comment by ashiagr** [comment]
Thanks for the ping @ParaskP7! 

👋  @AliSoftware!  

I've moved "To be done later" tasks to the parent task. Closing this task now.
