### ISSUE TITLE
My Site Dashboard - Pages Card (TBC)

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15202]
Parent #15746

The goal of this task is to create the new `Pages` dashboard card as per the `Comments` on the new design in pbArwn-2zz-p2 (TBC).

- [ ] TBC
- [ ] TBC
- [ ] TBC

**Comment by AjeshRPai** [comment]
Closing this issue as this was an old design, and the page's card was implemented with the [Project](https://github.com/orgs/wordpress-mobile/projects/180/views/1)
