### ISSUE TITLE
Tests for Location feature

### ISSUE THREAD

**Issue by mjangda** [wordpress-mobile/WordPress-Android#1522]
To support the changes in #1468, we should add some test coverage for the location feature since there are a lot of edge cases that we can't always easily catch with manual testing.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by aforcier** [comment]
Closing - https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/195 adds tests for post location (unit, XML-RPC and WP.com REST) in FluxC, which will soon be replacing current post location handling.
