### ISSUE TITLE
Adjust postEditorAnalyticsSession calls to make startup_time_ms meaningful for Stories Editor

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/WordPress-Android#15291]
### Expected behavior

For different editors in WPAndroid we us a `postEditorAnalyticsSession` object and `wpandroid_editor_session_start`  tracks event to track editor startup times.  

For the gutenberg editor we have described the `startup_time_ms` property for gutenberg as: "[`startup_time_ms`] is the representation of the loading time (on Android, time measurement starts during the activity onCreate and ends when we render Gutenberg content)."

For reference, the `wpandroid_editor_session_start` event is sending the following properties. 
<details>
<summary>Event Properties</summary>
<br>
blog_type	

has_unsupported_blocks	

device_info_model	

device_info_os	

device_info_os_version	

device_info_phone_radio_type	

device_info_wifi_connected	

editor	

editor_has_hw_disabled	

post_type	

device_info_language	

session_id	

startup_time_ms	

template	

unsupported_blocks	

user_info_app_scheme	

user_info_dotcom_user	

user_info_gutenberg_enabled	

user_info_jetpack_user	

user_info_number_of_blogs	

device_info_manufacturer	

device_info_is_rtl_language	

browser_type	

device_info_current_network_operator	

can_view_editor_onboarding	

content_type	

device_info_app_name	

device_info_app_version	

device_info_app_version_code	

device_info_bluetooth_enabled	

device_info_bluetooth_version	

device_info_brand	

device_info_device_orientation	

device_info_is_online	

device_info_display_density_dpi	

device_info_display_height	

device_info_display_size	

device_info_display_usable_height	

device_info_display_usable_width	

device_info_display_width	

device_info_has_nfc	

device_info_has_telephony	

device_info_is_large_display

</details>

### Actual behavior

Currently there is a problem with the `startup_time_ms` property when sent with the `wpandroid_editor_session_start` event during Stories Editor startup. The call to create the session and the code for calculting startup time are essentially right after each other making the measurement not useful: 

https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerViewModel.kt#L113-L117

For the stories editor, we should likewise not count the session as started with the `startup_time_ms` calculation until the stories editor is as close to showing as possible. In android terminology we probably dont want this counting as started until onResume lifecycle event is called, but more importantly we want the measurement to be meaningful and not always be zero. 

### Steps to reproduce the behavior
*recommend watching tracks live view for `wpandroid_editor_session_start` event for your test username if you have access to tracks ([example url](https://mc.a8c.com/tracks/live/?eventname=wpandroid_editor_session_start&user=cameron.voell%40automattic.com&useragent=)). Otherwise you can just debug with a breakpoint at the line [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerViewModel.kt#L117) and note that the `startup_time_ms` calculation is not meaningful. 

1. While logged on as a wpcom user use the add button and select Story Post
2. Choose any Media and click check mark
3. Verify the zero `startup_time_ms` via tracks or debugger

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 4 Emulator API 30

**Comment by jd-alexander** [comment]
@mzorz I have been looking into this issue. I was wondering if it would be good to start the tracking here 
https://github.com/wordpress-mobile/WordPress-Android/blob/870ae98ae906fb5d34bd852478dba580f5339c41/WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerActivity.kt#L359

What I am wondering is where is the best place that would represent a story being fully loaded. If I would need to look into overriding any behavior of the `ComposeLoopActivity`. 

I am going to look into this some more tomorrow. Let me know if you have any thoughts.

**Comment by mzorz** [comment]
Thank you @cameronvoell @jd-alexander 🙏 

I've been looking into this - I think the beginning of `handleMediaPickerIntentData()` is rather the start of the process that figures out [which mode ](https://github.com/Automattic/stories-android/wiki/1.-Operating-modes)the StoryComposer should start itself in. Given there are various entry points as you said, it may get trickier to find a specific point that works for defining the "after processing" but "before showing", especially if we want to also take the camera live preview or video playing into account.

StoryComposerActivity's `onStart()` or `onResume()` as pointed out by @cameronvoell seem good candidates at first, but looking a bit deeper it doesn't take into account the time incurred by adding media as slides from startup which is done in a coroutine in `addNewMediaItemsToEditorAsync()` in StoryEditorMedia.

So, in digging a bit more, I saw that the start() method actually checks that the session is only started once, so taking advantage of that we can place calls to the start() method in a couple of places - the first time the start() method gets called will be the one that counts for actual Stories composer startup time.

Now, regarding the places we'd want to measure, we have the following:

a) `appendMediaFiles`. This is the last part being called when the MediaPicker is presented before the Activity gets called (thus, feeding the` StoryComposer` with the media URLS the user chose from the picker)

```
    private fun setupViewModelObservers() {
        viewModel.mediaFilesUris.observe(this, { uriList ->
            val filteredList = uriList.filterNot { MediaUtils.isGif(it.toString()) }
            if (filteredList.isNotEmpty()) {
                addFramesToStoryFromMediaUriList(filteredList)
                setDefaultSelectionAndUpdateBackgroundSurfaceUI(filteredList)
            }
```

This part is executed for any media items chosen with the media picker (local to the device,  from other apps, fromm the free photo library, or from the WordPress site
's media).

_This part (a) covers most of the use cases that are of interest or are comparable to the time-to-start being measured for Aztec or Gutenberg._

b) if the user chooses to tap on the camera FAB presented on the picker, which triggers the live preview mode of the Story Composer, then things get a bit trickier. In reality, the moment when things are ready to be presented in this mode is detected either in BackgroundSurfaceManagerReadyListener or within `launchCameraPreviewWithSurfaceSafeguard`, both internal to ComposeLoopFrameActivity in the Stories library.

I'd argue this second moment is essentially not as important, given this is very specific to the Story composer, so in this case I'd stick to something simpler at the client app level (StoryComposerActivity), and just check whether we've been passed the `requestCodes.EXTRA_LAUNCH_WPSTORIES_CAMERA_REQUESTED  in `onLoadFromIntent`.

c) if the user adds an empty Story block to a Gutenberg post and then taps on ADD MEDIA, or edits an existing block, things work the same here.

That should cover all, but I'll dig in a bit more later. I can draft a PR with this soon :thumbsup:
