### ISSUE TITLE
Question: How to disable the Weekly Roundup notification?

### ISSUE THREAD

**Issue by djramones** [wordpress-mobile/WordPress-Android#15318]
### Expected (or desired?) behavior

Users are able to specifically disable the weekly roundup notification (introduced in version 18.1/#15195).

### Actual behavior

It's not clear how to disable this notification specifically, without inadvertently disabling other notifications that the user may still want to receive.

### Steps to reproduce the behavior

After opening the notifications settings on the app, and looking for the weekly roundup notification option specifically, none can be found. It's not clear if the "Site achievements" option covers this notification, and it seems "Site achievements" would include other kinds of notifications as well.

<img src="https://user-images.githubusercontent.com/50655786/133020951-06265c6c-ec26-4ca1-ae1e-53c4a1ca4743.jpg" width="300">

**Comment by thehenrybyrd** [comment]
Thanks for bringing this up! You're right that site achievements covers other kinds of notifications.
It could be useful to have control over the weekly roundup notification specifically.
cc: @Gio2018

**Comment by irfano** [comment]
I tested the version 19.4-rc-1 and Weekly Roundup switch is in the list now.
![Screenshot_20220317_000337](https://user-images.githubusercontent.com/2471769/158691977-4dee951c-9ffa-47d7-bdb4-90dad1475855.png)
