### ISSUE TITLE
Add Blogging Reminders toggle to Notifications Settings

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-Android#15321]
### Expected behavior
I expect to be able to toggle Blogging Reminders notification in the same place I toggle other notifications 

### Actual behavior
Blogging Reminder notification is under Site Settings, the reset of the notifications are under Notifications -> Settings -> Site -> Push Notifications. 

### Steps to reproduce the behavior
Notifications Settings             |  Blogging Reminders 
:-------------------------:|:-------------------------:
![IMG_9875](https://user-images.githubusercontent.com/1335657/133179004-fe89aae7-22f4-47f6-991a-41c1aa569940.PNG)|![IMG_9876](https://user-images.githubusercontent.com/1335657/133179008-2b50c288-1555-4838-9981-4dee8b1be099.PNG)

iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/17152

**Comment by mokagio** [comment]
@yaelirub @startuptester @Gio2018 Today is code freeze day for 18.3. Can you please let me know if we want to fix this as part of 18.3, which will require a PR against the release branch, or if I can push this to the 18.4 milestone?

Thanks!

**Comment by mokagio** [comment]
@Gio2018 wrote on Slack that the team will work on this for 18.4. I've updated the milestone accordingly. 👍
