### ISSUE TITLE
Upgrade FluxC-Android to Android 11

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#15338]
WordPress FluxC Android [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2117)

**Comment by ParaskP7** [comment]
👋 @ravishanker !

I am closing this issue since this [Flux PR](Upgrade FluxC to Android 11 #2117
) is now merged. Feel free to reopen it if I am missing a step here.
