### ISSUE TITLE
Android > Microsoft Edge: Latest version is showing up as an unsupported browser. Unable to reach the login page 

### ISSUE THREAD

**Issue by Robertght** [wordpress-mobile/WordPress-Android#15332]
This is a replica of this issue: https://github.com/Automattic/wp-calypso/issues/56295

### Quick summary

Android: Latest version of Microsoft Edge is showing up as an unsupported browser.  Users are unable to reach the login page

### Steps to reproduce

1. Go to Play Store and download the Microsoft Edge app
2. Access the app and search for "WordPress login". One of the first results should show as "Unsupported Browser - WordPress.com" you can access this link or try it directly here: https://wordpress.com/start/
3. [First, you'll see this notice](https://d.pr/i/rbYLht). Click on "Continue loading the page anyway"
4. [You shall see this blank unresponsive page now](https://d.pr/i/ZARwSc).
5. Only after refreshing the page multiple times I was able to access the login page.

### What you expected to happen

First, I would not expect that the most recent Microsoft Edge mobile browser to be an unsupported browser. If this is indeed an unsupported browser, I would expect at least to be able to reach the login page. 

### What actually happened

[The login page is showing as a blank unresponsive page](https://d.pr/i/ZARwSc).

### Context

#C03TY6J1A/p1631738946211800-sl

### Operating System

Android

### Browser

Microsoft Edge

**Comment by thehenrybyrd** [comment]
Hi @Robertght! Thanks for triaging!
So you're aware, this repo is used specifically for the WordPress App on Android. 
How WordPress.com loads on mobile web browsers is not part of app development, and is specific to WordPress.com (the website) itself.
I'm not entirely sure where this issue should go though. It's not part of what I'd traditionally think of as Calypso, but I do see a number of issues pertaining to WordPress.com's login page in /wp-calypso, so probably re-opening the original issue there is the best course of action. 
I'll close this issue - let me know if you have any questions!

**Comment by Robertght** [comment]
Thank you for clearing this up @thehenrybyrd ! You're right! I think I've confused myself with this one.
