### ISSUE TITLE
Upgrade Login-Flow-Android to Android 11

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#15340]
WordPress-Login-Flow-Android [PR](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/66)

**Comment by ParaskP7** [comment]
👋 @ravishanker !

I am closing this issue since this [Login PR](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/66) is now merged. Feel free to reopen it if I am missing a step here.
