### ISSUE TITLE
Self hosted press site. Post does not use theme

### ISSUE THREAD

**Issue by JoelHJ** [wordpress-mobile/WordPress-Android#15374]
[Type] Support

### Expected behavior
Post a new post I expect it to use the same theme as on PC.

### Actual behavior
It uses another theme (my theme has a dark and light option which I can change in a post online when I post a new post

### Steps to reproduce the behavior
Use Android app and post a post. 

##### Tested on [device], Android [version], WPAndroid [version]
Mobile Samsung s9+

I was looking to see if there is an option in the app to change post options like on PC. The option "Post Setting" "Select type" i can't find. This is where I can on PC change the post to the dark theme?

Any help would be amazing. 

Thank you
Joel

**Comment by thehenrybyrd** [comment]
Hi Joel,
For support requests, you can reach our support team from Me > Help & Support > Contact Support. 🙂
However, I can tell you that specialized post options from individual themes do not appear in the app. If you'd like to change this setting from your phone, you can head to My Site > View Admin to open wp-admin for your site.
Please get in touch with our support team if you need any further help.
