### ISSUE TITLE
Draft post coming from nowhere after post has been published

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1540]
One user first noticed this behaviour of zombie draft posts. I noticed it, only after using the "Share picture with WordPress" feature a lot (but I'm not sure this is related).

* Publish post "A" via "Share with WordPress"
* Publish post "B" via "Share with WordPress"
* Publish post "..." via "Share with WordPress"
* Notice post "B" is published and a draft "B" is also there

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
