### ISSUE TITLE
Some users lose content they're working on

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1543]
From a user:

> When sharing multiple photos to a post from the G+ gallery, several posts got stuck in local draft. I had to edit and publish again. Every post except one successfully published on the second attempt. One lost all content, including several images.

We also have comments on the Play Store from users who lost their work and can't find a local draft version. Seems only related to local drafts.

This is going to be hard to reproduce...

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
