### ISSUE TITLE
Fix authentication bug when sharing to Facebook

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#15456]
### Expected behavior

When sharing to Facebook, users expect a seamless experience authenticating their Facebook account, even if they don't have the Facebook app installed on their device.

### Actual behavior

Users attempting to share to Facebook (My Site → Sharing → Facebook) see what looks like a cryptic technical message or error when trying to authenticate via their Facebook account. After tapping Connect, a Facebook login page is shown briefly before users are redirected to a screen which explains how Facebook login is not permitted in embedded web views. It asks the user to download the Facebook app to continue.

The glitchy UX (Facebook login page shown briefly) plus the technical message ("login is not permitted in embedded web views") feels like a hurdle for most users, even if instructions to resolve the issue (by downloading the Facebook app) are included in the message.

Update: Installing the Facebook app does not allow users to authenticate and share to Facebook, see https://github.com/wordpress-mobile/WordPress-Android/issues/15456#issuecomment-973662924.

As @thehenrybyrd suggested offline, a better user experience might involve re-directing users to the device's web browser to login (and have it redirect to the app) if that is possible. It might be worth investigating what options we have for users such as this who don't have the Facebook app installed on their device. 

### Steps to reproduce the behavior

**Prerequiste**: Make sure the device does not have the Facebook app installed.

1. Go to the My Site tab
2. Tap Sharing
3. Tap Facebook
4. Tap Connect
5. Notice that the Facebook login screen is shown briefly
6. Notice after a second or two that are "Log in Disabled" screen is shown with an explanation of the issue and instructions to download the Facebook app
7. Install the Facebook app and try to share to Facebook again
8. Notice the warning from Step 6 is still shown (see https://github.com/wordpress-mobile/WordPress-Android/issues/15456#issuecomment-973662924)

**Comment by reginabally** [comment]
We have a report in [Google Play Store app review](https://play.google.com/console/u/0/developers/7957760354032996428/app/4973361825681449040/user-feedback/review-details?reviewId=gp%3AAOqpTOHUSfpfQY0D2nK8KQzuOuaJeHnbBiKqaNaOal51eoI2eqAC50wgoxW4JWHfUQjEwQIWYH70vRbfFp4l9Q&corpus=PUBLIC_REVIEWS) on TCL 10 SE, Android 11, WPAndroid 18.6.

> It does not allow you to log in with Facebook, this falka has several days, please solve.

I tested this on Huawei Nova 2i, Android 9, WPAndroid 18.6. I have the Facebook app installed on the device and also logged in. However, I was stuck at the warning on the in-app browser when I tried to connect my test site to Facebook in the app.

![Screenshot_20211119_100201_org wordpress android](https://user-images.githubusercontent.com/40906847/142552266-076f1619-2ae7-4fa2-a404-fbffd72b9a9a.jpg)

@erricgunawan was able to reproduce this on Redmi Note 9 Pro, Android 11, WPAndroid 18.6 too.

**Comment by fluiddot** [comment]
As per [this blog post from Facebook](https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/?locale=en_US), Facebook Login will no longer support using Android embedded browsers (WebViews) for logging in users, so we would need to follow the instructions the instruction to address the issue and use the new process for login into Facebook.

_Extracted from [the post](https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/?locale=en_US) article:_
> **Updated on August 27, 2021:** We will continue to support FB Login authentication on Android embedded browsers until October 5, 2021. Based on developer feedback, we are providing additional time for developers to plan for the deprecation of FB Login authentication on Android embedded browsers. Also note that the Passwordless flow referenced below is no longer an available option for developers. Please review the detailed documentation [here](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews).

- **Developer docs:** https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews

**Comment by guarani** [comment]
> I tested this on Huawei Nova 2i, Android 9, WPAndroid 18.6. I have the Facebook app installed on the device and also logged in. However, I was stuck at the warning on the in-app browser when I tried to connect my test site to Facebook in the app.

Thanks for sharing this. When I filed this issue, I didn't actually test to verify if installing the Facebook app resolved the login issue, I just assumed it did based on the error message – sorry about that.

> As per this blog post from Facebook, Facebook Login will no longer support using Android embedded browsers (WebViews) for logging in users, so we would need to follow the instructions the instruction to address the issue and use the new process for login into Facebook.

If the app needs to be updated to support the new process for login into Facebook, this issue seems high priority – wdyt @fluiddot?

I'm going to change the issue type from Enhancement to Bug.

**Comment by fluiddot** [comment]
> If the app needs to be updated to support the new process for login into Facebook, this issue seems high priority – wdyt @fluiddot?

Yeah it is indeed, I've shared the issue with the rest of the team, in case someone can check it further and introduce the migration.

> I'm going to change the issue type from Enhancement to Bug.

Thanks @guarani for updating the tags 🙇 , I'm wondering if we should also update the title and description of the PR to be more accurate on the issue, as instead of improving we're now referring to fixing the authentication, wdyt?

**Comment by guarani** [comment]
Good call! I updated the issue title and description to reflect how it's not possible to share to Facebook, even with the Facebook app installed on the device.

**Comment by renanferrari** [comment]
FYI I looked into this last week and posted a few considerations about it here: p1637357908163300/1637317466.158800-slack-C011BKNU1V5

**Comment by erricgunawan** [comment]
Just wanted to add a report from 4560157-zen:

> I am unable to connect the social media Facebook to have my posts automatically published in it. Whenever I click on it the login page appears once and then disappears and shows the following message : "For your account security, logging in to Facebook from an embedded browser is disabled. To continue, download and log in to the Facebook app on your device and try again."

**Comment by renanferrari** [comment]
@erricgunawan Thank you for the extra report. 

FYI I'm planning to tackle this bug next week if nothing else with a higher priority comes up. I'll keep you posted.

**Comment by erricgunawan** [comment]
No problem @renanferrari! Thanks for working on this.

I'm just adding the report here in case we need to track them for reasons. Feel free to work or prioritize it as necessary.

Here's another report from 4579208-zen (translated):

> I want to link my WordPress account with Facebook and it does not let me, I have tried

**Comment by renanferrari** [comment]
I wasn't able to focus on this issue this week, due to some other priorities. I should get back to it after the holidays.

**Comment by erricgunawan** [comment]
Again, just adding another report: 4684811-zen

I saw a separate Project Thread to start working on this. So, thank you!

**Comment by erricgunawan** [comment]
Another from 4678395-zen
