### ISSUE TITLE
Quick Start: Remove dead pixels around snackbars

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#15461]
Parent #15296

### Expected behavior
There should not be any dead pixels around snack bar messages causing underlying UI to be hidden.

### Actual behavior

There is an area where the UI is cut-off/hidden above some of the Snackbars.

See https://github.com/wordpress-mobile/WordPress-Android/issues/15258#issue-983621548 for more details.

##### See image below, the 'Stats' list item is being partly cut-off.

![131472839-e67c528f-19fb-4dab-952f-62229d6a5cc4](https://user-images.githubusercontent.com/1405144/137253973-6072fb4d-6563-4331-9e71-7380e57d6ffc.jpeg)

**Comment by ParaskP7** [comment]
FYI: Adding a comment here since #15466 might be related to this issue as well.

**Comment by ashiagr** [comment]
Closed via #15611
