### ISSUE TITLE
My Site screen is cut off when getting back from the editor

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15466]
### Expected behavior
The My Site screen displays correctly when getting back from the editor

### Actual behavior
Going back from the editor to the main screen cuts off the bottom part of the My Site options

### Steps to reproduce the behavior

1. From the _My Site_ screen open the editor
2. Close the editor
3. Notice that the part of the screen that was covered from the keyboard inside the editor is missing

https://user-images.githubusercontent.com/304044/137346024-899e6242-6a94-4c77-8b4c-e8c18596480a.mp4

_Note that the issue is not reproduced on Posts/Pages list when you get back from the editor_

**Comment by mchowning** [comment]
Do you know if anyone is working on this @antonis ?

**Comment by antonis** [comment]
@zwarm is working on a solution
