### ISSUE TITLE
My Site Empty View not shown when logging in/out/in with an account that has no sites

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#15494]
### Expected behavior
Expect to see Empty view when logging in with an account that doesn't have any sites

Login Epilogue empty View | My Site tab empty view
-- | --
<img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/138738974-8651996b-5990-4c7b-836a-16b39250fe52.png"> | <img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/138738985-a65222de-f3df-420b-bcfd-0d318a59d279.png">

### Actual behavior
The Choose a site view is showing

<img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/138739241-029da017-3b85-4139-a863-3371f7592bde.png">

### Steps to reproduce the behavior
NOTE: This bug goes back to at least 17.0 (pre-onboarding changes)
- Uninstall any WP app versions from your device
- Install latest version (at time of writing the issue 18.5. rc2)
- Log in using an account that has no sites
- Note that you are shown "Login epilogue empty view" (see above screenshot)
- Tap on "Not Right Now"
- Note that you are shown "My Site tab empty view" (see above screenshot)
- Log out of the app by tapping Me icon -> Log out of WordPress.com
- Log back into the app using an account that has no sites
- Note that you are shown the "Choose a site to open" view (or for versions pre-onboarding, the site list view)
* To get the app back into a usable state, swipe the app closed and reopen. If you continue the logout-> login path, you will encounter the same issue as described above.

##### Tested on [device], Android [version], WPAndroid [version]
Pixel5, Android 11, 17.0 and up

**Comment by Anatame** [comment]
Might work on this.

**Comment by ashiagr** [comment]
Hey @Anatame! Thanks for your interest in the issue. 🙇‍♀️ 
We had to increase the priority of the issue, as it was blocking another issue. 

I'll be taking up this issue. Let me know if you are interested in any other issues, I'll happy to assist you in finding one, thank you!
