### ISSUE TITLE
Media: Keyboard appears when changing orientation

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#155]
The cursor is always active in one of the text fields.  Rotating invokes the keyboard, even if it has been previously dismissed.

Nexus 7 / 2.5 beta 3

**Comment by kwonye** [comment]
Can you clarify which text field please? I wasn't able to reproduce on every text field I could find. Also, considering this bug is over a year old, maybe it got resolved without the issue being closed?

**Comment by aerych** [comment]
Wow. Old issue. I don't think this one is valid anymore. At least I can't reproduce it now. 
FWIW the steps to repro were:
- Select Media from the menu.
- Tap an existing item to view its detail
- Edit the media item
- Tap the caption or description text field, then dismiss the keyboard. 
- Rotate the device.
- The keyboard reappears.
