### ISSUE TITLE
Almost invisible buttons on ZenDesk/Support screens

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#15503]
### Expected behavior
When I open list of my tickets and there aren't any, the "Start a conversation" button should be clearly visible.

### Actual behavior
When I open list of my tickets and there aren't any, the "Start a conversation" button has same background as the screen and the button label is almost invisible

### Steps to reproduce the behavior
1. Open the app
2. Make sure you are not logged in or you are logged in with an account which doesn't have any support tickets
3. Go to the Support section (eg. Login with WordPress.com -> Tap on "?" icon in the toolbar 
4. Tap on My Tickets
5. Notice "Start a conversation" button is almost invisible

##### Tested on [device], Android [version], WPAndroid [version]
Samsung S20 and Samsung Z Flip - Android 11

<img src="https://user-images.githubusercontent.com/2261188/139204658-65c8e7f3-74fb-44a4-8d61-ea5542eabbea.jpg" width="250px" />

**Comment by malinajirka** [comment]
@hypest and I have done a quick investigation and it seems the WPAndroid app is overriding styles which are breaking ZenDesk UI (the ZenDesk UI is part of the ZenDesk library).

More info about possible solution can be found on this Slack convo - `p1635342946038200-slack-C0HTU7HV3`

**Comment by designsimply** [comment]
Also see https://github.com/wordpress-mobile/WordPress-Android/issues/11111.
