### ISSUE TITLE
Privacy Settings link buttons are not opening to anything

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#15516]
### Expected behavior
The various "learn more" link buttons in the Privacy Settings screen should open some informational page when tapped.

### Actual behavior
The buttons seem to receive the tap but nothing's opened afterwards.

### Steps to reproduce the behavior
1. On WPAndroid, tap on the top-right avatar icon to go to to the "Me" screen
2. Tap on "App Settings"
3. Tap on "Privacy settings"
4. Tap on any of the "Learn more" or "Read privacy policy" or "Read CCPA privacy notice" buttons and observe that nothing happens except for the buttons visually acknowledge the tap.

Video of the behavior:

https://user-images.githubusercontent.com/1032913/139655845-b3382a50-fcce-4661-aa8b-24c27f0aaa04.mp4

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 2XL
Android 11
WPAndroid v18.5-rc-2 but happens on older versions too.

**Comment by thehenrybyrd** [comment]
@hypest do you still encounter this issue?
I was unable to reproduce on Samsung Galaxy S21, Android 12, WP Android 20.0. All links opened in Chrome for me.

**Comment by hypest** [comment]
Yay, can't reproduce the issue myself either! Tested on a Samsung Note20U, WPAndroid v20.5-rc-1. Thanks for testing as well @thehenrybyrd! I'll close this now.
