### ISSUE TITLE
[Android] About Screen v1: Integrate About library into WordPress app

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#15528]

**Comment by thehenrybyrd** [comment]
@ravishanker can you add tags to this and #15527? Thanks!

**Comment by AliSoftware** [comment]
Should those be closed?

A tag 0.0.2 of About Library has now been released, and integrated into the WPAndroid client app (incl Localization for 18.9 now, via https://github.com/wordpress-mobile/WordPress-Android/pull/15708) so I think we could consider this done…?

…Except if you want to keep it open a bit longer to check that the translations get into GlotPress later this week, after the 18.9 code-freeze lands and wpcom imported the strings into GlotPress?

**Comment by AliSoftware** [comment]
Ping @ravishanker  again.

I'm gonna go ahead and submit 18.9 now, but would really like this being sorted out.

**Comment by renanferrari** [comment]
Thank you for the pings and sorry for the delay on this, @AliSoftware. Yes, these issues can be closed now.

**Comment by renanferrari** [comment]
Closed by #15529.
