### ISSUE TITLE
Add Pull To Refresh support for `Stories` media picker

### ISSUE THREAD

**Issue by pachlava** [wordpress-mobile/WordPress-Android#15535]
### Expected behavior

`Choose media` screen shown right after Story Post creation should support Pull To Refresh (PTR) in similar way as it's done for `Multimedia` section.

### Actual behavior
PTR does not work for `Stories`:

https://user-images.githubusercontent.com/73365754/140491329-9c4648f4-6d68-4ff5-ae3f-d5822c59b5e3.mp4

### Steps to reproduce the behavior
1. Start creating a new story post
2. Once `Choose media` screen is shown, minimize the app
3. Open device camera and take a photo
4. Open the app again, try PTR ~> it doesn't work.

### Tested on

Make|Model|Android Version|App Version
-|-|-|-
Samsung|A31|10|18.6-rc-1

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
