### ISSUE TITLE
[Android] About Screen v1: Add About [App] in Me in place of Share WordPress with a friend

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#15548]
If feature flag is enabled
- Add About WordPress under Me in place of Share WordPress with a friend option
- Remove About the app from Me -> App Settings

**Comment by AliSoftware** [comment]
@ravishanker I'm doing code-freeze of `18.7` today. Should this be addressed in 18.7 (ie was the feature flag enabled in 18.7) or should we move this to milestone `18.8`?

I don't see it in the `18.7` section of the `RELEASE-NOTES.txt` file so I'm assuming it didn't go in, but just wanted to double-check.

[EDIT] Ah I just found #15551 which seems related, and see that it hasn't been merged yet and that @renanferrari also changed the milestone for that PR from `18.7` to `18.8`, so I'm gonna do the same for this issue after all.
