### ISSUE TITLE
Reader: Buttons not showing up in Reader

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#15547]
It was reported in 4440212-zd-woothemes that the buttons added to a post did not show up when the post was viewed on the app's Reader screen. However, the buttons are displaying correctly when viewed on a mobile browser.

### Expected behavior

Buttons show up in the app's Reader.

### Actual behavior

The buttons added to the post displayed as a blank rectangle. According to the user, they added the buttons through the web editor.

![Screenshot_20211110_090032_org wordpress android](https://user-images.githubusercontent.com/40906847/141031185-5f9bc79b-cf19-4d19-bb10-ba658439845a.jpg)

### Steps to reproduce the behavior

1. Open the app's reader, look for the site reported in the ticket.
2. Tap the latest post (titled MTL – 76+77) and scroll down to the bottom of the post.
3. Noticed that there are a few blank rectangles as shown in my screenshot above.
4. View the post on a web browser, notice the buttons are displayed correctly.

##### Tested on Huawei Nova 2i, Android 9, WPAndroid 18.5, Android System WebView 95.0.4638.74
Originally reported on Samsung SM-F711B, WPAndroid 18.5, Android System WebView 95.0.4638.74

**Comment by reginabally** [comment]
I tested this again on my test site by adding buttons (through the app and Calypso) to a post, I was able to reproduce this by viewing the post on the app's Reader.

Test post: https://premiumtestsite20190311.blog/2021/11/10/test-button/

![Screenshot_20211111_155520_org wordpress android](https://user-images.githubusercontent.com/40906847/141260036-31cd42ea-e1c4-4043-9b70-43ffcf7d4cfa.jpg)

**Comment by zwarm** [comment]
I am not able to recreate this issue on a consistent basis. Actually, I was only able to recreate it 1 time. The following are the steps I took when it happened. 

- Created a new post
- Added one button on first row, 2 buttons on the second row, 4 buttons on third row 
- Published the post
- Launched the Android app using a fresh login
- Navigated to reader (I was already following the site)
- Tapped the post to open
- Buttons showed as empty boxes

After another dozen or so times, I was unable to duplicate the issue. I have tried with different length button text, differing the number of buttons on each row, adding paragraphs, etc.

Then I started digging through the resulting page code and all looked okay. But for sanity sake, I tried the following...
- From within calypso, I navigated to the post that doesn't show in Android
- Selected the post to open the editor
- Switched to the code editor (using the vertical more menu -> code editor)
- Copied the contents of the page (not the title)
- Exited out of edit
- Created a new post
- Switched to the code editor
- Copied the pasted content of the post that is broken
- Published
-  Launch the Android app
- Logged out and logged in
- Navigated to reader 
- Tapped the post which had the copied content 
- Buttons show as expected

@reginabally - can you repeat my second test (copying content into new post) with your broken post? I'd like to see if you get the same results as I did. Thanks.

**Comment by zwarm** [comment]
More detail

The format of the API post response has changed from
```
<div class="wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link">One</a></div>
</div>
<div class="wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link">Two</a></div>
<div class="wp-block-button"><a class="wp-block-button__link">Three</a></div>
</div>
<div class="wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link">one</a></div>
<div class="wp-block-button"><a class="wp-block-button__link">two</a></div>
<div class="wp-block-button"><a class="wp-block-button__link">three</a></div>
<div class="wp-block-button"><a class="wp-block-button__link">four</a></div>
</div>
 </div>
```

to 

```
<div class="wp-block-buttons" style="display: flex; flex-direction: row; flex-wrap: wrap; gap: var(--wp--style--block-gap,.5em);">
<div class="wp-block-button" style="display: inline-block; margin: 0;"><a class="wp-block-button__link" style="border-radius: 9999px; box-shadow: none; box-sizing: border-box; color: #fff; cursor: pointer; display: inline-block; font-size: 1.125em; padding: calc(.667em + 2px) calc(1.333em + 2px); text-align: center; text-decoration: none; word-break: break-word;">One</a></div>
</div>
<div class="wp-block-buttons" style="display: flex; flex-direction: row; flex-wrap: wrap; gap: var(--wp--style--block-gap,.5em);">
<div class="wp-block-button" style="display: inline-block; margin: 0;"><a class="wp-block-button__link" style="border-radius: 9999px; box-shadow: none; box-sizing: border-box; color: #fff; cursor: pointer; display: inline-block; font-size: 1.125em; padding: calc(.667em + 2px) calc(1.333em + 2px); text-align: center; text-decoration: none; word-break: break-word;">Two</a></div>
<div class="wp-block-button" style="display: inline-block; margin: 0;"><a class="wp-block-button__link" style="border-radius: 9999px; box-shadow: none; box-sizing: border-box; color: #fff; cursor: pointer; display: inline-block; font-size: 1.125em; padding: calc(.667em + 2px) calc(1.333em + 2px); text-align: center; text-decoration: none; word-break: break-word;">Three</a></div>
</div>
<div class="wp-block-buttons" style="display: flex; flex-direction: row; flex-wrap: wrap; gap: var(--wp--style--block-gap,.5em);">
<div class="wp-block-button" style="display: inline-block; margin: 0;"><a class="wp-block-button__link" style="border-radius: 9999px; box-shadow: none; box-sizing: border-box; color: #fff; cursor: pointer; display: inline-block; font-size: 1.125em; padding: calc(.667em + 2px) calc(1.333em + 2px); text-align: center; text-decoration: none; word-break: break-word;">one</a></div>
<div class="wp-block-button" style="display: inline-block; margin: 0;"><a class="wp-block-button__link" style="border-radius: 9999px; box-shadow: none; box-sizing: border-box; color: #fff; cursor: pointer; display: inline-block; font-size: 1.125em; padding: calc(.667em + 2px) calc(1.333em + 2px); text-align: center; text-decoration: none; word-break: break-word;">two</a></div>
<div class="wp-block-button" style="display: inline-block; margin: 0;"><a class="wp-block-button__link" style="border-radius: 9999px; box-shadow: none; box-sizing: border-box; color: #fff; cursor: pointer; display: inline-block; font-size: 1.125em; padding: calc(.667em + 2px) calc(1.333em + 2px); text-align: center; text-decoration: none; word-break: break-word;">three</a></div>
<div class="wp-block-button" style="display: inline-block; margin: 0;"><a class="wp-block-button__link" style="border-radius: 9999px; box-shadow: none; box-sizing: border-box; color: #fff; cursor: pointer; display: inline-block; font-size: 1.125em; padding: calc(.667em + 2px) calc(1.333em + 2px); text-align: center; text-decoration: none; word-break: break-word;">four</a></div>
</div>
</div>
```

Looks like a bunch of new styles were added.

**Comment by reginabally** [comment]
@zwarm Thanks for taking a look! I repeated the steps in your second test and I was able to see the buttons in the WPAndroid app's Reader.

Test post: https://premiumtestsite20190311.blog/2021/11/12/test-button-2/

![Screenshot_20211112_131230_org wordpress android](https://user-images.githubusercontent.com/40906847/141413542-5a08d407-4e82-47d6-bf00-e064f82a9ff7.jpg)

**Comment by zwarm** [comment]
@reginabally - Thanks again for the assistance, this is one of the weirdest issues I have seen, You can see the buttons, but I pulled up the post and I don't see them again. Can you check if they are still showing? Thanks

**Comment by reginabally** [comment]
@zwarm Yes! I refreshed the post and now I don't see the buttons anymore. This is indeed very strange!

![Screenshot_20211116_113821_org wordpress android](https://user-images.githubusercontent.com/40906847/141934204-20e0e7ae-4b03-4227-be86-4e2c5e86e7db.jpg)
