### ISSUE TITLE
Quick Post Status / Aside

### ISSUE THREAD

**Issue by markwaters** [wordpress-mobile/WordPress-Android#1556]
The app already has quick post capabilities for photo and video.
How about a quick post capability for a status / aside post ?
This would give us the ability to post quick tweet-like things.
I would hope that the status / aside post format would be automatically set.

The Twitterify plugin automatically creates wordpress tags by entering hashtags.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
