### ISSUE TITLE
If you delete your last site it stays visible until restart

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-Android#15592]
### Expected behavior
If I delete my only site I should be presented with the 'Add a site' empty view again

### Actual behavior
The last site stays visible and I am able to attempt to interact with it

### Steps to reproduce the behavior

1. Sign in with an account with no sites
2. Tap the add site button
3. Follow the steps to create a site
4. Once its created go to Site Settings
5. Tap the Delete Site button
6. Enter your site name to delete the site

##### Tested on [device], Android [version], WPAndroid [version]
Android Simulator, WPAndroid 18.6

**Comment by antonis** [comment]
I reproduced this on the latest `18.8` version. Adding a video for reference.

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/304044/144070519-d0e5a4bb-f990-46ea-a1c7-b63dd1ec5318.mp4
</details>

**Comment by SowmiaS** [comment]
Hello 👋 
I would like to look into this issue. kindly assign this issue to me.
Thanks

**Comment by SowmiaS** [comment]
Hello @emilylaguna 👋 ,

I had a look into the issue. 

1. > If I delete my only site I should be presented with the 'Add a site' empty view again

can you please give me an insight on which of the below screen referred to as `Add a site`? Hopefully the second one (`Create a new site`), but would like to clarify.

`Choose site screen` with `Add new site` dialog | `Create a new site` screen
--- | ---
![choosesite_addnewsite](https://user-images.githubusercontent.com/4975407/156497350-e83953d8-7ad4-43c2-9076-282c15f01488.jpeg) | ![create_newsite](https://user-images.githubusercontent.com/4975407/156497358-43706bc5-dfbe-483e-9653-b2daa7604b62.jpeg)

2. I could see a similar issue even when multiple sites are there. In that case, can we show the `Choose site` screen?

https://user-images.githubusercontent.com/4975407/156499571-70ae91fd-5b50-4bcf-aba8-7cf116fc48f0.mp4

Kindly correct me if I am wrong.

Thanks.

**Comment by AjeshRPai** [comment]
Hey @SowmiaS,

First of all, thank you for taking an interest in contributing to the issue. 🙌 

1. If I delete my only site, I should be presented with the 'Add a site' empty view again. This would be the same view shown in the `My site `tab when a user with no site is logged in. 

<img src ="https://user-images.githubusercontent.com/17463767/156746667-23838de1-044d-4e0f-8966-5301e3608320.jpg" width="200"/>

2. When multiple sites are there. In that case, we can show the `Choose site` screen. 👍 

3. If there are only two sites and we delete any of them, we should show the My Site tab with the other one selected. Say the user has only two sites, SiteA and SiteB.  SiteA is deleted, then SiteB should be selected by default in the MySite tab. 

I hope this comment clears all your queries.

**Comment by SowmiaS** [comment]
@AjeshRPai Thanks for the clarification.
