### ISSUE TITLE
Pages List: Add Copy link functionality for pages

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15612]
### Description
The user should be able to easily copy a page link (for posts the functionality is implemented in https://github.com/wordpress-mobile/WordPress-Android/pull/15570):

1. Press the dots at the right of a page in the list
2. A **Copy link button should be added above the Trash button**
3. When the user presses the *Copy link button* a **snackbar message appears saying "Link copied to clipboard"**
4. The link is available in the clipboard for pasting

**Comment by ovitrif** [comment]
Adding this link to the related issue for posts list: #13292

And link to the pull-request with the implementation for posts: #15570

**Comment by EmilyGoose** [comment]
Taking a crack at this issue - Current solution involves passing a nullable Context to onMenuAction so I can get the ClipboardManager in PagesViewModel. Not sure if this is the most elegant solution but once tests are written will submit a PR.

**Comment by antonis** [comment]
> Taking a crack at this issue - Current solution involves passing a nullable Context to onMenuAction so I can get the ClipboardManager in PagesViewModel. Not sure if this is the most elegant solution but once tests are written will submit a PR.

Thank you for looking into this @EmilyGoose 🙇 
We'll be happy to help and review your PR :)

**Comment by EmilyGoose** [comment]
Pull request #16321 created

**Comment by antonis** [comment]
> Pull request #16321 created

Thank you for contributing to `WordPress-Android` @EmilyGoose 🙇 
We will review your PR and get back to you :)
