### ISSUE TITLE
Reply to post vs reply to comment logic should be reviewed.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#15621]
This is a placeholder issue to come back to further understand it, for something that we noticed while reviewing [a PR here](https://github.com/wordpress-mobile/WordPress-Android/pull/15595) (reproduced in 18.7 release so it doesn't seem related to that PR specifically).

In the reader threaded comments screen, we noticed [the following](https://github.com/wordpress-mobile/WordPress-Android/pull/15595#pullrequestreview-813914716):

>[...] once you try to reply to a comment when you actually wanted to reply to the post, there seems not to be a straightforward path to come back to reply to the post. What worked for me was to dismiss the keyboard, wonder if we should consider coming back to reply to post if selecting again to reply on an already highlighted post

as an additional (and possibly related) [note](https://github.com/wordpress-mobile/WordPress-Android/pull/15595#issuecomment-977472728):

>If you dismiss the keyboard when in a full-screen reply window, and collapse the window you are stuck with the reply to comment.

cc @mattmiklic

**Comment by mattmiklic** [comment]
What I'd thought about here was allowing the user to tap the Reply button on the selected comment (the one that's being replied to) to un-highlight that comment and switch the reply back to "Reply to post."
