### ISSUE TITLE
My Site Dashboard - Phase 2 - Gather and Analyze Usage Data then Create Post with Findings

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15738]
Parent: #15198

After the feature flag has been enabled and this feature started running on production for a couple of sprints, the goal of this task is to gather analytics around its usage and impact and then to create a post with findings about all that.

**Comment by ashiagr** [comment]
Analytics P2: pbArwn-3Lc-p2
