### ISSUE TITLE
My Site Dashboard: Phase 2: Metrics - Track Dashboard Card Item Taps

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#15730]
Parent #15649

Track Dashboard Card Footer Link Taps as **MY_SITE_DASHBOARD_CARD_ITEM_TAPPED** with the following properties:
- type = “post”
- sub_type = “create_first”, “create_next”, “drafts”, “scheduled””

**Comment by AliSoftware** [comment]
@zwarm I'm doing the code freeze for 19.0 today, so moving this one to milestone `19.1`.
