### ISSUE TITLE
My Site Dashboard - Stats Card - API Endpoint

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15747]
Parent: #15199
Depends On: #15755

The goal of this task is to update the [new API endpoint](D69742-code) for the new dashboard cards, adding the `Stats` dashboard cards and any other improvements (like [ordering of posts](https://github.com/wordpress-mobile/WordPress-Android/issues/15736), etc).

- [x] pc82cg-kh-p2, D73653-code @zwarm

**Comment by ashiagr** [comment]
Endpoint changes deployed in:
D75095-code
D75101-code
