### ISSUE TITLE
My Site Dashboard - Stats Card - Improve Structure

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15745]
Parent: #15199 

The goal of this task is to improve on the [initial structure](https://github.com/wordpress-mobile/WordPress-Android/issues/15215) for the dashboard card (or any leftovers from [Phase 2](https://github.com/wordpress-mobile/WordPress-Android/issues/15198)).

**Comment by ashiagr** [comment]
Initial structure improvements were not needed for adding `Today's Stats`  dashboard card.
