### ISSUE TITLE
Create multi-project aware translation task

### ISSUE THREAD

**Issue by beaucollins** [wordpress-mobile/WordPress-Android#1574]
Replace the current `tools/update-translations.sh` with a multi-project aware version.

Potentially can use the merged assets in `build/intermediates/res/FLAVOR/BUILDTYPE/values` directory.

**Comment by maxme** [comment]
We need a way to translate the main project and the sub projects. The best idea would be to open a new GlotPress project for each library so the library and its translation can be reused in multiple projects.
