### ISSUE TITLE
Projects with low Build Activity - Survey

### ISSUE THREAD

**Issue by jadsonjs** [wordpress-mobile/WordPress-Android#15770]
Dear Developers of project **wordpress-mobile/WordPress-Android **,

We are conducting a study on CI metrics and we noticed that in your project, something peculiar happened.

During the period you are using Travis CI, the project passed by a long period of inactivity.
We noticed that the TravisCI configuration file (.travis.yml) was committed to your project on the date of **2014-03-31**.
But there is only a build history in TravisCI for a very short period, between **2019-01-21** and **2019-02-04**, in which were performed suddenly **285** builds.

Please, we would like you to answer this short survey with just 4 questions to help us identify the cause of this behavior.

https://forms.gle/UkkFrxpi7MNscYmV7

**Comment by mokagio** [comment]
I filled in the survey. 

To the questions "Did the behavior described actually occur in your project? Or was it due to some inconsistency in the Travis CI database or an error in the development process?", I answered:

> From the looks of it, our build history prior to the date you reported got lost. We actively used Travis CI up till 2019/02/04. This is the pull request that disabled it https://github.com/wordpress-mobile/WordPress-Android/pull/9168. We run Travis CI and CircleCI in tandem between 2018/12/07 and 2019/02/04, see https://github.com/wordpress-mobile/WordPress-Android/pull/8743, and Travis CI only before that.
