### ISSUE TITLE
[Android] About Screen v2: Remove old AboutActivity in WPAndroid

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#15803]

**Comment by AliSoftware** [comment]
FYI: Moved this to milestone 19.1 as this is cleanup post-19.0 and the related PR #15804 [is targeting 19.1](https://github.com/wordpress-mobile/WordPress-Android/pull/15804#discussion_r780851547) too.

**Comment by AliSoftware** [comment]
Moving this again, to 19.2 as I'm doing code freeze of 19.1 today, and #15804 has now been moved to milestone `Future` since anyway.

@ravishanker @renanferrari should we move this one to `Future` as well?

**Comment by renanferrari** [comment]
@AliSoftware Thanks for the ping. In this case, I'll just remove the milestone altogether.
