### ISSUE TITLE
Strings located in `libs/editor/WordPressEditor/src/main/res/values/strings.xml` are not translated

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-Android#15822]
The strings contained in [`libs/editor/WordPressEditor/src/main/res/values/strings.xml`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/res/values/strings.xml) are not being translated.

**Code example:**
https://github.com/wordpress-mobile/WordPress-Android/blob/9d41d753eedd1c8831ccd0cdd2ff21bed1a0fa37/libs/editor/WordPressEditor/src/main/res/values/strings.xml#L131-L134
https://github.com/wordpress-mobile/WordPress-Android/blob/88b6273c092bb5e8acc2f365e72b309e4d5c0697/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java#L848-L857

### Expected behavior
All strings contained in [`libs/editor/WordPressEditor/src/main/res/values/strings.xml`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/res/values/strings.xml), except the ones marked as non-translatable, should be translated and could be found in the resource localization files.

### Actual behavior
The strings contained in [`libs/editor/WordPressEditor/src/main/res/values/strings.xml`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/res/values/strings.xml) are not translated.
**NOTE:** I noticed that some of them are translated but because they're duplicated in [`src/main/res/values/strings.xml`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml).

https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/res/values/strings.xml

### Steps to reproduce the behavior
1. Change the device's language to non-English.
2. Open a post/page.
3. Insert an Image block and add an image.
4. Open the block settings by tapping on the gear icon button.
5. Tap on "Set as Featured Image".
6. Add another Image block with a different image.
7.  Open the block settings by tapping on the gear icon button.
8. Tap on "Set as Featured Image".
9. Observe that the popup message is not translated.

##### Tested on Samsung Galaxy S20 FE 5G, Android 10, WPAndroid 18.9
<img src=https://user-images.githubusercontent.com/14905380/149517095-094ad219-45c7-4ffb-ad47-e701cc903aef.jpg width=350>

**Comment by mchowning** [comment]
Thanks for reporting this @fluiddot . I'll take a look at this next week.

**Comment by fluiddot** [comment]
Following up https://github.com/wordpress-mobile/gutenberg-mobile/issues/4432, this issue will also address the following remaining untranslated strings:

**Replace featured image popup:**
- `Featured Image Already Set`
- `You already have a featured image set. Do you want to replace it?`
- `Replace`
- `Cancel`

**Featured image updated notice messages:**
- `Set as featured image`
- `Removed as featured image`

**Comment by mchowning** [comment]
Work on this ended up getting bumped due to other priorities. I'll keep it on my radar, but I'm removing my assignment for now.

**Comment by AliSoftware** [comment]
There's a strong possibility that [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16231) will solve this issue (which I discovered was logged here only minutes ago, thanks to Matt for uncovering it) 🎉

**Comment by thehenrybyrd** [comment]
@AliSoftware looks like that worked! I tested today, and if I change the app's language, I get a translated message when trying to replace a Featured Image. I'll close this issue, we can reopen if we find we're still missing strings from that file.
