### ISSUE TITLE
Draft Post screen inconsistency between Android and iOS

### ISSUE THREAD

**Issue by jostnes** [wordpress-mobile/WordPress-Android#15843]
### Expected behavior
The buttons displayed on Draft posts screen should be consistent between Android and iOS. Discussed here: p5T066-2Vl-p2#comment-11021

### Actual behavior
The behavior on Draft posts screen is not consistent between Android and iOS. On Android it's `Publish` where the user would end up publishing the post when tapped, on iOS it's `Update` where the user would remain on the post

### Steps to reproduce the behavior
1. Create a post and save it as a draft
2. Go to Drafts tab under Posts screen
3. Open one of the draft posts for editing
4. See that on Android the top right button is "Publish", on iOS, the top right button is "Update"

On Android:
![android draft post](https://user-images.githubusercontent.com/17252150/150510789-565ebe04-445a-4916-bab4-cebd0225040d.jpg)

On iOS:
![ios draft post](https://user-images.githubusercontent.com/17252150/150511307-7d7f34cc-f42d-4ba6-b427-a80ac9129106.PNG)

##### Tested on [device], Android [version], WPAndroid [version]
Tested on Oppo Reno6 Z, Android 11, WP 19.0

---
Edit: I added step to the repro scenario, after step 2.

**Comment by thehenrybyrd** [comment]
When we consider which direction to go with this, considering what users expect in various cases will be important.
Here's one instance of confusion, when a post was recently Scheduled but is now a Draft: https://github.com/wordpress-mobile/WordPress-Android/issues/15617

**Comment by AjeshRPai** [comment]
This is fixed in the current version of the app. Both Android and IOS shows publish on the toolbar.
