### ISSUE TITLE
Stats: Dark spots on the Countries map

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#15849]
Originally reported in 4706077-zd-woothemes.

### Expected behavior

I would expect to see consistent markings on the Countries map in the WPAndroid app and Calypso/WPiOS.

### Actual behavior

The user reported seeing dark/black spots in the Countries map on the Stat screen in the WPAndroid app. I can reproduce this in SSP on WPAndroid but the issue is not happening on WPiOS.

### Steps to reproduce the behavior

1. SSP to the site linked in the ticket
2. Go to My Site > Stats and tap the "DAYS" tab
3. Tap the "<" button to view the stats on 21 Jan 2022
4. Noticed there are some black/dark spots on the Countries map near India
5. Check the site's stats on Calypso or WPiOS, notice the discrepancy of the marking on the map.

**Screenshot on WPAndroid**

![Markup on 2022-01-24 at 11_08_27](https://user-images.githubusercontent.com/40906847/150728791-b4fbe3c4-decd-4f00-8c1b-6e92896487b8.png)

**Screenshot on Calypso**

![Markup on 2022-01-24 at 11_04_42](https://user-images.githubusercontent.com/40906847/150728824-479fdcc3-bd63-4782-8a39-65380705e5ef.png)

**Screenshot on WPiOS**

![IMG_458B4F5E02F8-1](https://user-images.githubusercontent.com/40906847/150728845-1b382865-6425-4614-bd2b-4f826a3d0019.jpeg)

##### Tested on Pixel 4 (Android emulator), Android 10, WPAndroid 18.9

**Comment by ravishanker** [comment]
This is still showing at the same spot.   Suspect that it is an overlapping gray lines appearing darker due to smaller size on map on mobile.  This is actually a embedded WebView, and have little control over it. 

This Geo is going to be revamped p1HpG7-rnS-p2  Probably not worth fixing it now.

**Comment by guarani** [comment]
Thanks for reproducing. I'm closing as won't fix since we're not fixing anything now.
