### ISSUE TITLE
My Site Dashboard - Remove "No Content" text in a draft post card

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#15850]
### Expected behavior

`My Site Dashboard - Draft Post Card` should not display `No Content` in the preview for a post with a non-featured image and nothing else in the body. 

### Actual behavior
`My Site Dashboard - Draft Post Card` displays `No Content` in the preview for a post with a non-featured image and nothing else in the body. 

### Steps to reproduce the behavior

- Create a draft post.
- Add a non-featured image to the post and nothing else to it.
- Go to `My Site Dashboard`.
- Notice that the `No Content`  is shown in the corresponding draft post card.

**Comment by ashiagr** [comment]
`No Content` is not shown in the posts screen for a post item (for both featured and non-featured images). So perhaps it makes sense to remove the `No Content` text from the draft post card to match it. I'll create a PR removing the text until we can come up with a better solution.

cc @startuptester, @osullivanchris

**Comment by AliSoftware** [comment]
I'm moving this to milestone 19.2 given that I'm doing the 19.1 code freeze today.
