### ISSUE TITLE
JSApplicationIllegalArgumentException: Error while updating property 'text' of a view managed by: RCTAztecView

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15876]
**Sentry Url**: https://sentry.io/share/issue/0b0f4f57de494b18ac35163cf4b7037a/
**User Count**: 21
**Count**: 109
**First Release**: 19.0
**First Seen**: 2022-01-28T16:48:22.458000Z
**Last Seen**: 2022-01-31T16:07:17Z
**24 Hours**: 40
**30 Days**: 112

```
JSApplicationIllegalArgumentException: Error while updating property 'text' of a view managed by: RCTAztecView

...
(17 additional frame(s) were not displayed)
```

@develric This seems very low in user count right now so probably low priority… but still wanted to report it here because it's new in 19.0, which got a very late rollout due to Google taking time approving it, so that might explain the low numbers. So probably worth keeping an eye on this one during the upcoming days to check if it evolves as 19.0 adoption grows.

**Comment by develric** [comment]
Hey @AliSoftware , yep I agree current numbers are pretty low but worth monitoring since it's a new crash 👍 ! I see there are a few changes related to the editor in the release notes for 19.0; trying to ping @antonis and @hypest if you or someone else on your teams can have a look since the issue seems editor-related. Thanks for the help and let us know 🙇 

PS: I'm keeping the Requires Triage label for now while we monitor it and figure out the possible cause and impact of the issue.

**Comment by hypest** [comment]
Thanks for the ping @develric !

Based on the stacktrace (`Unknown color` error in `ReactAztecManager`) it does look editor related at this point. @geriux is taking a quick look to gather information and help assess/triage.

**Comment by hypest** [comment]
Update: @geriux has investigated and found the culprit, and a [fix PR is in the making](https://github.com/WordPress/gutenberg/pull/38417).

**Comment by geriux** [comment]
> Update: @geriux has investigated and found the culprit, and a [fix PR is in the making](https://github.com/WordPress/gutenberg/pull/38417).

The fix ended up shipping in https://github.com/WordPress/gutenberg/pull/38474

The [other PR](https://github.com/WordPress/gutenberg/pull/38417) will follow up with some improvements.

**Comment by thomashorta** [comment]
Just a heads up that this happened again in version `24.7`, though it seems to have affected only 1 user so far.

@geriux can you check if it's worth opening a new GH issue for it?

https://a8c.sentry.io/share/issue/cc84004acd0d430e840711b53ae786d9/

**Comment by geriux** [comment]
Hey 👋 

After checking the logs, it appears it's related to adding `Mark` tags without color, this has been addressed in https://github.com/wordpress-mobile/AztecEditor-Android/pull/1080 let's monitor after this change is released to see if this issue stops being reported.
