### ISSUE TITLE
When sharing multiple images the images are added to the post twice

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15873]
### Expected behavior
When sharing multiple images  from an external app the images should be added once to the post

### Actual behavior
When sharing multiple images from an external app the images are added to the post twice

### Steps to reproduce the behavior

1. Open Files/Photos and select multiple images
2. Tap the Share icon in the bottom menu bar.
3. Select WordPress, then choose a site to share to.
4. Select "Add to new post".
5. *Notice* that images are added twice to the post

<details>
<summary>Sharing multiple images</summary>

https://user-images.githubusercontent.com/304044/151398175-863ebe71-7449-4958-982c-91931e000cd0.mp4
</details>

**Comment by hypest** [comment]
👋 Antonis, thanks for the ticket!

I wonder if this is related to a ticket we are wrangling as we speak (though for videos on the gallery block). Perhaps you can try the [installable build from the fix PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15870#issuecomment-1024403298) to see if it happens for you with it. I tried sharing 2 photos from the Google Photos app and works OK for me with that apk.

**Comment by antonis** [comment]
Thank you for the ping @hypest 🙇 
I confirm that with the [installable build from the fix PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15870#issuecomment-1024403298) I cannot reproduce the issue.
I also applied those changes on the latest `trunk` that [included a related fix I merged earlier](https://github.com/wordpress-mobile/WordPress-Android/pull/15864) and everything works as expected on my test debug build.
I'm assigning the issue to @ravishanker and you to be closed with https://github.com/wordpress-mobile/WordPress-Android/pull/15870 or https://github.com/wordpress-mobile/WordPress-Android/pull/15872

**Comment by hypest** [comment]
Closing as https://github.com/wordpress-mobile/WordPress-Android/pull/15872 got merged 👍
