### ISSUE TITLE
Stats endpoints are being called twice

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#15906]
We seem to be making duplicate requests on some of the Stats tabs.

Here is log of the calls being made on the Insights tab:
<img width="1045" src="https://user-images.githubusercontent.com/830056/152621132-5d33fc0c-036d-469f-a05a-9a040938b656.png">

And here is log for the Weeks tab:
<img width="1039" src="https://user-images.githubusercontent.com/830056/152621138-1826deae-99e8-4497-b7ef-b03ebc71138f.png">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
