### ISSUE TITLE
Translation on Join us in the About screen 

### ISSUE THREAD

**Issue by annchichi** [wordpress-mobile/WordPress-Android#15917]
### Expected behavior
Change the text to "加入我們"

### Actual behavior
In the About screen, I noticed that at the bottom, it says "join us," the translation in traditional Chinese feels like it's for business collaboration rather than to join to work with us. It might be great to adjust to this "加入我們"

### Steps to reproduce the behavior
Me > About WordPress 

##### Tested on [device], Android [version], WPAndroid [version]
Tested on Pixel 5, Android 12, WPAndroid 19.2-rc-1 (1166)

![CleanShot 2022-02-09 at 14 53 54@2x](https://user-images.githubusercontent.com/13378873/153138391-ed7b313c-5ae3-433d-a4d9-26cda4322529.png)

**Comment by thehenrybyrd** [comment]
@annchichi given our conversation in Slack, it sounds like you were able to add this suggestion on GlotPress. :) 
I'll go ahead and close this issue.
