### ISSUE TITLE
Post Settings: Blurred Featured Image

### ISSUE THREAD

**Issue by erricgunawan** [wordpress-mobile/WordPress-Android#15926]
### Expected behavior

Featured Image should not be blurred when previewing it in the Editor > Post Settings.

### Actual behavior

It's blurred:

![Screenshot_20220209_150137_org wordpress android](https://user-images.githubusercontent.com/1813857/153333412-7c94b41b-c32e-4c0a-b3c3-9d8cecb053ab.jpg)

### Steps to reproduce the behavior

1. Create a new post (or open an existing one to edit it).
2. Tap Menu > Post settings
3. In the Featured Image section, observe the blurred image.
4. If the post didn't have a Featured Image yet, tap "Set Featured Image".
5. Choose any images, either uploading a new one or choose from Media Library
6. The image would be blurred there. However, in the actual post itself, the image is fine. 

Might be worth to note this happens only on Atomic sites. 

When I tested on simple sites, I (think) it's not blurred there.

##### Tested on Redmi Note 9 Pro, Android 11, WPAndroid 19.1 (1165)

**Comment by erricgunawan** [comment]
Got the report from 4725331-zen

**Comment by thehenrybyrd** [comment]
I'm able to reproduce this in **WP 19.6 on Samsung Galaxy S21, Android 12**.
