### ISSUE TITLE
When sharing large videos the editor remains blank for a while

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15950]
### Expected behavior
When sharing videos from the device’s gallery, the editor screen loads instantly.

### Actual behavior
When sharing videos from the device’s gallery, the editor screen remains blank for a while(depending on size of video) before the video appears correctly in the block editor.

### Steps to reproduce the behavior
1. Open Files and select a video by tapping it.
2. Tap the Share icon in the bottom menu bar.
3. Select WordPress, then choose a site to share to.
4. Select "Add to new post".
5. **Notice** that the editor screen may remain blank for a while

##### WPAndroid `19.2`

Context `p5T066-2Yv-p2#comment-11254`

**Comment by ravishanker** [comment]
I've tried this a few times.  Even with a very large video (~ 2GB) as in the video below.  I noticed that the time between tapping share and opening WordPress app is long (understandably given the size) depending on the size of the video.  For e.g. ~10MB file opens quickly, while ~100MB file takes a few seconds and ~2GB take a few more seconds as in video below.  Once opened the editor screen doesn't really show blank  though as described in the issue.

https://user-images.githubusercontent.com/990349/158918917-92a71b36-22aa-442d-8c2f-8db8fb11553e.mov

I'm going to close this as I'm not sure if anything required to be fixed here on the WordPress app front.

Please re-open this with more specifics like size of the file and some detailed steps including some screen shots and video if possible
