### ISSUE TITLE
Login with a saved account + 2FA can cause a login loop

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-Android#15997]
### Expected behavior
After selecting a saved account, I should be able to go back an change the account being logged in.

### Actual behavior
Any attempt to go back retries logging in with the saved account.

### Steps to reproduce the behavior
- Select a saved account from the Google Smart Lock list.
- On the 2FA code entry view, tap back on the nav bar. 
- The email/password view is shown with the `Logging in` message displayed, then the code entry view is displayed again.
- Every attempt to go back does the same thing, until finally a message is displayed that the number of login attempts is exceeded.

**Comment by AliSoftware** [comment]
I think this is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/14950

Encountered this again recently while switching accounts during smoke testing when I fat-fingered and tapped on the wrong account on smart lock selector and tried to go back on 2FA screen. Very annoying.

**Comment by irfano** [comment]
Duplicate of #14950
