### ISSUE TITLE
[Site Intent Question] Display default verticals

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#15998]
### Description

A new screen has been added to the site creation flow. It will display ~20 default verticals that will either:
- be bundled with the app
- ~~or, be fetched from the verticals WP.com API: [`wpcom/v2/verticals`](https://public-api.wordpress.com/wpcom/v2/verticals) (TO-DO: link to separate issue)~~

Other considerations:
- Each vertical, when tapped, should send the vertical's ID to Tracks and navigate the user next screen (the "Choose a design" screen).
- ~~The verticals are English-only~~ The verticals will be localized
- Each vertical will have an associated emoji
- The screen will have a search input ~~but its functionality will be done in a separate issue (TO-DO: link to separate issue)~~
- The screen will have a "Skip" button that will also send a Tracks event
- This screen should only appear on dev-builds (until the feature is released)

This issue is UI-only and can be considered Done when the screen looks and behaves like the design below. ~~Dummy data can be used since API integration is a separate issue. The search input should be visible but not functional.~~

_Note: All development should be behind [the feature flag `SITE_INTENT_QUESTION`](https://github.com/wordpress-mobile/WordPress-Android/issues/16018)_

### Latest design

The latest design found below covers the updated site creation flow.

<img src="https://user-images.githubusercontent.com/1898325/155761319-a642b5fe-2c07-439f-8354-85ad3288a9c0.png" alt=""> 

The scope of this issue is the "Choose a site topic" screen:

<img width="250" alt="Screen Shot 2022-02-25 at 14 48 14" src="https://user-images.githubusercontent.com/1898325/155762853-5d659d5b-8d49-41dd-a2dd-8b4feb87c83b.png">

### Issue Breakdown:
- [x] #16051
- [x] #16052
- [x] #16053
  - [x] #16127
- [x] #16157  
- [x] #16165

**Comment by guarani** [comment]
👋 Hi @ovitrif, I've updated the issue description due to the recent decision to not use the verticals API but instead use bundled and localized verticals. Of course, please feel free to further edit the description or split this issue up as needed into separate issues.

**Comment by ovitrif** [comment]
Thank you @guarani! 🙇

**Comment by ovitrif** [comment]
I propose to further split this issue in the following deliverables (issues):

### 1. Display empty Site Intent Question screen in Site Creation Flow

  - [ ] The screen is displayed **only** when the `SITE_INTENT_QUESTION` feature flag is enabled
  - [ ] Header (Back button, Skip Button, Title & Subtitle) is displayed
    - [ ] Skip Button tap → Navigates to "Choose a Design" screen
    - [ ] Back Button tap →Navigates back
      - [ ] "Choose site" screen if logged in
      - [ ] "Welcome to WordPress" screen if not

### 2. Display list of default verticals on the Site Intent Question screen

  - [ ] [Default Verticals](pbArwn-3Qf-p2#default-verticals) are bundled in the app
    - [ ] The name of each vertical is localized
  - [ ] List of verticals is displayed
    - [ ] A list item is displayed as such:
      - [ ] Emoji icon in a gray circle
      - [ ] Name of the item with bold font weight
    - [ ] List item tap → Navigates to "Choose a Design" screen

### 3. Enable searching through default verticals on the Site Intent Question screen

- [ ] Search input is displayed above the verticals list
  - [ ] Placeholder with examples is displayed inside search input
- [ ] Search input tap (focus) → hides Title & Subtitle in Header (parallax slide down transition)
- [ ] Search input typing:
  - [ ] Updates the list to show only verticals matching the search term
    - [ ] Search result list items
      - [ ] Emoji icon is **not** displayed
      - [ ] Characters matching the search term are displayed with a **bold** font weight in item name
    - [ ] Continue button shows above keyboard
      - [ ] Continue button tap → Navigates to "Choose a Design" screen
  - [ ] Shows blank white surface when no matches are found
  - [ ] Search result list item tap → Navigates to "Choose a Design" screen
  - [ ] Search input empty:
    - [ ] Placeholder with examples is displayed inside search input
    - [ ] All verticals are displayed as if the search input is not focused
    - [ ] Continue button is hidden

@kyleaparker Can you please confirm that my understanding of the UI & UX is correct?

**Comment by antonis** [comment]
Those LGTM @ovitrif 👍 
I just a note that my understanding is that this screen will come before the "Choose a Design" screen for now. This means that all forward navigation actions will lead to the "Choose a Design" and not the "Choose a domain" screen.
When we implement the "Give your website a name" (that will replace the "Choose a domain" screen) in a next project this will change.

**Comment by ovitrif** [comment]
> Those LGTM @ovitrif 👍 I just a note that my understanding is that this screen will come before the "Choose a Design" screen for now. This means that all forward navigation actions will lead to the "Choose a Design" and not the "Choose a domain" screen. When we implement the "Give your website a name" (that will replace the "Choose a domain" screen) in a next project this will change.

Thank you Antonis 🙇 , I updated the comment with the correct info about navigating to the "Choose a Design" screen!

**Comment by kyleaparker** [comment]
> @kyleaparker Can you please confirm that my understanding of the UI & UX is correct?

@ovitrif this all looks good to me!

**Comment by kyleaparker** [comment]
>I just a note that my understanding is that this screen will come before the "Choose a Design" screen for now. This means that all forward navigation actions will lead to the "Choose a Design" and not the "Choose a domain" screen.
When we implement the "Give your website a name" (that will replace the "Choose a domain" screen) in a next project this will change.

This is correct 👍

**Comment by ovitrif** [comment]
@guarani I created 3 issues for tackling this and added reference to them at the end of the description 🎉

**Comment by ovitrif** [comment]
I added [#16165](https://github.com/wordpress-mobile/WordPress-Android/issues/16165) to the issue breakdown sections

**Comment by antonis** [comment]
Closing this as all the subtasks are complete
