### ISSUE TITLE
My Site Dashboard: Tabs - Pull-to-refresh

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#16004]
Parent #15989 

It has not been decided if PTR will remain within both tabs or as a single unit.

The goal of this task is to refactor pull-to-refresh within the My Site Fragment

- [ ] Move `SwipeRefreshLayout` to the root of `my_site_fragment`
- [ ] Implement as a single unit across tabs
- [ ] Handle animation between tabs
- [ ] Refactor/write unit tests

**Comment by ashiagr** [comment]
We decided to keep the existing functionality of pull-to-refresh (remain within both tabs), requiring no changes hence closing the issue.
