### ISSUE TITLE
My Site Dashboard: Tabs - Enable feature flag

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#16008]
Parent #15989 

The goal of this task is to enable the feature flag for My Site Dashboard - Tabs: `MySiteDashboardTabsFeatureConfig`

PS: Make sure to trigger the connected test and verify correctness.

**Comment by J569-del** [comment]
No entiendo el inglés, como no lo publiquéis en Español, no me entero de nada.
