### ISSUE TITLE
Jetpack App: Auto-dismiss keyboard when the error screen is displayed

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#16023]
### Expected behavior
While logging in via site address in the Jetpack app, when the error screen is displayed, the keyboard should auto dismiss.

### Actual behavior
While logging in via site address in the Jetpack app using a site that leads to the error screen with the message “need to have the Jetpack plugin installed…”, the keyboard covers the error.

### Steps to reproduce the behavior

1. Open `Jetpack` app.
2. Click "Enter your existing site address" on the `Landing` screen.
3. Enter a self-hosted site (without Jetpack) on the `Log In` screen.
4. Click `Continue`.
5. Notice that the keyboard does not dismiss and tapping the screen above the keyboard doesn’t lower the keyboard. One needs to scroll to read the full error and find the options buttons.

See `To Test: version 19.3-rc-1` comment for more details: p5T066-31e-p2#comment-11484

##### Note: This was not reproducible on `Pixel 5`, `Android 5` device,  so it could be a device-specific issue.

**Comment by thehenrybyrd** [comment]
Thanks @ashiagr!

For more context, this was initially tested on a **Samsung Galaxy S21, Android 11** device. 

https://user-images.githubusercontent.com/15107387/156173277-5ac668eb-b759-490b-88f2-7ce98ba44162.mp4

**Comment by ashiagr** [comment]
This issue is reproducible on `Android 11`, see p5T066-31e-p2#comment-11507 for more details.
