### ISSUE TITLE
Move Site header to app bar

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16031]
Parent #16002 

Todo 
- [ ] Collapsed view - site title animates into toolbar
- [ ] Expanded view - fully shown section (icon, title, url, site selector)
- [ ] Maintain smooth parallax scrolling
- [ ] Site header with tabs on feature flag enabled 
- [ ] Site header with no tabs on feature flag disabled 
- [ ] Empty Site header on No sites

**Comment by thehenrybyrd** [comment]
Hi @AjeshRPai!
Can you put appropriate labels on this issue? That helps me know I don't need to triage it since it's part of an on going project.
Thanks!
