### ISSUE TITLE
Android 12: User experience - Web intent resolution

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#16095]
Parent #16062

[Web intent resolution](https://developer.android.com/training/app-links/verify-site-associations)

The goal of this issue is to verify [Android App Links](https://developer.android.com/training/app-links/verify-site-associations) in the app.

**Comment by kopax-polyconseil** [comment]
Hello @ashiagr , just curious, did you find how to fix the android 12 web intent resolution so it's automatic ? Thanks for sharing !

**Comment by ashiagr** [comment]
Sorry for the late reply, @kopax-polyconseil. We followed the instructions from the [official documentation](https://developer.android.com/training/app-links/verify-site-associations) to get it working. Let us know if you're looking for a resolution to any specific error. 🙏

**Comment by ashiagr** [comment]
Closed via https://github.com/wordpress-mobile/WordPress-Android/pull/16696
