### ISSUE TITLE
My Site Dashboard: Tabs - Implement Feature Annoucement

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#16181]
Parent: #15989 

Implement the feature announcement for tabs using the standard layout.

**Comment by osullivanchris** [comment]
Here's the design for the Android My Site feature announcement

- I've requested a copy review [on the iOS issue](https://github.com/wordpress-mobile/WordPress-iOS/pull/18231)
- May or may not have a 'Find out more' blog link 
- The images are circles with colors (celadon 40, purple 40) from [color studio](https://color-studio.blog/) and icons from [Grid Icons ](https://github.com/Automattic/gridicons). But I can make SVG/PNG of just icon, or icon+circle if needed
- Heading 1: My Site Home
- Body 1: My Site has a new home tab that shows you up-to-date highlights from your site.
- Heading 2: You can still access your menu
- Body 2: Switch between your home and menu tabs any time.


![android announcement final copy](https://user-images.githubusercontent.com/50576199/160799367-c5598f76-56e9-436c-a776-21a8204ecafb.png)

**Comment by osullivanchris** [comment]
- Received [final copy from editorial](https://github.com/wordpress-mobile/WordPress-iOS/pull/18231#issuecomment-1082266339)
- Updating [my above comment](https://github.com/wordpress-mobile/WordPress-Android/issues/16181#issuecomment-1082008355) now to use the final copy in the description and image
