### ISSUE TITLE
Fix the toolbar height and margin

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16219]

**Comment by AliSoftware** [comment]
FYI, Moved the milestone of this issue to `19.7` since I'm doing the code freeze of `19.6` today 🙂

**Comment by AjeshRPai** [comment]
@AliSoftware This issue was closed with the PR https://github.com/wordpress-mobile/WordPress-Android/pull/16217. Sorry for not closing this issue earlier.
