### ISSUE TITLE
Unfollow error and follow/following button inconsistencies

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1623]
1. Unfollow a blog
2. On unfollow failure, taped button resets to "Following"
3. Notice other follow buttons on other posts from the same blog doesn't reset

See: https://cloudup.com/ctWNASPEICX

Note: surely a server issue, unfollowing a RSS feed fails almost everytime.

**Comment by nbradbury** [comment]
I should've closed this a while back as it's no longer an issue.
