### ISSUE TITLE
Quick Start for Existing Users V2  - User is not guided to the proper tab to see the current focus point.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#16288]
Parent #16347 

### Expected behavior
I would expect to se a focus point on the tab I need to go to complete the current Quick Start task.

### Actual behavior
There is no indication, for certain tasks, that the user needs to switch tabs to see the focus point and complete the task.

In a few tasks, if the user change tabs during the completion of the tasks (it could be either intentionally or accidentally) we are not indicating that the current focus point is in the other tab as we do for some of the tasks like `Customize your site > Visit your site`.

The issue will only happen when a tab different from the Initial Screen is selected before the user clicking `GO` to start the affected tasks. The issue is not reproducible when selecting a specific task from the list, since Quick Start card will only appear in the selected Initial Screen.

Impacted tasks identified so far: 
* `Customize your site > Edit your homepage`
* `Customize your site > Review site pages`
* `Grow your audience > Check your stats`

Expected behavior (reference task): `Customize your site > Visit your site`

### Steps to reproduce the behavior
Initial Screen: `Site Menu`
1. Complete `Customize your site > Check your site title`.
2. Tap `GO` to start the next task.
3. Complete `Customize your site > Choose a unique site icon`.
4. Tap `HOME` tab.
5. Tap `GO` to start the next task.
6. ❌  Notice that no focus point is displayed.
7. Tap `SITE MENU` tab.
8. Notice that the focus point is displayed over `Pages` quick link.

Initial Screen: `HOME`
1. Complete `Customize your site > Check your site title`.
2. Tap `GO` to start the next task.
3. Complete `Customize your site > Choose a unique site icon`.
4. Tap `SITE MENU` tab.
5. Tap `GO` to start the next task.
6. ❌  Notice that no focus point is displayed.
7. Tap `HOME` tab.
8. Notice that the focus point is displayed over `Pages` quick link ribbon card.

**Comment by ashiagr** [comment]
This issue seems to have been resolved after adjusting focus points for `Stats` and `Pages` to point to site list items similar to iOS in #16338.

**Comment by tiagomar** [comment]
Yep, it was resolved. I'll close this one. Thanks @ashiagr!

**Comment by AjeshRPai** [comment]
@tiagomar  👋🏼 

As part of the changes for Quickstart for Existing Users V2, [focus points were added in the quick link ribbon](https://github.com/wordpress-mobile/WordPress-Android/pull/16361), which will re-introduce this bug. I have added it as a known issue in the [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16361), and plan to take it up as a separate issue. 

cc: @ashiagr
