### ISSUE TITLE
[Blogging prompts v1] Implement dismiss action in existing local notification boilerplate.

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#16295]
We should add a dismiss action in existing local notification boilerplate, and implement it to both blogging prompts notification types (onboarding and daily prompt).

**Comment by thehenrybyrd** [comment]
@RenanLukas is this a task? If so can you label it with the `[Type] Task` and a feature label?
Labeling project tasks helps me see clearly what things in the queue are issues I need to triage :) Thanks!
