### ISSUE TITLE
Change tab title from Site menu to Menu

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16305]
Parent #15989

Change tab title from Site menu to Menu. 

Do not forget to change the "App Setting" for Initial Screen. Check for places that use the initial screen pref as "Site Menu" and doing comparisons agains MySiteTabType. You might need an explicit conversion when it comes to using "site_menu" in tracking events. Take a look at what was done for "home" and "dashboard" .

Reference 
pbArwn-4jn

**Comment by AjeshRPai** [comment]
>You might need an explicit conversion when it comes to using "site_menu" in tracking events.

@zwarm I have not implemented any changes for the tracking keyword we use, I felt that the tracking can be done using the "site_menu" keyword itself for **Menu** tab as we are using the "dashboard" keyword for **Home** tab. Do you think we should make that change now?. 🤔 . 

If we need to make that change, I believe we should change both the keywords, `dashboard` and `site_menu` to `home` and `menu`. WDYT.

**Comment by zwarm** [comment]
@AjeshRPai - The value for tracking should stay as  "site_menu" and "dashboard". Just validate that this is still the case after your changes. 🙇
