### ISSUE TITLE
Better "back" navigation after EditPostActivity is launched by ShareIntentActivity

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1637]
When we share an image with wpandroid, it opens a new EditPostActivity, hitting back here closes the app. We want to land on the postlist activity when hitting back.

**Comment by jstart** [comment]
Trying to make sure I understand this request, so correct me if I am wrong.
A user shares an image and it opens ShareIntentRecieverActivity which then opens EditPostActivity if the app has a blog for the logged in user.  Current behavior is that you press back button on the EditPostActivity and the app closes.  Desired behavior is that pressing back navigates you to the PostsActivity.

If this is the desired behavior, should we use 'android.support.PARENT_ACTIVITY' to specify which to go back to?  OR should we create the intent with a back stack from the ShareIntentRecieverActivity something like this:

```
Intent detailsIntent = new Intent(this, EditPostActivity.class);

// Use TaskStackBuilder to build the back stack and get the PendingIntent
PendingIntent pendingIntent =
        TaskStackBuilder.create(this)
                        .addNextIntentWithParentStack(upIntent)
                        .getPendingIntent(0, PendingIntent.FLAG_UPDATE_CURRENT);
````
Copied from: http://developer.android.com/training/implementing-navigation/temporal.html

**Comment by jstart** [comment]
My simple 'android.support.PARENT_ACTIVITY' attempt PR #2156

**Comment by maxme** [comment]
Yes, the problem is:

1. Share an image or text with WordPress
1. Switch to another app
1. Reopen WordPress and you're stuck on `EditPostActivity` (if you go back you close the app and if you come back, you're still on `EditPostActivity`, only solution is to publish or force close the app).

Adding a `PARENT_ACTIVITY` to `EditPostActivity` should work.

**Comment by maxme** [comment]
Closed via https://github.com/wordpress-mobile/WordPress-Android/pull/2156
