### ISSUE TITLE
[Site Design Revamp] Main View Updates

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#16392]
## Description

Update the initial site design screen shown on site creation for the Site Design Screen Improvements project.

<img src="https://user-images.githubusercontent.com/2092798/165140160-64c88e80-bcf7-497b-8589-8cf5c156521d.png" width="350px" />

This task can be broken down into multiple PRs. PRs should target the `feature/site-design-revamp` feature branch.

- [x] **A** Remove preview mode selector from nav bar
  - [x]  `enhanced_site_creation_site_design_thumbnail_mode_button_tapped` event
  - [x] Always show mobile thumbnails on all platforms
  - [x] The preview view should no longer update the device mode on the main view
- [x] **B** Rename title from “Choose a design” to “Choose a theme”
- [x] **C** Remove subtext (“Pick your favorite homepage layout…”) and assess if it should become an accessibility hint
- [x] **D** Remove category filter pills
- [x] **E** Remove primary and secondary button functionality (Preview / Create Site)

**Comment by mkevins** [comment]
Closing as completed. :heavy_check_mark:
