### ISSUE TITLE
Tapping a widget should load the Stats view for the corresponding site

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#16412]
### Expected behavior
- Tapping the widget loads the Stats view for the corresponding site

### Actual behavior
- Tapping the widget loads the Stats view for the currently selected site in the app

### Steps to reproduce the behavior
Prerequisites:
- An account logged into the app with at least two existing Wordpress (.com or connected to Jetpack) sites

Steps:
1. Add two widgets to the Home Screen, one for each site - Site A and Site B
2. Tap the widget for Site A
3. Observe the Stats view
4. Back on the Home Screen, tap the widget for Site B
5. Observe that the Stats view hasn't changed

**Comment by twstokes** [comment]
Related WPiOS issue:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/18452

**Comment by guarani** [comment]
👋 @twstokes Regarding the issue title, would changing it to:

> Tapping a widget _should load_ the Stats view for the corresponding site

be better?

**Comment by twstokes** [comment]
> 👋 @twstokes Regarding the issue title, would changing it to:
> 
> > Tapping a widget _should load_ the Stats view for the corresponding site
> 
> be better?

I think so! Updated. Thanks @guarani. 🙇

**Comment by irfano** [comment]
I followed the testing instructions and couldn't reproduce the issue. The issue was reported 2 years ago and has likely already been fixed.

[widgets.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/fca8383a-445a-4c70-86ca-cb2e67a2b74b)
