### ISSUE TITLE
My Site Dashboard: List Scrolling positions are not maintained 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16436]
### Actual behavior
My Site dashboard(Home and Menu tab) List view positions should be maintained after changing the bottom tabs

### Expected behavior
The Scrolling position of the user should be maintained even after switching to a new tab 

### Steps to reproduce the behavior
- Login to the App
- Open My Site tab and Scroll to a position on either tab 
- Navigate to Reader tab 
- Open My Site tab 
- Notice that the My Site(Home and Menu) tab scrolls to the top

##### Tested on [device], Android [version], WPAndroid [version]
Oneplus Nord, Android 11

**Comment by hmncube** [comment]
I am working on this.

**Comment by debojyoti452** [comment]
https://app.gitstart.com/clients/wordpressandroid/tickets/WPA-89
