### ISSUE TITLE
[Site Design Revamp] Main View - Add helper text to bottom

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#16478]
## Description

Add localized helper text to the bottom of Main View of the Site Design picker.

<img src="https://user-images.githubusercontent.com/2092798/166721005-a8400446-5fa3-42ff-a4de-b230d672d633.png" width="350px" />

**Comment by antonis** [comment]
Closed with https://github.com/wordpress-mobile/WordPress-Android/pull/16555
