### ISSUE TITLE
Quick Start showing Plans item despite app not showing plan information

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#16477]
### Expected behavior

The "Grow your audience" Quick Start screen should not show an "Explore plans" item. (The plans screen was removed in https://github.com/wordpress-mobile/WordPress-Android/issues/16471, but removing the corresponding Quick Start item was overlooked.)

### Actual behavior

The "Grow your audience" Quick Start screen shows an "Explore plans" item.

#### New site
1. Log in to the app
2. Create a new site
3. On the My Site tab, open the Menu
4. Tap "Grow your audience" 
5. Notice "Explore plans" is shown
6. Tap "Explore plans"
7. Notice the toast "Tap <icon> Plans to see your current plan and other available plans"

#### Existing site
1. Log in to the app
2. Locate an existing site that has not completed its Quick Start steps
3. On the My Site tab, open the Menu
4. Tap "Grow your audience" 
5. Notice "Explore plans" is shown
6. Tap "Explore plans"
7. Notice the toast "Tap <icon> Plans to see your current plan and other available plans"

### Additional information

As @zwarm ([internal reference](p1651671871579959/1651587009.445519-slack-C011BKNU1V5)) mentions:

> it's a bit involved to remove the quickstart task; especially taking into account users who have started on the quick start flow.

so that must be kept in mind when addressing this issue. 

Also, as @thehenrybyrd points out ([internal reference](p1651671795976489/1651587009.445519-slack-C011BKNU1V5)), **_if_** the removal of the Plans screen is temporary, it might be best to prioritize updating the plans and showing the screen again, instead of addressing this issue.

##### Tested on Samsung Galaxy S10, Android 12, WPAndroid 19.7

**Comment by AjeshRPai** [comment]
Reopening this issue as during regression testing, we have found an issue with the `Explore plans` task removal:

Steps to reproduce:

1. Install the app having the `Explore plans` listed (E.g. from `release/19.7.1` branch). 
2. Login to the app with a quick start in progress.
3. Complete all tasks including `Explore plans` but excluding one task like `Check your stats`.
4. Install the app from the current `release/19.9` branch.
5. Notice that `Quick Start` is completed even when `Check your stats` task was incomplete.

Pinging @ParaskP7, release manager for next beta release to hold off next beta till we include a fix for this.

**Comment by ashiagr** [comment]
Closed via #16613
