### ISSUE TITLE
Locale Picker: Add secondary label with current locale in App Settings

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#16483]
As brought up at p5T066-3c9-p2#comment-12233, it'd be nice to display the app's current locale as a secondary label to the main **Interface Language** label under App Settings: 
 
<img width="1007" alt="4lwoD0is3O" src="https://user-images.githubusercontent.com/2998162/167113624-942fa41c-6aa9-457b-80f9-4074696681a2.png">

This could likely be achieved by utilising `mLanguagePreference.setSummary()` within [the `AppSettingsFragment.java` file](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java).

##### Tested on Pixel 6, Android 12, [WPAndroid 19.8-rc-2](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/19.8-rc-2)

**Comment by OkoloArt** [comment]
can I work on this issue if it hasn't yet been assigned?

**Comment by SiobhyB** [comment]
@OkoloArt, absolutely, feel welcome to assign yourself to the GitHub issue and let us know if you have any questions. :) 🙌

**Comment by OkoloArt** [comment]
@SiobhyB Thanks, I tried logging into the app using google but it returns false

**Comment by OkoloArt** [comment]
It seems to always make use of the google services example file rather than the actual one

**Comment by SiobhyB** [comment]
@OkoloArt, authenticating via Google isn't supported in developer builds, but you can find more details about logging in here: https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication

The #mobile channel in [the WordPress Slack](https://make.wordpress.org/chat/) is likely the best place to go if you have more questions that the docs don't answer (so we don't end up cluttering this GitHub issue by mistake). The whole mobile team will also be available in that channel to jump in as needs be.

**Comment by ovitrif** [comment]
The fix in #17004 adds the desired label showing the same value that is shown in the Language Picker for the current app language.
