### ISSUE TITLE
My Site Dashboard: Fix `my_site_tab_tapped` tracking

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#16520]
### Expected behavior
On returning from another bottom tab to my site tab, `my_site_tab_tapped` should not be tracked.

### Actual behavior
On returning from another bottom tab to my site tab, `my_site_tab_tapped` gets tracked.

### Steps to reproduce the behavior

1. Launch the app
2. Enable tracking from Me -> App settings -> Privacy settings -> Collect information
3. Toggle tabs:  my site tab -> reader tab -> my site tab
4. Notice in logs: 
`Tracked: my_site_tab_tapped, Properties:{"tab":"dashboard","default_tab_experiment":"nonexistent"}`

##### Tested on WPAndroid 19.8

Noticed in PR: https://github.com/wordpress-mobile/WordPress-Android/pull/16513

**Comment by AjeshRPai** [comment]
Closing this issue as the tabs are removed from the app.
