### ISSUE TITLE
[Site Design Revamp] Main View - Use Serif typeface for section titles

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#16527]
Use Serif for the section titles on the design picker screen.

<img src="https://user-images.githubusercontent.com/2092798/167980019-dad1b264-dc27-4df9-ba77-76acecd80f6b.png" width="350px" />

PRs should target the `feature/site-design-revamp` feature branch.

**Comment by ovitrif** [comment]
This seems to be already resolved:


![Image](https://user-images.githubusercontent.com/4588074/168375248-386e58c7-8fc9-4375-88ce-423c5b735a10.png)
