### ISSUE TITLE
Jetpack App: Domains: search icon and loading indicator overlap while waiting for initial results

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#16627]
### Expected behavior
I'm not sure how to suggest resolving this, but I didn't expect a loading indicator to be overlapping with the search icon. Perhaps the loading indicator could be on the right side of the search bar?

### Actual behavior
The search icon is overlapped by a loading indicator until the user starts typing in the search field.

https://user-images.githubusercontent.com/15107387/170018155-003a02ec-a60b-4dc8-829b-349d0bfeefc7.mp4

### Steps to reproduce the behavior
1. Head into Domains and tap "Add a domain"
2. Before tapping the search bar or typing anything, note that there is a loading indicator overlapping the search icon.
3. Start typing, and note the search icon is removed, leaving just the loading indicator.

**Comment by ravishanker** [comment]
Fixed in #16638
