### ISSUE TITLE
Jetpack App: Domains: "Select domain" button doesn't appear on initial search

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#16628]
### Expected behavior
Expected to see "Select domain" button, in order to proceed with registering a domain.

### Actual behavior
The keyboard blocks the "Select domain" button when a domain is selected if searching for the first time. If you press "done", you'll see "select domain", and subsequent interactions with the search field keep that button displayed.

https://user-images.githubusercontent.com/15107387/170019528-702fb446-acb7-4031-8165-7d79449449cd.mp4

### Steps to reproduce the behavior
1. Head into Domains and tap "Add a domain"
2. Enter an initial search and wait for results to load
3. Select a domain
4. Scroll up and down, and note that there is no "Select domain" button.
5. Tap "Done" on the keyboard, and the keyboard will be closed and "Select domain" button appears.

**Comment by ravishanker** [comment]
This is happening only when tapping [Add a domain] button.  It doesn't seem to happen when going from [Search a domain] button!  Strange but true!!

**Comment by guarani** [comment]
@ravishanker, can this issue be closed?

**Comment by ravishanker** [comment]
Fixed in #16638
