### ISSUE TITLE
Domain search: Invalid urls displayed in suggested domains list for RTL languages.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#16641]
### Expected behavior
During site creation, suggested domains list should display valid urls for RTL languages.

### Actual behavior
During site creation, suggested domains list displays invalid urls like `.wordpress.comtesting` instead of `testing.wordpress.com` for RTL languages

### Steps to reproduce the behavior
1. Set the device language to Arabic or any other RTL language.
2. Enter site creation flow.
3. When choosing a domain, type anything.
4. ❌  Notice that the suggested urls are not displayed correctly.

|  Android ❌  | iOS - Reference ✅  |
| - | - |
| <video src="https://user-images.githubusercontent.com/42008628/170327890-d5170933-f7e5-41f3-be0b-1fe1d70a2c11.mp4"> | <img width="349" alt="image" src="https://user-images.githubusercontent.com/42008628/170330359-208a8715-55e8-4e22-bdf7-3149085836cd.png"> |

**Comment by carl-duncan** [comment]
Hey, I will handle this issue.

**Comment by carl-duncan** [comment]
I was able to replicate the issue, I am now resolving it.

**Comment by carl-duncan** [comment]
https://github.com/wordpress-mobile/WordPress-Android/pull/16643
