### ISSUE TITLE
Quick Start: Retain Quick Start focus point after device rotation

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#16656]
### Expected behavior
`Get to know your app` > `Check your notifications` and `Get to know your app` > `Connect with other sites` flows should not be dismissed after a device rotation.

### Actual behavior
`Get to know your app` > `Check your notifications` and `Get to know your app` > `Connect with other sites` flows are dismissed after a device rotation.

### Steps to reproduce the behavior

1. Launch the app.
2. Logout and login.
3. Select an existing site from the `Login Epilogue` screen.
4. Select "Show me around" on onboarding `Quick Start` dialog.
5. Go to `My Site` tab.
6. Notice that the `Quick Start` card is shown for the existing site with the title `Get to know your app`.
7. Tap on the card > then tap `Check your notifications` in the tasks modal.
8. Notice that the `Quick Start` focus point is shown on the notifications tab.
9. Rotate the device
10. Notice that the `Quick Start` focus point on the notifications tab is not present.

P.S. The same issue exists for `Connect with other sites` task.

Internal Ref: p5T066-3dy-p2#comment-12441

**Comment by hmncube** [comment]
I am working on this issue

**Comment by ovitrif** [comment]
> I am working on this issue

Hey @hmncube, are you still working on the issue?
I was thinking of looking into it if that's not the case.

Thank you 🙇 .

If you're still working on it I can help if you encounter issues / blockers.
