### ISSUE TITLE
Pages List: Copy Link causes small crash on first attempt

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#16652]
### Expected behavior
After tapping "copy link", the link will be copied (can be pasted) and a notice "URL copied to clipboard" will appear.

### Actual behavior
Under certain circumstances, there is a small crash. The screen briefly goes blank and then the My Site screen appears again. The link isn't copied.
I think the biggest factor is tapping "copy link" on a Page you've never copied before, however language settings may or may not also play a part.

### Steps to reproduce the behavior
1. Head into My Site > Home > Pages
2. Tap the kebab menu (...) for a particular page
3. Select "copy link"

In my testing, this caused a small crash numerous times. The first time, I had my App language and Device language set to German, and it happened immediately with the first page I tried copying the link for. Copying the link for that page again worked. After switching to Chinese (app and device), I noticed it again when I tried to copy the link of a different page. At first, I wasn't able to reproduce this in Arabic, but again I eventually did with a page I hadn't tried copying the link of before. I also got it to happen in English a few times.

https://user-images.githubusercontent.com/15107387/170669394-3a1f443e-4567-41ff-8073-05fd3f1ed5f0.mp4

**Comment by ovitrif** [comment]
I tried testing this more than 10 times. One time it reproduced (on English) it was with a newly created page.

Trying the same scenario multiple times with different pages didn't result in the crash.

So far I couldn't find the source of the problem; the only time it reproduced I didn't have the device `logcat` open so I have to be able to repro it again and it seems pretty difficult.

**Comment by ovitrif** [comment]
@thehenrybyrd I tried this more than 25 times and unfortunately the only time I could repro it was at the beginning where I forgot to grab the app logs. I didn't expect it to be that difficult to repro, but now I'm kinda blocked not being able to repro it.

I tried both emulator and physical device with no success to repro it after the initial time it did crash (that was in the emulator).

If it's reproducing more often on your device could you please share the app logs?
I suspect there should be an actual crash that would get logged (based on the previews, description and the one time I saw it).
That should be enough to pin-point the source of the crash and figure out a fix for it 🤞 

Thanks in advance!

**Comment by thehenrybyrd** [comment]
@ovitrif unfortunately it doesn't look like there's a crash in the logs. Other than a whole lot of 
```
90 - [May-31 09:01 DB] Site found by SITE_ID: 189176422
91 - [May-31 09:01 DB] Updating site: http://veggiegarden.blog
```

I only see the following:
```93 - [May-31 09:11 READER] reader post list > saving instance state
94 - [May-31 09:11 API] Dispatching action: AccountAction-FETCHED_SUBSCRIPTIONS
95 - [May-31 09:11 STATS] 🔵 Tracked: support_opened, Properties: {"default_tab_experiment":"dashboard","origin":"ME_SCREEN_HELP"}
96 - [May-31 09:11 UTILS] trackLastActivity, activityId: Help Screen
97 - [May-31 09:11 NOTIFS] notifications update service > completed
98 - [May-31 09:11 NOTIFS] notifications update job service > all tasks completed
99 - [May-31 09:11 NOTIFS] notifications update job service > destroyed
```

However, I was able to get back to a state where I could reproduce this a number of times, by uninstalling and reinstalling the app. Once I reinstalled I was able to reproduce ~10 times before I stopped seeing the crash.
