### ISSUE TITLE
CppException: Exception in HostObject::set for prop '_value': java.lang.NoSuchMethodError: no non-static method...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#16670]
**Sentry Url**: https://sentry.io/share/issue/b9691f04ba4243d0a66eb5f00b4c57d4/
**User Count**: 56
**Count**: 427
**First Release**: 19.9-rc-1
**First Seen**: 2022-05-16T16:38:02.803000Z
**Last Seen**: 2022-05-28T01:38:00Z
**24 Hours**: 0
**30 Days**: 429

```
CppException: Exception in HostObject::set for prop '_value': java.lang.NoSuchMethodError: no non-static method "Lcom/swmansion/reanimated/layoutReanimation/LayoutAnimations;.notifyAboutProgress(Ljava/util/Map;I)V"

Error: Exception in HostObject::set for prop '_value': java.lang.NoSuchMethodError: no non-static method "Lcom/swmansion/reanimated/layoutReanimation/LayoutAnimations;.notifyAboutProgress(Ljava/util/Map;I)V"
    at workletValueSetter (/workdir/gutenberg/node_modules/react-native-reanimated/src/reanimated2/core.ts (190:0):1:1121)
    at workletValueSetter (native)
    at startAnimationForTag (/workdir/gutenberg/node_modules/react-native-reanimated/src/reanimated2/layoutReanimation/LayoutAnimationRepository.ts (7:8):1:1222)

...
(16 additional frame(s) were not displayed)
```

**Comment by fluiddot** [comment]
I noticed that this crash only happened in version `19.9-rc-1` and not in `19.9`, so probably it was addressed before the version was released. However, there's another event also related to the React Native's Reanimated library that is actually happening in `19.9`: https://sentry.io/share/issue/0d746ce5b70b452ab8e1831424edb8d3/

However, so far only affected 36 users which represents a low impact (**0,01%** of users affected in that version).

**Comment by ashiagr** [comment]
As discussed in Slack thread: p1655194376208219/1655185052.847229-slack-C012H19SZQ8, closing this issue as the crash is not reproducible in 19.9.

We'll open a new one if this one gets traction in 19.9:  https://sentry.io/share/issue/0d746ce5b70b452ab8e1831424edb8d3/
