### ISSUE TITLE
App crashed when scrolling down in the app's editor

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#16675]
Reported in 5247167-zd-woothemes. The app crashed when the user scrolled down in the app's editor. I can reproduce in SSP with Pixel 4 (emulator), WPAndroid 19.9, and Android 12.

Sentry crash reports can be found [here](https://sentry.io/organizations/a8c/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1438088&query=user.display%3Afromdumpytodiva2017%40gmail.com&sort=-timestamp&statsPeriod=7d&yAxis=count%28%29).

### Steps to reproduce the behavior

1. SSP to the account
2. Go to My Site > Posts > Published, tap the post with the title containing "Crab Cakes Salad"
3. Scroll down to the bottom of the editor
4. App crashed

Video recording and more details about the issue (e.g., full post title) can be found in the ticket.

##### Reported on Samsung SM-G998U, Android 12, WPAndroid 19.9

**Comment by khaykov** [comment]
I think this is one of the occurrences of [this](https://sentry.io/share/issue/ab1e2ab600d540aa964a361d54a1dd5d/) issue, but reproducible. In general SIGSEGV issues are very hard to debug and fix, but since we can repro it might be worth giving a try.

Labeling this one as GB, since crash happening in editor.

**Comment by carl-duncan** [comment]
Hey, I will handle this one, just need more information in regards to the ticket.

**Comment by hypest** [comment]
I see `com.swmansion.reanimated` being in the stacktrace so, lemme cc @fluiddot since there were more Reanimated lib issues handled recently and this can be relevant.

**Comment by fluiddot** [comment]
> I see com.swmansion.reanimated being in the stacktrace so, lemme cc @fluiddot since there were more Reanimated lib issues handled recently and this can be relevant.

Thanks for the ping @hypest 🙇 !

I checked both the stack trace and user actions and this might be a different problem than the one we're currently trying to fix in ([this issue](https://github.com/WordPress/gutenberg/issues/41686)). Most of the crashes we've identified so far are occurring when the editor closes and is re-opened, so they differ from this one. Being this said, I'll cross-reference it with the mentioned issue in case the fixes we apply there also help in addressing this.

**Comment by fluiddot** [comment]
Based on the steps to reproduce this issue and that the content of the post contains Embed blocks, most likely this is caused by the same problem outlined in this [another issue](https://github.com/WordPress/gutenberg/issues/42514). It has been already solved in WPAndroid 20.3, so we could consider closing it, wdyt?

**Comment by dcalhoun** [comment]
I agree with @fluiddot. Given the device used is running Android 12 and the affected post content contains an Embed block, it is quite likely this was resolved with https://github.com/WordPress/gutenberg/pull/42517. @reginabally how do you feel about closing this?

**Comment by reginabally** [comment]
Thanks for following up, @dcalhoun and @fluiddot! I emailed the user who reported the issue about the fix and asked them if the issue is no longer happening.

I'm closing this for now and will reopen it if needed.
