### ISSUE TITLE
Notifications doesnt dismiss after logging out from the App 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16689]
### Expected behavior
Notifications should be dismissed after logging out 

### Actual behavior
https://user-images.githubusercontent.com/17463767/171617083-fc7dcd09-4e2f-4d6d-87d9-e594b0c7e439.mp4

### Steps to reproduce the behavior
- Login to the app 
- Create Post/Reply to a comment(finish any tasks which creates a notification) 
- Dont dismiss the notification 
- Logout from the app 
- Notice that the notification is still seen 

##### Tested on [device], Android [version], WPAndroid [version]
Samsung s22, Android 12

**Comment by carl-duncan** [comment]
Hi, I resolved that issue : https://github.com/wordpress-mobile/WordPress-Android/pull/16694
