### ISSUE TITLE
[android] Stats: Bugs, styles and refining

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#16684]
- [x] Card vertical paddings
- [x] Card radius to 10dp
- [x] Graph marker Comma [bug](https://github.com/wordpress-mobile/WordPress-Android/pull/16327#issuecomment-1110221404) on @irfano's device
- [x] Default cards
- [x] "Highlights" title in Insights tab
- [x] Update Views And Visitors strings, [slack message](p1652189996973789-slack-C02UJ9192TC)
- [x] Add date pickers on new detail screens.
- [x] ~~Remove total cards border in total detail screens.~~
- [x] @irfano: At first opening, some cards are not being shown in detail screens in the emulator. Check if that is reproducible in real devices.
- [x] @irfano: In `StatsFragment` `viewModels()` is being used instead `activityViewModels()`, check if that causes a problem, and fix.
- [x] Views & Visitors crash when talkback is on, LineChartAccessibilityHelper.kt:32 com.github.mikephil.charting.data.Entry cannot be cast to com.github.mikephil.charting.data.BarEntry
- [x] Dates in line chart are "null" in @irfano's emulator.
- [x] Title style, and layout problem 👇
<img src="https://user-images.githubusercontent.com/2471769/170678115-2fb793d7-165a-4bf3-b12e-ffbaa54d3afa.png" width=260>

**Comment by irfano** [comment]
This issue is fixed in various PRs.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
