### ISSUE TITLE
[Site Design Revamp] Reduce recommended thumbnail size

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#16743]
## Description

Due to observed limitations by the mShots service, recommended thumbnails are not rendered at their requested resolution and appear pixelated. Instead of showing larger recommended thumbnails, reduce their size to match the standard thumbnails.

Once the mShots API is updated we can revert back to the enlarged size.

<img src="https://user-images.githubusercontent.com/2092798/173615968-19d9a594-091d-48d7-ad8e-2622469986cd.png" width="350px" />

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/16747
