### ISSUE TITLE
[Site Design Revamp] Site Theme does not update recommended section title

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-Android#16746]
### Expected behavior
After selecting a vertical/topic, the Site Theme screen displays the selected vertical/topic, e.g. _Best for Food_. 

### Actual behavior
After selecting a vertical/topic, the Site Theme screen displays the the default _Best for Blogging_ text. 

### Steps to reproduce the behavior
1. Start the Site Creation flow
1. Select one of the main topics listed under the input
1. Notice the recommended section is not updated.

##### Tested on Samsung Galaxy S20, Android 12, WPAndroid 20.1-rc-1

Related to https://github.com/wordpress-mobile/WordPress-Android/issues/16540. 

https://user-images.githubusercontent.com/438664/173684529-2628f53e-47ed-44a1-ab6a-6929119c14ad.mp4

**Comment by dcalhoun** [comment]
@antonis I encountered this while testing the Site Design Revamp. Will you please confirm this is an issue in 20.1-rc-1? Thanks! 🙇🏻

**Comment by antonis** [comment]
Thank you for reporting @dcalhoun 🙇 
This occurs due to a delayed deployment of the new themes which are still in beta and should be fixed on the server with `D82060-code`.
I'll validate the solution and close it once the change is deployed.

**Comment by antonis** [comment]
This is now solved on the server side 🎉
