### ISSUE TITLE
No option to cancel pending email address on username change until refresh of the screen.

### ISSUE THREAD

**Issue by SowmiaS** [wordpress-mobile/WordPress-Android#16759]
### Expected behavior

When the user has a pending email address, the user should always have the option to cancel the pending email address.

### Actual behavior
**Given**  the user has a pending email address
The Snackbar is shown to notify the user to verify the pending email address. The Snackbar also has a `Discard` button for canceling the pending email address.
**When** the user changes the username
**Then** The Snackbar is shown as 'Your username is XXXX', which dismisses the pending email address Snackbar.
The user has to navigate back and come to the Account Settings screen to be able to cancel the pending email address. 

### Steps to reproduce the behavior
1. Login -> MySite -> Profile icon -> Account Settings
1. change the email address and Snackbar will be shown for pending email addresses.
2. change the username, Snackbar will be shown for a username change.
3. observe that there is no option to cancel a pending email address until the user navigates to a different screen and comes back.

https://user-images.githubusercontent.com/4975407/174020747-cf84933f-6b4f-444f-ae4b-c06f772c41ef.mp4

**Comment by SowmiaS** [comment]
Material guidelines - [ Consecutive Snackbars](https://material.io/components/snackbars#behavior:~:text=of%20ten%20seconds.-,Consecutive%20snackbars,-When%20multiple%20snackbar)
> When multiple `Snackbar` updates are necessary, they should appear one at a time.

In Android, **only one `Snackbar`** can be shown at a time. So I think we can display "Your username is XXXX" message in a `Toast` and pending email address message in `Snackbar` as it has to be shown until the user cancels the pending email address change.

Note: In the Account settings screen, "Password changed successfully" message is also shown in a `Toast`. 
wdyt?

Thanks 🙂

**Comment by thehenrybyrd** [comment]
@SowmiaS looks like you addressed this in #16371 🎉 Thanks! 
I think that takes care of the full issue, so I'll close it for now. Please feel free to reopen if necessary!
