### ISSUE TITLE
Reader Comment Enhancements

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1678]
We'd like to enhance the Reader detail view comments list to do the following:
- Support passing a `commentId` to the detail view, which will animate in the comment at the top of the view. Scrolling up would show the post content: https://cloudup.com/cN8ZPOEkEQk
- Enhance the comment view to include moderation, if the user has the correct permissions. If space is tight, place the moderation buttons in a 'More...' button.

The UI is also slightly different, nice icons and coloring:
![r0ra8gkinn-3000x3000](https://cloud.githubusercontent.com/assets/789137/3723438/83486316-1673-11e4-9edd-a45098b0f0c8.png)

A comment that needs moderation should look like this:
![3u-eprvbrs-3000x3000](https://cloud.githubusercontent.com/assets/789137/3723441/86775308-1673-11e4-803e-c6e85bde1c98.png)

This is related to the notifications redesign work going on here: https://github.com/wordpress-mobile/WordPress-Android/tree/feature/notifications-redesign, but we thought it'd be best to do this as a separate PR.

**Comment by oguzkocer** [comment]
We have a pretty different UI right now, so I am not sure if this still applies. @roundhill do you mind checking the original issue and the current state of the reader and share your thoughts on it? Thanks! /cc @nbradbury

**Comment by oguzkocer** [comment]
Oh, I just saw that this issue is added to `Notifications Refresh` project, so I am guessing that means it's still a valid issue. Can you confirm that @mzorz? If it's planned for the near future, can we add a milestone for it? Thanks!

**Comment by mzorz** [comment]
Thanks for the ping @oguzkocer , I probably tagged it Notifications initially to keep track of all I need to take a look at when took the project over, but probably like you said it's not needed anymore. Let's wait for @roundhill feedback. 👍

**Comment by roundhill** [comment]
I still think this would be pretty cool to do, because it puts the user in the context of the reader, but can still perform comment moderation actions. I believe I had a branch working with the basics of this, but it was over a year ago so it probably no longer applies.

That said though, my team is no longer focusing on this so we can probably just close this unless someone from Hogwarts is willing to give it a go.

**Comment by ChrissiePollock** [comment]
I just had another person ask for this in mobile support.
