### ISSUE TITLE
Email Address goes blank 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16795]
Email Address field goes blank on opening email address change dialog and pressing Ok

### Expected behavior
Email address field should remain as is. 

### Actual behavior
Email Address field goes blank 

### Steps to reproduce the behavior
- Login to the app 
- Go to me -> Account settings 
- Click at email address 
- Press ok 
- Notice that email address field goes blank 

https://user-images.githubusercontent.com/17463767/175032801-560248aa-1d34-4403-b79c-d99b9799e0a0.mp4

**Comment by thehenrybyrd** [comment]
I was able to reproduce this on **Samsung Galaxy S21 with WP Android 20.2-rc-2**.

**Comment by OkoloArt** [comment]
Hello, I'll like to work on this issue if it hasn't yet been resolved

**Comment by AjeshRPai** [comment]
@OkoloArt  Thanks for volunteering to help. It hasn't yet been resolved. You can find more information on how to contribute to the code base [here](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/CONTRIBUTING.md)

**Comment by OkoloArt** [comment]
@AjeshRPai , thanks. I tried signing in, even after changing client id and server key. I'm still not getting logged in. Do you know how I can resolve this

**Comment by AjeshRPai** [comment]
@OkoloArt Thanks for trying it out. I am not sure what issue you are facing with reproducing this bug. Please look at the **steps to reproduce** section in this Issue to reproduce. Am sorry, I can't see to understand where the client id and server key are used in reproducing the issue.

**Comment by gyanpra7880** [comment]
Hello, I'll like to work on this issue if it hasn't yet been resolved.
I have done many things in jetpack. So I could easily solve this issue.

**Comment by OkoloArt** [comment]
@gyanpra7880 , tried reproducing this issue on the pre-alpha app but I get a "client not permitted" message. I think this can only be reproduce when using the main WP Android and not the Pre-Alpha

**Comment by gyanpra7880** [comment]
@OkoloArt  so what should I do to solve this issue?

**Comment by lmischner** [comment]
I was able to reproduce this on Google Pixel 7, Jetpack 21.8. Note that you can't fix this from the app -- if I type in the email associated with the account, tapping OK still results in a blank email.
