### ISSUE TITLE
Action bar gets dismissed before the navigation to change user name screen 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16796]
### Actual behavior
The action bar gets dismissed(pause at 0:03) before the navigation to the Change username screen. 

### Steps to reproduce the behavior
1. Login to the app
2. Go to me -> Account settings 
3. Click at username 
4. Notice that before showing the user name search screen 
5. The action bar gets dismissed 

https://user-images.githubusercontent.com/17463767/175034139-5b41a23a-ccf4-4228-88fc-78b658a7fff4.mp4

**Comment by hakeem-gitstart** [comment]
Hello, i'm currently working on this

**Comment by gitstart** [comment]
#17037
