### ISSUE TITLE
Site Title overlap on Tablets

### ISSUE THREAD

**Issue by joashrajin** [wordpress-mobile/WordPress-Android#16817]
### Expected behavior

The title should not overlap the Navigation Tabs (Home, Menu)

### Actual behavior

Sites which have long titles have them overlap the Home and Menu Tabs

### Steps to reproduce the behavior

- Log into the app on a Tablet Device
- Make sure you have more than 1 site connected and you have one with a long title

##### Tested on a Samsung Galaxy Tab A, Android 7.1.1, WPAndroid 20.0

![Screenshot_20220624-141346](https://user-images.githubusercontent.com/16253818/175532359-fbd82d89-00f8-4398-a4a0-864918d11b31.jpg)

In #5305230-zen, the user was using a Lenovo TB-X104F, with Android version 8.1

**Comment by hmncube** [comment]
@joashrajin @thehenrybyrd should the site title be on the left of the navigation Tabs or on top of them? And also I am working on this issue.
