### ISSUE TITLE
Feature Request for Story post: Add the ability to add emoji to the post

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#16852]
Requested in 5337198-zd-woothemes. Translated from Portuguese:

> In the storys part you could put emoji options to decorate the post to look cooler if it is a story it has to have emoji

**Comment by thehenrybyrd** [comment]
@reginabally emoji can be added to Stories, by typing them in from the device's built-in emoji keyboard. They can then be enlarged and rotated as desired to decorate the post. I just confirmed this in WP Android 20.2-rc2.

I'll close this post for now, but if the user is unable to add emoji, please re-open and include more details about the trouble they're having.

**Comment by reginabally** [comment]
Thanks, @thehenrybyrd! ~I can't seem to rotate the emoji in the app (WPAndroid 20.1). Do you mind showing me the steps on how to do it?~

Edited: Please ignore my question. Just found out that I can use two fingers to rotate the text and emoji in the Story post. TIL for me!
