### ISSUE TITLE
Creating a Story post is not working

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/WordPress-Android#16867]
It was reported that posting a Story post no longer works, after some investigation, it looks like it started happening [after these changes](https://github.com/wordpress-mobile/WordPress-Android/pull/16632).

It looks like the process that uploads the images is not working as expected hence never updating the post and publishing it.

**Note:** Posting a Story block within the block editor works as expected, it only happens outside of the editor.

### Expected behavior
Users should be able to create a Story post outside of the editor.

https://user-images.githubusercontent.com/4885740/177332060-0cac64d8-813d-4b6e-8f06-4543220172bd.mov

### Actual behavior
The post is created as a draft but it doesn't add the Story block with the content and it doesn't get published.

https://user-images.githubusercontent.com/4885740/177329833-5b3ac9a0-d0f1-45e6-9e68-1fe88d4ea345.mov

### Steps to reproduce the behavior

- Open the app
- Tap on the Add new button 
- Select Story post
- Select some images
- Tap on the next arrow (top right)
- Type in a story title
- Publish the post
- Go to the Posts section
- Go to the Drafts tab
- Open the newly created post
- See that the post is empty

**Comment by ParaskP7** [comment]
This is now done and will be included in the next `20.2` release of the app.

Related Release PR: #16881
