### ISSUE TITLE
Infinity is shown in percentage change on Stats

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#16863]
### Expected behavior
Percentage change shouldn't show ∞% 

### Actual behavior
On Days/Weeks/Months/Years tabs percentage change is shown as for e.g. +9(∞%)

### Steps to reproduce the behavior
[Please see here for context](https://apptestingo2.wordpress.com/2022/06/28/to-test-wordpress-android-20-2/#comment-12771)

**Comment by bynalab** [comment]
Hi @ravishanker, Please can you provide more context on this issue? I can't seem to reproduce.
Thanks

**Comment by irfano** [comment]
Duplicate of #17314
