### ISSUE TITLE
[android] Long title problem on stats cards

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#16887]
### Expected behavior
The title of the stats cards below should fit in the card.
- Views & Visitors
- Total Likes
- Total Comments
- Total Followers
- Latest Post Summary

### Actual behavior
There is VIEW MORE button on these cards on the main stats screen. There isn't any button on the detail screen but there is still an empty room for the button on the detail screen.
<img src="https://user-images.githubusercontent.com/2471769/178066948-d7a58445-4218-4369-bc20-d31d55b39e1c.png" width=320>

### Steps to reproduce the behavior
1. Launch Jetpack app. 
2. Navigate to stats screen by using quick links or menu.
3. If the cards (mentioned above) are not present, go to the stats management (either through ⚙️ menu at the top right hand corner or Add new stats card at the bottom) and add cards and save, then return to Insights.
4. Check the title in detail screens.
5. Repeat 1-4 for different languages. We know German has a problem with long titles currently.

**Comment by olaitanade** [comment]
Hi @irfano @thehenrybyrd 
I'd need clarification on this issue please.

**Comment by irfano** [comment]
Hey @olaitanade !
On some cards, there is a button end of the title. That's why the title is not full-width on the screenshot.
We should set the title full-width if there is no button.

**Comment by olaitanade** [comment]
Alright
Thanks @irfano

**Comment by olaitanade** [comment]
I am new to wordpress, how do i create a long tittle to test my fix ? @irfano

**Comment by irfano** [comment]
>Views & Visitors
Total Likes
Total Comments
Total Followers
Latest Post Summary

Those cards are only available on the Jetpack app.
You can update use cases, and use hardcoded titles.

**Comment by olaitanade** [comment]
Thanks @irfano 
Done.
