### ISSUE TITLE
"Uploading null" message is displayed when uploading a post that contains a Story block

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-Android#16882]
### Expected behavior
On the home screen, when a post is being uploaded it should display the message `Uploading <POST_TITLE>`, independently of the content of the post.

### Actual behavior
On the home screen, when a post that contains a Story block is being uploaded, it displays the message `Uploading null`.

### Steps to reproduce the behavior
1. Go to the Posts screen.
1. Tap on the ➕  button located in the bottom-right corner.
1. Tap on "Blog post".
1. Add a Story block with an image.
1. Right after adding the Story block, tap on "Publish" and publish the post.
1. Before the post is uploaded, tap on the back button to go to the home screen.
1. Observe that the message `Uploading null` is displayed.

##### Tested on Samsung Galaxy S20 FE 5G, Android 11, WPAndroid 20.2 (using [this change](https://github.com/wordpress-mobile/WordPress-Android/pull/16881))

**Comment by ghost** [comment]
i want to try

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
