### ISSUE TITLE
Can't remove a featured image from a post

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#169]
Currently you can't remove a featured image from a post, only add. Perhaps we should make it more like WPiOS where there is a separate section in the post editor for adding/updating/removing a featured image.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by maxme** [comment]
Reopening - it's being resolved in #2500

**Comment by rachelmcr** [comment]
Closing - this is resolved in the new editor (https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/16).
