### ISSUE TITLE
Jetpack Focus: Enhance screenshots

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#16900]
This is the main issue for enhancing the Jetpack screenshots. 
For background information, please see this thread: pcdRpT-z4-p2

- Adjust screenshots  #16929 
  - Blog Editor
  - Notifications
  - Media/Photo
  - Blogging Reminders
  - Blogging Prompts
  - Choose site topic
  - Create new options (post, story, page)
  - Choose a layout
  - Adjustment for site topic on narrow displays #16967 

Preexisting issues that require more research before they can be addressed (see #16845 for more info)
- Gray overlay sometimes appears on views
   -- This happens on emulators running API < 30. (see parent issue #17128)
- Wiremock not finding the mock (although they exist) which leads to failing tests (see parent issue #17128 
- "Blog editor" fails to load. Fixed in #16929 

Notes
- FB remote config flags - they can't be found while the tests are running. This needs to handled as a one off issue each time a new flag is introduced because it can change the look of the screen.

**Comment by ParaskP7** [comment]
👋 @zwarm !

I am updating the milestone from `20.4` to the next one (`20.5`) as I am currently doing the code freeze for the new release. I am thinking it is safe for me to do so on this issue, but If that's not what you want, just let me know. 🙏

**Comment by zwarm** [comment]
Pre-existing items move to new parent #17128
