### ISSUE TITLE
`Log in with another account` button not working

### ISSUE THREAD

**Issue by pachlava** [wordpress-mobile/WordPress-Android#16960]
### Expected behavior
Tapping `Log in with another account` button should result in redirect to prologue screen.

### Actual behavior
Tapping this button does nothing, both in cases of getting to the screen via `WPCOM login` or via `store address login`.
Never mind that video is shot for debug variant with emulator, it's the same for release beta 9.7-rc-1 on a real device.

https://user-images.githubusercontent.com/73365754/181225830-35d3d5ca-785c-4bb3-83a9-15dbba730af3.mov

### Steps to reproduce the behavior

Way 1:
1. Make sure you're logged out
2. Tap `Enter your store address`
3. Enter `google.com` and tap `Continue`
4. In the next screen, tap `Log in with another account` ~> nothing happens

Way 2:
1. Make sure you're logged out
2. Tap `Log in with WordPress.com`
3. Enter some valid email address, which is not associated with a WPCOM account, and tap `Continue`
4. In the next screen, tap `Log in with another account` ~> nothing happens

**Comment by JorgeMucientes** [comment]
I've opened a [PR](https://github.com/woocommerce/woocommerce-android/pull/7080) here to fix the issue @pachlava 

Thanks for pointing this out. 

PS: The repository in which this issue was created is not the right one. This belongs to WooCommerce repo 😃

**Comment by pachlava** [comment]
>The repository in which this issue was created is not the right one

Oof, I'm sorry 😅 I probably spend too much time working on UI tests fixes for WPAndroid, so opening WPA repo became a sort of unconditioned reflex for me. Thank you for opening the PR (in correct repo 😆) @JorgeMucientes !
