### ISSUE TITLE
Stories: Errors while editing a Story block.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#16987]
### Expected behavior
It should be possible to edit Story blocks.

### Actual behavior
Sometimes the 'Can't edit Story' error is shown when trying to edit a Story block .

| Case 1 | Case 2 |
| :-: | :-: |
| <video width="300" src="https://user-images.githubusercontent.com/42008628/182500439-7fcf2068-a6e7-41db-bcb6-0ad8f83255a9.mp4"> | <video width="300" src="https://user-images.githubusercontent.com/42008628/182500356-fa80e4e8-0a69-4069-891e-4b2194f2b0de.mp4"> |

### Steps to reproduce the behavior
Case 1
1. Add a Story block to a post.
2. Select an image.
3. ❌  Notice that the image doesn't load properly. (Not 100% reproducible)
4. Tap the image to edit the Story block.
5. ❌  `Can't edit Story` dialog is displayed.

Case 2
1. Add a Story block to a post.
2. Select an image.
3. Rotate the phone twice: `Portrait` -> `Landscape` -> `Portrait`.
5. Tap the image to edit the Story block.
6. Tap the ✔️  in the top right corner to confirm the same image.
7. Tap the image to edit the Story block.
8. ❌  `Can't edit Story` dialog is displayed.

**Comment by geriux** [comment]
Hey @tiagomar thanks for creating the ticket.

Is this happening only in the current `20.4` beta? Does it work correctly on the production build?

What kind of site was it? Simple, self-hosted? Is it a public site or a private one?

Sorry for asking too many questions but that will help while we investigate this issue.

Thank you!

**Comment by tiagomar** [comment]
Hey @geriux!

I had't tried other releases but I just reproduce it in `20.3` production build.

The site is a Simple and public site.

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
