### ISSUE TITLE
Reader search screen doesn't give any feedback to the user when there's no internet connection.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#16997]
### Expected behavior
While searching for Posts and Sites in Reader, the user would be let know if there's no internet connection.

### Actual behavior
If the internet connection is lost while searching for Posts and Sites in Reader, there's no feedback to the user.

|  |
| :-: |
| <video width="300" src="https://user-images.githubusercontent.com/42008628/182728021-d1b93ecf-1caf-4333-84d5-e44fc8c6bb51.mp4"> | 

## Steps to reproduce the behavior
1. Airplane mode ON
2. Go to `Reader` -> `Search`
3. Search for any keyword
4. ❌ Notice that there's no feedback about connectivity.

**Comment by bynalab** [comment]
Hi @tiagomar, I'm currently working on this issue.
