### ISSUE TITLE
Jetpack: Comments approved via the notification bar have the message removed

### ISSUE THREAD

**Issue by joashrajin** [wordpress-mobile/WordPress-Android#17026]
### Expected behavior

The comment text should remain intact once the comment is approved

### Actual behavior

When you use the notification bar to approve a comment, the author's name is shown on the site, but the actual message from the comment is stripped, so you end up with an empty comment. This does not happen if you approve the comment via the app itself (opened) or via the web. 

### Steps to reproduce the behavior

- Ensure that you have your Discussion settings set to moderate/approve all comments
- Make a test comment on a site which is connected to your WP/Jetpack app
- Approve the comment via the notification bar

Recording: 

https://user-images.githubusercontent.com/16253818/184101808-4d2e8446-3d4d-4dda-af3c-7c70d89460cd.mov

**Comment by thehenrybyrd** [comment]
I was able to replicate this on **Samsung Galaxy S21, Android 12, JP Android 20.5-rc-1**. I used a WordPress.com simple site.
No revisions are saved, so as far as I can tell there's no way to restore the content once it's lost.

**Comment by develric** [comment]
Closing this by the containment fix #17044 , and opened the #17064.
