### ISSUE TITLE
Upload media error when uploading a new post is unclear

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1703]
For instance, (no reference to the post or blog, technical details, not sure if the post has been uploaded without the media)
![screen shot 2014-08-02 at 10 12 17](https://cloud.githubusercontent.com/assets/40213/3787481/c599c8a2-1a1c-11e4-8503-26c58e34d53d.png)

Also we should be careful, and not show network layer or API errors to the user - errors should be the way to tell them what failed, and what they can do next.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
