### ISSUE TITLE
People: Unable to scroll to Send button after entering comments when Inviting

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17047]
### Expected behavior
I expected to be able to scroll if the Send button isn't visible.

### Actual behavior
While in the comment box, notice the screen can't be scrolled up, and thus the Send button isn't visible.

### Steps to reproduce the behavior
1. Go to My Site > People, and tap "+" to invite someone.
2. Fill in an email address and role.
3. Enter a comment, and then attempt to scroll up to tap the "send" button.
4. Note you cannot scroll.

This will depend on screen size, as some screens can contain all the content and likely have no need to scroll.

https://user-images.githubusercontent.com/15107387/185405625-d1ac63e8-6f35-4751-9f3c-f24d58b955db.mp4

**Comment by hmncube** [comment]
@thehenrybyrd I am working on this issue
