### ISSUE TITLE
Apps Remote Config Tool: Feature Flags

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#17050]
This is the main issue for implementing the App Remote Config Tool for Feature Flags.

 
- [x] Add API calls to FluxC to call the `mobile/feature-flags`. See [here](pbArwn-57S-p2#comment-6401) @zwarm 
- [x] ~Introduce feature flag for use during development ? Is this really needed?~
- [x] Research if FB Remote Config "string" values work like the Feature Flag or if there is a direct call. Answer: there is a direct call to FB for the string value. See `ThreatDetailsNavigationEvents`.
- [x] Add logic to replace or supersede Firebase remote config with Remote Feature Flags (depending on the answer to the above task). This should also include a P2 post with a link to the PR so that all Android devs are aware we are doing this. In reality, this should be swapping out the FB call to the new endpoint. Perhaps this should be an addition and not a replace. See p1660862511985019-slack-C03T04HETR8 ⚙️ @AjeshRPai 
- [x] Add the logic for refreshing the remote flags - TTL logic and the logic for clearing the remote flags on logout @AjeshRPai 
- [x] Recreate all FB remote config feature flags for WP/JP in the MC Apps Remote Config Tool

Release Task List
- [x] Test that feature flags work as expected (default local values, overridden by remote values, + direct local changes using the me -> debug functionality)
- [x] Ensure FB remote config "strings" values still work as required.

**Comment by AliSoftware** [comment]
Moved this issue's target milestone to 20.8 as I'm doing code freeze for 20.7 today.

**Comment by AliSoftware** [comment]
Moving again to milestone `20.9`, as code freeze of `20.8` is happening today
