### ISSUE TITLE
Stats: non-graph cards with '0' stats load continuously 

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17108]
### Expected behavior
I expected cards with no data to present a message, such as "no data yet" or "no data for this period". 

### Actual behavior
Instead of presenting a message, these cards appear to load indefinitely.

### Steps to reproduce the behavior
1. Open Stats for a site with no recent views/visitors. 
2. Head to the Day, or Week tab.
3. Note that the top graph displays empty bars, and the rest of the cards show a loading animation that does not stop.

https://user-images.githubusercontent.com/15107387/187673506-70c9814a-9d9e-4b2d-a195-8a4d3562ddc7.mp4

**Comment by irfano** [comment]
We changed granularity tabs and this is no longer reproducible.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/f5162c86-7cc9-4383-840b-fb5057616bb6" width=320>
