### ISSUE TITLE
Reader: "Manage Topics & Sites" not translated

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17112]
### Expected behavior
In Reader, the "Manage Topics & Sites" settings heading should be translated.

### Actual behavior
Heading is not translated.

### Steps to reproduce the behavior
1. In Me > App Settings, change Interface Language to one of the Mag16 languages.
2. Head into Reader and tap the "gear" icon.
3. Note that "Manage Topics & Sites" is in English.

**Comment by debojyoti452** [comment]
@thehenrybyrd 
I am picking this task

**Comment by lazymia** [comment]
**Issue**:  Reader: "Manage Topics & Sites" not translated
**Precondition**: user changes language type and user is on the Reader page

# Test cases
**Condition**: a user can change language and the language type appears on all the headings

 - [ ] verify that the heading is translated to the language selected
 - [ ] ascertain that if language is changed to another, the headings follow suites and does not retain the language of the former
 - [ ] check that for all languages, there is a corresponding heading change
 
**QA Observation**

**Loom**

Cc @debojyoti452

**Comment by irfano** [comment]
The translation doesn't work only when the language is translated via App settings, not device settings. "Manage Topics & Sites" is not the only translation with the issue. When we found the root cause, we should check for other strings too. At first glance, I found Follow topics screens are not translated too.

<img src="https://user-images.githubusercontent.com/2471769/188590257-3fbf1635-6009-44a7-bf34-4c1b8cd7a09c.png" height=640>

**Comment by debojyoti452** [comment]
> The translation doesn't work only when the language is translated via App settings, not device settings. "Manage Topics & Sites" is not the only translation with the issue. When we found the root cause, we should check for other strings too. At first glance, I found Follow topics screens are not translated too.
> 
> <img alt="" height="640" src="https://user-images.githubusercontent.com/2471769/188590257-3fbf1635-6009-44a7-bf34-4c1b8cd7a09c.png">

@irfano 
It's happening because setting `label` from `manifest` will not work with locale change during runtime, so we need to add `title` from `activity` and will start working, soon will push the PR for this fix.
