### ISSUE TITLE
Bug RPC wordpress

### ISSUE THREAD

**Issue by PG338** [wordpress-mobile/WordPress-Android#17162]
have various random bugs with the android wordpress application (phone under android 11).

First : the application does not recognize the site as a wordpress site

second : xml-rtc connection bug cf attachment

I specify that these two bugs are random and that sometimes I can connect.

##### Tested on XIAOMI MIA3, Android 11, WPAndroid

**Comment by thehenrybyrd** [comment]
Hi @PG338,
It sounds like the WordPress app is having trouble connecting to your site.
Please head to Me > Help & Support > Contact Support, and our team will be happy to help troubleshoot with you.
Be sure to send them your site's address (URL), and any specific error messages you see when trying to connect.
Any further context or screenshots you can send will also enable them to help you solve this issue quickly.
