### ISSUE TITLE
RuntimeException: android.os.TransactionTooLargeException: data parcel size 1459760 bytes

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#17183]
**Sentry Url**: https://sentry.io/share/issue/b9cf5ce0048a49e797cadc30c2715c58/
**User Count**: 309
**Count**: 2155
**First Release**: org.wordpress.android@17.5+1058
**First Seen**: 2021-06-18T02:16:27.058000Z
**Last Seen**: 2022-09-20T09:40:44Z
**24 Hours**: 50
**30 Days**: 547

Not new, but 30 days are now >500, and number of users growing
<img width="311" alt="image" src="https://user-images.githubusercontent.com/216089/191234813-378e457a-ec4f-4bd9-8727-2209337bac95.png">

```
RuntimeException: android.os.TransactionTooLargeException: data parcel size 1459760 bytes

...
(3 additional frame(s) were not displayed)
```

**Comment by ravishanker** [comment]
More details https://sentry.io/organizations/a8c/issues/2462989315/?project=1438088

Suspect seems to be ReaderPostPagerActivity and potentially pager adapter

Useful info for debugging https://medium.com/shopback-tech-blog/handle-transactiontoolargeexception-237961bd5ef8

**Comment by antonis** [comment]
Closing as duplicate with https://github.com/wordpress-mobile/WordPress-Android/issues/9685
