### ISSUE TITLE
[Screenshots] Update emulator API version when running screenshot 

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#17191]
Parent Issue: #17128 

A gray overlay appears on views when taking screenshots on emulators running API < 30. 
Update the emulator to API 30 for the screenshot process to eliminate the issue.

**Comment by AliSoftware** [comment]
Note that once https://github.com/wordpress-mobile/WordPress-Android/pull/17096 lands, updating the API level of the emulators used to take screenshots should mostly be a matter of updating the `SCREENSHOT_DEVICES` constant in `fastlane/lanes/screenshots.rb` [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17096/files#diff-7f448e8d33ef3a5a6c249acf5737243310e667d8673cd96a2b1405ce3b3a1384R8-R19)
