### ISSUE TITLE
[Android] Stats: This week's visitor numbers don't match Web and counts non-unique visitors

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#17212]
This week's visitor numbers don't match Web. Web reports much lower numbers than mobile applications.

[See the investigation for more context.](https://github.com/wordpress-mobile/WordPress-iOS/issues/19337)

It most probably happens because on the Web only unique visitors are counted:
```
The unique weekly visitors can sometimes be less than the sum of daily visitors for the same week. The same goes for unique weekly visitors being less than your total monthly visitors. This occurs when the same visitor appears multiple times during the week or month.
```

See [WordPress support stats](https://wordpress.com/support/stats/)

![image](https://user-images.githubusercontent.com/4062343/192465084-0c4938a6-7ffc-4202-b88c-a9fe69c9417a.png)

### Expected behavior

This week's visitor numbers should match Web numbers.

### Steps to reproduce the behavior

1. Open Jetpack app with Stats enabled
2. Open Stats tab
3. Make sure "Views and Visitors" card is added
4. Compare visitor numbers with the Web
5. Click "Week"
6. Compare visitor numbers with the Web

**Comment by mkevins** [comment]
Closing in favor of: https://github.com/wordpress-mobile/WordPress-Android/issues/17450
