### ISSUE TITLE
[Android] Stats: This year's stats don't match numbers on the Web

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#17213]
Yearly statistics of views, visitors, likes, and comments match iOS but don't match the Web.

![image](https://user-images.githubusercontent.com/4062343/192469248-1365f3fd-ce07-4df8-b99b-fba976819cb1.png)

### Expected behavior

All the platforms have the same numbers.

### Steps to reproduce the behavior

1. Open Jetpack app with Stats enabled
2. Open Stats tab
3. Make sure "This year" card is added
4. Compare year statistic with the Web

**Comment by thabotswana** [comment]
Another report in 5690254-zen

>I have been writing to you about the difference between the number of views reported by the WordPress application in the Trends category and the number of views in the Years category.

## Web view

| Stats on WP.com | Stats on the app |
| - | - |
| <img src="https://user-images.githubusercontent.com/35628116/201874658-e0007e1e-39de-4a3b-9ab5-d4400f65340b.jpg" width="250" /> | <img src="https://user-images.githubusercontent.com/35628116/201874870-59f30972-233e-4422-b991-4f54dd2fd39b.jpg" width="250" /> |

WordPress - 21.0 - Version code: 1285
Android device name: Samsung SM-A137F

**Comment by staskus** [comment]
@thabotswana , thanks for notifying us!

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
> The visitor counter does not work

This issue was mentioned in this beta app review: https://play.google.com/console/developers/7957760354032996428/app/4974498245291407393/user-feedback/review-details?reviewId=6b83fda3-da1c-4b55-a437-dbf343755dc7&corpus=BETA_FEEDBACK

**Comment by ravishanker** [comment]
This seems to working alright now.  There's no data transformation happening in the code either!  See images below using Automattic Kudos site across mobile, and web!

| Android | Web |
|--------|--------|
| ![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/8c9ca019-79bb-4e35-852e-4fb2cec9d107)|![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/626f4b67-561c-47db-9e36-0dd7e6b50de1) ![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/0a0ac0ff-61a1-4c30-ac04-205d5b805678) ![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/58d0dfc2-a9c6-4aae-a51a-9a45f18e477f)| 



👋 @staskus - Could you please check this again?  If it's no longer an issue we can close this. 🙇

**Comment by staskus** [comment]
@ravishanker 

It looks like the issue is on the API side since it's reproducible both on the app and the web.

### Insights vs Years tab on the app:

- 2281 vs 2415 likes
- 1007 vs 1056 comments

| Insights      | Years |
| ----------- | ----------- |
| ![Screenshot_20240328_112652_Jetpack](https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/6558abfe-0279-4385-8191-b9dfad8cf935)      | ![Screenshot_20240328_112642_Jetpack](https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/38c19767-8fa3-4adb-bab2-321bab86bfac)       |

### Insights vs Traffic tab on the web:

- 5437 vs 5462 comments
- 11246 vs 11234 likes

| Insights      | Traffic |
| ----------- | ----------- |
| <img width="981" alt="Different numbers" src="https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/b6b5eca7-aaa8-4d4c-964d-99feb42a98b0">      | <img width="968" alt="2022" src="https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/237e31f9-7763-423c-8a43-0b5ecf011b86"> |

**Comment by staskus** [comment]
I investigated this before pc8eDl-BI-p2. This is API inconsistency and we can close Android and iOS (https://github.com/wordpress-mobile/WordPress-iOS/issues/19356) issues.

**Comment by guarani** [comment]
https://github.com/Automattic/jetpack/issues/36660 is where this bug is being tracked (sharing here for better visibility).
