### ISSUE TITLE
[Android] Stats: This week's views numbers don't match the Web or iOS

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#17211]
This week's views numbers on Android don't match Web and iOS. They also don't add up when adding day numbers separately for this week or for the last 7 days.

More context [in the investigation](https://github.com/wordpress-mobile/WordPress-iOS/issues/19337).

## Views card image:

- iOS shows numbers for the `Last 7 days` with the total of 825 views - correct
- Android shows 1026 which doesn't match either numbers for `This week` or `Last 7 days`

![image](https://user-images.githubusercontent.com/4062343/192462196-dfac0420-b1ac-4a55-801b-64b521e2c32e.png)

## Views details image:
- Web shows numbers for `This week` starting from Monday with the total of 782 views - correct
- iOS shows numbers for the `Last 7 days` (misleading) but the total of 825 views - correct
- Android shows 814 which doesn't match either numbers for `This week` or `Last 7 days`

![image](https://user-images.githubusercontent.com/4062343/192461186-47e20346-516c-4c26-b4da-b848d54e1759.png)

### Expected behavior

Both on the card and in the details view the numbers should match Web and show number of views  for "This week".

### Steps to reproduce the behavior

1. Open Jetpack app with Stats enabled
2. Open Stats tab
3. Make sure "Views and Visitors" card is added
4. Compare views numbers with the Web
5. Click "Week"
6. Compare views numbers with the Web

**Comment by staskus** [comment]
Note: The fix is implemented [on iOS side](https://github.com/wordpress-mobile/WordPress-iOS/pull/19393).

What was done:
1) On the main Insights view, the card shows stats for the last 14 days (splitting into two 7-day periods).
2) When we click "Week", we show stats based on weeks and taking into account the start of the week.

**Comment by mkevins** [comment]
Closing in favor of: https://github.com/wordpress-mobile/WordPress-Android/issues/17450
