### ISSUE TITLE
QR code login mechanism displays unexpected red text for success message

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-Android#17276]
### Expected behavior
The success text is displayed in a non-red color, likely the same color as other copy. The unexpected color is likely erroneously retained from the screen before where a security warning is displayed. 

### Actual behavior
The success text is displayed in a red color. 

<details><summary>Screenshot</summary>

![QR code login success displays red text](https://user-images.githubusercontent.com/438664/194146089-94b083eb-a29b-4937-be20-69c2288b0e69.jpg)

</details>

### Steps to reproduce the behavior
1. Visit https://wordpress.com/log-in. 
2. Tap _Login via the mobile app_. 
3. Follow the instructions provided to successfully log in. 
4. Note the text color displayed after succeeding.

**Comment by dcalhoun** [comment]
Hey @zwarm. 👋🏻 Do you happen to know if this is a valid bug and the text color is unexpected? Thanks!

**Comment by ovitrif** [comment]
> Hey @/zwarm. 👋🏻 Do you happen to know if this is a valid bug and the text color is unexpected? Thanks!

This issue was probably introduced with the Compose UI refactoring of the screen.
I'd say it's a bug, maybe of lower priority 👍
