### ISSUE TITLE
New site theme picker displays empty themes with no content

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-Android#17277]
This may be an API issue, not an app issue. 

### Expected behavior
Each theme preview image within the picker should display helpful content that showcases the theme's strengths. 

### Actual behavior
Some themes display little-to-no content in the preview images. 

<details><summary>Screenshots</summary>

![theme-picker-empty-1](https://user-images.githubusercontent.com/438664/194147194-b9a946cb-4f32-4f8c-8f91-2391ac005d8c.jpg)
![theme-picker-empty-2](https://user-images.githubusercontent.com/438664/194147196-96442aac-a757-4144-9b17-89d32446917d.jpg)
![theme-picker-empty-3](https://user-images.githubusercontent.com/438664/194147198-b5110187-7b23-43f5-af8d-68dc3e8a8b54.jpg)
![theme-picker-empty-4](https://user-images.githubusercontent.com/438664/194147200-e4b5379a-46e8-4f93-b0da-f04d9d930254.jpg)

</details>

### Steps to reproduce the behavior
1. Create a new WPCOM site. 
2. Select _News_ or _Personal_ as the site topic. 
3. Scroll through the presented theme previews.

**Comment by ovitrif** [comment]
Themes that have the no-content issue:
- Arbutus
- Remote
- Stewart
- Geologist

**Comment by ovitrif** [comment]
I've investigated this issue today and it might be related to recent changes to the API (internal ref: puPv3-ci2-p2#comment-24792).

**Comment by arthur791004** [comment]
Here is the fix: D89350-code

**Comment by ovitrif** [comment]
> Here is the fix: D89350-code

The fix was validated locally, then after it was deployed I validated it again in production.

Works like a charm, thank you @arthur791004 for fixing this so quickly 🙇

**Comment by arthur791004** [comment]
Thanks for the validation 👍 Do we need to purge the cache manually as I saw the mobile uses the mShot service to show the preview?
