### ISSUE TITLE
[UI Tests] - Re-enable disabled UI Tests

### ISSUE THREAD

**Issue by jostnes** [wordpress-mobile/WordPress-Android#17281]
There are 9 UI Tests that are currently disabled on WPAndroid. This is to track work to re-enable the tests or to remove them depending on the investigation results:

List of test cases:
- [x] e2eMessageCanBeSent
- [x] e2eSendButtonEnabledWhenTextIsEntered
- [x] e2ePublishFullPostClassic
- [x] e2ePublishSimplePostClassic
- [x] e2eLoginWithMagicLink
- [x] e2eLoginWithPasswordlessAccount
- [x] e2eLoginWithEmailPassword
- [x] e2eNavigateThroughPosts
- [x] e2eLikePost

**Comment by jostnes** [comment]
For the [e2eMessageCanBeSent](https://github.com/wordpress-mobile/WordPress-Android/blob/7192aea5d87d3020c453cb147eecd1271fdc860a/WordPress/src/androidTest/java/org/wordpress/android/e2e/ContactUsTests.java#L41-L62) test, I'm leaning towards removing it from the test suite for a couple of reasons:
1. This test has not been enabled in CI since its creation (see: [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15744))
2. As discussed in the PR, it would be noisy if this test ran every build and I'm not sure if the current value of the test (how many times has this feature stopped working, how often is this screen updated) would justify the amount of noise from it. There's currently no clean-up on Zendesk side, there are suggestions but again I'm not sure if the effort to implement that would be worth it for this one test.

@pachlava WDYT? I'll create the PR to remove this test soon if there are no objections to this, if we decide in the future that this test case has become critical we can always get it back from git history

**Comment by pachlava** [comment]
No objections for `e2eMessageCanBeSent` removal @jostnes 🙂

**Comment by jostnes** [comment]
For `e2eSendButtonEnabledWhenTextIsEntered` the reason it's failing in the CI is because the Contact Support screen is taking a very long time to load or maybe doesn't load at all (I can confirm that it works locally). 

I ran the test a few times by increasing the waiting time to wait for elements on the Contact Support screen and it was still stuck at loading on the Contact Support screen ([added normal wait](https://console.firebase.google.com/project/api-project-108380595987/testlab/histories/bh.f7bbef01bccfafb8/matrices/7074450095484945919/executions/bs.da631042f8e2f647/videos), [increased wait time to 250ms](https://console.firebase.google.com/project/api-project-108380595987/testlab/histories/bh.f7bbef01bccfafb8/matrices/8971841253142561206/executions/bs.3fdd773f974860d6/videos), [increased wait time to 400ms](https://console.firebase.google.com/project/api-project-108380595987/testlab/histories/bh.f7bbef01bccfafb8/matrices/8056463485225228440/executions/bs.7cd8e65a802b3d3c/videos)):
![image](https://user-images.githubusercontent.com/17252150/195005749-3980bde8-c109-47b2-93aa-662eb235d4ee.png)

I'm not sure why the screen doesn't load when running on FTL (it loads fine when testing using a local emulator), I'll revisit this after going through the other test cases. If we find that there's no solution to this one, I'd propose removing this from the test suite too since it isn't adding much value if we can't run it on FTL.

**Comment by jostnes** [comment]
For `e2ePublishFullPostClassic` and `e2ePublishSimplePostClassic`, I'll be removing these two. This is the [issue related](https://github.com/wordpress-mobile/WordPress-Android/issues/14389) to these two test cases. 

There is an internal discussion related to these two test cases: p9ugOq-20E-p2 and based on the discussion, looks like the tests are currently low-priority and have not been looked at for ~1 year. I've also looked at GitHub issues and PRs and have not seen any recent classic editor-related issues/PRs, confirming that this is a low-priority feature.

**Comment by jostnes** [comment]
After revisiting `e2eSendButtonEnabledWhenTextIsEntered` looks like it does work in FTL, I may have used a wrong element identifier previously which was why it wasn't working previously but after updating to the correct one it works fine now. This is [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17312) to re-enable the test, should be the last one before we mark this task as done.
