### ISSUE TITLE
Settings screen titles cut off instead of wrapping when too long

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17325]
### Expected behavior
I expected the titles of settings screens to wrap if the title is too long.

### Actual behavior
In German, the titles are too long and they get cut off.

<img src="https://user-images.githubusercontent.com/15107387/195535319-f5853bfd-7d45-4372-a012-439c18d59a15.jpg" width="50%">
<img src="https://user-images.githubusercontent.com/15107387/195535321-8945fb57-c848-4a23-8864-e4fdc5aa2cce.jpg" width="50%">
<img src="https://user-images.githubusercontent.com/15107387/195535322-3570e61e-808b-4e64-a57d-0d1d897aa035.jpg" width="50%">

### Steps to reproduce the behavior
1. Using Device language settings, change language to German.
2. Restart the app
3. Head to Reader and tap the "gear" icon.
4. Note that the title, "Themen und Websites verwalten" is cut off.
5. Head to Notifications (Benachrichtigungen) and tap the "gear" icon.
6. Note that the title, "Benachrichtigungen-Einstellungen" is cut off.
7. Head to My Site > Posts and select a post to edit.
8. Tap the "..." and select Post Settings (Beitrags-Einstellungen)
9. Note that the title, "Beitrags-Einstellungen" is cut off.

**Comment by irfano** [comment]
@thehenrybyrd, I'm not sure how we can solve this issue.
[In material guideline](https://m2.material.io/components/app-bars-top#anatomy), two lines title is recommended instead of a truncated title.

<img src="https://user-images.githubusercontent.com/2471769/198093588-c20c7102-ff30-4b6c-8b41-aac286f2cc4b.png" height=640>

**But** Google doesn't use that rule on its apps. Notice the title is truncated.
<img src="https://user-images.githubusercontent.com/2471769/198094363-2e5fc521-0045-48fb-ab78-6be1cee4c7bf.png" height=640>

Currently, the screen title is always a single line on the entire app. We can make long titles two lines but it looks a bit weird to me. So, I propose keeping the single-line standard for titles. **Wdyt?**

<img src="https://user-images.githubusercontent.com/2471769/198096441-9680eff5-b714-4525-a817-cf6c95cbe24f.png" height=640>

**Comment by thehenrybyrd** [comment]
@irfano it definitely is different, and I share your sense of "this is weird". And this is definitely not the first time I have seen Google choosing to ignore material guidelines 😅 

However, it's important to consider readability. 
For an example, let's take the German "Themen und Websites verwalten". In English, we say "Manage sites and topics". It's easy to tell what the verb (manage) is, even if this is cut off: "Manage sites and top..." 
However, in German the verb often comes last. So if we do a more direct translation we'd get something like "Topics and sites manage". 
Imagine then if this is cut off: "Topics and sites man..."

It becomes easier to misinterpret this. 
Since the title should only wrap when it would otherwise be cut off, my opinion is that the wrapping looking weird is worth the understandability.

What do you think?

**Comment by thehenrybyrd** [comment]
I ran into this in another place during smoke testing on Jetpack Android 21.0-rc-3:
If you use "login with QR code" to login to a web browser, the success message title in the app is too long in German: 

<img src="https://user-images.githubusercontent.com/15107387/198565426-37e3c8c0-ca5e-4f46-8931-9d3edcc81be6.jpg" width="50%">

**Comment by irfano** [comment]
> Since the title should only wrap when it would otherwise be cut off, my opinion is that the wrapping looking weird is worth the understandability.
What do you think? 

@thehenrybyrd, Makes sense! Making the title multiple lines would also align with the material guideline.
We can make this change to all screens. But we can start with some screens in which we've found an issue with the long title for now.

**Comment by thehenrybyrd** [comment]
@irfano sounds good! I'm going to mark this with "good first issue" - please let me know if you disagree (you'd know the complexity better than I).

**Comment by thehenrybyrd** [comment]
Another spot with this issue is in Stats > Add new card:

<img src="https://user-images.githubusercontent.com/15107387/203794824-ea39b13c-73b4-4e6f-b3cc-0eb465870472.jpg" width="50%">

**Comment by hrishibargal** [comment]
I would like to work on this issue could u please assign it to me if it is still open

**Comment by Excalibur1999** [comment]
look into this PR Excalibur1999:fix_for_#17325_title_getting_cut
