### ISSUE TITLE
RuntimeException: android.os.TransactionTooLargeException: data parcel size 3553624 bytes

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#17349]
**Sentry Url**: https://sentry.io/share/issue/bf042bd721534383bc6139c367225f8d/
**User Count**: 350
**Count**: 2998
**First Release**: org.wordpress.android@17.5+1058
**First Seen**: 2021-06-18T02:16:27.058000Z
**Last Seen**: 2022-10-18T09:53:12Z
**24 Hours**: 29
**30 Days**: 950

```
RuntimeException: android.os.TransactionTooLargeException: data parcel size 3553624 bytes

...
(3 additional frame(s) were not displayed)
```

**Comment by antonis** [comment]
Closing as duplicate with https://github.com/wordpress-mobile/WordPress-Android/issues/9685
