### ISSUE TITLE
 schedule post is auto enable, this is not good idea

### ISSUE THREAD

**Issue by ffmeet** [wordpress-mobile/WordPress-Android#17375]
### Expected behavior

The normal product logic is, click publish, it should be published immediately at the current time

### Actual behavior

In fact, when the wordpress app publishes an article, it automatically becomes a timed release, and the manual modification time is now, which is useless, update it, and finally plan it regularly.

Feedback from other people is that the time is set to yesterday, and the update has become published.

**Comment by thehenrybyrd** [comment]
Hi @ffmeet, can you clarify the issue for us? Currently, when I publish a post, it is set to publish immediately.
If that's not what you're seeing, please tell us how to reproduce the issue. Any screenshots you can include would also be helpful.

**Comment by twstokes** [comment]
In the latest Android version (24.6-rc-2) I'm seeing this behavior when publishing posts with the Publish Date set to "Immediately". It seems that the device time is included in the API call, which can turn this into a scheduled post if it's ahead of the server time.

**Steps to reproduce:**
1. Created a WP site connected to Jetpack (I did self-hosted, but a WP.com site may work as well)
2. On my Android device disabled auto time sync and put the time ~ten minutes ahead
3. Created a new test post and published it immediately

**Expected:**
The post to be published immediately.

**Actual:**
The post was scheduled to publish in the future.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
