### ISSUE TITLE
Android - Permissions Screen

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#17372]
## Description

This task is to create a screen for the UI to request notification permissions after the migration flow during Jetpack first launch. 

|Permissions screen|
|---|
|![notifications](https://user-images.githubusercontent.com/304044/198050141-95d53c85-0f2f-4054-98ec-3d5815ebaade.png)|

_Note that the final Android notification image depicted above might be different ([conversation](https://www.figma.com/file/qk5s4q4mZsXknwhMWo2vIY?node-id=5075:17254#293801174))_

Internal refs: `pcdRpT-175-p2`

**Comment by ovitrif** [comment]
Closing this issue since there are existing tickets for the remaining work (disable notifications in WP).
