### ISSUE TITLE
Jetpack: Title / navigation during login are cut off (arrow, "Get Started", help icon)

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/WordPress-Android#17405]
### Expected behavior
When logging in to Jetpack, the top of the app should always be accessible and below the top of the phone's info bar (with battery life, time, wifi signal, etc.)

### Actual behavior
The top of the app is hidden under the always-present info on the top of the screen (time, battery level, etc.)
This makes it really tough to either go back to the previous screen or access the help options.

I'm seeing this happen on these screens:
* Get started (login with WP.com credentials)
* Log In (password screen when logging in with WP.com credentials)
* Log In (login with site address)
* Log In (2FA / verification code input)

<img src="https://user-images.githubusercontent.com/103850310/199320265-2c2ed65e-181e-4698-90b3-8d29e82fee08.png" width=500px>

### Steps to reproduce the behavior
1. Start login process
2. Note overlap of phone info with top of Jetpack app

**Comment by ParaskP7** [comment]
👋 @lmischner @ovitrif !

I think this should have been automatically close, but it wasn't, should we now close that or is it still open purposefully? 🤔

**Comment by lmischner** [comment]
@ParaskP7 - No reason for it to be open that I'm aware of! Closing now.

FYI @ovitrif

**Comment by ovitrif** [comment]
Thank you both @ParaskP7 & @lmischner 🙇 , indeed the issue can be closed, should have been done by GitHub automagically 👀  but maybe that didn't happen because the fixing PR wasn't targeting `trunk`

**Comment by ParaskP7** [comment]
> ...but maybe that didn't happen because the fixing PR wasn't targeting `trunk`

True! 🤷
