### ISSUE TITLE
Stats Revamp: Use Jetpack green color for charts

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-Android#17418]
On JPAndroid, the Views & Vistors graph on the Stats Insights tab uses WordPress blue as the accent color. 

It would look nicer if we used the Jetpack green color - especially since the other Stats tabs use Jetpack green for the graphs.

<img src="https://user-images.githubusercontent.com/6711616/199759422-10bbd5ca-dafe-4729-aeb9-cc429200e7bb.png" width=200> | <img src="https://user-images.githubusercontent.com/6711616/199759411-b44a07ec-bcee-48c5-b57c-a798eaefa3b7.png" width=200>
-- | --

**Comment by guarani** [comment]
👋 @ravishanker, do you know if using blue here on the chart in the Jetpack app was intentional or not?

**Comment by irfano** [comment]
> 👋 @ravishanker, do you know if using blue here on the chart in the Jetpack app was intentional or not?

It was intentional. 
Initial discussion: p1656065217155559/1656022343.761309-slack-C02UJ9192TC
Current discussion: p1673863317990199/1673461455.583419-slack-C042DG1CHJN

**Comment by guarani** [comment]
Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/19883#issuecomment-1383943805, I'm closing this.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
