### ISSUE TITLE
Auto-linked url are not editable

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1742]
Steps:
 * Share a link to the WP app (e.g. Chrome -> Share -> WP)
 * The link appears in the Content TextEdit but can't be edited by tapping the "link" icon.

**Comment by georgestephanis** [comment]
Note to self: screencap process of duplicating the issue for FBOA students.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
