### ISSUE TITLE
Hide Scan Login Code when logged into an account with 2FA

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17434]
### Expected behavior
Expected not to see this option when logged into an account with 2FA, since Scan Login Code is not available for 2FA-enabled accounts.

### Actual behavior
Scan Login Code appears, leading me to believe I can use it. Then, when I try to use it to login to a WordPress.com site, I get an "Authentication Failed" message. This message encourages me to try scanning again.

### Steps to reproduce the behavior
1. Login to the Jetpack app with a WordPress.com account that has 2FA enabled.
2. In a web browser, open a browser or incognito tab where you're not logged into WordPress.com.
3. Head to WordPress.com > Login > Login via the Mobile App. Note the QR code is shown.
4. In the app, head to Me > Scan Login Code, and scan that QR code.
5. Note that authentication fails

Suggestion: Remove "Scan Login Code" from Me section when logged into an account with 2FA enabled.
Alternative: Adjust the "authentication failed" message to state that you cannot use QR code login for an account with 2FA enabled.

**Comment by zwarm** [comment]
FYI: @thehenrybyrd - we are adding a message to [calypso](https://github.com/Automattic/wp-calypso/pull/68917) too that this can't be used when 2FA is enabled. Just waiting on localization to complete.

**Comment by thehenrybyrd** [comment]
User report in 5719223-zd-woothemes, the user was unable to login via QR code, but doesn't know why.

**Comment by thehenrybyrd** [comment]
Also, as I forgot to link them earlier - the same suggestion exists for iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/19567
