### ISSUE TITLE
Stats: Enable Site Stats fails when Jetpack Plugin is in site-only connection state

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17433]
### Expected behavior
Expected tapping "Enable site stats" prompt to allow me to connect my site and load stats.

### Actual behavior
When the Jetpack Plugin is in a site-only connection state, tapping "enable stats" results in an error.

### Steps to reproduce the behavior
1. Create a new self-hosted site, and get it into site-only state by:
- From wp-admin on the web, install the Jetpack Plugin, and activate it.
- Still in wp-admin, tap "set up" for the Jetpack Plugin, but don't complete the process. When you see "Connecting as...", don't tap "Approve," instead press the back button.
- You'll now see the following in wp-admin > Jetpack, towards the bottom:
<img src="https://user-images.githubusercontent.com/15107387/200274795-9edcc444-52ab-47f9-b967-0545a9052e6d.png" width="90%">

2. In the app, add your self-hosted site. I did this while already logged into a WordPress.com account on the app.
3. Once added, tap "Stats" and note you see the "Enable site stats" prompt.
4. Tap "Enable site stats" and note you see the error "Unable to activate site stats".

https://user-images.githubusercontent.com/15107387/200276089-6872cd92-b074-49fe-9b56-1f043e0cc695.mp4

**Comment by pi3c3** [comment]
+1

**Comment by nizmotek** [comment]
+1

**Comment by ravishanker** [comment]
This seems like an exception rather than rule  or bug.  App has know knowledge of incomplete, and short circuited setup to cater for this case.

Looks like a stale issue, and over an year since this has been raised.  Hence closing
