### ISSUE TITLE
Stats: Negative percents (and other numbers with hyphens) are inverted in Arabic

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17447]
### Expected behavior
I expected numbers with hyphens, as with other numbers, to display LTR in Arabic.
For a correct example:

the best number is 35
أفضل رقم هو 35

### Actual behavior
Numbers with hyphens get ... mixed up, especially in conjunction with other characters like parentheses and periods.

### Steps to reproduce the behavior
1. Set your device language to Arabic
2. Open the Jetpack app and head to Stats > Insights, on a site that has less traffic this week than last week.
3. Note the negative percentages of the "Views and Visitors" card.

-or- 

1. Set your device language to Arabic
2. Open the Jetpack or Wordpress app and head to Me > About WordPress/Jetpack 
3. Note the inverted release number

Examples from Stats and About:

![invertednumbers](https://user-images.githubusercontent.com/15107387/201055740-bf703b3a-6842-4ba4-a6a2-cc99edcca7c0.jpg)

The hyphen (minus sign) appears to be the main instigator of the problem, but parenthesis and the period may also be playing a part.

**Comment by dlind1** [comment]
Similar issue in Calypso - https://github.com/Automattic/wp-calypso/issues/71657, so using one of the solutions from https://www.w3.org/International/questions/qa-bidi-unicode-controls should work here.

**Comment by irfano** [comment]
This is how percentages are shown on the web.

<img width="640" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/8599f28e-306c-47ba-914b-c21a3bd33eec">

**Comment by irfano** [comment]
I updated the strings on the translation page. But the direction of the percentage number is still wrong. So, it will look like this in the next release:

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/2587703c-ea33-40d9-9cca-95f72c8c07f0" width=320>

**Comment by irfano** [comment]
The app version bug is related to about lib. I've opened an issue there: https://github.com/Automattic/about-automattic-android/issues/54
