### ISSUE TITLE
Surface the block site option in the reader

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#17589]
### Description
In order to make the **block site option** more prominent we want to make it available on the site header. For this to happen we will:
* Add a new overflow `...` menu button next to the `Follow/Unfollow` button
* Tapping the `...` for the site should present an abbreviated menu with the option to **Visit Site**, or **Block this site**.

Note that tapping `...` on a post (whether in this view or elsewhere) would still give you the same options as we have today.

The expected functionality would look like the following mocks.

|Site view overflow ... button|Overflow menu|
|---|---|
|![site-view](https://user-images.githubusercontent.com/304044/205035268-b1455c4f-ac24-423b-920c-140b0cbaa14e.png)|![site-](https://user-images.githubusercontent.com/304044/205035299-ee3c3b16-48c0-46cf-b387-b9eaa5957b7e.png)|

Internal ref `pcdRpT-1ms-p2`

**Comment by zwarm** [comment]
Closing this issue. It is not necessary to resurface the blocking options to the header. See pcdRpT-1ms-p2 for the details.
