### ISSUE TITLE
Android - After migrating from WordPress the avatar is not showing

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#17647]
## Description
After migrating from the WordPress to the Jetpack app the avatar does not appear on the MySite screen

### To reproduce:
1. Uninstall the Jetpack app or clear app data
2. Start the migration flow from the WordPress app
3. Notice that the avatar is appears on the welcome migration screen
4. Proceed till the end of the flow
5. **Notice** That the avatar does not load on the *My Site* screen
6. Put the app on the background and bring it up again
7. Notice that the avatar now appears

**Comment by thehenrybyrd** [comment]
Similar issue over on iOS, though this one is specific to self-hosted sites: https://github.com/wordpress-mobile/WordPress-iOS/issues/19867
