### ISSUE TITLE
Android - Finish the WP app after the migration to JP is initiated

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#17656]
## Description
~~We should `finish` the WP app at the end of the migration flow.~~
We should `finish` the WP app at the start of the migration to Jetpack app, so that when users navigate back either from the Play Store or the Jetpack app, they don't land in the WordPress app anymore.

Note: We should check if that does not have side effects since the JP app calls the WP for fetching data. If that is the case we should drop this requirement.

Internal ref pcdRpT-1i3-p2#comment-2374

## Edits:
Based on the referenced internal discussion (pcdRpT-1i3-p2#comment-2374), my understanding is that we actually want this even sooner, when users tap on the `Try the new Jetpack app` button in the WordPress app.
I updated the title and description 👍

**Comment by ovitrif** [comment]
### Update
~~Probably this task won't materialize, as we're now [redirecting to the login flow](https://github.com/wordpress-mobile/WordPress-Android/pull/17628) when the user navigates back from the migration flow.~~

We'll still pursue implementing this enhancement (internal ref: pcdRpT-1i3-p2#comment-297)
