### ISSUE TITLE
Android - Hidden sites in the site list are not transferred

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#17654]
## Description
The hidden sites in the site list are not transferred in the WordPress to Jetpack migration

### To reproduce:
1. select a site in WordPress, then switch sites. Check that the first site is shown up top in site list.
2. complete the migration flow.
3. Notice that after flow, the hidden sites are shown

Internal ref pcdRpT-1i3-p2#comment-2342

**Comment by ovitrif** [comment]
> 3. Notice that after flow, the hidden sites are shown

I've tested this and it seems to be already the case, hidden sites from the WordPress app do remain hidden in the Jetpack app ✅ , when going to the Site picker screen.

Though what I understand from the internal ref (pcdRpT-1i3-p2#comment-2342), quoting:
> Sites that I hid from my My Sites list appear in the migration screen.

might be that we could consider hiding the sites from the migration screen, where they're not hidden 👍

**Comment by antonis** [comment]
Thank you for investigating @ovitrif 🙇 
> might be that we could consider hiding the sites from the migration screen, where they're not hidden 👍

If that's the case I think we could close the issue and follow up on the P2 thread with our findings.

**Comment by ovitrif** [comment]
> If that's the case I think we could close the issue and follow up on the P2 thread with our findings.

Thank you for the suggestion @antonis 🙇 

I've added an internal comment about this (ref: pcdRpT-1i3-p2#comment-2457)

**Comment by antonis** [comment]
Closing this issue (ref pcdRpT-1i3-p2#comment-2458)

**Comment by mkevins** [comment]
> it seems to be already the case,

Thanks for commenting! I was looking into this, and trying to determine when it was fixed - makes much more sense with the extra context 👍
