### ISSUE TITLE
Notifications: Stale locale for notifications items after locale switch

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-Android#17672]
### Expected behavior
The items should be displayed correctly with the chosen locale.

### Actual behavior
The items show inconsistent display, sometimes with a previously set locale.

### Steps to reproduce the behavior
1. Open the notifications screen
2. In device settings, change the language

Example: 

<img src="https://user-images.githubusercontent.com/8507675/207807736-60f0f415-9871-4717-8295-dab95babb4b8.png" width="360">

Note: It doesn't happen every time, and there may be a race condition involved.

##### Tested on Pixel 3a, Android 12, WPAndroid `trunk` @ https://github.com/wordpress-mobile/WordPress-Android/commit/63c03a2fdb813e68490162d7395ffc1fa0719683

**Comment by antonis** [comment]
I wasn't able to reproduce with the latest version of the app (`24.3`) on a Pixel 5/8 with Android 14.

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/afc9e6e9-d590-4187-9863-55dc393a242b

@mkevins feel free to reopen if the issue persist on your tests 🙇

**Comment by mkevins** [comment]
I also did not reproduce this on the latest `trunk` (7823b4d8514de38c5694a8076177da0988958170). However, instead I now see a different bug: after switching to Arabic, some notifications are blank. Weirdly enough, when I switch back to English, they are blank in dark mode, but not in light mode. 🤔 

Screenshots:

|Arabic|English|
|-|-|
|![blank-notifications-in-arabic](https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/694ef478-4f1f-4290-b7d9-c661cdb89cac)|![blank-notifications-in-english](https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/f394d85c-f256-49e9-87b9-98283c0d0031)|

This feels like a different issue, so not re-opening this one makes sense to me. If you agree, I can open a new one.

**Comment by antonis** [comment]
Thank you for testing @mkevins 🙇 

> This feels like a different issue, so not re-opening this one makes sense to me. If you agree, I can open a new one.

I tested both with change the language from the system setting and from the application settings in the me tab and wasn't able to reproduce the empty rows. My test device is a Pixel 5 with Android 14.
Even if the bug is device or Android version specific I think it makes sense to open a new issue to track it.

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/214e2cba-269c-4306-be6f-683053b7885c
