### ISSUE TITLE
Show a toast with message when trying to change the primary site, for users having only one site 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#17676]
### Expected behaviour

When trying to change the primary site when only one site is present, it shows a toast message notifying the user that only one site is present. 

https://user-images.githubusercontent.com/4975407/205236678-92dba67e-cadf-4d5f-ba8a-27451ff3ad7b.mp4

### Actual behaviour
https://user-images.githubusercontent.com/17463767/208032634-bc562cf2-4ce3-4d71-9e4c-0a161a6ddc51.mp4

### Steps to reproduce the behaviour
- Launch the WP app with an account having only one site 
- Go to Me -> Account settings -> Primary site 
- Notice that tapping on the primary site doesn't have any feedback

**Comment by dipankarupd** [comment]
Hey! It seems like nobody is working on this issue. Can I work to fix the issue?

**Comment by osullivanchris** [comment]
@AjeshRPai you asked me for a message to use on this issue, is that correct? I think it could say 
> Only one site is available so you can't change your primary site

I noted on the other task that we don't usually display any message though when someone taps a disabled field. What do you think about that?

**Comment by AjeshRPai** [comment]
@osullivanchris 

Sorry for the late reply, I think the message you suggested works  👍🏼 

>Only one site is available, so you can't change your primary site

**Comment by AyushUnleashed** [comment]
I want to work on this issue, can you guide me on how should I approach this & Assign me? @AjeshRPai 

As I am a beginner & this is just a small change in Toast message, I can do this & it will help me start my open-source journey.

**Comment by AyushUnleashed** [comment]
Update: I have done local setup of this project & I have started working on this issue.

**Comment by AjeshRPai** [comment]
Hey @AyushUnleashed 

Thanks for your interest. 

>As I am a beginner & this is just a small change in Toast message, I can do this & it will help me start my open-source journey.

Nice. Way to go 🙇🏼 

As described in the expected behaviour, we should display a toast message **Only one site is available, so you can't change your primary site** when the user tries to change the primary site with only one site available. 

Once you are done with the changes, you can create a PR and request for review from me. Please look at the [contributing guidelines](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/CONTRIBUTING.md) if you need any info or feel please free to ping and ask me here. 

I'm looking forward to your PR and more contributions. Once again, thanks @AyushUnleashed, I am assigning the issue to you.

**Comment by AyushUnleashed** [comment]
I added the Toast Message directly, but I cannot add a new string in strings.xml, there are several places where I can add it. (since Multiple Languages) can you guide me in adding a new string in strings.xml or should I avoid it for now? @AjeshRPai

**Comment by AjeshRPai** [comment]
Hey @AyushUnleashed 👋🏼 
You can add the string for en in strings.xml, and the translations will be taken care of during the release.

**Comment by AyushUnleashed** [comment]
@AjeshRPai I have created the pull request with changes, kindly go through it.
