### ISSUE TITLE
[Blogging Prompts] Add new analytics events to "My Site" card and create sheet

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#17689]
Implement the following analytics events:
- `blogging_prompts_my_site_card_viewed`: "My Site" home tab was loaded and prompt card is present.
- `blogging_prompts_create_sheet_card_viewed`: "Add new" sheet was loaded and prompt is present.

**Comment by thomashorta** [comment]
The implementation for one of the events will still be done, so I will reopen the issue:
- `blogging_prompts_my_site_card_viewed`: "My Site" home tab was loaded and prompt card is present.
