### ISSUE TITLE
Webpage Opens on Rotate on Overlay Screen

### ISSUE THREAD

**Issue by JB184351** [wordpress-mobile/WordPress-Android#17716]
### Expected behavior
I expect the Overlay screen to rotate as the device rotates and UI to change appropriately.

### Actual behavior
When rotating the device the webpage opens for the `Learn more at jetpack.com`.

### Steps to reproduce the behavior
1. I was testing this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17580#event-8153634849) when I saw it, though this PR is merged in by now.
2. Enable Phase 2 by going to App Settings > App Debug Settings > select the check box for `jp_removal_two`.

##### Tested on [device], Android [version], WPAndroid [version]
Samsung A51, Android 12, WPAndroid Trunk (as of 1/04/2023).

**Comment by zwarm** [comment]
@JB184351  👋 

Thanks for reporting this bug, but I'm having trouble reproducing. Can you give it another whirl and let me know if this is still occurring please? 

WPAndroid branch release/21.6 as of Jan 25, Google Pixel 5, Android 13

**Comment by JB184351** [comment]
> @JB184351 👋
> 
> Thanks for reporting this bug, but I'm having trouble reproducing. Can you give it another whirl and let me know if this is still occurring please?
> 
> WPAndroid branch release/21.6 as of Jan 25, Google Pixel 5, Android 13

Yeah, I can't seem to reproduce anymore, I'll close the issue now.
