### ISSUE TITLE
Author selection for Pages should not include users with roles lower than Editor

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#17739]
### Expected behavior
1. Author selection feature is available
2. List of authors doesn't contain users who have a role lower than Editor

### Actual behavior

**Self-hosted sites** without a WordPress.com connection
- Author selection feature isn't available

**WordPress.com sites** 
- Author selection feature is available
- List contains all users on the site
- When selecting the other user (with a role lower than Editor) and publishing the Page, an error is presented by the user interface

<img src="https://user-images.githubusercontent.com/2092798/211726997-da6225d8-99f6-4b67-9f91-083fabfb66ee.png" width="300" />

### Steps to reproduce the behavior

**Prerequisites:** Two users exist on a blog - one Administrator role, and one lower than Editor (e.g. Author or Contributor).

- [WordPress.com roles](https://wordpress.com/support/user-roles/)
- [WordPress.org roles](https://wordpress.org/support/article/roles-and-capabilities/)

1. Log into the app as the Administrator user
3. Tap the FAB and select Site page to create a page
4. Choose any layout
    - ℹ️ If the Blank Page layout was chosen, populate a title
5. Open the Page settings view and observe the options

### Notes

WordPress.com's web interface (Calypso) allows one of these users to be set and for the Page to be published without error.

**Comment by twstokes** [comment]
WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/19886

**Comment by zwarm** [comment]
I am not seeing this behavior in Android. My author list, for both posts and pages, show Admin, author, contributors, or editors roles. In addition, I double checked the api call and have verified we are requesting people where "authors_only=true". Perhaps this has changed from 2023.  @twstokes - can you verify this is still happening? Thanks

**Comment by twstokes** [comment]
@zwarm If you're not able to reproduce it with those steps then  we're probably good! Thanks for the follow up. I think we can close it.

**Comment by zwarm** [comment]
Closing. The issue seems to have been resolved.
