### ISSUE TITLE
Android - Add better logging for migration errors

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-Android#17746]
We are currently only logging a subset of possible errors via Tracks events, but we have a fairly comprehensive set of errors that we can detect. This task is to enable logging of these errors so that more details can emerge from users who wind up in support queues as a result of the migration.

**Comment by ovitrif** [comment]
Adding this reference to the code where migration errors are being handled, where we can start looking into enhancing the logging:

https://github.com/wordpress-mobile/WordPress-Android/blob/0002b4ede131f3bcc8f99596098d3832a81ffa95/WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt#L73-L84
