### ISSUE TITLE
Jetpack Feature Deadline Isn't Being Shown on the Banner

### ISSUE THREAD

**Issue by JB184351** [wordpress-mobile/WordPress-Android#17763]
### Expected behavior
I expect that for Phase 3 the Jetpack banner to give a countdown of when the feature will be removed from the app.

### Actual behavior
Right now the banner just says `Jetpack powered`.

### Steps to reproduce the behavior
1. In the app debug settings toggle on `jp_removal_three`.
2. Notice the banner only says `Jetpack powered`.

##### Tested on [device], Android [version], WPAndroid [version]
I tested this on a Samsung Galaxy A51 device, Android 12, WPAndroid trunk.

<img src="https://user-images.githubusercontent.com/36495451/212435390-ec0be14d-da60-42db-a4c5-0090bd49a4e8.jpg" width="250" height="500">

**Comment by AjeshRPai** [comment]
Hey @JB184351 
I am closing this issue as we are yet to do this implementation. The implementation is tracked [here](https://github.com/wordpress-mobile/WordPress-Android/issues/17335)
