### ISSUE TITLE
Improve error messages on failed post upload

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1777]
When a post failed to upload, we're displaying the error coming from the server, which is very cryptic for the user and doesn't help him to fix the problem.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by catehstn** [comment]
Is error messaging improved in FluxC, @aforcier - I think we talked about this but I could be wrong...

**Comment by aforcier** [comment]
@catehstn I think we were actually discussing login error messaging, which is improved with FluxC (some new cases identified and accurately reported).

Post error messaging is improved a bit, but not enough. The main improvement is that FluxC is identifying and classifying the server errors with more precision. But we're not doing a lot with the improvements in the UI yet - there's more work to do in presenting a custom error to the user in those cases. It'll just be a bit easier to do now with FluxC.

There are also [some issues](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/129) with identifying errors on XML-RPC sites. And WP.com errors, while identifiable, are not localized, so we need to handle that ourselves.

I think post error messages deserve a full sweep. I recommend keeping this issue open and working on this in the FluxC branch.

**Comment by maxme** [comment]
> There are also some issues with identifying errors on XML-RPC sites. And WP.com errors, while identifiable, are not localized, so we need to handle that ourselves.

We can't get better messages from XMLRPC responses. So we'll only fix this for wpcom sites (identify and provide a better message if the API message is cryptic).
