### ISSUE TITLE
[Blogging prompts] DayOne attribution string translation issue

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#17772]
Internal reference: p5T066-3NG-p2#comment-14206

Blogging Prompt Card on the Home screen has a missing piece of text in Portuguese. The text in English is “From DayOne” and it should be something like “De DayOne”, but it only says “De”.

![image](https://user-images.githubusercontent.com/5091503/212917317-0a78643e-495e-4bee-8e45-ee94439c1a77.png)

After a quick investigation, it looks like ALL languages have that translation mistake for the my_site_blogging_prompt_card_attribution_dayone string, and I think it’s because it’s using an HTML tag (`<b>`):
https://github.com/wordpress-mobile/WordPress-Android/blob/4b791d57a131178209b82772610f1b61386268c4/WordPress/src/main/res/values/strings.xml#L2329

I think this is the problem because even the original string in [GlotPress](https://translate.wordpress.org/projects/apps/android/dev/pt-br/default/?filters%5Bterm%5D=my_site_blogging_prompt_card_attribution_dayone&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) just says “From”, which resulted in this localization error.

![image](https://user-images.githubusercontent.com/5091503/212918648-0e631fad-4d63-49e4-b031-251462632e24.png)

### Expected behavior
The text in English is “From DayOne” and it should be something like “De DayOne” in Portuguese (and the proper translation in other languages).

### Actual behavior
The text in English is “From DayOne” and it should be something like “De DayOne”, but it only says “De”. Same for all other languages.

### Steps to reproduce the behavior
1. Install Jetpack
2. Log in with a WP.com account that contains a blog (with some posts)
3. Set either the device or app language (in App Settings) to anything different from en-US
4. Go to My Site -> Home
5. **Verify** the Blogging Prompts card is displayed
6. **Notice** the attribution text next to DayOne icon only has the translation for "From" and not "From DayOne"

##### Tested on Samsung Galaxy S21+, Android 13, JPAndroid 21.5-rc-1

**Comment by AliSoftware** [comment]
The solution to this issue should be to XML-escape the brackets around the HTML tag in the `values/strings.xml` file.
Then, once the fix lands into `trunk` (+ Team Global's wpcom cron job runs to import that file from `trunk` into GlotPress run), the new original will end up in GlotPress and be translated by translators again.

```diff
- <string name="my_site_blogging_prompt_card_attribution_dayone">From <b>DayOne</b></string>
+ <string name="my_site_blogging_prompt_card_attribution_dayone">From &lt;b&gt;DayOne&lt;/b&gt;</string>
```
