### ISSUE TITLE
The site settings title should update when the site title is updated

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#17775]
### Expected behavior
The screen title should update when the "Site Title" is updated on the Site Settings screen.

### Actual behavior
When the "Site Title" is updated on the Site Settings screen, the screen title stays the same.

[site-settings-title.webm](https://user-images.githubusercontent.com/2471769/212954587-1065ee05-ef73-4e5f-ae8b-8f144826bc00.webm)

### Steps to reproduce the behavior
1. Launch the app.
2. Navigate to "My Site → Menu → Site Settings".
3. Tap "Site Title" and update the site title.
4. Notice title on the "Site Title" button is updated, but the screen title at the top of the screen still shows the old title.

**Comment by hmncube** [comment]
@irfano I would like to work on this issue

**Comment by irfano** [comment]
> @irfano I would like to work on this issue

👋🏻 @hmncube!
Thank you! You can review "[How to Contribute](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/CONTRIBUTING.md)" page and work on it.

**Comment by kushagraahire** [comment]
@irfano I want to contribute to this issue.

**Comment by irfano** [comment]
Hey @kushagraahire! @hmncube could be already started to work on the issue. If so, you can select another issue from [good first issues](https://github.com/wordpress-mobile/WordPress-Android/labels/good%20first%20issue).

 ---

 @hmncube, are you still on the issue? If you started, I can assign the issue to you.

**Comment by hmncube** [comment]
@irfano Already started will open a PR in a couple of hours
