### ISSUE TITLE
Direct users to the new .org Mobile forum

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#17801]
The WordPress mobile apps have a new forum: https://wordpress.org/support/forum/mobile/

The app should switch from the current Zendesk-based support to the new forum to help users find solutions to their issues.

> **Warning**
> Update: This change should not affect the Jetpack app at all. Also, the designs are outdated.
>   - The WP app should replace the Zendesk support options with the forum
>   - The JP app should show the Zendesk support options as before

### Design
- Figma: qk5s4q4mZsXknwhMWo2vIY-fi-3882%3A14189

| <img width="944" alt="Screenshot showing iOS designs for forum entry point" src="https://user-images.githubusercontent.com/1898325/214139627-0b14c5aa-2563-4bda-9412-d91067559b1f.png"> |
| - |

### User stories
- As a user looking for answers to a question I have, I can navigate the forum without a WP.org account
- As a user with a question to ask, I will create a new WP.org account (or sign in to an existing one) to ask the question on the forum
- ~~As a user with an open support ticket on Zendesk, when I download the new app version, I can continue to get support by replying to the email I got when I started the support ticket~~
- ~~As a Talkback user, I can get support on the forums like I did previously via Zendesk~~
- ~~As a user posting to the forums multiple times, I only need to log into my WP.org account once~~
- ~~As a user wanting support, I don't need to leave the app (the forum is in an in-app web view)~~
- As a project maintainer, I want to remotely control this rollout via a feature flag

### What are the entry points into the forum?
Anywhere where we currently show a button to contact support. This includes:
- Open My SIte tab, tap profile pic, tap Help & Support
- ~~Open block editor, tap three-dot menu, tap Help & Support~~
- Tap Log in / Sign up button on app welcome screen, tap Help
- A support button is shown in various alerts shown throughout the app

### Shipping
Let's use a feature flag to release this (in case we want to pause it for any reason)

**Comment by guarani** [comment]
I updated the issue since this has been scoped down to just open the forum on the device's browser.
I also added a note that this issue only affects the WP app, not the JP app.

**Comment by guarani** [comment]
@ravishanker, do you think this is ready to close?

> A support button is shown in various alerts shown throughout the app

I remember seeing alerts in the iOS app that have a "contact support" button. Do you know if this is the case on Android as well?

**Comment by ravishanker** [comment]
Yes, since we're no longer implement web view
