### ISSUE TITLE
Add navigation from a Forum Support card to Forum

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#17808]
Parent: https://github.com/wordpress-mobile/WordPress-Android/issues/17801

Add navigation from a Forum Support card to Forum

- As a user looking for answers to a question I have, I can navigate the forum without a WP.org account
- As a user posting to the forums multiple times, I ~~only~~ need to log into my WP.org account ~~once~~
- ~~As a user wanting support, I don't need to leave the app (the forum is in an in-app web view)~~

### What are the entry points into the forum?

Anywhere where we currently show a button to contact support. This includes:
- Open My SIte tab, tap profile pic, tap Help & Support
- ~~Open block editor, tap three-dot menu, tap Help & Support~~
- Tap Log in / Sign up button on app welcome screen, tap Help
- A support button is shown in various alerts shown throughout the app

**Comment by guarani** [comment]
I edited the above since we scoped this down.

**Comment by guarani** [comment]
Similar to https://github.com/wordpress-mobile/WordPress-Android/issues/17801, do you think this can be closed @ravishanker ?

**Comment by ravishanker** [comment]
Yes, since there's [another issue opened for link from enter site address](https://github.com/wordpress-mobile/WordPress-Android/issues/17937) and sparrow will handle RN implementation required on editor contact support option
