### ISSUE TITLE
Create feature flag for WP app support forum

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#17804]
Create config for WP mobile app support forum feature

**Comment by guarani** [comment]
👋 @ravishanker, can this be closed? The linked PR says it fixes this, but not sure why GitHub didn't auto-close this when the PR was merged.

**Comment by irfano** [comment]
> 👋 @ravishanker, can this be closed? The linked PR says it fixes this, but not sure why GitHub didn't auto-close this when the PR was merged.

Yes, this should be closed. Closing now.
