### ISSUE TITLE
Weekly Roundup: Add singular strings to notification

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#17824]
### Expected behavior
The singular form of the noun is used when the value is 1.
- view
- like
- comment

### Actual behavior
The plural form of the noun is used when the value is 1.
- views
- likes
- comments

Observed in issue WPiOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/19994

![image](https://user-images.githubusercontent.com/2092798/214689294-f9d7aa7c-2e3f-4e19-9f9a-2105074db320.png)

### Steps to reproduce the behavior
1. Trigger a Weekly Roundup notification for a site with 1 view, comment, and or like

### Notes
- [Location of strings](https://github.com/wordpress-mobile/WordPress-Android/blob/0e366ccb920be2ae1754523c7b3d73b83840a816/WordPress/src/main/res/values/strings.xml#L4062-L4065)

**Comment by twstokes** [comment]
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/19994

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
