### ISSUE TITLE
Tapping the `Learn more at Jetpack.com` Does Nothing.

### ISSUE THREAD

**Issue by JB184351** [wordpress-mobile/WordPress-Android#17859]
### Expected behavior
I expect that the `Learn more at Jetpack.com` button in the overlay to bring me to a web view of the Jetpack blog post.

### Actual behavior
The `Learn more at Jetpack.com` button currently doesn't do anything. I didn't see this issue on trunk but creating an issue so we can track it and make sure it works as expected.

### Steps to reproduce the behavior
1. Enable Phase 4 on WP Android 21.6-rc-2, you can do that by logging into the account provided for [here](https://jetpackmobile.wordpress.com/2023/01/18/new-test-users-for-the-feature-removal-testing-phases/).
2. Select the `Learn more at Jetpack.com` button
3. Notice that nothing happens.

##### Tested on [device], Android [version], WPAndroid [version]
Tested on a Samsung Galaxy A51 with Android 12 and 21.6-rc-2 version of WP

##### Video of issue
https://user-images.githubusercontent.com/36495451/215910414-dfcb0516-6dbf-4bb0-b0a9-1cacc2b0b93d.mp4

**Comment by AjeshRPai** [comment]
Hey @JB184351 

This issue has been fixed with the [commit](https://github.com/wordpress-mobile/WordPress-Android/commit/343e90912dd7d328b8146bb56b06e06bad391a07) targeting `21.7` milestone. Since this is not a high-priority issue. I am not merging this fix to the `21.6.`

cc: @zwarm
