### ISSUE TITLE
Suggest paid domains

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-Android#17900]
The list of domain suggestions should include both free and paid domains.
For the API integration details see internal ref: pc8HXX-ZF-p2.

#### Subtasks

- [x] #17976
- [x] #17985
- [x] #18015

### Design

<img width="250" src="https://user-images.githubusercontent.com/4588074/220165887-3df8822e-439e-4446-a945-933a070f0942.png">

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)

**Comment by antonis** [comment]
Closed with subtasks:
* https://github.com/wordpress-mobile/WordPress-Android/issues/17976
* https://github.com/wordpress-mobile/WordPress-Android/issues/17985
* https://github.com/wordpress-mobile/WordPress-Android/issues/18015
