### ISSUE TITLE
Test forum support changes

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#17988]
This issue serves as a place to track testing of the new forum for users of the .org forum. Please note the scope of this change only includes the WordPress app. There should be no meaningful changes to the Jetpack app except for minor changes like an updated copy, which isn't covered here.

⚠️ Please note that until the remote feature flag is switched on, the above changes won't be present. See https://github.com/wordpress-mobile/WordPress-Android/issues/17989 for details.

**Comment by guarani** [comment]
Testing on eed18ccc2b7b1682432c165736bd27ff6cc851ee on Samsung S10 and Android 12. I turned the forums feature flag on using the in-app debug settings.

## Self-hosted users on the WordPress app
- [x] Self-hosted users who request help locating their site address are given forum support
- [ ] Self-hosted users who are logged in to their site using their site credentials and request help are given forum support ⚠️ (still showing chat-like support, created https://github.com/wordpress-mobile/WordPress-Android/issues/17991)
- [x] Self-hosted users who are logged in to their site using WP.com credentials (via the Jetpack plugin) and request help are given ~~chat-like~~ **forum** support ⚠️ (will re-test this because the expected behavior wasn't properly described)

## WP.com users on the WordPress app

- [x] WP.com users who are logged out and request help logging in are given forum support (no matter what plan they might have)
- [x] WP.com users logged in to a WP.com site with a free plan who request help are given forum support
- [x] WP.com users logged in to a WP.com site with a paid plan who request help are given chat-like support

## Users on the Jetpack app

- [x] All users on the Jetpack app are given chat-like support

**Comment by irfano** [comment]
Thank you, for the test plan @guarani.
I tested all items. They all passed except #17991 and it's fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/17997.

**Comment by guarani** [comment]
Re-testing on 07423f93117eac76bc7323910e60bd485be5d93f (from https://github.com/wordpress-mobile/WordPress-Android/pull/17997) on Samsung S10 and Android 12. I turned the forums feature flag on using the in-app debug settings.

## Self-hosted users on the WordPress app
- [x] Self-hosted users who request help locating their site address are given forum support
- [x] Self-hosted users who are logged in to their site using their site credentials and request help are given forum support
- [x] Self-hosted users who are logged in to their site using WP.com credentials (via the Jetpack plugin) and request help are given forum support 

## WP.com users on the WordPress app

- [x] WP.com users who are logged out and request help logging in are given forum support (no matter what plan they might have)
- [x] WP.com users logged in to a WP.com site with a free plan who request help are given forum support
- [x] WP.com users logged in to a WP.com site with a paid plan who request help are given chat-like support

## Users on the Jetpack app

- [x] All users on the Jetpack app are given chat-like support

**Comment by guarani** [comment]
Not an issue but worth noting that when logged into a WP.com account that had two sites:
- WP.com with Free plan
- Pressable self-hosted site

The app provided chat-like support. I think this makes sense because Pressable users are comparable to paid plan users.

**Comment by guarani** [comment]
Marked this done since all the testing scenarios have been executed.
