### ISSUE TITLE
Create a remote feature flag for WP support forum

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#17989]
Create a remote feature flag "ENABLE_WORDPRESS_SUPPORT_FORUM" to launch the forum to self-hosted and WP.com users on free plans on WPAndroid.

**Comment by guarani** [comment]
@irfano, can this one be closed now? Feel free to add yourself as the assignee and update its status to get it tracked within the forum project.

**Comment by irfano** [comment]
The flag was created for Android and versions higher than `21.7`. Internal ref: D102315-code
