### ISSUE TITLE
Jetpack app FAQ card on the Jetpack app support view

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18025]
## Description

pc8eDl-Ic-p2

### User story

As a Jetpack app user who has questions about switching to the Jetpack app, I want to find information before reaching out to support

### Criteria

1. Show card only if **all** the following criteria are true
- Jetpack app
- Jetpack migration was perfomed
2. Show the card on top of `Support` view
3. Track `support_migration_faq_viewed` when card is shown
4. Track `support_migration_faq_tapped ` when tapping the CTA
4. CTA should open a link the external browser
5. UI:
- Top text: "Thank you for switching to the Jetpack app!"
- Bottom text: "Our FAQ provide answers to common questions you may have.”
- CTA Text: "View our FAQ"
- Link: https://jetpack.com/support/switch-to-the-jetpack-app/

## Design

An equivalent fitting current design of Android could be made

![Image](https://user-images.githubusercontent.com/4062343/221867147-80d4c0c7-5a61-4e82-b325-aa8be73532d3.png)

**Comment by guarani** [comment]
👋 @staskus, I'm not sure I understand the `Support Forum` label here. Should it be `Support` instead?

**Comment by staskus** [comment]
> 👋 @staskus, I'm not sure I understand the `Support Forum` label here. Should it be `Support` instead?

@guarani,I see @ravishanker added this label but I agree that it's not support-forum related. 👍

**Comment by guarani** [comment]
Sorry, I assumed it was you who added it and didn't look.
