### ISSUE TITLE
App language not working for Indonesian

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#18029]
This issue is only reproducible on JP and it seems like it started on version `20.6`.
It works as expected on the previous version of the Locale picker (tested versions `17.5`, `19.4` and `19.8.1`) but it was also working for some time after the new Locale picker was created (tested versions `20.2` and `20.5`).

### Expected behavior
When Indonesian is selected on "App Settings", the app strings should be translated to Indonesian.

### Actual behavior
When Indonesian is selected on "App Settings", some of the strings in the Locale picker are displayed in Indonesian, as expected, but most of the app strings are displayed in English.

### Steps to reproduce the behavior
1 - Install JP starting from version `20.6`;
2 - Tap the user picture to open "Me" screen;
3 - Tap on "App Settings";
4 - Tap on "Interface Language";
5 - Select Indonesian.

##### Tested on emulator, Android 12, JPAndroid `21.7`.

**Comment by ravishanker** [comment]
JP strings are translated by our translation vendor, [and only in our Mag16](https://github.com/wordpress-mobile/WordPress-Android/blob/49eb5a778c905828d5521a82b2efcd24fa02e6b1/WordPress/build.gradle#L203). While WP strings are translated by the community, and includes complete translations and in a lot more locales. 

Although Indonesian is part of Mag16 on JP, The [translations on JP](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/jetpack/res/values-id/strings.xml) are incomplete [unlike on WordPress](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/res/values-id/strings.xml).

 Just in time on this topic p1677697155676749/1677696545.622859-slack-CEJT26EG1

**Comment by erricgunawan** [comment]
Looks like a similar case in the Hebrew language.

Translation on [Jetpack app](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/jetpack/res/values-he/strings.xml) is not as complete as [WordPress app](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/res/values-he/strings.xml).

Report from 6188048-zen
