### ISSUE TITLE
Enable forum support to all WP app users

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#18042]
### Expected behavior

From 22.0 onwards, show the forum on the WP app for all users. Zendesk support should be removed completely from the WordPress app's interface.

From 21.8 onwards, it was only available to self-hosted users and WP.com users on the Free plan. This change enables it for WP.com users on paid plans as well.

<sub>internal ref p1677806819908639/1676313024.578649-slack-C04KJRDTLF7</sub>

**Comment by ravishanker** [comment]
At the moment, it is only contact us for paid users.  Is the suggestion to show both forum and contact us for paid users?

**Comment by guarani** [comment]
> At the moment, it is only contact us for paid users. Is the suggestion to show both forum and contact us for paid users?

We should just show the forum to all WP users. Thanks for the question! I'll update the issue above to clarify this.
