### ISSUE TITLE
[Blaze] Post/Page info on Blaze Intro overlay is missing the background.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#18051]
### Expected behavior
Post/Page info on Blaze Intro overlay should have a background color as specified in the designs.

### Actual behavior
Post/Page info on Blaze Intro overlay is missing the background.

| Current Overlay | Design |
| - | - |
| <img width="300" src="https://user-images.githubusercontent.com/42008628/222824118-e583123c-6045-4ee4-8998-1903f9345ec9.png"> | <img width="300" src="https://user-images.githubusercontent.com/42008628/222823936-a68b714e-0da6-4454-98b2-cb455462232d.png"> |

### Steps to reproduce the behavior
0. Make sure that Blaze is enabled via the debug menu
1. Selecta site that has Blaze enabled.
2. Post/Page > Post/Page Menu > Promote with Blaze

**Comment by zwarm** [comment]
@tiagomar - I believe this was addressed in PR #18056 and is correct in the beta. Please take a quick look and lmk, then we can close this issue. Thanks

 <img width="300" src="https://user-images.githubusercontent.com/506707/224325889-51ae9f52-35fe-4015-b7a5-6dc2da602140.png">

**Comment by tiagomar** [comment]
Hey @zwarm, I think I failed at describing the issue. 😅 
By "info" I meant the post summary background and not the bulleted text.

| **Current** | **Design** |
| - | - |
| <img width="291" alt="image" src="https://user-images.githubusercontent.com/42008628/224811656-ea4366e4-e790-427d-bda7-d961ddd3edb1.png"> | <img width="291" alt="image" src="https://user-images.githubusercontent.com/42008628/224811722-25b51d70-8247-4fa1-8d50-991e00550826.png"> |

Both the beta (21.9-rc-1) and #18056 builds look the same as in this ticket's description.

**Comment by zwarm** [comment]
@tiagomar - Are you talking about the text looking white instead of gray? Just want to be clear that I understand the actual issue.
Thanks.

**Comment by AjeshRPai** [comment]
Hey @zwarm and @tiagomar 

First of all, Sorry for the late reply, 

@tiagomar Correct me if I am wrong, but I believe you are talking about the background colour on the Post info box here. Assuming that, I have created a fix in the [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/18098).  

If you are talking about the colour or the font family of the text in Post info, the design you have provided here and on the Figma Design spec is for the IOS, so there is a difference between the Android and IOS designs. We have used the default colour and font family that we use across the project for the Post info elements(Title and URL)

**Comment by tiagomar** [comment]
Sorry @zwarm and @AjeshRPai for not making myself understandable (twice). 😅 

> @tiagomar Correct me if I am wrong, but I believe you are talking about the background colour on the Post info box here. Assuming that, I have created a fix in the https://github.com/wordpress-mobile/WordPress-Android/pull/18098.

Yeah, that's what I was trying to say. =]

**Comment by tiagomar** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/18098
