### ISSUE TITLE
Very first Stats card is not always loaded on screen

### ISSUE THREAD

**Issue by pachlava** [wordpress-mobile/WordPress-Android#18065]
### Expected behavior

All stats cards that can be shown on screen should be shown after opening the screen, no PTR should be required.

### Actual behavior

1. In some cases, for JP variant (I could not reproduce this on WP), the very first Stats card is loaded only after PTR:

https://user-images.githubusercontent.com/73365754/223773395-9ed971b6-c145-4a6b-a39a-2796d9c81332.mov

2. In other cases ([example](https://buildkite.com/automattic/wordpress-android/builds/10502#01876bb0-cb7e-4fa4-bd0d-d9d8fbbea206)) the stats screen does not load at all.

This causes our `e2eAllDayStatsLoad` UI test to fail for JP.

I could not reproduce this on a real device yet.

### Steps to reproduce the behavior

1. Launch JP
2. Log in and open `Stats`
3. Open `Days` tab ~> in some cases, the first card with bar chart is loaded only after PTR.

##### Tested on `Pixel 2 API 31 Emulator`, `JPAndroid 21.8-rc-2`

**Comment by irfano** [comment]
I could reproduce this using a real device by testing it on a high-traffic website.  You can reproduce the issue on by testing it on mobile.blog.
I removed the "[Emulator]" label from the title.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/ac9428e3-4a11-43da-952c-3ac6febc4c6b" width=320>
