### ISSUE TITLE
[Common] Compose PrimaryButton progress color is wrong

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18143]
### Expected behavior
The progress color in the `PrimaryButton` should be always White, no matter the theme.

### Actual behavior
For the light theme, the circular progress color is black.

### Steps to reproduce the behavior
Go to any flow that uses the progress state of the `PrimaryButton`, such as installing the Jetpack plugin for self-hosted sites without Jetpack when accessing a Jetpack feature (such as stats).

**Comment by oguzkocer** [comment]
@thomashorta Should this issue be closed? According to [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/18144#issuecomment-1488760015), it was released as part of `21.9.1` hotfix. If that's the case, it'd be good to update the milestone as well.

**Comment by thomashorta** [comment]
@oguzkocer definitely! I forgot to update this issue, sorry about that, and thanks for bringing it up!
