### ISSUE TITLE
Domains Dashboard Card: Card UI

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18178]
**Specification:** pc8eDl-LC-p2
**Project board:** [GitHub](https://github.com/orgs/wordpress-mobile/projects/154/views/19)

Create Domains Dashboard Card

## Requirements

1. The card should resemble the design requirements
3. The card should support accessibility and voice-over features
4. The card should have localized text

## Design

![image](https://user-images.githubusercontent.com/4062343/227914773-3813d0b5-e54d-4d3a-88b9-92e53f8a3d49.png)

**Comment by ravishanker** [comment]
@staskus - Do we need to [update it to this design](pc8eDl-LC-p2#comment-614)

**Comment by staskus** [comment]
@ravishanker 

Heh, I didn't expect the design to change. Do you have enough capacity to deliver it before the end of the iteration?
