### ISSUE TITLE
Domains Dashboard Card: Analytics

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18180]
**Specification:** pc8eDl-LC-p2
**Project board:** [GitHub](https://github.com/orgs/wordpress-mobile/projects/154/views/19)

Implement analytics for domains dashboard card

## Requirements

| Event                                            | Description                                                 | Properties      |
|--------------------------------------------------|-------------------------------------------------------------|-----------------|
| direct_domains_purchase_dashboard_card_shown     | Tracked when a site meets the criteria and the app shows the dashboard card.   | position_index  |
| direct_domains_purchase_dashboard_card_tapped    | Tracked when a user taps a dashboard card.                  | position_index  |
| direct_domains_purchase_dashboard_card_hidden    | Tracked when a user taps a CTA to hide a dashboard card.    | position_index  |

`position_index`  describes the current placement of the card in the dashboard
- number, from 0 to the total number of dashboard cards

**Comment by ravishanker** [comment]
@staskus - Do we need to rename these events to dashboard_card_domain_[shown, tapped, hidden] style?

**Comment by ravishanker** [comment]
Also, Do we need to track More menu tapped?

**Comment by staskus** [comment]
@ravishanker 

>  Do we need to rename these events to dashboard_card_domain_[shown, tapped, hidden] style?

Well, there's no strict "need" for that. If you think it's better to do that, we can rename it. My original idea was to distinguish between different types of domain cards. However, maybe it could be done in another way. What do you think?

> Also, Do we need to track More menu tapped?

I'd say no. I haven't identified a use-case for that.

**Comment by ravishanker** [comment]
> maybe it could be done in another way

I can leave the actual tracking string as you specified above for now.

> I'd say no. I haven't identified a use-case for that.

All other cards have tracking on the more menu item.  So, I have added it.

**Comment by staskus** [comment]
> > maybe it could be done in another way
> 
> I can leave the actual tracking string as you specified above for now.
> 
> > I'd say no. I haven't identified a use-case for that.
> 
> All other cards have tracking on the more menu item. So, I have added it.

@ravishanker, okay, it works!

**Comment by ravishanker** [comment]
@staskus What is the position_index useful for?  How's that used in the analytics?

**Comment by staskus** [comment]
> @staskus What is the position_index useful for? How's that used in the analytics?

@ravishanker This is based on the initial discussions pc8eDl-LC-p2#comment-606. I want to understand the performance of this card based on its positioning.
