### ISSUE TITLE
Webview crashes on page with tons of unicode characters

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#182]
The article here http://wp.me/p18Fb6-15t crashes the webview.
I tried to preview a new theme on the site, but the theme preview screen uses a webview internally, and the app crashed.
Same crash when I used the "View Site" option, or the reader details screen.

**Comment by maxme** [comment]
I tried a copy of this article, preview is slow but it wasn't crashing. I don't think we can do any workaround, plus it's an edge case, so I'm closing this ticket.
