### ISSUE TITLE
Dashboard Cards: Implement the "Create a new page" section in the Pages card

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#18220]
- [x] Implement skeleton layout
- [x] Show skeleton in card
- [x] Update builder params
- [x] Update viewholder
- [x] Implement click events/handlers
- [x] Implement tracking events
- [x] Add/update unit tests

Note: Should this be broken up into individual GH issues. It has to go through the same steps as the card itself. Thoughts?

**Comment by AjeshRPai** [comment]
Hey @zwarm 

Just saw the comment. 

> Should this be broken up into individual GH issues? It has to go through the same steps as the card itself. Thoughts?

I don't think this needs to be broken up. 

> Implement context menu

The contextual menu you mean here is the "⠇" icon on the card, I suppose, which is a little bit confusing in this issue. The action on the contextual menu redirects to the `All pages` screen. So I am adding that task to #18216 


Also am removing the `Create new page` tasks from #18216, I think this issue captures all the tasks.
