### ISSUE TITLE
[My Site] Remove FAB tooltip

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18249]
On both iOS and Android - when you do a fresh install and log into the app, there's a tooltip pointing to the Floating Action Button saying 'Create a post, page, or story'. 

We have a lot more things going on now with various overlays and the dashboard. We should kill that tooltip, it's just adding noise.

Internal ref: p1680775438926479-slack-C0180B5PRJ4

Waiting for @osullivanchris to confirm if this tooltip should be removed only on both WP and JP apps and if it should be hidden only on the My Site screen or in the posts list as well.

**Comment by osullivanchris** [comment]
Yep, remove on both apps and also the posts list.

**Comment by oguzkocer** [comment]
@thomashorta :wave: I've been bumping #18249 & #18257 to the next milestone for the last few releases. This time I decided to remove the milestone to give you a chance to set it to the expected release. Sorry for the trouble!

**Comment by AjeshRPai** [comment]
Closed with the PR https://github.com/wordpress-mobile/WordPress-Android/pull/18606
