### ISSUE TITLE
[Blogging Prompts] Update prompts endpoint to v3

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18257]
Refs pctCYC-KA-p2

```[tasklist]
### Required
- [x] https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2710
- [x] Manually adjust the year of the prompt date from the v3 endpoint. ([backend is doing it](https://github.com/Automattic/jetpack/pull/30255))
- [x] Ensure that v3 prompts overwrite v2 prompts with the same date.
- [x] When answering a prompt, leave the draft title empty.
```

```[tasklist]
### Optional
- [x] Use `answered_link` to determine which page to open when ‘View all responses’ is tapped.
```

**Comment by oguzkocer** [comment]
@thomashorta :wave: I've been bumping #18249 & #18257 to the next milestone for the last few releases. This time I decided to remove the milestone to give you a chance to set it to the expected release. Sorry for the trouble!

**Comment by thomashorta** [comment]
> @thomashorta 👋 I've been bumping #18249 & #18257 to the next milestone for the last few releases. This time I decided to remove the milestone to give you a chance to set it to the expected release. Sorry for the trouble!

Thank you @oguzkocer, I hadn't realized we kept the old milestones for the GH issue, my bad! 🤦

**Comment by oguzkocer** [comment]
@thomashorta No worries at all. I didn't want to remove them without giving you a heads up, that's all 🤗
