### ISSUE TITLE
Scheduled post not publishing

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#18266]
### Expected behavior

A scheduled post should publish at the designated time.

### Actual behavior

A user reports that their scheduled post does not publish after the designated time passed.

### Steps to reproduce the behavior

Haven't tried to reproduced yet. Created the issue based on a Google Play review:

> Doesn't post scheduled posts ... It did at the start of me first using it, but now it's stopped altogether!

**Comment by guarani** [comment]
I gave this Medium priority due to High severity (affects editing experience) and Low impact (only one report, shared below).

> Doesn't post scheduled posts ... It did at the start of me first using it, but now it's stopped altogether!

Google Play Store review

**Comment by guarani** [comment]
@twstokes, I created this issue from a Play Store review and could reproduce although it could be related to an existing issue I've seen for years (see info I added to the issue description).

I'm not sure whether this issue warrants attention now or if I should leave it here to be picked up later. Do you know how to proceed? E.g. this could be added to the maintenance board (cc @tiagomar) but not sure what's the best practice.

**Comment by guarani** [comment]
Update: I mistook this for an iOS issue and tested there. I've now transferred this issue to the Android repo (had created it in the iOS repo).

I'll need to come back to this issue and test with an Android device.

**Comment by twstokes** [comment]
👋 Hey @guarani -

> Do you know how to proceed? E.g. this could be added to the maintenance board (cc @tiagomar) but not sure what's the best practice.

Good question - that'd be my best guess. That's the only area I'm aware of where we're triaging and working on non-critical issues. (Critical issues like crashes have been bypassing triage and are dealt with immediately)

> A user reports that their scheduled post does not publish after the designated time passed.

Regarding the technical issue here, I'd check to see if the client is fulfilling its responsibility of properly scheduling the post on the backend. Then, as noted before, it's most likely at the mercy of [WP-Cron](https://developer.wordpress.org/plugins/cron/) and how much activity the site sees.

**Comment by tiagomar** [comment]
> I'm not sure whether this issue warrants attention now or if I should leave it here to be picked up later. Do you know how to proceed? E.g. this could be added to the maintenance board (cc @tiagomar) but not sure what's the best practice.

First of all we need to understand what's really happening. Adding it to the maintenance board as is doesn't look productive to me.

> Regarding the technical issue here, I'd check to see if the client is fulfilling its responsibility of properly scheduling the post on the backend. Then, as noted before, it's most likely at the mercy of [WP-Cron](https://developer.wordpress.org/plugins/cron/) and how much activity the site sees.

Totally agree. I could also fin this issue, https://github.com/wordpress-mobile/WordPress-Android/issues/14732, that could explain the `but now it's stopped altogether!` part.

**Comment by guarani** [comment]
> Totally agree. I could also fin this issue, #14732, that could explain the `but now it's stopped altogether!` part.

Great find, @tiagomar! The fact that this is an Android issue you found could suggest it's not the client at fault, but the backend (although this isn't conclusive).

> First of all we need to understand what's really happening. Adding it to the maintenance board as is doesn't look productive to me.

What's factors should be considered when deciding whether to add to the maintenance board vs. investigating now?

**Comment by tiagomar** [comment]
> What's factors should be considered when deciding whether to add to the maintenance board vs. investigating now?

This is actually a bit subjective, but we're looking for high impact/high frequency issues. For this specific issue, while it can be quite frustrating not to have a post being publish when expected, we don't have evidence that it's frequent based on the fact that there weren't similar issues open or comments added, even with the WP-Cron possibly adding on top. However, if #14732 really turns out to be a good lead, adding it would make sense.

**Comment by guarani** [comment]
Gotcha, thanks for explaining, @tiagomar!

**Comment by twstokes** [comment]
Ref: p1682012547857229-slack-C025Q5RK2 that may be worth tracking.

**Comment by antonis** [comment]
Searching on how the scheduled posts work I found the [following notice on the documentation](https://wordpress.com/support/schedule-a-post-or-page/):

> Scheduled posts will be triggered by the first visit to your blog on or after the exact date/time you set. If you see that the scheduled time has come and gone and your post or page has not published, log out of WordPress.com and view your blog’s front page. Your visit should cause the post or page to appear.

I believe that this indicates the the client app works as expected. A fix would require a change on how the server works and I'm closing this issue.

**Comment by guarani** [comment]
> I believe that this indicates the the client app works as expected. A fix would require a change on how the server works and I'm closing this issue.

Thanks for finding this. Closing the issue sounds good since it's a known and documented issue.
