### ISSUE TITLE
[Site Creation Domain Purchases] Dark mode landscape background is not consistent

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#18269]
### Expected behavior
The backround color is consistent in landscape/dark mode

### Actual behavior

The background color does not cover the full width of the screen in landscape/dark mode

![Screenshot_20230413_165446](https://user-images.githubusercontent.com/304044/231783332-68cdec29-8b9b-4048-9499-15b070e85b95.png)

### Steps to reproduce the behavior
<details><summary>◐ Toggle the <code>SiteCreationDomainPurchasingFeatureConfig</code> flag</summary>

1. Go to `Me` → `App Settings` → `Debug settings`
3. Scroll to the `Features in development` section
4. Tap on the item corresponding to the flag
5. Tap `RESTART THE APP` button
</details>

1. Set the device in dark mode
2. Start the site creation flow
3. Select a design
4. Search for a domain
5. Turn the device in landscape mode
6. **Notice** that the background color is not consistent

_Note: that the issue is not reproduced with the SiteCreationDomainPurchasingFeatureConfig off_

**Comment by mkevins** [comment]
I have been investigating solutions to this, and just wanted to note here that the structure is similar in landscape in the control variation, but the background color is what is different in the `recyclerView`:

<img width="957" alt="Screen Shot 2023-04-25 at 10 20 16 AM" src="https://user-images.githubusercontent.com/8507675/234196294-d4d8a30f-b7a6-4f33-9245-b2e49f96a50d.png">

**Comment by mkevins** [comment]
We decided to make the background of the items in dark mode match the existing background (dark gray), which is simpler and more consistent with the rest of the flow. Implemented with #18320.
