### ISSUE TITLE
Stuck upload/undismissable notification

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1827]
A user had their post upload get stuck and they couldn't remove the notification:
![screenshot_2014-09-05-09-15-16](https://cloud.githubusercontent.com/assets/789137/4166862/b1a78ce6-350e-11e4-96f1-3ed85200e0b2.png)

**Comment by maxme** [comment]
Reopening this, 3.8 priority. Since we fixed #2282, the workaround used doesn't work (swipe the "failed" notification and try to upload again). 

We must find the root issue that causes the notification and the post to get stuck in an "uploading" state.

**Comment by maxme** [comment]
* PostUploadService must be a foreground service
* PostUploadService.onDestroy should reset the Post status from uploading to local draft 
* use PostUploadService.onStartCommand instead PostUploadService.onStart

**Comment by maxme** [comment]
* Notification must be created as soon as the onStartCommand is called
