### ISSUE TITLE
Domains Dashboard Card: Card UI v2

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18280]
**Specification:** pc8eDl-LC-p2

Create Domains Dashboard Card

## Requirements

1. The card should resemble the design requirements
2. The card should support light and dark mode
3. The card should support accessibility and voice-over features
4. The card should show "domain. Blog" static text (Use [Domains Dashboard Card UI v2.1 SVG.zip](https://github.com/wordpress-mobile/WordPress-Android/files/11269440/Domains.Dashboard.Card.UI.v2.1.SVG.zip))

## Design

<img width="343" alt="(Card) Domain Upsell – iOS Light" src="https://user-images.githubusercontent.com/4062343/232471334-0c604404-e7bf-40ec-9211-548b0fbcc8ad.png">
<img width="343" alt="(Card) Domain Upsell – iOS Dark" src="https://user-images.githubusercontent.com/4062343/232471338-f06922d6-43e3-4e4d-81ff-ccd30e081695.png">

**Comment by ravishanker** [comment]
@staskus - I'm not able to export from Figma.  It says, export is disabled.  If you are able to export, please export the image in light and dark in Vector format for android and attach it here.  Otherwise ask Paul to do it.  Thanks

**Comment by staskus** [comment]
@ravishanker 

These are SVG icons with all the possible asset combinations. I wasn't sure how to implement it better. 

[Domains Dashboard Card UI v2 SVG.zip](https://github.com/wordpress-mobile/WordPress-Android/files/11258679/Domains.Dashboard.Card.UI.v2.SVG.zip)

**Comment by staskus** [comment]
@ravishanker updated assets with a static text

[Domains Dashboard Card UI v2.1 SVG.zip](https://github.com/wordpress-mobile/WordPress-Android/files/11269440/Domains.Dashboard.Card.UI.v2.1.SVG.zip)
