### ISSUE TITLE
Domains Dashboard Card: Hide for P2 (WP for teams) 

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18293]
**Project Specs**: pc8eDl-LC-p2

### Description

Add additional criteria to Domains Dashboard Card Presentation: hide the card for P2 (WP for teams) sites

The site is identified by `is_wpforteams_site` `Blog` option.

**Comment by ravishanker** [comment]
@staskus Should this be disabled for all P2s or just the a8c P2s?

If only for a8c P2s then, it can be done using condition like `site.organizationId != Organization.A8C.orgId`

**Comment by staskus** [comment]
> @staskus Should this be disabled for all P2s or just the a8c P2s?
> 
> If only for a8c P2s then, it can be done using condition like `site.organizationId != Organization.A8C.orgId`

@ravishanker, thanks for sharing this additional approach, I didn't know about it! I think we can disable all P2s (`is_wpforteams_site`), the same as it's on the web for domain upsells.
