### ISSUE TITLE
Recorded Story video is stuck in processing in some cases

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#18316]
### Expected behavior
The recorded story video is processed 

### Actual behavior
The recorded story video is stuck in processing mode

https://user-images.githubusercontent.com/304044/234010260-81c1e868-f9da-471a-bc69-c7be704ec22c.mp4

### Steps to reproduce the behavior
1. Tap on the plus(+) fab and select `Story post`
2. Tap on the camera fab
3. Give the necessary permissions when asked
4. Hold the record button to record a video (even a second would be enough)
5. *Notice* that the processing indicator is loading indefinitely 

Notes:
I was able to reproduce the issue consistently on my Pixel 5/Android 13 device but it seems that the issue is not reproduced on other devices (ref p1682343063093139/1682338666.089339-slack-C011BKNU1V5).

##### Tested on Pixel 5, Android 13, JPAndroid 22.1

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
