### ISSUE TITLE
Align UI in the Domains screen of Site Creation

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-Android#18314]
Originally this task was a comment: https://github.com/wordpress-mobile/WordPress-Android/pull/18302#pullrequestreview-1395429729

> @antonis: I have a design nitpick that I don't consider blocking but I'd like design input on this. I think we the title-subtitle-search icon should be vertically aligned. Wdyt @paulforgione?

<img width="315" src="https://user-images.githubusercontent.com/304044/233599073-a4dae563-93dd-45ed-8c4f-ba94ad9b2562.png">

**Comment by paulforgione** [comment]
I think aligning the search icon makes sense.

I would also push the "search with keywords" placeholder copy to the right edge of that icon, and align the "Search for a short and memorable domain" copy to the left edge of the page's title as well:

<img width="360" alt="Initial" src="https://user-images.githubusercontent.com/4359124/234672932-516b5846-58ba-4c9b-97a5-ad554d846274.png">
