### ISSUE TITLE
Stats: `stats_insights_accessed` event is tracked even when the period segment is selected

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18343]
### Expected behavior

When opening Stats, if the period segment (Days/Weeks/Months) is selected, then `stats_period_accessed` event should be tracked.

### Actual behavior

`stats_insights_accessed` is tracked instead

### Steps to reproduce the behavior

1. Open Jetpack
2. Open Stats
3. Select "Days" segment
4. Come back to home
5. Select Stats again
6. "Days" segment is selected by default
7. Notice 2 events are tracked: `stats_accessed`, `stats_insights_accessed`

##### Tested on [device], Android [version], JPAndroid 22.3

https://user-images.githubusercontent.com/4062343/235462721-81fdba78-4a92-45b3-95ac-31c1e532d3cd.mov

**Comment by irfano** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/20194
