### ISSUE TITLE
Add tracks events

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-Android#18413]
This task is to add tracks data to the account closure flow. We should track success and failure, with the error type in case of failure ([similar to iOS](https://github.com/wordpress-mobile/WordPress-iOS/blob/97f66d819fa2ffb987afdd7876a012c2bd4e9fa8/WordPress/Classes/ViewRelated/Me/Account%20Settings/AccountSettingsViewController.swift#L298)).

**Comment by ovitrif** [comment]
Resolved in:
- #18444
