### ISSUE TITLE
[Blogging Prompts] View responses CTA doesn't look tappable

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#18447]
ref: pcdRpT-2eV-p2#comment-4631

### Expected behavior
`View all responses` should look tappable (use a "link" color and have some tap effect/ripple).

![image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/08c02c77-d78b-4e26-9883-243d02b787c3)

### Actual behavior
It just looks like a non-tappable text.

![image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/0fdf0cd6-a3ef-426d-905b-6b3ed74939e5)

### Steps to reproduce the behavior
1. Open the Jetpack app
2. Select a blog (more than 1 post)
3. Go to the Dashboard
4. Check the Prompts card

**Comment by hypest** [comment]
Fixed by the PR above, closing.
