### ISSUE TITLE
Blaze: Manage Campaigns - Implement the Remote Config for Webview URL's

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#18535]
## Description 
Implement the remote config url's for the webview 

## Links 
Design ref - 1Osrn9gb2xLaKG6lIft3WC-fi-1461_9777

```[tasklist]
### Todo
- [  ] Implement the remote config urls
- [  ] Set the default values 
```

**Comment by zwarm** [comment]
@AjeshRPai  - I believe we decided not to use remote config for the URL values, so I think we can close this issue. Doubling checking with you to be sure.

**Comment by AjeshRPai** [comment]
Hey @zwarm 

Sorry missed this ping. Yes, you are correct. We decided not to use remote config URL values 👍 . Closing this issue
