### ISSUE TITLE
Crash when selecting certain domains

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#18538]
### Expected behavior

After choosing a domain, the app should advance to the checkout screen to allow the user to complete the purchase.

### Actual behavior

The app crashes if I choose certain domains (e.g. hometitle.org that appears by default on the "Search domains" screen).

### Steps to reproduce the behavior
1. Tap the **Find a custom domain** dashboard card
2. Tap the first domain suggestion (should be hometitle.org)
3. Tap **Select domain**
4. Notice the app crashes

### Additional info

WP.com says "Sorry, the domain you are trying to add can not be bought on WordPress.com at this time." when trying to buy this domain. While WP.com doesn't suggest this domain by default like mobile does, users could come across this domain (or other unavailable domains), so we could handle this case gracefully on mobile by showing the same message.

<img width="1364" alt="Screenshot 2023-05-26 at 17 04 23" src="https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/8f2448c9-8051-44f7-9b56-487fd0029707">

Related iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/20748

**Comment by ravishanker** [comment]
It is not crashing when I tried it.  Wondering if this is related to this https://github.com/wordpress-mobile/WordPress-Android/pull/18517

Please try with a later version, and if the problem persists, we can investigate further!  

>**Note**
"Sorry, the domain you are trying to add can not be bought on WordPress.com at this time." message does appear when going from Plans card on dashboard, since we launch a WebView after domain selection, and it appear on Plans page if an unavailable domain is selected.

**Comment by guarani** [comment]
Hey @ravishanker, thanks for looking into this!

It's not crashing now either (not sure what's changed), but now users see a "You have no items in your card" message:
https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/bdd83e2b-8093-44ca-a4e4-2244003a3eae

> "Sorry, the domain you are trying to add can not be bought on WordPress.com at this time." message does appear when going from Plans card on dashboard, since we launch a WebView after domain selection, and it appear on Plans page if an unavailable domain is selected.

Good to know the new domain dashboard card handles this well 👍

**Comment by notandyvee** [comment]
Closing as the original crash seems to be fixed.
