### ISSUE TITLE
Android - Track user actions

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#18569]
Implement the following new analytic events.

Event | Trigger
---- | ----
`privacy_choices_banner_presented` | When the banner is presented
`privacy_choices_banner_settings_button_tapped` | When the settings button is tapped
`privacy_choices_banner_save_button_tapped` | When the save button is tapped

**Comment by ovitrif** [comment]
Addressed in the PR I linked above:
- #18696
