### ISSUE TITLE
x button on Jetpack overlay is not working in horizontal orientation

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#18584]
### Expected behavior
x button should dismiss the overlay in horizontal orientation.

### Actual behavior
x button does nothing.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/cca56b73-6408-4ac0-bd8f-1868c12ab354" width=600>

### Steps to reproduce the behavior
1. Launch the WP app in the horizontal orientation.
2. Sign up.
3. Tap Add a new site button → Create WordPress.com site.
4. When the Jetpack overlay opens, tap x button.
5. Notice it doesn't dismiss the overlay.

**Comment by SamantaTarun** [comment]
I'd like to look into this.

**Comment by bibekbhujel47** [comment]
I would like to work on this issue @irfano. Can you assign me.?

**Comment by irfano** [comment]
Hello @SigmaZardan! Thank you for addressing this issue, but it has already been resolved in [another PR](https://github.com/wordpress-mobile/WordPress-Android/pull/18597). I'm sorry for that and hope we can have your contribution on another issue.

**Comment by AjeshRPai** [comment]
Hey @SigmaZardan 
I am really sorry. I wasn't aware this issue was reported when I fixed it in another PR. So sorry for that. As @irfano said, I hope you will find another issue that you can contribute to.

**Comment by bibekbhujel47** [comment]
@AjeshRPai , @irfano It's okay guys, I will find another issues to work on. I am new to open source contributions and will clarify on the issues before working on it.
