### ISSUE TITLE
Plans on JP: Card does not adapt to Display size accessibility setting

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18590]
### Expected behavior

Search bar on the free to paid plans card should always fit no matter the Display size accessibility setting

### Actual behavior

Search bar on the free to paid plans card cuts off when the Display size accessibility setting is increased

### Steps to reproduce the behavior

1. Enable Free to Paid Plans feature flag
2. Log into a free .com account
3. Notice a Free to Paid Plans plans card appearing
4. Go to Settings -> Accessibility -> Display size and text
5. Increase Display Size and come back into the app
6. Notice the search bar on the card not fitting

##### Tested on Pixel 4, Android 13, JPAndroid / WPAndroid 22.6

| Image 1 | Image 2 |
| ------- | ------- |
| ![Screenshot_1686222936](https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/85f842db-3643-418b-8365-c5ab0b0d2eed) | ![Screenshot_1686222864](https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/440f6b93-f106-44d5-aaac-b2fc9b0f060b) |

**Comment by guarani** [comment]
👋 What's the difference between the `WP.com Plans` and the `Plans on JP Mobile` labels?

**Comment by staskus** [comment]
> 👋 What's the difference between the WP.com Plans and the Plans on JP Mobile labels?

I left only `WP.com Plans` as with the other tickets
