### ISSUE TITLE
Domain Dashboard Card: Remove related code

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#18725]
With the inclusion of Plans related card, Domain Dashboard Card is no longer needed:

- [ ] Remove dashboard card UI code
- [ ] Remove the feature flag
- [ ] Remove presentation criteria

**Comment by AjeshRPai** [comment]
Hey @staskus 

reminder: please make sure to remove the remote flags/local flags related to this as well.
