### ISSUE TITLE
"Scan Login Code" doesn't work

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#18785]
### Expected behavior
The "Scan Login Code" button should open the camera.

### Actual behavior
Tapping the "Scan Login Code" button does nothing.

https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/e272ee1c-64ec-4bfd-83c1-3a263ccbac9f

### Steps to reproduce the behavior
1. Log in to the app with an account 2FA disabled.
2. Navigate to Me.
3. Tap the "Scan Login Code" button.
4. Notice it doesn't open the camera screen.

**Comment by zwarm** [comment]
Unable to reproduce on Google Pixel 5X, JPAndroid 22.9-rc-1 (1359) or Samsung Gallery S20, Android 12, 22.9..rc-1
@irfano - Any chance you captured the logs?

**Comment by irfano** [comment]
> Unable to reproduce on Google Pixel 5X, JPAndroid 22.9-rc-1 (1359) or Samsung Gallery S20, Android 12, 22.9..rc-1
> @irfano - Any chance you captured the logs?

I tested both on a real device and an emulator, it's not opening. This is the failure message from `GmsBarcodeScanning`:
```
com.google.mlkit.common.MlKitException: Waiting for the Barcode UI module to be downloaded.
```

**Comment by zwarm** [comment]
Super helpful, it's Google related of course and doesn't happen consistently. ~There is a ticket to swap out scanning libraries. I'll combine this with that, as that is a larger effort.~ Keeping this ticket, but updating the labels.

Thanks! 

Other hints
- not enough storage on the device
- data connection is not there on the device. 
- Clear out the data of the Google Play Services and retry


To fix: Migrate to [Google MLKit library](https://href.li/?https://developers.google.com/ml-kit/vision/barcode-scanning/android)(bundled version). This library doesn't depend on the Google Play Services
