### ISSUE TITLE
Inserting big images can break the width of certain themes

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1879]
From one of our user:

> When using the web-based interface, if an image is inserted too large for a theme's width, the largest version possible for the theme is displayed. Something about how the image is inserted using the app makes this value absolute for the image and breaks the width of a few templates I have tested with on .org (twenty-fourteen and interface at least).﻿

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
