### ISSUE TITLE
Reader: VideoPress video can't be played when tapping on them

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-Android#18836]
### Expected behavior
VideoPress videos in the Reader should be played when tapping on them.

### Actual behavior
When opening a post in the Reader that contains a ViedoPress video, tapping on the video displays a fullscreen modal with the message "Unable to preview image". The video can still be played but only when tapping in the play icon button.

### Steps to reproduce the behavior
1. Open a post that contains a VideoPress video in the Reader.
2. Tap on the video. NOTE: Avoid tapping on the play button as it will play it.
3. Observe that a fullscreen modal is shown with the message "Unable to preview image".

https://github.com/wordpress-mobile/WordPress-Android/assets/14905380/2a6a6b6a-59e4-4df8-9462-adae4b2563a9

**Comment by tiagomar** [comment]
On 23.5-rc-1, I didn’t notice the "Unable to preview image" message, but a single frame of the video.


https://github.com/wordpress-mobile/WordPress-Android/assets/42008628/9c07c396-a0c0-4afc-96e1-cb7590e76707
