### ISSUE TITLE
Convert WPLaunchActivity to Kotlin

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#18867]
[WPLaunchActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/WPLaunchActivity.java) should be converted to Kotlin.

This screenshot is from after the conversion. lateinit var, `WordPress.wpDB` should be checked for null properly.
<img width="585" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/f478801e-ba42-4435-bb48-bf76b9ebcd6f">

Follow the guide: [Converting to Kotlin](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/docs/converting-to-kotlin.md)

**Comment by dmdbilal** [comment]
If this issue is still open, Can I work on this issue ?

**Comment by irfano** [comment]
This issue was resolved with #18888, but we forgot to close it. I am closing it now. Thank you for your interest, @dmdbilal, and if you would like, you can choose another issue from [good first issues](https://github.com/wordpress-mobile/WordPress-Android/labels/good%20first%20issue).
