### ISSUE TITLE
Unused section titles on Site Settings screen

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#18899]
### Expected behavior
When the section is empty, the section title shouldn't be visible.

### Actual behavior
When the section is empty, the section title is visible.

<img width="381" alt="Screenshot 2023-08-05 at 14 25 02" src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/08821a8b-9fae-439d-a494-d399bbae709d">

### Steps to reproduce the behavior
1. Launch the app.
2. Add a self-hosted site.
3. Navigate to "My Site → Site Settings".
4. Notice there are empty sections with visible titles.

##### Tested on Pixel 7 Pro Emulator, Android 13, JPAndroid 22.9-rc-1

**Comment by mziegler611** [comment]
@irfano I'd like to tackle this one! Can you assign it to me? Thanks.

**Comment by irfano** [comment]
> @irfano I'd like to tackle this one! Can you assign it to me? Thanks.

Yes, sure! Thank you for addressing this issue.

**Comment by mziegler611** [comment]
@irfano This is my first commit to the code base, how do I create my PR? I've coded my solution but I do not have permission to push my branch. (Permission to wordpress-mobile/WordPress-Android.git denied to mziegler611.) 
I have gone through this document https://make.wordpress.org/mobile/handbook/ but don't see anything that fits this situation. Do I need to create a fork of the repository and push my changes there? 
Thanks ! :)

**Comment by irfano** [comment]
Hey @mziegler611! Thanks for working on the issue. You can access all the necessary information for contributing on our [How to Contribute](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/CONTRIBUTING.md) page.
