### ISSUE TITLE
Improve Media/Themes Grid Layout

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1896]
The media/themes lists would look better if we:

 * Cropped the images to square in media
 * Removed the grey border from around a grid item
 * Have the theme screenshot extend beneath theme title so that the alpha shows

**Comment by kwonye** [comment]
Not exactly the same, but this will be addressed in the newest Themes version that matches the web.

**Comment by roundhill** [comment]
> Not exactly the same, but this will be addressed in the newest Themes version that matches the web.

:boom:

**Comment by tonyr59h** [comment]
Addressed in #3375
