### ISSUE TITLE
Quick Vid: Error uploading. Invalid File Type

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#190]
Not sure if this is a server issue or app issue. 
When publishing a quick video the following error appears. 
"Error: An error occurred while uploading media: Could not write file wpid-VID_20131023_181817.3gp (Invalid file type)"

Should the file type be .3gp? 

2.5 beta 4(?) / Nexus 7

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
