### ISSUE TITLE
🤖 Implement Status Logic

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-Android#19073]
We will fetch this data from the Backend. The endpoint is TBD.

- Complete Setup
- Failed
- In Progress
- Action Required
- Expired
- Renewing
- Verify Email
- Expiring Soon
- Error
- Verifying
- Active

**Comment by mkevins** [comment]
I have removed "must have", since this is now handled by the back-end.

**Comment by antonis** [comment]
Closing as deprecated (ref p1697201542661029/1697134971.291349-slack-C05NS0YV7HS)
