### ISSUE TITLE
🤖 Domain Details Screen as WebView

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-Android#19071]
A webview that displays the domain details.

## Screenshot Reference

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/15968946/240a095c-049c-411e-aae9-a984b166cd3b)

**Comment by antonis** [comment]
Design reference: rvVgXupiyONUcJMgPSoMFj-fi-2565_27782

**Comment by antonis** [comment]
Reopening since I need to revisit the urls for the special cases and error pc8HXX-1gR-p2
