### ISSUE TITLE
🤖 Domains List Endpoint

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-Android#19165]
Here is a quick look at how the data will be fetched:

1. Call All Domains  endpoint and show a list of domains, without the status attribute.
2. Lazily evaluate the status attribute only if the user scrolls to the domain card ( aka the domain card is visible ).
   - All statuses at least require a call to Domain Details endpoint
   - Some statuses require an additional call to Purchases endpoint.

Ref pc8HXX-1gR-p2#comment-1165

**Comment by antonis** [comment]
Added a implementation details based on Ref pc8HXX-1gR-p2#comment-1165

**Comment by antonis** [comment]
> All statuses at least require a call to Domain Details endpoint

Noting that the `domains` endpoint [is already implemented](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/ba92dd07fbcc2987c91a8d8a37fd5952881d3286/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt#L840).

**Comment by antonis** [comment]
> 
> Some statuses require an additional call to Purchases endpoint.

There seems to be [an implementation for site purchases](https://github.com/wordpress-mobile/WordPress-Android/blob/168186020b43ccbea613ce0744cc393b3c850d86/libs/networking/src/main/java/org/wordpress/android/networking/RestClientUtils.java#L229) but not on the FluxC repo
