### ISSUE TITLE
Plans in Site Creation: Update Domain Selection

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#19264]
## Description

Update domain selection view created for Domain selection during the Site Creation project:
- Change ordering to follow the one on the web
- Show "free for the first year" labels next to the eligible domains

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/3bca69aa-aaf3-4a49-b6e3-280b3540db52)

**Comment by staskus** [comment]
@ravishanker 

### Web

These are 2 queries that are used on domain selection during site creation on the web. Paid domains are combined with one `.wordpress.com` domain:

**Query 1 - fetch 29 paid domains:**
```
{
    "query": "myquerydomain",
    "quantity": 29,
    "include_wordpressdotcom": false,
    "include_dotblogsubdomain": false,
    "tld_weight_overrides": null,
    "vendor": "variation4_front",
    "recommendation_context": "",
    "tlds": []
}
```

**Query 2 - fetch 1 .wordpress.com subdomain:**

```
{
    "query": "myquerydomain3",
    "quantity": 1,
    "include_wordpressdotcom": true,
    "include_dotblogsubdomain": false,
    "only_wordpressdotcom": false,
    "tld_weight_overrides": null,
    "vendor": "dot",
    "managed_subdomain_quantity": 0,
    "tlds": []
}
```

<img width="800" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/e3ab8e6d-7fc5-4bea-b4a4-0c63e2f63041">

Top 2 paid domains are put on top and free domain is displayed as a first non-recommended option.

## Mobile

**Domain purchasing in site creation uses this query:**

```
{
    "query": "myquerydomain3",
    "quantity": 20,
    "include_wordpressdotcom": true,
    "include_dotblogsubdomain": true,
    "tld_weight_overrides": null,
    "vendor": "mobile",
    "managed_subdomain_quantity": 0,
    "tlds": []
}
```

## Changes

On the app, I suggest:

1. Continue making one query with 20 items
2. Include .wordpress.com subdomains (`"include_wordpressdotcom": true`)
3. Exclude dot blog subdomains (`include_dotblogsubdomain: false)`
4. Add sorting:
- The first two paid domains returned from API
- The first one free domain returned from API
- The remaining items

Example request:

```
{
    "query": "myquerydomain3",
    "quantity": 20,
    "include_wordpressdotcom": true,
    "include_dotblogsubdomain": false,
    "tld_weight_overrides": null,
    "vendor": "mobile",
    "managed_subdomain_quantity": 0,
    "tlds": []
}
```

Example response:
```
(lldb) po domainSuggestions
▿ 20 elements
  ▿ 0 : DomainSuggestion
    - domainName : "myqueryd.wordpress.com"
  ▿ 1 : DomainSuggestion
    - domainName : "myqueryd.blog"
  ▿ 2 : DomainSuggestion
    - domainName : "myqueryd.com"
  ▿ 3 : DomainSuggestion
    - domainName : "myqueryd.org"
  ▿ 4 : DomainSuggestion
    - domainName : "myqueryd.life"
  ▿ 5 : DomainSuggestion
    - domainName : "myqueryd.best"
<...>
  ▿ 17 : DomainSuggestion
    - domainName : "my-query-d.style"
  ▿ 18 : DomainSuggestion
    - domainName : "my-query-d.cloud"
      - some : "USD"
  ▿ 19 : DomainSuggestion
    - domainName : "my-query-d.team"
```

Example results after sorting:
```
(lldb) po sortedDomainSuggestions
▿ 20 elements
  ▿ 0 : DomainSuggestion
    - domainName : "myqueryd.blog"
  ▿ 1 : DomainSuggestion
    - domainName : "myqueryd.com"
  ▿ 2 : DomainSuggestion
    - domainName : "myqueryd.wordpress.com"
  ▿ 3 : DomainSuggestion
    - domainName : "myqueryd.org"
  ▿ 4 : DomainSuggestion
    - domainName : "myqueryd.life"
  ▿ 5 : DomainSuggestion
    - domainName : "myqueryd.best"
  ▿ 17 : DomainSuggestion
    - domainName : "my-query-d.style"
  ▿ 18 : DomainSuggestion
    - domainName : "my-query-d.cloud"
  ▿ 19 : DomainSuggestion
    - domainName : "my-query-d.team"
```

This would be the result:
<img width="907" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/2944b0f4-961c-41a5-9d6a-dc7258b735bf">

Any thoughts or concerns about such an approach?

**Comment by guarani** [comment]
👋 Putting the top 2 suggestions at the top and matching WP.com seems like a good move.
