### ISSUE TITLE
The reader_accessed event is not triggered if users switch app and come back, if the reader was already the last selected screen

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#19278]
I noticed that in Android if the last selected screen is the reader and the user switch-to-another-app->return-to-jp-app, the reader_accessed event is not fired, whereas this happens in iOS; I'm not sure which one should be the correct behavior but creating this issue to track it. We should define which one is the intended behavior and align the two platforms, so to get compatible tracking numbers and not risk wrong assumptions based on them.

### Steps to reproduce the behavior
- Use logcat to check the tracking events
- Open the JP app and select the My Site screen, then the Reader screen
- Observe the reader_accessed event is triggered
- Switch to another app and come back to the JP app
- Observe the reader_accessed event is not triggered

**Comment by RenanLukas** [comment]
p1704816002263729-slack-C01CW1VMLAF
