### ISSUE TITLE
Monitor rollout of issue #19100

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-Android#19305]
Issue #19100 has the potential to introduce a `NullPointerException` regression. Though we anticipate the risk as low, this task is to monitor the release proactively, so that we can revert if necessary during the beta period. The earlier we discover any new crashes associated with these changes, the better chance we have of reverting in time to avoid degrading the user experience in production.

For the following tasks, we should note the release in which the changes land, along with any particular area of the app which might benefit from additional testing focus, and communicate that to the groups listed.

```[tasklist]
### Tasks
- [ ] Ping the release rotation team to make them aware of these changes in case a NPE is introduced
- [ ] Ping the beta testers to be be advised on the potential for a new crash with these changes
```

**Comment by ParaskP7** [comment]
FYI: The `23.5-rc-1` beta release for Jetpack has been already published and ready for [monitoring](https://a8c.sentry.io/releases/23.5-rc-1/?project=5731682). The WordPress such beta release is also ready to be published, but hasn't been published yet, thus not ready for [monitoring](https://a8c.sentry.io/releases/23.5-rc-1/?project=1438088) just yet.

- Jetpack: No issues related to NPE regression on `onNewIntent(...)` so far.
- WordPress: N/A

**Comment by ParaskP7** [comment]
FYI: Not sure what happened since yesterday, but now I see the opposite, the `23.5-rc-1` beta release for Jetpack being ready to be published, but hasn't been published yet, thus not ready for [monitoring](https://a8c.sentry.io/releases/23.5-rc-1/?project=5731682) just yet, although new issues are already flowing-in. While, the WordPress such beta release has been already published and ready for [monitoring](https://a8c.sentry.io/releases/23.5-rc-1/?project=1438088).

- Jetpack: N/A (although I already see issues flowing-in, but them not being related to NPE regression on `onNewIntent(...)`)
- WordPress: No issues so far.

PS: Most probably I mixed things up yesterday on which app is published and not... 🤷

**Comment by ParaskP7** [comment]
FYI: The `23.5-rc-1` beta release for both, the Jetpack and WordPress apps, has been now published and ready for monitoring ([Jetpack](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=5731682) + [WordPress](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=1438088)).

- Jetpack: No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress: No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

FYI: A new draft `23.5-rc.2` beta release is about to me published as well, but that's just in-progress and thus can be safely ignored from monitoring ([Jetpack](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682) + [WordPress](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)), at least for the time being.

**Comment by ParaskP7** [comment]
`23.5-rc-1` Monitoring:

- [Jetpack](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=5731682): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- [WordPress](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=1438088): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

FYI: The `23.5-rc.2` beta release for both, the Jetpack and WordPress apps, is ready to be published, but hasn't been published yet ([Jetpack](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682) + [WordPress](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)).

**Comment by ParaskP7** [comment]
FYI: The `23.5-rc-2` beta release for both, the Jetpack and WordPress apps, has been now published and ready for monitoring  ([Jetpack](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682) + [WordPress](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)).

`23.5-rc-1` + `23.5-rc-2` Monitoring:

- Jetpack ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=5731682) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=1438088) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

**Comment by ParaskP7** [comment]
`23.5-rc-1` + `23.5-rc-2` Monitoring:

- Jetpack ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=5731682) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=1438088) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

**Comment by ParaskP7** [comment]
`23.5-rc-1` + `23.5-rc-2` Monitoring:

- Jetpack ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=5731682) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=1438088) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

**Comment by ParaskP7** [comment]
`23.5-rc-1` + `23.5-rc-2` Monitoring:

- Jetpack ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=5731682) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=1438088) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

**Comment by ParaskP7** [comment]
`23.5-rc-1` + `23.5-rc-2` Monitoring:

- Jetpack ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=5731682) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5-rc-1](https://a8c.sentry.io/releases/23.5-rc-1/?issuesType=new&project=1438088) + [23.5-rc-2](https://a8c.sentry.io/releases/23.5-rc-2/?project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

FYI: The `23.5-rc-2` beta release, for both Jetpack and WordPress, has 1% adoption so far (at least on Sentry). As such, so far, the number of crashes are relative to that. Today, the `23.5` production release,  for both Jetpack and WordPress, is about to be published to 10% of our users. Thus, more crashes will be soon flowing in. This will make it more obvious if crashes related to this #19100 issue will start appearing on Sentry our dashboard. Having said that, so far so good, which is a good indication that we are not expecting too many, or any such crashes to happen. 🤞

**Comment by mkevins** [comment]
> This will make it more obvious if crashes related to this https://github.com/wordpress-mobile/WordPress-Android/pull/19100 issue will start appearing on Sentry our dashboard. Having said that, so far so good, which is a good indication that we are not expecting too many, or any such crashes to happen.

Thank you for tracking this Petros! I agree, so far this is looking like a harmless changeset 👍 .

**Comment by ParaskP7** [comment]
`23.5` + `23.5` Monitoring:

- Jetpack ([23.5](https://a8c.sentry.io/releases/23.5/?issuesType=new&project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5](https://a8c.sentry.io/releases/23.5/?issuesType=new&project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

FYI: As of now, the `23.5` production release, for both Jetpack and WordPress, has been staged rollout to 10% of the users, with Sentry adoption being 1%. I'll continue monitoring this up until the end of this week and then close this issue, that is, should everything continues as smooth.

**Comment by ParaskP7** [comment]
`23.5` + `23.5` Monitoring:

- Jetpack ([23.5](https://a8c.sentry.io/releases/23.5/?issuesType=new&project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5](https://a8c.sentry.io/releases/23.5/?issuesType=new&project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

FYI: The `23.5` production release, for both Jetpack and WordPress, has been fully rollout to all users, with Sentry adoption being about 10% so far.

**Comment by ParaskP7** [comment]
`23.5` + `23.5` Monitoring:

- Jetpack ([23.5](https://a8c.sentry.io/releases/23.5/?project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5](https://a8c.sentry.io/releases/23.5/?project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

FYI: The `23.5` production release, for both Jetpack and WordPress, has been fully rollout to all users, with Sentry adoption being about 30% so far.

PS: Because `All Issues` are now `99+`, which is a lot, I am only checking the most important ones, the first page on that, but twice, ordered by event and then users.

**Comment by ParaskP7** [comment]
`23.5` + `23.5` Monitoring:

- Jetpack ([23.5](https://a8c.sentry.io/releases/23.5/?project=5731682)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).
- WordPress ([23.5](https://a8c.sentry.io/releases/23.5/?project=1438088)): No issues related to NPE regression on `onNewIntent(...)` so far (new, unhandled, or all).

FYI: The `23.5` production release, for both Jetpack and WordPress, has been fully rollout to all users, with Sentry adoption being about 50% so far.

PS: Because `All Issues` are now `99+`, which is a lot, I am only checking the most important ones, the first page on that, but twice, ordered by event and then users.

**Comment by ParaskP7** [comment]
👋 @mkevins !

> Thank you for tracking this Petros! I agree, so far this is looking like a harmless changeset 👍 .

I think we can stop the monitoring and close this issue. Everything is LGTM, wdyt? 🙏

**Comment by mkevins** [comment]
I agree, thanks for keeping track of this as it rolled out. 👍  I think similar future changes can be scaled up a bit, since we did not encounter any issues here - though it may make sense to ping release wranglers to keep it in mind, instead of explicitly checking every issue like was done in this one, since this overlaps somewhat with the release rotation tasks (i.e. triaging, etc.). Wdyt?

**Comment by ParaskP7** [comment]
👋 @mkevins and thanks for closing this! 🥇 

> I think similar future changes can be scaled up a bit, since we did not encounter any issues here - though it may make sense to ping release wranglers to keep it in mind...

I agree! 💯 

>  instead of explicitly checking every issue like was done in this one, since this overlaps somewhat with the release rotation tasks (i.e. triaging, etc.).

True. 👍
