### ISSUE TITLE
2FA code: Add clarity that the code is for WordPress.com

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#19442]
Add clarity to the verification code view that the code is for WordPress.com:

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2092798/ff0e5949-b956-4e8d-8569-4ef82720530c" width="300px" />

Ref: pbArwn-6hG-p2

**Comment by twstokes** [comment]
iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/21875

**Comment by 07jasjeet** [comment]
@twstokes Can I work on this? If yes, I would really appreciate some more details.

**Comment by twstokes** [comment]
@07jasjeet sure! We need to improve the messaging here by revising the string:

`Please enter the verification code from your authenticator app.`

to something like:

`Please enter the verification code for WordPress.com from your authenticator app.`

Before getting started you should confirm you can access this prompt (since your local setup uses [this authentication method](https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication)).

[The string lives inside this repo](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/blob/4c60a619ede69fea0696aa3000aa73c49737ed40/WordPressLoginFlow/src/main/res/values/strings.xml#L23) which is loaded as a dependency of the app, so there are a few steps to getting it updated:

1. The PR with the string change would be in the [WordPress-Login-Flow-Android repo](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android)
2. We'd need a PR in this repo (WordPress-Android) that points to the branch / hash for the changes in WordPress-Login-Flow-Android for testing
3. A release for WordPress-Login-Flow-Android would need to be cut / tagged
4. We'd bump the version for that dependency in this repo

We'd need to check with an Android dev for steps three and four since I'm from the iOS side. If we get past steps 1 and 2 someone else may be able to drive steps 3 and 4. Thanks!

**Comment by twstokes** [comment]
👋 @antonis would you mind reviewing what I have the above to check for accuracy? Thanks!

**Comment by antonis** [comment]
The instructions you provided look accurate. Thank you @twstokes 🙇 

> 1. The PR with the string change would be in the [WordPress-Login-Flow-Android repo](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android)

@07jasjeet In order to test the PR you can create a `local-builds.gradle` file [by copying the example](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/local-builds.gradle-example) and uncommenting the `localLoginFlowPath` line.
If you test this step locally I'll be happy to help with the rest since integrating the library is sometimes tricky.

Thanks again for stepping forward to help with this 🙇

**Comment by 07jasjeet** [comment]
@antonis The whole flow is working but the string change isn't being reflected for some reason. The external library (where I have my changes) is showing up in Android studio as well confirming that it is being used when building the app.

**Comment by 07jasjeet** [comment]
@antonis When changing the same string in this repository [here](https://github.com/wordpress-mobile/WordPress-Android/blob/19346259f9439706575c335f9d78ae5e4d608f67/WordPress/src/main/res/values/strings.xml#L3000), the effect takes place with or without the local library. Seems like the current login flow isn't using the string in [WordPress-Login-Flow-Android repo](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android).

When the string I mentioned is removed, everything works as expected.

**Comment by antonis** [comment]
> When changing the same string in this repository [here](https://github.com/wordpress-mobile/WordPress-Android/blob/19346259f9439706575c335f9d78ae5e4d608f67/WordPress/src/main/res/values/strings.xml#L3000), the effect takes place with or without the local library. Seems like the current login flow isn't using the string in [WordPress-Login-Flow-Android repo](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android).

Good catch @07jasjeet 👍 It seems that [the strings are merged on the main project for translation](https://github.com/wordpress-mobile/WordPress-Android/commit/2d45fdbe#diff-6bbab92723bb83a1300e86d496d62b9475a6a1e8b5a5feca27721edfbb09943fR2816) and the latter overrides the string in the [WordPress-Login-Flow-Android repo](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android).

Despite the difficulty in testing my understanding is that the proper way to change the string is to commit the change on the library project. This will get to the main app and be translated in the next release (cc @AliSoftware for a confirmation 🙏 ).

**Comment by 07jasjeet** [comment]
@antonis changed the string on both the projects to be on the safer side for now.

**Comment by AliSoftware** [comment]
> Good catch @07jasjeet 👍 It seems that [the strings are merged on the main project for translation](https://github.com/wordpress-mobile/WordPress-Android/commit/2d45fdbe#diff-6bbab92723bb83a1300e86d496d62b9475a6a1e8b5a5feca27721edfbb09943fR2816) and the latter overrides the string in the [WordPress-Login-Flow-Android repo](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android).
>
> Despite the difficulty in testing my understanding is that the proper way to change the string is to commit the change on the library project. This will get to the main app and be translated in the next release (cc @AliSoftware for a confirmation 🙏 ).

Correct.

**Comment by antonis** [comment]
> changed the string on both the projects to be on the safer side for now.

Thank you @07jasjeet 🙇 
Feel free to add me as a reviewer when you create the PR.

**Comment by 07jasjeet** [comment]
@antonis both the PRs are up and I can't add reviewers to a PR due to access issues afaik. 
[PR on this repo](https://github.com/wordpress-mobile/WordPress-Android/pull/19459)
[PR on Wordpress-Login](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/125)

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/125

Thank you for your work @07jasjeet 🙇 
This will ship with the next WordPress Android release 🎉
