### ISSUE TITLE
My Site: Deleting one and only site causes dashboard to bug out

### ISSUE THREAD

**Issue by 07jasjeet** [wordpress-mobile/WordPress-Android#19441]
### Expected behavior
When a user with **only one** site deletes that one and only site, refreshing dashboard should clear it and say no sites default message.

### Actual behavior
When a user with only one site deletes that one and only site, refreshing dashboard causes a snackbar message to pop up saying "Couldn't update dashboard" and the previous data of deleted site stays on the dashboard or My Site tab.

### Steps to reproduce the behavior
1) Have only one site.
2) Delete that one and only site.
3) Come back to dashboard.
4) A snackbar should pop up saying "Couldn't update dashboard".
5) Refresh
6) Same snackbar pops up.

**Comment by AjeshRPai** [comment]
Hey @07jasjeet  
Thank you for raising this issue, I have created a PR to fix this issue here - [Adds: the logic to handle site removed](https://github.com/wordpress-mobile/WordPress-Android/pull/19598) . Feel free to take a look and comment

**Comment by AjeshRPai** [comment]
Closed with the PR - https://github.com/wordpress-mobile/WordPress-Android/pull/19598
