### ISSUE TITLE
Show menu items in Dashboard for Self hosted sites

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#19461]
### Expected behavior
The Menu items should be shown on the dashboard for Self hosted sites in Jetpack app

### Actual behavior
Unified dashboard with card hidden message is shown in dashboard for Self hosted sites in Jetpack app

### Steps to reproduce the behavior
- Login to the Jetpack app with a self hosted site 
- Notice that the dashboard shown is as in the screenshot 
- Notice that no cards message is shown 

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
Pixel 4a, Android 13, trunk

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Medium` judging from the issue description. Please correct me if I'm wrong.
