### ISSUE TITLE
Dashboard Cards Personalization shows in eligible cards 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#19467]
### Expected behavior
For a site or user not having the capability of a feature, the card personalization for that card should not be shown 

### Actual behavior
The ability to hide/show a card of a feature that isn't available for the user is shown in the dashboard personalization screen

For example, the below screen shows blaze card hide/show ability but the feature is not available on the site

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/17463767/1e840fe8-77cc-48ee-9318-3d8cfc5ddba3" width="250" height="530">

### Steps to reproduce the behavior
- Go to Jetpack app and login to an account without having Blaze, Activity log or Post edit capability
- Go to Dashboard 
- Click on Personalize your Home tab 
- Notice that Blaze or Activity Log card hide/show toggle is shown

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
Pixel 4a, Android 13

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Medium` judging from the issue description. Please correct me if I'm wrong.
