### ISSUE TITLE
Comments not being sent 

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#19525]
### Expected behavior

When I comment on a post, the comment should be sent to the post author or site owner for approval.

### Actual behavior

When I comment on a post, the comment appears to be posted but the post author doesn't get the comment under (My Site > More > Comments).

### Steps to reproduce the behavior
1. Log into account A on a device running the beta specified below
2. Log into account B on another device
3. Use account A to comment on a post from account B
4. The comment will appear sent, but account B doesn't receive it

Try with two fresh accounts that don't have roles on each other's sites

**Comment by RenanLukas** [comment]
👋 
I've tried reproducing the issue but couldn't so far. More info pcdRpT-4n3-p2#comment-7168

**Comment by guarani** [comment]
Thanks a lot for testing this, @RenanLukas! It turns out that the comments were simply being sent to spam. I was using an old test account, so that could be related.

Sorry for the noise, I'll close this as it's not an issue.
