### ISSUE TITLE
Personalize Dashboard View Crash

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#19536]
Crash in JP app when updating the state of the cards within the Personalization View when an expected card state is not built.

CC: @AjeshRPai 

Crash Log
<details>
FATAL EXCEPTION: DefaultDispatcher-worker-1Process: com.jetpack.android.beta, PID: 6784java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)	at java.util.Objects.checkIndex(Objects.java:359)	at java.util.ArrayList.set(ArrayList.java:448)	at org.wordpress.android.ui.mysite.personalization.DashboardCardPersonalizationViewModelSlice.updateCardState(DashboardCardPersonalizationViewModelSlice.kt:183)	at org.wordpress.android.ui.mysite.personalization.DashboardCardPersonalizationViewModelSlice.access$updateCardState(DashboardCardPersonalizationViewModelSlice.kt:24)	at org.wordpress.android.ui.mysite.personalization.DashboardCardPersonalizationViewModelSlice$onCardToggled$1.invokeSuspend(DashboardCardPersonalizationViewModelSlice.kt:157)	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e60bd21, Dispatchers.Default]
</details>

**Comment by AjeshRPai** [comment]
Closed with the PR https://github.com/wordpress-mobile/WordPress-Android/pull/19537
