### ISSUE TITLE
Dashboard: Create Another Page doesn't open the editor

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-Android#19559]
### Expected behavior
That you are start the editor when you tap create another new page from the dashboard. 

### Actual behavior
Nothing. The button is not responsive. 

### Steps to reproduce the behavior
Load the dashboard. On the Pages card tap "create anther page".

**Comment by AjeshRPai** [comment]
Closed with https://github.com/wordpress-mobile/WordPress-Android/pull/19569
