### ISSUE TITLE
Site Preview: Safari icon is not the right colour

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-Android#19558]
### Expected behavior
That the safari icon matches all the other ones in dark mode. 

### Actual behavior

See
<img width="300" alt="Screenshot 2023-11-07 at 4 50 39 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/115071/75e5512f-a8ba-4596-aa3b-e73b949f3b7a">

### Steps to reproduce the behavior
In darkmode preview a site.

**Comment by staskus** [comment]
Not reproducible anymore. cc @NataliaDrause
