### ISSUE TITLE
Reader: tab do not look as expected

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-Android#19560]
### Expected behavior
That tabs vertical lines fall between the words. 

### Actual behavior
<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/115071/d4e1e0ce-83a9-4042-a3af-50d7ff84b73f" width="300" />

### Steps to reproduce the behavior
Navigate to the reader.

**Comment by RenanLukas** [comment]
👋  I was able to reproduce the issue with > 10 tabs on my Reader (with multiple custom reading lists).

**Comment by RenanLukas** [comment]
I'm closing this issue because the Reader tabs have been replaced by a dropdown menu, so we don't have tabs in the Reader feeds anymore.
