### ISSUE TITLE
🤖 Add pull-to-refresh on All Domains screen

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-Android#19562]
Add a pull-to-refresh behavior to the all domains screen. At a minimum, this should be implemented on the error screen after the fetch fails.

**Comment by antonis** [comment]
I opened an issue for adding a retry button https://github.com/wordpress-mobile/WordPress-Android/issues/19564.
 Feel free to close it if we go with the pull to refresh implementation.
