### ISSUE TITLE
"No sites" message is visible when there's self-hosted site

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#19587]
### Expected behavior
No sites message should not be visible when there's self-hosted site.

### Actual behavior
No sites message should not be visible when there's self-hosted site.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/c5a9563f-1d71-48e8-9060-e5b6dfd326a2" width=320>

### Steps to reproduce the behavior
1. Launch the JP app.
2. Log in with a wp.com account.
3. Add a self-hosted site.
4. Log out from your wpcom account.
5. Navigate to My Site.

#### After deleting a site (this is a different flow, but possibly the root cause is the same)

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/bb5c03ab-40c7-495b-90e2-b6d7f86188ce" width=320>

1. Launch the WP app.
2. Log in with a wp.com account with a single site.
3. Remove the site.

**Comment by AjeshRPai** [comment]
Closed with the PR https://github.com/wordpress-mobile/WordPress-Android/pull/19595
