### ISSUE TITLE
[Reader IA][Tags] Implement tags bottom sheet UI

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19607]
pcdRpT-4tr-p2

Similar to https://github.com/wordpress-mobile/WordPress-Android/issues/19612

Depends on https://github.com/wordpress-mobile/WordPress-Android/issues/19606

- Implement UI
- Implement action on [tags button](https://github.com/wordpress-mobile/WordPress-Android/issues/19606) that opens the bottom sheet

<img width="388" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/0f99de54-2390-4f07-b0d8-4a81dd86b882">

**Comment by thomashorta** [comment]
No changes are needed in the filter bottom sheet tag items as they already match the spec.
