### ISSUE TITLE
[Reader IA][Tags] Implement tags bottom sheet actions

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19608]
pcdRpT-4tr-p2

Similar to https://github.com/wordpress-mobile/WordPress-Android/issues/19613

Depends on https://github.com/wordpress-mobile/WordPress-Android/issues/19607

- Implement tapping on [tags bottom sheet item](https://github.com/wordpress-mobile/WordPress-Android/issues/19607): refresh the feed when a tag is tapped;
<img width="391" alt="Screenshot 2023-11-10 at 8 26 20 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/8584d265-695a-4b68-9d95-faee5454f692">

- When a tag is selected, add top button with the name of the tag and remove button (UI and action);
<img width="398" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/e89f452e-54c6-4809-90c1-067052f02ffa">
<br>
<br>

`Manage tags` button will be handled in [another issue](https://github.com/wordpress-mobile/WordPress-Android/issues/19609).

**Comment by thomashorta** [comment]
Closing this as is the work for this was done in https://github.com/wordpress-mobile/WordPress-Android/issues/19855
