### ISSUE TITLE
Quick Start should make use of new shortcuts

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#19600]
### Expected behavior

After site creation, the user is taken through Quick Start steps. When the step refers to an item in the user's visible shortcuts, the Quick Start indicator (circle) should point to the shortcut item.

### Actual behavior

The Quick Start indicator (circle) always points to the "More" item, which is an unnecessary extra step for users and doesn't show them the usefulness of the shortcuts.

### Steps to reproduce the behavior
1. Create a new site
2. Accept to be shown Quick Start steps
3. Notice that steps such as for Stats or Pages (which are default shortcuts), direct the user past the shortcuts and to the More option

**Comment by zwarm** [comment]
This is as designed. The focus point will only show on the "more" item and not on the individual quick link.

**Comment by guarani** [comment]
Fair enough @zwarm, thanks for clarifying!
