### ISSUE TITLE
[Reader IA] Remove "Manage Topics & Sites" entry point

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19619]
pcdRpT-4tr-p2

In the context of Reader IA project, managing followed blogs and tags will be handled in different flows, so we can remove "Manage Topics & Sites".

- Remove the icon from toolbar
<img width="353" alt="Screenshot 2023-11-10 at 9 27 59 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/51bb9ad8-8853-4851-a34b-04f0f6fc6536">

- Remove the unused code

**Comment by thomashorta** [comment]
Closing this as it was done as part of https://github.com/wordpress-mobile/WordPress-Android/issues/19605.
