### ISSUE TITLE
[Reader IA][Blogs] Implement blogs bottom sheet actions

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19613]
pcdRpT-4tr-p2

Similar to https://github.com/wordpress-mobile/WordPress-Android/issues/19608

Depends on https://github.com/wordpress-mobile/WordPress-Android/issues/19612

- Implement tapping on [blogs bottom sheet item](https://github.com/wordpress-mobile/WordPress-Android/issues/19607): refresh the feed when a blog is tapped;
<img width="386" alt="Screenshot 2023-11-10 at 8 59 33 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/5c1dfede-b056-4e10-8429-e1a356e2b615">
<br>
<br>

- When a blog is selected, add top button with the name of the blog and remove button (UI and action);
<img width="391" alt="Screenshot 2023-11-10 at 9 01 53 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/af1fe69a-748e-4a52-9fc6-36a7dede3c27">

<br>
<br>

`Manage blogs` button will be handled in [another issue](https://github.com/wordpress-mobile/WordPress-Android/issues/19614).

**Comment by thomashorta** [comment]
Closing this as it was implemented in https://github.com/wordpress-mobile/WordPress-Android/issues/19855.
