### ISSUE TITLE
[Jetpack Social] Fix share limits being shown for Atomic sites

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19641]
Share limits shouldn't be shown for Atomic sites in the context of Jetpack Social. There are 3 place to double-check using an Atomic site:

1 - Share limits dashboard card;
2 - Edit post - publish bottom sheet;
3 - Edit post - settings;

See p9F6qB-dLk-p2#comment-56603

**Comment by bobmatyas** [comment]
@RenanLukas Is there a timeline for when this might be fixed that we can share with the user? The ticket is still open and it would be nice if we could give them an update.

**Comment by RenanLukas** [comment]
@bobmatyas we're going to have a look this week.

**Comment by thomashorta** [comment]
@bobmatyas I just opened a PR (https://github.com/wordpress-mobile/WordPress-Android/pull/19848) fixing the issue on Android, though based on the reference in the original issue I believe the user was using iOS, which has the same bug.

I already sent a message to the iOS Engineers on my team (ref: p1703283004926699-slack-C01CW1VMLAF) about the root causes and the fix and I believe they will look into it soon and probably fix it for the 24.0 release as well (which should be available to users on January 8).

**Comment by dvdchr** [comment]
👋🏼 I also opened a PR to fix this for iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/22303. This fix targets app version 24.0.
