### ISSUE TITLE
SoTW 2023 card in the WordPress app

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19709]
Internal ref: pdb1SS-3F9-p2

Since we currently don't have a way of showing informational nudges/cards in the WordPress app, we will add a static card for inviting the users to check the State of the Word keynote event recording.

We'll add a simple card for SoTW in the WordPress app:

![image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/9bf21b77-7e3e-4bbf-8790-ed7b351cbda3)

## Overall Specs
- The card uses a remote feature flag: `wp_sotw_2023_nudge`
- The card is displayed on top of the My Sites menu.
- Tapping `Watch now` should open a link to the event landing page.
- The text does not need localization. It's only displayed in English.
- If we have enough time, allow the user to dismiss the card (once and forever).
  - In the card, I used the ellipsis menu, but we can use the `X` icon and directly dismiss the image if it's any easier.

### Card shown
`sotw_2023_nudge_post_event_card_shown`

### Card hidden ("hide this" button tapped)
`sotw_2023_nudge_post_event_card_hide_tapped`

### CTA tapped
`sotw_2023_nudge_post_event_card_cta_tapped`

**Comment by dvdchr** [comment]
Marking this as closed via these PRs:

- #19710 
- #19716
- #19717
- #19718 
- #19719 
- #19720 
- #19721

Thanks for your work, Thomás! 🙂
