### ISSUE TITLE
Contact Support: Suggested questions overlap with introduction

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-Android#19722]
See: pcdRpT-4GT-p2#comment-7728

### Expected behavior

Suggested questions shouldn't overlap the bot's intro message on the Help screen when the keyboard is displayed.

### Actual behavior

Suggestions overlap with the introduction message from the bot when the keyboard is displayed.

<img width="381" src="https://github.com/wordpress-mobile/WordPress-Android/assets/2454408/f1591327-21e5-403c-b533-f2c09bc43ca2">

### Steps to reproduce the behavior

1. Navigate to the Help screen
2. Tap on `Contact Support`
3. Tap on `Send a message...`

##### Tested on Galaxy A53 5G, Android 13, JPAndroid 23.8-rc-2

**Comment by ravishanker** [comment]
Please see pcdRpT-4GT-p2#comment-7738
