### ISSUE TITLE
Dashboard cards implemented with Jetpack compose have a background 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#19772]
### Expected behavior
The cards on the dashboard shouldn't have a background outside the rounded corners

### Actual behavior
<img width="657" alt="Screenshot 2023-12-07 at 7 02 07 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/17463767/08e71f85-e36d-4ac2-826a-b44dacbbe50a">

Notice that there is a background outside the rounded corners. This behaviour exists in the following cards 
- Blaze Campaigns Card 
- Personalize card
- Bloganuray Card
- Domain Dashboard Card

### Steps to reproduce the behavior
Login to the app with an admin account + jetpack site

**Comment by malirauf** [comment]
Hey,
I want to work on this issue.

**Comment by AjeshRPai** [comment]
Hey @malirauf 

Thanks for your interest to work on this issue. I have already raised a PR for this. 

May I suggest you look for issues with #good-first-issue tag.
