### ISSUE TITLE
Text contrast with the background is insufficient for certain Themes in the Editor.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#19824]
### Expected behavior
Text in the editor should have good contrast with the background.

### Actual behavior
Text in the editor is barely visible for `Geologist - Cream` theme.

Impacted themes identified:
`Geologist - Cream`
`Kigen`

<img width="300" src="https://github.com/wordpress-mobile/WordPress-Android/assets/42008628/497391e5-f148-418a-8763-36108eaf9d8f">

### Steps to reproduce the behavior
1. Set the site team as `Geologist - Cream`
2. Open an existing post or create a new one
3. ❌  Notice that the text is barely visible.

**Comment by tiagomar** [comment]
User report: 7439684-zd-a8c

**Comment by SiobhyB** [comment]
**Findings so far:**

It appears that is happening in themes that don't have a defined `--wp--preset--color--foreground` value. For example, these are the `preset` values for `Geologist - Cream`.  

```
    --wp--preset--color--black: #000000;
    --wp--preset--color--cyan-bluish-gray: #abb8c3;
    --wp--preset--color--white: #ffffff;
    --wp--preset--color--pale-pink: #f78da7;
    --wp--preset--color--vivid-red: #cf2e2e;
    --wp--preset--color--luminous-vivid-orange: #ff6900;
    --wp--preset--color--luminous-vivid-amber: #fcb900;
    --wp--preset--color--light-green-cyan: #7bdcb5;
    --wp--preset--color--vivid-green-cyan: #00d084;
    --wp--preset--color--pale-cyan-blue: #8ed1fc;
    --wp--preset--color--vivid-cyan-blue: #0693e3;
    --wp--preset--color--vivid-purple: #9b51e0;
    --wp--preset--color--primary: #000000;
    --wp--preset--color--secondary: #333333;
    --wp--preset--color--background: #FFFAED;
    --wp--preset--color--tertiary: #FFFFFF;
```

The theme sets its font colour using `color: var(--wp--custom--color--foreground)`. `--wp--custom--color--foreground` is then set to `--wp--preset--color--primary` elsewhere in the codebase.

However, when we retrieve colour values via [this function](https://github.com/WordPress/gutenberg/blob/353b73264e9764b3291c753cc5eeb71f21a7e4dd/packages/components/src/mobile/global-styles-context/utils.native.js#L315-L319), we're currently only retrieving the `preset` values.

We need to either figure out a way to retrieve the custom styles from the themes.

**Comment by SiobhyB** [comment]
A quick hacky-feeling way around this would be to add something like this within [this check](https://github.com/WordPress/gutenberg/blob/353b73264e9764b3291c753cc5eeb71f21a7e4dd/packages/components/src/mobile/global-styles-context/utils.native.js#L253-L263):

```
if (colorKey === 'foreground' && colorKey?.value === undefined) {
    matchedValue = mappedValues.color?.values?.find(({ slug }) => slug === 'primary');
}
```

The above would assume that most of these themes are assigning `--wp--preset--color--primary` as the foreground colour's value, in the absence of `--wp--preset--color--foreground`. 

I'm assuming it'd be preferable to change the way we fetch the theme's details, however.

**Comment by SiobhyB** [comment]
Noting that we were able to merge a fix on the server side and this issue is now fixed 🎉
