### ISSUE TITLE
Upload fails unless connected to a charger

### ISSUE THREAD

**Issue by agoston** [wordpress-mobile/WordPress-Android#1983]
If my mobile is not on a charger, upload will stall for hours (and never resumes). This happens 100% of the time, I can effectively only use the app while charging - but then why use the app?

This is a regression, it used to work just fine a few months ago. Sorry, I can't pinpoint it more precisely.

**Comment by maxme** [comment]
I just noticed we never replied to this ;) - but [we fixed an issue with the post upload service ~6 months ago](https://github.com/wordpress-mobile/WordPress-Android/commit/bc968c1ce1f94198ec164e7c547506b939677432) - version 3.8 of the app. The post upload service is now sticky and can't be stopped, even if the app goes to background or is killed by the OS or the user.
