### ISSUE TITLE
Refactor Login Prologue screen

### ISSUE THREAD

**Issue by justtwago** [wordpress-mobile/WordPress-Android#19841]
The entire login-related  codebase has to be refactored:
* Replace LoginPrologueFragment with LoginPrologueRevampedFragment and remove the feature flag.
* Move the entire LoginPrologueRevampedFragment logic to LoginPrologueRevampedViewModel.
* Get rid of an Android Context dependency from the LoginPrologueRevampedViewModel.
* Add tests to LoginPrologueRevampedViewModel.

**Comment by malirauf** [comment]
Hey, I want to work on this.
