### ISSUE TITLE
[Reader IA - Bug] Reader state is reset when changing Bottom Bar tabs

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19852]
While testing #19844 I noticed that when switching between bottom tabs (`My Site`, `Reader`, etc), the state of the `Reader` is not saved/restored, so the feed/content is always reloaded.

I don't think this is expected, so I'm creating this issue to track and fix this bug before we make a final PR targeting the feature branch to `trunk`.

cc @RenanLukas 

### Expected Behavior
The `Reader` tab state (such as selected feed and maybe scroll position) is kept when switching only bottom bar tabs.

### Actual Behavior
The `Reader` tab content is reset, going back to the default `Discover` feed and fetching content again.

### Steps to reproduce
On a build containing the changes from https://github.com/wordpress-mobile/WordPress-Android/pull/19844, do the following:
1. Install and log into Jetpack
2. Go to `Reader`
3. Choose a feed and scroll down
4. Go to `My Site`
5. Go back to `Reader`
6. **Verify** the Reader state is reset

**Comment by RenanLukas** [comment]
> The Reader tab content is reset, going back to the default Discover feed and fetching content again.

I couldn't reproduce the selected feed change (only the scroll reset). In my tests when switching back to `Reader` I'm always getting the previously selected feed, and not `Discover`.  Here's what I'm doing:

- Open Reader
- Select `Subscriptions`/`Liked`/`Saved` and scroll down
- Open "My Site"
- Open "Reader": the scroll is reset, but `Subscriptions`/`Liked`/`Saved` is still selected instead of `Discover`.

**Comment by thomashorta** [comment]
It looks like in the current state of `feature/reader-ia` branch (commit 92df6716814466e7669d68b40ce05b4ccbe12cd0) the selected feed is being kept but the content is being refreshed and losing the scroll position.

I also found a bug with `Saved` and `Lists` feeds showing the empty state on top of the feed.

I will attempt to provide a fix for both issues when opening a PR for #19852.

Here's a video of the current behavior, for all base feeds so far.

https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/a801b489-7b6e-44e2-ba25-9583c74d6cda

**Comment by thomashorta** [comment]
> I also found a bug with Saved and Lists feeds showing the empty state on top of the feed.

I didn't directly fix that issue https://github.com/wordpress-mobile/WordPress-Android/pull/20104 but since now the feed is not reset when rotating the screen or moving between bars, I couldn't reproduce it anymore.
