### ISSUE TITLE
[Reader IA - Bug] Pull-to-refresh opens Discover Feed

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19851]
While testing #19844 I found that the pull-to-refresh causes the feed to reset to "Discover".

Since we are working on a feature branch, I'm creating this issue to keep track of the bug so we fix it before making a final PR targeting `trunk`.

cc @RenanLukas 

### Expected Behavior
Pull-to-refresh refreshes the content of the current feed with the latest posts.

### Actual Behavior
Pull-to-refresh opens and refreshes the Discover feed.

### Steps to reproduce
On a build containing the changes from #19844, do the following:
1. Open and log into Jetpack
2. Go to `Reader`
3. Select a Feed that is not `Discover` in the top bar menu
4. Pull to refresh on the feed
5. **Verify** the `Discover` feed is opened and refreshed instead of the chosen feed

**Comment by thomashorta** [comment]
This was indirectly tackled in https://github.com/wordpress-mobile/WordPress-Android/pull/19856, which is in review right now.

**Comment by RenanLukas** [comment]
Another issue that might be related is that with a fresh install (and therefore `Discover` selected by default), when we select something else in the drop-down menu (e.g. `Subscriptions`) the menu component automatically changes back to `Discover` item
