### ISSUE TITLE
Title of blogging prompt is not translated to the device's locale

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-Android#19887]
### Expected behavior
All elements of blogging prompts should be translated to the device's locale.

#### Example with device's locale is set to Spanish
<img width="431" alt="Screenshot 2024-01-05 at 09 42 38" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14905380/22becb39-cf46-440e-918f-108dcee3920a">

### Actual behavior
The title of blogging prompt is always displayed in English.

### Steps to reproduce the behavior
1. Change your device's locale to a non-English language.
2. Open the app.
3. Observe that the title of the Blogging prompt card in _My site_ screen is not translated.
4. Tap on _Answer Prompt_ to create a post.
5. Observe that the title of the prompt is not translated.

**Comment by tiagomar** [comment]
Setting the priority as High due the impact in all non-English locales (at least Turkish, Spanish, Portuguese and Italian at time of writing) and Bloganuary being time sensitive.

**Comment by fluiddot** [comment]
Closing the issue as it was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/19888.
