### ISSUE TITLE
Preserve local drafts on sign out?

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1989]
A user had local drafts in the app, then signed out. The app cleared all of the posts. 

Maybe we could:
- Preserve local drafts, even on sign out?
- Show some kind of warning that local drafts will be lost if you sign out.

**Comment by roundhill** [comment]
Test cases:

1. User has WP.com account only, signs out and back in with same username.
_Expected result:_ All previous content is still available in the app
2. User has WP.com account only, signs out and back in with same username.
_Expected result:_ All previous content is deleted and only the new username's content is shown.
3. User has WP.com account and self-hosted site, signs out and back in with same WP.com username.
_Expected result:_ All previous content is still available in the app
4. User has WP.com account and self-hosted site, signs out and back in with different WP.com username.
_Expected result:_ All content is deleted, including self-hosted sites
5. User has self-hosted site(s), signs out and back in with matching username from any site.
_Expected result:_ All previous content is available in the app.
6. User has self-hosted site(s), signs out and back in with different username from any site.
_Expected result:_ All previous content is deleted.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by oguzkocer** [comment]
We currently show this message: 
> Logging out from your account will remove all of @%s’s WordPress.com data from this device, including local drafts and local changes.

So, this at least makes sure users understand how logout behaves. I do understand the idea behind preserving data, but I think it's too much of a hassle for something pretty controversial. Some users, including me, will always want to make sure their data is removed from the app on logout. So, even if we implement this feature, I'd really like us to give the user the option to either preserve the data for the next login or just remove it. Preserving the data without explicit permissions feels really wrong to me.

Also, login/logout is not something a regular user should need to do often, if at all. If you exclude the developers and the testers, we are targeting a small portion of the users with this feature and I'd expect half of them won't even want to preserve it. So, just the opportunity cost of working on this feature doesn't seem worth it to me. Just my 2 cents.

**Comment by maxme** [comment]
> So, just the opportunity cost of working on this feature doesn't seem worth it to me. Just my 2 cents.

I agree with the current state of the app it was a pain to preserve Posts after sign out and we actually had to revert the patch introduced in #2472 because it added new issues and complexity.

We can have a look at how we can do it in FluxC, I guess it should be much easier and maintainable if we consider a "PostBackupStore" (or backup/restore actions in the PostStore).
