### ISSUE TITLE
[Reader IA - Bug] Followed P2s feed not showing in drop-down

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#19898]
![image](https://github.com/wordpress-mobile/WordPress-Android/assets/47797566/e0725f07-6802-477c-9f39-d6bbe0baa8ea)

>While comparing the viewpager tabs and feeds content for before / after, I see a missing menu item for "Followed P2S" (that is a filterable with only Sites and no Tags elements, I think similarly to the Automattic item)

What I was trying to say here is (using the same user for the before/after):
- the "Followed P2s" item is missing in the after

About how to get the Followed P2s on your side, what follows is my best guess
>I think that menu is related to P2 the product sites that I think I created in that account from https://p2help.wordpress.com/getting-started/creating-a-new-workspace/ if it's useful to create the test scenario.

but I can share my test account with you if it's quicker (just dm me in slack 👍 )

_Originally posted by @develric in https://github.com/wordpress-mobile/WordPress-Android/issues/19856#issuecomment-1881059568_

**Comment by RenanLukas** [comment]
We should also consider adding the analytics event for when this menu item is clicked.
