### ISSUE TITLE
Post list: List can be empty after changing blogs with no internet connection.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#199]
Edge case. 

Be in airplane mode and have multiple blogs in the app. 
Tap to change blogs to a blog you have not previously synced. 
Immediately you see the no connectivity prompt when the post list tried to refresh. (Maybe it would be better to fail silently in this case.)
Dismiss the prompt and notice that the post list is completely empty, but the detail still shows the detail of the selected post of the previous blog. 

2.5 beta 4(?) / Nexus 7

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
