### ISSUE TITLE
[Reader IA] Add number of subscriptions to reader_accessed analytics event

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19907]
We should add the number of followed sites and tags as parameters of the `reader_accessed` analytics event.

While implementing it we should also check if it's possible to update this event so it has the same behavior as iOS (see discussion p1704816820032369/1704816002.263729-slack-C01CW1VMLAF). If it's not an easy change we'll create a separate issue for it.

**Comment by daniloercoli** [comment]
We're tracking this issue here: https://github.com/wordpress-mobile/WordPress-Android/issues/19836
