### ISSUE TITLE
Upgrade Wordpress-Android Target SDK to 34

### ISSUE THREAD

**Issue by notandyvee** [wordpress-mobile/WordPress-Android#19917]
Conducted a preliminary investigation based on the API changes being made to Android 14 devices. Listing them out here. There may be gaps with 3rd party libraries. For example, sentry, which needs an update.

----

- [x] [Schedule exact alarms are denied by default](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms)

Smoke test this and check it off.

---

- [x] [Context-registered broadcasts are queued while apps are cached](https://developer.android.com/about/versions/14/behavior-changes-all#pending-broadcasts-queued)

We only use system registered broadcasts. Smoke test and check it off.

---

- [x] [New reason an app can be placed in the restricted standby bucket](https://developer.android.com/about/versions/14/behavior-changes-all#triggers-to-restricted-bucket)

This is more of an FYI. We have the potential to log this to ensure the bucket never changes for us. Decide that and we can check it off.

---

- [x] [mlock limited to 64 KB](https://developer.android.com/about/versions/14/behavior-changes-all#mlock)

We do not use that.

---

- [x] [System enforces cached-app resource usage](https://developer.android.com/about/versions/14/behavior-changes-all#cached-apps)

A quick search doesn't show any places where `onStop` is doing any background work. Checking off now.

---

- [x] [Foreground service types are required](https://developer.android.com/about/versions/14/behavior-changes-14#fgs-types) - (Fixed here: https://github.com/wordpress-mobile/WordPress-Android/pull/19981)
- [x] [Foreground service permissions need to be added](https://href.li/?https://developer.android.com/about/versions/14/changes/fgs-types-required#permission-for-fgs-type)- - (Fixed here: https://github.com/wordpress-mobile/WordPress-Android/pull/19981)

We need to add [foreground service types](https://developer.android.com/about/versions/14/changes/fgs-types-required) to all the services below.

   - [x] .ui.uploads.UploadService
   - [x] .ui.media.services.MediaDeleteService
   - [x] .ui.reader.services.update.ReaderUpdateService
   - [x] .ui.reader.services.update.ReaderUpdateJobService
   - [x] .ui.reader.services.discover.ReaderDiscoverService
   - [x] .ui.reader.services.discover.ReaderDiscoverJobService
   - [x] .ui.reader.services.post.ReaderPostService
   - [x] .ui.reader.services.post.ReaderPostJobService
   - [x] .ui.reader.services.search.ReaderSearchService
   - [x] .ui.reader.services.search.ReaderSearchJobService
   - [x] .ui.reader.services.comment.ReaderCommentService
   - [x] .ui.suggestion.service.SuggestionService
   - [x] .push.NotificationsProcessingService
   - [x] .ui.notifications.services.NotificationsUpdateService
   - [x] .ui.notifications.services.NotificationsUpdateJobService
   - [x] .util.analytics.service.InstallationReferrerService
   - [x] .util.analytics.service.InstallationReferrerJobService
   - [x] .login.LoginWpcomService
   - [x] .ui.sitecreation.services.SiteCreationService
   - [x] .ui.stats.refresh.lists.widget.WidgetService
   - [x] .push.GCMMessageService
---

- [x] [OpenJDK 17 updates](https://developer.android.com/about/versions/14/behavior-changes-14#core-libraries)

* Smoke test regex Matcher.
* Smoke test production build to ensure there wasn't a proguard issue.

Test a few screens that use the following [Matcher](https://developer.android.com/reference/java/util/regex/Matcher) methods:

- [x] `appendReplacement`
- [x] `end`
- [x] `group`
- [x] `start`
- [x] `usePattern`

---

- [x] [JobScheduler reinforces callback and network behavior](https://developer.android.com/about/versions/14/behavior-changes-14#jobscheduler-reinforces-behavior)

Marking this as done since we are currently already declaring the `ACCESS_NETWORK_STATE` permission. It's recommended we migrate to `WorkManager`. But it doesn't appear required based on the changes we need to make.

---

- [x] [Minimum installable target API level](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level)

Marked as done. We don't support SDKs under 24. Android 14 removes support for SDKs less than 23.

---

- [x] [Media owner package names might be redacted](https://developer.android.com/about/versions/14/behavior-changes-all#media-owner-package-names)

Not seeing usages anywhere.

---

- [x] [Restrictions to implicit and pending intents](https://developer.android.com/about/versions/14/behavior-changes-14#safer-intents)

I can't find an instance where we use implicit intents. 

---

- [x] [Runtime-registered broadcasts receivers must specify export behavior](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported)

Test runtime broadcasts being registered using `registerReceiver` in the following classes:

- [x] MediaBrowserActivity - (My Site -> More -> Media -> WordPress Media) If it doesn't crash, we are good.
- [x] MediaSettingsActivity (Done via https://github.com/wordpress-mobile/WordPress-Android/pull/19979)
- [x] AppInitializer - Load the app. Put the app in the background. Go back into the app. Not crashing is good.
- [x] ReaderPostDetailFragment - This can be tested by going to the reader and clicking on any post (https://github.com/wordpress-mobile/WordPress-Android/pull/20116)
- [x] ConnectionStatusLiveData - (My Site -> Posts) No crash and seeing your published posts means we are good.

---

- [x] [Safer dynamic code loading](https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading)

Don't think we use this. Correct me if I am wrong.

---

- [x] [Additional restrictions on starting activities from the background](https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions)

Cannot find instances where we even start an activity from the background.

---

- [x] [Zip path traversal](https://developer.android.com/about/versions/14/behavior-changes-14#zip-path-traversal)

Do not see any of these usages in the app.

---

- [x] [User consent required for each MediaProjection capture session](https://developer.android.com/about/versions/14/behavior-changes-14#media-projection-consent)

Cannot find any mention of MediaProjection.createVirtualDisplay in the app. So assuming we are good.

---

- [x] [Grant partial access to photos and videos](https://developer.android.com/about/versions/14/changes/partial-photo-video-access)

~~I haven't tested this. Will update when I do.~~

After testing this, everything mostly works. There was a bug I noticed with my Samsung phone. Nothing major. PR up for this here: https://github.com/wordpress-mobile/WordPress-Android/pull/19979

---

- [x] [Secure full-screen Intent notifications](https://developer.android.com/about/versions/14/behavior-changes-all#secure-fsi)

We do not use fullscreen notifications.

---

- [x] [Changes to how users experience non-dismissible notifications](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications)

Any non-dismissable notification in general will now be dismissable, with some caveats. Shouldn't cause any issues upgrading.

---

- [ ] Before Release -[ Add foreground service declaration to Playstore ](https://href.li/?https://support.google.com/googleplay/android-developer/answer/13392821?sjid=13020304365605501834-AP#zippy=%2Cwhen-will-these-changes-for-full-screen-intent-in-android-take-effect%2Cwhat-is-changing-for-full-screen-intent-in-android%2Cwhat-is-the-difference-between-the-datasync-foreground-service-type-and-user-initiated-data-transfer%2Chow-do-i-know-what-foreground-service-type-to-use%2Cwhat-is-a-foreground-service-permission-and-does-it-need-to-be-granted-by-the-user-before-starting-a-foreground-service%2Care-there-any-additional-requirements-in-addition-to-declaring-the-appropriate-foreground-service-permission%2Cwhat-if-my-foreground-use-case-doesnt-match-any-of-the-defined-foreground-service-types%2Cwhat-does-user-perceptible-mean%2Cwhat-if-i-target-versions-prior-to-android)

**Comment by irfano** [comment]
Thanks for listing all these changes as a task list, @notandyvee! I'll review items you investigated as a second pair of eyes.

> - [x] [mlock limited to 64 KB](https://developer.android.com/about/versions/14/behavior-changes-all#mlock)
> - [x] [JobScheduler reinforces callback and network behavior](https://developer.android.com/about/versions/14/behavior-changes-14#jobscheduler-reinforces-behavior)
> - [x] [Minimum installable target API level](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level)
> - [x] [Media owner package names might be redacted](https://developer.android.com/about/versions/14/behavior-changes-all#media-owner-package-names)
> - [x] [Restrictions to implicit and pending intents](https://developer.android.com/about/versions/14/behavior-changes-14#safer-intents)
> - [x] [Safer dynamic code loading](https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading)
> - [x] [Zip path traversal](https://developer.android.com/about/versions/14/behavior-changes-14#zip-path-traversal)
> - [x] [User consent required for each MediaProjection capture session](https://developer.android.com/about/versions/14/behavior-changes-14#media-projection-consent)
> - [x] [Secure full-screen Intent notifications](https://developer.android.com/about/versions/14/behavior-changes-all#secure-fsi)
> - [x] [Changes to how users experience non-dismissible notifications](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications)

👍🏻 

> [System enforces cached-app resource usage](https://developer.android.com/about/versions/14/behavior-changes-all#cached-apps)
> A quick search doesn't show any places where onStop is doing any background work. Checking off now.

👍🏻 I think relying only on checking `onStop`s is not enough to ensure we don't use any background work after `onStop`. This is because there may be active threads bound to the activity. However, this is not a new problem. If my understanding is correct, Android 14 only amplifies the limitation. If there are any instances of using any background threads after `onStop`, it must already be an open issue or reported on Sentry. So, I believe we don't need to be concerned about this within the scope of this project.

> - [x] [Additional restrictions on starting activities from the background](https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions)

❓  We're using `PendingIntent` and [bindService()](https://developer.android.com/reference/android/content/Context#bindService(android.content.Intent,%20android.content.Context.BindServiceFlags,%20java.util.concurrent.Executor,%20android.content.ServiceConnection)) in the project. Should we test them or are they already compatible?

**Comment by notandyvee** [comment]
Thanks for the questions @irfano .

> > [System enforces cached-app resource usage](https://developer.android.com/about/versions/14/behavior-changes-all#cached-apps)
A quick search doesn't show any places where onStop is doing any background work. Checking off now.

> 👍🏻 I think relying only on checking onStops is not enough to ensure we don't use any background work after onStop. This is because there may be active threads bound to the activity. However, this is not a new problem. If my understanding is correct, Android 14 only amplifies the limitation. If there are any instances of using any background threads after onStop, it must already be an open issue or reported on Sentry. So, I believe we don't need to be concerned about this within the scope of this project.

As per the android docs on these changes:

> Apps that use typical framework-supported lifecycle APIs – such as [services](https://developer.android.com/guide/components/services), [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler), and [Jetpack WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) – shouldn't be impacted by these changes.

Your understanding is correct.

> > [Additional restrictions on starting activities from the background](https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions)

>❓ We're using PendingIntent and [bindService()](https://developer.android.com/reference/android/content/Context#bindService(android.content.Intent,%20android.content.Context.BindServiceFlags,%20java.util.concurrent.Executor,%20android.content.ServiceConnection)) in the project. Should we test them or are they already compatible?

For `PendingIntent`, the docs seem to refer to the [PendingIntent#send](https://developer.android.com/reference/android/app/PendingIntent#send(android.content.Context,%20int,%20android.content.Intent,%20android.app.PendingIntent.OnFinished,%20android.os.Handler,%20java.lang.String,%20android.os.Bundle)) method. I could not find any usages of that. So we should be good unless I missed something. Not efficient, but I simply searched for `"send"` and checked if it was called from an intent. None are. So we are good.

For `bindService`, the docs mention when binding a service from a different app. We only bind services from internal services or system services. Doesn't affect us. But let me know if you are aware of a service we use that's from another app on the device.

**Comment by notandyvee** [comment]
@AjeshRPai I went ahead and created a [drive link](https://drive.google.com/drive/folders/1vBjNm57boH-CNf83nNSu2PxqalNmzlT1?usp=sharing) for you and created the video screengrabs. Let me know if you can't access it. There is a doc in that folder that contains the services and an explanation. Each service is accompanied by an mp4 which contains the example video it sounds the declaration needs. The exception is `ReaderCommentService-and-SuggestionService-recording`. That one doubles for both `ReaderCommentService` and `SuggestionService`.

At this point I will convert the PR so it can be reviewed. I will request two approvals before we can merge. One from you Ajesh.

**Comment by AjeshRPai** [comment]
Hey @notandyvee 
Thanks for creating the videos. 🙌🏼
