### ISSUE TITLE
[Reader IA] The new pill label incorrectly displays "Selected Site" instead of tags

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#19938]
While testing https://github.com/wordpress-mobile/WordPress-Android/pull/19882 I encountered an issue that happens selecting the Subscriptions item and then choosing "XX Tags." The pill label incorrectly displays "Selected Site" instead.

Below is a recording of the problem.

https://github.com/wordpress-mobile/WordPress-Android/assets/518232/9f5170d9-bb4f-4d28-92fe-a7ae9a5f688c

**Comment by thomashorta** [comment]
It looks like you used an old build from `feature/reader-ia` when opening this bug, the current `feature/reader-ia` branch displays the correct behavior (including opening the Filter tag/site bottom sheet and proper update of the pill content):


https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/a7afc7d4-2cc9-4b57-b7c0-e2c185ad8218


So I'm closing this issue.
