### ISSUE TITLE
Donut charts label wrapping issue

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#19959]
### Expected behavior
Donut chart labels should use margins properly. 

### Actual behavior
Some donut chart labels are wrapped even though there are enough gaps between labels.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/625b41e7-00f4-419e-b2e1-4fb60f398f7a" width=300>

### Steps to reproduce the behavior
1. Log in.
2. Navigate to "My Site → Stats →"
3. Scroll down to see the Total Followers card and tap the "VIEW MORE" button on it.
4. Notice the first label is wrapped.

**Comment by ravishanker** [comment]
If this is going to removed in light of the new Subscribers tab.  Probably, not required to fix anymore
