### ISSUE TITLE
Stats Traffic: Charts for Week, Month, and Year

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#19951]
Parent: https://github.com/wordpress-mobile/jetpack-issue-repo/issues/1

Create charts for week, month, and year, and connect to date picker

![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/847f45fe-d701-4039-a99b-5a7ac6370013)

![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/d38979f4-3da1-4ad6-bdc1-7b4cd90ab2be)

![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/6b924e13-a9b9-43b6-9b2a-7f39197fd288)

**Comment by guarani** [comment]
Closing this since it's marked as Done
