### ISSUE TITLE
Update Sentry so it supports targetSdk 34

### ISSUE THREAD

**Issue by notandyvee** [wordpress-mobile/WordPress-Android#19980]
Sentry crashes with:

```
 Failed to initialize SystemEventsBreadcrumbsIntegration.
                                                                                                    java.lang.SecurityException: com.jetpack.android.prealpha: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
```

It's a specific securoty exception related only to Android 14 targetSdk.

[Sentry Fix](https://github.com/getsentry/sentry-java/pull/2990).

- [ ] https://github.com/Automattic/Automattic-Tracks-Android/pull/195

**Comment by notandyvee** [comment]
@irfano I ran some tests and realized that Sentry isn't actually being used in WP-Android directly, which I'm a bit surprised about.  I had updated it in stories (https://github.com/Automattic/stories-android/pull/745/files).

Just running it by you so I can close if you agree.

**Comment by irfano** [comment]
@notandyvee, Sentry is installed [automatically](https://docs.sentry.io/platforms/android/configuration/gradle/#auto-installation) through Gradle. 

Gradle code that enabled Sentry: 
https://github.com/wordpress-mobile/WordPress-Android/blob/1b865d8ac51a343ad1ce9eb30020c708a7c5f780/WordPress/build.gradle#L17-L28
