### ISSUE TITLE
Fetch/cache tag list and add an autocomplete element to edit post tags list

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1999]
We could probably reuse the UI element made for suggestion `SuggestionAutoCompleteText`. @oguzkocer

**Comment by maxme** [comment]
More details about this:

This is the actual screen when the user can select or create categories and tag his posts or pages.
![screencap-2015-03-03t17-19-17 0100](https://cloud.githubusercontent.com/assets/40213/6466680/ad0bdbc2-c1c9-11e4-8c48-03cf1943269f.png)

Instead of that boring `EditText`, we would like an autocomplete view that fetch and store the tag list in the database.

**Comment by maxme** [comment]
The best way to accomplish this is probably to make `SuggestionAutoCompleteText ` more generic.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
