### ISSUE TITLE
Update UI tests for Traffic tab

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#20001]
We need to check if we have UI tests that need to be updated in preparation for the new Traffic tab in Stats.

**Comment by notandyvee** [comment]
@irfano I just want to make sure I am reading things correctly. I only see one [stats test](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/androidTest/java/org/wordpress/android/e2e/StatsTests.kt).  And it's being ignored. So nothing will break. Does this match your understanding?

To @guarani , should i just update the test so we are testing the new stats page? Probably keep it simple to avoid making tests take long.

**Comment by guarani** [comment]
> To @guarani , should i just update the test so we are testing the new stats page? Probably keep it simple to avoid making tests take long.

If the current test is ignored, at least nothing will fail in CI when the feature flag is turned on 😄  Having a simple UI test for the Traffic tab would be nice.

**Comment by irfano** [comment]
Yes, there is only `StatsTest` for e2e tests. We can leave it as it is. 

> Having a simple UI test for the Traffic tab would be nice.

This sounds good. But we can also include "writing thorough UI tests" into the "stats-specific crash fixing" project.

**Comment by guarani** [comment]
Good idea! Would you like to create an issue and add it to the `Stats 2024 Initiative` GitHub board?
