### ISSUE TITLE
[Reader IA] Subscribing to blog in search screen doesn't update the chip count

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#20151]
### Expected behavior
The blogs chip count should be correct.

### Actual behavior
The blogs chip count is incorrect.

### Steps to reproduce the behavior
1. Install Jetpack and sign in;
2. Open Reader;
3. Open the drop-down menu and select `Subscriptions` feed;
4. Tap the search button;
5. Search for a blog;
6. Open blog details;
7. Subscribe to it;
8. Move back to `Subscriptions` feed;
9. Verify the number of blogs is shown correctly
10. Repeat steps 4-8 but this time unsubscribe from a tag.

**Comment by daniloercoli** [comment]
Tested again with the latest 24.2 branch, and it appears to function as expected. Feel free to close this ticket; we can reopen it if the problem re-appear.
