### ISSUE TITLE
Offline Mode: Synchronous Publishing

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-Android#20160]
## Tasks
- [ ] Show spinner in "Publish" button in the pre-publishing sheet 
- [ ] Success
   - [ ] Show a success toast message
   - [ ] Dismiss editor
   - [ ] Switch to "Published" tab
- [ ] Error
   - [ ] Show an error toast message
   - [ ] Re-enable "Publish" button in the pre-publishing sheet

**Comment by AjeshRPai** [comment]
This is descoped from the project as it involves major refactoring. For more details check the comment - internal ref [pcdRpT-5ID-p2#comment-9638](https://href.li/?https://wp.me/pcdRpT-5ID#comment-9638)
