### ISSUE TITLE
The message "The blogs in the list have not posted anything" remains displayed on the screen

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#20183]
- Open the Reader on a list or a feed that doesn't have content
- Move to another feed 
- You should see the message  "The blogs in the list have not posted anything" still displayed on the screen
- It goes away when you scroll to the bottom and new items are received from the server (see the video attached)

https://github.com/wordpress-mobile/WordPress-Android/assets/518232/7996643b-0dd5-4271-ad2e-43a2780032e4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by thomashorta** [comment]
I am investigating and fixing this issue now since when fixing https://github.com/wordpress-mobile/WordPress-Android/issues/20127 I ran into this problem way more often when the current selected feed is not Discover or Subscriptions when opening the app, so I will try fixing this as well.

**Comment by daniloercoli** [comment]
FYI: Found out that this issue is actually related (if not duplicate) of https://github.com/wordpress-mobile/WordPress-Android/issues/19837.
