### ISSUE TITLE
🤖 Change typography to sans-serif to match other areas of the app.

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-Android#20201]
This task is to change the font in the note block to sans-serif for consistency.

| Before | After |
|-|-|
|![note-block-serif](https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/2c466784-00c4-4377-bd83-614c047dafec)|![note-block-sans](https://github.com/wordpress-mobile/WordPress-Android/assets/8507675/ae1666ed-8240-45f4-874b-9bc8e86b234b)|

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/20202
