### ISSUE TITLE
[Reader] Subscribed Sites list is incomplete

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#20218]
This issue and it's cause were discovered by @daniloercoli.

When the user has many blogs (probably > 100, see below) some of them won't be shown in the `Subscriptions` feed or `Manage Tags & Blogs` screen. This happens because paging is not handled (like it is on web client) in [our implementation of the `read/following/mine` endpoint](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateLogic.java#L318C53-L318C63).

We have to implement paging in this endpoint, which includes adding `number` and `page` query parameters (see p1708454312137679/1708440747.970699-slack-C01CW1VMLAF).

This issue seems to be reproducible for users with > 100 subscribed blogs because `100` is probably the default value for `number`.

> [!WARNING]  
> It's worth saying that besides the endpoint paging not being implemented we also limit the number of displayed posts in the client (see [ReaderPostAdapter](https://github.com/wordpress-mobile/WordPress-Android/blob/23910cd08800006a2c8e18404de31fd509cae059/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java#L110)).

### Expected behavior
All subscribed blogs are shown.

### Actual behavior
Not all subscribed blogs are shown.

### Steps to reproduce the behavior
1 - Subscribe to > 100 blogs;
2 - Open Reader;
3 - Select `Subscriptions` feed;
4 - Verify the subscribed blogs chip: the number is wrong (compare it with web);
5 - Open "Manage Tags & Blogs" screen: some blogs that the user is subscribed to are missing.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by daniloercoli** [comment]
I suggest, as an initial implementation, to adopt the same approach as the Web Reader. They fetch all pages in the background until there are no more results. You can see it in action here https://wordpress.com/read/subscriptions and filter for `following/mine` in the nwetwork tab. (Ref: `https://public-api.wordpress.com/rest/v1.2/read/following/mine?number=100&page=1`).

**Comment by daniloercoli** [comment]
Noticed that we already have another issue tracking the same problem: https://github.com/wordpress-mobile/WordPress-Android/issues/13989

**Comment by daniloercoli** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/20430
