### ISSUE TITLE
🤖 Changes in the like status are not reflected in the list

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#20211]
Changes in the like status from the detail screen are not reflected in the list view till you refresh

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/806ed1f4-ac3f-4c6e-bb22-13525f72afb3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/20243
