### ISSUE TITLE
🤖 Notifications list stuck loading after receiving a PN

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#20210]
When opening a push notification and navigate back the notifications list loads indefinitely

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/752f05c6-05b2-4015-9872-3c6532d936f8

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/20243
