### ISSUE TITLE
🤖 The badge of notification doesn't display correctly

### ISSUE THREAD

**Issue by jarvislin** [wordpress-mobile/WordPress-Android#20247]
### Expected behavior
When we have unread notifications, it should display the badge (green dot) on the bottom tab.

### Actual behavior
It hides the badge event though I have some unread notifications.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/3839951/d16a1411-4e84-4aa4-8faf-424828f07d64" width=400/>

### Steps to reproduce the behavior
1. Sign in the JP app
2. Switch to the notifications tab (after you make a new notification)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
