### ISSUE TITLE
🤖 The like status blinks in the list after changing from the detail's screen

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#20248]
### Expected behavior
When the notification like status changes from the detail screen the status changes on the list without blinking

### Actual behavior
On some occasion (check 2nd notification on the video) the status state once before the final correct state

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/653dd2d4-256c-405d-9031-2686c400f3a0

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
