### ISSUE TITLE
Login on a self hosted site can lead to an unexpected Reader screen

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2026]
Edge case.

1. Login with a wpcom account
1. Select the Reader
1. Logout
1. Login with a self hosted account

![screen shot 2014-11-26 at 10 36 34](https://cloud.githubusercontent.com/assets/40213/5199066/c4d0f8d6-7558-11e4-8c6d-28c1350d0d1e.png)

**Comment by rachelmcr** [comment]
I tested in 4.8-rc-3 and can no longer reproduce this issue. After following the steps above, the Reader opens as expected.

Closing as resolved; please reopen if you can still reproduce this issue.
