### ISSUE TITLE
Traffic tab shows wrong data for a short time

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20288]
### Expected behavior
When changing the granularity on the TRAFFIC tab, the page should display the selected granularity immediately.

### Actual behavior
When changing granularity on the TRAFFIC tab, the page shows "blank page - old granularity - new granularity" in order. This causes flickering on the screen. 

[Screen_recording_20240226_215644.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/e48632ea-2770-4744-81aa-8b87f0720510)

### Steps to reproduce the behavior
1. Log in.
2. Open "My Site → Stats".
3. Change the granularity.
4. Notice that "blank page - old granularity - new granularity" are displayed in order.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@irfano love the animation when tabs appear! How does it work when switching between Views/Visitors/Comments/Likes? Does it transition from the current values or appear from 0?

**Comment by irfano** [comment]
> @irfano love the animation when tabs appear!

Great job from @ravishanker! 🚀 

 It appears from zero.

[animation.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/40680610-5973-469b-a0e7-7df4a5176d26)
