### ISSUE TITLE
When clicking "Contact Support" a blank page is shown

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#20291]
The issue is mentioned in this app review: p1708980287122289/1708875273.950209-slack-C06BDMKNBDF

The user seems to be reporting an issue in the “Me > Help > Contact Support” flow, which opens the `SupportWebViewActivity` with DocsBotAI in a completely blank state for them.

I am not familiar with that flow or the API we use for that bot, but I feel like some error might be going on and we are just ignoring it, leading to this blank page. Maybe we should at least log/track possible initialization errors or other types of DocsBotAI API errors. For instance, I notice we are calling `reject` on the `init` Promise in case of errors, but we are not doing anything with that where we call `init`.

Reject:
https://github.com/wordpress-mobile/WordPress-Android/blob/9d72eb12abbc67d222b8598d46f9249193bd1884/WordPress/src/jetpack/assets/bot_widget.js#L48-L50

Init code:
https://github.com/wordpress-mobile/WordPress-Android/blob/29f87ac38e168f10329aa27506850c97e9cacd10/WordPress/src/jetpack/assets/support_chat_widget.js#L10-L45

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ravishanker** [comment]
This issue seems to be due to DocsBot being down on those days.

In any case, there's a plan to move to Odie soon peZLxy-uI-p2.  Hence closing it.
