### ISSUE TITLE
The app does not preserve location metadata in uploaded pictures

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#20295]
The app does not preserve location metadata in pictures uploaded from mobile devices, even when the `Remove Location from media` setting is turned off in the Settings screen. 
Additionally, toggling off the `Optimize images` feature does not affect this outcome. In theory, when this setting is off the picture should be uploaded as-is, without any modifications.  

When uploading the same picture via the web, location metadata are retained, indicating the issue is specific to the mobile app.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by twstokes** [comment]
I tested using a simple WP.com site:

### Web
1. Upload an image with EXIF location metadata on web.
2. Using the Media view, download the original image.*
3. Confirm the EXIF location metadata was retained.

*Images scaled and processed by WordPress don’t appear to retain this data.

### iOS / Android
1. Make sure “Remove Location from Media” setting is toggled off.
2. Upload an image with EXIF location metadata using the app, via a new post or the Media view.
3. Go to step 2 on Web above.

iOS looked good, but I confirmed Android isn’t sending the data. Interestingly it’s not scrubbing the GPS field, but it’s zeroed out (which is kinda worse). I also wanted to note that this can be reproduced using the Media view in the app.

**Comment by antonis** [comment]
The issue is probably due to the [missing `ACCESS_MEDIA_LOCATION` permission introduced in Android 10 (API 29)](https://developer.android.com/reference/android/Manifest.permission#ACCESS_MEDIA_LOCATION). We might also need to use the [MediaStore.setRequireOriginal](https://developer.android.com/reference/android/provider/MediaStore#setRequireOriginal(android.net.Uri)) to access the URI with the exif information.

**Comment by antonis** [comment]
> The issue is probably due to the [missing ACCESS_MEDIA_LOCATION permission introduced in Android 10 (API 29)](https://developer.android.com/reference/android/Manifest.permission#ACCESS_MEDIA_LOCATION). 

I experimented with just getting the extra permission and the exif data are still redacted.

> We might also need to use the [MediaStore.setRequireOriginal](https://developer.android.com/reference/android/provider/MediaStore#setRequireOriginal(android.net.Uri)) to access the URI with the exif information.

We should indeed use `MediaStore.setRequireOriginal(Uri)` to access the original file with all its metadata, including location information. I believe that a proper solution needs to use a `ContentResolver` to create an `InputStream` to be used for the upload. This would look like:

```
val originalUri: Uri = ...
val resolver: ContentResolver = context.contentResolver

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
    val takeFlags: Int = Intent.FLAG_GRANT_READ_URI_PERMISSION or
            Intent.FLAG_GRANT_WRITE_URI_PERMISSION
    resolver.takePersistableUriPermission(originalUri, takeFlags)
}

val parcelFileDescriptor = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
    MediaStore.setRequireOriginal(originalUri)
    resolver.openFileDescriptor(originalUri, "r")
} else {
    resolver.openFileDescriptor(originalUri, "r")
}

val fileInputStream = FileInputStream(parcelFileDescriptor?.fileDescriptor)
```

The current upload mechanism is based on the [file path of the `MediaModel`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/model/MediaModel.java) and we need to investigate further how to [adapt it](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/media/WPRestUploadRequestBody.kt#L53).
