### ISSUE TITLE
[Reader] Use "follow" for tags

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#20297]
We recently changed several Strings in the apps from "follow"/"followed"/"following" to "subscribe"/"subscribed"/"subscriptions", but it turns out these new terms should be only used for **blogs**, so we now need to revert some of those changes back to the "follow" when talking about **tags**.

Internal ref: p1709029253585639/1708546908.187529-slack-C05N140C8H5

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
