### ISSUE TITLE
Stats Traffic: Views/Visitors/Comments/Likes tracked incorrectly

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#20313]
Both property key and value are incorrect when tracking `stats_overview_type_tapped`

1. Enable Stats Traffic
2. Open Stats
3. Open Traffic
4. Select "By Year" period
5. Change between views/visitors/comments/likes

**Result:**  `Tracked: stats_overview_type_tapped, Properties: {"granularity":"months"}`
**Expected:**  `stats_overview_type_tapped_views` / `stats_overview_type_tapped_visitors` / `stats_overview_type_tapped_comments`, `stats_overview_type_tapped_likes`, `Properties: {"period":"years"}` see https://github.com/wordpress-mobile/jetpack-issue-repo/issues/4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by irfano** [comment]
Good catch, @staskus! I somehow overlooked updating this event. It's fixed now.
