### ISSUE TITLE
Stats Traffic: Overlapping x-axis labels on the updated Bar Chart used in Details views

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#20312]
Overlapping x-axis labels on the updated Bar Chart used in Details views

## Steps to reproduce

1. Enable Stats Traffic Feature flag
2. Open Stats
3. Open Traffic tab
4. Select Posts & Pages card
 
![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/c248ce44-a24b-48c5-af85-bbc8573062cd)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
