### ISSUE TITLE
Stats Traffic: Weekly and yearly bar chart bars start above 0

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#20311]
https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/72748eed-73ae-4282-9235-2ce7aa310407

Pixel 7 Pro API 34 Emulator

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by irfano** [comment]
I can't reproduce this.
