### ISSUE TITLE
Stats Traffic By Week chart uses incorrect date range

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#20334]
### Expected behavior

The Traffic tab's "By week" view should use the same date range in the date picker and on the chart.

### Actual behavior

The Traffic tab's "By week" view uses
- `26 Feb - 3 Mar`  in the date picker (expected)
- `Feb 27 to Mar 4` on the chart

### Screenshots

![CleanShot 2024-02-28 at 23 00 09@2x](https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/333a55f9-d3e6-4520-85d0-68f1f5fcb64b)

### Steps to reproduce the behavior
1. Open the Stats Traffic tab (currently behind a feature flag)
2. Tap "By day" and change it to "By week"
3. Notice the date range of the date picker is different to the one shown on the chart

To reproduce, it may be necessary to have the device's time zone and the site's time zone different so that each is on a different day. **Update: I ruled this out after testing once my day and the site's day matched.**

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ravishanker** [comment]
This is showing correct here from Sydney.  May be someone can take a look at it again before closing it.

<img width=320 src=https://github.com/wordpress-mobile/WordPress-Android/assets/990349/dc60d487-6103-4c28-9f95-c37bbc659018 />

**Comment by guarani** [comment]
👋 Thanks for checking, @ravishanker. I realized this is reproducible only when the device timezone is UTC-1 or earlier. So any timezones in the Americas should reproduce this bug.

**Comment by irfano** [comment]
This issue persists when the site timezone is set to 0, and the device timezone is set to +14.
