### ISSUE TITLE
Stats Traffic chart counts show incorrect values

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#20335]
### Expected behavior

Stats should match those shown on WP.com.

#### Traffic By Month

The View count on Android is lower than on WP.com or iOS:

![CleanShot 2024-02-28 at 23 42 22@2x](https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/e2a9b8cc-c478-4259-8f43-977da03fd4a7)

#### Traffic By Year

Again, the View count on Android is lower:

![CleanShot 2024-02-28 at 21 55 06@2x](https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/4f572a82-7b81-4548-97f1-a0c0647ed0ed)

### Steps to reproduce the behavior
1. Open the Stats Traffic tab (currently behind a feature flag)
2. Switch to `By week` and compare the View count to WP.com
3. Switch to `By month` and compare the View count to WP.com

To reproduce, it may be necessary to have the device's time zone and the site's time zone different so that each is on a different day. **Update: I ruled this out after testing once my day and the site's day matched.**

##### Tested on Samsung Galaxy S10, Android 12, JPAndroid `trunk` 97b1c1b329917b40ec780d7c3911d215ba354292

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ravishanker** [comment]
Took a look into this using Automattic Kudos site a8ckudos.wordpress.com.  They all seem to match.  Not sure, if the stats are accounted for in 5 or 15 minute time blocks to explain this difference.   It's better someone takes another look to rule out this issue.

### Android

| Week | Month | Year |
|--------|--------|--------|
| ![Screenshot_20240229_143921](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/9956a3a3-1d03-4622-9b87-df8af541db18) | ![Screenshot_20240229_144024](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/542c95a2-c994-4ae8-ae8b-698d764a2aec) |![Screenshot_20240229_144056](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/847d782b-9a75-41d8-8f73-30f63ba3285a) | 

### iOS

| Week | Month | Year |
|--------|--------|--------|
| ![IMG_2343](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/a2300031-b21d-4e25-9a56-aeeca21fd775) | ![IMG_2344](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/80ce2226-488c-4b20-9f0c-c2fd76531412) | ![IMG_2345](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/b7e2939a-7d3e-46a9-be6d-3c0b051c6c8b) | 

### .Com

| Week | Month | Year |
|--------|--------|--------|
| <img width="320" alt="Screenshot 2024-02-29 at 2 43 10 pm" src="https://github.com/wordpress-mobile/WordPress-Android/assets/990349/451a7d24-d069-4816-8403-b8c896d54bb5"> | <img width="320" alt="Screenshot 2024-02-29 at 2 43 32 pm" src="https://github.com/wordpress-mobile/WordPress-Android/assets/990349/cbd6edff-71bd-48f5-9817-beb612c4547a"> | <img width="320" alt="Screenshot 2024-02-29 at 2 43 47 pm" src="https://github.com/wordpress-mobile/WordPress-Android/assets/990349/4614ebde-10c0-473a-9118-c43b3070a1af"> |

**Comment by staskus** [comment]
I cannot reproduce it straightaway as well. Is there some caching mechanism on Android that could explain this?

**Comment by irfano** [comment]
I could reproduce the issue. @ravishanker, if you look closer at the charts, you'll notice that the bar height is incorrect on the Android chart. On the month chart, the value of "26-3" is above 600 on iOS but below 600 on Android in your screenshot.

I fixed it with https://github.com/wordpress-mobile/WordPress-Android/pull/20340

Good catch, @guarani. 👍🏻
