### ISSUE TITLE
[Design System]: Update DS color definitions to Android values provided by Design

### ISSUE THREAD

**Issue by aditi-bhatia** [wordpress-mobile/WordPress-Android#20345]
### Expected behavior
The current [implementation](https://github.com/wordpress-mobile/WordPress-Android/pull/20259) of the Design System on Android uses the [Figma colors defined for iOS](https://www.figma.com/file/LyzJJa6ANKToUswWmRrZee/%F0%9F%A7%B1-Jetpack-App-Design-System-iOS?type=design&node-id=102-186&mode=design&t=Wi3R782flI5QJm3d-0). The color definitions will need to be updated once we have the updated list from Chris. See Slack convo [here](https://a8c.slack.com/archives/C04TXQU42HM/p1708599421092949) and PR discussion [here](https://github.com/wordpress-mobile/WordPress-Android/pull/20259#discussion_r1505232413).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
