### ISSUE TITLE
Stats Traffic: layout changes, like orientation cahnge, breaks the layout.

### ISSUE THREAD

**Issue by notandyvee** [wordpress-mobile/WordPress-Android#20343]
### Expected behavior

Traffic stats tab should still work when changing orientation.

### Actual behavior

Traffic stats tab breaks and shows nothing after orientation change.

### Steps to reproduce the behavior

* Turn on the traffic stats tab feature.
* Go to the stats screen.
* Change the orientation.

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]

* Pixel 4 XL
* Android 13
* Latest trunk

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
👋 @irfano, I think this was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/20393 (that PR has a different issue under "Fixes #", but that might be a typo)

**Comment by irfano** [comment]
> 👋 @irfano, I think this was fixed in #20393 (that PR has this issue under "Fixes #", but that might be a typo)

You're correct, there was a typo. I've fixed it. Thanks for catching it.
