### ISSUE TITLE
Chart on the Traffic tab shouldn't prompt "Double tap to activate" with Talkback

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20363]
### Expected behavior
On the TRAFFIC tab, when tapping bars, Talkback shouldn't prompt "Double tap to activate" because bars are not selectable.

### Actual behavior
On the TRAFFIC tab, when tapping bars, Talkback prompts "Double tap to activate".

https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/16d1458c-465d-4122-b3a3-483995f1936e

### Steps to reproduce the behavior

1. Log in JP app.
2. Enable Talkback from the device settings.
3. Open "My Site → Stats"
4. Open the TRAFFIC tab and select By week, By month or By year.
5. Tap on a bar.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
