### ISSUE TITLE
Pull-to-refresh is not working on the TRAFFIC tab

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20397]
### Expected behavior
Pull-to-refresh should update cards on the TRAFFIC tab.

### Actual behavior
Pull-to-refresh does not do anything on the TRAFFIC tab.

[update-bug.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/5ac2a747-ef5b-4a90-b543-835aba72568c)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by aditi-bhatia** [comment]
I've been working on debugging this issue but I am seeing it occur with both FF `enabled` and `disabled`. When it works with `FF enabled`, it won't work with `FF disabled`, and vice versa. It's also worth noting that killing the app and restarting it fixes the issue.

**Comment by aditi-bhatia** [comment]
Closing based on discussion here: https://github.com/wordpress-mobile/WordPress-Android/pull/20524.
