### ISSUE TITLE
Stats not loading Traffic by week in certain timezones

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#20412]
### Expected behavior

The Traffic should be filterable **By week**.

### Actual behavior

The Traffic tab doesn't load when I filter **By week**. This only breaks in UTC-positive timezones such as UTC+1.

### Screenshot

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/1898325/07f7a21c-61d2-4f6b-8d00-7d0ca2799756" width="350" />

### Steps to reproduce the behavior
1. Download Jetpack app v24.4 beta
2. Make sure the device is in a UTC-positive timezone such as UTC+1
3. Go to Stats > Traffic
4. Switch from **By day** to **By week**
5. Notice the chart doesn't load

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
