### ISSUE TITLE
The traffic chart bars are turning green

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20413]
### Expected behavior
After changing metric types on the Traffic chart, the graph should remain accurate.

### Actual behavior
After changing metric types on the Traffic chart, the graph is turning green.

https://github.com/wordpress-mobile/jetpack-issue-repo/assets/7199140/5b919f29-8896-457e-ab5a-8ddb92ee5f8f

### Steps to reproduce the behavior
1. Log in.
2. Select a site with high stats data.
3. Open Site → Stats.
4. Change metrics type to Likes or Visitors.
5. Change the metrics type Views again.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
Good catch folks! I couldn't reproduce this either until I went to a site with lots of traffic (thanks for adding that step to reproduce @irfano).

I moved this to Ready so it can be picked up, since I think it's triaged and has reliable steps to reproduce.
