### ISSUE TITLE
Error when trying to activate non-free themes

### ISSUE THREAD

**Issue by dsas** [wordpress-mobile/WordPress-Android#20419]
### Expected behavior
~~To have a clear indication that a particular theme isn't included in my WordPress.com plan, to be prompted to upgrade my plan to one that includes the theme and after upgrade, the theme to be activated and installed.~~

Looks like the real expected behaviour is to not list non-free themes that are not active on the users site.

### Actual behavior
I got a message saying "Something went wrong. Could not activate theme" which seems to originate from [ThemeBrowserActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/96d72f843168ce9efa723ed57881b705c1d5d84f/WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserActivity.java#L363)

### Steps to reproduce the behavior
 1. Open JP app
 2. Change site to one on the free plan
 3. Press "More"
 4. Press "Themes"
 5. Scroll to a theme that is not included in the Free plan, like Cakely
 6. Press the three-dot menu
 7. Press Activate

Of extreme relevance is that T-Rex have changed the way that themes are marked as being part of a plan or not. Simplifying slightly but themes can now be Explorer and up, Starter and up or Free and up. PT: paYJgx-4kX-p2

We are very willing to help with this.

~~At an initial glance it looks like the theme list on my free site is including themes that are starter/explorer-only under the new system, but isn't including themes that are premium under the old system.~~

It's treating themes that have been deployed without an individual theme price as "free", even if they're only available via purchasing a WordPress.com plan.

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
OnePlus CE something or other, Jetpack App 24.4-rc-1 (apparently I opted into the beta via the play store at some point).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by dsas** [comment]
Running through the code a bit:

 * The themes data is [fetched](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/theme/ThemeRestClient.java#L126) from `https://public-api.wordpress.com/rest/v1.2/themes`
 * The response is [mapped](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/564e35b89b1542924a63043bee20be4c65c21647/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/theme/ThemeRestClient.java#L231) to a `ThemeModel` which marks the theme as `free` if it doesn't include a price
 * The `ThemeBrowserFragment` [removes](https://github.com/wordpress-mobile/WordPress-Android/blob/96d72f843168ce9efa723ed57881b705c1d5d84f/WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.kt#L102) the premium themes from the list of themes (where premium means `!free`).

The themes that are not being displayed don't have an individual price and so are being treated as free. We removed the primary UI for making individual purchases last May (see p7DVsv-hCY-p2) and as of last month have stopped setting individual theme prices when moving a theme between plans.

Instead the code should check the `theme_tier` property in the API response `theme_tier.slug === 'free'` is themes included in the free plan and would be the quickest change to make to the code.

**Comment by dsas** [comment]
I'm not sure how big of a lift this is. I can assign prices to all of these themes for the interim but that is just playing whack-a-mole, a temporary workaround that will slow down theme deployment.

**Comment by dsas** [comment]
Highlighted in slack: p1709748614878359-slack-C0180B5PRJ4

**Comment by guarani** [comment]
Sharing the response JSON that includes `theme_tier` for reference

```
{
      "menu_order": -136,
      "author": "Automattic",
      "id": "cakely",
      "description": "Cakely is a business theme perfect for bakers or cake makers with a vibrant colour.",
      "stylesheet": "pub/cakely",
      "name": "Cakely",
      "author_uri": "https://automattic.com/",
      "demo_uri": "https://cakelydemo.wordpress.com/",
      "screenshot": "https://i0.wp.com/s2.wp.com/wp-content/themes/pub/cakely/screenshot.png?ssl=1",
      "theme_type": "hosted-internal",
      "download_uri": "https://public-api.wordpress.com/rest/v1/themes/download/cakely.zip",
      "theme_tier": {
        "slug": "premium",
        "feature": "premium-themes",
        "platform": "simple"
      },
      "taxonomies": {
      },
      "style_variations": [],
      "soft_launched": false
    },
```

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2969 in `24.4`
