### ISSUE TITLE
Stats displays empty data differently on iOS vs. Android

### ISSUE THREAD

**Issue by aditi-bhatia** [wordpress-mobile/WordPress-Android#20423]
### Expected behavior
Empty data should be displayed in the same format on both platforms.

### Actual behavior
On iOS, we seem to be displaying no bars at all, while on Android (with both feature flag off and on), we display the green gradient bar for 0 comments. 

iOS:
<img width="202" alt="Screenshot 2024-03-06 at 12 26 45 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/7199140/68273160-34c9-4cc8-99bd-010df703e7cf">

Android:
<img width="200" alt="Screenshot 2024-03-06 at 12 26 55 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/7199140/5f53002e-c59a-4cc4-9447-944f4a66ccf4">

### Steps to reproduce the behavior
When viewing traffic-related charts, click on a subcategory that has no data (i.e. `0 likes` or `0 comments`).

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
