### ISSUE TITLE
Stats traffic flashes previous graph momentarily after changing granularity

### ISSUE THREAD

**Issue by aditi-bhatia** [wordpress-mobile/WordPress-Android#20424]
### Expected behavior
After changing the granularity, the previous graph should not flash before displaying the expected graph.

### Actual behavior
When you change the granularity, the previous graph flashes momentarily before the actual graph gets displayed.

### Steps to reproduce the behavior
Switch between granularities (i.e. from `day` to `weeks`, or `weeks` to `months` and see that the previous graph flashes momentarily before displaying the expected graph.

It happens fairly quickly so it can be hard to see - for example, when I select `weeks`, I see the `days` metrics flash right before:

https://github.com/wordpress-mobile/WordPress-Android/assets/7199140/fd64d542-5b24-487a-9870-aadd5e633f34

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
