### ISSUE TITLE
Landscape tablet, post list updates but not the selected post

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2044]
On a dual pane post list: when switching from a blog with a selected post to a blog with no post:

![img_4172](https://cloud.githubusercontent.com/assets/40213/5264210/13b97164-7a39-11e4-96ae-4432e8fb37b9.jpg)

Note: This will be fixed when we drop the dual pane screens.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
