### ISSUE TITLE
[Reader] Comments like count not clearly visible when UI is disabled

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#20443]
### Steps to reproduce
1. Install Jetpack and sign in with a self-hosted site.
2. Open Reader.
3. Select "Discover" feed.
4. Open any post with comments.
5. 🔍  Open the comments list screen. Expected: the number of likes label and icon (e.g. `2 likes`) is visible. Actual: the number of likes label and icon is not clearly visible.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
