### ISSUE TITLE
[Reader] Rename the Edit button label to Manage

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#20454]
We need to change the `Edit` label to `Manage`  in the bottom sheet that allows you to select Tags and Sites. Ref: p1710330177642939-slack-C05N140C8H5

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/518232/840772c2-4b05-4337-8b5f-a7235be55020)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
