### ISSUE TITLE
The stats date selector should comply with large font sizes

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20453]
### Expected behavior
The stats date selector should comply with large font sizes

### Actual behavior
When the large font size is selected, the date selector buttons are not displayed and the UTC label is partly displayed.
|default size|large size|
|-|-|
|<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/8e154bd7-f3d5-4da5-82bc-c3d18411ce0a" width=320>|<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/4f6e79ba-4fcf-4581-8d60-031a507bf5db" width=320>|

### Steps to reproduce the behavior
1. Set the largest font size from the device's accessibility settings.
2. Log in to JP.
3. Open "My Site → Stats".
4. Notice that date selector arrows are not displayed on the TRAFFIC tab.

##### Tested on Pixel 8 Pro Emulator, Android 14, JPAndroid 24.4-rc-2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by irfano** [comment]
@oguzkocer, this is an accessibility issue on the Traffic tab that we are shipping with 24.4. I intend to address this in `release/24.4`.
