### ISSUE TITLE
Add retry mechanism for flaky UI tests.

### ISSUE THREAD

**Issue by notandyvee** [wordpress-mobile/WordPress-Android#20461]
### Expected behavior

Flaky tests fail without any retry logic.

### Actual behavior

When a test should work, but flakiness occurs, retry it N number of times before failing.

### Steps to reproduce the behavior

StatsTests are flaky due to a card not appearing sometimes. Reason unknown.

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]

Pixel 7 API 34 Emulator

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
