### ISSUE TITLE
Small Typo Correction in docs/talkback-guidelines.md

### ISSUE THREAD

**Issue by shail-mehta** [wordpress-mobile/WordPress-Android#20489]
Small Typo correction in docs/talkback-guidelines.md in Line no  218

`lifecyle`  ->  `lifecycle`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by shail-mehta** [comment]
PR: https://github.com/wordpress-mobile/WordPress-Android/pull/20490
