### ISSUE TITLE
Today's Stats card should open the day granularity on stats

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20487]
### Expected behavior
Today's Stats card should open the TRAFFIC tab with "By day" granularity or DAYS tab (when the `stats_traffic_tab` flag is off).

### Actual behavior
Today's Stats card is opening the INSIGHTS tab.

[todays stats issue.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/7ab68309-b90e-4a9a-9322-69ff57aa2d2c)

### Steps to reproduce the behavior
1. Log in.
2. Tap the dots button on the "Today's Stats" card.
3. Tap "View stats".

##### Tested on Pixel 9 Pro Emulator, Android 14, JPAndroid 24.4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
👋 @irfano, if this is a Traffic tab issue, let's keep this on the "Stats Traffic tab" board and off the "Stats Bug hunt" board. I think the latter is best for anything Stats that is not related to the Traffic tab, which has its own board. Wdyt?

**Comment by irfano** [comment]
@guarani, it makes sense but this issue was occurring in both cases, whether the traffic tab is enabled or disabled. I have updated the title of the issue.

**Comment by guarani** [comment]
Gotcha, that makes sense. Ok, thanks!
