### ISSUE TITLE
Stats Traffic tab dates should include year

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20488]
### Expected behavior
The date shown on the Stats Traffic tab when "By week" is selected should include the year to avoid confusion about which year is being displayed. (e.g. "Feb 19 - Feb 25, 2024")

Discussed in:
- p1709586750284709/1709585366.152709-slack-C06BR07TJHK
- p1709042259067229/1709042158.468369-slack-C06BR07TJHK

### Actual behavior
The dates on "By week" granularity" are shown without a year (e.g. "Feb 19 - Feb 25")

### Steps to reproduce the behavior
1. Open Stats
2. Go to the Traffic tab
3. Switch "By day" to different periods and notice the dates are displayed without a year.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
