### ISSUE TITLE
Offline: Mode: Implement SyncPublishing Viewmodel

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#20511]
## Description 

Add a ui model to get the current state o publishing in a new viewmodel

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by AjeshRPai** [comment]
This is descoped from the project as it involves major refactoring. For more details check the comment - internal ref pcdRpT-5ID-p2#comment-9638
