### ISSUE TITLE
Expanding items on the stats card causes the page to scroll to the top

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20523]
### Expected behavior
When expanding items on the stats card, the page to shouldn't scroll.

### Actual behavior
Expanding items on the stats card causes the page to scroll to the top.

[stats-scroll-issue.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/1898e8c1-011a-4da4-9d62-b310ec907502)

### Steps to reproduce the behavior
1. Log in.
2. Enable `stats_traffic_tab` from "Me → Debug Settings".
3. Navigate back.
4. Open "My Site →Stats"
5. Scroll down to the Referrers card.
6. Expand an item on the Referrers card.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
