### ISSUE TITLE
Scroll to top when selected bottom navigation tab is tapped

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#20550]
Same as https://github.com/wordpress-mobile/WordPress-Android/issues/15175 but for other tabs (`Notifications`, `My Site`). `Me` tab already handles it.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by RenanLukas** [comment]
FYI @daniloercoli ([discussion](https://github.com/wordpress-mobile/WordPress-Android/pull/20544#pullrequestreview-1965858452))
