### ISSUE TITLE
[Reader] Implement "Tags" feed fetching

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#20588]
To populate the new _Tags_ feed we will need to fetch a few posts from each tags and create a map of tags -> post lists that can be used by the feed.

Some important notes/ideas:
* The fetching function/use-case could receive the list of tags to be fetched
* We will fetch a limited constant number of posts for each of the requested tags
* At first, let's try to use only what the codebase already has in terms of fetching posts from tags (without creating extra Repositories or DB Tables)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
