### ISSUE TITLE
[Reader] Implement horizontal posts list UI component

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#20623]
Depends on https://github.com/wordpress-mobile/WordPress-Android/issues/20587

Implement list UI states: loaded, loading (use implementation of https://github.com/wordpress-mobile/WordPress-Android/issues/20628) and error (with retry). The actual logic will be implemented in a separate ticket.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
