### ISSUE TITLE
Stats Traffic & Subscribers: Reintroduce Traffic tab with an old chart and a new date picker

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20660]
Parent: https://github.com/Automattic/wordpress-mobile/issues/47

### Traffic tab updates

- Consolidate Days/Weeks/Month/Years tabs while keeping the same bar chart and the same behavior
- Add a new date picker that allows to switch between Days/Weeks/Months/Years

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
