### ISSUE TITLE
 Subscribers Line Chart Card

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20687]
Full Scope: https://github.com/Automattic/wordpress-mobile/issues/47
Design: [IqhXWz3Iir7RMb5XH5gGfZ-fi-883%3A4006](https://href.li/?https://www.figma.com/file/IqhXWz3Iir7RMb5XH5gGfZ/?node-id=883%3A4006)

Create a Subscribers Line Chart Card with a default date range and granularity.

### Scope

- Subscribers Line Chart Card

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
