### ISSUE TITLE
Subscribers List Card & Details

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#20689]
Full Scope: https://github.com/Automattic/wordpress-mobile/issues/47
Design: [IqhXWz3Iir7RMb5XH5gGfZ-fi-883%3A4006](https://href.li/?https://www.figma.com/file/IqhXWz3Iir7RMb5XH5gGfZ/?node-id=883%3A4006)

Information about endpoints: p1714120495398839-slack-C06BR07TJHK

Create a Card and Details view that would emulate the same behavior as "Subscribers" card on the web. 

### Scope

**Subscribers List Card**

Merge WordPress.com/Email tabs into a single list. Information about endpoints: p1714120495398839-slack-C06BR07TJHK

**Subscribers List Details**

- Open `People -> Followers` with `Followers` tab selected.
- Remove Email followers tab since it contains the same information [pejTkB-1l5-p2#comment-1315](https://href.li/?https://wp.me/pejTkB-1l5#comment-1315)
- Rename `Followers` to `Subscribers`.
- Update row design (https://www.figma.com/file/IqhXWz3Iir7RMb5XH5gGfZ/%F0%9F%93%8A-Stats?type=design&node-id=1137-3593&mode=design&t=7dK6fJ87QBjGJQ6X-0).
    - Open after selecting Subscribers cell https://wordpress.com/subscribers/{site_id}/{user_id}

![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/e553838d-e73e-4f26-9180-066d8d315783)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
