### ISSUE TITLE
Stats Insights: Remove social (publicize) subscribers

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-Android#20714]
Total Subscribers number on Insights is calculated by adding: wpcom + email + publicize (Jetpack social) subscribers. However, it's been removed from the web.

1. Update Total Subscribers card on Insights not to add publicize numbers
2. Update Total Subscribers -> Details to remove "Social" from Subscribers table

![image](https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/55099f86-4682-4f17-beaf-64098ee727ba)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
