### ISSUE TITLE
[Reader] Post Details not loaded from deep link

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#20754]
### Expected behavior
When tapping a WordPress.com site post link on a different app it should open the Reader feature of the Jetpack app in the Post Details screen, showing its content.

### Actual behavior
Tapping a WordPress.com site post link on a different app the first time opens the Reader in the Post Details with a message saying "The post no longer exists". Going back and tapping the **same** post link again works as expected.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/bd36979a-a96b-4313-8cc6-0fc224ed0707" width="300" />

### Steps to reproduce the behavior
1. On a different app (e.g.: Slack, Chrome, e-mail) that has a link to a post for a site hosted by WP.com
2. Tap a post link you never opened before (the site must match `*.wordpress.com` to open Jetpack)
3. The Jetpack app opens but shows the error message above
4. Go back/close the app
5. On the different app, tap the link again
6. The Jetpack app opens and shows the post content in Reader

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
