### ISSUE TITLE
Sharing: deactivating Jetpack's Shortlinks module doesn't remove wp.me from app

### ISSUE THREAD

**Issue by jeherve** [wordpress-mobile/WordPress-Android#2076]
Steps to reproduce:
1. Activate Jetpack on your site
2. Add that site to your WordPress app
3. Go back to your site, go to Jetpack > Settings, and deactivate the Shortlinks module
4. Back in the app, go to Posts, tap on one of the posts.
5. Tap the Share icon at the bottom of the post
6. The shared URL will be a wp.me URL.

I could reproduce with the latest Beta and with a site running WP Trunk and Jetpack Master.

**Comment by rachelmcr** [comment]
I tested in 4.8-rc-3 and confirmed that the app still uses shortlinks for sharing posts from Jetpack sites, regardless of the Shortlinks module settings.

WPMeShortlinks: https://github.com/wordpress-mobile/WordPress-Android/blob/f64e97cc8cd8502cdb661aab7e233e1f05659477/WordPress/src/main/java/org/wordpress/android/util/WPMeShortlinks.java

Shareable URL from web view: https://github.com/wordpress-mobile/WordPress-Android/blob/2a57008f7db7414a0ead50c7f1895878a906bda5/WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java#L110

**Comment by jeherve** [comment]
Reopening as it is still an issue.
