### ISSUE TITLE
Notifications and reader accessed events tracked in WP app when static posters shown.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#20780]
### Expected behavior
In the WP app, when a user accesses the notifications or reader and the static poster about the Jetpack app is shown, we should not track the "_accessed" event for that screen.

### Actual behavior
In the WP app, when a user accesses the notifications or reader and the static poster about the Jetpack app is shown, we track the "_accessed" event for that screen.

### Steps to reproduce the behavior
- Install the WP app
- Go to the Notifications/Reader tab (note: afaiu, this should be possible only with existing users by backend logic, not for new users for which those tabs are not available in the first place)
- Check the Jetpack static poster is shown
- Check the "notifications_accessed" or "reader_accessed" is triggered.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
