### ISSUE TITLE
[Site selection screen]: Site name and url overflows in RTL orientation

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#20803]
### Actual behaviour 
Site name and url overflows in RTL orientation 

### Steps to reproduce the behavior
1. Go to Me → App language 
2. Set language as Arabic or any other RTL language 

<img width="501" alt="Screenshot 2024-05-13 at 11 22 01 AM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/17463767/d4116e23-e9cd-4a8a-9401-4d3e2a20f7bb">

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
Pixel 6a, Android 13, [`trunk`] branch

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by AjeshRPai** [comment]
cc: @antonis  @jarvislin  Since you both worked on it. Just letting you know
