### ISSUE TITLE
[Reader] Update only tags that changed instead of the whole list in "Your Tags" feed

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#20811]
Currently we're updating the whole "Your Tags" list when the subscribed status of one tag changes. We should only update the subscribed/unsubscribed tag item instead  ([see here](https://github.com/wordpress-mobile/WordPress-Android/pull/20801#issuecomment-2108999829))

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
