### ISSUE TITLE
Enhance in-app reviews logic

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20820]
Currently, we show an in-app review prompt after the second post has been published, and only once. However, we’re overlooking users who manage sites or only read without publishing. 

#### Required changes
* If “LATER” is tapped on the old dialog, do not show the new prompt for 7 days.
* If “NO THANKS” is tapped on the old dialog, do not show the new prompt at all.
* If “RATE NOW” is tapped on the old dialog, reset the counters of the new prompt.
* When the old dialog is shown, reset the counters of the new prompt.
* Keep the old method but focus only on the happiest moments for the new prompt, since we can’t ask “Enjoying the app?” with the new prompt. So, update the new prompt logic with:
  * (Already existing): The second post is published OR
  * “like”, “comment like” and “follow” notifications are tapped 10 times in total.
* Reset the counters and wait for 7 days after the in-app review prompt is shown. (If the user has already rated, the prompt will not show up but only Google can control this behavior.)

Link for internal discussion: pc8eDl-1nq-p2#comment-1088

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
