### ISSUE TITLE
Tags feed position resetting to top on screen rotation.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#20834]
Noticed during a PR review [here](https://github.com/wordpress-mobile/WordPress-Android/pull/20791#pullrequestreview-2049848297)

### Expected behavior
When on the Tags feed screen, if I scroll deep into the feed, I'd like the feed position to be kept on screen rotation.

### Actual behavior
When on the Tags feed screen, if I scroll deep into the feed, and I do a screen rotation, the feed position is reset to the top.

### Steps to reproduce the behavior
- Go to the tags feed (and be sure to have enough tags followed to be able to scroll into the feed)
- Scroll down into the feed
- Rotate the screen 
- Notice the position of the feed is reset to the top

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
