### ISSUE TITLE
[Reader] Track how many people select text content in Post Details

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#20888]
In order to move forward with the content annotating proposal, we need to start tracking how many people select text content in the Reader and how many copy it. Ref: p1716377347554169-slack-C06D0RNJG11

iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/23250

Add the following events:
- [x] `reader_article_text_highlighted`
- [x] `reader_article_text_copied`
- [ ] `reader_comment_text_highlighted`
- [ ] `reader_comment_text_copied`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
