### ISSUE TITLE
[Reader] Show "Create Post" FAB in Reader

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-Android#20908]
As an initial experiment towards the Quick Post in Reader feature we want to enable the existing "create content" FAB (from the My Site page) in the Reader, but only showing "Create Post" actions in the bottom sheet.

| Button | Sheet |
|--------|--------|
| ![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/95a0139b-5a98-465b-b5ba-585a4d105367) | ![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/0d857da0-9eee-4738-914a-7242b0bb709e) | 

### Feature Flag

We want to target just a small amount of users with this initial feature, since we want to gauge its usage to decide on the best implementation for Quick Post in Reader, so this feature will be behind a remote feature flag that we will control the rollout percentage remotely.

The feature flag name is: `reader_floating_button`

### Analytics

To properly measure and analyze the usage and impact of this, we will set some specific events, similar to the existing ones for the FAB and Creation Sheet:
- `reader_create_sheet_shown` after tapping FAB
- `reader_create_sheet_action_tapped` when tapping a sheet item
   - `action`: `create_new_post` and `answer_blogging_prompt`
- `reader_create_sheet_answer_prompt_tapped` when tapping Answer Prompt
- `reader_create_sheet_prompt_help_tapped`  when tapping the “?” icon in the Prompts item
- `reader_create_fab_shown` when the fab is shown in the Reader page
- `my_site_create_fab_shown` when the fab is shown in the My Site page

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
