### ISSUE TITLE
Media: 404 images show as empty space in the list and detail.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#210]
To reproduce.
On a self hosted blog, add some media attachments to your blog. 
Login to the server and manually move / delete the image files. 
Go to the app and view the media feature.
The media items with the missing images will show a placeholder in the list but if you tap the list it will disappear. The detail always shows empty space where the image should be. 
A 404 image might be nice.
Maybe a bit of an edgecase but I'm thinking of blogs with missing media due to bad migrations or broken gallery plugins. 

2.5 beta 4(?) / Nexus 7

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
