### ISSUE TITLE
Unable to change date of a published post

### ISSUE THREAD

**Issue by alinclamba** [wordpress-mobile/WordPress-Android#21001]
### Expected behavior

If I want to change the date of a published post, I expect to see the new date, but it's not happening.

### Actual behavior

Edit a published post, and before updating/publishing, I change the publish date but the date isn't updating. 

### Steps to reproduce the behavior

1. Open a previously published post and make some changes
2. Before saving the changes, choose change the publish date and then update the post.
3. See that the publish date didn't change. 

This happens on mobile app only. 

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]

I tested on my Google Pixel phone with Android, but it was also reported 8323256-zd-a8c and [here](https://link.reviewbot.io/notification?action=share&review=b5dDFzdaAzqC2Pdqno08).

Issue initially opened https://github.com/Automattic/jetpack/issues/37851

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ricklabsdotn8** [comment]
8394609-zen

**Comment by ricklabsdotn8** [comment]
8448092-zen

**Comment by dcalhoun** [comment]
It appears this regression was introduced with https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3003, where we now conditionally send the local post date to the server. That would mean the regression is present from the 24.9 release onwards. 

I will explore if there is an alternative solution that addresses this regression while also preserving a fix for https://github.com/wordpress-mobile/WordPress-Android/issues/17375.
