### ISSUE TITLE
[Android 14] Foreground service type

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21039]
In order to update to Android 14, we need to use a [foreground service type](https://developer.android.com/about/versions/14/changes/fgs-types-required) with foreground-facing services.

Some work on this [has already been done](https://github.com/wordpress-mobile/WordPress-Android/pull/21033) to set the foreground type for [UploadService and MediaDeleteService](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/AndroidManifest.xml#L833-L842), but we need to include `SiteCreationService` and [LoginWpcomService](https://href.li/?https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/blob/trunk/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginWpcomService.java).

~~Also, on Upside Down Cake and above we need to call `ServiceCompat.startService` with a [foreground service type](https://developer.android.com/about/versions/14/changes/fgs-types-required#include-fgs-type-runtime). From a quick glance at our code, we may only need to be concerned about that for `UploadService` (if at all).~~

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by nbradbury** [comment]
Closed via #21047
