### ISSUE TITLE
[Android 14] Grant Access to Select Photos and Videos

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21042]
It looks like quite a bit of work on this [has already been done](https://github.com/wordpress-mobile/WordPress-Android/pull/19109), but when I granted partial access when adding to the media library, it acted like I hadn't granted access at all.

![media](https://github.com/wordpress-mobile/WordPress-Android/assets/3903757/931ee0b3-d8f6-4fca-b0fc-055a31c074f8)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by nbradbury** [comment]
False alarm with this one, it appears to be working as expected after all.
