### ISSUE TITLE
Address `RestrictedApi` lint warning in `WPMainNavigationView`

### ISSUE THREAD

**Issue by wzieba** [wordpress-mobile/WordPress-Android#21079]
### Expected behavior
`WPMainNavigationView` doesn't use internal-only classes from Material library.

### Actual behavior
`WPMainNavigationView` uses `BottomNavigationMenuView` and `BottomNavigationItemView` classes, which are restricted to library group only (internal in a sense).

https://github.com/material-components/material-components-android/blob/e1a103e2e11984baa675b06d9b52290f88f4478e/lib/java/com/google/android/material/bottomnavigation/BottomNavigationMenuView.java#L40-L42

### Steps to reproduce the behavior
Remove lint rule suppression in `WPMainNavigationView` and run `lintWordpressVanillaRelease` task

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
