### ISSUE TITLE
Feedback Form: Add attachments

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21105]
To match iOS, we need to enable users to add attachments to the feedback form. Note that iOS only enables selecting from photos, so arbitrary files aren't supported.

iOS screens below.

![iOS-Attach](https://github.com/user-attachments/assets/d15c7fa3-ce8f-4c37-9c5d-5fccde092578)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by nbradbury** [comment]
Closed via #21115
