### ISSUE TITLE
In-app review requested too often

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21100]
We've had several users [complain](https://appfigures.com/reviews/334298318386Lz4BDXmbf05Xc0EHoswNxdA?lang=en) that in-app reviews are requested far too often, even when a review has already been given.

![Screenshot 2024-07-30 at 4 07 04 PM](https://github.com/user-attachments/assets/751aa6a4-d10a-4d7d-8a9e-441859ad3666)

I'm confused by this, since it looks like our Android apps use Google's [in app-reviews library](https://developer.android.com/guide/playcore/in-app-review/kotlin-java), and that library is supposed to make sure reviews aren't requested too often.

We should research and resolve what could cause this, since it's resulting in poor reviews.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
