### ISSUE TITLE
Page Options: Add the option to set the parent of a Page

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-Android#2110]
Currently in neither the iOS or Android app are you able to set the parent attribute of a Page.
This is a feature request to have that added in a future version.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by aforcier** [comment]
This issue was auto closed during editor issue migration - re-opening as it's a post settings issue.

**Comment by rachelmcr** [comment]
This was recently requested again by a user in an app review (3 stars):

> Good App but i need to be able to choose a page parent.

**Comment by hoverduck** [comment]
Linking the same issue on iOS - https://github.com/wordpress-mobile/WordPress-iOS/issues/2928

**Comment by rachelmcr** [comment]
This was added in https://github.com/wordpress-mobile/WordPress-Android/pull/8180.
