### ISSUE TITLE
Bar chart issue on "Years" timeframe with few data

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2117]
<del>Rotating the device a couple times while years data is loading ends up with a bar chart with only one year visible.</del>

The ugly chart appears when there isn't enough data to fill the whole viewport/space reserved to the graph.

![device-2014-12-17-134336](https://cloud.githubusercontent.com/assets/3903757/5476763/240d6f8c-85f3-11e4-8c8d-ba2ad7ed2547.png)

Try to debug this on blogs created in the last year.

**Comment by tonyr59h** [comment]
Found a consistent reproduction of this issue, works on all filters (days/weeks/months/years). Seems to behave based on whether or not content exists at a date prior to the chosen column. You can 'walk' your way down the stats timeline but never back up.

**Comment by daniloercoli** [comment]
@tonyr59h The issue you're reporting has been fixed in #2142 (PR is currently awaiting review). I kept this ticket open because I want to test Stats on freshly created sites a little bit more. Stats with only one bar could end up rendered as the picture above.

**Comment by daniloercoli** [comment]
The ugly chart appears when there isn't enough data to fill the whole viewport/space reserved to the graph.
![screen shot 2015-02-25 at 10 25 20](https://cloud.githubusercontent.com/assets/518232/6376005/380846ec-bd1b-11e4-9b4d-70d02e258dac.png)
