### ISSUE TITLE
Publishing a post with empty audio or video blocks is allowed without any warning

### ISSUE THREAD

**Issue by RippleTester** [wordpress-mobile/WordPress-Android#21176]
### Expected behavior
The system should prevent publishing or provide a warning if the post contains empty audio or video blocks.

### Actual behavior
A post with empty audio or video blocks can be published without any content.

### Steps to reproduce the behavior
Click the 'Create a post or page' icon
Click the 'Blog post' button
Click the 'Audio'/'Video' icon to add an empty block
Click the 'PUBLISH' button

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
Galaxy S21 5G, Android 12, Jetpack 25.2.1 (1444)/WordPress 25.2.1 (1444)

https://github.com/user-attachments/assets/6fe62701-c5b0-410c-81c8-4950ef0fa808

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by asdkfjsd** [comment]
hello, i am a new contirbutor and willing to help,could you assign it to me?

**Comment by asdkfjsd** [comment]
hello, i am a new contirbutor and willing to help, can i work on this issue?

**Comment by dcalhoun** [comment]
Personally, I do not consider this is a legitimate bug. I think the outcome—publishing empty media blocks—is expected. Also, this same flow is possible in the web editor. I suggest we close this issue as "won't fix." 

WDYT @nbradbury?

**Comment by nbradbury** [comment]
@dcalhoun If this is how the web editor works, then I agree with you. I'll close this.
