### ISSUE TITLE
Clicking the 'Undo' icon clears all text input, and the 'Redo' icon recovers the text but positions the cursor incorrectly

### ISSUE THREAD

**Issue by ScenarioKG** [wordpress-mobile/WordPress-Android#21173]
### Expected behavior
The 'Undo' icon should remove the last action or text input, allowing you to correct specific mistakes (e.g., changing 'examile' back to 'example') rather than removing all the text.
The 'Redo' icon should recover the undone text input while keeping the cursor position at the end of the text.

### Actual behavior
The 'Undo' icon removes all the input text.
The 'Redo' icon recovers the input but places the cursor position incorrectly, not at the end.

### Steps to reproduce the behavior
Click the 'Create a post or page' icon
Click the 'Blog post' button
Type something into the body
Click the 'Undo' icon
Click the 'Redo' icon

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
Galaxy A14 5G, Android 13, JPAndroid / WPAndroid 25.2.1 (1444)

https://github.com/user-attachments/assets/c007b7ff-5169-4fa1-b21f-ad3fea8e1907

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by nbradbury** [comment]
I believe this is working as expected. Rather than clearing **all** the text, Undo clears the last entered paragraph. If you type three paragraphs, clearing them all requires tapping Undo three times.
