### ISSUE TITLE
Update bell & reader icons

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21187]
We have a few outdated icons in the main app navigation. We should replace these 2x with this [reader icon](https://www.figma.com/design/eqlepL7MHifK8Bgr1OWqLr/Dotcom-Design-Library?node-id=17463-17118&t=vejjQTaBDq8w2KQM-4) and rotate the [bell icon](https://www.figma.com/design/eqlepL7MHifK8Bgr1OWqLr/Dotcom-Design-Library?node-id=17466-15671&t=vejjQTaBDq8w2KQM-4) to align it vertically.

![image](https://github.com/user-attachments/assets/f59a019d-0baf-4434-ba32-89ae6511d5af)
![image (1)](https://github.com/user-attachments/assets/80a3fa4f-28f7-4ab4-bfef-d1a1113c7103)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
