### ISSUE TITLE
Lack of detailed change summaries in version conflict dialog

### ISSUE THREAD

**Issue by ScenarioKG** [wordpress-mobile/WordPress-Android#21192]
### Expected behavior
Change summaries should support the version choice.

### Actual behavior
Only timestamps are shown to differentiate versions.

### Steps to reproduce the behavior
1. Click the 'Posts'
2. Click the post with 'You've made unsaved changes to this post'
3. Observe the conflict resolution dialog.

##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
Galaxy S21 5G, Android 12, Jetpack 25.2.1 (1444)/WordPress 25.2.1 (1444)

https://github.com/user-attachments/assets/db17e20d-7091-4705-b946-d8cb1a083973

```[tasklist]
### Tasks
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by nbradbury** [comment]
This is a valid point, but I'd consider it working as expected.
