### ISSUE TITLE
Remove public data tests

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21221]
As discussed on [Slack](p1725898221295419-slack-C011BKNU1V5) and [elsewhere](https://github.com/wordpress-mobile/WordPress-Android/pull/17459#issuecomment-1316599260), both `WordPressPublicDataTest` and `JetpackPublicDataTest` cause local tests to fail. This has caused some confusion both with our developers and outside contributors.

These tests were added as part of the Jetpack migration project and can be removed.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
