### ISSUE TITLE
Improve wording of no connection message

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21283]
We use the strings "No network available" (title) and "There is no network available" (message) together in several places when we detect there's no network connection. As mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/21275#discussion_r1790413203), this is redundant and unhelpful. We should use better wording, or simply use only the title string and no message.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
