### ISSUE TITLE
Coil ImageLoader singleton

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21285]
According to [Coil's documentation](https://coil-kt.github.io/coil/image_loaders/#singleton-vs-dependency-injection):

> Coil performs best when you have a single ImageLoader that's shared throughout your app. This is because each ImageLoader has its own set of resources.

We should update the app to follow that advice.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
