### ISSUE TITLE
Improve self-hosted user list for screenreaders

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21284]
As mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/21275#discussion_r1790401431), the new self-hosted user list could use some accessibility improvements:

> From my perspective, the screen reader experience for this new list could be improved. E.g., swiping up/down moves between individual user items, but merely announces "list" repeatedly, which provides little context.

> We might improve the experience by having the top level list declare the total number of items ("list, 25 of 35 users"), individual items could announce some high-level information ("dcalhoun, administrator"), etc.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
