### ISSUE TITLE
Jetpack promo headline spacing

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21294]
The "JetpackStaticPoster" screen shown when tapping Reader, Notifications, or stats in the WordPress app has excessive spacing in the headline.

![Screenshot_20241011-115017](https://github.com/user-attachments/assets/da431688-ed08-4adc-bb8a-63851e4bb085)
![Screenshot_20241011-115026](https://github.com/user-attachments/assets/456d11cb-c669-42c2-8efd-877f36ee1a4d)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
