### ISSUE TITLE
Convert Jetpack Migration to Material3

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21317]
Once #21314 and #21316 are completed, the next step can be converting the Jetpack migration screens to Material3.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
