### ISSUE TITLE
Rename AppTheme to AppThemeM2

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21322]
As mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/21316#issuecomment-2427365418), it would make sense to rename `AppTheme` to `AppThemeM2` to make it clear it's Material2, and for consistency with `AppThemeM3`.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
