### ISSUE TITLE
Feedback form analytics

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21348]
The only event we're tracking in the feedback form is when the screen is opened. We should also track when the feedback form is submitted or cancelled.

Note that on iOS these are the two events and WPAndroid should match:

* _app_reviews_feedback_screen_opened
* _app_reviews_feedback_sent
* _app_reviews_feedback_screen_canceled

Feedback was originally part of the in-app review which is why these events are named this way.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
