### ISSUE TITLE
Warn when accessing feedback form from an Automattic email address

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21354]
Submitting the feedback form from an account with an Automattic email address will always fail. We should show a warning in this situation, similar to the iOS warning when accessing the support chat (and we should also show the warning when accessing support chat).

![IMG_7E25E83CDCDB-1](https://github.com/user-attachments/assets/9a4d122c-a3fe-435c-b1e4-50ba15a5ea71)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
