### ISSUE TITLE
In the "site settings" option, after changing the language selection, the practical language of the interface will not change.

### ISSUE THREAD

**Issue by HMJ0628** [wordpress-mobile/WordPress-Android#21362]
### Expected behavior
After entering the site setting, when we select a language, we expect the language setting of the page to change to the language mode we set.

### Actual behavior
When we choose another language, the language setting of the page is still Chinese mode.

### Steps to reproduce the behavior
1. go to "setting"
2. click on the language selection
3. select a language
##### Tested on [device], Android [version], JPAndroid / WPAndroid [version]
vivo S19 5G, Android 14, Jetpack 25.2.1 (1444)/WordPress 25.2.1 (1444)
https://github.com/user-attachments/assets/7c939d3b-43eb-43bd-8bf9-3cd9d36008f7

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
