### ISSUE TITLE
Stats: Bar graph colors do not differentiate between views and visitors in dark mode

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#21366]
### Expected behavior
- To be able to tell between views and visitors in dark mode

### Actual behavior
- In dark mode the bars are a solid green color

| Light | Dark |
| - | - |
| ![Android-Light](https://github.com/user-attachments/assets/c2cdbf0a-588e-4ccb-ab5b-06fa82fe07ce) | ![Android-Dark](https://github.com/user-attachments/assets/1834f0d0-9416-40ce-b33e-b76ad43b727b) |

### Steps to reproduce the behavior

In the Jetpack app go to Stats and toggle light / dark modes.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by twstokes** [comment]
Also notice that the graphs aren't the same width between dark / light mode.
