### ISSUE TITLE
Media: Tapping back from an item detail accessed via search does not take you back to search.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#214]
On the media feature:
Access the search feature via the actionbar menu.
Enter a search term to view a subset of the media items.
Tap on of the items to view its detail
Tap the back button. 
Instead of viewing the search results you're back on the main list. 

2.5 beta 4
Nexus 4 / 4.3

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by aforcier** [comment]
Re-opening this and closing the editor repo issue as this is a Media screen issue. @rachelmcr confirms it's still an issue as of `alpha-4`.
