### ISSUE TITLE
Use our uCrop fork

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21407]
[This dependabot PR](https://github.com/wordpress-mobile/WordPress-Android/pull/21405) updates the uCrop dependancy to the latest version, but as mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/21405#issuecomment-2454306927) we should update to our own fork: https://github.com/Automattic/uCrop

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by nbradbury** [comment]
This was addressed as part of #21312.
