### ISSUE TITLE
Remove unnecessary features in development

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21412]
The following "Features in development" default to True, so we should remove them from the app:

* GlobalStyleSupportFeatureConfig
* SiteIntentQuestionFeatureConfig

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by nbradbury** [comment]
Reopening since we removed `GlobalStyleSupportFeatureConfig` but not `SiteIntentQuestionFeatureConfig`.
