### ISSUE TITLE
Allow deleting one's own comments on another person's website

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-Android#21423]
We received a feature request from a user (8973860-zd-a8c) to allow deleting/trashing their own comment on someone else's website. 

In a web browser one can "trash" their own comment by clicking _Edit_ → _Trash_, but this ability is absent in the mobile app. Additionally, trashed comments can be only be permanently deleted by the website's administrators. 

Related:
* 8973860-zd-a8c
* https://github.com/wordpress-mobile/WordPress-iOS/issues/23770

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jkmassel** [comment]
I'm not sure this will ever be possible – once a comment goes on someone else's site, it belongs them, not to you.

It'd be difficult to prove you're the author of said comment to allow deletion.

This _might_ be feasible for WP.com, but probably never for .org sites

**Comment by dcalhoun** [comment]
As shared in https://github.com/wordpress-mobile/WordPress-iOS/issues/23770#issuecomment-2486819065, I think I was confused when believing this was possible on the web. It doesn't appear to be the case. 

Closing this for now. We can re-open later, if needed.
