### ISSUE TITLE
My Site Personalization accessibility

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21444]
As noted [here](https://github.com/wordpress-mobile/WordPress-Android/pull/21441#pullrequestreview-2427549531):

> I will note that the toggle elements have no description, so navigating controls[1](https://github.com/wordpress-mobile/WordPress-Android/pull/21441#user-content-fn-1-36596cf3cfe931b405a3abf149093532) with a screen reader is near impossible. I suggest we add descriptions that provide context when moving selection to each element—e.g., "Draft posts, your recent draft posts, on switch, double-tap to toggle." We might either add a description to the toggle or grouping the entire row into a single accessible group.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
