### ISSUE TITLE
Stats not showing all years

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21448]
When viewing stats for a page that has received views for several years, the most recent years are missing. The user has to scroll down and select "View more" to see all the years.

To reproduce:

* Select a site that has received traffic for a number of years
* Go to Stats 
* Change the filter to Years
* Under Posts & Pages choose a popular post (such as the home page)
* Note that the most recent years are missing

![stats](https://github.com/user-attachments/assets/039f30e0-22e0-4b63-8734-0054b6388a4e)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
