### ISSUE TITLE
FAB is out of place on a landscape tablet

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2144]
I believe it should be in the right corner of the detail view in this case. Probably a lot of work because we'd need to do something about the toolbar in the detail view:

![device-2015-01-02-145752](https://cloud.githubusercontent.com/assets/789137/5600498/e742f370-928f-11e4-8e81-364ad7403c61.png)

**Comment by maxme** [comment]
Not sure about having the FAB on the detail view, but we should kill that bottom toolbar in the detail view (should come with the new editor).

**Comment by roundhill** [comment]
Hmm, you're right, I see the FAB in the list in the Gmail app on my tablet. I'll close this for now.
