### ISSUE TITLE
Clicking "View more" link under  "Avg views per day" does nothing

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21451]
Tapping this link in stats does nothing:

![link](https://github.com/user-attachments/assets/c3a791cb-105e-4af1-af9d-53d6282cd518)

I tracked that down to [this line of code](https://github.com/wordpress-mobile/WordPress-Android/blob/0a324b6e200e402f9f8a933fa67cffc7c2459277/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt#L243), which explicitly states we do nothing. We should look into whether there is an action we can perform, and if not, remove the link.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
