### ISSUE TITLE
Missing social icons

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#21490]
Our [PublicizeServiceIcon](https://github.com/wordpress-mobile/WordPress-Android/blob/09d8ee094f97fa3affcc87a7f7ae0995c9b9c6cd/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeServiceIcon.kt#L15) class is missing icons for a few services. We should correct this.

![blue](https://github.com/user-attachments/assets/5c29f650-43c5-4cf8-b496-6833e09a5262)

[Related iOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/23860)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
