### ISSUE TITLE
Notifications: Align to 72dp ActionBar Title

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2154]
It's close, needs to be adjusted by a few dps:

![screen shot 2015-01-07 at 8 47 56 am](https://cloud.githubusercontent.com/assets/789137/5649366/07a7f440-964a-11e4-95c1-37325362d6f9.png)

**Comment by roundhill** [comment]
@drw158 To get this lined up, I'll need to reduce the avatar size... currently it is 48dp and the Material guidelines are using 40dp for a very similar layout: http://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing. Thoughts?

cc @nbradbury, what do you think of reducing `avatar_sz_medium` to 40dp? It would also help some of the Reader elements align better (with some additional spacing tweaks as well).

**Comment by nbradbury** [comment]
Making the medium avatar size 40dp is a pretty big reduction, and it makes it only 8dp larger than the small avatar. But I say give it a try :)

**Comment by drw158** [comment]
Yea, I'd say it's worth a try and see what it feels like. For this kind of stuff I usually feel ok breaking the guidelines.

**Comment by roundhill** [comment]
It looked bad at 40dp :) Too small.

@drw158 i've simply moved the text over to the left a few dps: how's this?
![device-2015-01-09-154250](https://cloud.githubusercontent.com/assets/789137/5689233/6eefe2e8-9816-11e4-82ae-7df0751be243.png)

**Comment by drw158** [comment]
Hm, yea there's not enough space now. Way too close...not sure what to do about that. I might look deeper into the guidelines tomorrow.

**Comment by roundhill** [comment]
I think we'll just leave this as-is for now.
