### ISSUE TITLE
Users report landing screen is always "Posts" since 3.5

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2161]
The app should reopen the last active activity. I tested a bit and I can't reproduce the problem (last active activity is reoppened).

**Comment by roundhill** [comment]
Sometimes I've killed the app for testing or whatever, and I end up back at the Reader even if I was somewhere else previously.

**Comment by nbradbury** [comment]
Note that PostsActivity [is the default](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/WPLaunchActivity.java#L35) when the previously active activity is unknown.

**Comment by nbradbury** [comment]
I spent some time looking into this and didn't see what could cause it. I wondered whether the problem was related to switching from `editor.commit()` to `editor.apply()` when saving prefs, but that change was made [back in August](https://github.com/wordpress-mobile/WordPress-Android/commit/10214ce40c4098702ab02904637c4d32fa7bb43a) so users would've reported problems before now.

**Comment by maxme** [comment]
If it comes from the switch from `editor.commit()` to `editor.apply()`, users should not go to Posts but to the previous "saved" state (from user' feedbacks, it seems they tend to visit the Stats page a lot, so they would probably land in the Stats page too).

I double checked we where saving the enumeration `.name()` and restoring it from `valueOf()` - unfortunately I've no better clue :(

**Comment by nbradbury** [comment]
Are we still getting reports of this? I'm wondering if it was a one-time thing since we did [change the startup process](https://github.com/wordpress-mobile/WordPress-Android/commit/3d6437d17aaeac893b7de44b850c7783c12d0f7c) in 3.5.

**Comment by maxme** [comment]
Nothing new, can't repro, moving the milestone to 3.9 - we'll close this for 3.9 if we still haven't new informations.

**Comment by Toof** [comment]
Samsung Galaxy S5
WordPress app 3.9-rc-2
Steps to reproduce:
1. Open WP App
2. Tap Hamburger
3. Tap Stats
4. Press "Back" button on bottom right of phone (not touchscreen)
5. Tap WP App icon
6. See Posts Screen
(screencast = https://n00blar.files.wordpress.com/2015/04/wpid-4-3-15-6-57-am.mp4 ) 

Note that on Step 4, from my home screen, if I view all apps, the WordPress app is still running and still displays the Stats page in the preview:

Note when it does NOT occur:
- When Step 4 is performed using the center "Home" button on the GS5
- When User goes from WP/Stats to the stacked "all apps" windows, and taps back into WP/Stats

This DOES still occur if:
- Step 5 is replaced with: Access WP/Stats from the "all apps" window, which _actually displays the stats screen_
(screencast = https://n00blar.files.wordpress.com/2015/04/wpid-4-3-15-6-58-am.mp4 )

It looks like this behavior is tied to using the 'Back' button to navigate away from the Stats page.

**Comment by maxme** [comment]
Won't happen with the new design.

**Comment by maxme** [comment]
That issue was a Launcher icon problem only on specific launchers. Fixed via #2824
