### ISSUE TITLE
Notifications: Fall back to using URL when loading blog preview

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2169]
Some wp.com users don't have a primary site, so the api won't provide a site id. We should fall back to using the Url if it was provided, and open it in the in-app browser.

**Comment by daniloercoli** [comment]
We could have the same problem in Stats, since we're opening the Reader blog preview in "Followers" and "Comments" section of Stats. I will send you a hug if you can fix this on Stats too, otherwise ping me when you're going to submit the PR, and I can replicate the checks in Stats.

**Comment by roundhill** [comment]
@daniloercoli I think we'll need to have the logic in both stats and notifications, because the blog preview activity has to do an API to load a site by its Url, and it doesn't fall back to loading a web view. So there's no delay we should just load the web view activity when there is no site id available.

**Comment by daniloercoli** [comment]
Ok, I will take care of Stats then. I'm not even sure we've this problem there.

**Comment by daniloercoli** [comment]
FYI - We should not have this issue in Stats, since we're always using the URL of the primary blog (if available) and not the siteID :
``
ReaderActivityLauncher.showReaderBlogPreview(
   context,
   0L,
   currentRowData.getURL()
);
``
