### ISSUE TITLE
QuickPost doesnt' like PIN Lock

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#217]
Enable the PIN lock feature, and try to use the QuickPicture/QuickVideo feature. When returning from the camera app the PIN Lock is shown on the screen. Even if you set the extended timeout on PIN Lock. 
This is because multiple activities are launched when the user hits the QuickPicture Item in the sidebar:
Sidebar -> EditPostActivity -> Camera Activity.

It's not a huge problem since QP is only used by a small % of users.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
