### ISSUE TITLE
Stats: Should we fall back to using URL when loading blog preview of private blogs, or HTTP protected blogs

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2170]
Some wp.com users have a primary site marked as private, so the Reader API will receive a 403 as response code (ex: https://public-api.wordpress.com/rest/v1/sites/kevinjmorrisuk.wordpress.com ) and the UI shows a simple error message "Unable to show this blog" in a Toast.

![screen shot 2015-01-14 at 00 26 55](https://cloud.githubusercontent.com/assets/518232/5731470/0f29d898-9b84-11e4-9d4c-bdb56a283d17.png)

I don't have much control over the Reader Blog Preview page from Stats, so it's hard for me to do something if an error occurs in the Reader. Should we modify the Blog preview page, and open the blog URL in the in-app browser when something is wrong with the REST API call?

I bet we have the same issue on self-hosted blog that are HTTP password protected.

/cc @nbradbury @roundhill

**Comment by daniloercoli** [comment]
I think this is another case that should be fixed server side. A new field that indicates if the blog is marked as private. In that case we call the in-app web browser, otherwise the Reader blog preview screen will be called.

**Comment by nbradbury** [comment]
Just an FYI: blog preview will work with a private blog if the current user is also a user of the blog.
