### ISSUE TITLE
On generic login error, add a button to easily share server response or contact support

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2179]
When a user hit the login error "We can't log you in", we should give him some options to read and share the server response and contact support if the server response doesn't help.

This error should only happen on self hosted sites, most of the time it's due to a server misconfiguration.

We should also consider some common self hosted errors like a 403 on xmlrpc.php (we could redirect to the FAQ)

**Comment by nbradbury** [comment]
How about making "Contact us" the first button, since the user is unlikely to know what "Application Log" means when they reach this screen?

![screenshot-2015-01-16_14 11 42 329](https://cloud.githubusercontent.com/assets/3903757/5782588/77f672fc-9d8a-11e4-8d7c-7813e5bf8f95.png)
