### ISSUE TITLE
Poor error message when re-publishing a deleted post

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#2183]
If there are one or more posts with local changes and any remote (non-local draft) post is deleted, the local changes of all posts are discarded without warning.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by aforcier** [comment]
Re-opening this issue as it's more of a post list issue than an editor issue.

Relevant comment by @maxme on https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/33:

The problem is a bit different now and local changes are not lost:

* Edit a published post with wpandroid, don't publish the changes.
* Go back to the Post list, you should see a "Local changes" notice on the post you just edited
* Move this post to trash on the Web
* Refresh the post list in wpandroid: the post and local changes are still there
* Publish the local changes and notice the post move from trash to published (IMO, that's the correct behavior)

A problem appears when you delete the post completely:

* Edit a published post with wpandroid, don't publish the changes.
* Go back to the Post list, you should see a "Local changes" notice on the post you just edited
* **Delete the post completely**
* Refresh the post list in wpandroid: the post and local changes are still there
* Publish the local changes and get an error: "Invalid post ID [404]" which seems normal. Error message comes from the XMLRPC response, not ideal.

I think it's an acceptable behavior if we had a better message.
