### ISSUE TITLE
app causing spike in usage on self hosted site - host emailed and asked me not to use 

### ISSUE THREAD

**Issue by kimstuart** [wordpress-mobile/WordPress-Android#2184]
First, this is my first time posting here so if it's a mess, I apologize in advance. 

I love the app, the Android version is super great and makes my life easier almost every day!  But...

The latest update of the app seems to be causing me a ton of problems with posting to my self hosted sites (and the one prior to the November update as well but it cleared up with that update).  

I use the app to post via Share from articles I read on the web on my phone - HTC One - so the posts are normally a URL and title, perhaps a line or two of commentary.  No images, no vide, none of that. 

I got an email from my host, asking me to please stop using it - 

At exactly 11:50am Eastern you started using the App.   At the same time the boxes utilization when through the roof.    This has happened before.

Each time the box implodes I know exactly what is going on...   The app causes so much load on the server it brings it to its knees.

I don't know why, but the app does something via its connection that makes the server use massive amounts of resources.    Each time this happens I see the app in the logs:

```
98.255.188.228 - - [12/Jan/2015:11:48:05 -0500] "POST /xmlrpc.php HTTP/1.1" 200 2450 "-" "wp-android/3.5 (Android 4.4.2; en_US; HTC HTC One_M8/cingular_us)"
98.255.188.228 - - [12/Jan/2015:11:48:06 -0500] "POST /xmlrpc.php HTTP/1.1" 200 934 "-" "wp-android/3.5 (Android 4.4.2; en_US; HTC HTC One_M8/cingular_us)"
98.255.188.228 - - [12/Jan/2015:11:48:06 -0500] "POST /xmlrpc.php HTTP/1.1" 200 1453 "-" "wp-android/3.5 (Android 4.4.2; en_US; HTC HTC One_M8/cingular_us)"
98.255.188.228 - - [12/Jan/2015:11:48:09 -0500] "POST /xmlrpc.php HTTP/1.1" 200 42345 "-" "wp-android/3.5 (Android 4.4.2; en_US; HTC HTC One_M8/cingular_us)"
98.255.188.228 - - [12/Jan/2015:11:48:10 -0500] "POST /xmlrpc.php HTTP/1.1" 200
```

Note the time...   I will send you a graph that matches exactly to your first hit.

(I didn't post the graph but can if needed) - and George Stephanis suggested that I email the following to myself from the app and attach it as well -- 
```
WordPress Android version: 3.5
Android device name: HTC One_M8

01 - resetting suggestion table
02 - WordPress.onCreate: begin
03 - WordPress.onCreate:      2004 ms, PostsActivity.onCreate
04 - WordPress.onCreate: end, 2004 ms
05 - instantiate XMLRPCClient using sFactory: class org.xmlrpc.android.XMLRPCFactoryDefault
06 - instantiate OAuth using sFactory: class org.wordpress.android.networking.OAuthAuthenticatorFactoryDefault
07 - instantiate RestClient using sFactory: class org.wordpress.android.networking.RestClientFactoryDefault
08 - instantiate XMLRPCClient using sFactory: class org.xmlrpc.android.XMLRPCFactoryDefault
09 - instantiate XMLRPCClient using sFactory: class org.xmlrpc.android.XMLRPCFactoryDefault
10 - instantiate XMLRPCClient using sFactory: class org.xmlrpc.android.XMLRPCFactoryDefault
```

**Comment by maxme** [comment]
All the `POST /xmlrpc.php` requests are the way the App communicate with your WordPress instance. It's used to get informations about your blog (blog options), refresh posts, pages, comments, etc. And it's also used to publish new posts.

When you start the app after a while, the app will run ~5 requests, but these requests are lightweight and your server should not use massive resources. 

Can you send us the full http log? If you see an abnormal number of requests, there is probably an issue in the App. If not, that could be an issue on your WordPress instance (maybe a plugin that makes your server use a lot of ressource each time the xmlrpc endpoint is accessed. It could also be a problem with your DB).

**Comment by kimstuart** [comment]
Yes, my host has suggested that we do a test tomorrow so he can see in real time what is happening and we can send the logs to you as well. 


Sent from my HTC

----- Reply message -----

**Comment by kimstuart** [comment]
Maxime - 
We ran a test of the app this morning while watching the server - here is what I got from my host - 

Here is the issue:
 
1.        You use the App
2.        As you are using the app the site is bombarded with hits by bots.   Google bot, twitterbox, stumbleupon, facebook, etc etc - ping backs from all over the place, etc etc.
 
So it is not the use of the App in and of itself.  It is what happens with all of the activity that happens while you are using the App that causes bots from all over the internet to pound your pages.
 
Bringing the server to its knees…  When you stop using the app…  everything goes back to normal.
 
Turn off the functionality to ping the world when changes are made or at least reduce the worldwide pings or do a small set of items that cause the pings…   
 
 
Logs of the activity:
199.59.148.211 - - [16/Jan/2015:14:32:48 -0500] "GET /atlasrewards/apple-pay-uk-release-date-could-be-spring-2015-it-pro/ HTTP/1.1" 301 - "-" "Twitterbot/1.0"
199.59.148.210 - - [16/Jan/2015:14:32:48 -0500] "GET /atlasrewards/apple-pay-uk-release-date-could-be-spring-2015-it-pro/ HTTP/1.1" 301 - "-" "Twitterbot/1.0"
5.39.64.74 - - [16/Jan/2015:14:32:55 -0500] "GET /robots.txt HTTP/1.1" 200 35 "-" "Mozilla/5.0 (compatible; Kraken/0.1; http://linkfluence.net/ <http://linkfluence.net/>; bot@linkfluence.net <mailto:bot@linkfluence.net>)"
54.90.171.17 - - [16/Jan/2015:14:33:20 -0500] "GET /atlasrewards/wp-content/uploads/sites/10/2014/07/AtlasDivilogo-300x43.png HTTP/1.1" 200 9149 "-" "Pinterest/0.1 +http://pinterest.com/ <http://pinterest.com/>"
54.65.51.115 - - [16/Jan/2015:14:32:54 -0500] "GET /atlasrewards/apple-pay-uk-release-date-could-be-spring-2015-it-pro/ HTTP/1.1" 301 - "-" "Crowsnest/0.5 (+http://www.crowsnest.tv/ <http://www.crowsnest.tv/>)"
199.16.156.124 - - [16/Jan/2015:14:32:56 -0500] "GET /robots.txt HTTP/1.1" 200 35 "-" "Twitterbot/1.0"
98.255.188.228 - - [16/Jan/2015:14:32:54 -0500] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 47 "http://atlasrewards.net/wp-admin/admin.php?page=wpseo_social&key=07741294c727af050a62767149e993a0&apps=%7B%220%22%3A%7B%22app_id%22%3A%22770990362924479%22%2C%22display_name%22%3A%22Atlas+Rewards+Blog%22%7D%2C%221%22%3A%7B%22app_id%22%3A%22139730029520125%22%2C%22display_name%22%3A%22Domino+Research+Blog%22%7D%7D <http://atlasrewards.net/wp-admin/admin.php?page=wpseo_social&key=07741294c727af050a62767149e993a0&apps=%7B%220%22%3A%7B%22app_id%22%3A%22770990362924479%22%2C%22display_name%22%3A%22Atlas+Rewards+Blog%22%7D%2C%221%22%3A%7B%22app_id%22%3A%22139730029520125%22%2C%22display_name%22%3A%22Domino+Research+Blog%22%7D%7D>" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
23.29.122.202 - - [16/Jan/2015:14:32:57 -0500] "HEAD /apple-pay-uk-release-date-could-be-spring-2015-it-pro/ HTTP/1.1" 200 - "-" "MetaURI API/2.0 +metauri.com <http://metauri.com/>"
23.29.122.222 - - [16/Jan/2015:14:32:57 -0500] "HEAD /apple-pay-uk-release-date-could-be-spring-2015-it-pro/ HTTP/1.1" 200 - "-" "MetaURI API/2.0 +metauri.com <http://metauri.com/>"
173.252.88.185 - - [16/Jan/2015:14:32:58 -0500] "GET /atlasrewards/apple-pay-uk-release-date-could-be-spring-2015-it-pro-2/ HTTP/1.1" 301 - "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php <http://www.facebook.com/externalhit_uatext.php>)"
23.96.208.137 - - [16/Jan/2015:14:33:00 -0500] "GET /apple-pay-uk-release-date-could-be-spring-2015-it-pro/ HTTP/1.1" 200 549 "-" "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)"
98.255.188.228 - - [16/Jan/2015:14:32:28 -0500] "POST /atlasrewards/xmlrpc.php HTTP/1.1" 200 179 "-" "wp-android/3.5 (Android 4.4.2; en_US; HTC HTC One_M8/cingular_us)"
140.109.21.214 - - [16/Jan/2015:14:32:58 -0500] "HEAD /apple-pay-uk-release-date-could-be-spring-2015-it-pro/ HTTP/1.1" 200 - "-" "Mozilla"
199.30.80.119 - - [16/Jan/2015:14:33:01 -0500] "HEAD /apple-patents-icloud-based-touch-id-syncing-for-devices-and-apple-pay-terminals-techcrunch/ HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 6.1; rv:12.0; StumbleUpon; noc@stumbleupon.com <mailto:noc@stumbleupon.com>) Gecko/20100101 Firefox/12.0"
199.30.80.114 - - [16/Jan/2015:14:33:01 -0500] "HEAD /why-apple-pay-wont-be-the-death-of-google-wallet-techrepublic/ HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 6.1; rv:12.0; StumbleUpon; noc@stumbleupon.com <mailto:noc@stumbleupon.com>) Gecko/20100101 Firefox/12.0"
199.30.80.115 - - [16/Jan/2015:14:33:01 -0500] "HEAD /apple-patents-icloud-based-touch-id-syncing-for-devices-and-apple-pay-terminals-techcrunch/ HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 6.1; rv:12.0; StumbleUpon; noc@stumbleupon.com <mailto:noc@stumbleupon.com>) Gecko/20100101 Firefox/12.0"

**Comment by maxme** [comment]
You can try deactivate pingbacks, or disallow search engine to crawl your site in your `robots.txt` file, but there's nothing we can do on our side.

**Comment by kimstuart** [comment]
Isn’t the “firehose” what’s causing this?  If it works like Jetpack/WP.com <http://wp.com/> then it would trigger the events, correct?
