### ISSUE TITLE
Stats: Track analytics on StatsViewAllActivity and StatsSinglePostDetailsActivity

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2187]
Title has it. There are 2 TODOs in place in the code.

**Comment by sendhil** [comment]
@daniloercoli - would you cc me on the PR for the mixpanel stuff when your finished with it?

**Comment by daniloercoli** [comment]
@sendhil I was thinking to ping you before start writing code :D
