### ISSUE TITLE
Duplicate the pagination at the top of the screen as well

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2201]
Due to the length of the list in the Followers detail view, and the need to have pagination, I think it would be best to duplicate the pagination at the top of the screen as well. Perhaps this could only be done on devices where all items can’t be shown without scrolling, that would be a nice touch.

**Comment by daniloercoli** [comment]
@jancavan - do you have any hint where to replicate the pagination at the top of the module?

![screen shot 2015-02-09 at 11 53 32](https://cloud.githubusercontent.com/assets/518232/6104990/ec0ff1ce-b052-11e4-985c-cffe690d625c.png)

![screen shot 2015-02-09 at 11 53 48](https://cloud.githubusercontent.com/assets/518232/6105018/32639b80-b053-11e4-9c41-234a4b74eeba.png)

**Comment by jancavan** [comment]
@daniloercoli In between the total count and Follower heading would be a good spot so it's similar to Calypso. Would be great to change the total count to something like - "Showing 1 - 20 of x followers" as well just on this page. 

![pagination](https://cloud.githubusercontent.com/assets/4924246/6115472/c658b24c-b05a-11e4-82b6-429f8c0e0f9f.jpg)
