### ISSUE TITLE
Chart changes width when switching between different data sets

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2210]
Chart changes width when switching between different data sets, presumably because its width is dependent on the width of the y-axis label elements ... these should probably be unrelated. 
Maybe better to allow for up to 1M on the y-axis as a max, always, and then let y-axis labels overflow into the chart itself?

**Comment by hypest** [comment]
It seems that the charts lib doesn't currently have a smart way of setting a reasonable minimum width while letting it be dynamic for larger values.

I will close this ticket and move it to the forked lib's repo instead. Thanks!

**Comment by pfghrd43** [comment]
https://s.wp.com/wp-content/mu-plugins/achievements/likeable-blog-5-2x.png
