### ISSUE TITLE
Don't unconditionally auto-refresh remote data on configuration change

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#2214]
Behavior when changing orientation should be consistent. Here's a list of screens I've checked and what network calls they make on configuration change:

| Activity | Behavior |
| --- | --- |
| Posts/Pages | always auto-refresh |
| Select Post Categories (inside Edit Post Settings) | no auto-refresh |
| Comments | no auto-refresh |
| Media | no auto-refresh |
| Reader | varies, see below |
| Notifications | no auto-refresh |
| Stats | no auto-refresh |
| Stats - Single Post Details | no auto-refresh |
| Stats - View All | no auto-refresh |
| Themes | no auto-refresh |
| Manage Blogs (Settings > Show/hide WordPress.com blogs) | no auto-refresh |

Reader details:
- Will always auto-update /read/menu and read/following/mine.
- Will also auto-update /read/liked or /read/following if those are selected from the menu.
- Will auto-update selected blog if 10 minutes have passed since last refresh.

**Comment by maxme** [comment]
:+1: for consistency

**Comment by nbradbury** [comment]
Blah, the reader previously didn't auto-update upon device rotation but I accidentally introduced that in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/2155). Could catch - it definitely shouldn't do that.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by maxme** [comment]
This issue was auto closed during editor issue migration - should be tested again a few screens were changed since that matrix was done.

**Comment by maxme** [comment]
Tested on 6.4

| Activity | Behavior |
| --- | --- |
| Posts/Pages | no auto-refresh  |
| Select Post Categories (inside Edit Post Settings) | no auto-refresh |
| Comments | no auto-refresh |
| Media | no auto-refresh |
| Reader | no auto-refresh |
| Notifications | no auto-refresh |
| Stats | no auto-refresh |
| Stats - Single Post Details | no auto-refresh |
| Stats - View All | no auto-refresh |
| Themes | no auto-refresh |
| Manage Blogs (Settings > Show/hide WordPress.com blogs) | no auto-refresh |

We can close that issue.
