### ISSUE TITLE
SwipeRefreshLayout is not displayed in freshly created activities

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#2220]
When creating activities which use the `SwipeToRefreshHelper`, the `SwipeRefreshLayout` isn't displayed while loading.

This appears to be a known issue with the v4 support library (since 21.0.0). It seems that the `SwipeRefreshLayout` is actually loading and working properly, but it's hidden behind the action bar. Some discussion and possible workarounds [here] (https://code.google.com/p/android/issues/detail?id=77712).

**Comment by mayankkarna** [comment]
Exactly which class of the code has this issue?

**Comment by maxme** [comment]
This is pretty annoying on a slow connection, especially on the Post list views where you can't open a post until the loading action is finished (and you can't see the loading indicator).
