### ISSUE TITLE
Take Advantage of Photon's Quality Parameter

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2255]
I noticed that images seem to take a while to load in the app occasionally. I decided to see how large the images were that photon was returning in the Reader, for example. They are quite large! Luckily photon has a `quality` parameter that we can use to trim down the size.

Here's what the app currently gets, I'm pretty sure photon is defaulting to `100` (uncompressed). This file is 139KB:
![15656278404_5fb46a9cb2_h](https://cloud.githubusercontent.com/assets/789137/5884583/63948c10-a314-11e4-8a90-10083b5be669.jpg)

I tried the same at `quality=80` and it takes the size down to 57KB (woot): 
![15656278404_5fb46a9cb2_h-1](https://cloud.githubusercontent.com/assets/789137/5884597/7edd43ae-a314-11e4-886e-aa571d1e08b6.jpg)

And here's `quality=50`, which I think pushes the quality down too far (39KB):
![15656278404_5fb46a9cb2_h-2](https://cloud.githubusercontent.com/assets/789137/5884601/8c676158-a314-11e4-8d8e-4a4d2853e18f.jpg)

We should add another optional parameter to `PhotonUtils.getPhotonImageUrl()` where we can pass the quality value in to whatever we desire. It'd be even cooler to adjust the quality value based on the device's current connection.

**Comment by roundhill** [comment]
Also, something to note if we are displaying large images (like the featured images in the Reader). Since many devices have such high pixel densities these days, we might be able to apply quite a bit of compression and they will still look really sharp: http://www.netvlies.nl/blog/design-interactie/retina-revolution

**Comment by daniloercoli** [comment]
Nice find @roundhill !

**Comment by roundhill** [comment]
Think of the bandwidth we've saved! :)

cc @aerych, are you using this in the iOS app?

**Comment by aerych** [comment]
> are you using this in the iOS app?

If we're not we will be soon! :D

**Comment by roundhill** [comment]
> If we're not we will be soon! :D

Yassssss
