### ISSUE TITLE
Pictures are uploaded in a service that internally uses AsyncTask

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#226]
Was trying to upload a picture to the blog from the media library. 
Found out that if you tap on the picture to show the details when it is in "uploading" state, the MediaItemFragment doesn't show a preview of the picture (even if it's a local picture stored on the phone).

This is because the ImageView that holds the pictures in MediaItemFragment is populated by an AsyncTask in background (correct, since bitmap decoding could take time), but at the same time another AsyncTask is uploading the picture in MediaUploadService, and there are no available threads to complete the rendering operation. When the uploading is completed the Rendering is finally done, since a thread is now available to run the task.

AsyncThreads should be used for short operations only. 
Don't know if there is a simple way to increase the number of concurrent threads in AsyncTask.

Same issue if you tap on another picture while the current picture is in "uploading". The preview of the 2nd picture is not shown on the screen even if it already uploaded on the blog, or available locally on the phone.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
