### ISSUE TITLE
Theme preview bumps stats

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2267]
I spent some time testing the live theme preview in WP Android with a private blog which only I have access to. Shortly afterwards, I got a notification that my stats are booming. This could only have happened if the live preview was bumping the view stats.

**Comment by maxme** [comment]
I think we have the same problem when a user preview a published post from the Editor.

**Comment by rachelmcr** [comment]
I tested this in beta version 4.8-rc-1 on a private site, by going to Themes and selecting "Try & Customize" to preview a handful of themes. Each time it opened the preview in the site's customizer, and afterwards I checked my stats and didn't have any new views. With the way previewing themes works now, I don't think this is an issue anymore.

If I open a published post in the editor and preview it, I don't see any bump in my stats there, either.

I'm closing this issue as it looks like it's resolved now, but please reopen if I missed anything.
