### ISSUE TITLE
Notifications test bucket for devs

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2275]
Let's implement a new URL handler that will help us troubleshoot Notification issues:

```
wordpress://notifications?bucket_name=string
```

When received, the app should map the Notifications bucket as specified. This will allow us to use enterprise builds to retrieve entities stored in [any random] bucket, and test how they are rendered.

**Comment by maxme** [comment]
:+1:

**Comment by daniloercoli** [comment]
Simperium is gone, and buckets too.
