### ISSUE TITLE
"True" support for RTL languages

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2278]
The app works with RTL languages, but it's not a true RTL support (everything should be reversed: UI elements too, drawer, back button, checkboxes, FAB, etc.)

This is what happen when I add `android:supportsRtl="true"` to our manifest:

![screencap-2015-01-29t10-53-12 0100](https://cloud.githubusercontent.com/assets/40213/5955635/22edcfec-a7a5-11e4-9190-485b230ae8aa.png)

(we should wait for the redesign before tackling this issue)

**Comment by tonyr59h** [comment]
This one is straightforward but will touch many of the layout files. Since I'm working the other language issue I figured this would be appropriate to tackle in case we have RTL language users.

There's a [bug on Samsung devices](https://code.google.com/p/android/issues/detail?id=60055) that will crash if paddingStart or paddingEnd is defined and run pre API 17. In order to get around it we simply define a new resource file with -ldrtl-v17 directory.

Other than that bug all I'll be doing is adding End/Start attributes for margins and layout alignments. [Per the docs](http://developer.android.com/about/versions/android-4.2.html#RTL)

**Comment by rachelmcr** [comment]
I checked and confirmed that RTL support is still an issue in alpha-13. Some text is aligned correctly but other text is not aligned correctly and the icons/design is not reversed as expected.

This issue was also raised in an app store review (3 stars).

**Comment by tonyr59h** [comment]
Thanks for the update :) It'd be nice to have this working but most of our bandwidth is being consumed on Calypsoification at the moment. There's only a few features left on that front so hopefully this will get some attention in a few releases.

**Comment by daniloercoli** [comment]
I think we should allocate resources to work on this ticket asap, regardless of the current status of FluxC and Calypsoification. This ticket is near to be 2 years old now, and I think it's not acceptable for us to have an app that doesn't scale/work well on RTL languages.

**Comment by tonyr59h** [comment]
Updating all the padding/margins to use Start/End seemed to work [well enough](https://www.dropbox.com/s/bnnzjopje1lxm0o/Screenshot%202017-02-17%2018.21.59.png?dl=0). Most icons and some text are on the wrong side, sometimes due to layout decisions (which are easy to adjust).

**Comment by tonyr59h** [comment]
[Material guidelines](https://material.io/guidelines/usability/bidirectionality.html) for supporting bi-directionality. It has some interesting information regarding icon and interactive UI element mirroring. 

cc @mattmiklic, this may be of interest 😃

**Comment by tonyr59h** [comment]
Updating the configuration is a fairly fragmented process. I think we'll only be able to support API 17+ devices for RTL layout changes if the device language is set to LTR. For API 17+ we can use [setLayoutDirection](https://developer.android.com/reference/android/content/res/Configuration.html#setLayoutDirection(java.util.Locale)) to force an update.

Some of the layouts aren't mirrored even if both the device and app language is set to RTL. They'll need some layout adjustments.

**Comment by tonyr59h** [comment]
There's a new method introduced in API 25 that deprecates the old method. That leaves us with:

* API 16: cannot force RTL, it's set based on device language
* API 17-24: use `setLayoutDirection` +`updateConfiguration` which are deprecated in API 25
* API 25: use `createConfigurationContext` method

After finding some strange behavior I put together a [sample app](https://cldup.com/mnsoSxexZK.png) to sort the details out.

**Comment by ChrissiePollock** [comment]
An internal request for this #196170-h.

**Comment by rachelsquirrel** [comment]
I have a user who reports that none of the site titles appear when they change the language to Arabic. They've given us a screenshot:

![cd6bfc137e08ae04699c56500d83ead0328eb961](https://user-images.githubusercontent.com/7946521/27736632-eab2807c-5d9c-11e7-856d-1a179c80ca37.jpg)

They all appear when he changes to English.

#197167-h

**Comment by hypest** [comment]
Another manifestation of the issue is reported for the comments list:

![rtl](https://user-images.githubusercontent.com/1032913/29519628-c7a009c0-8686-11e7-9310-3b9e4059ac65.jpg)

p4a5px-1WN-p2
