### ISSUE TITLE
Double Posting

### ISSUE THREAD

**Issue by samhotchkiss** [wordpress-mobile/WordPress-Android#2282]
I've found myself double posting via the app a number of times

What I do:
1. Create a post
2. Add an image
3. Hit publish
4. Say to myself "hmm, I didn't get any confirmation, I wonder if that worked?"
5. Open the post
6. Hit publish again
7. Facepalm

**Comment by maxme** [comment]
That's weird, if the first post has been published and you open it a second time (step 5), you should see an "Update" button, tapping that button won't publish a second post (but update the current one).

**Comment by maxme** [comment]
Just tested: actually if the first post is uploading (with and "Uploading" label in the Post List), and you open that post a second time, the "Publish" button is here and you can publish it a second time.

We shouldn't allow to open the post while it's uploading.
