### ISSUE TITLE
Getting from Post Creation (keyboard up) to Publish

### ISSUE THREAD

**Issue by samhotchkiss** [wordpress-mobile/WordPress-Android#2283]
I've figured out the process for this, but it seems very counter-intuitive to press the back button in order to publish a post that you're working on.  I would wager that we're losing users who get frustrated and leave (I almost did)

**Comment by maxme** [comment]
You mean leaving the fullscreen mode to make the action bar visible. right? (ie. tapping the hide keyboard button).

**Comment by samhotchkiss** [comment]
Right-- there's no hide keyboard button that I see, though.

Screenshot:
https://www.dropbox.com/s/jc60d94qkrzjrq3/NormalAppImage%288%29.png?dl=0

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
