### ISSUE TITLE
Post: On a slow connection, app doesn't seem to do anything while uploading image.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#231]
Create a new post and include an image from the phone.  Publish the post.
Notice the toast informing you that the post is being uploaded. 
On a slow connection, once the toast is gone there is a fair amount of time before the refresh spinner starts animating (because the list is being refreshed maybe?).  Probably the spinner should be animating from the start of the file upload.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
