### ISSUE TITLE
UI layout on larger tablets

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2346]
The web version of Stats has introduced a 2-columns layout on desktop, and large mobile screen. 

We need to experimenting it, and check if replicable on this native app, or add a padding to the left and right. The latter is the solution used on all other app's screens.

**Comment by daniloercoli** [comment]
I've assigned a low priority to this tickets, since the numbers of 10" inch tablets is relative small compared to total number of installations of the app.

**Comment by daniloercoli** [comment]
Screenshot of the app running on a 9" tablet: 
https://cloudup.com/cn-hhOuuJ_R

Screenshot of the app running on a 10" tablet: 
https://cloudup.com/c-cwoiumPaV

I think 2 columns layout isn't suitable for the main screen, but some improvements could be done in other parts of Stats.

<b>Change the graph height</b>
- We can try to adapt the height by using the width as reference. (Similar on what've done on the Map in "Countries" module).
- Or we can use a fixed value size.

<b>Change the "View All" Screen</b>
By adding padding to the left and right. See the Reader implementation.
![screen shot 2015-02-24 at 15 50 29](https://cloud.githubusercontent.com/assets/518232/6352588/133bad9a-bc44-11e4-83f6-61b443158930.png)

@jancavan - If you want to give it a try, you can use Nexus 9, and Nexus 10 emulators.

**Comment by jancavan** [comment]
@daniloercoli It looks fine to me on portrait, but seems a tad bit wide on landscape especially for the "View all" screens. I don't know if adding a left/right padding to the landscape view is the solution to this since if we do that, it might feel like they actually never really rotated the device at all? Because it's the exact same thing, just that the background color is more visible.

What if we add more bars to the landscape view?

![rotate](https://cloud.githubusercontent.com/assets/4924246/6399641/a4d0bc22-bda8-11e4-8080-c419eb0d6897.jpg)

**Comment by daniloercoli** [comment]
- We can probably show 10 bars on smaller tablets (those tablets that are between SW600DP and SW720DP).  First version of Nexus 7 for example, that has a resolution of 800x1280:
![screen shot 2015-02-26 at 23 57 35](https://cloud.githubusercontent.com/assets/518232/6404050/43cc93a8-be14-11e4-83aa-4069fa02f393.png)

![screen shot 2015-02-26 at 23 57 46](https://cloud.githubusercontent.com/assets/518232/6404051/43d2397a-be14-11e4-99ef-a1ae55a9bc2f.png)

- We can show 15 bars on all other tablets > SW720DP (that always have the drawer open in landscape).
Below screenshot from Nexus 9 and Nexus 10:
![screen shot 2015-02-26 at 23 57 13](https://cloud.githubusercontent.com/assets/518232/6404089/8af9d9ac-be14-11e4-95c8-f9c3e9572a55.png)
![screen shot 2015-02-26 at 23 57 23](https://cloud.githubusercontent.com/assets/518232/6404090/8afc8c60-be14-11e4-965a-12d3bde3138a.png)
![screen shot 2015-02-26 at 23 58 04](https://cloud.githubusercontent.com/assets/518232/6404092/8f42c0f0-be14-11e4-8d04-90a1c332a83d.png)
![screen shot 2015-02-26 at 23 58 17](https://cloud.githubusercontent.com/assets/518232/6404093/8f4544a6-be14-11e4-9f5d-f63f7f10e181.png)

If we want to dynamically changes the no. of bars when rotating from landscape/portrait, we need to define clear bounds, keeping in mind that the drawer is open on bigger devices. Most probably, only those devices that are between SW600DP and SW720DP will notice a change in the number of bars when in landscape.

**Comment by daniloercoli** [comment]
Move this ticket to future version. We want to wait the new app design without the drawer, and see then how to adapt Stats for it.

**Comment by daniloercoli** [comment]
Starting with a fresh ticket here: https://github.com/wordpress-mobile/WordPress-Android/issues/2764
