### ISSUE TITLE
New Approach to Views / Visitors

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2347]
The web version of Stats is going to introduce a new way to show users the relation between the counts of Views and Visitors.

We should replicate the new UI in this native app. Below is a screenshot of what is going to be web stats on mobile.
![53dec374-b2bb-11e4-84ac-bb18025da497](https://cloud.githubusercontent.com/assets/518232/6238424/3b9513ce-b6fb-11e4-9718-bf7e4528c9bf.jpg)

The PR is not yet merged/deployed to users, and minor changes could happen in the next few days, but we can already start implementing it, since changes required to show 2 dataset in the graph are not small.

**Comment by daniloercoli** [comment]
Hey @jancavan - What are the exact color codes of those 4 colors used in the chart above?

**Comment by jancavan** [comment]
@daniloercoli 
Lighter blue bar - $wordpress-blue (#0085be)
Lighter orange bar - $jazzy-orange (#f0821e)
Inner dark blue - #004e70
Inner dark orange - #a65a15

We may want to keep the number of bars we currently have and their width on mobile so they're easily tappable. The above was just a quick mockup I put together for the legend.

**Comment by daniloercoli** [comment]
@jancavan If you want to try this brach https://github.com/wordpress-mobile/WordPress-Android/tree/issue/2347-new-approach-views-visitors, it's ready for a first pass of feedback.

Not sure I've got the interaction right, since don't have access to Calypso developer env.

**Comment by jancavan** [comment]
@daniloercoli Legend looks good so far! Got a few comments:

1. change inner dark orange to `$orange-fire` (`#d54e21`)
2. make the color squares part of the label - so if you click on the color squares, this will activate/deactivate checkbox (not just clicking on the text)
3. make the color squares smaller than the checkbox and less rounded. The checkbox needs to be less rounded as well.

![android-legend3](https://cloud.githubusercontent.com/assets/4924246/6355583/df0a540a-bc0b-11e4-8972-218dac8d6573.jpg)

Thanks!

**Comment by daniloercoli** [comment]
@jancavan  - Just one small note.

> The checkbox needs to be less rounded as well.
The checkboxes I used above are the default implementation of Android. Not sure we want to hack around it. In "Settings" for example we've used plenty of them. 
Anyway, If we want I create a different drawable that replace the default version and see how it looks.

**Comment by jancavan** [comment]
@daniloercoli Ok, if it's the default then let's just leave it as it is :+1:

**Comment by daniloercoli** [comment]
@jancavan - I applied the required changes you've brought up in the latest review. 
Give it a run when you can.

I'm not sure we need to change the colors of bars/legend when switching between Views and visitors.
What if we always keep Views to blue (#0085BE), and Visitors to dark-blue (##004e70) ?

**Comment by jancavan** [comment]
@daniloercoli Yes, let's do it that way.

**Comment by jancavan** [comment]
@daniloercoli I saw your screencap and I agree, it does feel a bit jumpy and confusing on the Visitors tab so a few more changes:

1. can we just provide the checkbox option only for the Views tab? And the rest of the 3 tabs will only have a legend. We are going to be doing this in Calypso as well. 

Without the legend, it feels a bit jumpy switching from Views to any of the 3 other tabs.

2. make the color squares smaller and move it *before* the text label. It works how it is now, but it feels unconventional for a legend to have the description before the symbol.

3. remove the disabled checkbox.

4. make legend label smaller.

**Views**
![atab-views](https://cloud.githubusercontent.com/assets/4924246/6379614/7739bdec-bce8-11e4-9409-4811ef9f74c7.jpg)

**Visitors**
![atab-visitors](https://cloud.githubusercontent.com/assets/4924246/6379610/6c86c386-bce8-11e4-86b5-ef4f30a56f95.jpg)

**Likes**
![atab-likes](https://cloud.githubusercontent.com/assets/4924246/6379608/67422e88-bce8-11e4-8a94-a06fe870b8bb.jpg)

**Comment by daniloercoli** [comment]
@jancavan - Ready for another round of review.

**Comment by jancavan** [comment]
@daniloercoli Looks great! :+1: 

Sorry I had not noticed this earlier, but would it be possible to make the orange highlight less dark when Visitors is checked? I think this looks darker because there are 2 orange highlights on top of each other. When Visitors is unselected though, it looks fine.

![orange-dark](https://cloud.githubusercontent.com/assets/4924246/6397569/6fceb8a2-bd9a-11e4-8d56-97378a2b380c.jpg)

Something like this would be good:
![orange](https://cloud.githubusercontent.com/assets/4924246/6397522/25c1eacc-bd9a-11e4-8858-f83826be4f12.jpg)

**Comment by daniloercoli** [comment]
@jancavan - Sorry, I had noticed the issue immediately after I've pinged you, but the fix took some time. 
Now it's fixed in the branch.

Should we remove the highlight on the label? I don't see it on the web version.
![screen shot 2015-02-26 at 23 20 28](https://cloud.githubusercontent.com/assets/518232/6403243/3979a978-be0e-11e4-8c67-91755ea988d8.png)

**Comment by jancavan** [comment]
@daniloercoli Good catch. Yup, let's fix that please.
