### ISSUE TITLE
Referrers Search Engine links should be grouped into sublists

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#2355]
Currently, under Referrers > Search Engines, it's a single, mixed list of linked - Google, Yahoo, Comcast, Bing, etc.

![screenshot 2015-02-19 14 35 27](https://cloud.githubusercontent.com/assets/4924246/6277576/9299f988-b844-11e4-8ae7-cd2d6eb52f0d.png)

We should group them so they look cleaner and easier to scan.

![screenshot 2015-02-19 14 36 37](https://cloud.githubusercontent.com/assets/4924246/6277640/29e8628e-b845-11e4-9ab8-527815e3bc3c.png)

![screenshot 2015-02-19 14 39 39](https://cloud.githubusercontent.com/assets/4924246/6277644/2cd395d6-b845-11e4-97ef-99b680413505.png)

**Comment by daniloercoli** [comment]
Will try to include this upgrade in 4.0. It's not an easy change though.

**Comment by daniloercoli** [comment]
@jancavan - Unfortunately we can't display a 3 levels expandable lists with the current code. We have to re-think the way lists are build in stats and this will take a lot of time and will impact everywhere in Stats.

What If we display the first 2 levels only, but keeping them in par with the Web version?

![screen shot 2015-04-01 at 18 18 29](https://cloud.githubusercontent.com/assets/518232/6945696/da0d572a-d89b-11e4-8626-72fd60d2cf68.png)

**Comment by jancavan** [comment]
@daniloercoli if there are only 2 levels, it won't really tell you what the items are under each referrer - Google search for example doesn't tell you what the 427 are. Let's just keep it as it is for now until we figure out a solution.

**Comment by daniloercoli** [comment]
OK, let's just keep it as it is now. Anyway, I've created a PR https://github.com/wordpress-mobile/WordPress-Android/pull/2502 that improves the underlying code, and prepares the field for a 3-levels UI.

**Comment by daniloercoli** [comment]
There hasn't been any activity on this thread in more than one year. This is a UI-fix worth pursuing, even though Stats is in pause at the moment, so we may not see any update on this for another couple of months at least. 

More on this, as I said before, we can't display a 3 levels expandable lists with the current code. We have to re-think the way lists are internally handled in stats, and this will take a lot of time and will impact on every list available in Stats.
