### ISSUE TITLE
Can't insert pictures via share intent if in the process of uploading another post

### ISSUE THREAD

**Issue by jasmussen** [wordpress-mobile/WordPress-Android#2364]
This is an edgecase. It should probably be prioritized as such.

I start photo-posts by sharing from the gallery to the WordPress app. If I start uploading a post like that, and then immediately start another, no photo will be inserted in the post editor. 

Steps to reproduce:

- open photo gallery, share photo to WordPress app, hit publish
- *before the previous post has successfully uploaded*, pick another photo in the photo gallery, share to the WordPress app to start a post

The 2nd post will be empty. There will be a brief toast that says "Loading...", but no photo is inserted in the editor.

Here's a logcat: https://cloudup.com/ccFZ1t8RjMG

The obvious workaround is to wait for the first post to upload before starting the next.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
