### ISSUE TITLE
Set a consistent elevation (shadow) across the app on the action bar

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2389]
Action bar has a zero elevation settings on most screens, excepted on notification details (at least).

**Comment by nbradbury** [comment]
Drop shadow is also on:
* Post editor
* Post settings
* Post categories
* Post preview
* Comment editor
* Stats detail
* Settings
* Settings > Show/hide blogs
* Settings > Single blog settings
* Settings > Manage notifications
* Settings > Licenses
* Application log

**Comment by nbradbury** [comment]
Note that the usual fix is to use `<item name="android:windowContentOverlay">@null</item>` but there's an [API 18 bug](https://code.google.com/p/android/issues/detail?id=58280) that prevents this from working.

**Comment by tonyr59h** [comment]
http://stackoverflow.com/questions/17945785/what-happened-to-windowcontentoverlay-in-android-api-18/18093909 seems to solve the API 18 bug.
