### ISSUE TITLE
Update stats colors before 3.9 code freeze

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2390]
Current stats color mix colors from the handbook and custom colors.

We've made that change https://github.com/wordpress-mobile/WordPress-Android/pull/2185#issuecomment-76751213 - we can revert it if we only want custom colors or update the Web version accordingly.

I've added a TODO in the `develop` branch here: 
https://github.com/wordpress-mobile/WordPress-Android/blob/e062faec6a63223494bf4ef21a1bf438f1036a7f/WordPress/src/main/res/values/colors.xml#L113-L115

**Comment by daniloercoli** [comment]
@jancavan - Could you please give a run to "develop" and check what are the correct colors to use?

**Comment by jancavan** [comment]
![colors-correct](https://cloud.githubusercontent.com/assets/4924246/6512978/8862df1e-c32c-11e4-9ff1-33b320d6d357.jpg)

@daniloercoli here is a screenshot I took of `develop` and I have labeled them by what colors they should be.

There are still a couple of areas in Calypso where I need to update the colors to match the labels on the image above.

By the way, the active bar's inner graph seems to be missing on this branch?

![screenshot 2015-03-05 11 21 18](https://cloud.githubusercontent.com/assets/4924246/6512983/8ca5d540-c32c-11e4-9820-67edf2beec23.png)

**Comment by daniloercoli** [comment]
@jancavan - I've updated colors in the following branch https://github.com/wordpress-mobile/WordPress-Android/tree/issue/2390-Stats-update-colors
Give it a try when you have a second.

The "more" icon (the three dots icon) is still grey. We need new images for it.

**Comment by jancavan** [comment]
@daniloercoli I'm not sure I see the changes on branch `tree/issue/2390-Stats-update-colors`. This is what it looks like to me currently:

![screenshot 2015-03-06 09 42 05](https://cloud.githubusercontent.com/assets/4924246/6530369/272152a8-c3e5-11e4-92f2-e43958fb915b.png)

![screenshot 2015-03-06 09 44 19](https://cloud.githubusercontent.com/assets/4924246/6530394/63076514-c3e5-11e4-9145-d5016eba6c7c.png)

The tab icon colors need to be updated also. Do those need new images as well?

**Comment by daniloercoli** [comment]
@jancavan The branch already has the updates in it. Try with git pull -rebase and make sure Android Studio is pointing to the right branch.

**Comment by jancavan** [comment]
@daniloercoli Do you need new icons for the tabs as well? The icons need to be `$gray-dark` for inactive and `darken( $gray,20 )` for active.

**Comment by daniloercoli** [comment]
@jancavan - Yes, we need to change those icons then.

**Comment by jancavan** [comment]
@daniloercoli I'll send you the new icons shortly.

The rest of the color updates look good. Just a few other things:

![android-colors](https://cloud.githubusercontent.com/assets/4924246/6560798/01372358-c64a-11e4-9994-40674a3b8ead.jpg)

**Comment by daniloercoli** [comment]
Active Tab - It's already $gray-dark. 
Inactive Tab - It's already gray 10.

Updated the colors of the inactive labels.

**Comment by jancavan** [comment]
@daniloercoli x-axis looks good. Here are the icons https://cloudup.com/ch5PttTtHWC

Font colors for error messages and empty modules need to be updated as well:

![android-colors-error](https://cloud.githubusercontent.com/assets/4924246/6562633/14b292ce-c658-11e4-85d9-d6779e84a845.jpg)

**Comment by jancavan** [comment]
@daniloercoli Here are the icons for the tabs, chevron and more:
https://cloudup.com/cwfG0IJx1Qe

I've included the chevron icons because they need to be using `$gray`.

**Comment by daniloercoli** [comment]
Thanks @jancavan - I've updates colors and icons. Thinking that we need to update 2 other icons: the link icon, and the tag icon. See below:

![screen shot 2015-03-10 at 10 24 33](https://cloud.githubusercontent.com/assets/518232/6572126/f2466dec-c70f-11e4-98a6-2262fb4233ed.png)
![screen shot 2015-03-10 at 10 25 56](https://cloud.githubusercontent.com/assets/518232/6572128/f3d6c68e-c70f-11e4-98ea-21659b6ad92a.png)

**Comment by jancavan** [comment]
Sorry my bad, I missed those. Included the Category folder icon here as well https://cloudup.com/cqvxoRLymJz

**Comment by daniloercoli** [comment]
@jancavan - I've updated all the icons :)

This PR is ready for developer review!

**Comment by jancavan** [comment]
@daniloercoli saw the updates. Great job :+1:
