### ISSUE TITLE
Update Blog Preferences page to reflect masterbar changes

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2393]
Now that we are adding the "View Admin" button in the "My Site" page, there is no need to have that button in the `BlogPreferencesActivity` anymore. Aside from that, there are some other possible changes we might need to make as a result of all the masterbar changes.

**Comment by nbradbury** [comment]
I removed "View Admin" from blog preferences in commit c009d42.
