### ISSUE TITLE
Implement "Add Media" button in My Site page

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2394]
The implementation details and necessary activity for it is a bit unclear at the moment. We basically want a way to add new media to the selected blog from the my site page.

**Comment by tonyr59h** [comment]
We should re-use MediaPickerActivity for this, it's currently being used in [EditPostActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1313) to select media for a post.

**Comment by tonyr59h** [comment]
I've got the functionality in, now we need to make some UX decisions.

* There's an Add button in the media page, do we want both Add buttons?
* After the user has selected the media should it open the media page? stay on the My Sites fragment?
* Should we add the same four options that are available on the media page? (capture image/video, on device images/videos)

**Comment by folletto** [comment]
Hello! :)

So, the important thing here is to have everything aligned, which to me means:

* Involve @kellychoffman which is doing design for the Media component, so we can coordinate on all the platforms to create a nice experience.
* Me and @mnt can help in terms of UX and visual alignment.

In general, we should follow the established pattern (i.e. Posts) of:

* FAB on the media page
* Add on the navigation view

![screen shot 2015-04-30 at 11 08 19](https://cloud.githubusercontent.com/assets/4389/7410700/3cd82382-ef29-11e4-9be6-71a778b94bbd.png)


Could you please attach the screenshots of the current status on Android for that component so we have a starting point?

**Comment by tonyr59h** [comment]
[Here](https://cldup.com/x9-EgC9q-e.png) is the current My Sites view. When the user taps Add they are presented with the system launcher to choose where to get images from. We have a new media picker in the works that will eventually contain all media and present it in-app. It's stabilizing now and won't be able to replace the OS functionality for a few releases.

**Comment by folletto** [comment]
I think that's perfect, with that we're perfectly aligned. :)

Do/WIll we have also a FAB on the Media page inside?

**Comment by oguzkocer** [comment]
Here is how the Media page looks when you tap on the + button on the navigation bar: https://cloudup.com/cMggVpDCRJ0

I don't *think* we have a FAB there or if anything like that is planned.

**Comment by folletto** [comment]
Ok. I think that page will have at some point to be reworked in sync with Calypso... correct?

**Comment by oguzkocer** [comment]
Well... I'd assume most of our current pages in both iOS and Android will need to be reworked to be consistent with Calypso. I have no idea in which order or when we'll all do that though. After the v1 of masterbar changes are done for Android, I feel like maybe we should just look at both of the apps and identify problems/inconsistencies and work our way through them.

**Comment by folletto** [comment]
Ok, thanks! :)

So for the scope of this PR we should be good, right? :D

**Comment by oguzkocer** [comment]
@tonyr59h ^^^ ? :)

**Comment by kellychoffman** [comment]
@folletto Thanks for the heads up.

> Here is how the Media page looks when you tap on the + button on the navigation bar: https://cloudup.com/cMggVpDCRJ0

:+1: This looks good.

**Comment by tonyr59h** [comment]
@oguzkocer sounds like we're all set for a PR :)

Thanks for the input @folletto!
