### ISSUE TITLE
android studio 1.1.0

### ISSUE THREAD

**Issue by gutiersa** [wordpress-mobile/WordPress-Android#2402]
I am getting this build error:

Error:A problem was found with the configuration of task ':checkVanillaDebugManifest'.
> File 'C:\Users\NAME\AndroidStudioProjects\WordPress\src\main\AndroidManifest.xml' specified for property 'manifest' does not exist.

But the manifest is in:
'C:\Users\NAME\AndroidStudioProjects\WordPress\WordPress\src\main\AndroidManifest.xml

Android Studio is looking for it in the wrong place. Where do I change the location?

Thanks

**Comment by aforcier** [comment]
@gutiersa I wasn't able to reproduce this, but it looks like the generated `WordPress.iml` file has the wrong path. Perhaps you changed the folder structure after importing the project?

Try deleting the `WordPress.iml` file in the `WordPress\WordPress` folder, and then run `Build`>`Clean Project`. Does that fix the problem?

**Comment by maxme** [comment]
@gutiersa if you still need help with this, can you contact us on Slack https://make.wordpress.org/chat/ - thanks!
