### ISSUE TITLE
New analytics to track number of selected pictures in the media picker

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2405]
1. Implement wpios  - [`WPAnalyticsStatEditorAddedPhotoViaLocalLibrary`](https://github.com/wordpress-mobile/WordPress-iOS/blob/762f9e37f68f6efaad44681956c2abddaa3d4760/WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerMixpanel.m#L382)
2. add new properties to that event to count number of medias added at the same time (media multi selection)

maybe trigger it [here](https://github.com/wordpress-mobile/WordPress-Android/blob/1628-mediapicker/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostContentFragment.java#L1882)

**Comment by tonyr59h** [comment]
This'll be a good introduction to analytics in the app. Could you take a look at https://github.com/wordpress-mobile/WordPress-Android/tree/issue/2405-track-media to see if it's implemented appropriately?

When testing I saw the analytics in the Mixpanel live view, but couldn't verify that the property was used correctly.

**Comment by maxme** [comment]
Looks good but why do you convert the value to a String [here](https://github.com/wordpress-mobile/WordPress-Android/blob/314507f71b90e17537b8cb2fd1a42c8dc02d5988/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostContentFragment.java#L1741) and [there](https://github.com/wordpress-mobile/WordPress-Android/blob/314507f71b90e17537b8cb2fd1a42c8dc02d5988/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostContentFragment.java#L1747) ?

FYI, you can get all associated properties when you click on single event in mixpanel:
![screen shot 2015-03-10 at 15 49 55](https://cloud.githubusercontent.com/assets/40213/6577314/32c4fc08-c73d-11e4-9aa1-27cf34c7b59d.png)
