### ISSUE TITLE
Change the sign in dialog background color

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2413]
Introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/2185, the new color makes the dialog hard to read:
![screen shot 2015-03-10 at 15 25 07](https://cloud.githubusercontent.com/assets/40213/6576917/941d9170-c73a-11e4-9c18-4206902d47d6.png)

I temporarly changed it to `grey_darken_30`:

![screen shot 2015-03-10 at 15 31 24](https://cloud.githubusercontent.com/assets/40213/6576920/954fc5cc-c73a-11e4-8952-ec9c02b5239a.png)

@drw158 Can we use another existing (transparent?) color or define a new one?

**Comment by drw158** [comment]
I think `semi_transparent_grey_dark` (`grey-dark` at 70% opacity) should be good enough.

Let's try that.

**Comment by maxme** [comment]
Looks too transparent IMO: ![screen shot 2015-03-11 at 10 02 53](https://cloud.githubusercontent.com/assets/40213/6593143/cc12972e-c7d5-11e4-8d8c-b00549801b4d.png)

**Comment by drw158** [comment]
Yea, maybe we should just go with 'grey_dark`

**Comment by maxme** [comment]
Here is the `grey_dark` version: ![screen shot 2015-03-17 at 15 20 32](https://cloud.githubusercontent.com/assets/40213/6689233/2a676204-ccb9-11e4-9f79-0ebb45c913a4.png)

**Comment by drw158** [comment]
This looks good to me.

-- 
Dave Whitley / Designer

On March 17, 2015 at 9:21:04 AM, Maxime Biais (notifications@github.com) wrote:

Here is the grey_dark version:
