### ISSUE TITLE
Storing account details for the user

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2425]
We need an `Account` model where we keep information about the user such as their username, email, gravatar url, if it's a WordPress.com user or not etc. Ideally there should be a way to get the default WordPress.com account user so we can use that information in the new "Me" page. This will also be good for us developers for information management on account login/logout and when the user updates his/her information.

**Comment by maxme** [comment]
This model should include the following informations at least:

* wpcom user or not

if wpcom user:
* username
* display name
* email address
* gravatar url (store this or create an util function that converts his email address to a gravatar hash?)

**Comment by nbradbury** [comment]
Closed via #2495
