### ISSUE TITLE
Offline delete media item doesn't work as expected on API 16

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2433]
Per discussion on #2426, this was only noticed on API 16.

**Comment by rachelmcr** [comment]
Per that discussion, after activating WIFI this error shows up in the logs:

>E/WordPress-API﹕ NETWORK_XMLRPC - Unable to resolve host "tonyrankin.wordpress.com": No address associated with hostname

I re-tested this issue on an emulator with API 16 and couldn't reproduce this error (by disabling WIFI, deleting a media item, enabling WIFI). However, as noted in the discussion, this error may not reliably reproduce with those steps.

**Comment by tonyr59h** [comment]
I don't think this is an issue anymore, probably since FluxC was introduced. Going to close it out.
