### ISSUE TITLE
ViewPostFragment can't load private images

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2444]
`ViewPostFragment` should pass the token to load private images, similarly to how the Reader detail view does it.

**Comment by kwonye** [comment]
Unfortunately reoccurring on 5.2-alpha7. Changing milestone to latest release.

**Comment by roundhill** [comment]
Something's funky with the way the API is returning a private image url:

`https://droundhill.files.wordpress.com/2015/02/wpid-img-20150216-wa0000.jpg#038;h=1032?w=702&h=1248`
