### ISSUE TITLE
log contains full encrypted login/password

### ISSUE THREAD

**Issue by warpdesign** [wordpress-mobile/WordPress-Android#2451]
It seems the app journal (in settings / help panel) contains full login/password to the wordpress: is it intended?

**Comment by warpdesign** [comment]
I meant *un*crypted..

**Comment by roundhill** [comment]
Nope, that is not intended. Can you provide any context as to where the credentials were displayed in the log?

**Comment by warpdesign** [comment]
Sure. When updating an article with a featured image, I'm getting an error, looking into the log, I can see:

[POSTS] d:uploadFileHelper: [1,login, password, name=wp-1551531.webp, overwrite=true,bits=org.wordpress.android.models.MediaFile@3bf48141, type=image/webp}]

login,password being the full, not encrypted login/password of my self hosted wordpress website.

**Comment by maxme** [comment]
@warpdesign you're right, we're going to fix that for the next release.

**Comment by warpdesign** [comment]
Thanks!

**Comment by warpdesign** [comment]
Now that was fast! ;)

**Comment by maxme** [comment]
> Now that was fast! ;)

That was a small fix, but you'll have to wait a bit before seeing it live in the Play Store, 3.9 release will be published in 2 weeks.
