### ISSUE TITLE
Some vietnamese characters aren't supported in the font used in the Reader

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2460]
For instance:

![image](https://cloud.githubusercontent.com/assets/40213/6808435/3b14904a-d254-11e4-9004-989b45e9ddb6.png)

I'm sure we already had an issue opened for this, but I can't find it, and I don't remember what we did.

**Comment by drw158** [comment]
Open Sans should support Vietnamese:

![screen shot 2015-09-03 at 4 15 54 pm](https://cloud.githubusercontent.com/assets/618551/9671247/1e211dea-5257-11e5-829a-03e4aade3284.png)

We should compare the Open Sans font we are using in the app with the one on Google Fonts.

**Comment by rachelmcr** [comment]
I tested in 4.8-rc-3 (Nexus 9, Android 6.1) and none of the Vietnamese characters were missing in the reader:

![screenshot_20151207-193619](https://cloud.githubusercontent.com/assets/8658164/11637570/13251d8e-9d1a-11e5-83a3-e678c25c0d9e.png)

Closing as worksforme. If this is still an issue on specific devices, please reopen.

**Comment by maxme** [comment]
It's still an issue on Android 4.x devices, we're receiving comments in the Play Store about it. This is probably the same issue as https://github.com/wordpress-mobile/WordPress-Android/issues/3358 - but it's not a font problem.

**Comment by maxme** [comment]
Closing this, it's definitely the same bug as in #3358 (more context there).
