### ISSUE TITLE
Don't pass ordinal of StatsViewType

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2469]
We're passing an ordinal value of `StatsViewType` to `StatsViewAllActivity` in a few places. We shouldn't need to do this since enums are serializable.

Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/2464#discussion_r27266173

**Comment by daniloercoli** [comment]
I don't remember why I passed an ordinal there. I've the suspect I copied fragment creation code from Pivotal. Will switch them back to enums.
