### ISSUE TITLE
Drop WordPressDB

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2471]
The `WordPressDB`class is stuffed with warnings, looks like a pretty easy task to clean most of them up and get it looking cleaner.

**Comment by maxme** [comment]
We should even do the extra step and split WordPressDB, but the migration step is a bit scary :fearful:.

**Comment by aforcier** [comment]
`WordPressDB` will be dropped with the initial FluxC integration.

**Comment by aforcier** [comment]
Most of `WordPressDB` has been moved to FluxC. We're still keeping it around for:

1. Migration to FluxC
2. The Themes table

Eventually we can drop the migration code, and we'll move themes to a `ThemeStore` in FluxC, and we'll be able to drop `WordPressDB` and all references to it.

On that day, @maxme will cackle maniacally as he closes this ticket using a comically oversized bright red button.

**Comment by maxme** [comment]
> On that day, @maxme will cackle maniacally as he closes this ticket using a comically oversized bright red button.

![noding](https://cloud.githubusercontent.com/assets/40213/24295178/d2555de2-1099-11e7-8c6e-762511e870dc.gif)
