### ISSUE TITLE
Update SettingsActivity for masterbar changes

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2506]
We should update the `SettingsActivity` to reflect the masterbar changes we're making. That includes removing "Sign Out" and "Help & Support" buttons and anything else that'll come up.

**Comment by nbradbury** [comment]
"Sign Out" and "Help & Support" have already been removed, but there will likely be other changes we need to make.

**Comment by maxme** [comment]
Remove "add self-hosted site" (replaced by "Add site" in the site switcher view)

**Comment by nbradbury** [comment]
"Add self-hosted site" and the list of wp.com/self-hosted blogs was removed from settings in 68f9e4e.

**Comment by nbradbury** [comment]
Closed via PR #2569
