### ISSUE TITLE
Unnecessary refresh in media picker

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2510]
While testing #2499 I noticed a lot of flickering/refreshing in the media picker's "Site Images" tab, and I believe it's caused by the listener calling `notifyDataSetChanged()` every time a media item is downloaded ([see here](https://github.com/wordpress-mobile/MediaPicker-Android/blob/develop/mediapicker/src/main/java/org/wordpress/mediapicker/MediaPickerFragment.java#L298)). This causes the entire grid to be refreshed with each download.

**Comment by tonyr59h** [comment]
Moved to [MediaPicker-Android](https://github.com/wordpress-mobile/MediaPicker-Android/issues/14) repo.
