### ISSUE TITLE
Add the insights screen

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2519]
Insights has just been merged in the web version of Calypso-Stats. We should add this feature to the mobile app. 

Need help from designers. @jancavan

//cc @astralbodies

**Comment by astralbodies** [comment]
Yes, totally agree. I think the major source of frustration with the changes in WPiOS is the missing all time type of view.

**Comment by jancavan** [comment]
Yup :+1:  this is on the to-do list.

**Comment by isaackeyet** [comment]
Design review of progress as of May 28

![insights-review](https://cloud.githubusercontent.com/assets/3073557/7861686/ef663cda-0551-11e5-8cf1-a0ff74a698a2.png)


More things:
* I'm all for moving Other Recent Stats over to Insights from Day 1, but I'd coordinate with the rest of the team on timing. If it does happen, the app also needs to have a message like the one in option C in this comment: https://github.com/Automattic/calypso-pre-oss/pull/6251#issuecomment-105611342 
* Random observation: sometimes when tapping around and switching between Insights and Days it seems to get stuck in loading mode, the chart doesn't load and there doesn't seem to be a way to cancel out of it. I haven't been able to reproduce consistently.
* Placeholder elements are great, except when they don't match the content that's about to get loaded. I would skip them or come up with something that more closely resembles the UI to be loaded.

**Comment by daniloercoli** [comment]
Thanks for the feedback @isaackeyet !

The "Most popular" module is now updated. You can do another round on the UI.

 
> I'm all for moving Other Recent Stats over to Insights from Day 1, but I'd coordinate with the rest of the team on timing. If it does happen, the app also needs to have a message like the one in option C in this comment: Automattic/calypso-pre-oss#6251 (comment)

Will keep an eye on that ticket and move "Other Recent Stats" over if the rest of the team do the same on the web version.

>Random observation: sometimes when tapping around and switching between Insights and Days it seems to get stuck in loading mode, the chart doesn't load and there doesn't seem to be a way to cancel out of it. I haven't been able to reproduce consistently.

I noticed that too in the current version without insights. Will open a new ticket for it. https://github.com/wordpress-mobile/WordPress-Android/issues/2773

**Comment by jancavan** [comment]
@daniloercoli One minor comment: the "popular" module's heading needs to be changed to "Most popular day and hour". /cc @astralbodies
