### ISSUE TITLE
Very long titles should be truncated in the Post list

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#252]
![device-2013-11-04-103603](https://f.cloud.github.com/assets/40213/1463763/67299c7c-4536-11e3-894a-d2668a5b750f.png)

**Comment by mayankkarna** [comment]
I think this edit will help

    SidebarTopLevelView *headerView = [[SidebarTopLevelView alloc] initWithFrame:CGRectMake(0, 0, CGRectGetWidth(self.tableView.frame), 44)];
    Blog *blog = [[self.resultsController fetchedObjects] objectAtIndex:(section - 1)];
    if ([blog.blogName length] != 0) {
        if([blog.blogName length]<50)
        headerView.blogTitle = blog.blogName;
else { String subBlogName =blog.blogName.substring(0,50)+".......";
      headerView.blogTitle=subBlogName;
}
    } else {
        headerView.blogTitle = blog.url;
    }
    headerView.blavatarUrl = blog.blavatarUrl;
    headerView.isWPCom = blog.isWPcom;

**Comment by maxme** [comment]
@mayankkarna this is a mix of Objective-C and Java code...

**Comment by mayankkarna** [comment]
I think this is fine!

else { NSString  *subBlogName =[@blog.blogName substringWithRange:NSMakeRange(0,50)];
headerView.blogTitle=subBlogName;
}
} else {
headerView.blogTitle = blog.url;
}
headerView.blavatarUrl = blog.blavatarUrl;
headerView.isWPCom = blog.isWPcom;

**Comment by mayankkarna** [comment]
@maxme  can you assign me a bug related to java .

**Comment by solinger10** [comment]
I don't think this is a problem anymore. It looks like the post titles can only take up a max of two lines.

https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/post_list_row.xml#L22

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
