### ISSUE TITLE
Masterbar: logout of .com when user has self-hosted

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2524]
Right now logging out from the Me page always shows the sign-in screen, even if the user has a self-hosted site. It should instead log them out of .com and stay on the Me page. If the user displays the site picker, we should make sure it doesn't show any of their .com blogs.

**Comment by maxme** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/2630
