### ISSUE TITLE
error invalid_client message invalid client_id

### ISSUE THREAD

**Issue by Stackflood** [wordpress-mobile/WordPress-Android#2544]
1. Using Android emulator on Android studio.

2. Trying to create an account.

3.Keep getting this error even after creating/recreating new MyApp and hence getting a new client_id and client_secret.

4.client_id is definitely correct each time, but keep getting this error.

**Comment by maxme** [comment]
Can you post your `gradle.properties` here (hide your secrets)? and the full stack trace?

**Comment by Stackflood** [comment]
Maxime, please find the following :

1. gradle.properties

wp.oauth.app_id = 40389
wp.oauth.app_secret = cnSlxwQ6BQad0eNTROGjO9BlnQuj1rp9Pl7QIBMnSULYAZ7UgpF7KTpGhazFJb3K
wp.oauth.redirect_uri = http://android.wordpress.org/
wp.gcm.id = wordpress
wp.db_secret = wordpress
wp.mixpanel_token = wordpress
wp.simperium.app_secret = wordpress
wp.simperium.app_name = wordpress
wp.helpshift.api.key = wordpress
wp.helpshift.api.domain = wordpress.org
wp.helpshift.api.id = wordpress

2.Full Stack Trace :

04-17 20:27:16.009    1354-1354/org.wordpress.android D/dalvikvm﹕ Not late-enabling CheckJNI (already on)
04-17 20:27:18.158    1354-1354/org.wordpress.android E/Trace﹕ error opening trace file: No such file or directory (2)
04-17 20:27:18.358    1354-1354/org.wordpress.android D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 0ms
04-17 20:27:18.878    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 154K, 4% free 6286K/6535K, paused 20ms+6ms, total 142ms
04-17 20:27:18.878    1354-1354/org.wordpress.android D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 42ms
04-17 20:27:21.098    1354-1376/org.wordpress.android E/WordPress-API﹕ KeyStore integrity check failed.
    java.io.IOException: KeyStore integrity check failed.
            at com.android.org.bouncycastle.jce.provider.JDKKeyStore.engineLoad(JDKKeyStore.java:856)
            at java.security.KeyStore.load(KeyStore.java:589)
            at org.wordpress.android.networking.SelfSignedSSLCertsManager.loadTrustStore(SelfSignedSSLCertsManager.java:132)
            at org.wordpress.android.networking.SelfSignedSSLCertsManager.<init>(SelfSignedSSLCertsManager.java:45)
            at org.wordpress.android.networking.SelfSignedSSLCertsManager.getInstance(SelfSignedSSLCertsManager.java:95)
            at org.wordpress.android.networking.WPDelayedHurlStack$1.run(WPDelayedHurlStack.java:69)
04-17 20:27:21.488    1354-1354/org.wordpress.android D/Volley﹕ [1] VolleyLog.setTag: Changing log tag to WordPress
04-17 20:27:22.138    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 268K, 6% free 6452K/6855K, paused 16ms+3ms, total 279ms
04-17 20:27:22.718    1354-1354/org.wordpress.android D/MixpanelAPI - App Links (OPTIONAL)﹕ Context is not an instance of Activity. To detect inbound App Links, pass an instance of an Activity to getInstance.
04-17 20:27:25.078    1354-1354/org.wordpress.android E/WordPress-NOTIFS﹕ Device doesn't support GCM: Device does not have package com.google.android.gsf
04-17 20:27:25.178    1354-1354/org.wordpress.android I/WordPress-SUGGESTION﹕ resetting suggestion table
04-17 20:27:27.058    1354-1354/org.wordpress.android V/WordPress-UTILS﹕ WPLaunchActivity,  activityName: LOGIN, activityId: Login Screen, intent: null
04-17 20:27:27.099    1354-1354/org.wordpress.android V/WordPress-UTILS﹕ Launch default Activity: PostsActivity
04-17 20:27:29.149    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 302K, 6% free 6633K/7047K, paused 18ms+71ms, total 248ms
04-17 20:27:29.179    1354-1354/org.wordpress.android D/WordPress﹕ [1] Request.finish: 7658 ms: [ ] http://api.wordpress.org/androidapp/feedback-check/1.0/ 0x6a31e61b NORMAL 1
04-17 20:27:30.159    1354-1354/org.wordpress.android I/dalvikvm﹕ Could not find method org.wordpress.android.ui.WPDrawerActivity.isDestroyed, referenced from method org.wordpress.android.ui.WPDrawerActivity.isActivityDestroyed
04-17 20:27:30.159    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve virtual method 31033: Lorg/wordpress/android/ui/WPDrawerActivity;.isDestroyed ()Z
04-17 20:27:30.159    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
04-17 20:27:30.199    1354-1354/org.wordpress.android I/dalvikvm﹕ Could not find method android.view.Window.setStatusBarColor, referenced from method org.wordpress.android.ui.WPDrawerActivity.onCreate
04-17 20:27:30.199    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve virtual method 13834: Landroid/view/Window;.setStatusBarColor (I)V
04-17 20:27:30.209    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0045
04-17 20:27:31.429    1354-1354/org.wordpress.android I/dalvikvm﹕ Could not find method android.view.ViewGroup.onRtlPropertiesChanged, referenced from method android.support.v7.widget.Toolbar.onRtlPropertiesChanged
04-17 20:27:31.429    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve virtual method 13742: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
04-17 20:27:31.439    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x6f at 0x0007
04-17 20:27:31.699    1354-1354/org.wordpress.android I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
04-17 20:27:31.699    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve virtual method 654: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
04-17 20:27:31.699    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
04-17 20:27:31.709    1354-1354/org.wordpress.android I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
04-17 20:27:31.709    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve virtual method 676: Landroid/content/res/TypedArray;.getType (I)I
04-17 20:27:31.719    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
04-17 20:27:33.859    1354-1354/org.wordpress.android D/WordPress-PROFILING﹕ WordPress.onCreate: begin
04-17 20:27:33.909    1354-1354/org.wordpress.android D/WordPress-PROFILING﹕ WordPress.onCreate:      14769 ms, PostsActivity.onCreate
04-17 20:27:33.909    1354-1354/org.wordpress.android D/WordPress-PROFILING﹕ WordPress.onCreate: end, 14769 ms
04-17 20:27:34.909    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 207K, 5% free 6833K/7175K, paused 19ms+3ms, total 327ms
04-17 20:27:35.629    1354-1354/org.wordpress.android E/dalvikvm﹕ Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method org.wordpress.android.widgets.FloatingActionButton.setBackgroundCompat
04-17 20:27:35.629    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve new-instance 172 (Landroid/graphics/drawable/RippleDrawable;) in Lorg/wordpress/android/widgets/FloatingActionButton;
04-17 20:27:35.639    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0018
04-17 20:27:35.649    1354-1354/org.wordpress.android I/dalvikvm﹕ Could not find method org.wordpress.android.widgets.FloatingActionButton.setElevation, referenced from method org.wordpress.android.widgets.FloatingActionButton.init
04-17 20:27:35.649    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve virtual method 37840: Lorg/wordpress/android/widgets/FloatingActionButton;.setElevation (F)V
04-17 20:27:35.649    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0021
04-17 20:27:35.679    1354-1354/org.wordpress.android D/dalvikvm﹕ DexOpt: unable to opt direct call 0x03ec at 0x3d in Lorg/wordpress/android/widgets/FloatingActionButton;.setBackgroundCompat
04-17 20:27:36.499    1354-1354/org.wordpress.android D/dalvikvm﹕ GC_FOR_ALLOC freed 134K, 6% free 6781K/7175K, paused 181ms, total 197ms
04-17 20:27:36.529    1354-1354/org.wordpress.android I/dalvikvm-heap﹕ Grow heap (frag case) to 7.163MB for 470604-byte allocation
04-17 20:27:36.839    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 2K, 6% free 7238K/7687K, paused 33ms+30ms, total 313ms
04-17 20:27:36.839    1354-1354/org.wordpress.android D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 209ms
04-17 20:27:37.119    1354-1354/org.wordpress.android D/dalvikvm﹕ GC_FOR_ALLOC freed 0K, 6% free 7238K/7687K, paused 173ms, total 173ms
04-17 20:27:37.119    1354-1354/org.wordpress.android I/dalvikvm-heap﹕ Grow heap (frag case) to 7.359MB for 209164-byte allocation
04-17 20:27:37.349    1354-1354/org.wordpress.android D/dalvikvm﹕ GC_FOR_ALLOC freed 0K, 7% free 7442K/7943K, paused 201ms, total 201ms
04-17 20:27:38.669    1354-1354/org.wordpress.android I/dalvikvm﹕ Could not find method android.provider.Settings$Global.getInt, referenced from method org.wordpress.android.util.NetworkUtils.isAirplaneModeOn
04-17 20:27:38.669    1354-1354/org.wordpress.android W/dalvikvm﹕ VFY: unable to resolve static method 1500: Landroid/provider/Settings$Global;.getInt (Landroid/content/ContentResolver;Ljava/lang/String;I)I
04-17 20:27:38.679    1354-1354/org.wordpress.android D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x001d
04-17 20:27:39.879    1354-1354/org.wordpress.android D/WordPress-NUX﹕ No accounts configured.  Sending user to set up an account
04-17 20:27:41.029    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 753K, 12% free 7182K/8071K, paused 44ms+35ms, total 622ms
04-17 20:27:42.699    1354-1354/org.wordpress.android D/dalvikvm﹕ Trying to load lib /data/data/org.wordpress.android/lib/libgnustl_shared.so 0xb657f7b0
04-17 20:27:42.749    1354-1354/org.wordpress.android D/dalvikvm﹕ Added shared lib /data/data/org.wordpress.android/lib/libgnustl_shared.so 0xb657f7b0
04-17 20:27:42.749    1354-1354/org.wordpress.android D/dalvikvm﹕ No JNI_OnLoad found in /data/data/org.wordpress.android/lib/libgnustl_shared.so 0xb657f7b0, skipping init
04-17 20:27:42.749    1354-1354/org.wordpress.android D/dalvikvm﹕ Trying to load lib /data/data/org.wordpress.android/lib/libemailchecker.so 0xb657f7b0
04-17 20:27:42.749    1354-1354/org.wordpress.android D/dalvikvm﹕ Added shared lib /data/data/org.wordpress.android/lib/libemailchecker.so 0xb657f7b0
04-17 20:27:42.749    1354-1354/org.wordpress.android D/dalvikvm﹕ No JNI_OnLoad found in /data/data/org.wordpress.android/lib/libemailchecker.so 0xb657f7b0, skipping init
04-17 20:27:42.769    1354-1354/org.wordpress.android V/WordPress-NUX﹕ NewAccountAbstractOage.onCreate()
04-17 20:27:43.449    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 323K, 11% free 7260K/8071K, paused 24ms+40ms, total 154ms
04-17 20:27:45.359    1354-1354/org.wordpress.android V/WordPress-UTILS﹕ trackLastActivity, activityId: Login Screen
04-17 20:27:46.599    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 515 frames!  The application may be doing too much work on its main thread.
04-17 20:27:46.619    1354-1354/org.wordpress.android D/gralloc_goldfish﹕ Emulator without GPU emulation detected.
04-17 20:27:47.559    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 278 frames!  The application may be doing too much work on its main thread.
04-17 20:27:47.739    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 32 frames!  The application may be doing too much work on its main thread.
04-17 20:27:48.349    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 47 frames!  The application may be doing too much work on its main thread.
04-17 20:27:49.919    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 59 frames!  The application may be doing too much work on its main thread.
04-17 20:27:51.449    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 82 frames!  The application may be doing too much work on its main thread.
04-17 20:28:19.039    1354-1354/org.wordpress.android V/WordPress-NUX﹕ NewAccountAbstractOage.onCreate()
04-17 20:28:19.179    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 276K, 8% free 7430K/8071K, paused 20ms+33ms, total 92ms
04-17 20:28:19.569    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 180 frames!  The application may be doing too much work on its main thread.
04-17 20:28:19.830    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 63 frames!  The application may be doing too much work on its main thread.
04-17 20:28:21.510    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 42 frames!  The application may be doing too much work on its main thread.
04-17 20:28:26.570    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 282K, 7% free 7532K/8071K, paused 19ms+1ms, total 51ms
04-17 20:28:27.870    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 30 frames!  The application may be doing too much work on its main thread.
04-17 20:28:30.680    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 186 frames!  The application may be doing too much work on its main thread.
04-17 20:28:30.820    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 80 frames!  The application may be doing too much work on its main thread.
04-17 20:28:30.920    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 61 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.001    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 46 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.142    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 56 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.200    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 31 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.310    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 41 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.420    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 36 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.510    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 31 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.630    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 55 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.690    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 31 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.880    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 55 frames!  The application may be doing too much work on its main thread.
04-17 20:28:31.960    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 38 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.020    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 35 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.090    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 39 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.150    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 34 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.240    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 68 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.390    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 66 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.430    1354-1357/org.wordpress.android D/dalvikvm﹕ GC_CONCURRENT freed 363K, 7% free 7634K/8135K, paused 25ms+63ms, total 243ms
04-17 20:28:32.490    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 73 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.600    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 46 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.689    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 67 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.790    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 34 frames!  The application may be doing too much work on its main thread.
04-17 20:28:32.969    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 54 frames!  The application may be doing too much work on its main thread.
04-17 20:28:33.040    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 54 frames!  The application may be doing too much work on its main thread.
04-17 20:28:33.240    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 33 frames!  The application may be doing too much work on its main thread.
04-17 20:28:33.350    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 39 frames!  The application may be doing too much work on its main thread.
04-17 20:28:33.470    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 30 frames!  The application may be doing too much work on its main thread.
04-17 20:28:33.720    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 35 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.010    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 37 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.100    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 60 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.170    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 33 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.200    1354-1535/org.wordpress.android D/WordPress﹕ [68] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://public-api.wordpress.com/rest/v1/users/new 0x7b2dc254 NORMAL 1> [lifetime=3506], [size=57], [rc=403], [retryCount=0]
04-17 20:28:34.260    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 32 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.330    1354-1535/org.wordpress.android E/WordPress﹕ [68] BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1/users/new
04-17 20:28:34.350    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 30 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.420    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 37 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.550    1354-1354/org.wordpress.android E/WordPress-NUX﹕ null
    com.android.volley.AuthFailureError
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:170)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
04-17 20:28:34.560    1354-1354/org.wordpress.android E/WordPress-NUX﹕ Error message: {"error":"invalid_client","message":"Invalid client_id."}
04-17 20:28:34.620    1354-1354/org.wordpress.android D/WordPress﹕ [1] Request.finish: 3995 ms: [ ] https://public-api.wordpress.com/rest/v1/users/new 0x7b2dc254 NORMAL 1
04-17 20:28:34.620    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 97 frames!  The application may be doing too much work on its main thread.
04-17 20:28:34.810    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 109 frames!  The application may be doing too much work on its main thread.
04-17 20:28:35.000    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 119 frames!  The application may be doing too much work on its main thread.
04-17 20:28:35.159    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 132 frames!  The application may be doing too much work on its main thread.
04-17 20:28:35.300    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 75 frames!  The application may be doing too much work on its main thread.
04-17 20:28:35.370    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 33 frames!  The application may be doing too much work on its main thread.
04-17 20:28:35.490    1354-1354/org.wordpress.android I/Choreographer﹕ Skipped 39 frames!  The application may be doing too much work on its main thread.

**Comment by maxme** [comment]
> https://public-api.wordpress.com/rest/v1/users/new

Will fail to create new users with a "user's api key" (only a few whitelisted keys are allowed for this request). 

So you won't be able to create new users with your app id/secret. You'll have to create a new user on the Web (or on the app downloaded from the Play Store) and then you'll be able to sign in the app with your custom version of the app.

Note: exposed API is here https://developer.wordpress.com/docs/api/

**Comment by roundhill** [comment]
@Stackflood The client ID and secret were exposed when I received an email notification for this issue. For security reasons I revoked the application so you will need to create another one at https://developer.wordpress.com/apps/

**Comment by Stackflood** [comment]
:+1:
