### ISSUE TITLE
With the new media picker, users can't browse all folders on their device

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2548]
We should add a way to open the system image picker if they need it.

**Comment by maxme** [comment]
ref https://github.com/wordpress-mobile/MediaPicker-Android/issues/17

**Comment by Toof** [comment]
User reports being unable to access images on SD Card here: https://automattic.helpshift.com/admin/issue/26638/

**Comment by Toof** [comment]
We also have a customer report of being unable to access images on an SD Card using the new picker

**Comment by tonyr59h** [comment]
The legacy options were added back in #2587 

I've opened a [ticket](https://github.com/wordpress-mobile/MediaPicker-Android/issues/21) in the media picker repo to add SD card support.
