### ISSUE TITLE
Proposal - Editor should use src code of WordPressAnalytics 

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2549]
I think the editor should link and use the src code of `WordPressAnalytics`.  Like the other library project `WordPressUtils` that it uses and links.

```
dependencies {
    compile 'com.android.support:appcompat-v7:21.0.+'
    compile 'com.android.support:support-v4:21.0.+'
    releaseCompile project(path:':libs:analytics:WordPressAnalytics', configuration: 'release')
    debugCompile project(path:':libs:analytics:WordPressAnalytics', configuration: 'debug')
    releaseCompile project(path:':libs:utils:WordPressUtils', configuration: 'release')
    debugCompile project(path:':libs:utils:WordPressUtils', configuration: 'debug')
}
```

Otherwise we need to make sure to publish new artifacts on each update to the WordPressAnalytics prj. We have modified `WordPressAnalytics` without incrementing the release number, and publish new artifacts, resulting in weird errors in AS, that could take time to developer to understand what is happening.

**Comment by maxme** [comment]
There is a bug in Android Studio which consider some dependencies as artifact dependencies when gradle resolve them as source dependencies. Adding WPAnalytics as a source dependency in WPEditor would workaround this issue, but it also adds complexity by having a source dependency inside another source dependency. Ideally we would only have one layer of source dependency and only artifact dependencies for deeper layers.

That's also why we removed the wputils source dependency from wpeditor in https://github.com/wordpress-mobile/WordPress-Editor-Android/commit/aec64104bbc1fb14702e6cf78ff57656512c5848#diff-ff1371cc0d469a8fc19b088d1540a921
