### ISSUE TITLE
Failure in SSL library, usually a protocol error error

### ISSUE THREAD

**Issue by Stackflood** [wordpress-mobile/WordPress-Android#2570]
On Android > 4.1.
1.Login Screen : Entered Correct 

a).UserName
b).Passowrd

2.Clicked on Sign In

3.Got the following Error :

com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb89e0fe8: Failure in SSL library, usually a protocol error error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0xb32bfa4d:0x00000000)

4.Debugged : This error occurs here 

A). WPDelayedHurlStack --> 
      @Override
      B). public HttpResponse performRequest(...) 
      {
         C). setConnectionParametersForRequest(connection, request); -->
                  {
                      case Method.POST:
                      connection.setRequestMethod("POST");
                      D). addBodyIfExists(connection, request); -->
                                   {
                                     DataOutputStream out = new                      DataOutputStream(connection.getOutputStream());
                                   }
                   }
      } 

 
On Android < 4.1

Error : com.android.volley.NoConnectionError: java.io.EOFException inside 
4. B). at 
int responseCode = connection.getResponseCode();

The following link doesn't resolve this issue : https://code.google.com/p/android/issues/detail?id=24672

**Comment by Stackflood** [comment]
Hi,

Anyone can help with this? I am finding this error quite often now - may be 1 in 5 runs, even after testing the app on my phone - MI3

**Comment by maxme** [comment]
We made changes to how ssl discovery and connections are made, can you check if your problem still happens and reopen the issue in that case.
