### ISSUE TITLE
Cannot mark a comment as SPAM from the notifications screen

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2589]
I was trying to mark a comment as spam from the notifications screen, but wasn't able to do that.
Steps to repro:
- Receive a notification of new comment
- Go to the Notifications screen and tap on the comment
- Tap on the Spam icon
- The app takes you back to the notifications screen, but the comment is still there, and it's not marked as spam.
- You can tap on the comment again, open the details screen, and check the status of the comment: Still marked as "Pending" or "Approved"; 
- Refreshing notifications doesn't help.

![untitled](https://cloud.githubusercontent.com/assets/518232/7366884/a2f7060e-ed9b-11e4-9517-60cea151914c.gif)

**Comment by daniloercoli** [comment]
Maybe this was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/2586

**Comment by roundhill** [comment]
> Maybe this was fixed in #2586

Yes, should have fixed it. I'll close this for now, we can reopen if you still see the issue.

**Comment by roundhill** [comment]
Cool GIF btw ;)
