### ISSUE TITLE
Suggestion: add save/update button to keyboard

### ISSUE THREAD

**Issue by rralian** [wordpress-mobile/WordPress-Android#2592]
android version 5.1, app 4.0-rc-2

I found it very counter-intuitive when I was writing/editing a post that I first had to close the android on-screen keyboard in order to see a save/update button. I wanted to see/use a save button while I had my on-screen keyboard open. Either on the keyboard itself, or if that doesn't fit, maybe on the screen somewhere above the keyboard. It's scary to first close the keyboard without saving. Like scooby-doo mummy scary.

**Comment by oguzkocer** [comment]
With the new Android Editor this doesn't seem applicable anymore. The publish & settings button are now in the navigation bar, so they should always be accessible.
