### ISSUE TITLE
Disconnect from WordPress.com text cut off on small screen

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2593]
480x800 emulator:

![screen shot 2015-04-28 at 10 43 33 am](https://cloud.githubusercontent.com/assets/789137/7376284/905c6cda-ed93-11e4-9428-99dd2d1e31a0.png)

**Comment by fadils** [comment]
From a smaller screen perspective, it becomes the following:

![screenshot_2015-04-29-14-15-54](https://cloud.githubusercontent.com/assets/6204776/7386162/e4b3195e-ee7a-11e4-991e-7f963bf6a071.png)

Would it be OK to increase the list item height?

**Comment by nbradbury** [comment]
This is addressed in PR #2594.

**Comment by fadils** [comment]
Ah, awesome!
