### ISSUE TITLE
Previewing post bumps stats

### ISSUE THREAD

**Issue by rachelsquirrel** [wordpress-mobile/WordPress-Android#2598]
Previewing a post in the Android app is counted as a view in the stats. 

To reproduce, open a post in the app and then tap the eye icon to preview the post. Make sure you're signed out of the browser on your device. 

If the post is private or a draft then the preview is not counted in the stats. It only happens for public, published posts.

**Comment by maxme** [comment]
Apparently we're loading public previews in a non authenticated webview, I don't know what's the reason for this.

https://github.com/wordpress-mobile/WordPress-Android/blob/d92e32ba783aef0ad361d99d26fbba70899e9b32/WordPress/src/main/java/org/wordpress/android/ui/posts/ViewPostFragment.java#L204-L226 

I tracked the origin of this code: https://github.com/wordpress-mobile/WordPress-Android/commit/5527f12073cc38394ee6653011bc7682aed90409

**Comment by daniloercoli** [comment]
<blockquote>Apparently we're loading public previews in a non authenticated webview</blockquote>
I think we're doing this since the first versions of the app.

//cc @astralbodies - not sure if we have the same problem on iOS.

**Comment by astralbodies** [comment]
@daniloercoli looks like its a known issue in https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/99
