### ISSUE TITLE
geo location gets cleared on updating the post

### ISSUE THREAD

**Issue by thejeshgn** [wordpress-mobile/WordPress-Android#2616]
- Self hosted blog
- Steps on the app (Android, Version 3.9.1)

- Steps to replicate on the App
1. Create a post
2. Geo tag the post
3. Publish - Great, the post is geo tagged (verified on the site)
4. Edit post - edit contents of the post
5. Update/publish, the post geo tag gets cleared (verified on the site)
6. Edit post again
5. Update/publish, the post geo tag appears again (verified on the site)

Let me know if you need any more information to replicate

**Comment by maxme** [comment]
Confirmed

**Comment by xuugii** [comment]
Found the issue in PostUploadService.java!
When remoteGeoLatitude has a ID and try to send with "mClient.call("metaWeblog.editPost", params);" it does't get updated!


 I have a two solution for this:
1) mClient.call("metaWeblog.editPost", params); RPC ... I guess I cannot touch with it, since its the server side? 

2) simple fix (workaround) in PostUploadService.java 

change following lines from:
 try {
                    if (remoteGeoLatitude != null) {
                        hLatitude.put("id", remoteGeoLatitude.getInt("id"));
                    }

                    if (remoteGeoLongitude != null) {
                        hLongitude.put("id", remoteGeoLongitude.getInt("id"));
                    }

                    if (remoteGeoPublic != null) {
                        hPublic.put("id", remoteGeoPublic.getInt("id"));
                    }

                    if (mPost.hasLocation()) {
                        PostLocation location = mPost.getLocation();
                        if (!hLatitude.containsKey("id")) {
                            hLatitude.put("key", "geo_latitude");
                        }

                        if (!hLongitude.containsKey("id")) {
                            hLongitude.put("key", "geo_longitude");
                        }

                        if (!hPublic.containsKey("id")) {
                            hPublic.put("key", "geo_public");
                        }                    
                        hLatitude.put("value", location.getLatitude());
                        hLongitude.put("value", location.getLongitude());
                        hPublic.put("value", 1);
                    }
                } catch (JSONException e) {
                    AppLog.e(T.EDITOR, e);
                }

to

                       hLatitude.put("key", "geo_latitude");
                        hLongitude.put("key", "geo_longitude");
                        hPublic.put("key", "geo_public");
                        hLatitude.put("value", location.getLatitude());
                        hLongitude.put("value", location.getLongitude());
                        hPublic.put("value", 1);
