### ISSUE TITLE
Masterbar: stats on non-JP self-hosted

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2618]
Right now tapping the Stats button on a self hosted site show a Toast: "Stats couldn't be refreshed at this time." It should instead work like PR #2606 and let the user know they need to login for stats.

**Comment by daniloercoli** [comment]
This should be fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/2580

**Comment by maxme** [comment]
fixed in #2580 - user is asked to login to his JP account if the JP plugin is installed on the blog - or user is asked to install JP otherwise.
