### ISSUE TITLE
Page settings button shows wrong text

### ISSUE THREAD

**Issue by solinger10** [wordpress-mobile/WordPress-Android#2623]
When adding a page the settings button shows "Post settings" instead of "Page Settings"

It looks like there's a todo <a href="https://github.com/wordpress-mobile/WordPress-Android/blob/16af718b78324d20548dd5769f50953a99590d65/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L817">here</a>.

![2015-05-04 17 53 10](https://cloud.githubusercontent.com/assets/5845439/7458950/8481d95e-f266-11e4-8b7c-a72d41479090.png)
![2015-05-03 14 29 20](https://cloud.githubusercontent.com/assets/5845439/7458951/8484577e-f266-11e4-9962-c78c6ed280b3.png)

**Comment by rachelmcr** [comment]
I tested and confirmed this is still an issue in beta version 4.8-rc-1.

**Comment by rachelmcr** [comment]
I'm closing this issue, as the bug (and the planned fix) are being tracked in the Android editor repo: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/250
