### ISSUE TITLE
HTML entities in site title in the My site tab

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2625]
Worth checking other calls to `getBlogName()`

![screen shot 2015-05-05 at 08 34 39](https://cloud.githubusercontent.com/assets/40213/7468755/b53a0458-f30c-11e4-82ec-1ad256cdb2cf.png)

**Comment by nbradbury** [comment]
@oguzkocer I believe you were looking into this already (?)

**Comment by oguzkocer** [comment]
Yeap, I am working on it now.

**Comment by oguzkocer** [comment]
I've looked into other places `getBlogName` was used but didn't really find any problems in the UI. Hopefully I didn't miss anything.
