### ISSUE TITLE
Can approve or reply comments from notifications screen

### ISSUE THREAD

**Issue by thejeshgn** [wordpress-mobile/WordPress-Android#2627]
- Self hosted blog
- Version 3.9.1

- Get a notification for a comment
- Go to notifications screen
- Click on comment & app moves to single comment screen
- Click on approve tick mark
- Tick turns pink, goes back to notifications page, refreshes
- displays "An error occurred while moderating"

**Comment by rachelmcr** [comment]
Hi @thejeshgn! I tested this issue on a self-hosted blog running WordPress 4.3.1 and couldn't reproduce the behavior you described. Is this still an issue for you? (If so, I can continue testing it.)

**Comment by rachelmcr** [comment]
I'm going to go ahead and close this issue, since I can no longer reproduce it. If you still have trouble with this, please comment here and we can reopen and investigate it!
