### ISSUE TITLE
"Logged out" reader

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2628]
Now that we enable disconnecting from wp.com, the reader needs to handle a "logged out" experience to handle the case that the user has a self-hosted blog. Note that PR #2630 should be merged before starting on this.

@aerych Could you provide a brief summary of how this works in our iOS app?

**Comment by aerych** [comment]
In the iOS app, someone not signed in to wpcom is able to browse the default content returned from the read/menu endpoint. This is Freshly Pressed and a collection of tags.  Blog previews work and comments on a post are viewable, but following, liking, reblogging, and replying are unavailable.

**Comment by oguzkocer** [comment]
These are possibly going to be resolved once the "Logged out" version of the reader is fully implemented, but I thought they might help identifying existing issues. So, here is a short list of things I've found testing the app:

* When you have both self-hosted and WordPress.com account and you disconnect WordPress.com, the reader gets confused and starts throwing errors: https://cloudup.com/cJ0aq-C7ogb & https://cloudup.com/cPswFm920mr (thanks @daniloercoli)
* If you try to like a post in reader when you are logged in with self-hosted only, it says "incorrect password"
* If you try to comment on a post in reader when you are logged in with self-hosted only, it says "Couldn't post your comment" but it doesn't give any context to why
* If you like a comment on a post in reader when you are logged in with self-hosted only, it looks like it worked. Did it?

Note: Not that it matters but all of the tests were done in a pre-lollipop emulator

**Comment by nbradbury** [comment]
Thanks for the list @oguzkocer! All of these are being fixed in the [logged out reader branch](https://github.com/wordpress-mobile/WordPress-Android/tree/feature/logged-out-reader).
