### ISSUE TITLE
Better notifications page for self-hosted users

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2646]
For self hosted users we currently show "No Notifications" message in the Notifications page. It'd be great if we can do something similar to what Maxime suggested over Slack:

(a) if the selected wporg blog has the jetpack plugin installed (we can check that in blog options) then show the "Connect to wpcom" button
(b) if the selected wporg blog doesn't have this JP plugin installed then show the "Learn more" button

Here is how iOS counterpart looks like: https://cloudup.com/c2vJ-N1D4dw

/cc @roundhill

**Comment by roundhill** [comment]
@oguzkocer I started working on this, but it looks like there's already something that's at least a little better than 'No notifications' that was recently added by @nbradbury:

![screen shot 2015-05-11 at 3 21 31 pm](https://cloud.githubusercontent.com/assets/789137/7576353/8f488a14-f7f1-11e4-9c9f-8d041b839b1f.png)

If needed I can still add the Jetpack-specific message.

**Comment by oguzkocer** [comment]
I think just adding the Jetpack-specific message would be good enough. We might want to involve a designer to get an opinion for the "Connect to wpcom" version. @drw158 maybe?

**Comment by drw158** [comment]
That is a _little_ better than the "No Notifications" text. Users might get confused, since they think they are already signed to "WordPress" (their .org site).

I think what Maxime suggested sounds really good.

We actually thought about this at the recent designer's meetup so maybe there will be some good things to come of it.

For option A, I suggest something like:

> Use the Jetpack plugin to enable notifications.
(Sign in to Jetpack)

or

> Use the Jetpack plugin to view your notifications.
(Sign in to WordPress.com)

**Comment by hypest** [comment]
It's probably not very simple:
* If Jetpack is installed _and activated_, we will need to find out whether it's connected to wpcom account or just left there unconnected. If not connected, even signing in to wpcom on the app won't really help anything. On the contrary, it will lead to user confusion and support requests.
* If Jetpack is installed, activated and connected to a wpcom account we will need to find _which_ wpcom is that and prompt and restrict the user to connect to that one via this call-to-action. Otherwise the feature will still not work and lead to yet more support requests.

So, we should be very careful with our call-to-action sign in button here. That said, I think the current "simple" sign in to wpcom button is probably not that helpful.

**Comment by oguzkocer** [comment]
@hypest I'd suggest holding off on this one until FluxC is integrated. That should make things much easier.

**Comment by oguzkocer** [comment]
We should be ready to tackle this issue now that FluxC is integrated. @mattmiklic Can we get your input on this on your next Groundskeeping day?

**Comment by mattmiklic** [comment]
Hey @oguzkocer, I'm not completely clear on what's needed here yet. To be sure I'm understanding,

- iOS displays a "learn more" screen if a self-hosted user isn't connected to a dotcom account
- We want to add a button on Android that works the same way if Jetpack isn't installed
- We also want to add a new "connect to WordPress.com" screen if Jetpack _is_ installed on the self-hosted site; this would need a design for both Android and iOS.

Do I understand all of that correctly?

**Comment by oguzkocer** [comment]
@mattmiklic I think that covers it. But, just to be sure, let me layout all the scenarios and we can find a solution which covers all of them. I wanted your input not just on the design of a specific page, but generally how the whole flow would work best.

1. A Jetpack user might login with their .com credentials in which case the regular notifications screen should work.
2. A Jetpack user might login with their self-hosted credentials, in which case we won't have the .com token, so notifications won't work. I think we want them to login with their .com account in this case.
3. A self-hosted user that doesn't have Jetpack won't be able to do anything, But, we can introduce them to Jetpack at this point
4. A self-hosted user with a Jetpack plugin who has not yet connected to their .com account should be able to connect their .com account from mobile. Although I don't know if this is currently possible. I think we can check their plugin from xml-rpc, but not 100% sure.

There are also some cases where the user might use a different .com account credential from the one they connected their Jetpack to. But, I think we can ignore these cases, at least for now.

**Comment by maxme** [comment]
> A self-hosted user that doesn't have Jetpack won't be able to do anything, But, we can introduce them to Jetpack at this point

In stats, we "introduce" them Jetpack by letting them install the plugin on their site ("hey you need Jetpack to access the Stats, click here to install Jetpack plugin on your site"). I'm not sure why we should do something different here.

> A self-hosted user with a Jetpack plugin who has not yet connected to their .com account should be able to connect their .com account from mobile. Although I don't know if this is currently possible. I think we can check their plugin from xml-rpc, but not 100% sure.

Yes it's possible, it's also what we do in Stats if the site is Jetpack "installed" but not "connected".

**Comment by oguzkocer** [comment]
> In stats, we introduce them Jetpack by letting them install the plugin on their site ("hey you need Jetpack to access the Stats, click here to install Jetpack plugin on your site"). I'm not sure why we should do something different here.

@maxme I didn't know about that, thanks for clarifying!

**Comment by tonyr59h** [comment]
Hey @mattmiklic! Any progress on this?

**Comment by maxme** [comment]
We might not do this actually - putting this on hold.

**Comment by elibud** [comment]
Closing this in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/7198
