### ISSUE TITLE
Reader should update db when a blog is removed from a list

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2647]
If you remove a blog from a custom list, the posts that were downloaded before are not removed.

/cc @nbradbury

**Comment by rachelmcr** [comment]
I tested this in 4.8-rc-3 and confirmed that if I remove a blog from a custom list (using a web browser; I don't see a way to do that in the app) and then return to the list in the app, the posts from that blog that were downloaded before are still there. In a web browser, the old posts from that removed blog are no longer in the list.
