### ISSUE TITLE
Replying from comment page doesn't refresh the comments list

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2650]
If you go into My Site -> Comments -> Single Comment and reply to a comment and go back to the Comments page, the new comment is not added to the list. I think we should trigger a refresh when a new comment is added through the app.

**Comment by limpakos** [comment]
Okay, I will look into this... Can't self assign it, so hopefully this comment is enough...

**Comment by rachelmcr** [comment]
I tested with the steps above, and the new comment was added to the Comments list right away. Tested on Nexus 9, Android 6.0, app beta 4.8-rc-3.

Closing as resolved.
