### ISSUE TITLE
NotificationsDetailActivity leaked

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2656]
![107d448a-f6fd-11e4-8274-edbf5f5501b8](https://cloud.githubusercontent.com/assets/3903757/7554680/449ef3ec-f6ff-11e4-9369-e291a582059e.png)

**Comment by rachelmcr** [comment]
Checked with @nbradbury in Slack and he confirmed that this bug no longer exists. Closing as resolved.
