### ISSUE TITLE
Media upload state needs shadow

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2699]
The `media_grid_item_upload_state` TextView on the [media grid item layout](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/media_grid_item.xml#L33) uses `android:textColor="@color/white"` which makes it hard to see on a photo with a light background. Adding a shadow should make it work with both light & dark backgrounds.

**Comment by tonyr59h** [comment]
Addressed in #2624, closing.
