### ISSUE TITLE
Add a visible scrollbar in the Reader's tag list

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2703]
ref https://github.com/wordpress-mobile/WordPress-Android/pull/2694

> IMO, we should show the scrollbar in the tag list https://cloudup.com/cLSJarAZtTF - it's not obvious I can scroll the view here: https://cloudup.com/cS2l3XstY26

**Comment by nbradbury** [comment]
Ref: http://stackoverflow.com/questions/19812302/spinners-scrollbar-style

**Comment by tonyr59h** [comment]
Did someone finish this already (#2694 maybe)? All of my devices are showing a scrollbar in the tag spinner when I'm able to scroll it.

cc @nbradbury
