### ISSUE TITLE
Missing ripple in notifications

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2713]
Several of the notification layouts use a selector drawable for the background, which prevents the ripple effect from appearing on Lollipop. Using `android:background="?android:selectableItemBackground"` should provide the ripple effect automatically (and downgrade to a simple highlight on earlier devices).

![noripple](https://cloud.githubusercontent.com/assets/3903757/7672650/f9fc8efc-fcc7-11e4-88ac-340da58955ee.png)

**Comment by roundhill** [comment]
I'll fix this as I work on #2132
