### ISSUE TITLE
Users should be able to search through their blog list

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#2718]
Matt pointed out to us that for users with a lot of sites on their mobile app it was very difficult to find a particular blog as you had to scroll a lot. Let's add in the ability to search through the blog list to be able to more quickly find a particular site.

**Comment by maxme** [comment]
Web version looks like:
![screen shot 2015-05-19 at 08 49 21](https://cloud.githubusercontent.com/assets/40213/7697058/39368446-fe04-11e4-998c-e26c17ca625b.png)

**Comment by kwonye** [comment]
Thanks @maxme :smile:

**Comment by tonyr59h** [comment]
Addressed in #2767, closing.
