### ISSUE TITLE
Show a toast after saving a draft

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2730]
Easy solution is to add a 'Saved draft' toast appear if you leave the post editor w/o publishing:

> Just had a “crap did I just lose my post?!” moment.
> 
> Go to the WP icon (My Sites?)
> Tap on “Add” for “Blog Posts”
> Add some content
> Hit the back button
> You’re now back in the My Sites section without any sort of confirmation or indication on how to get back to the post you were in. Thankfully it was saved as a Local Draft so my work was still there but it was a panicked moment.

**Comment by tonyr59h** [comment]
Addressed in #2753, closing.
