### ISSUE TITLE
More Compact Tabs for Tablet UI?

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2732]
I've seen a few apps that will compact the tabs and left-align them when in a tablet UI in landscape:

![device-2015-05-19-153459](https://cloud.githubusercontent.com/assets/789137/7715692/ea39e9d8-fe3e-11e4-93a7-d2252798880b.png)

It appears that the material guidelines recommend this as well: http://www.google.com/design/spec/components/tabs.html#tabs-specs

Current look:
![device-2015-05-19-154801](https://cloud.githubusercontent.com/assets/789137/7715694/f8db1728-fe3e-11e4-92ce-e2e003f1c973.png)

@joen and @drw158, any thoughts?

**Comment by nbradbury** [comment]
As a clarification, what's being proposed is something along these lines:

![device-2015-05-19-185424](https://cloud.githubusercontent.com/assets/3903757/7715742/a3a92474-fe58-11e4-92f8-cb6041391796.png)
