### ISSUE TITLE
Better handle null blog in MySiteFragment

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2734]
Currently in my site page if the blog is empty, we have kind of an empty page which is not very user friendly: https://cloudup.com/ct5jiYNpZT0 As @nbradbury mentioned in [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/2724#issuecomment-103634684) it would be good to have an empty state where we can have an add site or switch site button there. I am hoping @mnt can help us with the design of it.

**Comment by mnt** [comment]
Just so I'm clear on the issue; this happens if I log into the app with a WordPress.com account that has no sites at all?

**Comment by oguzkocer** [comment]
@mnt: yeap!

**Comment by mnt** [comment]
Got it, thanks; I'll work up some options here.

**Comment by mnt** [comment]
I looked at how Calypso handles this state, and we've got a nice design in place there for the web. I've adapted it to fit a mobile screen here:

![no sites](https://cloud.githubusercontent.com/assets/1396552/7866146/7a35105a-053b-11e5-8a2e-536c66b6eeaf.png)

(We can update iOS with the same design later).

Here's how it looks on the web:
![screen shot 2015-05-28 at 12 56 33 pm](https://cloud.githubusercontent.com/assets/1396552/7866160/8e5ec24c-053b-11e5-9e28-5e4131953376.png)

**Comment by mnt** [comment]
@oguzkocer here are the Drake illustrations you'll need for that screen: https://cloudup.com/cBFgZdiOaXw

**Comment by oguzkocer** [comment]
Thanks @mnt, I'll start working on this as soon as I finish the issues I am working on currently.

**Comment by maxme** [comment]
Note: that can happen if the user hides all his blogs. So I'm wondering if "Add Site" should be changed to something else ("Show Site"?) in case the user has at least one blog.

**Comment by oguzkocer** [comment]
I *think*, we shouldn't let users to hide all of their sites. I'd expect an error message saying "you should at least have one site" when you want to hide the last one.

**Comment by maxme** [comment]
* There is a way to hide all blogs on the Web
* Previous versions have that so when users upgrade they have no blog selected

We could fix it client side by forcing one blog (main blog?) to be visible when the app start

**Comment by maxme** [comment]
Another way to have no current blog:

* Sign in a wpcom account
* Add a wporg site
* HIde all wpcom sites
* Remove wporg site

(Could also be fixed by forcing visibility on a wpcom site)

**Comment by oguzkocer** [comment]
Again, this is my personal opinion, but I think we should always force one blog to be visible. Just changing the message in this page would be easier for sure, but it just doesn't make a lot of sense to me to have an account with no visible blogs. I might be missing something though.

**Comment by maxme** [comment]
> I think we should always force one blog to be visible

I agree. 

It's a bit tricky to force one wpcom blog to be visible and set it as the current blog, I'm wondering if we should do that in `WordPress.getCurrentBlog()`.

> but it just doesn't make a lot of sense to me to have an account with no visible blogs

Yes, this is probably the effect of an unwanted action (For instance: a user that have a wpcom account and use it only for his wporg with JetPack site, if he removes his wporg site from the app - he's going to end up with no visible wpcom site).

**Comment by oguzkocer** [comment]
`WordPress.getCurrentBlog()` sounds like a good place to handle this.

**Comment by nbradbury** [comment]
The site picker prevents the user from hiding the current site [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java#L262), but as mentioned above there are edge cases that could cause all sites to be hidden.

I think `getCurrentBlog()` already handles some edge cases by calling [this routine](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L635), but that needs to be updated to set the first blog as the default regardless of visibility.

Once that's done, we're left with the original problem: what should "My Sites" show when the user doesn't have any blogs? I think the design @mnt provided solves that wonderfully.

**Comment by daniloercoli** [comment]
Note that one could open a wpcom account without getting a blog. It's a really edge case, but it could happen.

**Comment by mnt** [comment]
Preparing the no-sites design for @oguzkocer to implement; I made one slight change—using a standard Material Design raised button instead of the web-styled button that was in the earlier mockup.

![no sites android](https://cloud.githubusercontent.com/assets/1396552/8359450/67905824-1b34-11e5-97ad-644d84b3869a.png)

And here's the annotated mockup with measurements and font info.

![screen shot 2015-06-25 at 12 13 36 pm](https://cloud.githubusercontent.com/assets/1396552/8359457/7167e808-1b34-11e5-91f9-15ab4898b61b.png)

And the Drake illustrations I posted earlier, for good measure: https://cloudup.com/cBFgZdiOaXw
