### ISSUE TITLE
"My Site" and "Me" icons aren't tappable

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2738]
The icons next to the various labels on the My Site and Me fragments need to be tappable.

**Comment by nbradbury** [comment]
This is addressed in #2752.

**Comment by doanappdev** [comment]
I am able to add the code for this issue. As this is my first time adding code to the project I wanted to check if coding the following is ok

ImageView mySiteImageView = (ImageView) rootView.findViewById(R.id.my_site_view_site_icon);
        mySiteImageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ActivityLauncher.viewCurrentSite(getActivity());
            }
        });

**Comment by doanappdev** [comment]
I was checking out the functionality of how the button works, and wanted to suggest using a click handler on the Relative layout that holds the icon and button. This will make the icons and labels tappable and allow us to remove click events for each icon and button.

**Comment by nbradbury** [comment]
Closed via #2752
