### ISSUE TITLE
FAB menu enhancements

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2748]
1. We should add a transparent layer over the background when the FAB menu is visible (and change menu styling at the same time)
2. We should hide the fab menu when the user touch the background (feels natural and we don't want to allow actions, like tapping or scrolling while the menu is opened).

Maybe contribs for https://github.com/futuresimple/android-floating-action-button

**Comment by nbradbury** [comment]
Before customizing this library, we may want to investigate a different one. I've just started looking into [this one](https://github.com/Clans/FloatingActionButton), which at a glance appears to be a better choice since:
* It supports elevation and ripple on Lollipop
* It has built-in support for a faded background

**Comment by doanappdev** [comment]
Hi I wanted to contribute to this issue,
I have used  https://github.com/futuresimple/android-floating-action-button (which maxme mentioned)
in a previous project and found it to be reliable and simple to use. I had a look at the FAB suggested by nbradbury and this one looks ok as well. I guess either would be ok.

I'm new to contributing to this project and was wandering if someone had already started implementing the FAB button? and where can I access it to work on it?

cheers

**Comment by doanappdev** [comment]
Forget the last bit about where the code was for FAB, I can see the button on the blog post page.

**Comment by maxme** [comment]
@doanappdev we're using [this library](https://github.com/futuresimple/android-floating-action-button) in the current version of the app. We might switch to [this one](https://github.com/Clans/FloatingActionButton) since it offers what we're looking for (faded background and native lollipop implementation).

**Comment by doanappdev** [comment]
If you need someone to change the code to use the new FAB button let me
know,
ill be happy to do that.

**Comment by tonyr59h** [comment]
Hey @doanappdev, are you going to be working through this issue or do you mind if I take a stab at it?

**Comment by doanappdev** [comment]
Hi Tony,

I don't know whats happening with this issue, I was offering to help but
know one got back to me.
Let me know if you want to work on something and maybe we can both can work
on it

cheers

**Comment by nbradbury** [comment]
Closing this one - no longer relevant due to #2928
