### ISSUE TITLE
Notifications: Comment moderation doesn't work when opened from push

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2768]
If you open a comment push notification and then try to perform a moderation action, nothing happens.

From a quick debug, it appears that NotificationsListFragment is null in the `onActivityResult()` of WPMainActivity.

**Comment by maxme** [comment]
We're going to have the same problem for all fragments that needs `onActivityResult()` here. The viewpager doesn't guarantee that fragments will be instantiated and initialized. I'll play with EventBus to delegate the `onActivityResult()` - but I'm not sure that's the best solution.

**Comment by maxme** [comment]
Actually, I think we should move the some code from the fragment to a helper/controller class. (And that's probably true for other "pages" on the main viewpager).

For instance this https://github.com/wordpress-mobile/WordPress-Android/blob/7d6bcbba450020ac4689ec3f09f40e56d5842e3b/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java#L309-L315 doesn't require a fragment with a view.

Note: While testing I encountered a toast "Couldn't open notification" a few times, I'll try to reproduce and fill and issue.

**Comment by nbradbury** [comment]
> Actually, I think we should move the some code from the fragment to a helper/controller class. (And that's probably true for other "pages" on the main viewpager).

That's probably the best approach when the result *must* be handled even if the fragment doesn't exist.

**Comment by maxme** [comment]
Fixed in #2771
