### ISSUE TITLE
Notifications Don't Show Post Title Emoji

### ISSUE THREAD

**Issue by pento** [wordpress-mobile/WordPress-Android#2777]
![2015-05-29 01 57 49](https://cloud.githubusercontent.com/assets/352291/7878378/74379076-0629-11e5-8839-2ad5f78cf4cd.png)

From this post:

http://pento.net/2015/05/11/oh-hai-%F0%9F%91%B6/

**Comment by rachelmcr** [comment]
I tested a few variations of post title emoji and found that the emoji may or may not appear, depending on where they are in the post title. My heart emoji always appeared, and faces appeared if there were some in the middle of the title but not if they only came at the end of the title.

For example, the slug `i-♥-this-test-post-😊` appeared like this:

No emoji at the end of the post title in the list of notifications:

![screenshot_20151125-123903](https://cloud.githubusercontent.com/assets/8658164/11397606/ac892300-9372-11e5-80b8-28feb0b00dd7.png)

All emoji showing on the notification's detail screen:

![screenshot_20151125-123909](https://cloud.githubusercontent.com/assets/8658164/11397608/b002e174-9372-11e5-9121-02a1cafcb2c9.png)

In contrast, the slug `i-♥-this-😊-test-post-😊` appeared like this (all emoji showing everywhere):

![screenshot_20151125-124119](https://cloud.githubusercontent.com/assets/8658164/11397631/c9e52fb6-9372-11e5-8130-2a0aba17343c.png)

![screenshot_20151125-124123](https://cloud.githubusercontent.com/assets/8658164/11397633/cb6a9c86-9372-11e5-80a6-6d0a20b9a39c.png)

Device: Nexus 9
Android: 6.0
Version: 4.8-rc-1

**Comment by dmsnell** [comment]
Resolved in r130054-wpcom
