### ISSUE TITLE
Add a utility method to check if a URL is wpcom

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2785]
While reviewing https://github.com/wordpress-mobile/WordPress-Android/pull/2784, I noticed we're using different way to check for a `wordpress.com` url across the app (hostname ends with `wordpress.com`, url contains `wordpress.com`).

**Comment by roundhill** [comment]
:+1:

**Comment by daniloercoli** [comment]
Make sure to check all the calls to `isPrivate` and `isDotComBlog`. 
The former should also call the latter internally, since only wpcom blogs can be marked as private.

**Comment by daniloercoli** [comment]
Addressed in #3548
