### ISSUE TITLE
The spinner needs some padding/centering when the device is in landscape

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2813]
Stats and Reblog (not sure if there are other screens affected by this issue) use a spinner that is not correctly positioned when the device is in landscape. See pictures below:
![d684c250-0a00-11e5-9dee-64f94b1991ca](https://cloud.githubusercontent.com/assets/518232/8060235/80bfc34c-0ec4-11e5-87cd-0be68dd9ca27.png)
![screen shot 2015-06-09 at 16 28 17](https://cloud.githubusercontent.com/assets/518232/8060257/8f182f2e-0ec4-11e5-80db-79424144f8f7.png)

**Comment by daniloercoli** [comment]
I'm running out of ideas to tackle this issue. I tried forcing `layout_gravity` and `gravity` to spinner items without any luck. The Spinner takes the whole toolbar height but doesn't center the item when in landscape. 

May @nbradbury has ideas or a solution to it.

**Comment by nbradbury** [comment]
What exactly is the problem with the stats spinner? Is it the position of the spinner view itself, or the dropdown arrow?

**Comment by daniloercoli** [comment]
Both the stats spinner and the reblog spinner have the same problems when in landscape:
- The text is not vertically centered with the back icon
- The dropdown arrow is on the edge
![8f182f2e-0ec4-11e5-80db-79424144f8f7](https://cloud.githubusercontent.com/assets/518232/8102144/0d6ee868-101e-11e5-9ffe-8acc3f729ab6.png)

Seems that the whole item within the spinner is slightly pushed down.

**Comment by nbradbury** [comment]
Strange, I'm not seeing that at all on either a Nexus 10 running Lollipop or a Nexus 7 running API 18. What device/version are you using?

![stats](https://cloud.githubusercontent.com/assets/3903757/8114289/85557eaa-1041-11e5-9cac-33347987d7d6.png)

![reblog](https://cloud.githubusercontent.com/assets/3903757/8114294/89e93042-1041-11e5-8733-89dfc398d486.png)

**Comment by roundhill** [comment]
I see it on my Sony z3 compact, running 5.0.2. It is a 720p display.

**Comment by daniloercoli** [comment]
- Wiko Ridge running 4.4.4
- Genymotion Nexus 6 running 5.0.0

**Comment by nbradbury** [comment]
Oh, I was trying solely on tablets - now I see the problem. Try changing the `layout_height` in [toolbar_spinner.xml](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/toolbar_spinner.xml#L10) to `match_parent`.

**Comment by daniloercoli** [comment]
That does seem to fix the issue! Kudos to @nbradbury.
