### ISSUE TITLE
Searching and selecting non-visible site does not allow you to 'Visit Site'

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#2817]
Repro Steps:

1. Hide site A
2. In `SitePickerActivity` click the search icon and search for/select site A.
3. Click 'View Site'

Expected:
WebView of current blog is shown

Current behavior:
WebView of first visible blog is shown

**Comment by daniloercoli** [comment]
In `develop` searching and selecting a non-visible site doesn't allow to view Stats/Media and other action on the just selected blog.

**Comment by nbradbury** [comment]
Perhaps selecting a hidden site from the search results should make it
visible?

**Comment by daniloercoli** [comment]
@nbradbury Yes that was I suggested in the PR available here https://github.com/wordpress-mobile/WordPress-Android/pull/2815 

Btw, that PR does fix all the issues with hidden sites.

**Comment by kwonye** [comment]
@nbradbury @daniloercoli @maxme That's 3 for making it visible when selected. I'll change it to do that
