### ISSUE TITLE
Jetpack sites: site icon doesn't show up in sites list

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#2822]
In Site picker & Blog detail pages the custom site icon selected in the Jetpack sites are not showing up currently. It's due to constructing a gravatar url for the site address and not using what the REST api returns for the site icon.

**Comment by oguzkocer** [comment]
I was working on the `issue/2822-jetpack-site-icon` branch for this issue. I was close to a full implementation and we decided to postpone this for a later time. Here is the reason:

The REST api is currently not used by Jetpack blogs within the app and since the icon url is received through the REST api, the issue was a challenging one from the start. Since there was no perfect solution for it (at least as far as we could come up with), we wanted to save the Jetpack blogs we receive from the REST api and save them to the database as disabled blogs which means they wouldn't show up in the site picker hence no duplication. When we needed to find the site icon, we'd need to make an extra query to the db and find the Jetpack counterpart of the icon and return that. As you can tell, this was a big hack and wasn't really worth the trouble. I've also encountered some unexpected issues and the last one was, I was unable to add a self-hosted blog (Jetpack powered one) after the initial list is received from the REST api.

An alternative solution would have been to find the self-hosted counterpart of a Jetpack blog when we receive it from the REST api, and just override the site icon. It probably could work a little better, but I don't think it's a good solution either.

I've also learned yesterday that there is [an issue](https://core.trac.wordpress.org/ticket/16434) for the core WordPress to add support for the site-icon which will complicate things a little more. So, we are postponing this issue until the REST api is supported for Jetpack blogs. Since it's a small issue, I think it's worth waiting to implement a good solution rather than hack it right away.

/cc @maxme & @beaulebens

**Comment by dbspringer** [comment]
Any chance we can revisit this now that Site Icon is a part of core?

**Comment by oguzkocer** [comment]
I think the Jetpack blogs are still not implemented yet which means it'll still be hacky to add the site icon in the current situation. @maxme can verify that. I can have another look at it once I get a little bit extra time though.

**Comment by oguzkocer** [comment]
I think I was wrong about this in my previous comment, Jetpack implementation shouldn't really affect this actually when I think about this a little bit. So, I'll look at this again whenever I can spare some time which might be in a while. Thanks for bringing this up @dbspringer!

**Comment by rachelmcr** [comment]
Just noting that I checked in the latest beta (5.0-rc-2) and confirmed that Jetpack site icons don't show up there. (However, they are currently supported in the iOS app and Calypso.)

**Comment by oguzkocer** [comment]
I took another stab at this issue and I am sorry to report that we still can't find a good solution for this. The core has added the site icon https://make.wordpress.org/core/2015/07/27/site-icon/ however, it's still not served through xml-rpc api. @daniloercoli mentioned that he might be able to send a patch for the api addition, but even if he does it'll probably take some time to get it merged. This is the self-hosted side of things.

For Jetpack blogs, we are still not using the REST api, so we still don't have access to site icon data. However, in the following days @maxme's team will start working on the new network layer, so after that we might be able to finally switch to REST for Jetpack blogs.

When either of those 2 cases happen, I'll grab the issue again. Thanks for your patience!

/cc @astralbodies

**Comment by daniloercoli** [comment]
@oguzkocer - The core patch is here https://core.trac.wordpress.org/ticket/36030
If it gets merged in core, we can show the correct `site_icon` for all .org sites, Jetpack'ed or not. (XML-RPC Layer).

Note for .com: When the patch will get merged on core, we may want to add a filter on WPCOM. That filter fills in the `site_icon` option with the blavatar value. In this way we've the correct icon exposed on the XML-RPC layer even on wpcom. If we switch to REST before the merge, the filter is not needed.

**Comment by maxme** [comment]
> Note for .com: When the patch will get merged on core, we may want to add a filter on WPCOM. That filter fills in the site_icon option with the blavatar value. In this way we've the correct icon exposed on the XML-RPC layer even on wpcom. If we switch to REST before the merge, the filter is not needed.

I think, it's not necessary (for us at least), wpcom sites are fetched from [a REST call](https://github.com/wordpress-mobile/WordPress-Android/blob/72de10c5c13705dda9c735cd85e972870f5ce2b7/WordPress/src/main/java/org/wordpress/android/ui/accounts/helpers/FetchBlogListWPCom.java#L62-L62) already.

**Comment by daniloercoli** [comment]
Better :) 
Edited my comment above.

**Comment by maxme** [comment]
This should be fixed for jetpack site with FluxC integration (added the flux-obsolete label).

**Comment by lancewillett** [comment]
Noticed this today in dogfooding the alpha-32 version of the app on a Nexus 6P device.

Notably only my Jetpack sites don't have Site Icons.

Lots of work is happening over in Calypso to enable core WP site icons via site settings and Customizer, see <a href="https://github.com/Automattic/wp-calypso/milestone/119">the milestone</a> — so this could be more relevant soon as we try to close the UX gap between WordPress.com and Jetpack.
