### ISSUE TITLE
Drop reader reblog

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2831]
Reblogging is being dropped from the reader on all platforms. It may come back at some point, but not until after some serious re-thinking and re-designing.

~~Note: don't work on this until after #2828 has been merged.~~

**Comment by nbradbury** [comment]
[Related iOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3852)

**Comment by ChrissiePollock** [comment]
Users are noting this is missing and asking for it back such as https://automattic.helpshift.com/admin/issue/54782/
