### ISSUE TITLE
Add WebP image format support

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2885]
[MediaUtils](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java#L37) shows [_.webp_](https://developers.google.com/speed/webp/) images are not yet recognized. They are [available in API 14+](http://developer.android.com/guide/appendix/media-formats.html) so we should be able to add support.

**Comment by hypest** [comment]
I think the backend doesn't support `webp` yet so, we might want to postpone adding support on the mobile as well.

**Comment by tonyr59h** [comment]
> I think the backend doesn't support webp yet so, we might want to postpone adding support on the mobile as well.

Just updating that this is still the case. Going to close out this issue, we can revisit once it's supported.

**Comment by designsimply** [comment]
Re-opening because this came up in an app review and because I researched and found that support for the WepP image format was announced for WordPress.com in Dec 2015 at https://wordpress.com/blog/2015/12/04/webp-images-support/

App review quote for reference:

> Thank you for this update ! But I wonder why webp pictures are not available to upload ? 

* Version tested: 14.7-rc-2
* Device P20 (HWEML)
* OS Android 9

**Comment by designsimply** [comment]
Possibly related: https://core.trac.wordpress.org/ticket/35725#comment:17.

**Comment by reginabally** [comment]
From app review:

> I have allowed to upload .webp images to the site, but I cannot upload them through the application. Uploading images through a browser works

Date of the review: Oct 10, 2020, 21:15
Rating: 4 stars
No device, OS, and app version recorded.

**Comment by hypest** [comment]
WebP support will be [part of WordPress 5.8](https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/) so, we should consider adding support to the apps as well. cc @yaelirub for routing.

**Comment by yaelirub** [comment]
Thanks for the ping @hypest! @leandroalonso , can you please help to add support for .webp ?

**Comment by leandroalonso** [comment]
Sure, @ashiagr will help us with it. :)

**Comment by eduardozulian** [comment]
A two-star app review from Jun 15, 2021:

> App dont support .webp images

**Comment by ashiagr** [comment]
👋

After preliminary investigation, found that [WordPress Core 5.8](https://make.wordpress.org/core/5-8/) supports [webp mimetype](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/functions.php#L3147) but it is [not merged with our backend](https://opengrok.a8c.com/source/history/trunk/wp-includes/functions.php) yet. I see the last merge is `Core Merge 5.7`. So the `webp` mime-type is still not available to us.

![webp-support](https://user-images.githubusercontent.com/1405144/122545523-8f494380-d04b-11eb-8052-0da43cb123c1.png)

Also checked Calypso, it still gives this error:
<img width="792" alt="webp_not suported" src="https://user-images.githubusercontent.com/1405144/122544834-d256e700-d04a-11eb-9135-f2c13ec538db.png">

Will keep an eye on it, and enable it whenever it gets available.

cc @leandroalonso, @yaelirub, @hypest

**Comment by ashiagr** [comment]
Tracking via https://github.com/Automattic/jetpack/issues/19654
