### ISSUE TITLE
Notifications settings blank

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2905]
In develop, the notifications settings fragment is blank, I think this is a result of the changes to the pin lock library integration.

**Comment by kwonye** [comment]
addressed in #2908

**Comment by maxme** [comment]
FYI, we had one report on the beta https://photos.google.com/share/AF1QipPjzGZG4CZTII5STDe9VbYs3gvj0j-X0sb1RueaMp7axbekJtkEt2QEdwVUvESykg/photo/AF1QipNfppziTiFt-cNSP8NkqynvhociAxwxKQxaqwbp?key=T2NSaUV5Szh1cW90eGlUaTczc29FSGtiVkNzVlZn

**Comment by kwonye** [comment]
@maxme Thanks! It's fixed on 4.2 release.
