### ISSUE TITLE
Repo download is large

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2914]
We can take a few steps to decrease the download size of this git repo:

 * Set the start of the repo to some time after we stopped committing the `build` (or maybe `bin`) folder. This happened many years ago, and we can always go back to the svn repo if we need to see an earlier commit (which is highly unlikely I think)
 * Remove the `libs/*.jar` files from the history

**Comment by maxme** [comment]
Versions: 110 (2.8.1), 85 (2.5.1) and 77 (2.4.5) are still published in the Store (and are being used by some devices running old Android versions). These versions need `libs/*.jar`, so we should keep this directory.

It looks like we can safely remove the `/build/` and `/bin/` (used in wpToGo) directories.

Also users can shallow clone the repo using the `--depth` option, for instance:

    git clone --depth 10 https://github.com/wordpress-mobile/WordPress-Android.git

To clone and fetch the 10 last commits from the main (`develop`) branch.

**Comment by maxme** [comment]
So I tried [bfg](https://rtyley.github.io/bfg-repo-cleaner/) to remove `bin` using the following command:

    bfg --delete-folders "bin" --delete-files "bin" WordPress-Android.git

it removes files from 256 commits and makes the repo 7Mb smaller. IMHO, that's not interesting enough to change all our git history, break forks and need to rebase all opened branches.

Note: nothing was found when trying to delete "build/".
