### ISSUE TITLE
Post content can be lost if you publish before editor loads images

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2926]
1. Add a lot of images (I tested with 15) to a new post.
2. Save the post as a draft.
3. Edit the post again. Quick! Before the images load in the content area, press `Publish`.
4. The post will be uploaded empty, because the app grabs whatever is in the `EditText` and uploads it (which is nothing because the content loading task hasn't finished yet)

Pretty simple solution would be to just disable the Publish/Save button until the content loading task completes.

**Comment by kwonye** [comment]
Slightly related: wordpress-mobile/MediaPicker-Android#25

I cannot repro due to that bug. Will fix that before looking at this.

**Comment by sandymcfadden** [comment]
I just had another report of this happening. Are there any updates to it? I see the last milestone was 4.5

**Comment by maxme** [comment]
> I just had another report of this happening. Are there any updates to it?

The new editor will fix this problem, media will be uploaded when the user adds it to the post and a post can't be published if a media is not fully uploaded. 

If this is not a common problem, I think we should wait for the new editor to be released.

**Comment by rachelmcr** [comment]
>If this is not a common problem, I think we should wait for the new editor to be released.

Agreed. This doesn't seem like a common enough issue to spend time resolving it before the new editor is released.

**Comment by daniloercoli** [comment]
Closing this ticket, since the "new" (that soon will be called "old" again) editor fixed the problem.
