### ISSUE TITLE
Can't Choose to Trush Self Signed SSL 

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-Android#2927]
I've had a few reports and have now tested on a couple of test sites.
When you input your credentials it asks if you want to see details, and either accept or not accept the certificate.
Details shows a blank screen and choosing Yes to accept just brings back the same message again.
This is an example line from the app logs:
SSLHandshakeException failed. Erroneous SSL certificate detected.

**Comment by maxme** [comment]
Yes, just confirmed self signed SSL fell in an endless "Trust this certificate" -> "Yes" loop

**Comment by daniloercoli** [comment]
Addressed in #3150
