### ISSUE TITLE
Dividers in Notifications list are off for unread notifications

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2938]
![screen shot 2015-07-01 at 10 34 05](https://cloud.githubusercontent.com/assets/518232/8450913/4ded6858-1fdf-11e5-8b1f-7c8a79d29e76.png)

/cc @roundhill

**Comment by roundhill** [comment]
I think they're supposed to be inset like that, but it does look a little off since we recently added that blue background to the right and left side. What say you, @drw158?

**Comment by drw158** [comment]
Oh, I suppose the left and right margins got added when the tab design was implemented...

My first preference is to remove the left and right margins and make it full width. I don't see any reason to keep them, since we aren't using cards or anything like that. They aren't serving a purpose here.
