### ISSUE TITLE
"Your Stats are booming" Notification doesn't open native stats

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2939]
![stats-booming-issue-01](https://cloud.githubusercontent.com/assets/518232/8451037/4337da8c-1fe0-11e5-9a95-0d06a11eb879.gif)

**Comment by daniloercoli** [comment]
Hey @roundhill - What is the status of this? (If you remember it needs to be fixed server side).

**Comment by roundhill** [comment]
@daniloercoli sorry, was out last week. I believe @dmsnell was having a look at this.

**Comment by roundhill** [comment]
Hey @dmsnell I think you said you couldn't reproduce this? Any insight?

**Comment by roundhill** [comment]
Fixed on wp.com
