### ISSUE TITLE
Media grid spinner hacks

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2945]
MediaGridFragment uses a series of hacks to prevent the spinner listener from firing when the selection is made programmatically. and to avoid it firing when ActionMode is enabled. See [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java#L173) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/media_grid_fragment.xml#L22) and likely elsewhere.

Hat tip to @fliespl for noticing this problem in #2901.

**Comment by rachelmcr** [comment]
Just a quick update that I double-checked and the hacks are still in place in the current version of the app.

**Comment by nbradbury** [comment]
Note: it would be nice to replace the spinner with something that doesn't take up so much space that could be devoted to photos. Moving the filters to the options menu, perhaps?

**Comment by nbradbury** [comment]
No longer an issue due to recent changes, including #5366 and #5363
