### ISSUE TITLE
Images are always uploaded with SEO unfriendly filenames

### ISSUE THREAD

**Issue by gerdneuman** [wordpress-mobile/WordPress-Android#2946]
The only thing that stops me from using the WordPress App instead of Desktop browser is that image files are always uploaded with names like `wpid-<date>_<time>.jpg`, e.g. wpid-20150624_152545.jpg to wordpress media. 

So whatever SEO sensitive filename I pick for an image (I rename them earlier using another app), the WordPress Android app always overrides the name with this "meaningless" id. Afterwards there is no way of renaming the image filename in the app.

So during travelling I use the app to create blog posts, which I then afterwards I have to manually swap all the images just to have them with proper names.

I think there whould be an easy solution:
a) Either just use the original image filename and do not change it to `wpid-<date>_<time>.jpg`
b) Add a way one can edit the image filename during uploading it

**Comment by rachelmcr** [comment]
Thanks for bringing this up! I'm closing this duplicate issue and moving your comments here: https://github.com/wordpress-mobile/WordPress-Android/issues/2620
