### ISSUE TITLE
[Feature request] Login through link

### ISSUE THREAD

**Issue by TheLastProject** [wordpress-mobile/WordPress-Android#2961]
It would be nice to be able to login upon following a specifically formatted link.

As an example, for user "example" with password "pass" on a WordPress instance installed on "https://example.com/wp", the following URL could be created: `wordpress:example:pass@https://example.com/wp`.

Upon following the link, the login screen would be opened in the WordPress app with the data pre-filled:
![screenshot_2015-07-08-16-17-45](https://cloud.githubusercontent.com/assets/1885159/8572476/241515b8-258d-11e5-91d6-aa201ad92b29.png)

WordPress installations (or other systems wanting to make it easier for users to use their WordPress installation on their smartphone) could then show a QR code with this link on a page, allowing users to simply scan it to start using WordPress on their smartphone as well.

**Comment by maxme** [comment]
This is a good idea, passing the password is probably not a good idea though. We could use a temporary token for logging the user in, but that would need a new WordPress endpoint.

We could support at least support something like `wordpress://signin/?url=https://example.com/wp&username=example`.

Note: we could also use the referrer data when redirecting the user to install the app, adding a one step "install and signin" button to a WordPress site.
