### ISSUE TITLE
Best Views Ever color and All-time numbers  section

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#2967]
@daniloercoli 

The All-time numbers has too much extra space around them especially on tablet (landscape). Can we have it display 4 columns?

![screenshot 2015-07-10 10 47 59](https://cloud.githubusercontent.com/assets/4924246/8625253/76585982-26f2-11e5-8293-d6eabd90b326.png)

A couple other things on All-time:

1. Thin gray dividers are missing
2. "Best Views Ever" color needs to be yellow `#f0b849`. We're using `$alert-yellow`, not `$orange-jazzy`

![screenshot 2015-07-10 10 58 11](https://cloud.githubusercontent.com/assets/4924246/8625287/b192677c-26f2-11e5-8788-5dd15b90e8e8.png)

Thanks!

**Comment by daniloercoli** [comment]
> "Best Views Ever" color needs to be yellow #f0b849. We're using $alert-yellow, not $orange-jazzy
Right, but now that I changed the color of the label to yellow we need new icon...

![screen shot 2015-07-11 at 11 21 43](https://cloud.githubusercontent.com/assets/518232/8633248/222e75da-27bf-11e5-9a2d-6aacc3f19abd.png)


The one I used is "drawable/ic_action_like_active". Maybe it's the time to switch to the trophy icon?

**Comment by daniloercoli** [comment]
Below is a preview of the "All-time" module displayed in 4-columns for tablets.
![screen shot 2015-07-11 at 11 53 35](https://cloud.githubusercontent.com/assets/518232/8633345/8b647140-27c3-11e5-8888-87e899437cf0.png)

**Comment by jancavan** [comment]
@daniloercoli Thanks for updating the color. Yes, it actually needs to be changed to the trophy icon. Thanks for pointing that out! I'll get the new icon to you shortly.

**Comment by jancavan** [comment]
@daniloercoli here are trophy icons https://cloudup.com/cFj0IL19lYj

Preview looks good so far. Let me know when you have the branch already so I can take a look at it. Thanks!

**Comment by daniloercoli** [comment]
Thank you @jancavan!
I'm ready for a new PR that includes these changes, but we need to wait that the "2-columns layout" PR be merged in develop. Will ping you in the PR when it will be ready.

![screen shot 2015-07-14 at 16 30 20](https://cloud.githubusercontent.com/assets/518232/8675722/d632acf8-2a45-11e5-8ed5-c471f1b84960.png)

**Comment by daniloercoli** [comment]
@jancavan - The PR is almost ready, but I noticed an issue with the trophy icon when used in the single post stats details screen.

![screen shot 2015-07-15 at 12 26 29](https://cloud.githubusercontent.com/assets/518232/8696448/ab7af8a6-2aec-11e5-96ef-b3437e08a4d7.png)

Seems that the device upscales the icon resulting in a fuzzy picture.

I'd like to try with new images at the following sizes:
hdpi - 48px
xhdpi - 64px
xxhdpi - 96px

**Comment by jancavan** [comment]
@daniloercoli Let me know if these work: https://cloudup.com/cLgWZ_scjY5

**Comment by daniloercoli** [comment]
@jancavan - New icons are OK!
