### ISSUE TITLE
Pull to refresh icon is clipped on Post list

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2970]
Looks like the [PTR view is clipped](https://cldup.com/WudgvawHzL.png) since the Post Calypsoification.

**Comment by nbradbury** [comment]
Looks like this is caused by a [poorly-placed margin](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/post_list_fragment.xml#L45) on my part.
