### ISSUE TITLE
Highlights weekend bars in the graph

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2982]
Title has it.

![screen shot 2015-07-16 at 12 20 51](https://cloud.githubusercontent.com/assets/518232/8720763/0c417228-2bb5-11e5-9882-1288b94e8be3.png)
![screen shot 2015-07-16 at 12 21 15](https://cloud.githubusercontent.com/assets/518232/8720774/1b7db0da-2bb5-11e5-9596-fd95cd372edb.png)

**Comment by astralbodies** [comment]
How many bars max does Android have? I think iOS is still at 7 on iPhone and 12 on iPad.

**Comment by daniloercoli** [comment]
Depends on the resolution of the devices. I tried to stay close to the web version.
<b>Devices with 720DP or more</b>
Landscape ---> 15 items in the graph.
Portrait ---> 10 items in the graph.

<b>Devices with 600DP or more</b>
Landscape & Portrait ---> 10 items in the graph.

<b>Devices less than 600DP</b>
Landscape & Portrait ---> 7 items in the graph.

**Comment by astralbodies** [comment]
Okay so not extraordinarily different than iOS at the moment. Good to know. 

@isaackeyet or @jancavan what was the ultimate vision for the mobile platforms? Scrolling graph to show more bars?

**Comment by isaackeyet** [comment]
I think scrolling bars is really the only way to go. Load X on initial load, then immediately another batch, and then wait for scrolling to load any more. That way we can comply with touch target standards and be consistent about the number of bars we have available across devices. Of course there's some UX problems around both discovery and interaction there that would have to be fleshed out, but if either of you are ready to bite the bullet maybe it's time to do the work and make it happen.
