### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Stackflood** [wordpress-mobile/WordPress-Android#3008]
Notifications not showing up ["No Notifications"] while running the code in android studio and app on a Mobile device [Xiaomi MI3] , but showing up in the actual app [downloaded from Google Play Store]. Are there some settings in the code to work this out. Both are latest versions.

**Comment by roundhill** [comment]
You'll need to create your own dev app and get an id and token at https://developer.wordpress.com/apps

Then you can add those to `wp.OAUTH.APP.ID` and wp.OAUTH.APP.SECRET` in `/WordPress/gradle.properties`

**Comment by Stackflood** [comment]
Thanks for the reply @roundhill . I did add the gradle.properties file to the downloaded WordPress Project. Please check my gradle.properties file. 

wp.oauth.app_id = XYZ [hidden]
wp.oauth.app_secret = ABC [hidden]
wp.oauth.redirect_uri = http://android.wordpress.org/
wp.gcm.id = wordpress
wp.db_secret = wordpress
wp.mixpanel_token = wordpress
wp.simperium.app_secret = wordpress
wp.simperium.app_name = wordpress
wp.helpshift.api.key = wordpress
wp.helpshift.api.domain = wordpress.org
wp.helpshift.api.id = wordpress



Does this has anything to do with :

wp.simperium.app_secret = wordpress
wp.simperium.app_name = wordpress ?

P.S : I am able to see all my posts.

**Comment by roundhill** [comment]
Oh, you're right. Yeah, notifications uses simperium and we can't provide the secrets for that so it means you won't see them when building the app locally.

**Comment by Stackflood** [comment]
I am learning and simultaneously implementing things in my project using excellent code written in WordPress. Can you suggest some workaround for it ?

**Comment by roundhill** [comment]
No workaround, I'm afraid. Unless you wanted to re-code the Notifications area to use the WordPress.com REST API instead of Simperium...

**Comment by Stackflood** [comment]
Ok, may be pre-simperium versions like 2.8 and smaller can help ?

**Comment by roundhill** [comment]
That might work, you can give that a try. Going to close this for now, if you need further assistance please join the #mobile channel on WordPress Slack: https://make.wordpress.org/chat/

**Comment by Stackflood** [comment]
Thanks.
