### ISSUE TITLE
No post search

### ISSUE THREAD

**Issue by oquidave** [wordpress-mobile/WordPress-Android#3010]
Hey guys. I totally love the Android App. Very few bugs if any i've discovered. However, am appealed that there's still no post search. That means that the user has to scroll through hundreds or thousands of posts just to edit an old post. 

This is a feature request Please.

**Comment by maxme** [comment]
This should be implemented soon as a wordpress.com only feature (wporg API doesn't support searching posts), you can follow Post list enhancement list on this ticket: https://github.com/wordpress-mobile/WordPress-Android/issues/2793
