### ISSUE TITLE
Unify post preview

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3016]
Right now the app provides two different post previews:
1. [PostPreviewActivity](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewActivity.java), which is used from the post list
2. [EditPostPreviewFragment](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java), which is used from the post editor

The new [PostPreviewFragment](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewFragment.java) was written with this re-use in mind, so unifying the two shouldn't be much of an effort.

Note: Wait for #3015 to be merged before working on this.

**Comment by maxme** [comment]
Note that the visual editor won't need a post preview screen, but since we're going to keep the legacy editor as a backup *PostPreview* can't be dropped completely.

**Comment by maxme** [comment]
Closing this, we won't unify the previews, but we'll drop the "EditPostPreviewFragment" when we drop the legacy editor. I think we should also drop the PostPreviewActivity since it doesn't add anything valuable compared to the editor view.
