### ISSUE TITLE
New Post List Design Tweaks

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3019]
There's a few color issues w/ the new posts list (which is looking awesome!)

* The footer background color should be `#f3f6f8`
* The footer button icon and text should `#0087be`
* The 'More' button icon should be centered vertically w/ the text: 
<img width="328" alt="screen shot 2015-07-28 at 10 17 49 am" src="https://cloud.githubusercontent.com/assets/789137/8938188/f53f1c04-3511-11e5-90b7-1b76b2322756.png">

**Comment by nbradbury** [comment]
Closed via #3020
