### ISSUE TITLE
Skip Jetpack setup on NUX

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3023]
Android version of wordpress-mobile/WordPress-iOS#3627 (cc: @folletto)

**Comment by lancewillett** [comment]
Big :+1: to this. It's confusing how sites aren't added automatically here. It'd make for a much more seamless experience across web, desktop, and mobile apps.

**Comment by lancewillett** [comment]
Another +1 (I know, I know) — saw this *again* yesterday in testing out an alpha version of the app and it was jarring because the other apps and WordPress.com both work so smoothly with new Jetpack sites now.

**Comment by rachelmcr** [comment]
Just a note that we are currently working on the foundation required for this change (integrating WPStores into WPAndroid, `feature/wpstores-integration`). Once that is done we will have the ability to address this issue.
