### ISSUE TITLE
wordpress build error

### ISSUE THREAD

**Issue by ronanhardiman** [wordpress-mobile/WordPress-Android#3024]
after  gradlew clean 
build error:
D:\androidcode\WordPress-Android\WordPress\build\intermediates\res\vanilla\debug\drawable-hdpi-v4\action_mode_confirm_checkmark.png: error: Duplicate file.
D:\androidcode\WordPress-Android\WordPress\build\intermediates\res\vanilla\debug\drawable-hdpi\action_mode_confirm_checkmark.png: Original is here. The version qualifier may be implied.

Error:Execution failed for task ':WordPress:processVanillaDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'G:\Android\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

after delete action_mode_confirm_checkmark.png int WordPress but  after build another image Duplicate...
 
@roundhill

thanks

**Comment by roundhill** [comment]
Please hop on the #mobile channel on the WordPress slack and we can help you out there: https://make.wordpress.org/chat/

**Comment by ronanhardiman** [comment]
thank you
