### ISSUE TITLE
Calypso reader: card redesign

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3037]
* Remove follow button
* Add follow to "..." menu
* Move timestamp to below blog name
* Hyperlink color for blog name
* Primary tag appears in footer
* New comment, follow and like icons
* Show blavatar rather than gravatar
* Show headers even in blog preview
* Blog preview follow should be standard action item (ie: white text only)
* Remove blog/tag preview headers, just show blog/tag name in toolbar
* Tentative: show word count (requires endpoint change)

**Comment by tonyr59h** [comment]
Addressed in #3061, closing.
