### ISSUE TITLE
Restore shadow below ActionBar

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3058]
We should remove `setElevation(0.0f)` from the Activities that are calling it and allow Android to determine the elevation of the ActionBar for consistency.

Note to implementer: double check API20-. If they get a shadow when elevation is explicitly set then we should use `setElevation(getResources().getDimen(R.dimen.appbar_elevation))`. If they can't draw a shadow just remove the `setElevation(0.0f)` call altogether.

(list stolen from #2389)

* Post editor
* Post settings
* Post categories
* Post preview
* Comment editor
* Stats detail
* Settings
* Settings > Show/hide blogs
* Settings > Single blog settings
* Settings > Manage notifications
* Settings > Licenses
* Application log

**Comment by kwonye** [comment]
:shipit:
