### ISSUE TITLE
Post with Video should use [Video] tag

### ISSUE THREAD

**Issue by Torbe** [wordpress-mobile/WordPress-Android#3066]
Currently when adding a video to a post, the resulting html looks like:
```html
<a href="http://SOMEVIDEOFILE.mp4"><img class="alignnone size-full" title="Video" src="http://SOMEVIDEOFILE.mp4" alt="image" /></a>
```
It should rather be a WP-Shortcode like
```html
[video mp4="http://SOMEVIDEOFILE.mp4"][/video]
```

**Comment by maxme** [comment]
This will be implemented when video upload is integrated in the new post editor, you can track the progress of this feature here: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/121
