### ISSUE TITLE
No Connection bar will persist (in some circumstances) when regaining connection

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3073]
Repro:
- Start app with connection
- Disable connection so that bar appears
- Background app, then force quit app (swipe from backstack)
- Start app
- Re-enable connection

Connection bar persists but app functions as expected. Probably some initial state funkiness that is used to show/hide the connection bar.

**Comment by nbradbury** [comment]
I'm not able to reproduce this. Is it possible the connection hasn't been restored by the time you restart the app? For example, it can take a few seconds to restore the connection if you disable then re-enable airplane mode.

**Comment by tonyr59h** [comment]
I missed a step at the end there! I'm still able to consistently reproduce it on the HTC One and Galaxy S3. I can post a video if that would help.

**Comment by nbradbury** [comment]
Ah, I see the problem now and it's a simple fix. I'll submit a PR shortly.
