### ISSUE TITLE
The image can not scroll horizontal direction at Nexus 7

### ISSUE THREAD

**Issue by oldcwj** [wordpress-mobile/WordPress-Android#3076]
Device:Nexus 7
1. select MySiteFragment
2. select Blog Posts
3. select my post which has image
![screenshot_2015-08-16-09-19-58 0](https://cloud.githubusercontent.com/assets/262734/9291572/c2397ffe-43fb-11e5-8e0c-01e0d0ec59f0.png)
4. touch the image
![screenshot_2015-08-16-09-19-23 0](https://cloud.githubusercontent.com/assets/262734/9291573/d1ddd9c8-43fb-11e5-9249-fc8da4dfe0cc.png)
5. can not scroll horizontal

**Comment by maxme** [comment]
We changed the Post List view in version 4.4. The preview won't be shown right to the Post List anymore on tablets. And this problem won't exist (when you tap the image on a fullscreen preview you can scroll horizontally or vertically).
