### ISSUE TITLE
Tapping a tab icon calls onTabReselected and makes the view scrolls to top

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3095]
Demo: https://cloudup.com/cXvvwrLe6KK

Probably a bug in the support library v22: https://code.google.com/p/android/issues/detail?id=177189 - looks like it's fixed in v23.

**Comment by maxme** [comment]
confirmed: support v23 fixes the problem.
I'm going to update support libraries in https://github.com/wordpress-mobile/WordPress-Android/pull/2795 since android gradle plugin 1.3.x is required for that update.

**Comment by nbradbury** [comment]
Closed (fixed) via #3106

**Comment by maxme** [comment]
Problem came back with support libs v23.0.1  :/
