### ISSUE TITLE
Posts: Gallery preview

### ISSUE THREAD

**Issue by ockham** [wordpress-mobile/WordPress-Android#3114]
Running the latest beta, this is what I'm currently seeing in the 'Posts' view with posts containing only galleries (and no text at all):

![screenshot_2015-08-28-17-39-11](https://cloud.githubusercontent.com/assets/96308/9577936/06e60816-4fe6-11e5-95b8-efe88b18230d.png)

It would be nice to see the actual galleries instead of the shortcodes.

**Comment by maxme** [comment]
I'm not sure we should show actual galleries here in the list previews, maybe strip the tag to `[gallery]` only

**Comment by maxme** [comment]
Or remove shortcodes completely.

**Comment by ockham** [comment]
> Or remove shortcodes completely.

Yeah, I think shortcodes might be mistaken for some sort of error message or at least a pretty rough edge by users.
