### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by vastro** [wordpress-mobile/WordPress-Android#3119]
hi guys please help me with this issue
```
Warning:Dependency commons-logging:commons-logging:1.1.1 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.3 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency commons-logging:commons-logging:1.1.1 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.3 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency commons-logging:commons-logging:1.1.1 is ignored for debugAndroidTest as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.
```
can somebody help me?

**Comment by maxme** [comment]
These are only warnings and won't stop the build. If the build stopped, then you should get another error (please post it here).

Note: IIRC, these are transitive dependencies needed by robolectric, they should be gone when we update to the latest editor version https://github.com/wordpress-mobile/WordPress-Editor-Android

**Comment by vastro** [comment]
thanks maxme, it works, and i try installed on my device work like charm. can you give me a link about this open source project that i can understand? i  mean im new here, but i wanna create my own wordpress apps, e book or guide to customization?

**Comment by maxme** [comment]
If you want to help us with the WordPress-Android project, you can join the beta group on our [Google Plus community page](https://plus.google.com/u/0/communities/108813167297661427043), test the app and fill new tickets here when you hit a bug.

You're welcome to join our [public chat room on Slack](https://make.wordpress.org/chat/) (#mobile channel) if you need more details.
