### ISSUE TITLE
Uploaded local drafts duplicated in post list

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3137]
The post list *used* to exclude posts where `(localDraft=1 AND uploaded=1)`, which on the face of it doesn’t make sense  since local drafts by definition haven’t been uploaded. But it turns out that we previously kept these uploaded local drafts in the table (which is why there were excluded!).

Version 4.5 dropped the `uploaded` column but left these "uploaded local drafts" intact. A simple fix should be to perform `DELETE FROM posts WHERE uploaded=1 AND localDraft=1` the first time the app is run (ie: when the db is upgraded). Be sure to wrap this in an exception handler to deal with the case that the `uploaded` column doesn't exist.

**Comment by stephdau** [comment]
Sounds pinpoint accurate to what I've experienced.
