### ISSUE TITLE
Blog settings are not updated anymore when the user switch blogs

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3140]
We're only updating the main user site settings when the user logs in, reason for that: if the user has 200+ sites, we don't want to enqueue 200+ update settings requests.

So previously, we were updating settings when the user switched from a blog to another. I think we should continue to do that. Also, 200+ sites is not common, but some users have several sites, so we should update all settings on login for a maximum of N sites (N=10?).

This issue creates inconsistent view of the "Featured Image" checkbox in image settings, and creates other problems (blog titles are probably never updated).

That could be reason to create a 4.4.2  hotfix.

**Comment by daniloercoli** [comment]
> So previously, we were updating settings when the user switched from a blog to another. I think we should continue to do that.

I agree. I was using 4.4 yesterday and found out that options were never updated for a blog on switching. I had to put the app in background and put it back again, so one of the main RateLimitedTask fired off the getBlogOptions request.

> login for a maximum of N sites (N=10?).

This could be cool, but in which way we select 10 sites? The first 10? Would be awesome to select the most used sites.


> That could be reason to create a 4.4.2 hotfix.
Yes!! Or even add this ticket to the 4.4.1 hotfix. it should be easy if we re-introduce the synch of blog options when the user switches site.

**Comment by maxme** [comment]
> This could be cool, but in which way we select 10 sites? The first 10? Would be awesome to select the most used sites.

* update the first 10, 
* or simply update all sites if number of sites <= 10 (in case > 10, update the first one only).

**Comment by maxme** [comment]
> Or even add this ticket to the 4.4.1 hotfix. it should be easy if we re-introduce the synch of blog options when the user switches site.

4.4.1 has been released already.
