### ISSUE TITLE
(feature request) Press-this-like sharing

### ISSUE THREAD

**Issue by tybor** [wordpress-mobile/WordPress-Android#3149]
"Press this" used on desktop is wonderful while on mobile it isn't that great.
It would be wonderful to give "share with wordpress" a design like "press this", as it would greatly improve its usability.

PS: I searching a little the repo but could't find how to properly post a feature request. Please forgive me as this is this the first time I post at Wordpress-Android repo

**Comment by maxme** [comment]
"Press this" and "Share with WordPress" features are pretty similar. Not sure what you would like to have in "Share with WordPress". 

There is a big UI difference, mainly because there is one more step in "Share with WordPress" to select the blog and type of share (new post / media lib).

**Comment by hypest** [comment]
With the "Share with WordPress" functionality already in place and the lack of extra info about this feature request, I will close this ticket now. Please, feel free to open again and provide extra information on the proposal. Thanks!
