### ISSUE TITLE
Category with quotes not added to the post

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3152]
- Create a new post
- Tap Post Settings and create category in quotation marks – “test”.
- Make sure this category is added to the post and then publish it.

The category gets created but is not assigned to the post.

**Comment by maxme** [comment]
Problem comes from [here](https://github.com/wordpress-mobile/WordPress-Android/blob/c2380a734a2dc9a398356682d2ca3330b7c57634/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java#L264) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/a4df50968725142d42617c2a39d4c5884622aea0/WordPress/src/main/java/org/xmlrpc/android/XMLRPCClient.java#L482-482)

`"Test"` is first transformed to `&quot;Top&quot;` and then to `&amp;quot;Top&amp;quot;`

`&quot;Top&quot;` is correct if we send that to the XMLRPC endpoint.

**Comment by maxme** [comment]
Commit that introduced categories html encoding: https://github.com/wordpress-mobile/WordPress-Android/commit/e67b8b1d6281ec1e2a11b2f750309b46ebb4dd51

**Comment by rachelmcr** [comment]
Tested and confirmed that this is still an issue in 4.8-rc-3.

This is also an issue for categories with an apostrophe, as reported by a user.

**Comment by maxme** [comment]
If I remove the `encode` call [here](https://github.com/wordpress-mobile/WordPress-Android/blob/c2380a734a2dc9a398356682d2ca3330b7c57634/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java#L264), I can attach quote or apostrophe categories, but I can't attach categories containing a "&".

**Comment by maxme** [comment]
When I remove the encode call, XMLRPC message is correct (Note that `"` doesn't need to be encoded, while `&` must be encoded):

```
				<member>
						<name>categories</name>
						<value>
							<array>
								<data>
									<value>
										<string>"Top"</string>
									</value>
									<value>
										<string>H&amp;W</string>
									</value>
								</data>
							</array>
						</value>
					</member>
```

So I think [this](https://github.com/wordpress-mobile/WordPress-Android/blob/c2380a734a2dc9a398356682d2ca3330b7c57634/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java#L264) is an incorrect workaround (it should not exist), and the server side category is not corresponding to `H&amp;W`, so it can't be "attached".

**Comment by maxme** [comment]
The problem is server side for sure. When I create a `A&B` category, the XMLRPC call is (interesting bits only):

```
<member>
  <name>name</name>
  <value>
    <string>A&amp;B</string>
  </value>
</member>
```

But the server returns:

```
<member>
  <name>name</name>
  <value>
    <string>A&amp;amp;B</string>
  </value>
</member> 
```

(It's encoded twice)

**Comment by maxme** [comment]
I've checked the iOS app, it's not affected by this issue because it uses `wp.getTerms` while the Android app uses `wp.getCategories`.

They're is no valid workaround for this (we will break either `"` or `&`), we must use `wp.getTerms` (and eventually fix `wp.getCategories`).

**Comment by maxme** [comment]
Ok, so the problem is actually a combination of the the use of `wp.getCategories` and `metaWeblog.editPost` that wants category names and not category id or slug... :cry: 

So to fix that issue we have to switch to `wp.editPost` / `wp.newPost` :cry: (again)

**Comment by aforcier** [comment]
FluxC XML-RPC posts are using `wp.editPost`, `wp-newPost`, and categories will be pulled through `wp.getTerms`, so the FluxC integration should solve this one.

Adding it to my checklist for `TaxonomyStore` integration.

**Comment by aforcier** [comment]
Re-confirmed that this is fixed in the `fluxc-integration` branch.
