### ISSUE TITLE
Themes assets

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3155]
Assets in 36x36, 48x48, 72x72 in PNG format:

* Customize
* Details
* Support
* `gridicons-themes.svg`

Image (any size) of color `Gray color lighten( $gray, 20% )`.
Only requirement is that it's aspect ratio is 1 *0.75

![screen shot 2015-08-07 at 15 51 24](https://cloud.githubusercontent.com/assets/4389/9138503/2d300ba2-3d1c-11e5-9e2c-6d934e55d69c.png)

**Comment by folletto** [comment]
Cool!

I put all the assets in [this dropbox folder](https://www.dropbox.com/sh/edo1jx22fvnnw60/AADsSuVG7qiGVpwO2Ei8NW6Va?dl=0).

![gridicons-customize-72-graydark](https://cloud.githubusercontent.com/assets/4389/9790946/aa4849a0-57d0-11e5-8c8c-8a1528f44d07.png) ![gridicons-details-72-graydark](https://cloud.githubusercontent.com/assets/4389/9790950/ad13a3c8-57d0-11e5-8b73-4c17432eea3f.png) ![gridicons-support-72-graydark](https://cloud.githubusercontent.com/assets/4389/9790951/adf09b48-57d0-11e5-92bc-87ab5d61d44e.png) ![gridicons-themes-72-graylighten30](https://cloud.githubusercontent.com/assets/4389/9790963/bbb51baa-57d0-11e5-8e2f-c497125efd72.png)

The background color is our _Gray Lighten 20_: `#c8d7e1`, you should be able to do the background just by using the icon above and the color, which feels more flexible in the long term, but if you want an actual PNG with that proportions... I added that too to the Dropbox folder.

**Comment by kwonye** [comment]
@folletto, I'm sorry, the customize/detail/support assets are incorrect. My fault as I didn't realize they were different until now.

I cannot locate them, but can I get these assets please?

<img width="663" alt="screen shot 2015-09-15 at 11 21 19 am" src="https://cloud.githubusercontent.com/assets/1158819/9886520/9a5149ca-5b9f-11e5-9163-4402ad69f477.png">

**Comment by folletto** [comment]
They are correct: that's the Gridicons set, which will be updated on web too. So on that side you're a step ahead. ;)
