### ISSUE TITLE
Share feature issue in v. 4.4.+

### ISSUE THREAD

**Issue by JasonSnow-Mad** [wordpress-mobile/WordPress-Android#3160]
The Share button (< icon) when viewing a post from within the WordPress App is no longer functioning the same way in versions 4.4.+ of the WordPress App. 

Where before the feature would use the same functionality of the buttons on the page (including the title and wp.me link), it now displays only the Preview link for the post.

![screenshot_2015-09-09-17-12-12](https://cloud.githubusercontent.com/assets/8810295/9776019/f52f3c08-5708-11e5-923b-295c01f441ba.png)

**Comment by nbradbury** [comment]
@JasonSnow-Mad You're not the only one who has mentioned this! The good news is link shortening will return - see [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3154), which has already been merged with develop.

**Comment by JasonSnow-Mad** [comment]
Gah! I couldn't find it in issues, but forgot to search the PR. Thanks!
