### ISSUE TITLE
Probable race condition with Notification due to deferredInit

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3177]
Since we introduced `deferredInit`, simperium is now initialized [here](https://github.com/wordpress-mobile/WordPress-Android/blob/65399ae2f3c9272b6a7584e79e0f903371af2cbb/WordPress/src/main/java/org/wordpress/android/WordPress.java#L232-232).

Notes bucket is null [here](https://github.com/wordpress-mobile/WordPress-Android/blob/550422097599242efcbcfac7121e1144b6eb1224/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java#L86) and Notifications are not loaded.

Apparently that only happens onResume, but since the app sometimes "starts" onResume, that's maybe not related.

**Comment by maxme** [comment]
cc @roundhill

**Comment by roundhill** [comment]
I think I can fix this by moving a bit of code into `onResume()` of the notifications list fragment. Picking this up.
