### ISSUE TITLE
Add a way to stop Media file uploading

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#318]
We need to add a way to stop pictures uploading in "Media".
I was in "Media", and selected a picture to upload on the blog. Uploading started but I was in an area with poor coverage and it took 10 minutes without the possibility to stop it. 

Also, media library was unresponsive while uploading due to https://github.com/wordpress-mobile/WordPress-Android/issues/226.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
