### ISSUE TITLE
Deferred initialization causes problem with Mixpanel

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3206]
Loading account details is deferred, and may happen after we start tracking events.
Deferred initialization introduced here
https://github.com/wordpress-mobile/WordPress-Android/commit/b3bc0a0626b014a7325875b4c9882d5c85250b22

What's happen in details:
- The commit above does move the loading of the user account on a separate thread. 
- Meanwhile, before the initialization happens, the Analytics libraries could have already tracked some events when the app is in a state where the main .com account is still blank.
- Libraries tracks the user as a new anon user that is later (few events later in Tracks) aliased with the correct .com user

On Tracks we should not have problems (*need to double check this with the team), but in Mixpanel we have problems since the user is tracked as 2 distinct users.

Below is a picture that shows the UNIQUEs in Mixpanel for my account. (already logged in WP).

![screen shot 2015-09-21 at 18 36 58](https://cloud.githubusercontent.com/assets/518232/9998053/c73d117c-608f-11e5-814b-cbfe3e7412af.png)

A Tracks stack trace that shows what's happening:
```
stdClass Object
(
    [events] => Array
        (
            [0] => Array
                (
                    [_ui] => 7ea374d2fc1a48578865941018b62a3c
                    [_en] => wpandroid_notifications_accessed
                    [_ut] => anon
                    [_ts] => 1442852632039
                )

            [1] => Array
                (
                    [_en] => _aliasUser
                    [anonId] => 7ea374d2fc1a48578865941018b62a3c
                    [_ul] => daniloercoli
                    [_ts] => 1442852632383
                )

            [2] => Array
                (
                    [_en] => wpandroid_application_opened
                    [_ul] => daniloercoli
                    [_ts] => 1442852632489
                )

            [3] => Array
                (
                    [_en] => wpandroid_notifications_accessed
                    [_ul] => daniloercoli
                    [_ts] => 1442852632773
                )

            [4] => Array
                (
                    [last_visible_screen] => Notifications
                    [_en] => wpandroid_application_closed
                    [time_in_app] => 3
                    [_ul] => daniloercoli
                    [_ts] => 1442852635782
                )

        )

```

**Comment by daniloercoli** [comment]
Below is a stack trace of a `push_notification_received` event on my (logged to wpcom) account.

```
stdClass Object
(
   [events] => Array
       (
           [0] => Array
               (
                   [_ui] => be5e9b19e473428b808c9a68a437243c
                   [_en] => wpandroid_push_notification_received
                   [_ut] => anon
                   [notification_type] => comment
                   [_ts] => 1442854309542
               )

       )

   [commonProps] => stdClass Object
       (
           [device_info_brand] => WIKO
           ....

       )

)```

**Comment by daniloercoli** [comment]
I think the code here: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L244
```        
 // Refresh account informations
        if (AccountHelper.isSignedInWordPressDotCom()) {
            AccountHelper.getDefaultAccount().fetchAccountDetails();
        }
```
can be easily moved back to the `onCreate` method. It does load the account from a table in the db, and launches an async Volley call.

**Comment by maxme** [comment]
> and launches an async Volley call.

we should avoid any network call from the `App.OnCreate()` - but yes, we should move the default account loading to `App.OnCreate()`

**Comment by maxme** [comment]
I'm pretty sure the problem comes from the deferred call to the init() function [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L213) not from the `AccountHelper.getDefaultAccount()` call (it will load data from the DB on first call)

**Comment by daniloercoli** [comment]
I removed the thread in `initAnalytics` and called it from the main thread. Same issue.

**Comment by daniloercoli** [comment]
Moving the init of Analytics back to the main thread, and adding a call to `refreshMeta` fix the issue.
https://github.com/wordpress-mobile/WordPress-Android/compare/danilo/test-deferred-init?expand=1
