### ISSUE TITLE
Reader: Long tag name can overlap buttons

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3214]
Noticed this post in the Reader had a very long tag, and it overlaps the like/comment buttons:

![screenshot_2015-09-22-08-09-25](https://cloud.githubusercontent.com/assets/789137/10022466/d59a274c-6101-11e5-9364-1b12540f3ef1.png)

**Comment by nbradbury** [comment]
Note that this happens in both the list and detail views.
