### ISSUE TITLE
Login to wpcom doesn't refresh the main tabbed interface

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3222]
I did a couple of logins/logouts and found out that [resetFragments](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L317) doesn't actually recreate new fragments when called.

I set a breakpoint in [WPMainTabAdapter.getItem](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainTabAdapter.java#L53) and it doesn't get called upon login.

Sorry for the long GIF. At the end of the login process you can see that the Sites tab is still empty. Other tabs get populated with a delay (that's because i'm throttling the connection) instead the Sites tab isn't get updated.
![login-logout](https://cloud.githubusercontent.com/assets/518232/10043241/9dcf7cfe-61f1-11e5-9154-03a636f32e4b.gif)

/cc @nbradbury

**Comment by nbradbury** [comment]
Looks like an adapter problem. I changed the main tab adapter from a `FragmentStatePagerAdapter` to a `FragmentPagerAdapter` in this release - if you change it back to a `FragmentStatePagerAdapter` the problem goes away.
