### ISSUE TITLE
Notification stacking issue on 4.5.1

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3223]
Sometimes (?) notifications staking doesn't work, and user gets a growing list of notifications.

I can't repro, but @daniloercoli was affected by the bug too. 

From a Play Store comment:

> Notifications issue. With the latest update the notifications are not aggregated anymore. In a few minutes I had my status bar filled with a ton of notifications; annoying.

I wonder if that could come from this patch https://github.com/wordpress-mobile/WordPress-Android/commit/f8d51086d9ef3fd78d96f3fe3069c3dc8ae22309

**Comment by maxme** [comment]
Created a 4.5.2 milestone for it - feel free to move it to 4.6 if it's a rare issue.

**Comment by daniloercoli** [comment]
I can repro it on 4.4.4.

**Comment by roundhill** [comment]
Investigating! Maybe it only works on lollipop or higher...
