### ISSUE TITLE
Hard to add a self-hosted site when signed into a siteless wp.com account

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3231]
If you first log into a WordPress.com account that has no sites attached to it, trying to add a self hosted site is very difficult because the My Site tabs "Add Site" button in this situation (see screenshot) only enables creating a wp.com blog. Instead, it should show the same menu that the site picker does when you add a site, which enables choosing between creating a wp.com blog and adding a self-hosted one.

![screenshot_2015-09-23-13-18-40](https://cloud.githubusercontent.com/assets/3903757/10057111/9d45cba6-620c-11e5-9e7c-d5bf2c125eb5.png)

**Comment by nbradbury** [comment]
Side note: that FAB shouldn't be there since you can't create a post if you don't have any sites!

**Comment by tonyr59h** [comment]
Addressed in #3232, closing.
