### ISSUE TITLE
Implement posting activity

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Android#3238]
Related: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/263

![2015-06-04_11-15-33](https://cloud.githubusercontent.com/assets/373903/7988828/167d92ec-0aab-11e5-8523-4944d3b6ae2a.png)

Determine an interaction design and visual design for native (and make sure there is some similarity with iOS and the web version). 

cc: @daniloercoli

**Comment by daniloercoli** [comment]
#bug-scrub

There hasn't been any activity on this thread in more than one year. This is a new feature worth pursuing, even though Stats is in pause at the moment, so we may not see any update on this for another couple of months at least.
