### ISSUE TITLE
Reader: handle gaps between posts

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3247]
With high-traffic tags, or with users who don't sync very often, gaps may exist between the most recent existing post and the ones just retrieved from the server. These gaps mean the user is missing posts.

Detect when these gaps occur and provide a way for the user to load the missing posts, similar to how Twitter handles this situation.

See [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/4311) for @aerych's solution to this issue on iOS.

**Comment by maxme** [comment]
Fixed in #3291
