### ISSUE TITLE
Notifications: Allow settings access for wp.com user

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3252]
Notications settings are hidden if there is no push device id. Instead it should just check for a wp.com account, and if there is no device id we can hide the 'app notifications' setting.

**Comment by tonyr59h** [comment]
[This is where](https://github.com/wordpress-mobile/WordPress-Android/blob/a6412f9ff7e8da24066214bb196ae05ec909386a/WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java#L108) it's checking the access token. I think we can use `wpDB.getWPCOMBlogID()` to check for a .com account.

**Comment by roundhill** [comment]
I described this poorly. The issue is that the notification settings don't load unless you have a GCM id stored in the app. That shouldn't be required.
