### ISSUE TITLE
Sign In: Top right Help icon is not right aligned in landscape orientation

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3257]
Nexus 7, OS 5.1.1

To reproduce:
From a fresh install launch the app. 
Dismiss the keyboard and rotate to landscape orientation. 

The top right Help (?) icon stays aligned with the right edge of the text fields rather than the right edge of the screen.  By comparison, if you tap to launch the Help screen, you'll notice the close (X) button is left aligned to the screen edge.

**Comment by maxme** [comment]
IMO that's not an issue. We want all the infos in the login screen to stay in the same "box". While the close button (X) is a standard "back" button on an action bar.

What's your opinion on that @drw158?

**Comment by maxme** [comment]
Well after a test on a 10" tablet, the (X) button feels a bit out of place because there is no distinction between the action bar and the screen (action bar background color is the same that the page background color).

https://cloudup.com/cTaCw5EEDkU

**Comment by drw158** [comment]
I have a preference for an info button that is aligned to the right edge of the screen. It feels a bit off when it is aligned to the text boxes.
