### ISSUE TITLE
Sign in: Bottom of the help screen's close button is cropped when pressed

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3258]
Nexus 7, OS 5.1.1

To reproduce:
From a fresh install, tap the Help button at the top of the sign in screen to launch the Help screen.
Tap the close (X) button. 
Watch closely as the button's tap animates. You'll see the button highlight is cut off at the bottom.

**Comment by maxme** [comment]
This is the normal behavior on flat buttons: see this [video](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFSTNhRndpWXBwRDA/components-buttons-flatbuttons.webm) from the material guidelines

**Comment by aerych** [comment]
> This is the normal behavior on flat buttons: see this video from the material guidelines

That's fair, but the top of the button is not cropped, just the bottom, so it seems a bit unbalanced.

**Comment by maxme** [comment]
> That's fair, but the top of the button is not cropped, just the bottom, so it seems a bit unbalanced.

Not sure to understand, This is what I see when I long tap the (X) button
![screen shot 2015-10-02 at 16 47 14](https://cloud.githubusercontent.com/assets/40213/10249457/b9e32004-6925-11e5-92d8-3db6a0a9b9d8.png)

**Comment by aerych** [comment]
Ah! On my device the top wasn't cropped by the status bar.  I'll post a photo when I have it with me again.

**Comment by aerych** [comment]
> Ah! On my device the top wasn't cropped by the status bar. I'll post a photo when I have it with me again

My Nexus 7 is either trolling me, or I'm imagining things, or both.  :( 

Thanks for being patient @maxme

**Comment by maxme** [comment]
No worries, you need more :coffee: :coffee: :coffee: :coffee: :coffee: :coffee: :coffee:!
