### ISSUE TITLE
Nux: FAQ - offline error message is confusing

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3259]
Nexus 7, OS 5.1.1

To reproduce:
- Be offline. 
- From a fresh install, tap the Help icon to launch the help screen. 
- Tap the "Browse our FAQ" button. 
- When the new Activity loads a toast is displayed reading: "Unable to reach support" 

This is a little confusion since I tapped to view the FAQ not contact "support". Maybe the message could be more specific?

**Comment by maxme** [comment]
I've just checked if we could change that default Helpshift message. We can, it's `hs__could_not_reach_support_msg` but that would change the error message for all "offline" errors in Helpshift (FAQ, contacting support or whatever), so we can't be more specific.
