### ISSUE TITLE
Nux: Create wpcom account, username field keyboard is for URLs

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3260]
Nexus 7, OS 5.1.1

From a fresh install tap to create a new WordPress.com account. 
Tap to edit the username field.  
Notice that the keyboard shown is for a URL. 

Maybe a regular text keyboard would be a better fit?

**Comment by maxme** [comment]
Good catch! Input type for the username field is `textUri`, but it should be`textEmailAddress`.

**Comment by maxme** [comment]
Well actually we changed from `textNoSuggestions` to `textUri` in https://github.com/wordpress-mobile/WordPress-Android/commit/581df5a0d0b39bd6b939af8f8ed200d89b4f44ee - I'm wondering if this is used as a workaround

**Comment by maxme** [comment]
WordPress.com usernames are alphanumeric characters only, so the best keyboard would be alphanumeric only - The best keyboard would be one with no space or special characters, but it doesn't exist. So having `textVisiblePassword|textNoSuggestions` or `textUri` is quite the same...
