### ISSUE TITLE
Reader: UI momentarily frozen on Followed Sites

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3263]
Nexus 4, OS 5.1.1

To reproduce:
Switch to the Reader tab
Tap the gear icon to view the menu. 
Swipe twice right until you are viewing Sites You May Like
Swipe once left to view Followed Sites
The screen is now briefly frozen

Happens when logged in to WPcom and when not.

**Comment by nbradbury** [comment]
I wasn't able to repro the freeze, but I did notice some jank with the ViewPager when running on my N4. Optimizing each fragment's onResume should help.
