### ISSUE TITLE
Comments: Detail view comes back on rotation

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3264]
Nexus 4, OS 5.1.1

To reproduce:
1. Go to the first tab and select Comments.
2. Tap any comment in the list to view its detail. 
3. From the detail, tap the back button to return to the list. 
4. Rotate your device.
5. You are now back on the detail screen. 
6. Tap the back button to return to the list.
7. Rotate your device.
8. Go to step 5.

**Comment by rachelmcr** [comment]
Nice find. Tested and reproduced this with the steps above on 4.8-rc-3, Nexus 9, Android 6.0.

**Comment by nbradbury** [comment]
Note: don't work on this until #3505 is merged.
