### ISSUE TITLE
Reader: Menu allows deleting tags, but they return when refreshed.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3271]
Nexus 4, OS 5.1.1

While signed out,  view the reader and tap the gear icon to view the menu. 
Tap the "X" button on any of the tags under "Followed Tags" to remove it. 
Return to the list and notice that the same tags were removed from the dropdown. 
Tap the gear icon again.
Notice that the deleted tags are restored when the menu syncs.

**Comment by nbradbury** [comment]
The fix for this should be to hide the gear icon when the user is logged out.
