### ISSUE TITLE
Reader: Logged out reader shows text field to follow site/tag

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3273]
Nexus 4, OS 5.1.1

While logged out, view the reader's menu.
Try to add a site or tag via the text field. 
Following a site will fail, but following a tag will appear to succeed, even though the tag does not show up in the list. Interestingly an added tag will be the current topic when you dismiss the menu.

Maybe don't show the text field while logged out?

**Comment by nbradbury** [comment]
What should happen is the reader menu (ie: the gear icon) should be hidden when logged out, so you never get to that screen.

**Comment by aerych** [comment]
Ah! Yes.  I'm too used to the menu behavior on iOS and sometimes forget there selection on Android is done via the dropdown.

**Comment by tonyr59h** [comment]
Addressed in #3277, closing.
