### ISSUE TITLE
Reader: Comment button missing, then appears for previewed Jetpack site.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3276]
Nexus 4, OS 5.1.1

To reproduce.
- I'd started signed into a self-hosted account and later connected to wpcom.
- Choose the notifications tab
- Tap on a "Follow" notification "so and so followed your blog.."
- Tap the notification detail header to preview the site. In this case it was my self-hosted site.
- In the site preview, notice the posts have like buttons but not comment buttons. 
- Tap a like button.  A comment button appears.

**Comment by nbradbury** [comment]
@aerych I'm not able to repro this one. Do you see the same bug when you view the site preview outside of notifications (ie: tap the gear icon in the reader, switch to followed sites, then tap your site in the list)?

**Comment by aerych** [comment]
I can also reproduce it via the Sites I Follow screen. 
Try this:
- Follow ma.tt
- Preview ma.tt by tapping on its entry in the sites list. 
- Notice that there are icons for likes, but not comments. 
- Tap the like button. 

A comment button appears. 
https://cldup.com/zGl4Z_0kAI.mov

**Comment by nbradbury** [comment]
Thanks @aerych - I was able to repro this.
