### ISSUE TITLE
Notifications: Unable to sign in to Jetpack after signing out of wpcom.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3278]
Nexus 4, OS 5.1.1

To reproduce:
- From a fresh install, sign into the app with a self-hosted blog. 
- Switch to the "Me" tab and connect to WordPress.com. I used an account different from the Jetpack account connected to the self-hosted blog. 
- Sign out of WordPress.com.
- Switch to the notifications tab. 

Instead of an option to sign in to use Jetpack, you see a message that says "No notifications"

**Comment by roundhill** [comment]
This was fixed in #3255
