### ISSUE TITLE
Stats: The "Other Recent Stats" label is briefly visible before the first sync

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3279]
Nexus 4, OS 5.1.1

It goes by very quickly, but the "Other Recent Stats" labels are briefly visible at the top of the screen the first time the Stats page is visited. It is hidden as soon as the sync starts.

**Comment by daniloercoli** [comment]
The label is always visible on the screen. The problem are fragments that get created and positioned on the top of the label during startup. I think I need to make the label invisible, and make it visible after "top" fragments are positioned on the screen.
