### ISSUE TITLE
Comments: Images do not show when loaded.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3281]
Nexus 7, OS 5.1.1
(Saw this on the Nexus 4 also)

To reproduce: (there may be other paths)
Tap a comment notification for a comment that you have replied to, and your reply includes images.
In the notification detail, scroll down and tap the "You replied to this comment." message.
You're reply will show up in the list of comments that appears.
Wait a bit.  Notice the images do not load. 
Scroll away from the images and back.  
The images will now appear.

**Comment by rachelmcr** [comment]
I tested this on Nexus 9, OS 6.0, app beta 4.8-rc-1. In my testing, however, the images never loaded even after navigating away and back. I just see a greenish square in their place:

![2015-11-25 16 39 31](https://cloud.githubusercontent.com/assets/8658164/11403155/57390ffc-9393-11e5-9103-99c308d52dcb.png)

Tapping on that square brings up the image full screen, but the image never appears there.
