### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#3286]
Implement team management as part of people management for blogs. Here are the initial screenshots for the feature: https://cloudup.com/cSrd17DVG6r

**Comment by roundhill** [comment]
:+1:

**Comment by oguzkocer** [comment]
Depending on if we'll implement people management for self-hosted users or not (afaik, we'll) we'll decide either we'll use the remote user id or a local db identifier (or possibly keep a reference to the blog and use a combination of remote id and the blog id) for the Person table. I am just making a note of it here and we can think about it when we resume this feature.

**Comment by oguzkocer** [comment]
Closed in #4100.
