### ISSUE TITLE
FAB icon jumps under the snack bar when trashing 2 posts in a row

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3305]
Demo: https://cloudup.com/cx675nqeZtR

**Comment by maxme** [comment]
I wonder if it's a CoordinatorLayout / SnackBar issue.

**Comment by rachelmcr** [comment]
One of our beta testers checked this on an LG G4 running Android 5.1 with the 4.8 beta app, and couldn't reproduce this behavior. Can you still reproduce it on your end?

**Comment by maxme** [comment]
I can't repro, I guess it was a support lib issue.
