### ISSUE TITLE
"Your Browser is Out of Date" when Viewing Admin in Nexus 7

### ISSUE THREAD

**Issue by mrwweb** [wordpress-mobile/WordPress-Android#3308]
I've got a Nexus 7 (2013) Android Tablet with the WordPress for Android App (4.5.2), WordPress 4.3.1, and Android 5.1.1 (although this problem has existed for as long as I have used this tablet). When I go to "View Admin," I get this:

!["Your Browser is out of date message"](https://cloud.githubusercontent.com/assets/1238696/10321442/84430242-6c2d-11e5-8b60-2212ea2e6144.png)

**Comment by maxme** [comment]
We can't fix that client side so I asked in [#core](http://wordpress.slack.com/) if they could whitelist our mobile user agents (for the official Android and iOS apps) to avoid that banner to show up.
