### ISSUE TITLE
Sign Out: Unable to log out of a self-hosted site

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#3313]
When logged directly into a self-hosted site (not via Jetpack SSO) there's no option to sign out.  The only thing I can find in the menu is to Connect to WordPress.com, but even signing in to that and then disconnecting leaves me still logged in to the .org site.

**Comment by roundhill** [comment]
It's kinda hard to find, but scroll down to `Settings` in the Sites tab, and in there you can remove the site.

**Comment by hoverduck** [comment]
Maybe it should just be renamed then?  I saw that button, but thought of it in the context of having multiple sites on my account and removing one of them, rather than removing a site from the app.

**Comment by hoverduck** [comment]
Another thought on this - why is the logout option in a different place for WP.com and self-hosted?  That also led to my confusion over how to log out.

**Comment by maxme** [comment]
> why is the logout option in a different place for WP.com and self-hosted?

You can have several self hosted sites but only one wpcom account in the app. That's the main reason. On wpandroid versions < 4.0, the "Logout" button was wipping all data from the app (thus, signing wpcom user out and removing all self hosted sites from the app).

I think this approach is good, except in one situation: users with only one self hosted site in the app.

I don't know how much this "Remove site" button is used, We could eventually move it to the "My site" screen or have a long tap option in the site picker (a bit weird, since that would only work for self hosted). Or have a special case and move it to the "Me" tab when the user only have one self hosted blog it the app and is not connected to wpcom (I don't like special cases much :/).

**Comment by rachelmcr** [comment]
Another option might be to come up with a UI that is the same for removing WordPress.com sites from the app (currently "Show/hide sites") and removing self-hosted sites from the app. That can be considered on a site level for all sites, separately from being logged in/out to a WordPress.com account.

**Comment by mzorz** [comment]
Discussed with @maxme :

"We should have the Sign out button just do all of that, somewhere in the app in a clearer way
—> (have a Sign out button that removes all the sites, wp.com, connected, not connected, etc.)
"

**Comment by tonyr59h** [comment]
Implemented in `feature/fluxc-integration-discovery-improvements`. Now there is always a 'Disconnect/Sign Out/Logout' row that removes _all_ sites. If the user is connected to a self-hosted site there will also be an option to 'Connect to WordPress.com' as there was before.

**Comment by maxme** [comment]
This is related to https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/255#issuecomment-270357827

**Comment by maxme** [comment]
I vote for having one "Sign Out" button on the Me tab that removes all sites from the App (wpcom or selfhosted).

**Comment by catehstn** [comment]
I think this should be fluxc-obsolete - @maxme ?

**Comment by maxme** [comment]
We have to update the sign out experience in the FluxC integration branch.

**Comment by oguzkocer** [comment]
@tonyr59h If you're still working on this issue, could you make sure the sign-out removes all sites (including self-hosted) and shows the login screen. If you're not working on this, could you assign it to me and I'll take a crack at it next week as I worked on the FluxC changes for it.

We also had a mobile request about this recently.

**Comment by tonyr59h** [comment]
The branch is stale atm, I'll merge it up-to-date and see if it works as expected. If not I'm going to send this issue your way 😃

**Comment by tonyr59h** [comment]
All up-to-date and it seems to be working, though I've only just tried it out.

**Comment by tonyr59h** [comment]
Update: Feature is functioning on branch. New PR pending a design pass.
