### ISSUE TITLE
Media Library: Image disappears from view shortly after upload - 4.6-rc-3

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#3321]
When uploading a picture to the media library I see it show up in the view momentarily, and then it disappears.  After leaving and going back in it shows up just fine.  Here's a screencap recorded off of my emulator (on a self-compiled apk using the latest source from git) connected to a self-hosted site, although I saw the same problem on the latest beta on my OnePlus One connected to WordPress.com.

https://cloudup.com/iyGvmEjotjP

The difference is that the logfile on the emulator has an exception relating to the media library that isn't present on the real device.  Although you'll see in the video that re-opening the Media Library was unresponsive for a moment, so the exception may be related to that.  The full logfile can be found here:

http://wp-srstancil.rhcloud.com/2015/10/09/wordpress-application-log/

**Comment by rachelmcr** [comment]
I tested and reproduced this issue on my Nexus 9, Android 6.0, app beta 4.8-rc-1.
