### ISSUE TITLE
Adding a Video to a Post Show Wrong Icon

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3322]
If you add a video to a post, it shows an image icon. I believe it used to have a video icon. Maybe these days we can get a thumbnail preview of the video?

**Comment by rachelmcr** [comment]
I tested adding a video a new post in 4.8-rc-3 and the video showed a film icon:

![screenshot_20151210-154848](https://cloud.githubusercontent.com/assets/8658164/11720185/18c89e12-9f56-11e5-92ec-cdc103ba978e.png)

After saving the post, that switched to a wpvideo shortcode. I agree that a thumbnail preview would be preferable, in any case.

**Comment by hypest** [comment]
Closing and migrating this issue to the `WordPress-Editor-Android` repo. Thanks!
