### ISSUE TITLE
Uploading Video Hangs Device

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3323]
On my Galaxy S6, uploading a video appeared to hang my entire device, it wasn't responsive until the video finished uploading... very bad experience.

**Comment by rachelmcr** [comment]
I haven't been able to reproduce this yet. I tested on my Nexus 9, and uploading a video (in My Sites > Media or in a blog post) didn't make my device unresponsive. I was able to navigate around the app while the video/post uploaded. I'll keep testing on other devices.

**Comment by daniloercoli** [comment]
@roundhill Can we closed this ticket or it's still a problem for you? 
I'm not able to replicate issue on my test devices (Don't have a Galaxy 6 though).

**Comment by hoverduck** [comment]
Closing, as I think this is no longer an issue with the visual editor (since the media is uploaded before the post is published).
