### ISSUE TITLE
Missing log in case of errors in `WordPress.getBlog`

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3326]
In `WordPress.getBlog` there is a [catch Exception](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L425) without any logging.
Better to add a log line there.

**Comment by aforcier** [comment]
`WordPress.getBlog` is dead. Long live `WordPress.getBlog`.
