### ISSUE TITLE
Resurrect email auto filling in the Signup screen in Android 6.+

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3329]
That featured died with permission requests. See https://github.com/wordpress-mobile/WordPress-Android/pull/3328 and [this Android issue](https://code.google.com/p/android/issues/detail?id=189766&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars).

**Comment by maxme** [comment]
Note: this is still an issue in the Android side (the app requests the "Contact" permission when we try to get the default account email address).

**Comment by hoverduck** [comment]
Added `Broken Window` label because it's frustrating/confusing to a user when the app prompts for permissions and it isn't clear why

**Comment by maxme** [comment]
@hoverduck the app should not prompt anything here since we deactivated the feature.

**Comment by hoverduck** [comment]
@maxme Ah, I misunderstood your last comment then.  Thanks
