### ISSUE TITLE
Sharing media to the Media Library can result in corrupted images on 32-bit devices

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3332]
Tested from 4.4.2, it's been around since at least then. Sharing images to the media library (from Photos for example) can lead to some of the images getting corrupted. [See here.](https://danroundhill.files.wordpress.com/2015/10/wpid-wp-1445366465705.jpg)

**Comment by daniloercoli** [comment]
I can't repro this issue on 4.4.3 with the latest version of the app. Processor Arm7 32bit.
Note that Android 4.4.3 has the old Gallery app, and not the Photos app.

Can we close this issue if we ca't reproduce it anymore?

**Comment by tonyr59h** [comment]
> Can we close this issue if we ca't reproduce it anymore?

I think this is a safe bet, especially since is hasn't been reported in a while. We can re-open or create a new ticket if it pops up again.
