### ISSUE TITLE
Menus in material design should look like temporary surfaces that overlay their emitting element.

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3342]
Set the overlapAnchor attribute to true for pop-up menus and drop down spinners. We have 2 spinners in the Reader (tag picker and "..." menu on each post), need to check for other spinner.

Note: action bar overflow menus, blog settings and edit post settings spinners don't need any change,

**Comment by mzorz** [comment]
Checked the reader and it's behaving as desired by default.
Other places where we have overlapAnchor=false have been set on purpose as for example this one here https://github.com/wordpress-mobile/WordPress-Android/commit/467901f21aae6728f5b737306f3770b7ab726fa6

Closing the issue
