### ISSUE TITLE
Missing touch feedback on some flat buttons

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3343]
For instance, edit post settings buttons need touch feedback (and better styling).

**Comment by shahrukhqasim** [comment]
I would like to work on this. I have attached a screenshot. The button does highlight on touch but lacks  the proper 5.0 touch feedback style.
I also think it should be centered.


![screenshot from 2015-11-01 20-09-27](https://cloud.githubusercontent.com/assets/6279842/10869552/bd5dac9c-80d4-11e5-8ae3-609b7c2809aa.png)

**Comment by maxme** [comment]
We're going to replace the "Post settings" button with an action bar button icon soon. But there are some buttons on the Post settings screen that needs work (Category, Add location, etc.).

**Comment by sapuglha** [comment]
I will work on this issue. @shahrukhqasim are you still working on it?

**Comment by tonyr59h** [comment]
Addressed in #3561.
