### ISSUE TITLE
on android studio drawable/com_mixpanel_android_rounded_bottom_selected" compile error

### ISSUE THREAD

**Issue by dmcmillin** [wordpress-mobile/WordPress-Android#3353]
<item android:state_enabled="true" android:state_pressed="true" android:drawable="@drawable/com_mixpanel_android_rounded_bottom_selected" />

in com_mixpanel_android_choice_last_states.xml failed build on the entire resource. Says 

Error:(3, 87) No resource found that matches the given name (at 'drawable' with value '@drawable/com_mixpanel_android_rounded_bottom_selected').

**Comment by maxme** [comment]
We're not using `drawable/com_mixpanel_android_rounded_bottom_selected` internally (it could be used in the mixpanel library though) - so I don't know how you can get that message.

> Error:(3, 87)

Can you send the full error message, with the filename where this happens?

**Comment by dmcmillin** [comment]
C:\Users\danny\Downloads\WordPress-Android-develop\WordPress-Android-develop\libs\analytics\WordPressAnalytics\build\intermediates\exploded-aar\com.mixpanel.android\mixpanel-android\4.6.4\res\drawable\com_mixpanel_android_choice_last_states.xml

Error:(3, 87) No resource found that matches the given name (at 'drawable'
with value '@drawable/com_mixpanel_android_rounded_bottom_selected').
Error:(4, 87) No resource found that matches the given name (at 'drawable'
with value '@drawable/com_mixpanel_android_rounded_bottom_selected').
Error:(5, 88) No resource found that matches the given name (at 'drawable'
with value '@drawable/com_mixpanel_android_rounded_bottom_selected').
Error:(6, 87) No resource found that matches the given name (at 'drawable'
with value '@drawable/com_mixpanel_android_rounded_bottom_selected').
Error:Execution failed for task
':libs:analytics:WordPressAnalytics:processDebugResources'.
> com.android.ide.common.process.ProcessException:
org.gradle.process.internal.ExecException: Process 'command
'c:\Users\danny\AppData\Local\Android\sdk1\build-tools\23.0.1\aapt.exe''
finished with non-zero exit value 1



On Thu, Oct 29, 2015 at 12:30 AM, Maxime Biais <notifications@github.com>
wrote:

> We're not using drawable/com_mixpanel_android_rounded_bottom_selected
> internally (it could be used in the mixpanel library though) - so I don't
> know how you can get that message.
>
> Error:(3, 87)
>
> Can you send the full error message, with the filename where this happens?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wordpress-mobile/WordPress-Android/issues/3353#issuecomment-152102242>
> .
>



-- 
Vasari Plaster and Stucco, LLC
Web Support Specialist
805-845-2497

**Comment by maxme** [comment]
Can you check this file exists:
```
C:\Users\danny\Downloads\WordPress-Android-develop\WordPress-Android-develop\libs\analytics\WordPressAnalytics\build\intermediates\exploded-aar\com.mixpanel.android/mixpanel-android\4.6.4\res\drawable-nodpi-v4\com_mixpanel_android_rounded_bottom_selected.9.png
```

If it doesn't exist, clean your build and maven caches and try to build again.

**Comment by dmcmillin** [comment]
It does exist which is why I am wondering what the deal is. For some odd
reason I am having other issues too. including missing classes and styles
missing. even though it was pulled from the repo and verified

On Thu, Oct 29, 2015 at 1:53 AM, Maxime Biais <notifications@github.com>
wrote:

> Can you check this file exists:
>
> C:\Users\danny\Downloads\WordPress-Android-develop\WordPress-Android-develop\libs\analytics\WordPressAnalytics\build\intermediates\exploded-aar\com.mixpanel.android/mixpanel-android\4.6.4\res\drawable-nodpi-v4\com_mixpanel_android_rounded_bottom_selected.9.png
>
> If it doesn't exist, clean your build and maven caches and try to build
> again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wordpress-mobile/WordPress-Android/issues/3353#issuecomment-152115719>
> .
>



-- 
Vasari Plaster and Stucco, LLC
Web Support Specialist
805-845-2497
