### ISSUE TITLE
Swipe To Refresh can be triggered when a view it already refreshing

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3356]
Demo video: https://cloudup.com/c9HlwF1OeX5

Happens on the Reader and Posts list. Probably on other STR screens too.

I wonder if that comes from a change in our `SwipeToRefreshHelper`

**Comment by maxme** [comment]
Apparently, this is fixed in support lib v23.1.0 - https://code.google.com/p/android/issues/detail?id=183502

**Comment by maxme** [comment]
Confirmed, 23.1.0 fixes the issue

**Comment by tonyr59h** [comment]
Addressed in #3357.
