### ISSUE TITLE
Notifications returns to "All" filter after rotating device

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3362]
No matter what filter I am viewing, if I rotate my device between portrait and landscape it will return to the "All" filter view.

Steps:
1. Hold device in Portrait orientation
2. Tap from All to another filter view (Unread, Comments, Follows, or Likes)
3. Rotate device to Landscape orientation. Result: Notifications show "All" filter
4. Tap from All to another filter view (Unread, Comments, Follows, or Likes)
5. Rotate device back to Portrait orientation. Result Notifications show "All" filter

Expected behavior: After rotating the device, it is still on the same filter view I selected before rotating.

Tested on Nexus 7 (first gen), Android 5.1.1, WordPress app beta 4.7-rc-1

**Comment by nbradbury** [comment]
Closing per @rachelmcr's request
