### ISSUE TITLE
WordPresss-Android can't run after I gradlew now

### ISSUE THREAD

**Issue by orangebook** [wordpress-mobile/WordPress-Android#3367]
Can't run,do it for you flows,but it didn't run well,and has so mang error in my android studio,
Could you provide a APK and Demo with this project now

**Comment by orangebook** [comment]
I am waiting for you now

**Comment by maxme** [comment]
You can download the app in the Google Play Store, or install directly download the 4.6 apk here https://github.com/wordpress-mobile/WordPress-Android/releases/tag/4.6

**Comment by maxme** [comment]
If you give us more details about error you're experiencing, we could help you build the project.

**Comment by orangebook** [comment]
thank you , latter will try again

**Comment by rachelmcr** [comment]
@orangebook Are you still having trouble with this?
