### ISSUE TITLE
Rotation causes WebView to reload

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3374]
Looks like a pretty quick fix/optimization. Would help our slow-network users.

Related [stackoverflow question](http://stackoverflow.com/questions/12131025/android-preventing-webview-reload-on-rotate).

**Comment by kwonye** [comment]
@tonyr59h I have found out that this issue affects all webviews with in the app. I am going to remove the tag of "themes" and postpone this to 4.9 as it affects the entire app.

**Comment by tonyr59h** [comment]
Sounds good :+1:

**Comment by rachelmcr** [comment]
In addition to rotation, leaving the app and returning also reloads webviews in the app. It would be great if we could fix both (rotation and leaving/reopening the app).

Issue raised by a user in an app review.

**Comment by maxme** [comment]
This should be fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/3672
