### ISSUE TITLE
Notifications tab inside "View Admin" never loads

### ISSUE THREAD

**Issue by thingalon** [wordpress-mobile/WordPress-Android#3382]
To reproduce: 
1) Click "View Admin" on any site
2) Click the "Notifications" tab

It shows the new notification filter options just below the tab bar, but the notifications themselves never load; it just shows a spinner. 

Screenshot: https://cloudup.com/c2J5HTGKtUV

**Comment by roundhill** [comment]
... you know there's a native notifications area, right? Just making sure :)

**Comment by roundhill** [comment]
Filed an issue for the web notifications client. Going to close here.
