### ISSUE TITLE
Reader: misleading "not following any sites" message

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3389]
When the reader post list is empty and the user is viewing followed sites, the [empty text](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java#L533) always says the user is "not following any sites."

This can be misleading, since the list may be empty for other reasons (no recent posts, for example). To fix this, only show the message if the list of followed sites is empty.

![ctegxybusaajify](https://cloud.githubusercontent.com/assets/3903757/11077604/fc4f0cf6-87ce-11e5-87fc-86d6479f0281.jpg)

**Comment by shoofle** [comment]
I have never seen this screen display posts, actually; the most recent post on a blog I follow is two days old. (I took this screenshot!)

**Comment by hugocf** [comment]
I think this message is very misleading. It should distinguish the 2 different situations clearly, for example:

1. If the person isn’t really following any blog…  
> You’re not following any sites yet

1. If the person is following blogs, but no recent content is available…
>  It looks like there is nothing new to read

Also, although the sub-message works fine in both situations, it needs to be more clear about **which icon** to tap: at the “top” there are lots of icons, and you’d be surprised how many people confuse left with “right” :smile:

Adding the actual icon image inline in the message would make it much clearer in my opinion, and being a bit less specific about the actual positioning of the button makes the copy a little less brittle in case of future UI button changes/tweaks/rearrangements:

> But don’t worry, just tap the icon `<show icon image here>` at the top to start exploring!
