### ISSUE TITLE
Keep track of push notification's details in Tracks

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3390]
Look into how we can track push notifications better in Tracks. 

I think we can just dump the entire PN payload in Tracks. The PN payload is just a map (String -> Object), that we can copy in the properties map of the `push notification received` event. We should just prefix the keys with `push_notification_` label.
If we do this we can track any push notification in Tracks, without requiring changes on the client when we want to do analysis/funnels/etc. It could be probably a lot of data, but don't think we will have issues on our servers.

Example of data bumped in Tracks:
```
           [2] => Array
               (
                   [_en] => wpandroid_push_notification_received
                   [_ts] => 1447259835924
                   [_ul] => daniloercoli
                   [_ut] => wpcom:user_id
                   [push_notification_collapse_key] => do_not_collapse
                   [push_notification_type] => c
                   [push_notification_msg] => Monica2 commented on your post "Test"
                   [push_notification_note_timestamp] => 1447259831
                   [notification_type] => comment
                   [push_notification_note_id] => 2147535785
                   [push_notification_title] => New comment
                   [push_notification_user] => 7627282
                   [push_notification_noticon] => http://s2.wp.com/wp-content/mu-plugins/notes/images/noticon-comment.png
                   [push_notification_icon] => http://1.gravatar.com/avatar/1e3a33aa6bfb87420b03cef877d41336?s=256&d=identicon&r=G
               )
```

/cc @astralbodies 
/cc @xyu

**Comment by astralbodies** [comment]
I think there is a potential for privacy issues with putting the entire payload into Tracks. We can discuss outside of GitHub. :smile:

**Comment by daniloercoli** [comment]
There should be any issues, since PNs are for wpcom users only, and sensitive data are not exposed in Notes/PNs. We're already discussing this in the appropriate place :)
