### ISSUE TITLE
Themes: Persistent black spinner in theme search

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3402]
If I pull down to refresh while doing a theme search, I end up with a black spinner that only goes away if I either rotate my device or exit the search completely.

To reproduce:
1. Select a site and tap on Themes
2. Tap the search icon
3. Pull down to refresh (a black spinner appears)
4. Type in the search box (the black spinner stays)
5. Tap on a theme to view details, and then dismiss the popup (the black spinner is still there)

Seen on a Nexus 7 (first gen) and 9, WPAndroid 4.7-rc-3

![2015-11-13 16 00 39](https://cloud.githubusercontent.com/assets/8658164/11150446/fe28d5cc-8a1f-11e5-82bc-c2f3c3636d16.png)

**Comment by kwonye** [comment]
Oh interesting, this is the old theme browser, @rachelmcr.

**Comment by kwonye** [comment]
I am going to close this issue as 4.8 will replace this Theme Browser with a new implementation that doesn't have the issue.

**Comment by rachelmcr** [comment]
:+1: Works for me! I look forward to testing the new theme browser. :)
