### ISSUE TITLE
App acts weird if you're not an Editor or Admin on all of your blogs

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3418]
A user reported that the app is unresponsive and sometime lags or exposes unexpected behavior if hte user logged in isn't an Admin or Editor on all sites.

> also the login shows an odd behaviour: After entering my credentials at the login page the app shows a black screen for some moments then again requests the credentials, and again, and again, ...
But if I cancel the login request I actually enter the app and my site/statistics/...

Here's the log that shows some 403 and 401 errors:

WordPress Android version: 4.6
Android device name: Samsung GT-I8160
```
01 - WordPress.onCreate
02 - trackLastActivity, activityId: Me
03 - App comes from background
04 - ConnectionChangeReceiver.setEnabled true
05 - Connection status changed, isConnected=true
06 - Deferred Initialisation
07 - Already registered for GCM
08 - Configuring Simperium
09 - Number of old stats deleted : 11
10 - Response document received from the server: <?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <fault>
    <value>
      <struct>
        <member>
          <name>faultCode</name>
          <value><int>403</int></value>
        </member>
        <member>
          <name>faultString</name>
          <value><string>You are not allowed access to details about this site.</string></value>
        </member>
      </struct>
    </value>
  </fault>
</methodResponse>

11 - NETWORK_XMLRPC - You are not allowed access to details about this site. [Code: 403] - exception: You are not allowed access to details about this site. [Code: 403]
```
and later in the log
```
46 - Response document received from the server: <?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <fault>
    <value>
      <struct>
        <member>
          <name>faultCode</name>
          <value><int>403</int></value>
        </member>
        <member>
          <name>faultString</name>
          <value><string>You are not allowed access to details about this site.</string></value>
        </member>
      </struct>
    </value>
  </fault>
</methodResponse>
```

**Comment by maxme** [comment]
I wasn't able to reproduce this behavior on .com or self hosted site. I do see XMLRPC 403 errors in log, (during login, when the app tries to get comments), but the `InvalidCredentialsDetected` event is not triggered and so the Error Dialog is not displayed.

I wonder if his auth problem comes from something else.
