### ISSUE TITLE
Media: Simple image editing would be useful

### ISSUE THREAD

**Issue by dllh** [wordpress-mobile/WordPress-Android#342]
When adding an image to a post either by capturing from within the WP editor or when browsing from the photo library, you can't crop or change the orientation. A real life scenario:

1. I snapped a couple of photos of things my daughter had hand-written.
2. They're in the photo library now.
3. I upload to a post.
4. Oops, they're sideways.
5. I try to rotate within the WP app with no luck.
6. I go into the photo library and rotate and crop.
7. Now I have a duplicate image. 
8. What's worse, if I left the post mid-composition to edit the photos, my changes to the post are lost unless I remembered to save a draft first.
9. Now I reinsert into the post and publish.

If there's an API for doing even just basic rotating and cropping from within the app (say from the screen you get when you double-click an image within the editor), it'd make for a much improved workflow and reduce the likelihood of data loss.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
