### ISSUE TITLE
Widget: Some stats widget content is hidden when a site has a long title

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3424]
When a site has a long title, it goes onto a second line in the stats widget. This pushes down the rest of the widget content, cutting off the stats or even hiding them completely.

Here is a screenshot from my Nexus 9, Android 6.0, landscape mode:

![screenshot_20151119-105602](https://cloud.githubusercontent.com/assets/8658164/11269079/b3f2b090-8eac-11e5-97b5-ed40ba41c604.png)

**Comment by daniloercoli** [comment]
Note to self: if the fix is just few lines of code, include it in 4.8. Switch to 4.9 in all other cases.

**Comment by daniloercoli** [comment]
Fixed in #3438
