### ISSUE TITLE
Comments not showing until app reset

### ISSUE THREAD

**Issue by bryceadams** [wordpress-mobile/WordPress-Android#3429]
**Device:** Nexus 6P

Running the beta, I clicked comments on a post with ~25 comments. All were made within the last 20 minutes. It kept saying that there were no comments though. After closing it from the open apps dialog, and then reopening it, the comments loaded.

Sorry I don't have any more info - I realise this may be a bit hard to debug/replicate, but thought I should mention it.

**Comment by rachelmcr** [comment]
Thanks for the report! I tried reproducing this issue with the following steps:
1. Opened the app on my device
2. Published a post on a blog I follow from my laptop browser
3. Pulled to refresh the reader in the app and saw the post with 0 comments
4. Published a comment on the new post from my laptop browser
5. Pulled to refresh the reader in the app and saw 1 comment on the post
6. Tapped the comment icon and the new comment loaded

So I couldn't reproduce the issue with those steps, but wanted to note them in case there's a different approach that might reproduce it.

Device: Nexus 9
Version: 4.8-rc-1

**Comment by rachelmcr** [comment]
@bryceadams If you happen to recall the blog post (or just the blog) where this happened, I may be able to dig in with that info. Otherwise, I'm inclined to close this issue for now and reopen later on if we get a new report or find a way to reproduce it.

**Comment by bryceadams** [comment]
@rachelmcr sorry I can't remember. No problem and I'll reopen if I discover it again :)
