### ISSUE TITLE
Add version check for self-hosted discussion settings

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3434]
Current versions of WordPress self-hosted do not have the discussion settings triggers in place. Version-check before showing discussion settings on self-hosted sites.

**Comment by tonyr59h** [comment]
Just pinged for an update to the issue [here.](https://core.trac.wordpress.org/ticket/33425). Once I get the info I'll add the feature toggle.

**Comment by kwonye** [comment]
Update: WordPress 4.5 will likely have this. Older self-hosted versions will maintain the "old" settings (#3562) while the new 4.5 would have the new settings

**Comment by maxme** [comment]
Still no news from the WordPress ticket.
