### ISSUE TITLE
"Huge" font size cuts off text

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3435]
When text is set to "Huge" in settings, there is a possibility that the text can get cut off (see Blog Posts and Pages):

![screenshot_20151123-192656](https://cloud.githubusercontent.com/assets/1158819/11357032/68b4264e-9218-11e5-9c88-be4a58f59f7e.png)

**Comment by maxme** [comment]
We should not use a fixed height [here](https://github.com/wordpress-mobile/WordPress-Android/blob/1df701cde24db112c93380e10fca235b011cb3be/WordPress/src/main/res/values/styles.xml#L233-L233).  (Or use a dirty trick: use `sp` instead of `dp` for row layout_height)

**Comment by maxme** [comment]
We have the same issue on the Me tab
