### ISSUE TITLE
Add Link Pre-loaded Text Inconvenient

### ISSUE THREAD

**Issue by Essayoh** [wordpress-mobile/WordPress-Android#3443]
When I make a bunch of text into a hyperlink in the Android app, the text input field for the link is pre-loaded with ```http://``` which is actually kind of inconvenient, since almost all links on mobile are copy-pasted from my mobile browser window. Since the field doesn't filter out the double ```http://``` I have to delete it every time. 

Just a quick thought I wanted to put out there while it was fresh in the mind. Happy to discuss.

**Comment by rachelmcr** [comment]
In the iOS app, when you copy a link the URL field in the editor is prefilled with that link (so you don't even have to paste it). That would be a great enhancement to deal with this issue.

**Comment by maxme** [comment]
Ping @aforcier, not sure how it's done in the new editor, same as in the iOS app?

**Comment by aforcier** [comment]
The new editor uses the same setup as legacy, the link dialog was implemented here: https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/214

We could definitely duplicate the iOS app's behavior, or at the very least filter out double `http://`s.

I'll open an issue for this in the new editor repo - I don't think we need to worry about implementing this for legacy once it's in the new editor.

**Comment by aforcier** [comment]
I opened an issue in the editor repo. Closing this in favor of https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/268.
