### ISSUE TITLE
Media Library: Sharing multiple images to media library doesn't upload all images

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3445]
Might be related to #3332. I've noticed that if I select many images (say 5-10) in the Photos app and then share to the WP media library, it will only upload one or two of the images. And usually the second image is corrupted like in #3332.

Overall, Media seems really buggy and needs a good rework.

**Comment by maxme** [comment]
Does it happen with other "source" apps? like the old Gallery?

**Comment by daniloercoli** [comment]
I can't replicate this issue both on 4.4.3 Android and the old gallery app, and on Android 7.X with the new photos app. 
I tried by sharing 10 pictures to media gallery and they were uploaded without ay problem.
Closing this ticket for now, even though Media needs to be improved.
