### ISSUE TITLE
Media browser blank images

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3453]
Quite often while using the media browser, images that I know have already been downloaded (cached) show up blank. This happens in multiple situations, but I can repro it consistently by opening the media browser, tapping an image to view the detail, then returning to the media browser.

[Demo video](https://cloudup.com/c-XSENUbbu7)

**Comment by maxme** [comment]
I can't repro, anything in the logs?

**Comment by maxme** [comment]
Ok, I can repro on Android 6.0 (but only on 6.0), and it's actually happening almost everytime the view is refreshed... Horrible experience :/

**Comment by maxme** [comment]
On a 6.0 emulator: https://cloudup.com/csdUNrBY9pS
