### ISSUE TITLE
Inaccurate error message when user doesn't have permissions to upload media to a site

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3454]
Media Browser. When you don't have permissions to upload media to a site, you only get a "Media upload error" Toast.

We should show a specific message (XMLRPC message is: `You do not have permission to upload files. [Code: 401]`) and hide the "retry" button.

**Comment by daniloercoli** [comment]
I added a custom error message here `You don't have permission to upload media to the site`.
What if we use the error message returned by the server? (it's localized in the blog site language).

**Comment by daniloercoli** [comment]
Also, should we hide the "retry" button? One can change permissions on the server and upload media later, or can remove the media from the queue.

If we want to hide the "retry" button, er we need to introduce a new state for a Media object, and the code is going to grow in complexity.

**Comment by maxme** [comment]
> If we want to hide the "retry" button, we need to introduce a new state for a Media object, and the code is going to grow in complexity

Right, I just noticed the state is persisted and so the "retry" button stays here even on app restart. So forget about hiding it.
