### ISSUE TITLE
Track a new event: Application Installed

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3468]
I think the easiest is to track it from WordPressDB init: https://github.com/wordpress-mobile/WordPress-Android/blob/64b4710821617f449943373e7052f7256fb739c9/WordPress/src/main/java/org/wordpress/android/WordPressDB.java#L251-L251 (or defer tracking from here if analytics aren't initialized yet).

**Comment by daniloercoli** [comment]
> defer tracking from here if analytics aren't initialized yet

This! I think Analytics are not yet ready there.

**Comment by maxme** [comment]
> This! I think Analytics are not yet ready there.

Or write something only once (during first launch) in the shared pref just after analytics are ready, probably cleaner to do that.
