### ISSUE TITLE
Invalid drake_empty_results.png size in drawable-hdpi/

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3479]
I just noticed that `drawable-hdpi/drake_empty_results.png` is 400x250px, but it should be [400dp](https://github.com/wordpress-mobile/WordPress-Android/blob/256184b76252265c9affbfb76e83f72e3e45cac1/WordPress/src/main/res/values/dimens.xml#L215-L215), this is 600x375px

**Comment by maxme** [comment]
cc @kwonye

**Comment by kwonye** [comment]
Great catch, thanks @maxme. A great example of why we should move to svg as soon as possible (which I think the gradle plugin allows now)
