### ISSUE TITLE
Truncated text in Notification screen

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3481]
On specific combination of screen size / language, filter buttons text can be truncated like here (Galaxy S2, Czech):

![screencap-2015-12-08t15-14-09 0100](https://cloud.githubusercontent.com/assets/40213/11657929/1c4c2de8-9dc0-11e5-8077-acac0308f7d5.png)

I don't think there is a simple fix here that won't need a full redesign of this radio buttons. We could at least use `android:ellipsize="none"` or `android:ellipsize="marquee"`  so the ellipsis character `…` won't use half of the screen.

**Comment by mzorz** [comment]
@drw158 what do you think about this one?

**Comment by drw158** [comment]
Getting rid of the ellipsis might be fine. If someone wants to redesign it, we could let the button group scroll horizontally?

**Comment by mzorz** [comment]
What if, instead of the push button group, we use a filter (drop down selector) such as the one we have in the Reader or Comments sections? This would give enough space for pretty long words to be read.

**Comment by drw158** [comment]
That'd be fine I think, if we could do that only for users with truncated text. With the dropdown, it takes an extra tap to access items, and only the current item is visible.

**Comment by mzorz** [comment]
After considering this for a while, went ahead and implemented this solution https://github.com/wordpress-mobile/WordPress-Android/issues/3481#issuecomment-263638096 as @drw158 suggested
PR here: #4863
