### ISSUE TITLE
Analytics - READER_ACCESSED event is fired too often

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3486]
I'm not 100% sure if this is an error, but we may want to revise the way READER_ACCESSED is tracked in the app.
In details, the READER_ACCESSED event is tracked every time the Reader Posts List activity is shown on the screen. So if you go from the Article Details Screen back to the Reader Posts List screen READER_ACCESSED is fired. It's then fired twice when a user opens the reader and just read one article. 

Steps to reproduce the issue:
- Open the Reader (READER_ACCESSED fired)
- Tap on a Article (reader_article_opened fired)
- Go back to the posts list  (READER_ACCESSED fired)

@astralbodies - IIRC there were discrepancies on Reader Usage on the two platforms?

/cc @nbradbury

**Comment by nbradbury** [comment]
> So if you go from the Article Details Screen back to the Reader Posts List screen READER_ACCESSED is fired

That definitely shouldn't be happening - it should only be tracking when the user switches to the reader, not when they return to it.

**Comment by astralbodies** [comment]
Yup @daniloercoli there was - good catch :smile:

**Comment by daniloercoli** [comment]
@astralbodies - Note that with this PR merged, starting from wp-android 4.9, we've changed the way events are tracked for the main tab. 
Only the first access to an item in the main tabbed interface is tracked in Analytics.
EX: if you go to Notifications -> open a note (details screen) -> back to Notifications. Only ONE access to Notifications is bumped in Analytics: wpandroid_notifications_accessed -> wpandroid_notifications_notification_details_opened -> any other event that follow.
