### ISSUE TITLE
Trashing Post From App Permenantly Deletes It

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-Android#3490]
Tested in both current production version and current beta version.
When you trash a post from the app it is permanently deleted.

It would make more sense if it were sent to the Trash instead so that you have the ability to restore before it is gone for good.

**Comment by maxme** [comment]
Apparently we should not use the `wp.deletePost` XMLRPC call, but use `wp.editPost` and set the `post_status` to `trash`

**Comment by maxme** [comment]
I found a weird call here: https://github.com/wordpress-mobile/WordPress-Android/blob/bac388aac9284360069856505ee1c89c713211d6/WordPress/src/main/java/org/xmlrpc/android/ApiHelper.java#L491-L491

`wp.deletePost` should  move the post to trash (it works on iOS and they use `wp.deletePost`), and I found [this](https://wordpress.org/support/topic/xmlrpc-wpdeletepost-documentation-needs-an-addition?replies=1)
