### ISSUE TITLE
Remove masterbar tab reselect hack

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3493]
[This hack](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L129) which worked around [our favorite design lib issue](https://code.google.com/p/android/issues/detail?id=177189) is no longer necessary.

**Comment by tonyr59h** [comment]
Addressed in #3494.
