### ISSUE TITLE
Review analytics events - Some of them are unused.

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3504]
Using the following script:

```
events="APPLICATION_OPENED APPLICATION_CLOSED APPLICATION_INSTALLED APPLICATION_UPGRADED READER_ACCESSED READER_ARTICLE_COMMENTED_ON READER_ARTICLE_LIKED READER_ARTICLE_OPENED READER_ARTICLE_UNLIKED READER_BLOG_BLOCKED READER_BLOG_FOLLOWED READER_BLOG_PREVIEWED READER_BLOG_UNFOLLOWED READER_DISCOVER_VIEWED READER_FRESHLY_PRESSED_LOADED READER_INFINITE_SCROLL READER_LIST_FOLLOWED READER_LIST_LOADED READER_LIST_PREVIEWED READER_LIST_UNFOLLOWED READER_TAG_FOLLOWED READER_TAG_LOADED READER_TAG_PREVIEWED READER_TAG_UNFOLLOWED STATS_ACCESSED STATS_INSIGHTS_ACCESSED STATS_PERIOD_DAYS_ACCESSED STATS_PERIOD_WEEKS_ACCESSED STATS_PERIOD_MONTHS_ACCESSED STATS_PERIOD_YEARS_ACCESSED STATS_VIEW_ALL_ACCESSED STATS_SINGLE_POST_ACCESSED STATS_TAPPED_BAR_CHART STATS_SCROLLED_TO_BOTTOM STATS_WIDGET_ADDED STATS_WIDGET_REMOVED STATS_WIDGET_TAPPED EDITOR_CREATED_POST EDITOR_ADDED_PHOTO_VIA_LOCAL_LIBRARY EDITOR_ADDED_PHOTO_VIA_WP_MEDIA_LIBRARY EDITOR_UPDATED_POST EDITOR_SCHEDULED_POST EDITOR_CLOSED_POST EDITOR_PUBLISHED_POST EDITOR_SAVED_DRAFT EDITOR_TAPPED_BLOCKQUOTE EDITOR_TAPPED_BOLD EDITOR_TAPPED_IMAGE EDITOR_TAPPED_ITALIC EDITOR_TAPPED_LINK EDITOR_TAPPED_MORE EDITOR_TAPPED_STRIKETHROUGH EDITOR_TAPPED_UNDERLINE ME_ACCESSED MY_SITE_ACCESSED NOTIFICATIONS_ACCESSED NOTIFICATIONS_OPENED_NOTIFICATION_DETAILS NOTIFICATION_REPLIED_TO NOTIFICATION_APPROVED NOTIFICATION_UNAPPROVED NOTIFICATION_LIKED NOTIFICATION_UNLIKED NOTIFICATION_TRASHED NOTIFICATION_FLAGGED_AS_SPAM OPENED_POSTS OPENED_PAGES OPENED_COMMENTS OPENED_VIEW_SITE OPENED_VIEW_ADMIN OPENED_MEDIA_LIBRARY OPENED_BLOG_SETTINGS OPENED_ACCOUNT_SETTINGS OPENED_MY_PROFILE CREATED_ACCOUNT ACCOUNT_LOGOUT SHARED_ITEM ADDED_SELF_HOSTED_SITE SIGNED_IN SIGNED_INTO_JETPACK PERFORMED_JETPACK_SIGN_IN_FROM_STATS_SCREEN STATS_SELECTED_INSTALL_JETPACK PUSH_NOTIFICATION_RECEIVED PUSH_NOTIFICATION_TAPPED SUPPORT_OPENED_HELPSHIFT_SCREEN SUPPORT_SENT_REPLY_TO_SUPPORT_MESSAGE LOGIN_FAILED LOGIN_FAILED_TO_GUESS_XMLRPC PUSH_AUTHENTICATION_APPROVED PUSH_AUTHENTICATION_EXPIRED PUSH_AUTHENTICATION_FAILED PUSH_AUTHENTICATION_IGNORED SETTINGS_LANGUAGE_SELECTION_FORCED NOTIFICATION_SETTINGS_LIST_OPENED NOTIFICATION_SETTINGS_STREAMS_OPENED NOTIFICATION_SETTINGS_DETAILS_OPENED NOTIFICATION_SETTINGS_UPDATED THEMES_ACCESSED_THEMES_BROWSER THEMES_ACCESSED_SEARCH THEMES_CHANGED_THEME THEMES_PREVIEWED_SITE THEMES_DEMO_ACCESSED THEMES_CUSTOMIZE_ACCESSED THEMES_SUPPORT_ACCESSED THEMES_DETAILS_ACCESSED"

for i in $events; do
  [ `ack $i | wc -l` -le 3 ] && echo $i
done
```

I found some event names that are not used or not implemented in one tracker. 

Not implemented in mixpanel tracker:

- [x] ACCOUNT_LOGOUT

Event name exists, but not tracked and it should be. Not sure what to do with:

@nbradbury 

- [X] READER_DISCOVER_VIEWED

- [X] READER_FRESHLY_PRESSED_LOADED
- [X] READER_LIST_FOLLOWED
- [X] READER_LIST_PREVIEWED
- [X] READER_LIST_UNFOLLOWED

@kwonye 
- [x] THEMES_CUSTOMIZE_ACCESSED

@roundhill  

- [x]  NOTIFICATION_LIKED
- [x]  NOTIFICATION_UNLIKED
- [x] NOTIFICATION_SETTINGS_LIST_OPENED
- [x] NOTIFICATION_SETTINGS_STREAMS_OPENED
- [x] NOTIFICATION_SETTINGS_DETAILS_OPENED
- [x] NOTIFICATION_SETTINGS_UPDATED

Future events. Ok to have them here.
```
OPENED_ACCOUNT_SETTINGS (future)
OPENED_MY_PROFILE (future)
```

**Comment by nbradbury** [comment]
@daniloercoli `READER_DISCOVER_VIEWED` was added in [this hotfix PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3439/files#diff-6c7a325968c55524fd50f1a8ee490c51R1045), but it doesn't appear that hotfix made it into `develop`. That PR also removed `READER_FRESHLY_PRESSED_LOADED`.

I'm not sure when those `READER_LIST_*` events were added, but we're not using them yet (since managing reader lists isn't in the app yet). They will be used in the future, though.

**Comment by maxme** [comment]
@nbradbury Ooooops! Not merged in `release/4.8` actually, I'm on it.

**Comment by maxme** [comment]
> I'm not sure when those READER_LIST_* events were added, but we're not using them yet (since managing reader lists isn't in the app). They will be used in the future, though.

We should add a comment next to their declaration something like `// future` to avoid confusion with outdated event names.

**Comment by maxme** [comment]
> Ooooops! Not merged in release/4.8 actually, I'm on it.

Fixed, `READER_FRESHLY_PRESSED_LOADED` is no more in `release/4.8` and `develop`

**Comment by daniloercoli** [comment]
> We should add a comment next to their declaration something like // future to avoid confusion with outdated event names

Agree. will add it to future events.

**Comment by roundhill** [comment]
@daniloercoli We should add the `NOTIFICATION_SETTINGS*` events

**Comment by daniloercoli** [comment]
@roundhill Added in https://github.com/wordpress-mobile/WordPress-Android/commit/dbafbf46a3a25dc3f408f3271cd039f104f67a08

**Comment by kwonye** [comment]
Thanks for that @daniloercoli. We will be using `THEMES_CUSTOMIZE_ACCESSED`. PR here: #3511
