### ISSUE TITLE
Reader - Wrong liker avatar

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3522]
Open the "Likers" screen for a post in the reader, and check avatars. I noticed sometimes they're  duplicated (like in the picture below) or assigned to the wrong person. I bet this happen if you rotate the device when avatars are loading.

![wp-1450179168235](https://cloud.githubusercontent.com/assets/518232/11812741/e64a77f8-a33d-11e5-81ce-8f7c94900b72.png)

See Danilo and Tony ^

**Comment by nbradbury** [comment]
@daniloercoli I'm having trouble repro'ing this one. Do you only see this after rotating the device?

**Comment by daniloercoli** [comment]
Yes, rotating the device is the trick, it seems.

![screenshot_20151217-171220](https://cloud.githubusercontent.com/assets/518232/11874736/862ea254-a4e1-11e5-853b-196409d42f56.png)

I've accessed the Likers list for a post, and avatars were OK. I rotated the device to landscape and boom ^
