### ISSUE TITLE
Custom headers are sometimes ignored by the post list preview (and other WebViews)

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#3523]
The post list preview is sometimes unable to load images from private sites because the `WebView` doesn't call its `WebViewClient.shouldInterceptRequest()` method, which adds the necessary `Authorization` header (as well as the custom `UserAgent`). This can happen with non-private sites as well, but in that case only the custom `UserAgent` is missing.

This also affects the new editor's `WebView` and possibly other `WebView`s in the app.

Happens much more frequently on emulators than real devices, and somewhat more frequently on older devices than new ones. Possibly caused by the `WebView` processing the request before its `WebViewClient` has been initialized properly.

**Comment by daniloercoli** [comment]
Better to work on this after #2785

**Comment by hoverduck** [comment]
This issue is a year+ old, is it still relevant?  #2785 was closed around that time as well, FWIW.

**Comment by aforcier** [comment]
@hoverduck it should still be relevant, though it'll be even less important once Aztec lands and this no longer affects the editor.

I think we can close it for now. If we run into this issue again in a big way this issue still exists as a reference, but as things stand we're not likely to try to fix this.
