### ISSUE TITLE
Edit button from post takes you to calypso editor

### ISSUE THREAD

**Issue by johnHackworth** [wordpress-mobile/WordPress-Android#3527]
There's a flow that, as a user, feels pretty weird to me.
1. you are in the app, in your post list

![image](https://cloud.githubusercontent.com/assets/1554855/11834154/0a9dc0ec-a3ca-11e5-9cdf-131ee1109b84.png)
1. Click on 'view' in one of the posts

![image](https://cloud.githubusercontent.com/assets/1554855/11834161/1b2aa538-a3ca-11e5-8723-5f8f129e8e57.png)
1. In the post, click on 'edit'
   ![image](https://cloud.githubusercontent.com/assets/1554855/11834175/2de4cb36-a3ca-11e5-9ecf-f9313dba4448.png)

You are taken to calypso editor.

I'm not sure if this is feasible to do, but in this case, being inside the app, I would expect to be taken to the app editor instead of the web one.

**Comment by maxme** [comment]
IMO, the solution is to hide the HTML top bar when we open that page in our mobile apps.

**Comment by maxme** [comment]
We deactivated all links from the preview Webview, users are notified that they can't navigate this page.
