### ISSUE TITLE
mySiteFragment.java - removescheme, removetrailingslash, getHost error

### ISSUE THREAD

**Issue by dmcmillin** [wordpress-mobile/WordPress-Android#3552]
if (!TextUtils.isEmpty(mBlog.getHomeURL())) {
            homeURL = UrlUtils.removeScheme(mBlog.getHomeURL());
            homeURL = StringUtils.removeTrailingSlash(homeURL);
        } else {
            homeURL = UrlUtils.getHost(mBlog.getUrl());
        }

ln:306-311 displays those as cannot resolve method even though the correct files and functions are present. Using Android Studio newest. Any assistance would be appreciated. Thanks!

**Comment by maxme** [comment]
WordPress-Utils-Android has been updated, you should not get these warnings anymore.
