### ISSUE TITLE
Use the search to select a hidden site result in app weirdness

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3554]
1. Open the site picker
1. Select site XYZ
1. Select a hidden site with the search feature on the site picker
1. Tap back
1. Tap the New Post button
1. Notice the ActionBar title is XYZ and not the one previously picked

This could produce other errorr. We should probably make selected sites via search visible is they're hidden.

**Comment by kwonye** [comment]
Initial thought is that `Blog.hidden` is being used for more than whether or not it should be shown on the `SitePickerActivity`. I'll find all usages and see what's going on.
