### ISSUE TITLE
WordPress 4.4 post date is incorrect

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3555]
There is a bug in WordPress 4.4 that changed the `post_date` from local time to gmt time. https://core.trac.wordpress.org/ticket/35053

This results in the post not posting at the correct time. The fix will be in 4.4.1, but 4.4 will always have this issue. We'll need a special case for self-hosted sites on 4.4

**Comment by daniloercoli** [comment]
Core ticket was closed 11 months ago. We can mark this ticket closed, since WP 4.4 is an old version of WP now.
