### ISSUE TITLE
Menus Calypso - Add/Remove items

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3591]
Implement Add and Remove actions for menu items.
- [x] Posts
- [x] Pages
- [x] Categories
- [x] Tags
- [x] Links
- [x] Testimonials
- [x] Misc.

**Comment by rachelmcr** [comment]
Are we still planning to implement a Menus section in the app? A user recently noted that they couldn't add menu items in the app:

> Works smoothly, could not add pages to the menu in the app. Had to go to the wp website wich is far less android friendly.

**Comment by tonyr59h** [comment]
This one was held up due to lack of design. Since most of the feature is implemented and our designers have more bandwidth I think we should push this priority up a bit and get it over the finish line.

Thoughts @maxme, @catehstn?

**Comment by catehstn** [comment]
We don't have an abundance of design help ;) also calypso menus are being moved into the customizer, so there's no longer the consistency argument. would def like to see the customizer overall working better in the apps though.

**Comment by mattmiklic** [comment]
> This one was held up due to lack of design.

The design was provided last year in #4156. What had been implemented didn't match the design as of the last time I looked at it. If developers wanted to revisit it, I could help with another design review. That said,

> calypso menus are being moved into the customizer, so there's no longer the consistency argument. would def like to see the customizer overall working better in the apps though.

I agree with this; if we are favoring the Customizer over Calypso's Menus UI anyway on the web, I think improving the Customizer on mobile is a more interesting and potentially rewarding challenge.

**Comment by tonyr59h** [comment]
> I think improving the Customizer on mobile is a more interesting and potentially rewarding challenge.

Unless we `WebView` it 😉

**Comment by lancewillett** [comment]
Adding a vote to support menu management in Android (even if it's in a Customizer).

**Comment by tonyr59h** [comment]
Another thought...improving the Customizer is certainly a more interesting and impactful project for getting menu management in. However, that sort of project will take a _long_ time while native-non-customizer menu's are basically implemented (albeit ~year behind `develop`) so getting it shipped would be trivial in comparison.

**Comment by catehstn** [comment]
`year behind` && `trivial`

😂

I think this is lower priority than #betterjetpackxp.
