### ISSUE TITLE
Menus Calypso - Hierarchy customization

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3592]
Implement editable hierarchy for menus and their items.

- [x] UI: drag & drop
- [x] UI: add item above/below / to children
- [x] Implement UI data loaders (integrate network)
- [x] Implement database save/load

**Comment by mzorz** [comment]
Manually merged into `feature/3591-menu-items` (see issue #3591 and PR #4217)
