### ISSUE TITLE
Site settings default Post Format not saved on the server

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3597]
Looks like the post format is never saved if other settings aren't changed.

https://cloudup.com/cDSs9vHodO7

Should we post the changes only when the SettingsFragment is killed?

**Comment by hypest** [comment]
https://cloudup.com/cDSs9vHodO7 just displays a green screen for me. You have some other screengrab around or maybe the steps to reproduce? Cheers!

**Comment by maxme** [comment]
New screenrecording; https://cloudup.com/cR04ruzbujg

**Comment by maxme** [comment]
fixed via #3650
