### ISSUE TITLE
My Profile: Rotating device loses unsaved changes

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3608]
While editing the fields in the My Profile section in /me, I rotated my device. This closed the window where I was making the changes without saving anything, so my changes were lost. That wouldn't be so terrible for the first/last name or display name, but I had added a big chunk of text to the "About Me" section and it was frustrating to lose it and have to start over.

Ideally, I should be able to rotate the device and have the field I was editing stay open so I can continue editing it until I save or cancel the changes.

Tested on Nexus 9, Android 6.0.1, beta 5.0-rc-1

**Comment by rishabh7m** [comment]
Hi, I would like to work on this bug if no one is currently working on it :)

**Comment by maxme** [comment]
@rishabh7m you're welcome to work on it!

cc @oguzkocer
