### ISSUE TITLE
Fix double-counting of media tracking events for new editor

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#3610]
Media events are currently counted twice for the new editor (or would be once launched), once in `EditPostActivity` ([here](https://github.com/wordpress-mobile/WordPress-Android/blob/398edd542e8ac72eb23385651ee25691c99de490/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1240-L1322)) and once again in the editor fragment itself ([here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/10a08faaeb4438251fa74bee2e80434c150d5667/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L721)).

We should change `EditPostActivity` to only register the events if the legacy editor is being used; otherwise, defer to the editor itself for tracking the events.

Must be merged against `feature/visual-editor`.

**Comment by aforcier** [comment]
We'll also need to make some improvements to gallery tracking. Currently, we mark an `EDITOR_ADDED_PHOTO_...` event for each image in a gallery when it's added to a post:

https://github.com/wordpress-mobile/WordPress-Android/blob/e16e529e81ffb78fbc7796444f7bcca550c5fd70/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1564-L1578

We should offload this functionality to the `EditorFragment` for consistency with the other media changes outlined above, and only register the gallery events in `EditPostActivity` if the legacy editor is being used.

We also may prefer a broader `GALLERY_ADDED` event instead or additionally (discussion ongoing).

**Comment by maxme** [comment]
The more I think about analytics in our libraries, the more I think we should delegate **all** calls from libraries to the main project and kill the analytics dependency in libraries. Main point: make the libraries reusable somewhere else. That also mean we'll have to put callback calls (or emit events?) everywhere in the Editor :/

**Comment by maxme** [comment]
* avoid duplicates 
* Add a new `has_gallery` param for `PUBLISHED_POST ` event

**Comment by aforcier** [comment]
Merged in https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/280 and #3757.
