### ISSUE TITLE
HTML entities in Categories and Default Category on the Site Settings screen

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3627]
Should be `A&B`

![screencap-2016-01-20t16-46-37 0100](https://cloud.githubusercontent.com/assets/40213/12453914/ad2d4eea-bf95-11e5-89e3-b1f26f87510e.png)

**Comment by maxme** [comment]
Same problem on Calypso Web - could be a REST API problem.

**Comment by tonyr59h** [comment]
> Same problem on Calypso Web - could be a REST API problem.

I'll just convert them for display in the summary so we don't mess with how it's stored on the backend.

**Comment by tonyr59h** [comment]
Addressed in #3712.
