### ISSUE TITLE
Site Settings: Keyboard disappears immediately after opening Site Title or Tagline settings

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3629]
When I tap to open the Site Title or Tagline settings, the keyboard appears briefly and then immediately closes. I still see the cursor at the end of the text field, but I have to tap again on the text field to re-open the keyboard to make changes.

Tested on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-1

**Comment by tonyr59h** [comment]
I'm unable to reproduce on my HTC One or Nexus 5X. I'll give it another go when I have access to my Nexus 9. There's code in place that attempts to show the keyboard, we'll have to re-visit it.

**Comment by tonyr59h** [comment]
It's reproducing on my Nexus 9 now that I've flashed it to the same version you were using :smile_cat:
