### ISSUE TITLE
Site Settings: Selecting new blog language changes the names of the languages in the Language list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3632]
Steps to reproduce:
1. Select a site and open the Settings
2. Select Language (to choose the blog language)
Note that the list of languages displays the name of each language in that language and below displays the name of each language in your language (e.g. English/English, Deutsch/German, Español/Spanish).
3. Select a new language from the list.
Result: The second name of each language changes to the name of that language in the language you just selected (so if you select Español/Spanish, the list becomes e.g. English/Inglés, Deutsch/Alemán, Español/Español).

The blog language shouldn't affect the UI language, so the list of languages should always respect the device/app UI language and not the selected blog language.

Screenshot with English selected as the blog language:

![2016-01-20 19 59 21](https://cloud.githubusercontent.com/assets/8658164/12462736/caba0a30-bfb7-11e5-869e-3549fe263f05.png)

Screenshot with Greek selected as the blog language:

![2016-01-20 19 59 28](https://cloud.githubusercontent.com/assets/8658164/12462743/d0ff9608-bfb7-11e5-9b23-ec461ed978da.png)

Tested on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-1.

**Comment by daniloercoli** [comment]
Addressed in #3734
