### ISSUE TITLE
Themes - Menus - Difficult to Scroll to Add Items

### ISSUE THREAD

**Issue by sararosso** [wordpress-mobile/WordPress-Android#3636]
When clicking on Themes in the Android app, and then Menus, it’s almost impossible to scroll down to “Add Item” in Menu if there are existing items as it thinks you are just trying to reorder the existing items...

We were able to get around this by scrolling on the tiny margin on the side, but it's quite hard! :) 

![slack for ios upload-3](https://cloud.githubusercontent.com/assets/4126822/12467291/211017cc-bf8f-11e5-8922-9a6bd90dce13.jpg)

**Comment by kwonye** [comment]
Should be resolved by this: https://core.trac.wordpress.org/ticket/35130

**Comment by maxme** [comment]
I just tried and it's apparently fixed, I just commented on the trac issue.
