### ISSUE TITLE
Site Settings: Changing discussion threading to "none" causes settings to get out of sync in browser

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3641]
Under Settings > Discussion: More > Threading, setting the threading to "None" correctly disables comment threading on the site but doesn't uncheck the "Enable threaded (nested) comments" setting in the site's settings in a browser. As a result, the browser settings are out of sync and don't correctly control the site's comment threading.

Steps to reproduce:
1. In the app, select a site and go to Settings
2. Under Discussion, select More and then Threading
3. In the Threading window, select "None" and then "OK"
4. Check the front of the site and confirm that threading is off. (I used a post with a comment and a threaded reply, and the two comments were not threaded after making this change.
5. Check the site's discussion settings at https://wordpress.com/settings/discussion
Result: The browser settings have "Enable threaded (nested) comments up to 2 levels deep" checked. (Note that if you choose a different level of threading in the app settings, the browser settings change accordingly. The only issue is when "None" is selected.)

This doesn't only cause a syncing problem. After this, it's no longer possible to enable comment threading in the browser settings by simply unchecking/re-checking the "Enable threaded (nested) comments" setting. (This makes no change on the front of the site.) The only solution is to change the level of threading in the browser settings or re-enable threading from the app settings.

Testing on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-1.

**Comment by tonyr59h** [comment]
I think the best solution would be to add a switch to toggle threading, which is how it's handled in the Paging and Close After dialogs.

I also noticed an issue with Paging where the summary shows the value when it's disabled. I'll add a fix for that as well.

**Comment by rachelmcr** [comment]
Yeah, I think a toggle like that would make a lot of sense here.
