### ISSUE TITLE
Site Settings: Confusing display in discussion settings when "Paging" is toggled off

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3642]
In the discussion settings, the "Paging" setting always display the select number ("# comments per page") even if those settings are toggled off.

Steps to reproduce:
1. Select a site and go to Settings
2. Under Discussion, select More
3. Tap on "Paging" and toggle it on, selecting a number of days, and tap "OK." Confirm that under "Paging" it shows the number of days you selected.
4. Tap on "Paging" again and toggle it off, and tap "OK." Under "Paging" it still shows the number of days selected, instead of noting that Paging is disabled.

The "Close after" setting is also sometimes affected by this issue. Right after toggling "Close after" off, it will say "Never" under that setting in the discussion settings. However, if you exit the app and come back, it will go back to saying "# days" instead of "Never" (although the setting is still disabled).

Tested on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-1.

**Comment by rishabh7m** [comment]
Hi, I would like to work on this if anyone has not started :)

**Comment by maxme** [comment]
@rishabh7m you're free to work on any tickets unless it's assigned. And thanks for your contributions ;)

**Comment by tonyr59h** [comment]
Addressed in #3649.
