### ISSUE TITLE
Make Stats compatible with dual pane layout

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#3643]
This issue is a part of #3551 

Currently StatsActivity serves as a container for multiple abstract stats fragments that display stats data.
Stats are supposed to be a default view in upcoming double pane layout (like it's currently on the website). To be able to show stas as a part of dual pane layout we need to move all the code from StatsActivity to StatsFragment. 

Design wise, the main change will be to move the time frame spinner from toolbar 

![spinner_a](https://cloud.githubusercontent.com/assets/728822/12481638/dccb52b6-c08d-11e5-9d8b-9da49cac8328.png)

to fragment (we can't use toolbar in dual pane layout).

![spinner_b](https://cloud.githubusercontent.com/assets/728822/12481737/7560c4e8-c08e-11e5-9495-2576fc91b03c.png)

So the dual pane layout will look something like this:

![landscape](https://cloud.githubusercontent.com/assets/728822/12481891/a785b8d8-c08f-11e5-92c9-685502d1bc44.png)

About the code.
Most of the code nicely fits into fragment's lifecycle, except for couple of tricky parts:
There are multiple places in StatsActivity where finish() is called when something goes wrong, and activity just closes after showing error toast. This is fine in case of activity, but if the fragment is in dual pane layout this won't work, especially if stats will be a default fragment. 

Easy solution is to make StatsFragment remove itself after showing Toast/Snack with error message. This will leave us with confused user and some empty space (we could put WP logo there, or something like this).
![screenshot-2016-01-21_23 23 02 593](https://cloud.githubusercontent.com/assets/728822/12483006/0d1bc696-c096-11e5-94ce-1a5374e6e1fe.png)

Apart from issues with finish(), at some points user interaction might be required:

Missing Jetpack modal dialog
![jetpack](https://cloud.githubusercontent.com/assets/728822/12483297/79c88a80-c097-11e5-904c-71b2df244aac.png)

could be converted into Snackbar, but we would only have one button - YES

![jetpack2](https://cloud.githubusercontent.com/assets/728822/12483690/cae022e6-c099-11e5-994a-f453682eaf72.png)

Or, we can expand on error view idea, like this:
![screenshot-2016-01-21_23 48 58 8](https://cloud.githubusercontent.com/assets/728822/12483727/0117d156-c09a-11e5-92a5-ce55a4aeaf38.png)

The one issue I'm not exactly sure what to do about is the Sign in requirement for self-hosted site. I'm not sure at what circumstances exactly it happens (why would account not be signed in while browsing stats), but current code just launches SignInActivity without any prompt. I don't think this will work well within dual pane layout, especially when the fragment is default.

**Comment by maxme** [comment]
I'm not sure we want to implement dual pane anymore, we could eventually revisit the Stats view for large screen. cc @daniloercoli

**Comment by nbradbury** [comment]
I think we can close this one since we've moved away from dual-pane as a viable solution.
