### ISSUE TITLE
Site Settings: Some fields allow multi-line entries when they should be single-line fields

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3644]
In the site settings, some fields should only allow single-line entries, but currently the on-screen keyboard allows you to start a new line for a multi-line entry:
- Site Title (General settings)
- Tagline (General settings)
- Hold for Moderation (Discussion settings: Comments)
- Blacklist (Discussion settings: Comments)

This doesn't break anything, but it's confusing that the UI allows multi-line entries in these cases.

For site titles and taglines, the multiple lines are collapsed into a single line after saving.

Before saving:

![2016-01-21 16 28 13](https://cloud.githubusercontent.com/assets/8658164/12486785/0f158b10-c05c-11e5-97cb-ca5895dcffae.png)

After saving and reopening the site title setting:

![2016-01-21 16 28 23](https://cloud.githubusercontent.com/assets/8658164/12486792/1600f6bc-c05c-11e5-9209-24cbd579b570.png)

For the comment moderation and blacklist, the multiple lines are divided into separate entries once the screen is refreshed (and so they work correctly), but they are shown in a single entry at first which is confusing and hard to modify.

Entering multiple lines:

![2016-01-21 15 38 39](https://cloud.githubusercontent.com/assets/8658164/12486825/4229199a-c05c-11e5-8f16-ef24812b768e.png)

After saving the multi-line entry:

![2016-01-21 15 38 44](https://cloud.githubusercontent.com/assets/8658164/12486828/471ac732-c05c-11e5-8574-866355fbfec0.png)

After refreshing the screen:

![2016-01-21 15 39 04](https://cloud.githubusercontent.com/assets/8658164/12486839/4e19ef86-c05c-11e5-920a-92189cca599a.png)

Tested on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-1.

**Comment by maxme** [comment]
Similar to #3595
