### ISSUE TITLE
My Profile: no error shown if settings couldn't be retrieved/saved

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#3665]
Having created a new blank site and configured `wp.oauth.app_id`  and `wp.oauth.app_secret` in `gradle.properties`, go to the My Profile section in the app, the settings can't be loaded as we get a 401 error from the server. Attempting to modify any of the values then hitting the back arrow or back key throws an http `401` error as well as can be seen in the following logcat piece:

` 01-26 17:06:38.001 14234-14315/org.wordpress.android E/WordPress: [1816] BasicNetwork.performRequest: Unexpected response code 401 for https://public-api.wordpress.com/rest/v1.1/me/settings
01-26 17:06:38.002 14234-14234/org.wordpress.android E/WordPress-API: null
                                                                      com.android.volley.AuthFailureError
                                                                          at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
                                                                          at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
`

1) No errors are shown to the user - the user should be informed of what happened and ideally be suggested an action to take

2) It shouldn't be getting a 401 error at this time either

**Comment by mzorz** [comment]
I can confirm I consistently get 401 for `/rest/v1.1/me/settings` endpoint, even for GET requests - tried logging out and logging back in with new verification codes and getting new bearer tokens each time. Not the case for the other endpoints such as `/v1.1/tracks/record` or `/v1.2/read/sites/<id>/posts` for instance.

**Comment by mzorz** [comment]
OK - getting 401 from the server on My Profile screen was explained (app id needs be whitelisted). However a proper error handling would be good to have (i.e. still no toasts/alert shown to the user informing some problem appeared while trying to retrieve the current profile info)

**Comment by nbradbury** [comment]
> However a proper error handling would be good to have

:+1:

**Comment by oguzkocer** [comment]
Fixed in #3698.
