### ISSUE TITLE
View Admin: In-app browser refreshes view after rotating device

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3668]
When you use the in-app browser to view a site's wp admin dashboard, any time you rotate the device it refreshes and goes back to the main dashboard screen at `/wp-admin`. This loses your place and loses any unsaved work.

Steps to reproduce:

1. Select a site in the app and select "View Admin"
2. In the wp admin dashboard, navigate to another part of the dashboard (e.g. Settings > General)
3. Rotate your device

Result: You are returned to the main dashboard screen (instead of staying in the part of the dashboard you had navigated to).

Reported in an app review; tested and reproduced on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-2

**Comment by nbradbury** [comment]
Good catch @rachelmcr - this bug actually occurred not only in "View Admin," but also in many other places where an embedded webView was used.
