### ISSUE TITLE
Images are rotated in composition window

### ISSUE THREAD

**Issue by dllh** [wordpress-mobile/WordPress-Android#367]
Repro:

1. Snap a vertically oriented photo.
2. Write a new post.
3. Insert the photo.
4. Observe that it is oriented horizontally in the editor.
5. Publish.

Result: The photo is oriented correctly in spite of the sideways preview.

Expected: The preview will display correctly as well.

The first time I noticed this, I wasted some time going back in and rotating the image.
![screenshot_2013-11-26-06-57-40](https://f.cloud.github.com/assets/2738252/1621668/62096218-5693-11e3-910d-03f9cdb4c139.png)
![screenshot_2013-11-26-07-02-02](https://f.cloud.github.com/assets/2738252/1621671/6c2dad44-5693-11e3-9d67-b3ee36a5634a.png)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
