### ISSUE TITLE
Site Settings: "Learn More" popup not dismissible from left side

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#3677]
When trying to dismiss the popup by touching the area surrounding it, it's possible to do it from the right side, but not from the left side.

A screenshot to illustrate:

![dismiss-issue](https://cloud.githubusercontent.com/assets/11487924/12691826/b591b5ce-c6a4-11e5-833d-990af28669d3.png)

This happens on the Nexus 6

**Comment by maxme** [comment]
@tonyr59h should we use a "full screen" fragment instead (with an action bar and a back arrow)? Seems hard to read this in that very small area and feels like nothing else in the app.

**Comment by maxme** [comment]
Ooops... #3678

**Comment by tonyr59h** [comment]
Addressed in #3754.
