### ISSUE TITLE
Site Settings: "Learn More" popup can follow links in browser to odd pages

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#3678]
The "Learn More" pop up displays the links present in the webpage as usual, and therefore it's possible to go to unintuitive places from there. Maybe it would be better to open the support page using a new browser tab instead of as a pop up?

Here are some screenshots to illustrate:

![odd-pages-1](https://cloud.githubusercontent.com/assets/11487924/12691898/52123d42-c6a5-11e5-9847-c066b943bc58.png)
![odd-pages-2](https://cloud.githubusercontent.com/assets/11487924/12691899/52147044-c6a5-11e5-875a-af7e502710b9.png)
![odd-pages-3](https://cloud.githubusercontent.com/assets/11487924/12691901/52157a70-c6a5-11e5-9bdd-b86fe37a47c0.png)
![odd-pages-4](https://cloud.githubusercontent.com/assets/11487924/12691900/521539ca-c6a5-11e5-9803-1e86771ccb9a.png)

This is related to #3638

**Comment by tonyr59h** [comment]
> Maybe it would be better to open the support page using a new browser tab instead of as a pop up?

Other parts of the app will generally open a WebView in-app (rather than in the browser) so the UX isn't split between two apps. My first thought would be to intercept link clicks and ignore them. @mattmiklic any thoughts?

**Comment by tonyr59h** [comment]
Addressed in #3754.
