### ISSUE TITLE
Site Settings: Automatically approve setting from known users does not work as expected

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#3681]
When I select the 'Known users' comments' at the 'Automatically approve' section like this:

![approve-known-users](https://cloud.githubusercontent.com/assets/11487924/12697378/a89dd11e-c725-11e5-9ef1-2fbe589fecb9.png)

It saves the following two settings as on in wp-admin:
- Comment must be manually approved  
- Comment author must have a previously approved comment

![wp-admin-saved-known-users](https://cloud.githubusercontent.com/assets/11487924/12697384/da091cea-c725-11e5-9913-06d34ddf1f4a.png)

I expected only the 'Comment author must have a previously approved comment' checkbox to be checked, though, like this:

![expected-settings-for-known-users-approved](https://cloud.githubusercontent.com/assets/11487924/12697395/f6cefc00-c725-11e5-9c22-7bf3c7ca185d.png)

**Comment by tonyr59h** [comment]
Yikes! Can't believe this one slipped by my final test pass. Gonna mark this for `5.1` as it's a break in core functionality.

**Comment by tonyr59h** [comment]
Addressed in #3746.
