### ISSUE TITLE
Site settings: Blacklist/Moderation: should not be able to add newline character in item

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#3684]
Steps to reproduce:
1. Go to Site Settings > Discussion > More > Blacklist or Hold for Moderation
2. Click orange Plus button
3. See that you can enter a new line and it gets saved:
![add-new-line](https://cloud.githubusercontent.com/assets/11487924/12703874/f46047a4-c7f1-11e5-8ac5-4f7aaf0f5c6f.png)
![new-line-added](https://cloud.githubusercontent.com/assets/11487924/12703875/f57a25d8-c7f1-11e5-8f0c-248f00b89b0a.png)

Note that the newline character does not get saved in the backend, so it's a UI issue only.

**Comment by rachelmcr** [comment]
Dupe: #3644
This should be resolved by #3652.
