### ISSUE TITLE
Me: HTML entities are not decoded in author name

### ISSUE THREAD

**Issue by bluefuton** [wordpress-mobile/WordPress-Android#3688]
If an author name contains, for example, an ampersand, it is not decoded when displayed:

![2016-02-01 04 37 44](https://cloud.githubusercontent.com/assets/17325/12708925/9854d38e-c90a-11e5-98ed-92cd5d1201b9.png)

We recently ran into this on Calypso too: https://github.com/Automattic/wp-calypso/pull/2901

**Comment by oguzkocer** [comment]
Fixed in #3766.
