### ISSUE TITLE
After granting permissions for media upload, taken back to editor

### ISSUE THREAD

**Issue by bryceadams** [wordpress-mobile/WordPress-Android#3690]
When attempting to upload an image, I was prompted with the new dialog to grant permissions to view media on the device / upload (2 separate permissions). After granting permission to both of them, rather than allowing me to upload an image (expected), it took me back to the editor and I had to start the process again.

![screenshot_20160131-072311](https://cloud.githubusercontent.com/assets/1532482/12721285/bcad5ccc-c907-11e5-97ca-0a4e4aafb301.png)

Would be great if the flow wasn't interrupted after granting permission.

**Comment by rachelmcr** [comment]
Thanks for the report! What device/Android version/app version did that happen on?

When I test on my Nexus 9, Android 6.0.1, app beta v. 5.0-rc-2, the two permissions dialogs pop up but don't interrupt the flow. In both the editor and the Media section, the app immediately displays the usual media upload dialog after I give it permission to access/upload media.

**Comment by bryceadams** [comment]
Sorry, forgot to mention that! Using Nexus 6P, 6.0.1 and 5.0-rc2.



Best,Bryce

**Comment by rachelmcr** [comment]
Thanks! Hm. I tested this on a Nexus 6P emulator and couldn't reproduce there, either. After granting permission I was taken right to this media dialog:

![screen shot 2016-02-02 at 4 50 58 pm](https://cloud.githubusercontent.com/assets/8658164/12756801/5a19cf7a-c9cd-11e5-8a6c-c91c5467c173.png)

**Comment by bryceadams** [comment]
Hmm, maybe I just dismissed it by accident? If it comes up again I'll reopen :)
