### ISSUE TITLE
Comments: make Spinner status type filter part of the fragment 

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#3704]
Related to https://github.com/wordpress-mobile/WordPress-Android/issues/3643 and https://github.com/wordpress-mobile/WordPress-Android/pull/3691.

The Spinner now resides in the Activity's toolbar, but in order to be able to be used as a component, (as the filter acts on the data displayed by the RecyclerView), it needs be taken out of the Activity and moved into a fragment where the RecyclerView resides.

**Comment by nbradbury** [comment]
Closed via #3729
