### ISSUE TITLE
Theme browser won't load new themes when end of the list is reached.

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#3714]
Steps:
1. Open Themes from MySite.
2. Scroll down to the end of the list (might take a while).
3. While additional themes are loading and progress indicator is visible, rotate your device.
4. You are near the end of the list, progress indicator is jittering and the additional themes won't load.

And here is the **bad** part, after doing all abovementioned:
1. Go back to MySite.
2. Again, open Themes.
3. Scroll down to the end of the list.
4. Additional themes won't load. (In same orientation!).

Only thing that helps is app reinstall (maybe logout/login will help too).

Tested on Nexus 5 and Nexus 7 (2013).

**Comment by maxme** [comment]
I can repro. I'm not sure this is related to orientation change. When I hit the end of the list sometimes.

Also the method [`shouldFetchThemesOnScroll`](https://github.com/wordpress-mobile/WordPress-Android/blob/355068c8a176d6623b459c4530109b16690e539a/WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java#L317-L324) is flawed, it shouldn't return true when we hit the end of the list.

**Comment by tonyr59h** [comment]
Closed/obsolete via #6697. Now that all the themes are fetched upfront there's no additional loading when you reach the end of the list.
