### ISSUE TITLE
Stats: Weird behaviour of self hosted stats after disabling Jetpack.

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#3716]
Steps:
1. Add and select self-hosted blog from Site Picker.
2. Open Stats to make sure they are working (install Jetpack, if prompted).
3. Deactivate Jetpack from WP admin.
4. Open Stats again.
5. Login screen pops up asking you to login with WP.com account used to connect Jetpack.
6. Login.
7. Login screen pops up again.
8. Login.
9. Login screen pops up again.
10. :repeat: 

And here is the **bad** part, after doing all abovementioned:
1. Switch to some other blog from Site Picker (I switched to WP.com blog).
2. Switch back to self-hosted blog.
3. Open Stats.
4. Blank stats are shown.

You would expect Jetpack error to appear (we disabled Jetpack at step 3 of part 1) or Login screen to pop up. Or anything, that will suggest why stats are not working.

This can be fixed by enabling Jetpack or reinstalling app.
Tested on Nexus 5 and Nexus 7 (2013) with store and dev versions.

**Comment by rachelmcr** [comment]
Tested and reproduced on my Nexus 9 (Android 6.0.1, app beta 5.1-rc-2). Ideally we should go back to the popup prompting the user to install Jetpack on the self-hosted blog:

![2016-02-17 16 25 05](https://cloud.githubusercontent.com/assets/8658164/13116272/301508e4-d593-11e5-9487-f9e3febe612c.png)

**Comment by daniloercoli** [comment]
To address the issue properly we need to fix the backend. Working on it. No ETA at the moment.

**Comment by daniloercoli** [comment]
A first "quick" patch for this issue was merged in develop. Waiting FluxC for a full resolution of this kind of issues.

**Comment by lezama** [comment]
The backend fix broke https://github.com/Automattic/wp-calypso/issues/11308 :)
