### ISSUE TITLE
Reader post detail blank webview on activity pause/resume

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3724]
Spotted on the Play Store:

> The Wordpress Reader doesn't work. If you lock your phone, when you unlock it the page is blank.

I can reproduce:

1. Open a Reader post detail.
2. Lock your phone (or switch app / activity).
3. Unlock.
4. Webview is blank.

**Comment by nbradbury** [comment]
@maxme Are you seeing this with develop or an earlier version? I can't repro with develop, and I'm pretty sure this was fixed in #3583.

**Comment by maxme** [comment]
You're right, this is fixed in 5.1.
