### ISSUE TITLE
Virtual keyboard is not dismissed in site settings

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#3731]
PR https://github.com/wordpress-mobile/WordPress-Android/pull/3719 introduced a new issue, where the virtual keyboard stays on if the popup dialog is dismissed by tapping outside of it while editing.

Tapping `Cancel` or `OK` on the dialog does dismiss the keyboard but not if tapped outside of it. /cc @tonyr59h

**Comment by tonyr59h** [comment]
Verified that this is not an issue anymore, going to close for now.
