### ISSUE TITLE
Allow trashed comments to be "untrashed"

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#3732]
Comes from https://github.com/wordpress-mobile/WordPress-Android/pull/3729#issuecomment-182545665

> I just noticed that if you view the detail of a trashed comment, you can trash it again - which removes it from the list of trashed comments until you next refresh. This bug didn't come up before because prior to this PR we didn't show trashed comments. What should happen is you're able to untrash the trashed comment. I think this can be a separate issue with a separate PR - just wanted to mention it.

Same goes for  long-pressing/group actions on `trashed` list items.

Following the wp-admin site, actions on `trashed` list items should be:
- untrash (restore)
- spam
- delete permanently (check if there's API support for that)

**Comment by maxme** [comment]
> delete permanently (check if there's API support for that)

**Comment by mzorz** [comment]
The web admin app has a `restore` button for trashed comments, and it reverts then comment to its last state (as per my tests, it reverts to either of `approved|unapproved` states). After investigation it turns out there's no `restore` endpoint in the XMLRPC API. 
Given that there's no `restore` functionality supported by the XMLRPC API at the moment, we've decided to move on with the following:

Options:
1) having approve/spam/delete only (ditching `restore`) which surely is the most conservative approach, 
2) having `restore` set the comment status to `unapproved` as suggested by @maxme , as it will anyway be OK with the status lifecycle (trash->unapproved->approved)

Moving on with number 2 up here :+1: the functions we'll end up with are, as in the wp admin site:
Spam | Restore | Delete Permanently

**Comment by nbradbury** [comment]
Closed via #3745
