### ISSUE TITLE
Remove auto-sharing

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#3751]
As we have discussed on Slack, as part of the improvement of Account Settings, we are removing this feature completely. We believe it's not used often and not worth the trouble of maintenance.

**Comment by maxme** [comment]
+1 took me 2 minutes to realize it was the "reset auto-sharing settings" setting ;)

**Comment by rachelmcr** [comment]
It looks like this was resolved when #3753 was merged. I'll go ahead and close this issue, but please reopen if there are any lingering issues to resolve here.
