### ISSUE TITLE
Locale changes don't update ActionBar titles until there is a configuration change

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3755]
Good find @khaykov! Sounds like we're going to have to convert the remainder of our ActionBar usages to Toolbar in order to work around a caching issue.

See #3740 for more details.

**Comment by kwonye** [comment]
@tonyr59h is this safe to move to 5.6 or 5.7? I don't see any branch that has this work in it.

**Comment by tonyr59h** [comment]
Been investigating this one, some info before proceeding:

* Seems to be an issue with relying on the label supplied in `AndroidManifest`
* An explicit call to `ActionBar.setTitle` in `onCreate` will use the correct string
* To address this issue we've got to explicitly set the title in all Activities that use an ActionBar via `getSupportActionBar` _without_ using `Toolbar` _or_ calling `setTitle`

Activities that need updating:
- [ ] SSLCertsViewActivity
- [ ] AppLogViewerActivity
- [ ] HelpActivity
- [ ] EditCommentActivity
- [ ] SitePickerActivity
- [ ] NotificationsDetailActivity
- [ ] EditPostActivity
- [ ] AccountSettingsActivity
- [ ] AppSettingsActivity
- [ ] BlogPreferencesActivity
- [ ] MyProfileActivity
- [ ] NotificationsSettingsActivity
- [ ] StatsWidgetConfigureActivity
