### ISSUE TITLE
WPPrefUtils parse language code by using fixed length delimiter

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3756]
It seems that WPPrefUtils uses a fixed length delimiter (`NO_REGION_LANG_CODE_LEN`) in `public static Locale languageLocale(String languageCode)`, when parsing language code. 
Note that language codes could be upgraded server side to most recent "versions", and could return a 3 letters language code. See `language` definition in RFC5646 -  https://tools.ietf.org/html/rfc5646

I think it's better to validate what we receive from the server, with something like
`languageCode.indexOf("-")` and `languageCode.indexOf("_")` .

```
    public static Locale languageLocale(String languageCode) {
        if (TextUtils.isEmpty(languageCode)) return Locale.getDefault();

        if (languageCode.contains("-") || languageCode.contains("_")) {
            String sanitizedLanguageCode = languageCode.replaceAll("_", "-");
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                return Locale.forLanguageTag(sanitizedLanguageCode);
            } else {
                String[] splittedLanguageCode = sanitizedLanguageCode.split("-");
                if (splittedLanguageCode.length == 2) {
                    return new Locale(splittedLanguageCode[0],
                            splittedLanguageCode[1]);
                } if (splittedLanguageCode.length == 3) {
                    return new Locale(splittedLanguageCode[0],
                            splittedLanguageCode[1], splittedLanguageCode[3]);
                }
            }
        }

        return new Locale(languageCode);
    }
```

cc @tonyr59h @yoavf

**Comment by tonyr59h** [comment]
> I think it's better to validate what we receive from the server, with something like
languageCode.indexOf("-") and languageCode.indexOf("_") .

Agreed, this makes much more sense than the current implementation (albeit a bit more work :p).

**Comment by kwonye** [comment]
@tonyr59h is this safe to move to 5.6 or 5.7? I don't see any branch that has this work in it.
