### ISSUE TITLE
Getting a media error if VideoPress is not enabled

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#3758]
Publishing a post with a video ends up in a Android notification stating:
> Media Error
> Get the VideoPress upgrade to upload video!

We should improve this UX. Perhaps let the user know in advance that the post cannot be supported under the current plan.

**Comment by maxme** [comment]
It seems like a client bug - we should check this code https://github.com/wordpress-mobile/WordPress-Android/blob/03a9b3aff6eb366bfbe63cf545eacce4761b8433/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java#L773-L773 - and remove references to `WordPress.currentBlog` there.

**Comment by maxme** [comment]
I removed client side check for VideoPress in c1c3475 - we might have a server side issue on wpcom sites due to upload limitations via XMLRPC.
