### ISSUE TITLE
Improve description in PIN lock screen

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#3771]
I recently tapped on the `Turn PIN lock on` in Account Settings and I was presented by a screen asking me: Enter your PIN.

Now, what PIN would that be? My device pin? I'm sure not, but it might make lots of users sit there and think about it for a sec and still not be sure what this means or does. And what exactly will that lock down after I enter a PIN?

I guess we could improve this by adding a bit more detail here. Something like "Enter a new app PIN" (if I do it the first time around) or "Enter your current app PIN" if i'm going to change it. I'll leave to the more design+english fluent here to come up with the best wording ;)

**Comment by catehstn** [comment]
@mattmiklic can you suggest wording please?

**Comment by mattmiklic** [comment]
I'd go with 

- `Turn PIN code on` as the setting label,
- `Create your PIN code` when first setting it up,
- `Enter your current PIN code` as step 1 in changing it, and
- `Enter your new PIN code` as step 2 in changing it.

**Comment by maxme** [comment]
> Bonus points if we could integrate Fingerprint Unlock into this.

It's already integrated https://github.com/wordpress-mobile/PasscodeLock-Android/issues/22 - but I'm not sure if it's obvious (there is a small fingerprint icon below the virtual keypad).

**Comment by mattmiklic** [comment]
Oh nice! I hadn't actually turned it on. It might be nice to make it more clear in the description before you enable the feature that it works with fingerprint unlocking; I'll think about what we could do there on the next design groundskeeping day.

**Comment by tonyr59h** [comment]
We should hold off on this issue until we get more information on #5479.

NOTE: If we decide to remove the PIN lock this issue can be closed. If not we can close #5477.

**Comment by tonyr59h** [comment]
We're not going to continue to support the PIN lock feature. I'm going to close this issue out.
