### ISSUE TITLE
Update Site Settings to use new 1.2 REST endpoint language codes

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3781]
Looks like we can do away with using language IDs for WP.com settings and use language codes instead (`en`, `es`, etc...).

**Comment by maxme** [comment]
Does that mean we could drop the mapping file `WordPress/src/main/res/xml/wpcom_languages.xml`?

**Comment by tonyr59h** [comment]
Yep :)
