### ISSUE TITLE
Having a category with HTML entities make the Post.hasChanges() method returns true

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3788]
... probably due to how we load a Post.

<img width="371" alt="screen shot 2016-02-24 at 10 02 23" src="https://cloud.githubusercontent.com/assets/40213/13295664/cfcb18ce-dade-11e5-9fae-028d6fc2fded.png">

**Comment by maxme** [comment]
This was the root cause of this issue https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/295

**Comment by maxme** [comment]
I guess this is related to https://github.com/wordpress-mobile/WordPress-Android/issues/3788 - adding fluxc-obsolete label to this issue.

**Comment by aforcier** [comment]
Re-confirmed that this is fixed in the `fluxc-integration` branch.
