### ISSUE TITLE
Remove the Custom Media Picker from the app

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3789]
Our Custom Media Picker was introduced to:
1. replace the pop up menu we have when we tap the "insert media" button.
2. have a way to pick multiple photos / videos at once.

Unfortunately some of our users need to browse specific directories (depends of the Camera app they use) to pick their media, and that mean we would have to write a file browser within our Media picker. Our picker also suffer from some caching issues, and we don't have enough time to support it.

Proposed solution is drop it and, for supported API level, use the Android multi select media picker intent.

We could also try to leverage the Android picker to display images/videos from the WordPress LIbrary (We probably have to write a Content Provider to achieve that, but I don't know if we'll be able to reconcilate picked image and the WordPress Library image), that would allow us to kill the pop up menu completely.

cc @tonyr59h @aforcier 

Edit: Reminder to deprecate the [MediaPicker](https://github.com/wordpress-mobile/MediaPicker-Android) library once this is merged in.

**Comment by voltagex** [comment]
There's no info in your CONTRIBUTING doc to tell me whether +1s are allowed on this repo, so +1 from me.

I've just finished uploading a number of screenshots from an Android device and multiple select would have been great.

**Comment by maxme** [comment]
> I've just finished uploading a number of screenshots from an Android device and multiple select would have been great.

There are 2 ways in the current version of the app to select multiple images:

1. Select pictures in the Gallery or Photos app, then tap the "Share" button and select WordPress. The WordPress app will launch and ask you if you want to start a new post or upload the media to your library.
2. In the editor, when you tap the "Add media" button, you're prompted to choose between 5 options, use the last one ("New picker"), you can then select multiple images.

We're going to drop the latter, and replace it with the native multiselect picker.

**Comment by voltagex** [comment]
Thanks for that info.

**Comment by tonyr59h** [comment]
> for supported API level, use the Android multi select media picker intent

Note: API 18+ has support for the multi-select intent.

> We could also try to leverage the Android picker to display images/videos from the WordPress LIbrary

The [Storage Access Framework](http://developer.android.com/guide/topics/providers/document-provider.html) looks like it can handle that and will automatically add the library to the picker. I'll take a look at it, maybe we can finally get rid of the pop-up menu!

**Comment by maxme** [comment]
> ContentProvider added. The WordPress media library tab is now included in the system picker.

That's really nice!
 
> It's also possible to add Camera and Video options, which means all that's left to handle is gallery creation and we could axe the media pop-up

That would be awesome!

**Comment by tonyr59h** [comment]
The `DocumentsProvider` is just about finished! [Here's](https://cldup.com/9TFb-0gAJA.mp4) an example  showing the Media library and image capture flow. Unfortunately this will [only be available on API 19+](http://developer.android.com/guide/topics/providers/document-provider.html) meaning we'll need to continue using the MediaPicker library, albeit in a reduced capacity. Since the user will be able to use the system picker for their local files we can remove those tabs and provide only WordPress library media.

**Comment by maxme** [comment]
Would it be possible to show Media Library thumbnails? Picking a picture by its name is really bad.

The flow for taking picture / shooting video is a bit weird, I fear our users won't find it. I'm not sure if we con skip the popup :(

**Comment by tonyr59h** [comment]
> Would it be possible to show Media Library thumbnails?

Yes, the icons need a bit of attention but we will be showing a smaller thumbnail for each library image.

> The flow for taking picture / shooting video is a bit weird

Exactly my thoughts after implementing. If we wanted to forego the pop-up we would have to add another button to the editor toolbar but that would start to feel cluttered. I'll put the menu back in. At least now we won't have to come up with a solution for media gallery creation 👍

**Comment by maxme** [comment]
> Exactly my thoughts after implementing. If we wanted to forego the pop-up we would have to add another button to the editor toolbar but that would start to feel cluttered. I'll put the menu back in. At least now we won't have to come up with a solution for media gallery creation 👍

Yep the extra step of having pop up menu is not that bad, but our previous menu was not super friendly (6 options), having 2 options "Shoot" or "Pick" is much better.

**Comment by mattmiklic** [comment]
Had a chance to check this out today. Definitely like the idea of at least paring down the menu you see after tapping the image button in the editor, the current mix of options was pretty confusing, it's not immediately clear what they all do.

> Would it be possible to show Media Library thumbnails? Picking a picture by its name is really bad.

Agreed, is there any way to show these in a grid view instead of a list?

**Comment by tonyr59h** [comment]
> is there any way to show these in a grid view instead of a list?

Luckily for us that functionality is built into the system picker 😄 Users can switch it on the fly via an option in the Action Bar menu.

**Comment by tonyr59h** [comment]
[Progress video](https://cldup.com/HuNo1wVgc8.mp4) showing media content for the current blog filtered into each directory. Thumbnails working for images, video thumbnails still to come.

**Comment by mzorz** [comment]
Made some progress on this branch here, this is the ToDo list I've come up with, marking what's done:
- [x] merged develop and resolved conflicts
- [x] put the menu back in, with TAKE PICTURE or PICK PHOTO plus Pick
- [ ] implement actually grabbing whatever the user selected (one selection or multiple selection, and different kinds of
files) in onActivityResult in EditPostActivity to end up inserting the image / video in the post.
- [ ] implement video picker and thumbnails

**Comment by tonyr59h** [comment]
Closing this as irrelevant. The picker has been removed and @nbradbury is integrating a new photo chooser at the moment.

**Comment by tonyr59h** [comment]
[MediaPicker-Android](https://github.com/wordpress-mobile/MediaPicker-Android) deprecated.
