### ISSUE TITLE
Upgrade to support library v23.3 and use VectorDrawableCompat

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3791]
We must upgrade to v23.2 and add `vectorDrawables.useSupportLibrary = true` in our gradle config, also check that PNGs aren't generated anymore and make sure that works on all API levels.

**Comment by maxme** [comment]
There are some report of NPEs related to the RecyclerView version introduced by 23.2  - this ticket isn't a priority, we have very few VectorDrawables, so our apk size won't change much after the upgrade. It's safer to wait for v23.2.1 or later.

**Comment by tonyr59h** [comment]
Reminder: Update the `Drawable Resources` section in  `CONTRIBUTING.md` after this is merged.
