### ISSUE TITLE
Drop Open Sans for UI and use default font instead - keep Meriweather for user generated content

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3792]
Editor Ref: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/281

Calypso Ref: https://github.com/Automattic/wp-calypso/pull/3016

cc @nbradbury

**Comment by tonyr59h** [comment]
This might be a pain. There's a lot of new code added lately (between at least Site/Account settings) to customize fonts in preferences and the action bar.

**Comment by nbradbury** [comment]
FYI: I have a very outdated branch [here](https://github.com/wordpress-mobile/WordPress-Android/tree/feature/drop-open-sans) where I first explored dropping Open Sans.

**Comment by maxme** [comment]
@tonyr59h can you point it out? Looks like action bar font change should just be a matter of removing `app:fontFamily` attributes from `WPEditText`

**Comment by tonyr59h** [comment]
I may have been mistaken on the effort. It looks like most of the fonts I was referring to being set programmatically are done via [WPPrefUtils](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPPrefUtils.java).

**Comment by tonyr59h** [comment]
Part 2 completed in #3814, closing.
