### ISSUE TITLE
Switch to "AppCompat" versions of WPxxx widgets

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3799]
For example, `WPTextView` should extend `AppCompatTextView` rather than `TextView`. The AppCompat versions:

* Support textAllCaps style attribute which works back to Eclair MR1
* Allow dynamic tint via the background tint methods in ViewCompat
* Allow setting of the background tint using backgroundTint and backgroundTintMode attributes

Note: this should wait until the [Open Sans PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3796) is merged, since that renames some our widgets.

**Comment by maxme** [comment]
And we could probably replace the `fixWidowWords ` attribute by `android:breakStrategy="balanced"`
