### ISSUE TITLE
Preview query param is always set to true

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3800]
When browsing a post/page, the "preview" query param is [always set to true](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L171). It should only be true for unpublished posts/pages.

**Comment by nbradbury** [comment]
Hmm, I'm wondering if [the comment on that line](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java#L170) is incorrect and we always set the preview param to avoid bumping stats (?).

**Comment by maxme** [comment]
> Hmm, I'm wondering if the comment on that line is incorrect and

Yes, that comment is incorrect.

> we always set the preview param to avoid bumping stats (?).

Yes, this is the reason we use `preview=true` in all cases.
