### ISSUE TITLE
Reader: post view is empty after screen rotation

### ISSUE THREAD

**Issue by yoavf** [wordpress-mobile/WordPress-Android#3813]
When viewing a single post n the reader, rotating the screen makes the post disappear.

Video: https://cloudup.com/cPdTWiVEjBZ
Version: 5.1-rc-2 on Sony Z3C (D5803)

**Comment by nbradbury** [comment]
Thanks for the bug report @yoavf! This was actually reported already and was fixed in #3577 and #3583.

**Comment by maxme** [comment]
That's weird, this should not happen in 5.1-rc-2, I'll double check the 5.0 merge in `release/5.1` branch.

**Comment by maxme** [comment]
The fixes are in `release/5.1` and have shipped with 5.1-rc-2 - I'm unable to repro the issue on a Sony Z5C with 5.1-rc-2.

@yoavf does this happen consistently? (I wonder if we have another issue).

**Comment by yoavf** [comment]
@maxme yes, it does. How can I help debug?

**Comment by yoavf** [comment]
I've got a new build from the play store just now, `5.2-rc-1`, and I can't reproduce the issue anymore.

**Comment by maxme** [comment]
Thanks for the feedback @yoavf, and sorry I missed previous ping :/ - Good to know the bug is gone, I just hope this won't happen on final 5.1 (currently in staged rollout).

Issue is already closed, but feel free to reopen if it comes back.
