### ISSUE TITLE
Update public facing images to show updated fonts

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3816]
Note: Do not complete until 5.2 is released.

Now that we've dropped Open Sans we should replace screenshots that are supposed to reflect the current state of the app.

So far I've come up with:
- [ ] [Google Play Store](https://play.google.com/store/apps/details?id=org.wordpress.android)
- [ ] [Amazon App Store](http://www.amazon.com/Automattic-Inc-WordPress/dp/B004GFN11A/ref=sr_1_1?s=mobile-apps&ie=UTF8&qid=1456977684&sr=1-1&keywords=wordpress)
- [ ] WordPress.org apps [support site](https://apps.wordpress.org/support/) (wow these images are old!)
- [ ] Learn More dialog (in-app)

**Comment by nbradbury** [comment]
Any chance we can have fewer cat-related screenshots this time? Those just make our app look so cutesy.

PS: I'd say the same thing if we had dog-related screenshots, despite the fact that dogs are clearly superior creatures.

**Comment by roundhill** [comment]
How about hedgehogs? Everyone loves hedgehogs.

**Comment by tonyr59h** [comment]
> the fact that dogs are clearly superior creatures.

:+1: to that

I agree, we should broaden our appeal, don't want our app to look like a one-trick-pony ;)

**Comment by maxme** [comment]
> Any chance we can have fewer cat-related screenshots this time? Those just make our app look so cutesy.

The screenshot generating tool now use our official test site (it's travel blog).

**Comment by maxme** [comment]
done
