### ISSUE TITLE
Reader: using the FilteredRecyclerView component, elevation for actionbar should be eliminated for the Posts tab only

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#3827]
(Comes from this https://github.com/wordpress-mobile/WordPress-Android/pull/3801)
### Expected behavior
The elevation should only be visible for the Toolbar when a toolbar is present.

### Actual behavior
There's 2 degrees of elevation: one in the Actionbar, and another one in the toolbar

### Steps to reproduce the behavior
Just get the code from the cited PR and see the Reader tab. When the toolbar is visible, you'll see the elevation is set twice, once at the bottom of the actionbar, then again there's elevation at the bottom of the toolbar

**Comment by mzorz** [comment]
@nbradbury @mattmiklic provided a solution here: https://github.com/mzorz/WordPress-Android/pull/1 

And here's a quick video of it working https://www.dropbox.com/s/lhlbqwl6mumzabw/tablayoutshadow.mp4?dl=0

Let me know your thoughts

**Comment by mattmiklic** [comment]
This looks pretty good to me. It is a tiny bit awkward when the shadow disappears as you're swiping, but it doesn't bother me because I don't think users will look at it that closely, and it's only an issue during the swipe animation. :+1: from me.

**Comment by mzorz** [comment]
Awesome @mattmiklic !  @nbradbury I'll merge my fork's PR then you can merge the original #3801 , sounds good?

**Comment by nbradbury** [comment]
Sounds good!

**Comment by mzorz** [comment]
Merged - this issue can be closed now, and https://github.com/wordpress-mobile/WordPress-Android/pull/3801 ready for merge @nbradbury
