### ISSUE TITLE
Add scheduled posts indicator in calendar when scheduling post

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#3828]
This is a feature request for showing on the calendar when posts are already published or scheduled. Here's what the calendar looks like right now:

![wordpress-android-calendar](https://cloud.githubusercontent.com/assets/11487924/13555697/465ed6f6-e37c-11e5-8233-21910fdc4844.png)

Maybe we could add circles to indicate the days that already have posts scheduled or published? Calypso does it in a similar way:

![calypso-calendar](https://cloud.githubusercontent.com/assets/11487924/13555703/6e6d5334-e37c-11e5-9521-2073116abd0e.png)

**Comment by maxme** [comment]
I'm pretty sure this can't be done with the native date picker. Write and maintain our own date picker seems a bit out of scope, or very low priority.

**Comment by v18** [comment]
Okay, that's understandable. Thanks for looking! I'm marking this as closed, then.
