### ISSUE TITLE
Re login with different user - shows posts from last user

### ISSUE THREAD

**Issue by mihai28** [wordpress-mobile/WordPress-Android#383]
Hello,

I have 2 users, each one with his posts (private posts), when i switch-login from one to the other, I see the posts from the last user. This is solved if I refresh, but where can I set an automatic refresh for the current user at login (both in 'view admin' and 'my posts')?

I browsed the issues list, but found nothing of the sort.

Many thanks :)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
