### ISSUE TITLE
Enhancement - Request for tabs for draft posts vs published

### ISSUE THREAD

**Issue by ChrissiePollock** [wordpress-mobile/WordPress-Android#3859]
### Expected behavior
Make a separated tabs for draft and published post. (like the iOS app)

### Actual behavior
All posts show in one area. Some are identified as drafts while others are published

**Comment by rachelmcr** [comment]
This will be added as part of the Calypsoification of Posts & Pages (phase 3): https://github.com/wordpress-mobile/WordPress-Android/issues/2793

Closing this issue as this enhancement is being tracked there. Thanks!
