### ISSUE TITLE
Visual Editor: Pasting formatted text into the HTML editor pseudo-retains formatting

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#3864]
### Steps to reproduce the behavior
Write formatted text, copy it to the clipboard, switch to the HTML editor, paste the text in.  It looks formatted, but it's not.  Switching back to the visual editor loses the formatting.

### Expected behavior
The text should appear without formatting in the HTML editor.  There could be an argument for pasting in the text with the markup, but I don't think that's necessary.

### Actual behavior
The text appears with formatting, but it's actually plain text.

##### Tested on Nexus 6P, Android 6.0.1 (shown on emulator below)

![wp-android-visual-editor-2](https://cloud.githubusercontent.com/assets/7233112/13758037/af0bc43e-e9fd-11e5-9425-bcaf12243eae.gif)

**Comment by aforcier** [comment]
Moved to editor repo: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/318
