### ISSUE TITLE
Visual Editor: Pasting formatted text into the title field yields HTML code

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#3865]
### Steps to reproduce the behavior
Write, highlight, and copy formatted text.  Paste that text into the title bar of the post from the visual editor.  It appears formatted.  Switch to the HTML editor and you'll see the HTML codes.  Switch back to the visual editor, and the HTML remains.

If you don't switch to the HTML tab, and just publish instead, then the title shows up properly formatted on the published post.

### Expected behavior
Either pasting formatted text into the title bar should yield plaintext, or else formatting from the HTML editor should be retained when switching back to the visual editor

### Actual behavior
HTML formatting is lost in the title field when moving from HTML to visual editor

##### Tested on Nexus 6P, Android 6.0.1 (shown below on emulator)

![wp-android-visual-editor-3](https://cloud.githubusercontent.com/assets/7233112/13758411/bf5e8ff4-e9ff-11e5-969e-37396a22cca3.gif)

**Comment by aforcier** [comment]
Moved to editor repo: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/319
