### ISSUE TITLE
Visual Editor: Exiting a list element inside a block quote yields two block quotes

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#3866]
### Steps to reproduce the behavior
Create a list (ordered or unordered) inside a block quote.  Add a new element, but don't add any text to it.  Exit the list format by either pressing the list format button, or just press enter.  A second empty block quote is created.

### Expected behavior
You only have a single block quote

### Actual behavior
You end up with two block quotes

##### Tested on Nexus 6P, Android 6.0.1 (shown on emulator below)
![wp-android-visual-editor-4](https://cloud.githubusercontent.com/assets/7233112/13759751/07978bf8-ea06-11e5-9d40-cb1f5346a6c4.gif)

**Comment by aforcier** [comment]
Moved to editor repo: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/321
