### ISSUE TITLE
Visual Editor: Copy/Pasting a block quote copies CSS formatting, not the blockquote tag

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#3867]
### Steps to reproduce the behavior
Create a block quote around some text.  Copy the text, and paste it into another part of the post, and observe that it looks sort of like a block quote...but look at the HTML and you see it's just got the background color set.

### Expected behavior
The entire block quote is copy/pasted

### Actual behavior
Only a vague imitation of the block quote is copied.

##### Tested on alpha-3 Nexus 6P, Android 6.0.1 (shown below on emulator)
![wp-android-visual-editor-5](https://cloud.githubusercontent.com/assets/7233112/13759919/e486f698-ea06-11e5-836d-f9c6315e7e68.gif)

**Comment by aforcier** [comment]
Moved to editor repo: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/320
