### ISSUE TITLE
i18n: "No %s comments" is hard to translate

### ISSUE THREAD

**Issue by akirk** [wordpress-mobile/WordPress-Android#3877]
In b051669ecf9056b912cd7641ae329933a163f539 the string `No %s comments` was introduced which is hard to translate: it is a string concatenation, translators can't know what `%s` will mean and depending on `%s` different translations might be needed.

Possible solutions:
1. Revert back to `No comments with this status found`
2. Change the text to `No comments found with status: %s`
3. Introduce 5 new strings and use a `switch()`
  -  `No Approved comments`
  -  `No Pending comments`
  -  `No Spam comments`
  -  `No Unknown comments`
  -  `No Trashed comments`

cc @mzorz

**Comment by maxme** [comment]
Agreed, my vote goes for solution #3.

**Comment by mzorz** [comment]
Ok, I just finished #2 :), but working on #3 now
