### ISSUE TITLE
Investigate support for opening in the Reader links in subscription emails

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3888]
Subscription emails include several calls to action: Read more, comment, like, see all comments, etc. Currently these all open in a browser, but if the app is installed it would be nice to provide the option to view the links in the reader.

[Requested in the forums](https://android.forums.wordpress.org/topic/email-to-app-redirection?replies=2#post-21295).

**Comment by hypest** [comment]
#4669 will cover some of the use cases mentioned in this ticket (for example, tapping the post title in the email will bring up the app directly into the Reader or the picker to select the app).
