### ISSUE TITLE
Reader: Empty Likers in Detail View on Certain Posts

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3899]
In the Reader detail view, some posts don't show the likers. You can actually still tap on the area where they should display, and then it loads the likers detail view but it is empty:

![screenshot_20160324-080237](https://cloud.githubusercontent.com/assets/789137/14024595/1c9a39da-f1a7-11e5-8793-8fbf9755cff9.png)
![screenshot_20160324-080251](https://cloud.githubusercontent.com/assets/789137/14024596/1cb0d35c-f1a7-11e5-8a37-b63e88fd0595.png)

Other posts display the likers just fine... but here's one that I know for sure doesn't work: https://tekartist.org/2016/03/23/♫-dee-crell-form-2-all-i-am/

Tested on Samsung Galaxy S6, Android 6.0.1 on versions 5.2-rc2

**Comment by nbradbury** [comment]
Problem appears to be due to Jetpack posts not returning `meta/data/likes` section when `?meta=likes` is requested. For example, `read/sites/1618138/posts/27632/?meta=site,likes` doesn't contain that section. That section does exist for wp.com posts, though.

**Comment by nbradbury** [comment]
Update: the backend fix is being worked on, will close this issue once it's merged and tested.

**Comment by nbradbury** [comment]
Backend fix has been deployed and verified.
