### ISSUE TITLE
Reader missing followed posts

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3908]
From @rachelmcr:

> A user reported that the Reader in the Android app isn’t updating with new posts from all of the blogs they follow. They see new posts from some blogs (so it does update) but not all blogs. The Reader is working fine for them in a web browser, with all new posts appearing there. The user’s device is an Alcatel One Touch 6010D running Android 4.1.1 with WPAndroid 5.1.1 (in German).

> I am seeing the same behavior in my Reader on my Nexus 9, Android 6.0.1, WPAndroid alpha-4 (in English). I am seeing updates from some of the blogs I follow (mostly from RSS feeds I follow, but also one VIP site on wp.com) but other new posts aren’t showing up at all. I do see those new posts in the web Reader and the iOS Reader. When I try refreshing the Android Reader manually, I see [READER] d: requested posts response = UNCHANGED in my application log.

I was able to reproduce this with followed sites, but not consistently. Even when new posts are received, sometimes other new posts will be missing from the stream.

**Comment by rachelmcr** [comment]
A user reported this issue again in Helpshift issue 92103. In this case, no posts are appearing in their reader in the app (but they do see posts in the web reader).

Device details: Samsung Galaxy A8, Android 5.1.1, app version 5.1.1.

**Comment by rachelmcr** [comment]
A user also reported this issue in an app review (one star):

>bad update
>Since it has been updated I can not read the various blogs that I subscribe from the reader so please fix the problem.

**Comment by amylaneio** [comment]
Two more reports in Helpshift Issues 93398 and 93605

**Comment by nbradbury** [comment]
It looks like this is being caused by a bug in the backend. The endpoint `read/following/mine?meta=site` always shows the `is_following` field under `meta/data/site` as false. This causes the Android app not to consider any followed blogs as followed, so their posts are excluded from the reader and the blogs don't show up as followed.

**Comment by nbradbury** [comment]
Update: the backend fix has been deployed, and tested successfully with the Android app.

**Comment by rachelmcr** [comment]
Thank you! I confirmed that it's also fixed on my end, and I replied to all the users who reported that issue to let them know.
