### ISSUE TITLE
Can't schedule a saved draft

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3913]
Originally reported in https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/269: It isn't possible to schedule a saved draft. Changing the date does not schedule the post, and changing the date and status publishes the post immediately.

### Expected behavior
It should be possible to open a saved draft in the editor and schedule it to be published at a future date.

### Actual behavior
When you try to schedule a saved draft, it is published immediately instead of being scheduled for the future date you select.

### Steps to reproduce the behavior

1. Create a new post in the app
2. Open the post settings, change the status to Draft, and tap Save
3. Wait for the post to upload and confirm it is saved as a draft
4. Open the draft in the editor
5. Open the post settings, change the publish date to a future date/time, and tap Update
Result: Draft is still saved with current date/time. It isn't scheduled and the future publish date/time is not saved.
6. Open the draft in the editor
7. Open the post settings, change the status to Publish and change the publish date to a future date/time, and tap Schedule

Result: The post is published immediately instead of being scheduled for a future date/time

##### Tested on Nexus 9, Android 6.0.1

Originally reported by a beta user, tested and reproduced on a Nexus 9, OS 6.0, beta v. 4.8-rc-1.

I tested and confirmed this is still an issue using the steps above when publishing from the new visual editor on Nexus 9, Android 6.0.1, version alpha-4.

**Comment by rachelmcr** [comment]
This issue was also reported in two recent app reviews:

>I like this app but I can never schedule a post. Every time I try, even today when said said "schedule" it goes ahead and publishes it instantly. PLEASE FIX THIS!

>Scheduling still doesn't work
>Despite everything, setting a scheduled post means that it still goes live immediately

**Comment by maxme** [comment]
This was introduced by a bug in XMLRPC API on WordPress, it's fixed in WordPress 4.5 - https://core.trac.wordpress.org/changeset/37043

We could duplicate the logic client side, but I would prefer to avoid yet another workaround.

**Comment by maxme** [comment]
Confirmed, it's fixed in WordPress 4.5 (and wordpress.com).
