### ISSUE TITLE
My Sites: Visit Site view does not display Like button or Likes

### ISSUE THREAD

**Issue by danielwrobert** [wordpress-mobile/WordPress-Android#3918]
### Expected behavior

In the `View Site` view from the `My Sites`, the `Like` button and the list of Likes should show up at the bottom of the posts, next to the Follow button. I confirmed that this functions properly on iOS:

![2016-01-24 06 51 05](https://cloud.githubusercontent.com/assets/481776/14220113/08538b76-f82c-11e5-8fa3-f3f55d63b844.png)
### Actual behavior

On Android, this part seems to get stuck with the `Loading ...` message and never populates button or list of Likes:

![2016-01-24 11 52 54](https://cloud.githubusercontent.com/assets/481776/14220130/2a0980fe-f82c-11e5-8a65-a05a26a0947b.png)

This _may_ be related to #3899, but it seems like a different issue.
### Steps to reproduce the behavior

From the `My Sites` screen (the WordPress icon in the top nav bar), select a site (if you are already placed in the site details view, go back one view via `<- SWITCH SITE`). From there, select `View Site`. From here, when you scroll through the post listing on this front-end view of the site, you will notice that the `Like` buttons and list of Likes are not getting rendered but, instead, stuck at `Loading...`. This seems like a pretty minor bug but I thought it was worth reporting anyway, especially since it works on iOS. 
##### Tested on
- Nexus 6, Android version 6.0.1
- iPhone 6 Plus and iPhone 6s Plus, iOS version 9.3.1

**Comment by khaykov** [comment]
Fixed in #4254
