### ISSUE TITLE
Stats: broken view in Portrait mode on tablets

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3920]
Noticed this, when taking screenshots:

![en-5-stats-google_nexus_10___5_1_0___api_22___2560x1600](https://cloud.githubusercontent.com/assets/40213/14239776/b3b179c8-fa3f-11e5-8d78-437b134d9007.png)

### Steps to reproduce the behavior

Go to Stats in Portrait

##### Tested on Nexus 10 (Genymotion), Android 5 - wpandroid 5.2
(works OK on phone and tablet 7")

**Comment by daniloercoli** [comment]
Not 100% sure, but I think this issue was introduced with the latest changes to the layout made by @mzorz . Would you mind to take a look at this?

**Comment by mzorz** [comment]
sure! I'll check that as I get some time!

**Comment by mzorz** [comment]
hi @daniloercoli - sorry for not being able to try this before, I've just tested on a tablet using this commit (some days before I started my trial) https://github.com/wordpress-mobile/WordPress-Android/commit/fbea6283ad4a3aa81ea9cadb13b8ba234c209db3 and I can observe this behavior as well. So it doesn't seem related to my changes, but I'm happy to check in this again later this month as soon as I finish my rotation if you want! let me know :+1:

**Comment by mzorz** [comment]
Checked code and tested. Looks good to me! :+1:

**Comment by mzorz** [comment]
can't merge to `develop` myself though :grin:  - will let you do that

**Comment by daniloercoli** [comment]
Thanks @mzorz! Will do the merge.
