### ISSUE TITLE
Exceeding the 64k method limit

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#3924]
The `feature/gravatar-upload-okhttp` branch (at https://github.com/wordpress-mobile/WordPress-Android/commit/30fa9714d2072d1f635893e1ef97eecfdc65372f) manages to exceed the 64k method limit.

We need to decrease the app's current method count.

**Comment by maxme** [comment]
In current `develop` ede6a91b614322adb00d991c27618ad39fc3f27d, overall method count: 63910 (debug) / 63889 (release)- so that's definitely a problem we have to solve asap.

**Comment by maxme** [comment]
Most significant numbers:

```
android support 20573 + google libs: 6099
wpandroid itself + subprojects (editor, stats, etc.): 11877
kotlin runtime: 6603
helpshift: 4071
simperium: 955 + koushikdutta (async android): 2794
apache commons: 2396
crashlytics: 1013 + fabric: 1188
mixpanel: 1716
```

**Comment by maxme** [comment]
Adding proguard shrink mode helps to kill ~25K methods, but it adds ~15 seconds compile time. After proguard:

Overall method count: 38472

```
android support 12628 + google libs: 3043
wpandroid itself + subprojects (editor, stats, etc.): 11030
kotlin runtime: 139
helpshift: 3293
simperium: 762 + koushikdutta (async android): 1341
apache commons: 102
crashlytics: 699 + fabric: 797
mixpanel: 1273
```

Conclusions: 

* WPandroid count before / after is almost the same (no room for improvement here), 
* Stripping android support and google libs is the major win (13K). 
* Helpshift count seems huge even after shrinking. 
* We're using very few Kotlin runtime and Apache commons methods.
* We don't want to add 15 secs to each debug build :cry: 

I'll try to enable the new build tool chain (Jack and Jill), from the [doc](https://source.android.com/source/jack.html#incremental_compilation):
> JACK has shrinking and obfuscation support and uses proguard configuration files to enable shrinking and obfuscation features. Here are the supported and ignored options:

**Comment by hypest** [comment]
Will close this since we got some headway by #3927

**Comment by hypest** [comment]
Reopening so to keep an eye on it.

**Comment by sendhil** [comment]
Man... Helpshift sure has a lot of methods ;).
