### ISSUE TITLE
Reader: Primary tags shown in post cards can included url encoded ampersands. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3939]
The steps I took were: 

- Sign in to the app with a self-hosted, no wpcom acct. 
- Navigate to the reader.
- In the tag list, select "Science & Nature" 

Many of the primary tags shown in the list contained url encoded ampersands. Examples:
`#Musings &amp; Personal`
`#Crafts &amp; Fashion` 

If you tap to preview the tag the header in the preview will also included the encoded ampersand.

**Comment by nbradbury** [comment]
Example:

![amp](https://cloud.githubusercontent.com/assets/3903757/14444780/e0ac2d02-0015-11e6-9a73-d4bcfa0a5cd2.png)
