### ISSUE TITLE
Reader: Issue with primary tags under the News & Current Events topic 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3940]
To reproduce: 
- While signed in with just a self-hosted account browse to the reader and selected the `News & Current Events` topic. 
- Notice the post cards show a primary tag of `#News/ Current Events`.  The slash seems odd, maybe something misformatted? 
- Tap to preview the primary tag. 
- The tag preview shows "No posts with this tag."

**Comment by nbradbury** [comment]
Example:

![example](https://cloud.githubusercontent.com/assets/3903757/14444811/1abc0152-0016-11e6-8959-b1d67e89fbb4.png)
