### ISSUE TITLE
Stats: Incorrectly prompted that Jetpack was not installed. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3941]
My self-hosted test blog has the latest version of the Jetpack (3.9.6) plugin installed, but it is not connected to WordPress.com.
When tapping the Stats option in the blog details screen, I see the stats activity appear and try to sync. Eventually it stops syncing and I'm prompted with an error that reads: 
"Jetpack plugin not found, The Jetpack plugin is required for stats. Do you want to install Jetpack? No / Yes" 
If I tap yes I'm taken to the Add Plugins page and I see in the list of plugins that Jetpack is *already* installed.

**Comment by daniloercoli** [comment]
Unfortunately we can't detect when the plugin is installed but disabled on the self hosted installation with a non heuristic approach.

We can try to guess if the plugin is installed and disabled, but we can't be sure of that. For sure, it will be an improvement, since the new function that I've in mind returns `true` if, and only if, the plugin is installed and disabled. 
Should I try to implement that? /cc @astralbodies @maxme

**Comment by maxme** [comment]
How it's done in the iOS app? Worst case, we can reword that dialog: "Jetpack plugin not found, you either need to install or enable it."

**Comment by daniloercoli** [comment]
> ow it's done in the iOS app?

@astralbodies  ^

**Comment by astralbodies** [comment]
Added a self-hosted site that has the plugin installed but not connected:
![img_9777](https://cloud.githubusercontent.com/assets/373903/14529338/af9b31da-0219-11e6-91ea-07620ec1c989.PNG)

and

![img_9778](https://cloud.githubusercontent.com/assets/373903/14529339/b16dedcc-0219-11e6-8708-1ed348a5ddc0.PNG)

**Comment by aerych** [comment]
> Worst case, we can reword that dialog: "Jetpack plugin not found, you either need to install or enable it."

Looks like rewording would work until we can expose some new detection API.  https://jetpack.com/support/debug/ has functionality similar to what we'd want I think.  Maybe @kraftbj could lend an assist?

**Comment by aerych** [comment]
I pestered our friendly Jetpack folks with this question.  Support for detecting Jetpack connection issues is slated for the v4.1 release in June.  Maybe we can tweak the verbiage now and add some improved status detection for the future release.

**Comment by aerych** [comment]
Interestingly, I get a different result from @astralbodies on the iOS app. Same situation, a self-hosted blog with Jetpack installed but disconnected. 
![simulator screen shot apr 14 2016 10 31 33 am](https://cloud.githubusercontent.com/assets/1435271/14533832/5e29e48c-022c-11e6-8934-6542caaf800a.png)
![simulator screen shot apr 14 2016 10 31 41 am](https://cloud.githubusercontent.com/assets/1435271/14533846/6730b4f2-022c-11e6-8214-a1aefcd1a071.png)

**Comment by daniloercoli** [comment]
@astralbodies @aerych Installed, Active, but not connected?

**Comment by aerych** [comment]
My test case was installed and active, but not connected.

**Comment by aerych** [comment]
Retested, and confirming that when Jetpack is installed but not connected I see the prompt to install Jetpack
![screenshot_20160414-105312](https://cloud.githubusercontent.com/assets/1435271/14534556/516bcf28-022f-11e6-9187-cca6cc32d646.png)

The iOS app is examining blog options to glean a bit of info about Jetpack's state. 
https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Models/Blog.m#L611

**Comment by astralbodies** [comment]
Whoops, sorry, mine wasn't active but installed.
