### ISSUE TITLE
Post List: Stats appears broken for self-hosted / non-Jetpack blogs

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3944]
To reproduce: 
- Sign into the app with a self-hosted blog sans Jetpack. 
- Go to the blog list. 
- Notice that there is a Stats button shown in the post cards even though the blog is not connected to JP. 
- Tap the Stats button in one of the post cards. 
- The stats screen loads with an error that "stats couldn't be refreshed at this time"

I'd suggest not showing the stats button for published posts on self-hosted/non-Jetpack sites.

**Comment by aerych** [comment]
Same goes for the menu in the Page list.

**Comment by gaui** [comment]
I have JP on my self-hosted site, still I'm experiencing this issue.

**Comment by daniloercoli** [comment]
> I'd suggest not showing the stats button for published posts on self-hosted/non-Jetpack sites.

Stats button it's not available for self-hosted blog.
The button could be there is there was a previous installation of JP on the blog. Investigating this issue.

Also trying to fix the issue on JP blogs connected with another wpcom account, not yet configured into the app (configuration is done in the main Stats Screen).
To repro this issue: Add a blog connected to another .com account, and without configuring it in Stats, go to posts list and tap the Stats button.
The generic "stats couldn't be refreshed at this time" is shown, instead a better error message should be presented, or start the JP login flow.

**Comment by maxme** [comment]
This should wait for FluxC (or be checked / fixed in the FluxC integration branch) as Jetpack handling will be different.

**Comment by daniloercoli** [comment]
@maxme  Fixing the problem with Jetpack blogs connected to other wpcom account is an easy fix in develop. Is't FluxC 2 months away from our end-users?
I could fix it in both branches.

**Comment by maxme** [comment]
This was fixed in FluxC integration (Stats button is not visible on pure self hosted sites).
