### ISSUE TITLE
Media: Unable to use photos from library when camera permission has been denied.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3945]
To reproduce:
- From a fresh install open the editor and tap to add media to a post. 
- When prompted to allow access to the camera, tap deny. 
- When prompted to allow access to the library, allow. 

My expectation is WordPress won't have access to my camera but will still be able to pull media from the phone's gallery, or the blog's media library.  Instead I see an error message saying that permission is needed.

**Comment by daniloercoli** [comment]
@mzorz Is your work on the new media picker (https://github.com/wordpress-mobile/WordPress-Android/issues/3789) fixing this issue here?

**Comment by nbradbury** [comment]
@daniloercoli @mzorz This will be something I'll need to tackle as part of the device photo chooser I'm working on.

**Comment by mzorz** [comment]
This shouldn't be an issue with the new media picker. Will get in touch tomorrow with @nbradbury to check :+1:

**Comment by nbradbury** [comment]
Note to myself that this is still an issue, even with the new picker.
