### ISSUE TITLE
Site Picker: Add site launches with previous sites info filled in. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3947]
From a fresh install, sign in with a self hosted blog: 

- On the blog details screen tap "Switch Site"
- On the Choose site screen, tap the + button to add a new site. 

Notice the Sign in screen launches with the username and URL are already filled out with the previous site's info.

**Comment by aforcier** [comment]
This issue now only applies to the URL field - the username is no longer persisted since https://github.com/wordpress-mobile/WordPress-Android/pull/3971.

The URL field persistence issue is addressed in #4697.
