### ISSUE TITLE
Media: Improve experience when a user's role does disallows access to media.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3949]
On the Post, Pages and Comments lists, when a user's role does not give them permission to view that content we display a label stating so.   On the media feature, we display a toast that disappears.  What's more, the add media button remains active which just leads to a failed upload. (See attached.)  
Let's update the media feature to be consistent with Posts, Pages, and Comments. 
### Comment example

![screenshot_20160411-195758](https://cloud.githubusercontent.com/assets/1435271/14446876/32eae482-0020-11e6-8aa1-4f95d18b08f2.png)
### Media example

![screenshot_20160411-195804](https://cloud.githubusercontent.com/assets/1435271/14446877/35af9fa0-0020-11e6-8137-7d78db25197a.png)

**Comment by maxme** [comment]
This was fixed, the media library empty view is now consistent:
![screenshot-2017-01-02_16 20 03 859](https://cloud.githubusercontent.com/assets/40213/21591782/6b41c784-d107-11e6-83c7-4acc5b8d75e0.png)
