### ISSUE TITLE
Reader has problems with emoji

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3956]
Rather than describe it, here are screen shots of the list view and detail view.

List view:
![listview](https://cloud.githubusercontent.com/assets/3903757/14459202/8b3f19f0-0084-11e6-81b2-74c2c6be4c89.png)

Detail view:
![detailview](https://cloud.githubusercontent.com/assets/3903757/14459259/d0fa7732-0084-11e6-90ff-b3ae940e23a6.png)

**Comment by theck13** [comment]
Is this still an issue?  The list and detail views show the emojis as expected while I was testing.  See the examples below.

![20160525_135434](https://cloud.githubusercontent.com/assets/3827611/15554464/9ceb6900-2281-11e6-8be0-028adf259e1a.png)

![20160525_135423](https://cloud.githubusercontent.com/assets/3827611/15554463/9ceb1ca2-2281-11e6-86da-84290219ae3b.png)

**Comment by theck13** [comment]
This can no longer be reproduced.  The initial issue may have been be due to Open Sans font, which was dropped in v5.2 and replaced by the device's native font.
