### ISSUE TITLE
Implement Magic Link sign in

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3959]
Implement "Magic Links" much like how Slack does. Instead of asking the user to enter their password, they can enter their email and get a link to login.

Mirrors wordpress-mobile/WordPress-iOS#4912

**Comment by kwonye** [comment]
Feature currently lives in `feature/magic-link` branch cc @mattmiklic

**Comment by mattmiklic** [comment]
Looking good @kwonye. I took a quick look through logging in on dotcom with and without magic links. The only issue I noticed is that the screen that currently reads "Check your email" could be updated to match the language used on the iOS version of magic links. A button to sign in by password would be helpful on that screen, too, in case the user has trouble getting the magic link email.

I imagine the "Open Mail" button may not work on Android, but if we can include it it'd be nice to.

Here's the iOS mockup for reference:

![screen 3](https://cloud.githubusercontent.com/assets/1396552/14499456/58bd1d36-016c-11e6-883c-ff74791514bf.png)

**Comment by kwonye** [comment]
Also refer to wordpress-mobile/WordPress-iOS#5126 for consistency

**Comment by kwonye** [comment]
> A button to sign in by password would be helpful on that screen, too, in case the user has trouble getting the magic link email

Done and done. Thanks @mattmiklic!

> I imagine the "Open Mail" button may not work on Android, but if we can include it it'd be nice to.
Unfortunately there isn't an elegant way to do this. Opted to leave out, at least for V1

**Comment by maxme** [comment]
> Unfortunately there isn't an elegant way to do this.

I think if you broadcast a view intent with the correct type it will open the default email app for reading. If this not possible, the non elegant way is to list major email apps and broadcast an open intent directly.

**Comment by kwonye** [comment]
> I think if you broadcast a view intent with the correct type it will open the default email app for reading

Thanks @maxme! I was only able to find solutions for opening for composing messages, but another search resulted in me finding `Intent.addCategory(Intent.CATEGORY_APP_EMAIL)`

It requires API 15, but that should be fine by the time this feature ships.

cc @mattmiklic

**Comment by mattmiklic** [comment]
Nice; the "open mail" button opened Gmail like a charm. :+1:
