### ISSUE TITLE
Reader: Tag/Topic picker can vanish when signing out of wpcom

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3990]
To reproduce:
- Sign in to a self-hosted wpcom account. 
- Sign in to wpcom. 
- Switch to the reader tab.
- In the tag picker, select a tag you are following that is not one of the default/recommended tags shown to a signed out user. 
- Switch to the profile tab and sign out of wpcom. 
- Switch back to the reader. 

Notice the tag picker has vanished.

<img width="285" alt="screen shot 2016-04-19 at 4 25 14 pm" src="https://cloud.githubusercontent.com/assets/1435271/14656120/59973168-064b-11e6-9a70-9eaecd6f0c80.png">

**Comment by nbradbury** [comment]
Note: wait for #3984 to be merged before tackling this.
