### ISSUE TITLE
Reader: Empty list after previewing tag.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4000]
This is a bit of an edge case I think. Here are the steps I took:

Choose the `business-technology` tag. 
Find a post titled "The fallacy of overnight success" https://wordpress.com/read/blogs/72626863/posts/30269  The tag displayed on the post card is `the-fallacy-of-overnight-success`
Tap to preview the tag. 
The preview list appears but is empty.  

I guess we're excluding the previewed post in the Android app?  Makes sense, but an empty list is a bit odd.  Fwiw, on the web we show the post and iOS app we show the post. 

<img width="278" alt="screen shot 2016-04-22 at 9 43 52 am" src="https://cloud.githubusercontent.com/assets/1435271/14745796/8af019cc-0872-11e6-80cb-a5f005eacfd8.png">

**Comment by nbradbury** [comment]
I see the problem and it's an annoying one. What's happening is that the `ReaderPostService` is requesting posts with that tag, and there's only one of them. That post already exists locally, so when the service does [this check](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/services/ReaderPostService.java#L292) it determines there are no unchanged posts which in turn causes the list not to update to show that post.

**Comment by nbradbury** [comment]
This was resolved by the changes made in #4633
