### ISSUE TITLE
Themes are never automatically refreshed

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4002]
@tonyr59h noticed that Themes are never automatically refreshed in the Theme browser.

Add a timestamp preference of when the latest request for themes was, and automatically refresh if older than a week(?) when entering the Theme browser.

**Comment by kwonye** [comment]
Not a high enough priority to get in by 5.6. Also, this can be batched with the rest of the Themes updates that are necessary soon. Moving to milestone 5.7 for now.

**Comment by tonyr59h** [comment]
Closed via #6697 (specifically e0fd967bccdd41961a1dba8e754eac37586e213e).
