### ISSUE TITLE
Themes option not available under My Sites tab after signing in

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#4003]
### Expected behavior
The `Themes` option should be available when visiting the My Site tab after signing into an account with admin privileges.

### Actual behavior
The `Themes` option is unavailable until the app is restarted.

### Steps to reproduce the behavior
* Sign out
* Sign in with an account that has admin privileges
* Go to the My Site tab

The `Themes` option is not visible. Likely due to admin privileges not being verified before creating the My Site tab. See [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3902) for similar issue with the `Settings` option.

##### Tested on Genymotion emulator, Android API 17

**Comment by hoverduck** [comment]
FWIW, I've also seen this bug, but (assuming it's the same one) I was able to get the Themes option to appear by switching to a different site and back.
