### ISSUE TITLE
Language dialog is not pre-selected

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4009]
When you go into App Settings and your language is set to a language like `en_US`, `en_CA`, `es_CL` etc, when you open the language picker it should be pre-selected to your current language. However, for these custom cases it's not. We have changed the `available_languages.xml` array before to fix this issue, but that file is auto-generated, so it came back.

To fix it, we need to update the script that generates this file, so it doesn't happen again.

**Comment by maxme** [comment]
Fixed by #4010
