### ISSUE TITLE
Pin lock screen should not open new keyboard

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#4019]
When I open the app when the pin lock is enabled, I can open a new keyboard by clicking in the text box:

![keyboard-opens](https://cloud.githubusercontent.com/assets/11487924/14817908/1f470a6e-0b88-11e6-8569-3a22928e1166.png)

### Expected behavior

I expected that the keyboard would not open when clicking the textbox, since the numberpad is already displayed:

![keyboard-should-remain-closed](https://cloud.githubusercontent.com/assets/11487924/14817953/544f24a8-0b88-11e6-9e6c-9148afe4355b.png)

##### Tested on the Nexus 6, Android 6.0.1

**Comment by daniloercoli** [comment]
This is going to be tracked here https://github.com/wordpress-mobile/PasscodeLock-Android/issues/30
