### ISSUE TITLE
There should be an error message displayed when entering incorrect pin

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#4022]
### Expected behavior
On the 'When I enter the wrong pin multiple times, I should see an error telling me what's going wrong.

### Actual behavior
When I enter the wrong pin, I don't see an error. Instead, the pin textbox is cleared out and nothing else changes. On the opening screen, the app also 'shakes'

### Steps to reproduce the behavior
There are three places this can happen.

Place 1: 'Change PIN'
1. If you don't already have a pin code, go to User > App > Turn PIN lock on, and enter a pin.
2. Go to User > App > App Settings and click on 'Change PIN'
3. See a screen to enter your old pin. Enter an incorrect pin.
4. See that the incorrect pin is not accepted, the pin textbox is cleared, but there is no error message displayed. 

Place 2: 'Turn PIN lock off'
1. If you don't already have a pin code, go to User > App > Turn PIN lock on, and enter a pin.
2. Go to User > App > App Settings and click on 'Turn PIN lock off'
3. See a screen to enter your old pin. Enter an incorrect pin.
4. See that the incorrect pin is not accepted, the pin textbox is cleared, but there is no error message displayed. 

Place 3: The initial screen
1. If you don't already have a pin code, go to User > App > Turn PIN lock on, and enter a pin. Then close the app and swipe it off your recents screen.
2. Open the WordPress app and see the 'Enter your PIN' screen
3. Enter the wrong pin
4. See the pin textbox is cleared, and the screen shakes. No error message is displayed.
5. Enter the wrong pin again
6. See the pin textbox is cleared, and the screen shakes. No error message is displayed.

##### Tested on [device], Android [version]

**Comment by theck13** [comment]
When I enter an incorrect pin, the view shakes and a "Wrong PIN" message is shown at the top of the screen.  See the attached animation for example.

![pin](https://cloud.githubusercontent.com/assets/3827611/15417592/ecaa7dee-1e14-11e6-8d88-398ef924d4d3.gif)

If you aren't see this behavior, please let me know the following:
- WordPress app version
- Android version
- Device

**Comment by rachelmcr** [comment]
I tested this on my Nexus 9, Android 6.0.1, WPAndroid 5.4-rc-2, using the three scenarios from the original report. In each case, the "Wrong PIN" message appeared as expected at the top of the screen.

However, in the first two scenarios ("Change PIN" and "Turn PIN lock off") the screen didn't shake; only the "Wrong PIN" message appeared. I only got the screen shake in the last scenario, when I was unlocking the app.

**Comment by theck13** [comment]
I was able to reproduce that behavior, @rachelmcr.  It looks like the absence of shaking for "Change PIN" and "Turn PIN lock off" was just an oversight.  I created an issue (wordpress-mobile/PasscodeLock-Android#32) on the passcode repository.
