### ISSUE TITLE
Notifications: Add more detail to Android notification

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4031]
When a new comment comes in, I get a notification saying "User X commented on your post Y".  I'd love to be able to expand the notification and also see:

1) The body of the comment
2) The options to at least Like/Approve the comment in addition to replying.  Adding Trash and Spam might crowd things too much, but maybe not.
3) Which site the comment was on (not critical, but sometimes I forget where I published a given post, and it would be a nice reminder)

Numbers 1 and 2 will go a long way towards making WordPress notifications more usable on Android Wear as well.  Right now the only option is to Reply, which opens up the notification on the phone.  I'm going to write a separate issue requesting the Reply option be expanded to allow speech-to-text.

**Comment by mzorz** [comment]
> 1) The body of the comment

this needs a server-side modification, in progress

> 2) The options to at least Like/Approve the comment in addition to replying. Adding Trash and Spam might crowd things too much, but maybe not.

this is pure Android, adding that in this PR

> 3) Which site the comment was on (not critical, but sometimes I forget where I published a given post, and it would be a nice reminder)

server side modification too, in progress

I'm making modifications for the notification **subject** (which is what is shown in push notifications) to read as follows: "<Author> commented on <post name> of blog <blog name>: <comment content, **up to 90 chars**>"

For example:
"mzorz commented on A nice Friday at work of blog lifenuances: I liked your post a lot!".

@hoverduck can you confirm this is what you were expecting? thanks in advance 👍

**Comment by hoverduck** [comment]
@mzorz: Yep, sounds great!

**Comment by mzorz** [comment]
Opening a new issue just for the Android part here #4523

**Comment by mzorz** [comment]
Following discussions, ended up with this format (waiting for code review server side): "_Author_ commented on _post_name_: _comment-content-up-to-90-chars_"

**Comment by mzorz** [comment]
This is fixed server-side now @hoverduck ! yay 👍 :) closing this issue, the relevant Android part still pending review here #4523
