### ISSUE TITLE
Update Passcode Lock library to version 1.2

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#4041]
We need to update  PasscodeLock-Android library to new version (1.2.0 -  that we still need to publish on Maven central though).

It does contain an "important" security fix, and a bug that affects the keyboard on the unlock screen. The latter fix is currently under review. 

@tonyr59h I think we should update the library asap, and include it in v5.4 of wp-android.

**Comment by tonyr59h** [comment]
> I think we should update the library asap, and include it in v5.4 of wp-android.

I agree we should release it ASAP, but there's only two weeks left before the expected release.

cc @maxme, Thoughts?

**Comment by maxme** [comment]
@tonyr59h ok, I'll publish the artifact and merge it in `release/5.4` and then update the alpha and beta channels.

**Comment by maxme** [comment]
Apparently there are 2 PRs waiting before we can publish v1.2
