### ISSUE TITLE
Use roles from the network request

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4050]
For updating the users in people management, we should use the `/v1.1/sites/$site/roles` to get a possible list of roles instead of using an array resource to be able to support Jetpack sites.

**Comment by maxme** [comment]
@oguzkocer should we move this one to the FluxC repo? (and implement it in the Site Store?)

**Comment by oguzkocer** [comment]
We should @maxme, I just added [an issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/260) for it.

**Comment by oguzkocer** [comment]
Re-opening this issue since we need to make a lot of changes in the main repo to support it.
