### ISSUE TITLE
Bump min sdk to API 16 when the visual editor lands in release

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4052]
tagged 5.4 keep this tag if everything goes well with the 5.4 beta.

**Comment by nbradbury** [comment]
Note: as part of this, we should be sure to remove all our checks for `Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN` .

**Comment by maxme** [comment]
> Note: as part of this, we should be sure to remove all our checks for Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN .

I think it's better to keep some of them in certain places, I think about some generic utility functions for example.
