### ISSUE TITLE
My Sites: Have Header Tap Load Site

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#4055]
We could a) Save a row in my sites and b) match up closer to the web if we remove the 'View Site' row in my sites, and instead make the header clickable so that it loads the site in the in-app browser.

Would this be discoverable though? It might help to add an icon to the header to indicate what will happen if you tap on it.

Video concept: https://cloudup.com/cYmQ9AwbLKQ

**Comment by maxme** [comment]
I agree that we could have the site heard tappable but not sure about dropping the "View Site" button (I fear users won't understand we "moved" that feature). cc @mattmiklic

**Comment by mattmiklic** [comment]
It is a little trickier in the apps, where we don't have the hint of a highlight state that we do when using Calypso with a mouse. I wonder if moving View Site up to the top of the list, under Stats, to match iOS, might be a clearer way to make this option more visible.

We could try making the site title tappable in addition to keeping the existing link, though I'd recommend adding some tracking to these links to see if anyone actually finds it, before we removed the explicit "view site" link.

**Comment by maxme** [comment]
1. Make the site header tappable.
2. Keep "the view" site button.
3. Add different analytics events to both so we can compare (and eventually remove the view site button if usage is low).
