### ISSUE TITLE
Reader: Instagram embeds are empty

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4058]
If a post contains an Instagram embed, the embed frame and caption appear correctly in reader detail but the embedded image is blank.

![device-2016-05-04-170543](https://cloud.githubusercontent.com/assets/3903757/15029183/80c879f6-121a-11e6-899c-fc1ab1ecab7a.png)

**Comment by maxme** [comment]
Might be related to https://github.com/wordpress-mobile/WordPress-Android/issues/683 (oembed in webviews).

**Comment by maxme** [comment]
Example post: https://taliwutblog.wordpress.com/2017/04/04/instagram-embed/

**Comment by maxme** [comment]
The response from the REST endpoint (`https://public-api.wordpress.com/rest/v1.3/read/feed/14169949/posts/1405123639`) doesn't contain the `background-image` in the `style` element. Here is a full sample of the content returned by the end point:

```html
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:500px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
    <div style="padding:8px;">
        <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;">
            <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div>
        </div>
        <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/bNd86MSFv6/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Points of view. #hancock</a></p>
        <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A post shared by Alberto Tretti (@alberto.t) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2013-07-01T04:46:31+00:00">Jun 30, 2013 at 9:46pm PDT</time></p>
    </div>
</blockquote>
```

**Comment by maxme** [comment]
I guess this works on Calypso because some [js script](https://platform.instagram.com/en_US/embeds.js) is executed and replace this with the actual embed.

**Comment by maxme** [comment]
Apparently in Calypso, they have a list of embed to look for [here](https://github.com/Automattic/wp-calypso/blob/58f89ed6fe28b7fc97841b95eb587b4e6a1bb6f3/client/components/embed-container/index.jsx) and depending of what they find in the dom, they load some whitelisted js scripts that will process the embed.

**Comment by maxme** [comment]
I confirm that injecting `<script src="https://platform.instagram.com/en_US/embeds.js" type="text/javascript"></script>` in the Reader Webview fix the issue:

![screenshot-2017-04-05_11 55 12 556](https://cloud.githubusercontent.com/assets/40213/24700299/0779436a-19f7-11e7-9437-8378c9de8590.png)


We could eventually have a similar approach as the one used in Calypso (parse+whitelist+inject), but I wonder why the original embed code looks like stripped from the `background-image` part.
