### ISSUE TITLE
Visual editor: Removed bold/italic formatting re-applies after removal in 5.4-RC-1

### ISSUE THREAD

**Issue by nicoleckohler** [wordpress-mobile/WordPress-Android#4067]
### Expected behavior

1. Select bold or italic in visual editor
2. Type word(s) in formatted text
3. Select bold/italic again to clear selection
4. Press space key and type next word in non-formatted text

### Actual behavior

Pressing space re-applies the bold or italic formatting to the next word. The user must then manually re-clear the formatting a second time before they can begin typing.

**Screenshots:**

https://cldup.com/0P4QYC7Bhb.png (showing I've finished typing a word in bold and have cleared the formatting in the visual editor)
https://cldup.com/SPLxOlwyRE.png (I pressed space - note that the bold formatting re-applied)
https://cldup.com/aQb92uhMtY.png (on the next line I was able to reproduce with italics)

### Steps to reproduce the behavior

1. Apply bold or italic text in visual editor
2. Proceed to type a word
3. Un-apply formatting
4. Press space
5. Type another word, formatting will have been re-applied despite manual clear by user

##### Tested on...

This was tested in 5.4-RC-1 on my Nexus 5X (running Android Marshmallow 6.0.1, unrooted, up to April 2 security patch).

**Comment by aforcier** [comment]
Thanks for the report! The visual editor has its own repository and we have an existing issue for this over there: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/123.

Closing this one as a duplicate.

**Comment by nicoleckohler** [comment]
Aha, thanks @aforcier 👍
