### ISSUE TITLE
Add new property showing "where" a user is attempting sign in to Helpshift/logs

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4069]
Per @rachelmcr 

> Sometimes it can take a little back and forth before we realize that a user is having trouble on the Jetpack login screen, rather than the WordPress.com/self-hosted login screens. If we could quickly/easily distinguish between them, it could help speed up the support process.

**Comment by kwonye** [comment]
Won't be able to get to this by 5.6. Moving milestone to 5.7

**Comment by daniloercoli** [comment]
Closing this issue since we're tracking it here https://github.com/wordpress-mobile/WordPress-Android/issues/4912 with major details.
