### ISSUE TITLE
Don't call Smart Lock API again if the Activity is restarted and data filled

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4073]
Keep the state across signin activity instances, copy `mIsResolving` behavior from this sample https://github.com/googlesamples/android-credentials/blob/master/credentials-quickstart/app/src/main/java/com/google/example/credentialsbasic/MainActivity.java#L64

**Comment by kwonye** [comment]
@maxme I believe this is resolved in #4234

**Comment by catehstn** [comment]
Can this be closed @kwonye ?

**Comment by hypest** [comment]
Closing as no longer valid with the new Login flows.
