### ISSUE TITLE
Reader: Some Discover posts do not have a comment/like displayed

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4079]
### Expected behavior

Seeing a Discover post in the Android and Web Reader should result in the same experience
### Actual behavior

Some Discover posts in Android do not have the comment/sharing links that they do on the web version
### Steps to reproduce the behavior
1. Go to the Discover feed in Android and Web.
2. Scroll down until you see a discrepancy between whether or not a post has the comments/likes enabled. 
### Screenshots

Web: 
<img width="1279" alt="screen shot 2016-05-09 at 1 38 05 pm" src="https://cloud.githubusercontent.com/assets/1158819/15127468/b3e4bd52-15eb-11e6-861d-6e4f054cfd2d.png">

Android:
![screenshot_20160509-133814](https://cloud.githubusercontent.com/assets/1158819/15127491/c96b7c24-15eb-11e6-951d-29fcaf058235.png)

**Comment by nbradbury** [comment]
This is a limitation in both the Android and iOS readers right now. The problem is that liking/commenting is supposed to be done on the source post rather than the Discover post, and we don’t support that yet on mobile.

**Comment by maxme** [comment]
I noticed there is a like button on the DIscovery post detail. I'm not sure if it's a bug or not (does this like the discovery post or the post itself?).

![screenshot-2017-01-02_17 25 09 983](https://cloud.githubusercontent.com/assets/40213/21592770/7bfec820-d110-11e6-8c6b-54dd7a4ec2f8.png)
