### ISSUE TITLE
Reader: Comment/Like count out-of-sync for older posts

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4080]
### Expected behavior

All posts reflect the correct amount of comments/likes in the Reader list
### Actual behavior

Old (posts not fetched since last fetch) do not reflect the correct amount of comments/likes. Tapping the Post and going into the Post details view shows the correct amount of comments/likes. Backing out to the Reader again still continues to show the old comment/like count.
### Steps to reproduce the behavior
1. In the Reader, go to a feed that has cached posts
2. Update feed (pull down to refresh)
3. Find a post that was previously cached and see if there is a miscount.

**Comment by lancewillett** [comment]
I saw a similar bug with Reader and a Jetpack site (Android app version alpha-29, Nexus 6P, Android 7.0).

Steps I took:
1. Followed http://angryweasel.com/blog/ in Reader.
2. Clicked into a post to read it.
3. Clicked Like from the bottom "action bar" that hovers up when you scroll.
4. The like count in that bottom bar said "1 Like" whereas in the post view itself (just above) I could see two other people had liked it already. Viewing <a href="http://angryweasel.com/blog/test-bash-smash/">the post</a> in a desktop browser confirmed 3 likes.
5. Re-open the app, navigate to the post again in Reader, now my avatar shows up in the likes area of the post but the Android app "Like" count is still 1.

<img src="https://cloud.githubusercontent.com/assets/66797/20503861/d3dfb26e-b001-11e6-9e02-d3eae77bc10f.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/20503871/e078b8d6-b001-11e6-8c35-c74ae39a8b1a.png" width="480" />

**Comment by designsimply** [comment]
Bumped into this while testing with alpha-40.

Steps to reproduce:

1. Go to the Followed Sites stream in the Reader.
1. Scroll until you find a post with likes.
1. Tap on the post and scroll to the bottom.
1. Check to see whether the number of likes listed next to the star icon matches the number of likes shown on the post.

<strong>Result:</strong> very often, there are more likes on the post than are showing next to the star icon in the app.

<img alt="screenshot_20170323-143534" src="https://cloud.githubusercontent.com/assets/1119271/24272344/89c37b52-0fe2-11e7-9bae-12ddc0cd911a.png" width="270" />
<sup>Screenshot is showing this post: https://whenihavetime.com/2017/03/21/minimalism-stuff-letting-go-and-joy/</sup>

Tested on Pixel, Android 7.1.1, WPAndroid alpha-40.
