### ISSUE TITLE
[Reader] Can't follow the site WordPress.com

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#4087]
The `Sites you may like` section of the Reader shows `WordPress.com` in it, but when I tap on it I get an "Unable to retrieve posts" error message. There is an underlying Auth error.

I think it's an issue on the API side, but wanted to mention it here. If WordPress.com cannot be followed in the Reader, we should remove it from the suggestions list.
![reader-follow](https://cloud.githubusercontent.com/assets/518232/15212242/f2bf9974-183f-11e6-962c-e74aa9300b09.gif)

**Comment by nbradbury** [comment]
I'm not able to reproduce this. When I click any of my "Sites you may like," it correctly displays a list of posts. I couldn't tell from your GIF whether this is happening with one blog or all of them - if it's just one (or a few), could you let me know which one(s)?

**Comment by rachelmcr** [comment]
This issue was also raised recently on the WordPress.com side from a web user (see p2UL9c-2Gr-p2) and WordPress.com should no longer be a recommended site as of r136255-wpcom.

@daniloercoli can you confirm that you no longer see it in the suggestions list in the app?

**Comment by daniloercoli** [comment]
WordPress.com is no longer in the list of recommended sites.  Closing this issue since it's fixed server side. Thanks @rachelmcr!
