### ISSUE TITLE
Replace NoticonTextView by Vector Drawables

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4097]
When https://github.com/wordpress-mobile/WordPress-Android/pull/3856 is merged, we can remove `NoticonTextView` (it was a trick to use a special font for rendering vector icons) and replace them with image views (and equivalent vector drawables).

**Comment by maxme** [comment]
@theck13 is your [Vectorize all the things](https://github.com/wordpress-mobile/WordPress-Android/pull/4807) PR fixing this one?

**Comment by theck13** [comment]
The [vectorize-all-the-things](https://github.com/wordpress-mobile/WordPress-Android/pull/4807) pull request does not address Noticons.  I created https://github.com/wordpress-mobile/WordPress-Android/issues/4921 and https://github.com/wordpress-mobile/WordPress-Android/issues/4925 for fixing Noticon references.

**Comment by maxme** [comment]
Perfect, thanks!
