### ISSUE TITLE
Update Theme Browser to match the latest Web iteration

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4103]
The Theme Browser is behind the Web version.
- [x] Update url from `wp-admin/customize.php` to `wordpress.com/customize`
- [ ] Possibly remove "Try and Customize" in the overflow menu

**Comment by kwonye** [comment]
This isn't high enough priority for us to get in by 5.6. Moving to 5.7.

**Comment by rachelmcr** [comment]
The web version also recently launched new theme details pages:

o Update theme Details URL from `wordpress.com/themes/THEME_SLUG` to `wordpress.com/theme/THEME_SLUG`
o Update theme Support URL from `wordpress.com/themes/THEME_SLUG/support` to `wordpress.com/theme/THEME_SLUG/support`

**Comment by tonyr59h** [comment]
Note: Updating these URL's might fix #6646.

**Comment by tonyr59h** [comment]
Changes made on [this branch](https://github.com/wordpress-mobile/WordPress-Android/tree/issue/4103-update-themes-urls). It's working smoothly, always ending up at Calypso is nice!

Note: #6697 must be merged before this branch.
