### ISSUE TITLE
Optimize Optimizely start up

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4106]
Right now Optimizely is hanging the app start up time significantly. We can mitigate this by being a bit smarter about how we initialize Optimizely.

Because Optimizely is being used for the new log in screen, we can start Optimizely without blocking the rest of the start up for users that are already signed in. For new users, we'll have to still block as we need to have them see the login screen.

**Comment by maxme** [comment]
fixed via #4107
