### ISSUE TITLE
Use a `sortOrder` attribute in ReaderPost model instead of overriding the timestamp

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4119]
### Expected behavior
ReaderPost model should have a new attribute that represents the sort order weight for a ReaderPost instance, and all other classes using it should reflect this accordingly

### Actual behavior
Right now `timestamp`, being used as a sorting criteria, even when sometimes a value other than an actual timestamp is assigned to such `timestamp` attribute, which is misleading.

### Steps to reproduce the behavior
Check conversation here https://github.com/wordpress-mobile/WordPress-Android/pull/4096/files/0cc5bd209d8ebf0deeff93d716ca194d2eb0df4f#r64293763

**Comment by nbradbury** [comment]
Note: #4096 should be merged before tackling this.

**Comment by nbradbury** [comment]
Closed via #4160
