### ISSUE TITLE
Reader: isSamePost() doesn't account for changes to a post's text or title

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4177]
The reader uses [isSamePost()](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java#L541) to determine whether two posts are the same, and we rely on this to detect changes between a local post and the same post on the server. 

However, this comparison doesn't account for changes to a post's text or title, so those changes aren't reflected in the app.

Discovered while testing #4170.

**Comment by khaykov** [comment]
If we are going this way, do you think it will make sense to also include all the fields that are used in reader list - excerpt, words count, featured image? This way we would be able to reflect all the changes made to posts.

**Comment by nbradbury** [comment]
@khaykov I was hoping to keep that routine from comparing everything since it's called so often, but since we need to do the expensive text & title comparison it probably makes sense to include other fields in the comparison.
