### ISSUE TITLE
Login: Self-hosted login form not falling back to http

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4196]
### Expected behavior

When you try to log in to a site that doesn't support https, the app should fall back to http when it looks for the site's XMLRPC endpoint.

### Actual behavior

The app only looks for the site's XMLRPC endpoint over https and returns an error if the site doesn't support http.

In my testing, the app displayed an "Invalid SSL certificate" error:

![2016-06-08 14 00 03](https://cloud.githubusercontent.com/assets/8658164/15897018/9b006b90-2d8a-11e6-9790-08dfa8684c63.png)

A user also reported this issue, and the app logs showed that the app only checked the https URLs. It then displayed the error "Check that the site URL entered is valid." (107830-h)

#### Reproduce the error:

1. Open the app and go to log in to a self-hosted site (either on the self-hosted login screen or by adding a new self-hosted site to the app)
2. Enter your username, password, and self-hosted site's domain (e.g. yourgroovydomain.com) for a site that doesn't support https
3. Try to sign in

Result: You receive an invalid site URL or SSL error

#### Log in successfully:

1. Open the app and go to log in to a self-hosted site (either on the self-hosted login screen or by adding a new self-hosted site to the app)
2. Enter the same username, password, and self-hosted site URL beginning with http:// (e.g. http://yourgroovydomain.com) for a site that doesn't support https
3. Try to sign in

Result: You are logged in successfully

##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-13

Reported by users with WPAndroid 5.4.

**Comment by hypest** [comment]
Possibly relates to: #4194 , #4195
