### ISSUE TITLE
Post/Page Options: Allow users to change the post/page author

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4230]
It would be nice to be able to change the author of a post or page from the post/page settings, on multi-author sites.

Requested by a user in a recent app review.

Related iOS issue: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/632

**Comment by rachelmcr** [comment]
This came up again recently in support: 168113-h

**Comment by SiobhyB** [comment]
This was requested in a three star app review:

> Also please add the ability to change the author of the article/post. Right now there is no possibility to manage it.

**Comment by SiobhyB** [comment]
From a two star app review:

> Good app. Limited. Very limited. Can't change author.

**Comment by thehenrybyrd** [comment]
From a three star app review:
> please add author option in post option

**Comment by designsimply** [comment]
> C’è la possibilità di poter cambiare l’autore ad un articolo Utilizzando l’app?

Translated with Google:

> Is it possible to change the author to an article using the app?

<sup>(internal reference: 2255172-zen)</sup>

**Comment by SiobhyB** [comment]
Another request in 2721198-zen, from a user who has multiple authors on their site and would like the ability to assign posts to them.

**Comment by SiobhyB** [comment]
Another request in 2737674-zen, from a user who would like to assign posts to contributors directly from the app.

**Comment by designsimply** [comment]
> I enjoy the app and it makes the access to my website way easier. But I have a huge problem, I'm not able to change the authors of posts in the app. For that, I have to log on a browser. It would be great if you add the option to change authors of posts right on the app.
> 
> <sup>5-star app review by Ovi Lone Aug 8, 2020 at 7:55 AM - WPandroid 15.4-rc-1 Redmi 6A Android 8.1</sup>

<sup>(internal reference: play-store-feedbackid=gp:AOqpTOGkEs-OK-6Ed-WO5k_HtJQnpF9uO5MSuDtDCVPAaXb0FI24R3HfRBL9GFjSCU-2Nr-kPZdiEQ6g46LOgmC_)</sup>

**Comment by designsimply** [comment]
> Another major problem is there we couldn't change the author in the app.

* 2-star beta tester feedback
* Oct 27, 2020, 06:39
* Device: LGE LG G7 ThinQ
* Device language: English
* App version code: 939
* App version name: 16.0-rc-2
* Android version (SDK): Android 10 (SDK 29)

<sup>(internal reference: play-store-reviewId=gp%3AAOqpTOGxPytP9Xd-OvKfM-hn5mtQsQmTYXVx9GJjKOoDScX0q-KYXQTJvyJ0t8loRo6ydmeQYe6e8Idp3_GGDGji&corpus=BETA_FEEDBACK)</sup>

**Comment by reginabally** [comment]
From [an app review:](https://play.google.com/console/u/0/developers/7957760354032996428/app/4973361825681449040/user-feedback/review-details?reviewId=gp%3AAOqpTOF9ZbeipITxjgwITyt2WnIMfcNW-Jm3loAWjYU5UZ754w8ZLccxV3aaExSDCfDdFkEPbnasISqxn2aYLQ&corpus=PUBLIC_REVIEWS)

> I'd like to suggest adding the feature that allows the admin edit the author of a post from the app.

**Comment by develric** [comment]
Another related app store review request:

>Please give the possibility to choose the author of the text from the application.

(Internal reference: reviewId=919bdf91-a910-42d7-9edf-82b974b92250&corpus=PUBLIC_REVIEWS)

**Comment by azollafox** [comment]
Android version is not showing the "Author" field in "Publish" section of "Post setting" area. As it is available in iOS version. Please fix it ASAP. It will reduce the usage of app and overall rating.

(internal reference : reviewId=669bd9fe-bb18-499d-b9b9-7b709671bbdd&corpus=PUBLIC_REVIEWS )
