### ISSUE TITLE
Check Locale.getDefault() usage

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4235]
Check the conversation [here for context](https://github.com/wordpress-mobile/WordPress-Android/pull/4234#issuecomment-226190098)

1) We need to check all the places where `Locale.getDefault()` is used and make sure we use `RestClientUtils.patchDeviceLanguageCode()` instead, wherever needed.

2) Also, for a more grained control I'd suggest refactoring  `RestClientUtils.getRestLocaleParams()` to make use of the _currently configured locale_, provided by `context.getResources().getConfiguration().locale.toString()`  rather than `Locale.getDefault()` which is only updated upon application launch. Suggestion: use a new class `LanguageUtils` with methods `getDeviceLanguage` and `patchDeviceLanguage`

**Comment by maxme** [comment]
> Suggestion: use a new class LanguageUtils with methods getDeviceLanguage and patchDeviceLanguage

+1
