### ISSUE TITLE
Upload and link to full image setting toggle not working

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-Android#4241]
Under a sites settings (My Sites > Choose Site > Settings) there is a toggle to Upload and link to full image. The wording of this is a bit confusing and I'm not entirely sure what it is meant to do.
### Expected behavior

My expected behavior is if the toggle is turned off when I upload an image to a blog post it would not link the image to the full image.
### Actual behavior

Whether this is turned on or off (in the legacy editor or the visual editor) when I upload an image to a post it includes a link to the full image.
### Steps to reproduce the behavior
- Visit My Sites and choose a site
- Click Settings
- Turn off Upload and link to full image
- Start a blog post and add an image
- In visual editor click image and choose to edit, it will include a link to the full image
- In legacy editor publish the post then come back to edit
- Shows code linking to the full image

**Comment by daniloercoli** [comment]
> Under a sites settings (My Sites > Choose Site > Settings) there is a toggle to Upload and link to full image. The wording of this is a bit confusing and I'm not entirely sure what it is meant to do.

The wording is probably a bit confusion, but it means that the app will upload the pictures at their original sizes. If that setting is OFF, the app will resize pictures (if necessary) accordingly to media size settings of the site. The resize will happen before uploading, and then you will save bandwidth when this setting is turned on.

**Comment by daniloercoli** [comment]
`Upload and link to full image` option was dismissed in 7.0. Uploading a new image to a post includes a link to the full image. 
We're no planning to add it back in settings. Instead a new setting for it should be available in the new visual editor.
