### ISSUE TITLE
When user taps for details on a comment notification we should scroll them down to their actual comment instead

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-Android#4244]
### Expected behavior
When a user opens up a comment notification and then taps on the detail button to load all the corresponding comments we should like the web scroll down to the corresponding comment.

### Actual behavior
Right now tapping on the detail button will load the comments but hang out at the top.

### Steps to reproduce the behavior
1. Open comment notification.
2. Tap on detail button at the top

Parallel WPiOS Issue - https://github.com/wordpress-mobile/WordPress-iOS/issues/5540

**Comment by nbradbury** [comment]
I couldn't figure out where this was supposed to happen so I tried the iOS app and realized it has an arrow which shows all comments when clicked:

![simulator screen shot jun 17 2016 7 23 49 am](https://cloud.githubusercontent.com/assets/3903757/16149151/a5534b48-345c-11e6-9b2b-ecdce8d9c9cd.png)

The Android app is missing this feature, so it needs to be added as part of this issue.

**Comment by nbradbury** [comment]
After talking with @drw158 and @roundhill about this, it was decided that the best approach is to make the comment text clickable, and clicking it opens the comment list.
