### ISSUE TITLE
Missing characters in Greek

### ISSUE THREAD

**Issue by markx2** [wordpress-mobile/WordPress-Android#4260]
### Expected behavior
Properly display all characters

### Actual behavior
Font of the Android app doesn't support utf-8 characters. 
I write in Greek and some characters appear with different style. You could use a font like open sans which supports all languages.

### Steps to reproduce the behavior
Use Greek?

##### Tested on [device], Android [version]
Not tested.

**Comment by maxme** [comment]
Could be related to https://github.com/wordpress-mobile/WordPress-Android/issues/3358

@markx2 which Android version are you using?

**Comment by rachelmcr** [comment]
This issue came from a user (111881-h) using Android 4.4.2 with WPAndroid 5.4.2.

**Comment by maxme** [comment]
Confirmed on 4.2.2
![screenshot-2016-06-22_15 10 57 229](https://cloud.githubusercontent.com/assets/40213/16267718/8c691fd0-388b-11e6-93a1-53dff6b7ca88.png)

dup #3358
