### ISSUE TITLE
EmailCheckerIntegrationTest uses old version of EmailChecker

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4270]
Our [EmailCheckerIntegrationTest](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/androidTest/java/org/wordpress/android/ui/accounts/EmailCheckerIntegrationTest.java) needs to be updated to use emailchecker2.

**Comment by maxme** [comment]
We can kill it, it was a NDK test.

**Comment by maxme** [comment]
We removed `EmailCheckerIntegrationTest` already.
