### ISSUE TITLE
Improve app lock settings

### ISSUE THREAD

**Issue by shawnajean** [wordpress-mobile/WordPress-Android#4272]
### Suggested behavior
Three settings options for the app to relock:
* Lock app at device screen off
* Lock app after screen of for... minutes
* Enter password once to unlock app

Came in through HS: 112091-h

**Comment by theck13** [comment]
@shawnajean, we use the [PasscodeLock-Android](https://github.com/wordpress-mobile/PasscodeLock-Android) library for the WordPress app.  We may want to track these suggestions in that repository.

**Comment by shawnajean** [comment]
Thanks @theck13 - just added a new issue over there: wordpress-mobile/PasscodeLock-Android#37

**Comment by rachelmcr** [comment]
Closing as this issue is being tracked in the PasscodeLock-Android repo.
