### ISSUE TITLE
Media Library Displays Incorrect Thumbnail in Grid

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#4281]
### Expected

Image thumbnails maintain correct preview of media (i.e. image/audio/video).
### Observed

When flinging to scroll, some image thumbnails show incorrect preview.  See [video](https://drive.google.com/open?id=0B9xgw-QfHHbeVHJGeFJyR1MzU3M) for details.  Focus on the Angry Birds image at the bottom of the grid in the video.
### Reproduced
1. Go to Sites.
2. Tap Media option.
3. Scroll to bottom of grid.
4. Notice Angry Birds image.
5. Fling to middle of grid.
6. Fling to bottom of grid.
7. Notice Angry Birds image.
8. Fling to middle of grid.
9. Fling to bottom of grid.
10. Notice Angry Birds image.
##### Tested

LG G4 (LG-H815) on Android 6.0.1 with WordPress 5.4.2
Samsung Galaxy S III (SGH-I747) on Android 4.4.4 with WordPress 5.4.2
Samsung Galaxy S IV (SGH-I337) on Android 5.0.1 with WordPress 5.4.2
Samsung Galaxy Tab 3 (SM-T310) on Android 4.4.2 with WordPress 5.4.2

**Comment by daniloercoli** [comment]
I was't able to replicate this issue on the wp-android 6.7. Tried on 3 devices, and different blogs/sites with no luck. 
Wondering if it's now fixed thanks to latest changes to NetworkImage class. Closing this for now.
