### ISSUE TITLE
Media Image Too Small for High-Density Screens

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#4282]
### Expected

Show full-width image when viewing item details from Media library.
### Observed

Some images are too small when displayed on high-density screens.  See screenshots for details.

![media_item](https://cloud.githubusercontent.com/assets/3827611/16328701/e6633106-3999-11e6-87df-2343cca36ed2.png)
### Reproduced
1. Go to Sites.
2. Tap Media option.
3. Tap image with 700 width by 100 height.
##### Tested

LG G4 (LG-H815) on Android 6.0.1 with WordPress 5.4.2
Samsung Galaxy S III (SGH-I747) on Android 4.4.4 with WordPress 5.4.2
Samsung Galaxy S IV (SGH-I337) on Android 5.0.1 with WordPress 5.4.2
Samsung Galaxy Tab 3 (SM-T310) on Android 4.4.2 with WordPress 5.4.2

**Comment by nbradbury** [comment]
Note: I'm wondering if we can ditch this screen entirely and simply show the image full screen with the relevant metadata superimposed. Seeing it full screen is probably more in line with what the user expects when they tap a media item (and if they want that, then right now they have to tap the photo again once this screen shows up).

**Comment by daniloercoli** [comment]
We can close this since we've a new media preview screen Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/5640
