### ISSUE TITLE
Widgets with slideout settings don't display correctly

### ISSUE THREAD

**Issue by shawnajean** [wordpress-mobile/WordPress-Android#4293]
### Expected behavior
Be able to edit the Follow Blog widget in the app.

### Actual behavior
The Follow Blog widget settings pop out to the side, not below. So I can't see the entire form and it makes it difficult to modify the widget.

### Steps to reproduce the behavior
In the app, W > Themes > Customize > Widgets. Search for the Follow Blog widget and add it.

<img src="https://cloud.githubusercontent.com/assets/775884/16351689/8f6e498e-3a35-11e6-8fb6-b09c9b12ab23.png" width="300px">

##### Tested on Nexus 6P, Android 6.0.1

**Comment by rachelmcr** [comment]
This is also an issue in Calypso web on mobile devices. I've opened an issue upstream for Calypso: https://github.com/Automattic/wp-calypso/issues/6593
