### ISSUE TITLE
Switch Sites search results open the wrong site on URL matches

### ISSUE THREAD

**Issue by chad1008** [wordpress-mobile/WordPress-Android#4328]
### Expected behavior

When searching in Switch Sites, the results show matches based on site title or URL - tapping the site you want should open that site's options

### Actual behavior

If the site _title_ matches your search string, the correct site opens. If the site _URL_ matches (but the title doesn't) the app will open the wrong site.

In that case, if the site you choose from the results is the third in the list, the app opens the third site in the main Switch Sites list, not from your search results

### Steps to reproduce the behavior

1. In an account with multiple sites, find or create a test site that has a different site title than its URL (Example: '_This Is A Testing Site_' as the title and '_reallyobscurebug.wordpress.com_' for the URL).
2. Open the app and tap Switch Sites.
3. Note the order of sites listed. Which ones are first, second, third, and so on.
4. Tap the magnifying glass to search and enter a string that matches your test site URL, but not its title. In the above example you would use the first few characters of '_reallyobscurebug.wordpress.com_'
5. When your test site appears in the list, notice how far down it is (is it the first, second, third, etc., result).
6. Tap the test site to try opening it.
7. Notice the site that actually opened - it will be the site from the corresponding position in the main Switch Sites list.

**Comment by chad1008** [comment]
After some additional testing, this is also happening on sites where my search string matches the title, so it may not be limited to just URL matches. I'm not sure what the exact pattern is just yet.

**Comment by rachelmcr** [comment]
Velda also reported this issue, and I can reproduce it on certain sites in my site picker, as well. I can select these sites from the site picker when I'm not searching, but when I search and tap on the site in the search results, it chooses the site that's in that position in the non-search site list instead (as described in the original issue).

In my testing:
- Certain sites _always_ open the correct site from the search, no matter what text I search
- Certain sites open the incorrect site if I search text that matches the site's URL, starting from the beginning of the URL (e.g. if the site address starts with `rachel` and I search `rach` the wrong site is opened when I tap on the result)
- Those same sites open the correct site if I search text that matches a different part of the site's URL, not starting from the beginning of the URL (e.g. if the site address starts with `rachel` and I search `chel` the correct site is opened when I tap on the result)

However, I can't figure out the difference between sites that always open the correct site when I search from them, compared to sites that sometimes open the wrong site.

Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-17
