### ISSUE TITLE
Warn the user to clear failed images (or edit the post) on publish from Post List

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4341]
Similar to https://github.com/wordpress-mobile/WordPress-Android/pull/3897 but we should show that (kind of) dialog with all publishing ways (from the Post List, from the Editor).

Not doing it could cause published post to contain broken media.

**Comment by daniloercoli** [comment]
I think this will be address in Async MVP. cc @aforcier Though? Can we close this ticket?

**Comment by aforcier** [comment]
@daniloercoli not completely - if a post contains failed media, the 'Publish' button is removed from the card in the list and an error appears. However, restarting the app will still show a 'Local draft' as before, and the user will be able to publish a post with broken media.

**Comment by mzorz** [comment]
A solution to this could benefit from having this one https://github.com/wordpress-mobile/WordPress-Android/issues/6352 implemented first, so we can just get the `PostModel` list from FluxC's DB and update the view with each post's latest status as necessary in one go.

I propose we wait for #6352 to take care of this one.

**Comment by mzorz** [comment]
Closed via #6789
