### ISSUE TITLE
Reader: Images with height attribute are displayed with incorrect ratio

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4344]
### Expected behavior

Images should be resized in the reader according to the image's original width/height ratio.

### Actual behavior

Images with a height attribute (e.g. `<img src="URL" height="1000" />`) are displayed with the wrong width/height ratio in the reader:

![2016-07-04 15 49 46](https://cloud.githubusercontent.com/assets/8658164/16565781/720a8bda-4207-11e6-9227-bb7e3f61d071.png)

### Steps to reproduce the behavior

1. Create a new post
2. Add an image to the post
3. Publish the post and view it in the reader. Result: The image ratio is incorrect (too tall)
4. Open the post in the editor
5. In HTML mode, copy the image tag (to display the image twice in the post) and remove the height attribute from the second image
6. Update the post and view it in the reader. Result: The image ratio is correct for the second image

(I tested by copying the image instead of directly changing it to make sure I was seeing the updated post in the reader.)

##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-16

**Comment by hypest** [comment]
Here's another post (from "Discover") that images are displayed with wrong aspect ratio: https://wordpress.com/read/blogs/79615376/posts/2940
