### ISSUE TITLE
Unable to build as a Gradle project in Android Studio.

### ISSUE THREAD

**Issue by PbPguna** [wordpress-mobile/WordPress-Android#4348]
### Expected behavior

 WordPress-Android project have to get compiled without any error.

### Actual behavior

Failed to sync gradle project Wordpress-Android-develop

Failed to open zip file

Gradle dependency cache may be corrupt this sometimes occurs after a network connection timeout

Re-download dependencies and synch project(Requires network)

### Steps to reproduce the behavior

Download the project from Github / Clone project and compile it in Android studio

##### Tested on [device], Android [version]

Samsung galaxy s4

**Comment by PbPguna** [comment]
Me too experiencing the same issue..

**Comment by maxme** [comment]
@PbPguna What do you mean by "Failed to open zip file" ?

**Comment by PbPguna** [comment]
@maxme It is a console printed error while importing the project into Android studio..

**Comment by maxme** [comment]
@PbPguna Try these steps:

1. Clone the project using your favorite git client
2. Open Android Studio
3. Click "Import Project"
4. Select the root `build.gradle` file (`WordPress-Android/build.gradle`), Android Studio should open import the project

**Comment by PbPguna** [comment]
Thank you maxme. but still the problem exist.

**Comment by maxme** [comment]
Project works great in Android Studio. I've just tried to import a fresh version and everything went fine. Have you followed the instructions in the [README](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/README.md)?

Can you explain step by step how you try to import the project? From the download step.

**Comment by PbPguna** [comment]
Hi maxme,
Yes, i just follow the same instruction in readme. but i got the error below

Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>

what i did is

android studio-> File ->new-> import Project ->WordPress-Android-develop->build.gradle
and pressed ok.

Please help me to find solution.

**Comment by maxme** [comment]
Can you try to build using the command line tool (like explained in the README)?

I found some similar issues in StackOverflow [here](http://stackoverflow.com/questions/27770909/android-studio-gradle-sync-error) and [there](http://stackoverflow.com/questions/35101206/android-studio-re-download-dependencies-and-sync-project). Try to delete your AS cache and your gradle cache (`~/.gradle`).

**Comment by PbPguna** [comment]
When i try to compile in Android studio Teminal in a windows machine. I am getting the below issue while executing the "cp ./WordPress/gradle.properties-example ./WordPress/gradle.properties" query.

Result got :
'cp' is not recognized as an internal or external command,
operable program or batch file.

**Comment by maxme** [comment]
> When i try to compile in Android studio Teminal in a windows machine. I am getting the below issue while executing the "cp ./WordPress/gradle.properties-example ./WordPress/gradle.properties" query.

This means you have to copy the file `./WordPress/gradle.properties-example` to `./WordPress/gradle.properties` you can do it with your file manager.

**Comment by PbPguna** [comment]
Yes i did but still the problem exist .PFA
![githubattach](https://cloud.githubusercontent.com/assets/20279529/16761593/6fdd9f72-483e-11e6-83a5-56040e93bc3f.png)

**Comment by maxme** [comment]
Have you tried deleting your AS cache and your gradle cache (~/.gradle)? 

Ref StackOverflow issues [here](http://stackoverflow.com/questions/27770909/android-studio-gradle-sync-error) and [there](http://stackoverflow.com/questions/35101206/android-studio-re-download-dependencies-and-sync-project).

**Comment by PbPguna** [comment]
@maxme I am working in a system with a firewall in which many domains blocked. Many dependencies wont get complied in the network. Is it a issue of not building of the project in android studio.
