### ISSUE TITLE
Reader: Timestamp should be next to Author's name

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#4353]
### Expected behavior
For timestamp to be next to Author's name just like in Calypso:
![screenshot 2016-07-05 13 00 42](https://cloud.githubusercontent.com/assets/4924246/16597967/7ee91908-42b0-11e6-831e-f7631ef5b736.png)

### Actual behavior
Timestamp is next to the site name/URL:
![screenshot 2016-07-05 13 01 16](https://cloud.githubusercontent.com/assets/4924246/16597989/920f8c42-42b0-11e6-8979-6f28c759eacf.png)

The timestamp refers to the time post was published so it shouldn't be next to the site's name/URL.

### Steps to reproduce the behavior
1. Tap on a post from Reader
2. Notice how timestamp on full-post view is next to the site name/URL

##### Tested on [device], Android [version]
Nexus 5 simulator, Android 6.0

/cc @nbradbury

**Comment by theck13** [comment]
@jancavan, are you suggesting keeping the timestamp in the Reader tab shown in the first screenshot and removing it in the Reader Post screen shown in the second screenshot?

![reader_tab](https://cloud.githubusercontent.com/assets/3827611/16621663/44d7c436-4354-11e6-9743-67f2e7b6ad91.png)

![reader_post](https://cloud.githubusercontent.com/assets/3827611/16621669/47dcf138-4354-11e6-9363-a98f2c1ee271.png)

**Comment by jancavan** [comment]
Closing this issue and created a new issue instead as there were several items I missed during my initial review.

New issue here: https://github.com/wordpress-mobile/WordPress-Android/issues/4404
