### ISSUE TITLE
Reader: Follow/Following icons are still using old version

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#4354]
### Expected behavior
For Follow/Following icons to be using the latest version:
![screenshot 2016-07-05 13 08 52](https://cloud.githubusercontent.com/assets/4924246/16598214/a72acee2-42b1-11e6-9843-78473dd0414e.png)

![screenshot 2016-07-05 13 08 54](https://cloud.githubusercontent.com/assets/4924246/16598216/a8a7605a-42b1-11e6-8fbe-85ebef0fb9c0.png)

**Here are the SVGs in case you need them:** 
https://cloudup.com/cqULXWspuwT

**Colors:**
Follow: `grey_dark` / `#2e4453`
Following: `alert_green` / `#4ab866`

### Actual behavior
Follow/Following icons are still using the old version:
![screenshot 2016-07-05 13 05 47](https://cloud.githubusercontent.com/assets/4924246/16598131/4e56e71a-42b1-11e6-83fe-ce9f854fc914.png)

![screenshot 2016-07-05 13 06 51](https://cloud.githubusercontent.com/assets/4924246/16598141/59fe0c42-42b1-11e6-8fe1-1b5dd8c12ad0.png)

### Steps to reproduce the behavior
Visit any site stream on Reader.

##### Tested on [device], Android [version]
Nexus 5 simulator, Android 6.0

/cc @nbradbury

**Comment by jancavan** [comment]
Discussion: https://github.com/wordpress-mobile/WordPress-Android/pull/4359#issuecomment-233482144

@theck13 I didn't change the size of the icons (they're still `24 x 24 px`, but I've moved them down so they won't have any bottom padding. I think we can keep them vertically aligned for now. Let me know if this works.

https://cloudup.com/cJMK1TXNzwV

**Comment by jancavan** [comment]
The main issue was there seems to have a lot of white space at the very top as shown in this screenshot:

![screenshot 2016-07-19 12 00 50](https://cloud.githubusercontent.com/assets/4924246/16968395/68b32052-4dc3-11e6-8626-8614f8b32067.png)

**Comment by theck13** [comment]
How does this look?

![follow_icons](https://cloud.githubusercontent.com/assets/3827611/17003825/5be695aa-4e97-11e6-89dc-f6cc2a234d8c.png)

**Comment by jancavan** [comment]
@theck13 Looks much better 👍
