### ISSUE TITLE
People: confusing 'Invite sent' toast message

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#4358]
### Expected behavior
When an error occurs and the invite is not sent, I expect the error toast message to say that the invite was _not_ sent.

### Actual behavior
Instead, the toast error messages says that the invite was sent in these two cases:
- the email blocked invite emails from wp.com
- the username already exists as a user on the site

In both of these cases, I got a toast that 'Invites sent but error(s) occured!'

However, invites were not in fact sent (and should not be sent)

### Steps to reproduce the behavior
1. Go to the People area for a site
2. Click the '+' sign
3. Type in an email or username that is a member of the site (do not move cursor away from textbox area)
4. Click 'Send'
5. See this:

![invite-sent-but-error-1](https://cloud.githubusercontent.com/assets/11487924/16625391/6200fc30-4372-11e6-90ee-7c1447fed1d4.png)

If you add a user that blocked invites, you'll see this instead:

![invite-sent-but-error-2](https://cloud.githubusercontent.com/assets/11487924/16625394/65d8d9b8-4372-11e6-8784-1899aab33747.png)

##### Tested on [device], Android [version]
alpha-16, nexus 6, android 6.0.1

**Comment by rachelmcr** [comment]
Related issue when the user already exists as a member on the site: #4351

**Comment by hypest** [comment]
Cannot replicate using the `alpha-16` tag from source code. @v18 can you very if this is still happening for you? I think this is not an issue anymore. Thanks!

**Comment by hypest** [comment]
I expect this issue to me fixed now that https://github.com/wordpress-mobile/WordPress-Android/pull/4553 is merged. I'll close this ticket and please, feel free to reopen if verified not fixed! Thanks!
