### ISSUE TITLE
Media: Media library does not load media for sites with basic HTTP auth

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4363]
### Expected behavior

I expect to be able to view media in the site's media library (My Site > Media or in the Editor > Add media > Select from media library).
### Actual behavior

If a site has basic HTTP auth, media in the media library doesn't load and a placeholder is displayed instead:

![2016-07-07 14 37 16](https://cloud.githubusercontent.com/assets/8658164/16657007/bbf404f8-4458-11e6-8e46-8598d7092902.png)

(Images added from the media library or uploaded to a new post also display as broken images in the editor.)
### Steps to reproduce the behavior
1. Add a self-hosted site with basic HTTP auth to the app
2. Visit the My Site tab > Media

Result: The media thumbnails don't load.
##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-16

Reported on Nexus 5, Android 6.0.1, WPAndroid 5.5 in 114458-h

**Comment by ChrissiePollock** [comment]
Another one - https://automattic.helpshift.com/admin/issue/124986/

**Comment by aforcier** [comment]
Still an issue with FluxC, but will be fixed once https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/353 is merged.

**Comment by aforcier** [comment]
Fixed in wordpress-mobile/WordPress-FluxC-Android#353.
