### ISSUE TITLE
Slide in/out animations don't look good on multi-window

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4377]
### Expected behavior
Fragment/Activity transitions should look good on multi-window tablets.

### Actual behavior
Under certain configurations (wpandroid being the left window in a multi-window setup), the slide in/out animation overlaps with the other window

### Steps to reproduce the behavior

* On an Android 6.0 tablet, in landscape, engage in multi-window mode and have the wpandroid app be the left of the two windows
* On the MySite screen, tap on "Comments" to enter the comments screen
* Notice how the screen animation overlaps with the window on the right side of the device screen

A video showing the issue: https://cldup.com/JXW_DFD0ML.mp4

##### Tested on [device], Android [version]
Samsung T810, Android 6.0.1

**Comment by hypest** [comment]
Let's think what the solution should be for this one. My first thought is to disable the custom (slide) animations and let the system use the default anims. These days, the default ones seem to be fade in/out and that doesn't mess with the neighbor window when in multi=win mode.

The current implementation was put in place with #2740. Lemme summon @rickybanister and @mattmiklic on this one. Also, @nbradbury you might also want to chip in as I'm sure you have plenty of insight from the initial implementation.

So, the question is: should we keep (and try to fix somehow) the slide in/out anims or replace them? Thanks!

**Comment by rickybanister** [comment]
Shouldn't it just crop itself to the bounds of the app frame?

**Comment by maxme** [comment]
Note: this might be a Samsung only bug. I can't repro this behavior on Android N (animation is correctly clipped to the app boundaries).

**Comment by nbradbury** [comment]
I'd be surprised if this was anything other than a Samsung bug. It seems to me that Android N would be smart enough to know to clip the animation to the app bounds (otherwise countless apps would run into similar problems).

But fwiw, I wouldn't mind at all if we dropped that transition and stuck with the default. Or barring that, took a closer look at how we're using transitions to give the user context and made sure we're being consistent.

**Comment by hypest** [comment]
I don't have another Android 6 tablet besides the Samsung T810 so I can't test it in another hardware.
Tried a 6.0 emulator and the slide anim is indeed clipped to the app window. Although, there seems to be an issue (again, on the emulator) when the split screen is not 50-50: the other window sees to do some weird flickering. Flickering doesn't happen if I restore the split to 50-50 or if I remove the slide and let the default (fade) anims kick in.

Having said that, even if we demote this into a device (or brand) specific issue, I'd argue that the slide-in doesn't make much sense when in multi-window mode... the "illusion" of the view entering the screen is not there as when on a phone, since now the view "enters from behind the other window" which hardly makes sense. Unless we attribute some special meaning to our use of sliding, I'd say let's drop it in favor of whatever is default on the user's device.

**Comment by theck13** [comment]
> I'd argue that the slide-in doesn't make much sense when in multi-window mode... the "illusion" of the view entering the screen is not there as when on a phone, since now the view "enters from behind the other window" which hardly makes sense.

I thought the same thing.

**Comment by nbradbury** [comment]
> I'd argue that the slide-in doesn't make much sense when in multi-window mode

I'm completely okay with killing the transition in multi-window (or killing it on all devices and using the default - except for the site picker, which should slide in).

**Comment by hypest** [comment]
> except for the site picker, which should slide in

Interesting @nbradbury , I'm sure there's a back story to this that I miss so, would you mind elaborating on the exception? I mean, what's special with the site picker? The slide-in-from-the-left seems to have the "illusion problem" when the app sits on the right-side of multi-window anyway.

**Comment by nbradbury** [comment]
The site picker is a chooser - you're choosing a site that when tapped will return you to the previous screen and make that site the active one. Given that, I think a different transition than the default is necessary.

That said, the transition doesn't have to be what we have now, just something to differentiate it.

**Comment by hypest** [comment]
Aha, I see, thanks for elaborating @nbradbury . I think that having different animations to separate notions is a good thing and there is no need to use the same animation everywhere. I'll play a bit with some alternatives (to the sliding we currently have) and see if it makes sense. Thanks!
