### ISSUE TITLE
Editor: allow linking to existing content within post/page

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-Android#4388]
When adding a link to a post in the WordPress.com editor, you have the option of selecting from a list of posts/pages already published on your site.

![screen shot 2016-07-14 at 13 47 54](https://cloud.githubusercontent.com/assets/7240478/16853448/98949862-49c9-11e6-85d5-0c8f4aee17a1.png)

Within the Android app though, there isn't a similar option. Users need to open their site in a browser, find the post, and then copy/paste the URL.

![screen shot 2016-07-14 at 13 48 52](https://cloud.githubusercontent.com/assets/7240478/16853488/bef3b3d0-49c9-11e6-9ea7-f3034a0cd8aa.png)

It would be awesome if we could offer a similar functionality through the app that allowed users to scroll through a list of recent posts/pages or enter a search term for specific posts.

We have a corresponding issue open for [the iOS app here](https://github.com/wordpress-mobile/WordPress-iOS/issues/3930), but I couldn't find an enhancement in this repo. Also raised in #116811-h.
# enhancement

**Comment by rachelmcr** [comment]
This came up in an app review (from a user on version 10.6).

Also note that this is coming to iOS in version 10.9 (see https://github.com/wordpress-mobile/WordPress-iOS/pull/10074 for the current implementation on iOS).

**Comment by SiobhyB** [comment]
This also came up in 1550482-z.

**Comment by shiki** [comment]
This also came up in another user feedback: 

> it is missing simple functions like being able to link posts to a phrase (I have to manually copy/paste the link)

**Comment by thehenrybyrd** [comment]
From a two star review:
>  There is no ability to link to other pages on the site when creating a new post, aside from manually entering the URL. Feature request: Bring up a list of links to choose from on our own site when tapping the link option.

**Comment by thehenrybyrd** [comment]
Another request in #2076119-z
To link to internal content on the Android app, you'd need reconstruct the desired URL from the slug plus publish date. This would be way easier if we allowed internal linking, as we do in the iOS app: 
 https://github.com/wordpress-mobile/WordPress-iOS/issues/3930

**Comment by designsimply** [comment]
I re-tested this using the block editor with WPAndroid 15.0-rc-1, and I found that it's still not possible to link to existing content via a search. This issue is still valid. 👍

Here is an updated screenshot of the current link manager for reference:

<img src="https://user-images.githubusercontent.com/1119271/83581070-ff496200-a4fa-11ea-9c39-5b504e52fd07.png" width="200" alt="Screenshot_20200602-135835">
<p style="clear:both;"><sup>Tested with WPAndroid 15.0-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by designsimply** [comment]
The ability to search for and link to existing content on the site was added in https://github.com/wordpress-mobile/gutenberg-mobile/pull/2484 and shipped with WPAndroid 15.9. Props @mkevins @dratwas. 🎉

<img src="https://user-images.githubusercontent.com/1119271/98419096-9209a200-2041-11eb-99d1-acc644e95a48.gif" height="350" alt="20201106_144714">
