### ISSUE TITLE
"Update Google Play Services" message at startup

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4391]
Running the latest `develop` on a new Android N emulator without Google APIs, I see this at startup:

![zg_duifw2s](https://cloud.githubusercontent.com/assets/3903757/16887910/dd5d14ba-4aaa-11e6-98d3-e4989b0b28ac.png)

That goes away when I tap "Update" but it re-appears the next time I start the app. Note that the user is already logged in, so this isn't happening on the sign-in screen.

We thought it might just be the fault of an immature N emulator, but @hypest reports seeing this on his 6.0 Nexus 5X for several weeks.

**Comment by kwonye** [comment]
Thanks to @maxme for verifying that this only occurs when the user has Google Play Services, but is using an older version.

It is best practice to build against the latest GPS sdk, and considering that the [majority of users are always on the latest version](http://www.forbes.com/sites/ewanspence/2014/06/25/google-has-93-of-android-users-on-the-latest-google-play-service-outperforming-apples-ios7-adoption-rate/#2b7e2db5174b), I believe we can close this.

**Comment by maxme** [comment]
> That goes away when I tap "Update" but it re-appears the next time I start the app. Note that the user is already logged in, so this isn't happening on the sign-in screen.

On a stock emulator, when you tap "update" nothing happens because the Play Store is not installed. On a device, you should be redirected to the Play Store and asked to update Play Services.

**Comment by hypest** [comment]
Adding more info: I'm seeing the popup on my 5X on which _I don't have_ a Google account added and PlayServices are outdated v8.1.86 (2287566-448). App works normally though and receiving push notifications as well.

**Comment by rachelmcr** [comment]
I'm closing this issue as it doesn't look like it's an ongoing concern; please reopen if there's still something to address here.
