### ISSUE TITLE
Post Settings: Add option to edit the post/page slug

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4396]
A user requested the ability to edit the post slug directly in the app. This could be added to the post settings, perhaps enabled after the post is saved as a draft.

Here's the current post slug option in the Calypso editor, after saving a draft:

<img width="841" alt="screen shot 2016-07-19 at 11 27 15 am" src="https://cloud.githubusercontent.com/assets/8658164/16946899/d96e0958-4da3-11e6-9917-5cea50557e3e.png">

<img width="794" alt="screen shot 2016-07-19 at 11 27 33 am" src="https://cloud.githubusercontent.com/assets/8658164/16946924/f1f2a5e2-4da3-11e6-9590-ed368be3e85d.png">

Related iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/501

**Comment by rachelmcr** [comment]
We have a request from an app review to support editing post slugs — in this case it's also related to the slugs automatically generated for non-Latin languages:

>WordPress Android app is getting better day by day, but I am hindi user so I have to post articles in hindi ,that's why WordPress generated automatically hindi url, this is really bad. Please provide a feature to choose url for any post. Thank you

**Comment by oguzkocer** [comment]
I am adding the `Broken Window` tag to this issue since we are working on the Post Settings as part of that project.

**Comment by tonyr59h** [comment]
Closed via #5899.
