### ISSUE TITLE
Follow/Following text flashes incorrect color

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#4398]
As discussed here: https://github.com/wordpress-mobile/WordPress-Android/pull/4359#issuecomment-233485216

### Expected behavior
For Follow/Following text to use correct color on the get go

### Actual behavior
They're using the correct color now, however, they first are in gray before that happens

Video: https://cloudup.com/ccjLsyWHTMR

After the icon update in https://github.com/wordpress-mobile/WordPress-Android/pull/4359, this old text color behavior still exists

### Steps to reproduce the behavior
1. Go to Reader
2. Visit any feed
3. Click on the Follow button (or if you're already Following, click it again to unfollow)
4. Notice how the button's text color first uses gray then shifts to its correct color

### Tested on [device], Android [version]
Samsung Note 4, Android 4.4.4, WordPress 4.2

**Comment by theck13** [comment]
I can't reproduce the medium blue text color which lingers for a second or two before changing to dark blue or green as in your video.  I see you tested on WordPress 4.2.  The currently released version is WordPress 5.5.1.  Can you update and confirm it's still happening?

Also, I noticed the text is bright blue when you press the Follow button.  You can press and hold to see it better.  Should that stay dark blue while pressing?

**Comment by jancavan** [comment]
Just checked out https://github.com/wordpress-mobile/WordPress-Android/tree/issue/4398-reader-follow-text and this seems to have solved the issue. 

Thanks for fixing this.
