### ISSUE TITLE
Scheduled post notification not showing info

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4402]
Originally reported by @mjangda 

### Expected behavior
When a post is scheduled, a notification should be triggered with the basic information about the post being published

### Actual behavior
_I received a scheduled post notification just now and it looked like this in the notification drawer. 

Clicking through, the notification looks fine but lacked a lot of information when viewed in the drawer._ 

![empty_notif](https://cloud.githubusercontent.com/assets/6597771/16965463/9724944e-4dd6-11e6-82e2-905e43b88de7.png)

### Steps to reproduce the behavior
1. Schedule a post
2. Wait for the schedule to happen, with the app in the background

**Comment by hoverduck** [comment]
Not sure if it's the same root problem or not, but I also see this symptom on the notification for a successful Import operation.  E-mail notif shown here for context:

![image](https://cloud.githubusercontent.com/assets/7233112/17037904/23281a02-4f61-11e6-8eef-d11c032d7ad4.png)

**Comment by mzorz** [comment]
thank you @hoverduck ! Will look into it too 👍

**Comment by mzorz** [comment]
Checked into this, and it all was a server-side problem. Will close this issue after my patch goes into prod.

**Comment by mzorz** [comment]
![schedpost](https://cloud.githubusercontent.com/assets/6597771/17789683/b055b36c-6569-11e6-91b2-3e478824233b.png)

Solved, in prod now 
cc @mjangda @hoverduck
