### ISSUE TITLE
Reader: Stream and card layout differences with Calypso

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#4404]
I came across differences between Android and Calypso Reader. Basically, I noticed this mainly because I feel like the timestamp is in the wrong place - it doesn't seem like it pertains to the post itself, rather the entire site:

![screenshot 2016-07-19 16 53 49](https://cloud.githubusercontent.com/assets/4924246/16970505/61403e96-4dd1-11e6-97b4-a4d09b527f43.png)

**For Followed Sites:**

- Card:
![screenshot-2016-07-19-16 14 16](https://cloud.githubusercontent.com/assets/4924246/16970518/7b0dd3a6-4dd1-11e6-9272-2ce2c41707d6.jpg)

- I also noticed that if it's a non-wpcom site, their URL is not shown:
![screenshot 2016-07-19 16 27 55](https://cloud.githubusercontent.com/assets/4924246/16970005/ddc83ee0-4dcd-11e6-9b3e-d524fb45e3e7.png)

**For main Discover stream:**

- In Calypso, we have a single site header at the very top of the main Discover stream to avoid site header repetition:

![screenshot 2016-07-19 16 32 33](https://cloud.githubusercontent.com/assets/4924246/16970104/9a4585dc-4dce-11e6-9e57-8a39c535eb65.png)

Card:
![screenshot-2016-07-19-16 42 54](https://cloud.githubusercontent.com/assets/4924246/16970365/678d4a6a-4dd0-11e6-9212-d990d714b056.jpg)

**For Full-post view:**

![screenshot-2016-07-19-16 51 46](https://cloud.githubusercontent.com/assets/4924246/16970489/429a64d0-4dd1-11e6-950a-4f99a453e23d.jpg)

Let me know if I should break this up into several smaller issues.

/cc @nbradbury

**Comment by nbradbury** [comment]
> In Calypso, we have a single site header at the very top of the main Discover stream to avoid site header repetition

I decided to move this to a separate issue (#4415). Everything else mentioned above will be fixed in the same PR.
