### ISSUE TITLE
Plans: Link directly to the selected site rather than just /plans

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4425]
When looking at the plans in the WordPress app I'm already doing it from the context of a single site.  But when I click the link at the bottom of the Plans page to "Manage your plan" it just dumps me out at https://wordpress.com/plans, and I have to immediately re-select the site I'm working on.

It would be nice if the link pointed to https://wordpress.com/plans/example.wordpress.com

Tested in alpha-18 on a Nexus 6P, 6.0.1

**Comment by oguzkocer** [comment]
Closed in #4435.
