### ISSUE TITLE
Plans: Personal plan mistakenly listed as Free

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4426]
### Steps to reproduce the behavior
Select a site in the app which has been configured with the Personal plan.

### Expected behavior
I expect the plan to be listed as Personal, with the details of what's included in that plan listed on the main page when selected

### Actual behavior
The site is listed as having the Free plan, and there's no mention of the Personal plan anywhere.

**Comment by kwonye** [comment]
@nbradbury we'll have to change to `/v1.4/plans` cc @frosty

**Comment by rachelmcr** [comment]
I checked this again today, and my site with the Personal plan is correctly listed as having the Personal plan (both on the My Site dashboard and in the Plans section). However, the Personal plan doesn't have a logo:

![2016-08-01 10 27 03](https://cloud.githubusercontent.com/assets/8658164/17291293/f6570a7e-57da-11e6-912d-16262f6215e1.png)


Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-18

**Comment by nbradbury** [comment]
> However, the Personal plan doesn't have a logo:

This is an issue on the backend which is currently being worked on.

**Comment by nbradbury** [comment]
This is now fixed on the backend.

![screenshot_1470523971](https://cloud.githubusercontent.com/assets/3903757/17459457/14ee9ca6-5c07-11e6-8b7c-41668dd51676.png)
