### ISSUE TITLE
Plans: Reopening app on plans page appends plans text

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-Android#4429]
### Expected behavior

When reopening the app when already on the plans page, I expect the to see the same plans text

### Actual behavior

Each time the app is reopened, the plans text is added to the page, resulting in a large blob of duplicated text (see screenshots below)

### Steps to reproduce the behavior

1. Navigate to plans page
2. Close app
3. Reopen app - see plans text
4. Rinse & Repeat

##### Tested on Galaxy Tab A, 5.0.2

![android - 1](https://cloud.githubusercontent.com/assets/128826/17166845/d2654854-541c-11e6-8d52-9cd9cf62dc20.jpg)
![android - 2](https://cloud.githubusercontent.com/assets/128826/17166844/d262bdf0-541c-11e6-84e1-946e6134b505.jpg)

**Comment by nbradbury** [comment]
@alisterscott Wow, I'm embarrassed we didn't notice this before - thanks for catching it! I'm working on a fix now.
