### ISSUE TITLE
Can't preview how a draft looks on the site anymore

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4437]
### Expected behavior

If I have a saved draft in the app, I expect to be able to preview how it will look on my site before I publish it.

### Actual behavior

In version 5.5, drafts could be viewed to see how they will look on the site (and on-site preview). Steps:

1. Open the app and go to the Blog Posts list
2. Find a saved draft (marked "Draft" in the list)
3. Tap the "View" link to view an on-site preview

As of version 5.6, though, drafts can only be previewed in the in-app preview, not the on-site preview. Steps:

1. Open the app and go to the Blog Posts list
2. Find a saved draft (marked "Draft" in the list)
3. Tap the "Preview" link to view an in-app preview

@0nko could this have been introduced along with the Publish button in #4189, and if so, was it intentional? Unfortunately this prevents users from seeing a "real" preview of how the draft will look on their site.

#### Screenshots

On-site preview in version 5.5:

![screen shot 2016-07-28 at 1 14 17 pm](https://cloud.githubusercontent.com/assets/8658164/17212388/ccb8d02e-54c6-11e6-98d3-f30b87074d60.png)

![screen shot 2016-07-28 at 1 29 12 pm](https://cloud.githubusercontent.com/assets/8658164/17212450/49d81132-54c7-11e6-9c57-aeb499675514.png)

In-app preview in version 5.6:

![screen shot 2016-07-28 at 1 20 54 pm](https://cloud.githubusercontent.com/assets/8658164/17212396/db839602-54c6-11e6-9831-0513ac487038.png)

![screen shot 2016-07-28 at 1 26 38 pm](https://cloud.githubusercontent.com/assets/8658164/17212404/ef1cc792-54c6-11e6-8560-b68180cbfca8.png)

**Comment by 0nko** [comment]
Thanks @rachelmcr, I'll look into this.

**Comment by 0nko** [comment]
You are right, it was introduced in that PR. It my mistaken assumption that only published posts can be "viewed", whereas drafts/local drafts are only "previewed". I'll push a fix shortly.

**Comment by maxme** [comment]
@0nko can you branch from `hotfix/5.6.1` please? This would be great to have this fix in the next hotfix release.

**Comment by 0nko** [comment]
I was just going to ask about that. Yes :).

**Comment by aforcier** [comment]
Fixed  in #4451.
