### ISSUE TITLE
Viewer list is in wrong order

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4457]
Viewer list should be ordered as newest first, exactly as it's returned from the API.

**Comment by rachelmcr** [comment]
Sorry for the confusion — the Viewer list is already ordered as oldest first, as returned from the API.

Calypso web is different. There, Viewers are ordered as newest first. Should I open a Calypso issue to address that, so the behavior matches everywhere?

**Comment by oguzkocer** [comment]
@rachelmcr I fixed the issue, my bad on the original description.

**Comment by oguzkocer** [comment]
Fixed in #4460
