### ISSUE TITLE
People: Viewer section isn't immediately added/removed when you change site privacy

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4459]
### Expected behavior

If you change a site to private, the Viewer section should appear in People Management.

Likewise, if you change a site from private to public, the Viewer section should be removed from People Management.

### Actual behavior

The Viewer section is not added/removed from People Management until you close and reopen the app.

### Steps to reproduce the behavior

1. Open the My Sites tab and select a public site
2. Go to Settings
3. Change the Privacy setting to Private
4. Go back to the My Sites tab and go to People
5. Tap to view the People filter (Team/Followers/Email Followers). Result: The Viewer section does not appear in the app
6. Swipe to close the app completely
7. Reopen the app and go to People
8. Tap to view the People filter (Team/Followers/Email Followers/Viewers). Result: The Viewer section now appears in the app.

You can also repeat these steps, changing the Privacy setting back to Public/Hidden, and the Viewer section does not go away until you close and reopen the app.

##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-18
h/t @designsimply  for the original report

**Comment by oguzkocer** [comment]
When the site picker is visible we update the blog details and cache it. I think we also update the blog details every 6 hours or so, I am not sure. Without pushing details from server to client, which we don't do for anthing other than notifications, we can't know that the visibility of the site is changed on the server. You can actually open the site, go to people, come back to the site picker and go back into your site and the visibility will be updated, so no need to completely close the application. We consider these kind of situations as edge case and don't really handle it.

The opposite is a bit tricky, where the site is not visible and you can see the viewers and the site got changed to public and they're gone now. In these cases, we trust that any action the user takes will be responded with an error from the server side.

It's worth to note that this situation can happen on any feature. When you change something on the remote, it's very optimistic to expect it to be reflected on the apps immediately. Having said that, maybe with the stores implementation we'll update a single blog's detail when it's page is visible which would somewhat help with the issue.

In any case, this is a general issue with the app and not related to the people management or the viewers, so I am tagging this as "Wont Fix" and closing the issue.

Thanks for bringing it up @rachelmcr and for the original report @designsimply.
