### ISSUE TITLE
Plan: not enough room for tabs

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4466]
I just noticed a fourth plan was in today, and we don't have enough room for the 4 tabs on small screen devices:

![screenshot-2016-08-02_15 33 15 708](https://cloud.githubusercontent.com/assets/40213/17330302/a2c9aa3c-58c6-11e6-9df1-d50200c0b7cc.png)

We should probably use scrollable tabs, the experience is not the best, but it can adapt to any screen / number of plans / i18n.

**Comment by maxme** [comment]
cc @nbradbury

**Comment by maxme** [comment]
In french: 

![screenshot-2016-08-02_15 38 36 732](https://cloud.githubusercontent.com/assets/40213/17330459/31c326aa-58c7-11e6-9b00-2bd47dc4d080.png)

**Comment by nbradbury** [comment]
Closed via #4473
