### ISSUE TITLE
PeopleTable cache order is wrong

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4467]
### Expected behavior
When I go into the people page that I visited earlier, I expect the list to be ordered by display name (users) or default (follower, email follower & viewers)

### Actual behavior
When I visit the people page for the second time, I see the list start with display names starting with `C` and after the network request is completed people with display names starting with `A` and `B` just gets inserted.

### Steps to reproduce the behavior
* Go into the people page for a site with a lot of users (at least 21). You can change `PeopleUtils.FETCH_LIMIT` to something smaller if you don't have a site that has 21 users.
* Browse to the end of list, so the network requests are finished and at least the second page is loaded
* Go back to My Site
* Go into the People page again and you should see the order is messed up for a second until the network request is finished and people gets inserted all over the place

##### Tested on [device], Android [version]
It's a DB issue, so it's across all devices and versions.

**Comment by maxme** [comment]
I'll check this one was fixed by #4465

**Comment by maxme** [comment]
Addressed by 9ce6c43
