### ISSUE TITLE
How can i get posts from my Wordpress? Sorry, just beggining

### ISSUE THREAD

**Issue by JoaoRPF** [wordpress-mobile/WordPress-Android#4481]

**Comment by maxme** [comment]
Are you trying to modify the WordPress for Android app? Did you fork the project? You can read the code to fetch posts from the XMLRPC endpoint [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUpdateService.java).

If you're looking for a library to base a WordPress app on, have a look at [FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android), you'll be able to fetch Post very soon with it.

**Comment by JoaoRPF** [comment]
I tried some external libraries do access my blog information, but none of them has the possibility to extract posts by categorie/slug. Only a general get_posts

**Comment by maxme** [comment]
> I tried some external libraries do access my blog information, but none of them has the possibility to extract posts by categorie/slug. Only a general get_posts

It seems unrelated to this project (WordPress for Android app). You might have better luck asking for help with a precise question.
