### ISSUE TITLE
Kickstarter oEmbed URLs not embedding in posts published from the app

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4484]
### Expected behavior

I expected Kickstarter URLs starting with `kickstarter.com/projects` or `kck.st` to be embedded in a post, per the oEmbed list here:

https://github.com/WordPress/WordPress/blob/master/wp-includes/class-oembed.php#L94

This works as expected when publishing from the web and viewing the post on the web.
### Actual behavior

Kickstarter URLs are displayed as plain links in the published post (in the app and on the web) instead of being embedded.
### Steps to reproduce the behavior
1. Find a Kickstarter project and copy the link to it (both the full URL and the short `kck.st` version)
2. In the app, start a new post
3. Paste the links to the Kickstarter project on their own lines in the editor
4. Publish the post

Result: The projects are not embedded in the post.
#### Screenshots

Kickstarter URLs posted from the web editor and viewed in a browser:

![screen shot 2016-08-08 at 1 15 25 pm](https://cloud.githubusercontent.com/assets/8658164/17479386/37804d14-5d6a-11e6-971f-ad064df3e205.png)

The same Kickstarter URLs posted from the Android editor and viewed in a browser:

![screen shot 2016-08-08 at 1 15 36 pm](https://cloud.githubusercontent.com/assets/8658164/17479390/3f3260a6-5d6a-11e6-9bd8-b15868624af7.png)

**Comment by maxme** [comment]
This one should be easy to fix - see https://github.com/wordpress-mobile/WordPress-Android/pull/1963
