### ISSUE TITLE
NUX: Offer suggestions for username/site address when the first choice is already taken

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4485]
When a user creates a new account, we offer a fairly unhelpful error message if the username or site address is already taken:

Username isn't available:

> That username already exists

Site address isn't available:

> That site already exists

It would be great to offer suggestions to users when their first choice isn't available, so they don't have to repeatedly enter their choices and potentially continue to run into that error. Not being able to find an available username or site address is very discouraging and can lead users to abandon the signup.

**Comment by rachelmcr** [comment]
### Screenshots from the app signup

![2016-08-08 16 59 12](https://cloud.githubusercontent.com/assets/8658164/17488835/13367608-5d93-11e6-82eb-18c5d0b3e3aa.png)

![2016-08-08 16 59 01](https://cloud.githubusercontent.com/assets/8658164/17488837/14f7145c-5d93-11e6-9503-3c493e779bb8.png)


### Screenshot from web signup

![screen shot 2016-08-08 at 6 06 08 pm](https://cloud.githubusercontent.com/assets/8658164/17488880/4909981e-5d93-11e6-89ca-a8f633e597a3.png)

**Comment by maxme** [comment]
For the domain name, we can use the `/domains/suggestions` endpoint with the following params: https://public-api.wordpress.com/rest/v1.1//domains/suggestions?query=poney&quantity=1&include_wordpressdotcom=true

For the username, I don't think there is a better solution than appending random number after the what the user entered (probably not worth implementing that), we could eventually ask the user if he wants to use the domain prefix as username.
