### ISSUE TITLE
Too many concurrent connections

### ISSUE THREAD

**Issue by rostockahoi** [wordpress-mobile/WordPress-Android#4494]
### Expected behavior

I have a shared server with a Wordpress instance which is only used by me. I tried to use the Wordpress iOS and Android app to manage posts and stuff. The server is hosted at german provider Netcup.
### Actual behavior

Everytime I am doing a single action with the app (eg. edit post, upload media), the hoster's firewall triggers because of too many concurrent connections (as they say). The device's IP is then banned for this so the server is unreachable.
### Steps to reproduce the behavior

Actually to reproduce one needs a server at Netcup. I tried another fresh Wordpress, same thing. **So should the app really trigger the firewall? I am sure that I cannot make the provider change his firewall rules.**
##### Tested on [device], Android [version]

OnePlus X (latest Oxygen), iPhone SE (latest)
### Netcup support answer:

[...] Dies ist in der Tat ein serverseitiger Sicherheitsmechanismus und (leider) im Zusammenhang mit der Wordpress App bekannt. Diese baut, warum auch immer, zu viele gleichzeitige Verbindungen zum Server auf, sodass dann unsere Firewall eingreift. [...]

**Comment by TheMokke** [comment]
I have the same issue... with Netcup.

Is there a workaround?

Please fix the issue. :(

**Comment by maxme** [comment]
@TheMokke there is no work around with the app. We must query the XMLRPC API for a bunch of things to get infos and make the app work. This is not an issue with the app, it's an issue with your host. Ask them to update their firewall configuration and be less strict.

**Comment by rostockahoi** [comment]
Thanks @maxme to make that clear. I sent a note to the support with this thread so they can see it.

**Comment by rostockahoi** [comment]
@maxme can you estimate the amount of queries done? The support needs an idea of that in order to adjust firewall rules.

**Comment by maxme** [comment]
@rostockahoi that depends of your usage of the app. On a 5 minutes sample with and excessive usage (moderated and then deleted a bunch of comments), it's around ~40 requests/minute. So tell them 100 requests/minute, I don't think you can ever hit that with a normal usage of the app.

**Comment by stephankn** [comment]
Sorry for late reply: As I recently experienced the same issue with a Wordpress hosted on Netcup, here a working solution in case others are affected as well:

To bypass the xmlrpc rate limiter of the hoster you have to rename the xmlrpc.php endpoint. The FAQ of the wordpress app links to a plugin which changes the code to point to the now renamed endpoint. With this modification the app works again as expected.
