### ISSUE TITLE
Import successful notification empty

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4502]
originally reported here: https://github.com/wordpress-mobile/WordPress-Android/issues/4402#issuecomment-234375851

### Expected behavior
When a blog is imported and import finishes, a notification should be triggered with the basic information about the blog that has been imported.

### Actual behavior
_empty notification shown in the notification drawer. 

![image](https://cloud.githubusercontent.com/assets/7233112/17037904/23281a02-4f61-11e6-8eef-d11c032d7ad4.png)

**Comment by mzorz** [comment]
@hoverduck the fix for this is in prod now. Let me know if you find anything weird though 👍

**Comment by hoverduck** [comment]
@mzorz I checked it out and the Android notification now looks good, but the Calypso desktop (from the browser, not the app) notification is blank (again, showing corresponding mail notification for context):

<img width="359" alt="screen shot 2016-08-18 at 4 36 56 pm" src="https://cloud.githubusercontent.com/assets/7233112/17789928/48b89bcc-6562-11e6-8fbb-0a84c83b0ef5.png">

Should I open a new ticket on the Calypso side?

**Comment by mzorz** [comment]
Yes please - I think it might be a good idea -  cc @dmsnell  as it's probably because we changed the path for PNs and `WP_Note` callbacks are not called anymore (we're using v1.1. Notification builders now)
