### ISSUE TITLE
Use versionCode instead of versionName for registering devices to our PN server

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4503]
### Expected behavior
Each time the client app registers itself by means of calling `/devices/new` endpoint, we should be sending the `versionCode` as part of its meta-data. Version code is an incremental integer and thus is the right way to correctly identify / compare among versions.

### Actual behavior
Right now we are sending `versionName` (a String) for registering, and the server-side code is plagued with different ways for comparing app versions thus leading to possible bugs (and certainly confusion). The place in Android where this is being tracked and sent is here https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java#L98 (check parameter `app_version`).

**IMPORTANT NOTE** Please note that this change should be taken carefully as will probably need carefully going through analyzing already-registered values and evaluating the impact as we change both the registered value and the code that evaluates the value server-side

### Steps to reproduce the behavior
Just install the app on a device to make this part of the code run.

**Comment by daniloercoli** [comment]
I'm going to just add this new `version_code` field both on client and the sever. 
Server side we're safe. We will start storing this new key/value, and we will use it in the future, instead of using the `app_version` key/value. So basically, even on the server changes required are minimum.
