### ISSUE TITLE
PIN input screen can be easily bypassed

### ISSUE THREAD

**Issue by hlashbrooke** [wordpress-mobile/WordPress-Android#4504]
### Expected behavior

When opening the app with PIN lock on you should only be allowed to see anything once the correct PIN/fingerprint has been used.
### Actual behavior

When I see the PIN/fingerprint screen then hit my phone's back button, the app is then reopened without the PIN/fingerprint screen. This means that anyone can open the app and easily bypass the security check.
### Steps to reproduce the behavior
1. Switch PIN lock on
2. Exit the app
3. Wait a few seconds and then reopen the app - you should see the PIN/fingerprint screen
4. Press your phone's back button
5. _Quickly_ reopen the app - you should now be in the app without having to go through the PIN/fingerprint security check

**Tested on Samsung Galaxy S6 Edge, Android 6.0.1, App version alpha-19**

**Comment by marwendoukh** [comment]
I seem to able to reproduce 

**Test on Samsung Core 2 , Android 4.4.2 , App version alpha-20**

**Comment by aerych** [comment]
cc @maxme / @tonyr59h

**Comment by daniloercoli** [comment]
Created a ticket for this issue in the PasscodeLock-Android project here: https://github.com/wordpress-mobile/PasscodeLock-Android/issues/42

**Comment by daniloercoli** [comment]
Addressed in #4856
