### ISSUE TITLE
Running app in multi-window changes padding

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4505]
Running WordPress in multi-window makes the effective width much smaller. It should stay the same width.

Normal width:
![screenshot_20160822-135903](https://cloud.githubusercontent.com/assets/1158819/17900243/4fde6698-6913-11e6-8820-a4fbc6289c84.png)

Multi-window width:
![screenshot_20160822-135842](https://cloud.githubusercontent.com/assets/1158819/17900242/4fb1f93c-6913-11e6-87fa-805df7e90a22.png)

**Comment by kwonye** [comment]
As @maxme noted, a more thorough audit of multi-window for our app is a great idea. I'll do that and report back to this issue with a list.

**Comment by nbradbury** [comment]
I was curious what was causing this, so I took a look and it turns out it's due to Android telling the app it's in landscape when you switch to vertical multi-window mode. We use a larger left/right margin (based on `dimens/content-margin`) when in landscape, so switching to multi-window causes this larger margin to be used.

**Comment by hypest** [comment]
Thanks for the comment @nbradbury ! Makes it easier to debug and fix the issue.

@kwonye , I think I will tackle this one as it seems pretty narrow in scope and we can always fix any additional issues your audit might bring up! Let me know what you think. Thanks!

**Comment by kwonye** [comment]
Sounds great, thanks @hypest.

Also, looks like there are no other issues with split-screen. Copy-paste works well and all functionality is intact.

**Comment by hypest** [comment]
I've addressed this issue with PR #4530 . In there, I've also adjusted the margins logic for the Reader and Notifications list since those are affected by multi-window mode as well.
