### ISSUE TITLE
People: User role from Team shows up next to non-user viewer

### ISSUE THREAD

**Issue by vparkhere** [wordpress-mobile/WordPress-Android#4506]
### Expected behavior
When a user is going through the Team, Followers, Email Followers, and Viewers, the correct user role (or lack of) should show up next to the username.

### Actual behavior
Going from Team  > Followers > Viewers in rapid succession results in the user role of someone in Team showing up as the user role next to the Viewer's username.

<img src="https://cloud.githubusercontent.com/assets/11635760/17993827/48ac6360-6b08-11e6-8e3f-c72d2ee7d3d1.png" width="400">
<img src="https://cloud.githubusercontent.com/assets/11635760/17993826/48a6dbca-6b08-11e6-882f-5a14da159c70.png" width="400">

### Steps to reproduce the behavior
1) Go to Site dashboard > People.
2) Add viewer to site.
3) Start with Team selected, then select Followers (or Email Followers), then Viewers.

Result: A user role of a user in Team will show up as the user role of the viewer, despite the viewer not having a user role.

You must go from Team > Followers or Email Followers > Viewers to replicate the issue, going from Team > Viewers will result in seeing no user role next to the viewer, which is correct.

**Comment by rachelmcr** [comment]
Good eye! I can reproduce this on my Nexus 9, Android 6.0.1, WPAndroid alpha-20.
