### ISSUE TITLE
Reader Post List: emoji weirdness in post titles

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4507]
### Expected behavior

<img width="768" alt="screen shot 2016-08-26 at 09 37 47" src="https://cloud.githubusercontent.com/assets/40213/17997793/150a9a90-6b71-11e6-9f3d-a8b82d4b11ff.png">

(From Calypso reader)
### Actual behavior

![screenshot-2016-08-26_09 37 45 389](https://cloud.githubusercontent.com/assets/40213/17997802/1d7f3f1e-6b71-11e6-839a-146e7e8b2488.png)

(on a genymotino 6.0)

**Comment by nawabhussain** [comment]
is this issue resolved ?

**Comment by daniloercoli** [comment]
Can't reproduce this issue on wp-android 6.7.
Tried both on Genymotion, and on Nexus 5X.
