### ISSUE TITLE
People: Confusing styling on the Role selection dropdown

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4510]
The Role selector on the Invite page looks like it's hardcoded to the preset value of Follower/Viewer.  There's nothing in the visual to indicate that you can click on it to reveal a list of choices.  I'd expect to see a down arrow, or a box around it, or something to direct me to tap it.

I'd also like to see a help link to http://en.support.wordpress.com/user-roles/ with the descriptions of what the different roles mean, like the one that exists on the web version of the invite page.

<img src='https://cloud.githubusercontent.com/assets/7233112/18009194/34d1c67a-6b79-11e6-90f1-67219c45947d.png' width='250px'>

**Comment by rachelmcr** [comment]
>I'd also like to see a help link to http://en.support.wordpress.com/user-roles/ with the descriptions of what the different roles mean, like the one that exists on the web version of the invite page.

We could also write an in-app FAQ about the different roles, and potentially link from within the app to the FAQ. (I'll work on adding the FAQ in any case.)

**Comment by rachelmcr** [comment]
I added a FAQ titled "How can I add a user to my site" in Helpshift (for both Android and iOS apps). It includes a brief explanation for how to add users, and a summary of each user role with a link to the [WordPress.com support page](http://en.support.wordpress.com/user-roles/) for more details.

**Comment by nawabhussain** [comment]
@rachelmcr The FAQ should be opened in an in-app browser. I would suggest we do the same with the privacy policy and terms of service ( App Settings > Wordpress for Android ).
