### ISSUE TITLE
Reader: Post header doesn't appear on all posts in the post list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4517]
### Expected behavior

I expect the post header to appear on all posts in the Reader except in the Discover list (where the Discover section should have a site header but the posts shouldn't have post headers).

### Actual behavior

In the Reader post list, some posts have a header and others don't. I saw this on multiple lists, including Followed Sites and tag lists.

I also noticed that the problem was not consistent — the same site may have some posts with post headers and some without. Also, if I pulled down to refresh the list it didn't have an effect, but if I rotated the device between portrait and landscape the post header appeared on all the posts in the list.

However, when I tapped on a post with no post header, I did consistently see a post header on the post detail view.

@nbradbury could this be an unintended effect of #4436?

### Steps to reproduce the behavior

1. Open the app and go to the Reader
2. Select a list other than Discover
3. Scroll through the post list and look for posts with/without post headers

#### Screenshot

Posts with and without the post header, with the Food tag:

![2016-08-30 14 12 01](https://cloud.githubusercontent.com/assets/8658164/18094668/2e122f9a-6ecc-11e6-9c2f-175da36e38c2.png)

**Comment by nbradbury** [comment]
I can repro this, and I think you're right it's a side effect of #4436. I'm working on the fix now.
