### ISSUE TITLE
Potential resource leak in the org.wordpress.android.WordPressDB class

### ISSUE THREAD

**Issue by andrew659** [wordpress-mobile/WordPress-Android#4526]
In the class [org.wordpress.android.WordPressDB](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPressDB.java):

### Expected behavior

In the saveMediaFile() method (lines 1606 - 1609), the database cursor should be closed regardless it is empty or not (i.e., whether cursor.moveToFirst() returns true or false)

### Actual behavior

the database cursor is only closed when it is not empty (i.e., when cursor.moveToFirst() returns true)

**Comment by maxme** [comment]
Thanks for the report, we're going to drop the whole `WordPressDB.java` file soon.
