### ISSUE TITLE
Support Authy 2FA

### ISSUE THREAD

**Issue by edent** [wordpress-mobile/WordPress-Android#4528]
### Expected behaviour
As a user, I want to be able to use my [Authy](http://authy.com/) 2FA code to log in to my self-hosted WordPress via the Android App.

### Actual behaviour
There is no option to add a 2FA code in the WordPress app.

Authy disables XML-RPC services because they don't support 2FA.

I can re-enable XML-RPC, but that negates the security aspect of 2FA.

As far as I can tell, [2FA isn't natively supported on WordPress](https://make.wordpress.org/core/tag/two-factor/).

### Steps to reproduce the behaviour
1. Install Authy and configure on blog.
2. Try to log in to blog with Android app.

##### Tested on [device], Android [version]
Nexus 6, Android 6.0.1

See also https://github.com/authy/authy-wordpress/issues/21

**Comment by maxme** [comment]
The only supported 2FA is the one provided by WordPress.com. Unfortunately the app can't support this kind of WordPress plugins. I don't know how this plugin works, but sometimes this kind of 2FA plugins let you create "App password" you can use in this situation.
