### ISSUE TITLE
I can't login to my self hosted site.

### ISSUE THREAD

**Issue by sk29110** [wordpress-mobile/WordPress-Android#4529]
### Expected behavior
I can login to my self-hosted wordpress site using wordpress for android app

### Actual behavior
When trying to login it gives me error "Invalid SSL certificate"

### Steps to reproduce the behavior
after installing the wordpress for android.
enter login and password with self-hosted website url.

##### Tested on [device], Android [version]
android version 5.7
Samsung SM-T230NU

**Comment by maxme** [comment]
> When trying to login it gives me error "Invalid SSL certificate"

When you get that view, you should be able to "Trust this certificate". Are you using the self signed SSL certificate on your site?

**Comment by maxme** [comment]
@sk29110 that's weird. I just tried using the following URLs: `http://skoizumi.com/msl/xmlrpc.php`, `skoizumi.com/msl` and `http://skoizumi.com/msl`, our endpoint discovery returns `http://skoizumi.com/msl/xmlrpc.php` in all cases.

Can you try again and contact us via the in app messaging: tap the "?" button on the sign in screen then "Contact Us" (we'll get your app logs with your message that will help us debug).

**Comment by sk29110** [comment]
OK somehow it works now at home. I was testing on crappy internet that might be the reason.

**Comment by maxme** [comment]
Perfect, thanks for the update.
