### ISSUE TITLE
MediaStore integration

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4541]
As part of FluxC project, we'll be integrating the [MediaStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/122).

Here is a list of activities that needs to be updated with the new network layer:
- [ ] EditPostActivity
- [ ] MediaBrowserActivity
- [ ] MediaGalleryActivity
- [ ] MediaGalleryPickerActivity
- [ ] MediaPickerActivity

Main fragments we use in these ^ activities:
- [ ] MediaEditFragment
- [ ] MediaAddFragment
- [ ] MediaGalleryEditFragment
- [ ] MediaItemFragment

We'll also need to either update or get rid of these following classes:
- [ ] MediaUploadService
- [ ] MediaEvents
- [ ] MediaFile
- [ ] MediaGallery
- [ ] WordPressMediaUtils
- [ ] MediaSourceWPImages
- [ ] MediaSourceWPVideos
- [ ] ApiHelper.SyncMediaLibraryTask
- [ ] ApiHelper.EditMediaItemTask
- [ ] ApiHelper.GetMediaItemTask
- [ ] ApiHelper.UploadMediaTask
- [ ] ApiHelper.DeleteMediaTask

Not all of these classes will need major modifications and this might not be a comprehensive list as is, so we should update the issue if we find more classes that'll need to be updated for easy tracking.

/cc @maxme & @tonyr59h

**Comment by maxme** [comment]
🔥 ApiHelper 🔥

**Comment by aforcier** [comment]
This has been addressed - mostly in https://github.com/wordpress-mobile/WordPress-Android/pull/4616 and some subsequent smaller PRs.
