### ISSUE TITLE
can't disable "Your stats are booming!" app notification

### ISSUE THREAD

**Issue by snarfed** [wordpress-mobile/WordPress-Android#4558]
feature request: it looks like there's no way to disable the "Your stats are booming!" app (ie push) notification. i have all of the notification toggles turned off in _Notification Settings => [site] => App notifications_, but evidently none of them affect this.

i have one self hosted site and a few wordpress.com sites in the app, and this has only ever happened for the self hosted site. (that site gets the most traffic by far, though.)

this is on wordpress app version 5.8 and earlier, on a nexus 5x, android versions 6.x and 7.0.

(apologies for filing here, btw! i tried to post on https://android.forums.wordpress.org/ , but the _New Topic in this Forum_ link at the bottom is text, not a link, even when i'm logged in, and i couldn't find any other way to post.)

**Comment by daniloercoli** [comment]
This has been fixed server side. Let us know if you're still seeing this issue, thanks.
