### ISSUE TITLE
Search: Text color in saved searches is white

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#4560]
### Expected behavior
For text color to be `grey_dark` for readability.

### Actual behavior
Text color is white:
![screenshot_2016-09-22-13-35-50](https://cloud.githubusercontent.com/assets/4924246/18765326/0e87af0a-80ca-11e6-9c86-e31fd87762ed.jpg)

### Steps to reproduce the behavior
Type a keyword in Search to bring up the saved searched dropdown.

##### Tested on [device], Android [version]
WordPress Android Version Alpha-19

/cc @nbradbury

**Comment by nbradbury** [comment]
Note: I wasn't able to repro this with Android 6 or 7, but I was with Android 4.4.
