### ISSUE TITLE
Error liking original of reblogged post

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4572]
To reproduce:
Find a reblogged post in the reader.  The easiest way is to follow your own blog, reblog a post, then view that post in your followed stream. 
View the post detail. 
Find and tap on the link to view the original post. 
In the original post, scroll down and tap the like button. 
Notice that the tap is registered but the action fails. I'm left looking at a blank screen. 

Nexus 5x 
WPAndroid 5.8 rc 1
Android 7.0

**Comment by theck13** [comment]
Can you confirm the steps below will reproduce the issue?  I was able to view the original post without the blank screen you mentioned.

### Test
1. Go to blog [post](i.e. https://examplebloge.wordpress.com/2016/10/11/232/) from desktop browser.
2. Click ***Reblog*** button.
3. Click ***Reblog Post*** button.
4. Go to ***Reader*** tab in mobile app.
5. Select ***Followed Sites*** from dropdown list in action bar.
6. Tap reblogged post from Step 3.
7. Tap ***View original post*** link.
8. Notice original post loads with blank screen.

### Device
LG G4 (LG-H815) on Android 6.0.1 with WordPress 5.9

**Comment by aerych** [comment]
Whoops!  I had a typo in the description. I wrote `In the original post, scroll down and tap the link button. ` but I should have said `In the original post, scroll down and tap the like button. `
s/link/like 
I'll update the description

**Comment by theck13** [comment]
This occurs when tapping the `Like` button from any post in a `WebView`.  The subsequent URL is `https://wordpress.com/public.api/connect/?action=verify&service=wordpres` and the following message is logged.

```
10-13 13:18:36.311 18309-18309/org.wordpress.android.beta I/chromium: [INFO:CONSOLE(21)] "Scripts may close only the windows that were opened by it.", source: https://wordpress.com/public.api/connect/?action=verify&service=wordpress (21)
```

**Comment by theck13** [comment]
The HTML for `https://wordpress.com/public.api/connect/?action=verify&service=wordpress` is below.

```
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<script type="text/javascript">
		var isUsingHighlander = false;
		try {
			isUsingHighlander = ( null != window.opener && 'object' == typeof window.opener.HighlanderComments );
		} catch( e ) {}

		if ( isUsingHighlander ) {
			window.opener.HighlanderComments.doExternalLoggedIn( 'wordpress' );

			// If there's a Highlander nonce available, we should update it with the correct value
			var highlanderNonce = window.opener.document.getElementById( 'highlander_comment_nonce' );
			if ( highlanderNonce )
				highlanderNonce.value = '323f807b48';
		}
		window.open('', '_self', '');
		window.close();
	</script>
</body>
</html>
```

**Comment by theck13** [comment]
The `https://wordpress.com/public.api/connect/?action=verify&service=wordpress` HTML is verifying authentication then attempting to close itself before performing the action (i.e. Like).  Since the window wasn't opened by itself, the `Scripts may close only the windows that were opened by it.` message occurs and the window can't be closed.  You can see the behavior visiting the link below with a desktop browser and clicking the `Like` button.

https://leif.me/2016/06/from-playing-the-piano-to-algorithms-you-can-trust/

I'm not sure why this verification is required when the original `WebView` is loaded with authentication.
