### ISSUE TITLE
Save/restore local changes on logout/login and drop the scary warning dialog on logout

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4573]
The wording of the button, along with the pop up warning “Disconnecting your account will remove all of ___’s WordPress.com data from this device, including local drafts and local changes” is unnecessarily nerve-wrecking, especially if there are none.

Why can't it just be "Log out" along with a nicer message since the data is backed up on WordPress.com anyways? Especially if there are no local changes.

**Comment by rachelmcr** [comment]
For reference, there's some past discussion about the terminology (connect/disconnect v. log in/out) in this PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/3273

Whatever wording is used, I agree that a nicer message would be helpful to specify what the danger is on logging out (that is, local drafts/changes being lost).

**Comment by maxme** [comment]
> I agree that a nicer message would be helpful to specify what the danger is on logging out (that is, local drafts/changes being lost).

We should backup local drafts on logout and restore them on re-login (with the same sites). Once we have that we could just drop the dialog.

**Comment by oguzkocer** [comment]
> We should backup local drafts on logout and restore them on re-login (with the same sites). Once we have that we could just drop the dialog.

I am a little uncomfortable with this. As a power user I expect my local data to be deleted when I logout from an app. I understand that most of our users are not power users, but this still feels wrong to me security-wise.

**Comment by hypest** [comment]
For reference, here's an older ticket #1989 we might want to close (or not) after this one gets worked on perhaps.

**Comment by sarahblackstock** [comment]
Had a recent case where a user's phone rebooted suddenly and logged him out of the app, so all local drafts were lost, even though he had not intentionally logged out. He would have liked an option to restore the drafts somehow.

Internal ref: #186086-h

**Comment by tonyr59h** [comment]
Since we are (and should imo) showing a dialog to confirm logout already we can just reword the text and add a checkbox to toggle preserving user data once it's in FluxC.

**Comment by koke** [comment]
We've been discussing this (p4a5px-2bV-p2), and decided to show a simple confirmation if there are no local changes/drafts:

> Log out of WordPress

If there are any changes that would be lost, then we'd show this message:

> You have changes to X posts that haven’t been uploaded to your site and are only saved on this device. Logging out now will delete those changes. Log out anyway?

**Comment by nbradbury** [comment]
@koke Just an FYI I've opted to drop "and are only saved on this device" from the message (see #7655 ). I feel the more words there are, the less likely people will read the message.

**Comment by koke** [comment]
Thanks, updated the iOS issue to match: https://github.com/wordpress-mobile/WordPress-iOS/issues/3164

Closing this in favor of #7655
