### ISSUE TITLE
Widgets: Maybe improve prompt/graphic to clarify widget usage

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4577]
Would it make sense to tweak this prompt to show a 4x1 widget vs a 1x1 widget to be more consistent with the stats widget?  Also it might not be clear to, newer android users, or android users new to widgets, how to actually go about adding a widget.  Maybe we could link to an FAQ for further instruction? 
h/t Zing 

![screenshot_20160928-093349](https://cloud.githubusercontent.com/assets/1435271/18919774/f7cd9ed8-8564-11e6-8c26-a2daad30df39.png)

**Comment by maxme** [comment]
cc @daniloercoli and @jancavan

**Comment by rachelmcr** [comment]
>Maybe we could link to an FAQ for further instruction? 

I was thinking the same thing, and I'm brainstorming how to write a FAQ that clearly explains this (keeping in mind that the exact process can vary between devices and that there could be terminology confusion with WordPress widgets).

**Comment by jancavan** [comment]
> I was thinking the same thing, and I'm brainstorming how to write a FAQ that clearly explains this (keeping in mind that the exact process can vary between devices and that there could be terminology confusion with WordPress widgets).

This is actually the same reason why we decided against the addition of instructions in the past because they are bound to differ between devices/OS versions.

**Comment by rachelmcr** [comment]
I added a FAQ with the caveat that the exact steps can vary between devices:

https://automattic.helpshift.com/a/wordpress/?s=general&f=home-screen-stats-widget
