### ISSUE TITLE
Editor: Post preview shows error for iframe youtube embeds missing a scheme.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4579]
To reproduce: 
In a web browser, publish a new post with the following content:
`<iframe src="//www.youtube.com/embed/iOYdTx8ElXE" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>`
Notice that the `src` does not specify http or https. 
In the app, find the post in the post list and tap to view its detail. 
Notice that the webview tries to render the video but shows a 404 error as it assumes a `file` scheme rather than `http` or `https`.

**Comment by theck13** [comment]
I can't reproduce this one.  I created a new [post](https://examplebloge.wordpress.com/2016/10/11/232/), but I'm able to view the post in the app without error.  See the screenshots below for details.

![4579](https://cloud.githubusercontent.com/assets/3827611/19286450/f947a4a6-8fba-11e6-8f70-0cc9c9f4ff3b.png)

**Comment by aerych** [comment]
@theck13 WordPress.com sanitizes iframes (they are generally not allowed in wpcom posts) and converted to short codes that get re-rendered into valid markup.  It kind of avoids the problem in the issue description.  Do you have a self-hosted blog to try with?  If not I can add you to my sandbox.

**Comment by aerych** [comment]
The post I originally tested this with: 
https://aerych.wpsandbox.me/blog/2016/09/29/iframe-test/
