### ISSUE TITLE
Posting/Editing: Respect self-hosted blog's default post format when creating new posts.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4580]
Currently, for self-hosted blogs, the editor defaults to a Standard post format, regardless of what a user has set in Settings > Writing in wp-admin.  It would be nice if we could respect this setting.

**Comment by maxme** [comment]
@aerych I've been using this feature for a while on a wpcom test blog, is this issue self hosted specific?

**Comment by aerych** [comment]
@maxme Sorry. Yes this is specific to self-hosted blogs. I've updated the issue to reflect that.

**Comment by timnolte** [comment]
I'm starting to use Post Formats on my personal site more so I too would like to see this handled.

**Comment by oguzkocer** [comment]
This is currently not possible with the current xml-rpc api. There is no way to get the default post format of a site, unfortunately.

**Comment by timnolte** [comment]
I thought the WordPress app was moving to using the REST API? Is it not possible to keep this open and see if that is something that might be exposed via the REST API?

**Comment by aerych** [comment]
Hi @timnolte 
We currently have no timeline for when the mobile apps will adopt the core REST API.  If/when we do, we will have the opportunity to revisit this as a part of the larger scope of adopting that API.  Thanks for checking. :)
