### ISSUE TITLE
PDF links from the Reader show empty WebView

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4583]
### Expected behavior

When tapping a `.pdf` link in an article while in the Reader, I am expecting the PDF document to open and be readable.
### Actual behavior

Tapping a `.pdf` link in the Reader opens a WebView showing an empty white screen with a toolbar at the top.

![empty webview](https://cloud.githubusercontent.com/assets/1032913/18982554/b0f52562-86ef-11e6-8cc2-03c890a4b3cd.png)
### Steps to reproduce the behavior
- Write a post that has a link to a PDF file
- Open the post in the Reader
- Tap the PDF link
- Empty WebView should have come up
##### Tested on [device], Android [version]

Samsung Galaxy S4, Android v5.0.1, App version 5.8

**Comment by hypest** [comment]
I'd recommend opening those links via the system instead of the WebView.

**Comment by nawabhussain** [comment]
@hypest in a local pdf reader (installed on the phone) ?

**Comment by hypest** [comment]
Hey @nawabhussain , yeah, opening it outside of the WordPress app is what I would have in mind.
