### ISSUE TITLE
NUX: Site URL erased from self-hosted login form when app goes to background

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4584]
### Expected behavior

I often log in to self-hosted sites with these steps:

1. Enter my Username
2. Skip the password field
3. Enter my Site URL
4. Switch to my password manager app
5. Copy my password
6. Switch back to the WordPress app and enter my password in the login form
7. Sign in to the site

I expect my username and site URL to stay in the login form when I leave and reopen the app, so I can just paste in my password and continue on.

### Actual behavior

1. Enter my Username
2. Skip the password field
3. Enter my Site URL
4. Switch to my password manager app
5. Copy my password
6. Switch back to the WordPress app -> My site URL is erased from the login form (the username remains)

This also happens if I enter all of my details (username, password, and site URL) and then switch away and back.

##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-21

**Comment by aforcier** [comment]
I was only able to reproduce this when adding a self-hosted site with the app logged in (and not on first login to the app) - is that right @rachelmcr?

If that's the case, this should be fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/4691.

**Comment by rachelmcr** [comment]
Ah, yep, I can't reproduce this when I'm on the first login screen — only when adding a self-hosted site after the first login. Thanks for catching that detail!
