### ISSUE TITLE
Reader: can't follow blog with 302 temporary redirect

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4589]
In the past it was possible to follow a blog that had a 302 redirect, but it appears to fail now. Try to follow <a href="https://ma.tt">ma.tt</a> in the reader and it will fail, citing 302 as the failure status code.

**Comment by oguzkocer** [comment]
@nbradbury I can't reproduce this issue anymore. Do you mind trying it when you have some time? Thanks!

**Comment by nbradbury** [comment]
@oguzkocer I can't reproduce this anymore, either. I'll close this issue.
