### ISSUE TITLE
No videos in media library when trying to add to a post

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4593]
### Expected behavior

When using the `Select from media library" media option in the post editor, I'd expect to see videos there as well if library has some.
### Actual behavior

Only images are offered via the editor media library.
### Steps to reproduce the behavior
- Make sure a site's Media Library has at least one video. You can add one if needed.
- Go to edit a post
- While in the post body, tap the add-media button
- On the popped up menu, tap the `Select from media library` option
- Notice that no videos are offered
##### Tested on [device], Android [version]

Nexus 5X, Android v7.0, wpandroid v5.8

**Comment by hypest** [comment]
It seems like we could just start using [getMediaFilesForBlog(String blogId)](https://github.com/wordpress-mobile/WordPress-Android/blob/61ba7d2df6d231aa1e657c677c33545c497d4e5a/WordPress/src/main/java/org/wordpress/android/WordPressDB.java#L1634) for the picker.

**Comment by maxme** [comment]
@oguzkocer I guess this is something that should be fixed when we integrate the media store.

**Comment by designsimply** [comment]
I found that I can see videos and an option, but the videos don't have a poster image.

Tested on Pixel, Android 7.1.1, WPAndroid alpha-40.

<img alt="screenshot_20170323-144850" src="https://cloud.githubusercontent.com/assets/1119271/24273143/67a3a156-0fe6-11e7-8eef-e1d09766f99a.png" width="370" />

**Comment by hypest** [comment]
Not an issue anymore. Recent media picker rework has added proper support. Closing.
