### ISSUE TITLE
NUX: Add email confirmation prompt for WordPress.com users

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4600]
### Expected behavior

When a WordPress.com user signs up on the web, they are prompted to confirm their email address at the end of the signup flow:

![screen shot 2016-10-04 at 11 29 36 am](https://cloud.githubusercontent.com/assets/8658164/19071055/134f0136-8a26-11e6-8aec-fcd2b06dbdcd.png)

If the user doesn't confirm their email address at that step, they are blocked from publishing new posts and see a notice/reminder in the Calypso editor:

![screen shot 2016-10-04 at 11 32 14 am](https://cloud.githubusercontent.com/assets/8658164/19071135/73eb5684-8a26-11e6-9773-fde65de68d3c.png)

![screen shot 2016-10-04 at 11 33 13 am](https://cloud.githubusercontent.com/assets/8658164/19071140/76747386-8a26-11e6-84a8-fa60dbe9372a.png)

Currently, those same users are blocked from publishing in the WordPress app as well, but the publish button isn't deactivated — their posts just inexplicably become drafts instead of publishing. (They often have to reach out to support for an explanation of what's happening and for help confirming their email address.)

Instead, we should offer a similar notice/reminder within the app to help these users.
### Steps to reproduce the behavior
1. While logged out of WordPress.com, open https://wordpress.com/start
2. Sign up for a new account but don't confirm your email address
3. In the app, log in to your new account
4. Create a new post and try to publish it

Result: The post becomes a draft.
##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-22

Related issue for iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/6035

**Comment by maxme** [comment]
We can use the `email_verified` field from the account response

**Comment by tonyr59h** [comment]
@maxme, [doesn't look like](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountResponse.java) we're using that field from the response. I'll make the necessary changes and ping you for the review.

**Comment by maxme** [comment]
Yep we need to add it in FluxC / AccountModel (and do a db migration).
