### ISSUE TITLE
Reader: Update no recent posts message

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4611]
Rather than showing the loading box, we should probably show drake.
<img width="729" alt="screen shot 2016-10-06 at 1 40 16 pm" src="https://cloud.githubusercontent.com/assets/1435271/19165714/83b074c8-8bca-11e6-9db6-4c187251fad0.png">

**Comment by 0nko** [comment]
Is this the followed tag screen when no posts are found?

**Comment by aerych** [comment]
Indeed :)
