### ISSUE TITLE
Site Picker: Can't pick re-hidden site while searching

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4614]
This is a bit weird, and definitely an edge case, but here we go:

Start with several of your blogs hidden from the site picker and having your default site selected and its site detail visible. 
- Tap Switch Site
- Tap Search to view all your sites, including those that are hidden. 
- Tap one of the hidden sites. 

The site should be selected and unhidden when you tap it.
- Tap switch site to return to the site list. 
- Select the default site again. 
- Go back to the site list.
- Hide again the site you previously tapped.
- Still on the site list, tap Search.
- Tap the site you just hid to try to select it. 

Notice that nothing happens when you tap the site now. Seems like you should.

**Comment by hypest** [comment]
Fixed with #4634.
