### ISSUE TITLE
Editor: Make "Post Title" placeholder a friendlier call to action

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4615]
Originally requested by @mjangda
"Post Title" is rather cold and mechanical. Maybe we could use a friendlier placeholder here.

**Comment by hoverduck** [comment]
Corresponding iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/6051

**Comment by catehstn** [comment]
@mattmiklic do you have a suggestion?

**Comment by mattmiklic** [comment]
Discussed this a bit and we've decided to match Calypso's language everywhere it makes sense; which would mean "Title" as the placeholder for this field. We may revisit the idea of a friendlier/more engaging label if/when we revisit the posting experience, maybe post-Aztec.

**Comment by theck13** [comment]
The hint text for the title field in the editor is now "Title" for Aztec as of https://github.com/wordpress-mobile/WordPress-Android/pull/5040.
