### ISSUE TITLE
Editor: Issue with backspace with bluetooth keyboard

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4619]
Originally reported by @rachelmcr 

> A user reported an issue in the Android app v. 5.6, using a Galaxy Tab S2 (SM-T815) with Android 6.0.1 and a bluetooth keyboard. When they are leaving comments on other blogs or replying to comments on their own blog, and they hit the backspace key, it goes back two spaces instead of just one. This is a consistent problem but doesn’t happen with the same keyboard elsewhere in the app (e.g. the editor) or in other apps.

Needs confirmation.

**Comment by khaykov** [comment]
Same issue - #4737

**Comment by khaykov** [comment]
fixed in #4738
