### ISSUE TITLE
Editor: Empty draft after opening editor

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4621]
@rachelmcr reports: 

> A user reported that they were working on a draft (with lots of text and photos) for a number of days. They then opened it in the editor to keep working on it and discovered that the draft was empty.
> 
> I checked the logs that came in with the issue, and I noticed that there is a connection error near the beginning of the log: 08 - java.net.UnknownHostException: Unable to resolve host "public-api.wordpress.com": No address associated with hostname
> 
> Could that connection error have caused the content loss in the editor? And if so, can we prevent that from happening? I have seen some reports of similar issues in app reviews and when it happens with a local draft we can’t recover the content, so it’s a pretty serious issue.

Opening this issue to track possible/related occurrences

**Comment by hoverduck** [comment]
The content loss problems were (hopefully) fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/4927, so I'm closing this one.  We'll re-open or write a new issue if the problem resurfaces.
