### ISSUE TITLE
Editor: Increase font size of text in editor

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4622]
It would be nice if the font size of the editor could be adjusted for accessibility sake.

**Comment by aforcier** [comment]
After some confirmation and a new discovery, I'm happy to report that there are two Android system features that help with this:

1. Under `Settings` > `Accessibility` > `Font Size`, you can change the font size for the whole system UI, which will also alter the editor's font size
2. Also under `Settings` > `Accessibility`, there is a `Magnification gesture` option, which when enabled allows you to zoom in by triple-tapping one spot on the screen. This also works with the editor, and you can type while zoomed in for a very large font size

**Comment by theck13** [comment]
Using the system-wide settings like `Font Size` and `Magnification Gesture` is better than creating an editor-specific setting in the app.
