### ISSUE TITLE
Posting: Local changes warning misleading

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4623]
Member report shared by Chrissie P

> When I make local changes on the Android app I get a message that “this post has local changes which haven’t been published” with the option to “Publish” or “Revert”.

> “Publish” is misleading here. The post in question is a draft. I don’t want it published yet. I suggest this be escalated as bug.
> 
> But as it happens, nothing happens. When I hit the “Publish” button I get a brief spinning circle with no message to indicate if the action has succeeded it failed.
> 
> However when I switch back to the Posts screen the post is marked as having “local changes”. We loop round several times accepting the offer to “Publish” but although the spinning wheel takes longer to go away each time, the changes still remain local.
> 
> The same thing happens if I use the “revert” button. I still get the report that there are “local changes.

Screencast at http://ChBQNAP.myqnapcloud.com:8080/share.cgi?ssid=0OAnMJd

**Comment by maxme** [comment]
I had a look at the original ticket, looks like the user gets an error when he tries to update the draft (Publish actually change the post status from `draft` to `published`):

```
An error occurred while uploading the Post HTTP status code: 404 was returned. Not Found
```

This looks like a self hosted issue to me. Closing this ticket.

Note: Android 6.0, wpandroid 5.7
