### ISSUE TITLE
Reader: Can't share posts to some services

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4635]
### Expected behavior

I expect that when I view a single post in the Reader, I can tap the share icon to share it to any service that appears there.
### Actual behavior

If I try to share the post to certain services (such as Pinterest) I get the error "Please use a valid Web address." (A similar error has been reported for users with WhatsApp, although I haven't confirmed that error yet.)

I am guessing this is because the post's URL is prefixed by the post title, instead of being the URL on its own. If I share the post from the Blog Posts list, instead of the Reader, I can share it without any error.
### Steps to reproduce the behavior
1. Open the Reader in the app
2. Open the post detail for a post
3. Tap the Share icon in the top right
4. Select a sharing service such as Pinterest

Result: You see the error "Please use a valid Web address."

Alternate steps that work:
1. Open the My Sites tab in the app
2. Open the Blog Posts section
3. Tap "View" under a blog post
4. Tap the Share icon in the top right
5. Select a sharing service such as Pinterest

Result: The post is shared as expected.
##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-23

Reported on WPAndroid 6.0.1 in 135352-h

**Comment by maxme** [comment]
> Steps to reproduce the behavior
> 
>     Open the Reader in the app
>     Open the post detail for a post
>     Tap the Share icon in the top right
>     Select a sharing service such as Pinterest

@rachelmcr I can't reply using Pinterest, I'm not sure if anything changed on our side (or in the Pinterest app) since you reported that one. The code we use to share to other services looks correct (we share the shortened URL).

**Comment by rachelmcr** [comment]
I tested again and can't reproduce the issue anymore, so it looks like something has changed! Closing the issue.
