### ISSUE TITLE
Notifications: "Like" should not be an option for comments on Jetpack sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4642]
### Expected behavior

Jetpack does not currently support Comment Likes, so it doesn't make sense for "Like" to be an action on comment notifications for Jetpack sites.

### Actual behavior

In comment notifications (in the notifications tab and push notifications) there is an option to "Like" a comment on a Jetpack site.

Push notification:

![2016-10-12 13 54 47](https://cloud.githubusercontent.com/assets/8658164/19313047/009b342a-908d-11e6-8c55-1068a574ab74.png)

Notifications tab:

![2016-10-12 13 54 55](https://cloud.githubusercontent.com/assets/8658164/19313034/f269fbc0-908c-11e6-93db-66b22a41edd6.png)

In contrast, the Comments section for the same Jetpack site does not have the "Like" option:

![2016-10-12 13 56 02](https://cloud.githubusercontent.com/assets/8658164/19313026/e87b99ac-908c-11e6-9364-6213d9a1066d.png)

### Steps to reproduce the behavior

1. On a Jetpack site, make sure the site is set to approve incoming comments
2. From another account, make a comment on the site to trigger a notification
3. Check the notification and confirm it shows the "Like" action

##### Reported by a beta tester [here](https://make.wordpress.org/mobile/2016/10/04/call-for-testing-wordpress-for-android-6-0/#comment-19198)

**Comment by mzorz** [comment]
Ok, been investigating this. With the enhancements we made in #4590 we could most probably have the Note payload and look into it to see if the Note is "likeable" by this user, and so we can safely decide whether we need to offer/hide the `Like` button on the Notification layout itself.
If by any chance we can't figure this out by the time we need to draw the notification layout, I'm only offering the `Reply` action as it's the only safe bet we have.
