### ISSUE TITLE
Editor: Uploading multiple images/videos does not finish

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#4664]
### Expected behavior

All files get uploaded.
### Actual behavior

The uploading starts and then grinds to a halt at various levels of progress.
### Steps to reproduce the behavior
1. Create New Post
2. Insert multiple large photos or videos via Add Media > Select using multi-picker
3. Pictures begin to upload to post
4. Some are successful (varies how many) while others get “stuck” with a non-moving progress bar
##### Tested on OnePlus One, Android 6.0.1, WP alpha-24

Original report: https://mobilerequests.wordpress.com/2016/07/01/android-trouble-uploading-multiple-images

**Comment by khaykov** [comment]
Looks like it might related to #3445

**Comment by mzorz** [comment]
Tested on both Visual and Beta (Aztec) editors on current alpha - not a problem anymore since #5766 and #5780 were meged
