### ISSUE TITLE
Notifications Refresh Design

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4665]
Android has a [ton of stuff we can do with notifications](https://material.google.com/patterns/notifications.html#notifications-behavior) that we're not doing yet. Let's figure out what those are and what we'd like to do!

Ideas:
- Allow users to reply to notifications [within the notification itself](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#direct)
- Right now all [quick actions open the app](https://github.com/wordpress-mobile/WordPress-Android/issues/4602). Let's do it more like Gmail where it doesn't open the app.
- We can [create custom views](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#CustomNotification) now in notifications. Example [here](https://cloudup.com/iPTgwx2JDqE) (look at the Screenshot captured notification)
- We can look into how the notifications tab overall looks (the list, details, etc).

Also, here are web notifications so that we can keep them consistent https://cloudup.com/cmHKG-EptZE

cc @daniloercoli and @mzorz

**Comment by kwonye** [comment]
iOS here: https://github.com/wordpress-mobile/WordPress-iOS/issues/6093

**Comment by mzorz** [comment]
Just FYI these two are being tracked and tackled:
> - Right now all quick actions open the app. Let's do it more like Gmail where it doesn't open the app.

See #4659 which I'm working on these days actually

> - Allow users to reply to notifications within the notification itself

See #4401 - planning to get on it after finishing the above

As for these other ones:

> - We can create custom views now in notifications. Example here (look at the Screenshot captured notification)
> - We can look into how the notifications tab overall looks (the list, details, etc).

I'm sure these are a subject of exploration for design!

**Comment by mzorz** [comment]
update: issued PR #4667  for issue  #4659

**Comment by mzorz** [comment]
update: issued PR #4673 for issue #4401

**Comment by mzorz** [comment]
given we're not going for a full redesign, let's check usability issues with current design in other languages like this issue here #3481

**Comment by mzorz** [comment]
Closing as the Notifications Refresh project has reached to an end
