### ISSUE TITLE
Capital letters in account email causing Gravatar validation error

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4666]
### Expected behavior

I expect to be able to create a new account and upload a Gravatar for that account.
### Actual behavior

I am able to create a new account starting with a capital letter (e.g. `Example@example.com`), and when I then try to upload a Gravatar I get the error `Error updating your Gravatar`. The activity log shows this error:

```
Network call unsuccessful trying to upload Gravatar: {
"errors": {
"error": "Invalid account address"
}
}
```

I can't fix the capital letter through the app or the web, since changing from a capital letter to a lowercase letter isn't seen as a change of address. Support staff has to fix the email address to all lowercase letters, and then the Gravatar can be uploaded as expected.
### Steps to reproduce the behavior
1. In the app, create a new account with a capital letter at the beginning of the email address (e.g. `Example@example.com`)
2. On the Me tab, tap the Gravatar icon
3. Select a photo, make any edits (crop/zoom), and tap the checkmark to use it
4. Result: The Gravatar isn't uploaded and there is an error message `Error updating your Gravatar`
5. Go to Account Settings
6. Tap on "Email address"
7. Change the capital letter in the email address to a lowercase letter and tap OK
8. Result: The change is not saved (the email address with the capital letter remains)
9. Change the account's email address to all lowercase from the network admin
10. Open the app again and try to upload a Gravatar
11. Result: The Gravatar is uploaded as expected.
#### Screenshot

![screenshot_20161019-111933](https://cloud.githubusercontent.com/assets/8658164/19515436/555c6dbe-95ef-11e6-8e87-9e71acacb701.png)

**Comment by khaykov** [comment]
I opened a PR (#4731) that forces lowercase on user email during registration, but after some thought and discussions looks like it might be a better idea to fix this issue on Gravatar side instead. I'm going to close the PR for now, but we can always reopen it later if necessary.

**Comment by khaykov** [comment]
Fixed on Gravatar side, so should be working now!
