### ISSUE TITLE
Notification title says "New comment" but PN is for linked post

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4668]
### Expected behavior

The notification title to be something like "Linked to your post".
### Actual behavior

Notification title is "New comment". See screenshot:
![screenshot_2016-10-19-16-03-40](https://cloud.githubusercontent.com/assets/1032913/19519912/9412ce28-9616-11e6-8137-a27dd87113cb.png)
### Steps to reproduce the behavior
- Copy the public link to a post from a site you own and paste it to another post of yours. Update the post to save the change.
- Notification should arrive to your mobile
##### Tested on [device], Android [version]

Samsung Galaxy S4, Android v5.0.1

**Comment by daniloercoli** [comment]
Actually this is the correct behavior in case of Pingbacks.
A pingback is a type of comment that’s created when you link to another blog post where pingbacks are enabled. That's why you're receiving the PN with "New comment" in the title.
As you've already suggested we could improve the experience, by wording the title in a different way, but in the end the new note is a comment.

Also, consider that we need to change the server side code, in order to change the title.

**Comment by hypest** [comment]
Aha, I see what you mean @daniloercoli , thanks for the insight!

It is still an issue in the "... linked to your post" case though since nobody actually _commented_ anywhere. Not dramatic, but it does throw the user a bit off.

**Comment by daniloercoli** [comment]
> "... linked to your post" 

I think the text is part of the comment that appears on your site, below the original post. That's because the PN has it in the body. 
We can change the title of the PN to "New Pingback", but it in the end it's a comment on your site.

**Comment by hypest** [comment]
👍  for the "New Pingback" suggestion if that's possible!

**Comment by daniloercoli** [comment]
Hey @drw158 - Could you please jump in this convo and give us some direction about the correct wording?
I would expect a seamless experience with the web version of notifications. So we should change the wording on both side or leave it as they are now.

@kwonye @mzorz @jleandroperez

**Comment by mzorz** [comment]
I like "New Pingback" as a title for this specific case too, and I agree it'd be better to have the same wording on all platforms. Just checked the code server side and it seems we'd be able to do this kind of granular differentiation among "comments" and "comment_pingback".

**Comment by drw158** [comment]
I don't think we use the terms "trackback" or "pingback" in any other notification, so this would be introducing something users don't know about. I don't remember the "New Comment" text on Android. I don't think we have a title like that on the other platforms. I'll take a deeper look later.

**Comment by drw158** [comment]
We could:

- Instead of New Comment, we could replace that with "WordPress". I noticed several apps do this. It would change all PNs though.
- Say "New Link" for this case. I believe we only refer to pingbacks and trackbacks as "links" in notifications.

**Comment by daniloercoli** [comment]
Addressed server side.
