### ISSUE TITLE
Correctly guess when the user wants to sign in to a self-hosted site

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4684]
There's (at most) one user in the world that has the username "admin" or "administrator" or "user" in WordPress.com. So let's be smart and create a dictionary of usernames that automatically trigger the self-hosted sign in form.

(thanks to @aforcier for the idea) cc @aerych

**Comment by kwonye** [comment]
We'll want to keep the list in sync with iOS

**Comment by aforcier** [comment]
Looks like `user` is a no-go. The list I'll be going with is:

```
www
web
root
admin
main
invite
administrator
*wordpress*
```

Thanks @rachelmcr for the research help 😄
