### ISSUE TITLE
Support filtering posts by status

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#4693]
Allow the user to filter the post list by status (Published / Drafts / Scheduled / Trashed).

This will probably be implemented sometime after [FluxC integration](https://github.com/wordpress-mobile/WordPress-Android/issues/4394). Support for requesting posts by status from FluxC is tracked by https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/145.

**Comment by rachelmcr** [comment]
This was requested in a recent app review:

> App done well I would say. The only thing I miss is the distinction between published articles and drafts. All put together and, moreover, in date order creates a mess, at least to me that a lot with working drafts. Make 2 separate pages to publications and drafts would be a big help!

**Comment by rachelmcr** [comment]
This came up in a recent app review (2 stars):

>Uncomfortable. Upon entering the input section drafts are mixed with publications.

**Comment by rachelmcr** [comment]
A recent app review (5 stars) mentioned recovering deleted posts — a trash section in the app would help with that:

> It is too easy to fat first get and delete a post by mistake. There needs to be a way to recover deleted posts.

**Comment by rachelmcr** [comment]
This came up in another app review (3 stars):

> I think the article tab is not structured enough. I would like to be able to separate published, scheduled and drafted articles.

**Comment by sarahblackstock** [comment]
From an app review (4 stars): 

> App is great aside from one thing. Android app has no means to separate posted, scheduled, and draft posts. This feature is already in the IOS version. Hopefully that feature is coming soon.

**Comment by sarahblackstock** [comment]
another request for this: 

>It's pretty inconvenient that in my post section I can't switch between published, drafts and scheduled post. 

internal ref: #194551-h

**Comment by sarahblackstock** [comment]
From an app review (3 stars): 
> I use this app rather than using my laptop, easier for on the go, but on Android I cant filter any of my blog posts, so they all appear, published/scheduled/draft, really confusing! Won't be using it for writing posts till at least that's sorted, looks like laptop will have to come out!!

**Comment by sarahblackstock** [comment]
Request in app support: 

> Need an ability to filter on that screen between posts that are either Scheduled, Draft, Published or Trashed. 

internal ref: #217830-h

**Comment by sarahblackstock** [comment]
Feedback in app support (translated from French): 

>In iOS we have the draft articles and published but on Android all is mixed and hard to manage.

#230698-h

**Comment by SiobhyB** [comment]
This came up in 253443-h too, I had to navigate the user to a browser so that they could access their Trash.

**Comment by SiobhyB** [comment]
Another request for this in 254717-h.

**Comment by SiobhyB** [comment]
This came up again in 255564-h. The user would have liked the option to filter for their site's drafts.

**Comment by SiobhyB** [comment]
Another +1 from someone in 255818-h who would like to filter posts by draft.

**Comment by sarahblackstock** [comment]
Another request for this in support.
internal ref: #256545-h

**Comment by sarahblackstock** [comment]
Request for this in support. 
internal ref: #256584-h

**Comment by SiobhyB** [comment]
Another request in 257148-h for the ability to access their site's trash from the app.

**Comment by SiobhyB** [comment]
Came up in the recent round-up of app reviews here: p77Llu-9N5-p2

**Comment by SiobhyB** [comment]
Again in 261027-h.

**Comment by sarahblackstock** [comment]
Request in support to more easily filter/search posts since user has 100+ posts, resulting in a lot of scrolling.

internal ref: #264195-h

**Comment by oguzkocer** [comment]
See this comment: https://github.com/wordpress-mobile/WordPress-Android/issues/62#issuecomment-370587518

**Comment by SiobhyB** [comment]
From a five star review:

> Thank you for making this app. But the posts should be in categories (published, drafts, etc)

**Comment by KokkieH** [comment]
Another request [via Twitter](https://twitter.com/geek_astronaut/status/1027401346784419840)

**Comment by SiobhyB** [comment]
From a three star review:

> They are adding more features, but it's still impossible to filter my posts to see only the drafts...

**Comment by SiobhyB** [comment]
Another request in 1541569-z.

**Comment by SiobhyB** [comment]
A one star review:

> Can't sort out draft and published post., Page already has this feature, but post don't.

**Comment by oguzkocer** [comment]
This issue is now a part of a project starting as of today, so it shouldn't be too long before it's implemented.

**Comment by malinajirka** [comment]
Fixed in #9233 - will be released in the first iteration of [Post Filters project](https://github.com/orgs/wordpress-mobile/projects/23)
