### ISSUE TITLE
Reader: In refresh full-post, drop mystery man from "More on wpcom" RP block

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#4702]
### Expected behavior
For mystery man to not be displayed just like in the refreshed full-post header.

### Actual behavior
Mystery man is being displayed:

![screenshot 2016-10-26 13 38 42](https://cloud.githubusercontent.com/assets/4924246/19744292/c59803d0-9b81-11e6-87ff-1a3ad83a7d71.png)

### Steps to reproduce the behavior
1. Visit any post in the new full-post view.
2. Find a related post under the "More on wpcom" block that doesn't have a gravatar.

##### Tested on [device], Android [version]
Nexus 5 (Android Studio emulator)

/cc @nbradbury

**Comment by jancavan** [comment]
@nbradbury Sorry, but as mentioned in this issue: https://github.com/Automattic/wp-calypso/issues/8656, it should be gravatar > blavatar > feed icon, then if we can't find any of those, that's when we don't display anything.

**Comment by nbradbury** [comment]
This is partially addressed in #4703, which hides the avatar if the user doesn't have one but doesn't show a blavatar (since the response currently doesn't include one).
