### ISSUE TITLE
Me: small typo on the "Open source licenses" page

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#4714]
Steps to reproduce:
1. Go to the Profile &gt; "App Settings" &gt; "Open source licenses" page.
2. Scroll down to the "Notices for library: photoview" section.

<strong>Result:</strong> It appears there's an extra slash where there shouldn't be one.

<img src="https://cldup.com/rIb0nnov83.png" width="300" />

**Comment by maxme** [comment]
This file needs a refresh, we should make sure to remove licenses from libraries we don't use anymore.
