### ISSUE TITLE
Posting: images appear as html in local drafts

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#4716]
After closing and reopening a local draft, images appear as html and I expecting that they would still appear as images.

Steps to reproduce:
1. Start a new post using WPAndroid 6.1-rc-1
2. Add a title
3. Add an image to the body of the post
4. Tap back until you see the list of posts
5. Notice the new post is labeled "Local draft"
6. Tap on the new post that was just created

<strong>Result:</strong> The image appears as html, but I expected it to show up as an image.

<img src="https://cloud.githubusercontent.com/assets/1119271/19785326/3058eac0-9c56-11e6-860a-3272ab01ad12.png" width="200" align="left" /> <img src="https://cloud.githubusercontent.com/assets/1119271/19785327/305d6f00-9c56-11e6-91a5-48bddd21f1f3.png" width="200" align="left"/> <img src="https://cloud.githubusercontent.com/assets/1119271/19785328/30632594-9c56-11e6-80a8-db32c9df2371.png" width="200" />
<sup>New post screen on WPAndroid 6.1-rc-1 on a Samsung Galaxy Tab4 (SM-T330NU) Android 5.1.1</sup>

**Comment by aforcier** [comment]
@designsimply, it looks like you're using the legacy editor, which (unfortunately) has always had this limitation when adding images from the site's media library.

However, this flow should work when using the (newer) visual editor (Me -> App Settings -> Show visual editor).

**Comment by khaykov** [comment]
Closing this issue as it can resolved by using new editor.
