### ISSUE TITLE
Notifications: comment reply text persists to new comments (field should be empty)

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-Android#4724]
#### Expected behavior

After commenting on a post from Notifications, then opening up a new comment, the comment reply field should be empty.
#### Actual behavior

The previous comment I made persists in all comment fields, even other posts or blogs.
#### Steps to reproduce the behavior
1. Open Android app
2. Click Notifications menu item
3. Click on a comment on on of your posts
4. Type a reply and click SEND action
5. Comment is added
6. Now, navigate to another comment, and see your reply text from step 4 is pre-filled in the form — instead of an empty form field
#### Screenshots

<img src="https://cloud.githubusercontent.com/assets/66797/19813936/d1cca0e6-9cf0-11e6-8b10-7b92d66f341a.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/19813937/d1cd01a8-9cf0-11e6-99a8-9abf7f5bd819.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/19813938/d1ce6cfa-9cf0-11e6-982d-2c8b7bb47a54.png" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/19813939/d1ced456-9cf0-11e6-89d6-5e992e78662b.png" width="480" />
#### Tested on [device], Android [version]

Nexus 6P, Android version 7.0, WordPress Android app version alpha-25

Reference: https://make.wordpress.org/mobile/2016/10/27/call-for-testing-wordpress-for-android-6-1/

**Comment by maxme** [comment]
We have to update the PersistedText id using comment id and clear the field on publish (this was working some times ago, I'm not sure what happened) - I'll have a look at this.

**Comment by lancewillett** [comment]
Confirmed fixed in alpha-27 build. Nice! Thank you.

<img src="https://cloud.githubusercontent.com/assets/66797/20014733/74d1ed30-a275-11e6-92e5-db171bd23c24.png" width="480" />
