### ISSUE TITLE
Notifications: horizontal notification detail navigation (swipe)

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4727]
Right now the mobile web has up/down arrows to go the the next/previous notification without having to go back to the notifications list. We're going to be adding that to the mobile apps.

![img_0561](https://cloud.githubusercontent.com/assets/1158819/19863843/0b51177a-9f53-11e6-932e-021d48f1e8a0.png)

(note that Apple Mail has something similar) 

![img_0768](https://cloud.githubusercontent.com/assets/1158819/19863878/2e86e472-9f53-11e6-96db-3178a75fd308.PNG)

**Comment by mzorz** [comment]
Note: remember adding analytics to check usage of swipe vs arrows

**Comment by mzorz** [comment]
ToDo:
- [ ] add ViewPager to support swipe left/right gesture
- [ ] add left-right arrows where the EDIT button is currently (top-right corner of the screen, on the action bar)
- [ ] move EDIT button to the item actions below the comment/notification body (along with SPAM/TRASH, etc.)
- [ ] add analytics tracking to check usage of swipe vs arrows
