### ISSUE TITLE
Denying access to self-hosted WP-Site. 

### ISSUE THREAD

**Issue by manni65929** [wordpress-mobile/WordPress-Android#4735]
### Expected behavior
Denies access to other author's media gallerys. Prohibits use of other's media

### Actual behavior
Permits access to and use of media in other author's media libaries even though permission has been restricted for the internet site at www.___.com

### Steps to reproduce the behavior
None, no error message. 

##### Tested on [device], Android [version]
Samsung Galaxy Note II, Android 4.4.2.

##### Detailed description

I've setup a self-hosted multi-author website that would deny authors to view or use other author's media (photos, video, sounds). This is done via the plugin WPFront User Role Pro, because WP 4.6.1 appears not to have a similar limitation for the author roles. Using the WP App in my smart phone, I find that the restrictions are circumvented and the authors can use any media of other author's libraries. I only know this of the Android-Version so far. 

Is there a way to prevent the Wordpress APPs (regardless of OS or version) from accessing the site at all? 

Thanks for the help

**Comment by rachelmcr** [comment]
The WordPress app communicates with your site using [XML-RPC](https://codex.wordpress.org/XML-RPC_Support). The [XML-RPC WordPress API](https://codex.wordpress.org/XML-RPC_WordPress_API) includes information such as whether a user has permission to access the media library on the site. If the plugin you're using does not restrict that permission, any client communicating with your site via XML-RPC will also circumvent that plugin's behavior.

If you'd like to prevent the app (and other clients) from accessing the site, you can disable XML-RPC.
