### ISSUE TITLE
Reader: Blavatars missing from posts in Reader posts list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4741]
### Expected behavior

I expect the same blavatar to appear on the post card (top left) in the Reader posts list and on the single post view.

### Actual behavior

I see a blavatar and author avatar on the single post view, but no blavatar on the same post in the post list.

Looking through my Followed Sites list in the Reader, it looks like most blavatars are not showing there. (I do see them for an RSS feed I follow and en.blog.wordpress.com.)

cc @nbradbury 

#### Screenshots

Reader post list:

![2016-11-02 17 17 29](https://cloud.githubusercontent.com/assets/8658164/19939774/4078cb52-a122-11e6-8c9f-9ef83884b251.png)

Single post view:

![2016-11-02 17 17 35](https://cloud.githubusercontent.com/assets/8658164/19939779/42f723c4-a122-11e6-9e20-d7bd6bca94c0.png)

##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-26

**Comment by nbradbury** [comment]
This was resolved as part of the reader stream refresh (#4776)
