### ISSUE TITLE
Change logo to WordPress.com when logging in to WordPress.com

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4742]
To match https://github.com/wordpress-mobile/WordPress-iOS/pull/6142

We'll switch the logo based on what log in screen the user is currently in

**Comment by hypest** [comment]
Reopening this as currently, the app does show the logotype, but shouldn't do it on the initial login screen. The .com logotype should appear only after the app has detected that this is indeed a .com login.

@mattmiklic , can you share more info on the desired flow? Thanks!

**Comment by mattmiklic** [comment]
In short: the first screen of the app can accept logins for any kind of WordPress blog; self-hosted or WordPress.com. We don't want to give a mistaken impression as to what kinds of accounts are supported. So the first screen should include the (W) mark alone. After entering a WordPress.com username or email address, the next screen should show the WordPress.com logotype. After entering a username or email address not associated with a WordPress.com account, we should show the existing self-hosted login screen. A visual representation of the flow is below.

<img width="737" alt="screen shot 2017-01-10 at 12 17 06 pm" src="https://cloud.githubusercontent.com/assets/1396552/21827386/5e4f8432-d759-11e6-82e6-ae5771f5d947.png">

Let me know if you have any other questions, happy to clarify!

**Comment by hypest** [comment]
Fixed with #5353
