### ISSUE TITLE
Show quick actions when the device is locked

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#4749]
Quick Actions are not shown on the lock screen. (Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/4736).

When you unlock the device notifications are recreated and action buttons added. Instead I checked the GMail app and it seems to have quick actions even on the lock screen. If one of those quick action buttons are clicked the device shows the numeric keyboard to unlock it....

**Comment by mzorz** [comment]
Closing and opening #4755
