### ISSUE TITLE
FAQ is empty for non-English languages

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4758]
If the device language is set to a non-English language, the FAQ just says something like "No questions found". We should either translate our FAQ and upload it to Helpshift OR at least show the English version.

/cc @rachelmcr

**Comment by rachelmcr** [comment]
It looks like Helpshift should fallback to English as the default language for our FAQs (the default value for `enableDefaultFallbackLanguage` is true):

https://developers.helpshift.com/android/sdk-configuration/#enableDefaultFallbackLanguage

So I'm not sure why it isn't, but perhaps we can resolve it by explicitly setting that.

**Comment by oguzkocer** [comment]
Thanks for looking it up @rachelmcr! You beat me to it :)

Looks like that fixes the issue, sending a PR in a bit.

**Comment by oguzkocer** [comment]
Closed in #4759.
