### ISSUE TITLE
Notifications + Pinghub

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#4761]
Implement Pinghub WebSocket client, to receive updates, regardless of the Push Notifications setting.

 ### Details:
- [ ] Maybe create `Automattic/pinghub-android` repository.
- [ ] Keep synching notifications right after launch / login, and introduce updates driven by Pinghub.
- [ ] Make PingHub working fine together with Push Notification payload.

### Verify:
- [ ] Verify that Notification Actions (Edit Comment / Reply) result in a Pinghub update message
- [ ] Verify that marking a Note as Read (in another device) results in a Pinghub update message
- [ ] Verify that destructive actions result in "notification deleted" notification

**Comment by maxme** [comment]
How PingHub will benefits our users? GCM does the same job already, I don't really see the point of adding more complexity to the app.

**Comment by daniloercoli** [comment]
We won't replace GCM with PingHub for PNs.

Instead we want use it to keep the clients in synch with the server and use as less as possible REST calls.

I know we can use GCM for almost the same things we want to achieve by using PingHub, but there are few key advantages with PingHub:

- We will have one single code on the server that updates clients, regardless if they're Android, Desktop, or iOS. No more double implementations.

- Communication is 2-ways. Clients can write messages on the channel and the server acts in response of them. Basically we can update, mark it as seen, delete a note from the client, and send the changes on the server by using a pinghub message.

- We can reach users with PNs disabled.

- No more payload limit.

cc @jleandroperez @dmsnell 
and @mzorz  (but probably you're already seen this).

**Comment by maxme** [comment]
So, we're going to replace all the REST calls for notifications with PingHub?

**Comment by mzorz** [comment]
initially not all, but hopefully many :)

**Comment by dmsnell** [comment]
What is GCN?

**Comment by mzorz** [comment]
Google Cloud Messaging (now "Firebase")

**Comment by daniloercoli** [comment]
> So, we're going to replace all the REST calls for notifications with PingHub?

Almost all the REST calls could be easily migrated to PingHub. (When we'll be ready to accept and process incoming messages on the server).
I would say, the initial notes refresh, and pull to refresh, can use the REST API, at least in the first version of PingHub integration. If everything works OK we can move all calls to PH in a second sprint.

**Comment by maxme** [comment]
Ok that would make sense to only have one way to communicate with the notification "server", my fear is having an extra complicated implementation for such a simple screen.

**Comment by mzorz** [comment]
Closing as the Notifications Refresh project has reached to an end
