### ISSUE TITLE
Sign in: add message from helpshift in the "login failed" screen

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4762]
### Expected behavior

When you enter an invalid username/password 3 times, the screen shown should provide a direct help/hint for your problem. From checking the Helpshift queue it became apparent that most of the issues were resolved when users followed the actions suggested in this text:

```

If you’d like to sign into your self-hosted WordPress site using the app, please tap on the ‘Add Self-Hosted Site’ link at the bottom of the login screen.

This will add another field to the form where you will enter your Site URL.

```

So we'd like to add this text directly in that screen, so users can help themselves get in the app.

### Actual behavior

Right now when you enter an invalid username/password 3 times, a screen is presented and 2 main options are shown:
a) Lost your password?
b) Contact us

![screenshot_20161109-103137](https://cloud.githubusercontent.com/assets/6597771/20151196/1c0ddcac-a66e-11e6-8afc-1235837d0476.png)

When you tap on Contact Us, you get a Helpshift message:
```

If you’d like to sign into your self-hosted WordPress site using the app, please tap on the ‘Add Self-Hosted Site’ link at the bottom of the login screen.

This will add another field to the form where you will enter your Site URL.

```

So users have to basically try logging in and then they have to tap on  "Contact us" before getting any further help.

### Steps to reproduce the behavior
a) try an invalid username/password combination 3 times
b) check the results

**Comment by hypest** [comment]
Closing as no longer valid with the new Login flows.
