### ISSUE TITLE
Killing app while editor is open leaves an (Untitled) draft

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4765]
### Steps to reproduce the behavior
1) Open a new post
2) Kill the app from the overview screen
3) Open the app back up and navigate to the Blog Posts page
4) Observe the (Untitled) local draft

![android-untitled](https://cloud.githubusercontent.com/assets/7233112/20156260/a09655ec-a69d-11e6-976b-3c895b328eee.gif)

**Comment by catehstn** [comment]
@hoverduck same as #4846 - can you try and repro? This was hopefully resolved in #4927.

**Comment by hoverduck** [comment]
Closing, unable to reproduce
