### ISSUE TITLE
Leaving the editor removes Featured Image from post

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4766]
### Steps to reproduce the behavior
1) Open the editor for a new post, setting the title and body
2) Open post settings and set a featured image.
3) Back out of the editor
4) Navigate to the Blog Posts list and edit the post
5) Open post settings and confirm the featured image is still set
6) Publish the post
7) Note that your post no longer has a featured image

![android-no-featured-image](https://cloud.githubusercontent.com/assets/7233112/20158398/06c65fec-a6a8-11e6-9062-ede75e25a534.gif)

##### Tested on Nexus 6P, Android 7.1.1 (shown above on an Android 4.4 emulator)

**Comment by aforcier** [comment]
I'm re-opening this and attaching the `fluxc-integration` label as this may require some FluxC-side changes (once we have `MediaStore` integrated and can test this).

**Comment by aforcier** [comment]
This can be closed once https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/308 has been tested and merged.

**Comment by oguzkocer** [comment]
As mentioned by @aforcier, this issue has been fixed. I just tested it just in case and everything is working well.
