### ISSUE TITLE
HTTP Auth dialog is shown when we should show a specific error message.

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4767]
In `feature/fluxc-integration`, when the xmlrpc endpoints return a 403 ( on `listMethods`), we show a HTTP Auth dialog to the user when we should show a "Access to your XMLRPC endpoint is forbidden, you should check your http server config or contact your host".

We should also redirect the user to the right FAQ page on that screen.

**Comment by aforcier** [comment]
The backend changes needed for this have been implemented in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/224. Instead of the HTTP Auth error, discovery returns a `XMLRPC_FORBIDDEN` error (we'll just need to handle that case appropriately).
