### ISSUE TITLE
Notification edit button moved to below comment

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4768]
To make way for the up/down arrows in the nav bar, we'll be moving the edit button as shown in this mockup:

iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/6140

![d4be49ca-a697-11e6-8b39-476219022ffd-2](https://cloud.githubusercontent.com/assets/1158819/20197759/f4afb944-a755-11e6-8462-ffd2c4e1b91e.png)

**Comment by mzorz** [comment]
investigating the `like` issue on this issue here #4818
