### ISSUE TITLE
Sign in: Auto-check username after incorrect username/password error to suggest URL field

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#4769]
When user fails to enter valid credentials more than once for a given username we should kick off a `IS_AVAILABLE_USERNAME` action (from `AccountStore`) and conditionally show the URL field if the username isn't recognized.

**Comment by aerych** [comment]
This is one we should probably defer for now. Its possible we'll invalidate this one as part of the login refresh.   I'm also a little concerned this might accidentally complicate the experience while trying to be helpful.   It would be nice if we didn't have to assume what the user was trying to do.

**Comment by hypest** [comment]
Closing as no longer valid with the new Login flows.
