### ISSUE TITLE
Sign in: Identify and handle failed logins to self-hosted site without RSD information

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#4770]
Note: Identifying the problem should be handled by FluxC.

When a user attempts to sign into a valid/existing domain but we're unable to locate the `xmlrpc.php` file and RSD is not available we should link the user to [this support document]() and show a message indicating the problem.

As a bonus, if we can definitively identify that the site is powered by WordPress (or not) we should expose that to the user.

**Comment by hypest** [comment]
Currently, the app receives the `NO_SITE_ERROR` error when both xmlrpc.php and RSD are missing. To be able to differentiate the case and point to a relevant help/FAQ section, FluxC discovery will need to identify that WP is present nevertheless. I've [opened a ticket](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/603) in FluxC for this.
