### ISSUE TITLE
Sign in: Add specific message when users fail to login with valid username/email but wrong password

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#4771]
We currently only offer one error code to handle username -or- password incorrect issues. Since we can determine if the username is recognized or not we should let the user know just the password is incorrect in certain circumstances.

**Comment by hypest** [comment]
Can't be sure if this is the reason we do it like this but generally, login forms do not differentiate the messages on purpose, to avoid leaking information by confirming the username, email or password separately.

**Comment by maxme** [comment]
@hypest I think this was the reason, but there is an api endpoint to test if an email address is registered or not. I don't think any endpoint exists to test for a username. 

If we have to fix it, we must change the authentication endpoint to reply with the correct error.

**Comment by aforcier** [comment]
Actually there's even an endpoint for usernames we could use: `/is-available/username/`. So we could, if we wanted, do a second call after auth failure to verify whether the email or password is actually registered on WP.com.

**Comment by hypest** [comment]
The new login flows have separate screens for email and then password so, this is already "fixed" for that case.

OTOH, the _username_ + password happens on the same screen and the error message is indeed not specifying which one was wrong.
