### ISSUE TITLE
Editor: Navigating away from editor while media uploads causes problems

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4784]
### Steps to reproduce the behavior
1) Open the editor for a new or existing post or page
2) Add an image
3) While it's uploading navigate Back to the previous screen
4) Navigate to the Posts or Pages list
5) Publish the post/page without opening it for editing first

### Expected behavior
To be unable to publish while uploading, like what happens when attempting to publish from the editor

### Actual behavior
I'm able to publish the post, which then has a bad `img` tag in it pointing to a non-existent image.  The media upload never completes, leaving an empty entry in the media library.  In the GIF below it shows a constant "Uploading" spinner, but in other cases I've seen it show a "Retry" label...and when I clicked that I then got the infinite spinner and no actual upload.

![android-bad-upload-media](https://cloud.githubusercontent.com/assets/7233112/20313881/508a7d70-ab26-11e6-91ec-9d6cd898f48f.gif)

This animation shows it moving pretty fast, but the upload problem starts as soon as you leave the editor, no matter how fast you publish it.

**Comment by maxme** [comment]
The post shouldn't be publishable at this point. I'm pretty sure this is blocked from the "Publish" button in the Editor but not on the "Publish" button in the post list.

Note: Aztec should handle things differently (media uploads will continue when hitting the "Publish" button).

Related to https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/264 https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/439 https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/369

**Comment by daniloercoli** [comment]
Aztec is not so far away. Marking this ticket as Aztec-obsolete.

**Comment by hypest** [comment]
Closing as no longer happening. In recent versions of the app, the posts or pages list respect the media-uploading state and do not offer the "Publish" functionality.
