### ISSUE TITLE
Editor: Setting media width >2000px silently fails

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4785]
### Steps to reproduce the behavior
1) Add an image to a post
2) Edit the image
3) Set the width to anything greater than 2000px and save

### Expected behavior
To either be able to set the width to an arbitrary value, or be warned that >2000px is not allowed

### Actual behavior
The field is silently set back to 2000px with no errors or indications of a problem

**Comment by hoverduck** [comment]
FWIW, this also applies to the other fields on the image settings page, i.e setting the Title field to a crazy-long string is silently lost as well.

**Comment by tonyr59h** [comment]
It seems the web allows arbitrarily large values for width so we should allow the same.
