### ISSUE TITLE
Magic Link: Logging in with magic link results in "Incorrect username or password" errors

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4798]
### Expected behavior

When I log in to a WordPress.com account, I expect everything to work the same no matter how I log in (username & password, email & password, email & magic link).

### Actual behavior

When I log in with a username & password or email & password, the app works as expected.

When I log in with my email and a magic link, some parts of the app do not work. Instead, I get the error "Incorrect username or password." This happens when I tap on:

- Blog Posts > View an individual post
- Pages > View an individual page
- Themes > any action (e.g. Customize, Details, Support)

In the logs, I see this corresponding error: `Username empty/null`

### Steps to reproduce the behavior

1. Open the app (logged out) to the login screen
2. Enter your WordPress.com account email address
3. Tap "Send link" to get the magic link
4. Open your email and tap the button to log in
5. Logged in, go to Blog Posts and tap "View" under a post

Result: You get the error "Incorrect username or password."

You can repeat this after logging in with a password and note that it works as expected.

##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-28

**Comment by aerych** [comment]
cc @kwonye

**Comment by kwonye** [comment]
Thanks for the report, @rachelmcr! Pretty urgent. I'll tackle it as soon as I can.

**Comment by maxme** [comment]
Note: this is already fixed in the `feature/fluxc-integration` branch via this https://github.com/wordpress-mobile/WordPress-Android/blob/bf15cc5dea426356e8215863703120fee03ebad1/WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java#L258-L260

**Comment by daniloercoli** [comment]
Fixed in #4870
