### ISSUE TITLE
Opening a link to comment on a post (/#respond) does not put focus on the reply box

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4799]
### Expected behavior

When I open a link to comment a post, e.g. from a WordPress.com subscription email, I expect the comment view for that post to open in the Reader with the focus on the reply box.

The URL format for this link is this:

`https://*.wordpress.com/{year}/{month}/{day]/{post-slug}/#respond`

### Actual behavior

The comment view for that post opens in the Reader, but the focus isn't on the reply box. I have to tap on the reply box to start commenting.

### Steps to reproduce the behavior

1. Subscribe to a WordPress.com site (with a *.wordpress.com URL)
2. Open an email subscription notification in your email app on your device
3. At the bottom of the email, tap the "Comment" button
4. If prompted, select to open the link in the WordPress Reader

Result: The comments view for that post opens in the Reader, but the focus is not on the reply box.

##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-28

**Comment by hypest** [comment]
Confirmed!

**Comment by hypest** [comment]
Fixed with #4843
