### ISSUE TITLE
Opening a link from a comment subscription email does not open it directly in the Reader

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4800]
### Expected behavior

When I choose to open a link in the WordPress Reader, I expect the link to open directly in the Reader.

### Actual behavior

If the link is from a comment notification email (an email notification that someone commented on a post I was subscribed to), the link always opens first in my web browser and only then opens in the Reader.

I believe this is because the links in comment subscription emails all begin with `https://public-api.wordpress.com/` with a redirect to the actual comment link. Once the browser processes the redirect, it opens the link in the Reader.

Could we somehow recognize those URLs and handle the redirect in the app, so it doesn't have to open the browser first?

### Steps to reproduce the behavior

1. Subscribe to the comments on a WordPress.com post (on a site with a *.wordpress.com URL)
2. From a separate account, comment on the post (to trigger a comment notification email)
3. In the comment notification email, tap on any of the links to the comment, the post, to reply to the comment, or to like the comment.

Result: The link opens first in a web browser, and then opens in the Reader (or returns to your email app and prompts you to select where you want to open it).

##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-28

cc @hypest

**Comment by hypest** [comment]
> I believe this is because the links in comment subscription emails all begin with https://public-api.wordpress.com/ with a redirect to the actual comment link. Once the browser processes the redirect, it opens the link in the Reader.

Right, that's the reason basically.

> Could we somehow recognize those URLs and handle the redirect in the app, so it doesn't have to open the browser first?

Probably yes, but that would be a feature enhancement, it wasn't in scope for the work so far anyway. Even if it ends up being doable in the app, we might still want to consult with the API people to make sure it's OK to do that. Effectively, the redirect is there for analytics purposes and it's better to make sure we can replicate that in-app while not bypassing something else as well.
