### ISSUE TITLE
ViewPager swipe indicator inconsistent with reader Discover

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4838]
The ViewPager swipe indicator added in #4837 is inconsistent with Discover. It appears if the user taps the first post in the Discover stream but not otherwise.

**Comment by nbradbury** [comment]
This is actually working correctly. "Editor Pick" Discover posts are opened individually since we need to retrieve the original (source) post in order to display it. In this situation the ViewPager really only does have one article, so that swipe indicator doesn't appear.

**Comment by mzorz** [comment]
👍
