### ISSUE TITLE
Media Library: Allow uploading any file

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4842]
Currently we only support uploading image & video files in the app. A user is asking to upload mp3 files for example (#144231-h). We should probably support every file type we currently support in wp-admin.

Summary with a list of remaining work can be found pOhUr-47V-p2 + comments.

**Comment by rachelmcr** [comment]
Just a note: We had an open issue in the editor repo with 11 comments (mainly user feedback) requesting support for uploading arbitrary file types. I closed that issue in favor of this one but wanted to make a note of the frequent user requests for this.

**Comment by rachelmcr** [comment]
Another request from an app review:

>I use wordpress for my podcast.  It's pretty silly I can upload video but can't upload an mp3. Please fix this and then I will adjust my rating to 5 stars.

**Comment by rachelmcr** [comment]
We have another request from an app review, in this case for PDF and DOC files:

> Le falta poder subir archivos de texto (pdf doc etc) según la versión de android no se puede

**Comment by rachelmcr** [comment]
Another app review specifically mentioned PPTX files:

> I can't upload pptx from phone app

**Comment by rachelmcr** [comment]
A recent review mentioned audio file uploads:

>Audio is not uploaded

**Comment by formosattic** [comment]
A support request from #193741-h, for audio files upload:

> I can't add audio ....

**Comment by htdat** [comment]
From 255607-h for PDF files 

> can I upload pdf on android version?

**Comment by SiobhyB** [comment]
Another request in 256204-h from someone who'd like to upload audio files via the app.

**Comment by SiobhyB** [comment]
Again in 257658-h, from a user who'd like the option to upload audio files.

**Comment by SiobhyB** [comment]
Another user who'd like to upload audio files in 259785-h.

**Comment by mattmiklic** [comment]
Another request for uploading MP3s in 265439-h.

**Comment by SiobhyB** [comment]
Another request for audio files in 268809-h.

**Comment by SiobhyB** [comment]
The user in 271478-h would like to be able to upload audio files via the app too.

**Comment by SiobhyB** [comment]
Another request from someone in 273833-h who would like to upload PDF files via the app.

**Comment by SiobhyB** [comment]
Again in 273237-h. The user would like to upload PDF files via the app.

**Comment by SiobhyB** [comment]
From a five star review:

> Good app then But am finding it difficult to upload audios Any help

**Comment by SiobhyB** [comment]
From a one star review:

> App is not good music bloggers can't use this app because you can not upload audio ...

**Comment by SiobhyB** [comment]
From a four star review:

> A good app to remotely manage your wordpress Blog, BUT for whatever reason you cannot upload audio files to your self hosted wordpress. Please fix that!

**Comment by SiobhyB** [comment]
Suggested again in 279856-h.

**Comment by tmmbecker** [comment]
User in 279618-h would like to upload audio files via the app.

**Comment by SiobhyB** [comment]
User in 284155-h would like to be able to upload audio files.

**Comment by SiobhyB** [comment]
User in 286554-h would like to be able to upload audio files.

**Comment by SiobhyB** [comment]
From a three star review:

> It's great but can't upload audio files. Need to fix that.

**Comment by SiobhyB** [comment]
In 289155-h:

> Kindly enable us to upload pdf files with the help of WordPress android app.

**Comment by SiobhyB** [comment]
A request for audio in 289579-h.

**Comment by SiobhyB** [comment]
Another request for audio in 290504-h.

**Comment by SiobhyB** [comment]
Request for audio in 237283-h.

**Comment by SiobhyB** [comment]
Request for audio in 291076-h.

**Comment by charliescheer** [comment]
Request for PDF in 291904-h

**Comment by SiobhyB** [comment]
Request for audio in 292356-h.

**Comment by SiobhyB** [comment]
Request for PDF in 1367684-z.

**Comment by SiobhyB** [comment]
Request for PDF in 1390320-z.

**Comment by SiobhyB** [comment]
From a one star review:

> Can't add PDF, WORD, EXCELL files from the app..Hate it..

**Comment by SiobhyB** [comment]
From a three star review:

> Too bad we can not upload other types of files such as mp3 ... The application is limited to photos and videos. ....

**Comment by SiobhyB** [comment]
Three star review:

> The app is well-designed and has a lot of functions. However it doesn't allow you to upload pdf and word documents, which is only possible through the web browser.

**Comment by SiobhyB** [comment]
This was requested in 1579531-z.

**Comment by SiobhyB** [comment]
Another request to support more file types in 1580866-z.

**Comment by SiobhyB** [comment]
A one star review:

> Can't upload files to the website. You can only upload photos!

**Comment by SiobhyB** [comment]
Another request in 1612996-z:

> The WP app won't upload video or audio. Why is that?

**Comment by SiobhyB** [comment]
Another request for audio in 1692867-zen.

**Comment by SiobhyB** [comment]
Another request for videos and audio files in 1749835-zen.

**Comment by SiobhyB** [comment]
A three star review:

> Too bad we can not add a document but only photos and videos ...

**Comment by malinajirka** [comment]
Another request for pdf files in 1833679-zen.

**Comment by malinajirka** [comment]
Another request for mp3 files 1835129-zen.

**Comment by SiobhyB** [comment]
A three star review:

> Can you please add the feature of uploading media such as documents, not just the photo to upload. Thank you

**Comment by eduardozulian** [comment]
A request for audio and documents in 1910582-zen.

**Comment by thehenrybyrd** [comment]
Had a request to support uploading PDFs in #2079388-zen, in which the user mentioned they'd contacted us about this a year ago.

**Comment by lucasgonze-smp** [comment]
After much googling I found my way to this issue because I need to upload mp3s from phone to blog. I am not voting for this issue because it has so many votes already that the problem must be organizational. 

Some key person or group among the developers must be blocking on this. Their reasoning is not public. The votes on this ticket and many frustrated wordpress users are well known but irrelevant.

Note to fellow users: the workaround is to use the web browser on your phone.

**Comment by lucasgonze** [comment]
After much googling I found my way to this issue because I need to upload mp3s from phone to blog. It is pointless to vote for this issue because it has so many votes already, and has been around so long, that the problem must be organizational.

Some key person or group among the developers must be blocking. Their reasoning is not public. The votes on this ticket and many frustrated wordpress users are well known but irrelevant.

Note to fellow users: the workaround is to use the web browser on your phone. It's horrible UI but works.

**Comment by melindahelt** [comment]
#2331561-zen also requesting PDF upload

**Comment by gingerling** [comment]
This drives me crazy! I often reference PDFs in my blog posts, currently I write my blog in the app and then I have to go to my desktop and login to the site to add the links to PDFs... I use the app because I have disabilities and I find it more accessible than using the PC. That the app is missing this basic feature is very frustrating, but more frustrating is this bug report!

Why is there no response to this bug from a developer????? At least explain what the problem is.....

**Comment by thehenrybyrd** [comment]
#2392431-zen requesting PDF uploads.

**Comment by erricgunawan** [comment]
#2441460-zen :

> the "add document" button of the web interface is not present in the app for Android or for iOS / iPadOS. Would it be possible to add it? Thanks.

**Comment by eduardozulian** [comment]
2643984-zen requested PDF uploads.

**Comment by SiobhyB** [comment]
Another request in 2721198-zen, from a user who'd like to upload PDFs.

**Comment by thehenrybyrd** [comment]
Another request in #2861711-zen for mp3s.

**Comment by designsimply** [comment]
This came up in 14.8 beta testing and I closed https://github.com/wordpress-mobile/WordPress-Android/issues/11859 as a duplicate and wanted to note it contains a helpful video illustrating the problem.

**Comment by elibud** [comment]
Another user request for this feature, two star review:

> Please make a feature to display pdf. Because it's troublesome to change the pdf to jpg and then post it.

@bummytime can we add it to our backlog please?

**Comment by planarvoid** [comment]
Many user request this feature, from four star reviews. 

> ...But We Can't Add Mp3 Format Audio File

> The App works well overall but it there's still no upload audios on the media tab. Please fix.

**Comment by mzorz** [comment]
Heads up a related effort has been done (and left unmerged) in:

- WPAndroid https://github.com/wordpress-mobile/WordPress-Android/pull/8027
- FluxC https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/837
- Aztec https://github.com/wordpress-mobile/AztecEditor-Android/pull/737
Also see #8052 and #4842.

Might be worth to see what it takes to get the dust off these and take it from there.

Plus: I would imagine that users will want to use the uploaded audio files to some Post right after so, I guess it wouldn't hurt to also look into what it'd take to support this not only in the Media browser but also on Aztec (taking from where it was left) and mobile Gutenberg.

**Comment by designsimply** [comment]
This app review mentions wanting to be able to upload audio and also make some good points about the stability of the uploader:

> One thing that WP needs is a good uploader, compared to YouTube, Google, etc, it is very hard to upload things on the website using a slow internet connection. Any little drop out and the whole upload fail. An app like this could help but I just discovered that audio can't be uploaded from the app.
> 
> <sup>2-star app review by Tom Richards - 6/11, 4:38 AM - WP Android 13.8 Samsung Galaxy Note8 Android 9</sup>

**Comment by erricgunawan** [comment]
From forums:

> I used to upload files (docs, audio) to my posts, but all I have in Android app are *images, video, gallery*. How do I attach other formats? Found nothing relevant at *media* screen.

**Comment by designsimply** [comment]
Here's another note about this from an app review:

> The first thing I wanted to do - upload a document to media - seems impossible (or unintuitive if I'm missing something). The 'add' buttons in the 'media' tab provides filters only for images and videos. There needs to be an option for any file type.
> 
> <sup>3-star app review by Ben Gamblin - 7/1, 12:19 AM - WPAndroid 15.1 (885) LG G6 Android 9</sup>
