### ISSUE TITLE
PIN Lock breaks "Open with Reader" flow

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4847]
### Steps to reproduce the behavior
1) Set a PIN lock on the WP app
2) Click a link to a post, and select "Open with WordPress.com Reader" if prompted
3) Input PIN

### Expected behavior
The post opens in Reader

### What actually happens
The post appears extremely briefly before the PIN lock screen opens.  After inputting the PIN we're then left on whatever screen was last open in the app.

Note that this works fine if you open the link first in an app's internal browser, then click "Open in Chrome" before being redirected to the Reader.

**Comment by hypest** [comment]
Even though I cannot reproduce this issue, it might get fixed when https://github.com/wordpress-mobile/WordPress-Android/pull/4900 gets merged.

**Comment by hoverduck** [comment]
Closing, no longer able to reproduce
