### ISSUE TITLE
Samsung Multiwindow support not working

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4852]
### Expected behavior
The WPAndroid app should be available / eligible for Samsung multiwindow support (please to not be confused with Android 7 native multiwindow support).

### Actual behavior
The application is not listed as eligible anymore, as reported on some Samsung devices.

### Steps to reproduce the behavior
WP is no longer available as an app that you can access in the split screen menu when using other apps

**Comment by hypest** [comment]
Can't replicate the issue on my Android 6.0.1 Galaxy Tab S2 :(
The app is available for splitscreen. Are there some specific steps to follow to replicate?

Here's what I try:
* Put an app in splitscreen mode (e.g. Google Chrome)
* The system then displays a small list of apps that are available to add as the right-hand screen
* "Unfortunately", the WordPress app is offered in that list so, it seems it's working for me on this device...

**Comment by mzorz** [comment]
thank you @hypest -  we couldn't replicate either, but from what I've been checking that line in this PR is needed in order for the app to be discovered / eligible as a multiwindow app on Samsung devices. We might re open the issue if anyone complains later - unfortunately this is all I have to offer
