### ISSUE TITLE
Site chooser: no progress shown when loading

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4860]
### Expected behavior
When the loading operation in the site chooser list is in progress, some indicator should be shown.

### Actual behavior
Sometimes it takes a bit to load, but no progress is shown.

### Steps to reproduce the behavior
1. be an admin for lots of sites, like me :)
2. got to `switch site` for first time
3. Wait for it to load, and observe there is no progress indicator that the app is doing anything

**Comment by maxme** [comment]
>     follow lots of sites, like me :)

You mean be a member of a lot of sites? (This is not a Reader related issue, right?)

**Comment by mzorz** [comment]
> You mean be a member of a lot of sites? 

Yes exactly
