### ISSUE TITLE
Notification Settings: make the site list show the first 3 sites to give room for other settings

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4866]
When you have a lot of sites, the notification settings screen in the WordPress Android app gets very, very long as the sites are listed before the “Other” and “Sights and Sounds” sections.

It might be better for folks with lots of sites if the more general settings were first, and the site-specific afterwards to make getting to the general settings easier.

**EDIT**: following iOS implementation here as per @rachelmcr 's comment here https://github.com/wordpress-mobile/WordPress-Android/issues/4866#issuecomment-264825366

**Comment by rachelmcr** [comment]
Before we move the general settings up, I'd like to propose an alternate solution that has the added benefit of consistency with the iOS app:

When a user has a lot of sites, only a few sites (the user's primary site and two others) appear in the "Your Sites" section on the main Notification Settings screen. There is a "View All" option to view the full list of sites and adjust their notification settings. Other notification settings appear below that section.

![2016-12-05 10 51 50](https://cloud.githubusercontent.com/assets/8658164/20882670/f1efbdd4-bad9-11e6-9d03-52e4b5186b40.png)
