### ISSUE TITLE
Quote with Ordered List in Comment Displays as Bullet List

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#4881]
### Expected
A quote containing an ordered list is shown as it is in a browser (i.e. as a quote with an ordered list).

### Observed
A bullet list with a quote is shown when viewing a comment with a quote containing an ordered list in the app.  The comment contents are shown below.

```
<blockquote>
  <ol>
  <li>Cache invalidation</li>
  <li>Naming things</li>
  <li>Off-by-one errors</li>
  </ol>
</blockquote>

Don’t forget distributed systems:
  2. Exactly-once delivery
  1. Guaranteed order of messages
  2. Exactly-once delivery
```

Those contents were translated into HTML from Markdown.  The original comment contents are shown below.

```
> 1. Cache invalidation
2. Naming things
3. Off-by-one errors

Don’t forget distributed systems:
  2. Exactly-once delivery
  1. Guaranteed order of messages
  2. Exactly-once delivery
```

### Reproduced
1. View [this comment](https://examplebloge.wordpress.com/2016/12/07/ordered-list/comment-page-1/#comment-12) in a browser.
2. Notice quote with ordered list.
3. View [this comment](https://examplebloge.wordpress.com/2016/12/07/ordered-list/comment-page-1/#comment-12) in the WordPress app.
4. Notice bullet list with quote.

##### Tested
Google Pixel on Android 7.1.1 with WordPress 6.2

**Comment by nheagy** [comment]
#5142 is a dupe but it has a nice example screenshot fwiw ;)

**Comment by tonyr59h** [comment]
I've got a [solution to this](https://cldup.com/0siOLb-SUV.png) that involves replacing `ul`, `ol`, and `li` HTML tags with custom tags for `WPHtmlTagHandler` to process. It's a bit hacky looking but unless we want to use a `WebView` it's looking like the best (only?) solution available.

[This SO question](http://stackoverflow.com/questions/38935756/html-tag-handler-not-called-in-android-n-for-ul-li) is what led to the implementation.
