### ISSUE TITLE
Notification timestamp resets after device is locked

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4886]
Report: "As of the last day or so, I’ve noticed the timestamp in the “pull down” resets whenever I unlock my device. It says now upon unlock and counts up until the device locks again, then starts over. I’m on a Google Pixel, latest software. WordPress 6.3-rc-1."

I can reproduce this consistently. Note the "1m" timestamp in this notification:

![screenshot_20161208-121319](https://cloud.githubusercontent.com/assets/3903757/21019869/1fc2ac86-bd40-11e6-86dd-44dfb1706cb2.png)

When I return to the lock screen, that same notification has a "now" timestamp.

![screenshot_20161208-121353](https://cloud.githubusercontent.com/assets/3903757/21019909/4cdb3102-bd40-11e6-9003-c4e104b9e697.png)

And the "now" timestamp persists after unlocking.

![screenshot_20161208-121409](https://cloud.githubusercontent.com/assets/3903757/21019955/7a0839e0-bd40-11e6-8e8c-5306b54bfd9b.png)

**Comment by mzorz** [comment]
Notifications are re-built each time on screen lock/unlock to consider the possibility of the user having WPPIN enabled, in which case we show/hide (actually, re-build completely with or without, respectively) the quick actions. If an app is PIN-protected, we don't show any quick actions as to not offer the possibility for somebody different than the owner to reply/like/approve a comment or a 2FA notification.

Will see what we can do, I think people having PIN enabled will have to live with notifications being re-created each time (thus losing the actual original timestamp), but  we can enhance the experience for the rest of the users by preventing this from happening for them
