### ISSUE TITLE
Notifications: Unable to swipe between in-app notifs after opening from system notification

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4888]
### Steps to reproduce the behavior
1) Spawn a WP.com notification, such as by leaving a comment on your site as another user
2) Open the Android notification, which should launch the app to the WP notification
3) Try to swipe to older notifications

### Expected behavior
To have the same swiping behavior as when opening the notification from inside the app

### Actual behavior
Nothing happens.  Backing out of the notification and re-opening it restores the swiping ability

**Comment by mzorz** [comment]
Got it - not a bug, but will try and implement the same behavior as when going into the list, so it doesn't look like one
