### ISSUE TITLE
Notifications: Opening WP notif from Android system notification doesn't appear as Read

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4889]
### Steps to reproduce the behavior
1) Spawn a WP.com notification, such as by leaving a comment on your site as another user
2) Open the Android notification, which should launch the app to the WP notification
3) Back out to the notifications list

### Expected behavior
To have the notification marked as read

### Actual behavior
The notification still appears unread.  It's a display issue only, looking at the notification on another device it appears read (or if you refresh the in-app notifications list)

**Comment by mzorz** [comment]
Been investigating this, for note keeping:

We have a situation of race condition where when you tap on a notification and read a note (by opening the note detail activity) we mark it read locally, but the act of tapping on it brings the app to the foreground triggering the notificaitons update service which brings the whole notifications batch for this user _before_ we can mark it read on the server, thus washing the db and setting the note again as `unread`. Working on a solution to it.
