### ISSUE TITLE
New Sign-in related Tracks events

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4903]
This is a master ticket for the group of Sign-in related events we'd like to add Tracks for.

Additional events will be added to this list as we investigate the sign-in flows.

### Events to add
- [x] Default/Main Sign in screen displayed
- [x] Create account initiated
- [x] Email already used (error) when creating a new account/user
- [x] Username already exists (error) when creating a new account/user
- [x] Failed to create a new account

**Comment by daniloercoli** [comment]
Addressed in #4918
