### ISSUE TITLE
Poor formatting on site Notification Settings pages

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4909]
Navigate to Me -> Notification Settings, then choose a site.  Notice that there's no margin between the top of the display and the first menu item ("Notifications tab").  It makes me feel like I'm scrolled part-way down already, and I keep wanting to scroll up to see what I'm missing.

<img src="https://cloud.githubusercontent.com/assets/7233112/21139318/5239d766-c100-11e6-84b7-d1e471bfdd3e.png" width=350>

##### Tested on Nexus 6P, Android 7.1.1, WP alpha-30

**Comment by tonyr59h** [comment]
More info: I'm finding that this issue only shows up on API 24+, both on my emulators and physical devices.

**Comment by tonyr59h** [comment]
This is also visible via Site -> Settings -> More

**Comment by tonyr59h** [comment]
Seems that the action bar is being added with an incorrect root [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java#L46). It should use `android.R.id.list_container` ([added](https://developer.android.com/reference/android/R.id.html#list_container) in API 24) on API 24+ devices.
