### ISSUE TITLE
Editor: End tag can be set before starting tag. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#491]
In the editor tap to edit the content. 

Somewhere in the middle of the content, tap one of the formatting options.  I chose bold. 
Notice the opening bold tag is set, and the bold option is highlighted.
Move the cursor to a point in the text prior to the opening bold tag. 
Tap the bold format option again to set the closing tag. 

We could argue that this is on the user, but if the cursor is moved prior to the start of the format tag it might make sense to reset the button's state.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
