### ISSUE TITLE
YouTube embeds are not expanding

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#4910]
### Expected behavior
Pasting a Youtube link into the editor I expect the post to include an expanded YouTube video, like it does on the web, but it’s just the text of the link.

### Actual behavior
The post does contain a simple link.

### Steps to reproduce the behavior
- Start a new post in the Android app. 
- Pick any title you like.
- Paste a youtube link into the body of the post (https://youtu.be/RbXchpAZR8c)
- Hit publish

**Comment by maxme** [comment]
I think it's a dup of https://github.com/wordpress-mobile/WordPress-Android/issues/5007 and actually caused by https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/462

**Comment by maxme** [comment]
This is fixed, it was a dup of #5007
