### ISSUE TITLE
Identify failed signups in Helpshift

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#4911]
We need add to our Helpshift implementation the tag to identify signup errors.

At the moment signup errors and issues are not tagged in HS, instead login errors and issues are marked with the tag `origin:login-screen-error` and `origin:login-screen-help`.

**Comment by rachelmcr** [comment]
Let's use the tag `origin:signup-error` for these failed signups.

**Comment by hypest** [comment]
Unfortunately, we currently don't show an error screen when signup fails, unless it's a case of an unknown error. That means we don't have the opportunity to uniquely flag the Helpshift launch with a sign-up specific origin tag. The screen basically is still the login screen but with some mutated labels and extra input fields.

We could start using that "mode" of the login screen to help us flag the Helpshift origin but then, if the user changes back to login mode it would "reset" the origin tag. That can lead to false positives or negatives.

We might want to introduce a fail counter in sign up like we have in the login case where we show the error screen after 3 failed attempts to login. In such case, the Helpshift launch button can uniquely be tagged with the desired tagname. This means a change in the flow though so, let's ping @mattmiklic on this.

**Comment by mattmiklic** [comment]
Hey @hypest, can you explain for me what the change would be from the user's perspective?

**Comment by hypest** [comment]
Hey @mattmiklic , sure. So, currently, we keep the user is in the signup screen after *any* number of signup errors occur. An example of such an error is "username exists" where we pop up a small error hint window on the username edit field. We handle a big set of "known errors" that way. If an unexpected error occurs we change to an error screen.

Contrast that to the login case where we allow for 3 errors before we change to the error screen.

So, the reason I summoned you in this case is for perhaps considering a similar change to an error screen for signup as well. It could be the same "3 strikes" before moving to the error screen.

**Comment by maxme** [comment]
@hypest I think we just want to tag helpshift issues coming from the "?" (Help) button from the sign up screen.

**Comment by hypest** [comment]
@maxme here's the thing: we will need to start by tagging the "?" button with `origin:signup-screen-help` and then change it to `origin:signup-screen-error` if an error happens or instead, we can introduce an error screen like the 3-strikes login screen one. I'd vote for the 3-strikes one since it has more clear call-to-action options.

**Comment by maxme** [comment]
We don't need a `origin:signup-screen-error` tag since there is no such screen, only `origin:signup-screen-help` makes sense.

The 3-strikes login screen error was introduced to nudge self hosted users to tap on the "Add self hosted site" button, we don't need that for signup.

**Comment by hypest** [comment]
Aha, thanks for the insight @maxme ! In that case, what's your thoughts @rachelmcr (and perhaps @daniloercoli as well since you opened this ticket) ?

**Comment by rachelmcr** [comment]
Sorry, I missed this ping. As long as the tag identified that the origin is the signup screen, I'm not concerned about tracking whether there was an error. The tag `origin:signup-screen-help` is fine with me as long as we can be consistent with the tag used in iOS. cc @nheagy

**Comment by rachelmcr** [comment]
We discussed this further and decided to drop `-help` and `-error` from these origin tags, so let's implement this as `origin:signup-screen`.
