### ISSUE TITLE
Pin lock screen appears after requesting Android M permissions

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4916]
This is an edge case and only happens once as you give the app permissions, but:

### Expected behavior
When you install the app for the first time and start using features that require permissions from the system, since Android 6.0 system dialogs are presented to interact with the user so they can allow access to the required system features (for example, attempting to include some media while editing a post). Once the user allows this, the flow should continue in the app seamlessly, regardless of the user having PIN lock enabled or not.

### Actual behavior
When PIN lock is enabled, and you have not allowed permissions for the first time to access media and record audio/video, tapping the “add image” icon in a draft post being edited asks for the permissions and then presents the PIN lock screen (which looks awkward)

### Steps to reproduce the behavior
1. install the app for first time
2. log in to it
3. enable PIN lock
4. start a new draft post
5. tap on the include image icon
6. give the app the necessary permissions  by accepting the system dialogs that appear there
7. the PIN lock screen is shown.

**Comment by tonyr59h** [comment]
Place permissions are requested (to verify):
- [ ] MediaBrowserActivity
- [ ] EditPostActivity
- [ ] MeFragment
- [ ] ShareIntentReceiverActivity

**Comment by tonyr59h** [comment]
I think the safest bet here is to use the `setExtendedTimeout()` feature when we request permissions in each of the above locations. If we want a catch-all solution in one spot we'll have to deal with saving state which seems overcomplicated.

**Comment by mzorz** [comment]
Cool! didn't know about `setExtendedTimeout` 👍
