### ISSUE TITLE
Replace Noticons with Gridicons in Notifications Tab

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#4921]
### Expected
Icons in the Notifications tab show the updated [Gridicons](https://github.com/Automattic/gridicons).

### Observed
Icons in the Notifications tab show the outdated [Noticons](https://github.com/Automattic/design-handbook/tree/master/fonts/noticons).

### Reproduced
1. Go to ***Notifications*** tab.
2. Notice icons are Noticons.

The clock to the left of the text *OLDER THAN A WEEK*, the white comment bubble in the blue-grey circle in the lower right-hand corner of the avatar, and the back arrow to the left of the text *Maxime* are the Noticons to be replaced in the screenshot below.

![notifications](https://cloud.githubusercontent.com/assets/3827611/21234275/4a5e7834-c2af-11e6-8569-370ae73e603c.png)

##### Tested
Google Pixel on Android 7.1.1 with WordPress 6.2

**Comment by mattmiklic** [comment]
This is still an issue; noticed today.

![gridicons-android](https://user-images.githubusercontent.com/1396552/38645634-c23982a2-3db2-11e8-8d44-9c5dab6217c2.png)

**Comment by theck13** [comment]
This is still an issue.

**Comment by theck13** [comment]
This is still an issue.

**Comment by planarvoid** [comment]
I've moved this into a project cause it's still an issue. In the recent color changes the background color of icons changed from grey to blue. I think that's not intentional @osullivanchris ?

<img width="478" alt="Screenshot 2019-10-02 at 09 20 00" src="https://user-images.githubusercontent.com/1079756/66025189-20822a80-e4f6-11e9-8134-b52a7fc72ae0.png">

**Comment by osullivanchris** [comment]
I think we are using blue icon backgrounds for unread notifications, and grey for read ones. So that is probably intentional. 

Gonna ping @mattmiklic here as he's been working on color updates and also replied to this thread previously.

**Comment by mattmiklic** [comment]
> we are using blue icon backgrounds for unread notifications, and grey for read ones. So that is probably intentional.

Yep, 💯! And thanks @planarvoid; it will be great to get these replaced with Gridicons.
