### ISSUE TITLE
FluxC integration: Site picker sometimes doesn't work

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#4922]
I'm sometimes unable to switch sites using the site picker in the `fluxc-integration` branch. There is no error, but I'm returned to the site fragment with the same site active as before. The only way to change sites is to remove the current site (or sign out of WP.com).

I've so far only been able to reproduce this on an emulator (API 23). This will happen every time I use the site picker until the app is reinstalled (and most recently, the issue persists even after multiple clean installs).

After some testing, I'm seeing that `getSiteFragment()` is returning `null` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/9da8acdef1c8fc55f8c8af4610433f9c45191c5e/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L563), so the result of the `SitePickerActivity` seems to be discarded, and that's the reason the site doesn't changed.

**Comment by aforcier** [comment]
Small side note, related to the site picker but probably not to the actual issue - there's an unused `SiteModel` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/9da8acdef1c8fc55f8c8af4610433f9c45191c5e/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java#L364).

**Comment by maxme** [comment]
I can repro with "Don't keep activities" enabled

**Comment by aforcier** [comment]
Fixed in #4942.
