### ISSUE TITLE
Notifications: duplicate Like note

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4923]
### Expected behavior
Notes shouldn't be duplicate.

### Actual behavior
When liking and unliking shows 2 equal Notes on the Notifications tab.
![screenshot_1481727030 copy](https://cloud.githubusercontent.com/assets/6597771/21235578/1cab22d0-c2d6-11e6-92a5-3e2eaaca55c7.png)

### Steps to reproduce the behavior
I can repro by liking a post on the web, viewing the note on Android, then unliking and liking the same post again.

**Comment by mzorz** [comment]
I'm thinking given you like the note twice, a new note is generated server-side each time, thus it would probably be another kind of problem. Need to test and validate this behavior

**Comment by maxme** [comment]
I've seen the same kind of issue, I received 3 times the same PN, when I tapped one of them the app opened on the Notifications tab and I've seen the 3 notes there.

The Notifications list then refreshed and these notes disappeared.

Also note this was a comment like and it was an old one (more than a week ago).

**Comment by mzorz** [comment]
Just tested and confirmed this is a server-side issue:

1. when an event such as a like happens, a push notification is enqueued (and a notification is generated)
2. the Note is not generated if there is already a like note for this comment from this user already in there (but the PN is)
3. client-side, we are building the Note from the PN payload, and the list is re-created from scratch either when it's updated from the NotificationsUpdateService or when a refresh is forced by the user with pull-to-refresh. 

Given point 2 and 3, that explains why the note is seen 3 times (meaning, more than once) in the Notifications tab list itself and is gone after refreshing.

Corollary: this needs to be fixed server-side so PNs only are triggered once, just like the Notes are generated once

**Comment by mzorz** [comment]
**Update:** Server-side if a `like`-note with duplicate key is triggered then its `time` column is updated only (pushing it up in the notes list), but the email notifications are triggered as well, so leaving as is (email and PNs are alike in the sense they act as alerts of an event that has just happened) and replicating the behavior when creating notes locally on the Android client (that is, check if the note exists just update it).
From reading the code on Android this _should_ be working like that, but for some reason it isn't. Investigating.

**Comment by mzorz** [comment]
**Update:** I'm investigating why sometimes the wpcomID is different than the note ID. For instance, I could repro it by liking/unliking a comment 3 times in succession (having our update service disabled so I make sure to have the inconsistent state forever)

After doing that, my local DB has 3 different keys

2745330533
2745311545
2745311501

only one of them corresponds to the one key in the wp.com database

Given all 3 keys are different each time when received by the client, we have no way to detect dupes  client side. I'm now investigating how the different IDs were produced, and when...

**Comment by daniloercoli** [comment]
I've replied with some comments in the back chat since it's more a wpcom issue.

**Comment by mzorz** [comment]
Closing via #4959
