### ISSUE TITLE
Comments: Comment moderation error appears when commenting on a site you aren't a member of

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4933]
### Expected behavior

If I am not a member of a site, I expect to be able to comment on posts on the site, and reply to comment notifications (e.g. if the site owner replies to my first comment, and I reply to their comment from the notification). However, I don't expect to be able to moderate comments on that site.

### Actual behavior

If I am not a member of a site, I can comment on posts and reply to comment notifications on the notifications tab in the app, but I also get the error `An error occurred while moderating` after my comment reply is published.

I don't expect the error message, because I don't have permission to moderate comments on site's where I'm not a member. The app shouldn't try to moderate the comment in that case.

### Steps to reproduce the behavior

1. Leave a comment on someone else's post (on a site you're not a member of)
2. Have the post author reply to your comment
3. On your notifications tab in the app, reply to the post author's comment

Result: You get a `Reply published` confirmation message, but then the `An error occurred while moderating` message.

##### Reported by a user in 150931-h

**Comment by maxme** [comment]
Please fix this in the `feature/fluxc-integration` branch, and not in `develop`.

**Comment by oguzkocer** [comment]
Both @rachelmcr & me tried this issue again, but it seems to have been resolved, probably during `fluxc-integration`.
