### ISSUE TITLE
Customizer: "Select Files" button doesn't work

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4934]
### Expected behavior

I expect all the visible UI elements in the customizer to work as they do in a web browser.

### Actual behavior

I can't upload images using the customizer's "Select Files" button. Two places this appears:

1. Site Logo > Select logo > Upload Files
2. Header image > Add new image > Upload Files

The button doesn't do anything when I tap on it, so I have to exit the customizer, upload the image to the Media section, and then re-open the customizer to use it.

If the button won't work within the app, it'd be best if we could hide that Upload Files tab to avoid creating the expectation that files can be uploaded there.

### Steps to reproduce the behavior

1. In the app, open a site's Themes section
2. Tap "Customize" to open the site's customizer
3. Open the Site Logo section
4. Tap the "Select logo" button
5. Go to the Upload Files tab
6. Tap the "Select Files" button to try to upload a file

Result: Nothing happens, so you can't upload a file there.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-31
Originally reported in an app review.

**Comment by daniloercoli** [comment]
> If the button won't work within the app, it'd be best if we could hide that Upload Files tab to avoid creating the expectation that files can be uploaded there.

Customizer is actually a webview inside the app. 
Accessing the local file system is prohibited on purpose in our implementation of webview. I think we can either modify our implementation of the webview, and enable the dialogs that ask permissions to use camera and accessing the file system, (but this could be tricky and could lead to other errors), or just open the native device browser. 
I will try this 2nd option for now.

**Comment by tonyr59h** [comment]
> I would try this 2nd option for now.

Agreed that this is the best route for now. Shall we make a ticket for using our WebView sometime in the future?
