### ISSUE TITLE
Pending Draft Notifications not working when no pending drafts at launch

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4941]
### Expected behavior
Pending drafts notifications should be triggered if you have drafts sitting there for more than 3 days. (read #4835 for a detailed spec)

### Actual behavior
Pending drafts notifications not ever triggered if first time you launch the app you have no drafts in your blog posts list.

### Steps to reproduce the behavior
- open blog post list
- make sure you delete all the drafts you have if any
- force stop the app
- launch the app again and go to blog posts
- write a draft
- change the device date to something beyond 3 days in the future
- get back to the app
- it should show the pending drafts notification, but it doesn't.

Note:
- if you had a draft post already there, and forced stop the app then started it back again (with the date set to 3 days ahead), it would work

**Comment by daniloercoli** [comment]
Addressed in #4943
