### ISSUE TITLE
Post images disappear after scroll in Posts view

### ISSUE THREAD

**Issue by aaronyan** [wordpress-mobile/WordPress-Android#4951]
### Behavior
When viewing a list of published Posts, the posts' images will disappear if you perform the following:

1. Scroll down
2. Scroll back up
3. Some posts now do not show images

### Before scrolling down:

![screenshot_20161221-102456](https://cloud.githubusercontent.com/assets/4505888/21421442/bc3227f2-c7e7-11e6-92e0-c30bac2aa5f5.png)

### After scrolling down and then scrolling back up:

![screenshot_20161221-102501](https://cloud.githubusercontent.com/assets/4505888/21421445/c0e836f6-c7e7-11e6-813e-9d415731fc10.png)

##### Tested on [device], Android [version]
Google Pixel, Android 7.1.1, WordPress Android Alpha-31

**Comment by hoverduck** [comment]
I was able to reproduce this bug on my 6P, also running 7.1.1 and wp alpha-31

https://cloudup.com/csoJZhmTx_b

**Comment by maxme** [comment]
Confirmed, that also happens in the Reader and actually in almost all lists with images when you scroll down and up slowly. I had a quick look, and I think this comes from this changeset https://github.com/wordpress-mobile/WordPress-Android/commit/7054cd4abb08dc3069543c79175a4b5f880e323b - I don't think we should call `resetImage` in `onDetachedFromWindow`. cc @nbradbury

**Comment by nbradbury** [comment]
@maxme I think you're right this is related to that change. I've assigned this to myself, but likely won't tackle it until after Christmas.

**Comment by davoraltman** [comment]
Reproduced on Asus Zenfone 3 running 6.0.1
