### ISSUE TITLE
Remove Smart Lock for self-hosted

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4961]
When Smart Lock auto-fills a username/password and the user hasn't modified any textfields, if the user clicks "add a self-hosted site", we should clear out the WordPress.com username/password.

Repro steps:
1. Open the app and have Smart Lock auto-fill the username/password
2. Tap "Add a self-hosted site"
3. The app goes to the self-hosted login with the wp.com username/password still filled in.

**Comment by hypest** [comment]
No longer valid. The new login flows implementation only save to SmartLock on successful WPCOM login.
