### ISSUE TITLE
Understanding how self hosted login works

### ISSUE THREAD

**Issue by wilburt** [wordpress-mobile/WordPress-Android#4962]
I wish to built a login system for my app for my wordpress site. I have tried to understand the self hosted login system but I find it too complicated. Please can you explain it to me?

**Comment by hoverduck** [comment]
To be clear, you're looking to fork this project and use it as the base for a custom app for your WordPress site?  Or are you just having issues using the app as-is to log into your site?

It may be worth looking at the WordPress.org Slack channel ([here](https://make.wordpress.org/chat/)) for chatting about development, or the Forums ([here](https://wordpress.org/support/))

**Comment by wilburt** [comment]
Yes, I want to use it as a base for my custom app for my WordPress site.

**Comment by maxme** [comment]
@wilburt better to ask in the Slack channel.
