### ISSUE TITLE
Removing bold/italic removes it from the previously applied word(s)

### ISSUE THREAD

**Issue by davoraltman** [wordpress-mobile/WordPress-Android#4963]
### Expected behavior
While writing a post, I apply bold or italic to a word. I move the cursor to the next position. Since bold(or italic) is still selected, it will be applied to the next letters too. However, when I click on bold again, it should remove the application of bold so that I can continue to write without making the words in bold.

### Actual behavior
When I click on bold again, it selects the previous word and removes bold from it. The only way for me to keep it bold and remove the bold application for next letters is to click on space first and then click on bold again. This shouldn't be necessary if I didn't select the word that was bolded. And if I don't want my **!** or **,** to be bolded too, I have to add space, click on bold again, add **!** and then remove the space.

### Steps to reproduce the behavior
- Mark a word in the editor in bold
- Move the cursor past that word so that it's not selected
- Click on the bold icon again

It's the same thing with italic.

I am not sure if this is intended behavior but in my opinion, it shouldn't be. Adding it here to hear your thoughts. Cheers :)

##### Tested on Asus Zenfone 3, Android 6.0.1

**Comment by theck13** [comment]
I agree; the actual behavior is counterintuitive to me.  The new editor, [Aztec](https://github.com/wordpress-mobile/WordPress-Aztec-Android), has the behavior you expected and it will be added to the WordPress app soon.

**Comment by hoverduck** [comment]
@theck13 I'm going to close this issue since it will be fixed in Aztec.  Re-open if you still need this for tracking.
