### ISSUE TITLE
Schedule Post calendar formatting problems when switching screen orientation

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4965]
### Expected behavior
To be able to see the full calendar for scheduling a post regardless of screen orientation

### Actual behavior
The calendar appears cut off in two different ways depending on where you start:

A) With the device starting in portrait orientation open the post options page and select the PUBLISH option to open the calendar.  Now rotate the device to landscape orientation and observe that the calendar is cutoff halfway down.
![screenshot_20161228-101254](https://cloud.githubusercontent.com/assets/7233112/21528668/3922e67e-cd02-11e6-8de8-766f5ae47033.png)

B) With the device starting in landscape orientation open the post options page and select the PUBLISH option to open the calendar.  Notice that the bottom row of the calendar is cutoff.
![screenshot_20161228-101303](https://cloud.githubusercontent.com/assets/7233112/21528669/39244bd6-cd02-11e6-9cba-1db072e77796.png)

##### Tested on Nexus 6P, Android 7.1.1, WP alpha-31
(Originally reported on mi redmi 3s prime and Andorid OS is 6.0.1)

**Comment by maxme** [comment]
We're using the system date picker, but apparently it's broken when the "neutral" button text is too long (the string "Immediately" in our case).

[According to the doc](https://developer.android.com/reference/android/widget/DatePicker.html#setCalendarViewShown(boolean)) the style is broken on Android 24+

**Comment by rachelmcr** [comment]
This was reported again on a Huawei P8lite (ref: 168147-h), where the calendar shows 4 rows of dates and the 5th row is cut off. The device is in portrait orientation but the action buttons (OK, CANCEL, IMMEDIATELY) are stacked like in the second screenshot above.
