### ISSUE TITLE
Notifications: enhance pending drafts notifications texts and behavior

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4972]
Having one 24h reminder is a thing but having the same notification coming back every day is showing up to not be useful but rather annoying.

Have +1 day, +1 week, +1 month reminders, with different messages randomly chosen, that could even be fun:

- 1 day:

```
You drafted “post title” yesterday. Don’t forget to publish it!
Did you know that “post title” is still a draft? Publish away!
```

- 1 week:

```
Your draft, “post title” awaits you — be sure to publish it!
“Post title” remains a draft. Remember to publish it!
```

- 1 month

```You drafted “post title” X days ago. Your audience awaits it!
Don’t leave it hanging! “Post title” is waiting to be published.
```

**Comment by mzorz** [comment]
checked with editorial, good to go this way 👍

**Comment by kwonye** [comment]
I agree with the backoff 👍
