### ISSUE TITLE
Support Standard WordPress Post Formats

### ISSUE THREAD

**Issue by timnolte** [wordpress-mobile/WordPress-Android#4973]
### Expected behavior:
Present proper Post Format fields in app after changing the Post Format type in the Post Settings.

### Actual behavior:
There is only 1 post format presented regardless of the Post Format selected. This requires saving posts as a draft and using the web admin via a browser to properly complete posts.

### Steps to reproduce the behavior:
Choose any other Post Format from the Post Settings when starting a new Post.

**Comment by rachelmcr** [comment]
@timnolte Do you use a plugin to add extra fields based on the post format, or does your theme add those fields? The WordPress [post format](https://codex.wordpress.org/Post_Formats) feature allows themes to style the post differently according to the post format you select, but doesn't add fields to the post editor based on post format. The app supports the option to choose post format but isn't designed to support additional editor fields.

**Comment by timnolte** [comment]
@rachelmcr OK, so the theme that I'm using on my blog must be providing the Post Editor fields then. I mistakenly assumed that WordPress was providing those fields because the Post Formats feature was turned on. Interesting that I've actually read a blog post recently about the fact that Post Formats are a severely forgotten WordPress element. I guess until the Post Formats have an official Post Editor UI implementation there is no way to bring this functionality to the mobile app. It's a huge shame.

**Comment by timnolte** [comment]
I hope this might be reopened once there is a standard post editor UI built in for post formats.
