### ISSUE TITLE
Reader Doesn't Support Self-Hosted Subdirectory Installs

### ISSUE THREAD

**Issue by timnolte** [wordpress-mobile/WordPress-Android#4975]
### Expected behavior:
Submitting a URL for a WordPress installation in a site's subdirectory should show that installs posts and not the root site.

### Actual behavior:
The Reader looks to be stripping all subdirectory information from the URL entered and will only show the root domain/site posts.

### Steps to reproduce the behavior:
Try following http://chrislema.com/blog/ and you'll end up with old chrislema.com root site posts only and not new posts under the /blog/ subdirectory site.

**Comment by nbradbury** [comment]
I'm not able to reproduce this. In both the web and Android readers, when I follow http://chrislema.com/blog/ it correctly follows the feed in that subdirectory http://chrislema.com/blog/feed/ (which doesn't contain any posts).

**Comment by timnolte** [comment]
After some testing through the WordPress.com Reader it looks like this issue is more to do with some of the strange ways some folks have their WordPress blog feeds setup with redirects. One issue that I do see is that sites that get added and recognized as Feeds instead of WP sites don't show up right in the Android app but do show up on WordPress.com.

**Comment by nbradbury** [comment]
> One issue that I do see is that sites that get added and recognized as Feeds instead of WP sites don't show up right in the Android app but do show up on WordPress.com.

@timnolte Can you elaborate on what you mean by "don't show up right in the Android app?" Are they not showing up at all, or just not showing up the way you expect, or... ?

**Comment by timnolte** [comment]
@nbradbury many sites I add to follow end up as just feeds and don't even show in the "Sites I'm Following" management list. I believe items from those feeds do show up as new in the list but I'm not sure. I could give you an export of my subscription list.
