### ISSUE TITLE
Notifications: Multiple pending draft notification links to Notifications display instead of Post List

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4978]
### Steps to reproduce the behavior
1) Create several local draft posts
2) Push your device date 3+ days into the future
3) Open the WordPress app
4) Click the notification or its edit button

### Expected behavior
To be directed to the Posts List

### Actual behavior
The WP app opens to the notifications pane

**Comment by mzorz** [comment]
Closed via #4985
