### ISSUE TITLE
Use a dash in Mixpanel event names

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4995]
Following the rest of the names defined, the `Create Account` events should have a dash in the names to separate the specific event from its "overall" group name.

So, these events https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerMixpanel.java#L798-L821 need to have a dash added to become like "Create Account - Initiated"

**Comment by manisha-A** [comment]
Hi, Is this issue fixed as well?

I am looking at line https://github.com/wordpress-mobile/WordPress-Android/blob/0aabf8b3dae5de4e25a8047f3c14396021ac2b5c/libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java#L222

**Comment by hypest** [comment]
Mixpanel has been deprecated from the apps and is no longer relevant. Thanks for surfacing this ticket @manisha-A! Will close it now.
