### ISSUE TITLE
Featured image are showing in low resolution

### ISSUE THREAD

**Issue by LennyObez** [wordpress-mobile/WordPress-Android#5005]
Hey there,

When I watch my feed in WordPress for Android, it appears aliased.

As my screen is in FullHD (1920x1080), my image in 4K with a low weight (less than 50 ko) and my internet connection is 4G, it should:

### Expected behavior
Appear in a great quality without any aliasing.

### Actual behavior
Appear in a bad quality with aliasing.
http://image.noelshack.com/fichiers/2017/02/1483963241-screenshot-20161226-115812.png

### Steps to reproduce the behavior
Create an article on your WordPress website,
Upload a featured image to this article,
Search for your article on WordPress App.

**Comment by nbradbury** [comment]
Fixed in #5321
