### ISSUE TITLE
Kickstarter oEmbed URLs not embedding if URLs do not have a slash at the end

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#5007]
Steps to reproduce:

1. Install WPAndroid version 6.5 (currently 6.5-rc-1).
1. Search Google for a Kickstarter campaign (i.e. kickstarter nomatic travel bag).
1. Click on the first search result.
1. Copy the URL.
1. Start a new post using WP Android 6.5.
1. Add a title and one line of text.
1. Add the link copied earlier on a line by itself at the bottom of the post.

<strong>Example URL:</strong> https://www.kickstarter.com/projects/1131502390/the-nomatic-travel-bag

<strong>Result:</strong> In my Google search result, I was led to a Kickstarter URL without a slash at the end of the URL. Without the slash at the end, the embed fails to work.

<img alt="screenshot_2017-01-09-15-05-36" src="https://cloud.githubusercontent.com/assets/1119271/21786032/5114d4a0-d67f-11e6-97c9-9934e730ec66.png" width="300" />
<sup>Seen at https://design5279.wordpress.com/2017/01/10/nomatic-travel-bag/ using the default browser on a Samsung Galaxy Tab4 (SM-T330NU) running Android 5.1.1.</sup>

**Comment by maxme** [comment]
I don't think this is related to the ending slash, this might be due to this https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/462
