### ISSUE TITLE
Show embeds in the Posts view

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#5008]
### Expected behavior

I expected to be able to see oEmbeds working in the Posts view in the app.

### Actual behavior

Embeds just look like plain links in the Posts view.

<img alt="screenshot_2017-01-09-14-48-53" src="https://cloud.githubusercontent.com/assets/1119271/21786212/13521f8c-d680-11e6-9368-f2386b8260d4.png" width="300" />

### Steps to reproduce the behavior

1. Install WPAndroid 6.5-rc-1.
1. Create and publish a post with a kickstarter, reddit, twitter moments, or facebook news embed.
1. Find the post on the Posts page in the app and check to see if the embed is working there.

##### Tested on Samsung Galaxy Tab4 (SM-T330NU), Android 5.1.1

**Comment by maxme** [comment]
The posts are limited in height. I don't think we should show the oEmbeds here (or anything else than text in this field).

**Comment by hoverduck** [comment]
@maxme Should we close this issue as working by design, or is it worth having somebody look at an alternate way to represent the embeds in the post list?
