### ISSUE TITLE
Featured Image Selection Feature Request

### ISSUE THREAD

**Issue by chrisfromthelc** [wordpress-mobile/WordPress-Android#5012]
When editing or posting a new post, selection of a featured image seems to be limited to the Media Library, regardless of the app's permissions to access the camera or device's photo library.

Ideal functionality would present the user with a modal similar to the one presented when media is inserted in the post (with only applicable selections, of course).

![attachment](https://cloud.githubusercontent.com/assets/8002138/21789219/9f211882-d690-11e6-82d1-6f6708bae5dc.png)

**Comment by rachelmcr** [comment]
Related: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/265

**Comment by rachelmcr** [comment]
This came up again in feedback from a user trying out Aztec and expecting to be able to upload a featured image directly from the device. (Internal ref: 207702-h)
