### ISSUE TITLE
Stop sending users who want to start over to Helpshift

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#5013]
Currently we are sending all users who want to start over to Helpshift. Instead we'll be sending users to either a pre-filled email form if they are a paid customer or a webview to https://en.support.wordpress.com/empty-site/ if they are a free customer.

Same as https://github.com/wordpress-mobile/WordPress-iOS/issues/5131

**Comment by elibud** [comment]
Linking to iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/5131

**Comment by elibud** [comment]
Android friends, please note that a new field has been added to the sites API endpoints: `plan.is_free` so we can easily know were to direct users.
