### ISSUE TITLE
Add ability to search your own posts/pages

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#5014]
We got a request from user:

> I want to search my posts in the App, sometimes I need to modify an older post or just read it. But I can't do it easily with the mobile clients.
> I think it is a useful feature, and I'm willing to see it in next version. :D

This feature already exists in iOS so it only makes sense to add it to Android version too.

**Comment by aforcier** [comment]
We have a (very old) open issue for this already: https://github.com/wordpress-mobile/WordPress-Android/issues/62

**Comment by khaykov** [comment]
Closing as duplicate 👍
