### ISSUE TITLE
Accents with Bluetooth Keyboard do not work in the editor

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#5020]
An Android user reports that with their Spanish bluetooth keyboard, they can’t add accents to the characters. It works correctly elsewhere (e.g. in the Helpshift conversation) but not in the editor.

Reported by @rachelmcr

**Comment by theck13** [comment]
We should test this with [Aztec](https://github.com/wordpress-mobile/WordPress-Aztec-Android) as well.

**Comment by maxme** [comment]
> We should test this with Aztec as well.

We're using "fluxc-obsolete" label for issues that will probably be fixed by FluxC integration - might be worth creating a "aztec-obsolete" label.

**Comment by kwonye** [comment]
@maxme good call, created.

**Comment by hypest** [comment]
Tested the app with a Belkin BT case+keyboard I have here and it seems to work OK with Greek, both in Aztec and in the hybrid visual editor. Also tried and added Spanish as an option and I'm able to add accented characters by typing the `'` char first and then the letter. Can't fully verify this for Spanish though as I'm not familiar with what accented characters should be available.

**Comment by kwonye** [comment]
Thanks for testing, @hypest!
