### ISSUE TITLE
Add Setting for Aztec Editor

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5030]
Add option in App Settings for Aztec editor in `feature/aztec-integration` branch.

**Comment by maxme** [comment]
@theck13 for Aztec rollout, we can do the same thing as we did for the hybrid editor:
* Have an option in the App Settings screen
* Only show that option (and enable it) for Alpha users (ie. put it under a build flag) - [available vs. enabled](https://github.com/wordpress-mobile/WordPress-Android/blob/b2a2b18a3a17eb4fc887478641dec15efd930607/WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java#L370-L380)
* Eventually have a specific URIs to make the option available and enable / disable Aztec, like [here](https://github.com/wordpress-mobile/WordPress-Android/blob/edd7185c51e2cd60a5e8e6f53fd8e6b0d0f1f978/WordPress/src/main/java/org/wordpress/android/ui/VisualEditorOptionsReceiver.java).
