### ISSUE TITLE
[Analytics] Jetpack user not tracked correctly

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5035]
While reviewing the site migration, I've found that the method [`WordPressDB.hasAnyJetpackBlogs()`](https://github.com/wordpress-mobile/WordPress-Android/blob/cba1d9280655edcf27b42091d594fb97a86c6734/WordPress/src/main/java/org/wordpress/android/WordPressDB.java#L2143-L2145) never worked. It assumes the field `api_blogid` defaults to 0, which is incorrect.

This never worked and will be fixed when FluxC is merged.

**Comment by aforcier** [comment]
Confirming that `AnalyticsUtils` is now using `SiteStore.hasJetpackSite()` to determine Jetpack user status for metadata.
