### ISSUE TITLE
Format Toolbar Remains Enabled for Post Title with Aztec Editor

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5041]
### Expected
The format toolbar is disabled when the post title field is selected.

### Observed
The format toolbar is enabled when the post title field is selected.

### Reproduced
1. Go to ***Sites*** tab.
2. Tap ***Create*** floating action button.
3. Notice format toolbar buttons are active with post title field selected.

##### Tested
Google Pixel on Android 7.1.1 with WordPress alpha-33

**Comment by hypest** [comment]
Fixed with #5106
