### ISSUE TITLE
Connect Aztec Media Options to WordPress App Actions

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5046]
### Expected
Choosing an option from the media menu performs associated action within the app.

### Observed
Choosing an option from the media menu shows message or does nothing.

### Reproduced
1. Go to ***Sites*** tab.
2. Tap ***Create*** floating action button.
3. Tap ***Media*** format toolbar button.
4. Tap ***Gallery*** option.
5. Notice "Launch gallery" message.
6. Tap ***Media*** format toolbar button.
7. Tap ***Photo*** option.
8. Tap ***Device camera*** option.
9. Notice nothing happens.
10. Tap ***Media*** format toolbar button.
11. Tap ***Photo*** option.
12. Tap ***Device photos*** option.
13. Notice nothing happens.
14. Tap ***Media*** format toolbar button.
15. Tap ***Photo*** option.
16. Tap ***Media library*** option.
17. Notice "Open library" message.

##### Tested
Google Pixel on Android 7.1.1 with WordPress alpha-33

**Comment by 0nko** [comment]
Solved by #5129.
