### ISSUE TITLE
Differentiate Helpshift login tag among wpcom/wporg/jetpack modes

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5048]
Currently, the login screen tags the Helpshift launch via the `?` button on the login screen with the `origin:login-screen-help` tag. Let's differentiate the tag based on the login "mode" displayed at the time the user taps the `?` button. Let's also remove the `-help` term as it's redundant.

So, let's use `origin:wpcom-login-screen` for when in wpcom or magiclink mode, `origin:wporg-login-screen` when in selfhosted mode and `origin:jetpack-login-screen` when asking the user to login with wpcom to see the stats on a jetpack site.

**Comment by nheagy** [comment]
Mind if we drop `-help` or `-error` from these completely? That way we'd just have `origin:wpcom-login-screen`, `origin:wporg-login-screen`, and `origin:jetpack-login-screen`? @rachelmcr?

**Comment by hypest** [comment]
Following a discussion in chat, sure, let's remove the `-help` part. I'll revise the ticket description. /cc @nheagy
