### ISSUE TITLE
ReaderDatabase crash in onDowngrade()

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#505]
ReaderDatabase.onDowngrade() crashes right now because it calls super(), which immediately throws a SQLiteException. Simple fix is to not call super().

**Comment by Stackflood** [comment]
Hi @roundhill , @nbradbury .I am going through the code for ReaderList activity. Can you kindly help me locate the code where ReaderDatabase is initiated on the very first time the application launched or ReaderPostListActivity clicked.

**Comment by nbradbury** [comment]
@Stackflood The db is initialized on the first call to [ReaderDatabase.getDatabase()](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java#L73), which at the moment happens when the reader post list is created and it purges the database [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java#L1129).

**Comment by Stackflood** [comment]
thanks @nbradbury for the quick response. purgeDatabaseIfNeeded() is called from the OnStart() of the ReaderPostListFragment. which comes after onActivityCreated - in which we have a spinner getting all the data for the respective tags. 

-- For the very first time the database is loaded
1. If the database is getting initiated in the OnStart(), where the spinner is getting the data from ?
2. Also , please help me locate the method where the first API call to fetch back tags is made.

**Comment by Stackflood** [comment]
Hi @nbradbury , waiting for a response.

**Comment by nbradbury** [comment]
The "spinner" is actually a label designed to look like a spinner. When clicked, it displays a popup menu of available tags - see `showTagPopupMenu()` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderTagToolbar.java#L87). That menu is populated using a [ReaderTagMenuAdapter](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderTagMenuAdapter.java).

**Comment by Stackflood** [comment]
Ok, but the second question remains : 

"2. Also , please help me locate the method where the first API call to fetch back tags is made."

**Comment by nbradbury** [comment]
> please help me locate the method where the first API call to fetch back tags is made.

Fetching tags is handled by [ReaderUpdateService](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/services/ReaderUpdateService.java#L50). You'll see there are three places where that's called, the first of which happens immediately after signing in.
