### ISSUE TITLE
Media: filters don't work

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5055]
### Expected behavior

When going to the Media section within the app's main menu, a grid with the available media for the currently active site is shown.
On top of that, a filter reads "All(xx)" and when you tap there, these options are shown:
- All (xx)
- Images (yy)
- Unattached (zz)
- Custom Date...

Tapping on any of these should apply the selected filter and update the list accordingly (i.e. if you tap `Images`, just show images, or if you tap `Unattached`, just show those items in the library that have not yet been included in any of your site's posts).

### Actual behavior

Tapping on any of those filters does nothing, and not even refreshing the list (pull to refresh gesture)  makes any changes to the list (it just shows all available content in the library).

### Steps to reproduce the behavior
1. Log in to WPAndroid app
2. go to your site's Media section (first tab)
3. Check the filters appear. If you don't have any items in your library, please add some (2 at least).
4. Tap on any filter
5. Watch the list remains the same.

**Comment by maxme** [comment]
I confirm, there is something weird with these filters - adding fluxc-obsolete label since we're integrating the media store.
