### ISSUE TITLE
Comment Like Status is Reverted When Device is Rotated

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5062]
### Expected
Rotating the device retains comment like status.

### Observed
Rotating the device reverts comment like status.  The like/unlike is saved on the backend, but the interface does not reflect the correct state.

### Reproduced
1. Go to ***Notifications*** tab.
2. Tap a comment notification.
3. Notice the state of the ***Like/Liked*** button.
4. Rotate the device.
5. Notice the state of the ***Like/Liked*** button is unchanged.
6. Tap the ***Like/Liked*** button.
7. Notice the state of the ***Like/Liked*** button is changed.
8. Rotate the device.
9. Notice the state of the ***Like/Liked*** button reverts to the original state.

##### Tested
Google Pixel on Android 7.1.1 with WordPress 6.5

**Comment by maxme** [comment]
Should be fixed in the FluxC integration branch

**Comment by aforcier** [comment]
👍 can't reproduce in `alpha-41`.
