### ISSUE TITLE
Jetpack auth login screen mode bypassed when switching to password login

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5063]
### Expected behavior
The login screen mode should still stay in "Jetpack auth" mode when dropping out of magic-link login mode back to password mode.

### Actual behavior
The login screen is presented as normal login, losing the "To view your stats, log in to the WordPress.com account you used to connect Jetpack." message and offering self-hosted login and account creation on the spot.

### Steps to reproduce the behavior
* With no WPCOM account connected and only a Jetpack selfhosted site added to the app
* Tap on the "Stats" item on the site screen. The app asks to login to the WPCOM account connected to Jetpack
* Enter the email address and tap "Next"
* Tap on "Enter your password instead" to switch back to password login mode
* Boom. Login screen is no longer Jetpack auth configured

##### Tested on [device], Android [version]
Nexus 5X, Android v7.1.1

**Comment by maxme** [comment]
Please fix this in the fluxc integration branch

**Comment by hypest** [comment]
This should be handled as part of the new login project #5814

**Comment by hypest** [comment]
Fixed with latest Login Rework PRs so, closing it.
