### ISSUE TITLE
hs-tags gets duplicate tags

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5066]
### Expected behavior
The `hs-tags` key in Helpshift's metadata hashmap should not have duplicate tags.

### Actual behavior
The `hs-tags` key in Helpshift's metadata hashmap can have duplicate tags.

### Steps to reproduce the behavior
* With the app's data cleared and while being on the login screen
* Tap the `?` button on the upper right
* Tap on the `Contact us` button
* Go back to the starting login screen
* Tap the `?`button
* Using the debugger, put a breakpoint at https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/HelpshiftHelper.java#L169
* Tap the `Contact us` button and observe the `mMetadata` on the debugger. The `hs-tags` key would include two copies of the `origin:wpcom-login-screen` tag.

##### Tested on [device], Android [version]
Nexus 5X, Android v7.1.1

**Comment by maxme** [comment]
We could make the HelpshiftHelper a bit smarter and use a map to store specific tags (like `origin` prefixed tags), this would help with multiple with this: https://github.com/wordpress-mobile/WordPress-Android/pull/5057#issuecomment-275314874
