### ISSUE TITLE
Use FluxC's volley queue for the ImageLoader

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5072]
`WordPress.imageLoader` no longer gets the bearer token for WPcom requests, which means images from private sites aren't working anywhere that relies on it (e.g. the legacy editor, and soon Aztec).

This used to be handled in [`WPDelayedHurlStack`](https://github.com/wordpress-mobile/WordPress-Android/commit/59d3a7a64971904ec2a43ecb0e9b2b1f8f50d939). The proposed solution is to inject FluxC's volley queue to it can be used by the `ImageLoader`.

**Comment by nbradbury** [comment]
Closed via #5087
