### ISSUE TITLE
Reader: Implement a Read It Later feature

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5075]
When using the reader, sometimes you see a story that is interesting, but you don’t have time to read. It would be nice to have a way to flag a story as “read it later”, and a way to view a list of stories flagged this way.

This feature should:
- be implemented only in the client since there is no REST API support
- be available in the signed out reader.
- display an icon or button in the post cells to save a post for later reading.
- provide a way to access a list of posts saved for later.
- remove a saved post from the saved list once its been read, including if it was not read from the saved list.

Bonus:
- display an notification that there are unread saved stories after a day or two.

### Copy of the corresponding iOS issue - https://github.com/wordpress-mobile/WordPress-iOS/issues/6135

**Comment by mzorz** [comment]
I love this ❤️

**Comment by mzorz** [comment]
This can be closed now actually! As the feature landed already 🎉 https://github.com/wordpress-mobile/WordPress-Android/pull/7814
