### ISSUE TITLE
Reader: Error unfollowing a site that has been deleted

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5076]
To reproduce:

1. Create a new wpcom blog.
2. Follow the blog
3. In your Reader's following stream, confirm that posts from the blog appear.
4. Delete the wpcom blog.
5. Go to the Reader's Manage Sites screen and try to unfollow the delete blog. 

You'll see an error message stating that API requests have been disabled for that site, and the site is not removed from your following list.

I tried to reproduce this in the web reader and was able to successfully unfollow the site.  This suggests we need to update which endpoints the app calls to unfollow a site.

@nbradbury 

cc @aerych as this is present in the iOS reader as well.
https://github.com/wordpress-mobile/WordPress-iOS/issues/6457

**Comment by nbradbury** [comment]
Notes: on Android the user simply sees a toast stating "unable to unfollow this blog." The endpoint is v1.1 `sites/{site}/follows/mine/delete`. The status code of the response is 403.

**Comment by nbradbury** [comment]
If we use v1.2 of that endpoint, we get a 404. The site still isn't removed from the user's followed sites, though.

**Comment by nbradbury** [comment]
Slack discussion with the reader squad proposed the solution is for the backend to treat unfollowing a deleted site as a successful unfollow. This really is a backend issue, but I'm leaving it open until I hear it's resolved on the backend.

**Comment by nbradbury** [comment]
Update: this turned out to be a problem to fix on the backend, so it's up to the mobile apps to work around it by calling `/read/following/mine/delete?url=` when unfollowing by ID fails with a 403.
