### ISSUE TITLE
FluxC integration: Sign Up - Some error from the server should not be displayed

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5088]
IMO, that would be better to change the API message, but in the meantime we can interpret form of the error types and display our own messages.

Example when I try to signup with an existing email:
```
{
	"error": "email_exists",
	"message": "Invalid email input"
}
```

We display: `Invalid email input` in that case.

**Comment by aforcier** [comment]
Fixed in #5250.
