### ISSUE TITLE
Private site images using HTTP aren't fetched

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5093]
If a post in a private site contains a local (private) image that's mistakenly using `http://` (probably through manual editing - images inserted from the library should have `https://` added automatically), the app is unable to load the image using the custom `ImageLoader` (in the `fluxc-integration` branch).

This is working in `develop`:
1. Request private site’s image using `http://`
2. Request is sent, no headers are added (expected, we don't send auth tokens over HTTP)
3. Receive 301 redirect to same URL with `https://`
4. Follow HTTPS redirect, applying the auth header now that it’s secure
5. Image request succeeds

This is what's happening in the `fluxc-integration` branch:
1. Request private site’s image using `http://`
2. Request is sent, no headers are added (expected, we don't send auth tokens over HTTP)
3. Receive 301 redirect to same URL with `https://`
4. Follow HTTPS redirect, but **no headers are added**
5. Image request fails (receive `403` from server)

**Comment by maxme** [comment]
This should be fixed by https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/301

**Comment by oguzkocer** [comment]
@maxme Should we close this since that PR is merged?
