### ISSUE TITLE
Notifications: Improve text formatting in comment notifications

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5114]
Here's a mockup of a potential new design for comment notifications, that uses hierarchy and two lines to make the text of the notification clearer. It doesn’t show a preview of the comment on the lockscreen, but if the notification is expanded the entire comment is visible.

![image](https://cloud.githubusercontent.com/assets/7233112/22606188/ff4d8c42-ea20-11e6-94c3-84267677db6f.png)

cc: @mattmiklic 
iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/6570

**Comment by sudhirkhanger** [comment]
What exactly is expected of this bug report

- [ ] Restrict comment to two line.

- [ ] Line one - Comment type `on` blog name.

- [ ] Line two - comment author name.

- [ ] Expand notification - show detailed comment. How many lines of comment?

This is more or less what we have now.

![screenshot_1530416245](https://user-images.githubusercontent.com/841656/42130855-f3bd26ee-7d0e-11e8-910d-a09b1e4753e1.png)
![screenshot_1530416251](https://user-images.githubusercontent.com/841656/42130856-f3fc06d4-7d0e-11e8-8794-1a5495bfc9ec.png)

**Comment by hoverduck** [comment]
@mattmiklic - It's been a while since you built these mock-ups.  Is this issue still valid, or should we close it?

**Comment by mattmiklic** [comment]
I believe it is still valid. @nozomimimi is currently doing some design work on richer notifications on iOS; I'm not sure if there's any plans to revisit the notifications design for Android but surfacing this for her eyes just in case it's no longer relevant or we decide to do more on Android.

**Comment by iadeelzafar** [comment]
Is this issue still valid? If yes, I'd like to work on this as I'm a new contributor to this project. So, this can be a good one to start off.

**Comment by mattmiklic** [comment]
I just took a look at the current state of notifications to see if this issue was still valid. The hierarchy and content of the notification is clear both in the default and expanded states. Therefore, I believe we can close this one.

<img width="883" alt="Screen Shot 2019-06-24 at 5 31 52 PM" src="https://user-images.githubusercontent.com/1396552/60053667-71d47f80-96a6-11e9-9e40-550607bcaace.png">
