### ISSUE TITLE
Jetpack: Enable Plans section for Jetpack-connected sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5121]
### Expected behavior

All sites should have a Plans section on the My Sites tab (to match Calypso):

- AT Business plan users should see WordPress.com plans with the Business plan active. Related Calypso issue: https://github.com/Automattic/wp-calypso/issues/8836
- Jetpack users should see [Jetpack plans](https://jetpack.com/pricing/).

### Actual behavior

Currently, Jetpack-connected sites do not have a Plans section.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-34

**Comment by maxme** [comment]
In the `fluxc-integration` branch we see:

![screenshot-2017-02-07_08 52 20 957](https://cloud.githubusercontent.com/assets/40213/22682420/d7a42332-ed12-11e6-82d7-99093114c0de.png)

It seems some data are lacking from the API call on Jetpack sites, also it seems we get duplicate plans.

**Comment by aforcier** [comment]
It looks like currently AT sites are still returning Jetpack plans from the endpoint (so they'd be as broken as a normal Jetpack site if we displayed plans for them).

As I understand it AT sites should be returning WordPress.com plans - I'll look into why this isn't the case.

**Comment by elibud** [comment]
We will not be implementing this for now, Plans are not displayed for Jetpack sites in the apps.
