### ISSUE TITLE
Jetpack: Enable Themes section for Jetpack-connected sites & AT Business sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5122]
### Expected behavior

All WordPress.com or Jetpack-connected sites should have a themes section (to match Calypso). Jetpack-connected sites & Business sites that have been automatically transferred should display themes available for those sites.

### Actual behavior

Currently, only WordPress.com sites have a Themes section.

**Comment by maxme** [comment]
It looks like only minor changes are needed in the `fluxc-integration` branch to make this work: 

* Use v1 instead of v1.1 endpoint to fetch the theme list.
* Update screenshot URLs (prepend `https`).

**Comment by aforcier** [comment]
Note: For AT sites at least (and perhaps Jetpack sites as well), the response of `/sites/$siteId/themes/mine` when using an uploaded theme is missing a few fields compared to a WordPress.com theme:

```
{
  "id": "dandy",
  "screenshot": "...",
  "name": "Dandy",
  "description": "...",
  "tags": [
    ...
  ]
}
```

It looks like we're okay for displaying this as a current theme, except that we'll have to account for `preview_url` missing.
