### ISSUE TITLE
People: Add support for People Management to Jetpack-connected sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5123]
### Expected behavior

I expect to be able to manage the users/followers on my site (in the People section) for WordPress.com and Jetpack-connected sites. (This includes Business sites that were automatically transferred.)

### Actual behavior

The People section is only supported for WordPress.com sites.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-34

**Comment by maxme** [comment]
This works as expected in the `fluxc-integration` branch (added the `fluxc-obsolete` label). 

![screenshot-2017-02-07_08 55 19 282](https://cloud.githubusercontent.com/assets/40213/22682516/4a2e60d4-ed13-11e6-8a89-3fd6c6b9fa70.png)

**Comment by maxme** [comment]
Hmm actually the user "Max LeTest Subscriber" has a subscriber role, not a contributor.
