### ISSUE TITLE
Settings: Add support for full site settings to Jetpack-connected sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5124]
### Expected behavior

I expect to be able to manage my site's settings (in the Settings section) for WordPress.com and Jetpack-connected sites. (This includes Business sites that were automatically transferred.)

Settings I should have access to:

- General (title, tagline, address, privacy, language)
- Writing
- Discussion
- This device
- Advanced (maybe not for Jetpack sites)

### Actual behavior

I only have access to these settings for WordPress.com sites. Jetpack-connected sites still show these settings only:

- Account details
- HTTP credentials (optional)
- Media
- Remove site button

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-34

**Comment by kwonye** [comment]
@tonyr59h can comment better on this, but with Jetpack sites using the WP.com API, we can simply add an additional check for Jetpack connectivity and it should work as-is.

Also, @tonyr59h is this eligible for the fluxc-obsolete tag?

**Comment by oguzkocer** [comment]
With the integration of FluxC, this works as expected right now.
