### ISSUE TITLE
Improve design styling of share-to-post dialog

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5126]
### Steps to reproduce the behavior
1) From another app select a picture or text and click the Share action
2) Select WordPress

The site picker dialog functions well, but could probably use a design refresh.

![image](https://cloud.githubusercontent.com/assets/7233112/22655814/50f84b00-ec5f-11e6-91d3-0f214e7c1939.png)

**Comment by tonyr59h** [comment]
I'm going to give this a whirl and try to adhere to Android standards. Going to add a `Cancel` button and use the flat style. Since the `Add to` option only has two choices would it make sense to ditch the spinner for option buttons or something else? cc @mattmiklic

**Comment by mattmiklic** [comment]
> Since the Add to option only has two choices would it make sense to ditch the spinner for option buttons or something else?

Yeah, if there's only a couple of options and they'd all fit on one screen, radio buttons seem like the right approach.

I haven't spent a ton of time on this, but I took a quick stab at mocking this screen up in the current Material Design visual style.

![share-to](https://cloud.githubusercontent.com/assets/1396552/26175670/67251e74-3b21-11e7-9add-307c98cdceaa.png)
