### ISSUE TITLE
Add help information to Post Settings page

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5127]
### Steps to reproduce the behavior
1) Start a new post
2) Tap the gear icon to open the Post Settings dialog

Many of the options here are a little confusing for a new user not familiar with WordPress.  It would be nice to add little help badges next to the various settings to provide pop-up context.  Or at least a link to the help documentation online.

Specific questions that were raised: What does “Post format” mean? What’s the difference between Categories and Tags? What’s the purpose of the Excerpt, and why is it a single line? etc.

**Comment by maxme** [comment]
Here is the badge indicator and tooltip in Calypso:
<img width="455" alt="screen shot 2017-03-21 at 11 07 00" src="https://cloud.githubusercontent.com/assets/40213/24142358/9f8509fa-0e26-11e7-8ce7-aba52cb302ff.png">

I'm not sure what's the best option to add this on Android. We could just add the help text as a placeholder in Excerpt:

<img width="373" alt="screen shot 2017-03-21 at 11 10 11" src="https://cloud.githubusercontent.com/assets/40213/24142681/99244700-0e27-11e7-84a0-b34ef4ed3fd4.png">


[Tooltips](https://material.io/guidelines/components/tooltips.html#tooltips-tooltips-desktop) exist in Material design (accessible via tap+hold), but I'm not sure this will help anyone.

cc @mattmiklic

**Comment by oguzkocer** [comment]
> Tooltips exist in Material design (accessible via tap+hold), but I'm not sure this will help anyone.

Tap & hold doesn't seem intuitive here to check out a tooltip, but it's probably better than not having anything else.

What do you think @mattmiklic?

**Comment by tonyr59h** [comment]
Will you be addressing this one with your Post Settings project @oguzkocer?

**Comment by oguzkocer** [comment]
@tonyr59h Yeap, this should be handled as part of the Post Settings changes. Thanks for having a look!

**Comment by oguzkocer** [comment]
Unless there is something specific we missed, this is handled as part of the #5811 work.
