### ISSUE TITLE
Posts List: Consider opening drafts in Edit mode instead of Preview when tapping on card

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5128]
### Steps to reproduce the behavior
1) Create a draft post, then quit back to the Posts List
2) Tap on the card itself, not one of the buttons at the bottom

The question is whether this should open to the editor by default, or into the post preview like it does for published posts.  Personally I could see it go either way.  Both options are available from the toolbar on the bottom of the post, so changing the default behavior doesn't remove any functionality.  But keeping it to the Preview mode keeps the behavior consistent across all cards regardless of status.  If changing the behavior we also need to consider what should happen for scheduled posts.

The behavior on iOS is a little different.  If you click the card of a local draft, it opens up the editor.  But if you click the card of a draft post saved online, then it opens the preview.

**Comment by nbradbury** [comment]
Note that on the web, tapping a post always opens it for editing.

**Comment by maxme** [comment]
I'd drop all previews, the editor is now visual and it's looking exactly like the local preview (they use the same styles).

The only interesting preview is the "in situ preview" when a post is published (or saved as a draft) the user can view the post with his site theme + customizations. IMO that should be a specific action, not the default when you tap a Post List item.
