### ISSUE TITLE
Featured image not obvious when editing a post

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5130]
When a post has a featured image, opening the post in the editor gives no visual cue that there's a featured image. You have to go into the post settings to find that out.

It would be nice if there was something on the editor screen itself that indicated there's a featured image.

**Comment by catehstn** [comment]
Calypso shows the image above the post, which is a bit annoying (if it's a portrait image for example), but the visual cue is nice.
