### ISSUE TITLE
Primary domain URL doesn't update

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-Android#5132]
When changing the primary domain for a site, the app isn't updating to display the new URL.

Logging out and then in again will force showing the new URL, but future changes will once again be ignored.

**Comment by maxme** [comment]
That's probably fixed in the FluxC integration branch - added `fluxc-obsolete` label for future check.

**Comment by aforcier** [comment]
In the FluxC integration branch:

1. Signed into a WP.com site
2. Changed the primary site in Calypso
3. Confirmed that the site URL can be updated by moving the app to the background and re-opening it
4. Confirmed that the site URL can be updated by navigating away from the My Site fragment and back, e.g. by visiting the site settings
