### ISSUE TITLE
FluxC: Post list refresh progress bar stuck loading

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5135]
* Pull to refresh the post list and the progress bar will be visible
* Before the request finishes tap on the new post button
* Create a new post
* When you go back to the post list, both the new post progress bar and the refresh one will be visible
* After the request for new post finishes that progress bar will go away, but the refresh one will stay forever

![double loading](https://cloud.githubusercontent.com/assets/662023/22694622/009e8872-ed59-11e6-8008-8785648efabc.png)
![forever](https://cloud.githubusercontent.com/assets/662023/22694620/0042841e-ed59-11e6-9862-c949af88ce27.png)

**Comment by oguzkocer** [comment]
@maxme I've spent quite a bit of time debugging this and found out the root cause of it. Here is what's happening and why it's a FluxC integration branch bug and doesn't exist in `develop`.

First off, here is the sequence of events in `develop`:
1. User starts a manual fetch in post list and navigates to post preview
2. Since the fragment is retained and not destroyed the `PostListFragment.onEventMainThread(PostEvents.RequestPosts event)`  still gets triggered so the necessary updates are done

Here is what happens in `feature/fluxc-integration`:
1. User starts a manual fetch in post list and navigates to post preview
2. The fragment is still retained but it will trigger the `onStop` event where we will stop receiving post store events
3. The request success block never happens and since we still retain the fragment it'll show up with the progress bar as well as relevant flags will still be set to fetching state

I am not sure what the correct solution here is. I _think_ we should reset the state of the fragment when it's resumed and make sure the info is used from `PostStore`. Afaik we shouldn't retain instances if we can help it, but from what I can tell the editor depends on the `PostListActivity` and it has `configChanges` flag, so I assume we are retaining the fragment & activities there for the editor.

**Comment by maxme** [comment]
fixed by #5151
