### ISSUE TITLE
FluxC: Reverting changes don't update post detail page

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5137]
* Edit a post and go back without updating the remote (keep the changes local only)
* Go back to post list, because the detail page won't update right now #5136 
* Go into the detail page and revert the changes
* Notice that the page is not updated

![local changes to revert](https://cloud.githubusercontent.com/assets/662023/22694931/0edfa5f0-ed5a-11e6-8e2e-d7366f73e795.png)
![reverted changes don t show up](https://cloud.githubusercontent.com/assets/662023/22694935/1197a6bc-ed5a-11e6-9adb-0efeb4b2901f.png)

**Comment by aforcier** [comment]
Fixed in #5141.
