### ISSUE TITLE
FluxC: make sure we don't migrate any kind Jetpack sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5140]
We must not migrate any kind of Jetpack sites when the app is upgraded to FluxC. It seems that Jetpack sites that are connected to non main wpcom account are migrated, see this example: https://github.com/wordpress-mobile/WordPress-Android/issues/5134#issuecomment-278127286

**Comment by maxme** [comment]
I have a patch ready, waiting for https://github.com/wordpress-mobile/WordPress-Android/pull/5044 to be merged.

**Comment by aforcier** [comment]
Fixed in #5147.
