### ISSUE TITLE
FluxC: Posts List, Trash a published post doesn't work

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5146]
I think we're missing a call to the delete action [here](https://github.com/wordpress-mobile/WordPress-Android/blob/b61f7d7e70d110cfffc399838031e371b7d35196/WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java#L535-L543).

**Comment by aforcier** [comment]
Fixed in #5146.
