### ISSUE TITLE
FluxC: most recent sites grouping is not working

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5149]
Most recent sites are not updated

In the example below I had "pony396" selected before opening the picker, so I should see it in the top of the list:
![screenshot-2017-02-10_10 55 53 787](https://cloud.githubusercontent.com/assets/40213/22822471/f2dfbd04-ef7f-11e6-9ac5-55a479da44cc.png)

**Comment by aforcier** [comment]
Fixed in #5150.
