### ISSUE TITLE
Editor: Contributors should not see the option to publish posts

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-Android#5163]
### Expected behavior

If my role on a site is Contributor, I shouldn't see an option to Publish in the editor. Instead of Publish, the primary action I see should be "Submit for Review."

### Actual behavior

When I use the app as a Contributor, and write a post, I see a big Publish button. If I click on it, the editor closes like normal. But if I navigate to my Posts list, I see that it's only been saved locally; it's not actually uploaded to my site at all. After a minute, I'll get a bad error message.

### Steps to reproduce the behavior

- Add a contributor to a site
- Login to the app as that user
- Open the editor
- Write a post and click Publish.

Current flow:
![androidflow](https://cloud.githubusercontent.com/assets/1396552/22900327/f99c8cb6-f1fb-11e6-9050-479a4d835a3b.png)

**Comment by rachelmcr** [comment]
We also have a more general issue about handling permissions better, which mentions publishing: https://github.com/wordpress-mobile/WordPress-Android/issues/1296

I think this is the most critical case, though, so we could leave it open to be addressed first.
