### ISSUE TITLE
Can you please help me out in integrating only wordpress login into my app

### ISSUE THREAD

**Issue by hasanarmsys** [wordpress-mobile/WordPress-Android#5175]
I am developing an app in which i want to add wordpress login.

I have explored your login part for Add self-hosted site. But i am facing difficulty in integrating it into my app.

So can you please help me out in integrating this login part into my app.

Thanks

**Comment by maxme** [comment]
You can have a look the [FluxC repository](https://github.com/wordpress-mobile/WordPress-FluxC-Android), it's a network and persistence library that communicate with WordPress sites.

The [example app](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/example/src/main/java/org/wordpress/android/fluxc/example/MainFragment.java) is a pretty good start.

You can join us on our [public Slack](https://github.com/wordpress-mobile/WordPress-Android#need-help-to-build-or-hack) if you want to chat.
