### ISSUE TITLE
FluxC - Media Integration - Media uploaded in the editor appears as thumbnail

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5176]
Media upload in the editor adds media the wrong place. I experienced some weird behavior in the Hybrid editor when uploading a picture: the image was add to the title a few times (randomly).

Also it seems the picture has the wrong size (I see a `?w=150` on the URL, which seems pretty weird)

**Comment by maxme** [comment]
Media misplacement was fixed by #5209, but the sizing issue still exist (I'm changing this ticket title)

**Comment by aforcier** [comment]
Fixed in #5213.

**Comment by aforcier** [comment]
Actually, leaving this open, we should re-confirm this fix for self-hosted site media uploads once that's fixed.

**Comment by maxme** [comment]
Confirmed this works on Self Hosted sites (`FileURL` field is correctly set).
