### ISSUE TITLE
Fluxc - Media Integration - Paging is broken in media browser

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5177]
Pagination is broken in media browser

**Comment by aforcier** [comment]
PR with FluxC-side changes needed for this fix: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/322

**Comment by aforcier** [comment]
Fixed in wordpress-mobile/WordPress-FluxC-Android#322 and #5251.
