### ISSUE TITLE
Aztec: Editor scrolls to top when content changes

### ISSUE THREAD

**Issue by akirk** [wordpress-mobile/WordPress-Android#5184]
### Expected behavior
Aztec editor retains the scrolling position even when loading images.

### Actual behavior
Aztec editor scrolls to the top.

### Steps to reproduce the behavior
Open a post in Aztec with a few images (that have not been loaded previously, thus showing a placeholder image), scroll down while they are loading.

**Comment by theck13** [comment]
@akirk, this has been fixed, merged into the [library](https://github.com/wordpress-mobile/AztecEditor-Android), and will be included in the next release.
