### ISSUE TITLE
Aztec: (Non-Aztec) posts are modified by just opening them

### ISSUE THREAD

**Issue by akirk** [wordpress-mobile/WordPress-Android#5185]
### Expected behavior
Old, non-Aztec posts stay unchanged.

### Actual behavior
Unknown changes are made to the post. Just looking at an old post flags it as containing "Local changes".

### Steps to reproduce the behavior
Open a post that has not been created with Aztec, don't change anything and go back. Toast will say "Changes saved" and post is flagged as "Local changes".

**Comment by hypest** [comment]
Cannot replicate with latest alps (`alpha-49`) so, closing this. Please feel free to reopen if still occurring. Thanks!

**Comment by akirk** [comment]
This is still the case whenever I open a post that was not created with Aztec (and already published) and back out again then it is still  flagged as with "Local changes" (in alpha-54). This is especially annoying with the "pending draft nudge" that is then triggered for this already published, unmodified post.

**Comment by hypest** [comment]
Reproduced against our Hogwarts blog. Will re-open the ticket now.

Thank you @akirk for the patience and for reporting again!

**Comment by hypest** [comment]
Hey @0nko , you might want to have a look at this when you get the chance. Thanks!

**Comment by mzorz** [comment]
While we still might want to follow up on this in Aztec internals if needed, we've come up with a solution to identifying actual changes in https://github.com/wordpress-mobile/WordPress-Android/pull/6610, which is landing in WPAndroid version 8.2

Closing this as of now, and thanks @akirk for reporting and your patience!
