### ISSUE TITLE
Aztec: Constant app crashes when using non-stock keyboards

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5186]
### Expected behavior
To be able to use any keyboard I want

### Actual behavior
The app crashes when using anything other than Gboard.  Tested with Google Voice Typing, Swype, Hacker Keyboard, and LastPass

### Steps to reproduce the behavior
1) Start a post
2) Type a word in the post body or title and press enter or space
3) Crash

At first it seemed like it was only crashing on pressing Enter (not space or selecting the autocomplete suggestion), but when I went to record this video it was crashing on everything.  

https://cloudup.com/chE-z_MDz2V

**Comment by akirk** [comment]
Also happens with Swift Keyboard, though 1Password keyboard works. Highly annoying!

**Comment by khaykov** [comment]
Fixed in the develop branch of Aztec. Stay put for an update!
