### ISSUE TITLE
Fluxc - Media Integration - Upload indicator doesn't show up in MediaBrowser

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5194]

**Comment by aforcier** [comment]
Note: Error handling and retrying also needs some work in the MediaBrowser (media not in store, store media doesn't match remote, etc...). Possibly worth a separate issue.

**Comment by maxme** [comment]
Upload indicator was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/5196
