### ISSUE TITLE
Featured image appears blank on local drafts in posts list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5197]
### Expected behavior

I expect the featured image for a post to appear above that post in the posts list.

### Actual behavior

If the post is a local draft, a blank space appears above the post in the posts list, but the featured image itself does not appear (even if the image was selected from the site's media library).

#### Screenshots

Post as a local draft:

![2017-02-16 12 39 49](https://cloud.githubusercontent.com/assets/8658164/23021815/bf4209f0-f445-11e6-8a66-e7c0d458f30a.png)

Post after saving it to the server as a draft:

![2017-02-16 12 40 20](https://cloud.githubusercontent.com/assets/8658164/23021823/c62fb532-f445-11e6-9bc6-947961dd4401.png)

### Steps to reproduce the behavior

1. Create a new post in the app.
2. Open the post options.
3. Set a featured image (selecting an image from the media library).
4. Go back to exit the editor. Note the blank space above the post in the posts list.
5. Open the post in the editor again.
6. Publish the post or change its status to Draft and save it. Note the featured image appears above the post in the posts list.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-35 (using visual editor)

**Comment by mzorz** [comment]
Closing via #6279
