### ISSUE TITLE
FluxC: Duplicate Jetpack site

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5201]
### Steps to reproduce the behavior
* Login with a .com account which has a Jetpack site connected to it
* Go into site picker and make sure the Jetpack site shows up
* Add your Jetpack site as a self-hosted site with the `+` button
* We should show a "Duplicate site" error in this case, since it's already added as a Jetpack site and using REST API, however a second site shows up.

The site objects for these 2 sites are different, as expected.

**Comment by aforcier** [comment]
Fixed in #5203.
