### ISSUE TITLE
Aztec (alpha-35) Editor UX

### ISSUE THREAD

**Issue by chrisfromthelc** [wordpress-mobile/WordPress-Android#5204]
When switching between HTML and Visual mode, the button for that should be a little more explicit as to which mode you're in.

**Visual Mode:**
![screenshot_20170216-092801](https://cloud.githubusercontent.com/assets/8002138/23030262/7adda762-f42a-11e6-8efd-a12eac3aa1b2.png)

**HTML Mode:**
![screenshot_20170216-092558](https://cloud.githubusercontent.com/assets/8002138/23030279/8390c344-f42a-11e6-8b68-9d6f9a6d80ab.png)

Although the lowlighting of the visual editor buttons is an indicator, I fear it is not plain enough for most users. It increases the potential of someone typing out a post, then switching to Visual mode and losing line breaks when Visual mode is activated, but no `<p>` tags have been generated.

**Comment by 0nko** [comment]
The toolbar has been redesigned and it is now what the current mode is.
