### ISSUE TITLE
Stats: Switch country flags to use emoji character rather than Gravatar

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Android#5206]
A new field, `flag_emoji`, will be available (or may already be) for representing the country's flag icon. Switch over to that instead of using the `flag_icon` URL. There was a Gravatar caching issue affecting the flag icons and while it is fixed it makes sense to use what's available without hitting the Internet again.

iOS issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/435

cc: @daniloercoli

**Comment by maxme** [comment]
Emoji flags were introduced in Android 5.0, so we can't use them instead of Gravatars. We'll fix #5303 by embedding icons or add missing Gravatars :/
