### ISSUE TITLE
FluxC - Media Integration - Editor: Add support for galleries

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5210]
I removed some unworking code in https://github.com/wordpress-mobile/WordPress-Android/pull/5208 that needs to be done in another way.

**Comment by aforcier** [comment]
I've renamed this issue to specifically address gallery support (from existing uploaded images).

Gallery uploading isn't supported until we replace the all-picker - I've opened a separate issue for that: https://github.com/wordpress-mobile/WordPress-Android/issues/5244.
