### ISSUE TITLE
Attempting to dowload an image from self hosted blog fails until third party server downloads it

### ISSUE THREAD

**Issue by couling** [wordpress-mobile/WordPress-Android#5222]
*It is worth noting that this issue has been detected on a self hosted blog where server access logs are redily available.*

### Expected behavior

- From the media view click (press) an image to view the attachment page.  
- From there click (press) the image.  
- Expected:  Download the actual image not a resized version.
- Also Expected: Download direct and not via third party servers.

 
### Actual behavior

- From the media view click (press) an image to view the attachment page.  
- From there click (press) the image.  
- Actual Behaviour: Initially the user is presented with "unable to view image".  If you retry in a few minutes the image loads.
- Also Actual Behaviour: Third party server from `192.0.99.x` to `192.0.101.x` downloads the image.  It appears that the image is being sent to the device via a third party server

Request from tablet:

    77.___.___.___ - - [19/Feb/2017:19:50:03 +0000] "GET /wp-content/uploads/2017/02/p1020442-01.jpeg?w=800 HTTP/1.1" 200 3328764 "-" "Mozilla/5.0 (Linux; Android 4.4.2; SM-T230 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36 wp-android/6.7".

![screenshot_2017-02-19-12-18-44](https://cloud.githubusercontent.com/assets/23001043/23105911/179a6aa8-f6de-11e6-80f0-5e80a72da28a.png)

Request from third pary server:

    192.0.101.168 - - [19/Feb/2017:19:50:08 +0000] "GET /wp-content/uploads/2017/02/p1020442-01.jpeg HTTP/1.1" 200 3321177 "-" "Photon/1.0"

![screenshot_2017-02-19-12-18-53](https://cloud.githubusercontent.com/assets/23001043/23105914/1fdd8a88-f6de-11e6-9543-1f8cd99e82d6.png)

### Steps to reproduce the behavior

1.  Set up self hosted blog
1.  Log in android tablet
1.  Upload an image
1.  From the Media view click the image
1.  From from the resulting view, click the image

##### Tested on [device], Android [version]

Samsung galaxy tab 4.  App Version 6.7 (downloaded from Play store).

**Comment by maxme** [comment]
Hi @couling, I confirm we use our service Photon to download, resize and optimize pictures on this screen. This makes the mobile experience faster (less data to download on the phone). The error "unable to view the image" error you got was probably a temporary hiccup or a client timeout.

**Comment by couling** [comment]
Hi @maxme.  Thanks for your response. No this is not temporary.  It has been a problem ever since I started using the app and is still an issue now.

I think the use of the Photon server should be switched off by default for self hosted blogs and the user should be given a setting to manually turn it back on.

This is for a number of reasons:

1. This exposes private / hidden content to third party servers without the user's knowledge or permission
2. [I suspect] this caches hidden content on third party servers without the users's knowledge or permission.
3. It can cause performance problems.  *I suspect this is the cause of the problems I see*.  Where the blog and device are located a long way from the Photon servers, but the blog and device are located close together, the round trip to / from the Photon server will cause performance problems.
4. It assumes that firewall rules between the blog and Photon servers match the rules between device and blog.  This is provably wrong on internal intranet blogs where the device is logged onto the internal network.

At the very least, this is broken for me (most likely because I am in the UK with a self hosted blog in the UK and the Photon servers are in America

**Comment by maxme** [comment]
@couling the privacy issue is definitely a good reason for us to remove this feature for self hosted sites. I'll check if there is a way to get resized version of the file from self hosted sites.
