### ISSUE TITLE
importing project gives many error

### ISSUE THREAD

**Issue by muthu1001** [wordpress-mobile/WordPress-Android#5226]

**Comment by muthu1001** [comment]
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\networking\SelfSignedSSLCertsManager.java

**Comment by muthu1001** [comment]
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\networking\SelfSignedSSLCertsManager.java
Error:(125, 49) error: cannot find symbol variable DB_SECRET
Error:(136, 50) error: cannot find symbol variable DB_SECRET
Error:(157, 55) error: cannot find symbol variable DB_SECRET
Error:(158, 55) error: cannot find symbol variable DB_SECRET
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\push\GCMRegistrationIntentService.java
Error:(32, 39) error: cannot find symbol variable GCM_ID
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\ui\accounts\helpers\CreateUserAndBlog.java
Error:(116, 44) error: cannot find symbol variable OAUTH_APP_ID
Error:(117, 48) error: cannot find symbol variable OAUTH_APP_SECRET
Error:(131, 44) error: cannot find symbol variable OAUTH_APP_ID
Error:(132, 48) error: cannot find symbol variable OAUTH_APP_SECRET
Error:(145, 44) error: cannot find symbol variable OAUTH_APP_ID
Error:(146, 48) error: cannot find symbol variable OAUTH_APP_SECRET
Error:(182, 44) error: cannot find symbol variable OAUTH_APP_ID
Error:(183, 48) error: cannot find symbol variable OAUTH_APP_SECRET
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\util\HelpshiftHelper.java
Error:(100, 50) error: cannot find symbol variable HELPSHIFT_API_KEY
Error:(100, 81) error: cannot find symbol variable HELPSHIFT_API_DOMAIN
Error:(101, 32) error: cannot find symbol variable HELPSHIFT_API_ID
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\ui\accounts\helpers\LoginWPCom.java
Error:(62, 66) error: cannot find symbol variable OAUTH_APP_ID
Error:(63, 50) error: cannot find symbol variable OAUTH_APP_SECRET
Error:(64, 50) error: cannot find symbol variable OAUTH_REDIRECT_URI
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\ui\accounts\login\MagicLinkRequestFragment.java
Error:(135, 46) error: cannot find symbol variable OAUTH_APP_ID
Error:(136, 50) error: cannot find symbol variable OAUTH_APP_SECRET
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\WordPress.java
Error:(235, 96) error: cannot find symbol variable MIXPANEL_TOKEN
Error:(529, 39) error: cannot find symbol variable GCM_ID
F:\WordPress-Android-develop\WordPress\src\main\java\org\wordpress\android\WordPressDB.java
Error:(247, 64) error: cannot find symbol variable DB_SECRET
Error:Execution failed for task ':WordPress:compileVanillaDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by muthu1001** [comment]
help me to solve this error

**Comment by maxme** [comment]
@muthu1001 please follow the instructions in the README: https://github.com/wordpress-mobile/WordPress-Android#build-instructions

**Comment by muthu1001** [comment]
where to create gradle.properties under word press folder or under the wordpress-Android_develop folder.
If I create that what are the lines to be included to make proper build.
1.for heap size, 2.for parallel mode, 3.Gradle selective when configuring projects & 4.Gradle daemon is used to run the build.
please clarify me
