### ISSUE TITLE
Remove links to old admin

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5227]
### Expected behavior
When I go to the first tab in the app and look for the last option in the menu "View Admin", I should be taken to Calypso.

### Actual behavior
Instead, I'm taken to the old admin (`wp-admin`).

### Steps to reproduce the behavior
1. Go to the first tab on the Android app
2. scroll down to the last option, `View Admin`
3. Tap on it
4. Watch the wp-admin console open

**Note** the same thing happens when you go to Themes -> current theme -> customise

**Comment by maxme** [comment]
IIRC that depends of the user's creation date.

**Comment by mzorz** [comment]
Interesting! - I think it might be time for us to just move on to Calypso, but I guess this is all a backend problem then. Been checking the code and we get the adminUrl from the `SiteModel` which is populated with data coming from the server.
