### ISSUE TITLE
Decoding image without resizing

### ISSUE THREAD

**Issue by struggggle** [wordpress-mobile/WordPress-Android#5232]
Dear developers,

When loading an image, Google suggests us to resize the image before decoding them, so as to save memory resource and avoid OutOfMemory exception. 
https://developer.android.com/topic/performance/graphics/load-bitmap.html#read-bitmap
" To avoid java.lang.OutOfMemory exceptions, check the dimensions of a bitmap before decoding it, unless you absolutely trust the source to provide you with predictably sized image data that comfortably fits within the available memory "

I noticed that in the following code, image resizing is correctly applied:
org.wordpress.android.util.ImageUtils.java  doInBackground()
https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java#L243
https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java#L230

However, in the code below, images are decoded directly without resizing: 
(1) org.wordpress.android.util.ImageUtils.java   downloadBitmap()
(image is read from a url)
https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java#L151
(2) org.wordpress.android.ui.media.WordPressMediaUtils$BackgroundDownloadWebImage.java  doInBackground()
(image is read from a url)
https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java#L279

I am curious about the latter cases. Why these methods do not resize images? Do you think they will affect WordPress's performance?

For the images read from internet, in many cases, they are larger than required. Perhaps we should resize the images before decoding them, which can reduce time and memory overhead and help make app more smooth in user interaction.

Thanks.

**Comment by liufsd** [comment]
+1
