### ISSUE TITLE
Reader: Menu items are not Translated

### ISSUE THREAD

**Issue by nellofn** [wordpress-mobile/WordPress-Android#5240]
### Expected Behavior:
The Discover section should load in Spanish.

### Actual Behavior:
Discover module loads with English strings.

### Steps to reproduce the behavior:

1. Switch the app locale UI to Spanish (es)
2. Click the Reader icon
3. Reader menu items (Discover, Followed Sites, Posts I Like) shows in English

![image](https://cloud.githubusercontent.com/assets/17755234/23181621/08d537a4-f84c-11e6-9a58-405d2a47bd9c.png)

Tested on a Blu studio selfie phone, Android 5.1

**Comment by bluefuton** [comment]
Thanks for the report @nellofn!

Just to confirm, is it only the menu items which appear in English?

Do the the menu items appear in Spanish in other parts of the Android app (i.e. outside the Discover section)?

**Comment by nellofn** [comment]
The menu items and the section titles (Discover, Followed Sites & Posts I Like) appears in English. That is, if I click on any of those items, the title appears in English as well, though my guess is that both the menu items and titles uses the same string.

**Comment by tonyr59h** [comment]
[This comment](https://github.com/wordpress-mobile/WordPress-Android/blob/4a55fa018eb1634d811680a46afb473219aa346e/WordPress/src/main/java/org/wordpress/android/models/ReaderTag.java#L18) lead me to a pretty non-invasive fix.
