### ISSUE TITLE
Achievements: You've made your first post is not Translated

### ISSUE THREAD

**Issue by nellofn** [wordpress-mobile/WordPress-Android#5241]
### Expected behavior
Achievements should be displayed in Spanish when the locale setting is Spanish (es)

### Actual behavior
Achievements for: You've made your first post on _sitename_ is displayed in English

### Steps to reproduce the behavior

1. Create or login with a new WordPress.com account 
2. Switch the app locale UI to Spanish (es)
3. Publish your first post
4. The Achievement is displayed in English:

![achievements](https://cloud.githubusercontent.com/assets/17755234/23182384/bbcc42c4-f84e-11e6-81d1-d74ced65c223.png)

##### Tested on [device], Android [version]
Tested on a Blu studio selfie phone, Android 5.1

**Comment by maxme** [comment]
@mzorz or @daniloercoli  do you have an idea if we actually send localized push notifications? Does this use the language set in the account settings?

**Comment by daniloercoli** [comment]
@maxme Yes, we actually send localized push notifications, but you've to switch the language setting on wpcom. It doesn't use the device locale, instead PNs use the user-language setting on .com.

**Comment by mzorz** [comment]
:point_up: that what Danilo said :+1:
