### ISSUE TITLE
Re-introduce gallery uploading

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5244]
Since we've dropped the 'new picker' in the [original MediaStore integration PR](https://github.com/wordpress-mobile/WordPress-Android/pull/4616), we don't currently support using local images to create a gallery.

Some code relevant to gallery uploading was also removed in #5208 and #5242, which will need to be re-instated once we re-introduce galleries from local images.

**Comment by maxme** [comment]
I guess this feature will come back soon with https://github.com/wordpress-mobile/WordPress-Android/pull/5221
