### ISSUE TITLE
Several Lint Warnings on usage of deprecated APIs and ignored return value

### ISSUE THREAD

**Issue by FICIssuePivot** [wordpress-mobile/WordPress-Android#5247]
Hello,

I am using Lint to check for warnings in WordPress and found several valid warnings.
1.  **To support older versions than API 17 (project specifies 16) you should also add android:paddingRight="?android:attr/listPreferredItemPaddingRight"**
Similar warnings are found on line 18 and line 19 in [wp_simple_list_item_1.xml](https://github.com/wordpress-mobile/WordPress-Android/blob/master/WordPress/src/main/res/layout/wp_simple_list_item_1.xml#L18).
 [android:layout_alignParentStart](https://developer.android.com/reference/android/R.attr.html#layout_alignParentStart) and [android:layout_alignParentEnd](https://developer.android.com/reference/android/R.attr.html#layout_alignParentEnd) are not introduced before API 17. So they may not be effective on API lower than 17.

2. **Field requires API level 23 (current min is 16): android.view.KeyEvent#KEYCODE_NAVIGATE_NEXT**
The warning is reported on [line 90 in AbstractFragment.java](https://github.com/wordpress-mobile/WordPress-Android/blob/master/WordPress/src/main/java/org/wordpress/android/ui/accounts/AbstractFragment.java#L90)
This [field is introduced in API 23](https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_NAVIGATE_NEXT). It would be better to add a API level check before using it or may cause some unexpected problems.

3. **'getColor(int)' is deprecated**
Many warnings on this API are reported in the project (like in NoteBlockClickableSpan.java, ThemeBrowserAdapter.java, etc.) This API [is deprecated since API 23](https://developer.android.com/reference/android/content/res/Resources.html#getColor(int)) and I have found discussions on this API [here on StackOverflow](http://stackoverflow.com/questions/31590714/getcolorint-id-deprecated-on-android-6-0-marshmallow-api-23). New API is introduced to consider the theme when getting color.

4. **Result of <code>File.delete()</code> is ignored**
This warning is reported on [line 643 in PostUploadService.java](https://github.com/wordpress-mobile/WordPress-Android/blob/master/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java#L643). It is possible File.delete() may fail sometimes and if so, the file will always be there and consume disc space.

5. **Method execute must be called from the main thread, currently inferred thread is worker**
The warning is reported [on line 310 in org/xmlrpc/android/ApiHelper.java](https://github.com/wordpress-mobile/WordPress-Android/blob/master/WordPress/src/main/java/org/xmlrpc/android/ApiHelper.java#L310)
According to the official JavaDoc, execute(Params...) must be called from main thread. ([https://developer.android.com/reference/android/os/AsyncTask.html](https://developer.android.com/reference/android/os/AsyncTask.html) in section Threading rules)

6. Deprecated classes of apache http used in XMLRPCClient.java
I found warnings on usage of `org.apache.http.auth.UsernamePasswordCredentials` and `org.apache.http.client.methods.HttpPost`. These classes were deprecated and suggested to be buggy [https://android-developers.googleblog.com/2011/09/androids-http-clients.html](https://android-developers.googleblog.com/2011/09/androids-http-clients.html)

These are the valid warnings I have found in the project. Maybe some of them have already been noticed by you but still I hope this information can help.

**Comment by sudhirkhanger** [comment]
Would you prefer a single commit for all lint warnings or a maybe one commit for each of the lint warning?

**Comment by iadeelzafar** [comment]
If this issue has been resolved, I think this ticket can be closed.

**Comment by hypest** [comment]
Tried `gradlew lintVanillaRelease` on dc41909f75 and:
1. Not seeing `To support older versions than API 17...` anymore
2. Not seeing `Field requires API level... `anymore
3. Not seeing `'getColor(int)' is deprecated` anymore
4. Not seeing `Result of File.delete() is ignored` anymore
5. Not seeing `Method execute must be called from the main thread` anymore
6. Not seeing `Deprecated classes of apache http used in XMLRPCClient.java` anymore

That means that all the originally mentioned issues have been resolved.

**Comment by hypest** [comment]
Here's the follow up ticket with the latest warning: https://github.com/wordpress-mobile/WordPress-Android/issues/12098
