### ISSUE TITLE
Async publish: background upload

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5252]
Being stuck in the editor while pictures are uploaded isn’t a great experience.

The idea here is to build a service that takes care of all the hurdles of uploading, while letting the user use the rest of the app without caring.

- [x]  investigate current state of media upload service with FluxC
- [x]  design an upload service that doesn't depend on the Editor being present as it currently is
- [x]  be able to upload media files for different posts all at the same time
- [ ]  balance / queueuing to make the most of bandwidth (have n parallel upoads if possible, maybe even with a setting the user can change)
- [ ]  also, if a draft for which some media is being uploaded is DELETED while the transfer is in progress, the transfer should be canceled.
- [ ]  recover from errors automatically when possible
- [ ]  restart the service if not running or if pending uploads when app starts (phone off / on).
- [ ]  test for number of files and file size

**Comment by catehstn** [comment]
@aforcier I think this is relevant to your interests :)

**Comment by aforcier** [comment]
> @aforcier I think this is relevant to your interests :)

It certainly is! @mzorz and I had a quick chat about this, while I'm still rounding off things on FluxC he'll be studying the (somewhat extensive) changes to post and media uploads in the FluxC branch (and I'll be able to answer/deal with any FluxC questions that might come up).

By the time I've switched fully to media we'll hopefully have a clearer picture of what to do in what order and how it should all be allocated (cc @daniloercoli).

**Comment by mzorz** [comment]
Closing this issue as the stuff in here is being tracked elsewhere
