### ISSUE TITLE
FluxC: Set newly created WP.com site as current

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5262]
When a new WP.com site is created, we should set that site as the currently selected on automatically.

See TODO [here](https://github.com/wordpress-mobile/WordPress-Android/blob/9165eda5497437b9c95ea4f96e3608ddd7221b33/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java#L289) for WP.com case.

**Comment by oguzkocer** [comment]
Fixed in #5317.

As discussed on Slack with @maxme, the title and content of the issue changed to "setting the new wp.com site as current". A new issue will be opened for the self-hosted issue, so it can be handled separately.
