### ISSUE TITLE
MediaGridFragment: cursors never closed

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5269]
We never close the cursors used in the MediaGridFragment [here](https://github.com/wordpress-mobile/WordPress-Android/blob/13f27c86fab09237a7645f1fe35055b9fc011206/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java#L415-L415)

**Comment by nbradbury** [comment]
No longer an issue since we've dropped cursors from the MediaGridFragment in #5506
