### ISSUE TITLE
FluxC: Trashing comment doesn't show it in Trashed for a while

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5281]
I don't know if this is an integration issue or a FluxC one, but I thought it's better to open it here. When I trash a comment and switch to "Trashed" filter, the comment doesn't show up there. It does an auto-fetch due to changing the filters, but it doesn't show up after the fetch either. Most likely that's because the comment trash request is not yet completed, or it's a caching issue. I'd expect for us to change the status of a comment to "Trashed" when this happens, at least after the trashing request is completed and throw an event, so the list is updated.

**Comment by oguzkocer** [comment]
It turns out we don't actually moderate the comment until the "Undo" bar is hidden. That's the reason of the delay and I think this behavior is more important than showing the trashed comment immediately in the "Trashed" list. Unless we're willing to do a hacky solution (not sure if that will even work) , I don't think it's worth trying to fix this.

https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsActivity.java#L268-L291

/cc @maxme

**Comment by maxme** [comment]
Yes, we that for all undo actions, because it's easier to delay the action than really undoing (reversing) it.

**Comment by oguzkocer** [comment]
> Yes, we do that for all undo actions, because it's easier to delay the action than really undoing (reversing) it.

Definitely agreed! I just wasn't familiar with how it worked, so while testing yesterday, I thought it was a bug.
