### ISSUE TITLE
Aztec: Can't delete a title properly

### ISSUE THREAD

**Issue by mikeyarce** [wordpress-mobile/WordPress-Android#5299]
### Expected behavior
That I would be able to delete my Post title, using the backspace key

### Actual behavior
I can't delete it, the cursor keeps going to the wrong place.  Sometimes I can't delete the whole thing and it leaves 1 character there that's impossible to delete.  Other times I can delete it but it's not an easy task.

### Steps to reproduce the behavior
1. Add a title to a Post
2. Try using Backspace

Here's a video!
![out](https://cloud.githubusercontent.com/assets/3220162/23412215/baa7eb1a-fd89-11e6-8dce-70318c41c354.gif)

##### Tested on [device], Android [version]
Pixel XL, 7.1.1

**Comment by 0nko** [comment]
Thanks for the report. This is a known bug on Nougat. We are already tracking this issue [here](https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/213). So I'll close this one.
