### ISSUE TITLE
Add link to premium themes selector in Themes section in app

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5310]
Currently the apps only offer free themes. We want to let our users know there are premium themes they can obtain in the web.

I'd add it right below the search bar after you tap on it (the "Current theme" section is hidden and the search tab gains a prominent space occupying the whole header space), so this way we are sure the user is attempting to search for a theme as their intent is clear.

This is the action that makes the search bar go to the top, hiding the "Current theme" section: 

![themes](https://cloud.githubusercontent.com/assets/6597771/23467508/0318c128-fe7d-11e6-8c44-eec21f7d275e.gif)

This is the place we'd use for the CTA:

<img width="525" alt="screen shot 2017-03-01 at 12 46 32 pm" src="https://cloud.githubusercontent.com/assets/6597771/23467560/244a17d4-fe7d-11e6-8f93-327694251098.png">

Something like  **“Hey, want more? We have premium themes! go here <link>”.**

Link is `https://wordpress.com/design/premium/<site domain url>`

**Comment by bysl** [comment]
Placement sounds good!

Here is a suggestion for the copy:
Browse premium themes for more options > 
or even
Browse premium themes for more >

**Comment by mzorz** [comment]
Checking in with the rest of the app I can see there's this button for Plans here:

![screenshot_20170306-143208](https://cloud.githubusercontent.com/assets/6597771/23625816/3c182ea4-0289-11e7-8994-cefffec83f47.png)

So this is how it would look like if we placed the button there at the bottom, which I think looks better as you can see the results from filtering and _then only_ if nothing is of your choice as you scroll down, there's the button suggesting you can still look for more alternatives by pressing it. Does it still sound good @bysl ?

![themes2](https://cloud.githubusercontent.com/assets/6597771/23625840/4fab3e84-0289-11e7-8951-4ee2d10563e1.gif)

(the proxy error in the end is just because of my emulator configuration)
