### ISSUE TITLE
FluxC: Set newly added self-hosted site as current

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5325]
When  the user adds a self-hosted site, we should set that site as the currently selected on automatically.

See #5262 for the newly created wp.com site version and #5317 for it's fix.

**Comment by oguzkocer** [comment]
Changed the label to `fluxc` since this is not a priority for us.

**Comment by rachelmcr** [comment]
I just noticed this issue after adding a self-hosted site to the app. I thought there might have been a silent failure, until I found the site listed in the site picker.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-56

**Comment by oguzkocer** [comment]
@maxme Do you think this should be a part of `Broken Windows` project?

**Comment by gingerling** [comment]
+1
