### ISSUE TITLE
Disable undo/redo buttons when can't perform the action

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#5331]
### Expected behavior

If we can't perform the undo/redo action due to being on the start/end of the history, the buttons are disabled.

### Actual behavior

The buttons are always enabled.

### Steps to reproduce the behavior

Edit something in the editor and then tap on undo. Notice that even though there is no more history, the button is still enabled.

**Comment by theck13** [comment]
This should be possible with https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/252.  The [changes made to the `MainActivity`](https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/252/files#diff-080f87f4de5c976596b3984cb842ba65) of the demonstration app can be mimicked in the WordPress app to implement it.

**Comment by 0nko** [comment]
I know, I just added it here because someone mentioned it on Mobile requests, so I wanted to make sure we wouldn't forget about it.

**Comment by nbradbury** [comment]
Just wanted to add that we'll probably want to disable undo/redo when "media mode" is enabled, ie: `formattingToolbar.isMediaModeEnabled()`
