### ISSUE TITLE
Jetpack: Add back all roles in the invitation screen for Jetpack sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5355]
Due to a limitation in Jetpack , we had to hide all roles except "Follower" from the invitation screen for jetpack sites - Ref https://github.com/wordpress-mobile/WordPress-Android/pull/5350#issuecomment-285349919. When this limitation is solved, we should add hidden roles back.

Related to https://github.com/Automattic/wp-calypso/issues/11107

**Comment by elibud** [comment]
This has been fixed, right @oguzkocer ?

**Comment by oguzkocer** [comment]
This looks to be working in current `develop`.
