### ISSUE TITLE
Alert the user to canceled video upload when leaving editor

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5371]
### Expected behavior
To either allow for background uploading of media, or warn me when an upload is canceled

### Actual behavior
If you leave the editor while a video is uploading, it silently fails and is removed from the post.  The same action during a picture upload leaves a placeholder for the image that indicates the upload failed, and alerts you to the error when you attempt to publish.

### Steps to reproduce the behavior
1) Create a new post and insert a video
2) Navigate away while the video is uploading
3) Return to the editor for that post and notice it's empty

##### Tested on Nexus 6P, Android 7.1.2, wp alpha-38

**Comment by maxme** [comment]
We should probably close this ticket, background uploading is coming via https://github.com/wordpress-mobile/WordPress-Android/issues/5252
