### ISSUE TITLE
Photo chooser: smarter fragment attachment

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5394]
As mentioned by @mzorz [here](https://github.com/wordpress-mobile/WordPress-Android/pull/5386#issuecomment-286444354), look into whether it makes sense to check whether the photo chooser fragment is already attached before attaching it.

**Comment by designsimply** [comment]
@nbradbury it looks like the photo picker moved to its own package under ui soon after this request was made and I saw it had quite a few commits since then. Could you let me know if it's still worth looking into?

**Comment by nbradbury** [comment]
@designsimply I think it's safe to close this.

**Comment by designsimply** [comment]
Oops. Didn't close this before but am closing it now because a lot of changes have been made to the media picker since the original request. Please file any problems you find in a new issue and they will be triaged from there!
