### ISSUE TITLE
Categories: only syncing default 100 categories

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-Android#5395]
As seen on iOS https://github.com/wordpress-mobile/WordPress-iOS/issues/6861, it looks like we're also only syncing the default 100 categories via REST for Android:

https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/networking/WordPressNetworking/src/main/java/org/wordpress/android/networking/RestClientUtils.java#L90

Also sorta-fixed for iOS in https://github.com/wordpress-mobile/WordPress-iOS/pull/6862

**Comment by aforcier** [comment]
Just noting that FluxC [already requests](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/277) the maximum number (1000) of categories from the REST API.

However, we haven't migrated categories in the WP.com site settings screen to FluxC yet ([TODO](https://github.com/wordpress-mobile/WordPress-Android/blob/cb401debe9e4aaa7be04f80e014c2babcc1516dc/WordPress/src/main/java/org/wordpress/android/ui/prefs/DotComSiteSettings.java#L333)) - but we are using FluxC for categories when they're used in posts.

**Comment by kurzee** [comment]
@aforcier awesome! I'll go ahead and close this out then.
