### ISSUE TITLE
Media library doesn't show unicode filename properly

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5397]
### Expected behavior
Image with Unicode in the file name shows correctly

### Actual behavior
Unicode file name is not shown properly.

### Steps to reproduce the behavior
Add an image with unicode in title (e.g.: `长名字.png`) from desktop browser.

From Android app, create a new post, insert media and try to `Create gallery`. In the image selection, unicode title is not shown properly.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

![unicode](https://cloud.githubusercontent.com/assets/1484624/23934510/17dc00bc-0903-11e7-97ad-8a606c8c3fae.jpg)

**Comment by daniloercoli** [comment]
cc @nbradbury

**Comment by nbradbury** [comment]
We can close this one since we'll be dropping filenames shortly - see #5407
