### ISSUE TITLE
Previously added video in media library unable to be loaded

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5399]
### Expected behavior
Video shows thumbnail correctly in media library

### Actual behavior
It shows `Loading...` forever

### Steps to reproduce the behavior
Add a video from Android app in a post. 
Start a new post, try to insert an image gallery. In the media library, notice the video stays as `Loading...` forever.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

![loading](https://cloud.githubusercontent.com/assets/1484624/23935235/03bbebec-0908-11e7-9397-4774693441da.jpg)

**Comment by nbradbury** [comment]
Just looked into this and I believe the description is incorrect. That "loading" indicator isn't related to the video, instead it's related to infinite scroll - ie: the user scrolled the media grid to the point that more items need to be loaded.

I'm not sure why it would get stuck in that loading state, but the media browser has been substantially rewritten over the past few months and it's very likely this problem no longer exists. At any rate, I tried many times to reproduce it but was unable to.
