### ISSUE TITLE
Gallery setting not obvious

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5402]
### Expected behavior
More clear hint there is more gallery settings at the bottom

### Steps to reproduce the behavior
After select images to be added to image gallery, the `Gallery setting` button at the bottom is not very obvious. Without the arrow on it in the first place, user hardly notices it has a pull up settings menu:
![gallerysetting](https://cloud.githubusercontent.com/assets/1484624/23935418/2a946e5a-0909-11e7-9dfa-3834bcd19ef0.jpg)

After click on it, and pull down the menu, it will show the arrow. If we show this arrow in the first place, it will make it more clear and obvious to the user:
![gallerysetting2](https://cloud.githubusercontent.com/assets/1484624/23935435/3cab3b5a-0909-11e7-8fc2-9a9fc770af9b.jpg)

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

**Comment by nbradbury** [comment]
Closing this since gallery creation was rewritten in #5805
