### ISSUE TITLE
No Done or Next option in the gallery creation process

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5403]
### Steps to reproduce the behavior
After the image selection is finished, user has to click on the **back** arrow to go the **next** step, which is a bit counter intuitive.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

![nodone](https://cloud.githubusercontent.com/assets/1484624/23935489/83847f50-0909-11e7-9a6c-ea894a097428.jpg)

**Comment by nbradbury** [comment]
Closing this since gallery creation was rewritten in #5805
