### ISSUE TITLE
Reverse button in Gallery setting is not clear on what it does

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5404]
### Expected behavior
A better name of some visual effect on Reverse button

### Steps to reproduce the behavior
The `REVERSE` button in Gallery settings is not clear to the user what it actually does.

After clicking on it, there is no visual effect change to be seen, user will be likely to try it multiple times which could revert the effect and causes more confusion.

And not quite clear why only this option is all capital letters.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

![reverse](https://cloud.githubusercontent.com/assets/1484624/23935573/d10e3cb6-0909-11e7-980e-ec5954dfbf98.jpg)

**Comment by nbradbury** [comment]
We can close this since the reverse button was dropped in #5771.
