### ISSUE TITLE
Stop uploading confirmation confusion

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5406]
### Expected behavior
When asked "Stop uploading", a simple "Yes" or "No" is more clear

### Actual behavior
Both "CANCEL" and "STOP UPLOAD" sounds a yes to me somehow

### Steps to reproduce the behavior
Create a new post, insert a video, and try to abort in the middle of upload.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

![stopcancel](https://cloud.githubusercontent.com/assets/1484624/23935714/ab01a606-090a-11e7-82ea-7b3b26d98eb1.png)

**Comment by tonyr59h** [comment]
Many of the existing prompts in the app go with the OK/Cancel nomenclature (as opposed to Yes/No). I'm going to move forward with consistency in mind and use OK/Cancel.
