### ISSUE TITLE
Site name should be clickable on My Sites tab

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5413]
### Expected behavior
To be able to tap the card with my site name at the top of the My Sites page and view my site, similar to the action in Calypso web

Note that with this action we could drop the "View Site" button from the External section

### Actual behavior
Nothing

### Steps to reproduce the behavior
1) Open the app
2) Navigate to the My Site(s) tab
3) Tap on your site name

##### Tested on Nexus 6P, Android 7.1.2, wp alpha-39

**Comment by maxme** [comment]
Dup https://github.com/wordpress-mobile/WordPress-Android/issues/4055
