### ISSUE TITLE
Reader: track the correct ID when blocking a site

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5429]
As noted [here](https://github.com/wordpress-mobile/WordPress-Android/pull/5421#pullrequestreview-27300804), we should probably be tracking the ID of the blocked site rather than the current site.

@aerych What does the iOS app do in this situation?

**Comment by aerych** [comment]
> What does the iOS app do in this situation

Tracks the ID of the blocked site.
https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/ReaderSiteService.m#L192
