### ISSUE TITLE
Stats item feels cramped

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5441]
Should we add some padding? Or a section title?

![cramped-stats-item](https://cloud.githubusercontent.com/assets/40213/24070546/0fb5d45c-0bc0-11e7-9e4e-ae2c3adc7791.png)

**Comment by mattmiklic** [comment]
I'd just add a bit of padding above Stats. While you're in there, look at the padding between the "External" header and the View Site link; it looks like there's more padding/spacing there than between the "Publish" header and the Blog Posts link.

**Comment by tonyr59h** [comment]
> it looks like there's more padding/spacing there than between the "Publish" header and the Blog Posts link.

Things only a designer could notice 😮 

I checked with Android Device Monitor just to be sure (you're right, ofc). All the headers are spaced equally except for `External`.

**Comment by tonyr59h** [comment]
As for the `Stats` spacing, I'm going to get it space it consistently with the other items. It should look right if I pretend the bottom of the `Switch Site` container is like the bottom of the header titles.
