### ISSUE TITLE
Post list: duplicate featured image

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5442]
Happened on a Jetpack site (That could happen on other sites).

Posts have all different featured images but the same (garage shelves) is used.
![screenshot_20170317-084746](https://cloud.githubusercontent.com/assets/40213/24070566/7211b7e2-0bc0-11e7-8df2-780509bc390b.png)

**Comment by oguzkocer** [comment]
@maxme Any idea about how to reproduce this? By any chance, do you remember what you might have done before this happened?
