### ISSUE TITLE
Media - cannot upload videos - 7.0-rc3

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5464]
It seems that I cannot upload any video on 7.0-rc3.

![device-2017-03-21-115210](https://cloud.githubusercontent.com/assets/518232/24144348/2b55a3da-0e2d-11e7-9d2f-ccdd6d117190.png)

![device-2017-03-21-120031](https://cloud.githubusercontent.com/assets/518232/24144570/0e335ab2-0e2e-11e7-986d-508682c19da1.png)

cc @aforcier

**Comment by aforcier** [comment]
Hmm I'm able to upload videos on `alpha-41` - where on the device is the video coming from? We should have flushed away any leftover empty media from https://github.com/wordpress-mobile/WordPress-Android/issues/5417, but it's possible that didn't work for you for some reason.

**Comment by daniloercoli** [comment]
As per chat conversations and debugging, this issue happened because I uninstalled the app when there were old 0-bytes videos in the cache folder.

Upon re-installation, the 0-bytes files cleaning routine (https://github.com/wordpress-mobile/WordPress-Android/pull/5425/commits/05395e659c6bf3ce73cde3c9b637b7aec958e45f) doesn't have access the cache folder since no permission were granted to the app. So those 0-bytes videos are still there and I tried to upload them.

@aforcier It's up to you to close this issue and maybe opening a new one for the cleaning issues.

**Comment by aforcier** [comment]
@daniloercoli I opened this issue to track rethinking the media cache: https://github.com/wordpress-mobile/WordPress-Android/issues/5468

For empty files specifically, they'll only persist for alpha/beta users who uninstall the app before installing the new version, and even then they'll be cleared the first time they do an app upgrade in the future anyway. Given that, I think we can close this.
