### ISSUE TITLE
Improve Helpshift tags to identify more paid upgrades

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5469]
We currently tag Helpshift issues with the WordPress.com/Jetpack plan on each site the user has in the app (https://github.com/wordpress-mobile/WordPress-Android/pull/4653). We use those tags to identify users with paid upgrades for priority support. However, this excludes users with paid upgrades but no plans, e.g. custom domains.

We should identify WordPress.com accounts/sites with any paid upgrade (not just plans) and add a tag to those Helpshift conversations to identify the upgrade.

**Comment by ScoutHarris** [comment]
During the Zendesk implementation, we discussed and implemented HE desired tags. I'm closing this. If the HEs need additional tags, we can open ZD related tickets.

(cc @oguzkocer )
