### ISSUE TITLE
Remove the PIN lock feature from the app

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5477]
Remove it from the app and remove the settings in App Settings.

Before we remove it, we should:
1. One version before the removal, we should alert PIN lock users (via a dialog on startup) that this feature will be removed, and propose them a better way to share their phone (using a Guest account on their phone). Add a page in the Helpshift FAQ and have a shortcut to open it.
2. On upgrade, show the same dialog for the users who still have the feature enabled, and add a "contact us" button that redirects to helpshift.

**Comment by maxme** [comment]
Relevant: https://support.google.com/pixelphone/answer/6115141

**Comment by daniloercoli** [comment]
We should also mark the library as deprecated / not supported anymore on the relevant gitHub repo.

**Comment by rachelmcr** [comment]
The pin lock was removed in https://github.com/wordpress-mobile/WordPress-Android/pull/8236 and the README for https://github.com/wordpress-mobile/PasscodeLock-Android notes that it is not maintained. Closing as resolved.
