### ISSUE TITLE
Reader: tap to open image link

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5478]
Right now tapping an image shows it in a fullscreen gallery, which prevents tapping a hyperlinked image to navigate to the link.

Calypso dropped the gallery, so perhaps we should drop that feature entirely (?). If not, we should decide between not showing the gallery when the image is linked, or changing the gesture which shows the gallery.

**Comment by fraying** [comment]
@aerych reports: "Currently the iOS reader will display a larger sized image if the image does not have a link.  If the image was wrapped in a link, the link is opened."

Could we do the same here?

**Comment by fraying** [comment]
Ultimately, I'd like us to move away from the "tapping on an image shows just the image" behavior altogether. It's kind of oldschool. The newschool is a pinch-to-zoom on the image (check it out in the Instagram stream - it’s the bomb).

Personally, 9 times out of 10, when I tap an image, I actually meant to check to see if it was linked somewhere, or did something, or it's an accidental tap. So when it just takes up the whole screen, I’m annoyed.

**Comment by nbradbury** [comment]
> Could we do the same here?

Yes, I'll change the Android reader to work the same as iOS.
