### ISSUE TITLE
Media Library - The "state" of items seems to be inconsistent

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5483]
I was testing uploading in the Media Library and found out a couple of issues that I think are all related each other. So i'm opening this single issue, but feel free to decouple, if they're different issues.

Issue 1 (Video here: https://cloudup.com/cbfyyY7d-4l )
- Not sure how, but I found myself with 2 items in the "Uploading" state in the library. Only one should be in the uploading state, and the other one should be in the "Queued" state.
- Adding a new item to the queue switches the status of the 3 new items to "Queued" and the spinning is running on the top of the text.

Issue 2 (Video here: https://cloudup.com/cCKVhkgeRl7 )
- Starting from an incoherent state where all the 3 items are in the "Queued" state.
- PTR and the state issue seems to be fixed. Again, not sure why there is the spinner running in the Queued state though.
- Single click on the queue files does nothing, or it's hard to tap on the correct area to open the details screen.
- Long clicked, selected an item in the Queued state, and selected Delete. All the 3 items disappeared from the screen. When I did PTR the one in the uploading state reappeared on the library.

Issue 3 (Video here: https://cloudup.com/chaZh-1rFwl )
- Long click are enabled on the items in "Uploading" state. It should not be enabled I think.
Only the single tap to stop the uploading should be available. (Open to suggestions on this).

cc @nbradbury

**Comment by nbradbury** [comment]
> Again, not sure why there is the spinner running in the Queued state though.

Resolved in #5488

**Comment by nbradbury** [comment]
> Long click are enabled on the items in "Uploading" state. It should not be enabled I think.
> Only the single tap to stop the uploading should be available.

Based on a Slack discussion about this, we're going to enable long-pressing any non-deleted item. If an uploading item is selected and deleted, we're going to cancel the upload. @mzorz is currently working on adding the ability to cancel an upload when multiple uploads are underway.

**Comment by daniloercoli** [comment]
Steps  to replicate no. 1 (I think all of them are related, so fixing one will fix almost all of them) 👍 
- Go to Media Library.
- Tap the '+' button to add a new media, select `capture photo`.
- Take a new photo and approve it.
- The app shows the item with the correct `Uploading` state and the loading spinner. 
- Tap the '+' button to add a new media, select  `capture photo`.
- Take a new photo and approve it.
- The app shows the 2 new items in the `Queued` state. 

Optional:
- Don't touch the device or do anything. Wait until the uploading of the first item finishes.
- The app refreshes the screen and the 2nd item is correctly shown as "Uploading.

**Comment by mzorz** [comment]
Just FYI - I will test and tackle this as part of the multiupload/multicancel WIP tests, when integration is done 👍

**Comment by mzorz** [comment]
Feedback collected from @nbradbury for later reference: ```* I attached two videos to a post, then viewed the media browser and saw a RETRY item and a QUEUED item. Not sure if this is in any way related to async changes, but I found it odd that it didn't automatically retry, and that the QUEUED item was apparently stuck until I retried the other item.```

**Comment by mzorz** [comment]
I think this should be ready since https://github.com/wordpress-mobile/WordPress-Android/issues/6515 has been there. @daniloercoli would you like to test it again and confirm whether we still have any erratic behavior?

**Comment by daniloercoli** [comment]
I'm going to close this post since the original issue seems fixed, even though I found other glitches with Media in Aztec + Media Library. Will open new tickets for those.
