### ISSUE TITLE
Unable to load more than 20 pages

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5487]
Only the first 20 pages on the site are loading on the Pages list. If you scroll down to the bottom of the list, you get a loading indicator but the rest of the pages don’t load.

**Comment by aforcier** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/387.

**Comment by aforcier** [comment]
wordpress-mobile/WordPress-FluxC-Android#387 merged - I'll close this issue once `release/7.0` has the updated commit hash to include the fix.

**Comment by maxme** [comment]
Done in https://github.com/wordpress-mobile/WordPress-Android/commit/f33a1f227a8fa12345c40c7e5ddd93144c8f25e3
