### ISSUE TITLE
Reader: missing posts

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#5491]
### Expected behavior

All posts that I see at https://wordpress.com/ with a browser also appear in Reader on WPAndroid.

### Actual behavior

Posts are missing in Reader on WPAndroid compared to viewing on the web.

### Steps to reproduce the behavior

1. Go to Reader in WPAndroid and browse posts.
1. Look for any large gaps in time such as from 5h to 2d.
1. Compare to https://wordpress.com/ in a browser to see if any posts are missing while viewing Reader in WPAndroid.

Note: I don't check Reader on WPAndroid every day. I can't remember exactly, but it's likely I haven't checked Reader on WPAndroid in 2d and that could be why the gap starts at that time for me.

<img alt="screenshot_20170323-161509" src="https://cloud.githubusercontent.com/assets/1119271/24272980/859b3076-0fe5-11e7-8ea5-54ec7bae7855.png" width="360" />

![screen shot 2017-03-23 at thu mar 23 4 16 59 pm](https://cloud.githubusercontent.com/assets/1119271/24272994/986da634-0fe5-11e7-9623-1856cb27f4d0.png)

Maybe related: #3908

**Comment by catehstn** [comment]
I sometimes see this on the web - especially after the weekend when it's like it doesn't load all the posts that happened between then and when I last refreshed.

**Comment by KokkieH** [comment]
Another report of this via 850116-f

The user reporting this is using Android 6.0.1, WPAndroid 7.0

I was also able to confirm on a Nexus 5X, Android 7.1.2, WPAndroid 7.1

**Comment by mikeyarce** [comment]
I came to report this today!  I've been noticing this a lot and it basically means I can't use the Reader for the Android app because it misses too many posts.

Today I found it missed 37 posts, whereas just using the browser showed everything.  I've reported this in the past and the suggestion has been to just log out and log back in.  I think doing that will clear the Reader cache but at this point, I would need to do that every day in order to use the Reader.

**Comment by blowery** [comment]
On the web, we have a protocol for detecting gaps between the most recent set of updates and the most recent posts we have loaded. You can see that by visiting https://WordPress.com/?at=2017-01-01 and waiting for the update pill. Click the pill and scroll down and you'll see a "load more posts" button and will start to fill the gap. 

I thought the native apps had gap detection as well, but perhaps not? It works by comparing the last item in the update set to the first item in storage. If they're different, we mark a possible gap in the stream and show the according UI. 

We've been thinking about ditching the UI piece and just filling the gaps automatically, but have not written any code to do it just yet.

**Comment by blowery** [comment]
> I also wanted to say this is not specific to Android, but I have noticed this on the Desktop app as well. So I think it might be more of a Reader thing than an Android App thing.

That's more troubling. Is it mostly in the a8c stream, or the main following stream, or both?

**Comment by mikeyarce** [comment]
@blowery Good questions!  I should add that I normally see this when I use the "Load more posts" button - it just doesn't load all the missing ones.   I don't use the Reader for non-A8C stream Reading very much, but I will start looking at my regular stream to see if I notice any gaps.

I'll keep an eye on my Desktop App again.  When I opened it just now it needed an update, so I'll see if it's happening still after the update.

**Comment by catehstn** [comment]
Saw this again today. Contender for hack week, @koke ?

**Comment by loremattei** [comment]
I'm reopening this since it has been reported again with the last version of the app.

**Comment by designsimply** [comment]
This came up in a mobile request with the following description:

<blockquote>For example, I’ll see a post in my Reader that says it was posted 8 hours ago and the next post says it was published 3 hours ago…a 5 hour gap. But when I open up Safari or Chrome on my iPhone and log into WordPress and go to the reader, there is no such gap. All the “missing” posts between 8 hours ago and 3 hours ago are there.</blockquote>

<sup>(internal references: p4a5px-2mT-p2, 1852243-zen)</sup>

**Comment by designsimply** [comment]
Escalating from `[Pri] Medium` to `[Pri] High` because it has come up several times and we need to determine whether this is an issue that needs to be solved at the API level or whether it can be resolved within the WordPress mobile apps directly.

**Comment by thehenrybyrd** [comment]
Another app user has reported this in 19251520-zen.
Samsung SM-G930V, WPAndroid 12.0
The user sent us this screenshot:
![readergap](https://user-images.githubusercontent.com/15107387/55783076-4d5d0400-5ab6-11e9-8e0f-8d7d65ffc21b.jpg)

I was able to check what should have been in their reader at that time:
<img width="288" alt="noreadergap" src="https://user-images.githubusercontent.com/15107387/55783078-51892180-5ab6-11e9-87ed-23f593a1ed4d.png">
And there are many many posts after that Biden post and before the Sandwich Shop post.

**Comment by designsimply** [comment]
Noting some testing steps @oguzkocer helped me with:

1. Sign up for a new account at https://wordpress.com/start/user
1. Go to Reader > Followed Sites > Manage and unfollow everything.
1. Follow `oguzkocertest.wordpress.com`.
1. Log in to WPAndroid.
1. Go to Reader and refresh the list.
1. Go back to a browser (any other client) and follow another site such as `longreads.com`.
1. Switch to the Discover list.
1. Follow one of the sites from that list you weren’t following before.
1. Go to WPAndroid > Reader > Followed Sites.
1. Pull to refresh.
1. Scroll 19 posts.

**Result:** I see a gap but there is a clear separator and button named “Load more posts”. However, it appears some people do not get the "Load more posts" button and that's where the problem is happening.

<img src="https://user-images.githubusercontent.com/1119271/56435376-70956980-6295-11e9-9edb-a379b83715b5.png" width="270" alt="Screenshot_20190419-111640">
