### ISSUE TITLE
Default category and post format for WP.com/Jetpack sites aren't always respected

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5500]
When creating a new post, we set it up with the user's default category and post format for that site (currently, for WP.com and Jetpack sites only). However, this is currently only working if the user has visited the Site Settings for that site, and made a selection for the category and the post format - even though we've already fetched and stored the setting from the server.

When this occurs, we send a category of `0` to the server, which is replaced remotely with the real default category. The post format, however, we default to `standard`, ignoring the user's real default setting.

**Comment by nellofn** [comment]
@aforcier is this still in the works?

A colleague running Android 8.0.0 and the app version alpha-108 let me know over DM, that when she tries to publish a post, it keeps creating a new default “uncategorized” category. A default category was set before, but it’s not automatically selected when posting, therefore she end up with hundreds of posts in a category that she then had to delete (“uncategorized”).

**Comment by aforcier** [comment]
@nellofn I'm not sure that that's the same issue, though it's possible the result of the unset category is different now than it used to be. The bug as it was understood back then would have prompted the server to use the real default category - the only ill effect was in the post format.

No one really worked on this one and I don't recall the details - I'm adding the `groundskeeping` tag to this to make sure a groundskeeper takes a look at what's causing the "uncategorized" category creation.

**Comment by aforcier** [comment]
@malinajirka it looks like you're on duty this week, perhaps you might have some time to take a look at this?
