### ISSUE TITLE
Recent notification "not found" and blank notifications

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5528]
User reported a transient bug in notifications:

* New notification shows up in the notification list.
* Tapping through to either, get a "not found" error.
* After 20 secs, it just showed blank content (on the single notification detail screen).
* Then it started working fine.

Happened on alpha-43 (probably happen in 7.0 as well).

I think there is a missing loading indicator, or it's hidden. Not sure about the "not found error". Investigation needed.

**Comment by mzorz** [comment]
Going to look into this. 2 questions in the meantime:
1) do we know what kind of notification it was? (like? comment?)
2) are we talking about the system's notification dashboard or is it the notifications list within the app (4th tab)?
thanks in advance

**Comment by daniloercoli** [comment]
Fixed in #5538
