### ISSUE TITLE
Implement notification channels for Android O

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5530]
From the [doc](https://developer.android.com/preview/features/notification-channels.html
):

> Android O introduces notification channels to provide a unified system to help users manage notifications. When you target Android O, you must implement one or more notification channels to display notifications to your users. If you don’t target Android O, your apps behave the same as they do on Android 7.0 when running on Android O devices. 

Adding the "Blocking" label here, since it should be pretty easy to implement (one liner).

**Comment by mzorz** [comment]
We keep bumping this one to the next version :) - we could create a dummy "WP General" channel just to comply with the Android O requirement, but  I think we need input from UX design here before attempting to put a PR together. 
The design guidelines cover this extensively here: https://material.io/guidelines/patterns/notifications.html#notifications-settings

From that analysis, I'd expect things such as:
- channels themselves (i.e. Uploads? Comments? Activities? News?)
- importance
- Sound
- Lights
- Vibration
- Show on lockscreen
- etc

to be defined as an output, so we can properly turn that into code as described here https://developer.android.com/guide/topics/ui/notifiers/notifications.html#ManageChannels

On another note, we might also need to / could better use the predefined `categories` as well, for example `CATEGORY_PROGRESS` for the upload progress foreground notification, `CATEGORY_ERROR` for errors, `CATEGORY_MESSAGE` for Comments / Replies, etc.

What do you think @maxme ?

**Comment by maxme** [comment]
We have this in the notifications settings already (and users can pick there preferences for each site and sync with the Web version). So I'd keep one "dummy" channel + our notifications settings for now. And we can revisit this later.

**Comment by mzorz** [comment]
Closing via #7593
