### ISSUE TITLE
Bug report 7.0: Unable to open comments

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5544]
User review in the Play Store:

> The app was working perfectly till the last update. After the recent update I am unable to open comments written on my blog. Please fix it. This is a serious issue. In the notifications only the likes notifications opens up others show "unable to open" please fix this bug!

A second one:

> It's not showing comments since the latest update

I'm not sure if this is only related to notifications or if it's a problem in the Comment list.

**Comment by oguzkocer** [comment]
Fixed in #5549.
