### ISSUE TITLE
Detect post content upstream collision and stop

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5561]
With #4305 merged, there are a couple of cases where the user can be left in confusion or data get lost:

1. If a draft has already been changed via some other device or the web, auto-saving it online can create a new revision, effectively "hiding" the change that was made elsewhere
2. If it's a Jetpack site with the revisions feature turned off, auto-saving will overwrite what's already there with no way of getting it back.

So, we should probably try to detect when the auto-save can be confusing or catastrophic and stop the auto-save right there, keeping the changed locally only and perhaps offering the user some information of what happened and how to proceed (e.g. give the options to force-push or discard).

**Comment by hypest** [comment]
Hey @theck13 , since you're working on the Revisions/History project, is any part of this ticket relevant at this point? We can close it if not.

**Comment by theck13** [comment]
Revisions/History will allow users to view and load previous versions of pages and posts.

> If a draft has already been changed via some other device or the web, auto-saving it online can create a new revision, effectively "hiding" the change that was made elsewhere

In this case, users can view the "hidden" changes and apply them, but there is no automatic merging or way of notifying the user that changes have been made elsewhere after they started editing.

> If it's a Jetpack site with the revisions feature turned off, auto-saving will overwrite what's already there with no way of getting it back

Revisions/History won't help much with this scenario.  If users intentionally turn off revisions, then that would be expected.

**Comment by zdenys** [comment]
I'm not sure if the case of this user is relevant #9972795-HC. If not, I may need to report it as a separate issue.

**Comment by designsimply** [comment]
This issue was addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/8989.
