### ISSUE TITLE
"Already logged in" toast when returning to app

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5562]
I minimized the app while logging in, and when I returned to it the login screen was still showing. I tapped the login button and was told I'm already logged in.

![login](https://cloud.githubusercontent.com/assets/3903757/24514647/01f8e69c-1543-11e7-8d3e-bfd3556d496c.png)

I hit the back button and was taken to the main activity, already signed in.

**Comment by hypest** [comment]
Closing as no longer valid with the new login flows.

Note however that https://href.li/?https://github.com/wordpress-mobile/WordPress-Android/issues/6700 effectively "supersedes" this one for the new login flows.
