### ISSUE TITLE
Fail to retry media uploads

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5571]
1. Create new post
2. Add new media
3. Quit the editor before media has been uploaded (tap back button)
4. Re-open the same post
5. Tap the "retry" button on the image -> upload never end 💥 

Note: it seems caused by the `mCurrentUpload` state not being reset after upload cancellation

**Comment by maxme** [comment]
When the editor exits, uploads are canceled via [this method](https://github.com/wordpress-mobile/WordPress-Android/blob/9bf7fc562d057af25efcac724c42db578ef277fe/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2128-L2133), but the upload manager is not aware of any cancellation, so its state is not updated and when the user retry to upload a new picture, upload manager thinks there is already one in progress (the one that was canceled previously) and it's stuck in this state until the service is destroyed.

**Comment by mzorz** [comment]
closed via #5573
