### ISSUE TITLE
Advertise "Optimize Images" setting

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5572]
<del>We've dismissed the old `picture resize setting` in favor of the new `optimize images` setting without adding anything to make it discoverable. 
(For the record, the old setting item wasn't hugely discoverable as well).</del>

We should ask the users whether they’d like to enable it and tell them where to change it in the future. Asking this at first image uploading in the Editor.

**Comment by quicoto** [comment]
So we can no longer resize the image before uploading?

That feature was great to upload images taken with phone that are huge and don't want to upload to then resize server side.

**Comment by daniloercoli** [comment]
We're working on re-adding an improved version of it asap.
