### ISSUE TITLE
Followers Screen Does Not Load

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5597]
### Expected
When tapping the ***See all of your followers*** button link at the bottom of the ***Recent Followers*** screen, a list of all of your followers is displayed in the ***Followers*** screen.

### Observed
An empty card is displayed on the ***Followers*** screen as shown in the screenshot below.

![followers](https://cloud.githubusercontent.com/assets/3827611/24809007/5e10e90a-1b7b-11e7-8ac2-4d31b5032cb9.png)

### Reproduced
1. Go to ***Notifications*** tab.
2. Tap ***Follows*** button.
3. Scroll to bottom of list.
4. Tap ***See all of your followers*** button link.

**Comment by rachelmcr** [comment]
A user also reported this issue in support. Internal ref: 188356-h

**Comment by rachelmcr** [comment]
This was reported again by another user in support. Internal ref: 189184-h
