### ISSUE TITLE
Implement Site Settings - .org

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5605]
Calypso Site Settings - .com - has been implemented in #3568

.org site settings are still missing. Ref: https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/85

**Comment by maxme** [comment]
There was a .org site settings but I think XMLRPC endpoint is still missing. https://github.com/wordpress-mobile/WordPress-Android/blob/f02ff4ad9e514e9dfbfcb7a203e8e55b6b347fa5/WordPress/src/main/java/org/wordpress/android/ui/prefs/SelfHostedSiteSettings.java
