### ISSUE TITLE
Change default behavior of selecting a post in the "my posts" screen

### ISSUE THREAD

**Issue by gregsdennis** [wordpress-mobile/WordPress-Android#5610]
### Expected behavior
When I click on a post that I've written, it should view by default with an option to edit.

### Actual behavior
Currently, the default behavior is edit, which creates a draft that I then have to delete by backing out to the list then select "preview" then selecting "revert."

### Steps to reproduce the behavior
Go to the "my posts" screen and tap on the main portion of one of the posts.  The post is then loaded in edit mode.

##### Tested on [device], Android [version]
Nexus 5x, Android 7.1.2

**Comment by hoverduck** [comment]
It was a conscious decision to open the post in the editor as opposed to a view/preview mode - https://github.com/wordpress-mobile/WordPress-Android/pull/5131 / https://github.com/wordpress-mobile/WordPress-Android/issues/5128

But this ticket can be used to drive improvements to the flow to make it easier to exit without creating a new draft if there were no changes made.

**Comment by gregsdennis** [comment]
It seems counterintuitive to edit as the default behavior, as if I've been trained that the behavior should be view by other applications.  I can conjure up any examples, but that's the feeling I get.
