### ISSUE TITLE
Once Jetpack comment likes are launched make sure they are supported in the app

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#5618]
### Expected behavior
All application sections with comments should support Likes for Jetpack sites once that feature is implemented server side.

**Comment by hoverduck** [comment]
Linked iOS issue - https://github.com/wordpress-mobile/WordPress-iOS/issues/7006

**Comment by elibud** [comment]
@tonyr59h can you take care of this one? We need to add the parameter `force=wpcom` to `sites/SITE_ID/posts/POST_ID/replies` and `sites/SITE_ID/comments` to fetch the `i_like` flag from comments. Thx
