### ISSUE TITLE
Text copy/pasted from content to title includes "aztec_cursor"

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#5629]
### Steps to reproduce the behavior

1. Type some text in the post content area
2. Copy a word
3. Paste it in the title area
4. Notice the title starts with "aztec_cursor"

**Comment by rachelmcr** [comment]
I re-tested this issue and can no longer reproduce it. (Tested on Nexus 9, Android 7.1.1, alpha-87)
