### ISSUE TITLE
Posts with uploading media are sent to server when leaving the editor

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5645]
### Expected behavior
While media is uploading in a new post in the editor, exiting the post should store it as a draft. Upon re-opening the draft, the images that were uploading should be set to 'failed', allowing me to retry to upload them.

### Actual behavior
The post is saved to the server as a draft, with the local URL of the media file and editor-internal HTML:

```html
<img class="uploading" src="/storage/emulated/0/DCIM/Camera/IMG_20170411_132235.jpg" />
```

### Steps to reproduce the behavior
1. Open either Aztec or the hybrid editor
2. Insert a local image
3. While the image is uploading, exit the editor
4. Notice the 'uploading' notification
5. Check post content on the server

**Comment by mzorz** [comment]
closed via #5649
