### ISSUE TITLE
Editor: with Aztec enabled, can't add a link with visual editor

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-Android#5654]
### Expected behavior
Copy a URL on my phone's clipboard, open a post, edit it, and highlight a word. Then click an editor toolbar icon for "Add Link" — which opens a dialog to paste in the URL, creating a hyperlink.

Here's what it looks like with the Visual editor enabled.

<img src="https://cloud.githubusercontent.com/assets/66797/25049071/b97e9552-20f4-11e7-816c-ef9ca3f06bd9.png" width="480" />

### Actual behavior
There's no link or button for adding a link when I enable the Aztec editor.

<img src="https://cloud.githubusercontent.com/assets/66797/25049067/b5fd81ae-20f4-11e7-810f-253841f635e2.png" width="480" />

##### Tested on [device], Android [version]
Nexus 6P, WordPress for Android alpha-48.

**Comment by aforcier** [comment]
@lancewillett the format bar in Aztec should be scrollable - the link button is close to the end of the list.

I believe there are plans to re-order the status bar so buttons with higher usage appear without scrolling.

**Comment by lancewillett** [comment]
Oh my! Totally missed that. I see the arrow shape in the toolbar UI now.

Could we consider a tooltip or "this is new" guide for this? I imagine people wouldn't know they can scroll. I certainly didn't think of it.

**Comment by lancewillett** [comment]
I'm happy to close this. :)

**Comment by aforcier** [comment]
cc @0nko on this suggestion:

> Could we consider a tooltip or "this is new" guide for this? I imagine people wouldn't know they can scroll. I certainly didn't think of it.

**Comment by astralbodies** [comment]
On iOS we also bounce the toolbar a bit when it first appears to give the hint that it moves.

**Comment by 0nko** [comment]
@alex Yeah, we can do that. I'll create an issue for this in Aztec repo.
