### ISSUE TITLE
Use Aztec v0.5.0-alpha.5 in 7.2

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5656]
[This change](https://github.com/wordpress-mobile/WordPress-Android/commit/54225b61f16f31dbc61d40af5e8add768434efda) is in the latest alpha but not in the `release/7.2` branch, and it's needed to fix a crash when inserting media in Aztec (among other fixes).

**Comment by hypest** [comment]
For completeness' sake, which crash you have in mind @aforcier ?

**Comment by aforcier** [comment]
This one: https://github.com/wordpress-mobile/WordPress-Android/issues/5551

**Comment by aforcier** [comment]
Fixed in #5695.
