### ISSUE TITLE
Crash report on multiple versions: ClassCastException in downloadExternalMedia

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5669]
```
Fatal Exception: java.lang.ClassCastException: libcore.net.url.FileURLConnection cannot be cast to java.net.HttpURLConnection
       at org.wordpress.android.util.HTTPUtils.setupUrlConnection(HTTPUtils.java:21)
       at org.wordpress.android.editor.Utils.downloadExternalMedia(Utils.java:194)
       at org.wordpress.android.editor.ImageSettingsDialogFragment$4.run(ImageSettingsDialogFragment.java:322)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by daniloercoli** [comment]
cc @aforcier

**Comment by aforcier** [comment]
It looks like we're unreasonably expecting an `HttpURLConnection` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/8c6ba3d344e29000045540bdc763e752c6de5021/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/HTTPUtils.java#L21), when all we can count on is a `URLConnection`. We get away with this most of the time as stock Android indeed implements this using an `HttpURLConnection`, but the stack can be differently configured for non-stock Android devices, and we can get different implementations of `URLConnection` (`libcore.net.url.FileURLConnection`, `sun.net.www.protocol.file.FileURLConnection`, ...) for different devices.

The best solution is to drop `HTTPUtils`, and use our `ImageLoader` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/d258b3d75dcbaecde87b065f02096642437a46d1/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/Utils.java#L173-L232) (which we're calling when displaying the image in the image settings screen) as we do everywhere else.
