### ISSUE TITLE
OkHttp "Unexpected end of stream" uploading image

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5690]
Customer reports an "unexpected end of stream" error when uploading images. [This issue](https://github.com/square/okhttp/issues/2738) in Square's repo may help with the fix.

![endofstream](https://cloud.githubusercontent.com/assets/3903757/25144401/abd313fc-243b-11e7-80bf-1988a1fcc0a7.png)

**Comment by maxme** [comment]
Is this a frequent one? I guess it only happens on self hosted sites?

**Comment by nbradbury** [comment]
Yes, this is a self-hosted site. He says he has problems uploading any images, and I'm assuming this specific problem is what he frequently sees. I've heard no other reports of this.

Note he also says the problem didn't occur until he upgraded the app recently.

**Comment by tonyr59h** [comment]
> because the server keep_alive timeout is lesser than the client timeout.

Have we tampered with the timeout lately?

**Comment by tonyr59h** [comment]
[This commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/1e2dc04fc961a86389c6e7c6619487299f1a3d1b#diff-4b66763ebf0af33585da417243b8d3a1R73) looks like it increases the timeout from 10s to 30s/60s. Looks fishy, @maxme any idea if that could lead to this error?

**Comment by maxme** [comment]
Closing this one, the media upload code have changed a lot since it was opened and I haven't seen more report of this.
