### ISSUE TITLE
Investigate the Toast "This blog is hidden and couldn't be loaded."

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5692]
1. Why does this happen (site should be visible when selected).
2. Why do we show this? (can't we do everything on hidden sites?).

**Comment by KokkieH** [comment]
I just came across this error while trying to create a post on a test site where my user account is an admin, not the owner. Few observations:

The site was set as hidden from search engines. Switching it to private or public in settings made no difference.

The site was not hidden from the Calypso site list, and switching it between visible and hidden via My Blogs in WP-Admin made no difference.

I'm not able to make the error appear on any site I own, regardless of the site visibility settings, or whether the site is visible or hidden in Calypso.

I then tried it on another site where I'm only an admin, not the owner, and the error appeared again, so that appears to be a possible cause for this. However, it does not happen for internal P2 sites, even though I don't own those.

**Comment by designsimply** [comment]
I tried the following testing steps based on @KokkieH's comment to see if trying to create a new post while logged in as a user with Administrator role (but who is not an owner) on a site hidden from search engines would trigger the "This blog is hidden and couldn't be loaded" toast message but I couldn't see the notice.

1. Go to My Site > Manage > Settings > Privacy.
1. Change the Privacy to Hidden.
1. Go to My Site > Manage > People and invite a separate user as an Administrator.
1. Accept the invitation sent in the previous step.
1. Log out of the app (if you were logged in) and log in as the user that was just added as Administrator.
1. Create and publish a new post.

Results: I was able to create and publish a new post while logged in to a site hidden from search engines while logged in to the WPAndroid app as a user with the Administrator role that is not the owner.

<sup>Tested with WPAndroid 13.5-rc-1 on Pixel 3 Android 10.</sup><sup>Tested with WPAndroid alpha-192 on Pixel 3 Android 10 while logged into `made4testing0318.blog` as `user803` (an admin on the site but not the owner).</sup>

@KokkieH  any chance you could do a quick check to see if the problem you reported above is still happening for you in the Android app?

**Comment by designsimply** [comment]
I also tested after making the site private (not just hidden from search engines) and I tried testing with a different site which was hidden from the Calypso site list and found the same results—I don't get prompted with the message "This blog is hidden and couldn't be loaded."

@maxme do you recall why you made this issue to investigate that toast message or what you were doing in the app to trigger that notice?

**Comment by KokkieH** [comment]
@designsimply I'm not able to trigger that error now, no, though I can't even remember exactly how or where it appeared when I stumbled across this last year. My notes above are shockingly lacking in detailed steps to replicate :)

Checked on v.13.5-rc-1, Huawei P20Lite, Android 9

**Comment by maxme** [comment]
> I also tested after making the site private (not just hidden from search engines) and I tried testing with a different site which was hidden from the Calypso site list and found the same results—I don't get prompted with the message "This blog is hidden and couldn't be loaded."

I don't think it's related to private sites or sites hidden from search engine (the problem can happen on these sites as well). 

I just checked the source code and this string still exist: `error_blog_hidden`, the toast is triggered [here](https://github.com/wordpress-mobile/WordPress-Android/blob/fec059a251980c88ce485dc6e1aadb3f64cd58df/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L355). This seems like a logic error in the code:
- When a site is selected, it will be marked visible (in the app).
- Users should only be able to create new posts from a selected site or a visible site.

There might be a code path that allows creating new posts from a hidden site (I wonder if the "Share with... WordPress" feature can trigger this). If there is such code path, we should do something about it: 
- Mark the site visible.
- Or check why we can't create new posts on hidden sites. If there is no blocker, allow it and remove this toast.

**Comment by kraftbj** [comment]
I was able to duplicate this toast via the following:
```
    Open the app.
    Hit My Site at the bottom left
    Choose Switch Site
    Hit the search icon on the top (BONUS: I would expect the search input box to grab focus, but it doesn’t. I need to tap it to actually search, even though the keyboard is displayed on screen).
    Tap the text input box and search for a hidden site.
    Tap a hidden site to choose.
    See the site is now the current site.
    Tap new post button at the bottom.
```

**Comment by designsimply** [comment]
I made a more specific bug report for the case @kraftbj raised: https://github.com/wordpress-mobile/WordPress-Android/issues/10911 because this conversation seems more general, although now I'm wondering if it could be considered a duplicate. @maxme wdyt?

**Comment by designsimply** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/10911 with an ask to please re-open if this comes up again.

Props @kraftbj for providing steps to reproduce. 😍
