### ISSUE TITLE
Add editor source properties to editor analytics events

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Android#5696]
Add a property `editor_source` to all editor-related analytics events so we know which editor they were using. On iOS use `legacy`, `hybrid`, and `aztec` values to indicate which editor.

Equivalent iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/7051

**Comment by 0nko** [comment]
Fixed in #6419.
