### ISSUE TITLE
Editing: Add support for creating links that open in a new window/tab

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5697]
A user (in an app review) requested support for creating links that open in a new window/tab, similar to the web editor:

![screen shot 2017-04-19 at 3 57 23 pm](https://cloud.githubusercontent.com/assets/8658164/25186715/e893cab0-2518-11e7-8b9c-1ab08bc304a8.png)

**Comment by SiobhyB** [comment]
Also requested in 1341555-z.

**Comment by helphack333** [comment]
Yes please support for option link open in new tab in link editor in Android wp app

**Comment by mzorz** [comment]
Closing, this will land in WPAndroid 10.8 as this fix https://github.com/wordpress-mobile/AztecEditor-Android/pull/742 has just been merged
