### ISSUE TITLE
quick photo doesn't work for private blogs

### ISSUE THREAD

**Issue by dllh** [wordpress-mobile/WordPress-Android#572]
Repro:

1. Switch to private blog.
2. Tap Quick Photo.
3. Take photo and tap check mark to continue.

When doing this on a private wpcom blog, I get the attached error. It may not be specific to private blogs, but that's my only repro so far.

![screenshot_2013-12-24-12-21-31](https://f.cloud.github.com/assets/2738252/1806836/7b8b8638-6cc0-11e3-8706-dcc494ceee80.png)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
