### ISSUE TITLE
Media Detail Screen: landscape pictures are cropped and not scrollable horizontally

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5740]
See https://cloudup.com/c1MZNPgNaik

I guess this can be fixed along with https://github.com/wordpress-mobile/WordPress-Android/issues/5739 - just wanted to report both issues.

**Comment by daniloercoli** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/5744
