### ISSUE TITLE
Add a way to share/download media from WP Media Library (Preview Screen)

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5743]
eg. via a download button in the full screen view toolbar for instance. 

Usage: my favorite pony picture is stored in my WP library, I want to download the original picture so I can edit and add filters or save it in my dropbox.

**Comment by daniloercoli** [comment]
We're only sharing the URL atm. 

Related to this https://github.com/wordpress-mobile/WordPress-Android/pull/5723

**Comment by daniloercoli** [comment]
Fixed in #5886
