### ISSUE TITLE
Add support for WordPress galleries

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#5749]
~~WordPress galleries depend on [shortcode support](https://github.com/wordpress-mobile/AztecEditor-Android/issues/17).~~

It turns out that the Visual editor doesn't treat the `[gallery]` shortcode in any special way and it just adds it as a plain text. Therefore, this can be already implemented in WordPress without any changes to the library.

**Comment by 0nko** [comment]
It turns out that the Visual editor doesn't treat the `[gallery]` shortcode in any special way and it just adds it as a plain text. Therefore, this can be already implemented in WordPress without any changes to the library.

Moving this issue to the [WordPress repo](https://github.com/wordpress-mobile/WordPress-Android/issues/6452).

**Comment by maxme** [comment]
Note: I de-prioritized this issue because of a very low usage (0.3% of posts published with a gallery via the hybrid editor).
