### ISSUE TITLE
Add slug to Post Settings

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5751]
We should add the ability to show/change the slug for the post just like in Calypso and in iOS.

**Comment by elibud** [comment]
Also, we should pre-populate the slug when the suggested one: https://github.com/wordpress-mobile/WordPress-iOS/issues/7083

**Comment by rachelmcr** [comment]
This looks like a duplicate of this issue: https://github.com/wordpress-mobile/WordPress-Android/issues/4396

**Comment by oguzkocer** [comment]
I didn't realize we had an open issue, thanks @rachelmcr, closing this one!
