### ISSUE TITLE
Jetpack users logging in via their self hosted credentials get asked to sign in again

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5755]
Some self-hosted users with Android 7.1 are reporting that they are unable to use their sites in the app. They describe the issue like this:

* They add their self-hosted site to the app.
* The login is successful.
* They close the app.
* They reopen the app and are presented with the login screen again.
* When they try to log in again, they get a duplicate site error (“that site already exists in the app”).

I can reproduce the issue if I log in to my Jetpack-connected site as a regular self-hosted site, without logging in to WordPress.com. (Non-Jetpack self-hosted sites work as expected, based on my testing.)

Another case: the user is logged in to a different WordPress.com account in the app (not the account linked to the Jetpack site), and they are having the same problem.

**Comment by maxme** [comment]
Should be fixed by https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/427

**Comment by mzorz** [comment]
Closed via #5766
