### ISSUE TITLE
Self hosted site removal not removing completely

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5756]
As reported by @designsimply  - might be related to #5755 

### Expected behavior
Removing a self hosted site should never show it again.

### Actual behavior
Removing a self hosted site, logging out and back in shows the site again.

### Steps to reproduce the behavior
I was able to remove a self-hosted site, but if I log out and log back in then the site is there again.

Steps to reproduce:

1. Log in to an account with a self-hosted site.
2. Tap the W icon.
3. Long-press on a self-hosted site.
4. Tap “Yes” when prompted with “Remove this site from the app?”
5. Confirm that the site was removed.
6. Log out.
7. Log back in.
8. Look for the site that was previously removed.

Result: after removing a self-hosted site and logging out and back in again, I can still see the site listed in the site picker.

**Comment by tonyr59h** [comment]
This seems to have been fixed along with #5755.
