### ISSUE TITLE
New photo picker doesn't show images uploaded to WP Media Library from Google Drive

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5757]
Originally reported by @designsimply 

### Expected behavior
Uploading an image to the media library should also show in the image picker within the editor.

### Actual behavior
Images uploaded from google drive to the media library do not show up in the image picker within the editor.

### Steps to reproduce the behavior

1. Go to Media > + > Select a photo from gallery.
2. Tap the hamburger icon at top left and select a Google Drive account with an image in it.
3. Select an image to upload.
4. Verify the image was uploaded to the media library.
5. Start a new post.
6. Tap into the content area.
7. Tap the add media icon.
8. Look for the image that was just added.

Result: the image uploaded to Media from Google Drive wasn’t available in the photo picker in the Editor.

##### Tested on [Google Pixel], Android [7.1.2]

cc @nbradbury

**Comment by daniloercoli** [comment]
The new photo picker doesn't just picture from the WP Media library. It does show recent pictures on the device.

**Comment by mzorz** [comment]
Just to document - we discussed on Slack and came up with a different approach so people can notice there is the WP Media Library, https://github.com/wordpress-mobile/WordPress-Android/issues/5759
