### ISSUE TITLE
Media Metadata details in Visual Editors

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5758]
We should re-use the new media metadata full-screen preview introduced here https://github.com/wordpress-mobile/WordPress-Android/pull/5640 in Visual Editors.

At the moment there is still the old UI

![screenshot_20170426-175704](https://cloud.githubusercontent.com/assets/518232/25484415/3ab323e4-2b5a-11e7-8b50-ae6e6b12c0a8.png)

cc @nbradbury

**Comment by nbradbury** [comment]
After looking into this, I realized the editor image settings and media details aren't the same thing at all. The editor image settings are about the `<img..>` tag attributes, whereas the media details are about the metadata for the media library item.

These are completely different things, so we can't use the same details fragment for them. We could, however, make the design of the editor image settings mimic the media details by changing it into a translucent overlay.

@daniloercoli We can close this issue, but I'll leave that to you.

**Comment by daniloercoli** [comment]
Right! Closing this ticket, and opening a new one about making this screen better, and similar to the media settings screen. https://github.com/wordpress-mobile/WordPress-Android/issues/5769
