### ISSUE TITLE
Settings: Empty "Advanced" section appears for self-hosted sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#5763]
### Expected behavior

I don't expect to see an "Advanced" section in the settings for self-hosted (non-Jetpack) sites, since there's nothing to show there.

### Actual behavior

The section "Advanced" appears in settings with nothing underneath it.

### Screenshot

![2017-04-27 15 09 55](https://cloud.githubusercontent.com/assets/8658164/25490438/c0cac54a-2b64-11e7-80e0-4f31b3303ef9.png)

**Comment by oguzkocer** [comment]
This should have been fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/5620 in previous alpha but it looks like those changes are not in `release/7.3` branch. We are looking into it.

**Comment by oguzkocer** [comment]
It turns out the merge was OK, but 2 different PRs changed that class one merged to `develop` and the other to `release/7.2` so we didn't catch this issue until `release/7.2` was merged back to `develop`.
