### ISSUE TITLE
Can't update pages on self hosted sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5768]
Self-hosted users on Android (one with app v. 7.1 and one with 7.2-rc-3) who are reporting problems updating pages in the app. In both cases, when they try to update a page their site returns the error “The post type may not be changed.”

Should probably be fixed in FluxC (I guess we have to change XMLRPC params or call), worth a new connected test.

**Comment by cyfralus** [comment]
I've also noticed, that creation of new page is going to create new post. After investigation of the network packages I catch POST request and post_type value in update/creation page is set to: post instead of page.

**Comment by maxme** [comment]
Will be fixed by https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/436

**Comment by maxme** [comment]
@cyfralus yes the `post_type` wasn't set correctly in the XMLRPC client, thanks for your contribution!
