### ISSUE TITLE
Make Image Settings screen mimic the Media Details screen

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5769]
Make the design of the editor image settings mimic the media details by changing it into a translucent overlay.

The new media metadata full-screen preview introduced in #5640 is way better than the current version (shown below) available in Visual Editors. Unfortunately, as explained here https://github.com/wordpress-mobile/WordPress-Android/issues/5758#issuecomment-297814269, we can't reuse the same fragment, but we can try to mimic make the two UI look similar.

Current version:
![screenshot_20170426-175704](https://cloud.githubusercontent.com/assets/518232/25484415/3ab323e4-2b5a-11e7-8b50-ae6e6b12c0a8.png)

Video of the new version: https://cloudup.com/cXwi6iFC8We

**Comment by designsimply** [comment]
An update was recently added to allow you to download images from the Media Library to your device:

<img alt="screenshot_20170523-142605" src="https://cloud.githubusercontent.com/assets/1119271/26377772/f483151c-3fce-11e7-806d-947c4792ae1f.png" width="270" />

Will that option also be included in the Image Settings screen available when you tap on an image within a post you are editing?

**Comment by daniloercoli** [comment]
cc @nbradbury

**Comment by nbradbury** [comment]
I just started working on this issue, but I'm not planning to enable downloading media from a post's image settings. I think that should be dedicated to modifying the attributes of the image in the post.

**Comment by nbradbury** [comment]
Closed via #6503
