### ISSUE TITLE
Bring gallery settings back - WP Media Library pictures

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5771]
As per chat conversation we going to re-add the gallery settings screen back to the app.

At the moment, in wp-android 7.3, a new gallery is automatically created when the user multi-selects pictures from WP Library, and the gallery shortcode inserted into the post content.
We agreed that gallery settings screen is required since there is no other way for the user to change default settings in the editor. (Tapping on the shortcode doesn't open gallery settings screen yet). 

It should be a single dialog/screen that gives the option to customize the gallery settings (type & number of columns), or insert plain pictures to the post/page.

**Comment by aforcier** [comment]
Fixed in #5805.
