### ISSUE TITLE
Photo picker help

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5775]
We're receiving feedback that some of the actions in the new photo picker aren't clear. Long-press multi-select isn't very discoverable for new users, and the three icons at the bottom can be confusing.

After discussing various solutions, such as a help overlay, tutorial, etc., we decided on this simpler approach:

* Add a toast explaining long-press, "Tap and hold to select more than one photo." This should appear the first three times the feature is accessed.
* Change the WP media library title from "Select from media library" to "WordPress media."
* Change the device icon menu to show "Choose photo from device" and "Choose video from device"

**Comment by aforcier** [comment]
Fixed in #5803.
