### ISSUE TITLE
Bring gallery settings back - device pictures

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5776]
Related to this https://github.com/wordpress-mobile/WordPress-Android/issues/5771 but for local device pictures. This is scheduled instead for `7.4` (or later), since it could take more work to get done.

**Comment by daniloercoli** [comment]
For reference [here](https://github.com/wordpress-mobile/WordPress-Android/pull/3465) is the PR that added galleries to the visual editor.

We should implement this feature on the top of async-uploading, so we don't need to redo this twice for a feature that is used by a very small portion of users.

**Comment by nbradbury** [comment]
Based on a Slack conversation, we're considering this "on hold" for a while. It's a feature we're not sure many will use and it's non-trivial to implement. Given the other challenges, this one can take a back seat.

**Comment by jkmassel** [comment]
We have galleries as part of Gutenberg now, so I'm comfortable closing this.
