### ISSUE TITLE
New photo picker - delay opening the preview screen

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5777]
Noticed there’s a short delay between tapping the preview icon and the preview appearing.
There is also a short delay closing the preview screen.

I tested the preview screen in WP Media Library, and it works without any dealy there.

Would be cool to fix this in `7.3`. Otherwise let's work this in `7.4`.

**Comment by aforcier** [comment]
Fixed in #5804.
