### ISSUE TITLE
Filter Comments by Status

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#58]
Comments should be able to be filtered by their status.
​https://twitter.com/the_tim/status/19755927005

http://android.trac.wordpress.org/ticket/75

**Comment by mzorz** [comment]
Addressed on https://github.com/wordpress-mobile/WordPress-Android/pull/3691 (XMLRPC) and
 https://github.com/wordpress-mobile/WordPress-Android/pull/3692 (RESTApi)
