### ISSUE TITLE
Promo Dialog for Stats doesn't look good

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5802]
### Expected behavior
The promo dialog should look good

### Actual behavior
The promo dialog takes all the screen on pre-lollipop, and is too dark for latest OS versions.

<img width="693" alt="screen shot 2017-04-30 at 1 41 46 pm" src="https://cloud.githubusercontent.com/assets/6597771/25566349/41c33c64-2dad-11e7-89ce-2a88f24fbb8d.png">
Galaxy S3, Android 4.2.2

<img width="1671" alt="screen shot 2017-04-30 at 1 40 51 pm" src="https://cloud.githubusercontent.com/assets/6597771/25566348/41c2aa24-2dad-11e7-90ca-66da135cb741.png">
Custom tab, Android 4.1.1

![screenshot_20170430-134814](https://cloud.githubusercontent.com/assets/6597771/25566355/69895012-2dad-11e7-8ae4-124d8cec7502.png)
Google Pixel, Android 7.2.1

### Steps to reproduce the behavior
1. log in to the app for first time
2. go to Stats
3. check the dialog that pops up

**Comment by oguzkocer** [comment]
I have fixed the bg color issue in `issue/promo-dialog` but I am having trouble finding the cause for the dialog showing up as full screen. @nbradbury as a UI wizard, would you maybe have any idea why that might be the case pre-lollipop? I am running ideas to try and fix this.
