### ISSUE TITLE
When viewing a post in system browser don't append preview=true

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Android#5806]
### Expected behavior
When a published post is viewed in the system browser the direct URL/slug should be used without any parameters to bypass stats tracking.

### Actual behavior
When viewing a published post (tapping view under a post in the posts list) the parameter `?preview=true` is appended for the view inside the app. If the URL is then opened in the system browser (or with share > copy) the parameter is still included. Not knowing if the system browser is logged into WordPress.com and also not knowing the destination of the shared URL (for a friend, Tweet, e-mail, etc) we should strip that parameter off.

### Steps to reproduce the behavior
1. Go to a blog.
2. View the published posts.
3. Tap View on a post.
4. Tap the globe icon to open in the system browser.

Internal reference: `p4a5px-1IG-p2`

**Comment by maxme** [comment]
Note: we should keep this parameter in the preview screens (Webview).

**Comment by catehstn** [comment]
Ran into this the other day - I think this causes user complaints about inaccurate stats.
![screenshot_20170603-221322](https://user-images.githubusercontent.com/6810182/26874694-73c84e02-4b76-11e7-9bae-807086320523.png)
