### ISSUE TITLE
Post Settings: New dialog to edit the excerpt

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5807]
The current excerpt editor is inlined in the Post Settings. It makes the screen complicated and hard to read. To avoid this, we're going to open a dialog with a text area with a hint.

![excerpt](https://cloud.githubusercontent.com/assets/40213/25608501/647379e4-2f1b-11e7-870b-a42be3a1514e.png)

**Comment by oguzkocer** [comment]
Since we have added this functionality in a feature branch in #5873, I think we should just close the issue to make it easier to track things.
