### ISSUE TITLE
Post Settings: New screen to edit tags

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5808]
Similar to https://github.com/wordpress-mobile/WordPress-Android/issues/5807, instead of editing the tags inline in the Post Settings screen. We'll display them inlined but we'll allow edition in a new screen (Title, textarea with tags suggestion, hint).

![tags](https://cloud.githubusercontent.com/assets/40213/25608631/f1eba332-2f1b-11e7-85b3-33f36b50a7c3.png)

**Comment by mattmiklic** [comment]
Here's a look at a mockup of how I see this screen working:

![tags1](https://cloud.githubusercontent.com/assets/1396552/26365983/511f9308-3fb7-11e7-8d94-2d19599f1a29.png)

- The text input is placed on a card, to separate it from the list below
- Suggestions in the list are separated by 1px borders

Here's a version with color and measurement info:

<img width="1108" alt="screen shot 2017-05-23 at 12 32 52 pm" src="https://cloud.githubusercontent.com/assets/1396552/26366011/78145f5c-3fb7-11e7-847d-fcebf4cb6862.png">

**Comment by tonyr59h** [comment]
Closed via #5932.
