### ISSUE TITLE
Post Settings: New screen to edit location

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5809]
Similar to #5807, instead of having the location actions inlined in the screen, we'll show the location status ("not set", "Paris, France", "48.8578939, 2.2936799", depending of the location data we have) in the post settings list, tapping on it will open a new screen with the current actions and a map.

![location](https://cloud.githubusercontent.com/assets/40213/25608694/53956dca-2f1c-11e7-8eed-406f08c624ed.png)

**Comment by oguzkocer** [comment]
I am not clear on how the Location page will work exactly @maxme & @mattmiklic. Do we have a design for this or an established pattern that I don't know about?

**Comment by mattmiklic** [comment]
Just to document what @oguzkocer and I talked about -- I suggested that we try using the <a href="https://developers.google.com/places/android-api/placepicker">Place Picker</a> UI widget, which gives us a good location-choosing UI basically for "free." Depending on how that works, I can either plan to make edits to that interface if needed, or create our own, based on that design.

**Comment by mattmiklic** [comment]
Here's the solution we discussed for removing a location from a post. Tapping the location row when none is set opens the Place Picker. Tapping it when location is set brings up a simple menu with Change and Remove options.

The icons are `gridicons-location` and `gridicons-cross`, both are `grey_darken_10` and 18dp in width and height.

![remove-location](https://user-images.githubusercontent.com/1396552/27243246-fc04b280-52ae-11e7-8e29-99d90387ab1b.png)

**Comment by oguzkocer** [comment]
I think it's safe to close this one since #6097 is merged. I am also assigning this to @maxme since he's the one worked on it.
