### ISSUE TITLE
Site Details: Configuration section and Settings option missing for self-hosted site connected to Jetpack

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#5825]
To reproduce:

#### Scenario 1
Be signed out of the app. 
Use the self-hosted login form to add a self-hosted site that is connected to Jetpack. 
When the Site Details screen appears notice that the Configuration section and Settings option are both present. 
Wait a moment and rotate your device. 
Notice that these options have now vanished. 

#### Scenario 2
Go to your blog's wp-admin and disconnect Jetpack. 
Return to the app and let the updated site data sync (tap back to the site picker and then back to site details). 
Wait a moment and rotate the device. 
Notice that the Configuration section and Settings option have returned. 

#### Scenario 3
Remove the site from the app (as you can do that now). 
Log in again repeating the steps in Scenario 1. 
Notice that the Configuration section and Settings option are always present. 

#### Scenario 4
Go back to your wp-admin and reconnect Jetpack
Repeat the steps in Scenario 2
Notice that the Configuration section and Settings options vanish.

**Comment by tonyr59h** [comment]
Fixed in a recent update, closing this one out. Thanks for verifying @aerych 😃
