### ISSUE TITLE
Not able to login to self hosted site account

### ISSUE THREAD

**Issue by PankajM03** [wordpress-mobile/WordPress-Android#5843]
### Expected behavior
When the "Login" button is clicked after providing credentials (i.e. mail id, password and site address), app shall proceed to login as the self hosted site is already added in the app.

### Actual behavior
Instead of logging in to the self hosted account, the app tries to add the self hosted site to the app and returns an error message "This site already exist in the app, you can't add it"

When the site already exist in the app, it shall login on supplying valid credentials.

### Steps to reproduce the behavior
1. Start Wordpress app. (Self hosted site account already added to the app during previous invocation of the app) 
2. Enter email ID and click "Next"
3. Enter password and click "Log in"
4. Wait for login to succeed
5. Wordpress app flashes error message "This site already exist in the app, you can't add it" and fails to login to self hosted site

##### Tested on [device], Android [version]
OnePlus One.

**Comment by rachelmcr** [comment]
@PankajM03 Thanks for reporting this bug! We addressed some causes for that message in https://github.com/wordpress-mobile/WordPress-Android/issues/5755 and https://github.com/wordpress-mobile/WordPress-Android/issues/6135. Are you still having this issue in the latest version?

**Comment by hypest** [comment]
Closing this as dormant. Please, feel free to reopen if tested and the problem still persists. Thanks!
