### ISSUE TITLE
Orientation isn't correct when uploading photos - Take 2

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5855]
We should provide a better fix for #5737. Proposed solution is below.

- If optimize image is ON
optimize the picture and do nothing else since the picture is already rotated (if necessary) during the optimization process. *The editors must use the optimized file as source of their visual objects.*

- If optimize image is OFF
-- Check the blog, if it's wpcom do nothing on the original photo. But use the EXIF metadata before adding it to the editor(s).
-- If it's not on wpcom, rotate the picture, *The editors must use the optimized file as source of their visual objects.*

Other things to do:
- [x] Media Picker should use the orientation data and show thumbnail properly
- [x] Media Preview screen should use orientation EXIF data and show the picture properly
- [x] Media Library should take in consideration the optimize picture feature even for local device pictures
- [x] MediaBrowserActivity should call the same function before adding a media from device library.
- Not strictly related to this PR, but we we need to provide a way of cleaning the cache folder.

**Comment by tonyr59h** [comment]
Closed via #5857.
