### ISSUE TITLE
Media Async upload: different working copies of PostModel

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5858]
Follows from #5780 

It could happen that 2 images are being uploaded, then both finish practically at the same time, then when we try to modify the post’s content (to replace the local image with the remote one) we:
1. take the post from the db, where 2 images are local and “uploading”
2. a) image A gets replaced with the remote one, and this gets saved into the DB
2. b) image B gets replaced with the remote one, and this gets saved into the DB

We end up having a post with image A local, and image B remote, because what was saved last is 3) with a copy of the post that had both local images only.

### How to solve this?

We need a way to ensure that all images get saved / replacing the post content.
Fortunately, the service runs as long as there’s stuff enqueued for upload.

Proposed solution: In the MediaUploadService, what I’m going to do now is wait for all images in the queue (for a given post) to complete, and only then a) get a copy of the post’s content and b) make all replacements at once, then save.

**Comment by mzorz** [comment]
As discussed, what we're going to do is:
1. Wait for all images to be finished uploading, and then modify the Post object with all changes at once.
2. If the user opens the Post in the Editor while some media file are still uploading, modify the Post with all images that have already finished uploading.

**Comment by aforcier** [comment]
Fixed in #5973.
