### ISSUE TITLE
Load post content in background thread

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#586]
Copy the entire contents of Romeo and Juliet into a post: http://shakespeare.mit.edu/romeo_juliet/full.html

The app will become sluggish as it loads the content into the post editor. If you save the post as a local draft, the view post fragment also struggles to load the content. We should load the content in background thread in order to not block the UI.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
