### ISSUE TITLE
EditorFragment is missing the profiling stop calls

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5860]
Only these calls are found in `onCreate()`:
```
        ProfilingUtils.start("Visual Editor Startup");
        ProfilingUtils.split("EditorFragment.onCreate");
````

Should also have these in onDestroy:

```
                ProfilingUtils.dump();
                ProfilingUtils.stop();
```

**Comment by aforcier** [comment]
@mzorz we actually are calling them, once the WebView DOM has finished loading:

https://github.com/wordpress-mobile/WordPress-Android/blob/364e6cb972d347d2b4dfbddc1b7810ed2b310d7d/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L1287-L1289

**Comment by mzorz** [comment]
gotcha @aforcier ! closing
