### ISSUE TITLE
Trashed post reappearing (snackbar / refresh race condition)

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5862]
### Expected behavior
In the posts list, when you trash a post, it should not reappear in the posts list unless you tap `undo` in the snackbar right after trashing

### Actual behavior
if you trash a post the snackbar is shown (and the item in the list disappears), then if you refresh the list before the snackbar is hidden, the post re-appears (because it hasn’t been deleted on the backend yet).

**Comment by oguzkocer** [comment]
This should not be a problem with the latest iteration of the post list.
