### ISSUE TITLE
Unable to retrieve posts in Reader after relogin

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#5874]
### Expected behavior
After you log out and log in into the app the reader works as expected.

### Actual behavior
After you log out and log in into the app the reader does not load any posts.
![screenshot-2017-05-11_10 15 30 196](https://cloud.githubusercontent.com/assets/728822/25927710/cd5e17d4-3632-11e7-90c1-53a33b393805.png)

### Steps to reproduce the behavior

1. Login into app, make sure that Reader is working.
2. Log out from the app.
3. Immediately log in again.
4. Switch to Reader tab and confirm that posts are not loaded.

Pull to refresh is not working in this case either.

**Comment by rachelmcr** [comment]
I re-tested this issue and no longer reproduce it. Closing as resolved.

Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-84.
