### ISSUE TITLE
Keyboard shows up automatically when entering Post Settings

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#5883]
### Expected behavior
Keyboard should be hidden when entering the Post Settings screen.

### Actual behavior
Keyboard shows up with focus on the `Tag` input field.

### Steps to reproduce the behavior
* Go to post editor
* Hide or show keyboard (doesn't matter)
* Go to Post Settings, keyboard automatically pops up

**Comment by oguzkocer** [comment]
Since we don't have any text fields in the Post Settings page anymore, I think it's safe to close this one.
