### ISSUE TITLE
Filter posts/pages by author

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5884]
We currently have issues for filtering the posts by status #4693 and searching them #62, but there is no way to, for example, filter them to show the current user's posts. This is a possible improvement we should at least keep in mind.

**Comment by SiobhyB** [comment]
+1! This came up in the recent round up of app reviews from someone who owns a multi-author site. It's currently hard for them to see who authored posts from within the app.

Ref: p77Llu-9N5-p2

**Comment by oguzkocer** [comment]
See this comment for more context: https://github.com/wordpress-mobile/WordPress-Android/issues/62#issuecomment-370587518

**Comment by oguzkocer** [comment]
We are adding this feature as part of Post Filters project. There will be 2 selections, "Me" and "Everyone" where "Me" should show posts only authored by the current user and "Everyone" should show all the posts in the site with the selected status filter. Assuming that XML-RPC supports it, this feature should work for both self-hosted and WordPress.com/Jetpack sites. Here are the current designs for this:

![authors](https://user-images.githubusercontent.com/662023/54165727-5667a080-4438-11e9-8133-6ffcb1b8c6bb.png)

**Comment by drspaceboo** [comment]
@oguzkocer Does author selection need to be part of the `TabLayout` itself? Or would it be OK to put it next to it.

My thought is that it might be better (not to mention simpler) to have the button that allows users to filter by author to sit next to the scrolling `TabLayout`. Since that choice will be affecting all of the tabs, and is not itself a tab.

**Comment by oguzkocer** [comment]
> My thought is that it might be better (not to mention simpler) to have the button that allows users to filter by author to sit next to the scrolling TabLayout. Since that choice will be affecting all of the tabs, and is not itself a tab.

@drspaceboo Good question. I think that is how it's supposed to work because that's how it works on the Web. However, it doesn't hurt to double check with our designer for this project @SylvesterWilmott.

cc @malinajirka

**Comment by drspaceboo** [comment]
@oguzkocer Should we be storing a `SharedPreference` for which option the user selects for filtering? Or is it OK if it resets to "Everyone" when they re-enter the posts list?

**Comment by malinajirka** [comment]
@drspaceboo Thanks for asking - I've discussed it with Sylvester and we should remember the selected option.

**Comment by SylvesterWilmott** [comment]
>My thought is that it might be better (not to mention simpler) to have the button that allows users to filter by author to sit next to the scrolling TabLayout. Since that choice will be affecting all of the tabs, and is not itself a tab.

@oguzkocer As the tabs scroll horizontally the area containing the author control will remain fixed. This is not reflected well in the screenshots but to clarify:

<img width="360" alt="Scrolling Tabs" src="https://user-images.githubusercontent.com/36532468/54601385-d6909600-4a36-11e9-92c1-7e3cb52272bb.gif">

**Comment by oguzkocer** [comment]
Implemented in #9484.
