### ISSUE TITLE
Scheduled posts should say Sync in the Editor Menu

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5919]
Currently if a post is scheduled we still use the "Schedule" label for the button, whereas we should be using the "Sync" label instead to be consistent with the post list. While at it, we should make sure other scenarios are correctly labeled as well.

**Comment by oguzkocer** [comment]
I've spent a few hours on this today and didn't get anywhere with it. There are a couple issues with this:
1. We can't just change the button, we also need to change what happens when the button is tapped. This is not very straightforward unfortunately.
2. The bigger problem is that the user can change the status of the post at any time. So we can't actually work off of the post status. We could use the original post's status to some degree, but it gets complicated.

In light of this research, I no longer believe this fits into the Post Settings project. Instead, I think this should be handled when we remove the post status from Post Settings.

Pinging @iamthomasbishop since I believe he's going to design the changes to Post Status.

**Comment by iamthomasbishop** [comment]
Maybe I'm missing something, but why are we thinking of using "sync" here? Isn't "schedule" or "scheduled" the terminology everywhere (posts list, post edit screen, also in calypso)?

**Comment by oguzkocer** [comment]
@iamthomasbishop This PR might give the background on it: #5728. However, I'd suggest thinking everything through together when this is handled. So, I'd suggest to clearly define each scenario and what should happen in post list and editor and how we should label them. When I started working on that PR, it seemed really easy, but it turned out to be pretty tricky.
