### ISSUE TITLE
"Share with WordPress" site selector arrow gets overlapped by long site titles

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#5923]
Steps to reproduce:

1. Switch to the visual editor by going to App Settings > Set Editor Type > Visual.
1. Open the Photos app.
1. Tap an image then tap the share icon and select WordPress.
1. In the site selector, switch to a site with a really long title.

<strong>Result:</strong> the blog selector arrow of can be a little hard to spot with long blog names.

<img alt="screenshot_20170523-075006" src="https://cloud.githubusercontent.com/assets/1119271/26377947/c2b00c1a-3fcf-11e7-907e-4b9854234ca6.png" width="270" />
<sup>Tested with Pixel, Android 7.1.2, WPAndroid alpha-58.</sup>

**Comment by tonyr59h** [comment]
We're not the only ones [seeing this issue.](http://grokbase.com/t/gg/android-developers/129jtpa188/text-inside-the-spinner-view-overlaps-arrow)
