### ISSUE TITLE
Themes - Inconsistency between 'Details' and 'Support'

### ISSUE THREAD

**Issue by formosattic** [wordpress-mobile/WordPress-Android#5928]
Tested with a free, and premium theme activated.

In **Themes > Details**, activated state of the theme is correctly detected:
<img src="https://cloud.githubusercontent.com/assets/15944096/26402148/a9cb57da-40bb-11e7-92f4-c8f291acf199.png" width="250" />  <img src="https://cloud.githubusercontent.com/assets/15944096/26402197/d78a8be6-40bb-11e7-907f-52509995a99f.png" width="250" />  

In **Themes > Support**, should show **Customize** instead of prompting to activate the theme:

<img src="https://cloud.githubusercontent.com/assets/15944096/26401471/b37fc1ba-40b8-11e7-8878-70df7d060279.png" width="250" />           <img src="https://cloud.githubusercontent.com/assets/15944096/26401475/b741b61e-40b8-11e7-8ec9-955e472792dc.png"  width="250" />

Tested on S7 Edge, 7.4-rc-2.

**Comment by maxme** [comment]
These are webview, and I'm not sure why Calypso is showring different labels here. I'm not sure we're opening the same URLs, that might be the cause of it.
