### ISSUE TITLE
Replace the floppy disk icon used in media detail by gridicon cloud download

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5935]
![jgzkksnreh-900x900](https://cloud.githubusercontent.com/assets/40213/26437212/05b5248a-411c-11e7-9d23-252c1698d808.png)

Gridicon replacement: https://github.com/Automattic/gridicons/blob/master/svg-min/gridicons-cloud-download.svg

**Comment by daniloercoli** [comment]
cc @nbradbury
