### ISSUE TITLE
Image thumbnails for uploads aren't generated in Aztec

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5936]
Inserting a local image (at least from some content sources) in Aztec fails to generate a thumbnail, displaying a placeholder and an error toast:

![aztec-thumbnail-broken](https://cloud.githubusercontent.com/assets/9613966/26447829/6583d3ba-4118-11e7-800e-0d31d95567e7.png)

The upload proceeds normally, and closing+re-opening the post (or switching to HTML mode and back) after the upload completes will show the image correctly.

It looks like [this call](https://github.com/wordpress-mobile/WordPress-Android/blob/a06bfbe2258b2145bb967936f9e7331f1f23415f/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java#L518) is returning a `null` bitmap. This is due to [`MediaUtils.getRealPathFromURI` returning a null path](https://github.com/wordpress-mobile/WordPress-Android/blob/a06bfbe2258b2145bb967936f9e7331f1f23415f/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java#L398). This looks to have been introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/5857 (`ImageUtils` and `MediaUtils` were refactored).

cc @daniloercoli

### Steps to reproduce the behavior
1. In Aztec, add an image

**Comment by daniloercoli** [comment]
Fixed in #5938

**Comment by lancewillett** [comment]
Confirmed fixed in alpha-59 -- previously I'd get the missing placeholder graphic and "Unable to upload media" message.

After updating, the image placeholder appears as expected.

![2017-06-06 15 01 57](https://cloud.githubusercontent.com/assets/66797/26836006/8231e16c-4a8e-11e7-868a-748692df2a46.png)

Testing with WP for Android alpha-59 on a Nexus 6P.
