### ISSUE TITLE
Support Jetpack options

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5947]
In Jetpack, users have control over certain options and they can enable / disable certain functions. We should read these options and make sure the app is behaving correctly depending of what is enabled/disabled.

First step of this ticket would be to list the available options and how it impacts the app.

We opened this ticket mainly because we need to check if Photon is enabled in Jetpack (`Speed up images and photos`) before using it in the app.

**Comment by elibud** [comment]
All settings have been added var this one: https://github.com/wordpress-mobile/WordPress-Android/issues/6652 coming soon :)
