### ISSUE TITLE
Uploading post as draft shouldn't give "Published" notification

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5952]
### Expected behavior
To see a notification or popup notifying me that a post was uploaded specifically as a draft

### Actual behavior
I got a notification saying "Post published", which sent me into a panic to see whether it was actually published or not.

### Steps to reproduce the behavior
1) Start a new post
2) Exit the editor without publishing

The "Uploading" notification could also use some re-wording to confirm that it's a draft as well.

![image](https://cloud.githubusercontent.com/assets/7233112/26500176/f8c14000-4202-11e7-970d-0d9d9c8f620b.png)
^ The post here is titled "Test draft"

**Comment by rachelmcr** [comment]
I noticed the same issue and had similar panic thinking the post had been published.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-61

**Comment by 0nko** [comment]
The notification is automatically dismissed now after upload is finished and a message pops up at the bottom of the screen that shows it's only a draft:

![screenshot_1520354667](https://user-images.githubusercontent.com/1522856/37045415-2e17326c-2166-11e8-89fe-ead164a9e26e.png)
