### ISSUE TITLE
Unable to sign in to 2FA accounts under some circumstances

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5956]
After signing out of WordPress.com, signing back into a 2FA account leaves you stuck in an endless sign in loop. After inserting your username and password, instead of the 2FA code prompt showing up you get this:

![endless-login](https://cloud.githubusercontent.com/assets/9613966/26505944/a9fc39b4-4218-11e7-97d4-4898855d899b.png)

The same thing happens if the wrong credentials are entered - the error messages are displayed briefly and then you're sent back to a screen with just the username field.

It looks like the problem might be that `WPMainActivity` also receives the `OnAuthenticationChanged` event with error (`NEEDS_2FA`, or another sign-in error), which ends up [launching a new `SignInActivity`](https://github.com/wordpress-mobile/WordPress-Android/blob/a48ce1f457da3ccc6fe0feaf063058ad65222095/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L637) with the 'Log in again to continue' message. (On a clean install, or if the app is stopped after sign out, `WPMainActivity` is not yet running, so this bug doesn't happen.)

### Steps to reproduce the behavior
1. Sign into a WordPress.com account (2fa or not does not matter)
2. Sign out of WordPress.com
3a. Attempt to sign into a WordPress.com account with 2fa (using username + password)
3b. Alternatively, enter an invalid username/password and attempt to sign in

Reported by @elibud.

**Comment by maxme** [comment]
We actually forgot the reset site selection on sign out and we test for a selected site [here](https://github.com/wordpress-mobile/WordPress-Android/blob/a48ce1f457da3ccc6fe0feaf063058ad65222095/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L636-L638).
