### ISSUE TITLE
Self hosted site should be selected after authentication via Site Picker

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#5959]
### Expected behavior
If I'm already logged into the app and want to add a new site I would expect it to be the selected site when returning to the main (tab) activity.

### Actual behavior
The previously selected site stays selected after adding a new one.

### Steps to reproduce the behavior
* Login to WP.com
* Add a new self-hosted site via the Site Picker
* Return to the main activity

Result -> My WP.com site is still selected

**Comment by maxme** [comment]
Note this is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/5325

**Comment by tonyr59h** [comment]
Should be handled by FluxC, closing.
