### ISSUE TITLE
Can't insert images to the legacy editor

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5968]
After the recent changes to the media selection, it looks like when you add an image to a post in legacy editor, it just shows a placeholder image. We got some reports about this through Helpshift.

![screenshot_20170530-185942](https://cloud.githubusercontent.com/assets/662023/26592759/68903d72-456a-11e7-86f8-8cf2fd7753c7.png)

**Comment by aforcier** [comment]
This is the same issue as https://github.com/wordpress-mobile/WordPress-Android/issues/5939, and has been fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/5950 - should be fixed in final 7.5.
