### ISSUE TITLE
No manual refresh of the sites list

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5979]
### Expected behavior
To be able to manually refresh the sites list (ala pull-to-refresh). Useful when you know there is a new site and want to update to it.

### Actual behavior
The app will need to be killed to refresh or need to wait for the 15mins-after-last-update to pass to auto-refresh.

Test on WP v7.4

**Comment by oguzkocer** [comment]
This was a conscious decision if I remember correctly. @nbradbury I think you've worked on this, I am not sure, if so, could you remind us why it was designed this way? If not, do you remember who worked on it?

**Comment by nbradbury** [comment]
I did work on the site picker, yes. I don't recall any discussion about PTR on it, but if it was discussed chances are we simply didn't think it was necessary.

**Comment by tonyr59h** [comment]
Should be a pretty trivial addition with FluxC's `FETCH_SITES` action. That will handle the .com side of things at least. I don't think we need to update anything self-hosted since new sites are added/removed via the site picker already.
