### ISSUE TITLE
Media picker: portrait video doesn't preview correctly in landscape 

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5980]
### Expected behavior
While the device is in landscape, previewing a portrait video in the media picker should display OK, possibly with the video centered on the screen.

### Actual behavior
The video is left aligned on the screen

Tested on WP v7.4

**Comment by daniloercoli** [comment]
Fixed in #https://github.com/wordpress-mobile/WordPress-Android/pull/5965

**Comment by hypest** [comment]
Thx @daniloercoli ! My GitHub ticket search failed me and I didn't find the already opened ticket.
