### ISSUE TITLE
Drafts shouldn't have a date if not specified by the user

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5989]
Whenever a draft is created, we add a date to it which means when it's published, the date it's published actually shows when the draft is created. Here are the steps to reproduce it:

1. Create a draft and go back to the post list (it’ll become a remote draft if you have network)
2. Wait for a minute and publish the post. Now you have a published post 1 min ago

**Comment by maxme** [comment]
Related? https://github.com/Automattic/wp-calypso/issues/9014

**Comment by oguzkocer** [comment]
Fixed via #6122 & #6185.
