### ISSUE TITLE
Share to WordPress Dialog can load with no default

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6017]
Under some circumstances, it's possible for the revamped share dialog to load with no pre-selected option:

![share-dialog-no-default](https://user-images.githubusercontent.com/9613966/26850340-27c6a4e6-4ad5-11e7-84a9-a0926907531d.png)

It looks like the cause is that we're using the resource ID stored in preferences to remember the user's choice, but resource IDs can change between different builds.

### Steps to reproduce the behavior
1. Install a clean beta or release build of the app (I used 7.5 release)
2. Share a photo to the app
3. Notice "New post" is pre-selected
4. Complete the share, adding the photo to either a new post or the media library
5. Without uninstalling or clearing data, install an alpha build with a higher version (I used alpha-59)
6. Share a photo to the app
7. Notice no option is selected, and quickly tapping Share shows a toast 'Unrecognized action requested, ignoring'

cc @tonyr59h

**Comment by tonyr59h** [comment]
> but resource IDs can change between different builds.

D'oh! Thanks for reporting this, I'll take care of this one :)
