### ISSUE TITLE
Pages section loads Posts instead of Pages

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6027]
### Expected behavior
When accessing the Pages section, Pages should be shown.

### Actual behavior
When accessing the Pages section, Posts are shown instead.

### Steps to reproduce the behavior
1. Tap My Site.
2. Tap Pages.
3. The message Fetching posts will be displayed.
4. Then the list of Blog Posts will appear instead of Pages.

**Comment by aforcier** [comment]
Looks to affect Android 7.0 and up.

**Comment by mzorz** [comment]
Closing via #6029
