### ISSUE TITLE
Share to WordPress can break after app upgrade

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6042]
Once a user has shared to the WordPress app before, updating to the latest version breaks it. I believe this is because we should clear the existing stored pref `wp-settings-share-last-used-image-addto` once on app update, to clear away any saved value using a resource id instead of an int constant. (ref https://github.com/wordpress-mobile/WordPress-Android/pull/6025)

### Steps to reproduce the behavior
1. Install a clean `alpha-59`
2. Share a photo to the app, and complete the action
3. Install `alpha-60`
4. Share a photo to the app again
5. Notice that a selection is made, but pressing the 'Share' button shows a toast 'Unrecognized action requested, ignoring'

##### Tested on Pixel, Android 7.1.2

cc @tonyr59h

**Comment by tonyr59h** [comment]
Arghhh, updates!! Thanks for testing this though 😃

**Comment by tonyr59h** [comment]
Closed via #6060.
