### ISSUE TITLE
Not able to edit an image in a post - Visual Editor

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6049]
### Expected behavior
Tapping on a image on the Visual Editor should allow to edit the image settings (name, etc).

### Actual behavior
If you insert an image from the native photo picker, tap Edit, and nothing happens.

### Steps to reproduce the behavior
1. Start drafting a new post
2. Add an image by tapping on the media icon
3. Once the image finishes uploading, tap on it. The "Edit" overlay is shown
4. Tap on "Edit" and nothing happens.

**Comment by annezazu** [comment]
Cropped up in this ticket in helpshift 195460-t

**Comment by mzorz** [comment]
Closing via #6055
