### ISSUE TITLE
Credit translators in a "contributors" page

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#6054]
From the Community Summit, there was a suggestion for us to credit translation contributors and one place we can do it is in our Licenses screen, or a new contributors screen.

Same as https://github.com/wordpress-mobile/WordPress-iOS/issues/7368

**Comment by kwonye** [comment]
Questions:

1. Who do we credit? Everyone? Just the person's current language?
2. Do we need their permission? Is it implied?

**Comment by tonyr59h** [comment]
Awesome idea!
