### ISSUE TITLE
wordpress:// URLs don't trigger the app

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6062]
### Expected behavior
URLs starting with `wordpress://` should be handled by the app

### Actual behavior
The browser makes its way to the search engine, i.e. it searches for the entered text instead of launching the app, which should be registered

### Steps to reproduce the behavior
1. install the app and login
2. enter the following URL in the browser (i.e. to enable Aztec)
`wordpress://aztec?available=1&enabled=1`
3. the app should open and a Toast should be shown, but instead the browser tries to search for the entered text on the default search engine / tries to parse the URL itself.

**Comment by 0nko** [comment]
You can't just type the URL in the browser. You need to click an actual link on a page with the address and it will work. The browser does not know how to pass it to another app, unfortunately so there's nothing we can do here. So the right advice is to point people to the blog post with the `wordpress://` link.

**Comment by mzorz** [comment]
Thank you @0nko!
