### ISSUE TITLE
In-app language settings not sticking for some languages

### ISSUE THREAD

**Issue by formosattic** [wordpress-mobile/WordPress-Android#6068]
### Expected behavior
Have the app interface displayed in the chosen in-app language setting.

### Actual behavior
The chosen language settings sticks for some languages, but not others.

Issues encountered for these languages: Hebrew, Chinese (zh-hk, zh-cn, or zh-tw).

### Steps to reproduce the behavior

Device language setting: English (US)

1- App Settings > Interface Language, choose a language like Hebrew, Chinese (zh-hk, zh-cn, or zh-tw), the dashboard then shows in the chosen language.
2- Close the app
3- Open it again, the dashboard has reverted to English (US)

##### Tested on [device], Android [version]
Samsung S7 Edge, Android 7.0

**Comment by maxme** [comment]
👍 I was able to repro on my phone (Sony Z5C) with zh-cn - probably language code weirdness with Android/ISO codes.

I can't repro when I switch from en-us to fr-fr (everything works normally).

**Comment by tonyr59h** [comment]
Setting the locale directly [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java#L126) seems to be the culprit. Using [WPPrefUtils.languageLocale](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPPrefUtils.java#L191) does the work of splitting the language and region when creating the Locale.
