### ISSUE TITLE
Accessibility - Inconsistent High Contrast Fonts

### ISSUE THREAD

**Issue by formosattic** [wordpress-mobile/WordPress-Android#6070]
### Expected behavior
Have high contrasts fonts settings display consistently throughout the app.

### Actual behavior
High contrasts fonts is applied on some strings but not consistently, and the color is sometimes hard to read.

### Steps to reproduce the behavior
Activate High Contrast Fonts in device settings.

Some inconsistencies encountered:

- High Contrast Fonts not applied to all strings, see example with "Change PIN"
![_photo_2017-06-15_12-02-22](https://user-images.githubusercontent.com/15944096/27176511-136f94fe-51c3-11e7-8fa6-f8c295653100.jpg)

- Hard to read color contrasts, "Visit" link, comments and Likes count:
![_photo_2017-06-15_12-00-08](https://user-images.githubusercontent.com/15944096/27176537-35a9f618-51c3-11e7-836a-5348b0d1d217.jpg)

##### Tested on [device], Android [version]
Samsung S7 Edge, Android 7.0

**Comment by catehstn** [comment]
Time to delete pin lock then 💪🏼

**Comment by iegorka** [comment]
High Contrast Fonts does not work correctly with the "light color" font in the light background.
The same problem with another apps..
