### ISSUE TITLE
Not able to edit an image in a post - Aztec

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6080]
### Expected behavior
Tapping on a image on the Aztec Editor should allow to edit the image settings (name, etc).

### Actual behavior
If you insert an image from the native photo picker, tap Edit, and nothing happens.

### Steps to reproduce the behavior
1. Start drafting a new post
2. Add an image by tapping on the media icon
3. Once the image finishes uploading, tap on it. 
4. Nothing happens.

##### Tested on [ Samsung Galaxy S7 Edge Duos], Android [7.0], 7.6-rc-2

Please note this is a sister issue with #6049, but observed in Aztec. Also note I haven't been able to reproduce this on the following handsets:
- Google Pixel, Android 7.1.1
- emulator: Samsung Galaxy S3, Android 4.2.2

**Comment by hypest** [comment]
Cannot reproduce on a S7 Edge running app version 7.6-rc-2, Android version 7.0 I tested moments ago.

**Comment by mzorz** [comment]
Closing - invalid, the user was really observing #6049.

**Comment by mzorz** [comment]
Thank you @hypest
