### ISSUE TITLE
Comments: Add ability to insert images into comments

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6086]
We should add the option to insert images into comments via the app.

This could be part of "aztecification" of comments, giving users the ability to create rich text comments including images.

**Comment by erricgunawan** [comment]
I've just got a request for this in 2705433-zen:

> When I try to post a comment with a picture from my phone, it doesn't work. Plain text goes well, but attaching a picture is not possible.

> I've searched all settings, but can't find a setting or reason for this.

I'm not sure if this is tracked elsewhere. If so, I'm happy to move the report to the right place.
