### ISSUE TITLE
Login rework: Rotation re-opens the epilogue screen

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6111]
### Expected behavior
After logging in to WordPress.com and dismissing the epilogue screen, rotating the device while on the main app's screen (say, on MySite) should still show the main app screen.

### Actual behavior
The epilogue screen re-appears on rotation.

### Steps to reproduce the behavior
* Log into WordPress.com
* Dismiss the login epilogue screen when it appears. Notice you're now on the main app's screen.
* Rotate the device and notice the login epilogue screen re-appearing

Tested on the `feature/new-login` branch.

**Comment by maxme** [comment]
Closed via #6398
