### ISSUE TITLE
Remove Google+ from Sharing

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#6123]
Google recently [disabled OAuth requests from WebViews](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html), which means given our current design we can no longer support G+ in sharing/publicize.

Down the road we may want to support Google Sign-in to re-enable G+ support, but for now we should remove G+ from this feature in the Android app.

**Comment by catehstn** [comment]
Good catch - not worried about removing this. Should keep an eye on support and see if anything comes up though. /cc @rachelmcr
