### ISSUE TITLE
Media upload: connectivity loss leaves upload in inconsistent state

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6155]
### Expected behavior

**Part 1:** If you start uploading an image in a Post, and you lose connectivity (for instance, by turning airplane mode ON), the upload should be marked FAILED so the user can retry uploading at a later time when connectivity is regained.
**Part 2:** Then also the user should be allowed to start any other uploads on that same or any other posts.

### Actual behavior
**Part 1:** The upload gets stuck there after losing connectivity, when the actual upload should FAIL (happens for both Aztec and Visual editors, I believe this is a FluxC thing to take care of, but should be investigated deeply)
**Part 2:** if you try and upload one image, then turn airplane mode ON, exit, turn airplane mode off, start another different new draft, attempt to insert a new image -> the image shows a small progress on the screen but never really uploads anything and doesn’t notify the user about it, the logs show this:

```
06-26 15:05:07.556 30900-30900/org.wordpress.android.beta I/WordPress-MEDIA: Ignoring request to uploadNextInQueue, only one media item can be uploaded at a time.
```
There’s no way to recover from this unless stopping / restarting the app.

### Steps to reproduce the behavior
Part 1:
1. start an upload, 
2. let it progress a bit, 
3. turn airplane mode ON 
4. Observe it gets stuck there

Part 2:
After completing steps 1-4:
5. start a new draft
6. try inserting an image using the media picker
7. watch it have an initial progress and get stuck there forever.

**Comment by aforcier** [comment]
Probably related: https://github.com/wordpress-mobile/WordPress-Android/issues/6026.

**Comment by mzorz** [comment]
Thanks - just updated the description to also reflect a blocking behavior
