### ISSUE TITLE
Adding media to WP Media Library can freeze the app to death

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6167]
This is a weird one.

Steps to repro:
- Open WP Media Library
- Tap on the `+` sign to add a media
- When the option menu is on the screen tap back

Nothing happens. The only option is to close the app.
https://cloudup.com/cbTWZK8Bft0

Tested on Android 5 and Android 4.3

cc @nbradbury

**Comment by daniloercoli** [comment]
Re-opening this issue since I'm still experiencing it on `develop` atm. 

Side note: Rotating the device fixes the problem, the options menu disappears. Instead when I originally reported it, you had to close the app to "fix" the problem.
cc @nbradbury

**Comment by nbradbury** [comment]
Note: this doesn't occur on all devices - I was only able to repro on a Lollipop device.
