### ISSUE TITLE
Jetpack: Browse and manage plugins installed on Jetpack sites

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6193]
Jetpack sites should show a new row on My Sites for managing plugins.

- [x] Activate/deactivate
- [x] Toggle auto-update
- [x] Update

![](https://cldup.com/BGrRZ5D-dF.png)

**Comment by oguzkocer** [comment]
We have all of these working in `feature/plugins-master` and the remaining few small issues are being elsewhere.
