### ISSUE TITLE
Add the ability to search Posts and Pages

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#62]
The only way to search the content is to go the the browser and search the site. Would be convenient to search within the app.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by rachelmcr** [comment]
I'm reopening this issue, since the search would be part of the Blog Posts list, Pages list, and Comments list rather than the editor itself.

We have also received two recent requests from users for a search function in the Blog Posts list.

**Comment by rachelmcr** [comment]
Another user (in an app review) requested a feature to search within a site for a specific blog post.

**Comment by KokkieH** [comment]
Had another request for this via [Twitter](https://twitter.com/user/status/771302723807424512) today.

**Comment by ChrissiePollock** [comment]
Another request in HS today #134729-h

**Comment by khaykov** [comment]
We got a request from user:

> I want to search my posts in the App, sometimes I need to modify an older post or just read it. But I can't do it easily with the mobile clients.
> I think it is a useful feature, and I'm willing to see it in next version. :D

**Comment by aforcier** [comment]
Another request today in app support (for posts).

**Comment by rachelmcr** [comment]
Another user noted the lack of search (on posts) in an app review:

>No se puede buscar entradas en tu propio blog

**Comment by rachelmcr** [comment]
Another user (in a 4-star app review) requested post/page search:

> I love this app! I only need one feature to be added. Please make a search tab so I can find past pages and articles faster

**Comment by tonyr59h** [comment]
We should include searching People in this ticket as well.

**Comment by maxme** [comment]
I split this ticket into https://github.com/wordpress-mobile/WordPress-Android/issues/62 https://github.com/wordpress-mobile/WordPress-Android/issues/5510 and https://github.com/wordpress-mobile/WordPress-Android/issues/5511

**Comment by sarahblackstock** [comment]
Had a request to be able to search Blog Posts in the app today (due to wanting to update a specific post, but having so many that they are struggling to find the right post).

**Comment by tonyr59h** [comment]
Thanks for reporting, always appreciated 😄 

The PR is currently in review, you can expect this feature in the 7.5 release around the beginning of June.

**Comment by tonyr59h** [comment]
This feature is living on a separate branch while the final bugs are being addressed. Going to add the checklist to this issue to track them all:

- [ ] After no-network toast the search view should be hidden
- [ ] Status text isn't shown while searching
- [ ] Rotations show the original list and perform the search again, should cache results and display immediately on rotation - This one may be better to add to its own issue
- [ ] If you type a search term, wait just a bit and tap on the back button (before the list refreshes), it'll just say no posts: https://cloudup.com/cEkB7ebhCcu
- [ ] If you search a term which yields more than a single page, once the second page is loaded, it'll jump you to the beginning of the page (almost): https://cloudup.com/cJDkt_Tkxy1 - may be fixed, need to double-check this one
- [ ] We should have a different text for the empty view when the search term doesn't yield any results

**Comment by jblz** [comment]
Another request in app support

**Comment by sarahblackstock** [comment]
Request in app support: 

> it's difficult to look for the exact post; for older posts, I'd have to keep scrolling and waiting for the app to load. 

internal ref: #217720-h

**Comment by htdat** [comment]
> In Android app , in Blog Posts section , there is no option for search a particular post. So please give a search option because that is a necessity for all

Ref: 239365-h

**Comment by SiobhyB** [comment]
This came up as a common request in a review of app feedback from the past six months.

Ref: p77Llu-9N5-p2

**Comment by SiobhyB** [comment]
Another request in 264579-h.

**Comment by oguzkocer** [comment]
I removed the `Broken Window` and `Low Hanging Fruit` labels from this issue. It is a deceptively hard one to handle because we have some pagination issues we'll be fixing soon. After that, the implementation of the search function itself should be a fairly simple one. This also applies to the post filters.

I am also assigning the issue to myself, but I won't be working on it until the pagination issue is fixed.

**Comment by SiobhyB** [comment]
From a four star review:

> Overall great experience having this mobile app to manage my content from anywhere. But Blbadly need a function to "SEARCH THE BLOG POSTS" Will rereview the app to 5 star after this update. Keep it up the good work team;)

**Comment by SiobhyB** [comment]
Five star review:

> This app is perfect but please I need to be able to search for posts; scrolling is not all that easy. Thanks

**Comment by khaykov** [comment]
Another request:
> I'm looking for a search box in WordPress app to find a post or page from huge tunes of posts or pages i created before. i suggested please embed an search box at top of all pages or posts when come in its part in wordpress app.

**Comment by SiobhyB** [comment]
From a one star review:

> Doesn't hve search box in site pages window and blog posts window to find desire page or post visited via visitors seen in status page. my blog has very long lists both for pages and posts so is impossible can find desire page or post from huge mess

**Comment by SiobhyB** [comment]
From a three star review:

> Next expectation: searching a post. I've got a 1000 of them and would like to check again all the content I've written from the beginning but it seems that I have to slide down the page for ever to be able to reach my first post... Am I mistaken?

**Comment by nellofn** [comment]
This was also [requested](https://android.forums.wordpress.org/topic/android-functionality-distinguish-and-search-through-published-and-draft-posts?replies=2) in the public Android forum and keeps popping up every here and there in the queues.

**Comment by oguzkocer** [comment]
Just an fyi: This issue will be worked on very soon.

**Comment by SiobhyB** [comment]
From a four star review:

> Please add search option in blog posts. Thank you

**Comment by SiobhyB** [comment]
From a four star review:

> can you somehow add search bar to blog post field? it's annoying to scroll down so deep when i wanna edit past posts that have been published so long time ago...

**Comment by BandonRandon** [comment]
Another request:
> Could we ever get a “Search” button for pages on the app? Just a simple magnifying glass that lets us find specific posts would be very handy! 
https://en.forums.wordpress.com/topic/local-changes-on-wordpress-app/page/2/#post-3155700

**Comment by SiobhyB** [comment]
From a three star review:

> Please can you guys add the option of searching for posts or pages that's has been published long time ago for easy editing? Thanks

**Comment by SiobhyB** [comment]
From another three star review:

> Furthermore it is not possible to search for an article by name or date publication in order to modify it, and search among 200 articles each time to change one of last year is really absurd. If you can interesting my blog is called mptechnoblog, and deals with smartphones.

**Comment by SiobhyB** [comment]
From a two star review:

> It would be useful to complete the search in the list of articles and pages. If I have a lot of clanky, so I can not reach them through that list to some of them. !!!!!!!!!!!!! Otherwise, view it as a super tool for managing webpages.

**Comment by SiobhyB** [comment]
From a one star review:

> Plz add option to insert images in post from a url & option to search website posts. Scrolling to old posts takes Lot's of time.

**Comment by SiobhyB** [comment]
From a three star review:

> Please add search post fiture. I difficult to edit old post. Thank you

**Comment by aerych** [comment]
Oguz are you still planning on wrangling this one?  If not NDE can try to pick it up after Stats or Revisions ships.

**Comment by aerych** [comment]
> it'll be just a UI change to add search and/or filtering to it

Awesome!

> Can you give me a week or so to get the changes merged

NDE is a month or so minimum before we'd be able to look at another project.  You'll most likely beat us to it :)

**Comment by donalirl** [comment]
Another request in #1567079-zd

**Comment by oguzkocer** [comment]
This issue is now a part of a project starting as of today, so it shouldn't be too long before it's implemented.

**Comment by thehenrybyrd** [comment]
Had a request for this in an Android review today. 
> please add searching of post in this app. it is hard going through all your post in order to edit older post. I'll make it 5 star when the feature is added

**Comment by thehenrybyrd** [comment]
Another request in #2128757-zen

> Please add search button. I made around 1k post now and it's really annoying heaving to scroll all the way down anytime you want to edit older posts. Please put Searching feature in your next update. Thanks.

Looks like we're working on this though, thanks! :)
