### ISSUE TITLE
Post upload errors cause content loss

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6226]
### Expected behavior
Uploading a post and getting an error during upload should save the intact failed post as a local draft (or a locally changed post).

### Actual behavior
The post is saved as a local draft, but any changes since the last save are gone.

I believe we used to update the local copy immediately before attempting to upload, but we don't seem to anymore.

### Steps to reproduce the behavior
1. Write a short new post
2. Publish it and induce an upload error
3. Notice that the post is saved as an empty local draft

**Comment by mzorz** [comment]
closed via #6227
