### ISSUE TITLE
Media async: adjust cancelled uploads when coming back to Aztec

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6253]
### Expected behavior
If an upload is in progress and you exit the editor (Aztec), then the media upload fails, then get back into the editor, the image should be shown/marked as available for retry (i.e. marked failed)

### Actual behavior
The image is shown as being still in upload progress, which is incorrect.

### Steps to reproduce the behavior
on branch `feature/async-media`
1. open a new draft
2. include an image to upload
3. while it's uploading, exit the editor
4. make the image upload fail (i.e. turn airplane mode on)
5. get back to the editor
6. see the image is shown as "still uploading"

### Proposed solutions

We considered 2 options: 

1) either the AztecEditorFragment is in charge of this, and when it opens up again, we should check if there’s any canceled images and mark them properly, or 

2) when the `MediaUploadService` service is done with something and ends in error, we can do the same as we were doing for the success case: go ahead and call a static method in `AztecEditorFragment` that properly replaces the `class` properties for error ones

The PR tackling this, if not otherwise noted, should go with option number 2

**Comment by mzorz** [comment]
I think #6284 is actually a dupe of this. Will test and confirm.

**Comment by aforcier** [comment]
Fixed in #6366.
