### ISSUE TITLE
Media: featured image is sometimes not shown in Posts list

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6279]
Sometimes the Featured image is not shown on posts after having created a post with one or more images, waiting for everything to upload, and then coming back to the Posts list, when using the Visual Editor in particular. Couldn’t figure out a way to reproduce consistently / check if it happens with Aztec as well.

**Comment by nbradbury** [comment]
Note that the featured imageView is actually visible, but the image is blank.

![screenshot_1500572436](https://user-images.githubusercontent.com/3903757/28431660-13b1754e-6d53-11e7-8369-89cf231c34b0.png)
