### ISSUE TITLE
Media: reattachment sometimes jumps a bit

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6282]
#### To test:
- CASE B: SINGLE UPLOAD, start upload and exit the editor, before it ends get back to the editor, see if it reattaches (Aztec only)

Sometimes reattaching shows a very low progress and then jumps to the current progress. We might want to save the progress to the DB for each upload, so we can accurately reflect it for reattachment.

**Comment by aforcier** [comment]
Note: Part of the work on overall progress tracking for posts ended up involving keeping a record of the latest progress for each media in the `MediaUploadHandler`. When we have that, we can offer a way to query that through the `UploadService`, and show the last known progress for media when we open the editor.
