### ISSUE TITLE
Develop crashes in Themes since FadeInNetworkImage is not available

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6300]
Title has it. We've removed FadeInNetworkImage here https://github.com/wordpress-mobile/WordPress-Android/pull/6295/commits/bd2bc218dc615917a5228ba8ebae6729e8ab677f
Without checking usage in xml files. I had done a simple search in java file only.

**Comment by nbradbury** [comment]
Fixed via #6301
