### ISSUE TITLE
Hide "Categories & Tags" in Page Settings

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6320]
![screenshot-2017-07-17_11 28 00 546](https://user-images.githubusercontent.com/40213/28262542-a0325f14-6ae3-11e7-9a1d-b2d82c5165eb.png)

**Comment by oguzkocer** [comment]
This is a big facepalm moment for me as I am just now realizing that I never actually tested the new Post Settings with a page. Thanks for noticing this before it made it's way to the users!
