### ISSUE TITLE
Login - tapping back on "Add Self-hosted site" screen clears fields and dismisses screen

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6326]
### Expected behavior
In the login screen (first screen of the app): entering email, then tapping Add self-hosted site, then tapping back shouldn't dismiss the screen completely and then also clear the email field, but rather bring the previous state of the screen back.

### Actual behavior
When tapping the back button while on the "Add self-hosted site" screen, the app is dismissed, and bringing it up from the recent apps list shows the fields are all cleared up.

### Steps to reproduce the behavior
1. start the app
2. start typing your email
3. accidentally tap on “Add self-hosted site”, when what you really wanted to do is tap “NEXT”
4. tap back
5. the app is just plainly dismissed, and when you look for it with the recent apps button and bring it up to the foreground again, the email field is cleared now (you have to enter it again).

**Comment by hypest** [comment]
Closing as no longer valid on the new login flows. I've verified that the email is preserved if user (accidentally or not) goes into the self-hosted flow and return.
