### ISSUE TITLE
SignIn: On email check network error, wrong screen is shown

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6337]
In case of a network error during the `IsAvailableEmail` action, we show the "A magic link email has been sent" screen while the email can be wrong.

In the [`handleEmailAvailabilityEvent()` method](https://github.com/wordpress-mobile/WordPress-Android/blob/459c0b2dbe7bf2d8822b90a79ee4ed49ef4048ff/WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java#L1337-L1351), we should check if the `event.isError()`, and only if it's not we can call the `mListener.onMagicLinkRequestSuccess()`.

**Comment by hypest** [comment]
Closing as no longer valid on the new login flows.
