### ISSUE TITLE
Login Rework: use `users/%s/auth-options` for email availability

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6359]
Over at the iOS side of the apps, the WPCOM email availability check is performed through the `users/%s/auth-options` API endpoint rather than `is-available`. We should probably do the same.

@aerych may be able to provide more background to that.

**Comment by aerych** [comment]
> aerych may be able to provide more background to that

For sure.  The auth-options check does two things for us:
First, it checks if an email address is associated with a wpcom account. 
Second, it identifies if that account requires a password-less login option.   (In these cases we can remove the option to switch to the password form from the magic link screens.

**Comment by hypest** [comment]
What do you think we should do with this ticket @aerych ? It's priority feels low and we could perhaps add it to Groundskeeping even though it's a task and not an issue.

**Comment by aerych** [comment]
> It's priority feels low

Agreed

> we could perhaps add it to Groundskeeping

Works for me.  In theory it would help streamline login for anyone with a passwordless login so probably worth the effort.

**Comment by renanferrari** [comment]
Closed in favor of #12216.
