### ISSUE TITLE
Async media: modify error plus call to action case message

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6365]
For the case described [in this comment](https://href.li/?https://github.com/wordpress-mobile/WordPress-Android/pull/6333#issuecomment-316478984), the message and color / icon to be implemented should be as follows:

![screen-shot-2017-07-20-at-18-29-22](https://user-images.githubusercontent.com/6597771/28432179-5e6c1af8-6d5d-11e7-818b-e2fbb4a1e91b.png)

**Comment by daniloercoli** [comment]
Fixed in #6375
