### ISSUE TITLE
Clicking comment notification doesn’t scroll far enough

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6370]
User got a comment notification. And when they clicked that notification, they weri only scrolled about halfway down the post (post has a lot of comments). They were able to reliably reproduce this on the same post with different notifications.

**Comment by designsimply** [comment]
Re-opening because this came up again in beta testing for WPAndroid alpha-157 (12.0 alpha). The app has trouble scrolling to a specific comment in a long thread of comments, which can be disorienting.

<sup>(internal reference: https://wp.me/p5T066-N7#comment-2617)</sup>
