### ISSUE TITLE
Post Settings: Excerpt, replace the text edit dialog by a full screen text edit

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6372]
Current dialog is not convenient for writing long excerpt. @mattmiklic proposed design to improve the excerpt editing experience:

![post-settings-android](https://user-images.githubusercontent.com/40213/28462095-f3f73de8-6e19-11e7-957b-f6cf5c2df15f.png)

**Comment by rachelsquirrel** [comment]
It would also be good to add a character count to the excerpt box since social media sites often have a limit and then users can easily tell when they've reached that limit.

Requested in 210766-helpshift.
