### ISSUE TITLE
Async media: Repeat uploads for the same post get a different progress notification

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6377]
Since https://github.com/wordpress-mobile/WordPress-Android/pull/6333, we're showing a different progress notification for posts on repeat uploads.

Notification on first upload of a post:

![progress-notif-bug-first-publish](https://user-images.githubusercontent.com/9613966/28473223-abc44ce4-6e11-11e7-8ba1-0e325e320439.png)

Notification after editing and re-uploading that post (without having restarted the app):

![progress-notif-bug-second-publish](https://user-images.githubusercontent.com/9613966/28473245-c69f4384-6e11-11e7-81ef-ba872929c327.png)

Those notifications are also not foreground ones, so we're losing the safety of a foreground service for those posts.

**Comment by mzorz** [comment]
Closing via #6388
