### ISSUE TITLE
Aztec: Improve Media Settings

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6378]
There are some missing fields from the Image Settings screen in wpandroid:

* Alignement
* Link
* Caption

wpios issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/7596

**Comment by nbradbury** [comment]
@0nko I think this has already been addressed in Aztec, but wanted to verify with you before closing this issue.

**Comment by 0nko** [comment]
We didn't have shortcode support till now so those things were removed from the settings. Shortcodes were [just added](https://github.com/wordpress-mobile/AztecEditor-Android/pull/436), though, so they can be added back.

**Comment by nbradbury** [comment]
@0nko Looking at the image settings now, I'm already seeing these fields.

![screenshot_1501683039](https://user-images.githubusercontent.com/3903757/28878522-85167e4a-776d-11e7-9e45-555a14b9bd54.png)

**Comment by 0nko** [comment]
That's a wrong editor. If you switch to Aztec you'll see this:

![image](https://user-images.githubusercontent.com/1522856/28879222-e1516b8c-77a1-11e7-8917-1d9a801e1029.png)

**Comment by nbradbury** [comment]
Note: this will be tackled once Aztec is the sole editor. We'll be dropping the existing image settings and using the new [media settings](https://github.com/wordpress-mobile/WordPress-Android/pull/6643) from WP Android.
