### ISSUE TITLE
Async media: Enable post settings screen for Aztec when uploading media

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6380]
With reattachment working for Aztec, we should be able to [enable the post settings screen](https://github.com/wordpress-mobile/WordPress-Android/blob/b5dacc361b7803d9311be127e7120f3c75d8a0ef/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L731) while media are uploading.

**Comment by mzorz** [comment]
Closed via #6381
