### ISSUE TITLE
Reader: certain posts with an image don't show the image

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-Android#6405]
Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/7613 but for Android app.

### Expected behavior
When viewing Reader I'd expect to see a photo in the post preview card when the post in question contains an image.

### Actual behavior
Just the title shows, no image. This seems to be related to posts made with the native app Aztec editor only — posts published with visual editor, or Calypso web editor appear as expected.

![2017-07-26 09 13 57](https://user-images.githubusercontent.com/66797/28632943-f935e95a-71e6-11e7-821d-d48890a6bed8.png)

![2017-07-26 09 14 03](https://user-images.githubusercontent.com/66797/28632942-f9356868-71e6-11e7-8f0f-6dcc8daa5b2c.png)

### Steps to reproduce the behavior
1. Reader, look at a site like lance.blog or photo.cate.blog
2. View the posts list for a post you've published with an image, via Aztec editors.
3. You'll see some posts missing an image.

##### Tested on
Nexus 6P, Android app alpha-66

Possibly related to this Calypso Reader issue: https://github.com/Automattic/wp-calypso/issues/12609

**Comment by nbradbury** [comment]
Looks like this has the same cause as the Calypso issue - the images are inserted without any size information. 

However, this is no longer a problem since Aztec inserts the image class (`size-full`, etc.) and we now consider the image class when choosing the featured image (thanks to #5944 and #6125).
