### ISSUE TITLE
Async media: Support retrying posts with failed media

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6407]
Currently, a post that has failed media will show up in the post list like this:

![post-list-6-media-error](https://user-images.githubusercontent.com/9613966/28644923-79c08fa2-7229-11e7-928c-c16dfaf73197.png)

To retry the post upload, we need to edit the post and either retry the individual media items, or remove them/replace them.

Depending on the type of media error, it would be great if we offered the Retry option from the post list (and eventually the error notification).

We already do this when the error is related to the post itself, and there weren't any failed media:

![post-list-5-post-error-retry](https://user-images.githubusercontent.com/9613966/28644936-88a704ce-7229-11e7-9e88-cf4af062ebc2.png)

Some implementation work is required to actually support retrying post uploads with failed media. Once that's in place, we could enable retries for cases we can reasonably expect the retry to succeed (e.g. connection errors), and work on more automated fixes (maybe offering to resize the failed media automatically if the error was a file limit type).

**Comment by aforcier** [comment]
We should also show more helpful errors than the generic "Media upload failed. Edit the post to retry." we currently show in the post list for posts with media errors. (see conversation [here](https://github.com/wordpress-mobile/WordPress-Android/issues/6386#issuecomment-318228293))

**Comment by mzorz** [comment]
Related comment (we could address both #6407 and #4341 in one PR) https://github.com/wordpress-mobile/WordPress-Android/issues/4341#issuecomment-319413063

**Comment by mzorz** [comment]
Closed via #6789
