### ISSUE TITLE
Reader post detail should show the RSS excerpt (if any) for Jetpack sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6409]
Calypso applies a special treatment for Jetpack posts from sites that have RSS excerpts enabled. It only shows the excerpt and the featured image, if any, and shows a notice `Visit SITE_NAME for the full post.`.

Example of this kind of post: https://wordpress.com/read/blogs/67272686/posts/7751

**Comment by nbradbury** [comment]
@aerych Is this something that needs to be added to the iOS reader as well?

**Comment by aerych** [comment]
Totes needed.
