### ISSUE TITLE
New Post: changes in Settings are not saved as a draft when post is empty

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6413]
### Expected behavior
Starting an empty draft and going straight to Settings, changing things in there ( publication date, format, slug, etc) should produce an empty draft saved when exiting the Editor

### Actual behavior
An empty, new post is not being saved when the only thing modified is anything in the Settings area

### Steps to reproduce the behavior
1. Start a new post
2. Open the post settings, and set something that doesn't open a new fragment (publication date, format, slug, etc - excerpt is excluded since it makes the post qualify under `isPublishable`)
3. Exit the editor
4. The post is not saved as a draft

**Comment by maxme** [comment]
I wasn't able to reproduce that one, what I did:

Fist test (including patch from #9722):
- New post
- Open post settings
- Edit slug
- Back to post
- Back to post list
- Post has been saved as "Untitled" local draft 😸 

Second test:
- New post
- Open post settings
- Edit tags
- Back to post
- Back to post list
- Post has been saved as "Untitled" local draft 😸 

Note: might be related to that #9562 (if you were editing slug only, it wasn't saved).
