### ISSUE TITLE
Smart Lock covering New Editor Promo Dialog

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6415]
### Expected behavior
When logging in and shown the New Editor promo dialog, I should be able to dismiss one popup and then continue reading the other one that was left behind.

### Actual behavior
Tapping on the grey area of the screen dismisses both popups, so I can't really read the New Editor promo dialog.

![screenshot_20170727-144830](https://user-images.githubusercontent.com/6597771/28685342-d6359a84-72dd-11e7-9f8b-7913bab27d99.png)

### Steps to reproduce the behavior
- tried logging in to the app (I have 2FA enabled). so entered email, hit continue, then entered password when given the option to use magic links, then the 2fa field appeared, entered the code, 
and it was logged in.
- the “try the new editor” promo dialog came up
- the smart lock popup came up right afterwards
- tapping on the grey area of the screen made BOTH go away, so I couldn’t read the promo dialog

**Comment by hypest** [comment]
Can we test this again now that the new Login flow is merged? The SmartLock for Passwords save popup no longer coincides with the main activity and instead comes up "earlier", along with the epilogue screen.

**Comment by mzorz** [comment]
Confirmed it works and this one no longer applies - thanks @hypest !
