### ISSUE TITLE
Login Rework: can't paste 2FA code from Authenticor app into Verification code input field

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-Android#6435]
### Expected behavior
I expected to copy and paste text into the form field.

### Actual behavior
I cannot seem to long-tap or otherwise pull up the paste function.

### Steps to reproduce the behavior
1. Use a WP.com user account with 2FA turned on.
2. Log out of the app.
3. Log in.
4. When prompted for the Authenticator verification code, try to copy and paste it into the field.

![screenshot_20170731-115842](https://user-images.githubusercontent.com/66797/28793573-3f7f9622-75e8-11e7-9dc8-b13f8cca07db.png)

##### Tested on [device], Android [version]
Nexus 6P, Android 7.1.2, WordPress for Android app alpha-68

**Comment by aforcier** [comment]
I noticed this too - also, we used to support automatically grabbing the authenticator code from the clipboard `onResume` and filling the field - this doesn't seem to work anymore.

**Comment by lancewillett** [comment]
Yeah! I miss the auto-grabbing. Super nice UX.

**Comment by designsimply** [comment]
Tested and confirmed using alpha-68 on a Pixel with Android 7.1.2. I couldn't paste in a verification code from Authy like I have been able to in the past.

**Comment by hypest** [comment]
Confirmed copy/paste not triggering on some devices (other devices, like the Galaxy S2 Tab, work normally).

I've opened a separate ticket for the auto-paste issue: https://github.com/wordpress-mobile/WordPress-Android/issues/6443
