### ISSUE TITLE
Login Rework: overlapping elements in tablet landscape

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6442]
### Expected behavior
The login prologue animations and promotional texts should be arranged side-by-side with a healthy amount of margin between them when running the app on a tablet holding it in landscape mode

### Actual behavior
The promo text is overlapped by the animated imagery. See screenshot:
![2017-07-31-18-19-43](https://user-images.githubusercontent.com/1032913/28814724-69bac5a0-76a7-11e7-97b8-38813fe5eb51.png)

### Steps to reproduce the behavior
* With the app date cleared, run the app on a tablet and hold it in landscape mode

##### Tested on [device], Android [version]
Samsung Tab S2, Android v6.0.1

**Comment by mzorz** [comment]
Closing via #6449
