### ISSUE TITLE
Login Rework: re-instate the auto-paste of the 2FA code

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6443]
### Expected behavior
When a 2FA code is in the clipboard, the should pick it up and auto-fill the 2FA input field with it like it did before the Login Rework changes.

### Actual behavior
The app doesn't auto-fill the 2FA input field.

### Steps to reproduce the behavior
* Try to log in to a wpcom account that is protected with 2FA
* On the 2FA input screen, switch to your Authenticator app and copy a 2FA code
* Return to the wpandroid app
* 💥  the 2FA code is not auto-pasted

**Comment by mzorz** [comment]
Closing via #6446
