### ISSUE TITLE
PromoDialog: WebView in ReleaseNotesActivity lacks loading sign

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6472]
### Expected behavior
When a web page indicating release notes or more information about a feature is accessed, it should either upload immediately (which cannot be assured) or show a  "loading..."  sign

### Actual behavior
No  "loading..."  is shown, it took more than 4 seconds to start showing something for me the first time, so it really looked broken

### Steps to reproduce the behavior
1. uninstall the app and install it again (or delete all data)
2. start a new draft
3. tap on PUBLISH
4. you should see the promo dialog
5. if you tap on the `What's New` link, a new screen is opened
6. it doesn't show a "loading" wheel or sign

**Comment by elibud** [comment]
Closing as the screen has been dropped.
