### ISSUE TITLE
Login button doesn't work first time if Smart Lock capabilities not present

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6479]
### Expected behavior
When you tap on the `Login` button, it should do something

### Actual behavior
Tapping on `Login` the first time doesn't do anything on devices without Smart Lock (i.e. without Google Play Services)

### Steps to reproduce the behavior
1. install the app
2. tap on Login
3. observe nothing happens
4. tap on Login again
5. you're taken to the Login screen.

**Comment by hypest** [comment]
This was basically a duplicate of #6427 so, will close that as well.
