### ISSUE TITLE
ViewPostFragment does not resolve relative urls (patch added)

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#65]
In my blog, I use relative URLs. This is the case for image URLs and for anchors leading into my blog. I use it anywhere, where I can, so my blog will work after a global domain change, too.
But the Client is not able to resolve them. Images are missing and links are opened with ​file://.. instead of ​http://blog/ ..
I'll add an image of my post view before my patch, a screenshot after my patch and the patch itself, that resolves the problem.

Patch is here: http://android.trac.wordpress.org/ticket/257

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
