### ISSUE TITLE
Async Media: Video not uploaded correctly after exiting Aztec editor

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6531]
### Expected behavior

I expect that with async media uploads, when I exit the editor, the video will continue uploading in the post.

### Actual behavior

In Aztec, if I exit the editor while uploading a video, the video is not uploaded correctly:

- The draft is uploaded with a reference to a local video file on the device.
- When I reopen the editor and tap on the video, it tells me the file is still uploading but the progress bar doesn't move and it never finishes the upload.

I confirmed that the same video file uploads correctly if I remain in the editor during the upload; it's only a problem if I exit the editor before the upload finishes.

### Steps to reproduce the behavior

1. Enable the Aztec editor.
2. Start a new post.
3. Add a video to the post.
4. Before the video finishes uploading, exit the editor. Note that there is no message about "Uploading Media" on the post in the post list, and the draft is saved/uploaded to the server.
5. Open the editor again. Tapping on the video or trying to switch to HTML mode indicates that the video is still uploading, but there is no sign that the upload is happening.
6. In a browser, open the post and view it in HTML mode. Note that a reference to a local video on the device is included in the `[video]` shortcode.

**Comment by mzorz** [comment]
Closing via #6540
