### ISSUE TITLE
Async Media: Error in page list calls it a "post" instead of a "page"

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6541]
### Expected behavior

I expect that errors with pages will refer to a "page."

### Actual behavior

If there is an error uploading media to a page, the error on the page list refers to it as a post:

> We were unable to upload this post's media. Please edit the post to try again.

![2017-08-17 16 06 24](https://user-images.githubusercontent.com/8658164/29419256-8c8c89bc-8366-11e7-82ed-6d72e18e829e.png)

However, the system notification correctly refers to it as a page:

![2017-08-17 16 06 31](https://user-images.githubusercontent.com/8658164/29419283-9e400332-8366-11e7-9ce4-f713a6292b60.png)

### Steps to reproduce the behavior

1. Create a new page.
2. Add media to the page.
3. Exit the editor while the media is still uploading.
4. Disconnect from the internet (e.g. go into airplane mode) and check the error on that page in the page list.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-72

**Comment by aforcier** [comment]
Fixed in #6544.
