### ISSUE TITLE
Async media: upload notifications for media library

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6546]
When a user goes to the Media Browser and starts uploading a media item:

- Show overlaying label and spinner while on Media screen (as is done currently).
- Show notification _if_ user leaves Media screen.
- Also this notification should auto-dismiss once the media has been uploaded, but stay there if there was an error.
- Show just one notification even if multiple items are being uploaded, ideally showing "real" progress

**Comment by iamthomasbishop** [comment]
My 2 cents:

> Show overlaying label and spinner while on Media screen (as is done currently).
👍 

> Show notification if user leaves Media screen.
Why only if they leave the media screen? Should the progress notification start and show regardless of where they are? If you look at something like Dropbox, I believe this is how it works. When you start an upload, it starts a progress notification in your drawer.

> Also this notification should auto-dismiss once the media has been uploaded, but stay there if there was an error.
Agreed - if successful, the progress notification should disappear - should we then proceed to show a complete/success notification (again, using Dropbox as an example)?

> Show just one notification even if multiple items are being uploaded, ideally showing "real" progress
I think so. We could collapse multiple items being uploaded into a single progress notification (_X files remaining_ to give the user an idea of progress, preferably with an actual progress UI element).

So in other words, here's a summary of what I'm thinking (this is assuming the user is uploading multiple items):

* User chooses files and starts upload
* A progress notification is added to their drawer. This notification shows a title, progress UI, and shows X files remaining (if only 1 file, this messaging would be slightly different)
* Once the upload process is complete, that progress notification disappears
* If uploads successful, we show a success/complete notification that stays visible
* If error'd, show an error notification that allows the user to tap and go directly to where the error happened.

Does this sound right? I am using Dropbox as a reference, which I believe is a solid notifications UX. I think this is a good place to start without including snackbars. From there, during user tests/observations, if I notice people are struggling with the process, we can iterate. Having sys notifications like this is very valuable assuming the user knows to use them.

**Comment by mzorz** [comment]
> Why only if they leave the media screen? Should the progress notification start and show regardless of where they are? If you look at something like Dropbox, I believe this is how it works. When you start an upload, it starts a progress notification in your drawer.

Sure thing - we can have it right as the upload starts. Also, we will actually need to have it because of a technicality ([we're using a foreground service for uploads](https://developer.android.com/guide/components/services.html#Foreground), which needs to show a notification).

> If uploads successful, we show a success/complete notification that stays visible

We can run tests to decide on this a discussed elsewhere! 👌 @iamthomasbishop can you confirm the options being considered are the following?:
a) leave a persistent success notification you can tap to get you to the Media Browser screen
b) make an auto-dismiss success notification (after a few seconds)
c) don't show success notifications at all

**Comment by aforcier** [comment]
Echoing what @mzorz said that we'll want to have the notification display as soon as the upload shows. We don't do this currently, but we should be, especially once we're targeting Android O. (Some technical background in https://github.com/wordpress-mobile/WordPress-Android/issues/6389.)

One caveat is that we'll need share the progress notification with post uploads (whether we're uploading media for a post, or the post content itself). We're using a single service to handle posts, media, and media within posts, and we can't have two progress notifications. So we'd want to communicate, from a single notification, these various possible upload situations:

1. Single post uploading media, then uploading content
2. Multiple posts uploading media and/or content at different stages
3. Single media uploading (from the library, or from inside a post in the editor that we haven't tried to upload yet)
4. Multiple media uploading at different progress levels
5. Single/multiple posts uploading at different stages and single/multiple media uploading at different progress levels

We can be as specific or broad as we want, but we should consider the progress notification something that belongs to uploads in general, and not to the media library or the editor.

**Comment by mzorz** [comment]
Closing via #6713
