### ISSUE TITLE
Build app get error

### ISSUE THREAD

**Issue by jemsfaukner** [wordpress-mobile/WordPress-Android#6550]
I download your source code and build APK . Generate but when install in android device and register a new user then its give an invalid id every time.

Login Process Working perfectly 
![screenshot_20170821-175139](https://user-images.githubusercontent.com/17474890/29519072-9a499cee-8699-11e7-9bf3-f6b3e4fa6c03.png)

**Comment by maxme** [comment]
Please read and follow instructions from the [OAuth2 Authentication](https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication) section in the project README.
