### ISSUE TITLE
Downgrade the Gravatar change popup tooltip

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6552]
Back when the ability to change your Gravatar directly from the "Me" screen was introduced, we added a "New! Tap your Gravatar to change it" popup tooltip to help bring the feature into user's attention.

The feature is no longer new and we should probably remove the popup and replace it with a more subtle way to denote support for Gravatar changing.

**Comment by maxme** [comment]
+1000000

**Comment by iamthomasbishop** [comment]
Mockup with notes based on condo in the original mobilerequests ticket:

<img width="1166" alt="screenshot 2017-09-05 11 59 40" src="https://user-images.githubusercontent.com/1200432/30073007-cea0034a-9231-11e7-9652-a47608793c07.png">

**Comment by maxme** [comment]
@iamthomasbishop I did a quick and dirty fix to change this screen in the android app. Something looks wrong with the "change photo" label (I used the sizes you provided in the iOS screenshot), maybe too much vertical space used on this screen. Perhaps, we could move the name/username to the right of the avatar?

With the `Change photo` label:
![screenshot-2017-12-14_18 53 50 736](https://user-images.githubusercontent.com/40213/34007081-db72e9a2-e100-11e7-8c90-8922ddd2f8e3.png)

Without:
![screenshot-2017-12-14_18 36 06 148](https://user-images.githubusercontent.com/40213/34007080-db5adeac-e100-11e7-9106-8e9a0a1b6e5f.png)

It's maybe just a visual effect of this test account name `T&W`.

**Comment by iamthomasbishop** [comment]
I think the spacing is okay, but I'm wondering if we should use a card background behind the header area, which is the pattern that we've been following on login/signup, etc. Here's what it looks like on login:

![screenshot_20171214-121457](https://user-images.githubusercontent.com/1200432/34007743-80f2f1c6-e0c8-11e7-977d-388d809f88dc.jpg)

**Comment by maxme** [comment]
It looks better but it makes the view scrollable on some devices, which is not ideal IMO:

![screenshot-2017-12-15_09 59 05 441](https://user-images.githubusercontent.com/40213/34034425-bb622622-e17e-11e7-9b36-9ff3494d1080.png)

**Comment by iamthomasbishop** [comment]
Ping @mattmiklic bc I believe you worked on the cards for login - do you think the cards should also apply on this page (profile) for consistency with the login cards (screenshot above)? The downside is that the last item could get pushed out of the viewport in some cases (which I think isn't the end of the world) because of the height using a card adds, but I wanted to check with you before making a call.

Fwiw, profiles on both iOS and Android are currently card-less, so maybe we could push @maxme 's proposal now and address the cards separately.

**Comment by mattmiklic** [comment]
> Ping @mattmiklic bc I believe you worked on the cards for login - do you think the cards should also apply on this page (profile) for consistency with the login cards (screenshot above)?

I like the look of the cards visually, and don't mind much that they make the page scroll. But I don't have a strong opinion either way; it'd also be fine to address the card styling separately from this.
