### ISSUE TITLE
WPMediaUtils.getOptimizedMedia() is not guarded by AppPrefs.isImageOptimize()

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6559]
### Expected behavior
When the "Optimize Images" app setting is OFF the app should not resize images before adding to a post.

### Actual behavior
App resizes images (to 3000px, 85% quality) even when the "Optimize Images" setting is OFF.

### Steps to reproduce the behavior
* Clean install the app
* Navigate to "Me > App Settings" and notice that the "Optimize Images" setting is turned off
* Using the debugger, insert a breakpoint in `WPMediaUtils.getOptimizedMedia()`
* Go create a new post and insert a local image. Notice the breakpoint being hit and the code continuing to resize the photo.

##### Tested on [device], Android [version]
Nexus 5X, Android v7.1.2

**Comment by daniloercoli** [comment]
Fixed in #6562
