### ISSUE TITLE
Reader FullPost: big margins on content

### ISSUE THREAD

**Issue by aaronyan** [wordpress-mobile/WordPress-Android#6591]
The margins on many FullPost are large and inconsistent with each other. Here's an example:

http://wp.me/P11AhY-4Sd

Device: Google Pixel
OS: Android 7.1.2
Version: alpha-73

![screenshot_20170825-060147](https://user-images.githubusercontent.com/4505888/29724118-7be1a42a-8984-11e7-91bb-df10f9fe4321.png)

**Comment by aaronyan** [comment]
Here's another example with slightly different margins: http://wp.me/p4qSXL-2kC

![sensitive_data](https://user-images.githubusercontent.com/4505888/29735944-c91a9d3c-89b1-11e7-9e05-432359e4db0b.png)

**Comment by joelwills** [comment]
I have the same issue, same device and version as above:

Device: Google Pixel
OS: Android 7.1.2
Version: alpha-73

However on some posts it's even worse, for example:

![Screenshot](http://joelwills.com/rVPP77+)

Link to image: http://joelwills.com/rVPP77

**Comment by catehstn** [comment]
@nbradbury - do you have time to take a look at this, please?

**Comment by hypest** [comment]
Seems to be a regression caused by https://github.com/wordpress-mobile/WordPress-Android/pull/6514

**Comment by mzorz** [comment]
Just adding information - @hypest investigated the issue and found PR https://github.com/wordpress-mobile/WordPress-Android/pull/6514 to be where the issue seems to have originated
