### ISSUE TITLE
[LG - G4] Unable to add media to WP Media Library

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6595]
Users with LG G4 can't upload media to the media library, since tapping on one of the menu items does nothing.

**To reproduce the issue**
- Start the Android app
- Switch to the first tab
- Select Media
- Then tap on the `+` sign top left and select a picture
- The upload should start

##### Tested on Sony Xperia - Android 4.3

If possible, try to fix this in `8.2`.

cc @nbradbury 

and cc @theck13  that should have an LG device (G3)?

**Comment by theck13** [comment]
I confirmed the behavior on my LG G4 (LG-H810).  Tapping the `+` action displays the `Add to media library` menu, but tapping on the menu items does nothing.  The menu remains displayed.

**Comment by daniloercoli** [comment]
Fixed in #6596
