### ISSUE TITLE
Editor: Auto-expand the toolbar on landscape/large devices

### ISSUE THREAD

**Issue by philipjohn** [wordpress-mobile/WordPress-Android#6605]
### Expected behavior

When I highlight text in the editor when writing in landscape on my tablet I expect to see all the available for icons.

### Actual behavior

Many icons are hidden, despite there being ample space, forcing me to tap the three dots icon to the right of the screen.

### Steps to reproduce the behavior

1. Using a larger device in landscape mode
1. Enter the editor and your some text
1. Highlight the text
1. Look for the hyperlink icon on the toolbar
1. Two the three dots icon to the right
1. Hyperlink icon appears

##### Tested on Google Pixel C, Android 7.1.2

![screenshot_20170829-134932 2](https://user-images.githubusercontent.com/136342/29881167-bff840f8-8da1-11e7-8999-da86368603b0.png)

**Comment by elibud** [comment]
@maxme is this one still an issue?

**Comment by mzorz** [comment]
Discussed with @rachelmcr; we can generalize this as an enhancement and make use of the available space and show all icons when such space exists. Applied the `Enhancement` label and removed the `Bug` label on this issue.

**Comment by frosty** [comment]
If I remember correctly, the reason for hiding some of the icons is down to showing basic vs 'advanced' options, rather than due to screen space. @iamthomasbishop should be able to tell us more :)

**Comment by maxme** [comment]
We should maybe run some user tests (actually I think Thomas did that
already).

**Comment by iamthomasbishop** [comment]
@frosty @maxme That's correct. After seeing a decent amount of usage and hearing some feedback, I think we should probably expand the toolbar by default in cases that the screen is >= ~ 600dp/pt.

**Comment by megsfulton** [comment]
Going to close out this 'Needs Design' issue. Changes to this are tracked [in this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/8850).
