### ISSUE TITLE
Aztec: Swiping over newly added image opens image settings

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6608]
### Expected behavior

I expect that after I add an image to a post, I can tap to open the image settings. If I don't tap on the image, I can swipe over the image to move up/down in the editor.

### Actual behavior

Immediately after adding an image, if I swipe to move up or down in the editor it opens the image settings instead. This happens no matter how quickly I swipe over the image.

If I add an image and then tap somewhere else in the editor to place the cursor there, I can then swipe up and down normally without opening the image settings for the image I just added.

This only happens in Aztec. If I add an image to the hybrid editor I can swipe in the editor without any issue.

### Steps to reproduce the behavior

1. Enable the Aztec (Beta) editor in the app.
2. Start a new post.
3. Add one or more images to the post.
4. Swipe up or down over the image you just added. Result: The image settings open.
5. Tap somewhere else in the editor and then swipe. Result: The editor scrolls as expected.

Screencast of the issue:

https://cloudup.com/cLCZUHrR5p7

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-75

**Comment by mzorz** [comment]
I can confirm even not swiping for me the whole screen would take the touch action after adding a new image: uploading a video on Aztec and let it succeed, then re-opening the Post shows a tiny arrow or play icon, and the whole screen below the video detects as if you were touching the video, and thus triggers the player associated action.

Tested on Samsung Galaxy S3

**Comment by khaykov** [comment]
This might be related to click detection for media spans [here](https://github.com/wordpress-mobile/AztecEditor-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/EnhancedMovementMethod.kt).

**Comment by rachelmcr** [comment]
Closing as I can no longer reproduce this issue. (Retested on Nexus 9, Android 7.1.1, alpha-87)
