### ISSUE TITLE
project creates WordPress-vanilla-debug.apk which can't be installed on simulator outside Android Studio

### ISSUE THREAD

**Issue by vikramvi** [wordpress-mobile/WordPress-Android#6615]
### Expected behavior
1. When I use WordPress-vanilla-debug.apk generated by project; it gets installed by always crashes while launching.
2. When I launch is on emulator through Android Studio it works but in stand alone mode it always fails to launch.

**Comment by maxme** [comment]
@vikramvi Can you post the crash logs (stack trace)?

**Comment by vikramvi** [comment]
@maxme how to get crash log from simulator ?

**Comment by vikramvi** [comment]
WordPress-Android/WordPress/build/outputs/apk/WordPress-vanilla-debug.apk this gets installed from Android Studio and launches properly.

Same apk file when I install on same simulator; it does get installed but tapping on it is throws error.

I tried command `adb logcat` and log is https://gist.github.com/vikramvi/1f3da887070ec4b165ae30af1d3b9302
