### ISSUE TITLE
No way to add self-hosted site

### ISSUE THREAD

**Issue by bryanklingner** [wordpress-mobile/WordPress-Android#6617]
### Expected behavior
When adding a site on app version 8.1 version code 458, I expect a link to "Add self-hosted site" per https://apps.wordpress.com/support/#faq-android-gs1

### Actual behavior
No link to add a self-hosted site appears. Specifying a non-Wordpress.com site address in the "Enter the address of your WordPress site you'd like to connect" leads to the error "Couldn't connect to the WordPress site. There is no valid WordPress site at this address. Check the site address (URL) you entered.

Attached the application log from the app as well.
[error_log.txt](https://github.com/wordpress-mobile/WordPress-Android/files/1272898/error_log.txt)

I tried with two self-hosted sites and got the same error.

The same site worked fine on a previous version of the app. 

### Steps to reproduce the behavior
Launch the Android app (8.1), click "LOG IN", then click "Log in to your site by entering your site address instead"

**Comment by bryanklingner** [comment]
Sorry I forgot to notate this is on Android 8.0.0

**Comment by maxme** [comment]
@bryanklingner it looks like there is a problem on your site `https://blog.overt.org`. When I try to post a public request `system.listMethods`, I see a `500 Internal Server Error` error on that site.

```shell
curl -v -H "Content-Type: text/xml"  -d '<methodCall><methodName>system.listMethods</methodName><params/></methodCall>' https://blog.overt.org/xmlrpc.php

> POST /xmlrpc.php HTTP/1.1
> Host: blog.overt.org
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: text/xml
> Content-Length: 77
>
* upload completely sent off: 77 out of 77 bytes
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.10.3 (Ubuntu)
< Date: Mon, 04 Sep 2017 07:36:50 GMT
```

That might come from a broken WordPress plugin or a broken WordPress install. You should check your nginx server logs to understand the underlying error.

Note: you can also check your site XMLRPC endpoint via this tool: http://xmlrpc.eritreo.it/

**Comment by bryanklingner** [comment]
Argh, sorry about that. I saw the absence of the link for the self-hosted site and assumed something about the app had changed. I will address the error on my server and reopen if the problem persists.
