### ISSUE TITLE
Unable to sync project

### ISSUE THREAD

**Issue by skfaisal93** [wordpress-mobile/WordPress-Android#6624]
While syncing project always getting following error:

`Error:Could not download maven-ant-tasks.jar (org.apache.maven:maven-ant-tasks:2.1.3): No cached version available for offline mode`

What is the solution?

**Comment by maxme** [comment]
@skfaisal93 what command did you run? `./gradlew build`?

**Comment by rachelmcr** [comment]
I'm going to close this as it hasn't had any recent activity. @skfaisal93 please let us know if you're still having trouble, and what command you tried.
