### ISSUE TITLE
Featured image not being refreshed

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6640]
### Expected behavior

Having a Post/Page on the handset, if you set the featured image for a Page or Post on the web, and then check the mobile app, the mobile app should reflect these changes accordingly.

### Actual behavior

Having a Post/Page on the handset, if you set the featured image for a Page or Post on the web, and then check the mobile app, the mobile app never refreshes the Featured image setting for that specific Post, even if you do pull to refresh in the Posts/Pages list.

### Steps to reproduce the behavior

1. Open Wordpress app 
2. Find the page and open it 
3. Then I click the Setup/ Configuration icon on top 
4. set a featured image there
5. click BACK or UPDATE
6. tap back once more to exit the editor
7. once in the Posts list, you'll briefly see the "uploading" state for that Page/Post, as changes are sent to the server
8. check the web admin, and confirm the featured image is set there.
9. Now remove the image in the web admin

10. Back on the Android app: go to the main menu, and click Pages (or Posts) -> to see the list of Pages.
11. Tap on the Post/Page you're working on.
12. Tap the settings icon
13. Verify the Featured image is still there, when changes on the server happened.

14. Now, go back to the Pages/Posts list on the app, and do pull to refresh.
15. Tap on the Page/Post you were working on
16. Tap on the settings icon in the editor
17. Verify the Featured image is still there, when it shouldn't.

**Comment by hypest** [comment]
Can't replicate on alpha-280. The featured image setting properly seems to update in my testing. Closing as fixed!
