### ISSUE TITLE
Themes: Theme detail for retired theme leads to blank page

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6646]
### Expected behavior

If I am using a retired theme on my site, when I go to Themes > Details or Themes > Support for the current theme I expect to see a message about the retired theme, i.e. this page: https://wordpress.com/theme/ecto

### Actual behavior

When I select Themes > Support I see that retired theme message, but when I select Themes > Details I get a webview with a masterbar and blank page:

![2017-09-21 17 47 19](https://user-images.githubusercontent.com/8658164/30742587-b0c2937a-9f91-11e7-8817-23b763a3af74.png)

### Steps to reproduce the behavior

1. Set a retired theme as the active theme on a site.
2. Open your site's Themes section in the app.
3. Under "Current Theme" select Details.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-75

**Comment by designsimply** [comment]
To close the loop, I tested this today using WPAndroid alpha-172 (12.6 alpha) on Pixel 3 Android 9 with the Pachyderm theme (retired) activated and both the theme details and theme support links in the header area in the Themes page of the app worked normally. The customizer, however, opens with an error and that issue has been filed separately at https://github.com/wordpress-mobile/WordPress-Android/issues/10030. 😊
