### ISSUE TITLE
Reader: Right edge of post cut off in portrait view

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6647]
### Expected behavior

I expect the full width of posts in the Reader to be visible in both portrait and landscape views.

### Actual behavior

I can view the full width of posts in landscape view, but the post is wider than the visible area in portrait view so the right edge gets cut off:

![2017-09-22 12 33 41](https://user-images.githubusercontent.com/8658164/30742769-918ce8f6-9f92-11e7-90e0-4d64971ce6cf.png)
![2017-09-22 12 33 46](https://user-images.githubusercontent.com/8658164/30742774-95e2d4b0-9f92-11e7-9378-c1afe022b139.png)

### Steps to reproduce the behavior

1. Open the Reader.
2. Tap to open a post detail view.
3. Rotate between portrait and landscape.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-75

**Comment by maxme** [comment]
I can repro on a Nexus 9 emulator (7.0.0).
