### ISSUE TITLE
Activity Log and Rewind

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#6653]
We want to implement the Activity Log with the rewind feature on the mobile apps.

**Comment by planarvoid** [comment]
FluxC - Vojta
- [ ] Pull activity log
- [ ] Store activity log
- [ ] Pull rewind status
- [ ] Store rewind status

**Comment by usernamefghh** [comment]
#6653

**Comment by scote444444** [comment]
Hi, i have a domains international its name is Sébastien Côté m'y langage its french me? scote4444/@scote4444.ws for individuals To deposit at sell time for me a Github help Me please i have funny noble network- 223713 too so Google platform help Me amount 396.05$ crédit and free 354 says #8537 Github please news
