### ISSUE TITLE
A8C Reader: Error when viewing cross posts to a site you are not a registered user

### ISSUE THREAD

**Issue by aaronyan** [wordpress-mobile/WordPress-Android#6659]
On mobile devices, if you click on a cross post that comes from a private site where you are not a registered user, the post cannot be retrieved. This problem will only happen for Automatticians (specifically in the a8c stream). The error can be produced on multiple operating systems (both iOS and Android).

On Google Pixel Android 8.0.0 - WordPress App alpha-75, we get the following error:

![screenshot_20170925-102600](https://user-images.githubusercontent.com/4505888/30823226-59982c6c-a1e0-11e7-8c19-8a952a790097.png)

**Comment by aerych** [comment]
Thanks for the report @aaronyan.  We've made a conscious choice to limit enhancements to the reader that only affect a8cs. 
Closing.
