### ISSUE TITLE
Add back the caption to image settings

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#6663]
Caption field has been removed from the image settings in Aztec because shortcodes were not supported. They can now be added back.

**Comment by ChrissiePollock** [comment]
Request for this in #232368-h

**Comment by maxme** [comment]
Related to this issue https://github.com/wordpress-mobile/WordPress-Android/issues/6378

PR: https://github.com/wordpress-mobile/WordPress-Android/pull/6992

**Comment by maxme** [comment]
Fixed via  #6992 - 🍾  thanks @khaykov and @0nko 🍾 !
