### ISSUE TITLE
Login - Suggest device default email address 

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6699]
I noticed that the login screen doesn't suggest the default email address available on the device.
![device-2017-10-09-144251](https://user-images.githubusercontent.com/518232/31338650-703354f8-ad00-11e7-827a-37a7d21844e8.png)

As seen in the picture above there are no suggestions when I type the first letters of the email address currently active on the device.

**Comment by maxme** [comment]
This requires the "Contact" permissions :/

**Comment by maxme** [comment]
Related to this: https://github.com/wordpress-mobile/WordPress-Android/issues/3329
