### ISSUE TITLE
Login: misleading error message when no connectivity

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6728]
### Expected behavior

When logging in to the app, errors in connectivity should reflect what happened

### Actual behavior

When logging in to the app, entering an email address and hitting "NEXT" with poor connectivity can lead to a misleading error message that reads "This email is not registered on WordPress.com".

### Steps to reproduce the behavior
Setup your emulator to go through a proxy, but do not setup the proxy.
1. open the app
2. tap on LOG IN
3. enter a valid email address
4. hit "NEXT"
5. observe the error shown is "This email is not registered on WordPress.com", when in reality the app couldn't even reach the server.

**Comment by hypest** [comment]
The current error message is indeed misleading. Had a look and we can change it to something more generic. Unfortunately, the error message we get from FluxC is too generic to make out the connectivity but the Volley error does have hints for it. So, I'd suggest we tackle this at the FluxC level if possible.

**Comment by mzorz** [comment]
While I 100% agree we could do better by getting more granularity/detail from FluxC in the errors, please let's still correct the message in the login. i.e. `This email is not registered on WordPress.com`  is not guaranteed to be true, let's put something more broad and hint the user  on possible solutions, for example `"An error occurred. Please check your connection and make sure you enter a registered email address."` (let's ask for Editor's review for this)

**Comment by hypest** [comment]
Note, the app already does some basic connectivity test (like, WIFI or GSM data available) upon hitting the "Next" button but this particular error (deeper, proxy or similar errors) are not caught.

So, a "Please check your connection" error message although related, won't be too helpful either. Contrast that with `Failed to connect to /192.168.1.106:8888` which is the error Volley actually emits in logcat when my device fails to connect to the proxy. That's a way more specific error the user (or Support!) can act upon.

Don't get me wrong, I too think we need to move away from the misleading `This email is not registered on WordPress.com` message. Your proposed message is probably a good starting alternative. But I just wanted to raise the point that we should also tackle this at the FluxC level if we want to be more helpful to the user.

**Comment by mzorz** [comment]
> I just wanted to raise the point that we should also tackle this at the FluxC level if we want to be more helpful to the user.

That is being tracked here
https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/506
