### ISSUE TITLE
Unable to edit a draft post (changes fail to save)

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#6729]
### Steps to reproduce the behavior
1. Create a new post (whether via the web or the app)
1. Save the post as a draft (do not publish)
1. Navigate to the Posts list
1. Open the draft post and make changes
1. Tap Update
1. Tap Update again, because nothing appeared to happen (separate bug?  There's a crazy-long delay here before the UI responds to the button click)

### Expected behavior
For the draft to be updated

### Actual behavior
The card in the Posts List shows the new content briefly, but it disappears after the upload is "complete".  The changes are lost, and never seen again on the device or on the web.

Here's a video of it in action...but fair warning, it takes ~1 minute after making the updates before anything starts to happen, and then another ~1.5 minutes before the updated text disappears.  Every piece of this takes a really long time, despite a healthy internet connection (tested at 8Mbps upload, 30Mbps down)

https://cloudup.com/cKaxRoL-JTD

The problem was seen using all three editors (Legacy / Visual / Beta).  I ran through the test probably a dozen times, and was only able to successfully edit the draft once.  I can't figure out what was different about that one attempt, but wanted to mention it.

**Comment by mzorz** [comment]
This is super weird @hoverduck ! I have tried it here several times without luck (i.e. works well here). Could it have been a temporal issue? My gut guess would be it's due to some kind of connection problem.
This icon up there in the video 
<img width="39" alt="screen shot 2017-11-14 at 10 23 42 am" src="https://user-images.githubusercontent.com/6597771/32782113-f82c0ace-c94f-11e7-83e4-9e8dd2c29ffa.png">
suggests there is something running in the background on that device, could something else be slowing down things on your handset?

**Comment by hoverduck** [comment]
Yeah, I can't reproduce it anymore either.  I _believe_ I was working from a coffee shop when I initially wrote the ticket, so maybe it is a network slowdown issue.  I'll try to give it another shot next time I'm out of the house.

As for background apps, I always have that :smile:  `AutoInput, LastPass, Tasker, Lux`

**Comment by mzorz** [comment]
> As for background apps, I always have that 😄 AutoInput, LastPass, Tasker, Lux

:D lol - glad it's something network related, OTOH we should be able to tell the user there was some kind of problem, I'll try and see if I can repro on artificially produced slow conditions

**Comment by mzorz** [comment]
Even on super slow connection, tapping `UPDATE` immediately reacts and shows the process of uploading the Post has started for me. Leaving this one closed.
