### ISSUE TITLE
Aztec help icon misalignment

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6736]
### Expected behavior
Aztec help icon should be horizontally aligned to the right and share the same vertical baseline as the `Title` hint

### Actual behavior
The icon is misaligned

<img width="776" alt="screen shot 2017-10-17 at 12 47 23 pm" src="https://user-images.githubusercontent.com/6597771/31674909-652098dc-b363-11e7-8d66-9e4bb40a5b5c.png">

### Steps to reproduce the behavior
1. start a new draft
2. observe the misalignment

**Comment by maxme** [comment]
Fixed via #6730
