### ISSUE TITLE
No 'login with password' option in small devices

### ISSUE THREAD

**Issue by DiegoRBaquero** [wordpress-mobile/WordPress-Android#6749]
### Expected behavior

One is able to login with password in small devices.

e.g.:
![](https://github.com/DiegoRBaquero/Bitacora-Pruebas-Automaticas/blob/master/WordPress-Android/It2/img/Login-Contrase%C3%B1a.jpg?raw=true)

### Actual behavior

No label/button is shown and one is forced to use 'Link in email' login:

![](https://github.com/DiegoRBaquero/Bitacora-Pruebas-Automaticas/blob/master/WordPress-Android/It2/img/Login-Sin-Contrase%C3%B1a.jpg?raw=true)

### Steps to reproduce the behavior

Run the app in default Android AVD (very small screen)

##### Tested on Android Emulator, Android 25

Created with `avdmanager create avd -n test -k "system-images;android-25;google_apis;x86"`

This discovery was part of the *Automated Testing* course at Universidad de los Andes.

**Comment by hypest** [comment]
Thanks for reporting @DiegoRBaquero and appreciate the thoroughness!

I wonder though, is this still an issue? We recently [had a PR merged](https://github.com/wordpress-mobile/WordPress-Android/pull/6685) that adds a scrollview to this screen so the secondary action (password login) is visible by scrolling. Isn't this solution working on your setup?

In any case, let me take this opportunity to note that there is an [open PR](https://github.com/wordpress-mobile/WordPress-Android/pull/6482) that tackles the issue with a more user friendly design so, we're getting there I guess :)

**Comment by DiegoRBaquero** [comment]
Awesome, then I guess we can close this issue :)
