### ISSUE TITLE
Media Library - Retry button/action could be unavailable on failed uploads

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6777]
I found a flow in the app where I can't retry the uploading for a failed media in Media Library.
`Delete` is the only option available on the failed item. 

Steps to reproduce the issue:
- Turn Airplane mode ON
- Go to photos app and share to WP Media Library
- The item is added to the library, but has the `enqueued` state label over it, and the `delete` icon as well
- Turn Airplane mode OFF, and now the device is able to connect to the Internet
- Go back to WP Media Library, do a PTR just to check that everything is working OK
- You will notice the item still had the `enqueued` state label over it, and the `delete` icon. There is no way to re-try the upload.

The only way to get the "retry" icon is to close the app, and restart it from scratch.

**Comment by mzorz** [comment]
Just tested this over the new code as well and can confirm still is happening
