### ISSUE TITLE
Media Library - Item get stuck in the uploading phase

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6778]
If you start uploading a new item to the Media Library, and then, without waiting for the item to be fully uploaded, open the preview screen for another media, it could happen that the first item in "uploading"  state doesn't change its state to "uploaded" when the upload finishes.

Steps to reproduce the issue:

- Start uploading a video to the media library
- Start uploading a picture to the media library
- Tap on the picture and access the preview screen
- Stay on the preview screen till the video finishes the uploading
- Go back to media library
- The video item has the spinning indicator over it. Doesn't matter how long you wait, you have to go back to site menu and than again to media library to get the correct state/overlay over the video

I bet it's a problem with listeners that got un-registered when opened the preview screen.

**Comment by mzorz** [comment]
Just tested this over the new code and can confirm still is happening

**Comment by planarvoid** [comment]
I've tried to reproduce this issue using the test steps and it's not happening any more so I'm closing it.
