### ISSUE TITLE
Hard to delete self-hosted site from the app

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6779]
In the current version of the app long clicking the site in sites list opens the `Delete this site` pop-up. Even though long-click is a common pattern on lists on Android, it seems that some people, even experienced Android users, don't remember it.

We should consider to re-add the "delete site" option in site settings for self-hosted sites.

This request came from `Mobile Requests` P2.

**Comment by iamthomasbishop** [comment]
@daniloercoli Has this been done already? I'm seeing it in the site settings if I go to a single Site then to Settings.

**Comment by daniloercoli** [comment]
Ohh, I think I got where the problem is. 🤕 

In sites list, if you tap and hold a Jetpack site the "Remove site" dialog is shown to users.
Instead if you select that Jetpack site, and go to `Settings`, there is no way to remove it from the app. Just "Disconnect from WordPress.com" is available in settings screen.
