### ISSUE TITLE
Site picker layout is broken in RTL

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6783]
Site picker layout is broken in RTL, the icons appear but not the text.
![device-2017-10-25-102112](https://user-images.githubusercontent.com/518232/31988195-8a1ec7ce-b96e-11e7-8f38-dad1716af47f.png)

Site menu is also half broken.
![device-2017-10-25-102101](https://user-images.githubusercontent.com/518232/31988199-8cfe226e-b96e-11e7-9746-1302bbd778dc.png)

**Comment by mzorz** [comment]
Closed via #6784

**Comment by amire80** [comment]
Thank you!
