### ISSUE TITLE
Async media retry: Post list item not showing right label / first button row

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6796]
Originally reported in https://github.com/wordpress-mobile/WordPress-Android/pull/6795#issuecomment-340025757

### Expected behavior
Tapping on `Retry`  on a failed Post list item should reset its label and first button row to the normal/uploading state

### Actual behavior
The progress bar is shown but both the label and the `Retry` button are still shown.

![image](https://user-images.githubusercontent.com/6597771/32117272-1136d310-bb4e-11e7-9787-e9cdd26a32c2.png)

### Steps to reproduce the behavior

Steps to reproduce:
1. start a new draft
2. include some media items
3. exit the editor
4. turn airplane mode ON
5. see the error appear
6. tap on  `Retry` on the failed Post list item
7. observe the uploading re-starts (notifications appear, etc.) and the progress bar appears and starts getting updates, but both the status label and button rows stay the same (i.e. in the "error/retry" state)

**Comment by mzorz** [comment]
This one is fixed at the FluxC level with this PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/596

**Comment by tonyr59h** [comment]
Closed via #6798.
