### ISSUE TITLE
Use image resize dimensions in blog's options

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#68]
The 'Default Image width' selector uses a bunch of predefined dimensions in it. I think it should show the predefined dimensions the user has set on the blog options.
Something like this:

 * Original size
 * Max (actual dimensions read from options)
 * Medium (actual dimensions read from options)
 * Small (actual dimensions read from options)
 * Custom (Maybe?)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
