### ISSUE TITLE
Comments: Increase comment reply field height for long comments

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6809]
The height of the comment reply field only expands up to a certain point, which makes it difficult to type long comments. (The amount of visible text is more limited on devices with smaller screens.) It would be nice to increase the height of that comment reply field more to display more of the comment.

### Screenshot

![screenshot_2017-10-31-12-56-03](https://user-images.githubusercontent.com/8658164/32225066-bc06311a-be3b-11e7-8ea1-c2af5c1b5ec7.png)

##### Tested on Moto E, Android 5.1

Ref: p4a5px-1YY-p2
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/8076

**Comment by maxme** [comment]
On a tablet/chromebook it looks really bad:

![screenshot 2017-12-21 at 6 53 37 pm](https://user-images.githubusercontent.com/40213/34268242-4adb25a0-e680-11e7-8510-577957d0f941.png)
