### ISSUE TITLE
Eliminate blocking operations when adding media

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6815]
### Expected behavior
Adding media should be done immediately, and any optimisation processing needed is done in the background

### Actual behavior
When image/video optimisation is ON, a dialog is shown that reads "Adding media...". It doesn't take too long (depending on the HW and actual media items being processed) but still it's a blocking operation and is less than ideal.

### Steps to reproduce the behavior
1. go to the ME tab. 
2. go to App Settings.
3. Turn video / images optimsation ON
4. go to Posts list
5. start a draft
6. include some images / videos
7. observe the "Adding media" dialog is shown

**Comment by daniloercoli** [comment]
> Adding media should be done immediately, and any optimisation processing needed is done in the background

Not quite easy to implement. We're adding a resized picture to the editor, and takes time to resize pictures on older devices, or if it's already under heavy loading.

If we use original picture we can crash the app quite easily, due to excessive usage of memory (OOM issues), or to the attempt of drawing a big bitmap over a canvas.

**Comment by mzorz** [comment]
> If we use original picture we can crash the app quite easily, due to excessive usage of memory (OOM issues), or to the attempt of drawing a big bitmap over a canvas.

Can we use just a placeholder that reads "loading...", for example? then once the process is done, we can replace the placeholder with the image that is being use today (that's what I had in mind, sort of).

What this issue looks forward to replace is the blocking dialog alone.
