### ISSUE TITLE
Eliminate blocking operations from Featured Image setting

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6816]
Comes from https://github.com/wordpress-mobile/WordPress-Android/pull/6792#issuecomment-340032363

Related issue #6815 

### Expected behavior
Adding a featured image to a Post shouldn't make you wait while it uploads.

It would be nice to let the UploadService handle everything in the background and save the featured image when it’s done uploading, without blocking interaction

I imagine this:
1. in the settings screen, tap on “Set featured image”
2. media picker appears, and lets the user choose
3. immediately after choosing, the user is taken back to the Post settings screen and they can see the image in the  “featured image” section, with an “Uploading” overlay, just like what we do in the Media Browser screen
4. once the upload is finished, the image is presented there without overlays, just like what is shown there today.

### Actual behavior
A blocking dialog appears when you pick a featured image and you're stuck there until it finishes uploading.

### Steps to reproduce the behavior
1.  start a draft
2. tap on the settings icon in the editor
3. tap on the "Set featured image"
4. pick an image
5. observe the dialog is shown, blocking any interaction until it's finished.

**Comment by antonis** [comment]
Tested on the latest version (`19.7-rc-3`) and the issue is not reproduced anymore 🎉 

https://user-images.githubusercontent.com/304044/165896211-1ad2d888-2485-4c7a-90ad-68f2b2debfa9.mp4
