### ISSUE TITLE
oEmbed support rendering comments

### ISSUE THREAD

**Issue by beaucollins** [wordpress-mobile/WordPress-Android#683]
Support oEmbed for URL's in comments and posts in the posts, pages, comments and reader.

**Comment by oguzkocer** [comment]
Looks like the iOS counterpart of this issue is closed with `Graveyard` label by @kurzee. Does that mean we're not going to add it? Should we close the Android one as well?

**Comment by maxme** [comment]
Still a good idea, but low prio. We should probably whitelist the sources.
