### ISSUE TITLE
Add Word Counts to Editor

### ISSUE THREAD

**Issue by ChrissiePollock** [wordpress-mobile/WordPress-Android#6832]
User requests to see a Word Count in Posts and Pages Editor
#236861-h

**Comment by rachelmcr** [comment]
Related requests tracked for the hybrid editor: https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/443

**Comment by SiobhyB** [comment]
Also requested in 259822-h.

**Comment by sarahblackstock** [comment]
Requested in an app review. 

> too bad that when I write a post the number of words is not directly on the far right as in the desktop version.

**Comment by sarahblackstock** [comment]
Requested via Twitter on January 18.

> Do you think you could do a word count feature in the future? Would love to see that get implemented.

**Comment by SiobhyB** [comment]
Requested again in 264809-h.

**Comment by nellofn** [comment]
Requested again on 289407-h

**Comment by SiobhyB** [comment]
From a three star review:

> It's a shame to have to go to WordPress via the browser to know the number of words that compose our articles.

**Comment by SiobhyB** [comment]
Another request for a word count from a three star review:

> No option to view word count when writing on mobile. You'll need to use the website or a different app just to see how many words you've written.

**Comment by thehenrybyrd** [comment]
From a 5 star review:
> I lo ve this app, however, can we PLEASE have a word-count like the IOS version has?

**Comment by thehenrybyrd** [comment]
And another from a 4 star review:
> It would be nice if it have more text formatting. Also, words count.

**Comment by rfaile313** [comment]
Another request in 2020807-z

>Can you PLEASE add a word count for posts on the Android version like you have on the iOS version?

**Comment by designsimply** [comment]
Adding to Groundskeeping because there are 15 requests tracked here (and at https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/443) so far as of 2019-05-13.

**Comment by planarvoid** [comment]
I think this shouldn't be part of Groundskeeping. It should be a separate (small) project. We should consider whether we should do it both in Aztec and Gutenberg and have some designs.

**Comment by charliescheer** [comment]
Another request #2055362-zen

**Comment by designsimply** [comment]
Thanks @planarvoid! I've added the `Needs Design` label to request a decision about whether to add Word Count and designs for it if yes.

**Comment by poojashetty18** [comment]
Requested again in 2472766-zen

**Comment by SiobhyB** [comment]
This was requested again in 2761039-zen.

**Comment by erricgunawan** [comment]
Requested on 2791066-zen

**Comment by designsimply** [comment]
Block, word, and character count were added to the block editor in https://github.com/wordpress-mobile/WordPress-Android/pull/12191. Props @hypest. 🎉

To find the word count in WPAndroid, open a post or page in the block editor, tap the three dots at top right, and select "Content structure".

<img src="https://user-images.githubusercontent.com/1119271/90044199-8b5dcf80-dc8a-11ea-98b6-e6722a6c56da.jpg" width="270" alt="Screenshot_20200812-105133"> <img src="https://user-images.githubusercontent.com/1119271/90044195-88fb7580-dc8a-11ea-807b-10aefa6be15c.jpg" width="270" alt="Screenshot_20200812-105140"> 

<p style="clear:both;"><sup>Tested and confirmed using WPAndroid 15.5-rc-1 on Pixel 4 Android 10 for WordPress.com, Jetpack, and self-hosted sites.</sup></p>
