### ISSUE TITLE
Creating Draft on Android App sets publish time to current time

### ISSUE THREAD

**Issue by sboisvert** [wordpress-mobile/WordPress-Android#684]
Creating a draft on Android has a different behavior than on the Web interface.
When creating a draft, you leave the Publish: at Immediately and change the status to draft it will save the publish date (as current date/time) when you access the post in the web interface, the publish time will be the time the draft was created. Therefore when you press publish it gets published back in time.

This is a different behavior than the web interface where when saving a draft the Publish date stays to "Immediately" and then later on when you hit publish it sets to the current publish date and not the previous draft date.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
