### ISSUE TITLE
Signup - Errors are not properly shown on the UI

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6840]
A user reported in HS that they were not able to signup to wpcom, but no valid error were shown on the screen. So they were lost, and didn't know what to do next.

FYI: The email was already in use on wpcom.

 See the attached picture:
![da109aab33c7d52f88759d87feb42984ea78eb29](https://user-images.githubusercontent.com/518232/32539437-b0253574-c469-11e7-9c7a-76ed2716289b.png)

Note: Make sure that network errors are correctly handled in that screen.

**Comment by elibud** [comment]
Closing as this is no longer relevant with the new flow.
