### ISSUE TITLE
Aztec + Sharing to WordPress --> empty post content

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6843]
Try to share a new link from YouTube, or Chrome (or any other app) to WP. Create a new article, and tap publish without touching the content. The user reported empty content, even though the publication ends without any errors.

**Comment by nbradbury** [comment]
FYI: I was able to repro this on API 22, 24, and 26, so it doesn't appear to be specific to older Android versions.

**Comment by daniloercoli** [comment]
Oh thanks, I wasn't able to repro it on my Nexus 5X running Android 7.

**Comment by maxme** [comment]
I tried to share different content from different sources with Aztec and it works fine for title + text (from Google Keep), images (from Google Drive and Photos). 

It fails for embeds (Youtube) and only when passed via "share with", when I copy/paste the url directly from youtube and publish, everything seems fine.

**Comment by maxme** [comment]
Problem comes from [this](https://github.com/wordpress-mobile/WordPress-Android/blob/2c4b7042bda043b58cba6e49639b5fba7b1f618a/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1794-L1806) - `contentChanged` is `false` when coming from the share dialog and the content is never saved to the post object.
