### ISSUE TITLE
Visual bug in account creation screen

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6847]
It looks like there's an alignment issue in the sign-up screen, causing the password field text, icon, and visibility toggle to overlap:

![sign-up-screen-display-bug](https://user-images.githubusercontent.com/9613966/32664353-0029cde6-c5ff-11e7-81d3-5fa75e4c1b04.png)

**Comment by hoverduck** [comment]
I'm seeing this too - Nexus 6P / Android 8.0 / wp alpha-85

**Comment by aforcier** [comment]
Duplicate of #6917, which was resolved in #6970.
