### ISSUE TITLE
Reader: rename "Posts I Like" to "My Likes"

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-Android#6848]
When selecting a stream in the Reader, the label for liked posts is currently "Posts I Like." This should be updated to "My Likes" to match the Reader on the web.

**Comment by aerych** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/8129

**Comment by aerych** [comment]
@nbradbury I seem to remember the Android reader at one point had some logic that relied on titles matching a certain string.  Not sure if its still true or if it would ever have mattered for likes, but I want to double check that it won't cause a regression if we change the title in the REST API.  Can you confirm?

**Comment by nbradbury** [comment]
@aerych That should be fine. The Android reader no longer has that logic, instead it relies on the endpoint to determine if we're looking at liked posts (ie: `getEndpoint().endsWith("/read/liked")`).

**Comment by aerych** [comment]
Excellent. Thank ya sir.  I'll whip up the API patch.

**Comment by aerych** [comment]
Deployed.
