### ISSUE TITLE
Bad ability to add WordPress.com account as self-hosted, overrides existing login

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#6869]
### Expected behavior
To get an error or warning when attempting to log into a WordPress.com account masquerading as a self-hosted site

### Actual behavior
The new account is logged in and the existing account is logged out.

### Steps to reproduce the behavior
1) Log into the app with a wpcom account
2) Navigate to the Site Picker and choose Add Site
3) Select `Add self-hosted site`
4) Supply the URL of a WordPress.com site
5) Login with WordPress.com credentials
6) Where'd my other site go?

**Comment by rachelmcr** [comment]
Related: https://github.com/wordpress-mobile/WordPress-Android/issues/4636
