### ISSUE TITLE
Query : Copy gradle.properties-example to gradle.properties.

### ISSUE THREAD

**Issue by vikramvi** [wordpress-mobile/WordPress-Android#6882]
### Expected behavior

1. As per documentation it says

Copy `gradle.properties-example` to `gradle.properties.`

- do you mean rename gradle.properties-example to gradle.properties ?
- I didn't find any gradle.properties file in the project
- Or I need to create new gradle.properties with contents from gradle.properties-example ?

**Comment by vikramvi** [comment]
@rachelmcr can you please per above query ?

I'm from QA Automation background & need to build this project. 
IMHO adding detailed instructions will help who are not from android development background as well.

**Comment by maxme** [comment]
Hi @vikramvi, the documentation is clear and it's a pretty common pattern for open source Android apps.

**Comment by vikramvi** [comment]
@maxme can you please answer to my specific queries in main issue ?
