### ISSUE TITLE
Notifications: Fallback Gravatar doesn't display in comment notifications

### ISSUE THREAD

**Issue by justinshreve** [wordpress-mobile/WordPress-Android#6918]
### Expected behavior

When receiving a comment notification from a user who does not have a Gravatar set, I expect to see the "mystery" fallback avatar like I do in iOS and web notifications.

List view (Web):

<img width="411" alt="screen shot 2017-11-28 at 11 33 58 am" src="https://user-images.githubusercontent.com/689165/33340123-1123fd3a-d430-11e7-9453-6c6ff7675335.png">

Full notification view (Android):

<img width="406" alt="screen shot 2017-11-28 at 11 32 38 am" src="https://user-images.githubusercontent.com/689165/33340082-ed1b2378-d42f-11e7-845b-fa0c4a38b5d0.png">

### Actual behavior

There is a space where the Gravatar should go, but no fallback.

List view (Android):

![listview](https://user-images.githubusercontent.com/689165/33344622-70a453e6-d43e-11e7-89d8-f90c599afe47.png)

Full notification view (Android):

![singleview](https://user-images.githubusercontent.com/689165/33344644-847c8e24-d43e-11e7-93a8-3a0e6a3ea48a.jpeg)

We discovered this while working on a new notification for product reviews (based on comment notifications): https://github.com/Automattic/wp-calypso/issues/18549. However, no matter what I seem to pass, we can't get the same behavior in Android as we do on other platforms. It is a problem in the existing comment notification too.

### Steps to reproduce the behavior

* Leave a logged out comment on a post and use an email without a Gravatar attached.
* Open your notifications on Web vs Android and notice the missing avatar.

##### Tested on

I tested this myself using an emulator (AMIDuOS), running Lollipop, using the Play Store version of the WP app. @timmyc sees the same issue on his actual device (see comment below).

**Comment by timmyc** [comment]
Seen on my device motox4 running Android 7.1.1 and the version of the WP app:

![lqze2f](https://user-images.githubusercontent.com/22080/33346747-977a0630-d445-11e7-9d64-40ee70bf0e61.jpg)
