### ISSUE TITLE
Site-creation rework: Site category screen

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6925]
Implement step 1 of the site-creation wizard, the site category selection.

| Step 1: Site Category |
| --- |
| ![screen shot 2017-11-30 at 23 03 24](https://user-images.githubusercontent.com/1032913/33454818-b0dece24-d622-11e7-864c-c35fe0241fe2.png) |

**Comment by hypest** [comment]
Hey @folletto are the image assets of the 3 categories available to add to this ticket? Thanks!

**Comment by folletto** [comment]
Yep they are 1:1 the same in Calypso:

* https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/type-blog.svg
* https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/type-website.svg
* https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/type-portfolio.svg
