### ISSUE TITLE
Site-creation rework: Creation progress screen

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6929]
Implement the in-progress stage of the site-creation wizard, the UI presented while the site is created and configured in the background.

| Site creation in progress |
| --- |
| ![screen shot 2017-11-30 at 23 27 52](https://user-images.githubusercontent.com/1032913/33455942-53308854-d626-11e7-934d-d092c5d00f27.png) |

| Status bar Notification when app backgrounded |
| --- |
| ![screen shot 2017-11-30 at 23 31 49](https://user-images.githubusercontent.com/1032913/33456036-bcb28304-d626-11e7-8e25-78fbd1bb5e4d.png) |

| Error screen |
| --- |
| ![screen shot 2017-11-30 at 23 35 32](https://user-images.githubusercontent.com/1032913/33456155-305c3aca-d627-11e7-9878-20a8c10851ab.png) |

**Comment by hypest** [comment]
Since this screen is displayed while the site-creation service has already started in the background, it seems that it might be needed to act like a modal, disabling/hiding the top "Back" button and inhibiting the hardware Back button too. What do you think @folletto ?

**Comment by folletto** [comment]
While would be nice to "cancel" I think it's kinda hard to do it at this time (also because I expect most of the time for this screen to be rather quick), so your solution feels excellent to me 👍

**Comment by hypest** [comment]
Regarding the "Step 1 of 5" notification subtitle @folletto , is it OK if we reduce it to "4" steps for now? The fifth step is the preloading of the site on a webview but that will most probably be a main-UI operation and the notification (only visible when main UI is backgrounded) won't reflect it anyway.

**Comment by folletto** [comment]
Ok 👍
