### ISSUE TITLE
Keyboard takes up the whole screen space in landscape

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6941]
![device-2017-12-05-123933](https://user-images.githubusercontent.com/518232/33605304-70db9182-d9b9-11e7-948b-4d0b7b1843f6.png)

### Steps to reproduce the behavior
Start the editor (Aztec or the old Visual editor) and rotate the device landscape

**Comment by designsimply** [comment]
I couldn't replicate this using 13.8-rc-1 on my Pixel 3 Android 10 device.

<img src="https://user-images.githubusercontent.com/1119271/70493561-5d096e00-1ac5-11ea-9e53-9a12896794da.png" width="400" alt="Screenshot_20191209-203400">
<sup>Tested with WPAndroid 13.8-rc-1 on Pixel 3 Android 10.</sup>

Or with a Nexus 4 Android 5.1 emulator.

<img src="https://user-images.githubusercontent.com/1119271/70493613-84603b00-1ac5-11ea-88c2-680cb2d181a2.png" width="400" alt="Screenshot_1575949585">
<sup>Tested with `develop` @ `fd1e8475e6` on an emulator of Nexus 4 Android 5.1.</sup>

Closing. Please re-open if I've missed something in testing.
