### ISSUE TITLE
Editor: Changes lost when the only change is adding media from the media library

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6946]
### Expected behavior

I expect any changes to a post to be saved when I exit the editor or tap the "Update" button in the editor.

### Actual behavior

If the only changes to a saved post are adding media from the media library, the changes are not saved.

### Steps to reproduce the behavior

1. Start a new post.
2. Add some content to the post.
3. Save the draft.
4. Open the post in the editor again.
5. Add media (video or photo) from the media library.
6. Tap the back arrow. Note that autosave does not happen.
7. Open the post in the editor again. Note that the media has disappeared.
8. Add media (video or photo) from the media library again.
9. Tap the "Update" button.
10. Open the post in the editor again. Note that the media has disappeared again.

##### Tested on Nexus 9, Android 7.1.1

**Comment by maxme** [comment]
Might be related to https://github.com/wordpress-mobile/WordPress-Android/issues/6843
