### ISSUE TITLE
Aztec: Editor loses focus when switching from HTML to visual mode with media in the post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#6954]
### Expected behavior

I expect the editor to stay in focus when switching between HTML and visual mode (ideally with the cursor returning to the same position in the post).

### Actual behavior

When there is media in the post, switching from HTML to visual mode loses focus so the cursor is gone, although the keyboard remains open on screen.

### Steps to reproduce the behavior

1. Start a new post in Aztec.
2. Add text and media to the post.
3. Tap somewhere in the post to ensure the editor has focus, if needed.
4. Switch to HTML mode.
5. Switch back to visual mode. Note that the cursor is gone and the editor has lost focus, so typing has no effect.

(If you repeat these steps but only add text to the post, without media, the cursor returns to the same position as before when you switch back to visual mode.)

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-87
cc @mzorz

**Comment by hypest** [comment]
This issue will be fixed when https://github.com/wordpress-mobile/AztecEditor-Android/pull/701 gets merged into wpandroid.
