### ISSUE TITLE
Tapping rapidly twice on the  "create Post" orange button opens 2 editors

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6959]
### Expected behavior
Tapping more than once on the "create Post" orange button should just open the Editor once.

### Actual behavior
The Editor activity is created and added to the backstack twice

### Steps to reproduce the behavior
1. open the app
2. tap on the orange button twice, very quickly
3. Observe 2 Editor screens are opened. Tap back once, and you see the other screen. Tap back once more, and you're taken to the main screen.

**Comment by lethalskillzz** [comment]
Unable to reproduce this bug (API 22).
