### ISSUE TITLE
Update Jetpack Logo

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#6960]
Update the Jetpack logo to the new version everywhere it appears in the app. We have at least a couple of places:

- [x] Last paged image in Log In (animation, json file)
- [x] Install Jetpack prompt (from Stats)
- [x] Empty notifications state with no .com account prompt (not sure this happens on Android but on iOS we prompt to install Jetpack from here)

New icon files:

[jetpack.json.zip](https://github.com/wordpress-mobile/WordPress-Android/files/1540933/jetpack.json.zip)
[icon-jetpack-gray.svg.zip](https://github.com/wordpress-mobile/WordPress-Android/files/1540934/icon-jetpack-gray.svg.zip)

**Comment by theck13** [comment]
I don't think we have any Jetpack drawables in the repository.

**Comment by elibud** [comment]
On iOS we use it on the Stats screen when a self-hosted site doesn't have Jetpack setup and for some Jetpack notifications. I don't know if the naming would match but we call it `icon-jetpack-gray`. I'll update the new version of the icon once I get it from @mattmiklic 

![simulator screen shot - iphone 8 - 2017-12-07 at 11 14 53](https://user-images.githubusercontent.com/5558824/33719846-d5150dc6-db40-11e7-9d2f-fcd6423870fc.png)

**Comment by oguzkocer** [comment]
If I remember correctly we have the same screen on Android. I'll check it out next week when I am on Groundskeeping rotation, thanks @elibud!

**Comment by elibud** [comment]
![img_7083](https://user-images.githubusercontent.com/5558824/33738731-06fd979e-db79-11e7-8277-90afb1c6bff2.png)

This is the login screen.

**Comment by elibud** [comment]
And attached the zipped svg file.

[icon-jetpack-gray.svg.zip](https://github.com/wordpress-mobile/WordPress-Android/files/1540583/icon-jetpack-gray.svg.zip)

**Comment by elibud** [comment]
And the zipped json file.

[jetpack.json.zip](https://github.com/wordpress-mobile/WordPress-Android/files/1540932/jetpack.json.zip)

**Comment by theck13** [comment]
I'm not sure about the logo on the Stats screen, but the logo on the Login prologue screen is actually part of the [jetpack.json](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/assets/login_anims/jetpack.json) file.  It looks like the screenshot below on Android.

<img src="https://user-images.githubusercontent.com/3827611/33746152-a3277532-db78-11e7-801d-fc0780ad203b.png" width="320">

I think @mattmiklic generated that file for the login animations.

**Comment by mattmiklic** [comment]
> I think @mattmiklic generated that file for the login animations.

I sent the new JSON to @elibud yesterday; she added a link to it in the issue but here's a direct link: https://github.com/wordpress-mobile/WordPress-Android/files/1540933/jetpack.json.zip
