### ISSUE TITLE
Plugins v1 Design Review

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#6981]
I wanted to open a new issue for us to discuss and fix a couple possible design issues raised by @nbradbury. It's hard to keep track of these in a PR, so hopefully this will help with that. @mattmiklic could you check out the following issues and reply to **this** issue with your thoughts on those? Thanks!

https://github.com/wordpress-mobile/WordPress-Android/pull/6973#issuecomment-350819648
https://github.com/wordpress-mobile/WordPress-Android/pull/6973#issuecomment-350821510
https://github.com/wordpress-mobile/WordPress-Android/pull/6973#issuecomment-350852834
https://github.com/wordpress-mobile/WordPress-Android/pull/6973#commitcomment-26200524

**Comment by oguzkocer** [comment]
@mattmiklic Just wanted to remind that this is a blocker for us and we need to merge this feature before the end of Friday.

**Comment by mattmiklic** [comment]
> This is nitpicky, but I noticed we're using periods at the end of sentences on snackbars, which Google recommends against here.

This feels a bit strange to me. It also conflicts with our own standards (in the field guide) on using terminal punctuation in our writing. My inclination is to say that we should follow our own standards here unless there's a strong sense from Android users that using punctuation would seem wrong.

**Comment by mattmiklic** [comment]
> The delete confirmation dialog seems very wordy - the web app is much more concise.

This matches the notice displayed in Calypso:

<img width="573" alt="screen shot 2017-12-13 at 1 30 12 pm" src="https://user-images.githubusercontent.com/1396552/33955540-e5658f2a-e009-11e7-99a5-dbaefe6b7990.png">

I believe the expanded message is intended to help reinforce which site the plugin is being removed from. This is appropriate for Calypso since multiple sites can be managed within the app; I think this reasoning would also apply to the native apps.

It might help to split the second sentence starting with "This will deactivate..." into a second paragraph, as Calypso does, to break up the big block of text.

**Comment by mattmiklic** [comment]
> This can be addressed separately, after designer input, but just wanted to mention I'm not a fan of leaving this switch enabled but unclickable (confusing UI, user will likely think it's a bug).

> I felt the same way, but there is not too much we can do. We can set the switch to disabled which will make it grey, but that'll look like the plugin is disabled.

> Seems like we should hide/disable that switch, and maybe add a label informing the user that Jetpack can't be disabled in the app.

This came up in the Design i3 discussion thread (ref: p9c7Jx-96-p2). Specifically it was mentioned that in Calypso Plugins, Jetpack can't be disabled, but there's a link to a "connection management" screen where it can be disconnected. We discussed including the option to disconnect as it was already nearly implemented on iOS, but decided in the end to ship v1 without the ability to disconnect Jetpack in the apps.

A label that explains that the user can't disconnect from the apps might be a good addition, but I think we can ship v1 without it. @rickybanister mentioned that they're going to iterate on the connection management process a bit on the web, so we might link to it in a webview or build our own disconnection flow in the future depending on what they decide.

**Comment by mattmiklic** [comment]
@oguzkocer the solution I proposed in the thread I referenced was to hide the "Active" toggle and the Remove Plugin option specifically for the Jetpack plugin. It would look like this:

![slice](https://user-images.githubusercontent.com/1396552/33963138-e5f3d650-e021-11e7-9aee-b366f4612c78.png)

**Comment by oguzkocer** [comment]
> the solution I proposed in the thread I referenced was to hide the "Active" toggle and the Remove Plugin option specifically for the Jetpack plugin

That sounds good, I'll make that change.

**Comment by mattmiklic** [comment]
> In several other areas in the app, we add some left/right padding in list and detail pages for tablets. Do we think we should do that here?

I just took a look at some of the examples where we're using similar card styling for lists; in post settings, media settings, and sharing. Media settings and sharing adds padding inside the card backgrounds, which does look pretty nice. Post settings doesn't have any additional padding for tablets.

The app is currently a little bit inconsistent when it comes to lists (some use card backgrounds, some have no background; some have padding, some don't; the padding isn't always consistent from screen to screen). I think we will have the opportunity to address all of this at once, in a comprehensive way, in a future project. For that reason, I think it would be OK to proceed without adding padding for tablets at this time — I'll keep it on my list of things we should look at when we're looking at tablet-specific design issues.

**Comment by nbradbury** [comment]
I'm good with all of the above.

**Comment by oguzkocer** [comment]
#6997 implemented the changes discussed in this issue.
