### ISSUE TITLE
Drop the help (?) button in the Aztec title

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6984]
I guess we can remove the `ReleaseNotesActivity` at the same time.

**Comment by lethalskillzz** [comment]
Then I guess there will be a need to drop the What's new (?) button as well.

![screenshot_2017-12-12-15-49-22](https://user-images.githubusercontent.com/8193385/33890859-af2b53b4-df54-11e7-8d60-2834cc5d1c25.png)

**Comment by maxme** [comment]
@lethalskillzz you're right. We'll actually drop this dialog as well, since we're going out of beta. Ref https://github.com/wordpress-mobile/WordPress-Android/issues/6958

**Comment by mzorz** [comment]
Closing via #7019
