### ISSUE TITLE
Jetpack theme activation error

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#6988]
Following the steps below results in theme activation error: `The specified theme was not found.`

1. Activate a theme on a wp.com site
2. Activate the same theme for a Jetpack site

![screenshot_1513208336](https://user-images.githubusercontent.com/662023/33968219-ee1fb0de-e034-11e7-8cc0-1f08af1bf7a2.png)

**Comment by elibud** [comment]
Is it possible the theme is not installed on the site? Ping me when you get to work on this one, since I've implemented the feature on iOS I might have some ideas.

**Comment by oguzkocer** [comment]
No, it's not related to that and it's more than likely a DB issue.

**Comment by oguzkocer** [comment]
Fixed in #6996.
