### ISSUE TITLE
Can set WordPressEditor library to start and disable editing

### ISSUE THREAD

**Issue by 120660021** [wordpress-mobile/WordPress-Android#7000]

**Comment by maxme** [comment]
@120660021 Can you explain in details what's the problem, eventually with steps to reproduce your problem.

**Comment by 120660021** [comment]
These two methods can not be used?
---------------------------------------------------------------------------
// MARK: - Editing

ZSSField.prototype.enableEditing = function () {

    this.wrappedObject.attr('contenteditable', true);

    if (!ZSSEditor.focusedField) {
        ZSSEditor.focusFirstEditableField();
    }
};

ZSSField.prototype.disableEditing = function () {
    // IMPORTANT: we're blurring the field before making it non-editable since that ensures
    // that the iOS keyboard is dismissed through an animation, as opposed to being immediately
    // removed from the screen.
    //
    this.blur();

    this.wrappedObject.attr('contenteditable', false);
};

**Comment by 120660021** [comment]
@maxme

**Comment by 120660021** [comment]
I want to preview directly using WordPressEditor library

**Comment by maxme** [comment]
@120660021 Apparently there are not used in the app, but you can probably use these functions by calling them like we do in `EditorFragment` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/86b8e81dea6801510873df446368f60208215973/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L1089-L1091):

```
mWebView.execJavaScriptFromString("ZSSEditor.enableEditing();");
```

And:
```
mWebView.execJavaScriptFromString("ZSSEditor.disableEditing();");
```

**Comment by 120660021** [comment]
According to what you said has been modified, but still can edit。
---------------------------------------------------------------------------------------
![qq 20171215180616](https://user-images.githubusercontent.com/8433054/34037247-0351928a-e1c3-11e7-8fd1-d5c88eff5574.png)
![device-2017-12-15-180755](https://user-images.githubusercontent.com/8433054/34037258-0aa17474-e1c3-11e7-95de-d67d3403bad3.png)

**Comment by maxme** [comment]
In the screenshot, you're using the "Beta" editor, which is not the one you're modifying (the Webview-based editor). Try to go to the "Me" tab, select "App Settings" and pick "Beta" editor in the Editor selector.

**Comment by 120660021** [comment]
Set, but still editable
---------------------------------------------
![qq 20171215183139](https://user-images.githubusercontent.com/8433054/34038142-3931c2aa-e1c6-11e7-8608-f1f3b5bc8529.png)

**Comment by maxme** [comment]
@120660021 I'm sorry, but you'll have to debug this one then. We don't use these functions and we're going to remove the Webview based editor from the app soon.

Also note the app and the editors are GPL licensed, you will have to release your work under GPL if you publish it.

**Comment by 120660021** [comment]
Thank you
