### ISSUE TITLE
Compatibility Issue in LearnMorePreference

### ISSUE THREAD

**Issue by strooonger** [wordpress-mobile/WordPress-Android#7003]
### Expected behavior
In API version > 23, when no network connection, dialog will close, and toast "Could not load page" will show.
![image](https://user-images.githubusercontent.com/34035150/34108509-4aa13292-e43b-11e7-887d-89e7a9ddc552.png)

### Actual behavior
In API version <=22, when no network connection, dialog will not close, and toast will not show.
![image](https://user-images.githubusercontent.com/34035150/34108419-e625c594-e43a-11e7-8612-2424b40f98b5.png)

### Steps to reproduce the behavior
Following the steps can reproduce the bug.
1. Login account in WordPress.
2. Click "Settings" in "Configuration" tab.
3. Click "More" in "Discussion" tab.
4. Choose "Airplane mode" to turn off the network.
5. Click "LEARN MORE"

The root cause is "onReceivedError(WebView view, int errorCode, String description, String failingUrl)" is added in API 23, which is not compatible for the devices in API version <=22. See [WebViewClient document](https://developer.android.com/reference/android/webkit/WebViewClient.html)
##### Tested on [device], Android [version]
Nexus 5X, API version 26 and 22

**Comment by maxme** [comment]
Thanks for the report, we're going to remove this very soon via https://github.com/wordpress-mobile/WordPress-Android/issues/6958
