### ISSUE TITLE
Gravatar change breaks if "Don't keep activities" is ON

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7007]
### Expected behavior
The Gravatar change feature (triggered via the Me screen by tapping on the Gravatar) should work as normal, letting you select a picture and then upload it automatically.

### Actual behavior
After selecting a picture, nothing apparent happens. The app shows up still on the Me screen without any progress or change.

### Steps to reproduce the behavior
* Enable the "Don't keep activities" from the System's Developer options
* Go into the the app, logged in a WPCOM account and navigate to the Me screen
* Tap on the Gravatar and select a picture
* Nothing happens next. It should have continued with the Gravatar change process.

##### Tested on [device], Android [version]
Nexus 5X, Android v7.1.2

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue following the steps above. In my testing, I can finish the Gravatar change process and confirm that my new Gravatar appears even with "Don't keep activities" on.

Tested on Nexus 9, Android 7.1.1.
