### ISSUE TITLE
Local video preview fails

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#7011]
Discovered by @daniloercoli:

- Create a new post
- Tap to add media
- Long press on a device video to show preview
- It should play the video, but instead the screen remains black

**Comment by designsimply** [comment]
Tested and confirmed that if you long-press on an item in the Aztec media picker you either get a blank screen or an error that says, "unable to load media." ([35s](https://cloudup.com/c-RaBLJpAdL))

<sup>Tested with WPAndroid 13.8-rc-1 on Pixel 3 Android 10.</sup>

Moving to `AztecEditor-Android`, see https://github.com/wordpress-mobile/AztecEditor-Android/issues/886.
