### ISSUE TITLE
Plugins: Unable to delete plugin, leads to bad active status

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#7014]
### Expected behavior
To be able to delete a plugin

### Actual behavior
The plugin deactivated, but failed to remove:
![wp-android-plugins-failure-to-delete](https://user-images.githubusercontent.com/7233112/34222062-3cec4878-e588-11e7-9af9-a8b188fea418.jpg)

### Steps to reproduce the behavior
1) I created a new site on Pressable and connected it via Jetpack
2) I loaded the site in the app and navigated to Plugins
3) I opened Akismet and attempted to Remove it
4) The plugin was deactivated, but threw the above error on delete.

Subsequent attempts to delete all throw the same error.  Now the plugin says deactivated in the app and wp-admin agrees.  I tried re-activating it from the app, and now the app thinks it's active but wp-admin says it's not.

The application logs don't show anything relevant.

**Comment by hoverduck** [comment]
Update: I had my test sites confused.  I saw this error on a site I created on Pressable, not jurassic.ninja.

So this is likely a case of the site being misclassified as Atomic even though it's a regular Pressable + Jetpack

**Comment by oguzkocer** [comment]
@hoverduck I doubt there is anything we can do about this one on the client, but I'll look into it.

**Comment by oguzkocer** [comment]
I've looked into this issue again and it's a server side one for sure. @lezama Do you think your team can take a look at this and see if there is anything we can fix on the server side? Also, I am closing this issue, but it'd be great to open a new one wherever it makes the most sense. Thanks!

**Comment by lezama** [comment]
We can take a look

**Comment by lezama** [comment]
@oguzkocer could you give us the error message the API request is returning?

**Comment by oguzkocer** [comment]
@lezama I don't have a way to reproduce the issue, maybe @hoverduck can help.

**Comment by hoverduck** [comment]
I tried reproducing it as well, and got a slightly different result.

When I clicked REMOVE PLUGIN I ended up stuck on the "Disabling Akismet Anti-Spam..." screen and can't navigate away.  After killing the app and starting over I see that it _is_ deactivated, but then clicking REMOVE again leaves me stuck on "Removing Akismet Anti-Spam...".  I let it sit there for a few minutes with no action, and it repeats if I do kill/restart the app.

Since it's a Pressable site I wasn't able to get to the server logs :confused:

**Comment by oguzkocer** [comment]
If we can find a reliable way to reproduce this issue, I think we might be able to improve the "being stuck" issue. However, looking at the code, that really shouldn't happen unless there is an edge case we are missing. Please feel free to ping me if you can reproduce that issue reliably with the steps required and I'll take care of it.

As a side note, I _think_ we should be able to get the logs for a Pressable site. That might be worth asking around.
