### ISSUE TITLE
Unable to dismiss failed upload notification, drains battery

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#7017]
### Expected behavior
To be able to dismiss a notification

### Actual behavior
It keeps coming back from the dead

### Steps to reproduce the behavior
1) Connect a Jetpack site and make sure you can access it from the app
2) Shut down the site (but don't disconnect it from wpcom)
3) Start writing a post on the site and let it try to auto-save your draft to the web

Now I have a "Upload failed" notification that returns immediately after I dismiss it.  Clicking the Retry button likewise dismisses the notification before it immediately returns.

https://cloudup.com/cPcKqkv7PDK

**Comment by hoverduck** [comment]
Looks like this is worse than it initially seemed...I rebooted my phone as the only way to get rid of the notification.  I thought it worked, but as a result of bad timing, this was also around when my Tasker script that hides work-related notifications came on.  So it did not work...I rebooted, and I'm still seeing the notification.  My phone has been on for ~5 hours since the reboot, and WordPress has used 18% of the battery, claiming it's been active for 3h 46m in the foreground.

<img width=350 src="https://user-images.githubusercontent.com/7233112/34238044-abf098b0-e5cd-11e7-879c-0d5f952532b2.jpg">

What's worse is that I've since disconnected the missing site from my wpcom account, but it still shows up in the sites list on the app, even after doing a pull-refresh.  Logging out and back in seems to have been the trick to actually resolve the problem.

Here's a sample from the Application Logs:

```
57 - [Dec-21 02:30 API] Dispatching action: UploadAction-PUSHED_POST
58 - [Dec-21 02:30 API] Dispatching action: PostAction-PUSHED_POST
59 - [Dec-21 02:30 POSTS] PostUploadHandler > Post upload failed. UNAUTHORIZED: API calls to this blog have been disabled.
60 - [Dec-21 02:30 POSTS] updateNotificationErrorForPost: There was an error uploading this post: You don't have permission to view or edit posts.
61 - [Dec-21 02:30 POSTS] PostUploadHandler > Completed
62 - [Dec-21 02:30 API] Dispatching action: PostAction-UPDATE_POST
63 - [Dec-21 02:30 API] Dispatching action: PostAction-PUSH_POST
64 - [Dec-21 02:30 API] Volley error on https://public-api.wordpress.com/rest/v1.1/sites/140222830/posts/new/?context=edit&locale=en_US - exception: null
65 - [Dec-21 02:30 API] StackTrace: com.android.volley.AuthFailureError
 at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
 at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
```

**Comment by hoverduck** [comment]
One more time... Even after logging out and back in and confirming the bad site was not in my Sites List, the notification still came back after I published a post on a different site.  This time I clicked on the notification itself rather than just the Retry button, and was taken to this screen:

![wp-android-bad-post](https://user-images.githubusercontent.com/7233112/34258364-a278153e-e62b-11e7-8098-39c85d556de9.jpg)

From here I clicked Delete, and it seems like that finally cleared up the issue (although I've been wrong about that before).

**Comment by mzorz** [comment]
The loop behavior was detected in https://github.com/wordpress-mobile/WordPress-Android/pull/7385 but it seems this proves there are other ways to trigger the same condition. @daniloercoli is putting together a solution which I think will work - I'll review later once the PR is up 👍
