### ISSUE TITLE
Posting/Media - multiple media failures show "1 file not uploaded" notification

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#7029]
When multiple images that are being uploaded fail in the Editor (I tried on Aztec only), an error notification reading "1 file not uploaded" is shown, when it should be for multiple files.

**To Test** 
- Add several pictures to the post
- Put the device in airplane mode
- Media fails
- The notifications says "1 file not uploaded"

**Comment by rachelmcr** [comment]
I tested and couldn't reproduce this issue. When multiple media files failed, the correct number was shown, for example:

> Upload failed for "Post Title"
> 3 files not uploaded
