### ISSUE TITLE
Autoupdates status sometimes gets out of sync

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#7033]
Steps to reproduce:

1. Go to Plugins > Hello Dolly.
1. Turn off Autoupdates.
1. Deactivate the plugin.
1. Remove the plugin.
1. Go to Calypso and re-install the plugin.
1. Go back to the app and open the Plugins page.
1. Check to see if the "Active" and "Autoupdates" statuses match.

<strong>Result:</strong> the "Active" status is correct but the "Autoupdates" status sometimes gets out of sync with what I see on the web compared to what I see in the app.

<img width="1280" alt="screen shot 2017-12-22 at fri dec 22 2 50 30 pm" src="https://user-images.githubusercontent.com/1119271/34313521-f3bbd130-e728-11e7-8b1d-4512e7ab425d.png">

<img width="1280" alt="screen shot 2017-12-22 at fri dec 22 3 00 00 pm" src="https://user-images.githubusercontent.com/1119271/34313524-f8b08834-e728-11e7-88b4-a13de16e18ea.png">

<img alt="screenshot_20171222-145041" src="https://user-images.githubusercontent.com/1119271/34313566-4883993c-e729-11e7-9348-b9fb12cd9209.png" width="270" /> <img alt="screenshot_20171222-145035" src="https://user-images.githubusercontent.com/1119271/34313565-486bb92a-e729-11e7-92e6-2e8fe87ed5a7.png" width="270" />

<sup>Tested with Firefox 57.0.1 on macOS 10.13.2 and Pixel, Android 8.1.0, WPAndroid alpha-90.</sup>

**Comment by designsimply** [comment]
Note: this seems to fix itself after a while, so the only problem may be that the update doesn't happen right away and it's a bit confusing when they are out of sync (and I'm not sure whether anything can be done about that).

**Comment by oguzkocer** [comment]
I wouldn't expect users to do this kind of thing and it's expected that it'll go out of sync for a short period of time if these specific steps are followed. There is nothing we can do about this.

With pull to refresh coming #7015, the user should be able to manually start a sync in such a case. Since that's pretty much all we can do, I am closing this issue. Thanks for the report @designsimply!
