### ISSUE TITLE
Avatar on Me Tab is Blank for Accounts without Gravatar

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7035]
### Expected
Avatar view on the Me tab shows the default icon (e.g. [`gridicons-user-circle`](https://github.com/Automattic/gridicons/blob/master/svg-min/gridicons-user-circle.svg)) if the account does not have an image on Gravatar.

### Observed
Avatar view on the Me tab shows a blank, white circle if the account does not have an image on Gravatar.  See the screenshot below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/34315951-319e6f26-e747-11e7-8e45-ef3aab3c684f.png" width="320">

### Reproduced
1. Log in to account without Gravatar.
2. Go to Me tab.
3. Notice blank, white circle.

##### Tested
Google Pixel 2 running Android 8.1.0 with WordPress 9.0

**Comment by arunsathiya** [comment]
**My test case.**

Removed the Gravatar associated with my WordPress.com email ID on [the Gravatar settings page](https://en.gravatar.com/emails), still saw the same old Gravatar image.

Logged out, logged in. Still saw the same Gravatar image.

Cleared data for the WordPress Android app and logged in. I see the blank image as reported in this issue.
