### ISSUE TITLE
Add Consistent Tracking for Sharing to WP

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#7050]
When sharing from another app to WP through the sharesheet, we're not tracking `media_library_photo_added`. We should since this action is being done.

Thanks @daniloercoli for finding and reporting this.

**Comment by kwonye** [comment]
@daniloercoli so far we only do `MEDIA_LIBRARY_ADDED_PHOTO` for a single item, but with sharing there's an option to do multiple media items. Any ideas how we should approach this?

1. We send an individual tracking event for every media item
2. We send a single event with data about every media item

**Comment by daniloercoli** [comment]
Hey @kwonye - In `EditPostActivity`, when multiple pictures are added to the post, we're sending an individual tracking event for each of the media added. (Point 1. of the list above).

It's not a problem performances wise, since events are gathered all together in sent to the server in batch.

**Comment by kwonye** [comment]
Ah perfect, thanks @daniloercoli!
