### ISSUE TITLE
Include Jetpack status when contacting support for a Jetpack site 

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#7067]
When a user contacts support for a Jetpack site we label the issue `jetpack`, lets also include the Jetpack connection status information as `jetpack-status:status` to help trouble shoot Jetpack issues.

cc: @sarahblackstock

**Comment by oguzkocer** [comment]
We have expanded on this idea and added site state information for the current blog in Zendesk. We have also added the site's state in the blog information field, in which we list all the blogs of a user.

I believe we don't need this anymore, but if there is anything we want to do more about it please let us know. /cc @ScoutHarris
