### ISSUE TITLE
Reinstate launching follow-up services from login service

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#7068]
Previously, the `LoginWpcomService` was responsible for launching follow-up services (reader, notifications) upon successful login. Since the `LoginWpcomService` was moved to the login flow library (https://github.com/wordpress-mobile/WordPress-Android/pull/6935), the services are now started [when the app is relaunched instead of in the background](https://github.com/wordpress-mobile/WordPress-Android/commit/b246d4dbb9c3dcc4ea3517e52b1a1a9c255b667b#diff-061a2d2319816d00f81a9918ff3e2026). While minor, we should reinstate this behavior in the future.

Originally noted here: https://github.com/wordpress-mobile/WordPress-Android/commit/8d189cd1e64b8efab32f0c3808745455f8dae8c8#r26715591.

**Comment by designsimply** [comment]
@aforcier is this issue still valid? Can we categorize this issue as technical debt? What are the implications of updating this, why would it be good to update and what good impact will it have?

**Comment by aforcier** [comment]
Was sorting through some old notifications and came across this, sorry I missed it!

It's been quite a long time, I can't say for sure what the implications would be, or even how relevant this is anymore with all the changes to the login flow since.

I think it's fair to either categorize this as technical debt or close this entirely. Since it doesn't seem to have affected us in 2.5 years I'd be inclined to just close it.

**Comment by planarvoid** [comment]
I agree @aforcier , I'm closing this issue 👍
