### ISSUE TITLE
Plans: Update plans icon to Jetpack logo

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7075]
### Expected behavior

The Plans icon in Calypso is now using the Jetpack logo, and the app should match it:

<img width="274" alt="screenshot 2018-01-09 15 02 42" src="https://user-images.githubusercontent.com/8658164/34747686-3d973424-f54e-11e7-9ffa-3da0a498ad22.png">

### Actual behavior

The app is still using an old logo for Plans under My Sites > Site Detail screen.

Internal ref: p4a5px-272-p2

**Comment by folletto** [comment]
Related: https://github.com/Automattic/gridicons/issues/261

**Comment by elibud** [comment]
Pending this merge: https://github.com/Automattic/gridicons/pull/273 and Gridicon regenration
