### ISSUE TITLE
Site description spacing isn't correct in single-site Reader view

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#7104]
There should be more padding/margin above the site description

![img_6937](https://user-images.githubusercontent.com/1158819/34966050-b171f3e8-fa0d-11e7-8bf0-7f139f9466bc.jpg)

**Comment by 0nko** [comment]
That's iOS, isn't it?

**Comment by beaulebens** [comment]
Yep

**Comment by 0nko** [comment]
Moved to wordpress-mobile/WordPress-iOS#8855.
