### ISSUE TITLE
QuickPost button cannot be added to the homescreen

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#7107]
### Expected behavior
* Quick Post widget can be added to a homescreen

### Actual behavior
* After saving the widget doesn't appear on the homescreen

### Steps to reproduce the behavior
* User selects a QuickPost from widgets
* User picks a site 
* User picks a name for the widget
* User  saves widget
* Widget does not appear on the screen

##### Tested on [device], Android [version]
* Google Pixel 2 XL - 8.1.0

**Comment by rachelmcr** [comment]
I tested this on my Nexus 9, Android 7.1.1, and couldn't reproduce the issue, so it may be device specific.
