### ISSUE TITLE
Themes: App cannot load theme details or view/try .org themes

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7113]
### Expected behavior

I expect to be able to tap on any uploaded theme on my site (in the app's Themes section) to view details about it.

### Actual behavior

If I uploaded the theme from the WordPress.org repo, and it isn't available on WordPress.com, I get the error "Could not load theme" when I select any of the following:

- The theme's thumbnail image
- Try & Customize
- View
- Details
- Support

The only theme action that works is "Activate," which successfully activates the theme on my site. 

### Steps to reproduce the behavior

1. In a web browser, upload a theme (that isn't available on WordPress.com) to an Atomic or Jetpack site from the WordPress.org theme repo: https://wordpress.org/themes
2. In the app, select that site and open the Themes section.
3. Try tapping on the uploaded theme.
4. Try selecting each of the actions from the theme's ellipsis menu.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-92

**Comment by designsimply** [comment]
Tested and confirmed using Pixel, Android 8.1.0, WPAndroid alpha-93 that when I install a WordPress.org theme, such as OnePress, using a browser that the "Activate" option is the only one that works for that theme.
