### ISSUE TITLE
Notifications: New Post Notifications missing overlay icon in comment list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7120]
### Expected behavior

I expect new post notifications to show the same icon overlay (over the Gravatar) as appears in Calypso:

![image](https://user-images.githubusercontent.com/8658164/35049525-37f81ccc-fb98-11e7-81b6-131f47ef2fc3.png)

### Actual behavior

New post notifications in the app show a grey circle instead of the icon seen in Calypso:

![screenshot_20180117-151141](https://user-images.githubusercontent.com/8658164/35049744-e8fac1fa-fb98-11e7-9924-ea122ab8057c.png)

### Steps to reproduce the behavior

1. Enable new post notifications on a site — currently possible at https://wpcalypso.wordpress.com/following/manage (internal ref: p5PDj3-4mp-p2)
2. Publish a post on that site
3. Check your notifications in Calypso and the app

**Comment by jancavan** [comment]
The "Blog posts" icon should be used here instead of the "info" icon:
https://github.com/Automattic/wp-calypso/issues/21623

**Comment by theck13** [comment]
The "info" icon now appears for my new post notifications on Android.  It looks like it was fixed by r169675-wpcom along with the corresponding [iOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/8460).  Can this be closed, @rachelmcr?

**Comment by rachelmcr** [comment]
Ah yep, this can be closed, too. Thanks!
