### ISSUE TITLE
Reader shows gallery instead of featured image

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#7142]
When a reader post has several images, we show a gallery of those images instead of showing the featured image. We should always show the featured image when one is assigned.

[This post](https://themechroblog.wordpress.com/2018/01/15/flawless-victory-fatality/) is an example of this. Right now we show this instead of the featured image:

<img width="250" alt="themechroblog-reader-chrome" src="https://user-images.githubusercontent.com/3903757/35183883-f54ddfd6-fdba-11e7-8d5e-82ce802a0099.png">

**Comment by KokkieH** [comment]
This is inconsistent with how posts are displayed in the web Reader, though. Don't we want to display Reader Post Cards in the mobile app Reader as well?

Came looking for this as we had a complaint from a user [via Twitter](https://twitter.com/ItsJoanAkob/status/969442715246186497) about this change.
