### ISSUE TITLE
Can't activate Premium Theme

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#7152]
When working with a WordPress.com site that has Premium or Business you should be able to activate a premium for free.  

However when I tried to activate a few different premium themes on my site that has the business subscription on it, I was being asked to purchase the theme and was unable to activate it for free 

To replicate this behavior:
1. Select a site that has either Business or Premium on it
2. Go to My Site > Theme
3. Find a premium theme and try to activate it.
4. It should take you to another page where it asks you to purchase the theme instead of being able to activate it.

Samsung Galaxy tabA
WordPress 9.2
Android 5.1.1

**Comment by sdixon194** [comment]
+1 was able to reproduce on two separate Android devices.
