### ISSUE TITLE
Plugins: "Your WordPress Version" is not detected/displayed

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7185]
### Expected behavior

When I view a plugin detail page, I expect to tap on the plugin version info and see:

- Version
- Last Updated
- Requires WordPress Version
- Your WordPress Version

### Actual behavior

On all my sites (Atomic & Jetpack, on various hosts) the "Your WordPress Version" isn't showing my actual WordPress version. Instead, all I see is a `?`:

![screenshot_20180201-165439](https://user-images.githubusercontent.com/8658164/35691913-b7a9cc9c-0771-11e8-9843-8495c399f99d.png)

### Steps to reproduce the behavior

1. Select a Jetpack or Atomic site in the app.
2. Open the Plugins section.
3. Select a plugin.
4. Under the name of the plugin, tap where it says "Version 1.0 (i)".
5. On the popup that appears, look next to "Your WordPress Version."

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-95

**Comment by nbradbury** [comment]
This is caused by a FluxC bug that has since been fixed. Ref: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/689
