### ISSUE TITLE
Login button does nothing if PlayServices are not available

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7191]
https://github.com/wordpress-mobile/WordPress-Android/pull/7184 introduced a new issue where the Login button doesn't do anything if PlayServices are not available or outdated.

Steps to reproduce:
1. Downgrade Gooogle PlayServices on your device
2. Clear app's data and launch the app
3. Dismiss the "Play Services need updating" popup
4. Tap on the "Login" button and notice that nothing happens

**Comment by mzorz** [comment]
Closed via #7192
