### ISSUE TITLE
Images added in incorrect order

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#7199]
I was able to replicate by following these steps:

1. Navigate to the new post editor within the app.
2. Tap the + icon.
3. Select multiple images to be added to the post in the order you’d like them to appear.
4. For example, here I wanted the images to appear in the order indicated by the numbers:

![image](https://user-images.githubusercontent.com/1522856/35765794-c20be1d8-08cb-11e8-9c92-b6bb287171dc.png)

The posts didn’t actually appear in the order indicated by the numbers when uploaded to the app, though:

![image](https://user-images.githubusercontent.com/1522856/35765797-e09e9f5a-08cb-11e8-9e4f-e6fa6b21a072.png)

**Comment by daniloercoli** [comment]
Media Picker returns the selected pictures in the correct order. I was able to replicate this issue in Aztec demo app by just adding >3 pictures to it. Moving this issue on the Aztec repo here: https://github.com/wordpress-mobile/AztecEditor-Android/issues/627
