### ISSUE TITLE
Invite roles are not working for the first time

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#7202]
After a fresh install, it looks like the roles won't be fetched for the first time a user tries to invite (and possibly change) roles. It only shows the follower role as the available option. We should probably refresh the page after roles are fetched or start the fetch early so it's ready for first use.

**Comment by designsimply** [comment]
I tried the following steps:

1. Go to People.
1. Check roles. 
1. Delete and reinstall the app.
1. Log back in and go to People again.
1. Check that roles for existing users looks good.
1. Try to invite a user as an Editor or Author role.

Result: roles appeared normally for existing users and when inviting a new user after deleting and reinstalling the app.

<sup>Tested with WPAndroid alpha-156 (12.0 alpha) on Pixel 3, Android 9 on a WordPress.com Premium site.</sup>

@oguzkocer I am closing this issue as I was unable to replicate the problem in testing. Would you please do a quick check of my testing steps above to make sure I got them right and re-open the issue if anything is amiss?

**Comment by oguzkocer** [comment]
@designsimply Those steps make sense to me, thanks a lot for checking it!
