### ISSUE TITLE
Can't post to hidden site

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#7203]
When the user tries to edit a post for a site that isn't visible, we [show this error message](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L325):

![download](https://user-images.githubusercontent.com/3903757/35890048-088ada22-0b6c-11e8-8e8e-380753072726.png)

I'm not sure we should be doing this - it seems odd not to be able to post to a site just because it was hidden in the site list.  But if there is a reason for us to do this, we should at least reword the message (it tells the user to go to Settings, which is incorrect) and perhaps ask them if they want to unhide it.

**Comment by rachelmcr** [comment]
I tested this again and it's no longer an issue. Changes made to the site are saved and the site is automatically shown in the site list.
