### ISSUE TITLE
Adding QuickPress widget leads to the Old login flow

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7214]
### Expected behavior
When a user is not logged in and they add the QuickPress widget the **new** login flow is shown.

### Actual behavior
When a user is not logged in and they add the QuickPress widget the **old** login flow is shown.

### Steps to reproduce the behavior
1. Try to add the QuickPress widget to your home screen.

##### Tested on [device], Android [version]
Emulator - Api 27

**Comment by maxme** [comment]
I wonder if we should kill that feature.

**Comment by malinajirka** [comment]
@maxme So should I just display a Toast "Please login into WordPress" instead?

**Comment by maxme** [comment]
This, or even kill the QuickPress feature completely, it's probably super low usage.

**Comment by malinajirka** [comment]
I'll just display the Toast for now. We will probably add Android App Shortcuts support within few weeks so we can decide then whether we want to keep the QuickPress widget or not.

**Comment by rachelmcr** [comment]
I tested this again (in WP alpha-136) and when I'm logged out of the app and add the QuickPress widget I'm taken to the new login flow as expected. Closed as resolved.
