### ISSUE TITLE
Unable to paste text to a blank post/page editor

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7217]
### Expected behavior

When I copy text to my device's clipboard, I expected to be able to "long-press" anywhere in a blank post/page editor and see the option to "Paste". This expectation comes from how copying/pasting works with other apps on my device.

### Actual behavior

After I copy some text to my device's clipboard and navigate to a blank post/page editor, nothing happens if I long-press within the editor. I need to first enter some text before I can long-press and see the option to "Paste". 

### Steps to reproduce the behavior

1. Copy some text to the device's clipboard.
2. Open the WordPress app.
3. Navigate to My Site > Blog Posts and tap the button to create a new blog post.
4. Long-press anywhere within the editor for the new blog post to confirm the option for pasting doesn't show.
5. Enter some text to the editor then confirm you're able to paste by long-pressing in the editor and selecting the "Paste" option.

This was reported in an app review and is also something I've come across in day-to-day usage of the app.

Ref: p77Llu-9N5-p2

##### Tested on Pixel, Android 8.1.0

**Comment by supernovia** [comment]
Noting I can currently paste to the title and content area, as well as to the slug, add categories field, etc.  I'm on alpha-111

**Comment by SiobhyB** [comment]
@supernovia: I can confirm this works for me now too! 🎉 Thanks for testing. :)
