### ISSUE TITLE
Cannot compose offline with images

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7218]
The fact that post cannot be composed offline with images came up in a round-up of feedback in p77Llu-9N5-p2.

### Expected behavior

For images that are uploaded to a post or page while offline to be saved to the post when the device is back online.

### Actual behavior

Any images that are uploaded to a post or page while offline are removed when you attempt to update the post. You can, however, manually tap on each image to retry the upload.

### Steps to reproduce the behavior

1. Turn WiFi off on device.
2. Navigate to My Sites > Blog Posts and either create a new post or edit an existing one.
3. Upload multiple images and enter some text.
4. Turn WiFi back on on device.
5. Navigate to post to "Update". You'll then see an error alerting you to the fact that your images will be lost.

##### Tested on Pixel with alpha-96, Android 8.1.0

**Comment by SiobhyB** [comment]
Requested again in 260509-h.

**Comment by maxme** [comment]
This was fixed with the introduction of Aztec and with the post and media upload service improvements.
