### ISSUE TITLE
Request for full screen when scrolling through posts in Reader

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7219]
The recent round-up of app reviews (internal ref: p77Llu-9N5-p2) included this review:

> While reading, the navigation buttons should autohide, and the option to top notification should be available to so that we can get full view of the blog we are viewing. Other than that everything works perfectly. Just the full screen view would be really appreciated as most other apps autohide the navigation buttons , which are stupid on android.

An example of an app that hides the navigation buttons is Twitter for its "[Twitter Moments](https://twitter.com/i/moments)" feature. You can navigate to Twitter's search results and then tap on a "Moment" to be taken to a full screen view, where the navigation buttons are hidden and you scroll through the different Tweets in that "Moment".

**Comment by donalirl** [comment]
Another request for this feature in #1563012-zd:

>I hope the post reader screens would hide the Android notification and navigation bars when the user scrolls down while reading, like in many other reading apps.

Another example of an app that does this is Pocket.

**Comment by planarvoid** [comment]
This has been already implemented. Scrolling down in a reader hides the top and bottom toolbars. I'm closing this issue.
