### ISSUE TITLE
Typo in en-rCA and en-rGB Stats page

### ISSUE THREAD

**Issue by MindyPostoff** [wordpress-mobile/WordPress-Android#7236]
On the Stats page there is a typo on the Tags & Categories header, where an extra "s" is added to Categories, so that it reads:

Categoriess

**Comment by rachelmcr** [comment]
Thanks for reporting, @MindyPostoff! Translations (including English varieties) are controlled by GlotPress, and anyone is welcome to contribute new translations and fixes: https://translate.wordpress.org/

I went ahead and submitted fixes for this issue:

https://translate.wordpress.org/projects/apps/android/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=59070&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

https://translate.wordpress.org/projects/apps/android/dev/en-gb/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=59070&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc
