### ISSUE TITLE
Reflect changes to SuggestDomainsPayload

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#7246]
As mentioned in the #7245, while updating the fluxc hash, I had to pass the correct number of parameters to `SuggestDomainsPayload`. Let's make sure we pass the correct parameter values for the `onlyWordpressCom` in `NewUserFragment` and `NewBlogFragment`.

@hypest Do you mind taking care of this as soon as you're back from the meetup, it shouldn't take more than 2 minutes :)

/cc @theck13

**Comment by hypest** [comment]
I think this will be handled "automatically" when we merge the `feature/new-signup` branch in a few days. Besides, `NewUserFragment` and `NewBlogFragment` will be completely removed by that merge.

**Comment by oguzkocer** [comment]
Sounds good, thanks for taking a look @hypest!
