### ISSUE TITLE
Bug: can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [wordpress-mobile/WordPress-Android#7252]
### Expected behavior
Be able to build the project just fine, after importing it

### Actual behavior
Has a build error:
![image](https://user-images.githubusercontent.com/5357526/36351488-8516dad2-14b3-11e8-9c2e-3e1c6ce0ccee.png)

### Steps to reproduce the behavior
clone the project and open it.

##### Tested on [device], Android [version]
IDE:
Android Studio 3.2 Canary 3
Build #AI-173.4595177, built on February 9, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by rachelmcr** [comment]
Please be sure to copy the `gradle.properties-example` file to `gradle.properties` — step 3 in the [build instructions](https://github.com/wordpress-mobile/WordPress-Android#build-instructions). :)

**Comment by AndroidDeveloperLB** [comment]
Why does it have build instructions?
Why not clone and build, like any other normal repo?
Anyway, now that I've read it, I can't find where is the "gradle.properties" file on step #3. This file doesn't exist. What does it even mean to copy it ? Copy its content? Copy by creating a new file somewhere and putting the content there?

**Comment by catehstn** [comment]
It's in the top level project directory: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/gradle.properties-example

Unfortunately with complex projects you can't always clone and build, but some setup is required - especially relating to things (e.g. API keys) that can't just be checked into GitHub.

**Comment by AndroidDeveloperLB** [comment]
@catehstn Your link points to "gradle.properties-example" file . This I already found, and didn't write about it.
What I ask about is "gradle.properties".

**Comment by catehstn** [comment]
@AndroidDeveloperLB right, you need to copy that file to make the `gradle.properties` file, as per [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/7252#issuecomment-366680333).

This isn't a sample project? This is an actively developed, complex application. It's also not a library.

**Comment by AndroidDeveloperLB** [comment]
Oh I was hoping it has a library somewhere within, for rich-text editing.
Can you please modularize it, so that the part of rich-text-editing would be on a different repository?

**Comment by rachelmcr** [comment]
You can find the rich-text editor component that's used in the WordPress app (code name Aztec) in this repository:

https://github.com/wordpress-mobile/AztecEditor-Android

**Comment by AndroidDeveloperLB** [comment]
@rachelmcr Thank you. Sadly I've found an issue with it, so I've reported here:
https://github.com/wordpress-mobile/AztecEditor-Android/issues/643
