### ISSUE TITLE
Update supported Jetpack login URLs

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#7262]
On the new Jetpack connection flow we currently trigger a native log in redirect for this URL: `wordpress.com/log-in`, we need to also support this one: `wordpress.com/log-in/jetpack`. 

@planarvoid  can you please update Android to support both and target your changes at the frozen branch (we want this to go out with 9.4). Thank you.

iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/8657

**Comment by planarvoid** [comment]
This is currently not an issue on android because we don't do `equals` match on the path, only `contains`.
@elibud should I implement the more strict check as part of this ticket?

**Comment by elibud** [comment]
Yes I think it's a good idea to do a more strict check, I'll reopen and move the milestone.
