### ISSUE TITLE
App language is restored back to default when the app is killed

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7267]
### Expected behavior
When a user selects a language in the app settings, the language is preserved even when the app is killed.

### Actual behavior
When a user selects a language in the app settings and the app is killed, the app is again in the default language.

### Steps to reproduce the behavior
1. Change language in the settings to Hebrew.
2. Force close/kill the app.
3. Start the app - the app is in the default language.

##### Tested on [device], Android [version]
Emulator - Api 27

Might be related to #7265.

**Comment by maxme** [comment]
Note: this happens on API > 25 due to [`updateConfiguration`](https://github.com/wordpress-mobile/WordPress-Android/blob/79b83d4e6d75a58b30d189d31428e43ef14b0aa0/WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java#L126) not working anymore.
