### ISSUE TITLE
Unspecified error when posting to site which is on https but was added to app with http

### ISSUE THREAD

**Issue by gingerling** [wordpress-mobile/WordPress-Android#7271]
### Expected behavior

I added a site that runs with https, I added it without https://www. Is connected fine and gave me access to everything, however after clicking upload, there was an unspecified error and the changes would not upload. I re-created the site again, the same thing happened, I had access to I recreated it AGAIN, this time specifying https, and it worked fine.

**Comment by gingerling** [comment]
Sorry I pressed submit by mistake and now it won't let me edit it.

I added a site that runs with https, I added it without https://www. Is connected fine and gave me access to everything, however after clicking upload, there was an unspecified error and the changes would not upload. I re-created the site again, the same thing happened, I had access to edit and view all of the posts however when I try to upload the changes, it just said error changes cannot be uploaded or something. I recreated it AGAIN, this time specifying https, and it worked fine.

**Comment by gingerling** [comment]
Tested on Android 7, Samsung Galaxy Note 5.

**Comment by gingerling** [comment]
Actually the issue might be something else, it's now not working again even with https

**Comment by gingerling** [comment]
Hi can anyone provide me with help debugging, I am getting a generic error and am no longer able to post to my site. I can't seem to get any info out of the app .

**Comment by rachelmcr** [comment]
Hi @gingerling! Our support team can take a look — to get in touch, please open the app, go to the Me tab (the person icon at the top), open "Help & Support," and select "Contact us." That way our team can use the in-app support to gather more details about your site and the errors and investigate that for you. :)
