### ISSUE TITLE
Auth/Settings: Non-admins on self-hosted site can't update password in app

### ISSUE THREAD

**Issue by gingerling** [wordpress-mobile/WordPress-Android#7272]
### Expected behavior
Apologizes if it's a duplicate, I'm on mobile and it won't let me search.

I recently changed my password and it doesn't seem possible to update a password in the app, the only option seems to be to delete and re add a site from the app.

**Comment by gingerling** [comment]
To clarify, self hosted site, and the user type was editor. I noticed that when logged in with an admin account there may be a way to change the password under security. However this does not show for an editor, only the jetpack security settings show then.

**Comment by rachelmcr** [comment]
Thank you for the report! I confirmed that I only see the option to change my password on a self-hosted site if I am an administrator (tested on Nexus 9, Android 7.1.1, WPAndroid alpha-97).

Related: https://github.com/wordpress-mobile/WordPress-Android/issues/6225

**Comment by gingerling** [comment]
Thanks!

**Comment by rachelmcr** [comment]
As noted in https://github.com/wordpress-mobile/WordPress-Android/issues/8478, if a site isn't using Jetpack, this bug means that non-admin users see a blank page in the site settings:

![image](https://user-images.githubusercontent.com/8658164/47496521-e7095f80-d84e-11e8-8456-a1db88a833c2.png)
