### ISSUE TITLE
After adding a new site to app, it lands you in other site

### ISSUE THREAD

**Issue by gingerling** [wordpress-mobile/WordPress-Android#7273]
### Expected behavior

After adding a new site to the app, the next green would show the posts etc from the new site. 

### Actual behavior

When you add a new site to the app, rather than dropping into that site, you are showing the posts etc from whichever site you were on before you added the the new one. To you access the posts of the new site you have to

**Comment by gingerling** [comment]
Go back through the switch site menu to select the new site.

**Comment by gingerling** [comment]
Hey can someone help me enable debugging or something, I can't get this the app to upload, the error message is generic and unhelpful. I'm really keen to help but I can't work out how to get more information out of the app.

**Comment by rachelmcr** [comment]
Thanks for the report! We're currently tracking this issue here: https://github.com/wordpress-mobile/WordPress-Android/issues/5325
