### ISSUE TITLE
Weird UX for post categories

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#729]
When selecting a category for a post, if a category is already checkmarked and you try to checkmark Uncategorized, the Uncategorized checkmark disappears right after you add it. I understand why this is being done, but it's a weird user experience.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by aforcier** [comment]
Re-opening since it's a post settings issue and not an editor issue.

**Comment by hypest** [comment]
Not able to replicate with recent code. Closing this. Please, feel free to open again if issue still stands. Thanks!
