### ISSUE TITLE
Navigating to Themes > Support > Write takes you to web-version of the editor

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7291]
### Expected behavior

I expected the design of the post editor to be consistent, no matter how I reached it within the app.

### Actual behavior

If you navigate to My Site > Themes > Support, you're taken to the web view of the theme's support page. If you then tap the "Write" icon at the top, you're taken to the web-version of the editor instead of the app's editor. The web-version of the editor has a few problems, which has the potential to create a poor experience for the user.

Is there any way to redirect users back to the app's editor?

### Steps to reproduce the behavior

1. Go to My Site > Themes within the app. 

2. Tap on the "Support" option on the top of page. 

3. Tap on the "Write" button in the top toolbar. 

### Tested

I tested on my Pixel phone, which runs on Android 8.1.0 and uses WP alpha 98.

We received the report from the Android Developer Support Team, who tested on a Pixel C tablet.

Internal reference: 263150-h

**Comment by SiobhyB** [comment]
An example of an issue that comes up when using the editor in a browser while on mobile: https://github.com/Automattic/wp-calypso/issues/22761

**Comment by SiobhyB** [comment]
@rachelmcr just pointed me to the following issue that would fix this: https://github.com/Automattic/wp-calypso/issues/13532

I think we can close this one in favour of that? (I don't have admin rights on this repository else would close myself.)

**Comment by rachelmcr** [comment]
Closing this issue. :)
