### ISSUE TITLE
Quick Video progress is unclear

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#73]
Testing quick video with a short 2 second video. 
From the posts lists, tap to show the dashboard and choose quick video
When I hit publish I'm taken back to the posts list.
I see my quick video post under local drafts and sometimes I see the activity spinner spinning.
If I'm patient, I'll see the spinner start (possibly a second time) and the quick photo post will finally move out of the local drafts and into the posts list. 
If I choose quick video from the dashboard (and without posts in the background) I don't see any indication of progress. If I return to the posts list at this point I don't see a local draft, but if I refresh the successfully uploaded quick video appears after the sync.
This is mostly a UX issue where there is a couple of points where it is unclear what is happening with the quick video I took.
Nexus One / 2.3.6

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
