### ISSUE TITLE
Plugin List: When a new plugin is installed the switch for activate does not appear.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#7317]
When working in the Android app on the plugins page, if you install a new plugin the switch to activate that plugin does not appear right away.  To be able to activate it you have to leave the plugin page and then enter it again.  Once reloaded the activate switch appears.

To Replicate:
1. go to the plugins page and search out a new plugin
2. when looking at the new plugins page, click the install button.
3. the auto update button will appear after install, but the activate button will not.

<img style="width: 50%;" src='http://cld.wthms.co/DJRUOs+'>

Tested on:
WordPress 9.5
Android 5.1.1
Galaxy Tab A

**Comment by oguzkocer** [comment]
I am guessing this was only an issue during beta as this hasn't been the case for a very long time. Closing the issue.
