### ISSUE TITLE
Update strings in new signup flow

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7320]
The following strings should be updated for style and consistency with iOS:

1. The signup button on the prologue screen: `Sign Up`. New text: `Sign up for WordPress.com`
2. The magic link screen: `We sent an email with a link, open it to proceed with your new WordPress.com account.` New text: `We sent you a magic signup link! Check your email on this device, and tap the link in the email to finish signing up.`
3. The “new account” screen (after using the magic link) says this at the bottom: `Log in will be possible by getting a new email like the one you just used, but you can setup a password if you prefer.` New text: `You can always log in with a magic link like the one you just used, but you can also set up a password if you prefer.`
4. After selecting the username on the "new account" screen, at the top of the username screen: `Your username is currently "{username}". It will be used for mentions and links, but otherwise people will just see your display name, "{display name}"`. New text: `Your current username is {username}. With few exceptions, others will only ever see your display name, {display name}.`

Internal ref: p5T066-Bj-p2
cc @hypest @theck13

**Comment by hypest** [comment]
I've added the Design and Copy Review labels. When we clear those we can implement the final strings. /cc @folletto

**Comment by folletto** [comment]
Barred Editorial changes, all looks good to me 👍 

I know you know, but: we need to make sure this is the same across Android and iOS.

**Comment by hypest** [comment]
Removing "Needs design review" as per @folletto 's comment above.

**Comment by elibud** [comment]
Removing Needs Copy Review as the Editorial team has been involved in the original thread and we are in a hurry to get the updated strings out to translators.

**Comment by benhuberman** [comment]
I know the label has been removed, but just wanted to confirm anyway that yes, the proposed changes look great.
