### ISSUE TITLE
Signup: Error uploading a Gravatar during signup flow

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7322]
### Expected behavior

I expect to be able to upload a Gravatar on the New Account screen in the signup flow (or for that upload option to be disabled if it isn't expected to work).

### Actual behavior

Every time I try to upload a Gravatar during the signup flow, I get this error:

> There was some trouble uploading your avatar.

When I try the same Gravatar on the Me tab after completing signup, the upload works.

### Steps to reproduce the behavior

1. Select "Sign Up" on the prologue screen.
2. Select "Sign up with email."
3. Enter a new email address.
4. Check your email and use the magic link to continue signing up.
5. On the New Account screen, tap on the Gravatar icon at the top of the screen.
6. Select an image to use as your Gravatar.
7. Crop the image as desired.

Result: The upload fails and an error appears. (I don't see any errors in the activity log in the app.)

##### Tested on Nexus 9, Android 7.1.1

**Comment by elibud** [comment]
@theck13 please look into this one

**Comment by theck13** [comment]
The only case when that error is shown without any application logging is [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java#L587) (i.e. when the upload is finished and the image is being set to the view on the screen).  @rachelmcr, if you tap the ***Continue*** button after uploading the image and seeing the error, is the avatar on the ***Me*** tab still not shown?  Note that the Gravatar API is not instantaneous so you may have to wait a few minutes.  I would recommend testing with these steps.

0. Get to ***New Account*** screen by signing up.
1. Tap avatar icon.
2. Choose image.
3. Crop image.
4. Notice ***There was some trouble uploading your avatar.*** error message.
5. Tap ***Continue*** button.
6. Tap system Overview navigation button.
7. Remove WordPress app by swiping it from the list.
8. Wait five minutes.
9. Launch WordPress app.
10. Go to ***Me*** tab.

**Comment by rachelmcr** [comment]
> if you tap the Continue button after uploading the image and seeing the error, is the avatar on the Me tab still not shown?

The Gravatar _does_ show up on the Me tab when I test with the steps you outlined. (It didn't show up until I relaunched the app.)

**Comment by theck13** [comment]
> It didn't show up until I relaunched the app.

The image view on the ***Me*** tab isn't refreshed unless the app is moved to the background, which is why relaunching helped.

The Gravatar API has some delay issues before the image can be accessed with the URL.  Perhaps we could use a different error message to indicate the upload succeeded, but the image cannot be displayed.

**Comment by elibud** [comment]
Can't we just display the just uploaded image unless the update fails?

**Comment by theck13** [comment]
We should be able to set the view to the downloaded image when the Gravatar API fails, but that may still confuse users when they see an empty avatar on the ***Me*** tab after seeing their image on the ***Signup Epilogue*** screen.  Ultimately, fixing the API would be the best solution.

**Comment by elibud** [comment]
Oh got it, I had misunderstood the issue. In the upload successful case is the Me tab automatically refreshed eventually though?

**Comment by theck13** [comment]
Yes, the ***Me*** tab refreshes during the [`onResume` stage](https://github.com/wordpress-mobile/WordPress-Android/blob/4e90f03f66f872d6c0989501ee5f2df36e22f0c0/WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java#L223-L227) in the [`refreshAccountDetails`](https://github.com/wordpress-mobile/WordPress-Android/blob/4e90f03f66f872d6c0989501ee5f2df36e22f0c0/WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java#L253-L254) and [`loadAvatar`](https://github.com/wordpress-mobile/WordPress-Android/blob/4e90f03f66f872d6c0989501ee5f2df36e22f0c0/WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java#L288-L319) methods, specifically.  That means it will be refreshed once the app is resumed after being in the background.  However, if the Gravatar API has not updated the URL yet, the avatar will still show the default icon.

**Comment by elibud** [comment]
I'm more concerned about what happens if the app doesn't go to the background. For example, a user signs up, uploads their avatar, uses the app for a bit and then checks the Me tab, will it have the picture?

**Comment by theck13** [comment]
That depends on the Gravatar API.  The URL we get back from the API immediately after uploading an image is exactly the same as it is five minutes later.  Sometimes the URL returns an error.  Sometimes the URL returns an image.
