### ISSUE TITLE
Site Creation: API call to site address suggestion endpoint needs to be authenticated

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7336]
### Expected behavior

During the site address step of the site creation flow, I expect that the API call the app makes to the site address suggestion endpoint will be authenticated. That way, I can register a subdomain that matches my username (since that subdomain is reserved and isn't other available).

### Actual behavior

When I search for a subdomain that matches my username, the exact match doesn't appear in the results.

### Steps to reproduce the behavior

1. Sign up in the app for a new account.
2. After signup, create a new WordPress.com site in the app.
3. On the site address step, search for a site address that matches your username. (For example, if you signed up with the username `rachelmcr` search for a site address `rachelmcr.wordpress.com`.)

Result: The exact match doesn't appear in the results. This is most likely because the API call is not authenticated, so the address appears to be unavailable.

##### Tested on Nexus 9, Android 7.1.1

**Comment by hypest** [comment]
I've opened a [PR over at the FluxC repo](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/731) that fixes the call. When that gets merged I will incorporate it to wpandroid.

**Comment by elibud** [comment]
@hypest assigning this over to you since you are already working on it.
