### ISSUE TITLE
Mobile Plans for Gutenberg Support

### ISSUE THREAD

**Issue by timnolte** [wordpress-mobile/WordPress-Android#7340]
### Expected behavior
Gutenberg block editing support.

### Actual behavior
Unknown

### Steps to reproduce the behavior
Install Gutenberg plugin, app shows no indicator that Gutenberg is installed.

##### Tested on [device], Android [version]
Moto Z2 Force, Android 8.0

_This is more of a way to open up the discussion on what the plans will be, or should be, for the mobile apps once Gutenberg hits core. There has been a lot of focus and talk on the user experience in the WordPress Dashboard and post editing but I have heard no one talk about what Gutenberg means for the mobile apps. I use the mobile app about 80%-90% of the time when managing my sites so this is a huge topic for me._

**Comment by rachelmcr** [comment]
cc @maxme @koke Since this is a pretty big topic, could we close this issue and use https://make.wordpress.org/mobile/ for discussion on mobile Gutenberg?

**Comment by koke** [comment]
Yes, we have only recently started exploring our options and it's a bit early to tell, but I'm planning to make a post on make/mobile once we have a clearer plan. Our goal is to support as much of the Gutenberg experience as possible on mobile, but we're still defining how we get there.
