### ISSUE TITLE
Plugins: VaultPress on Atomic site marked as inactive

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7346]
### Expected behavior

Clear status for all plugins, including plugins like VaultPress that are managed for me on Atomic sites. For example, Calypso shows this status:

> Auto-managed on this site

### Actual behavior

The VaultPress plugin is marked as inactive and I can't change it. The most confusing case for me was VaultPress, but other plugins that are managed for me on Atomic sites (Jetpack, Akismet) can be potentially confusing because I don't have any controls for them.

### Steps to reproduce the behavior

1. Select an Atomic site in the app.
2. Open the plugins section.
3. View the status and details for Atomic managed plugins (Jetpack, Akismet, VaultPress).

### Screenshots

Plugins in the app:

![2018-03-01 11 55 27](https://user-images.githubusercontent.com/8658164/36843820-07c5723a-1d48-11e8-9710-adf8bbc3666b.png)

Plugins in Calypso:

![screenshot 2018-03-01 11 39 32](https://user-images.githubusercontent.com/8658164/36843745-ca6e15b8-1d47-11e8-9a09-160244f203ed.png)

**Comment by oguzkocer** [comment]
Closing this issue in favor of #7367 which is being worked on. My comment [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7575#issuecomment-394488823) is also relevant.
