### ISSUE TITLE
Timezone screen collapses while loading the list.

### ISSUE THREAD

**Issue by tarunvijwani** [wordpress-mobile/WordPress-Android#7352]
### Expected behaviour
When clicked on timezone option, list of cities and their timezones should be displayed.

### Actual behaviour

When clicked on timezone option, timezone screen collapses while loading the list and redirecting to the dashboard.
### Steps to reproduce the behaviour

1.  Click on Settings option under My sites
2.  Click on Timezone

Link to the GIF: https://d.pr/isyZpR
##### Tested on [device], Android [version]
Device: Redmi note 3
App Version: 9.5-rc-1
Android Version: 5.1.1

**Comment by rachelmcr** [comment]
I tried reproducing the bug as described, but the timezone list loads correctly for me. I also changed the timezone and confirmed my change was saved successfully.

I tested with a new site created in the app. The test site was set to UTC+0 by default, and I am in UTC+0 myself, in case that makes a difference.

**Comment by hypest** [comment]
I think this issue might be happening on some devices (and Android version combinations) where this crash occurs: https://github.com/wordpress-mobile/WordPress-Android/issues/7376
