### ISSUE TITLE
Two versions of EventBus lib available in wpandroid

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7354]
We currently expose 2 versions of EventBus in wpandroid:

* de.greenrobot.event:2.4.0
* org.greenrobot.eventbus: 3.0.0 (via FluxC)

There doesn't seem a good reason to have both around so, we should consolidate.

**Comment by hypest** [comment]
By quickly having a look at this it seems we will need to migrate the usage of `registerSticky()` which has been depricated in 3.x versions of the lib.

**Comment by designsimply** [comment]
@hypest would you consider this a `Tech debt` issue?

**Comment by hypest** [comment]
👋 @designsimply , yes, this can be considered tech debt, thanks for checking! I will add the label.
