### ISSUE TITLE
Update Plugin Detail Version Row Layout

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7363]
Update the layout of the plugin detail version row including the changing height and button style.  See the animation below for illustration.

![plugin_detail_install_button](https://user-images.githubusercontent.com/3827611/36912232-63196a4a-1e03-11e8-90d2-89ad49d55c3f.gif)

**Comment by oguzkocer** [comment]
This is slightly related, but we should also fix this asymmetry. @theck13 Let me know if you want me to separate it into another issue.

<img width="589" alt="plugin selection" src="https://user-images.githubusercontent.com/662023/36922508-12bf4b22-1e36-11e8-82d0-94a08137c709.png">
