### ISSUE TITLE
Posts accidentally deleted

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#7374]
### Expected behavior

Not to be able to accidentally delete a post.

### Actual behavior

The user mentioned that holding the phone in the right hand places the "Delete" button in a very precarious location. He accidentally hit the delete button on the post. The issue was then compounded when there was no way to access the trash from the mobile app.

![screenshot_20180209-120723](https://user-images.githubusercontent.com/5558824/36974712-5f0e7580-2056-11e8-94d2-2f02b8a55f1d.jpg)|![screenshot_20180209-120737](https://user-images.githubusercontent.com/5558824/36974715-60a287a6-2056-11e8-844e-52f46c8ab78c.jpg)

Internal ref: p2-p4a5px-29j

**Comment by mzorz** [comment]
Will do this and follow along the lines of what's implemented on iOS in https://github.com/wordpress-mobile/WordPress-iOS/pull/8806

**Comment by iamthomasbishop** [comment]
Needs a copy review, but something like this should do for a stop-gap solution:

![screenshot 2018-03-05 14 59 14](https://user-images.githubusercontent.com/1200432/36999499-e1f15312-2085-11e8-838c-a362b88b4e91.png)

Also should apply to Pages list and other post types where the user can `Trash` (eg. Portfolio, etc).
