### ISSUE TITLE
Alignment removed from images with caption

### ISSUE THREAD

**Issue by gemmagarner** [wordpress-mobile/WordPress-Android#7427]
Image alignment is removed from images with a caption.

### Steps to reproduce the behavior

1. Open the Android app
2. Tap the add icon to create a new post
3. Tap the + (add media) icon
4. Choose an image
5. Tap the image in the post to load the customisation options
6. Reduce the size to "Medium" (or any size smaller than the content width on desktop)
7. Select “Centre” in Alignment
8. Add a caption in "File Details"
9. Tap the X to return to the post
10. Tap “Publish”

### Expected behavior

The image to be centre aligned.

### Actual behavior

It looks like alignment is ignored because the image sits to the left. This is most noticeable on desktop browsers where the width of the content is larger.

![caption-ignored](https://user-images.githubusercontent.com/11627765/37107003-1cdf32ae-222b-11e8-8f2c-e01d72353243.jpg)

If you go back to the image customisation options in the app after publishing or updating the post, alignment is set to "None".

![caption-ignored-3](https://user-images.githubusercontent.com/11627765/37107610-ad22d248-222c-11e8-8cdb-c98a9d13b225.jpg)

The image alignment is correct if no caption is added.

##### Tested on [device], Android [version]

Google Pixel 2016
Android 8.1.0
App version 9.4

Reported in 891885-f

**Comment by khaykov** [comment]
There was some rework of image settings around caption and image sizes, which appears to fix this issue, as I can no longer reproduce it. Closing for now.
