### ISSUE TITLE
Cannot Login to WP Mobile After Server Move

### ISSUE THREAD

**Issue by pointsnerd** [wordpress-mobile/WordPress-Android#7455]
### Expected behavior
Previously had WP Mobile working normally but after moving servers, the app cannot pull down new post, comments or any other information.  

### Actual behavior
Tried removing site and re-adding.  When attempting to re-add, WP Mobile states "Couldn't connect to the WordPress site.  There is no valid WordPress site at this address.  Check the site address (URL) that you entered."

All attempts at different formats produce the same error (http, https, www)

### Steps to reproduce the behavior
Attempt to add http://www.pointsnerd.ca 

##### Tested on [device], Android [version]
OnePlus 3, Andr
![screenshot_20180309-104652](https://user-images.githubusercontent.com/37222971/37221712-1d98beb4-2388-11e8-9ca9-2b5916f32ece.jpg)
oid 8.0.0

**Comment by theck13** [comment]
@pointsnerd, please follow the steps below to contact our support and get your issue resolved.

1. Tap the ***Help*** action button in the upper right-hand corner of the Site Address screen (i.e. the same as your screenshot).
2. Tap the ***Application Log*** button on the Help screen.
3. Tap the ***Copy*** action button in the upper right-hand corner of the Application Log screen.
4. Tap the back arrow to exit the Application Log screen.
5. Tap the ***Contact Us*** button on the Help screen.
6. Enter your name and email address into the input fields.
7. Enter a short description about your issue in the ***How can we help?*** field.
8. Paste your application log into the ***How can we help?*** field after your short description.

I'll pass along your information to the support team to help expedite a resolution.
