### ISSUE TITLE
German translation missing (9.6-rc.1)

### ISSUE THREAD

**Issue by pr0gr8mm3r** [wordpress-mobile/WordPress-Android#7478]
After update to version 9.6-rc.1 the strings on the first page (managing website articles, ...) were in English, although the interface language said 'Deutsch (Deutschland)'. Setting it manually to 'Deutsch' really changed it to German

##### Tested on LG K3, Android 6.0

**Comment by maxme** [comment]
@pr0gr8mm3r thanks, we'll investigate before 9.6 final release.

**Comment by AmandaRiu** [comment]
@pr0gr8mm3r I've tested several scenarios on an emulator running Android 6.0 and for this version and am unable to duplicate the issue, but I may not be looking in the right place. Can you attach a screenshot of the issue? 

Here is list of screenshots that compare the major screens on version 9.5 on top, to version 9.6 on the bottom:
![comparison_9 5_to_9 6](https://user-images.githubusercontent.com/5810477/37358948-f8bfaa12-26b1-11e8-970f-d08ca7fe1eaa.png)

**Comment by pr0gr8mm3r** [comment]
1. I had version 9.5 installed and the language was set to German (worked)
2. Updated to 9.6, language of everything except the news feed (2nd tab) was in English
3. I went into the settings (3rd tab: App Settings), the interface language was set to 'Deutsch (Deutschland)'
4. I have set it to 'Deutsch' (there was no 'Deutsch (Deutschland)' option)
5. Worked

**Comment by malinajirka** [comment]
I was able to reproduce the behaviour.
1. Change system settings to any language other than English (Czech for example)
2. Install the app
3. The app interface is in English

When you sign in and open the app settings, it shows "Czech" but the app interface is still in English. When you repick the Czech in the app settings, it finally changes the app interface to Czech.

Tested on
SDK 27 Pixel 2, SDK 27 Emulator

Works on Emulator SDK 18, so it's related to the SDK version.

@mzorz We might want to change the milestone back to 9.6, as it seems like a critical bug. WDYT?

**Comment by daniloercoli** [comment]
API 21 - Android 5.0.2 - Custom ROM
I can't replicate the issue reported above ^, but found a minor problem.
Started from scratch with a clean installation and system language set to Italian. Switched to English US in app. Close and re-open the app. The app is in English, when I open App Settings it says English (United States) , but when I tap to switch the language the entry English United Stated is not selected. (Minor problem, but it should be selected)

**Comment by mzorz** [comment]
Addressed in #7557

**Comment by mzorz** [comment]
Closing via #7557
