### ISSUE TITLE
Cannot restore a trashed post

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#7489]
Steps to reproduce:

1. Go to My Sites > Blog Posts.
1. Tap "Trash" for any post.
1. Try to figure out how to restore the post that was just deleted.

<strong>Result:</strong> couldn't find a way to restore my trashed post or undo that action if it was a mistake (even though there is now a delete confirmation which is awesome 😍).

<img src="https://user-images.githubusercontent.com/1119271/37433336-1bef4034-27a1-11e8-9137-41b6dfa3630c.png" width="270">
<sup>Tested with Pixel, Android 8.1.0, WPAndroid alpha-103 for https://convenient-cuban.jurassic.ninja/ running WordPress 4.9.4 and Jetpack 5.9.</sup>

**Comment by rachelmcr** [comment]
Do you think we could close this issue in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/4693 (which will add a trash filter for finding and restoring trashed posts)?

**Comment by oguzkocer** [comment]
We currently show a Snackbar with an Undo button when a post is trashed and only actually trash the post when the snackbar is dismissed. We'll hopefully work on the post filters soon which will make the undo action unnecessary as @rachelmcr mentioned. I think we can close this issue now unless you disagree @designsimply?
