### ISSUE TITLE
Jetpack Connect Leaves Multiple Instances of Stats

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7500]
### Expected
After going through the Jetpack connect flow and completing the final step by tapping the ***Approve*** button, the ***Stats*** screen is shown and tapping the back arrow goes to the ***Sites*** tab.

### Observed
After going through the Jetpack connect flow and completing the final step by tapping the ***Approve*** button, the ***Stats*** screen is shown and tapping the back arrow goes another ***Stats*** screen.  Tapping the back arrow on the second ***Stats*** screen goes to the ***Sites*** tab.

### Reproduced
1. Log in with only self-hosted site without Jetpack.
2. Go to the ***Notifications*** tab.
3. Tap the ***Set Up Jetpack*** button.
4. App launches web view.
5. Tap the ***Install Jetpack*** button at the bottom of the web view.
6. Tap the ***Install Now*** button at the bottom of the web view.
7. Tap the ***Activate Plugin*** button at the bottom of the web view.
8. Tap the ***Set Up Jetpack*** button in the middle of the web view.
9. App launches login flow.
10. Enter an email address in the ***Email Address*** field.
11. Tap the ***Next*** button.
12. Tap the ***Enter Your Password Instead*** button.
13. Tap the ***Next*** button.
14. Tap the ***Continue*** button.
15. Tap the Approve button in the web view.
16. Notice the first ***Stats*** screen.
17. Tap the back arrow.
18. Notice the second ***Stats*** screen.
19. Tap the back arrow.
20. Notice the ***Sites*** tab.

##### Tested
Google Pixel 2 on Android 8.1.0 with WordPress alpha-103

**Comment by planarvoid** [comment]
I can't reproduce this on the last version so I'm closing this ticket
