### ISSUE TITLE
Site-creation: domain suggestion screen may be too obscured

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7509]
In some cases, even on big-screen devices, the suggestions part of the domain suggestion screen may be completely obscured by the combination of the on-screen keyboard and the "Create site" CTA,  causing confusion to the user.

[Example video](https://www.usertesting.com/v/418f5f13-b247-4918-9e83-c7f52d7f9d80?encrypted_video_handle=BYMTqb8UneeSnLx9njEjXA#!/notes) from a user test (skip to the [2:55] timestamp).

**Comment by planarvoid** [comment]
@folletto Hey, I was thinking about hiding the toolbar in the whole site creation process on scrolling. That might give us some extra screen space. WDYT? Or any other ideas?

**Comment by SylvesterWilmott** [comment]
This issue has been addressed in the new Site Creation

**Comment by mattmiklic** [comment]
Confirmed that this is fixed with the new site creation flow.
