### ISSUE TITLE
Site-creation: "Creating" screen confusing when slow

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7510]
We don't have any animation or clear message to "please wait" and the user can be confused as to whether they need to do something else/more, wait, or perhaps the app is hung.

[Example video](https://href.li/?https://www.usertesting.com/v/d1d6da7b-97bd-437d-819e-14c4bc7f3ea9?encrypted_video_handle=2_5hXg0VRlCwEtzN_lIlQg#!/notes) from a user test (skip to the [5:22] timestamp).

**Comment by planarvoid** [comment]
@folletto Hey, any ideas about what this "please wait" should look like? thanks

**Comment by folletto** [comment]
Thanks, it's a really interesting observation.

I think we could consider two approaches:

1. We can make the "..." in the currently active line to alternate (like remove one, then another, then another... ` ..` > `. .` > `.. ` and loop)
2. We can add the default spinner below the text, with the same margin there's between the existing image and the first line.
