### ISSUE TITLE
Advanced discussion settings show extra toolbar after returning to settings activity

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#7520]
Steps to reproduce:

1. Navigate to settings.
2. Scroll to Discussion category and press More.
3. Press Home button to minimize the app.
4. Get back to the app.
5. Notice extra toolbar.

[![https://gyazo.com/2633352f243cfbacc5268d52fdebe033](https://i.gyazo.com/2633352f243cfbacc5268d52fdebe033.gif)](https://gyazo.com/2633352f243cfbacc5268d52fdebe033)

Tested on Android Nexus 5X API 25 emulator.

**Comment by designsimply** [comment]
Closing because I re-tested using WPAndroid alpha-157 (12.0 alpha) on Pixel 3 Android 9, with a self-hosted and WordPress.com Free site, and I am no longer able to reproduce the problem.
