### ISSUE TITLE
Add Filtering and Searching to Blog Posts List

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7532]
Add filtering and searching to the ***Blog Posts*** list including Published, Draft, Scheduled, and Trashed.  See the mockups below for illustration.

![filter](https://user-images.githubusercontent.com/3827611/37776966-14457ad6-2dac-11e8-9f66-6b7e4b43cb11.png)

Along with a complementary issue for ***Site Pages***, this will fix https://github.com/wordpress-mobile/WordPress-Android/issues/62, https://github.com/wordpress-mobile/WordPress-Android/issues/4693, and https://github.com/wordpress-mobile/WordPress-Android/issues/5884.

**Comment by nellofn** [comment]
This will be a really nice addition. 

A user asked how to go about finding trashed content on Android for its self hosted site (1316298-zen).

**Comment by rezzap** [comment]
Another user asked for this in 1595629-zen.

**Comment by SiobhyB** [comment]
This comes up frequently in the app reviews. An example from a recent three star rating:

> Quite nice. Unfortunately it is not possible to sort the posts, for example drafts/published or the oldest post first. This makes it hard to find drafts which are some months old, because there is no search option. I would be happy to rise the rating, if the app gives me the features above in future. Thanks for your work.

**Comment by charliescheer** [comment]
Another request from #1672607-zen

**Comment by thehenrybyrd** [comment]
Here's another in #1678733-zen

**Comment by SiobhyB** [comment]
Another request from a four star review:

> An app almost excellent for managing a blog and to follow others, only negative note: the drafts are mixed with the articles already published.

**Comment by thehenrybyrd** [comment]
Another where a user would like to restore a trashed post. Without the ability to view trashed posts, they can't be restored from the app. #1749484-zen

**Comment by oguzkocer** [comment]
Closing this in favor of #4693 and #62 since we'll work on each feature separately.

Note for HEs: These issues are now a part of a project that's starting as of today, so it shouldn't be too long before they are implemented.
