### ISSUE TITLE
Jetpack Settings > Security displayed for non-Jetpack sites

### ISSUE THREAD

**Issue by akirk** [wordpress-mobile/WordPress-Android#7539]
### Expected behavior
A non-Jetpack site should not have Jetpack settings exposed.

### Actual behavior
![screenshot_20180323-101034 copy](https://user-images.githubusercontent.com/203408/37821131-1005cbf6-2e83-11e8-9ddb-581a5ae9e908.png)

### Steps to reproduce the behavior
Open the Settings for a Non-Jetpack site. Seems the return of [Don't show Jetpack settings for non-Jetpack sites](https://github.com/wordpress-mobile/WordPress-Android/pull/6334/commits/275f07b8fd30e85a6b152d270f2f18e3f70a8503) from #6334.

**Comment by nbradbury** [comment]
Note: this seems to occur only for self-hosted sites.
