### ISSUE TITLE
Unable to click on commenter's name to view their blog

### ISSUE THREAD

**Issue by andrewfleming** [wordpress-mobile/WordPress-Android#7549]
### Expected behavior
click on a commenters name to view their blog

### Actual behavior
Commenter's name does not link to their blog

### Steps to reproduce the behavior
- Visit post with comments
- Click on commenter's name

##### Tested on [device], Android [version]
Will need to update with this info

1038810-zen

**Comment by thebud15** [comment]
Requested info here: 

Mobile: Motorola g4 plus. 
Android: Nougat 7.0

**Comment by rachelmcr** [comment]
Thanks for this report! I see there's also a duplicate report of this issue with some comments from developer investigation, so I'm going to close this issue. We'll continue tracking this over here: https://github.com/wordpress-mobile/WordPress-Android/issues/8109
