### ISSUE TITLE
Editor: Overflow menu item says "Publish Now" but saves as draft instead

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7562]
### Expected behavior

When I select "Publish Now" I expect the post to be published.

I also expect a new post to have the action "Save as Draft" rather than "Publish Now" if it hasn't been saved yet.

### Actual behavior

When I create a new post I see the item "Publish Now" in the overflow menu, and when I select that item it saves the post as a draft instead.

### Steps to reproduce the behavior

1. Start a new post in the app.
2. Enter some text in the post.
3. Open the overflow menu and note that there is no "Save as draft" option.
4. Select "Publish Now."

Note that the post is saved as a draft (not published), which matches the toast messages that appear on screen:

> Your post is uploading
> Draft saved online

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-105

**Comment by designsimply** [comment]
Tested and confirmed using Pixel, Android 8.1.0, WPAndroid alpha-105.

<img src="https://user-images.githubusercontent.com/1119271/38108790-2d371552-3353-11e8-9b06-3ccf161b516c.png" width="270">
