### ISSUE TITLE
Media: "Space Used" in Settings shows wrong number for total media storage space

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#7564]
### Expected behavior

I expect the "Space Used" section in my site's settings to show the percentage of media storage space I have used out of my site's total space available. For example, a free site has 3 GB of total storage space so I'd expect something like this:

> Space Used
> 43.6% of 3 GB

### Actual behavior

My site's settings seems to be showing the remaining available storage space instead of my site's total storage space. This is what I see:

> Space Used
> 43.6% of 1.7 GB

56.4% of 3 GB is 1.7 GB, so that seems to be my remaining storage space instead of my total.

### Steps to reproduce the behavior

1. Select a WordPress.com Simple site in the app.
2. Make sure you've uploaded some media to the site.
3. Check the Media section in the site's Settings.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-105

**Comment by designsimply** [comment]
Tested and confirmed using Pixel, Android 8.1.0, WPAndroid alpha-105 with madefortesting567.wordpress.com / personal plan where the total available space is listed as 11.1 GB where 13 GB is the expected number.

<img src="https://user-images.githubusercontent.com/1119271/38118838-bc9c670c-337a-11e8-9577-acc1ad636939.png" width="270">

**Comment by mzorz** [comment]
Closing via #7569
