### ISSUE TITLE
Stats Widget Text Misaligned

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#7565]
I noticed while adding the stats widget to the home screen that the labels are slightly off-center:

<img width="312" alt="screen shot 2018-03-28 at 1 10 50 pm" src="https://user-images.githubusercontent.com/789137/38054951-40603ddc-328d-11e8-93cb-8112b02a63ea.png">

This was on a Pixel 2 emulator on API 26.

**Comment by jeherve** [comment]
Came here to report the same thing, on a HTC U11, running Android 8.0.0

**Comment by jorgecasariego** [comment]
Actually, there's a problem with the icon beside the text. After getting the values the image stays blank or disappears   

![stats_widget_preview](https://user-images.githubusercontent.com/2581647/39224883-65e035f4-4817-11e8-93bd-a341116242ca.png)

**Comment by theck13** [comment]
This has been fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/8263 and https://github.com/wordpress-mobile/WordPress-Android/pull/8265.
