### ISSUE TITLE
Sing up for Wordpress.com button not not changing to the same language as the interface language

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#7570]
I was poking about the newest version of the Android app and I noticed if I sign all the way out of the app 
the "Sign up for WordPress.com" button does not translate to the same language as the interface, it stays in English.

I checked this on my iPhone in French, German and Dutch, and the effect was the same
<img src='http://cld.wthms.co/YYfWXC+'>

I checked with @elibud and she says that the translations are there, and they should be changing, but it isn't.

WordPress Android alpha 103
Android 5.1.1

To reproduce:  
1. Set your device to a language that is not English
2. Log completely out of the app.
3. The sign up button should still be in English

**Comment by elibud** [comment]
The translation for French and German was added on March 20th so it should be available on the next release :) The Dutch one is still missing some validation by the looks of it.
