### ISSUE TITLE
Site icon does not always appear in site picker and site settings for Jetpack sites

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#7576]
### Expected behavior
The site icon should always be displayed for Jetpack sites on site picker and site settings.

### Actual behavior

For some sites it doesn't work:

![screenshot_20180330-154543](https://user-images.githubusercontent.com/5558824/38140864-32f16628-340c-11e8-9a44-b6586d352034.png)![screenshot_20180323-233453](https://user-images.githubusercontent.com/5558824/38140865-351e72e2-340c-11e8-864f-52d71d193c56.png)<img width="47" alt="screenshot-2018-03-30-at-15-46-43" src="https://user-images.githubusercontent.com/5558824/38140890-567663f0-340c-11e8-9203-a357f4f4a04f.png">

##### Tested on WPAndroid Alpha 105 HTC U11

p2-p4a5px-2b0

**Comment by nbradbury** [comment]
Looks like this was fixed by #7722
