### ISSUE TITLE
Support Revisions in the app

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-Android#7577]
Users should have an option to pick the revision of a post they want to edit. 

Lack of support for Revisions has come up in some other issues (#5681, #3381) but I think we should have an issue to track Revisions support in general, as it's a big missing piece.

Related issue on iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/7810

**Comment by rachelmcr** [comment]
Closing as we now support revisions! Woohoo!
