### ISSUE TITLE
Featured images not displayed in Reader's single post view

### ISSUE THREAD

**Issue by jeherve** [wordpress-mobile/WordPress-Android#7587]
I subscribe to quite a few Jetpack sites in the Reader, and I can see the featured images / images Reader picked for that post when looking at the posts in the list view. However, when I tap in the post to view the full image, it is nowhere to be found:

List view, where a thumbnail of the image appears:
![screenshot_20180401-114728](https://user-images.githubusercontent.com/426388/38239717-ca5146d6-372d-11e8-949e-5b370ba52401.png)

In single view, the image is nowhere to be seen:
![screenshot_20180401-114722](https://user-images.githubusercontent.com/426388/38239742-dd57db14-372d-11e8-87ef-666e4f452aa7.png)

Would it be possible to display those images there?

<ul>
    <li>HTC U11</li>
    <li>WPAndroid Alpha 105</li>
</ul>

**Comment by planarvoid** [comment]
Right now we're not showing the featured image in the post detail. Does it make sense to add it? @osullivanchris

**Comment by osullivanchris** [comment]
@planarvoid  is this specific to Jetpack? I tested it with my WordPress.com test blog and the featured image is showing when I go into the post. 

So it would make sense to see it there for Jetpack too, I don't know why it wouldn't. Let me know if you can find out any more details about when it doesn't appear and why.

**Comment by designsimply** [comment]
> I tested it with my WordPress.com test blog and the featured image is showing when I go into the post.

I tested just now with my WordPress.com test blog and the featured image does not show for the individual post view for the Reader with a WordPress.com site. ([1m7s](https://cloudup.com/cSL2YxdSeu9)) @osullivanchris is it possible you confused seeing the image in the body of the post as the featured image when you looked at the individual post in the Reader? May I have the link to the post you tested so I can have a closer look?

**Comment by osullivanchris** [comment]
@designsimply maybe this has been covered by our conversation on #10568?

I've retested and what I'm seeing is if there is an image in the body, I do not see the featured image. When there is no image in the body, I see the featured image. 

The test site I am using can be found at https://oranspeppapig.blog/

I need to get some better test URLs lol
