### ISSUE TITLE
Wordpress app for android can not upload media (photos) 

### ISSUE THREAD

**Issue by saswe** [wordpress-mobile/WordPress-Android#7588]
### Expected behavior
Wordpress app for android can not upload media (photos)
Wordpress for iOS works great!

##### Tested on [device], Android [version]
samsung galaxy s7  and samsung galaxy s4

**Comment by rachelmcr** [comment]
Thanks for reporting this issue! Please share more details about what happens when you try to upload media, including the exact steps you take in the app. It would also help to know if any errors appear in the app's log — you can go to the Me tab (the person icon) > Help & Support > Application log to check that.

**Comment by pmciano** [comment]
Getting another report of this in 273759-h

User is having an issue uploading images and publishing posts with images from the WordPress app.

> the image begins to load and stops. I already made other publications through the application, everything worked normally.

The issue doesn't appear when using a normal browser, whether at WordPress.com or in the site's normal Dashboard.

Problem is being experienced with all images, which are small in size and there is plenty of space on the device. 

Logs have been provided.

Device is Moto G (5) running Android 7.0.

**Comment by pmciano** [comment]
@elibud They did not report that and when asked, stated there was plenty of space available.

**Comment by elibud** [comment]
Can we get the logs from the user please @pmciano? Maybe there's some clues there, please don't add them here though as they may contain confidential data.

**Comment by pmciano** [comment]
@elibud Logs were requested and provided on 4/10/2018. I've [uploaded them here](https://mc.a8c.com/pb/1dce3/#plain) in case you can't access Helpshift.

**Comment by mzorz** [comment]
The logs in 273826-h  (related to 273759-h)  show this
```
16 - [Apr-10 16:46 MEDIA] MediaUploadHandler > Error uploading media: Invalid response from the Jetpack site
17 - [Apr-10 16:46 API] Dispatching action: MediaAction-UPDATE_MEDIA
18 - [Apr-10 16:46 MEDIA] MediaUploadHandler > No more media items to upload. Skipping this request.
19 - [Apr-10 16:46 MAIN] UploadService > Media upload failed for post 41 : GENERIC_ERROR: Invalid response from the Jetpack site
20 - [Apr-10 16:46 POSTS] updateNotificationErrorForPost: Ocorreu um erro durante o upload de mídia neste post: Não foi possível realizar a operação.
```

So this line is of particular interest: `**GENERIC_ERROR: Invalid response from the Jetpack site**`

This happens after a while uploading (i.e. 70% of the file). This is not likely a WordPress Android issue, but rather something going on on the site side. I'm closing this one and continue on Helpshift @pmciano

**Comment by vyktorjonas** [comment]
Hello, in my case I fixed it by pausing Cloudflare
