### ISSUE TITLE
Publicize: Unable to connect to a Facebook page

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7591]
### Expected behavior

I expected to be able to connect my site to either a Facebook page on my account via the app, as I'm able to do from a browser (as per [our docs](https://en.support.wordpress.com/publicize/#facebook-profiles-pages)).

### Actual behavior

I was not given the option to connect to a Facebook page. I was, instead, automatically connected to my personal profile without being given the option to connect to a page instead.

### Steps to reproduce the behavior

1. Navigate to My Site > Sharing within the Android app.
2. Tap "Facebook" then "Connect" to connect your site to your Facebook account.
3. Notice that you're automatically connected to your personal profile, and not given the choice to connect to a page on your account.

##### Tested on Pixel, Android 8.1.0, WP alpha-105.

**Comment by SiobhyB** [comment]
This was reported in 271938-h.

**Comment by SiobhyB** [comment]
This came up again in 290043-h.

**Comment by kwonye** [comment]
Thanks, @SiobhyB! Added to the top of the list for groundskeeping on Android!

**Comment by mzorz** [comment]
closed via #8115
