### ISSUE TITLE
Can't Access Commenter Site via Gravatar in Comments Section

### ISSUE THREAD

**Issue by pmciano** [wordpress-mobile/WordPress-Android#7592]
On the iOS version of the WordPress app, when viewing comments, you can access a commenter's site by tapping on their Gravatar image.

![img_0016-576x1024](https://user-images.githubusercontent.com/6855537/38323335-f053c13c-380a-11e8-90c4-a78f2f7114fb.jpg)

On the Android version of the app, you cannot. This would be a useful feature to have across the WordPress apps.

Tested on SM-G955F, Android 7.0, WordPress app 9.6

272195-h

**Comment by jorgecasariego** [comment]
This issue might be related to #7549
