### ISSUE TITLE
WebView scroll position not persist after decive rotation

### ISSUE THREAD

**Issue by calbee633810** [wordpress-mobile/WordPress-Android#7619]
### Expected behavior
In the help screen, click "Browser our FAQ" and open any one of the FAQs. Scroll screen to the bottom and rotate screen.  The scroll position of WebView should persist.

### Actual behavior
However, WebView scroll back to top after rotation.

<img width="281" alt="screen shot 2018-04-09 at 9 53 53 pm" src="https://user-images.githubusercontent.com/38213896/38501888-98f5be92-3c40-11e8-81c6-39b6d6016207.png">
Screenshot before orientation change

<img width="436" alt="screen shot 2018-04-09 at 9 54 05 pm" src="https://user-images.githubusercontent.com/38213896/38501918-aae56cf6-3c40-11e8-9512-29f0170c2716.png">
Screenshot after orientation change

Seems other places using WebView also suffer from similar bug. It very annoying especially when reading long articles loaded by WebView because users have to scroll a long way to restore reading position. Should be fixed by remembering scroll position when lifecycle events happen.

### Steps to reproduce the behavior
Go the Help -> Click Browse our FAQ -> Click Login/Signup -> Click Known plugin conflicts -> Scroll screen to bottom -> rotate screen

**Comment by rachelmcr** [comment]
I tested this on a moto e5 play, Android 8.1.0, WPAndroid alpha-163 and the scroll position is now retained when I rotate the device. If the issue persists for you, please let us know.
