### ISSUE TITLE
Stock photos rotation problems

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#7623]
As mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/pull/7582#issuecomment-379950988), there are some rotation-related problems in the new stock photos feature:

1. the empty view (that reads “Search to find free photos…” is not keep on rotation

2. if you start an upload and rotate the screen, the upload doesn’t end properly, furthermore the ProgressDialog leaks

**Comment by abidhahmed** [comment]
@nbradbury - This issue seems to persist in the latest 9.9 beta - I checked on `9.9-rc-1`.
