### ISSUE TITLE
Reader image viewer starts from the beginning on rotation

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7624]
### Expected behavior
Viewing an image in the embedded Reader post image viewer should keep the currently displayed image on rotation.

### Actual behavior
The image viewer displays the first image of the post, loosing its position in the image list.

### Steps to reproduce the behavior
1. In the Reader, open a post with more than one photos
2. Tap on the first photo. The embedded image viewer is launched and the photo is displayed full-screen
3. Swipe to move to the next image
4. Rotate the device
5. The image viewer returns to the first photo

##### Tested on [device], Android [version]
Nexus 5X, Android v7.1.2

**Comment by jorgecasariego** [comment]
@nbradbury I did this task but I didn't realize you were assigned to this. 😮 

Sorry 🤦‍♂️

**Comment by nbradbury** [comment]
@jorgecasariego Oh, feel free to tackle it - I assigned myself but got distracted by other code and haven't touched it yet.

**Comment by jorgecasariego** [comment]
Yes @nbradbury 😄  - I'll wait for someone to review the PR.

**Comment by planarvoid** [comment]
This issue has been already fixed
