### ISSUE TITLE
Geolocation disappears from app on save

### ISSUE THREAD

**Issue by jeherve** [wordpress-mobile/WordPress-Android#7626]
### Steps to reproduce

1. Create a new post in the mobile app.
2. Go to post settings and set the location for that post.
<img src="https://user-images.githubusercontent.com/426388/38561420-4799aef8-3cd8-11e8-92f9-3ef583d2ab67.png" width="270" alt="screenshot_20180407-220405">

3. Save the post as a draft.
4. When you get back to post settings, the geolocation data seems lost.
<img src="https://user-images.githubusercontent.com/426388/38561408-3e62c89c-3cd8-11e8-91ef-2ce48c298d86.png" width="270" alt="screenshot_20180407-220426">

5. Yet it is in fact saved, I can see it if I look at the draft in wp-admin
<img src="https://user-images.githubusercontent.com/426388/38561433-5334649c-3cd8-11e8-9eb5-55b2642ab9c1.png" width="270" alt="screenshot_20180407-220557">

**Comment by charliescheer** [comment]
Another report
#1471336-zen

**Comment by sarahfg** [comment]
We got a user inquiry about this issue in #2481797-zen. Are there any updates on this issue @jeherve or @rachelmcr ?

**Comment by rachelmcr** [comment]
I re-tested this issue on my moto e5 play, Android 8.1, WPAndroid alpha-195 and can no longer reproduce the issue. When I follow the steps above to add a geotag to my post, that geotag persists when I reopen the draft in the app. (I also see it saved for my post in the classic Calypso editor on the web.)

Can someone who is still seeing the issue share their steps to reproduce and the environment (device, app version, etc.) where it's happening?

**Comment by jeherve** [comment]
I can still reproduce on my end, on a Jetpack site, with WP Android Alpha 195, on a HTC U11 running Android 9. I followed the exact same steps.

**Comment by rachelmcr** [comment]
Thanks! I had tested on a self-hosted (no Jetpack) site and a WordPress.com site and couldn't reproduce there, but I can reproduce on a Jetpack site.

I added this to the Groundskeeping project for investigation during a maintenance rotation, but it may not be prioritized unless we receive more reports of the issue or focus a rotation on editor issues in particular.

**Comment by sarahfg** [comment]
Thank you both for checking this out!

**Comment by ashiagr** [comment]
I can reproduce it on a Jetpack site.

Noticed that in iOS, location on the view is set [using post's metadata](https://github.com/wordpress-mobile/WordPress-iOS/blob/675d1b645ee0c78a176887cb6a59fc6eceae3317/WordPress/Classes/Services/PostService.m#L839) while in Android it is set [using the geo param](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/75050e8e588c95ea5ba836194ece8aa0011b8472/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java#L426) which is returned null for such sites.

I'll set location from `metadata` if `geo` param is null in Android, to make it consistent with iOS.
