### ISSUE TITLE
Sort Your Sites and Followed Sites Alphabetically in Notification Settings

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7660]
### Expected
***Your Sites*** and ***Followed Sites*** are sorted alphabetically in ***Notification Settings***.

### Observed
***Your Sites*** and ***Followed Sites*** are not sorted alphabetically in ***Notification Settings***.  ***Your Sites*** are sorted with your default site first followed by a semi-alphabetical list.  ***Followed Sites*** are sorted by most recently followed first.

### Reproduced
1. Go to ***Me*** tab.
2. Tap ***Notification Settings*** item.
3. Notice order of ***Your Sites*** and ***Followed Sites***.

#### Note
This cannot be addressed until https://github.com/wordpress-mobile/WordPress-Android/pull/7614/ is merged since it adds the ***Followed Sites*** section to ***Notification Settings***.

#### Tested
Google Pixel 2 running Android 8.1.0 on alpha-107

**Comment by elibud** [comment]
Can you take care of this one @theck13 ?

**Comment by theck13** [comment]
I can do this after finishing my current priority.  This may be a candidate for the `good first issue` label too.

**Comment by jorgecasariego** [comment]
I could take this issue if you don't have problem @theck13 

for this task it is necessary to make a change in FluxC, right?

**Comment by theck13** [comment]
I don't have a problem with that at all, @jorgecasariego.  If you want to take over, just remove me and add yourself as the assignee.  Thanks!

I think this can be done on the WordPress layer or the FluxC layer.  You can use whichever you think is best.

**Comment by jorgecasariego** [comment]
@theck13 I didn't remove you as the assignee because I still don't have enough permissions to assign or remove issues 😬
