### ISSUE TITLE
Link button adding site address to new links

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#7672]
This was problem was brought to my attention in this issue https://automattic.helpshift.com/admin/issue/276206 When you are creating a link in the Aztec editor using the link button from the toolbar, if you do not put in a full link (starting with http or https) the link button will assume that the link is a page on your site, and add your site's url to the beginning of the link that is created.
So for example if your site address is https://myawesomesite.wordpress.com/ and you create a link to apple.com using the link button the link created will be https://myawesomesite.wordpress.com/apple.com/
If you enter the link at https://apple.com/ the link will be created correctly.

To reproduce:

Start editing a post in Aztec
Click on the link button and create a link with out entering http or https
insert the link and publish the page.
Now if you visit your new page or post and look at the link the address will not be correct.
I tested this with a WPCOM site, Jetpack site, and self hosted w/o Jetpack same results.

Samsung Galaxy Tab A
Android 5.1.1
WordPress Alpha 103

**Comment by rachelmcr** [comment]
Thanks for the report! I'm going to close this issue in favor of https://github.com/wordpress-mobile/AztecEditor-Android/issues/460 (same issue reported in the Aztec repo).
