### ISSUE TITLE
Publish with confidence shown when updating a draft

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-Android#7675]
I opened an existing draft and tapped the update button, and I got the "Publish with Confidence" dialog:

![wpandroid-publish-draft](https://user-images.githubusercontent.com/8739/39302060-addad874-4951-11e8-8c0c-04cd5e2131cf.png)

The button label (and other copy) says "publish" which was scary, since I only wanted to save a draft, not publish.

**Comment by 0nko** [comment]
@iamthomasbishop What do you think about this? Should the copy change to "save/update" when there is an `Update` button instead of `Publish`? Or should we only show the promo dialog when publishing?

**Comment by iamthomasbishop** [comment]
You shouldn't see this dialog at all while it's still a draft - only while publishing :)

Is there a bug here where tapping the `Update` button on a draft is publishing? If so, that's another separate issue.
