### ISSUE TITLE
Save posts for later - Add new column to ReaderPostTable

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7685]
Extend the ReaderPostTable so it can store information whether the post has been bookmarked.

There can be multiple rows (one per tag) with the same post, make sure the new column is up to date in all rows.

Extend the ReaderPost model and add mapping so it gets correctly (de)serialized from/to the database.

**Comment by khaykov** [comment]
Fixed in #7713
