### ISSUE TITLE
Save posts for later - ReaderPostTable  - Add support for migration scripts

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7689]
Currently, all the tables are dropped and recreated when the version of the db is incremented. Add support for migration scripts for ReaderPostTable, so it doesn't get dropped whenever the db version is incremented.

**Comment by mzorz** [comment]
Closing as found in the `Done` column

**Comment by khaykov** [comment]
Fixed in #7759
