### ISSUE TITLE
What's Next: Add Checklist Progress Activity

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7710]
Add a ***What's Next*** checklist to show the progress of tasks.  See the mockups below for illustration.

![checklist](https://user-images.githubusercontent.com/3827611/39582760-e154a068-4eab-11e8-81e4-37f6813ff155.png)

**Comment by oguzkocer** [comment]
@theck13 I randomly came across this issue (I was looking for project ideas) and it looks like it has been addressed in #7844. Should we close this issue?

**Comment by theck13** [comment]
Yep!  Closing.
