### ISSUE TITLE
What's Next: Add Checklist Completed Notification

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7711]
Add a notification when the ***What's Next*** checklist is completed.  See the mockups below for illustration.

![notification](https://user-images.githubusercontent.com/3827611/39583076-850e2396-4eac-11e8-91c3-64a36047e48c.png)

**Comment by manisha-A** [comment]
Hi, Is this still needed?

**Comment by theck13** [comment]
The notification was added in https://github.com/wordpress-mobile/WordPress-Android/pull/8202.
