### ISSUE TITLE
What's Next: Add Analytics Tracking

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7712]
Add analytics tracking to the following events of the ***What's Next*** feature.  See the screenshots and lists below for details.

![whats_next_analytics_01](https://user-images.githubusercontent.com/3827611/39721724-a3b120b0-51fd-11e8-9024-b9ed751bb4c0.png)

<ol>
<li><code>whats_next_dialog_seen</code></li>
<li><code>whats_next_dialog_negative_tapped</code></li>
<li><code>whats_next_dialog_positive_tapped</code></li>
<li><code>whats_next_list_accessed</code></li>
<li><code>whats_next_list_create_site_tapped</code></li>
<li><code>whats_next_list_view_site_tapped</code></li>
<li><code>whats_next_list_browse_themes_tapped</code></li>
<li><code>whats_next_list_customize_site_tapped</code></li>
<li><code>whats_next_list_add_social_tapped</code></li>
<li><code>whats_next_list_publish_post_tapped</code></li>
<li><code>whats_next_list_follow_site_tapped</code></li>
<li><code>whats_next_list_skip_all_tapped</code></li>
<li><code>site_whats_next_complete</code></li>
<li><code>whats_next_list_complete_seen</code></li>
<li><code>notifications_whats_next_received</code></li>
<li><code>notifications_whats_next_opened</code></li>
<li><code>whats_next_request_seen</code></li>
<li><code>whats_next_request_negative_tapped</code></li>
<li><code>whats_next_request_positive_tapped</code></li>
</ol>

<img src="https://user-images.githubusercontent.com/3827611/39721727-a6d4bd24-51fd-11e8-8bed-e5039ff6bd14.png" width="256">

23. <code>whats_next_dialog_final_seen</code>
24. <code>whats_next_dialog_final_negative_tapped</code>
25. <code>whats_next_dialog_final_positive_tapped</code>

**Comment by folletto** [comment]
Note: since there are entire groups of `whats_next_list_` like 5 to 11, wouldn't be better to do properties in these scenarios?

Like `whats_next_list_action` and then these have a property `type=create_site` and so on?

**Comment by manisha-A** [comment]
I need a clarification. Is this issue still relevant? Is this not called `Quick Start` instead of `What's Next`?

**Comment by theck13** [comment]
What's Next was renamed Quick Start.  The analytics were added in https://github.com/wordpress-mobile/WordPress-Android/pull/8228.
