### ISSUE TITLE
Save posts for later - add tracking events

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7716]
Add tracking events for savePostLater feature
- post saved for later (ReaderPostAdapter.toggleBookmark/toggleSaveForLater)
- saved for later post opened (probably ReaderPostDetailFragment -> ShowPostTask.onPostExecute)
- saved for later post removed (ReaderPostAdapter.toggleBookmark/toggleSaveForLater)
- saved posts reader menu item selected
- Snackbar "View all" button clicked

**Comment by mzorz** [comment]
Closing as found in the `Done` column
