### ISSUE TITLE
Save posts for later - Collapse(remove)/Expand(undo) animations

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7719]
Add collapse animation and undo action when an item from the bookmarks/savedForLater list is removed.

Add an expand animation when the user performs the undo action.

@iamthomasbishop Could you please attach a prototype? Thanks!

**Comment by iamthomasbishop** [comment]
Sure thing! Here's a demo:

![post collapsing - android](https://user-images.githubusercontent.com/1200432/39635619-a180db54-4f83-11e8-9124-fa668aeb9ca3.gif)

Some notes:

* When collapsing, everything within the card fades out, while the new title ("Removed [post_title]...") and `undo` button fade in. The cards below it also slide up with the height change.
* All animations are using an ease-in-out curve (`bezier(0.42; 0; 0.58; 1)`), with a duration of 250ms, but I'll see how it feels on-device during design review and adjust if necessary. Note: If there's another standard we're already using across the app, I'm also open to sticking w/ that.
* The undo/expand action reverses the collapse transition - same curve and timing.
* After looking again, it might make sense (if straight-forward to implement) to make the whole _collapsed_ post tappable to undo.

**Comment by khaykov** [comment]
Implemented in #7770
