### ISSUE TITLE
Drafts Keep Creation Date as Publish Date

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7729]
### Expected behavior

If I draft a post within the app then publish it in a web browser at a later date, I'd expect the publish date to reflect the date/time that I hit the "Publish" button.

### Actual behavior

When you create a draft in the app and save it and then come back later to publish the draft it keeps the original draft creation date and time as the published date and time.

Related GH issues:

* https://github.com/Automattic/wp-calypso/issues/9014
* https://github.com/wordpress-mobile/WordPress-Android/issues/2891

##### Tested on Pixel, WP alpha-109, Android 8.1.0

Reported in a four star Play Store review:

> This app has one very annoying feature. If you start writing a post draft with it, the publish time for the post will be when the draft is first saved, and not when the post is actually posted. Let's say I start a draft today using the WordPress app. Then, a week from now, I finish up the draft, but now I'm writing in Firefox on my self-hosted WordPress instance. The "Publish on" shown on the post will be the date when the draft was first saved using the app, and not "Immediately", like it would have been if I'd created the draft in Firefox instead of the app.  Long story short; the "Publish on" value should be "Immediately" unless something else is explicitly configured, regardless of if the draft was created in Firefox or using the app.

**Comment by koke** [comment]
A fix for this just [landed in core](https://core.trac.wordpress.org/changeset/45906). I have no idea if we need to do any changes on the Android side to support that properly

**Comment by davoraltman** [comment]
I have another case in 2494473-zen

The user drafted the post on October 21st and the Audit log shows it. When the post was published on November 15th (the Audit log shows this), the post's publish date is displayed as October 21st. So it ended up in the Reader area dedicated for posts published on October 21st. The user eventually changed the publish date in the post.

Site ID: 155451064
Post ID: 251

They only had an issue with this particular post and they used both the app and the web version of WordPress.com for publishing this post.

(asked for more details of the app and device and will update the GH issue here)

**Comment by SiobhyB** [comment]
This trips me up too, most recently when I started a draft for a post on the 14th March and published it on the 16th. The post kept the 14th as the publish date, as it was created from the app.

This likely affected engagement as, even though I updated the date retroactively, the Reader displays items based on their original publish date. The post, therefore, appeared pretty far done the feed for those who follow my blog via the Reader (the people most likely to engage with the post by "liking" or commenting on it). I also didn't want to re-publish as that would have meant those who follow via email would receive a duplicate email.

**Comment by designsimply** [comment]
I created several drafts today and plan to publish them after waiting a few days with these testing steps in mind. 

1. Create and save a few drafts.
1. Wait a few days.
1. Re-open the draft in the editor and publish.
1. Check the date and time of the published post to see if it was published on the date expected.
1. Publish one of the drafts from the Posts List screen.
1. Check the date and time of the published post to see if it was published on the date expected.
1. Repeat one of the previous scenarios if you have any additional saved drafts.

Aside: I think the project currently underway to show the site, date/time, visibility, and tags right before publishing is going to help with this _tremendously_! 😍

**Comment by hypest** [comment]
Still happening in my testing. Also, there's the [same issue on WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/issues/10188).

That said, we nowadays have a pre-publishing dialog that indeed shows that the datetime is older than the current datetime, though it doesn't highlight it in any particular way. What I'm trying to say is that the user can notice that and change on the spot actually.

I tried the flow on the web (WPCOM site, via Gutenberg) and although the post is marked as "updated", the datetime on it is that of the publishing moment, not the draft creation moment. So, I guess the question becomes whether the app should change to default to the current time automatically or not. I feel that mirroring the web behavior is proper, or at least to change the design mobile to make it more clear while publishing that the datetime is older.

All in all, I will replace the "Bug" label with the "Enhancement" one.

**Comment by SiobhyB** [comment]
I'm going to go ahead to close this issue as there's a newer issue at https://github.com/wordpress-mobile/WordPress-Android/issues/15244 outlining the same problem. That newer issue has received some recent developer attention and is marked as high priority for groundskeeping.
