### ISSUE TITLE
Toolbar Duplicated on Settings Sub-Preference Screen

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#7774]
### Expected
Settings sub-preference screen shows one toolbar when navigating away and back to the app.

### Observed
Settings sub-preference screen shows multiple toolbars when navigating away and back to the app.  See the screenshot below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/40197838-d4e52bc8-59d1-11e8-8182-83cea33649e6.png" width="240">

### Reproduced
1. Go to ***Sites*** page.
2. Tap ***Settings*** under ***Configuration*** section.
3. Tap ***More*** under ***Discussion*** section.
4. Tap home or overview navigation button to leave app.
5. Launch app again.
6. Repeat steps 4 and 5.
7. Notice one additional toolbar for each repetition.

##### Tested
Google Pixel 2 running Android 8.1.0 on alpha-109

**Comment by nbradbury** [comment]
Note: same thing happens with security settings.
