### ISSUE TITLE
Update Reader Manage

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#7797]
Reder->Manage: We should update the endpoint and the UI to search for sites by title and not only by URL addresses as it works on the web.

<img width="388" alt="reader-search-feed-example" src="https://user-images.githubusercontent.com/5558824/40385746-00130cba-5dde-11e8-8068-d88fdcf09d2d.png">

**Comment by planarvoid** [comment]
I was looking into this and I'm not sure how to approach this. Our current web search in reader seems to have two sets of results, one is the same as in our app and the second one searches by title. We're also missing the `follow` button in the app search so I'm not sure the search purpose is the same. What am I missing @elibud

**Comment by nbradbury** [comment]
Sniffing the web reader, it looks like we can add search via this endpoint:

`https://public-api.wordpress.com/rest/v1.1/read/feed?&q=[searchTerm]&offset=0&exclude_followed=true&sort=relevance`

**Comment by elibud** [comment]
@planarvoid please ping @frosty and @nbradbury for all reader matters, they are much more likely to have the answers than I am. Thanks

**Comment by nbradbury** [comment]
Related FluxC PR is [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/822)
