### ISSUE TITLE
Save post for later - retain 'unsaved' posts in the Saved Post List on config change

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7800]
### Expected behavior
When the user 'unsaves' a post in the Saved Posts List and rotates the device, the 'unsaved' post will retain in the list.

### Actual behavior
When the user 'unsaves' a post in the Saved Posts List and rotates the device, only saved posts are shown.

### Steps to reproduce the behavior
1. Go to Saved Posts list in Reader
2. Click on the Save for later icon (unsave the post)
3. Notice the card of the post is collapsed
4. Rotate the device
5. Observe the collapsed card is not shown

**Comment by khaykov** [comment]
Fixed in #7802
