### ISSUE TITLE
Crash - Remove failed uploads dialog

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7803]
### Expected behavior
When a user wants to publish a post which contains an image which wasn't successfully uploaded to the server a confirmation dialog is shown.

### Actual behavior
When a user wants to publish a post which contains an image which wasn't successfully uploaded to the server, the app crashes.

### Steps to reproduce the behavior
1. Create a new post
2. Type any title
3. Turn on Airplane mode
4. Try to upload an image
5. Turn off Airplane mode
6. Click on the publish button
7. Notice a dialog is shown - "Some media uploads have failed. You can\'t save or publish
        your post in this state. Would you like to remove all failed media?"

**Comment by daniloercoli** [comment]
Addressed in #7804.
