### ISSUE TITLE
Save posts for later - invalid undo item

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7813]
### Expected behavior
When a post is unsaved in other list than "Saved posts list", an undo item should not be created. 

### Actual behavior
When a post is unsaved in for example "Followed sites" list and the user navigates to "Saved posts list", an undo item is displayed.

### Steps to reproduce the behavior
1. Go to Reader - Followed sites list
2. Save and unsave a post
3. Go to saved posts list
4. Observe an undo item is displayed

**Comment by kwonye** [comment]
@malinajirka is this resolved in #7814?

**Comment by malinajirka** [comment]
Unfortunately, it's not. I must have overlooked this issue. It's on my list now.
