### ISSUE TITLE
Just opening a post in Aztec could result in local changes

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#7819]
There is an issue with Aztec that can slightly change the content of the current post even if the user has not made any changes to it.

To test this:
- Open a post in the editor
- Don't edit anything
- Switch to HTML
- Tap BACK
- You will see the post marked with local changes

This happens because there is an internal conversion from HTML to Span(s) that doesn't preserve (and probably can't) the exact HTML code passed in input. The conversion back to HTML is done internally by Aztec, when we request the content again on exit, and the produced HTML can be slightly different (attributes order, inline tag not closed) from what we passed in input.

We've already tried different approaches to fix this issue (see #7767), but those were not working as expected. This should be fix Aztec side, and integrate the changes here.

**Comment by hypest** [comment]
Additional PR to fix more manifestations of the issue: https://github.com/wordpress-mobile/AztecEditor-Android/pull/719
