### ISSUE TITLE
Reader - clear cache on Pull-to-Refresh

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7834]
### Expected behavior
When the user PTR the cache should be cleared. Otherwise some posts might be missing - for example posts from a blog which was recently added to the followed blogs.

### Actual behavior
When the user PTR the cache is not cleared - only 20 most recent posts are fetched.

For more info see #7733

**Comment by nbradbury** [comment]
@aerych Would love your thoughts on this and whether it would make sense to implement on iOS as well.

**Comment by aerych** [comment]
Anytime a user pulls to refresh in the iOS reader we blow away anything that was previously synced. :)

**Comment by planarvoid** [comment]
@aerych I've checked the android app and calypso and it seems that the endpoint doesn't clear its cache on PTR. For example when you delete a post, it will be still returned from the endpoint on PTR. Do you send any specific flag to force the reader refresh on iOS?
