### ISSUE TITLE
Migrate to new Google API keys in newer app versions

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7842]
Let's try to follow the best practices for API keys outlined in https://developers.google.com/maps/api-key-best-practices.

Perhaps we'd like to devise a plan if we end up changing anything with our current keys. For example, we could leave the current keys as is and produce new ones, used in newer app versions. We can then retire the old ones in the future, after some stabilization period passes.

**Comment by designsimply** [comment]
This issue still appears valid. @hypest can you confirm? Is there any detail you can add that may help make it more actionable or are there any updates you know of that could be relevant to note at this point?

**Comment by hypest** [comment]
I'm not sure if there's been any relevant work from Platform9, there might have been. @jtreanor , does this ticket ring any bells to any effort done in Platform9 so far?

**Comment by designsimply** [comment]
Still valid.

**Comment by jkmassel** [comment]
Closing this down as we long ago adjusted how we do code signing.
