### ISSUE TITLE
Incorrect spacing in notification body

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-Android#7849]
A notification for a comment with an unordered list should have equal spacing between all its items. 
The following notification displays correctly in Calypso, but adds extra spacing in the Android app:

![androidextraspacing](https://user-images.githubusercontent.com/5558824/40920419-d693fe3a-67e2-11e8-80ce-2173e7240e1b.png)

Reported by @m, ping @elibud for notification contents.

**Comment by kwonye** [comment]
The same fix for iOS should apply here: https://github.com/wordpress-mobile/WordPress-iOS/pull/9542
