### ISSUE TITLE
Sign up: Ensure tracks events are not anonymous after signing up

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#7856]
After creating a new account the Tracks anonymous ID should no longer be used, and the account_created event itself should be sent as a logged in user.
See [here](https://github.com/Automattic/Automattic-Tracks-Android/blob/develop/AutomatticTracks/src/main/java/com/automattic/android/tracks/TracksClient.java#L461) and [here](https://github.com/wordpress-mobile/WordPress-Analytics-Android/blob/develop/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java#L309) for the relevant tracks code. We need to make sure mNosaraClient.trackAliasUser is being properly called from the sign up flow.

**Comment by loremattei** [comment]
Closed via #7880.
