### ISSUE TITLE
The app bar is empty for blog with no Title set

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#7874]
The top bar is completely empty if the site has no title.

![device-2018-06-08-152402](https://user-images.githubusercontent.com/518232/41160672-b7d43f04-6b30-11e8-9daa-566ef552a720.png)

Instead the blog card does use the URL of the site in place of the title:
![device-2018-06-08-152746](https://user-images.githubusercontent.com/518232/41160686-c03bd710-6b30-11e8-9250-6e346b3bea26.png)

I think we should show "WordPress" if the blog title is empty.

**Comment by sank20** [comment]
Hi, I'd like to take up this issue. Adding the string "WordPress" if the blog title is empty. May I suggest adding a placeholder text such as <no title> (can be used every time when empty strings are allowed, in different places); or maybe if the title is empty, the content of the blog can be set in ellipisized form.

**Comment by oguzkocer** [comment]
This issue was addressed in #7946, however I had to revert the merge as I missed [an issue](https://github.com/wordpress-mobile/WordPress-Android/pull/7946#issuecomment-401190890) with it.

**Comment by hypest** [comment]
FWIW, tried `develop` against a site with an empty title and the app still has it's app bar empty.
