### ISSUE TITLE
Bottom Navigation: Talkback announcements for each option

### ISSUE THREAD

**Issue by AmandaRiu** [wordpress-mobile/WordPress-Android#7894]
### Expected behavior
Talkback announces a label that best describes what each option available in the bottom navigation bar.

### Actual behavior
Clicking each option gives the following:
- ✅   **My site**: "My site - view your site and manage it including stats"
- ❌  **Reader**: "My site - view your site and manage it including stats reader - follow content from other sites"
- ✅  **New Post**: "New Post - write a new post"
- ❌  **Me**: "My site - view your site and manage it including stats"
- ❌  **Notifications**: "My site - view your site and manage it including stats"

### Steps to reproduce the behavior
1. Enable TalkBack in the Accessibility menu in device settings.
2. In WordPress: single-click on each option and note the audio announcement.

##### Tested on [device], Android [version]
- LG G5 API 24

**Comment by loremattei** [comment]
Closed via #7914
