### ISSUE TITLE
Posts and pages with multiple bold elements freezes the app

### ISSUE THREAD

**Issue by nellofn** [wordpress-mobile/WordPress-Android#7909]
A user reports in 287195-h that when opening a specific blog post in the app, the app goes black and freezes. I checked the post content in the html view and I see that the post has lots of bold html elements which I suspect could be causing the app to freeze.

### Steps to reproduce the behavior

I was able to replicate this issue by creating a [test post](https://sitiodepruebaesp.wordpress.com/2018/06/14/test-post/) and a [test page](https://sitiodepruebaesp.wordpress.com/test-page-with-bold-elements-only/) in a test site, including only random text and the same amount of bold html elements I suspect are causing this issue.

If I try to edit either the test post or page in the app, the screen goes black and freezes after a couple of seconds. 

##### Tested on:
**My test:** 
App version 10.1, Android 5.1, Model Blue Studio Selfie.

**User config:**
App version 10.1, Android 8.0.0, Model: SM-G955N.

**Comment by daniloercoli** [comment]
Thanks for reporting this @nellofn 

> I was able to replicate this issue by creating a test post and a test page in a test site, including only random text and the same amount of break html elements I suspect are causing this issue.

Would you mind to provide raw HTML code of the post that is breaking the app?

**Comment by nellofn** [comment]
Sure @daniloercoli

Here's a raw copy: https://cld.wthms.co/V0vQrB

**Comment by koke** [comment]
From the conversation, it seems that all those tags are not intentional. I don't think we should add code to cleanup a one time thing when we can just ask the user to clean up the post content (or do it for them).

**Comment by SiobhyB** [comment]
Just noting here that the user came back and I've removed all those extra tags from their post. I'm not sure _how_ those tags ended up there in the first place. The user mentioned that they'd had an issue with an image in that post not loading, but is not sure if that is somehow related. They've also never seen this issue before. I've asked them to let us know if it happens again.

**Comment by mzorz** [comment]
Marked this one as `Candidate for groundskeeping rotation`  - there's already a [PR I put together](https://github.com/wordpress-mobile/AztecEditor-Android/pull/721) but it's breaking other tests on Aztec. Ideally, the groundskeeper can take it up from there 👍

**Comment by mzorz** [comment]
**Update**: the PR is up now and ready for review https://github.com/wordpress-mobile/AztecEditor-Android/pull/721
