### ISSUE TITLE
Associate a custom domain to a site with a business plan

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#7923]
Many of business sites don't have a custom domain associated even though it's free with their plan. We want to prompt and allow users that have already bought a business plan to associate a custom domain to their site.

The attached designs show the entire automated transfer flow. We want to implement the five screens illustrating domain registration, plus the dialog that is the entry point to the flow.  After completing the domain flow the user should be returned to the plugin installation flow.

![at_android_i32](https://user-images.githubusercontent.com/1435271/41607838-97e1e9ba-73ac-11e8-9321-5224b80e2567.jpg)

**Comment by jkmassel** [comment]
Domain registration is now part of the app, so this should be resolved.
