### ISSUE TITLE
 [Aztec + GB] self-closing blocks are not rendered correctly

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7930]
### Expected
Self-closing blocks should show the question mark to show a defined representation for an unknown (to Aztec) entity

### Observed
On WPAndroid the name of the tag is shown, plus a trailing `/`.

This is how it goes on WPAndroid:
<img width="335" alt="screen shot 2018-06-13 at 17 26 59" src="https://user-images.githubusercontent.com/6597771/41376793-ac34926c-6f30-11e8-8137-939cb254e9ba.png">
<img width="346" alt="screen shot 2018-06-13 at 17 26 50" src="https://user-images.githubusercontent.com/6597771/41376794-ac5d1de0-6f30-11e8-9265-99afea762ab5.png">

However, it looks alright on the AztecDemo app:
<img width="272" alt="screen shot 2018-06-13 at 17 37 17" src="https://user-images.githubusercontent.com/6597771/41376822-bcec39fc-6f30-11e8-9251-dc574cc55db1.png">
<img width="277" alt="screen shot 2018-06-13 at 17 37 12" src="https://user-images.githubusercontent.com/6597771/41376823-bd185320-6f30-11e8-9cf5-ec51495ea133.png">

### Reproduced
1. Insert this code as the sole Post content: 
```
<!-- wp:latest-posts /-->
```
2. Open the Visual Mode and verify the observations

#### Tested
[Nexus 5] on [Android 6.0] with [latest commit e2d2c9ba9c74584dddff4924b6fb14dbe639aba4]

This ticket was transcribed from https://github.com/wordpress-mobile/AztecEditor-Android/issues/716

**Comment by daniloercoli** [comment]
Looks good! :shipit:
