### ISSUE TITLE
Track what accessibility features are enabled (including talkbalk)

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#7936]
According to [this](https://groups.google.com/forum/#!topic/eyes-free/9pajGQLp4X0) we can track what accessibility features a user can have.

@khaykov do you know if we've explored this option yet? I recall a conversation where we said it was not possible.

**Comment by khaykov** [comment]
Yes, technically I think we can, but there are some concerns about privacy that we need to clear first.

**Comment by kwonye** [comment]
Ok, with GDPR and privacy concerns, it's not worth making sure we are doing everything legally to get the numbers of this. We would have/will continue working on accessibility regardless of what the numbers say. Closing.
