### ISSUE TITLE
Zendesk functionality is not available after changing support email couple of times

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#7942]
Zendesk functionality is not available after changing support email couple of times

Steps to reproduce:
1. Go to "Help & Support" page, change your email (I added a dot).
2. Go back to Me fragment, and back to "Help & Support" page.
3. Change your email to the one used previously.
4. Go back to Me fragment, and back to "Help & Support" page.
5. Notice that "Contact us", "Browse our FAQ" and "My Tickets" are not clickable.

Sometimes it takes me two tries to repro this.

Tested on Pixel on Android 8.1.0 with zendesk master branch.

**Comment by oguzkocer** [comment]
Fixed in #7951.
