### ISSUE TITLE
Title is not scrolling automatically when long text is written

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7948]
### Expected behavior
When typing in a long-ish post, editor's title line should get scrolled out of view as the text grows.

### Actual behavior
While typing in long text, the content text itself gets scrolled as the text grows but title line is not scrolled out of view.

### Steps to reproduce the behavior
1. Start a new post on the Beta editor
2. Type in a few lines of text in the content area
3. Keep adding lines until the content text starts scrolling
4. Notice the title input being still in view and not moving as new lines of content text gets added

##### Tested on [device], Android [version]
Nexus 5X, Android v7.1.2, app version v10.2

**Comment by mzorz** [comment]
I confirm this:
- _does NOT_ happen on a Pixel with Android 8.0
- _does NOT_ happen on Samsung S3 (Android 4.2.2 API 17)
- _does_ happen on Nexus 6 with Android 5.1
- _does_ happen on a Nexus 5 with Android 6.0 (API 23)

**Comment by resid9406** [comment]
I've reproduce the issue on Samsung A7 (Android )
1) I can see the same issue as you, but when hide the keyboard and start scrolling the title input disappear as you wanted.
2) If you keep writing and never hide the keyboard the title view still on screen

![issue2](https://user-images.githubusercontent.com/17255390/42140796-551bf4ec-7d69-11e8-96a1-40dc1b9d8937.jpeg)

**Comment by designsimply** [comment]
Moved to https://github.com/wordpress-mobile/AztecEditor-Android/issues/890.
