### ISSUE TITLE
Android: Improve the discoverability of stock images

### ISSUE THREAD

**Issue by nozomimimi** [wordpress-mobile/WordPress-Android#7950]
### Expected behavior
Make the stock photos easier to find.

### Actual behavior
It's hard to find now unless you know it exists and specifically look for it.

Currently, you need to go to "+ (add media)" inside the editor, -> tap on the "images" icon -> then select "Choose from Free Photo Library".

cc: @kwonye

**Comment by kwonye** [comment]
https://cloudup.com/cz1LZPOD3hX

I personally love how messaging apps do their multiple sources.

**Comment by nozomimimi** [comment]
i2 of the design above :)

![android_free_photo_discoverability_improvement_i2](https://user-images.githubusercontent.com/36741426/42476006-2884664a-83d5-11e8-829d-657850a25214.jpg)

**Comment by megsfulton** [comment]
Closing this issue out, the block editor and recent media library updates have addressed this.
