### ISSUE TITLE
Android: Add “Duplicate” or "Copy post" functionality

### ISSUE THREAD

**Issue by nozomimimi** [wordpress-mobile/WordPress-Android#7954]
### Expected behavior
Currently on the mobile app, "Duplicate post" functionality is not available. (It exists on Calypso, see the image below)
We should bring this functionality to the mobile app.

[![https://gyazo.com/0eb5ef47b7f9c8c333ce096ae30f8895](https://i.gyazo.com/0eb5ef47b7f9c8c333ce096ae30f8895.png)](https://gyazo.com/0eb5ef47b7f9c8c333ce096ae30f8895)

**Comment by osullivanchris** [comment]
Behaviour per Calypso:

- When a user chooses the 'copy' option on a post, they are launched straight into the editor
- All of the content from the existing post is copied over to the new post. However the duplicate post acts as a 'new' post in that it is a draft without any status selected yet, regardless of whether it was duplicated from a published or draft post
- The post has the exact same title name. So "Superman or Batman" creates another post also called "Superman or Batman", not appended by v2, copy, etc
- The Android design can be implemented with existing UI, just adding to the menu
- The iOS design is dependent on https://github.com/wordpress-mobile/WordPress-iOS/issues/11646 where we have the more flexible sheet menu

![Blueprint Android](https://user-images.githubusercontent.com/50576199/61964868-dc8b1a80-afc6-11e9-939e-0a0862a76601.png)
![Blueprint iOS](https://user-images.githubusercontent.com/50576199/61964869-dc8b1a80-afc6-11e9-9ef1-833f2b90b590.png)

**Comment by osullivanchris** [comment]
iOS designs ready too. Should we create a separate iOS task or change the name / location of this task?

**Comment by megsfulton** [comment]
🚢🚢🚢

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13521
