### ISSUE TITLE
Post Format Gallery is not handled correctly

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7988]
### Expected behavior
When a post with `Gallery` post type is published using calypso, images in the gallery should be displayed in the app (Aztec and 'My Site->Blog Posts').

### Actual behavior
When a post with `Gallery` post type is published using calypso, only `[gallery ...]` shortcode is displayed in the app (Aztec and My Site->Blog Posts).
![gallery-bug](https://user-images.githubusercontent.com/2261188/42217787-d641f4fa-7ec6-11e8-8b6f-bcb878444687.png)

### Steps to reproduce the behavior
1. Create a post with postType `Gallery` (using Calypso) -> note: not all themes support `Gallery` post type, so you might need to change theme (`Cubic` worked for me)
2. Go to the app
3. Open My Site -> Blog Posts
4. Notice there is `[gallery]` shortcut instead of the images
5. Click on the post
6. Notice there is a `[gallery ...]` shortcut again

 Note:
I'm not sure this is a bug or something we don't support yet.  Wdyt @0nko ?

**Comment by 0nko** [comment]
This is not a bug. Galleries are not supported in Aztec.
