### ISSUE TITLE
Respect analytics opt-out setting with 3rd parties

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-Android#8035]
Make sure when the user opts out of tracking (#7743) it not only disables Tracks but also make sure we're not tracking anything in Fabric or Helpshift.

**Comment by koke** [comment]
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/9764

**Comment by nbradbury** [comment]
Android version of the above link: https://docs.fabric.io/android/crashlytics/advanced-setup.html#enable-opt-in-reporting
