### ISSUE TITLE
Test app for accessibility

### ISSUE THREAD

**Issue by Wingo5315** [wordpress-mobile/WordPress-Android#8041]
Would it be possible if you could test the app for accessibility?

**Comment by rachelmcr** [comment]
Thanks for the suggestion! The team does investigate and make improvements for accessibility, and you can see upcoming tasks and open issues here:

https://github.com/wordpress-mobile/WordPress-Android/issues?q=is%3Aopen+is%3Aissue+label%3AAccessibility

If you find any specific accessibility issues in the app, please report them as individual issues here. Thanks!
