### ISSUE TITLE
Media: allow uploading audio files

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#8052]
This is a subset of #4842, which asks for uploading of any file type. This issue is specifically about adding the ability to upload audio files.

**Comment by rfaile313** [comment]
User Request for this in 2252944-zen

**Comment by pmciano** [comment]
Requested in 2373893-zen

**Comment by pmciano** [comment]
Requested in 2374050-zen

**Comment by rezzap** [comment]
From a forum post:

> I am suggesting in the media option that you can add audio, because at the moment you can only videos and photos or take photos and record videos and I also wanted to suggest the option of recording audios. (translation)

**Comment by msilbers** [comment]
requested in #2780117-zen

"The interface does not allow me to select audio files to upload to the media library."

**Comment by thehenrybyrd** [comment]
Another request in #2861711-zen for mp3s.

**Comment by designsimply** [comment]
Here's another request for audio uploads from an app review:

> One thing that WP needs is a good uploader, compared to YouTube, Google, etc, it is very hard to upload things on the website using a slow internet connection. Any little drop out and the whole upload fail. An app like this could help but I just discovered that audio can't be uploaded from the app.
> 
> <sup>2-star app review by Tom Richards - 6/11, 4:38 AM - WP Android 13.8 Samsung Galaxy Note8 Android 9</sup>

**Comment by rezzap** [comment]
Another request in #3060163-zen

>A month ago we could also upload audio to blog posts . Today when I opened the app did not show the option anymore . I planned to start an audio series on my blog but due to the above problem I cannot now .

I'm not sure why they thought this was an option previously, but I directed them to the browser.

**Comment by rezzap** [comment]
Another request for this in 3079891-zen

> How do I upload a .mp3, for an audio blog?

**Comment by designsimply** [comment]
Another request from an app review:

> Suggestion: make it possible to upload audio files to the media library.

(gp:AOqpTOEWCE7yi-RPfgItBUAZxEMBMrJhBgLN8UBpsOU_rIZvNUHul-L-Dn4m68_NLXk7QR_TSAf7Vgnfm4Nkgw-app-reviewid)
