### ISSUE TITLE
Localize TOS URL where possible

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#8068]
The Terms of Service URL we use (Me > App Settings > WordPress for Android > Terms of Service) is [hardcoded to en.wordpress](https://github.com/wordpress-mobile/WordPress-Android/blob/55adddd51fd284bc01563cf669cea10a48775836/WordPress/src/main/java/org/wordpress/android/Constants.java#L4). Translated versions of that page exist for several languages - we should use those where possible.

**Comment by elibud** [comment]
Do you know if all that's required is to send the locale param @aforcier?

**Comment by aforcier** [comment]
@elibud from my checks it doesn't look like it, we'd have to store a list of all the valid locale subdomains on WordPress.com and use the `[locale].wordpress.com/tos` URL if we know the subdomain exists (otherwise use `en.wordpress.com`).

I'll check with i18n and see if there actually is a clever way to do this with a param.

**Comment by elibud** [comment]
Pinging @akirk as he may know the path forward, also once we have a solution lets fix it in iOS too.

**Comment by elibud** [comment]
@loremattei created an issue for iOS here: https://github.com/wordpress-mobile/WordPress-iOS/issues/9824

**Comment by akirk** [comment]
We can do a link like https://wordpress.com/tos/?lang=

What are common language slugs in Android? On WordPress.com we currently have these defined:
- French `fr`
- Spanish `es`
- German `de`
- Italian `it`
- Hebrew `he`
- Russian `ru`
- Japanese `ja`
- Brazilian Portuguese `pt-br`
- Dutch `nl`
- Korean `ko`
- Turkish `tr`
- Indonesian `id`
- Chinese (China) `zh-cn`
- Chinese (Taiwan) `zh-tw`
- Arabic `ar`
- Swedish `sv`

If different ones are used in the app we'll need to do some rewriting, so it would be great if you could  list out/compare them with the ones used in Android.

**Comment by akirk** [comment]
Ok great. In the spirit of supporting the same slugs as the API, we'll also use the parameter `?locale=` which will accept the same slugs.

So https://wordpress.com/tos/?locale=ja_JP will redirect to https://ja.wordpress.com/tos/ and https://wordpress.com/tos/?locale=pt_BR will redirect to https://br.wordpress.com/tos/

**Comment by elibud** [comment]
Are those URLs working already @akirk?

**Comment by nbradbury** [comment]
Hey @akirk, I'm "groundskeeper" this week and was wondering about tackling this on the Android side. What's the status of that API change?

**Comment by akirk** [comment]
Hi, sorry this has fallen off my plate. I had implemented this in D16387-code but received quite some pushback on doing the locale mapping server-side. Could we do the [mapping for the locale codes we have on WordPress.com](url
https://github.com/wordpress-mobile/WordPress-Android/issues/8068#issuecomment-407344267) in the Android app?

**Comment by aforcier** [comment]
@akirk just to make sure I follow your meaning - you're proposing we still add server-side support for requests of type https://wordpress.com/tos/?lang=, but that it only accepts the language codes of the kind you outlined in your comment you linked to - is that correct?

If that's the case, we can certainly do that - but could you share some detail on what the arguments were? That is, what's the reasoning against aligning the TOS URL requests with the locale format the WordPress.com API expects?

**Comment by akirk** [comment]
Yes, please map them to the locale codes I mentioned above. I am not aware of the WordPress.com API supporting other locale codes, are you sure?

**Comment by aforcier** [comment]
> Yes, please map them to the locale codes I mentioned above. I am not aware of the WordPress.com API supporting other locale codes, are you sure?

Followed up over chat, with the notifications endpoint as an example that handles `locale=xx_YY` requests.

**Comment by akirk** [comment]
Sorry for the super long delay but this has now landed, so redirects like https://wordpress.com/tos/?locale=zh_CN work.

**Comment by elibud** [comment]
Thank you @akirk 
@aforcier can you check that is working on Android and have someone double check in iOS please?

**Comment by aforcier** [comment]
Nice @akirk! Tested the redirects a bit, seems to be working well.

I'll work on patching the app to append the parameter to the ToS URL requests.
