### ISSUE TITLE
Sharing from a phone app to WordPress Android results in empty post

### ISSUE THREAD

**Issue by msilbers** [wordpress-mobile/WordPress-Android#8103]
### Expected behavior
The expected behavior when sharing from another app that has the sharing to WordPress option, that the full content of what is being shared would be posted. This was reported by a user in #1274193-zen and I am able to replicate it.

### Actual behavior
Only the title is posted.

### Steps to reproduce the behavior
1. Open Samsung Notes (or similar app, user reported this for Samsung Memos)
2. Write a new note with any amount of content and a title
3. Click Share and share the text to WordPress.com's app on Android
4. It will show the content of the post in a draft and show the Publish button
5. Click Publish and only the title will show

Here is a screenshot of the note once it is in the WordPress.com app: https://cloudup.com/cBc3m42pXsR
Here is the resulting post: https://rollerbladingatnight.wordpress.com/2018/07/24/title-of-test-again/

##### Tested on:
Samsung Galaxy S8 - SM-G950U
Android 8.0.0
Samsung Experience (??) version 9.0
Samsung Notes app version 2.2.00.33

**Comment by sophiegyo** [comment]
I'd like to note that I encountered a similar problem raised by someone who was trying to share Youtube URLs via the WordPress app on mobile:
https://github.com/wordpress-mobile/WordPress-Android/issues/8062

They may not be related but as it's very similar behaviour I think it's worth linking.

**Comment by kriskorn** [comment]
A user has shared a workaround with us:

If an image is added before the text in Memo, then the Memo can be shared with WordPress and the image AND the text are preserved. 
The image can be then deleted and the text modified before publishing in WordPress. 

#1274193-zen

**Comment by rachelmcr** [comment]
I tested this on my Nexus 9, Android 7.1.1, WPAndroid alpha-125. I wrote the note in Google Keep and shared it from there to the WordPress app, and the post published with the full content as expected. Is this still an issue or is it resolved in the latest version?

**Comment by rachelmcr** [comment]
I'm closing this issue as I can no longer reproduce it on my end. If anyone is still experiencing this issue, please comment with more details and we can reopen. :)
