### ISSUE TITLE
Make WordPress.currentBlog private and use WordPress.getCurrentBlog() instead

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#812]
WordPress.getCurrentBlog() tries to recover a blog object if there wasn't one previously set, so it's safer to use than WordPress.currentBlog throughout the app.

**Comment by aforcier** [comment]
The upcoming FluxC integration removes `WordPress.currentBlog` and `WordPress.getCurrentBlog()` entirely, and we instead pass the current `SiteModel` through the app.

**Comment by aforcier** [comment]
RIP `currentBlog` and `getCurrentBlog()`.
