### ISSUE TITLE
"Save as Draft" uploads 2 draft posts on the remote site  

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#8132]
### Expected behavior
One draft post sent as Draft to the remote site.

### Actual behavior
2 draft posts sent as draft to the remote site.

### Steps to reproduce the behavior
- Go to Posts list screen
- Tap on New post
- Insert the Title and test content
- Tap on "Save as Draft" & immediately go back on post lists
- Wait until the post is uploaded
- Tap to refresh the list
- You should have 2 draft posts with the same content/title

**Comment by hypest** [comment]
Can't reproduce on WPAndroid v17.0-rc-2, Pixel 2XL, Android v11. I only see one draft created. Tested both on WPCOM and a selfhosted site. Will close this ticket now but, please feel free to reopen if it still occurs, thanks!
