### ISSUE TITLE
App sometime crashes when loading a video thumbnail

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8183]
### Expected behavior
The app won't crash after the user presses back button while loading a video thumbnail.

### Actual behavior
The app sometimes crashes after the user presses back button while loading a video thumbnail.

### Steps to reproduce the behavior
1. Go to Media library
2. Click on the Plus sign in the top right corner
3. Take video
4. Press back button as soon as you are redirected back to media library and the video is still uploading
5. Observe the app sometimes crashes

##### Tested on [device], Android [version]
Emulator - Android api 27

Stacktrace from Fabric
```

com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed (RequestManagerRetriever.java:312)
--
  | com.bumptech.glide.manager.RequestManagerRetriever.get (RequestManagerRetriever.java:131)
  | com.bumptech.glide.manager.RequestManagerRetriever.get (RequestManagerRetriever.java:115)
  | com.bumptech.glide.Glide.with (Glide.java:697)
  | org.wordpress.android.modules.GlideApp.with (GlideApp.java:88)
  | org.wordpress.android.util.image.ImageManager.load (ImageManager.kt:52)
  | org.wordpress.android.ui.media.MediaGridAdapter$1$1.run (MediaGridAdapter.java:472)
```

**Comment by loremattei** [comment]
Closing as it's been fixed by 8184 :-)
