### ISSUE TITLE
News Card - Tracks

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8193]
Track
- The card was shown `newscard_shown`
- User clicked on the "Read more" button `newscard_dismissed`
- User manually dismissed the card `newscard_extendedinfo_requested`

Also track following properties
- origin - location where the card was displayed within the app (first version will always track 'reader')
- version - which announcement (version of the card) was shown

**Comment by loremattei** [comment]
Moving to the next version because this one has been released.
