### ISSUE TITLE
Hide the "Get started" message after creating a site

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#8233]
### Expected behavior
After creating a site, the user sees the site preview without a "Create your website at WordPress.com" message.

### Actual behavior
After a user creates a site, they see a site preview with a message "Create your website at WordPress.com" and a button "Get started" on top of the screen. After clicking the button, the screen shows a toast “Links are disabled on the preview screen”. 

![screenshot_20180824-092616](https://user-images.githubusercontent.com/1079756/44647664-fd29a980-a9de-11e8-9bf7-f85bac6f3041.png)

### Steps to reproduce the behavior
* Create an account
* Go through the site creation flow
* Finish the process
* The Site preview opens.
* The message is visible on top of the screen above the site preview

**Comment by elibud** [comment]
iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/10040

**Comment by elibud** [comment]
@khaykov please take a look at this one during your groundskeeping rotation, the iOS PR has a solution that should work here too.

**Comment by hypest** [comment]
just to close the loop, I commented on the iOS PR https://github.com/wordpress-mobile/WordPress-iOS/pull/10040#issuecomment-423080819
