### ISSUE TITLE
Posting: change EditText hint when it has the focus

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#826]
In the post editor, when you tap the editor to start typing your post the hint still includes "tap to add text and media."

![device-2014-02-06-110045](https://f.cloud.github.com/assets/3903757/2100638/a332a610-8f4a-11e3-9e67-d2485b91dc4d.png)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
