### ISSUE TITLE
Post content is lost when copy/pasting from other apps and making no edits

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8275]
### Expected behavior

When copying text from another app and pasting it into a new draft in the WordPress app, the content should be saved/published.

### Actual behavior

If you copy and paste text into a new draft in the WordPress app, and save the draft or publish without making further edits to the post content, the content is lost (the post is saved/published with just a title and no content).

This is especially a problem for anyone who composes a draft post in another app and then copy/pastes it into the WordPress editor. Although the can copy/paste the content again (it isn't completely lost) it can result in an embarrassing empty post being published.

This is very similar to https://github.com/wordpress-mobile/WordPress-Android/issues/8201.

### Steps to reproduce the behavior

1. Go to any app where you can select and copy text, such as Chrome or a note-taking app.
2. Select a piece of text and wait for the contextual menu to appear
3. In the contextual menu, tap on `COPY`.
4. In the WordPress app, start a new post.
5. Tap on the Title area and enter a title.
6. Long tap in the Content area and paste the content you copied.
7. Hit Publish on the upper right corner of the screen.
8. When asked to confirm, confirm.
9 Now go to the posts list, and select the post you just created.
10. Observe there is no content in the content area.

You can also see the same issue by saving the post as a draft, or by switching from Visual to HTML mode in the editor.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-126

**Comment by rachelmcr** [comment]
We have received at least three recent user reports (internal ref: p4a5px-2ff-p2).

**Comment by daniloercoli** [comment]
This issue has been fixed in #8279, and the next public release 10.8 will contain the fix.

**Comment by SiobhyB** [comment]
I've followed up with all users from the original post. :)
