### ISSUE TITLE
Jetpack Connect: Google login/signup fails when self-hosted account email is not connected to WordPress.com account

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8289]
### Expected behavior

Jetpack Connect works with all WordPress.com account login & signup options.

### Actual behavior

Jetpack Connect sometimes fails with Google login/signup. As far as I can tell, it fails when your self-hosted account (that you used to log in to the self-hosted site in the app) uses an email address that is not connected to a WordPress.com account.

### Steps to reproduce the behavior

0. Create a self-hosted site with an admin account that uses an email address not linked to a WordPress.com account.
1. Log in to only the self-hosted site in the app.
2. Go to _My Site_ tab.
3. Go to _Stats_ section.
4. Select _Install Jetpack_ button.
5. Select _Don’t have an account? Sign up_ at the bottom of the screen.
6. Select _Sign Up With Google_ button.
7. Choose Google account with email not linked to a WordPress.com account.
8. Tap _Continue_ button on Epilogue screen.

Result: I was returned to the My Site screen showing this error:

> Check that the site URL entered is valid

At this point I was logged in to my new WordPress.com account in the app, but when I tapped on the Stats item again I still saw the Install Jetpack button from earlier. I had to go through the Jetpack connect process again to finish connecting my new account.

(Same results if you use Google to log in to an existing WordPress.com account instead of Google signup at step 6.)

### Logs

App logs include a similar error to the on-screen error:

```
89 - [Sep-10 10:05 STATS] 🔵 Tracked: connect_jetpack_selected, Properties: {"source":"stats"}
90 - [Sep-10 10:05 UTILS] Empty or null or invalid URL passed to WPWebViewActivity
```

**Comment by elibud** [comment]
@planarvoid can you please take a look?
