### ISSUE TITLE
Featured images on pages are broken.

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#83]
Edit a page
Add an image. 
Tap the image and check the option to use it as a featured image. Do not check the option to include the image in the content. 
Publish the page. 
An image tag for the featured image is included in the post body even though you did not check the option to do this.
The image tag is missing a src attribute, and has android-uri="content:// ... " instead.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
