### ISSUE TITLE
Blog Posts List Shows Error Message When Publishing

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8300]
### Expected
Error is not shown when successfully publishing post.

### Observed
Error is shown when successfully publishing post.

### Reproduced
0. Clear app data.
1. Log in.
2. Go to ***My Site*** tab.
3. Tap ***Blog Posts*** item under ***Publish*** section.
4. Tap ***Create*** button.
5. Enter title and/or content.
6. Tap ***Publish*** action button.
7. Tap ***Publish Now*** button
8. Notice error shown below.
> An error occurred when loading the post. Refresh your posts and try again.

##### Tested
Google Pixel 2 on Android 9.0 with WordPress alpha-127

**Comment by SiobhyB** [comment]
We received another report that seems similar to this issue in 1419032-z.

The user is on 10.9-rc-2 and seeing the "An error occurred when loading the post. Refresh your posts and try again." error when attempting to publish posts to their Jetpack site within the app.

Their logs can be found in the ticket.

**Comment by 0nko** [comment]
A fix for this was only released yesterday in 10.9-rc-3, so it's just an old manifestation of the issue. I'll close this again but feel free to reopen if something comes up.
