### ISSUE TITLE
Media: Add Storage Space indicator to Media section

### ISSUE THREAD

**Issue by nellofn** [wordpress-mobile/WordPress-Android#8323]
Currently, to check a site’s media storage space in Android devices, we need to go to “My Sites > Settings > Media (Space Used)".

![screen shot 2018-09-17 at 9 48 02 am](https://user-images.githubusercontent.com/17755234/45644332-8175c680-ba8b-11e8-8b46-b3c6888def6c.png)

It'd be nice to have the storage space detail somewhere in the Media section itself, in line with WP Admin, Calypso and iOS.

**Comment by iamthomasbishop** [comment]
A proposal, as discussed internally:

Add an info bar with a text button to the Media page on `Site` > `Media`. This would use the same label of `X% of X GB` as seen above, but append `used` to the end. It would look like this:

<img width="400" alt="screenshot 2018-09-17 14 45 14" src="https://user-images.githubusercontent.com/1200432/45646231-52aa2100-ba88-11e8-91c3-feec2a525748.png">

@theck13 pointed out that this label could turn to red when storage is getting full, and I think this would be a useful addition.

**Comment by thehenrybyrd** [comment]
I ran into this issue as I was figuring out where to tell folks to look for media space on Android. Glad we're already looking at adding this!

For reference, here's what it looks like on iOS:

<img src="https://user-images.githubusercontent.com/15107387/47617798-d584b980-dad3-11e8-8481-cd7a0954ded4.jpeg" width="250px">

Clicking the "+" in media brings up these options and displays the space used at the top.
