### ISSUE TITLE
Customizer is opened for a different site

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8348]
### Expected behavior
Tapping the _Customize_ button on the _Themes_ screen should open the Customizer for the current user site.

### Actual behavior
Tapping the _Customize_ button on the _Themes_ screen kicks the user to the device’s browser app. If the user is logged in to a different account in the browser than in the WordPress app, then a different site is shown.
If the user is not logged in in the browser, then a new login request is shown.

**Comment by rachelmcr** [comment]
There's a related ticket for autologin when launching the customizer: https://github.com/wordpress-mobile/WordPress-Android/issues/5077

I'm not sure if autologin would only help when you're logged out of the browser, or if it could also be used to log you in to a different account than the one you're currently logged in to in the browser.

**Comment by rachelmcr** [comment]
This came up again in testing feedback (internal ref: pxLjZ-52s-p2).

> Attempting to customize the theme opens up in chrome kind of jarring if you have a different account / have to log in again. (assuming this and below is some form of a not yet implemented situation)

**Comment by rachelmcr** [comment]
I'm going to close this issue in favor of #5077 since that seems like the next step for improving this experience.
