### ISSUE TITLE
Site Picker multi-selection not preserved on configuration change

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#8350]
### Expected behavior
When you select multiple sites in Site Picker, the selection should be retained on configuration change.

### Actual behavior
Selection is not retained on configuration change.

### Steps to reproduce the behavior

1. Use account with multiple sites and first alphabetical site hidden.
2. Go to My Site tab.
3. Tap Switch Site button in top card view.
4. Notice active site is selected.
5. Long-press next site in list (below divider if present).
6. Notice no sites are selected.
7. Notice top toolbar title shows 0 selected.
8. Tap any site.
9. Notice top toolbar title shows 1 selected.
10. Rotate the device.
11. Notice selection mode is disengaged and selected sites are not retained.

##### Tested on [device], Android [version]
Nexus 5X emulator, api 28

**Comment by BElluu** [comment]
Hello. Can I take care of this task?

**Comment by khaykov** [comment]
@BElluu Yes, absolutely :)

**Comment by hafizrahman** [comment]
I'm looking at this.
