### ISSUE TITLE
Unable to read the vertical menu options on the native app

### ISSUE THREAD

**Issue by susanannadsouza** [wordpress-mobile/WordPress-Android#8353]
Device : Android [One Plus 5 with 8.1.0 Version]
Javaclient 6.1.0.jar
Appium Desktop 1.6.2
Problem statement : The native App has a vertical menu which has been recently updated with new names as per the client requirement . There are 9 menu options in the list .
When the app loads only 5 of them are visible. To read the other 4 , need to scroll the app downwards.
I have writtenthe below code for the same. But the 1st menu is not read by the code written by me , Need help in correcting the same

WebDriverWait driverExplicitWait = new WebDriverWait(d, 1000);

String try1=driverExplicitWait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//android.widget.TextView[@content-desc=\"My Prescriptions.\"]"))).getText();
		
System.out.println(try1);
		
List<WebElement> list1=d.findElementsByXPath("//android.widget.TextView[@index='1']");
System.out.println(list1.size());
swipeToBottom();

WebDriverWait wait = new WebDriverWait(d, 1000);
String try2=wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//android.widget.TextView[@content-desc=\"Account.\"]"))).getText();
System.out.println(try2);
List<WebElement> list=d.findElementsByXPath("//android.widget.TextView[@index='1']");
System.out.println(list.size());
		
                if(list1.equals(list))
		{	
		Iterator<WebElement> Str_loop1 = list1.iterator();
		while (Str_loop1.hasNext())
		{
			WebElement value1=Str_loop1.next();
			String menuOption1=value1.getText();
			System.out.println(menuOption1);
		}
		}
		else
		{
			Iterator<WebElement> Str_loop = list.iterator();
			while (Str_loop.hasNext())
			{
				WebElement value=Str_loop.next();
				String menuOption=value.getText();
				System.out.println(menuOption);
			}
		
		}
		}
		

Output:
My Prescriptions
7
Account
9
Home
Refill now
Reminders
Family Care
Find a Store
Transfer Rx
Doctors
Delivery Order History
Account

![after scroll](https://user-images.githubusercontent.com/42570648/45873159-61a61180-bdaf-11e8-94ea-d960d499e34b.jpg)
![upon appload before scrol](https://user-images.githubusercontent.com/42570648/45873172-68348900-bdaf-11e8-8e0a-c8a25ecda8b4.jpg)

**Comment by rachelmcr** [comment]
Hi @ susanannadsouza, I'm sorry for the confusion. When I mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/10185 that it was in the wrong repo, I wasn't thinking to open a new issue here. It doesn't look like the issue you are describing is related to the WordPress app itself — if I understand correctly, you are dealing with a completely different app and that isn't something we can help with as it isn't related to the WordPress app.

**Comment by susanannadsouza** [comment]
Ohh, my apologies.
