### ISSUE TITLE
Bottom bar left and right margins are too small

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#8357]
Label of last item in the main bottom bar - `Notifications` - seems that it's too close to the edge of the screen. 
![screen shot 2018-09-24 at 09 50 20](https://user-images.githubusercontent.com/518232/45941774-fa22d880-bfdf-11e8-8349-ba07e1e1e095.png)

![screen shot 2018-09-24 at 09 56 17](https://user-images.githubusercontent.com/518232/45941832-3f470a80-bfe0-11e8-8e67-2e96518ffe8a.png)

On devices with curved screen, like the S9/s9+, the last letter  happens to be drawn on the right edge of the screen, and the final result is the following below:
![wp-15377761550251876135885799734897](https://user-images.githubusercontent.com/518232/45942301-28a1b300-bfe2-11e8-99c2-d4f55410c0ff.jpg)

i've checked with some other apps and it seems they use a wider margin.

(The same margin is applied to the first item in the bar, but its label is short and fits better).

cc @iamthomasbishop

**Comment by iamthomasbishop** [comment]
I believe that's the nature of having that long of a label. The alternative was to shrink the font size on that label, and I'm not sure that's any better. 

cc @nbradbury

**Comment by nbradbury** [comment]
Reducing the font size is one alternative. Right now it's 12sp, which is the minimum size Google recommends. If we go smaller we'll get a warning, but we can override this with `tools:ignore="SmallSp"`.

<img width="385" alt="screen shot 2018-09-25 at 7 54 49 am" src="https://user-images.githubusercontent.com/3903757/46013248-b391b480-c099-11e8-97e6-ce240c064d13.png">


I _think_ it would be okay to go smaller. Here's how it would look:

![all](https://user-images.githubusercontent.com/3903757/46013285-d7ed9100-c099-11e8-9f69-fa1c0ed64ac7.png)

Another option is to drop the labels entirely, which I kind of like. If we go that route, though, I think we'd need to add "Reader" to the toolbar in the reader fragment.

**Comment by daniloercoli** [comment]
> Another option is to drop the labels entirely, which I kind of like.

+1 on dropping the label.
If we decide to remove it I suggest to add few `dp` to icon size and make them slightly bigger.

Uploaded a screenshot from FB and our app:
![device-2018-09-25-153140](https://user-images.githubusercontent.com/518232/46018262-c5934780-c0d9-11e8-8089-996dfaeba9ff.png)
![device-2018-09-25-153511](https://user-images.githubusercontent.com/518232/46018264-c75d0b00-c0d9-11e8-9ed2-551fbad9cd8b.png)

**Comment by iamthomasbishop** [comment]
I definitely wouldn't remove the labels, as they help with discoverability and are very much in line with the Material guidelines. I also wouldn't shrink the label below the minimum size (12sp) because then you're getting into readability issues. I know it's not ideal that text could get close to the edge on certain curved-edge displays, but I think it's better than the alternatives.

Another alternative (which I don't think we should do) could be to swap the `Me` and `Notifications` tabs so the long label isn't last in the list, but that would require changing it on iOS as well, and not sure I want to go down that road.

@theck13 that's a good catch, we should definitely fix that.

**Comment by theck13** [comment]
I create a new issue for the icon tint [here](https://github.com/wordpress-mobile/WordPress-Android/issues/8370).

**Comment by mattmiklic** [comment]
I'm going to close this one; as @iamthomasbishop mentioned above, while certain phones with curved screens may do weird things with what's displayed on screen, that feels like it's the nature of a phone that curves the edges of whatever's displayed on screen.

The design team will be doing a round of work on our navigation in a few weeks, so I don't think it makes sense to modify how these tabs are being displayed at this time.
