### ISSUE TITLE
Rare NPE crash in ActivityLogListFragment 

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#8363]
```
Caused by kotlin.TypeCastException: null cannot be cast to non-null type org.wordpress.android.fluxc.model.SiteModel at 
org.wordpress.android.ui.activitylog.list.ActivityLogListFragment.onViewCreated(ActivityLogListFragment.kt:57)
```

5ba662b6f8b88c2963e156c0-fabric

**Comment by JavonDavis** [comment]
Reopening because ☝️ seems to be the same crash in a different activity, thinking it might be a good idea to open a similar PR to #8632 to log additional data in `PostsListActivity` to help reproduce

**Comment by designsimply** [comment]
**90-day impact:** ~21 per day
**Users affected in the last 90 days:** 752
**Limited to:** Android 9 and above

<sup>https://sentry.io/share/issue/730912cdc8744fa6abc162fd9d289865/</sup>

**Comment by designsimply** [comment]
The WORDPRESS-ANDROID-GP issue in Sentry still seems to be happening in current releases. @planarvoid @malinajirka would you recommend re-opening this issue or creating a new GitHub issue for this?

**Events in the last 90d:** 9,400
**Users affected in the last 90d:** 1,400
<sub>WORDPRESS-ANDROID-GP: https://sentry.io/share/issue/730912cdc8744fa6abc162fd9d289865/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1024074753&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/89963565-2e6c0600-dc05-11ea-9dd3-575b11f7fa86.png)</a>

**Comment by malinajirka** [comment]
@designsimply It seems like the same issue so I think we can just re-open it. I've moved it to Groundskeeping backlog so it can be prioritised.

**Comment by designsimply** [comment]
**Events in the last 90d:** 10,800
**Users affected in the last 90d:** 1,000
<sub>WORDPRESS-ANDROID-GP: https://sentry.io/share/issue/730912cdc8744fa6abc162fd9d289865/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1024074753&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96056222-333a7980-0e43-11eb-8621-a233dc6db852.png)</a>

🤔 in the last 90d there were more instances but fewer users affected with sliiiightly fewwer events per day overall. Still relatively medium-high frequency on this one compared to other things we're tracking right now.
