### ISSUE TITLE
Bottom Navigation Does Not Tint Icon on API 21

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8370]
### Expected
Both icons and text in the bottom navigation are tinted [`blue_medium`](https://github.com/wordpress-mobile/WordPress-Android/blob/3d8bf0c33b2ded6da0de9769b6743b4c863c65ff/WordPress/src/main/res/values/colors.xml#L40) `#00aadc` on API 21.

### Observed
Not icons, but text in the bottom navigation is tinted [`blue_medium`](https://github.com/wordpress-mobile/WordPress-Android/blob/3d8bf0c33b2ded6da0de9769b6743b4c863c65ff/WordPress/src/main/res/values/colors.xml#L40) `#00aadc` on API 21.  See the screenshot below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/46022957-9832a380-c0b1-11e8-8f04-4f18e7f24bdf.png" width="320">

#### Note
This was observed on API 21, but it should be verified with all API levels we support.

### Reproduced
0. Use device running API 21.
1. Go to ***My Site*** tab.
2. Notice icon is not tinted.
3. Go to ***Reader*** tab.
4. Notice icon is not tinted.
5. Go to ***Me*** tab.
6. Notice icon is not tinted.
7. Go to ***Notifications*** tab.
8. Notice icon is not tinted.

##### Tested
Google Pixel 2 on Android 5.0.2 with WordPress 10.9

**Comment by nbradbury** [comment]
@theck13 If we're moving to min API 21, the fix for this is simple. We just need to change [this routine](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt#L233) to this:

```
private fun setImageViewSelected(position: Int, isSelected: Boolean) {
    getImageViewForPosition(position)?.isSelected = isSelected
}
```

And then in the `navbar_item` layout, change the icon tint to a color selector, like this:

```
<selector
    xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:color="@color/blue_medium" android:state_selected="true"/>
    <item android:color="@color/grey_lighten_10"/>

</selector>
```
