### ISSUE TITLE
When a self hosted site has no pages or post the app shows an error instead of no sites.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#8377]
Hey y'all, I noticed a problem with an error that is appearing in the Android app.  If you have a site that is self hosted w/o jetpack,  and you delete all of the pages or posts from the app, you receive an error message that says "Pages couldn't be refreshed at this time"

The behavior of pages vs posts is slightly different.  With pages the error appears when you try to swipe down to reload the page
<img src='http://cld.wthms.co/N3zPms+'>

And if you go to My Site > Blog Posts on a self hosted site that has no posts the whole page appears with that error, and doesn't give you a chance to create a new post.
<img src='http://cld.wthms.co/ZE2mwm+'>

Steps to replicate:
1.  Create or connect to a self hosted WordPress site w/o jetpck
2. Go to My Site > Pages or My Site > Blog Posts and delete all of the pages or posts that appear
3. For pages swipe down to see the error, for blog posts, leave the page and return for the message to appear.

Note:  Tested this on a wpcom site and this did not happen.

wpAndroid 10.9.1
Android 5.1.1
Galaxy Tab A

**Comment by rachelmcr** [comment]
Thanks for the report! I reproduced this on a test site (note that to trigger the error on Site Pages you can't have any pages at all, including other filters).

I don't see any meaningful errors in the app log for the Blog Posts, but after refreshing the Site Pages I see this error in the log:

`[Sep-28 10:25 PAGES e] An error occurred while fetching the Pages`

**Comment by rachelmcr** [comment]
cc @theck13 Could this be related to changes made with the Actionable Empty States project?

**Comment by theck13** [comment]
The pages/posts screens were not modified in the Actionable Empty States protect.  From the [Part 2 pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/8072):
> The following screens are not fully implementing the design described in #7996 since they will be included in future projects (i.e. stats refresh and pages/posts filtering).
> 
>  - Stats
>  - Site Pages
>  - Blog Posts

**Comment by rachelmcr** [comment]
Thanks for that clarification! I missed that note.

The posts screen is yet to be worked on, but @planarvoid is this something that looks familiar from the work you did on Properly Placed Pages, with the empty state on the pages list screen?

**Comment by planarvoid** [comment]
I'll look into this. I assume this is related to the Properly Placed Pages project.
