### ISSUE TITLE
Creating a site from the app doesn't set the site language

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8379]
### Expected behavior

When my device is set to a non-English language, and I create a new account and site, I expect the account and site language to match my device language.

### Actual behavior

The account language is set correctly to match my device language, but the new site is always set to English.

### Steps to reproduce the behavior

1. Set your device to a non-English language.
2. Open the app (log out if needed, to start on the login/signup screen).
3. Sign up for a new account.
4. Create a new site.
5. Check the account and site languages.

Original report (internal ref): p77Llu-b6J-p2 (h/t @daniloercoli)
##### Tested on Nexus 9, Android 7.1.1, WPAndroid 10.9.1

**Comment by daniloercoli** [comment]
Turned out to be a server side problem. Investigating and trying to get a patch on the server.
