### ISSUE TITLE
RuntimeException - AztecImageLoader - AztecMediaSpan.draw

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#8387]
It seems that the new `AztecImageLoader` based on Glide has introduced a spike of RuntimeExceptions in `AztecMediaSpan.draw` - Internal ref: 5a2735cd61b02d480df3abcc.

I had opened an issue [here](https://github.com/wordpress-mobile/AztecEditor-Android/issues/748) in the Aztec repo, but probably it was not the correct place where to report it, since noticed that disabling `clearTargets` method in [AztecImageLoader](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/services/AztecImageLoader.kt#L83) fixes the problem.

Steps to repro:
- Start the app and go to posts list
- Tap on Edit for a post that contains lot of pictures
- Once the editor is on the screen and the placeholders visible
- Rotate the device landscape
- (Wait a bit)
- Rotate the device portrait
- Tap home screen
- Wait a couple of secs 
- Re-open the app
- Crash

@malinajirka Would you mind to take a look at this, since you've migrated the loaders to Glide?

**Comment by malinajirka** [comment]
I must have missed the spike - sorry. Great job for figuring out the repro steps!!!  Thanks

I think we just need to make sure the 'clearTargets' method is called only when the activity is finishing. I'll test it and create a PR tomorrow/on Friday.

**Comment by daniloercoli** [comment]
Fixed in #8397
