### ISSUE TITLE
Activity Log strings do not update with app language change until restart

### ISSUE THREAD

**Issue by davipontesblog** [wordpress-mobile/WordPress-Android#8405]
### Expected behavior

When the site language is set to pt-br, and the user interface language is set to pt-br, the mobile experience should be in pt-br.

### Actual behavior

On the app, when displaying the site options it shows it all in pt-br, so “Activity Log” shows “Atividade”. But when you tap on “Atividade”, it shows “Activity Log” on the top, and the actions logged are all in English as you can see on the screenshot [here](https://cloudup.com/cLxqIiq6T7Q), as well as the messages when trying to rewind.

### Steps to reproduce the behavior

- Create a WordPress com site with a Business plan, and install a plugin. In this example I installed WooCommerce.
- Set site language to pt-br
- Set user interface language to pt-br
- Go to "Atividade" 
- See untranslated strings

**Comment by 0nko** [comment]
I played around with the system language settings and everything got translated properly. When I tried to change the language in the app settings, though, I could reproduce the issue.

**Comment by davipontesblog** [comment]
I tested this a bit more and it seems to be related to the Android system language. I changed the system language on my phone to Portuguese, killed the app, and re-opened it, and it showed everything in Portuguese. Changed it back to English, then killed/re-opened, and it showed in English. So somehow it’s feeding off of the system language.

**Comment by rachelmcr** [comment]
I'd make an adjustment to the expected behavior:

> When the site language is set to pt-br, and the user interface language is set to pt-br, the mobile experience should be in pt-br.

I expect the app to conform primarily to the device language setting or app interface language setting (when that setting differs from the device language). The main issue here seems to be that the Activity Log language doesn't update without restarting the app — similar issue previously resolved here: https://github.com/wordpress-mobile/WordPress-Android/issues/7265

**Comment by designsimply** [comment]
Thank you for the report @davipontesblog!

> I tested this a bit more and it seems to be related to the Android system language. I changed the system language on my phone to Portuguese, killed the app, and re-opened it, and it showed everything in Portuguese. Changed it back to English, then killed/re-opened, and it showed in English. So somehow it’s feeding off of the system language.

I tested and confirmed the same behavior using WPAndroid 13.8-rc-1 on my Pixel 3 Android 10.

Closing this as a duplicate in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/7559.
