### ISSUE TITLE
Better Error Messaging for Invalid URLs

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#8460]
### Expected behavior

If I enter an invalid URL at the login form, I expect to receive an informative, helpful error message that informs me why I'm not able to log into the app.

### Actual behavior

The following error appears if I enter an invalid URL at the login form, which isn't that helpful to users:

"Couldn't connect to WordPress site. There is no valid WordPress site at this address. Check the site address (URL) you entered."

Screenshot:

![screenshot_20181021-215621](https://user-images.githubusercontent.com/2998162/47272355-4845e000-d57c-11e8-867e-65edf250c911.png)

### Steps to reproduce the behavior

1. Navigate to the app's login screen and select the "Log in by entering site address" option.
2. Enter some nonsense text, for example "DFOJDOFJF".

##### Tested on Pixel, alpha-132 of WordPress for Android

This was raised by @jtreanor and some other recent support rotations as a lot of support requests are made up of users who enter an invalid URL. More informative error messaging could have a positive impact on the number of incoming requests.

iOS version of this issue is here: https://github.com/wordpress-mobile/WordPress-iOS/issues/10294

**Comment by thehenrybyrd** [comment]
Ran into this in #1648733-zen, where the user had entered the URL "Santara Net Review".
It would be great to produce an error that states this isn't a URL, and gives an example of a URL.

**Comment by thehenrybyrd** [comment]
Another in #1666486-zen  - the user entered "La vie d'una Maison"

**Comment by thehenrybyrd** [comment]
#1667453-zen - the user entered "Datos".
Looks like some folks don't understand they need a "domain.tld" format for this to work. They're entering the name/title of their site, instead.

**Comment by thehenrybyrd** [comment]
#1693402-zen, entered "mcgospelentertainment".

**Comment by thehenrybyrd** [comment]
Here's another who entered "Estanislao Mallofre Jane". #1749121-zen

**Comment by thehenrybyrd** [comment]
Another example here in #1834758-zen

![notaurl](https://user-images.githubusercontent.com/15107387/53492469-a2622f00-3aa1-11e9-817e-8fb50741342a.png)

**Comment by thehenrybyrd** [comment]
Another case in 1899497-zen. They've entered an apparently random sequence of numbers and letters.

**Comment by thehenrybyrd** [comment]
Another in 1923800-zen. Again, a random-looking sequence of numbers and letters.

**Comment by designsimply** [comment]
Raising in priority due to the number of user reports referenced.

**Comment by thehenrybyrd** [comment]
Thanks Sheri!
I ran into another of these today in 1949634-zen.
Folks seem to think they can just type in relevant search terms.
I blame Google 😆

**Comment by oguzkocer** [comment]
I have asked for design request for this and already received some tips. I also requested a copy for it. Once I get the copy as well, I'll open a PR for it.
