### ISSUE TITLE
Enhancement: Interchange positioning of media library and device library icons

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/WordPress-Android#8477]
Currently the media uploader on the app shows the device library icon at the first, followed by camera and WordPress media library icon.

### Suggestion

It would be a great idea if the WordPress media library icon and the device media library icon can be interchanged.

<img width="720" alt="screen shot 2018-10-24 at 21 01 12" src="https://user-images.githubusercontent.com/18581859/47442474-057c4600-d7d0-11e8-8844-64df4883888c.png">
<sup>Image indicating the device library icon and WordPress media library icon on the media uploader section of the app</sup> 

### Reason behind this idea

Most often I have already uploaded an image to the WordPress media library, and when I want to insert this image again, I use the media uploader but choose the image from my device library instead - resulting in duplicate image on the media library.

Having the WordPress media library icon show up first eliminates this, in that users would be picking the image from the media library itself to use on their posts/pages. 

### Other apps

I haven't been able to check how this looks on the WordPress for iOS app.

**Comment by rachelmcr** [comment]
I'll ask designers to weigh in on this. I'd advocate for keeping the buttons positioned as-is, because one of the advantages of the mobile app is the ability to easily upload media directly from the device — it feels right to me to have those be primary/ordered first in this toolbar.

**Comment by rachelmcr** [comment]
Given that the focus for future editor development is now on Gutenberg, I took a look at how the media picker works there:

<img src="https://user-images.githubusercontent.com/8658164/67573142-88abe100-f72f-11e9-9ad0-2e6cae3116ef.png" width="50%">

Instead of presenting the media picker immediately with the device library as the default, you are now prompted to choose the source first. I think this resolves the main issue raised originally:

> Most often I have already uploaded an image to the WordPress media library, and when I want to insert this image again, I use the media uploader but choose the image from my device library instead - resulting in duplicate image on the media library.

**Comment by arunsathiya** [comment]
I agree. Thanks, @rachelmcr!
