### ISSUE TITLE
WordPress.org site settings: Blank view for non-admin users

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/WordPress-Android#8478]
### Steps to reproduce 

- Add a self-hosted WordPress (WordPress.org) site to the WordPress for Android app.
- Login as a non-administrator user.
- Open `Settings` section.

### Expected behavior

Username and password fields are shown, like in the case of the administrator user's session.

### Actual behavior

A blank, white view is seen.

![blank view on site settings for non-admin user on wordpress for android](https://user-images.githubusercontent.com/18581859/47443043-21ccb280-d7d1-11e8-8859-b2711f8ba3de.jpg)
<sup>Image indicating the blank view on self-hosted WordPress (WordPress.org) site settings on WordPress for Android</sup> 

##### Tested on [device], Android [version]

- [WordPress for Android 10.9.1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/10.9.1) - latest releases page
- Android 8.1.0

**Comment by rachelmcr** [comment]
Thanks for the report! This looks like another manifestation of the issue reported in https://github.com/wordpress-mobile/WordPress-Android/issues/7272.

**Comment by arunsathiya** [comment]
Looks like I missed noticing that one, thanks Rachel!
