### ISSUE TITLE
[Site Creation] Step: Site Preview - Unit Tests

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8506]
Write unit tests for Step: Site Preview VM. Parent ticket #8505

**Comment by malinajirka** [comment]
I've moved this back to Not Done state as a lot of changes were introduced in #8825

**Comment by oguzkocer** [comment]
Sorry about that @malinajirka, I thought this was not necessary anymore as I was trying to update the project tickets.

**Comment by malinajirka** [comment]
No reason to apologize @oguzkocer :). We weren't sure whether the loading screen would be part of the PreviewFragment or not.
