### ISSUE TITLE
[Site Creation] Analytics

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8509]
Make sure we track the same events as in the old Site Creation flow + add missing events ideally for all users interactions.

Final scope : p9wMUP-eo-p2
The preliminary scope of this task is being discussed here : p9wMUP-dZ-p2

Project master thread : p9wMUP-bk-p2
Plan proposal : p9wMUP-bs-p2

**Comment by kwonye** [comment]
We also want to make sure our internal analytics doc is updated

**Comment by kwonye** [comment]
[Aggregate doc of all our tracks events](https://docs.google.com/spreadsheets/d/1sWo5K6GsaLzojBewS25o05XAqWAnyyRBNZ2S9wfjG2w/edit#gid=0)

**Comment by oguzkocer** [comment]
Fixed in #8998.
