### ISSUE TITLE
Remove the location permissions

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#8516]
The app manifest includes the unnecessary location permissions (`android.permission.ACCESS_FINE_LOCATION` and `android.permission.ACCESS_COARSE_LOCATION`). 

They are only referenced by the utility class but they're not being used anywhere, so it's safe to remove them.

**Comment by drspaceboo** [comment]
Looks like this issue can be closed

**Comment by 0nko** [comment]
Why is that?

**Comment by drspaceboo** [comment]
I thought the previous PR resolved it but it was never completed and merged.
I'm sorry, I was skimming issues and thought this was accidentally still open.

**Comment by theck13** [comment]
This issue was addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/9165.

**Comment by 0nko** [comment]
@drspaceboo now it's closed :)
