### ISSUE TITLE
Pages screen: Overflow menu icon for pages not shown after opening editor

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#8520]
### Expected behavior
Pages shown in the Pages screen should show an overflow menu icon "..." to the right, that displays actions available to perform on the given Page.

### Actual behavior
Sometimes the overflow menu icons are not shown and you can't do anything.

![overflow_icons](https://user-images.githubusercontent.com/6597771/47792652-3f32dc80-dcfb-11e8-80c9-9b79a816dc2e.gif)

### Steps to reproduce the behavior
1. set airplane mode ON
2. from the main menu, go to the Pages screen
3. start a new draft, enter a title and some text
4. tap back (you should be able to find your draft under `drafts` tab)
5. observe the items in the list do not have any actions available (the three dots to the right of them).

Workaround: 
- go back to the main screen again and back to Pages, and voila they're back there.

I've noticed it sometimes also happens when moving an item from one tab to another (i.e. by making a published item a draft, or moving to trash, etc.).

**Comment by rachelmcr** [comment]
As noted in https://github.com/wordpress-mobile/WordPress-Android/issues/8608 this issue isn't limited to offline:

1. Go to ***My Site*** tab.
2. Tap ***Site Pages*** item under ***Publish*** section.
3. Notice overflow menu is shown for each page list item.
4. Tap page list item.
5. Notice editor is opened.
6. Tap back arrow.
7. Notice overflow menu is hidden for each page list item.
8. Swipe down to refresh list.
9. Notice overflow menu is hidden for each page list item.
