### ISSUE TITLE
Pages: Error fetching pages on a specific site

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8526]
We have a user report that the Site Pages list can't be refreshed, although the site is connected in the app and there are no other errors.

Trying to access pages in the app results in the error "Pages can't be refreshed at this time" and this error appears in the logs: `An error occurred while fetching the Pages`

This happens consistently on multiple devices (different manufacturers, different Android versions) so it doesn't seem to be device specific, and it started happening with version 10.9.1 so it could be related to Properly Placed Pages and how we fetch and display pages now.

Internal ref: p4a5px-2hN-p2

**Comment by SiobhyB** [comment]
We've heard news that this is fixed in 11.1. 🎉
