### ISSUE TITLE
Persistent crash when setting image size to full size if image has a caption.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#8543]
I was poking around with images today, looking for a different problem, when I came across a persistent crash.  After looking into it for a while I figured out that if an image has a caption and you try to set the site size of the image to full size it will cause the android app to crash.

It does not seem to have the problem with any other sizes, and the crash only happens if the image already has the caption before you try to edit it.  

Steps to replicate:
1. create a new post and insert an image.  Open the settings for that image and change the size to anything other then full size and add a caption to that image.  Save the settings and publish the post.
2. Edit the published post again and go back to the image settings.  Change the size of the image slider back to full size and then tap on the X to exit out of the settings.
3.  After hanging for a second the app will crash.

Tested on:
Android 5.1.1
WPAndroid alpha 133
Galaxy Tab A

**Comment by rachelmcr** [comment]
Thanks for the report! This sounds like the issue reported in https://github.com/wordpress-mobile/WordPress-Android/issues/8492 which has a fix coming in 11.2 (https://github.com/wordpress-mobile/WordPress-Android/pull/8517).
