### ISSUE TITLE
[GB-Integration] Make sure rotating the device maintains content 

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#8548]
### Expected behavior
Rotating the device should preserve content, and caret position.

### Actual behavior
Rotating the device does show the GB mobile "demo" content instead.

### Steps to reproduce the behavior
Start the gb-integration branch (feature/gutenberg-mobile), open a GB post, the new gb-mobile editor is used to edit the post. Rotate the device...

**Comment by mzorz** [comment]
This was closed via #9030
