### ISSUE TITLE
Editor: Revisions show HTML entities

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8558]
### Expected behavior

I expect post revisions to display the content as it would appear in the HTML view of the editor.

### Actual behavior

HTML entities are displayed in the revisions, e.g. instead of a quotation mark it shows `&quot;` like this:

![screenshot_20181106-181120](https://user-images.githubusercontent.com/8658164/48084914-da8eea80-e1f0-11e8-884a-8d2708da4718.png)

I confirmed that if I load the revision the content loads correctly (no HTML entities), but I wasn't confident about that when I was looking through the revisions.

##### Tested on Moto e5 Play, Android 8.1.0, WPAndroid alpha-135

cc @theck13 @khaykov

**Comment by elibud** [comment]
@rachelmcr is this OK to close as it mimics the web behavior?

**Comment by rachelmcr** [comment]
Yes, let's close this. I found an open issue on the web side to address this behavior: https://github.com/Automattic/wp-calypso/issues/23977

And our plan to enhance revisions with a visual view should be higher impact.
