### ISSUE TITLE
Refreshing Saved Posts List Doesn't Dismiss Removed Posts

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8559]
### Expected
When swiping down to refresh the ***Saved Posts*** list, removed posts are dismissed from the list.

### Observed
When swiping down to refresh the ***Saved Posts*** list, removed posts are not dismissed from the list.  See the animation below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/48085420-ce3e6980-e1bf-11e8-84fb-6adeea89342c.gif" width="240">

### Reproduced
0. Save post(s).
1. Go to ***Reader*** tab.
2. Tap filter dropdown list in toolbar.
3. Tap ***Saved Posts*** item in list.
4. Tap ***Add to Saved Posts*** action (i.e. bookmark icon) on saved post.
5. Notice card showing post is removed from list is shown.
6. Swipe down to refresh list.
7. Notice card showing post is removed from list is shown.

##### Tested
Google Pixel 3 on Android 9.0 with WordPress 11.0

**Comment by jorgecasariego** [comment]
What should be the behavior if we perform the following steps?

1. Go to _**Reader**_ tab.
2. Tap filter dropdown list in toolbar.
3. Tap  _**Saved Posts**_ item in list.
4. _**Saved posts**_ list
5. Touch _**Add to saved posts**_ action (that is, the bookmark icon) in the saved publication.
6. Notice card showing post is removed from list is shown.
7. Go to _**My site**_ tab or _**Me**_ tab
8. Go back to _**Reader**_ tab.
9. Note that the card continues to show that the publication has been removed from the list


<img src="https://user-images.githubusercontent.com/2581647/52385394-19d30e80-2a60-11e9-91b1-170225848e05.gif" height="500">

If that is not the desired behavior then in #9191 I might also add _purgeUnbookmarkedPostsWithBookmarkTag()_ in onResume() method. 

What do you think @theck13 ?

cc @malinajirka  @elibud

**Comment by malinajirka** [comment]
Thanks Jorge! AFAIK it's intended behavior. However, we can definitely change it, if it makes more sense. @SylvesterWilmott Wdyt?

**Comment by SylvesterWilmott** [comment]
Certainly the **expected** behaviour would be that the removed items are cleared on refresh but I'm also curious about the reason it was implemented this way.

**Comment by malinajirka** [comment]
Calling `purgeUnbookmarkedPostsWithBookmarkTag()` in onResume() will clear the posts even on device rotation. I'm not sure it's desired behavior.

>Certainly the **expected** behaviour would be that the removed items are cleared on refresh but I'm also curious about the reason it was implemented this way.

@iamthomasbishop Do you by any chance remember the reasoning behind this decision?

**Comment by malinajirka** [comment]
If it were up to me, I'd just keep the current behavior + clear the removed items on pull-to-refresh. It's an extremely minor issue anyway and it's probably not even worth fixing.

**Comment by iamthomasbishop** [comment]
> Certainly the **expected** behaviour would be that the removed items are cleared on refresh but I'm also curious about the reason it was implemented this way.

I agree with this – I think we had discussed clearing when you navigate away from the page after clearing an item, but the pull-to-refresh should do the same.
