### ISSUE TITLE
Changes to image settings not preserved

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#8569]
Seems like a regression of #5296.

### Steps to reproduce the behavior

1. Go to Blog Posts
2. Open a post with an image (or add one)
3. Tap on the image to open the media settings
4. Add a caption to the image
5. Change the alignment to Center, for example
6. Tap the X button to leave and save the settings
7. Tap on the image again
8. Notice the alignment is not set

##### Tested on [device], Android [version]
Android 8.0, emulator

**Comment by elibud** [comment]
@0nko are you taking care of this one?

**Comment by hypest** [comment]
Cannot replicate on an 8.0 emulator (Nexus 5X) nor on a physical Pixel 2XL (Android 9). Are there perhaps some other steps to include to reproduce?
