### ISSUE TITLE
Drafts Automatically & Unintentionally Publishing

### ISSUE THREAD

**Issue by torres126** [wordpress-mobile/WordPress-Android#8570]
I'm not too sure if this is the best place to report an issue, but there's something which seems to have happened more than once, and it's rather frustrating.

### Expected behaviour

Drafts should remain drafts when media is uploaded to the Media Library, but the media should be uploaded regardless

### Actual behaviour

A recent draft is published when media is uploaded to the Media Library, even though there was no modification made to that post. 

### Steps to reproduce the behaviour

1. Create a new blog post and upload an image
2. Close the app (do not save the blog post as a draft, but do not click "Publish" either)
3. You can wait if you wish (there was a matter of days between step 2 and step 4 in the times which this has happened to me)
4. Enter your Gallery and hold an item, then click "Share" or the equivalent
5. Select "WordPress" and "Add to Media Library"
6. Draft turns into a published post

### Additional Context

-Samsung Galaxy Tab S2 SM-T713
-Version 11.0 of WordPress app 
-Using the Beta editor
-Activity log, unfortunately I can't upload directly to GitHub for some reason :(
https://clubpenguinmountains.files.wordpress.com/2018/11/screenshot_20181107-182850.jpg

An issue similar to this occurred in February 2018 too with my blog, and if I recall correctly, it was this exact same thing too which provoked the post to publish unintentionally. I'm assuming that because of this, it is a bug with the WordPress app, as it's never happened through a web browser, including with Calyspo and the Classic Editor. I'm able to recreate this on a test site too.

Thanks! :)

**Comment by rachelmcr** [comment]
Thanks for reporting that issue! I reproduced it with the steps you provided.
