### ISSUE TITLE
Logo Proposal for Project Enhancement

### ISSUE THREAD

**Issue by debpedrano** [wordpress-mobile/WordPress-Android#8589]
Good day PO,

This repo is getting bigger and I am offering you logo design for the repo, everything is for free. I just want to contribute and gain more knowledge about graphics.

Is there any chance I can open up this issue and have your permission to create a logo?

**Comment by rachelmcr** [comment]
Thank you for the offer! However, WordPress for Android is part of the [WordPress](https://wordpress.org/) project, so we don't need a new logo at this time. :)
