### ISSUE TITLE
Update "beta" label for Aztec in app settings

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8611]
Under Me > App Settings we have an editor setting that still lists Aztec as the Beta editor.

Especially with Gutenberg coming out, we need to relabel Aztec so it's clear it is the latest stable editor, not beta. (Also, do we need to keep Aztec, Visual, and Legacy editors all available there?)

![screenshot_20181115-162353](https://user-images.githubusercontent.com/8658164/48567327-ab653100-e8f4-11e8-8c90-789e2efafb0d.png)

Note that this is not an issue in iOS, which no longer has an editor selector (only Aztec).

cc @hypest

**Comment by hypest** [comment]
Good point and question @rachelmcr , thanks for opening this ticket.

My suggestion would be to rename "Beta" to "Classic" to perhaps closer mirror the Classic editor on WordPress-web, and in preparation of discerning from "Gutenberg/Block" a bit later. We should probably do the rename asap so people can have some time to get used to the new name. cc @loremattei , @koke 

In terms of keeping all past editors or dropping any, I think we were keeping Visual as it had better media performance in cases and we were also keeping Legacy for some reason. @daniloercoli , perhaps you have some recollection or insight about the Legacy editor?

**Comment by rachelmcr** [comment]
I agree that if we have all three it's confusing to choose between them. If we want to keep the reference to Classic perhaps Aztec could be labeled "Classic (Default)" or something like that.

**Comment by daniloercoli** [comment]
> In terms of keeping all past editors or dropping any, I think we were keeping Visual as it had better media performance in cases and we were also keeping Legacy for some reason. @daniloercoli , perhaps you have some recollection or insight about the Legacy editor?

You're right about the Visual editor (the one powered by web-view). It's there to help users loading posts with a lot of media that fail in Aztec. 

> Looking at the data we have I see less than 3% of posts used anything other than Aztec, so we might want to consider dropping the other two early.

I vote to drop `Legacy` and `Visual` asap, and check the reviews/feedback/help requests from our users.

**Comment by SiobhyB** [comment]
+1 for removing Legacy and updating the Beta label. :D I just posted a case where Legacy caused some confusion for both a user and a HE in p4a5px-2jk-p2. Users are currently stuck in HTML mode if they're on the Legacy editor, which may be even more confusing when editing posts created in Gutenberg (due to the markup generated for blocks). Multiple editors can also cause unecessary confusion from a support-perspective.

**Comment by koke** [comment]
The old editors were removed from the UI in #9208
