### ISSUE TITLE
Support for Giphy

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#8627]
I would like to be able to import gifs from Giphy. The iOS app already has this as shown in wordpress-mobile/WordPress-iOS#10276.

## Key Features

- Import from the Editor
- Import from the Media Library
- Picker
  - Search
  - Preview
  - Pick multiple gifs

## Feature Branch

Pull requests are merged on this main feature branch:  [shiki/WordPress-Android/tree/issue/8627-giphy](/shiki/WordPress-Android/tree/issue/8627-giphy)

## Tracking

This is a quick reference of what's happening with this project. 

| Task          | Status        | Pull Request         |
| ------------- | ------------- | ------------- |
| **Import from the Editor** |  ✔️ | shiki/WordPress-Android#6 |
| **Importing from the Media Library** |  ✔️ | shiki/WordPress-Android#3 |
| **Picker** | | |
| ↳ Search | ✔️| shiki/WordPress-Android#1 |
| ↳ Preview | ✔️| shiki/WordPress-Android#4 |
| ↳ Pick multiple GIFs | ✔️| shiki/WordPress-Android#2 |
| ↳ Searching while typing | ✔️ | shiki/WordPress-Android#8 |
| ↳ Show an empty view if there are no results |  ✔️ | shiki/WordPress-Android#5 |
| ↳ Error handling if network requests fail |  ✔️ | shiki/WordPress-Android#7 |
| **Others** | | |
| ↳ Analytics | ✔️| included in shiki/WordPress-Android#3 and shiki/WordPress-Android#8 |
| ↳ Localization | ✔️| _handled by automation_ |
| ↳ Attribution for [giphy-android-sdk-core](/Giphy/giphy-android-sdk-core) | ✔️| shiki/WordPress-Android#9 |
| **Wrap up** | | |
| ↳ We have to attribute Giphy (e.g. logo) |  ✔️ | included in  shiki/WordPress-Android#5  |
| ↳ Merge all to [wordpress-mobile/WordPress-Android](/wordpress-mobile/WordPress-Android) | | #8792  | 
| ↳ Update `RELEASE-NOTES.txt` | ✔️| included in shiki/WordPress-Android#8 |
| ↳ Review copy (`strings.xml`) | ✔️| |
| ↳ Integrating `gradle.properties` changes with production builds | ✔️| |

**Comment by kwonye** [comment]
A few things I caught from the first review that I think we should add:

1. In the empty list view, we have to attribute Giphy. Let's add an empty view with the logo. Feel free to ping me for that.
2. This is an extra, but can we have the initial results be the trending list through the [trending endpoint](url
https://github.com/Giphy/giphy-android-sdk-core#trending-endpoint)?

**Comment by shiki** [comment]
> 1. In the empty list view, we have to attribute Giphy. Let's add an empty view with the logo. Feel free to ping me for that.

I added this to the task list. 

> 2\. This is an extra, but can we have the initial results be the trending list through the [trending endpoint](url
>     https://github.com/Giphy/giphy-android-sdk-core#trending-endpoint)?

@kwonye To be clear, do you mean that when the user opens the Giphy Picker, they should immediately see the trending GIFs? Also, does it make sense to do this after we've finished the actual _importing_ of GIFs to the Media Browser and Editor?

**Comment by kwonye** [comment]
> Also, does it make sense to do this after we've finished the actual importing of GIFs to the Media Browser and Editor?

Yea, let's not worry about this for now, sorry about getting too excited about it 😋

**Comment by shiki** [comment]
Closing this issue now since #8792 has been merged. 🙂
