### ISSUE TITLE
Gutenberg - mobile Editor opt-in for Alpha

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#8684]
Comes from https://github.com/wordpress-mobile/gutenberg-mobile/issues/222#issuecomment-442074545

> We'll have a simple switch on Me > Settings that replaces what the -gutenberg command line argument does now. This setting (and Gutenberg) should only be visible on debug and internal builds. Below, it should have some explanation that this is an experimental feature.

As discussed elsewhere with @koke  and @elibud, this manual switch is a need for showcasing the feature and giving the user full control (at their own risk)  just for internal testing (alpha).

ToDo:
- [x] show new (persistent) switch in Me > Settings
- [x] the switch should only be visible on debug and internal builds (alpha)
- [x] below, show an explanation that this is an experimental feature.
```
*EXPERIMENTAL*
💣 This is still an experimental version of Gutenberg 🙈
```

~- [ ] add Tracking~
- [x] if the setting is enabled:
- launch Gutenberg when it's a Gutenberg Post
- launch Aztec for existing non-Gutenberg Posts
- launch Gutenberg for new posts
- [x] if the setting is disabled:
- launch the editor of their choice according to existing settings

**Comment by mzorz** [comment]
WPiOS counterpart https://github.com/wordpress-mobile/WordPress-iOS/issues/10554

**Comment by koke** [comment]
This is only for internal builds and likely temporary, we don't need tracking.

**Comment by mzorz** [comment]
> This is only for internal builds and likely temporary, we don't need tracking.

Updated the description

**Comment by diegoreymendez** [comment]
On top of what's mentioned in the description of this issue, this is the logic we use to allow the user to switch between editors in iOS:

- If Gutenberg is enabled:
  - When in Aztec:
    - Show the option to switch to Gutenberg only if the post has blocks or is empty.
  - When in Gutenberg:
    - Show the option to switch to Aztec for all posts.
- If Gutenberg is not enabled:
  - Don't show the option

**Comment by mzorz** [comment]
Closing via #8695
