### ISSUE TITLE
Site Creation: Site Preview Landscape

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#8687]
We have a slightly different design for the landscape version of the new site preview screen. Since the original PR is merged without it, I am opening an issue for this just to make sure we don't forget about it.

**Comment by oguzkocer** [comment]
@SylvesterWilmott I have made some progress on this today, but I just realized something. What are we going to do with the animations? That kind of makes me question whether this is actually worth it or not. Probably still is, but yeah. Before I proceed further, could you let me know your thoughts on the animation?

/cc @malinajirka since you have worked on the animation, I am hoping you can guide me a bit on this.

**Comment by SylvesterWilmott** [comment]
Yes, for landscape the animation will behave differently. The text + button will fade in and the screenshot will push in from the bottom.

**Comment by malinajirka** [comment]
>/cc @malinajirka since you have worked on the animation, I am hoping you can guide me a bit on this.

Sure thing. Feel free to either create a separate issue and I'll take care of it or let me know what you want to help with. ;-)
