### ISSUE TITLE
Simple formatting shows as HTML after publishing

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#871]
If you create a post and add some simple formatting, the post is rendered with that formatting (so bold items are bolded, etc.). But if you publish the post and then edit it, the formatting is rendered as HTML tags.

![post-simple-html](https://f.cloud.github.com/assets/3903757/2174183/7993c420-95ac-11e3-99ae-e7401fac4cd1.png)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
