### ISSUE TITLE
Facebook publicize connection keeps failing

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8715]
Related to #8115 
### Expected behavior
When the user tries to connect a Facebook account with no pages to their site the app displays meaningful error with explanation why it can't connect to the account.

### Actual behavior
When the user tries to connect a Facebook account with no pages to their site the app displays generic error which isn't very helpful.

### Steps to reproduce the behavior
1. Try to add a Facebook account with no pages.

Notes
I think the issue is on the [following](https://github.com/wordpress-mobile/WordPress-Android/blob/04ce455c5adecf5ca8009864d55218ae2566f075/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java#L147) line -> we don't show the chooser dialog when there is exactly one connection and we assume this connection will work. However, if this is a User Profile connection and the service (such as Facebook) doesn't support other than external connections, it'll fail with meaningless error message.

I think we should modify the check to `if (... || jsonConnectionList.length() == 0)` and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/04ce455c5adecf5ca8009864d55218ae2566f075/WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java#L166) propagate a specific error to the UI and show a meaningful message.

cc @kwonye

**Comment by kwonye** [comment]
That sounds like a great solution, @malinajirka. If I recall correctly I thought we didn't get a profile back at all if there was no pages. Looks like that's not the case.

**Comment by designsimply** [comment]
Tested and confirmed ([11s](https://user-images.githubusercontent.com/1119271/54551169-273ebb00-4973-11e9-8ff6-d79d1803c347.gif)) using WPAndroid alpha-156 (12.0 alpha) on Pixel 3 Android 9. In my case I tested with a Facebook account that has a Page that is unpublished in Facebook > Page > Settings > General > Page Visibility ([screenshot](https://user-images.githubusercontent.com/1119271/54549109-fe1c2b80-496e-11e9-8e5b-7ec12a4f6fc9.png)).

<img src="https://user-images.githubusercontent.com/1119271/54551304-7684eb80-4973-11e9-806c-75992fe4c0e1.png" width="200" alt="sharing-screen"> <img src="https://user-images.githubusercontent.com/1119271/54551303-7684eb80-4973-11e9-9826-96653437b85f.png" width="200" alt="connect-facebook"> <img src="https://user-images.githubusercontent.com/1119271/54551302-7684eb80-4973-11e9-8562-26d248b87f44.png" width="200" alt="connect-facebook-profile-error"> 

I couldn't get the app logs to save for some reason (or I missed them) but I caught a screenshot:

<img src="https://user-images.githubusercontent.com/1119271/54551514-e1362700-4973-11e9-9ea7-a7eb7ecb6d7e.png" width="200" alt="Screenshot_20190318-111926">

**Comment by designsimply** [comment]
This came up again in 12.3 beta testing. I found that I was unable to connect Facebook or LinkedIn—the result was the same for each: "An error occurred". My test Facebook account does have a Page but it is unpublished ([screenshot](https://user-images.githubusercontent.com/1119271/57123603-9fa0e600-6d3f-11e9-8814-29f27cbb4f38.png)).

Video: [4m39s](https://cloudup.com/cUT7q0RMu8d)

<img src="https://user-images.githubusercontent.com/1119271/57123832-83517900-6d40-11e9-8d82-d7754f6a24a9.png" height="470" alt="Screen Shot 2019-05-03 at 1 10 04 AM"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57123831-83517900-6d40-11e9-91bd-2cfe4053fa73.png" height="470" alt="Screen Shot 2019-05-03 at 1 10 49 AM">
<sub>Tested with WPAndroid alpha-168 on Pixel 3 Android 9 on `architectural-worm.wordpress.com` Jetpack (and also other sites).</sub>

[app-log-to-connect-LinkedIn-and-Facebook-sharing-services.txt](https://github.com/wordpress-mobile/WordPress-Android/files/3140892/app-log-to-connect-LinkedIn-and-Facebook-sharing-services.txt)

```
71 - [May-03 01:54 SHARING] publicize service > created
72 - [May-03 01:54 SHARING] publicize service > destroyed
73 - [May-03 01:54 SHARING] null
74 - [May-03 01:54 SHARING] StackTrace: com.android.volley.ServerError
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

75 - [May-03 01:54 UTILS] App goes to background
76 - [May-03 01:54 MAIN] ConnectionChangeReceiver successfully unregistered
77 - [May-03 01:55 UTILS] App comes from background
```

<sup>(internal reference: p5T066-Pl-p2)</sup>

**Comment by osullivanchris** [comment]
Here is a ticket with a user experiencing this issue. Getting more info from the user to understand the issue https://woothemes.zendesk.com/agent/tickets/2047729

**Comment by designsimply** [comment]
@osullivanchris 2047729-zen mentions a different case because they are trying to connect a Facebook account with a page whereas this bug is about trying to connect a Facebook account with no pages. If you can open a new issue with a quick list of steps to reproduce then I will check it out!

**Comment by shiki** [comment]
The LinkedIn failure does not seem to be related to the Facebook error. I created a separate issue for it: https://github.com/wordpress-mobile/WordPress-Android/issues/10252.
