### ISSUE TITLE
Post editor: soft keyboard disappears after inserting media

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#872]
The soft keyboard goes away after choosing a photo to add to a post. The user has to tap in the editText to re-display the keyboard.

![device-2014-02-14-142012](https://f.cloud.github.com/assets/3903757/2174233/5a469bdc-95ad-11e3-849c-702dbabecdd3.png)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
