### ISSUE TITLE
Site Creation: Verticals page header is missing

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#8751]
When I was working on the domain page, I have been trying to go back and forth between them and I ended up with the below state where the header is missing when it should be shown a few times. Unfortunately I don't have the exact steps to reproduce it, but typing something in the input of the verticals page, selecting one to go to domain page, coming back and fiddling with the input again should work.

![screenshot_1544214658](https://user-images.githubusercontent.com/662023/49677056-b110eb00-fa4a-11e8-9d9a-2ad04eed7bda.png)

**Comment by malinajirka** [comment]
Fixed in #8753
