### ISSUE TITLE
Login failure after entering correct 2FA

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#8754]
This happens on debug builds only. It works fine on production version 11.3.

### Expected behavior

The successful login page should be shown after entering the Verification Code.

### Actual behavior

![dec-09-2018 06-31-19](https://user-images.githubusercontent.com/198826/49698252-70b28980-fb7e-11e8-8754-c60d5d79d55d.gif)

An error saying "Couldn't retrieve your profile" is shown instead. This is shown in the logs:

```
D/sync_get_request: Is caching: https://public-api.wordpress.com/rest/v1.1/me/settings/?locale=en_CA
E/Volley: [9525] BasicNetwork.performRequest: Unexpected response code 401 for https://public-api.wordpress.com/rest/v1.1/me/settings/?locale=en_CA
E/Volley: [9525] BasicNetwork.performRequest: Unexpected response code 401 for https://public-api.wordpress.com/rest/v1.1/me/settings/?locale=en_CA
E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/me/settings/?locale=en_CA
    com.android.volley.AuthFailureError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
D/WordPress-API: Dispatching action: AccountAction-FETCHED_SETTINGS
W/WordPress-API: Error fetching Account Settings via REST API (/me/settings)
    Error: com.android.volley.AuthFailureError
E/WordPress-API: onAccountChanged has error: SETTINGS_FETCH_ERROR - A fresh access token must be used to query information about the current user.
```

#### Setup

- Used `develop` branch. At that time, I was at commit 01de4c62ec.
- Used a WordPress.com account. 2FA is enabled.
- Followed the [OAuth2 Authentication](https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication) instructions to set up `app_id` and `app_secret`.
- Tested on Android Emulator Nexus 5X API 28 (Pie).

#### Steps

1. Log in with the email address
2. Enter password manually to continue logging in
3. At the Verification Code screen, enter the 2FA code from your Authenticator app.

The error is shown after that.

#### Bypass

After entering the 2FA code and receiving the error, you can bypass the login screen by:

1. Force close the app
2. Open it again
3. You will be automatically logged in and the _My Site_ page should be shown.

**Comment by rachelmcr** [comment]
Thanks for the report!

I have run into this error before, as well, but only when testing with a WordPress.com account with 2FA where I linked a Google account to the WordPress.com account and then later changed what Google account was linked to it (internal ref: p5T066-xS-p2). It felt pretty edge case at the time — just mentioning it here in case that scenario sounds familiar.

**Comment by shiki** [comment]
@rachelmcr As far as I can remember, I've never linked a Google account. I looked at my current settings and there's no Google account linked too. I hope this info is useful.
