### ISSUE TITLE
Editor revisions: loading latest revision makes post get uploaded even if no changes

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#8773]
### Expected behavior
When loading the same history revision as the current one, the Post should not get updated.

### Actual behavior
The post gets updated when the last history revision version gets loaded on the Editor.

### Steps to reproduce the behavior
1. start a new Post (Aztec)
2. type a title
3. start a paragraph, enter "first version" as text.
4. tap back
5. observe the post gets uploaded as a draft
6. open it again and edit  paragraph "first version" enter something else, for example I entered "second version"
7. tap back to make the first entry in history
8. open it again
9. now add a new paragraph with text "hello"
10. tap back, open it again and tap on History to see you have 2 entries there.
11. load one of the older entries
12. wait for the snackbar to hide
13. tap on undo
14. tap back - the post is uploaded (IIUC, it shouldn't).

NOTE: If you set airplane mode ON before step 14, the post is then marked with `Local changes` as described in the [original report](https://github.com/wordpress-mobile/WordPress-Android/pull/8768#issuecomment-446239923).

**Comment by malinajirka** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9320

**Comment by mzorz** [comment]
@malinajirka #9320 has been closed without merging with reasoning behind so explained in https://github.com/wordpress-mobile/WordPress-Android/pull/9320#issuecomment-468025340  so, if this issue is still happening then it should be re-opened IIUC. Can you verify and re-open if needed? Thanks!

**Comment by malinajirka** [comment]
Ohh, I missed the fix wasn't merged. Thanks pointing that out.

However, I believe we can keep this issue closed as step 13 isn't supported anymore -> the undo button in the Toolbar overflow menu is disabled.

If the user clicks on the UNDO action in the SnackBar it works as expected -> the post won't get uploaded.

**Comment by mzorz** [comment]
🎉 thank you for clarifying! 

> I believe we can keep this issue closed as step 13 isn't supported anymore -> the undo button in the Toolbar overflow menu is disabled.

Tested and agreed, this issue is not applicable anymore :)
