### ISSUE TITLE
Improve Gradle integration of Gutenberg and React Native dependencies

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#8783]
Unlike pretty much every other Android library, React Native is not distributed through a maven repository (see [this issue](https://github.com/facebook/react-native/issues/6459)). To get around this we currently use [jsdelivr](https://www.jsdelivr.com/), which is a cdn that mirrors npm, as a maven repo this like this:

```
repositories {
    ...
    maven {
        url "https://cdn.jsdelivr.net/npm/react-native@0.57.5/android"
    }
    maven {
        url "https://cdn.jsdelivr.net/npm/jsc-android@224109.1.0/dist/"
    }
}
```

This mostly works well but has a some issues:

1. Gradle sometimes tries to fetch other dependencies from this "repos", causing Gradle to fail with an error like this:
```
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://cdn.jsdelivr.net/npm/jsc-android@224109.1.0/dist/com/google/firebase/firebase-iid/'
```
2. WordPress-Android has quite a bit of config for Gutenberg's dependencies in its gradle files, including hardcoded version numbers. Ideally it would be dealt with transitively and there would be no problem.

I have outlined a few options to resolve this below. If the implementation gets tricky we may want to consider making a Gutenberg Gradle plugin to encapsulate it.

### 1. Require 'yarn install' in WordPress-Android

I'm not keen on the idea of requiring all WordPress-Android developers to have a working `node` toolchain and have to run `yarn install` but this is the simplest option. Gradle could use `node_modules` as a local repo and everything should work fine.

If we fail to come up with a better option we may need to consider this.

### 2. Mirror React Native in maven repository

Another option is that we could just put the artifacts in maven repo somewhere and include that in our projects, something like this:

```
maven { url "https://dl.bintray.com/gutenberg-dependencies/maven/" }
```

This would require some work to automate uploading new versions of React Native etc. but I don't think it would be too bad. Once done, everything would behave as if React Native was any other Android library.

### 3. Use gradle-node-plugin to download dependencies

[gradle-node-plugin](https://github.com/srs/gradle-node-plugin) is a Gradle plugin for integrating Node + friends into a Gradle project. Once installed, it allows you to run something like `./gradlew yarn_add_react-native` to install React Native into `node_modules/`. It should be possible to run a task like this prior to building so that the dependencies will be present.

This is similar to option 1 above but hopefully without putting more requirements on developers of WordPress-Android.

### 4. Download the dependencies manually

Similar to the previous point, we could download just the dependencies we want from `jsdeliver` in a pre build task so that they can be used as local maven repos. It adds a little complexity in our implementation but could be completely independent of node/yarn.

For example, React Native can be downloaded from this url:

```
https://registry.npmjs.org/react-native/-/react-native-0.57.8.tgz
```

### 5. Wait for Gradle 5.1

This probably isn't a realistic option because we may be waiting for quite some time but its worth mentioning. [Gradle 5.1 will include](https://github.com/gradle/gradle/issues/1369#issuecomment-443137040) the ability to limit repositories to specific dependencies like this:

```
repositories {
    maven {
        url "https://repo.mycompany.com"
        content {
           includeGroupByRegex "com\\.mycompany.*"
        }
    }
}
```

cc @hypest @wordpress-mobile/platform-9

**Comment by hypest** [comment]
Some related info about how come the RN lib is not on jcenter, etc https://github.com/facebook/react-native/issues/13094

**Comment by jtreanor** [comment]
@hypest We can definitely try that next. One thing I don't love about that is that it requires us to hardcode the versions of React Native and JSC in WordPress-Android. It would be great if this wasn't needed.

I'm personally keen on the idea of using uploading the artifacts we want to something like Bintray so we should require no gradle tricks are scripts on the WP side.

**Comment by loremattei** [comment]
> I'm personally keen on the idea of using uploading the artifacts we want to something like Bintray so we should require no gradle tricks are scripts on the WP side (option 2).

This looks like a very good option to me as well. I don't know how much time it would take to set up the _custom_ maven repository, but it looks like clean solution with a very small impact of devs daily workflow.

**Comment by jtreanor** [comment]
I have set up a custom maven repo on Bintray that has the dependencies we need here: https://bintray.com/jtreanor/gutenberg-dependencies-test

I have made a branch to use this here: https://github.com/wordpress-mobile/WordPress-Android/compare/react-native-repo

There is a proguard error on building `vanillaRelease` (debug works fine) but the dependencies do resolve correctly. Given the simplicity of this, it seems like a good option to me.

**Comment by hypest** [comment]
Hmm, nice work there @jtreanor . I'm wondering though, we actually need to have close control of what version of RN and JSC we're using so, how can we control that (and better, how to have it part of version control) with the bintray repo?

Note, the RN version needed is tightly coupled with gutenberg-mobile. It's not just using what's latest for example.

**Comment by jtreanor** [comment]
> I'm wondering though, we actually need to have close control of what version of RN and JSC we're using so, how can we control that (and better, how to have it part of version control) with the bintray repo?

Of course! Like all dependencies, versions are important. This is not a special case. However, since React Native is not a direct dependency of WordPress-Android (or WordPressEditor), that version information shouldn't live here.

In fact, the versions are already defined in the `.pom` file generated by Jitpack for `react-native-gutenberg-bridge`: https://jitpack.io/com/github/wordpress-mobile/gutenberg-mobile/5cfe37c6f4/gutenberg-mobile-5cfe37c6f4.pom

```
<dependency>
  <groupId>com.facebook.react</groupId>
  <artifactId>react-native</artifactId>
  <version>+</version>
  <scope>runtime</scope>
</dependency>
```

It currently allows any version. We can update that to a more specific version by changing this line in the Gutenberg bridge: https://github.com/wordpress-mobile/gutenberg-mobile/blob/master/react-native-gutenberg-bridge/android/build.gradle#L89

> Edit: I guess we will need to have all needed versions pushed/uploaded and avail in parallel?

Yes, the Maven repo should contain all versions of React Native and JSC (or those that we ever use). It should be quite straightforward to write a script to sync npm and bintray with this.

**Comment by jtreanor** [comment]
Thinking about this some more, I think we also have an opportunity to simplify how `wp.BUILD_GUTENBERG_FROM_SOURCE` works if using the maven repo approach I suggested above.

Since the repo could contain any RN versions we want, it could remove the need to load the dependencies from `node_modules`, even in source mode.

This means we could use `maven { url "https://dl.bintray.com/wordpress-mobile/gutenberg-dependencies" }` in both source and binary mode, without needing to switch on `if (rootProject.ext.buildGutenbergFromSource)`.

**Comment by hypest** [comment]
> Thinking about this some more, I think we also have an opportunity to simplify how wp.BUILD_GUTENBERG_FROM_SOURCE works if using the maven repo approach I suggested above.
> 
> Since the repo could contain any RN versions we want, it could remove the need to load the dependencies from node_modules, even in source mode.

Looping back (from chatting over Slack), I think that when using sources it is important to actually use the local `node_modules` folder so, it is quite undesirable to get the dependency as binary from a remote repo. All in all, the binary mode is only in place to help non-gb devs avoid RN as much as possible so, let's keep the "sources" mode as close to the proper RN dev flows as possible.
