### ISSUE TITLE
Preview for posts/pages doesn't include line breaks

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#8787]
### Expected behavior

When previewing a post or page, I expect for it look like the version of the post or page, with line breaks included.

### Actual behavior

Line breaks aren't included when previewing posts or pages within the app. All text is included on one line, which doesn't accurately reflect what the publish post or page actually looks like.

Screenshot of text within the post editor:

![screenshot_20181212-204200](https://user-images.githubusercontent.com/2998162/50002288-8ddcc300-ff97-11e8-99c9-636fb4ce169e.png)

Screenshot of what the text looks like when previewed from the post editor, with missing line breaks:

![screenshot_20181212-204218](https://user-images.githubusercontent.com/2998162/50002379-dac09980-ff97-11e8-8c46-91e78648d9a1.png)

### Steps to reproduce the behavior

1. Navigate to My Site > Blog Posts and create a new post.
2. Enter some text for post, including multiple line breaks (using the return key on your phone's keyboard).
3. Tap the three dots to the upper right of the post editor then "Preview". 

##### Tested on Pixel, Android alpha-142

Reported in 1633451-z.

Possibly related to another preview issue in https://github.com/wordpress-mobile/WordPress-Android/issues/8755.

**Comment by drspaceboo** [comment]
Could not replicate with either Master or Develop today. Perhaps this issue has been resolved.

**Comment by rachelmcr** [comment]
I also couldn't reproduce this issue. If the issue persists, please provide additional details or steps to reproduce it and we can reopen for investigation.
