### ISSUE TITLE
Feature request: Add option to select color for each site to help identify site

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#8862]
### Enhancement request

I wonder if it is possible in the Wordpress app different websites to give a different color - so that you can immediately recognize which one edited?
(So the upper and the blue bar always looks different)

Requested by user: 1666346-zen

**Comment by iamthomasbishop** [comment]
Thanks for the request, @rezzap, this is really interesting and the first I've heard of something like it. I have a couple questions, to make sure I am understanding the use case and context:

* Can you explain how you discovered this idea? Was there something specific that happened or went wrong that surfaced the need for something like this?

* Where in the app would you expect this site-specific color to be shown in the app bar?

* How/where would you expect to "set" a custom color for a site?

* Are your sites self-hosted, WordPress.com, or a mix?

Thanks again, for taking the time to make a request!

**Comment by rezzap** [comment]
Hi @iamthomasbishop (sorry for the delay in following up with this),

This request was posted by a user through the mobile app, so I'm not sure exactly on the best way to comment on this in terms of what the user was looking for. 

I've sent a request to the user with your questions to see if this is something they can clarify on. 

I can confirm that the user has a number of different self-hosted site listed in the app and I can see how having the option for each site to use a different color tab (instead of the default blue) would help to determine which site you're working on more clearly. 

I'll follow up if we receive additional information from the user.

**Comment by rezzap** [comment]
The user has sent the following information:

> I writing on six WordPress sites, where only two are public.
> 
> Several times i had the problem that i made an entry to the wrong blog because i didn't look to the title. Now i've two blog's where the first Letters are the same (picture). There is no way to see which blog i'm on. I cannot see the favicon. I set them - but they aren't shown - especially while writing an blog entry.

<img width="552" alt="image 2019-02-02 at 5 15 07 pm" src="https://user-images.githubusercontent.com/10325627/52167125-62ac5f80-270e-11e9-89c6-4b576f9c928f.png">
<img width="544" alt="image 2019-02-02 at 5 17 33 pm" src="https://user-images.githubusercontent.com/10325627/52167132-8079c480-270e-11e9-82f3-a58300720764.png">

**Comment by iamthomasbishop** [comment]
Ah, that's interesting, thanks for sharing @rezzap! I think there are multiple things going on here: 

* They seem to be using an old editor, which will probably be deprecated soon. However, regardless of which editor is active, we  need to improve the messaging here. When a post is created, perhaps we should show a Snackbar (https://material.io/design/components/snackbars.html) along the bottom of the screen that appears for 1-2 seconds and says "New post on [Site Name] created." and offers a button to [Switch sites].  This would be a good issue for Groundskeeping. I'll tag it as such.

* While the original request was to color the App Bar, I'm not sure if that alone is the right solution moving forward. The new Block Editor (aka Gutenberg) will remove the color from the App Bar altogether, as to provide more focus on the content. The original plan was to show the Site Icon on the App Bar (where the Site Name currently is) as an identifier, but I think I'll add this as an issue to put in this project's backlog for consideration.

* Odd that the Site Icon isn't showing there - that might be a bug. Would you mind creating an issue for this?

**Comment by rezzap** [comment]
Thanks for that information @iamthomasbishop. I've created the new issue for the site icon, though if I didn't understand what the issue is exactly, feel free to edit this to clarify. 

I think your suggestion about adding the Snackbar and site icon would definitely be good alternatives to helping with this.

**Comment by iamthomasbishop** [comment]
> I've created the new issue for the site icon

I'm sorry for the confusion – I misunderstood where they meant the site icon wasn't displaying. I thought they were referring to the Site home on the My Sites ("Meine Webseiten") tab. If the icon isn't showing properly _there_, then that's a bug :) 

We aren't currently showing the Site Icon on the Editor itself (although this has been explored in Gutenberg), so that isn't a bug.

**Comment by designsimply** [comment]
I tested this using WPAndroid 15.5-rc-1 and found that the Site Title is now displayed at the top of the block editor. If anyone is still having issues, please first make sure you are using the newest editor. You can turn on the block editor for a site in My Site > Settings.

<img src="https://user-images.githubusercontent.com/1119271/90048279-81d76600-dc90-11ea-8e2d-4c78b0ba1e52.jpg" width="270" alt="Screenshot_20200812-113734">

<p style="clear:both;"><sup>Tested with WPAndroid 15.5-rc-1 on Pixel 4 Android 10.</sup></p>
