### ISSUE TITLE
Confusion when domain is registered to WordPress.com site but pointing to Jetpack site

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#8876]
### Expected behavior

If a domain, **example.com**, is registered to a WordPress.com site, **example.wordpress.com**, but points to a Jetpack site, I would expect this to be clear from the site list in the app.

In Calypso, if a domain is not pointing to WordPress.com, the WordPress.com subdomain is displayed in the site picker. So, **example.com** and **example.wordpress.com** would be listed when viewing the list of sites from the site picker. This helps to avoid confusion when a user's managing their sites, as it doesn't make it seem like there's two instances of **example.com**.

I would expect the same behaviour in the app.

### Actual behavior

The app's site picker displays the domain that's registered to a WordPress.com site, regardless of whether the domain points to another host. So, **example.com** would be listed twice when navigating to My Sites > Switch Site. 

This has caused a great a deal of confusion for the user in 1634497-z. They believe that they're seeing incomplete stats when, in fact, they're viewing stats for their old WordPress.com site.

### Steps to reproduce the behavior

1. Start by creating a WordPress.com site and register a domain to it.
2. Change the domain's name servers to point it to a WordPress site that's hosted outside of WordPress.com.
3. Connect that site to WordPress.com via the Jetpack plugin.
4. Navigate to My Sites > Switch Site in the app. You'll see the domain appear twice in your list of sites. Log into WordPress.com in a web browser to see how this is handled differently in Calypso.

**Comment by ravishanker** [comment]
This doesn't seem to happening anymore.  I've followed the steps listed and I could see only one domain.  So, closing this issue for now.

**Comment by ravishanker** [comment]
This doesn't seem to happening anymore.  I've followed the steps listed and I could see only one domain.  So, closing this issue for now.
