### ISSUE TITLE
Site Creation: Skip Button Margins Differ

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8883]
### Expected
***Skip*** buttons in the _**Site Creation**_ flow have the same margins.

### Observed
***Skip*** buttons in the _**Site Creation**_ flow do not have the same margins.  The button on ***1 of 3*** has [`16dp` top, bottom, start, and end margins](https://github.com/wordpress-mobile/WordPress-Android/blob/8b867405382d221c5dbf16d00e68f4c4f5e8484c/WordPress/src/main/res/layout/new_site_creation_verticals_screen.xml#L68).  The button on ***2 of 3*** has [`12dp` top margin](https://github.com/wordpress-mobile/WordPress-Android/blob/8b867405382d221c5dbf16d00e68f4c4f5e8484c/WordPress/src/main/res/layout/new_site_creation_site_info_screen.xml#L134), [`12dp` bottom margin](https://github.com/wordpress-mobile/WordPress-Android/blob/8b867405382d221c5dbf16d00e68f4c4f5e8484c/WordPress/src/main/res/layout/new_site_creation_site_info_screen.xml#L132), and [`16dp` end margin](https://github.com/wordpress-mobile/WordPress-Android/blob/8b867405382d221c5dbf16d00e68f4c4f5e8484c/WordPress/src/main/res/layout/new_site_creation_site_info_screen.xml#L133).

### Reproduced
0. Build `feature/master-site-creation` branch.
1. Go to ***Sites*** tab.
2. Tap ***Switch Site*** view.
3. Tap ***Add new site*** action.
4. Tap ***Create WordPress.com site*** item.
5. Tap any site type in list.
6. Notice ***Skip*** button margin.
7. Tap ***Skip*** button margin.
8. Notice ***Skip*** button margin is smaller.

##### Tested
Google Pixel 3 on Android 9.0 with alpha-144

**Comment by oguzkocer** [comment]
This is fixed in #8991.
