### ISSUE TITLE
Font size in preview appearing too large with gutenberg

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#8899]
We have not been able to replicate this issue yet, we have received a report in #1672232-zen from a user who is trying to preview their posts from the WordPress app while using gutenberg on their wpcom simple site and when the preview loads the font size is much larger than normal.
<img src="https://cdn-std.dprcdn.net/files/acc_593859/BUPqs7" />

The user has tested preview and publish from a web browser and the font is appearing the correct size, they are only seeing this larger font in the Android app.

The steps that the user has given us to recreate this issue:
1. in a web browser, on simplesite in the block editor create a new post and enter some text using a standard paragraph block
2. save the post as a draft
3. go to the android app and find that draft post, click on preview

the font should appear larger.

WordPress 11.4
Classic editor on app/gutenberg on site

**Comment by rachelmcr** [comment]
I tested this with the Twenty Nineteen theme and the same content on a test site. I see the same preview as the screenshot above, but I don't see any difference between the preview in the app and the preview in the browser on my phone.

I'm closing this issue as it isn't app-specific — if it can only be reproduced with a specific theme I'd recommend reporting it as a theme bug, or if it's Gutenberg-specific it could be reported to the appropriate Gutenberg repo.
