### ISSUE TITLE
Build error with 'Failed to notify project evaluation listener.'

### ISSUE THREAD

**Issue by 15510101913** [wordpress-mobile/WordPress-Android#8903]
### Actual behavior
I'm according to the Build Instructions step by step to build, but build failed , the error msg is 'Failed to notify project evaluation listener' ; how to fix it ?

**Comment by rachelmcr** [comment]
cc @wordpress-mobile/platform-9

**Comment by 15510101913** [comment]
> Hi @15510101913, thanks for opening this. There are several things that could cause this error. Could you run `./gradlew assembleVanillaDebug --stacktrace` and post the output here? It should give us the detail needed to understand the issue.

**Comment by 15510101913** [comment]
thanks for your answer, my problem has resolved！

**Comment by jtreanor** [comment]
I'm glad to hear you got this sorted. Let us know if you see any more issues 😄
