### ISSUE TITLE
Giphy: Provide a clear error message when network connection is lost while adding GIF

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8907]
### Expected behavior

It would be nice to have a clear network error message throughout the Giphy user flow if I lose my network connection.

### Actual behavior

If I don't have a network connection when I do a Giphy search, I get a clear error message. However, it's less clear if I lose my connection after searching:

1. Search Giphy for a GIF.
2. After search results are loaded, disconnect from internet (or try on a flaky connection).
3. Try to preview the GIF — the result is a generic "Unable to load media" message.
4. Try to add the GIF — the result is a generic "Error downloading the image" message.

We probably need to audit the app for cases like this when the network issue occurs partway through the flow (instead of just the starting state) but I think it's good to keep this kind of case in mind with new features. Not critical for launch, but it'd be nice to handle it.

##### Tested on moto e5 play, Android 8.1.0, WPAndroid alpha-144

cc @shiki @kwonye

**Comment by oguzkocer** [comment]
Fixed in #8916.
