### ISSUE TITLE
[Site Creation] Make sure the .blog subdomains work with new flow

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#8921]
We need to send the full url for .blog subdomains as the `blog_name` while we create a new site. See #8915 for details on how this was fixed in the current site creation flow.

**Comment by malinajirka** [comment]
Will be fixed when #9499 is merged.

**Comment by diegoreymendez** [comment]
@malinajirka, @oguzkocer - I think this can probably be closed since the PR is merged.  Can you confirm?

**Comment by oguzkocer** [comment]
Yes, we can close this, thanks @diegoreymendez!
