### ISSUE TITLE
Local Changes Label Is Not Removed from Page after Discarding Local Changes

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8948]
### Expected
The _**Local changes**_ label on the page in _**Site Pages**_ is removed after discarding local changes for that page in the editor.

### Observed
The _**Local changes**_ label on the page in _**Site Pages**_ is not removed after discarding local changes for that page in the editor.

### Reproduced
0. Select site with at least one published page.
1. Go to ***Sites*** tab.
2. Tap ***Site Pages*** item under ***Publish*** section.
3. Tap page without ***Local changes*** label.
4. Edit page title or content in editor.
5. Enable airplane mode.
6. Tap back arrow to exit editor.
7. Disable airplane mode.
8. Notice page with ***Local changes*** label.
9. Tap page with ***Local changes*** label.
10. Tap ellipsis action in top toolbar of editor.
11. Tap ***Discard Local Changes*** item in menu.
12. Tap back arrow to exit editor.
13. Notice page with ***Local changes*** label.
14. Swipe to refresh pages list.
15. Notice page with ***Local changes*** label.

##### Tested
Google Pixel 3 on Android 9.0 with alpha-145

**Comment by designsimply** [comment]
Closing because the "Discard Local Changes" feature was removed from the editor in https://github.com/wordpress-mobile/WordPress-Android/pull/10127.
