### ISSUE TITLE
Publicize: Remove Google+ option

### ISSUE THREAD

**Issue by niallkennedy** [wordpress-mobile/WordPress-Android#8949]
Google+ APIs will be shut down March 7, 2019 with intermittent failures starting January 28.
https://developers.google.com/+/api-shutdown

Remove Google+ as a service option within Publicize to avoid API failures.

**Comment by rachelmcr** [comment]
Thanks for raising this issue!

Once Google+ is removed from the REST API the apps should no longer show Google+ as a sharing option (similar to when Path was removed last year, https://github.com/wordpress-mobile/WordPress-Android/issues/8320).

@elibud are you ok with just that approach in the apps? Alternately we could show some messaging ahead of time, similar to Calypso. Here's what shows up for Google+ in Calypso right now:

![screenshot 2019-01-14 11 33 45](https://user-images.githubusercontent.com/8658164/51110513-dc78b980-17f0-11e9-85ac-9be6bdae65cf.png)

**Comment by elibud** [comment]
I'm totally fine with that approach, Google+ should've already warned their users. Thanks @rachelmcr

**Comment by rachelmcr** [comment]
Ok, great! I also confirmed that we already hide Google+ as a sharing option for sites that don't already have a connection set up, so the only change will be for users who have a connection now.

Closing this issue as it will be resolved with the REST API change.
