### ISSUE TITLE
Discarding Local Changes don't remove the `Locally Changed` status

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#8957]
As a follow up to #8940 after following the testing steps below, if I go into the editor and `Discard Local Changes` from the `...` menu option, the post is successfully reverted to the published post but the `Local changes` status is not removed and the `Discard Local Changes` option is still enabled. Both issues are probably due to the post still being marked as `isLocallyChanged` in DB. I assume this issue will be resolved with #5984 but I wanted to note this just in case.

```
1. Create a draft while I am online in the app. That'll create the draft in remote.
2. Go offline
3. Make changes to the post and go back. This will save the changes as local draft
4. Go to web or any other client and make changes to the post.
5. Publish the post.
5. now turn airplane mode off on the device and pull to refresh on the Posts list.
6. Observe the post, that was marked with "local changes" doesn't get updated and is still accessible.
```
_Testing steps are pulled from #8940_

**Comment by rachelmcr** [comment]
Does this have the same underlying cause as https://github.com/wordpress-mobile/WordPress-Android/issues/8948 (looks like same issue but for pages vs. posts)?

**Comment by oguzkocer** [comment]
It probably does @rachelmcr, but it's hard to say without investigating it.

**Comment by planarvoid** [comment]
^ ignore this reference, it was a typo in the ticket number

**Comment by hypest** [comment]
Closing this as the menu item is not available anymore (see https://github.com/wordpress-mobile/WordPress-Android/pull/10127).
