### ISSUE TITLE
Preview: Images on private sites are broken in local preview

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8964]
### Expected behavior

I expect a preview (local or remote) to display all images.

### Actual behavior

In local previews, images load correctly for public/hidden sites, but only a broken image for private sites:

![image](https://user-images.githubusercontent.com/8658164/51176788-bbc66780-18b5-11e9-88ad-185b1ce910eb.png)

Seen while testing https://github.com/wordpress-mobile/WordPress-Android/pull/8938.

### Steps to reproduce the behavior

1. Select a WordPress.com Simple site and set it to Private.
2. Start a new post.
3. Add an image to the post. (Wait for it to upload or select an image from the site's media library.)
4. Preview the post. Result: The local draft shows a broken image.
5. Save the draft.
6. From the post list, select "View" to preview the draft. Result: The remote draft loads the image as expected.

**Comment by oguzkocer** [comment]
As [mentioned](https://github.com/wordpress-mobile/WordPress-Android/pull/8938#issuecomment-454064923) in #8938, this issue is also present after saving the post in remote. Same testing steps can be followed to reproduce this issue. Once the draft is saved, if you open the editor, select the `Preview`, the image will be broken. Here is a gif of me going through these steps: https://cloudup.com/cboUsDLlmwi

**Comment by rachelmcr** [comment]
The preview I'm seeing in that gif is still the local preview. As noted in https://github.com/wordpress-mobile/WordPress-Android/issues/4243#issuecomment-425411070 whenever I preview from within the editor I see the local preview.

When I view the remote preview (e.g. by saving the draft and previewing from the posts list) the image loads as expected.

**Comment by rachelmcr** [comment]
Ah, thanks for clarifying! I was thinking about remote preview, not remote posts. It all makes sense to me now and I see the same behavior with both local and remote posts on my end. 👍

**Comment by mzorz** [comment]
Fixed through #9523
