### ISSUE TITLE
Stats: Latest Post Summary strings missing ending punctuation

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8985]
The strings `stats_insights_latest_post_empty`, `stats_insights_latest_post_with_no_engagement`, and `stats_insights_latest_post_message` in the stats refresh are missing ending punctuation. It looks like Calypso stats use an ellipsis, at least for the `stats_insights_latest_post_message` message:

![screenshot 2019-01-16 15 47 47](https://user-images.githubusercontent.com/8658164/51261319-eabd0600-19a7-11e9-8a45-9f735fe7b889.png)

##### Tested on [moto e5 play], Android [8.1.0], WPAndroid alpha-147

**Comment by planarvoid** [comment]
We discussed this with @SylvesterWilmott and we'll use colons instead of ellipsis in the Android app

**Comment by SylvesterWilmott** [comment]
The ellipsis at the end of the string here looks like truncation at first glance. I think we should use a `:` @planarvoid
