### ISSUE TITLE
Notifications: Filter bar layout broken for some non-English languages

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8988]
### Expected behavior

I expect the notifications filter bar to work for all languages, similar to how it works in English:

![screenshot_20190116-175153](https://user-images.githubusercontent.com/8658164/51268258-9588f080-19b7-11e9-8a7a-3fa6138f7081.png)

### Actual behavior

In languages where the filter labels are longer than expected, the filter bar doesn't all fit on-screen and you have to scroll horizontally to view it. I observed this in Spanish and Turkish:

![screenshot_20190116-174539](https://user-images.githubusercontent.com/8658164/51268339-ca954300-19b7-11e9-9ccc-ebb8ce66eae8.png)

![screenshot_20190116-174845](https://user-images.githubusercontent.com/8658164/51268319-c10bdb00-19b7-11e9-87ef-121ff9b9f402.png)

Also, in RTL languages the filter bar isn't organized right-to-left. In addition to an unexpected order, the rounded edges are in the wrong place:

![screenshot_20190116-174650](https://user-images.githubusercontent.com/8658164/51268427-04664980-19b8-11e9-9ecd-6b8366ec3a89.png)

##### Tested on [moto e5 play], Android [8.1.0], WPAndroid alpha-147

**Comment by planarvoid** [comment]
We no longer have the filter bar so I'm closing this issue
