### ISSUE TITLE
My Site - Wrong margins on tablets

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8992]
Margins of menu items in My Site section are broken on tablet.
![screenshot_1547713183](https://user-images.githubusercontent.com/2261188/51304753-42f01880-1a39-11e9-92ed-e332095fe39b.png)

It works as expected in Me section
![screenshot_1547713197](https://user-images.githubusercontent.com/2261188/51304756-44b9dc00-1a39-11e9-8a18-9493e3cf96a8.png)

##### Tested on [device], Android [version]
Emulator Nexus 9

**Comment by khaykov** [comment]
I tested this issue on Nexus 9 emulator and looks like it was resolved in #8801.
