### ISSUE TITLE
Stats - Stats on some websites are missing

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8994]
### Expected behavior
All stats for the website are shown in the app.

### Actual behavior
Some stats are missing in the app.

This log might be related
`E/WordPress-STATS: VisitsAndViewsResponse: data, date & dataPerPeriod fields should never be null`

Refreshed stats - branch `feature/rtl_in_stats`
![stats_refresh](https://user-images.githubusercontent.com/2261188/51310771-ad0fba00-1a47-11e9-9077-f1af8f08c234.gif)

Olds stats - `release/10.9`
![old_stats](https://user-images.githubusercontent.com/2261188/51310772-ad0fba00-1a47-11e9-81ee-8e73c7d1d158.gif)

### Steps to reproduce the behavior
- It works fine on some website 🤷‍♂️ 
1. Open Stats
2. Select for example "Years"
3. Select a year which has some activity on the graph
4. Notice the "Posts and Pages, Clicks etc" blocks are empty

##### Tested on [device], Android [version]
Emulator Pixel 2, Android 9

cc @0nko @planarvoid

**Comment by SiobhyB** [comment]
Another report in 1724025-zen.

I was able to replicate on my Pixel, Android 9.

**Comment by aerych** [comment]
Fixed in #8996
