### ISSUE TITLE
Login: Prologue swipes the wrong way for RTL

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8997]
### Expected behavior

When my device is set to an RTL language, I expect the login prologue to start on the right-most screen, so I swipe right to progress through the screens.

### Actual behavior

Instead, it _looks_ like the login prologue starts on the right-most screen (based on the dots at the top of the screen) but I still have to swipe left to progress through the screens, same as with the LTR layout.

![wpandroid-rtl-prologue](https://user-images.githubusercontent.com/8658164/51320400-93766e80-1a57-11e9-8316-f65236709f46.gif)

**Comment by malinajirka** [comment]
I believe we have the same issue in all ViewPagers in our app. Last time I investigated the issue I found out that Android doesn't natively support RtL ViewPagers. We could create a custom component, but I'm not sure it's worth the effort as it can be really tricky - ViewPager is quite complex component. I have been hoping Google would add support in one of the Support Library updates.
What we might try is force direction of the page indicator so it's not so confusing at least.

**Comment by planarvoid** [comment]
I've tested this issue and it's fixed now with the updated Prologue screen. The view pager starts on the right-most screen and swipes to left.

![Screenshot_1620639892](https://user-images.githubusercontent.com/1079756/117640307-2ede0100-b185-11eb-841d-da767bfd42a9.png)
