### ISSUE TITLE
[Site Creation] Segments - "mobile" attr is being ignored

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8999]
`GET verticals/segments?locale=en_US`

Response contains "mobile" attribute which indicates whether the segment should be displayed on mobile devices. We are currently ignoring this attribute and we show even segments which have `mobile=false`.

**Comment by oguzkocer** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1089 & #9053.
