### ISSUE TITLE
Stats: Display Visitors Over Views in Stats Graph

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#9028]
Some people miss seeing the number of visitors to their sites when viewing the stats graph within the app. The number of visitors used to display in a darker colour against the number of views. This is still the case in Calypso, but not with the refreshed Android stats.

**Comment by SylvesterWilmott** [comment]
@planarvoid Is this possible using our charting library?

**Comment by planarvoid** [comment]
@SylvesterWilmott it should be but I'll need some time to investigate
