### ISSUE TITLE
Gutenberg beta opt-in Dialog

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9031]
This issue explains the opt-in scenarios for Gutenberg (public) Beta rollout.

The wpcom API has been enhanced with an endpoint `/sites/:site/gutenberg` that gives us information on whether the user has opted in/out for Gutenberg on the web and mobile for a specific site (the granularity for opt-in is `per-user/per-site`). We will use this information to understand when to prompt the user with an opt-in dialog.

### Prerequisites

- [x] API docs - the new endpoint to use is `/sites/:site/gutenberg`, see explanation in https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1084
- [ ] API docs for Transform API.
- [ ] opt-in Dialog design - let's try to keep it simple, see flows below to understand where this would fit in (cc @iamthomasbishop )

### Functionality
We should query the API when:
- app comes from background (maybe throttled every n times), so we can have the freshest value each time
- when the user switches to another site in the app (given the information is per-user/per-site).

With these values, we can then perform the following checks and flows when the user tries to write a new Post or, when the user opens an existing Post.

#### For new Posts
- if the current selected site is wp.com or jetpack enabled and has Gutenberg on the web
- if user has already opted either out or in, exit flow and let the right Editor show up.
- else if user hasn't answered on any platform yet (have yet to check the API docs on this), offer opt-in on mobile.
- else if user opted in on web, hasn't yet answered on mobile: offer opt-in on mobile.
- else if user opted out (actively) on the web: automatically opt-out on mobile (that means, changing their setting to Aztec) and show Aztec.

#### For existing Posts
- if the current selected site is wp.com or jetpack enabled and has Gutenberg on the web
- if user has already opted in, check if the Post contains GB blocks. Open with GB if yes, or use the Transform API to transform to GB and open GB if not (see https://github.com/Automattic/wp-calypso/pull/29790).
- else if user has opted out, check if the Post contains GB blocks. if YES: show Aztec compatibility dialog warning (currently existing in the apps). If not, just open Aztec as usual. (This is all currently implemented behavior for Aztec)
- else if user hasn't answered on mobile, check if the Post contains GB blocks. If YES: show opt-in dialog. If No: open Aztec.

#### For .org users
Simply check local setting (Use Gutenberg enabled/disabled), and:
- use Aztec for all posts if not enabled (showing current Aztec compatibility warning dialog)
- use Gutenberg for new posts if enabled
- _TBD see if we can use the transform API in isolation for org users in the case of having Gutenberg enabled and attempting to open an old Post._

**Comment by daniloercoli** [comment]
Closing this issue since it's already outdated. We're going to open new ones with the plans for v13.0.
