### ISSUE TITLE
Gutenberg early beta (part 1) informative Dialog

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9034]
For the early beta of Gutenberg mobile:

- if the user opens existing GB post: instead of showing an opt-in dialog, we'll still go ahead and open -mobile Gutenberg (as it's likely to be less issue-prone for GB posts than Aztec) and show an informative dialog explaining them about the new Editor and where they can switch back to classic. Then open Gutenberg on "ok". We won't show this dialog but once.
- if the user opens a non-GB post, then show in Aztec. We then wouldn't need to use the opt-in API at this stage.
- for new Posts, we'd still have Aztec in the first half of the beta, and we may add an opt-in dialog by the half of the phase

####  ToDo
- [ ] need dialog design
- [ ] need dialog copy
- [ ] tracks?

**Comment by iamthomasbishop** [comment]
For sake of getting something up for discussion, I've put together some rough Blueprints to help give some context and hopefully make copy writing a little easier. Some context, goals:

* In this scenario, the user has already been using Gutenberg on the specific post they're opening in the app
* This is less of an "opt-in" and more of an acknowledgement that we've enabled Gutenberg for this post 

The goals here are to:

* Show a quick acknowledgement to users who are already using the Block Editor, _once_ and get out of the way
* Provide clear messaging/actions/paths to – acknowledge, learn more, and explain the path to revert to Aztec
* For the sake of shipping something quickly, focus on the basics, copy. Next iteration could contain an illustration, but I don't necessarily want it to feel like an "announcement".

Here's what I'm imagining, based on what @mzorz proposed recently.

![mobile gutenberg beta opt-in - gb post - android i1](https://user-images.githubusercontent.com/1200432/52012133-67b7a780-249f-11e9-8948-e0bbb434ad78.jpg)

I'd love to hear any feedback, especially from @mzorz @rachelmcr @hypest and @koke 

--------

[Companion iOS issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10869)

**Comment by koke** [comment]
This looks good to me, I'm wondering what would you expect to have in the learn more page? I'm trying to avoid the same mistake we did with the Aztec compatibility alert, where we ended up linking to the default Gutenberg support page because we didn't plan for anything mobile specific.

In this case, users encountering this alert are already aware of the block editor. What else do we want to say to them that it's not covered by the alert?

**Comment by iamthomasbishop** [comment]
> In this case, users encountering this alert are already aware of the block editor. What else do we want to say to them that it's not covered by the alert?

That's a good question. I thought there had been some discussion previously about pointing to an informational page. If we don't have/need it, then let's update the dialog actions to remove the `learn more` action. I'm on the fence about the `get started` action, I wonder if a simple `ok` to acknowledge would be sufficient.

**Comment by mzorz** [comment]
> I wonder if a simple ok to acknowledge would be sufficient.

I think the OK button enforces the idea that there is nothing else to do, for an informative dialog it gives a sense of "end of message" which is really all we want to convey in this very dialog (a kind of FYI and nothing else), so "OK" should probably do the job IMO, does that make sense?

**Comment by iamthomasbishop** [comment]
Works for me! I'll update the blueprint in another comment below for transparency, but for the sake of moving this along feel free to :shipit: if we're in agreement !

**Comment by rachelmcr** [comment]
This dialog with an OK button sounds good to me, too.

The only case I'm wondering about here is what will happen if a user wants to force Aztec for all posts in the app. Although we aren't doing an opt-in, would it make sense to offer an opt-out during the beta period that applies across the board, or are we ok with having those users manually switch to Classic each time they open a Gutenberg post in the app?

**Comment by koke** [comment]
> It may not be obvious to beta users that this is something they're only seeing because they are part of the beta program

To clarify, this won't be just for beta testers, all builds are getting this in 11.9

**Comment by diegoreymendez** [comment]
@iamthomasbishop - Is the design still being worked on?

This is a ticket where figuring out what we want to show exactly before getting started makes the most sense, as we'd need to resolve what component to use for the dialog.  We could re-use existing components (as the one pointed by @rachelmcr) or use the plain alert dialog from the OS depending on what we want.

**Comment by diegoreymendez** [comment]
In the designs you show above, I think a regular dialog would do.

**Comment by iamthomasbishop** [comment]
@diegoreymendez A normal Alert would work, agreed.

**Comment by daniloercoli** [comment]
Addressed in #9234
