### ISSUE TITLE
Gutenberg early Beta (part 2) informative/opt-in Dialog

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9035]
When an user opens the new version of the app, the app will check whether the user has already opted in to Gutenberg or not by using the API
(see https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1084 and https://github.com/wordpress-mobile/WordPress-iOS/issues/10870). If they are already using Gutenberg for the given site, this new Dialog will be shown with the announcement. 

The flow would be as follows
1. the user opens the app for first time or makes a site switch
2. we check the opt-in API to see if the user has already made a choice about using Gutenberg for this site.
3. If they have, we show the announcement Dialog
4. The opt-in Dialog says something along the lines of "Do you want to try Gutenberg mobile on this site?"
5. It could be nice to have this opt-in show first time along with a checkbox that says  `[ ] enable Gutenberg for all my sites`, so we don't keep asking each time they switch sites.
6. whatever the choice is, it needs to be saved through the API as well.

#### ToDo
- [ ] needs this first https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1084
- [ ] needs design
- [ ] needs copy

**Comment by daniloercoli** [comment]
Closing this issue since it's already outdated. We're going to open new ones with the plans for v13.0.
