### ISSUE TITLE
Gutenberg - add switch to come back/from Aztec

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9037]
Comes from https://github.com/wordpress-mobile/WordPress-iOS/pull/10565 and https://github.com/wordpress-mobile/WordPress-Android/issues/8684#issuecomment-443324495

Originally was intended to ship with https://github.com/wordpress-mobile/WordPress-Android/pull/8695#issuecomment-443149824 but never did.

#### ToDo
(copied from https://github.com/wordpress-mobile/WordPress-Android/issues/8684#issuecomment-443324495)
This is the logic we use to allow the user to switch between editors in iOS:

- If Gutenberg is enabled:
  - When in Aztec:
    - Show the option to switch to Gutenberg only if the post has blocks or is empty.
  - When in Gutenberg:
    - Show the option to switch to Aztec for all posts.
- If Gutenberg is not enabled:
  - Don't show the option

**Comment by mzorz** [comment]
Relevant iOS PR so we have as a reference of behavior: https://github.com/wordpress-mobile/WordPress-iOS/pull/10565

**Comment by hypest** [comment]
@marecar3 is AFK these days so, assigning this to me and we ca re-assign if we like.

**Comment by hypest** [comment]
Latest iteration on this issue is this flow:

* Gutenberg is always available
* When in Aztec, show the option to switch to Gutenberg only if the post has blocks or is empty
* When in Gutenberg, show the option to switch to Aztec for all posts
