### ISSUE TITLE
[Site Creation] Switch to the new site creation flow and remove unused code

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9045]
Remove all classes and resources related to the old site creation flow and switch to the new flow.

**Comment by oguzkocer** [comment]
Fixed in #9046 & #9048.

**Comment by malinajirka** [comment]
Reopening: #9048 was reverted in #9104

**Comment by diegoreymendez** [comment]
Moving this to the Site Creation Improvements project, in order to wrap up the original Site Creation Project.
