### ISSUE TITLE
[Site Creation] Remove the "New" prefix from Site Creation Classes & Resources

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9051]
We have been using the `New` prefix in the new site creation flow so it doesn't conflict with the old one. With #9048 we are removing the old site creation flow, but @malinajirka and I have decided to keep the `New` prefix for 1 release. This will make it easier to revert the changes in #9048 if the need arises.

cc @kwonye

**Comment by kwonye** [comment]
Thanks for the context. Let's make sure this gets done for the release after we release if the new site creation flow doesn't totally blow up!

**Comment by oguzkocer** [comment]
> Thanks for the context. Let's make sure this gets done for the release after we release if the new site creation flow doesn't totally blow up!

Agreed, I've added the `11.8` milestone and also added the ticket to our project, so hopefully we won't miss it 🤞

**Comment by diegoreymendez** [comment]
Moving this issue to the Site Creation Improvements project so I can close the old board.
