### ISSUE TITLE
[Stats Refresh] Switch DWMY overview card date bar for title bar

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#9060]
As part of stats improvements: remove the date bar on DWMY overview card and add title bar using the title `Traffic`. Date will be moved to a dedicated bar in another ticket.

![title_bar](https://user-images.githubusercontent.com/36532468/51604170-d925b200-1f03-11e9-8ca9-4a402f07104e.png)

**Comment by planarvoid** [comment]
this is no longer required @SylvesterWilmott
