### ISSUE TITLE
[Stats Refresh] Add full number section to DWMY overview block

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#9067]
As part of stats improvements: add full number section to DWMY overview block. This section should show a label which changes depending on which overview tab is selected and large numbers should not be shortened

![full_number](https://user-images.githubusercontent.com/36532468/51605174-315db380-1f06-11e9-80c2-3c9889aba622.png)

**Comment by annacmc** [comment]
Received a user request for displaying full numbers for large stats numbers at #1948147-zen

>Could you please update the stats page to show in whole numbers? It's really annoying to track progress on the go when the number is cropped to 231k

**Comment by SylvesterWilmott** [comment]
Thanks for reporting that @annacmc 

@planarvoid I think we have the space to add another digit before it shortens. What do you think?

**Comment by planarvoid** [comment]
I think so too @SylvesterWilmott
