### ISSUE TITLE
Add wpcom Authorization Header to XML-RPC requests

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#911]
Add the wpcom Authorization Header to XML-RPC requests (when needed), and get rid of password.

I had already implemented this here https://github.com/wordpress-mobile/WordPress-Android/commit/bdb50be7d368e94ae2569babc4e89e62b472ab47 
but it did not make the cut for 2.6.1 (We can reuse that code though). 

Keep the following things in consideration:
- username/password are still used in a lot of place. Ex: AuthenticatedWebViewActivity, ReaderAuthActions (search for WordPress.WPCOM_PASSWORD_PREFERENCE).
We should switch those calls to the OAuth Header.
- The backend first check the Authentication Header, if available it will use it for authentication purpose, completely ignoring the username/password available within the XML-RPC request document.  
- ^ I think we can even skip the storage of password in the app when the bullets above are completed.

Related: https://github.com/wordpress-mobile/WordPress-Android/issues/851

**Comment by maxme** [comment]
Fixed in 0a563257354fdd4eb14af3cd2433a00b7d2d0804
