### ISSUE TITLE
Pages: Viewing/previewing a page only shows local preview

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#9122]
### Expected behavior

If a page doesn't have local changes (all changes are synced to remote) I expect to be able to view/preview the remote version of the page, as it looks on my site.

### Actual behavior

When I view/preview a page, I only ever see the local preview.

### Steps to reproduce the behavior

1. Open My Sites > Site Pages.
2. Go to the Published filter and find a page with no local changes.
3. Tap the ellipsis menu next to the page and select "View."

Result: You see the local preview and not the remote version of the published page.

![screenshot_20190125-140141](https://user-images.githubusercontent.com/8658164/51750399-e381b080-20a9-11e9-89b7-abbb20bdad8f.png)

**Comment by maxme** [comment]
> If a page doesn't have local changes (all changes are synced to remote) I expect to be able to view/preview the remote version of the page, as it looks on my site.

Now that we have remote previews for post with local changes, we can go a bit farther with the following:

> I expect to be able to view/preview the remote version of the page whatever it's status (local changes, draft, etc), as it looks on my site.
