### ISSUE TITLE
Stats: Views and Comments label going off the screen

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#9128]
### Expected behavior

Labels not going off the screen.

### Actual behavior

A user reported this. 

> Since the last update my statistics page is not completely legible and it is bothering me. The text and numbers are cut off and the statistics widget isn't loading any numbers at all.

![](https://woothemes.zendesk.com/attachments/token/3e6wBlFlujEr3J9hAVUEsXVL9/?name=Screenshot_20190124-104515_WordPress.jpg)

I couldn't reproduce this by just increasing the device's font size so it may be related to the language? 

### Device Info

WordPress - 11.5.2 - Version code: 667
Android device name: Samsung SM-A520F
Country Code: NL

**Comment by rachelmcr** [comment]
Thanks for the report! This is language specific — it was also reported in https://github.com/wordpress-mobile/WordPress-Android/issues/8986 and fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9024, so the user will get that fix in 11.7.
