### ISSUE TITLE
Stats pages displaying the wrong day when accessed from the country section

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#9130]
I came across this problem while working on this issue 1733185-zen.

When you are viewing the new stats section on the days window, if you pick a different day other than what ever today's date is, and then scroll down to the countries section the information will still be up to date.  However if you tap on the view more link for the countries section to view it in more details the date reverts back to today's date automatically.  

You can see this behavior in this video https://www.youtube.com/watch?v=a99aX4uXHr0&feature=youtu.be

Steps:
1. Go to the new stats section > Day > A day that is not today.
2. Scroll down countries and select the View More button.
3. The day at the top will say the wrong day and the stats will be displaying today.

Tested on Android 5.5
WordPress alpha 150

**Comment by rezzap** [comment]
A user has reported a similar behavior for the referrer section of the day window view in 1749224-zen.

1. Go to new stats section > Day > A day that is not today.
2. Scroll down to referer section and click the 'View More' button.
3. The day at the top will say the wrong day and the stats will be displaying today's stats.

**Comment by SiobhyB** [comment]
@planarvoid mentioned that this is going to be fixed in version 11.7 of the app. Can this be closed?

**Comment by rachelmcr** [comment]
Closing as this will be resolved with the 11.7 release.
