### ISSUE TITLE
gradlew compile  failed

### ISSUE THREAD

**Issue by vinout** [wordpress-mobile/WordPress-Android#9134]
H:\android\wordpress\WordPress-Android>gradlew installVanillaDebug

> Configure project :WordPress
WARNING: You're using the example google-services.json file. Google login will fail.
WARNING: You're using the example google-services.json file. Google login will fail.
Could not find google-services.json while looking in [src/wasabi/debug, src/debug/wasabi, src/wasabi, src/debug, src/wasabiDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/wasabi/release, src/release/wasabi, src/wasabi, src/release, src/wasabiRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/zalpha/debug, src/debug/zalpha, src/zalpha, src/debug, src/zalphaDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/zalpha/release, src/release/zalpha, src/zalpha, src/release, src/zalphaRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/vanilla/debug, src/debug/vanilla, src/vanilla, src/debug, src/vanillaDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/vanilla/release, src/release/vanilla, src/vanilla, src/release, src/vanillaRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :WordPress:downloadJSBundle
Downloading JS bundle from https://s3-us-west-1.amazonaws.com/gutenberg-mobile-js-bundle/wordpress-mobile/gutenberg-mobile/2c4cff2784c9b0589b9325292b2f284ce54a3dfd/android/App.js

> Task :WordPress:downloadJSBundle FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'H:\android\wordpress\WordPress-Android\WordPress\gutenberg-tasks.gradle' line: 24

* What went wrong:
Execution failed for task ':WordPress:downloadJSBundle'.
> java.net.ConnectException: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 29s
1 actionable task: 1 executed

H:\android\wordpress\WordPress-Android>

**Comment by jtreanor** [comment]
@vinout Thanks for opening this!

Are you still having trouble running `./gradlew installVanillaDebug`? It looks like there may have been a temporary problem accessing Amazon S3 during the task.

**Comment by jtreanor** [comment]
@vinout Feel free to reply here if you are still having this issue.
