### ISSUE TITLE
[Site Creation] Infinite progress indicator

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9138]
NewSiteCreationService can enter an invalid state when it can't be started, but the UI is showing a progress indicator - since the back button is suppressed the only way out is to kill the app. 

### Steps to reproduce the behavior
1. Start the new site creation flow
2. Select a segment
3. Skip
4. Skip
5. Type any domain
6. Turn on the flight mode
7. Select a domain
8. Create Site
9. Turn off the airplane mode
10. Retry
-> Notice the progress indicator is infinite

cc @SylvesterWilmott This is the type of bug I was afraid of. Since the user can't exit the flow with the back button, the only way out is to kill the app. Showing a warning dialog when the user presses the back button would be safer. Don't you want to reconsider?

**Comment by malinajirka** [comment]
This is happening because the `NewSiteCreationPreviewFragment` binds to the service in `onResume` -> the service is created, but not started -> the default state after creation is `IDLE`, but [this](https://github.com/wordpress-mobile/WordPress-Android/blob/ce978083e48580afb82dcfadf6db91f1ee3673b5/WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/NewSiteCreationService.kt#L101) line prevents the service from actually starting the task. 

When the internet connection is available the service is manually started from the ViewModel before onResume is executed, hence it works as expected.

**Comment by malinajirka** [comment]
The issue was introduced in #9101.

**Comment by SylvesterWilmott** [comment]
>since the back button is suppressed the only way out is to kill the app.

@malinajirka Yeah this is not great if you drop your connection.

>Showing a warning dialog when the user presses the back button would be safer. Don't you want to reconsider?

I agree, I think this is the best way to address this.

<img width="480" alt="screenshot 2019-01-30 at 10 40 12" src="https://user-images.githubusercontent.com/36532468/51975956-72f8dc00-247b-11e9-8a3a-cee6de912bc4.png">

**Comment by malinajirka** [comment]
@SylvesterWilmott Just to make sure we are on the same page. This behavior is not expected even when you drop your connection. It can happen only due to a bug. However, I feel it's a bit risky to assume there won't be any bugs.

**Comment by SylvesterWilmott** [comment]
@malinajirka Thanks for the clarification. Let's proceed with the warning dialog above.

**Comment by malinajirka** [comment]
I've created an issue #9157
