### ISSUE TITLE
Upload progress updates not working on Post list

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9145]
### Expected behavior
When you start a draft and insert an image, then tap back, the image uploads in the background. If you go to the Posts list, an indicator of upload progress is shown on the post card.

### Actual behavior
The upload progress indicator on the Post card in the Posts list is not updated as the upload progresses.

### Steps to reproduce the behavior
1.  go to the Posts list
2. start a new draft
3. insert one image (better to insert something big so you get a chance to wait for the upload to progress, or insert multiple images)
4. tap back to get to the Posts list again
5. scroll up a bit to check the new draft in the list
6. observe the upload progress indicator is not being updated (if you see the foreground notification you'll see it's updated correctly)

**Comment by oguzkocer** [comment]
We can try to look into this as part of the post filters project. It sounds like all we need to do is invalidate the post list when the upload status of a post is changed. I thought we were already doing this, but maybe the FluxC event for it is not being triggered or there is another event that we need to observe. Either case, this should be an easy fix 🤞

**Comment by malinajirka** [comment]
We've replaced the determinate progress bar with indeterminate one during the post filters project. However, the source of this issue was fixed in #9600.

**Comment by mzorz** [comment]
Hi there @malinajirka 👋 

> We've replaced the determinate progress bar with indeterminate one during the post filters project. However, the source of this issue was fixed in #9600.

I don't know the details but, just tested this on latest `feature/master-post-filters` branch and I observed that first time I tried (choosing an image already on the device), the indeterminate progress bar didn't appear. It did the second time I tried though (choosing to take a photo on the spot).
Tried several times and it worked 100% of the times when taking a picture on the spot, and 0% of the times when choosing an image that was already on the device.

Steps to reproduce (A):
(using Aztec)
1. go to the Posts list and tap on the DRAFTS filter tab.
2. start a new draft
3. insert one image from the device (just tap on the cross on the toolbar and pick one of the images shown)
4. tap back to get to the Posts list again
5. scroll up a bit to check the new draft in the list
6. observe there is no upload progress indicator (if you see the foreground notification you'll see it's updated correctly). The progress bar only appears when the Post starts to get uploaded, but not while Media is uploading.

Also (B), once it finishes, the Post disappears from the list, and you have to scroll up to  "discover" it again.

Video here https://cloudup.com/c9XNSQLrS8m

What do you think, should we re-open this one (A) and open a new one for (B) or leave this one closed and open new, separate issues for A and B?

Also wondering, why did we get back to an indeterminate progress bar when we used to have the fine grained information to tell the user actual progress? Without further information, the change itself seems like a step back, but I'm sure I'm missing information. Any pointers to discussions / clarifications welcome 🙇

**Comment by oguzkocer** [comment]
> Also (B), once it finishes, the Post disappears from the list, and you have to scroll up to "discover" it again.

This is the same issue as #9146 and we are waiting @SylvesterWilmott's input on it.

> What do you think, should we re-open this one (A) and open a new one for (B) or leave this one closed and open new, separate issues for A and B?

@malinajirka Once you reproduce the issue, can you please open a new issue for this in the Android Post List Improvements project?

> Also wondering, why did we get back to an indeterminate progress bar when we used to have the fine grained information to tell the user actual progress?

I believe it was a design change, but @malinajirka would know better. If it wasn't a planned change or we decide to revert the change, let's open a separate issue for this one as well.

**Comment by malinajirka** [comment]
Thanks @mzorz ! 

>Also wondering, why did we get back to an indeterminate progress bar when we used to have the fine grained information to tell the user actual progress?

This was probably just my misunderstanding between me and Sylvester. I'm planning to discuss it with him during the design review which we are planning to do before we merge the branch into develop. We might end up fixing it before the merge or creating an issue.

>What do you think, should we re-open this one (A) and open a new one for (B) or leave this one closed and open new, separate issues for A and B?

I'll take a look at it tomorrow and probably create a new issue.

**Comment by mzorz** [comment]
Thanks for the quick return @malinajirka ! 🙇
