### ISSUE TITLE
Posts list: floating action button doesn't move when snackbars appear

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9147]
### Expected behavior
The FAB for starting a new draft should move up as the snackbars appear

### Actual behavior
The FAB for starting a new draft does not move and lies hidden behind the snackbar

### Steps to reproduce the behavior
1. go to Post list
2. start a new draft, write something
3. tap BACK
4. observe the snackbar appears but the FAB doesn't move.

Same happens when trashing a post from within the Posts list
1. go to posts list
2. tap TRASH on one of the posts
3. hit ok
4. the snackbar appears but the FAB doesn't move

**Comment by malinajirka** [comment]
Fixed in #9180. We'll be merge into develop along with first iteration of the [Post filters project.](https://github.com/orgs/wordpress-mobile/projects/23)
