### ISSUE TITLE
Gutenberg state lost when Activity killed

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9148]
### Expected behavior
Content shouldn't be lost even if the system chooses to kill the Editor Activity while it's open but in the background

### Actual behavior
if `Don't keep activities` is turned ON, and you open the Gutenberg editor and type something in it, then send the app to the background and bring it back to the foreground, the editor appears empty (the content is not saved / re-populated).

### Steps to reproduce the behavior
1. set `Don't keep activities` ON and choose to use Gutenberg in App Settings within WPAndroid/Me tab.
2. start a new draft
3. type something
4. send the app to the background (i.e. tap the HOME button of the device)
5. bring it back to the foreground
6. observe the Editor shows empty now

**Comment by hypest** [comment]
> 3. type something

Just checking, does that mean the title is empty? Maybe this is related to #9153 ? Can you re-check @mzorz if possible? Like, can you try again but with setting the title and the content in step 3?

**Comment by mzorz** [comment]
@hypest I'm currently testing the fix in #9153 and I can confirm the steps described in this one (#9148) still happen there as well

**Comment by mzorz** [comment]
For the record: tested the steps described here on Aztec and couldn't reproduce there.

**Comment by hypest** [comment]
[Agreed](https://github.com/wordpress-mobile/WordPress-Android/pull/9030#issuecomment-458920250) to try handle it as part of #9030.

**Comment by hypest** [comment]
Already fixed.
