### ISSUE TITLE
Editor: Media image upload and publish error even though upload was successful

### ISSUE THREAD

**Issue by rickmgithub** [wordpress-mobile/WordPress-Android#9159]
### Expected behavior
For the media image to upload and publish without reporting an error

### Actual behavior
Post and included image uploads correctly but still produces an error on the device saying file not uploaded.

### Steps to reproduce the behavior
STEPS TO REPRODUCE BEHAVIOUR
1) I set myself up as a beta tester on the Android app Beta 11.6
2) I used ricksstoretestsite.home.blog as the test platform.
3) I first tried uploading an image to the page titled "test 4". (https://ricksstoretestsite.home.blog/test-4/)
4) The image uploaded to the page. 
5) Clicked update
6) In the device notifications, it showed the scrolling upload arrow icon but then produced an error triangle next to it with the message "Upload failed". 
When I pulled down the notifications tab this is what it showed - Screenshot here - https://screenpresso.com/=LwGrd
7) When I went back into the same page on the device the image appeared to be there correctly published.
8) To double check, I loaded the same page on my desktop computer and the page appeared with the image correctly as well. 
9) To test this further, I tried the same steps on a post rather than a page to see if it made any difference. The post is called "Test post img" (https://ricksstoretestsite.home.blog/2019/01/30/test-post-img/)
10) I uploaded the same image and published it again getting the same error.
11) I checked again on my desktop and the post was there.
12) I tried a few more tests on the same pages but it produced the same results as above.

##### Tested on [device], Android [version]
Samsung S9 with Android 8.0.0

**Comment by rachelmcr** [comment]
@rickmgithub Does this happen on every site you test with, or only on this one? I haven't been able to reproduce the issue so I'm trying to narrow down possible factors that could cause this to occur.

**Comment by nusagates** [comment]
I am facing this issue too on my blog nusagates.com and budairi.web.id

**Comment by mzorz** [comment]
Closing via #9423
