### ISSUE TITLE
Custom Post Type Views Don't Display in "Posts and Pages" Module

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#9167]
### Expected behavior

I expected for views for any posts or pages to display in the "Posts and Pages" module under Stats. This expectation includes custom post types, like portfolio projects or product pages. This matches up to the behaviour I see in the Stats section in Calypso.

### Actual behavior

In 1768568-zen, a user reported that views in the "Posts and Pages" module didn't add up to their site's total views. I noticed that the missing pages from that module were all product pages created by the WooCommerce plugin.

I was able to replicate the issue by visiting both a "normal" page and a portfolio page on my test site.

You can see that my views to both the normal page, **About St. John’s College**, and the portfolio page, **Green Gold**,  display correctly in Calypso:
 
<img width="367" alt="screenshot 2019-02-02 at 11 36 40" src="https://user-images.githubusercontent.com/2998162/52163771-ffef9f80-26de-11e9-9905-284b6ef30df9.png">

The views for the portfolio page, **Green Gold**, are missing from the "Posts and Pages" module in the app:

![screenshot_20190202-113530](https://user-images.githubusercontent.com/2998162/52163786-6c6a9e80-26df-11e9-827d-e581da76c37c.png)

### Steps to reproduce the behavior

1. Publish both pages and custom post types, such as portfolio items, to a test site.
2. View both the pages and custom post types. Make sure you're viewing from an incognito browser or while logged out, so that the views are counted by our stats system.
3. Confirm that the views are displaying correctly in the "Posts and Pages" module in Calypso.
4. Confirm that the views for the custom post types are missing from the "Posts and Pages" module in the app. You can double check the total view count to be sure that the views to the custom post types have been registered.

##### Tested on Pixel, alpha-150, Android 9

**Comment by charliescheer** [comment]
Another report  #1973665-zen

From web browser
<img src="https://user-images.githubusercontent.com/1119271/56618201-153de100-65df-11e9-970d-e97fba4f266e.png">

from wpAndroid
<img src="https://user-images.githubusercontent.com/1119271/56618164-fc353000-65de-11e9-8cf4-ca2387a0a520.png">

I looked into one of my sites and I was able to replicate this problem in alpha 162 - Android 5.1.1
