### ISSUE TITLE
Missing Border for Personal Plan's Image

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#9169]
### Expected behavior

I expected the styling for images above the descriptions for each plan to be consistent. 

For the Premium plan, you can see the image is in a circle with a white border:

![screenshot_20190202-202627](https://user-images.githubusercontent.com/2998162/52209117-cc497c80-287a-11e9-825f-066ed7c2674e.png)

### Actual behavior

The image for the Personal plan is missing a white border:

![screenshot_20190202-202621](https://user-images.githubusercontent.com/2998162/52209129-d4092100-287a-11e9-9ca6-649a7fa652f7.png)

This was reported to us in 1763907-zen.

### Steps to reproduce the behavior

1. Navigate to My Site > Plans.
2. Switch between the different plans to see the difference in the image for WordPress.com Personal.

##### Tested on Pixel, Android 9

**Comment by rachelmcr** [comment]
@khaykov Is it worth keeping this issue open or will this be addressed as part of the Plans v2 work (https://github.com/wordpress-mobile/WordPress-Android/issues/9108)?
