### ISSUE TITLE
[Gutenberg] Rotation issues left to tackle

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#9177]
#9030 was merged but a couple of things need to be taken care of still on rotation:

1. Title loses focus (if it was focused before anyway). This will get fixed "automatically" when https://github.com/wordpress-mobile/gutenberg-mobile/pull/513 gets merged and included.
2. ~Scroll position is lost~ When an input field has focus and we rotate, the list doesn't auto-scroll to keep it in the viewport.

**Comment by antonis** [comment]
Closing the issue since I wasn't able to reproduce it with the latest version of the app (22.5) 🎉
