### ISSUE TITLE
Restore Trashed Post Action

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9181]
Once we add the post filters, we'll update the UI to have a `Restore Post` action. With this issue, we'll tackle the implementation of that action. `RESTORE_POST` `PostAction` has been added in this FluxC PR: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/985

**Comment by malinajirka** [comment]
I thought I'd just add the restore action and everything else would be handled automagically, but it's not the case. 

- There seems to be a couple of issues with the way post changes are being propagated - after I restore a post it still has "postStatus = trashed" even though it's being displayed in Published tab -> the result is the post list button actions don't match the actions for Published section.
- I need to manually pull to refresh the post after trash/restore actions (invalidating the data doesn't seem to help) + sometimes a trashed post appears in the trashed tab, but disappears after 0.1s and reappears after another PTR

I think it makes more sense to look into it when the Post List grand refactoring is merged https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1193

cc @oguzkocer

**Comment by malinajirka** [comment]
Ohh, :head-bang: I haven't realized this https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1008 isn't implemented yet. It'll definitely solve some of the issues.

**Comment by oguzkocer** [comment]
Yeap, and the restore action is not very well tested yet. We have the action, but there might be issues with it. I can work on the trashing/restoring after the refactor is done.

**Comment by oguzkocer** [comment]
Implemented in #9588.
