### ISSUE TITLE
Add support for toggling post list UI

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9184]
We'd like to add support to toggle between two different layouts for the post list rows. The current design, card layout will be one of them. We'll implement a shorter version as can be seen in this tentative design: https://cloudup.com/cBtFWQBCvZr. Note that these designs might change before this issue is tackled.

**Comment by malinajirka** [comment]
Current design for the toggle 
<img width="703" alt="Screenshot 2019-04-15 at 07 59 54" src="https://user-images.githubusercontent.com/2261188/56111582-c944c980-5f58-11e9-966f-e06e4fbceede.png">
Note: The design for the author filter is a bit out-of-date. But it doesn't matter for this task.

**Comment by malinajirka** [comment]
Here are the sources of the icons:
https://github.com/Automattic/gridicons/blob/master/svg-min/gridicons-list-unordered.svg
https://material.io/tools/icons/static/icons/baseline-view_day-24px.svg

**Comment by malinajirka** [comment]
The feature has been merged into a working branch - `feature/post-filters-compat-view-toggle`
