### ISSUE TITLE
Navigation bar is missing after image is changed while app is in Landscape orientation

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/WordPress-Android#9199]
### Steps to reproduce the behavior
1. Enable Gutengerg
2. Open New Post
3. Insert image block
4. Choose an image from the WordPress library
5. Rotate the device (Landscape)
6. Click on the edit button from Formatting Toolbar
7. Choose some image from WordPress library

### Expected behavior

Navigation Bar should be presented

### Actual behavior

Navigation Bar is missing 

##### Tested on [device], Android [version]
Nexus 5x, 8.0
WPAndroid version alpha-150

**Comment by hypest** [comment]
Adding some findings, this is currently "implemented" by some borrowed logic from the Aztec fragment. See [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java#L319-L327).

What's not working OK is the logic to re-show the appbar when touching on the UI. See [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java#L319-L327).

In any case, I'd say this is not a blocker for the v0.3.5 release of Gutenberg-mobile.

**Comment by daniloercoli** [comment]
Addressed in #9311
