### ISSUE TITLE
Handle site change and scroll to target post on PostList

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9225]
Fix following issues:
- Commit [94c2afa](https://github.com/wordpress-mobile/WordPress-Android/commit/94c2afad9fca1c23bb0363ce8b2d5eba612c0113) and [1ea1da9](https://github.com/wordpress-mobile/WordPress-Android/commit/1ea1da9e665262f2a64ced5b806350762bf82d5a) removed support for opening Post List screen on a target post.

- Commit [94c2afa](https://github.com/wordpress-mobile/WordPress-Android/commit/94c2afad9fca1c23bb0363ce8b2d5eba612c0113) removed code which handled situation when the current site has changed. (I assume it can happen when we open the PostListFragment from an outdated notification).

**Comment by malinajirka** [comment]
I think there is a bug in `PostListFragment`

We try to get the `targetPostId` in `onViewCreated` with `nonNullActivity.intent?.getIntExtra(...)`, however the `targetPostId` is actually in Fragment's `Argument`, so it should be retrieve with `requireNotNull(arguments).getInt(...)`.

**Comment by oguzkocer** [comment]
Fixed in #9301.
