### ISSUE TITLE
Browse without registration ?

### ISSUE THREAD

**Issue by pharma-vie** [wordpress-mobile/WordPress-Android#9231]
So as not to tire without interest
Can I get a visitor to browse my site without registering?
He only registers if he wants to place replies or showers.

**Comment by designsimply** [comment]
Correct. A visitor may browse a publicly available available site via the WordPress Android app by going to Reader (2nd icon in the bottom navigation) > gear icon (near top right) > Followed Sites and then entering the URL to follow in the field at the bottom.
