### ISSUE TITLE
Feature Request: Allow creation of new Pages from “New Post” button

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9235]
### Feature Request

An Android user wrote in to make a suggestion. They’d like to be able to tap the “New Post” button (between “Reader” and “Me”) and select from a new Post or a new Page.

Is this something we would want to change?

![screenshot_2019-02-10-20-47-04-1](https://user-images.githubusercontent.com/1119271/52733697-94c88780-2f80-11e9-9bfe-b4566e1d564a.jpeg)

/hat tip @thehenrybyrd for the original report (internal reference: p4a5px-2lo-p2 by way of 1792187-zen).

For comparison, WordPress gives multiple options (Post, Media, Page, User) when you tap "+ New" in the main toolbar:

![screen shot 2019-02-13 at 11 16 39 am](https://user-images.githubusercontent.com/1119271/52734107-9e9eba80-2f81-11e9-9fb5-f1f70b725ef3.png)
<sup>Seen at testingallthetime.com running WordPress 5.0.3 and no active plugins tested with Safari 12.0.3 on macOS 10.13.6.</sup>

And WordPress.com does not give multiple options, clicking "+ Write" in the main toolbar starts a new post:

![screen shot 2019-02-13 at 11 16 36 am](https://user-images.githubusercontent.com/1119271/52734218-e1609280-2f81-11e9-813f-6f6c1c4ca312.png)
<sup>Seen at cute.wordpress.com on WordPress.com tested with with Safari 12.0.3 on macOS 10.13.6.</sup>

**Comment by kosmasdimitropoulos** [comment]
I would like to try solve this issue

**Comment by designsimply** [comment]
@iamthomasbishop and @theck13, can you please add your thoughts on this issue or direction if you have some to offer? I know we've discussed the idea in the past and wanted you to have an opportunity to weigh in here. 🙂

**Comment by theck13** [comment]
My initial thought was using a bottom sheet dialog to choose between page and post.  See the animation below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/54797905-53786700-4c13-11e9-9822-71443adcabdb.gif" width="320">

From a technical point of view, we could extend <a href="https://github.com/wordpress-mobile/WordPress-Android/blob/19d8591335de160e89df8e6de61c0e380662140a/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/widgets/WPBottomSheetDialog.java">`WPBottomSheetDialog`</a>

**Comment by iamthomasbishop** [comment]
I think there's something to this issue and some cool suggestions floating around, but I think this issue deserves some thorough design discovery/exploration (one that is informed by the block editor's progress) to ensure we're taking an informed approach.

With that said, I'm not going to be much help for the next few weeks because I'm on parental leave 😄 If in the meantime anyone else is willing/able to take a stab at it, feel free!

**Comment by rachelmcr** [comment]
Closing since we do have this now:

<img src="https://user-images.githubusercontent.com/8658164/88401148-43513880-cdc1-11ea-8bed-674222de4e4e.jpg" width="300px">
