### ISSUE TITLE
[Gutenberg] Sharing a photo doesn't show the photo in the editor

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#9244]
### Expected behavior
Sharing a photo (to create a new post with it) should launch the editor and the photo should be visible in it.

### Actual behavior
The editor (Gutenberg) is launched but the post is totally empty, no photo shown at all.

### Steps to reproduce the behavior

1. Have the "Use block editor for new posts" App Setting turned ON
2. Go to Google photos and share a photo to the "WordPress" app
3. Notice the editor coming up, but the new post is totally empty

##### Tested on [device], Android [version]
Pixel 2XL, Android 9.0, wpandroid alpha-151

**Comment by mzorz** [comment]
Reopening this one so we can properly work on a solution that involves Gutenberg and not falling back to Aztec (#9312) in this case as per the issue's description
