### ISSUE TITLE
Handle unknown post status in Post Filters

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9252]
As discussed [here](https://github.com/wordpress-mobile/WordPress-Android/pull/9226#discussion_r256627484) we need to handle `Unknown` post statuses in the post filters tab. I believe this will only matter for self-hosted sites which changes the default post statuses (or add to them). We don't know what the solution for this will be, so we can use this issue to discuss it.

Since this doesn't affect many people (if any), it's a low priority issue for us.

**Comment by malinajirka** [comment]
Fixed in #9640
