### ISSUE TITLE
Post list - Tab selection not updated on swipe gesture

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9285]
### Expected behavior
When the user changes tabs using swipe gesture, the tab layout isn't updated.

### Actual behavior
When the user changes tabs using swipe gesture, the tab layout is updated.

### Steps to reproduce the behavior
1. My Site
2. Blog Posts
3. Swipe between tabs using gesture
4. Notice the selected tab in the tablayout isn't being updated

![9db633080721709caccef0bef80abc7e](https://user-images.githubusercontent.com/2261188/53078834-5ccbc200-34f5-11e9-9281-fccbba621d01.gif)

**Comment by oguzkocer** [comment]
Fixed in #9288.
