### ISSUE TITLE
discuss SQLite database migration to Room

### ISSUE THREAD

**Issue by tech-mint** [wordpress-mobile/WordPress-Android#9291]
Room benefits:

> Room is an ORM, Object Relational Mapping library. In other words, Room will map our database objects to Java objects. Room provides an abstraction layer over SQLite to allow fluent database access while harnessing the full power of SQLite.
> 
> Difference between SQLite and Room persistence library:-
> 
> In case of SQLite, There is no compile time verification of raw SQLite queries. But in Room there is SQL validation at compile time.
> As your schema changes, you need to update the affected SQL queries manually. Room solves this problem.
> You need to use lots of boilerplate code to convert between SQL queries and Java data objects. But, Room maps our database objects to Java Object without boilerplate code.
> Room is built to work with LiveData and RxJava for data observation, while SQLite does not.

I opened this issue to understand if there is a need for database migration to Google official ORM:
> we highly recommend using Room instead of SQLite
https://developer.android.com/training/data-storage/room/

**Comment by designsimply** [comment]
Thank you for raising this issue @tech-mint ! The question of using the Room DB in FluxC comes up from time to time and no decision to switch has been made as of yet. Do you have experience with migration to Room that you can comment on by chance?

**Comment by jkmassel** [comment]
We're planning to deprecate FluxC, so this issue is no longer relevant.
