### ISSUE TITLE
[Stats Refresh] Improve icon/avatar loading states

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#9303]
This is an issue to improve the general icon/avatar loading states in Stats

While an icon is loading show a square as a placeholder. This applies to the blocks `Publicise` and `Referrers`

- Square is 24dp
- Corner radius is 2dp
- Colour is `grey_lighten_30`
- Fade icon in when loaded

While an avatar is loading show a circle as a placeholder. This applies to blocks `Comments` `Followers` and `Authors`

- Circle is 24dp
- Colour is `grey_lighten_30`
- Fade avatar in when loaded

<img width="394" alt="screenshot 2019-02-21 at 11 56 21" src="https://user-images.githubusercontent.com/36532468/53167422-ca4c2100-35cf-11e9-8e2c-12b7bafb9cee.png">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
