### ISSUE TITLE
Volley error on xmlrpc.php - exception: null

### ISSUE THREAD

**Issue by edent** [wordpress-mobile/WordPress-Android#9321]
### Expected behavior

I can log in to my self-hosted site. I can retrieve posts. I can retrieve and approve/delete comments.

I cannot edit posts or publish new ones.

### Actual behavior

Uploads time-out. Logs show this repeatedly:

```
93 - [Feb-23 10:14 API] long type could be misinterpreted when sent to the WordPress XMLRPC end point
94 - [Feb-23 10:15 API] Volley error on https://shkspr.mobi/blog/xmlrpc.php - exception: null
95 - [Feb-23 10:15 API] StackTrace: com.android.volley.TimeoutError
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:147)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
```
Android App:
* WordPress - 11.7 - Version code: 675

From Health-Check:

* WordPress 5.1 
* PHP 7.1.26 
* The REST API is available. 
* The loopback request to your site completed successfully.
* All required and recommended modules are installed.

**Comment by designsimply** [comment]
I did a quick check with WPAndroid alpha-154 (11.9 alpha) on Pixel 3, Android 9 and I was able to edit posts and publish new posts to a site running 5.2-alpha-44768 and PHP 7.1.26 (jurassic.ninja test site) without problems.

I noticed the line after the `xmlrpc.php - exception: null` mentions `com.android.volley.TimeoutError`. So I tried [measuring the response time](https://stackoverflow.com/a/22625150/1100719) for that file comparing your site and mine but they looked the same to me (note: I tested response time from Terminal on a MacBook and I am not sure if this needs to be tested separately from mobile in order to be a good test).

```
% curl -w "@curl-format.txt" -o /dev/null -s "https://shkspr.mobi/blog/xmlrpc.php"
    time_namelookup:  0.067341
       time_connect:  0.069495
    time_appconnect:  0.111819
   time_pretransfer:  0.111926
      time_redirect:  0.000000
 time_starttransfer:  0.714310
                    ----------
         time_total:  0.714404
% curl -w "@curl-format.txt" -o /dev/null -s "https://alleged-swift.jurassic.ninja/xmlrpc.php"
    time_namelookup:  0.004334
       time_connect:  0.085247
    time_appconnect:  0.268768
   time_pretransfer:  0.268882
      time_redirect:  0.000000
 time_starttransfer:  0.718159
                    ----------
         time_total:  0.718264
```

**Comment by SiobhyB** [comment]
I was able to edit posts and pages for a self-hosted site on a Pixel 5, Android version 11, and version alpha-285 of the WordPress app. 

I also searched through our internal P2s and ticket system but wasn't able to find matching reports from within the last two years.

As this report came in around two years ago and we haven't been able to replicate or dig into similar reports, I'll go ahead to close this issue for now. 

@edent, if you're still following along here and continue to have problems editing posts within the latest version of the app, feel welcome to re-open! You can also contact our team directly via _Me_ → _Help & Support_ → _Contact Support_ in the app. We'd love to gather more details and dig into this further if it's a problem you're still seeing.
