### ISSUE TITLE
Change DEFAULT site

### ISSUE THREAD

**Issue by pharma-vie** [wordpress-mobile/WordPress-Android#9323]
how i can change the address of the DEFAULT home discover.wordpress.org to my adress example.wordpress.com.

**Comment by designsimply** [comment]
I think you mean in the Reader. To do that:

1. Go to Reader > Followed Sites > (tap the gear icon). 
1. Select the site to unsubscribe from (i.e. Discover).
1. Tap "Following" at top right to unsubscribe from that blog in the Reader.

**Comment by designsimply** [comment]
I am closing this issue as it was reported in the bug tracker but appears to be a help request. 

If you need further help, I will still see replies here or you can always to go Me > Help & Support > Contact us within the app to ask questions about using the app. Thank you!
