### ISSUE TITLE
[Site Creation] tagline is not saved

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9342]
### Expected behavior

When I add a tagline during site creation, I expect it to be saved to the site.

### Actual behavior

Tagline set during site creation is not saved.

### Steps to reproduce the behavior

1. Go to My site > Switch Site > + > Create WordPress.com site.
1. Create a new site including setting a tagline.
1. Go to Settings > Tagline to see if the tagline was saved.

Video: ([1m50s](https://cloudup.com/cANGrNBk6ma), skip to 14s then 1m40s).

<img src="https://user-images.githubusercontent.com/1119271/53527854-46010e80-3aa5-11e9-8917-4b0cd8e4a95e.png" width="270" alt="screenshot_20190227-153424"> <img src="https://user-images.githubusercontent.com/1119271/53528057-c293ed00-3aa5-11e9-96cd-f266b76ad62a.png" width="270" alt="screenshot_20190227-153813">

##### Tested with WPAndroid alpha-154 (11.9 alpha) on Pixel 3, Android 9.

Corresponding iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/11151.

**Comment by oguzkocer** [comment]
@kwonye If I remember correctly, this is not implemented on the server side yet. Could you please confirm if that's the case? cc @malinajirka

**Comment by stevebaranski** [comment]
@designsimply A discussion about this topic is underway via `p1552602073005000-slack-bt-site-creation`, and a resource has been assigned. If confirmed as a server-side issue, the issue should not require a client-side fix. Otherwise, a change will need to be expedited.

cc: @malinajirka @oguzkocer @ctarda @kwonye

**Comment by michaeldcain** [comment]
This was fixed in D25611-code.

**Comment by rachelmcr** [comment]
Confirmed the tagline is working now in this site creation flow. Thank you!
