### ISSUE TITLE
Stats: percent change value shown at top right should be a meaningful value

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9343]
### Expected behavior

If the selected bar in a graph has zero views while the previous bar has data, there should be a meaningful percentage (or nothing) there.

### Actual behavior

If the selected bar in a graph has zero views while the previous bar has data, then the percentage is displayed as “(-∞%)”.

### Steps to reproduce the behavior

1. Open a site with low traffic.
1. Find a bar in a graph with zero views.
1. Click on the bar with zero views.
1. Note whether the value shown at top right is meaningful.

<img src="https://user-images.githubusercontent.com/1119271/53535140-eadc1580-3abe-11e9-8209-e181cc56fcf6.png" width="270" alt="screenshot_20190215-132640">

##### Tested with WPAndroid alpha-151 (11.8 alpha) on Pixel 3, Android 9.

<sup>Found during WPAndroid 11.8 beta testing (internal ref: p5T066-LD-p2).</sup>

**Comment by SylvesterWilmott** [comment]
I think we can remove the percentage entirely in instances where it shows `∞%` or `-∞%`.

Moving this to the Stats Refresh project
