### ISSUE TITLE
Quick Start Progress Does Not Update After Skipping Task(s)

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#9345]
### Expected
Quick Start progress (e.g. "1 of 6 complete") updates when returning to ***Sites*** tab after skipping task(s).

### Observed
Quick Start progress (e.g. "1 of 6 complete") does not update when returning to ***Sites*** tab after skipping task(s).

### Reproduced
0. Select site with Quick Start in progress.
1. Notice _**Next Steps**_ view is shown.
2. Notice progress of _**Customize Your Site**_ and _**Grow Your Audience**_ types.
3. Tap _**Customize Your Site**_ or _**Grow Your Audience**_ type.
4. Long-press uncompleted task in list.
5. Tap ***Skip Task*** option.
6. Tap ***X*** in top app bar.
7. Notice progress of _**Customize Your Site**_ and _**Grow Your Audience**_ types is same as Step 2.

##### Tested
Google Pixel 3 on Android 9.0 with alpha-153

**Comment by khaykov** [comment]
Fixed in #9346
