### ISSUE TITLE
Change infinity % to 100% when dropping from N views to 0

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#9350]
When there is a change from any number to 0, the percent change should be -100% instead of infinity. Infinity symbol should be showing only in case of raise from 0 (0 -> 1 is +infinity %)

**Comment by designsimply** [comment]
Tested and confirmed! Tracking at https://github.com/wordpress-mobile/WordPress-Android/issues/9343.
