### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by trymeouteh** [wordpress-mobile/WordPress-Android#9387]
Please add the Andriod Wordpress app onto F-Driod. This way Andriod users who do not have access to Google Play Store can download the Wordpress app and use it.

**Comment by designsimply** [comment]
I researched this and found a similar request and reply in https://github.com/wordpress-mobile/WordPress-Android/issues/1914#issuecomment-58000677 which mentions why this cannot be done:

<blockquote>The WordPress app is strongly linked to wordpress.com functionalities (wordpress.com hosted login, Reader and Notifications for instance). App can be built without these secrets (using `gradle.properties-example`, see the README.md for build instructions) but only used for self hosted sites (ie, users won't be able to login to their wordpress.com account and get push notifications or access the reader logged in interface).

We're now giving developers the possibility to get OAuth access token for _testing purposes only_ -  see http://developer.wordpress.com/docs/oauth2/ so you can't distribute the app with OAuth access token in Fdroid.

One solution could be to create a specific gradle task that build the app without wordpress.com functionalities and "secrets" requirement.
</blockquote>

If you do not have access to the Play Store, you can install WordPress from the .apk. It does have some downsides: some features won't work (Push Notifications, Login with Google, etc.) and you need to re-download and reinstall to get updates. I'm mentioning this as an alternative and something possibly helpful to others even if it may not be ideal for your case.

**Comment by tibaultbordeaux** [comment]
Could someone explain where I would find such an official .apk file from wordpress?
As an user, not as a developer.

**Comment by designsimply** [comment]
@tibaultbordeaux, you can find an .apk file linked on the GitHub page for each release. See https://github.com/wordpress-mobile/WordPress-Android/releases.

**Comment by narcisgarcia** [comment]
Me and many F-Droid users we prefer self hosted sites than wordpress.com
This means a clean Wordpress app is needed although (or even better) is self hosted limited.
