### ISSUE TITLE
[Gutenberg] Can’t start a post from the Media section

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/WordPress-Android#9401]
**Expectation**: I’m used to having the option to upload media to My Sites > Media and using the “Write Post” notice/snackbar to start a new post with that media already added to the post.
Actual: When I select “Write Post” after uploading media, I get a new blank Gutenberg post.

**Steps**:
Go to My Sites > Media in the app.
Upload a new image.
When the image finishes uploading, tap “Write post” in the notice/snackbar that appears. Result: A new Gutenberg post opens with no content.

**Comment by mzorz** [comment]
Closing via https://github.com/wordpress-mobile/WordPress-Android/pull/9442
