### ISSUE TITLE
Client cannot use "password" grant_type` error.

### ISSUE THREAD

**Issue by pharma-vie** [wordpress-mobile/WordPress-Android#9403]
I am creating an application for my wordpress site.
what interests me more is the application and not the website.

I want to use the open source code of Wordpress Mobile;

but I see that users even if they have created their accounts on the web (wordpress.com) or on the official application, they can not connect to my application, and the error message: **Client cannot use "password" grant_type` error** always appear. and only my account can connect.

is there a solution for this problem?

My problem lies in the obligation of authentication to post comments ...

There is a way to turn authentication to Google Firebase and then the user can post the comments without going through the wordpress.com registration.

**Comment by theck13** [comment]
You're more than welcome to use any of the open source code from the WordPress-Android repository as long as you release any application using that code under the [GPL](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/LICENSE.md) as well to stay within the spirit, and the letter, of the [GPL](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/LICENSE.md).

As the [***OAuth2 Authentication*** section of the `README.md`](https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication) file states, "Login is restricted to the WordPress.com account with which the credentials were created.  […]  Using another account […] will cause the `Client cannot use "password" grant_type` error."  You can read more about how OAuth2 works for WordPress.com  at https://developer.wordpress.com/docs/oauth2.

**Comment by designsimply** [comment]
Closing because an answer has been provided. Thank you!
