### ISSUE TITLE
Share: Rotating device while sharing media to a new post results in multiple media uploads

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#9408]
### Expected behavior

I expect that when I share media to a new post in the app, only one copy of the media file will be uploaded.

### Actual behavior

When I share media to a new post in the app, if I rotate my device it uploads multiple copies of the media file and adds each copy to the new post.

### Steps to reproduce the behavior

1. Open the Photos app.
2. Select a photo and share it to WordPress.
3. Select "Add to new post" to add the photo directly to a new post.
4. After the editor opens and you see the new photo uploading, rotate your device.
5. Result: A second copy of the photo will be uploaded and appear in the post.

Each time you rotate your device at this point it will add a new copy of the photo to your post.

##### Tested on [moto e5 play], Android [8.1.1], WPAndroid [alpha-156]

Observed while testing the change made in https://github.com/wordpress-mobile/WordPress-Android/pull/9322, although I'm not sure if this issue is new/related to this PR or not. cc @mzorz

**Comment by mzorz** [comment]
Closing via #9427
