### ISSUE TITLE
Update Gradle plugin to 3.3.+

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#9436]
As of this writing, `3.3.2` is the latest Android Gradle plugin. We should update the project to use it. However, at the moment updating to `3.3.+` generates some build warnings:

* [x] `'variant.getGenerateBuildConfig()' is obsolete`
* [x] `'variant.getExternalNativeBuildTasks()' is obsolete`
* [ ] `'variant.getJavaCompile()' is obsolete` (2 instances)

The first warning can be resolved by using the new provider config for this Crashlytics task:

```groovy
android.applicationVariants.all { variant ->
    variant.generateBuildConfig.dependsOn(generateCrashlyticsConfig)
}
```

to
```groovy
android.applicationVariants.all { variant ->
    variant.generateBuildConfigProvider.configure {
        dependsOn(generateCrashlyticsConfig)
    }
}
```

The next warning requires the Fabric gradle plugin to be updated to support `3.3.+` and fix its internal warnings - this has already happened, we just need to update to `io.fabric.tools:gradle:1.28.0` when we're ready.

The last set of warnings, and the ones without an easy fix yet for `3.3.+`, come from the Bintray plugin used in a few of the subtrees (`libs/utils` and `libs/analytics`). The Bintray plugin needs to be updated for that, we'll want to check on that periodically: https://github.com/novoda/bintray-release/releases. (It would be nice if there was a way to ignore this part of the subtree Gradle build when building WPAndroid, since it's irrelevant to actually building WPAndroid - but I don't know of one offhand.)

Note that we can of course update to `3.3.+` whenever we want, they're just warnings - but they're pretty noisy and we may want to hold off a bit if we can until they can be addressed.

cc @jtreanor

**Comment by aforcier** [comment]
Note that apparently earlier Fabric plugins don't work at all with Gradle `3.3.+` - everything seems normal but the app can't reach Fabric (see https://github.com/woocommerce/woocommerce-android/pull/911).

So we should extra definitely not update to `3.3.+` without also updating our Fabric plugin version as outlined above.

**Comment by jtreanor** [comment]
Wow!

Thanks for the update. Perhaps we should accelerate looking at alternative crash reporting providers.

**Comment by aforcier** [comment]
@oguzkocer I believe we can close this now, #12896 upgraded us past this to `4.0.1`, and the main problem libraries (Crashlytics and Fabric) aren't used anymore, and I think the Bintray plugin has been updated. ccing you anyway in case you spot anything relevant in here to any new warnings you might have noticed.
