### ISSUE TITLE
[Stats Refresh] Add spaces between fragment when moving between tabs

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#9447]
See #9421 

This is to add some space between blocks when moving between tabs in Stats

- Add 16dp space between fragments

**Comment by theck13** [comment]
Adding 16dp margin between pages can be done with this:
`ViewPager.setPageMargin(getResources().getDimensionPixelSize(R.dimen.margin_extra_large));`
