### ISSUE TITLE
Update row type to include percentage in Stats

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#9459]
Add a bar that contains the percentage of the top value in the list items in Stats blocks in posts / pages, tags / categories, authors (the highest value would be 100% - a bar that stretches under the whole textview). The color of the bar is `#c8d7e1`, height is `4dp`, the designs are attached:

<img width="511" alt="Screenshot 2019-03-28 at 08 55 19" src="https://user-images.githubusercontent.com/1079756/55139977-4db0e300-5137-11e9-8d2d-25ffe27dd77c.png">

**Comment by AmirGamilDev** [comment]
Hi.

Just wanted to clarify something:

Text in issue says 4dp but image shows 8dp.  Please confirm which it should be.  Guessing 4?

Thanks 😊

**Comment by SylvesterWilmott** [comment]
@AmirGamilDev I believe the `8dp` in the screenshot is the space between the text label and the bar. The bar itself is 4dp.

**Comment by AmirGamilDev** [comment]
Ah I see it now. Thanks @SylvesterWilmott👍
