### ISSUE TITLE
Verification code field doesn't handle enter key

### ISSUE THREAD

**Issue by CassieKillsIt** [wordpress-mobile/WordPress-Android#9489]
### Expected behavior
When going through the log in process pressing the enter key (on a physical keyboard) should trigger the same action that clicking the IME action button would.

### Actual behavior
Pressing enter on a physical keyboard doesn't do anything

### Steps to reproduce the behavior
1. On an emulator fresh install or log out
1. Go through the log in process with an account that has two factor auth set up
1. Enter the verification code with a physical keyboard and press enter

##### Tested on [device], Android [version]
Tested on the Android emulator running API 28

**Comment by designsimply** [comment]
I was unable to reproduce the problem using WPAndroid alpha-159 (12.1 alpha) on Pixel 3 Android 9 with a Logitech K811 keyboard connected via Bluetooth by pressing enter to advance to the next screen after entering a verification code from my Authenticator app.

<img src="https://user-images.githubusercontent.com/1119271/55420031-4ae93000-5533-11e9-92f4-4ae51b23aa57.png" width="270" alt="Screenshot_20190402-101045">

**Comment by planarvoid** [comment]
I couldn't reproduce this issue
