### ISSUE TITLE
Posts List - wrong ui state when retrying

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9490]
### Expected behavior
A progress bar and text "Uploading post" should be shown when you are retrying upload after an error.

### Actual behavior
The disabled overlay is displayed, but the view keeps showing an error message instead of showing "Uploading post".

### Steps to reproduce the behavior
1. Open a published post
2. Change it's content
3. Set "Edge" connection type on the emulator
4. Click on publish post
6. Turn the airplane mode on
7. Notice the upload fails and an error message is displayed
8. Turn the airplane mode off
9. Click on retry and notice the error state is being shown and there isn't any progress bar visible

The gif is from the Post Filters WIP, but it behaves +- the same on the production version.
![wrong-state-after-retry](https://user-images.githubusercontent.com/2261188/55137445-47b80380-5131-11e9-95bd-53056b963a08.gif)

##### Tested on [device], Android [version]
Emulator Android 8.1

**Comment by malinajirka** [comment]
The PostModel still contains the error_state after you hit Retry. I think we can either prioritize "uploading" state over "error" state in the `PostListItemUiStateHelper` or perhaps fix the PostModel state in FluxC.

**Comment by mzorz** [comment]
This _may_ be related to https://github.com/wordpress-mobile/WordPress-Android/issues/9145

**Comment by malinajirka** [comment]
Fixed in #9707
