### ISSUE TITLE
Site Picker selection does not match highlighted rows

### ISSUE THREAD

**Issue by robertoissc** [wordpress-mobile/WordPress-Android#9516]
### Expected behavior
When you long press a site in Site Picker and enter selection mode, the pressed site should become selected and the highlighted rows should equal the selected sites.
If you exit the selection mode only the active site should remain highlighted.

### Actual behavior
When you long press a site in Site Picker the site doesn't get selected and the highlighted rows doesn't match the selected sites.
If you exit the selection mode the rows remain highlighted.

### Steps to reproduce the behavior
1. Use an account with multiple sites.
2. Go to My Site tab.
3. Tap Switch Site button in top card view.
4. Notice active site is selected.
5. Long-press next site in the list.
6. Notice active site is highlighted.
7. Notice top toolbar title shows 0 selected.
8. Tap another site.
9. Notice top toolbar title shows 1 selected and there are two sites highlighted.
10. Press back.
11. Notice sites are still highlighted.

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid alpha-162 (12.2 alpha) on Pixel 3 Android 9. Thank you for the report!

**Comment by designsimply** [comment]
I noticed we have an earlier report of this at https://github.com/wordpress-mobile/WordPress-Android/issues/8343 so I'd like to close this issue in favor of tracking in the newer one. Thank you again for the report.
