### ISSUE TITLE
Post List - Author filter icon on Android 5 is too large

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9518]
### Expected behavior
The "Everyone" filter icon has appropriate size on all devices.

### Actual behavior
The "Everyone" filter icon is too large on Emulator Android 5.1 (Nexus 4)

![Screenshot_1554448886](https://user-images.githubusercontent.com/2261188/55611021-8d557b80-5784-11e9-86af-96589984a700.png)

### Steps to reproduce the behavior
1. My Site
2. Blog posts
3. Notice the author filter icon

##### Tested on [device], Android [version]
Emulator Android 5.1 (Nexus 4)

**Comment by oguzkocer** [comment]
Fixed in #9532.
