### ISSUE TITLE
Don't re-create the PostsPagerAdapter when author filter changes

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9522]
When we change the author filter, we are currently re-creating the whole adapter. This was a temporary solution used in a trial and will need to be updated. It might make sense to do this with search as it'll need to be able to update the list descriptor of a fragment as well.

**Comment by malinajirka** [comment]
Post list search was recently merged - https://github.com/wordpress-mobile/WordPress-Android/pull/10023. This issue should be pretty straightforward now.
