### ISSUE TITLE
Post Filters - Design Review

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9530]
Do a full design review of all the changes in `feature/master-post-filters` before it's merged into `develop`.

**Comment by SylvesterWilmott** [comment]
Here's a list of amendments and design changes for Post List/Post Filters roughly in order of priority.

1. use roboto/sans-serif for card labels. Card labels include: timestamps, post state labels (Local Changes, Private, Pending review etc.)
2. Copy:  When moving a post from trash to draft, snackbar copy should be `Post moved to drafts` button: `Publish`
3. Copy:  When local changes are made to a post, snackbar copy should be `Post saved on device` button: `Update`
4. Copy: Change `binned` to `trashed` on "Trash" tab empty state
5. Copy: When a published post has local changes and is published, snackbar copy should be `Post updated` button: `View`
6. Remove "W" list footers. We need to make sure we keep enough space on the base of the list to make sure the FAB is not covering any content as well.
7. Adjust the body text line height/spacing to match the reader cards
8. Remove bottom margin from progress bar, the progress bar should sit flush to the bottom of the card
9. Increase padding on the right side of the author selection menu. The value used should be 24dp.

**Comment by malinajirka** [comment]
Partially fixed in #9770. Created an issue for the issues which haven't been fixed - #9769
