### ISSUE TITLE
Post List - can't publish post pending review from post list

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9538]
When I submit a post for review and I open the post list as an admin, I'd expect to see "Publish/Approve" action on the pending review item. Instead there is just "View" action and I need to open the editor, click on overflow menu and click on "Publish now".

@SylvesterWilmott Is this really an issue or intended behavior? Thanks!

**Comment by SylvesterWilmott** [comment]
>I'd expect to see "Publish/Approve" action on the pending review item

I've been thinking about this for some time and I agree, the action should be "Publish", this follows the logic of any currently unpublished changes on published or draft posts.
