### ISSUE TITLE
Add a Quick start step for Stats

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#9541]
We'd like to add a new step to the Quick start for new users that will introduce the Stats feature to them.

**Comment by theck13** [comment]
Quick Start currently has an item titled "Check your site stats" under the ***Grow Your Audience*** category that directs you to ***My Site*** > ***Stats***.  Is that what you had in mind?  See the screenshot below for illustration.

![quick_start_stats](https://user-images.githubusercontent.com/3827611/55747365-f3463b00-59f0-11e9-9a51-e52317c4e749.png)

**Comment by planarvoid** [comment]
I think we don't want to add a new step right now because of the mentioned reason.
