### ISSUE TITLE
Address TODOs in Post filters project

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9547]
Before we merge the `feature/master-post-filters` branch into `develop` we need to remove all the `TODO`s we added during this project by either fixing the `TODO`s or opening issues for them.

**Comment by malinajirka** [comment]
Created an issue for [this](https://github.com/wordpress-mobile/WordPress-Android/blob/75991eea4e4581ad0790f3d538ef55867bf5f186/WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt#L68) todo: #9576

**Comment by malinajirka** [comment]
Fixed in #9640
