### ISSUE TITLE
Notification Settings: “All My Followed Sites” list doesn’t match Reader: “Followed Sites” list

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#9549]
### Expected behavior
Both “Followed Sites” lists would list the same set of sites.

### Actual behavior
Reader > Settings (gear icon) > Followed Sites lists shows all sites.
Me > Notification Settings > All My Followed Sites appears to be missing non-WordPress.com/Jetpack sites.

These sites are followed via RSS, and their posts do appear in the Reader.

My guess here is that the lists are different because of the difference in notifications behavior. WordPress.com doesn't control notifications for those RSS sites, since they don't use Jetpack or WordPress.com.
However, I don't think most users are aware of this. It would be better to have the lists match, to reduce confusion. Perhaps in the notifications section we could add "Followed via RSS - no notifications" below those sites.

### Steps to reproduce the behavior
Make sure you're following a mix of WordPress.com/Jetpack sites and some that are followed via RSS (add the URL in Reader > Manage to [follow by RSS](https://en.support.wordpress.com/reader/#finding-and-following-blogs).).

Reader > Settings (gear icon) > Followed Sites to see all your followed sites.

Go to Me > Notification Settings > All My Followed Sites and note that some sites (the RSS ones) are missing.

**Screenshots from user report:**
Reader:
![readerfollowed](https://user-images.githubusercontent.com/15107387/55784522-703ce780-5ab9-11e9-884a-eec179daef10.jpg)
Notification Settings:
![notifsfollowed](https://user-images.githubusercontent.com/15107387/55784519-6e732400-5ab9-11e9-8f0c-44533cfb101a.jpg)

**Screenshots from my own testing:**
Reader:
![readerlist](https://user-images.githubusercontent.com/15107387/55784824-0244f000-5aba-11e9-99c1-87fec7d0534c.png)
Notification Settings:
![notifslist](https://user-images.githubusercontent.com/15107387/55784828-040eb380-5aba-11e9-9135-33da5522dc75.png)

**Comment by designsimply** [comment]
I tested this using my Pixel 3 Android 9 device and confirmed that a site followed via RSS does not show up in Me > Notification Settings > All My Followed Sites.

I followed http://marvelageofcomics.com/ by entering that URL at **Reader > Followed Site > Mange > Follow Something New** in Calypso.

I followed https://gostica.wordpress.com/ by going to https://gostica.wordpress.com/ in a browser and **clicking the "Follow" option at bottom right**.

On the All My Followed Sites screen in the app, I can see "GOSTICA" `gostica.wordpress.com` listed but I cannot see "FantasticAmazingIncredible" `marvelageofcomics.com` listed.

<img src="https://user-images.githubusercontent.com/1119271/55916800-9ee6bb00-5baa-11e9-88de-71730eb93b88.png" width="270" alt="Screenshot_20190410-160601">
<sup>Me > Notification Settings > All My Followed Sites tested with WPAndroid alpha-163 (12.2 alpha) on Pixel 3 Android 9.</sup>

On Calypso, I noticed that the site missing from the "All My Followed Sites" notifications settings screen in the app also has a "Settings" option missing at Reader > Followed Sites in a desktop browser view. 

![Screen Shot 2019-04-10 at 3 55 41 PM copy](https://user-images.githubusercontent.com/1119271/55916744-78c11b00-5baa-11e9-9792-6dce68a7e2a5.png)
<sup>Seen at https://wordpress.com/following/manage logged in as `user0313`.</sup>

Oddly, I couldn't find the equivalent of the All My Followed Sites screen in Calypso > Me > Notifications Settings so I think that's an app-only list.

**Comment by designsimply** [comment]
I tested this again today using WPAndroid alpha-164 (12.2 alpha) on Pixel 3 Android 9 and found the same result: when I go to Reader > Settings (gear icon) > Followed Sites for account `user0313` I can see 20 followed sites. When I go to Me > Notification Settings > All My Followed Sites I can see 17 followed sites and these are the three that are missing: `marvelageofcomics.com`, `www.youtube.com/channel/UC5J-hZ4wNf7OlkzIn49LHoQ`, `www.strategic-culture.org` (all of these are subscriptions via RSS, two are not WP sites and the WP site is self-hosted without Jetpack).

**Comment by theck13** [comment]
Yep, those lists are different.  The ***Reader*** > ***Edit tags and sites*** > ***Followed Sites*** list has all sites shown in the Reader.  The ***Me*** > ***Notification Settings*** > ***All My Followed Sites*** list has all sites that have notification settings.  As mentioned above and shown in the [Calypso screenshot](https://user-images.githubusercontent.com/1119271/55916744-78c11b00-5baa-11e9-9792-6dce68a7e2a5.png), certain followed sites (i.e. feeds) don't have notifications settings.

Another possible solution would be to include feeds in the ***Me*** > ***Notification Settings*** > ***All My Followed Sites*** list, but indicate they are disabled by giving them a different text color and showing a "Feeds do not have notification settings" or similar message when those items are tapped.

**Comment by planarvoid** [comment]
Should we implement the suggested solution @osullivanchris ?

**Comment by osullivanchris** [comment]
@planarvoid Hey, I agree with the suggestion from @theck13 

Although you can't do anything with the sites that don't have notification settings, the user may not know why they're no on the list. Greying them out and showing the message on tap makes it clearer to the user.

We already have a style for disabled fields in Me>Account settings>username (which can't be changed). We could use the same grey out treatment here.

On tap I would present a basic native dialogue. I think the text  "Notifications are not supported for this site" would be ok. When we have something to show here we could ask for editorial review.
