### ISSUE TITLE
Can't Publish a local draft while offline.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9556]
~~When you open a local draft and click on Publish you are redirected back to Post List with no error/info message and it almost seems like it succeeded ( the “Local draft” label is still displayed)~~

When you open a local draft and click on Publish you are redirected back to Post List with a Toast error message.

<img src="https://user-images.githubusercontent.com/198826/57097172-4780ca00-6cd4-11e9-88fd-a26d905c7a96.gif" width="320">

## Tasks

- [ ] Replace Toast with a Snackbar
- [ ] Schedule the changes? – needs discussion

**Comment by maxme** [comment]
I get a Toast, but it's almost the same color as the post list (and not visible) - it makes the app feels borken. Replace with a Snackbar?
