### ISSUE TITLE
Offline Support: Can't delete a post.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9558]
## Description:

When attempting to delete a post while offline we show a non-blocking but also non-standard “There is no network available” message that takes an unusually prominent space in front of the post lists.

On top of that the post isn't scheduled for deletion at all.

## Matching iOS issue:

https://github.com/wordpress-mobile/WordPress-iOS/issues/11425

**Comment by shiki** [comment]
> shows that blocks the UI.

It does not seem to be _blocking the UI_ because I can still tap anywhere else. Still, it should probably be a Snackbar. WDYT, @megsfulton ? 

<img src="https://user-images.githubusercontent.com/198826/55907961-6d172980-5b95-11e9-8f1d-087eb06e5811.png" width="320" />

**Comment by shiki** [comment]
Oh, wait, no. Should the post be marked as deleted *locally* and we'll update the remote once the app is online?

**Comment by diegoreymendez** [comment]
I've updated the description to account for your questions @shiki .  I think the post should be marked for deletion indeed, although we can decide to split it as a separate issue eventually.

**Comment by oguzkocer** [comment]
I think we should consider this a locally changed post and consider it a part of syncing with remote. I believe how we will go about syncing will make how to handle this issue very clear. I have noted my thoughts on syncing [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9568#issuecomment-481890791).

**Comment by megsfulton** [comment]
Agree with the points made so far. 

On the design side, I think we should use a snack bar to inform the user that the post will be queued for deletion.

**Comment by osullivanchris** [comment]
A lot of issues seem to be snowballing/falling like dominoes if we follow the proposed approach from #9555 

Following the same logic, we would here tell the user that the post **_will be_** deleted when they get online again.

Seems in line with the previous conversation here. I know you labelled it so let me know if anything else needs thinking through @yaelirub

**Comment by maxme** [comment]
> Following the same logic, we would here tell the user that the post **_will be_** deleted when they get online again.

Ok, so on the dev side we have to:
1. Remove the blocking Toast.
2. Schedule post deletion (TBD technically).
3. Show a status on the post "Post will be deleted when connection returns".

Looking at the proposal in https://github.com/wordpress-mobile/WordPress-Android/issues/9555#issuecomment-507234326 - I suppose we'll do the same for this ticket, so we'll keep the post in its current state, ie. if it's a draft it will stay in the "Draft" tab, if it's a "published post", it will stay in the "Published" tab, etc.

**Comment by osullivanchris** [comment]
> so we'll keep the post in its current state, ie. if it's a draft it will stay in the "Draft" tab, if it's a "published post", it will stay in the "Published" tab, etc.

I think you're probably right. It would be bad to say that its deleted when it hasn't been deleted yet. Especially if you delete a live/published post. We don't want to reassure someone the job of deleting it is _done_ when its actually still live on their site.

Should we then add a label e.g. "Will be deleted when connection returns" - does that feel weird?

**Comment by osullivanchris** [comment]
Final design and copy for this issue, solution goes across #9555 and #9949  as well
![Offline Actions](https://user-images.githubusercontent.com/50576199/60972383-18af5180-a31e-11e9-8dd8-3cc74432bcb9.jpg)

**Comment by yaelirub** [comment]
Closing this one as a decision has been made. Decision and implementation details are captured in this ticket :https://github.com/wordpress-mobile/WordPress-Android/issues/1020.
