### ISSUE TITLE
Vague error message when you create a new post while offline.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9565]
When you create a post while offline and publish it, you get a device is offline notice with a vague error message.

| |  |
|--------|-------|
|<img width="320" src="https://user-images.githubusercontent.com/198826/57090924-35e3f600-6cc5-11e9-9f98-9a5c911a2985.gif">|  <img width="320" src="https://user-images.githubusercontent.com/40213/57134281-fa6d2880-6da5-11e9-8f88-42983c4ffc52.gif">   |

## Tasks

- [ ] Replace with a Snackbar
- [ ] The message can be more clear. We should probably mention that it was not published and was saved as a draft instead.

**Comment by maxme** [comment]
Confirmed, that's a bug.

**Comment by shiki** [comment]
@maxme @diegoreymendez I cannot seem to reproduce this. Here's what I did:

![2019-05-02 10-27-48 2019-05-02 10_29_24](https://user-images.githubusercontent.com/198826/57090924-35e3f600-6cc5-11e9-9f98-9a5c911a2985.gif)

**Comment by maxme** [comment]
When the post is created from the "Published" tab, this is still confusing. I think we should replace that Toast with a Snackbar.

![offline-post-publish](https://user-images.githubusercontent.com/40213/57134281-fa6d2880-6da5-11e9-8f88-42983c4ffc52.gif)

**Comment by shiki** [comment]
Thanks, @maxme. I updated the description. ☝️

**Comment by maxme** [comment]
Fixed via #9805
