### ISSUE TITLE
Display a Snackbar when trying to update a post while offline

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9567]
Editing an existing post - selecting “update” from the 3 dot menu displays a “post is updating” snack bar, but it dismisses without indication that it has failed or saved the changes locally.

Reproduced on `develop` (24ed5e8d7dc92d6e2987dba6a431a6784548fe1d).

<img width="320" src="https://user-images.githubusercontent.com/198826/57100656-c67a0080-6cdc-11e9-93e0-ba37984a8ee2.gif">

**Comment by malinajirka** [comment]
I've just reproduced the behavior on the current develop 4af441c1fb2326596f0bc1eb14c4d7848cfbb74d. The only indication something went wrong is the "Local Changes" label, but imho it's not enough.

I think this ticket should be solved with the same approach as these two tickets https://github.com/wordpress-mobile/WordPress-Android/issues/9555 and https://github.com/wordpress-mobile/WordPress-Android/issues/9565.

**Comment by maxme** [comment]
Side note: These 2 "Update" options (from the action bar and from the sub-menu) are very confusing to me and even if these options end up remotely saving the post, we're not following the same code paths: 
- from the three dots menu we show a confirmation dialog, 
- from the action bar "update" button, we don't show that dialog.

I filled an issue for this: https://github.com/wordpress-mobile/WordPress-Android/issues/9825
