### ISSUE TITLE
Better reflect failed upload status of media in posts while offline.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9569]
Adding a photo from the camera adds a scary looking red overlay to it and the “upload failed” message goes into the system level notifications - there’s no app level indication the upload failed while editing the post

**Comment by maxme** [comment]
I re-created the same issue with images 🤦‍♂️  - closing this one as dup.
https://github.com/wordpress-mobile/WordPress-Android/issues/9730
