### ISSUE TITLE
Back dating a brand new post still shows "Immediately" for the publish date

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9573]
Steps to reproduce:

1. Start a brand new post.
1. Enter a title and some content.
1. Tap More > Post settings > Publish.
1. Select a date in the past and tap "OK".
1. Did the publish date show up under "Publish"?
1. Tap "Publish" again.
1. Select a date in the past and tap "OK".
1. Did the publish date show up under "Publish"?
1. Repeat the steps for a previously saved draft. 

<strong>Result:</strong> when I back date a brand new post the "Post settings" > "Publish" value says "Immediately" but when I future date a post then it's updated to show a timestamp. I expected to see a timestamp when back dating a brand new post—although, I noticed the decision made in https://github.com/wordpress-mobile/WordPress-Android/pull/6122 seems to go against that. (<a href="https://cloudup.com/cCPPo3vIFM3">2m11s</a>)

<img src="https://user-images.githubusercontent.com/1119271/55841850-35a17200-5aee-11e9-9777-17e6b9be7666.png" width="270" alt="Screenshot_20190409-173603">
<sup>Tested using WPAndroid alpha-162 (12.2 alpha) on Pixel 3 Android 9 with a WordPress.com Free site.</sup>

h/t @scruffian for the original report (internal reference: p5T066-OB-p2).

@mzorz if the decision in 6122 still stands, then this issue should be closed as wontfix with an explanation.

**Comment by mzorz** [comment]
> This behavior is different compared to previously saved drafts. 

Exactly, it shows `Immediately` only for drafts that have not been saved yet. The reasoning behind it is the following route applies: it's a draft that has not even been saved yet, thus making it effectively "Immediately" as soon as you publish it.

It's also described in <a href="https://github.com/wordpress-mobile/WordPress-Android/pull/9466">this PR #9466</a> (see <strong>test case D</strong>) so it would keep the same functionality as before.

We can remove the `Immediately` label completely so it's easier to not misinterpret or make it too ambiguous. To be fair, this was brought up by @daniloercoli <a href="https://github.com/wordpress-mobile/WordPress-Android/pull/9466#issuecomment-476514270">here </a>and @oguzkocer <a href="https://github.com/wordpress-mobile/WordPress-Android/pull/9466#pullrequestreview-218549260">while testing/reviewing the PR before</a>, but I explained that was the case as it was working before so, we decided to leave the functionality as is and only bring up the discussion with a designer about what's best to do in that case later.

Now it seems to be a good time to discuss, I can surely bring the  `Immediately` label down and let the user see the date with no special handling, which seems like the common sense expectation @daniloercoli, @oguzkocer, @designsimply and others had (and to be honest, probably mine as well, just that I tried to keep things "as they were" from a developer perspective). 

Can we summon a designer to see if we need to ditch that special `Immediately` label altogether?

Adding the `Needs Design solution` label 👍

**Comment by mattmiklic** [comment]
My expectation would be to see something like:

<img width="253" alt="Screen Shot 2019-04-12 at 12 51 59 PM" src="https://user-images.githubusercontent.com/1396552/56053333-d0ce5d80-5d21-11e9-9642-bb9d770b94c6.png">

when a draft is backdated. The "immediately" label is confusing, especially because the post actually is backdated when it's published. But it sounds like there are some [complexities](https://github.com/wordpress-mobile/WordPress-Android/pull/9466#issuecomment-476514270) discussed in #9466. @iamthomasbishop could you take a look at this one in the context of your editor work?

**Comment by iamthomasbishop** [comment]
I've not read all of the history of this issue, but at first glance I agree with something along the lines of @mattmiklic's assessment – an explicit label. Assuming we want to keep in-line with what exists for `scheduled` posts (screenshot below – `Scheduled for: [date], [time]`), backdated posts would be labeled as: `Backdated for: [date], [time]`. 

![image](https://user-images.githubusercontent.com/1200432/56605083-ecaaec80-65c8-11e9-8f7b-6f6fa465866a.png)

**Comment by mzorz** [comment]
Excellent!  Thank you @iamthomasbishop 🙇  - will try and put something together along these lines
