### ISSUE TITLE
Author selection filter doesn't work on self-hosted site with Jetpack

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9575]
### Expected behavior
When I select "Me" in the Author filter on Post List screen, my posts are shown.

### Actual behavior
When I select "Me" in the Author filter on Post List screen, the list is empty even though I've just published a post. Might be happening just on a self-hosted site with Jetpack.

### Steps to reproduce the behavior
1. Make sure you've published a post
2. My Site
3. Blog Posts
4. Select "Me" in the author selection filter
5. Notice the list is empty even though you've published some posts

![bug-author-filter](https://user-images.githubusercontent.com/2261188/55862807-81e5c400-5b79-11e9-8943-b4f241679ddb.gif)

##### Tested on [device], Android [version]
Emulator Android 9.0

**Comment by oguzkocer** [comment]
Fixed in #9583.
