### ISSUE TITLE
Post List - trash/restore + undo 

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9602]
When you 
1. perform an action on a post list item (trash/restore) 
2. undo the action
3. you can undo the undo 
4. Steps 2-3 can go on forever

It can be a bit confusing as users tend not to read labels/messages and they might think they are still undoing the first action.

![undo-undo](https://user-images.githubusercontent.com/2261188/56037007-97e8b580-5d2e-11e9-8639-3deaa8dccfee.gif)

**Comment by oguzkocer** [comment]
Fixed in #9613.
