### ISSUE TITLE
Comments: Change dropdown to tabs

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-Android#9609]
This view would be better served by a tab bar across the top with All / Pending / Approved / Trashed / Spam

The styling of the tabs should match what's used in Stats / Notifications.

Current state:
![Screenshot_20190412-103339](https://user-images.githubusercontent.com/161697/56061503-78499100-5d1e-11e9-8c24-91bb310c1ae8.png)

Proposed:
![Comments](https://user-images.githubusercontent.com/161697/56061496-754ea080-5d1e-11e9-905c-2b5852cb3cc0.png)

**Comment by khaykov** [comment]
Done in #14140 👍
