### ISSUE TITLE
Adjust notifications layout to align to keylines.

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-Android#9610]
Currently in the Notifications screen the text of notifications in the list don't align to the 72dp keyline. We should reduce the size of avatars in notifications from 42dp to 36dp so that we can move the text 8dp to the left so it aligns. 

This screenshot shows, from left to right: the current design, the current design with a keyline overlay, and the new proposed design.

![Notifications](https://user-images.githubusercontent.com/1396552/56065697-9d9cc600-5d43-11e9-884c-7d9a6ba9527b.png)

**Comment by designsimply** [comment]
To whomever picks this one up 🙂 consider working on https://github.com/wordpress-mobile/WordPress-Android/issues/4921 at the same time since it's closely related.

**Comment by theck13** [comment]
Even though both issues are related to the _*Notifications*_ tab, I don't think they are closely related.  This issue involves adjusting the size/margin/padding of a few views while https://github.com/wordpress-mobile/WordPress-Android/issues/4921 involves changing the icon coming from the API.

**Comment by designsimply** [comment]
Dangit. 😁

**Comment by mattmiklic** [comment]
While not technically related, it would be really nice if #4921 were to get attention from a helpful groundskeeper while we're thinking about Notifications. :)
