### ISSUE TITLE
Adjust Me screen layout to align to keylines

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-Android#9611]
Currently on the Me tab the icons and labels don't align to the 16dp and 72dp keylines. They also have horizontal dividers between list items, which doesn't match the design of the list of settings on the My Sites tab. We should align the icons and remove those dividers to better match the standard set on the My Sites screen.

This screenshot shows, from left to right: the current design, the current design with a keyline overlay, and the new proposed design.

![Me](https://user-images.githubusercontent.com/1396552/56065682-92499a80-5d43-11e9-80f4-00637e750cea.png)

**Comment by mattmiklic** [comment]
Additionally, we should check to ensure that icons are being displayed at the correct size. By default these icons should be 24dp, 16dp, or 12dp. The current size seems to be somewhere in-between.

**Comment by jkmassel** [comment]
The design has substantially changed since this issue was filed, so I'm closing it for now
