### ISSUE TITLE
Offline Support: Local Drafts and regular Drafts offer different menu options.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9612]
As reported be @megsfulton [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9568#issuecomment-482673135):

> And this gif might be a new issue. Notice how both of these posts are drafts, but they have different actions in the editor (Publish vs Update).

![56057705-59de9800-5d14-11e9-825b-a47cfb099f17](https://user-images.githubusercontent.com/1836005/56064209-c7f08280-5d47-11e9-99cf-7d02fae2dd0f.gif)

**Comment by maxme** [comment]
The wording is different because one of the post is published already (Update action) and the other is not (Publish action). 

I think the underlying issue here is that we want to upload local drafts as soon as the network is available.

**Comment by megsfulton** [comment]
>The wording is different because one of the post is published already (Update action) and the other is not (Publish action).

In this case, the post with the update action is unpublished as it still has the orange "drafts" label in the post list and it also has "publish" in the quick actions in the list view.

The end of the gif sequence is publishing the post, which might be confusing.

**Comment by shiki** [comment]
Subscribing @wordpress-mobile/ravenclaw

**Comment by maxme** [comment]
> In this case, the post with the update action is unpublished as it still has the orange "drafts" label in the post list and it also has "publish" in the quick actions in the list view.

This is correct, my mistake, the post wasn't published but only saved online (draft).

I'm a bit confused now, and I'm not sure what's the correct behavior. My proposition:
- In the editor: show a "Save" button in the action bar, for both drafts and local drafts.
- In the editor: Keep the ["Publish Now" option](https://user-images.githubusercontent.com/40213/58236276-d8324f00-7d42-11e9-845d-53854a57615c.png) in the overflow menu.
- In the post list: Keep the "Publish" button  for both drafts and local drafts.

**Comment by shiki** [comment]
@iamthomasbishop. I saw that there is a change in publishing flow in p77Llu-9Fn-p2. Is that related to this discussion?

**Comment by malinajirka** [comment]
I like @maxme's proposal. Should we mark this discussion as resolved and proceed with a fix or do we want to wait for an input from a designer?
