### ISSUE TITLE
Calypso is shown in WebViews

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#9625]
The fixes in Automattic/wp-calypso#31160 changed Calypso so that it will no longer show Calypso UI when a site is viewed using the WordPress mobile app. This works on iOS but not on Android.

| iOS (Expected Behavior) | Android (Actual Behavior) |
|--------|-------|
| ![2019-04-15 14 11 16](https://user-images.githubusercontent.com/198826/56162256-cb268100-5f88-11e9-9e05-a6e4a3599ace.png) |![2019-04-15 14 08 45](https://user-images.githubusercontent.com/198826/56162394-235d8300-5f89-11e9-9b68-f9c7241174b9.png)    |

## Tasks

This needs to be fixed in 2 areas:

- [x] Site → Blog Posts → View button: #9627 
- [ ] Site → View Site: #9667

## Tested on

Tested on Pixel 3, Android 9.

**Comment by elibud** [comment]
This is good to close, right?

**Comment by shiki** [comment]
@elibud We're still working on #9667.
