### ISSUE TITLE
Stats: Request to link directly to posts/pages from stats 

### ISSUE THREAD

**Issue by rfaile313** [wordpress-mobile/WordPress-Android#9642]
User provided feedback about the "removal of the link from the blog stats to the post the stats report on" in the Android app to the post. 

Sheri took a look at this and thinks that they may have been in a web view. We can't track down when (if at all) it was in the app itself and/or was removed. Thus, this is an enhancement rather than a fix. 

### Expected behavior
Stats page will have link to posts/pages that stat views are generated from.

### Actual behavior
There are no links. 

### Steps to reproduce the behavior
My Sites > Stats > View More

##### Tested on Samsung Galaxy S9+, Android 8.0.0, WPAndroid 12.1.2

Request: 1963279-z

Corresponding iOS issue https://github.com/wordpress-mobile/WordPress-iOS/issues/11344

**Comment by designsimply** [comment]
Adding a screenshot for reference:

<img src="https://user-images.githubusercontent.com/1119271/56238601-15bd0180-604c-11e9-967e-44756f3170d5.png" width="270" alt="Screenshot_20190416-133056">
<p style="clear:both;"><sub>Tested with WPAndroid alpha-164 (12.2 alpha) on Pixel 3 Android 9.</sub></p>

**Comment by charliescheer** [comment]
Another request in #1986729-zen
