### ISSUE TITLE
Webviews: cannot do authenticated interactions in Reader webviews on sites with a custom domain

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#9650]
### Expected behavior

When I view a post in a webview from the Reader while logged in to a WordPress.com account, I expect to be authenticated in the webview.

### Actual behavior

When I view a post in a webview from the Reader, if the post is on a site with a *.wordpress.com address I'm authenticated. But if the site has a custom domain, even if it's hosted on WordPress.com I'm not authenticated in the webview. I see it as it I'm logged out of my WordPress.com account.

### Steps to reproduce the behavior

1. Log in to WordPress.com in the app.
2. Go to the Reader.
3. Find a post on a site with a *.wordpress.com address and select "Visit" to view the post in a webview. Confirm you're logged in (e.g. if you try to comment you see that you're already logged in and can comment as yourself).
4. Find a post on a WordPress.com site with a custom domain and select "Visit to view the post in a webview. Note that you aren't logged in (e.g. if you try to comment you have to fill out the name/email/URL fields).

**Comment by shiki** [comment]
@rachelmcr I'm getting a related issue. It seems to have gotten worse. 😬 Now, I'm getting a _"The password field is empty"_ error when I view a `*.wordpress.com` site. 

<img src="https://user-images.githubusercontent.com/198826/56318579-bb3fa600-611c-11e9-87fb-aff1436ec56d.gif" width="320">

I tested this on production (12.1.2), develop (2d20deb27d527da685a7578baf2fadae224f0ae7), and 12.0. I deleted the app from the device (Pixel 3, Android 9) before testing. It happens on all versions. 

Does this look familiar?

**Comment by shiki** [comment]
As for the first issue you mentioned, it looks like we tried to fix this in #5742. @oguzkocer, can you please confirm if the issue is the same as #5742?

**Comment by rachelmcr** [comment]
> Now, I'm getting a "The password field is empty" error when I view a *.wordpress.com site.

Whoa, that's very weird. I haven't seen that before that I can recall, and I can't reproduce it now on alpha-164 (fresh install on device - moto e5 play, Android 8.1) or develop (`2d20deb`) on a simulator (Pixel 2, Android 9). I'm not sure what's going on there for you.

**Comment by designsimply** [comment]
Tested and confirmed that the comment form does not recognize me as a logged-in user when I go to Reader and tap "Visit" for posts on sites with custom domains (including free .blog domains) even though I am logged in to WordPress.com in the app. 

<img src="https://user-images.githubusercontent.com/1119271/59476956-551b8a80-8e10-11e9-8a0f-81a02286a5bf.png" width="270" alt="Screenshot_20190613-191809">
<sub>Tested with  WPAndroid alpha-173 (12.6 alpha) on Pixel 3 Android 9 for https://wibblywobblytimeywimey.travel.blog/2019/06/14/dorayaki/</sub>

**Comment by malinajirka** [comment]
Note: The solution applied [here](https://github.com/wordpress-mobile/WordPress-Android/pull/9667#issuecomment-502062219) - allowing cookies for 3rd party sites, might fix the issue.
