### ISSUE TITLE
Async promo dialog being shown for first post that is not a draft 

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9658]
Originally reported by @malinajirka in https://github.com/wordpress-mobile/WordPress-Android/pull/9655#issuecomment-484145172, modified description here to better reflect what's going on

### Expected behavior
The async promo dialog is shown only once and tells the user they can "publish with confidence." (or "schedule with confidence" for scheduled posts).
I believe we should only show this dialog then, when the user has a `DRAFT` or any other status except `PUBLISH` and they actually want to `PUBLISH`, as per the description in original commit https://github.com/wordpress-mobile/WordPress-Android/commit/0b353a074fe009cdad175d636f2fbcbc767d585b, PR https://github.com/wordpress-mobile/WordPress-Android/pull/6467

### Actual behavior
the Async Promo dialog is  being shown for posts with status other than DRAFT/SCHEDULED, even for Posts with status `Pending` particularly as per the original report.

![first-save](https://user-images.githubusercontent.com/2261188/56300900-0f578400-6137-11e9-8fe4-6eaacef5d2e8.gif)

### Steps to reproduce the behavior
1. Clear app data
2. Blog Posts
3. Click on FAB
4. type something into title
5. overflow menu - post settings
6. change status to Pending review
7. click on "Save" and notice Async promo dialog is shown

**Comment by daniloercoli** [comment]
I'm not quite sure we still need the Async promo dialog. I guess it was introduced to highlight the new feature back in mid 2018, but now it's common to many apps publishing in the background. There is also the system bar notification icon, that blinks during the uploading, and the post is clearly shown in posts list as "uploading in progress"...

Btw, i'm talking about the async promo dialog, not the "confirm to publish" dialog.

**Comment by mzorz** [comment]
I thought the same @daniloercoli 😄 - for the time being (groundskeeping) I'm only focusing on fixing rather than bringing in another decision level as we'd need to put this in consideration of design. 

Going to open an issue for discussion 💯

**Comment by mzorz** [comment]
Opened issue for further discussion of the Async Promo Dialog removal in https://github.com/wordpress-mobile/WordPress-Android/issues/9665

**Comment by mzorz** [comment]
Closing via #9661
