### ISSUE TITLE
Remove Async promo dialog YES/NO

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9665]
Coming from https://github.com/wordpress-mobile/WordPress-Android/issues/9658#issuecomment-484397837 by @daniloercoli 

Pinging @iamthomasbishop here (question is, are we ok to get rid of the Async promo dialog? see below).

![Untitled](https://user-images.githubusercontent.com/6597771/56372334-25b41d00-61d5-11e9-8c1d-1081ca73669e.png)

The Async Promo Dialog is still there since the introduction (August, 2017), while it looks like nothing to  brag about, it may still be informative about how to do next steps (also that's probably already taken care of somehow with the Quick Start project, already in place in the app - not sure though).

Opening the discussion here.

**Comment by iamthomasbishop** [comment]
I think there is some value in keeping the dialog, as it helps address some common anxiety that we've heard from talking to users around publishing confidence. With that said, I do think we could either:

* Only show it when the user takes the action of _publishing_, or...
* Tweak the copy/actions to match the context of the action that's being taken

The former might be easier in this case (only show when the _publish_ action is taken), so maybe that's what we could do for now. I imagine this part of the publishing flow will get some attention in the near future, so let's not spend too much time on it.

**Comment by mzorz** [comment]
> Only show it when the user takes the action of publishing

Great, this is exactly how it works now (it's only shown once, for the first time you tap on Publish after installing the app).

Closing this one then! Thanks for quickly jumping in @iamthomasbishop 🙇
