### ISSUE TITLE
[Stats Refresh] Add stats insights management feature announcement

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#9687]
This is an issue to add a feature announcement dialog to the app for Stats Insights Management. Users should see the feature announcement if:

- They visit the stats view
- They have not already seen the feature announcement

<img width="390" alt="Screenshot 2019-04-23 at 14 00 16" src="https://user-images.githubusercontent.com/36532468/56582870-292e1680-65d0-11e9-8557-851eda596989.png">

**Comment by michelleweber** [comment]
Some of these terms are probably titles/proper names that should be capitalized (I imagine "Insights" and maybe "Manage," yeah?) but too many of them in a sentence makes it a little hard to read. Suggest:

_Choose what stats to see, and focus on the data you care most about. Tap Edit at the bottom of Insights to customize your stats display._

**Comment by SylvesterWilmott** [comment]
Thanks @michelleweber 

Issue updated with the new copy.
