### ISSUE TITLE
Search box doesn't get keyboard focus

### ISSUE THREAD

**Issue by sixhours** [wordpress-mobile/WordPress-Android#9690]
### Expected behavior

When clicking on the search input field, a keyboard should pop up and the cursor should appear in the input field.

<img width="354" alt="Screen_Shot_2019-03-15_at_5 02 23_PM" src="https://user-images.githubusercontent.com/2124984/56588049-a34ea300-65b0-11e9-85bc-de57d581a08c.png">

### Actual behavior

No keyboard appears, no cursor in the search box.

### Steps to reproduce the behavior

- Select switch site
- Select the search icon
- The list of sites changes but the search field isn’t focussed

##### Tested on [device], Android [version], WPAndroid [version]

Google Pixel 3, Android Pie 9.0, unsure of WPAndroid version.

**Comment by designsimply** [comment]
Closed https://github.com/wordpress-mobile/WordPress-Android/issues/9631 as a duplicate.

**Comment by designsimply** [comment]
<img src="https://user-images.githubusercontent.com/1119271/54844500-b19d5c80-4c9c-11e9-8183-eff6fe99135a.png" width="270" alt="Screenshot_20190322-121028"> <img src="https://user-images.githubusercontent.com/1119271/54844499-b19d5c80-4c9c-11e9-85d9-1aa27ae1b5c5.png" width="270" alt="Screenshot_20190322-121041">

<sup>Tested with WPAndroid alpha-159 on Pixel 3 Android 9.</sup>

**Comment by designsimply** [comment]
This came up in a feedback post:

> I would expect the search input box to grab focus, but it doesn’t. I need to tap it to actually search, even though the keyboard is displayed on screen.

<sub>(internal reference: p4k3M4-2BP-p2#comment-2107 cc @kraftbj)</sub>

**Comment by designsimply** [comment]
Adding a vote for this myself (selfishly 😊) as this one trips me up all the time!
