### ISSUE TITLE
Remove PostListItemUploadStatus

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#9712]
With the addition of `UploadUiState` in #9707 `PostListItemUploadStatus` is no longer necessary, so we should get rid of it.

**Comment by malinajirka** [comment]
The `PostListItemUploadStatus` accesses static methods of `UploadService` and therefore cannot be properly tested. Imho it's still useful. We could somehow workaround it and perhaps clean up the code, but I believe there are a lot of other parts which are in a much worse state. 

I'm closing this issue, but feel free to re-open it.
