### ISSUE TITLE
Better Error Messaging for Invalid URLs - Take 2

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9720]
## Description

This is a follow up to https://github.com/wordpress-mobile/WordPress-Android/issues/8460

This feature has been [enhanced for WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/issues/10294#issuecomment-486260221) beyond the initial solution proposed above.

The URL validation is now triggered by the user typing, and the "Next" button is not enabled until a valid URL is detected.

The URL validation error (pending editorial review) was changed to:

```
Enter a valid URL eg. example.com.
```

## iOS Demo:

Here's the iOS demo of the enhanced feature:

![invalidURL](https://user-images.githubusercontent.com/1836005/56762670-c460f080-6776-11e9-8d28-29b51dcc1fd9.gif)

**Comment by designsimply** [comment]
Moving up in priority because it was already updated in WPiOS and we want the experience across platforms to be consistent when possible.

**Comment by shiki** [comment]
@diegoreymendez When I checked iOS, it looks like this plan has since been reverted after the fixes for https://github.com/wordpress-mobile/WordPress-iOS/issues/11617. On iOS, I can enter "oneword" and the _Next_ button is immediately enabled. Is this plan still valid?

**Comment by diegoreymendez** [comment]
It wasn't entirely rolled back.  The "Next" button is still disabled in some scenarios where the URL is clearly wrong, but the domain validation is much more forgiving than it was at first.

If you want to see this in action, try typing "%%%%" in the domain name: the "Next" button will be disabled and you'll see an error message beneath the input field.

**Comment by shiki** [comment]
@diegoreymendez Thank you! I'll try to implement it to be less forgiving and test the regressions that were brought up on iOS. 

> I'm not sure this should be higher priority though

I picked it up because it was close to the top in the Groundskeeping prioritized board and I _thought_ I could finish it before my rotation is up.
