### ISSUE TITLE
[Site Creation] Add shadow to domains screen button bar

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#9723]
As mentioned in #9711 , the domains screen button bar is missing a shadow. We should add the shadow to be consistent with other parts of the flow.

**Comment by antonis** [comment]
Hey @SylvesterWilmott 👋 

as part of [“Choose a Domain” screen redesign](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2722) a shadow has been added in the bottom toolbar with [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13424)

In my understanding this resolves this issue. Please reopen if that's not the case.

<image width="360" src="https://user-images.githubusercontent.com/304044/99583181-cb4ff380-29eb-11eb-9a5f-ca4ad8ea5c44.png"/>
