### ISSUE TITLE
Trigger an auto-upload or remote auto-save to preview drafts or published posts

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9728]
When the user wants to preview a draft, we can just save a revision and preview it. However, when dealing with published posts saving would mean changing the published content and not just previewing it.

Edit: read [detailed cases here](https://github.com/wordpress-mobile/WordPress-Android/issues/9728#issuecomment-494274367).

**Comment by maxme** [comment]
Note that with this change implemented, we should also update the "Preview" button from the Edit Post menu. It currently shows a local preview, but it should open the remote one (after the autosave call has finished).

**Comment by maxme** [comment]
A change is needed on the FluxC side as a prerequisite to fix this ticket: https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1247

**Comment by yaelirub** [comment]
Hey @maxme ,
>Press preview on draft, local draft, or new post -> auto-upload draft (show an activity indicator during upload) -> get preview URL -> show the preview (Related to the auto-upload draft PR: #9774)


Should we add "save locally" and "create revision to the steps here?

**Comment by maxme** [comment]
> Should we add "save locally" and "create revision" to the steps here?

Good point about "save locally", I'm not sure about the "create revision" step, I can't see it in Calypso. I updated the description (copy/pasted from the UE post).

**Comment by maxme** [comment]
I wanted to split this into 2 tickets, but the changes are really similar and the UI update (activity indicator / error management) will use the same code, so better to do this atomically. Adding some details here to our future implementation:


- [ ] Press preview on draft, local draft, or new post:
  - Press preview on draft, local draft, or new post.
  - Save it locally.
  - "Push" the post **as a draft**[1] via the UploadService.
  - Show an activity indicator during saving/upload.
  - Wait for the upload to finish.
  - Get the preview URL or forge it locally?
  - If the upload fails, stays on the editor and show a snackbar.
  - If the upload succeeds open the URL in our Webview.

- [ ] Press preview on published post with local changes
  - Press preview on published post with local changes
  - Save it locally.
  - "Push" the post **as a remote auto-save** via the UploadService.
  - Show an activity indicator during saving/upload.
  - Wait for the upload to finish.
  - Get the preview URL from the updated PostModel.
  - If the upload fails, stays on the editor and show a snackbar.
  - If the upload succeeds open the URL in our Webview.

[1] TBC: We might need to temporarily change the post status.

**Comment by yaelirub** [comment]
A couple of notes from iOS implementation that might help.
>TBC: We might need to temporarily change the post status.

We added a new "autosave" status .

>Show an activity indicator during saving/upload.

For draft we are showing "Saving...",  for published we are showing "Generating preview..." 

>Get the preview URL or forge it locally

For draft we are constructing the url from the permalink based on the authentication (nonce, cookie or none)

**Comment by shiki** [comment]
Subscribing @wordpress-mobile/ravenclaw
