### ISSUE TITLE
Improve failed upload media UI in the editor(s?)

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9730]
Failed media upload overlay is a bit scary:

![Screenshot_20190426-170208](https://user-images.githubusercontent.com/40213/56817152-4c153080-6845-11e9-848c-baa204664551.jpg)

iOS version looks better:

![img_0790c303f4e5-1](https://user-images.githubusercontent.com/40213/56817268-90083580-6845-11e9-9c4e-af9d859ce546.jpeg)

We should add the same message under the retry icon.

**Comment by designsimply** [comment]
😂 (ponypony)

**Comment by malinajirka** [comment]
Just for completeness: The image overlay looks scare just in Aztec.

The following image is from Android - Gutenberg.
![Screenshot_1557229428](https://user-images.githubusercontent.com/2261188/57296876-5b5e6e80-70ce-11e9-8552-e6e40e35896d.png)

**Comment by maxme** [comment]
I had a look at how Aztec was managing image overlays, and the missing text issue is definitely coming from [an Aztec limitation](https://github.com/wordpress-mobile/AztecEditor-Android/blob/8b30f7966520973c23a2f06aecd6a974c5970863/aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecMediaSpan.kt#L56-L78).

I see 2 solutions to add text, both are kind of hacky (will use [Canvas.drawText](https://developer.android.com/reference/android/graphics/Canvas.html#drawText(java.lang.CharSequence,%20int,%20int,%20float,%20float,%20android.graphics.Paint))) and I'm not sure how it will look.

I'll remove the red overlay as it's quite scary, do some overpaint and is not needed if we have an icon + text (like in Gutenberg or Aztec iOS).
