### ISSUE TITLE
Reader + Notifications: Unable to open a public post in System Browser

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#9766]
### Expected behavior
Be able to open the current post in the Reader Post Screen in the external browser.

### Actual behavior
The Reader Post screen is loaded again instead, on the top of the current one.
See the video: https://cloudup.com/cdYeRtLYBRZ

### Steps to reproduce the behavior
- Publish a post on a blog you're following
- You should see a notification that a post is published in your notifications stream
- Tap on the notification and access the Reader Post screen
- Tap on the Browser icon in the top bar
- Boom! Keep tapping!

**Comment by planarvoid** [comment]
> You should see a notification that a post is published in your notifications stream

@daniloercoli I can't really reproduce this notification and all the other links from notifications to posts seem to work.

> Publish a post on a blog you're following

doesn't trigger a notification. Does it happen to you also from the other notifications?

**Comment by daniloercoli** [comment]
> doesn't trigger a notification. Does it happen to you also from the other notifications?

Have you enabled notification for new posts in settings?
![Screenshot 2019-10-11 at 12 08 44](https://user-images.githubusercontent.com/518232/66643898-fe885680-ec1f-11e9-9937-88a3de597ff9.png)

**Comment by planarvoid** [comment]
thanks for the tips @daniloercoli , I had no idea these settings exist. I've managed to get a notification and try the flow and I can't reproduce the bug:

![browser_from_notifications](https://user-images.githubusercontent.com/1079756/66986248-d3d64c00-f0be-11e9-9f5a-0f262ed6866a.gif)

**Comment by develric** [comment]
I was unable to reproduce as well; I tried on Pixel 3 Emu API29 and OnePlus 7T API30 with WPAndroid 12.2, 12.3 (that should be the released versions before and after the alpha-168 mentioned in the issue) and current develop (at this point in [history](https://github.com/wordpress-mobile/WordPress-Android/tree/a860d8b29eb097aed016d28092021c4fa756a2c4)).

I guess we may be missing some specificity in the test scenario context or step to reproduce? @daniloercoli are you still able to reproduce this in your test scenarios? Thanks 🙇

**Comment by daniloercoli** [comment]
Not able to reproduce this issue anymore. Closing it.
