### ISSUE TITLE
[Post List] Apply maximum width to card view

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#9784]
For consistency between post list and reader, we should apply the same maximum width to the post list card view and for consistency with the pages list we should follow the constraints there for the post list list view.

**Comment by malinajirka** [comment]
@SylvesterWilmott I'm not sure I understand this ticket correctly, but the maxWidth parameter seems to be consistent.

![maxwidth](https://user-images.githubusercontent.com/2261188/61635815-abdc7580-ac94-11e9-9b55-deb3366c7628.jpg)

**Comment by SylvesterWilmott** [comment]
>I'm not sure I understand this ticket correctly, but the maxWidth parameter seems to be consistent.

You're right. We can close this then.
