### ISSUE TITLE
Uploading a draft shows mildly horrifying "Uploading Post" message

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#9790]
Suggested in #9774 by @mattmiklic in [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/9774#issuecomment-488818593). 

### Expected behavior

The message should show "Uploading Draft". 

### Actual behavior

@mattmiklic:

> When the local draft begins to upload, the status changes from "Local Draft" to "Uploading Post." My first reaction was to fear that my draft was being published, not just saved as a draft on the server. Could we change this to "Uploading Draft" so it's clearer that it's still a draft?

<img src="https://user-images.githubusercontent.com/198826/57040634-4a6cb380-6c1d-11e9-8850-9138c2a4996a.gif" width="320">

### Steps to reproduce the behavior

This will need #9774 to be merged first. 

1. Create a draft while offline
2. Go back online

The draft should auto-upload, showing the _uploading_ message.

**Comment by malinajirka** [comment]
@shiki AFAIU we want to show "Uploading draft" instead of "Uploading post" whenever a draft is being uploaded - even when we trigger the upload manually. Is this really dependant on #9774?

**Comment by shiki** [comment]
@malinajirka I was probably thinking it's easier to test if that was merged first. But you know the code better than me, so I'm definitely wrong. 😁

**Comment by malinajirka** [comment]
👍 I believe opening the editor and clicking on the back button will trigger the upload. I'll look into it and I'll make sure it won't cause any or only easy to resolve conflicts;).
