### ISSUE TITLE
Media Uploading notification doesn't seem to be in synch with the media uploading/uploaded

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#9802]
### Affected device(s)
Samsung S9 on Android 9.
Can't reproduce the issue on my other testing device (Nexus 5X on Android 7.1). Also tried on emulators with no luck.
@malinajirka confirmed that he was not able to reproduce this exact issue on his devices (Emulator + Pixel 3 Android 9).

### Expected behavior
The Uploading notification to be correctly cleared if I stop the Media Uploading by tapping on the media and selecting "Stop Uploading".

### Actual behavior
The network connection is correctly stopped, but the notification is still there in the notifications center, the progress indicator is of course stuck at the current position, and a new Upload failed notification is added to the stack.

![device-2019-05-07-120327](https://user-images.githubusercontent.com/518232/57291781-66120700-70c0-11e9-949d-27a3f6d47646.png)

### Steps to reproduce the behavior
- Start Aztec
- Add a Video
- Tap on the video and select Stop Uploading
- See the notification still in the system NC, and the new notif about upload failed

See also **Scenario 3** [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9802#issuecomment-490028057).

I also noticed that sometimes weird things happen with media notifications.
- 2 uploading notifications not grouped into 1
![device-2019-05-06-162732](https://user-images.githubusercontent.com/518232/57234889-f6e5d580-7021-11e9-9ea0-b62d0d6084b0.png)

- Tried to upload 2 files, after the 1st video finished I got this in the notifications center:
![device-2019-05-06-161343](https://user-images.githubusercontent.com/518232/57235423-1fba9a80-7023-11e9-8962-f5185ce4f8f3.png)
(Not sure of the steps to replicate this issue)

Tested on current develop - `d3c89dd7d4dcd3d138bc544642b3ace38cb2a96a`

cc @mzorz 
@marecar3

**Comment by daniloercoli** [comment]
I've investigated this a bit further with images, and I see uploading notifications reporting wrong info when adding images to the editor and there are errors uploading them.
EX:
- Start a new post
- Add 4 pictures to the editor
- 2 of those media fail uploading right immediately, and there is the red overlay over them 
- The notifications center reports this info:
![device-2019-05-06-174020](https://user-images.githubusercontent.com/518232/57236772-1121b280-7026-11e9-85e6-cf62e877a150.png)

- When the 2 "good" pictures finishing to upload:
![device-2019-05-06-174225](https://user-images.githubusercontent.com/518232/57236976-7f667500-7026-11e9-91e8-0c9f08707579.png)

And then the app is stuck in the current state with notifications.



**Note**
In another test of mine I tapped retry in the editor and ended up in the following notification:
![device-2019-05-06-173802](https://user-images.githubusercontent.com/518232/57236591-bee09180-7025-11e9-8d7e-8b71920b6f43.png)

**Comment by daniloercoli** [comment]
**Scenario no. 3**
- Start a new post
- Add media to it
- Save it as draft and exit the app
- The media started uploading correctly
- If the media fails uploading for some reason, the notification is NOT refreshed

https://cloudup.com/ccVRBOLfH28

- Opening the app in posts list it says "Uploading media..." for the post (see the linked pictures above)

**Comment by designsimply** [comment]
I tried testing this a few times using WPAndroid alpha-170 on Pixel 3 Android 9 but I was unable to see any notifications in the system NC ([41s](https://cloudup.com/ck18CH7Cj-n)). I tried checking notifications settings for the app itself and all looked well ([screenshot](https://user-images.githubusercontent.com/1119271/57547567-0152e880-731c-11e9-9569-8cdabba35e16.png)).

**Comment by designsimply** [comment]
I was able to see this happen today while testing with WPAndroid alpha-171 on Pixel 3 Android 9 with these steps:

1. Create a new post and start uploading an image.
1. Turn off both cellular data and WiFi (separate from airplane mode).
1. Notice the image begins uploading again.
1. Notice the system notification saying "Uploading…" gets stuck open even after the image has successfully uploaded after network connectivity was returned.

<img src="https://user-images.githubusercontent.com/1119271/58995660-54e91280-87b2-11e9-9620-1806715360e7.png" width="270" alt="Screenshot_20190605-164451">
<sup>Note: this notice seems like it should go away but it has been stuck there for quite a while *after* coming back from going offline in the middle of an image upload.</sup>

@malinajirka would you mind giving this one another go to see if you are still unable to replicate the problem in testing?

**Comment by malinajirka** [comment]
I think [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/9956) might solve the issue. I have been testing it on my Pixel 3 a few days ago and I never ended up with a stuck notification.

**Comment by malinajirka** [comment]
@designsimply I'd suggest closing this issue until someone encounters it again. I tried to reproduce it today without success. I still hope it got fixed in #9956.

**Comment by designsimply** [comment]
👍closing per the recommendation (and the hope it was fixed in #9956 🙂) with an ask to re-open if it comes up again.
