### ISSUE TITLE
Local draft with more than one media fails to upload

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#9804]
### Expected behavior

A local draft with more than 2 media should be uploaded if there is an internet connection.

### Actual behavior

The upload fails even after retrying multiple times.
 
<img src="https://user-images.githubusercontent.com/198826/57248627-11a75280-7000-11e9-8106-3945b59e685b.gif" width="320">

### Steps to reproduce the behavior

1. Go offline
2. Create a draft post
3. Add 2 images to the post 
4. Exit the editor
5. Go online
6. Tap on the _Retry_ button. 

If there is only one media attached to the draft post, the upload succeeds.

Tested on Pixel 3, Android 9, WPAndroid `develop` (2e3b2a60b2a83d28628f39ada84b7a7449ead627)

**Comment by malinajirka** [comment]
Possibly related to https://github.com/wordpress-mobile/WordPress-Android/issues/9802

**Comment by shiki** [comment]
Did not get much progress on this. There's a lot about the `UploadService`, `PostUploadHandler`, and `MediaUploadHandler` classes that I found difficult to understand. The next time I look at this, I'll probably start by documenting how these classes work.
