### ISSUE TITLE
Sharing Settings: "Learn more" links are unresponsive

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9828]
Steps to reproduce:

1. Go to Sharing > Connections.
1. Tap on Facebook > "Learn more" (and note that the link works).
1. Tap on Twitter > "Learn more". 
1. Tap on Tumblr > "Learn more".
1. Tap on LinkedIn > "Learn more".

**Result:** Sharing > Connections > Twitter, Tumblr, LinkedIn "Learn more" links do not work. ([31s](https://cloudup.com/cECksERN1Ot))

<img src="https://user-images.githubusercontent.com/1119271/57477092-26c8ef00-7255-11e9-9618-066a8e127c30.png" width="270" alt="Screenshot_20190509-122042">
<p style="clear:both;"><sub>Tested on WPAndroid alpha-170 on Pixel 3 Android 9 using a WordPress.com Free site `wibblywobblytimeywimey.travel.blog` for testing.</sub></p>

```
70 - [May-09 18:12 SHARING] publicize service > created
71 - [May-09 18:12 SHARING] publicize service > destroyed
72 - [May-09 18:12 UTILS] No valid URLs passed to URLFilteredWebViewClient! HTTP Links in the page are NOT disabled, and ALL URLs could be loaded by the user!!
```

h/t Pranali for the original report (internal reference: p5T066-Pl-p2#comment-2807).

**Comment by hafizrahman** [comment]
Looking at this.
