### ISSUE TITLE
OAuth vulnerability in the official Wordpress app

### ISSUE THREAD

**Issue by tamjidrahat** [wordpress-mobile/WordPress-Android#9829]
We found you bundled both App ID and App secret for Wordpress OAuth login within your application code (in file: **org.wordpress.android.modules.AppConfigModule.java**) in the official Wordpress Android app in Google Play. This would allow an attacker to easily retrieve the App ID and App secret by simply decompiling the apk file.

A malicious attacker, having access to both App ID and App secret of your application, could create a modified Wordpress application to trick benign users to login in Wordpress. To this end, attacker can obtain user's access token and use it to have full access to user's account.

How to fix this?
Most secured way to fix this is to store the app ID and secret in the backend server and perform the authentication API call from server-to-server. If that's not possible, such secrets can be stored as encrypted format using secured storage such as Android Keystore. This gives some extra layer of security against the attack scenario mentioned above.

Looking forward to having your respond on this. Thank you very much.

**Comment by designsimply** [comment]
Thank you for the report. This was discussed by one of the teams working on mobile app releases and by the security team and was found not to be a threat. I will see about providing a more detailed explanation for you after I review all of the correspondence.

<sub>(internal reference: p3btAN-160-p2)</sub>
