### ISSUE TITLE
After a failed publish, hitting the retry button several times publish several duplicated posts

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9845]
After a failed publish, hitting the retry button several times publish several duplicated posts.

### Expected behavior

Only publish one post, whatever the number of times "retry" is tapped.

### Steps to reproduce the behavior

- Try to publish a post with poor network condition.
- Publish failed, see the "retry" button in the post list.
- Hit the "retry" button N times.
- Connection works well -> refresh the list -> notice N duplicate posts published.

Note: this was experienced by one of our internal tester @hlashbrooke - I tried to reproduce it but I was unable to do so. There might be a missing step or some missing information.

WPAndroid alpha-170

**Comment by hlashbrooke** [comment]
Some additional info from when this happened to me is that the error I received when attempting to publish simply said `GENERIC_ERROR` so it wasn't anything helpful.

It's worth highlighting that I didn't have _no_ network connection, it was simply too poor to manage publishing a post, so my guess about what happened is that it did actually publish the post each time but the app wasn't aware that it happened and just received a generic error. Then when my connection improved, I saw all the published posts in my feed (along with all the x-posts from it of course).

**Comment by maxme** [comment]
> it did actually publish the post each time but the app wasn't aware that it happened and just received a generic error. T

Yep, that's probably right, we should maybe hide the retry button if we get a timeout or if we can't read the response from the "create new post" network call.

**Comment by maxme** [comment]
Side note: I was able to repro the `GENERIC_ERROR` message in the Post List (pretty bad UX):

![Screenshot_1557750652](https://user-images.githubusercontent.com/40213/57621499-e5ee1480-758b-11e9-9efc-bd2f0d6a9602.png)

I used network throttling + enable airplane mode to generate a timeout:
```
2019-05-13 14:30:44.999 16707-16707/org.wordpress.android.beta E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.2/sites/124661775/posts/new/?context=edit&locale=en_US
    com.android.volley.TimeoutError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:147)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
2019-05-13 14:30:45.001 16707-16707/org.wordpress.android.beta D/WordPress-API: Dispatching action: UploadAction-PUSHED_POST
2019-05-13 14:30:45.013 16707-19791/org.wordpress.android.beta D/WordPress-API: Dispatching action: PostAction-PUSHED_POST
```

**Comment by malinajirka** [comment]
I'm not sure what would be the best way to solve this issue.

>Yep, that's probably right, we should maybe disable the retry button if we get a timeout or if we can't read the response from the "create new post" network call.

If we simply disable it, we might prevent the user from publishing the post, right? AFAIK the button is disabled when the (re)upload is in progress, right?


This is a common synchronization problem and one of the simplest solution is to create a UUID for each post on the client side. When the server receives multiple "create post" requests with the same UUID, it just returns http 409 or similar. But it'd require significant changes on both client and api :(.

**Comment by maxme** [comment]
> If we simply disable it, we might prevent the user from publishing the post, right?

That's right, it's tricky, because we would need to re-conciliate an uploaded Post and a local Post without being sure they're linked: The local post don't know about the remote id since we didn't get the server reply.

> AFAIK the button is disabled when the (re)upload is in progress, right?

Yes, buttons (all of them) are disabled during upload.

> This is a common synchronization problem and one of the simplest solution is to create a UUID for each post on the client side. When the server receives multiple "create post" requests with the same UUID, it just returns http 409 or similar. But it'd require significant changes on both clients and api :(.

That's right, I think the only good solution to this problem is to change the API behavior. I guess the clients change will be pretty minor.

Client-only solutions will only be band-aids and have a part of uncertainty/risk.

**Comment by maxme** [comment]
Note that we're waiting for API changes or inputs on this internal thread paaHJt-Ac-p2

**Comment by elibud** [comment]
As we don't have an ETA for an API update, can we proceed with client side guards that would reduce the number of occurrences of this one please?

**Comment by designsimply** [comment]
Removing the `[Pri] High` label as it was only reported by one person internally and we don't have a record here of any other user reports of this problem. Removing the `Blocked` label based on @elibud's request to proceed with client side safeguards first.

**Comment by diegoreymendez** [comment]
@maxme @malinajirka - I'm trying to understand the underlying issue here, but having some trouble doing so.  What confuses me about this issue is that we don't have this problem in iOS (to the best of my knowledge), even without API support.

This makes me think there's probably something I ignore about the way publishing works in Android that's different from iOS.

Can we maybe leverage @shiki 's expertise to do a quick review of why this is a problem in Android but not in iOS?

PS: I don't want us to spend a lot of time in this, but if doing a quick comparison is possible I'd like us to at least consider it.

**Comment by maxme** [comment]
> Can we maybe leverage @shiki 's expertise to do a quick review of why this is a problem in Android but not in iOS?

**Comment by SiobhyB** [comment]
I attempted to replicate this as part of a recent triage effort (ref: p9ugOq-1Og-p2) but wasn't able to. Here's what I tried:

* Drafted a new post within the app.
* Enabled airplane mode.
* Attempted to publish the draft. 
* When the publish failed, I tapped the **More** option alongside the draft in the posts list and then attempt to **Retry** several times.
* Disabled airplane mode.
* Published the post and reviewed the posts list.

In my testing, the post was only ever published one time. The testing was done on a Pixel 5, Android version 11, and version alpha-285.

As this issue has been historically difficult to replicate, however, I'm hesitant to close based on the above testing. 

While digging into this further, I also found [this newer, related issue](https://github.com/wordpress-mobile/WordPress-Android/issues/13137), where the problems with the API are again discussed.

@maxme, @malinajirka, do you think it's fair to close one of these issues as a dupe? (I'm leaning towards closing this one as @malinajirka went into a bit more detail around a possible fix in the newer issue, let me know what you think!)

**Comment by malinajirka** [comment]
@SiobhyB  I remember I saw a PR on the backend, which implemented a check to make sure two posts with identical content don't get published. I can't find it right now, but unless we are able to replicate the issue we might even consider closing both issues. Either way, I agree that closing at least this issue in favor of the newer issue make sense.

**Comment by SiobhyB** [comment]
Great, thanks for confirming!
