### ISSUE TITLE
Site Creation: Track event "support_opened"

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9855]
## Description:

Since iOS is tracking the event "wpandroid_support_opened", we need to do this in Android too.

The will be useful to know if our New Site Creation flow is causing particular trouble.

There are no custom properties for this event.

**Comment by maxme** [comment]
This was fixed recently via https://github.com/wordpress-mobile/WordPress-Android/pull/9824

**Comment by diegoreymendez** [comment]
@maxme - Thanks.  I noticed the event in tracks recently, but couldn't find the matching issue adding support for this.

**Comment by diegoreymendez** [comment]
I'm removing this issue from the project as nothing was really done.
