### ISSUE TITLE
Site Creation: Fix deep linking in first-post congratulations email.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9864]
## Description:

After creating a WP.com site, and right after publishing the first post, the user is getting a mail in their inbox titled: "Congratulations on your first post!".

This email has a blue button to start a new post.

We need to ensure both this link is opened by the App.

## Images:

![IMG_06FCCD794808-1](https://user-images.githubusercontent.com/1836005/57740014-2d5bca00-768c-11e9-83fa-b351e970d2eb.jpeg)

## Corresponding iOS issue:

https://github.com/wordpress-mobile/WordPress-iOS/issues/11693

**Comment by maxme** [comment]
I thought a bit about this one and we can't deep link a standard url like `https://ddancestore.wordpress.com`, this would open every wpcom site in the app. We need to add something to add a parameter to the URL (and update the email template). For example in this email the link to `ddancestore.wordpress.com` could be `https://ddancestore.wordpress.com/?from=email`

Also I'm not sure what's the link on "Start a New Post" action (can you post it here?), but if it's could have `https://wordpress.com/post/ddancestore.wordpress.com` or something like that, it should be deeplink-able in the apps.

Last question: should all links in this email deep linked? For example our `plans` feature in the app is pretty bad, we should open the Web page instead.

**Comment by maxme** [comment]
I created a new site and posted a new post to get that email, some notes:

- The link on the "Start a New Post" button redirects to `https://wordpress.com/post/4poniessss.home.blog` (which could be deeplinked in the app).
- I created a site with a free custom domain `4poniessss.home.blog`, for some reason, it's not linked in the email, see [here](https://user-images.githubusercontent.com/40213/57839787-a0b62680-77c7-11e9-9cbd-bc2beffb8b24.png). I don't know if the email template was changed. If we want to be able to catch any kind of custom domains (free or not), the link must be something like `https://wordpress.com/view/4poniessss.home.blog` and not a direct link.
- The `plan` link redirects to `https://wordpress.com/plans/`, IMO it should redirect to `https://wordpress.com/plans/4poniessss.home.blog` and should not be deep linked in the app.

**Comment by diegoreymendez** [comment]
From what I'm reading about Universal links in iOS, I believe the same approach should work there.

Also - the plans link should NOT redirect to the App, that's correct.

**Comment by maxme** [comment]
Note, it's easy to test URL intents with `adb`:

```
adb shell am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d https://wordpress.com/post/ddancestore.wordpress.com
```

**Comment by diegoreymendez** [comment]
Updated the issue description, we only need to ensure "New Post" deep links into the Apps.
