### ISSUE TITLE
Notification list sorting by date sometimes swap 2 notes

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#988]
It happens all the time with these 2 notifs https://cloudup.com/cA6sx0cB8CF - they probably have the same timestamp, I guess the list is resorted at some point with a different comparison method (or first come from a db query and sorted after).

**Comment by roundhill** [comment]
@maxme have you seen this again? I'm inclined to close this one as I haven't heard any other reports.

**Comment by rachelmcr** [comment]
I haven't seen any other reports of this issue. I'm closing this for now, and we can reopen if it becomes an issue again.
