### ISSUE TITLE
Post List: option to toggle multiple users' posts should not be present on a single-user site

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9881]
I expected not to see the toggle for Me/Everyone in the Post List on a single-user site.

Steps to reproduce:

1. On the web, go to My Sites > [multi-user site] > Blog Posts.
1. Observe that there is a toggle to see posts for Me or Everyone.
1. On the web, go to My Sites > [single-user site] > Blog Posts.
1. Note there is not a toggle to view Everyone's posts.
1. Repeat the same steps in the app and compare the results.

<strong>Result:</strong> on the web the Me/Everyone toggle for the Post List only appears for a multi-user site and does not appear for a single-user site. ([1m6s](https://cloudup.com/cWSpVXoPWhk))

<img src="https://user-images.githubusercontent.com/1119271/57896268-2d370800-780d-11e9-945e-5c1ddce83119.png" width="270" alt="Screenshot_20190516-190106">
<sup>Tested with WPAndroid 12.4-rc-3 on Pixel 3 Android 9.</sup>

Found while beta testing WPAndroid 12.4.

**Comment by AjeshRPai** [comment]
This has been fixed in the current Android app version.
