### ISSUE TITLE
Stats Expandable View Does Not Animate Smoothly on Collapse

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#9888]
### Expected
The view below an expandable list row animates smoothly when the expandable list row is expandable and collapsed.

### Observed
The view below an expandable list row animates smoothly when the expandable list row is expandable, but not collapsed.

#### Note
Ideally, the expand/collapse chevron, the expand/collapse row, and the view below the expand/collapse row all animate smoothly.  See the animations below for illustration.

Expected|Observed|Ideal
-|-|-
![stats_before](https://user-images.githubusercontent.com/3827611/56392406-39b44a80-61e6-11e9-91c1-48884c41b7f6.gif)|![stats_after](https://user-images.githubusercontent.com/3827611/56392414-3b7e0e00-61e6-11e9-9fd3-f9d5476644f0.gif)|![expandable](https://user-images.githubusercontent.com/3827611/58037702-3d8c0300-7aeb-11e9-80c0-1ce051e6d09c.gif)

### Reproduced
0. Select site with at least one post.
1. Go to ***Sites*** tab.
2. Tap ***Stats*** item.
3. Tap ***Years*** tab.
4. Tap author in ***Authors*** section.
5. Notice view animates smoothly when view is expanded.
6. Tap author in ***Authors*** section from Step 4.
6. Notice view does not animate smoothly when view is collapsed.

##### Tested
Google Pixel 3 on Android 9.0 with alpha-171

**Comment by irfano** [comment]
This can no longer be reproduced.
