### ISSUE TITLE
Offline Support: editor action buttons confusion for published posts.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9913]
The options we are giving our users to save changes to a published post are confusing.

## Steps to reproduce:

1. Open a published post.
2. Make some edits.
3. Notice that the main action button is title "Update".
4. Tap on it: this will publish the changes.
5. Reopen the same post and make more edits.
6. Tap "..." and notice that the second action button is also titled "Update".
7. Tap on it, and notice that the changes are saved locally.

This is confusing, because we have two different actions with the same name.

## Proposed changes:

1. If the site is a WP.com site, we should consider using the `autosaves` endpoint when pressing the back arrow in the editor.
2. Change the title on the main action button so that it reads "Publish" instead of "Update".

@wordpress-mobile/ravenclaw

**Comment by diegoreymendez** [comment]
I'm not adding the "Offline Support" label to this issue since it's only marginally related, but I'm adding it to our project since it's too close to our current work to ignore (IMHO).

**Comment by shiki** [comment]
@diegoreymendez This seems similar to #9825. Should we merge them?

**Comment by diegoreymendez** [comment]
@shiki - Thanks for being on top of things.  This started with some other observations from my end and ended up becoming this issue... considering @maxme gave a very good description to the original issue I'm fine with closing this.
