### ISSUE TITLE
Previews: very large gaps appear for page breaks

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9915]
Steps to reproduce:

1. Create and publish a post with the block editor that has more than one block.
1. Add a page break block between other blocks.
1. Go to More > Preview.
1. Check to see if the spacing looks reasonable.

<strong>Result:</strong> a very large gap of empty space appears where page break blocks are used in the editor.

<img src="https://user-images.githubusercontent.com/1119271/58204660-fbed8a80-7c99-11e9-827e-809a38635435.png" width="270" alt="Screenshot_20190522-134955"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/58204665-ff811180-7c99-11e9-9e95-c5c28946e75c.png" width="270" alt="Screenshot_20190522-135009">
<sub>Tested with WPAndroid alpha-171 on Pixel 3 Android 9.</sub>

**Comment by maxme** [comment]
This is our local preview screen. We can close this ticket when we drop local previews #9729

**Comment by maxme** [comment]
Local previews have been dropped 🏆
