### ISSUE TITLE
Previews: headings aren't displayed correctly

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9916]
Steps to reproduce:

1. Create a new post with the block editor.
1. Add a heading block.
1. Add a few paragraph blocks.
1. Go to More > Preview.
1. Check to see if the heading appears as expected.

<strong>Result:</strong> headings aren't displayed correctly in previews.

Editor view: | Preview:
------------ | -------------
<img src="https://user-images.githubusercontent.com/1119271/58205520-f5f8a900-7c9b-11e9-8798-4ac3691dc209.png" width="270" alt="Screenshot_20190522-141249"> | <img src="https://user-images.githubusercontent.com/1119271/58205569-1294e100-7c9c-11e9-90db-277d29f29335.png" width="270" alt="Screenshot_20190522-141257">
In-app browser: | Chrome view:
<img src="https://user-images.githubusercontent.com/1119271/58205580-16286800-7c9c-11e9-91b3-f8891d72aaee.png" width="270" alt="Screenshot_20190522-141329"> | <img src="https://user-images.githubusercontent.com/1119271/58205588-1a548580-7c9c-11e9-83ad-7d3a76cb1971.png" width="270" alt="Screenshot_20190522-141343">

<sub>Tested with WPAndroid alpha-171 on Pixel 3 Android 9.</sub>

**Comment by maxme** [comment]
This is our local preview screen. We can close this ticket when we drop local previews #9729

**Comment by maxme** [comment]
Local previews have been dropped 🏆
