### ISSUE TITLE
Previews: image captions are not centered in previews but are centered in the block editor and on the web

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9917]
Steps to reproduce:

1. Create a new post with the block editor.
1. Add an image block including a caption.
1. Go to More > Preview.
1. Publish the post.
1. Compare the preview to the editor and web view after publishing.

<strong>Result:</strong> image captions appear centered in the editor and on published post but are not centered in previews.

Editor view: | Preview:
------------ | -------------
<img src="https://user-images.githubusercontent.com/1119271/58206697-73bdb400-7c9e-11e9-9feb-bf52048ff7c8.png" width="270" alt="Screenshot_20190522-142905"> | <img src="https://user-images.githubusercontent.com/1119271/58206706-77e9d180-7c9e-11e9-81a9-3432c59f4f33.png" width="270" alt="Screenshot_20190522-142914">
In-app browser: | Chrome view:
<img src="https://user-images.githubusercontent.com/1119271/58206732-8a640b00-7c9e-11e9-8cd3-0c92e45d06eb.png" width="270" alt="Screenshot_20190522-142932"> | <img src="https://user-images.githubusercontent.com/1119271/58206737-8cc66500-7c9e-11e9-94e3-b7975ccd49ef.png" width="270" alt="Screenshot_20190522-142945">

<sub>Tested with WPAndroid alpha-171 on Pixel 3 Android 9.</sub>

**Comment by maxme** [comment]
This is our local preview screen. We can close this ticket when we drop local previews #9729

**Comment by maxme** [comment]
Local previews have been dropped 🏆
