### ISSUE TITLE
Previews: links to YouTube videos and Google Maps don't work

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9918]
Steps to reproduce:

1. Create a new post.
1. Add a link pointing to a YouTube video.
1. Add a link pointing to a Google Maps link share.
1. Go to More > Preview.
1. Tap on each link to see if they work.

<strong>Result:</strong> links to things like YouTube videos or Google Maps do not work in previews. ([2m31s](https://cloudup.com/cOny4mkVylB))

<img src="https://user-images.githubusercontent.com/1119271/58207650-512c9a80-7ca0-11e9-8eb3-7d79e2e49ff6.png" width="270" alt="Screenshot_20190522-144414">
<sub>Tested with WPAndroid alpha-171 on Pixel 3 Android 9.</sub>

**Comment by maxme** [comment]
This is our local preview screen. We can close this ticket when we drop local previews #9729

**Comment by maxme** [comment]
Local previews have been dropped 🏆
