### ISSUE TITLE
Run Android UI tests on CircleCI via Sauce Labs

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#9919]
I'd like to explore the idea of running our existing UI tests on CircleCi via SauceLabs... Can we set up a branch looking at what that would look like?

**Comment by rachelmcr** [comment]
Are there specific benefits you hope to get by running the UI tests via SauceLabs, compared to our current setup?

**Comment by JavonDavis** [comment]
At the time my main reason for this is that we have an open source plan for Sauce Labs and this was an attempt at reducing that cost and utilizing the free VMs we had available on Sauce  Labs. I had explored this and compared it with our current payment plan with Firebase and discussed it with James and the cost was negligible and wasn't worth the effort for the change. 

I think we can close this.

**Comment by rachelmcr** [comment]
Got it. Thanks for the update!
