### ISSUE TITLE
Can't share highlights group from Photos app

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#992]
If you are on the 'highlights' tab in the Photos app, there is a share button where you can share all of the pictures you captured in a day. The WordPress app doesn't show as a share target.

![screen shot 2014-02-27 at 3 08 27 pm](https://f.cloud.github.com/assets/789137/2289246/b2e93838-a004-11e3-9f86-81b60a585cef.png)

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
