### ISSUE TITLE
Cannot connect to Facebook to automatically publish posts to a page

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-Android#9924]
### Expected behavior
Connect to my Facebook page so that my Wordpress posts also publish to my Facebook page

### Actual behavior
When connecting to a Facebook page, after the flow is complete a toast appears saying 'An Error occured' and it does not seem to have been successful

### Steps to reproduce the behavior
1. In the Android app, go to a site
2. Choose sharing under configuration near the bottom
3. There is the option to automatically share on networks. Choose Facebook.
4. Tap the 'connect' button below the information
5. Go through flow the Facebook steps (login/continue, choose the page to use with wordpress, choose what wordpress is allowed to do)
6. See message 'you've now linked Wordpress to Facebook', which makes it seem like we've been successful
7. Returning to the same screen as step 4 within wordpress, a toast message appears saying 'An error has occured'

##### Tested on [device], Android [version], WPAndroid [version]
A user reported on ticket 2047729-zen 
I have verified the same issue is happening to me on a Google Pixel 3a, Wordpress for Android v 12.4, Android version 9

##### Related ticket
https://github.com/wordpress-mobile/WordPress-Android/issues/8715
But in that case the user has no Facebook pages. In this case, even when having a Facebook page an error occurs.

![user screenshot](https://user-images.githubusercontent.com/50576199/58270351-7a712780-7d81-11e9-9890-5b36057ebccb.png)

**Comment by osullivanchris** [comment]
Noting that the user who reported this issue was an admin on a public Facebook page. They were able to connect successfully on the desktop/web version.

**Comment by Josimarcsilva** [comment]
Automatic sharing on social networks is one of the most important features of the App. The error reported above is preventing the use of this incredible feature.

Is there any forecast to correct the above error?
Thank you.

**Comment by shiki** [comment]
PR #10251 adds a friendlier error message if there is no page. As for this issue, I could not reproduce it. I can reproduce the error if:

- The Facebook account has no Pages.
- The Facebook account has Pages but did not select them during the connection flow. 

If I select a Page, I can always consistently link with Facebook.

**Comment by marecar3** [comment]
Hey, @osullivanchris @Josimarcsilva I would like to add one more case which has happened to me.

In short, there is a case that the desired scenario won't work if the page isn't published. Here is the full description: https://github.com/wordpress-mobile/WordPress-Android/pull/10251#issuecomment-513330229.

cc: @shiki

**Comment by malinajirka** [comment]
I was able to reproduce this issue when I set "Don't keep activities" in the developer settings.

1. My Site
2. Sharing
3. Facebook
4. Connect
5. Enter your Facebook credentials
6. The Webview asks you to provide 2-fa code
7. Switch to the Facebook app and get the code [in case your account isn't 2-fa protected, just move another app into foreground and then bring the WordPress app back]
8. Finish the FB login and give the app access to at least one published fb page
9. An error occurs

I created a fix in https://github.com/wordpress-mobile/WordPress-Android/pull/10376.
