### ISSUE TITLE
After publishing while offline, the "retry" button on the Post List button will publish the Post

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9933]
Imported from this comment https://github.com/wordpress-mobile/WordPress-Android/issues/9555#issuecomment-492858217

> This is how things currently work right now:
> 
> - Android: Publishing while offline and retrying will lead to the post being uploaded and **published**
> - iOS: Publishing while offline and retrying will lead to the post being uploaded as a draft
> 
> I'm not sure which one is right but Android's behavior is scary for me as a user. 

## Decision
As the user intended to publish the post, retrying should also publish the post
To clarify, we should amend the error state to mention posting. Error message should say "Could not upload media. Post not published." Then its clear that retry relates to posting, not just media.
To make this work we need to differentiate the error state in publishing/saving/scheduling scenarios. 

1. User publishes and media upload error (use case in this issue)
Error Message: "Could not upload media. Post not published."
Action and behavior: Retry. Retrying publishes the post if media uploads successfully

2. User schedules and media upload error (scheduling rather than publishing)
Error Message: "Could not upload media. Post not scheduled."
Action and behavior: Retry. Retrying schedules the post if media uploads successfully

3. User saves and media upload error (user did not intend to publish)
Error Message: "Could not upload media."
Action and behavior: Retry. Retrying only retries uploading the media as the user has not changed the post state

## Related Issues

https://github.com/wordpress-mobile/WordPress-iOS/issues/11420

**Comment by shiki** [comment]
Subscribing @wordpress-mobile/ravenclaw

**Comment by maxme** [comment]
Note: the "retry" button only appear when there is a failed upload on a media. There is also a "retry" button in the notification.

post list | notification
-|-
![Screenshot_1558708650](https://user-images.githubusercontent.com/40213/58335719-7fe27680-7e42-11e9-9b20-ff395b985733.png) | ![Screenshot_1558708743](https://user-images.githubusercontent.com/40213/58335723-81ac3a00-7e42-11e9-8077-c5f2bd839f55.png)



I agree with this comment, I think "retry" is unclear in this case. I prefer the iOS approach.

**Comment by shiki** [comment]
I opened a discussion related to this in https://github.com/wordpress-mobile/WordPress-iOS/issues/11420.

**Comment by yaelirub** [comment]
Hey @maxme, is there a decision for this one (there's an iOS related one) or do we need to discuss more?

**Comment by maxme** [comment]
Not yet, there is a draft PR for it: https://github.com/wordpress-mobile/WordPress-Android/pull/10053

Added the "Needs design" label since it's UX issue.

**Comment by osullivanchris** [comment]
Not sure where the best place is but I commented on [11420](https://github.com/wordpress-mobile/WordPress-iOS/issues/11420) and [9555](https://github.com/wordpress-mobile/WordPress-Android/issues/9555) with a suggestion

**Comment by maxme** [comment]
@osullivanchris  - I read discussions on these tickets, looks like we want to close this one and keep this behavior. I wonder if we should change the button label though, "Retry to Publish" maybe.

**Comment by osullivanchris** [comment]
**Description of the issue and decision:**
- User tries to publish
- There is an issue with the media they have included in the post
- We do not publish because the media was not attached correctly
- Tell the user the post did not publish due to the media issue
- To resolve the user can 'retry' which will try publish again (and fix the media issue at the same time)

**For copy review**
1. The error message: "Unable to upload this post's media" could say something meaning "Could not publish due to an issue with this post's media". However this error also occurs in a draft post. So we can only really say "Could not upload media" as a generic. Could consider two separate errors but it would be extra work. So preferable if only one.
2. The action "Retry" We think it should say something that clarifies you're "Retrying publishing"  which will try re-upload the media and publish.

the two are tied together.

Will post the final solution to the related iOS issue https://github.com/wordpress-mobile/WordPress-iOS/issues/11420 once we finish the copy review.

**Comment by michelleweber** [comment]
As a user, "Could not upload media" does not necessarily imply to me that the post wasn't published -- maybe it published, but without my images. It'd be nice to specify: "Could not upload media. Post not published." 

You could then reinforce that with "Retry" as the action. (You could do "Retry publication," but I think making the first message clearer allows you to stick with the shorter action.)

**Comment by osullivanchris** [comment]
Sounds great to me. Thanks @michelleweber 

Are you happy to go with that @maxme ? The only copy change would be on the error message. If this gets your thumbsup I'll capture the decision on the iOS task as well.

**Comment by maxme** [comment]
Works for me! Thanks @michelleweber

**Comment by shiki** [comment]
The original decision in the PR description confused me so I crossed it out and linked to https://github.com/wordpress-mobile/WordPress-Android/issues/9933#issuecomment-509146998 instead. 

Crossed out original:
> We have decided to take the iOS approach and prevent the Retry button on local draft from automatically publishing the post

**Comment by malinajirka** [comment]
Just to clarify the decisions made here and in https://github.com/wordpress-mobile/WordPress-Android/issues/9555.

- If the post contains a media and the user clicks on publish in offline -> we'll show one of the messages/actions Maxime summarized in the description of this issue.

- If the post doesn't contain any media and the user clicks on publish in offline -> we'll show the message from https://github.com/wordpress-mobile/WordPress-Android/issues/9555 
Error Message: "Offline. Publishing when connection returns."
Action and behavior: Cancel. Changes the status of the post to "Draft".
---> When the device becomes online and we try to upload it, but the upload fails, we'll show the current error message (usually "GENERIC_ERROR" and retry button). I think we might want to consider improving this scenario as part of this ticket as well. 

cc @osullivanchris

**Comment by osullivanchris** [comment]
@malinajirka sounds right to me. I'd like to know more about the generic error scenario. I feel like it might be a separate ticket though. Noting that #9555 has been updated with final UI and copy for clarity

**Comment by malinajirka** [comment]
>I'd like to know more about the generic error scenario. I feel like it might be a separate ticket though.

I've created a separate issue https://github.com/wordpress-mobile/WordPress-Android/issues/10200

>Noting that #9555 has been updated with final UI and copy for clarity

Perfect, thanks @osullivanchris !
