### ISSUE TITLE
Easier mocking for Kotlin classes in instrumented tests

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-Android#9937]
In #9909, we had to make the class `LocalDraftUploadStarter` and some of its methods `open` for Mockito to be able to mock them. See [this discussion](https://github.com/wordpress-mobile/WordPress-Android/pull/9909/files#r286878795) for additional info. 

Ideally, we shouldn't have to do this so the classes will stay `final` in production. 

## Goals 

Find a better solution. A known candidate is the [All-open compiler plugin](https://kotlinlang.org/docs/reference/compiler-plugins.html#all-open-compiler-plugin)

**Comment by cameronvoell** [comment]
Taking a look at this one.
