### ISSUE TITLE
Remove failed uploads is not working in block editor

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-Android#9953]
### Description

I encountered an issue with media blocks (video and image) after a failed upload. When I have a failed upload in a post, I am unable to "UPDATE" the post after that point, and "REMOVE FAILED UPLOADS" does not seem to work. If I "RETRY" the upload successfully, or "REMOVE" the media from the "Please tap for options" dialog, "UPDATE" resumes working normally. However, if I remove the block via the trash icon, I can no longer "UPDATE" the post, and I cannot "REMOVE" the failed uploads. This results in a condition where my local changes can never be uploaded.

### Steps to reproduce the behavior
1. Open a post (with the block editor).
2. Add an image block.
3. Put device in :airplane: airplane mode.
4. Select Add Image -> Choose from device.
5. Select an image (observe that the upload fails with "Failed to insert media. ...").
<img src="https://user-images.githubusercontent.com/8507675/58531874-25bd2900-8227-11e9-9a37-0a2e9c3b1415.png" width="360">

6. Tap the :wastebasket: trash icon to remove the block.
7. Turn off :airplane: airplane mode.
8. Tap "UPDATE" to upload the changes to the server.

### Expected behavior
The changes should save to the server.

### Actual behavior
Saving the changes is prevented with the following dialog: "Some media uploads have failed. You can't save or publish your post in this state. Would you like to remove all failed media?" Options: { "CANCEL", "REMOVE FAILED UPLOADS"}.

Selecting "REMOVE FAILED UPLOADS" does not appear to have any effect.

### Screencast
Originally encountered while testing video block:
<img src="https://user-images.githubusercontent.com/8507675/58453035-e7f3ce00-815c-11e9-984f-c473ba26fe35.gif" width="360">

### Additional information
The `GutenbergEditorFragment` has [a method](https://github.com/wordpress-mobile/WordPress-Android/blob/654bf6da2dd30a4308d3ee853e5d1f0dea0bc882/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java#L674) `hasFailedMediaUploads` which returns true if the post still has `mFailedMediaIds`. This [prevents the post from updating](https://github.com/wordpress-mobile/WordPress-Android/blob/654bf6da2dd30a4308d3ee853e5d1f0dea0bc882/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2060), and results in `showRemoveFailedUploadsDialog` being called instead. The `removeAllFailedMediaUploads` method, however, does not remove anything. In examining the code, I noticed that the `isUploadingMedia` [method of the same class](https://github.com/wordpress-mobile/WordPress-Android/blob/654bf6da2dd30a4308d3ee853e5d1f0dea0bc882/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java#L669) _always_ returns `false`. This seems to suggest that the responsibility of tracking upload progress is not intended to be handled by this class. @hypest wdyt?

**Comment by hypest** [comment]
> This seems to suggest that the responsibility of tracking upload progress is not intended to be handled by this class.

Allow me to summon @mzorz on this one as I'm sure Mario will have good context to add on this.

**Comment by mzorz** [comment]
hi @mkevins Is this issue still valid?  let me know :D thanks!

**Comment by mkevins** [comment]
<img src="https://user-images.githubusercontent.com/8507675/83833634-bfb78b80-a72f-11ea-9b5e-300f8a7265c7.png" width="140">  :smile: This appears to no longer be an issue. I retested on 14.9 via the steps described (using "save" instead of "update"), on both a new post as well as an already existing post, and the post can be saved after removal of the block containing failed media. Note: the media is still queued for upload, and uploads when the post is saved, but this does not prevent the post from being saved, which was the original cause for the issue.
