### ISSUE TITLE
Analytics: Resume bumping wpandroid_site_created

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#9959]
For more context see the comment thread at p77Llu-c4u-p2
With the introduction of the new site creation flow back in March, we stopped bumping the `wpandroid_site_created` event in favor of `wpandroid_enhanced_site_creation_completed`.  

To address some confusion in the event names and other dashboards that might have been impacted, we'd like to resume bumping the `wpandroid_site_created` event.  We want to stop bumping `wpandroid_enhanced_site_creation_completed` since it will make it easier to aggregate data across both events.

## Matching iOS Issue:

https://github.com/wordpress-mobile/WordPress-iOS/issues/11809

**Comment by diegoreymendez** [comment]
Ping @malinajirka - I think it would be nice to have this change reverted this week if possible.  I'll be tackling the iOS one.
