### ISSUE TITLE
Request to add a confirmation dialog before discarding local changes

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#9971]
Can we consider adding a confirmation dialog before discarding local changes when the "Discard Local Changes" button is tapped?

Steps to reproduce:

1. Go to Blog Posts and open a post or draft using the default editor.
1. Make a change to the post.
1. Tap the three dots at top right to see the more menu.
1. Note the close proximity of "Post Settings" and "Discard Local Changes".
1. Tap "Discard Local Changes".

<strong>Result:</strong> it's very easy to accidentally tap "Discard Local Changes" when you mean to tap "Post Settings" and you can't get those local changes back.

<img src="https://user-images.githubusercontent.com/1119271/58825791-730d1200-85fc-11e9-9502-92e4b7b92b99.png" width="270" alt="Screenshot_20190603-123300">
<sup>Tested with WPAndroid alpha-171 on Pixel 3 Android 9.</sup>

The following request was made by a user in support:

> After I create a post, I go to post settings to add features image, tags, categories etc. The problem is that it's very easy to hit discard local changes instead of post settings. There's no combination popup that asks you if you're sure you want to wipe out all your changes. You can restore it but it's super annoying. I was asking for a pop up that simply asks for combination when discarding local changes.

Note: a possible argument against adding an extra "are you sure?" dialog here is that there is already an Undo option in case you tap the "Discard Local Changes" button by mistake. I will add the `Needs Design Review` tag in order to get feedback about adding an extra notice in addition to the Undo option. 

<img src="https://user-images.githubusercontent.com/1119271/58826337-bcaa2c80-85fd-11e9-9c74-fb44ae9e1df2.png" width="270" alt="Screenshot_20190603-124059">
<sup>Tested with WPAndroid alpha-171 on Pixel 3 Android 9.</sup>

h/t @charliescheer for the original report (internal references: 2055362-zen and p4a5px-2oP-p2).

Also see https://github.com/wordpress-mobile/WordPress-Android/issues/9561.

**Comment by iamthomasbishop** [comment]
A few things come to mind regarding this issue:

* We should clean up this ••• menu up at some point. I've been considering some refinements/organization and will share these in the near future.
* In the immediate term, we should probably show a confirmation dialog when choosing this option, similar to publish confirmation. The copy could read something along the lines of: `Title:` "Discard local changes?" `Body:` "This will restore the previous version of the post." `Buttons:` "Cancel", "Discard".
* We might consider moving the menu option up in the menu –  perhaps between `HTML mode` and `History`?

I'd like to hear others' thoughts on this, as there is some work happening on the discard options. CC'ing some of those folks.

// cc @megsfulton @osullivanchris @maxme

**Comment by maxme** [comment]
My [opinion is to remove this option,](https://github.com/wordpress-mobile/WordPress-Android/issues/9561#issuecomment-492962841). Usage is pretty limited (2% IIRC) and could be done via Undo or the History Revision.

If we want to keep it, adding a confirmation dialog makes sense to me.

**Comment by iamthomasbishop** [comment]
@maxme Can you provide some context into that 2% number? Not sure where that is from or what it is in relation to – does this mean the discard option accounts for only 2% of the taps in this options menu? Or is it 2% of posts are discarded using this button? Not sure of the context here.

I agree that undo/redo/history are all helpful tools, but discard could be a convenient shortcut that (while used sparingly), might provide value. Just want to make sure I understand that trade-off.

**Comment by osullivanchris** [comment]
We decided to remove the 'Discard Local Changes' action per https://github.com/wordpress-mobile/WordPress-Android/issues/9561 and paCBwp-9N-p2

That will resolve the issue with users tapping it accidentally so I am going to close this one.
