### ISSUE TITLE
Split checkstyle configuration: Common, WPAndroid, WCAndroid, FluxC

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#9978]
We have some specific checkstyle rules that are problematic when we apply them on other projects. We should split our checkstyle configuration and have:

- a common configuration ()
- and specifics for WPAndroid, Fluxc (enventually other libs/projects)
- update the gradle config to allow multiple checkstyle tasks.

Some details about the gradle config [here](https://github.com/Automattic/style-config-android/pull/2#discussion_r278252132):

> I had a look at the checkstyle documentation and at the gradle checkstyle plugin doc. I couldn't find anything great to manage multiple configuration files. But Gradle would let us define multiple checkstyle tasks. We could use this to have multiple configuration files (one generic stored in this repo and one specific by project).
> 
> Might be tricky though... I found an example there: https://github.com/natgaertner/checkstylegradleparallelbug/blob/master/build.gradle

**Comment by jkmassel** [comment]
Closing this, as we've dramatically adjusted our listing setups over the years.
